### ISSUE TITLE
Vampiric Embrace

### ISSUE THREAD

**Issue by imtrollingu** [SunstriderEmu/BugTracker#1009]
**Description:**

Vampiric Embrace trigger Blackout

**Current behaviour:**

Vampiric Embrace triggers Blackout, this shouldn't happen as it isn't a shadow damage spell.

http://db.hellfire-tbc.com/?spell=15286
http://db.hellfire-tbc.com/?spell=15326

**Expected behaviour:**

Nothing should happen except Vampiric Embrace landing on the target

**Steps to reproduce the problem:**

Problem seems to happen on 40% of casts

**Comment by kelno** [comment]
Confirmed still happening

**Comment by kelno** [comment]
Fixed a while ago
