### ISSUE TITLE
[priest] Shadowfiend will not obey commands outside of combat

### ISSUE THREAD

**Issue by plutonium447** [SunstriderEmu/BugTracker#1016]
**Description:**
When Shadowfiend is summoned and not in combat it will not obey any commands given to it from the pet bar, and will only retaliate to attacks to it from other mobs.
If the Shadowfiend is in combat, then the priest is able to control it using the pet bar.

**Current behaviour:**
Shadowfiend controls do not work while the shadowfiend is not in combat.

**Expected behaviour:**
Shadow priests should be able to control Shadowfiend with the pet bar that appears on their screen at all times.

**Steps to reproduce the problem:**

1. Be Priest                        
2. Find a mob to attack
3. Cast Shadowfiend
4. Attempt to use pet command bar on the mob while out of combat. - test here
5. Aggro the mob via aggro radius
6. allow the shadowfiend to aggro onto the mob via aggressive/ defensive behaviour
7. notice the shadowfiend can now be controlled

This bug makes it very diffcult for shadow priests to use their shadowfiend spell as they need to be within melee range of the targeted mob for the shadowfiend to begin attacking.

**rev. hash/commit:**
10866

**id's**
[spell] Shadowfiend (34433) http://db.hellfire-tbc.com/?spell=34433
[npc] Shadowfiend (19668) http://db.hellfire-tbc.com/?npc=19668

**Comment by DotDotGoose** [comment]
Confirming this issue with tests on Murmur and other various distance fights. 
The only way it will attack is by being next to the mob otherwise it will run back to the caster
losing time on attacking and not gaining mana.

**Comment by giveusmezpls** [comment]
update Shadowfiend still acting strange, sometimes in non-instances world use he works perfect - you use the spell and he appears on the target and starts attacking. however in several raids when summoned the shadowfiend will return to the priest and has to be issued the stay command before he will honor the petattack command.

**Comment by kelno** [comment]
Updated. Still an issue? (might need to wait next update)

**Comment by Jerrythemagicdog** [comment]
fixed
