### ISSUE TITLE
Hellfire Ramparts - Vazruden issues

### ISSUE THREAD

**Issue by Paralol** [SunstriderEmu/BugTracker#1021]
**Description:**

Damage and ability timing of end boss Vazruden seems incorrect.

**Current behaviour:**

Melee damage of Vazruden is either too high or too fast.
Fireball is being cast by Nazan too often.
After first wipe the boss doesn't despawn You can kill the boss by itself and the boss respawns in the air. Only able to pull it with a pet.

**Expected behaviour:**

Boss able to be killed.

**Steps to reproduce the problem:**

1. Do the fight

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/4516769/55601005-f0a1d680-57a1-11e9-85d1-4709459aabb7.png)

**Comment by Paralol** [comment]
Damage in this fight is still excessively high.

**Comment by kelno** [comment]
Dungeon reworked since
