### ISSUE TITLE
[Quest] 10018 - Vestments of the Wolf Spirit

### ISSUE THREAD

**Issue by Kekass** [SunstriderEmu/BugTracker#1023]
**Description:**

While having the QUEST [10018]( http://db.hellfire-tbc.com/?quest=10018) - Vestments of the wolf spirit quest complete you cannot hand in the quest @ NPC  [18384](http://db.hellfire-tbc.com/?npc=18384) Malukaz , although  you can still talk to him. says something about nagrand and about how much work there is to do. you cannot hand in the quest as he has no ? above his head.

**Current behaviour:**

got to Terokkar forest 50.1 , 46.3
Talk to Malukaz and get quest
Go kill 12 wolfs get their pelts
Go back to Malukaz
no option to complete quest

**Expected behaviour:**

got to Terokkar forest 50.1 , 46.3
Talk to Malukaz and get quest
Go kill 12 wolfs get their pelts
Go back to Malukaz
Complete Quest
Get next quest [Patriarch Ironjaw](http://db.hellfire-tbc.com/?quest=10023)

CHANGEME
[03:36]Sunstrider rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Unix, RelWithDebInfo, Static)

**Comment by Kekass** [comment]
Was just talking to a guildie about the quest from what they've said that the next quest in the chain [Patriarch Ironjaw](http://db.hellfire-tbc.com/?quest=10023) is some how putting the quest giver into a the state where you cannot hand in quests and only starts working again once the person who picked up the quest completes the entire chain... not sure how to test this or confirm it.

**Comment by Jerrythemagicdog** [comment]
Thank you, indeed the script would get stuck on a certain step during the next quest's event.
Fixed.

**Comment by DeadxReckon** [comment]
This turn in just bugged for me in Burning Crusade Classic.  Could this be indicative of ActiBlizz using your code?
