### ISSUE TITLE
[Quest] The Vengeful Harbringer 

### ISSUE THREAD

**Issue by Kekass** [SunstriderEmu/BugTracker#1024]
**Description:**

The QUEST [10842 - The Vengeful Harbringer](http://db.hellfire-tbc.com/?quest=10842) seams to complete as soon as you pick it up and not when you have used the ITEM [30527 Draenei Tomb Relic](http://db.hellfire-tbc.com/?item=30527) at 50 , 54 (underground Tomb of Lights) to summon the NPC [21638 - The Vengeful Harbinger]( http://db.hellfire-tbc.com/?npc=21638) you're supposed to kill to complete the quest.

**Current behaviour:**

Go to 37.4 - 50.9 in Terokkar Forest and talk to High Priest Orgalum get the quest and it is already complete. if you go to the Dreanei tomb Relic located in the tomb of lights and use the quest item nothing happens the item just goes on cooldown for 30sec and thats it.

**Expected behaviour:**

when you use the item in the correct location it should spawn the NPC [21638 - The Vengeful Harbinger]( http://db.hellfire-tbc.com/?npc=21638) and once you have killed that another NPC   [184830 Draenei Ascendant](http://db.hellfire-tbc.com/?object=184830) should spawn to let you hand in the quest.

**Steps to reproduce the problem:**

1. Go to 37.4 - 50.9 in Terokkar Forest and talk to High Priest Orgalum
2. Quest is complete
3. Try and use [30527 Draenei Tomb Relic](http://db.hellfire-tbc.com/?item=30527) at 50 , 54 anyways
4. Nothing Happends

**rev. hash/commit:** 
Sunstrider rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Unix, RelWithDebInfo, Static)

**Comment by zemfi** [comment]
Above issue didnt include the .rev number; but confirmed, it is still bugged as of 10914, as described above.

**Comment by Sheikthecatman** [comment]
Issue was fixed in [1ad1eecf68bdcaafae184b36f52a2ed14ec199db](https://github.com/kelno/sunstrider/commit/1ad1eecf68bdcaafae184b36f52a2ed14ec199db) and the fix is already live.
