### ISSUE TITLE
[quest] Teron Gorefiend, i am...

### ISSUE THREAD

**Issue by cryptochiefy** [SunstriderEmu/BugTracker#1025]
After accepting quest an animation happens and the boss appears that you need to kill but you cant attack the boss, and you also get turned into a wisp.  The quest npc then bugs and no one can hand in quests or accept quests from him. This chain offers a great helmet reward.
![bug](https://user-images.githubusercontent.com/42995820/55607588-f0b0cf00-57bf-11e9-980f-e29ac61e99dc.png)

**Comment by Tamosheik** [comment]
Please follow the report template. If you require help, please ask, taking note of the pinned messages in #game-issues channel in discord.

Teron Gorefiend, I am... - QUEST ID#10639
Karsius the Ancient Watcher - NPC ID#21877

As an aside, commentary on the quest reward/s has no bearing on the bug.

**Comment by Jerrythemagicdog** [comment]
Updated in '567cfce6361c8456137f6d1a451deee43d787e68' (scripts) - will be fully functional once the possessed unit gets cleared correctly.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed!
