### ISSUE TITLE
[GameObject] Nether Drake Egg - Eggs don't hatch

### ISSUE THREAD

**Issue by Tamosheik** [SunstriderEmu/BugTracker#1028]
**Description:**
Using the Nether Drake Egg (OBJECT ID#184867) displays the opening animation but no drake is spawned.

**Expected behaviour:**
http://db.hellfire-tbc.com/?quest=10609
Opening a Nether Drake Egg should have a 1/3 chance of spawning either:
Proto-Nether Drake (NPC ID#21821)
Adolescent Nether Drake (NPC ID#21817)
Mature Nether Drake (NPC ID#21820)

**Steps to reproduce the problem:**
1. Use Egg
2. Nothing spawns

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 
Server Info not currently available

**Comment by zemfi** [comment]
Quest = What Came First, the Drake or the Egg? (#10609)

Probably should change the issue title aswell so its easily searchable, ie. avoid dupes.

Still broken as of .rev 11061

**Comment by Jerrythemagicdog** [comment]
tested, works now.
