### ISSUE TITLE
[Reputation] Gray level mobs should give less reputation 

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1029]
**Description:**

Grey mobs used to give 20% of the normal reputation until the release of Patch 3.0.8.  See the mob difficulty colors chart for when mobs transition from green to grey. 

**Current behaviour:**

Currently no diminishing reputation gains based on the level of player vs. level of mob when it's gris.

**Sources:**

https://wowwiki.fandom.com/wiki/Reputation
https://wow.gamepedia.com/Mob_difficulty_colors
https://wow.gamepedia.com/Reputation

**Steps to reproduce the problem:**

1. Go into a dungeon with lower level mobs (e.g. Ramparts) as level 70
2. Get full reputation for the mobs

**Comment by cryptochiefy** [comment]
Dont think u can farm rep at ramps unless its heroic after you reach honoured maybe

**Comment by giveusmezpls** [comment]
Are you sure this does not work? I get significantly less vs. Vanilla mobs and much less for lower level quests also (not sure if intended).

**Comment by Jerrythemagicdog** [comment]
Confirmed to be working correctly, the Ramparts issue was due to wrong restrictions - the creatures there were granting full reputation way beyond the intended reputation bracket.
