### ISSUE TITLE
[Quest] Lost in Action

### ISSUE THREAD

**Issue by giveusmez** [SunstriderEmu/BugTracker#1033]
**Description:**

The Lost in Action quest's npc Windcaller Claw does not give credit for his part of the quest, he is not 'discoverable' causing the quest to be impossible to complete.

**Current behaviour:**

Windcaller Claw responds correctly but does not give credit for the quest.

**Expected behaviour:**

Windcaller Claw gives credit for his objective in the quest.

**Steps to reproduce the problem:**

Click on Windcaller Claw with the quest Lost in Action.

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

![hashblabla2](https://user-images.githubusercontent.com/49213988/55667711-c8060380-58ab-11e9-86b8-1dd2656d0b61.png)

**Comment by Tamosheik** [comment]
Quest ID#9738

**Comment by zemfi** [comment]
Naturalist Bite (#17893) dialogue is broken, doesnt go past this point:

![lostin](https://user-images.githubusercontent.com/46832429/58093334-a1105080-7c11-11e9-8bfc-4031452dcab2.jpg)

.rev 11347

**Comment by Jerrythemagicdog** [comment]
Tested, works correctly now - possibly fixed in bulk with SAI import.
