### ISSUE TITLE
[dungeon] Dreghood slaves sometimes follow players before despawning

### ISSUE THREAD

**Issue by plutonium447** [SunstriderEmu/BugTracker#1054]
**Description:**
After defeating Coilfang Slavemasters, Dreghod Slave NPCs will sometimes not flee from the vicinity, and instead follow players for a short duration before despawning. The slaves do not attack players while this occurs.

**Current behaviour:**
Dreghood Slaves follow players after they are "freed" by players, not attacking, until they eventually despawn.

![Screenshot from 2019-04-09 09-13-00](https://user-images.githubusercontent.com/40911527/55765257-40d6ac80-5ab2-11e9-875c-109bafef347c.png)

**Expected behaviour:**
Dreghood Slaves should immediately flee from the vicinity and from the party of players when all nearby Coilfang Slavemasters are killed.

**Steps to reproduce the problem:**

1. Go to Heroic Steamvaults
2. Go to the hallway leading to the second boss of the instance, Mekgineer Steamrigger
3. See the hallway full of Coilfang Slavemasters and Dreghood Slaves
4. Engage Coilfang Slavemasters
5. Dreghood Slaves will come to attack the players
6. Kill the Coilfang Slavemasters
7. Notice how sometimes Dreghood Slaves follow the players around instead of running away

**rev. hash/commit:** 
**10913**

**id's**
[npc] Coilfang Slavemaster (20624) http://db.hellfire-tbc.com/?npc=20624
[npc] Dreghood Slave (20628) http://db.hellfire-tbc.com/?npc=20628

**Comment by Jerrythemagicdog** [comment]
Thanks!
Tested, no longer following the player.
Slightly reduced the despawn timer.
