### ISSUE TITLE
[dungeon] coilfang enchantress will sometimes cast spells when polymorphed

### ISSUE THREAD

**Issue by plutonium447** [SunstriderEmu/BugTracker#1056]
**Description:**
When a Coilfang Enchantress is polymorphed, it will continue to cast spells against players, such as Lightning Bolt.

**Current behaviour:**
Coilfang Enchantress mobs will sometimes cast spells - such as Lightning Bolt - against players even when polymorphed.

![Screenshot from 2019-04-09 08-22-40](https://user-images.githubusercontent.com/40911527/55765487-5c8e8280-5ab3-11e9-9662-96d17134ae24.png)

**Expected behaviour:**
Coilfang Enchantress mobs should not be able to cast any spells at all when polymorphed.

**Steps to reproduce the problem:**

1. Go to Heroic The Slave Pens
2. Find a Coilfang Enchantress mob
3. Cast Polymorph on it
4. wHy Is ThAt ShEeP cAsTiNg SpElLs?!

This issue has only been seen on the Heroic mode verison of The Slave Pens.

**rev. hash/commit:** 
**10913**

**id's**
[npc] Coilfang Enchantress (17961) http://db.hellfire-tbc.com/?npc=17961
[spell] Lightning Bolt (37664) http://db.hellfire-tbc.com/?spell=37664
[spell] Polymorph (12826) http://db.hellfire-tbc.com/?spell=12826

**Comment by kelno** [comment]
She's been reworked and doesn't seem to do it anymore
