### ISSUE TITLE
[Quest] Administering the Salve

### ISSUE THREAD

**Issue by Azytheoneandonly** [SunstriderEmu/BugTracker#1059]
**Description:**

Not getting credit for healing npcs with the quest item.

**Current behaviour:**

When you use item Healing Salve it cures the debilitated mag'har grunt
but does not give you credit.

Demo: https://streamable.com/c36k5

Edit: So if you don't target the NPC and use the Healing Salve it doesn't modify the NPC but gives you quest credit as seen below.

https://streamable.com/5cm7a

**Expected behaviour:**

To get credit when you heal the NPC with the Healing Salve.

**Steps to reproduce the problem:**

1. Pick up quest and attempt to heal the npcs

Quest: http://db.hellfire-tbc.com/?quest=9447
Quest item: http://db.hellfire-tbc.com/?item=23394
Quest NPC: http://db.hellfire-tbc.com/?npc=16847

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/37324574/55776510-5c58ac00-5ae0-11e9-9a6f-9f13de7e059f.png)

**Comment by Jerrythemagicdog** [comment]
Thanks!
Fixed by woiwoz recently.
