### ISSUE TITLE
[Tanking] Mob Knockbacks/Pushback drops threat (Expanded)

### ISSUE THREAD

**Issue by zemfi** [SunstriderEmu/BugTracker#1062]
**Description:**

Added expanded tag since its similar to #966 but that is closed as a question, and this has more info. Recently tanked a run on this new core and noticed this among other things.

**Current behaviour:**

Getting pushed back from melee mobs (in Hellfire Ramparts) with 100% threat causes a threat drop to the tank being punted. Getting punted but also charging back to that same mob gains the threat again, suggesting its a proximity issue.

**Expected behaviour:**

Various Melee trash mobs should **always** hold 100% aggro on the pushback of the tank (ie chasing the tank while hes in the air, maintaining aggro)

**Steps to reproduce the problem:**

CHANGEME
1. Group for an instance with various trashmobs that have a punt
2. Tank said mob, obviously having aggro, get punted
3. Target of said mob suddenly changes to another player.
3.1 Get punted, but also charge back in, noticing the switch.

(Tanked as bear)

**rev. hash/commit:** 

.rev 10913

**Comment by kelno** [comment]
The "gains threat again" part is interesting.
It may be that the tank is considered unreachable while in the air and thus the creature will target someone else because of that.

**Comment by Jerrythemagicdog** [comment]
I've tried many creatures with knockbacks in the open world and in instances.
There is no threat being dropped at any point. The creature follows the target with the highest threat so in this case while the tank was in the air someone must have gotten higher on the aggro table.
