### ISSUE TITLE
Unable to set hearthstone with Dreg Cloudsweeper in Wildhammer Stronghold, Shadowmoon Valley

### ISSUE THREAD

**Issue by Korblo** [SunstriderEmu/BugTracker#1070]
**Current behaviour:**

Dreg Cloudsweeper (npc=19352) in Wildhammer Stronghold, Shadowmoon Valley is unable to be set as a hearth location. 
Tested with hearthstone in first bag slot, and also with a deleted hearthstone. In both cases the innkeeper does an animation but there's no confirmation in chat to say that "X is now your home."  Hovering over the hearthstone or Astral Recall shows the previously set location (Shattrath in my case) and additionally, contrary to other innkeepers, you will not be given a new hearthstone if it was deleted.

**Expected behaviour:**

Being able to set your hearthstone to Wildhammer Stronghold.

**Steps to reproduce the problem:**

1. As an alliance character, speak with Dreg Cloudsweeper (npc=19352) in Wildhammer Stronghold, Shadowmoon Valley.
2. Select the "Make this inn my home" option.
3. Observe no confirmation of new hearthstone location and your hearthstone still being the previously set location.

**rev. hash/commit:** 

Sunstrider rev. 10914 (d7f974381da2+) 2019-04-09 00:46:01 +0100 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by kelno** [comment]
Thanks!
The issue is actually very dumb... the innkeeper is out of sight from you if you stand on the other side of the bar, so he can't cast on you.

**Comment by kelno** [comment]
To dev: Have to find the spell the innkeeper is casting and make it ignore los

**Comment by kelno** [comment]
Fixed
