### ISSUE TITLE
[Quest] Skywing

### ISSUE THREAD

**Issue by zemfi** [SunstriderEmu/BugTracker#1072]
**Description:**

This escort quest (#10898) has the escort NPC marked as neutral enemy.

**Expected behaviour:**

The escort npc (#22424) should be marked as friendly (not attackable)

![skywing](https://user-images.githubusercontent.com/46832429/55945188-a206a780-5c8d-11e9-86da-0544e2e40956.jpg)

**rev. hash/commit:** 

.rev 10914

**Comment by Bearlyable12a** [comment]
Confirmed same issue for me as alliance. Skywing npc post quest start is horde flagged.

**Comment by Jerrythemagicdog** [comment]
Fixed
