### ISSUE TITLE
[Quest] Ar'tor, Son of Oronok - NPC Cannot Be Found

### ISSUE THREAD

**Issue by Alobis** [SunstriderEmu/BugTracker#1076]
Description:
Ar'tor, Son of Oronok (NPC 21292) in SMV - Illidari point is missing

Current behaviour:
Ar'tor, Son of Oronok (NPC 21292) in Illidari point - SMV is missing and players are unable to complete Ar'tor, Son of Oronok (Quest ID 10528)

Expected behaviour:
The NPC is present for the quest, has a quest dialogue, and the quest can be completed.
Ar'tor will then start the next quest in the chain.

Steps to reproduce the problem:
    Step 1 Go to SMV - Illidari point
    Step 2 Attempt to find Ar'tor (/target Ar'tor, /target Ar)
    Step 3 press F to pay respects if you can find his corpse (or if you can't)

rev. hash/commit:
Sunstrider rev. 10914 (d7f974381da2+) 2019-04-09 00:46:01 +0100 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by giveusmezpls** [comment]
Confirmed still not working on 18/04/19.

**Comment by Tamosheik** [comment]
Quest ID is incorrect. Correct Quest ID# 10527

**Comment by Mediowow** [comment]
Still not working 02 Jun 19 after server maintenance.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
