### ISSUE TITLE
Locked chests not unlocking. Benedict's chest and Kolkar's Booty

### ISSUE THREAD

**Issue by PepeFroggington** [SunstriderEmu/BugTracker#1078]
**Description:**

When looting a key off of a body, the key goes onto my keyring. However, when I click on the chest, the key disappears and the "unlocking" progress bar goes to completion. After the bar has finished, the chest is still unlocked. This has happened with 2 chests / keys so far: 
Benedicts chest (object=3239)
Benedicts Key (item=4882)
Kolkar's Booty (object=3642)
Kolkar Booty Key (item=5020)

**Current behaviour:**

The chest stays locked after "unlocking" it

**Expected behaviour:**

The chest should then allow me to click on and loot it.

**Steps to reproduce the problem:**

1. kill a [Kolkar Stormer](https://vanilla-twinhead.twinstar.cz/?npc=3273), [Kolkar Wrangler](https://vanilla-twinhead.twinstar.cz/?npc=3272) or [Barak Kodobane](https://vanilla-twinhead.twinstar.cz/?npc=3394) (I found my key on a stormer)
2. Loot [Kolkar Booty Key](https://vanilla-twinhead.twinstar.cz/?item=5020) off of them
3. Click on [Kolkar Booty](https://vanilla-twinhead.twinstar.cz/?object=3642) (this specific one in my case)
4. The chest does not unlock, despite showing the unlock bar go to completion.

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/49545655/56012727-1d6d6500-5d31-11e9-8562-9a238470f65b.png)

**Comment by Jerrythemagicdog** [comment]
Tested, works correctly now - most likely fixed along with https://github.com/SunstriderEmu/BugTracker/issues/1227
