### ISSUE TITLE
[Quest] The Fel and the Furious (ID 10612)

### ISSUE THREAD

**Issue by dinkletron** [SunstriderEmu/BugTracker#1080]
**Description:**
Killing the Deathforged Infernals whilst in the Fel Reaver do not the register as kills.

**Current behaviour:**
When you interact with the Fel Reaver console, you take control of the Fel Reaver, but killing the required mobs do not credit the quest.

**Expected behaviour:**
You can indefinitely control the Fel Reaver, and repeatedly kill the Deathforged Infernals but they don't register as kills.

**Steps to reproduce the problem:**
1) Accept quest from Nakansi
2) Right click the consoles down the slope
3) Run through the infernal mobs and click button 3/4 to kill them
4) Nil register

**rev. hash/commit:** 

![Capture](https://user-images.githubusercontent.com/29308094/56030001-1eb58680-5d5f-11e9-8555-f7d0da7f03e0.JPG)

**Comment by plutonium447** [comment]
I attempted to doublecheck this issue, but could not activate the fel reaver.
Clicking on the consoles does nothing.

rev. **11262**

**Comment by Mediowow** [comment]
Managed to complete this quest 01 Jun 19 as alliance. We had to fly to the horde consoles iot interact with the felreaver. The abilities (rocket and sonic boom) were working and was able to complete quest. Had to kill the horde guard that patrols before getting into the console though.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
