### ISSUE TITLE
Hunter Pet Ability not auto casting after 1 stack

### ISSUE THREAD

**Issue by HueHueTBCTheBarrens** [SunstriderEmu/BugTracker#1097]
Pet casts [Scorpid Poison](https://tbc-twinhead.twinstar.cz/?spell=27060) on target, will not re-cast until it drops off.

**Current behaviour:**

Casts Scorpid Poison Once, not re-casting on mob

**Expected behaviour:**

Should stack 5 times, can stack more then once by casting the pet ability on target, but will not automatically do it

**Steps to reproduce the problem:**
1. Hunter level 69+ to cast [Tame Beast](https://tbc-twinhead.twinstar.cz/?spell=1515) on a level 68/69 [Scorchshell Pincer](http://tbc.cavernoftime.com/npc=21864) or other pets with [Scorpid Poison ](https://tbc-twinhead.twinstar.cz/?spell=27060)
2. Turn _on_ autocast of [Scorpid Poison](https://tbc-twinhead.twinstar.cz/?spell=27060)
3. Attack mob
4. ????
5. Stops casting after one stack is applied. 

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/29525708/56088037-710bba00-5ebb-11e9-9407-613751c01067.png)

**Comment by kelno** [comment]
Working now?

**Comment by Jerrythemagicdog** [comment]
Not working (rev 11735)

**Comment by kelno** [comment]
Fixed
