### ISSUE TITLE
[Quest] Gor'tesh the Brute Lord

### ISSUE THREAD

**Issue by spclifford88** [SunstriderEmu/BugTracker#1098]
Cannot complete Gor'tesh the Brute Lord quest in Burning Steppes. 

Killing Gor'tesh does not contain his head.

![image](https://user-images.githubusercontent.com/7194275/56088105-67c72100-5eac-11e9-87b5-987347b0baf4.png)

**Comment by Tamosheik** [comment]
Please follow the report template. Doing so allows the devs to work on fixing the bugs rather than chasing down details. For more information, check the pinned messages in the #game-issues channel on discord, or ask for help.

Gor'tesh - NPC ID#9176
Gor'tesh the Brute Lord - QUEST ID#3824
