### ISSUE TITLE
Hints of a New Plague quest NPC not behaving correctly

### ISSUE THREAD

**Issue by MatthyusWoW** [SunstriderEmu/BugTracker#1102]
Hints of a New Plague quest NPC not behaving correctly

During the Hints of a New Plague? quest line, there is a portion of the quest where you need to 'Protect Kinelory'. When the quest is accepted, she just stands on her hill and the Forsake Courier spawns next to her.

Quest line - https://wowwiki.fandom.com/wiki/Quest:Hints_of_a_New_Plague%3F_(4)
Quest NPC - https://www.wowhead.com/npc=2713/kinelory

**Expected behaviour:**

During the Hints of a New Plague? quest line, there is a portion of the quest where you need to 'Protect Kinelory'. What should happen when the quest is accepted, is that Kinelory is meant to fight her way to Apothecary Jorell's  hut.

https://wowwiki.fandom.com/wiki/Quest:Hints_of_a_New_Plague%3F_(4) - Explains what happens during the event.

**Steps to reproduce the problem:**

CHANGEME
1. Step 1 - Accept Quest 'Hints of a New Plague? (step 4 - Protect Kinelory)
2. Step 2 - She is meant to run down the hill, instead the Forsaken Courier spawns next to her.

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/49612701/56093193-13e22980-5ef8-11e9-98a7-69176b6c21ce.png)

**Comment by Tamosheik** [comment]
Quest ID #660

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed!

**Comment by brunojesus86** [comment]
Good evening, as of today the courier quest is not working properly, killed him alone and he despawns, kill each of the bodyguards 1 by 1 and leaving the courier to last and it despawns, dont find a way to loot him normally
