### ISSUE TITLE
[NPC] Coarse Stone Statue / Rough stone statue doesn't heal

### ISSUE THREAD

**Issue by Varen** [SunstriderEmu/BugTracker#1103]
**Description:**

Jewelcrafting-made Stone Statues (tried Coarse and Rough so far) spawn an NPC that's supposed to heal the player, but it does nothing and just stands there, sometimes to be hit by npcs.

**Current behaviour:**

Coarse Stone Statue stands still and does nothing.
![image](https://user-images.githubusercontent.com/3650235/56094010-56434080-5ecf-11e9-95bc-e0a5a9a8eb8e.png)

**Expected behaviour:**

NPC should channel a healing spell that heals its owner over time.

**Steps to reproduce the problem:**

Using the item in combat (id 25880, or 25498), out of combat, with or without health, results in the spawning of said npc who will hang around for a few seconds then disappear.

**rev. hash/commit:** 

CHANGEME
![image](https://user-images.githubusercontent.com/3650235/56094009-52172300-5ecf-11e9-9342-30a680fe32ee.png)

**Comment by Jerrythemagicdog** [comment]
Fixed, thanks!

**Comment by juujuu123321** [comment]
can you reopen this? Solid stone statue does not work when in combat and I believe many other statues as well

**Comment by juujuu123321** [comment]
> 
> 
> Fixed, thanks!

not fixed
