### ISSUE TITLE
[Quest] The Skettis Offensive - Cannot Be Turned In

### ISSUE THREAD

**Issue by Tamosheik** [SunstriderEmu/BugTracker#1104]
**Description:**
The quest The Skettis Offensive (10879) cannot be turned in after objectives have been completed.

**Current behaviour:**
![image](https://user-images.githubusercontent.com/40758487/56096459-c5e71900-5f2b-11e9-8b6f-021ab595183f.png)

**Expected behaviour:**
Quest should be able to be turned in

**Steps to reproduce the problem:**
1. Accept The Skettis Offensive from Defender Grashna (22373)
2. Defend against the attack
3. Unable to turn in quest. End NPC Rilak the Redeemed (22292) has a grey ?

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/40758487/56096488-224a3880-5f2c-11e9-9526-a8b064db8b7b.png)

**Comment by Jerrythemagicdog** [comment]
Fixed
