### ISSUE TITLE
Daily Dungeon Reset clears progress of normal dungeons and removes ID

### ISSUE THREAD

**Issue by giveusmezpls** [SunstriderEmu/BugTracker#1110]
**Description:**

When the daily dungeon reset occurs normal dungeons which do not have saved/locked IDs should not remove players current progress.

**Current behaviour:**

At the daily reset timer, normal dungeons are reset removing group progress and sending them to their hearthstone locations.

**Expected behaviour:**

Non-Heroic, Non-Raid dungeons should not be reset during the daily reset process.

**Steps to reproduce the problem:**

1.  Be in a dungeon.
2. Wait for the daily reset, this could take up to 24 hours.
3. Be sad you are now in your hearth location instead of the dungeon you are working hard on with your friends.
4. Report to the Github page.
5. Give Nolin some whoppers.

During the above steps I was drinking coffee in my pajamas so you might want to take the same approach to ensure the same result.

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/49624667/56107059-91a14600-5f87-11e9-9977-efee2d67aaaf.png)

**Comment by kelno** [comment]
Just to be sure, those gets reset with the weekly reset still?

**Comment by kelno** [comment]
Updated, need testing

**Comment by artieau** [comment]
Closing as have had no reports since Endless go live.

**Comment by giveusmezpls** [comment]
its not acceptable to close this without fixing, as usual terrible support
from GM Artie.

**Comment by kelno** [comment]
Is this still an issue?
