### ISSUE TITLE
Dire Maul North: Door to courtyard broken

### ISSUE THREAD

**Issue by BrockSamson1** [SunstriderEmu/BugTracker#1111]
**Description:**

Dire Maul North: Door to courtyard with guard fengus which allows access to deeper bosses is not able to be interacted with with key or without. Appears as a solid barrier.

**Current behaviour:**

Door is wall.

**Expected behaviour:**

Door is door.

**Steps to reproduce the problem:**

Approach door. Note wall.

**Comment by giveusmezpls** [comment]
Turns out instead of a door Nolin went cheap and bought a real fake door.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
