### ISSUE TITLE
[Quest] Illidan's Pupil

### ISSUE THREAD

**Issue by zemfi** [SunstriderEmu/BugTracker#1112]
**Description:**

Quest Illidan's Pupil (10646) unable to complete.

**Current behaviour:**

Accepting the quest you engage in dialogue/story with the quest giver Altruis the Sufferer (18417), but unable to proceed after the second page of dialogue.

**Expected behaviour:**

Go through his story, and quest is completeable.

**Steps to reproduce the problem:**

CHANGEME
1. Accept Quest 
2. Talk with Quest Giver NPC
3. Doesn't proceed past second lot of dialouge, as below.

![illidan](https://user-images.githubusercontent.com/46832429/56123476-dba22000-5fb7-11e9-97f4-45877652b304.png)
(cant go past this page)

**rev. hash/commit:** 

.rev 10962

**Comment by oj449** [comment]
still broken 
.rev 11082

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago with "85a766a30b233e48fe08d9691783921cb0065ce3"
