### ISSUE TITLE
Wyrm from Beyond (NPC ID 21796) spawning when not on quest

### ISSUE THREAD

**Issue by dinkletron** [SunstriderEmu/BugTracker#1116]
**Description:**
The Wyrm from Beyond NPCs (ID 21796) are attacking players who are not on the quest Gauging the Resonant Frequency (ID 10594), they are not visible to the player.

**Current behaviour:**
When in Razor Ridge, these NPCs will attack you, but you can't attack back because they are invisible.

**Expected behaviour:**
This NPC should only spawn when you use the quest item ID 30701 when on the quest ID 10594.

**Steps to reproduce the problem:**
1) Go to Razor Ridge
2) Get attacked by the Wyrm from Beyond
3) ??

 **rev. hash/commit:**

**Comment by giveusmezpls** [comment]
can confirm i was hit by this mob for over 20 minutes and it never stopped nor could i hit it back.

**Comment by zemfi** [comment]
Missing from the OP, still an issue as of .rev 11061

#21796 #10594 #30701 #10594

**Comment by Jerrythemagicdog** [comment]
Fixed
