### ISSUE TITLE
Spectrecles (SMV) not available from NPC

### ISSUE THREAD

**Issue by dinkletron** [SunstriderEmu/BugTracker#1118]
**Description:**
The Spectrecles (Item ID 30719) are not available from Chief Apothecary Hildagard (NPC ID 21772) if you lose/delete the item.

**Current behaviour:**
When you speak with the NPC, there is no option to obtain a new pair of Spectrecles.

**Expected behaviour:**
When you speak with the NPC, you should be able to click a button and she casts Spell ID 37602 (Replace Lost Spectrecles) to give you a new pair.

**Steps to reproduce the problem:**
1) Delete the Spectrecles from bags
2) Talk to NPC

 **rev. hash/commit:** 	

![Capture](https://user-images.githubusercontent.com/29308094/56266064-a1a75a00-612e-11e9-99df-9053b6b8e52b.JPG)

**Comment by kelno** [comment]
Fixed
