### ISSUE TITLE
[Mage] Water Elemental refuses to attack when ordered to attack a Polymorphed target.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1124]
**Description:**
Water Elemental (spell: 31687) doesn't want to attack a Polymorphed target (spell: 118).
He just stands there and doesn't attack (/petattack or /click PetActionButton4).

1. .learn 31687 and .learn 118
2. Summon a Water Elemental
3. Polymorph a target
4. He doesn't want to attack it.

 **rev. hash/commit:** 	
rev. 10993

**Comment by giveusmezpls** [comment]
i think you need to get a new elemental, yours is disobedient

**Comment by hufsa** [comment]
There shouldnt be any checks like this in TBC

**Comment by Jerrythemagicdog** [comment]
Fixed
