### ISSUE TITLE
Warriors getting rage on attacks that are absorbed.

### ISSUE THREAD

**Issue by giveusmezpls** [SunstriderEmu/BugTracker#1125]
**Description:**

Warriors are getting rage when hitting against priest shield/absorb mechanics which is not intended, this is a wrath feature (3.1.0) and should not be in the TBC server.

**Current behaviour:**

![image](https://user-images.githubusercontent.com/49624667/56287140-ee0a8e00-615e-11e9-96c3-baed2a2e6e6d.png)

**Expected behaviour:**

Wrath of the Lich King Patch 3.1.0 (2009-04-14): Attacks that are absorbed (such as by  [Power Word: Shield]) will now generate rage. 

**Steps to reproduce the problem:**

1. have zero rage
2. hit a priest shield
3. get rage.

 **rev. hash/commit:**

**Comment by Jerrythemagicdog** [comment]
Is it from hitting the shield, or is he maybe generating rage from Reflective Shield? (and if so, should he?)

**Comment by kelno** [comment]
Fixed with 11380

**Comment by hufsa** [comment]
Still happens, tested today

**Comment by kelno** [comment]
Okay fixed again, there were two places rewarding rage for this.
