### ISSUE TITLE
Victory Rush for Horde broken

### ISSUE THREAD

**Issue by Dorothy28** [SunstriderEmu/BugTracker#1132]
**Description:**

Victory Rush for Horde not working

**Current behaviour:**
![WoWScrnShot_041819_111730](https://user-images.githubusercontent.com/49740679/56335692-d2e06280-61e0-11e9-8090-1639b6190252.jpg)
![WoWScrnShot_041819_111756](https://user-images.githubusercontent.com/49740679/56335699-db389d80-61e0-11e9-8b5a-72b971422579.jpg)

When ever you kill a mob that yields xp/honour as horde Victory doesn't activate.

**Expected behaviour:**

When ever you kill a mob that yields xp/honour Victory Rush will activate

**Steps to reproduce the problem:**

Attack and kill any mob that yields honour and XP as a horde warrior

CHANGEME
1.Attack and kill mob
2. Victory Rush does not light up
3. Horde Specific ( More than 1 horde warrior experiencing same issue )

Id's

Spell : Victory Rush #34428

Sources:
https://tbc-twinhead.twinstar.cz/?spell=34428

**Comment by Cheelout** [comment]
Tested on Green and Yellow mobs,
On a level 68 and level 70 Toon.

**Comment by SUN-Leekie** [comment]
Cannot reproduce, fixed somehow?

**Comment by kelno** [comment]
Closed for now, can't reproduce
