### ISSUE TITLE
Quest item drop variance based on group status

### ISSUE THREAD

**Issue by Alobis** [SunstriderEmu/BugTracker#1133]
**Description:**
Quest item drop rates appear to vary wildly based on whether the player is in a party.
Different levels of investigation across different quests - Artie has noticed it across many quests.
This entry will refer specifically to the quest item A Mysterious Tome

**Current behaviour:**
While being grouped, one player received the quest item A Mysterious Tome (http://db.hellfire-tbc.com/?item=28552) and accepted the quest.
I was then unable to see the book on the Unyielding Knight (http://db.hellfire-tbc.com/?npc=16906) that the first player looted it from.
We then killed probably equaled 50-60 knights during that time.
None of them dropped the book.
Dropped group to test if that was causing an issue and it dropped first kill out of group.

**Expected behaviour:**
Quest items are received based on the players quest status, not those of the party.

**Steps to reproduce the problem:**
Step 1. Go to the location of the Unyielding knights and form a group.
Step 2. Have one player loot the book when it drops and accept the quest then attempt to have the second player loot it.
Step 3. Then kill mobs attempting to get the drop
Step 4. Drop group as a workaround to attempt for the drops

 **rev. hash/commit:** 	
Sunstrider rev. 11015 (13b9a922417+) 2019-04-17 19:32:40 +0200 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by kelno** [comment]
Was that a raid group ?

**Comment by Alobis** [comment]
It wasn't a raid group. We still received quest completion for the kill
credits.

**Comment by kelno** [comment]
Been touching the drop rates a lot these last months, I'm 100% positive they do not vary.
