### ISSUE TITLE
Finish implementing SPELL_EFFECT_ACTIVATE_OBJECT MiscValue

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#1146]
To dev:  
Original topic:  
https://github.com/TrinityCore/TrinityCore/issues/21078
With especially this post being very interesting:  
 https://github.com/TrinityCore/TrinityCore/issues/21078#issuecomment-420115205
Logic is already mostly implemented but commented out in the core: https://github.com/kelno/sunstrider/blob/c7641cfd34b3903b0192ad0a3a1f562fe061bd48/src/server/game/Spells/SpellEffects.cpp#L5871

We currently have the first few effects implemented because they are only animations, but to implement the other ones EVERY gameobject scripts must be reviewed and possibly adapted.

The benefits here would be:  
- Having fewer hand scripted gameobjects scripts
- Having them closer to Blizzlike in most cases
- Probably get a lot of missing scripts as well

**Comment by Faq** [comment]
guessing this can be closed as link is dead

**Comment by kelno** [comment]
Link is only openable by the few initiates that showed their worth to our great blizzlike god.

**Comment by kelno** [comment]
Merged in TC: https://github.com/TrinityCore/TrinityCore/commit/203573db83fb1d3f141b5aadbf1d1ca0a637bf94
