### ISSUE TITLE
[Karazhan ] - Wizard of Oz - The Crone despawns before combat

### ISSUE THREAD

**Issue by Cheelout** [SunstriderEmu/BugTracker#1154]
**Description:**

After killing all the initial adds the Crone spawns but then disappears and combat is lost and the fight ends

**Current behaviour:**

After killing all the initial adds the Crone spawns but then disappears and combat is lost and the fight ends

NPC ID: 18168

**Expected behaviour:**

The Crone should engage the raid group

**Steps to reproduce the problem:**

CHANGEME
1. Engage Wizard of Oz Opera Event
2. Kill all initial Adds
3. Observe that Crone spawns and despawns

 **rev. hash/commit:** 	
11053

**Comment by SUN-Leekie** [comment]
#137

**Comment by kelno** [comment]
Fixed by woiwoz with 11295

**Comment by artieau** [comment]
Boss now works, however the 4 adds at the start of encounter now do not automatically aggro players.
@kelno

**Comment by Jerrythemagicdog** [comment]
the entire event needs to be rewritten
