### ISSUE TITLE
Drakes chillin

### ISSUE THREAD

**Issue by hufsa** [SunstriderEmu/BugTracker#1166]
**Description:**
Mature Netherwing Drake (Entry 21648) seem to have incorrect flags.
Dem drakes fly around for a while until they sit down like in the image below.

**Current behaviour:**
Dem drakes be chillin hard af. Thinkin they got some floor beneath them or smth like, rly?

**Expected behaviour:**
Dem drakes need to hover/flap their wings, right?

**Steps to reproduce the problem:**
Go to Netherwing Fields in Shadowmoon Valley.
Look at dem drakes.

 **rev. hash/commit:** 	
11063 (53ac31a3160c)

![drakes](https://user-images.githubusercontent.com/1609919/56593713-60122580-65ec-11e9-8c06-c24afa8a3bbd.png)

**Comment by kelno** [comment]
Seems fixed

**Comment by Jerrythemagicdog** [comment]
Wasn't fixed, creature_template_movement had Flight set to 2 while we already do the same thing in the script for the drake - resulted in the visual oddity captured on the screenshot.
Fixed now, also enabled smooth movement to make it prettier!
