### ISSUE TITLE
Unable to swap Blacksmithing specializations.

### ISSUE THREAD

**Issue by qoth** [SunstriderEmu/BugTracker#1173]
**Description:**

Currently players who learned a weapon specialization before the 2.0 switch are unable to swap weapon specializations in Blacksmithing.

**Current behaviour:**

Talk to your respective teacher and look for gossip option to unlearn specialization.
Master Swordsmith [17039] - Seril Scourgebane [11193]
Master Hammersmith [17040] - Lilith the Lithe [11191]
Master Axesmith [17041] - Kilram [11192]

No option will be present.

**Expected behaviour:**

Speaking to your respective specialization teacher should give the gossip option to unlearn your spec for 100g.

**Steps to reproduce the problem:**

CHANGEME
1. Logon to a toon who completed weaponsmithing and/or a specialization before the upgrade
(Examples: Majinhoochx [Hammersmith])
2. Visit the respective trainer (Lilith the Lithe)
3. No gossip option will be available

I believe this is related to the fact that spell ui 'Weaponsmith' ID [9787] is not present on these characters after the migration from Vanilla to TBC. Adding this spell back to all of those who have a Master Weapon specialization should resolve the issue.

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/35262513/56737769-520a0380-67aa-11e9-89da-368bfc6731db.png)

**Comment by qoth** [comment]
@Tamosheik

**Comment by Tamosheik** [comment]
An SQL fix has been deployed which has solved the issue with current characters, however an additional check needs to be added to the exotic vendor on faction change:

**Horde to Alliance:**
UPDATE `character_queststatus_rewarded`  SET `quest`=5284 WHERE `quest`=5302;

**Alliance to Horde:**
UPDATE `character_queststatus_rewarded`  SET `quest`=5302 WHERE `quest`=5284;
