### ISSUE TITLE
[Quest] The Big Bone Worm

### ISSUE THREAD

**Issue by zemfi** [SunstriderEmu/BugTracker#1175]
**Description:**

Quest: The Big Bone Worm (#10930) requires an item to summon an NPC to kill required for the quest, it is random, but not happening after numerous(!) tries.

**Current behaviour:**

Killing the required Decrepit Clefthoof (#22105) Doesnt spawn the required Hai'shulud (#22038) to kill to complete the quest. Tried with a grp of two, over 40-60+ tries, even with **both** of us summoning at the same time.

**Expected behaviour:**

Kill the required Decrepit Clefthoof, and after a few/reasonable time, the Hai'shulud to kill for the quest should appear and be killable.

**Steps to reproduce the problem:**

CHANGEME
1. Accept Quest
2. Kill Decrepit Clefthoof (#22105)
3. Use Fumper (#31825)
4. After countless attempts Hai'shulud (#22038) wont spawn at all.

 **rev. hash/commit:** 	

.rev 11071

**Comment by giveusmezpls** [comment]
This quest DOES work, I had one group get it in 2, one in 5, and another in 23.

**Comment by zemfi** [comment]
How long ago did you get this? as in the most recent one?

We had 2 of us trying to spawn it, to the point we were both 'fumping' at the same time and nothing, and spending alot of time on it, well over 60+ tries (probably more since we were both doing it).

Either incredibly bad rng or something that should be checked if its broken or not.

**Comment by SUN-Leekie** [comment]
Tried it and it spawns the first time.

**Comment by Jerrythemagicdog** [comment]
Quest works, AI for Hai'shulud fixed
