### ISSUE TITLE
deathwish sometimes fades early

### ISSUE THREAD

**Issue by oj449** [SunstriderEmu/BugTracker#1176]
**Description:**
the warrior spell deathwish
https://tbc-twinhead.twinstar.cz/?spell=12292
sometimes lasts less than 10 seconds before going away, or perhaps a random number that is much less than 30 seconds
**Current behaviour:**
use deathwish and it will turn off before 30 seconds
**Expected behaviour:**
deathwish lasts 30 seconds
**Steps to reproduce the problem:**
1. use deathwish
2. sometimes it turns off early
i only really have 1 combat log to prove this, it happens rather rarely, less than 20% but more than 5% of the time or so, but note in this combat log that i use bloodrage, a 10 second buff, and deathwish, a 30 second buff, at the same time yet bloodrage is the last to fade away
[2019-04-26_11-02-38.zip](https://github.com/thebarrensissues/Issues/files/3119332/2019-04-26_11-02-38.zip)
![visual](https://user-images.githubusercontent.com/47352954/56777130-1fe0bc00-6813-11e9-8015-cf5dc2fdde59.png)

**Comment by Jerrythemagicdog** [comment]
Was probably related to the timer issue or Enrage / Death Wish interaction.
