### ISSUE TITLE
execute issue with sweeping strikes

### ISSUE THREAD

**Issue by oj449** [SunstriderEmu/BugTracker#1177]
**Description:**
execute doesn't hit full damage sometimes to the extra target for sweeping strikes
https://tbc-twinhead.twinstar.cz/?spell=25236
https://tbc-twinhead.twinstar.cz/?spell=12328
**Current behaviour:**
execute sometimes hits only the base rage cost damage to the second target, sometimes it hits the full amount, not sure why
**Expected behaviour:**
execute always hits the same damage it hit to the first target to the extra sweeping strikes target, not just the base rage cost damage
**Steps to reproduce the problem:**
1. get a target to low health with sweeping strikes up and another target next to them
2. execute one in a way that sweeping strikes procs onto the other
3. watch the damage numbers
![visual](https://user-images.githubusercontent.com/47352954/56777557-8f57ab00-6815-11e9-931a-ead36e8a9a14.png)

**Comment by oj449** [comment]
could be related to the other issue i made for execute where it seems to be coded incorrectly, not related to sweeping strikes itself

**Comment by oj449** [comment]
Found patch note for patch 1.11, noting that execute will only do base damage to sweeped mobs unless they are also 20% or less, so it seems this is working as intended

**Comment by kelno** [comment]
Thanks for the research! Can you link the line from the patch note?

**Comment by oj449** [comment]
Patch 1.11.0 (20-Jun-2006): This spell has a number of fixes: When used in conjunction with Execute and the second victim is below 20% health, they will be hit with the full Execute amount. If the second victim is not below 20% health, they will be hit with normal melee swing damage; If the ability you are using does not deal damage, it will not use a charge of Sweeping Strikes; The extra attack it generates when used with Whirlwind now has the correct damage range; The additional attacks generated by this ability will now properly take into account the armor of the second target.
i did test and execute does seem to be hitting full damage only when the cleave target is below 20% so this is working correctly it seems, tho i think it might be doing base execute damage and not aa damage, as it seems to hits only 500 or so with the base damage being 700, whereas my auto attack damage is 1000 so it should hit a bit more

**Comment by Jerrythemagicdog** [comment]
An addition here: 
Currently if the secondary target is above 20% execute doesn't do a normal melee swing worth of damage as it should.

rev. 13055

**Comment by kelno** [comment]
Fixed with next update
