### ISSUE TITLE
NPC spells are resetting auto attack swing timer

### ISSUE THREAD

**Issue by qoth** [SunstriderEmu/BugTracker#1184]
**Description:**

NPC spells are resetting auto attack swing timer

**Current behaviour:**

Whenever an npc is casting a spell, it is resetting their auto attack swing timer, resulting in same frame attacks. This is especially harsh on mobs that cast cleave, Example: High King Maulgar

**Expected behaviour:**

Swing timer should be unaffected by spells.

**Steps to reproduce the problem:**

CHANGEME
1. Engage High King Maulgar 
2. Watch time between attacks
3. Witness Auto attack-> Cleave -> Auto in the same frame.

 **rev. hash/commit:** 	
![image](https://user-images.githubusercontent.com/35262513/56851231-b617fd80-694b-11e9-8a33-283e67b171ad.png)

**Comment by giveusmezpls** [comment]
you can check the mobs in black morass as good examples, almost all the rift lord and rift keeper will display this behavior.

**Comment by kelno** [comment]
Could it be that only creatures with dual wield are affected?

**Comment by Cheelout** [comment]
@kelno No High King Maulgaur swings a big 2 handy mace and we see the same issue on him

**Comment by kelno** [comment]
Probably fixed with 11266

**Comment by kelno** [comment]
Maulgar has Dual Wield for some reason, it's going to be removed when the boss is reworked.
Any other example?

**Comment by Jerrythemagicdog** [comment]
fixed
