### ISSUE TITLE
There is no DR in PvE

### ISSUE THREAD

**Issue by oj449** [SunstriderEmu/BugTracker#1195]
**Description:**
there should be stun dr types, controlled stuns and uncontrolled stuns that do not dr each other, such as charge and mace spec, they should not reduce each others timer
https://tbc-twinhead.twinstar.cz/?spell=11578 - charge
https://tbc-twinhead.twinstar.cz/?spell=12704 - mace spec rank 5

**Current behaviour:**
use a controlled stun on an enemy(any stun that is able to be used on command, hand of justice, intercept, etc), and then try to hit them with an uncontrolled stun(mace spec, deep thunder, etc), it will last half the duration that it is listed as.

**Expected behaviour:**
use a controlled stun on an enemy(any stun that is able to be used on command, hand of justice, intercept, etc), and then try to hit them with an uncontrolled stun(mace spec, deep thunder, etc), they should both last their full durations as they shouldn't be on the same stun dr as each other.

**Steps to reproduce the problem:**
as above

rev. 11098

**Comment by Kaziner** [comment]
https://wowwiki.fandom.com/wiki/Diminishing_returns

WoW Icon 16x16 Patch 1.9.0 (03-Jan-2006): The stun effect's duration no longer diminishes or is diminished by controlled stun abilities and spells:
[Improved Starfire]
[Improved Concussive Shot]
[Impact]
[Seal of Justice]
[Blackout]
[Mace Specialization] (rogues and warriors)
[Pyroclasm]
[Improved Revenge]

**Comment by oj449** [comment]
yeah, but currently in the client those are all being dr'ed by other abilities, as well as deep thunder will be there for tbc and stormherald, or well any % chance stun proc items

**Comment by Kaziner** [comment]
The above suggests that Mace spec stun shouldn't DR with intercept or conc blow; I'm just providing a bit of research to support the ticket

**Comment by kelno** [comment]
Big thanks Kaziner, I'll use that list for starters. Can you think of some new tbc spells that should use the same mechanic ?

**Comment by oj449** [comment]
I've gone through all the spells added and the old spells but it seems no more rng stuns were added besides item stuns.

**Comment by oj449** [comment]
checked hunter pet abilities - no random stuns

**Comment by kelno** [comment]
Thanks!

**Comment by oj449** [comment]
seems to have been a fix released for this, and uncontrolled stuns are not being dr'ed by controlled stuns, however it seems instead they just aren't being dr'ed at all.

**Comment by kelno** [comment]
Indeed there was a fix.
Regarding you last sentence, it seems for work for us for controlled stun, we tried with blackout and mage impact. Is is wrong with something else?

**Comment by kelno** [comment]
It seems to happen only for some specific spells, I need a very precise list.

https://tbc-twinhead.twinstar.cz/?spell=12704 - mace spec rank 5 
is indeed in the group wrong

**Comment by oj449** [comment]
odd, try having a warrior with deep thunder and mace spec and a priest with the shadow dmg stun stunning a target, it won't dr on live atm, was very powerful

**Comment by oj449** [comment]
https://youtu.be/Cbvhms300FE?t=44
showing a lucky number of procs not dr'ing either themselves or each other, when it should be that all uncontrolled stuns dr each other and don't interfere with controlled stuns

**Comment by oj449** [comment]
that was mace stuns not dr'ing and deep thunder procs, but when i was raiding revenge stuns and shadow magic stun were both not dr'ing as well

**Comment by kelno** [comment]
It shouldn't DR in PvE though?
We tested only in PvP setups

**Comment by oj449** [comment]
hmm, i can't find anything saying it shouldn't dr in pve scenarios, as it seems insanely busted to have any cc that doesn't dr that has no actual cooldown

**Comment by oj449** [comment]
case in point for hydross, we had a shadow mage using their 15% chance on shadow damage and my deep thunder/mace spec combo and they were stunned nearly the whole time

**Comment by oj449** [comment]
druids can just cyclone lock mobs lol

**Comment by oj449** [comment]
https://wowwiki.fandom.com/wiki/Diminishing_returns - mentions in patch notes for DR groups for pve
https://www.wowhead.com/forums&topic=24405 - 2nd comment
"It's not all that hard to find:

http://www.wowwiki.com/Diminishing_returns

And yes; cs, ks and mace stun have dr in both PvE and PvP."

**Comment by kelno** [comment]
I see, it seems indeed that some spells should DR in PvE:
https://wowwiki.fandom.com/wiki/Diminishing_returns?oldid=1387171
