### ISSUE TITLE
[Warlock] Pets are missing a Soul Link and Demonic Knowledge buffs on them (visual)

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1198]
**Description:**

Warlock summons should get a visual Soul Link buff on them - it's currently missing. The spell works correctly otherwise.

**Current behaviour:**

No soul link buff on pet (the damage is shared correctly):

https://imgur.com/a/iODUYjP

**Expected behaviour:**

Screenshot of a video from retail ("Noone 3 frost mage pvp"):
https://imgur.com/a/X2rp7CC

**Steps to reproduce the problem:**

1. Summon a warlock pet
2. Cast Soul Link
3. Buff on pet is missing

 **rev. hash/commit:** 
	
Sunstrider rev. 11100

**Comment by Jerrythemagicdog** [comment]
Actually also missing Demonic Knowledge visual on the pets, looks sketchy.
![image](https://user-images.githubusercontent.com/46463908/62840543-4debee00-bc94-11e9-96f6-3be9abcf81f9.png)


comparison to retail: https://imgur.com/a/X2rp7CC

**Comment by hufsa** [comment]
Kid's sketchy

**Comment by Jerrythemagicdog** [comment]
The data in DB is correct but when we .list aura on the Felhunter for example we're missing the Soul Link spell on him (seems to not be casted)
`SELECT * FROM spell_pet_auras WHERE spell = 19028;`

**Comment by hufsa** [comment]
Fixed
