### ISSUE TITLE
[Warlock] [Item] Void Star Talisman doesn't fully work

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1199]
**Description:**
Void Star Talisman (item ID: 30449) increases our pet's resistances by 130 and the warlock's spell damage by 48.

**Current behaviour:**

Currently it only increases warlock's spell damage done by 48, the pet's resistances are unchanged (https://imgur.com/a/7txIDjG)

**Expected behaviour:**

The pet's resistances should be boosted by 130.

**Steps to reproduce the problem:**

1. Summon any pet as warlock
2. .additem 30449
3. Resistances in pet panel don't go up.

 **rev. hash/commit:** 	

rev. 11111

**Comment by Jerrythemagicdog** [comment]
The spell applied by the item Void Star Talisman has two effects, one of them has to be scripted because it's a dummy aura (18350 that's the one giving resistances to the pet.)

**Comment by kelno** [comment]
fixed

**Comment by TheMoneyHater** [comment]
Are you sure this got fixed? I can't see it working.

**Comment by kelno** [comment]
Regression here, fix doesn't work anymore

**Comment by kelno** [comment]
Fixed with next server update
