### ISSUE TITLE
[Movement] Pet movement and Charge mechanics sometimes don't work properly.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#120]
**Description:**

Pet movements and Charge mechanics behave weirdly in certain spots (tested on Ruins of Lordaeron and Blade's Edge Arena.) Places like the tomb in the middle of RoL sometimes make the pet freeze when issued with an attack command or result in the pet taking a sub-optimal path to the target (for example running around the tomb instead of on top of it to reach the target). In these same spots Charge based spells can't find a path either and just don't work. The same behavior is observed in Blade's Edge Arena on the two big pillars that are connected to the bridge with ropes. There is no charge path from those and pets can't pathfind - they also refuse to walk on the ropes and kind of float onto the pillar. The pets also fall through these pillars randomly when issued a follow command and fall down on the ground following their owner (should run all the way through the ropes->bridge->ramp to the owner.)

**rev. hash/commit:** 

latest

**Comment by kelno** [comment]
Is this fixed for Blade's Edge Arena?
(Only the real arena should be fixed, not the one in world)

**Comment by Jerrythemagicdog** [comment]
Fixed a long time ago for RoL and BEA.
