### ISSUE TITLE
[SSC] - Morogrim Tidewalker - Water grave does not bump

### ISSUE THREAD

**Issue by Cheelout** [SunstriderEmu/BugTracker#1200]
**Description:**

Water grave does not deal damage

**Current behaviour:**

Water grave does not deal damage

**Expected behaviour:**
https://www.wowhead.com/spell=38028/watery-grave
Watery Grave

Teleport 4 players under the waterfalls. ~6000 damage after 6 seconds, and some (about 1.5k) falling damage. ~50 Yard Range from Morogrim Tidewalker. ~ 30 sec cooldown. People close to the watery grave target will also take damage.

**Steps to reproduce the problem:**

CHANGEME
1. Engage Morogrim
2. Get tombed
3. Watch no damage

Revision:
11111

**Comment by SUN-Leekie** [comment]
Core issue with the effects not being applied because the player is stunned/root. @kelno is on the case.

**Comment by kelno** [comment]
Dev note:
Allowing knockback to target rooted unit without further changes will kick players.
Reason for this is that the order of movement changes sent is wrong:
1. S->C Knockback
2. S->C Unroot
3. C->S Unroot ack
4. C->S Knockback

This is a particular case, apparently the client will always send the unroot first before the a knockback, regardless of the order they are received. Which kinda makes sense.
So the solution would be to sent unroot first. Might require some spell aura trigger rework to allow this.

**Comment by Jerrythemagicdog** [comment]
Fixed after next restart.
