### ISSUE TITLE
[SSC] - Clearing the 6 platforms does not boil the water and stop fish spawning

### ISSUE THREAD

**Issue by Cheelout** [SunstriderEmu/BugTracker#1202]
**Description:**

When all 6 Platforms are cleared past Hydross, the water does not boil.

**Current behaviour:**

When all 6 Platforms are cleared past Hydross, the water does not boil.

**Expected behaviour:**

When the 6th platform is cleared, the water is meant to boil and the fish are meant to stop spawning.

https://wow.gamepedia.com/Serpentshrine_Cavern_walkthrough

Scalding Water
As long as the 6 platform packs surrounding The Lurker Below are cleared, the water will be boiling, killing all of the Coilfang Frenzy in the water. Entering the water during this condition results in a Scalding Water debuff, which inflicts 500 damage every 3 seconds (avoidable by using any forms of waterwalk). This is considerably less damage than attacks from the Coilfang Frenzy. If the platform packs respawn, the water stops boiling and the Coilfang Frenzy return.

Defeating The Lurker Below prevents both the Scalding Water and the Coilfang Frenzy, allowing more convenient navigation of the instance.

**Steps to reproduce the problem:**

CHANGEME
1. Clear all the platforms
2. No fishy cooked :(

 **rev. hash/commit:** 	
11111

**Comment by kelno** [comment]
Can you source that please?

**Comment by Cheelout** [comment]
In the link in the article and extract is in the ticket

![image](https://user-images.githubusercontent.com/38281939/57050954-578fae00-6cc2-11e9-87b0-65c304965d32.png)

**Comment by Cheelout** [comment]
Also this: https://www.youtube.com/watch?v=5bB-z2SIc58

**Comment by SUN-Leekie** [comment]
Fixed in 11145.

**Comment by SUN-Leekie** [comment]
New fix in 11327.

**Comment by artieau** [comment]
Now no fishing spawning at all before any platforms cleared @kelno rev. 13051

**Comment by kelno** [comment]
Fixed since
