### ISSUE TITLE
[Quest] Divination: Gorefiend's Truncheon

### ISSUE THREAD

**Issue by zemfi** [SunstriderEmu/BugTracker#1212]
**Description:**

2 Issues:
You can see the mobs without wearing the required item (Item: Spectrecles #30719)
The NPC to hand the quest in doesnt seem to be there? (NPC: Ancient Shadowmoon Spirit #21797)

**Current behaviour:**

As Above

**Expected behaviour:**

Shouldnt be able to see the required mobs (NPC: Ghostrider of Karabor #21784) to kill without equiping the above item. To had in the completed quest, the NPC should be there..

**Steps to reproduce the problem:**

1. Accept quest, dont wear the goggles, you can still see the NPC's to kill.
2. Complete Quest
3. No NPC to hand-in?

Looks to be related to this: #1025.

 **rev. hash/commit:** 	

.rev 11118

**Comment by Mediowow** [comment]
Did this on 01 Jun 19, appeared to be working. Had to kill around 9 ghostriders for the item to drop.

**Comment by Jerrythemagicdog** [comment]
Thanks!
Tested now, works correctly.
