### ISSUE TITLE
[Professions] Skinning: Not able to skin (receive loot) from other players/dead npc's properly

### ISSUE THREAD

**Issue by zemfi** [SunstriderEmu/BugTracker#1213]
**Description:**

Noticed this issue for awhile, but if you try and skin a npc killed by someone else, or an npc that is already dead, and you had nothing todo with killing/dmg etc (not in a party/raid), often you can skin the creature, but get no loot (no loot window) and the corpse becomes un-skinnable.

**Current behaviour:**

As above

**Expected behaviour:**

When you skin something, you should receive loot (loot window).

**Steps to reproduce the problem:**

Part 1:
1. Have someone separately kill a skinnable npc (looted, no party etc)
2. Skin the creature, and suddenly nothing happens, no loot window, corpse becomes un-skinnable.

Part 2:
1. Go to Shattered Plains in Shadowmoon Valley (54,15) 
2. Try to skin one of the dead Domesticated Felboar, same as above.

 **rev. hash/commit:** 	

.rev 11118

**Comment by giveusmezpls** [comment]
Is this possibly related to the empty slot issue where people can get mobs which have nothing on them but are still lootable? 
It might be unlikely because in group these types of mobs are unskinnable

**Comment by Jerrythemagicdog** [comment]
Seems to be partially fixed by woiwoz some time ago, sometimes it still doesn't allow to skin a creature for some reason (tested in Durotar on "Venomtail Scorpid" and "Bloodtalon Scythemaw" with player A killing and player B attempting to, sometimes successfully, skin.)

**Comment by Varanak** [comment]
If a guard kills an npc that wasn't tagged by you, it is skinnable giving skill points to skinning, but no loot is available.

**Comment by kelno** [comment]
FIXED.
Happened if the killer player wasn't not found.
