### ISSUE TITLE
Darkmoon Faire Damage buff is resistable.

### ISSUE THREAD

**Issue by giveusmezpls** [SunstriderEmu/BugTracker#1215]
**Description:**

The Sayge tells me my fortune and grants me a buff giving damage from 1-10%. Unfortunately it is a hostile cast and therefore both resistible at a high chance due to level difference and causing you to enter combat with the NPC.

NPCID=14822

**Current behaviour:**

Not good.

**Expected behaviour:**

Good.

**Steps to reproduce the problem:**

1. Go to the man at the faire.
2. Click the man, choose all the best options, kill the man, slay your friend, murder his family to get the damage buff.
3. Be sad you are now in combat with no buff and a useless piece of paper.
4. Report it on Github.
5. Speak out loud the words you are typing to your friend Tanglez to amuse him.
6. Submit the bug.

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/49624667/57114639-7dce5000-6d8d-11e9-9fcc-d9522ef4c6b5.png)

**Comment by giveusmezpls** [comment]
even if you dont resist you still get put in combat.

**Comment by artieau** [comment]
Please provide Spell ID of the buff

**Comment by giveusmezpls** [comment]
here is one spellid sir https://vanilla-twinhead.twinstar.cz/?spell=23738

**Comment by kelno** [comment]
to dev: This should be detected as positive... I dunno why it isn't though.

**Comment by kelno** [comment]
fixed
