### ISSUE TITLE
[DUNGEON] Uldaman: Archaedas Summoning not working

### ISSUE THREAD

**Issue by Chriski** [SunstriderEmu/BugTracker#1218]
**Description:**

When having 3 people (the required amount) click the Altar to activate Archaedas and start the fight, Archaedas will gain the tornado visual around him, yell 'Who dares awaken Archaedas? Who dares the wrath of the makers' but remain untargetable to everyone, and he will follow the last person to click the Altar.

**Current behaviour:**

When having 3 people (the required amount) click the Altar to activate Archaedas and start the fight, Archaedas will gain the tornado visual around him, yell 'Who dares awaken Archaedas? Who dares the wrath of the makers' but remain untargetable to everyone, and he will follow the last person to click the Altar.

**Expected behaviour:**

Click the Altar to activate Archaedas and start the fight. Archaedas should agro the last person to click the altar, and then become targetable.

**Steps to reproduce the problem:**

1. Step 1- 3+ people click altar
2. Step 2- Observe mob following around last person to click
3. Step 3- Become stuck inside the room as the door is locked.

 **rev. hash/commit:** 	

Sunstrider rev. 11145 (1df84fbe3ee5+) 2019-05-03 17:33:45 +0200 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
