### ISSUE TITLE
[Reputation] Aldor/Scryer Bug

### ISSUE THREAD

**Issue by Azytheoneandonly** [SunstriderEmu/BugTracker#1224]
**Description:**

Scryer/Aldor Rep bug that has been appearing over and over.

edit: player just reported that they had completed quest spoken to one of the npc, logged off to send some marks over and as soon as they came back in they were at war.

**Current behaviour:**

Choose your Allegiance to Aldor/Scryers and be at war with them while neutral and unable to untick at war.

**Expected behaviour:**

Not be at war with selected faction and/or be able to untick it.

**Steps to reproduce the problem:**

1. Do City of Light Quest: Pick up followup to Either.
2. Be at war with faction you pick.

Allegiance to the Aldor: https://tbcdb.com/?quest=10551

Allegiance to the Scryers: https://tbcdb.com/?quest=10552

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/37324574/57190993-19b1b480-6f64-11e9-9dd6-9fb136129a71.png)

**Comment by Cheelout** [comment]
The quests are not removing the At War flag with either faction picked.

**Comment by Cheelout** [comment]
Also the quests should put you to Friendly, instead the put you to Neutral

**Comment by Jerrythemagicdog** [comment]
Tested now:
1. Allegiance to the Aldor sets the player to Friendly with the Aldor, no issues after relogging.
2. Allegiance to the Scryers sets the player to Friendly with the Scryers, no issues after relogging.

Seems like there was an issue with porting characters over to a different core on The Barrens.

**Comment by kelno** [comment]
Yeah this was because of the porting
