### ISSUE TITLE
Chests and keys interaction

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1227]
**Description:**
When opening a chest and having only 1 key left the loot window disappears very fast / doesn't open at all and the key gets consumed.

https://streamable.com/9wtej

It's really visible at the end when there's only one key left.
It only happens without auto-looting the chest (shift-click or enabled in options).

**Expected behaviour:**
The loot window should stay open for longer and allow the player to loot the items.

**Steps to reproduce the problem:**

1. .go xyz  -3091.506836 1759.867432 75.437843 530
2. .additem 30426
3. open the chest with the key without auto-loot enabled 

 **rev. hash/commit:** 	
rev. 11155

**Comment by kelno** [comment]
Fixed
