### ISSUE TITLE
windfury icd not applying correctly

### ISSUE THREAD

**Issue by oj449** [SunstriderEmu/BugTracker#1228]
**Description:**
windfury weapon is not incurring a global cool down of 3 seconds for both main hand and offhand on a shaman, and instead both applications of the spell have their own icd
https://tbc-twinhead.twinstar.cz/?spell=25505
https://blue.mmo-champion.com/topic/18050-tbc-enhancement-shaman-faq/
post about someone explaining the behaviour of the icd on 2 weapons
"The Windfury Cooldown 
After windfury procs it cannot proc again on either hand for 3 seconds. Since no usable 1H weapons are slower than 2.9s (or 3.9s with flurry), this means that no 1H weapon in the entire game can proc windfury twice in a row. Note that this means that windfury will proc less than the 20% promised on its tooltip. Please read "Optimal Weapon Speeds" below for more information. 
- When only one weapon has windfury, each hit outside of the cooldown has a 20% chance to proc WF. This leads to a 11-18% overall proc rate, depending on gear, weapon speed, spec, and luck. Slower is better. 
- In version 2.0 the shared cooldown could be avoided by downranking windfury on the off-hand. This was removed in 2.1 and the cooldown is now shared. This change reduces overall enhancement shaman DPS by 10-18%, depending on spec, weapon speed, gear, and spell use. 
- When both weapons have windfury of any rank, each hit outside of the cooldown has a 36% chance to proc windfury. This leads to a 11-14% procrate with weapons faster than 2.0s unhasted and a 14-18% procrate with weapons slower than 2.0s unhasted. Slower is better. Handy reference chart: 

3.0s normal, 4.0s with flurry = no swings wasted (no 1H weapons >20dps exist at this speed) 
1.5s normal, 2.0s with flurry = one swing wasted 
<1.5s normal, <2.0s with flurry = two swings wasted "
**Current behaviour:**
windfury weapon for shamans can proc their mainhand and offhand windfury weapons at the same time
**Expected behaviour:**
windfury weapon only procs once every 3 seconds, regardless if u have it on both weapons as they should share the same icd
**Steps to reproduce the problem:**
enchant 2 fast weapons with windfury weapon
hit something for a while
notice 2 procs within the same window of 3 seconds
image of it happening:
![visual](https://user-images.githubusercontent.com/47352954/57326879-d10b1e80-7150-11e9-860d-8c196eca9063.png)
rev. 11165

**Comment by SUN-Leekie** [comment]
Updated for 2.4: https://web.archive.org/web/20080914162601/http://forums.worldofwarcraft.com/thread.html?topicId=79203452&sid=1

> Windfury Weapon
> - Scales with weapon DPS, attack power, melee haste, melee crit, melee tohit. 
> - Mitigated by armor and block, avoided by dodge, parry, and miss. 
> - Has a 5% special attack type melee miss chance. 
> - Benefits from weapon mastery for 10% more damage. 
> - The best enchant for enhancement shamans on both hands. 
> - The two extra attacks can proc flurry, unleashed rage, and weapon on hit effects. They do not consume flurry charges and don't glance. 
> - The two offhand attacks are affected by the standard offhand 50% damage reduction. The WF proc's attack power bonus is not. 
> - WF totem only procs on autoattacks and "on next melee" attacks like heroic strike. The WF attack itself is white damage and generates rage. WF totem scales with melee gear, so it's a fantastic buff for rogues, paladins, and warriors. 
> 
> The Windfury Cooldown 
> After WF procs it cannot proc again on either hand for 3 seconds. No 1H weapon in the entire game can proc WF twice in a row. This means that WF will proc less than the 20% promised on its tooltip. 
> - When only one weapon has WF, each hit outside of the cooldown has a 20% chance to proc. This leads to a 11-18% overall proc rate, depending on gear, weapon speed, spec, and luck. Slower is better. 
> - When both weapons have WF, each hit outside of the cooldown has a 36% chance to proc. This leads to a 11-14% procrate with weapons faster than 2.0s unhasted and a 14-18% procrate with weapons slower than 2.0s unhasted. Slower is better. Handy reference chart: 
> 
> 3.0s normal, 4.0s with flurry = no swings wasted (no 1H weapons >20dps exist at this speed) 
> 1.5s normal, 2.0s with flurry = one swing wasted 
> <1.5s normal, <2.0s with flurry = two swings wasted (bad!)

**Comment by kevin-chowanski** [comment]
Any news on that?

It is really gamebreaking for me tbh

![wf1](https://user-images.githubusercontent.com/62059560/76962071-d1527980-691e-11ea-9010-594050bb7acd.jpg)

--

![wf3](https://user-images.githubusercontent.com/62059560/76962127-ea5b2a80-691e-11ea-9ecd-793e0031c3ee.jpg)

--

![wf2](https://user-images.githubusercontent.com/62059560/76962136-edeeb180-691e-11ea-8583-d29779438afb.jpg)

2 procs same second :D

**Comment by kelno** [comment]
So you're telling me it's game breaking for you not to be nerfed?

**Comment by kelno** [comment]
Made a fixie, the cooldown is now shared between all ranks and right/left hand.
Need some testing then applied with next server update.

**Comment by TheMoneyHater** [comment]
reeeeeeeeeeeeeeeeeeeeeeeeee
