### ISSUE TITLE
elemental focus and shamanistic focus interaction

### ISSUE THREAD

**Issue by oj449** [SunstriderEmu/BugTracker#1231]
**Description:**
the talents elemental focus
https://tbc-twinhead.twinstar.cz/?spell=16164
and, shamanistic focus are currently only stacking for tooltips only, but when you use a shock, even though it will read it as no mana cost, it will still cost 40% of the mana cost when it should be free

https://tbc-twinhead.twinstar.cz/?spell=16164 - elemental focus
http://calculators.iradei.eu/talents/shaman?0000000000000000000005002301000000000000000000000000000000000 - shamanistic focus

forum posts with people saying it should be free
http://www.arenajunkies.com/topic/33038-elemental-focus-and-shamanistic-focus/
"both can pro(c) and it will be 100% free to cast a shock"
https://www.wowhead.com/forums&topic=12357
"Yes, shocks would be 100% mana free if everything lined up."

**Current behaviour:**
with both talents up the mana cost on the tooltip is 0 but it will cost you mana to cast it
**Expected behaviour:**
with both talents up the mana cost on the tooltip is 0 and it is free to cast
**Steps to reproduce the problem:**
have both talents up and use a shock spell
rev. 11175

**Comment by kelno** [comment]
See test: "talents shaman shamanistic_focus"

**Comment by kelno** [comment]
Made some rewrite here, to test!

**Comment by Jerrythemagicdog** [comment]
Fixed in https://github.com/kelno/sunstrider/commit/80e03d3a5e7ff3a2fd97d859f751940639112204
