### ISSUE TITLE
The Binding (Felhunter Quest ) unable to accept 

### ISSUE THREAD

**Issue by jcond23** [SunstriderEmu/BugTracker#1232]
The Quest chain to obtain the felhunter works fine until you try to accept the https://www.wowhead.com/quest=1795/the-binding .

**Current behaviour:**

When you talk to Strahad Farson to accept the binding its says you do not met the requirements and the option to accept the quest is no longer there.

**Expected behaviour:**

You should be able to start the quest were Strahad Farson summons the felhunter and you kill it completing the quest.

**Steps to reproduce the problem:**

1. Step 1 Complete Chain up to the point of trying to accept the binding quest.	

Sunstrider rev. 11175 (a2c15efda62f+) 2019-05-07 21:52:40 +0200 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by SUN-Leekie** [comment]
Cannot reproduce, can you give us more information?

**Comment by jcond23** [comment]
trying to accept the binding quest from Strahad Farson after doing the previous quests in the chain it gives you the error you do not meet the requirements for this quest error and than the quest disappears.

**Comment by SUN-Leekie** [comment]
That's what I did and I could accept the quest without an issue so I need more info about that, if you can take a little video, that could help.

**Comment by Jerrythemagicdog** [comment]
Fixed.
To dev:
The Binding had a Horde version of the quest in the PrevQuest (quest_template_addon).
