### ISSUE TITLE
[Quest] Securing the Celestial Ridge (10274)

### ISSUE THREAD

**Issue by BarrensJerk** [SunstriderEmu/BugTracker#1241]
**Description:**

Quest not completable after completing all requirements - complete button grayed out

**Current behaviour:**

After killing NPC Veraku (18544), player receives quest credit for killing him. Quest in log says complete. Go to hand in, with quest item Challenge of the Blue Flight (29101) in inventory, quest complete button is still gray.

**Expected behaviour:**

Complete quest objectives, hand in quest

**Steps to reproduce the problem:**

 **rev. hash/commit:** 	

re. 11236

**Comment by SUN-Leekie** [comment]
Can't reproduce

**Comment by Jerrythemagicdog** [comment]
Tested recently (9314ed64214f4f4b8f22e92bebc5ae18f228d1d2), no problems.
