### ISSUE TITLE
[Quest] - Trial of the Naaru Magtheridon - Not rewarding Tempest Key

### ISSUE THREAD

**Issue by Cheelout** [SunstriderEmu/BugTracker#1242]
Quest is currently not rewarding Tempest Key. 
Quest ID: 10888
Item ID: 31704

**Comment by Cheelout** [comment]
Fixed with SQL Update:
--Fix Trial of the Naaru: Maghtheridon no Tempest Key
UPDATE `quest_template` SET `RewItemId2` = 31704, `RewItemCount2` = 1 WHERE `entry` = 10888;

**Comment by Jerrythemagicdog** [comment]
merged from Cheelout's PR. Thanks!
