### ISSUE TITLE
Fighting creatures in water results in them evading

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1245]
**Description:**
When fighting a creature near water it starts evading if the players goes into water.
https://streamable.com/z3q4v

**Expected behaviour:**

Creature should go in the water.

**Steps to reproduce the problem:**

1. Be a gnome character (swimming in shallow water)
2. .go xyz 195.870377 5825.013184 21.491346 530
3. Creature will evade.

https://imgur.com/a/G76A6w4

 **rev. hash/commit:** 	
11246

**Comment by kelno** [comment]
Only happen with a lowly gnome

**Comment by Jerrythemagicdog** [comment]
Indeed, I am but a lowly gnome.
