### ISSUE TITLE
Special Mob Abilities can reset auto attack in some (or all?) cases.

### ISSUE THREAD

**Issue by giveusmezpls** [SunstriderEmu/BugTracker#1249]
**Description:**

It appears in some cases that mobs can use abilities directly after an auto attack and then be granted another chance to auto immediately afterwards. This creates a spikey incoming damage situation which can make content harder than intended and will make balancing some content very difficult.

**Current behaviour:**

An example of this is Fathom-Guard Tidalvess (NPCID=21965) on Fathom-Lord Karathress (NPCID=21214) uses his Frost Shock (SPELLID=38234) after melee and is granted an immediate second melee attack.
Since he also should have the ability to windfury if you combine these two the tank will not be very happy.

The bug is **not specific to this mob** and has been experienced in other places such as the Rift Lord (NPCID=17839) in Black Morass using his Mortal Strike (SPELLID=15708) ability.

If you need more examples to find the bug please let me know and I will find and post more.

**Expected behaviour:**

The cast time of a spell should have no interaction with the melee swing timer of the NPC.

**Steps to reproduce the problem:**

Please use the current behavior for this information.

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/49624667/57661933-58183500-7630-11e9-87c5-26644c97d742.png)

**Comment by giveusmezpls** [comment]
https://cdn.discordapp.com/attachments/576804198612598785/577792190395187210/unknown.png

**Comment by giveusmezpls** [comment]
![image](https://user-images.githubusercontent.com/49624667/57688204-3c3c7f80-7680-11e9-8a8a-a1c4776abda9.png)

saving examples

**Comment by kelno** [comment]
I can't reproduce that on Tidalvess, is that fixed maybe? We made a change related to attack speed

**Comment by Cheelout** [comment]
@kelno Nah Para is just a shit tank.

**Comment by giveusmezpls** [comment]
> @kelno Nah Para is just a shit tank.

I must disagree emphatically.
