### ISSUE TITLE
Nightmare Vine Nodes Missing

### ISSUE THREAD

**Issue by BarrensJerk** [SunstriderEmu/BugTracker#1264]
Currently there are 43 nightmare vine nodes in Shadowmoon Valley, where there should be 102.

Map of nightmare vine nodes in SMV from gatherer addon off Barrens currently:
![Current gatherer](https://user-images.githubusercontent.com/44628946/58069323-2119c480-7bd8-11e9-9787-b83e4679d995.jpg)

The nodes in game currently correspond to online databases like Twinstar
https://tbc-twinhead.twinstar.cz/?object=181280
The 40 or so nodes here correspond to our current in game nodes. 

On live though there were significantly more nodes. There wasn't a change in NMV nodes between 2.0 and 2.4, then in 2.4 they were added to locations outside SMV like Throne of KJ, Blades Edge in fel areas etc.
https://wowwiki.fandom.com/wiki/Nightmare_Vine

Gathermate_data from 2.3.3 shows ~102 NMV nodes in SMV
https://www.wowace.com/projects/gathermate_data/files?page=12
(The earliest upload of gathermate_data unfortunately)

Screenshot of gatherer data from 2.3 in November 2007 shows an identical spread of nightmare vine nodes to the gathermate_data 
http://wow.tgbus.com/shell/shangye/200711/20071129164600.shtml
![2007 novemeber nightmare vine](https://user-images.githubusercontent.com/44628946/58069583-1449a080-7bd9-11e9-93e5-0c763419c4ef.jpg)
![Gathermate 2 3](https://user-images.githubusercontent.com/44628946/58069586-1875be00-7bd9-11e9-91a8-1f8f8c37203a.jpg)

At the moment its significantly harder to collect NMV than any other herb. It's harder and takes longer than it did on live. Since we're missing +60% of the nodes, and they seem to spawn statically rather than in response to nodes being depleted by active farming or in response to number of players in the zone.

**Comment by kelno** [comment]
That's because Nightmare Vine Nodes are already pooled. But their pooling will be updated again with https://github.com/SunstriderEmu/BugTracker/issues/1509
