### ISSUE TITLE
[SSC] - Vashj - Phase 3 - Spawns large amount of Spore Bats

### ISSUE THREAD

**Issue by Cheelout** [SunstriderEmu/BugTracker#1265]
**Description:**

Approximately just after 2 minutes into Phase 3 (After Tainted Core Phase) Vashj spawns what looks like a hundred spore bats, this should not happen

**Current behaviour:**

Approximately just after 2 minutes into Phase 3 (After Tainted Core Phase) Vashj spawns what looks like a hundred spore bats, this should not happen

**Expected behaviour:**

Sporebat spawn rate is correct up until then, it just spawns like "The rest" of them..

**Steps to reproduce the problem:**

CHANGEME
1. Engage Vashj
2. Get to Phase 3
3. Observe spore bat spawns until just after 2 minutes
4. Rape brigade assemble

 **rev. hash/commit:** 	

11347

**Comment by giveusmezpls** [comment]
do you have a source?

**Comment by kelno** [comment]
I checked Vashj I don't see the issue
First bat is summoned after 15, then after 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, ... then 5 between each
If that's wrong I need some more data

**Comment by Jerrythemagicdog** [comment]
Can't reproduce, seems correct.
