### ISSUE TITLE
Movement prediction rework

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#1282]

**Comment by kelno** [comment]
Mostly done!

**Comment by kelno** [comment]
Issue still: 
https://streamable.com/uwzw3

Blaze:
u have to kinda pay attention
but basically what happens is
he has huge melee range because hes a big boy
but he still feels the need to hug me
and predict my movement
and as a result
he does these little micro stutters
and sometimes turns randomly like a moron

**Comment by Jerrythemagicdog** [comment]
Seems to affect pets and other cases as well (for example kind of breaks the "Follow" action in SmartAI as it disregards the angle and distance and uses prediction to override that.) 

Here are some examples from Blade's Edge Arena:
https://imgur.com/a/skrapUY

Other examples to look at are a creature that's using the follow functionality for example in SAI,
for example: 
.go crea 66903 - the Felhunter chasing the imp should be behind him (the intention behind using the follow function) but now he predicts his path and walks on the pillar.

**Comment by kelno** [comment]
It's done
