### ISSUE TITLE
Supremus stuck in kite phase after a wipe

### ISSUE THREAD

**Issue by Harrock1** [SunstriderEmu/BugTracker#1284]
**Description:**

After the first phase transition, Supremus remains in phase 2 for the rest of the pull and subsequent attempts

**Current behaviour:**

Boss does not correctly return to phase one after a kite phase.

**Expected behaviour:**

Kite phases should last 60 seconds, alternating with phase 1.

**Steps to reproduce the problem:**

1. Pull supremus, survive 1 minute. 

2. Wipe.

3. Pull, notice he starts in phase 2.

 **rev. hash/commit:** 	

11530

**Comment by kelno** [comment]
Thanks, I'm closing this as BT has not been touched yet and needs a full rework.
