### ISSUE TITLE
Spells with SPELL_EFFECT_SUMMON(28) shouldn't always despawn summons on owner's death.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1285]
**Description:**

Spells with SPELL_EFFECT_SUMMON(28) will always despawn the summoned creature on owner's death (unless stated otherwise in scripts). We need to change the rule or maybe provide an option from SAI to disable it (like SetCanDespawnSummons).

**Current behaviour:**
Spells like 35737 are necessary to complete quests and proper functioning of an event (summoning Nexus-Prince Razaan in Blade's Edge Mountains). Creatures are supposed to cast it on death and the trigger is supposed to fly to its destination (.go xyz 2819.591797, 5238.729004, 264.463135 530) to activate other triggers. Currently our trigger despawns immediately because the owner dies.

**Expected behaviour:**

Some summons are supposed to persist through owner's death. The rule needs to be changed or we need to provide optionality.

https://www.wowhead.com/npc=21057/nexus-prince-razaan#comments:id=212687

**Comment by woiwoz** [comment]
a haha...Let me see.
