### ISSUE TITLE
Players are able to join arena queue several times

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#1294]
I don't think they actually are several times in the queue but they override their last position in the queue, they can override an invitation like this.

**Comment by hufsa** [comment]
![aq](https://user-images.githubusercontent.com/1609919/61798202-2d650c80-ae29-11e9-8876-416712eadebb.png)

After joining the queue multiple times, the queue popped but I couldnt enter. The "you will be removed from the queue" timer ended but this is still visible. Clicking Enter battle does nothing.

**Comment by kelno** [comment]
It can be reproduced by killing a p
Events:

T1:
- player A dies and gets rooted (and acks)
T2:
- Player B dies
- Arena ends
- player A gets revived and root is removed (client does ACK this)
- All players have their client control disabled

At this point if player A switches map he is still rooted.
Seems to be an issue with removing root and removing client control at the same time.

**Comment by kelno** [comment]
Fixed with 8a0932ac8bb082150b777c81f2eaaf5f023c4795

**Comment by kelno** [comment]
The initial bug is fixed but this should be improved: 
we can register for bg then only arena and have registered for both (while we want it to be impossible)
