### ISSUE TITLE
[SmartAI] Enabling Gravity on creatures with previously Disabled Gravity has no effect.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1296]
**Description:**
Title.

**Expected behaviour:**
The creature should have gravity enabled when set so.
An example to look at: 
http://dev.sunstrider.com.test/creature/entry/22448/smartai
^ we disable his gravity in: 
http://dev.sunstrider.com.test/smartai/script/2244800
and enable it in: 
http://dev.sunstrider.com.test/smartai/script/2244801

**Steps to reproduce the problem:**
To see the above example in action:
1. .go xyz 3735.568604, 5366.791504, -7.884708, 530
2. .quest add 10742
3. /use Rexxar's Battle Horn
4. Observe Rexxar after the RP event.

**Comment by kelno** [comment]
Just to leave a trace of the discussion:
Always use ACTION_SET_CAN_FLY, disable gravity is bad bad bad

https://github.com/kelno/sunstrider-scripts/commit/c7710611e9d0f8ccb8e9a0bbfb844276bebeb511
