### ISSUE TITLE
Visibility issues on creatures and gameobjects

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1297]
**Description:**
It seems that after the change that came with the fix for https://github.com/SunstriderEmu/BugTracker/issues/882
there are some general issues with visibility that used to work before.
Some examples to look at are:
.go creature 74524
this one has a per-guid smartAI script that sets him invisible. It worked before the changes, now he and his friends are always visible.
Another example is the gameobject that is invisible by default and we set visible in a SmartAI script here:
http://dev.sunstrider.com.test/creature/entry/20555/smartai
in a script for this creature we set the near gameobject visible for a while and then invisible again
http://dev.sunstrider.com.test/smartai/script/2055500

I'm not sure what's causing this, but the goblins were invisible before those changes and I can't get the gameobject to be visible by setting it's visibility. Maybe those two are part of the same issue.

**Comment by kelno** [comment]
For the record, the set visibility action doesn't work for gameobjects. Those are usually set as invisible using a negative spawn time in DB.
To spawn them:
ACTION_RESPAWN_TARGET 
To despawn them:
ACTION_FORCE_DESPAWN

**Comment by kelno** [comment]
Okay I fixed the first case, it's actually a new bug unrelated to visibility.
Closing this issue unless there are other cases.
