### ISSUE TITLE
Creature spreading seems to not always spread creatures correctly (fanning)

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1300]
**Description:**

Creature spreading / fanning seems to not always spread creatures correctly. My theory is that when we first pull them they don't spread at all anymore but if we move around they seem to spread after they group for the second time.
Some pictures:
After pull: https://imgur.com/a/oUDVYAY
After moving around: https://imgur.com/a/2oJuSqK
Easy to observe in Karazhan or any place with a lot of creatures in one place
Location in the issue:
.go xyz -10988.952148, -1957.737427, 79.974304, 532

**Comment by Jerrythemagicdog** [comment]
Update: some creatures position themselves out of attack range https://imgur.com/a/s3UszsQ

**Comment by Jerrythemagicdog** [comment]
Seems resolved after changes.

**Comment by kelno** [comment]
Probly https://github.com/kelno/sunstrider/commit/71d3f38cffb25c3c8dbb2cdac14e93257f9bc7a5
