### ISSUE TITLE
Free-for-all looting in instances for players not present during boss kill.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1301]
**Description:**

When a player is outside the instance but in the raid group he should not be eligible for any loot if he wasn't present for the kill. 

**Current behaviour:**

Currently we're able to summon someone inside the instance (warlock summoning), set the loot to Free-for-all and have people pass and allow the summoned person to loot an item. It's working correctly for Master Looter where we are unable to give an item to him but FFA is not restricted (also should be). This allows for people from outside the raid to get items without killin g the boss.

**Expected behaviour:**
Free-for-all should be restricted how Master Looter is restricted.

**Comment by Jerrythemagicdog** [comment]
There was a weird situation that happened, we killed Gruul, the loot mode was set to Group Loot and I as the person with the loot permission (it said Loot:Skill) could not loot the creature. There also seems to be issues in the outside world with "You don't have permission to loot that" sometimes

**Comment by kelno** [comment]
Were you in combat with him at least?

**Comment by Jerrythemagicdog** [comment]
I was in combat because the boss does a "zone in combat" (I think I had GM turned off.)
The issue occured while we were looking at prediction and it was just one person running around and the other observing so it goes like this:


1. Have two players in an instance (Gruul for consistency) and Loot Mode set to Group Loot
2. Have one player do some damage to the boss while the other one idles
3. (RNG part) - have the already engaged player kill the boss (.damage was used) and in our case the Group Loot rolled the loot to the idle player and that resulted in him not being able to loot anything.

**Comment by kelno** [comment]
Fixed
