### ISSUE TITLE
[Rogue] Surprise Attacks are not working correctly

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1302]
**Description:**

The 41-talent point "Surprise Attacks" (32601) in Rogue's Combat talent tree make finishing moves not able to dodge and increase the damage of Sinister Strike, Backstab, Shiv and Gouge.

**Current behaviour:**

Currently all of the listed spells in the tooltip are affected by the talent and it's making them not able to dodge - Sinster Strike, Backstab, Shiv and Gouge. Could be that all of Rogue's abilities are affected.

**Expected behaviour:**

Only finishing moves should be not able to dodge.

**Comment by kelno** [comment]
Fixed by https://github.com/kelno/sunstrider/commit/465b41b0d9833624391e8b28b10877535916386d
