### ISSUE TITLE
Losing client control after teleporting out of arena

### ISSUE THREAD

**Issue by hufsa** [SunstriderEmu/BugTracker#1304]
After an arena game, one of my characters lost the "client control", preventing any movement. After the next game, the other character in the arena team also lost it. Both characters "rooted" in place, not responding to input movement.

**Comment by kelno** [comment]
Also c2e83a0176ed16e5c3f9d445d5518375684d334c

**Comment by kelno** [comment]
Events:

T1:

player A dies and gets rooted (and acks)
T2:
Player B dies
Arena ends
player A gets revived and root is removed (client does ACK this)
All players have their client control disabled
When player A leaves, Player::TeleportTo gets called but this line: SetUnitMovementFlags(GetUnitMovementFlags() & MOVEMENTFLAG_MASK_HAS_PLAYER_STATUS_OPCODE); still has the root in GetUnitMovementFlags for some reason.
