### ISSUE TITLE
[Rogue] Deadly Throw and focus interaction

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1306]
**Description:**

When casting Deadly Throw with other target in /focus it appears to do an animation and portion of the attack (but no damage) on the primary target we have selected while the damage goes to the /focus target correctly:
https://streamable.com/088sh

**Expected behaviour:**

Everything should hit the /focus target as that's the target of the spell

**Steps to reproduce the problem:**
0. Be a Rogue, .additem 35032
1. Make a macro "/cast [target=focus] Deadly Throw"
2. Get 2 targets (world creatures preferably), get combo points on one of them, while the other one is idle
3. Target the idle creature and use your focus macro.

**Comment by kelno** [comment]
Funny effect, I guess there is a triggered spell (maybe the interrupt component) not casted on the right target. If that's the case, the bug is not only visual but actually gamebreaking

**Comment by kelno** [comment]
gloves spell: 32748

**Comment by kelno** [comment]
This was a proc_flag issue
