### ISSUE TITLE
[Party] HP of party members is not displayed properly

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1308]
**Description:**

When partied the party member's HP is displayed as 1/1 after teleporting and not being in range.

**Expected behaviour:**
Should display the actual value of party member's HP regardless of distance (citation needed).

**Steps to reproduce the problem:**

1. Party up with a friend
2. Teleport to different places
3. The HPs display as 1/1

**Comment by kelno** [comment]
Needs more specific reproduce steps

**Comment by kelno** [comment]
Possible reproduce:
After a restart in a party of two, the second player to connect did see the first one greyed out with 1 hp.

**Comment by kelno** [comment]
Also after resurrects

**Comment by z5n** [comment]
unable to reproduce
