### ISSUE TITLE
Threat issue with Stealth

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1311]
**Description:**

When engaging a creature from Stealth it doesn't react and regenerates health. (it's not engaged)
To check easily you can .go crea 16100 and engage him from Stealth.

**Comment by kelno** [comment]
Related to https://github.com/TrinityCore/TrinityCore/commit/0e7c66cb4c7ff7d44e232d0b50703a48605ffd24

Fixed for now, waiting for a definitive trinity fix.

I think another issue with this was that a creature getting online again (from offline threat state) would trigger AI hook EngagementStart again.
