### ISSUE TITLE
No corpse on the ground when a warlock pet dies

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1312]
**Description:**
This is an issue that happens to Warlocks, maybe it's a general one that happens to any pet.
When we kill a warlock's Felhunter there is no corpse - it despawns immediately. There should be a corpse.

**Conditions under which the problem occured:**

1. Enter any arena as a warlock
2. Summon a Felhunter
3. Have the enemy kill the pet
4. No corpse, despawns immediately

**Comment by hufsa** [comment]
https://youtu.be/IAoe3akMZUE 12.50

**Comment by kelno** [comment]
There is a new issue now with warlock summons
If you use "Fel Domination" (18708) to resummon a pet immediately while the corpse is still there, the summoning fails
We should revive it in that case
Or rather I suppose, remove the old corpse
Then only summon the pet

**Comment by kelno** [comment]
Reversed for now, need a new fix for the original issue

**Comment by hufsa** [comment]
What happens when the "summoning fails"? Do we get a message? Does the spell cast finish or does it not cast at all?

**Comment by hufsa** [comment]
> **Conditions under which the problem occured:**
> 
> 1. Enter any arena as a warlock

Does this only happen in arena?

**Comment by kelno** [comment]
No message, cast finish, mana is used, and no pet is resurrected.
Also it's everywhere.

**Comment by Jerrythemagicdog** [comment]
Won't change.
