### ISSUE TITLE
[Warlock] Summoning any pet as a Warlock changes your class to Mage

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1313]
**Description:**
Summoning any pet as a Warlock turns your class into a Mage (changes your class completely).
This must be a recent regression as it did not happen earlier today when testing around 15:00.

Relogging does not help.

**Current behaviour:**

Summon any pet (tested with Felhunter and Felguard) - your class changes to Mage permanently, complete with talent tree.

 **rev. hash/commit:** 	
rev. 11873 (PTR)

**Comment by hufsa** [comment]
Hahahah

**Comment by kelno** [comment]
https://github.com/kelno/sunstrider/commit/d6d3a4fa#diff-5589ee47b3a7ad220cff105a8fe7eac3L19390
