### ISSUE TITLE
Creatures not pathing in part of Blade's Edge

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1314]
**Description:**

Some creatures like these ogres (https://streamable.com/4e1xc) are evading when aggroed for no apparent reason. Maybe it's terrain related. 
Here's a .debug threat of that creature:
https://media.discordapp.net/attachments/198064465562959873/606114495017910272/unknown.png?width=937&height=749

To fight the same ogres do:
.go xyz 2603 6310 -3 530

**Comment by kelno** [comment]
It's not related to one creature, no creature is able to path there.
`.mmaps path` will also fail there.

Note that it's not related to changing tile, all this happens in 20,27

**Comment by kelno** [comment]
Seems to be happening as well in Wintersprint 5954.053223, -4100.515137, 600.260193, 0.470390
(dragon there flies in the ground because it doesn't find any valid poly to path to)
