### ISSUE TITLE
Various blinks issue

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1315]
Kelno: Highjacking this for a list of issues:
- [x] (1) Blinking when back to a wall
- [x] (2) Blinking a bit up in the vmap height case
- [x] (3) Abuse in BE arena

Also fear can put players in such places as well, that's the exact same issue and same fix needed.

Old issue:
**Description:**
Blink seems to gain distance from current height of the Mage. It allows us to for example blink from the edge of the ramp on Blade's Edge Arena to the upper part of the bridge or Blink through the tomb on Ruins of Lordaeron. 
The way to consistently (or semi-consistently) reproduce all of these is to

1. .learn 1953
2. Jump right before pressing blink and move forward while in the air (one gentle "W" press).

Here are some examples of Blinks that should not be possible but are with the described "technique":
Blade's Edge Arena:
https://streamable.com/sy1fn
https://streamable.com/v0x0x

Ruins of Lordaeron:
https://streamable.com/lf3m0
https://streamable.com/a251c
https://streamable.com/4vd9y
https://streamable.com/c7hvr
https://streamable.com/wyqas

The general rule appears to be:
Blink shouldn't gain height from jumping and rather prioritize sticking the mage to the ground / terrain. It should obey Line of Sight checks and not blink players through pillars (one of the clips on RoL, or the pillar in starting rooms on RoL.) One of the clips also shows a blink "over" the tomb on RoL which should not be possible - the destination is not in line of sight.

**Comment by kelno** [comment]
Updated with https://github.com/kelno/sunstrider/commit/6f1da3b080d77a18be58613a4e3635d549da809c

**Comment by kelno** [comment]
Updated again

**Comment by Jerrythemagicdog** [comment]
It's very close to being perfect now.
In the album are some where Blink doesn't work or does a weird thing. 
When facing a wall or some texture that's elevated the Blink seems to jump you up and you can end up in some places where you can't get with movement:
https://imgur.com/a/yWySWrZ
Perhaps the problem is that blink "jumps" the player up and gives him extra height.
There also appears to be a consistent problem when being around walls, even with your back turned to the wall where it results in us not blinking.

Both of these issues can also be seen here: https://streamable.com/hxi9a

**Comment by kelno** [comment]
Thanks that's very clean

**Comment by kelno** [comment]
Updated again

**Comment by kelno** [comment]
Updated again, only the "Blinking to a non walkable point" is an obvious issue now

**Comment by Jerrythemagicdog** [comment]
Similar issue here with fear effect (later into the clip): https://streamable.com/usm7p

**Comment by kelno** [comment]
Closing and moving the "non walkable point"  thing to this issue:
https://github.com/SunstriderEmu/BugTracker/issues/1352
