### ISSUE TITLE
[Rogue] Vanish leads to a "invalid target" message in some cases while the buff is still active

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1316]
**Description:**

When using Vanish it applies a sanctuary effect on us to not take damage / be under the effects of incoming mid-air spells (fixed in https://github.com/SunstriderEmu/BugTracker/issues/119). It appears that the effect is not cleared for the entirety of the duration of the buff (spell 26889) 

1. .learn 26889 
2. .additem 5140 
3. .cast 26889
4. the enemy who tries to attack you will now get an "Invalid target" message (presumably because of the sanctuary effect)

**Comment by kelno** [comment]
Fixed
