### ISSUE TITLE
[Priest] Victim and Caster of Mind Control is not in combat upon leaving and entering MC

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1317]
**Description:**
The victim of Mind Control (10912) is not in combat upon leaving Mind Control (even very early like 2 seconds into the effect.) It's abusable in many ways for both parties.

**Expected behaviour:**

Entering Mind Control should set two players in combat, the timer should start ticking since the end of the effect on both parties.

**Steps to reproduce the problem:**

1. .learn 10912
2. Cast it on an enemy player
3. Nobody entered combat state at any point

**Comment by hufsa** [comment]
MC should put both players in combat and last througout the entire duration, combat timer start ticking when the MC effect wears off.

**Comment by kelno** [comment]
Fixed
