### ISSUE TITLE
Socketing Gems does not display them as active in the socketed gear piece

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1321]
**Description:**
When putting gems into gear and pressing "Socket Gems" to confirm the gems don't get applied visually (they do in reality) and further pressing of the button shows a warning message that Socketing them will destroy currently socketed gems.

**Expected behaviour:**

When pressing the button "Socket Gems" they should be applied. The warning message should show up if a player is replacing gems.

While it's only visual it can confuse players and definitely be an annoyance.

**Steps to reproduce the problem:**

1. Put gems into gear
2. Try to click "Socket Gems"
3. Gems are socketed (they work) but the visual display is wrong.

**Comment by kelno** [comment]
Tu be more clear, what's happening is that when we press "Socket Gems", the UI does not "lock" the gem in and grey out the button.
![image](https://user-images.githubusercontent.com/3866946/62831609-923ea600-bc22-11e9-97c9-043c523fb378.png)

**Comment by kelno** [comment]
I've no idea how it's supposed to be done.
Lich King does send SMSG_SOCKET_GEMS_RESULT which I suppose is supposed to handle this, but idk what to send on TBC.
I've checked at cmangos, windrunner and corecraft, it seems to me they all do the same thing we do since 2008.

**Comment by kelno** [comment]
Broken since https://github.com/kelno/sunstrider/commit/0824bfa2a419c1e0c4eb0cb96b8a6eecec890d5f

**Comment by kelno** [comment]
FIXED
