### ISSUE TITLE
[Warlock] Imp with Phase Shift active is affected by SD

### ISSUE THREAD

**Issue by ghost** [SunstriderEmu/BugTracker#1322]
**Current behaviour:**
* Summoning Disorientation remains on the pet after being resummoned (affects FelDom summons).  
* Imp with Phase Shift active is affected by SD.

**Expected behaviour:**
* SD should not continue for the remaining duration on the resummoned pet.
* Imp with Phase Shift active should be immune to SD.  
> Battleguard on 2008/03/03 (Patch 2.3.3)
> Imps are affected as well. However, if they're under the effects of Phase Shift, they won't suffer from the stun.

 **rev. hash/commit:** 	
Sunstrider rev. 12020 (0686b9fb2e4e) 2019-08-16 15:53:53 +0100 (dev branch) (Unix, RelWithDebInfo, Static)

**Comment by kelno** [comment]
Fixed the first issue

**Comment by hufsa** [comment]
Fixed other issue about phase shift
