### ISSUE TITLE
[Hunter] Multi-Shot

### ISSUE THREAD

**Issue by ghost** [SunstriderEmu/BugTracker#1323]
**Current behaviour:**
Multi-Shot not working like a chain-type ability. Seems to only check the main target for jumps.

**Expected behaviour:**
Barroth said:
> I think the calculation is based on the multishots Target instead of the caster.
http://www.youtube.com/watch?v=dKx0KsCNBH4#t=452
This cast has quite a big angle ~ 45 degree I'd say, which, at 41 yards range and if it works like a cone, means it could hit enemies which are 30yards away from each other.
It probably should be area based around the Maintarget, like:
cast at maintarget, check circle area with 10yards radius around that target. if sth is found the closes one is the 2. target and then it checks the circle area(10yards) around that target.  

More info:
[cc-bug626](https://github.com/ccshiro/cc-buglist/issues/626)
[cc-bug25](https://github.com/ccshiro/cc-buglist/issues/25)

**Steps to reproduce:**
* Stand at max range from the closest target dummy, with the other two behind it, making sure those are out of MS range.
* Fire Multi-Shot at the closest dummy (the one in range).
* Observe as MS jumps only to the 2nd dummy.

 **rev. hash/commit:** 	
Sunstrider rev. 12024 (542eb5de99e5) 2019-08-16 18:06:04 +0100 (dev branch) (Unix, RelWithDebInfo, Static

**Comment by kelno** [comment]
To dev: 
Look in Spell::SearchChainTargets there is already something about that for melee spell, maybe we just need to expand it.

**Comment by woiwoz** [comment]
But I don't think DynamicObject has anything to do with that.LOL

**Comment by kelno** [comment]
No it's not related

**Comment by earthworm-jim** [comment]
Another thing to note about MS:

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/4217
