### ISSUE TITLE
[Hunter] Snake Trap

### ISSUE THREAD

**Issue by ghost** [SunstriderEmu/BugTracker#1324]
**Current behaviour:**
Snakes attack only hunter's target and only if the hunter is attacking that target.

**Expected behaviour:**
> When the trap is activated, snakes start to attack the nearest targets. It is possible that some snakes will attack one target and some will attack other. After the target is dead, snakes attacks next target (in close range).

> Snakes have a surprisingly large aggro radius and should generally only be used when you know that either their 15 second effect will not outlast the target mob(s) or when you have a lot of room to work. If there are any snakes left after you kill your primary target, and there is another valid target within ~23 feet, they will run off and attack them for you. 

> Snakes themselves have ~15 feet range, e.g. they will go for closest targets in 15 feet, plus they have ~8 feet spit radius. 

[WoWWiki Aug 19, 2008](https://wowwiki.fandom.com/wiki/Snake_Trap?oldid=1578021)

 **rev. hash/commit:** 	
Sunstrider rev. 12028 (f0445535c296) 2019-08-16 19:49:23 +0200 (dev branch) (Unix, RelWithDebInfo, Static)

**Comment by z5n** [comment]
closing in favor of #5178
