### ISSUE TITLE
Deep wounds 

### ISSUE THREAD

**Issue by liderer** [SunstriderEmu/BugTracker#1326]
Problem :  warriors tailent "Deep wounds"
Every critical strike refresh  deep wounds "stacks" , and increased damage .  Should  just replace previous effect. 
Just spam hamstring , stack this tailent to 650 damage per tick . 
https://imgur.com/ysfUbEC

**Comment by Jerrythemagicdog** [comment]
Thanks, it indeed seems to be building up.

**Comment by kelno** [comment]
Fixed
