### ISSUE TITLE
Grounding totem 

### ISSUE THREAD

**Issue by liderer** [SunstriderEmu/BugTracker#1327]
1)  while me CCed , "aura redirect effect"  fades (sometimes) , if not fades he anyway full ignore enemy spells . 

       https://youtu.be/I7dWzlVm07U after priest fear me effect fades instant 

2) https://youtu.be/wQP2LEcgid8  wlock cast full pack dots , grounding ignore this 

3) ignore some spells like " freezing trap" .. ~ 7-8 sec after i am in trap , effect is returning but anyway ignore all enemy spells.
    https://youtu.be/K1fpMMYa3ds

**Comment by kelno** [comment]
Fixed
