### ISSUE TITLE
Lightning Shield procs 

### ISSUE THREAD

**Issue by liderer** [SunstriderEmu/BugTracker#1328]
Should proc after any "negative effect " doesnt matter , deal he damage or no.   In current moment , proc only after taken damage (water shield with same mechanic works fine)

One charge was consumed when mage casted poly (no dmg cuz he had ice barrier)
https://youtu.be/RBKOMclpmFs?t=57s etc same negative spells : 

1) Curse of tongues triggered shield and lock recieved 400 dmg
https://youtu.be/JFrsPsU6AA8?t=3m50s

2) Prist fear trigered shield and hit for 494 dmg
https://youtu.be/JFrsPsU6AA8?t=55s 

3) Viper sting triggered shield and hitted hunter for 508
https://youtu.be/RTuy2wSodfA?t=30s

4) One charge consumed sham is affected by warrior fear and hes hitted for 500 dmg
https://youtu.be/FlnUhUqVTKE?t=2m19s

5) One charge consumed when lock casted corruption and got hit for 402
https://youtu.be/RBKOMclpmFs?t=3m20s

**Comment by kelno** [comment]
Fixed

**Comment by Jalapan** [comment]
https://www.youtube.com/watch?v=0q-p4W3dJcM

Here is video proof of periodic auras should not affect water/lightning shield.

Look at the shamans stack of watershield when netherspite does aura dmg, nothing happends.
