### ISSUE TITLE
Healing stream totem

### ISSUE THREAD

**Issue by liderer** [SunstriderEmu/BugTracker#1329]
http://tbc.cavernoftime.com/spell=25567

Healing stream totem - not affected bonus healing coefficient 

https://imgur.com/rJw5WO0   without tailents , heal like on tooltip: 18 per tick (check combat log) 

Should affected healbonus coefficient - 4.5% per tick , also should affected shaman tailent Purification . Purification works , but cant test atm correct or no . 

https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=1549176 

https://web.archive.org/web/20080611233345/http://elitistjerks.com:80/691947-post839.html

**Comment by kelno** [comment]
Fixed
