### ISSUE TITLE
 [Nature's Guardian] 

### ISSUE THREAD

**Issue by liderer** [SunstriderEmu/BugTracker#1332]
http://tbc.cavernoftime.com/spell=30886 

Problem . this talent does not work correctly . Should heal 10% of my max HP , with internal cooldown 5 sec . Proc chance so low (not looks like 50%) . 

Proof : https://youtu.be/04AlNll8lBg 

There was no cooldown during the start of the test , for the entire time that the rogue beat me, taking into account the cooldown in 5 seconds, it should have proc ~ 3 times

**Comment by kelno** [comment]
Cooldown was 30s and is now 5s. The chance seems to be correct.

**Comment by Jerrythemagicdog** [comment]
fixed
