### ISSUE TITLE
[Hunter] Snake trap

### ISSUE THREAD

**Issue by Donell70** [SunstriderEmu/BugTracker#1335]
**Description:**
Melee hits from snake traps.

**Current behaviour:**
All snakes melee hits always miss when they attack enemy.

**Expected behaviour:**
Snakes melee hits must have basic normal melee mechanic.

"Out of the snakes, four vipers appear, hitting for approximately twice as much as the venomous snakes. The melee damage of the snakes being very low, the poisons are the main intent of the ability." https://wowwiki.fandom.com/wiki/Snake_Trap

**Comment by Jerrythemagicdog** [comment]
Thanks!
They had no melee damage.
Fixed.
