### ISSUE TITLE
[Hunter] Frost Trap Entrapment

### ISSUE THREAD

**Issue by earthworm-jim** [SunstriderEmu/BugTracker#1336]
**Current behavior**
Entrapment can only proc when Frost Trap is triggered.

**Expected behavior**
> This talent is strongest when used with frost trap, as each "pulse" of the traps effect can trigger entrapment and they occur once per second. Previously, this meant that once the target became entrapped, they would likely remain entrapped for the entire duration of the frost trap. (25% chance to entrap, 4 chances to re-entrap over 4 seconds.) However, entrapment is now affect by diminishing returns. This still means that a frost trap will generally entrap a foe for 7 seconds instead of 4. Anyone standing on a frost trap for more than a few seconds will eventually become entrapped.

source: [WoWWiki](https://wowwiki.fandom.com/wiki/Entrapment?oldid=1368007)

Sunstrider rev. 12109 (5925fcaecee6) 2019-08-19 17:52:32 +0100 (dev branch) (Unix, Debug, Static)

**Comment by Jerrythemagicdog** [comment]
To dev:
The initial idea was that the secondary effect of Frost Trap Aura (https://kelno.allumeciga.re/suntools/external/spellinfo/?id=13810) is supposed to handle the proc of Entrapment (leads to dummy effect).
But other traps that are supposed to proc Entrapment (Immolation Trap, Frost Trap, Snake Trap, Explosive Trap) don't have that secondary effect: 
Immolation Trap: https://kelno.allumeciga.re/suntools/external/spellinfo/?id=13797
Snake Trap: https://kelno.allumeciga.re/suntools/external/spellinfo/?id=45145
Explosive Trap: https://kelno.allumeciga.re/suntools/external/spellinfo/?id=27026

**Comment by kelno** [comment]
We need to make a difference between trap activation then subsequent application.
If I understand this correctly frost trap is the only one being able to proc later than trap activation? If that's the case the secondary effect of 13810 idea still seems to hold.

**Comment by kelno** [comment]
Fixed
