### ISSUE TITLE
Feign Death resets only a few creatures from the pack.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1337]
**Describe the bug**
As in the title.

**To Reproduce**
1. Pull a pack of creatures in an instance.
2. Feign Death when they're about to reach you.
3. Some of them reset, some of them don't.

**Expected behavior**
All of them should reset.

**Comment by kelno** [comment]
Couldn't reproduce, need moar details
![image](https://user-images.githubusercontent.com/3866946/63652376-f0f63a80-c75f-11e9-8f82-a372e20dc255.png)
Maybe my pack was too small?

**Comment by hufsa** [comment]
Could this be resist-related?

**Comment by kelno** [comment]
Don't think we have FD resist implemented in any way

**Comment by hufsa** [comment]
> Don't think we have FD resist implemented in any way

Okay, let's start by fixing that issue then?

**Comment by kelno** [comment]
It's not going to help with this one, and seems like a very low prio

**Comment by Jerrythemagicdog** [comment]
This was due to packs not linked correctly in Hellfire Ramparts. 
It's gotta be fixed case per case. After recent formation additions all the known cases should be fixed.
