### ISSUE TITLE
Maim (Druid spell) is ignored and broken by pet attacks.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1338]
**Describe the bug**
A spell like Maim (22570) should order any nearby pet to stop attacking similar to Rogue's Gouge or Blind

**To Reproduce**

1. Have a pet hitting a target
2. Maim the target
3. Pet will break it ignoring the Maim.

**Comment by hufsa** [comment]
Afaik Maim is not considered "breakable by cc" by the core, because it should only break on direct damage.

**Comment by Jerrythemagicdog** [comment]
This is indeed a weird one and I'm not sure what the correct behavior is.

**Comment by kelno** [comment]
Maybe we can go full game designer™ on this one and assume it should not be broken.

**Comment by Jerrythemagicdog** [comment]
It would make sense, especially that the tooltip says "Any directly damaging attack will revive the target."

**Comment by kelno** [comment]
Proooobably fixed, testme

**Comment by Jerrythemagicdog** [comment]
Fixed
