### ISSUE TITLE
Fear Ward gets consumed when hit by a Fear while affected by Cyclone or Cloak of Shadows

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1340]
**Describe the bug**
Fear Ward (6346) gets consumed even though the effect is resisted or immuned by another effect. 

**To Reproduce**

1. Cast Fear Ward on player X
2. Cast Cyclone / Cloak of Shadows on player X
3. Cast fear on player X
4. Fear Ward gets consumed even though the Fear can't land.

**Comment by kelno** [comment]
Fixed
