### ISSUE TITLE
Players disconnecting and reconnecting in Arena Preparation appear as hostile to their teammates.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1341]
**Describe the bug**
If a player disconnects and reconnects, or is in another arena while accepting a queue for the next arena he will become hostile to his teammate.

**To Reproduce**
Scenario 1:
1. Accept an arena queue
2. Disconnect
3. Reconnect to the arena
4. You're no longer in party with your teammate and you're hostile to them

Scenario 2:
1. Be in arena
2. Be slow to leave and have an overeager partner who wants to play all the time
3. The queue pops up while you're still in the last arena
4. Accept the match.
4. You're now hostile to your teammate.

**Comment by hufsa** [comment]
Both scenarios should be impossible.

In other words, you should not be able to reconnect into an arena game if you disconnect. You should not be able to q if any party member is already in arena.

**Comment by Jerrythemagicdog** [comment]
> In other words, you should not be able to reconnect into an arena game if you disconnect.

Why not if the character hasn't died / it's still the starting room? This is not a bad quality of life change.

**Comment by blblblaz** [comment]
if we can make it work properly i say implement it! if its scuffed like now i say remove it! not big priority currently this is some shit for when the server is alrdy out

**Comment by hufsa** [comment]
Sure, if it's fail proof.
If we want to spend time developing stuff that ensures the character that disconnects stays targetable and "in melee range", sure. Feels very low prio mainly because of lots of testing required and for little to no value imo.

**Comment by kelno** [comment]
Still have to develop something to disallow reconnecting in arena though and it might not be easier than the probable one line fix for this

**Comment by hufsa** [comment]
If you believe this is a one line fix then I see no reason to not do that instead.

**Comment by kelno** [comment]
We still have to fix it for bg anyway and I believe it's the same bug

**Comment by kelno** [comment]
Fixed
