### ISSUE TITLE
Killing Totems puts the Shaman in combat.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1345]
**Describe the bug**
Killing a Totem puts the Shaman in combat (restarts combat timer).
Attacking and killing totems should not put the Shaman in combat, combat inherited from summons should be restricted to pets with a pet bar.

**To Reproduce**
1. Summon a Totem (.additem 5176 .cast 25533)
2. Kill the Totem as an enemy player
3. Shaman will be in combat as a result.

**Comment by kelno** [comment]
Fixed
