### ISSUE TITLE
Shadow Sight does not remove Stealth.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1346]
**Describe the bug**
Shadow Sight (34709) when applied on the player should remove Stealth or other Invisibility related effects. Currently not the case. 

To dev:
Gameobject template id: 184663
Faction for us right now is 0 which seems wrong, most cores have 114 (Treasure) but it seems unrelated to the problem (Stealth is still not removed with that). 
The spell is also "made" negative in SpellInfo (only affecting the display though, perhaps missing an attribute.)

**Comment by kelno** [comment]
Fixed
