### ISSUE TITLE
Cloak of Shadows removes Flare debuff.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1349]
**Describe the bug**
Cloak of Shadows (31224) removes Flare (1543) debuff. 
Also if the player enters a flare while stealthed + CoS, flare has no effect (it should).

To dev: This is partially solved by a hack - changing the schoolMask to physical, but it doesn't handle the case where an already Stealthed Rogue with CoS enters a Flare.

**Comment by kelno** [comment]
Fixed
