### ISSUE TITLE
Warlock pet damage is too high.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1350]
**Describe the bug**
Warlock's pet damage is too high across all pets. The scaling with master's spell damage or level might be too high. It appears that currently they do double the damage compared to the expected one.

**Comment by hufsa** [comment]
Are we talking about the melee damage here?

**Comment by Jerrythemagicdog** [comment]
Yes, melee damage.

**Comment by blblblaz** [comment]
as far as i can see its the base damage of pets that is too high

https://wow.gamepedia.com/index.php?title=Felhunter&oldid=1556620
https://wow.gamepedia.com/index.php?title=Succubus_(warlock_minion)&oldid=1602317
https://wow.gamepedia.com/index.php?title=Imp&oldid=1575594
https://wow.gamepedia.com/index.php?title=Felguard_(warlock_minion)&oldid=1571875

compared to the stat tables in these links our pets have more than double the base damage:
voidwalker has 246-351
felhunter has 227-351
succubus has 341-442
felguard has 319-443
imp has 235-315
(all stats untalented on naked lvl 70 undead char)

also the other stats of pets like intellect, stamina, spirit, agility, strength pretty much exactly coincide with those stat tables, only damage and in some cases armor are different

**Comment by hufsa** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/53#issuecomment-448635678

**Comment by kelno** [comment]
Base damage is updated, scaling untouched for now

**Comment by Jerrythemagicdog** [comment]
Fixed since then.
