### ISSUE TITLE
Fear and blinks can put players in places where they normally can't stand and result in them falling down / slipping off.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1352]
**Describe the bug**
Fear can put players in places where they normally can't go themselves (because the terrain would be too steep).
For example: https://www.youtube.com/watch?v=DMaCg_US5pU 12:40

**Comment by Jerrythemagicdog** [comment]
Related: https://github.com/SunstriderEmu/BugTracker/issues/1315

**Comment by kelno** [comment]
Okay I'm closing this one and using the other one, the fix is exactly the same for both.

**Comment by kelno** [comment]
Closing the other issue and moving the "blink" part here too, since it's the exact same issue and same fix.

**Comment by Jerrythemagicdog** [comment]
Possible improvements to Shadowstep as well here:
https://streamable.com/83r31

**Comment by kelno** [comment]
Should be fixed with 89306d5966137a4deba583eeec01ec359fbd8247 \o/

**Comment by kelno** [comment]
Fixed for blink as well
(applied with next server udpate)
