### ISSUE TITLE
Players can get permamently rooted when Blinking and being Charged at the same time (need reproduce steps).

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1355]
**Describe the bug**
Players get permanently rooted after getting charged (or Intercepted - 25275) when using Blink (1953). 

**To Reproduce**
Not 100% sure about the reproduce steps but:
1. Cast Blink (1953)
2. While Blinking and the Blink buff is active get Intercepted (25275)
3. The player becomes rooted forever after that. 

Worth noting that this only happened in the Duel Zone and has not been seen (to my information) in Arena.

**Comment by kelno** [comment]
Probly fixed
