### ISSUE TITLE
Players are displaced and appear to be not where they are.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1356]
**Describe the bug**
It appears that the delay between where the player actually is vs. where he is displayed to be for the observing player is too long and causes many issues especially in PvP situations (https://clips.twitch.tv/GentleBadButterShadyLulu).

The delay can also be seen locally with 2 clients open and running across the screen.

**Comment by hufsa** [comment]
Should be resolved. Needs testing.
