### ISSUE TITLE
AoE Range on persistent area auras seems too big for Flare

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1357]
**Describe the bug**
The AoE Range on spells appears to be too big on spells like Flare (1543) especially. The range reaches far further than 10 yards.

**Comment by kelno** [comment]
We need to compare the visual in our side and see if it matches with retail. (Maybe the range is fine and the visual is not)

**Comment by kelno** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/556 actually
