### ISSUE TITLE
Pets told to cast an ability while not in line of sight do not move in line of sight to cast that spell. 

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1358]
**Describe the bug**
Pets such as Felhunter (spell 691) do not move in line of sight or start moving towards the target when ordered to cast a spell (for example Devour Magic on a friendly target to dispel some effect.)

**Comment by kelno** [comment]
To confirm: Should the behavior be:

When I cast a spell from the pet it should always also enable auto attack?

I highly doubt there is a complicated logic such as "go into LoS, cast the spell then go back to whatever you were doing".

**Comment by hufsa** [comment]
Good question! I'll try to find information about this.

**Comment by Jerrythemagicdog** [comment]
About this, we have confirmed with @hufsa that there is no history of commands for the pet and the behavior of the pet after casting a spell on a target other than current depends on the set mode (passive / aggressive / defensive) and selected command (follow / attack / stay).

Scenario 1:
1. Pet is on "passive" mode and the selected command is follow
2. We order it to cast a spell on the enemy or teammate that's far / out of los
3. Pet runs to cast the spell and comes back to the owner

Scenario 2:
1. Pet is already attacking a target (in passive mode)
2. We order it cast a spell on the enemy out of range / los
3. The pet does that and switches the target of attacks
If the target is friendly the pet comes back to the owner.

Scenario 3:
1. Pet is not attacking a target and is in aggressive mode with follow selected
2. Pet is told to cast a spell on a target out of range / los
3. Pet runs to cast the spell and if the target is an enemy starts attacking it
Similar thing was observed when the pet was on defensive mode.

**Comment by kelno** [comment]
Would I be correct if I apply the same logic to "out of range" cases in addition to the "out of LoS"?

**Comment by Jerrythemagicdog** [comment]
We should try and see but it seems that they are identical / similar.

**Comment by hufsa** [comment]
Yes. Out of LoS and out of range behavior is identical. 

Scenario three is identical in both defensive and aggressive mode.

**Comment by kelno** [comment]
Did a thing, need testing. Updated the PTR.

**Comment by Jerrythemagicdog** [comment]
Seems to be working really well, the only weird thing is that when we order the pet to cast a spell the GCD for that spell seems to be triggered at the moment of issuing the command rather than when the spell is actually casted.

**Comment by kelno** [comment]
Fixed

**Comment by Jerrythemagicdog** [comment]
Scenario 1 is not functioning correctly anymore, if the pet is next to the owner and in "Passive" mode and we order it to cast a Spell Lock on a target (doesn't matter focus or main target) it will go on to attack that target instead of just casting the Spell Lock.
