### ISSUE TITLE
Slows are not correctly removed when leaving the arena (for example Crippling Poison)

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1359]
**Describe the bug**
It appears that slow effects such as Crippling Poison are persisting through the Arena after leaving.

1. Apply Crippling Poison on a target
2. The match ends
3. Leave the match with Crippling Poison
4. The target is slowed.

Just to make it clear: The debuff itself was removed but the movement speed alteration wasn't.
Can be fixed with the latest movement changes.

**Comment by kelno** [comment]
Is this still happening? We couldn't reproduce it.

**Comment by kelno** [comment]
Fixed until actually not fixed
