### ISSUE TITLE
Serpent Sting and Cloak of Shadows interaction.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1361]
**Describe the bug**
Cloak of Shadows (31224) should remove Serpent Sting (27016) (it currently does) but it should not prevent the Rogue from being hit by Serpent Sting (27016) while under the effects of Cloak of Shadows (31224).

**To Reproduce**
1. Cast Serpent Sting (27016) on a target
2. Cast Cloak of Shadows (31224) as the target
3. Correctly removes Serpent Sting
4. Try to reapply Serpent Sting.

**Comment by kelno** [comment]
Research here: confirm the "not prevent from being hit" part is actually supposed to work that way.

**Comment by Marhaba0** [comment]
judgement of justice also goes through cloak but i'm not sure if it is supposed to

**Comment by kelno** [comment]
Maybe SPELL_AURA_MOD_ATTACKER_SPELL_HIT_CHANCE is not supposed to affect ranged weapon spells

**Comment by kelno** [comment]
Fixed
