### ISSUE TITLE
Creature spells and abilities can crit on players

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1362]
**Describe the bug**
Creature spells and abilities can crit on players.

**Expected behavior**
Creature spells and abilities should not be able to crit (unless explicitly stated in the spell - very rare cases, if any at all).

It happened with the Sharpshooters in Old Hillsbrad Foothils and their Multi Shot ability (dealing Arcane damage).

**Comment by kelno** [comment]
Fixed with https://github.com/kelno/sunstrider/commit/0c7c3e7693447732fd6a5d55364ef82801a0e52c
