### ISSUE TITLE
[Hellfire Ramparts] [Heroic] Vazruden the Herald, dragon bugged in middle of platform

### ISSUE THREAD

**Issue by Marhaba0** [SunstriderEmu/BugTracker#1364]
**Describe the bug**
The dragon Nazan becomes stationary in the middle of the platform if a player casts a dot or debuff spell on Vazruden the Herald when he is descending down to the platform. this happens at the start of the boss fight, The dragon remains in its spot casting fireball but doesn't move .

**To Reproduce**
1. Cast Serpent Sting/Curse of Elementals/debuff or dot spell on Vazruden the Herald when he is descending to the platform

Please ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://www.wowhead.com/npc=17307/vazruden-the-herald
https://www.wowhead.com/npc=17536/nazan

**Expected behavior**
It should be flying overhead, circling the platform while casting fireball, then descend onto the platform when Vazruden is at 40% hp 

**Screenshots/videos**
my vod/twitch clip on ptr realm with this bug: https://www.twitch.tv/videos/470442338?t=31m28s

**Additional context**
https://www.wowhead.com/npc=17536/nazan#comments:id=27143
https://youtu.be/cr9BSathz4I?t=167

**Comment by Jerrythemagicdog** [comment]
To dev: make Vazruden the Herald immune to PC while he's descending after being called down by killing the Sentries

**Comment by artieau** [comment]
Seems good now, didnt see this happen

**Comment by Jerrythemagicdog** [comment]
Thanks!
