### ISSUE TITLE
[Blood Furnace] [Heroic] Keli'dan the Breaker no channel spell/immunity in 'Fire Nova'

### ISSUE THREAD

**Issue by Marhaba0** [SunstriderEmu/BugTracker#1365]
**Describe the bug**
Last boss in heroic BF has no channel animation/buff when he casts Fire Nova. He pulls the group toward him when he says 'Come closer... and BURN!' but has no immunity and channel time for 5 seconds, the spell goes off anyway while he is attacking the highest aggro target.

Please ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

https://www.wowhead.com/npc=17377/kelidan-the-breaker
https://www.wowhead.com/spell=30940/burning-nova

**Expected behavior**
He should pull the group towards him and become immune for 5 seconds then fire nova should go off

**Screenshots/videos**
https://www.twitch.tv/videos/470459941?t=00h23m06s

**Additional context**
https://youtu.be/_YviwaQPD-8?t=229

**Comment by Jerrythemagicdog** [comment]
Fixed a couple of days ago, was working correctly yesterday when you guys did it. Thanks for the report though!
https://github.com/kelno/sunstrider-scripts/commit/b5d04ba558076e40344aad6c425dd4777b3b5713

**Comment by kelno** [comment]
Me missing the correct visual spells

**Comment by Jerrythemagicdog** [comment]
Turns out we had the correct spell, just for some reason it requires a Soul Shard and was failing.
Thanks for the sources, fixed!
