### ISSUE TITLE
[Blood Furnace] [Heroic] Patrol missing

### ISSUE THREAD

**Issue by Marhaba0** [SunstriderEmu/BugTracker#1366]
**Describe the bug**
Shadowmoon Warlock and Felguard Brute are idle in corner not patrolling, we were able to skip them easily :D

**Expected behavior**
They should be on a patrol path, stopping momentarily when the warlock buffs felguard:
https://youtu.be/iMJ-uH5X7Yk?t=349

**Screenshots/videos**
vod clip: https://www.twitch.tv/videos/470459941?t=00h18m41s

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Fixed
