### ISSUE TITLE
[Paladin] Righteous Defense can be dodged by creatures and doesn't have an effect on caster creatures while they're casting.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1367]
**Describe the bug**
Righteous Defense (31789) should not be dodgable by enemy creatures. It's a spell that should not be dodgable.

To dev:
For some reason it had dmgClass set to 2. The only thing to check is if it's still affected by melee hit rating correctly (not spell hit rating).

**Comment by Jerrythemagicdog** [comment]
Fixed

**Comment by Jerrythemagicdog** [comment]
https://github.com/kelno/sunstrider/commit/2f42be878f2c886872bba0fb0c5c2db7a25e6709

**Comment by kelno** [comment]
caster creatures don't change target

**Comment by kelno** [comment]
Fixed
