### ISSUE TITLE
[Paladin] Seal of Righteousness can crit when the target has Judgement of Crusader applied (with Improved Seal of the Crusader). 

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1368]
**Describe the bug**
Seal of Righteousness (27156) has an attribute that does not allow it to crit. That part works correctly except when we apply Judgement of the Crusader (27159) on the enemy with the talent Improved Seal of the Crusader (20337).

**To Reproduce**
1. Get Improved Seal of the Crusader (Retribution tree)
2. Apply Judgement of the Crusader on the target with the talent skilled
3. Cast Seal of Righteousness and observe that your Seal can crit.

**Expected behavior**
Seal of Righteousness swings should not be allowed to crit. Only Command and Blood should.

**Comment by kelno** [comment]
Fixed with https://github.com/kelno/sunstrider/commit/3830ec6cd32157a37233f2f1e2791d30b9ee5ff6
