### ISSUE TITLE
[Rogue] Vanish buff gets removed by Distract.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1369]
**Describe the bug**
Vanish buff (26888) gets removed by Distract (1725). 

**To Reproduce**
1. Cast Vanish (26889)
2. Get Distracted (1725) by an enemy
3. The buff disappears making the player lose all the bonus Stealth levels.

**Expected behavior**
It should not remove the Vanish buff.

**Comment by kelno** [comment]
Fixed
