### ISSUE TITLE
[Karazhan] The Wizard of Oz fight bugs

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#137]
**Description:**

The Wizard of Oz fight is bugged, at the start all the NPCs do their RP events at once (should be in some intervals)
After killing Tinman, Dorothy, Tito, Scarecrow and Roar - The Crone (18168) spawns but does not do anything and despawns. 
The exit door does not open and it's impossible to progress.

**Comment by Jerrythemagicdog** [comment]
Here's a video from retail with the correct RP events and the order in which the NPCs engage with the players: https://youtu.be/08CE7FU4H-M?t=400

**Comment by kelno** [comment]
Opera was reworked since.
https://github.com/kelno/sunstrider-scripts/commit/2fca74fe3e2cac9a448dfef6fcb8796d2d09a65d#diff-f19aee655c2b918d6373a5d2fe260e6a
