### ISSUE TITLE
[Rogue] Using Vanish while already in Stealth does not grant the Vanish buff.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1370]
**Describe the bug**
Casting Vanish (26889) while already in Stealth does not grant the Vanish buff (26888) to the Rogue.

**To Reproduce**
1. Cast Stealth on a Rogue
2. Cast Vanish (26889)
3. The buff does not get applied.

**Expected behavior**
The Rogue should gain the buff.

**Comment by kelno** [comment]
Fixed
