### ISSUE TITLE
Player debuff timers on targets are not updated on visibility update.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1371]
**Describe the bug**
Player debuff timers are not correctly updated on visibility update.

**To Reproduce**
1. Player X applies a debuff on a target as  on player Y( let's say Expose Armor)
2. Player Y enter stealth then leave Stealth
3. Player X can no longer see the debuff timers of his own spells on player Y.

**Comment by kelno** [comment]
Fixed
