### ISSUE TITLE
[Paladin] Seal of Righteousness does not benefit from Judgement of Crusader bonus Holy Damage.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1372]
**Describe the bug**
Seal of Righteousness (27156) swings do not benefit from Judgement of the Crusader (27159) bonus Holy Damage.

**Expected behavior**
The SoR attack swings should benefit from the Judgement of the Crusader bonus.

To dev:

Spell 27156 (SoR) has an override with "0x20000000 | SPELL_ATTR3_NO_DONE_BONUS" with a comment saying "Added SPELL_ATTR3_NO_DONE_BONUS, calculation is done in the script" which doesn't handle the JoC case in the script and prevents it from scaling correctly (maybe for many other effects too).

**Comment by kelno** [comment]
Fixed
