### ISSUE TITLE
[Item][Spell] Spider's Kiss (Fang of the Crystal Spider + Venomspitter)

### ISSUE THREAD

**Issue by ghost** [SunstriderEmu/BugTracker#1375]
**Describe the bug**
Spider's Kiss is subject to DR.  
It can be removed by Blink, Vanish etc.

**Expected behavior**

> By versusvs (1,562 –  1·1·10)  on 2009/01/19 (Patch 3.0.3)
you have no idea just how lucky you are to get both in 1 run,
its like a 1/10 x 1/10 chance to get fang of the crystal spider, then some stupidly low chance to get the venomspitter.
gratz, just for clarification on the proc from set:
**the '10 second net' is a POISON proc, meaning vanish(possibly other remove impairment effects as well) will not remove it (last time i checked) also there is no internal cooldown as far as i can tell and there are NO diminishing returns.**
all in all the proc is pretty awesome and i consider it one of the best in the game
Last edited by versusvs on 2009/01/19 (Patch 3.0.3)  

---

> From Thottbot By KaaBoom on 2006/06/19 (Patch 1.10.2)
Subject: "This set is good for PVP until you get an epic dagger."Yeah i have this set. and i also have the barmen shanker and the dagger that the baron drops off in strat dead (the bonescraper). Ill tell you now the damage is ok, i am a main DPS rogue in my guild and this set is ok. But the real benefit for this set is in PVP.
As a 60 rogue This item set is beautiful. **Nothing breaks the immobilisation proc. Mages who blink will blink but then still stay immoblised after they finished blinking. Druids who change forms still stay imobilised.** This proc allows me to beat up on flee casters easily. I have the dagger in my main hand and the mace in my off hand and the individual procs dont happen often but the combo proc happens all the time.
For those rogues who want a nice set for pvp try this set. the DPS isn't the greatest but the imobilisation proc is a beauty.
Saying this though When i eventually get an epic dagger like the felstriker or the lobotimiser then i will put this set in my bank and go and get the bonescraper out again. This is because that dagger is good as an off hand weapon but the DPS of an epic dagger is superior to this set.

**Comment by Jerrythemagicdog** [comment]
Thanks, we're keeping it this way.
