### ISSUE TITLE
[Warrior] Spell Reflect has no effect against Freezing Trap

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1378]
**Describe the bug**
Spell Reflection (23920) has no effect against Hunter's Freezing Trap (1499).
It should consume the trap (and the Spell Reflection buff) and not have any effect on the warrior or the Hunter.

**To Reproduce**
1. Put a Freezing Trap down as a Hunter (1499)
2. Use Spell Reflection (23920)
3. Run into the trap

**Comment by kelno** [comment]
Bug actually was: the reflect is not consumed even if it prevents the gob spell.
Fixed
