### ISSUE TITLE
Mind Soothe/Mind Vision  removes Spell Reflect/grounding totem 

### ISSUE THREAD

**Issue by liderer** [SunstriderEmu/BugTracker#1379]
Mind Soothe https://www.tbcdb.com/?spell=25596

Problem : 
this priests spell  removes spell reflect/grounding totems effects -what should not be . (spell have a  physical school) 

How it should work:

1 )its tbc july 2008 - s4 on retail :

www.arenajunkies.com/topic/28105-concerning-spell-reflect
"as far as i know mind soothe does not work on spell reflect "
"Yeah sorry about that, it gets reflected but doesn't eat the debuff. dam "
"mind soothe doesnt work on spell reflect for quite a while now because its a phisical"

2)next proves past tbc ,but about tbc :

www.arenajunkies.com/topic/70334-interesting-priest-tricks-and-info/page-4

" in season 3 & 4, mind soothe was 'reflected' but didn't consume the spell reflect buff. i dont know if this has changed"

3)   
http://www.arenajunkies.com/topic/89975-how-do-you-remove-spell-reflect
"mind soothe didnt consume spell reflect in TBC even though it got reflected, I supposed it still worked like that "

**Comment by liderer** [comment]
same problem with Spell "Mind Vision"https://www.tbcdb.com/?spell=10909 

Also remove spell reflect/grounding totem at unlimited distance 

https://imgur.com/s0vmcXF

**Comment by kelno** [comment]
Thanks! 
Fixed

**Comment by kelno** [comment]
Scratch that: it's now reflected/redirected and not consumed.
