### ISSUE TITLE
Frost Trap (or possibly other traps) expires immediately if the hunter can't see the target

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1381]
**Describe the bug**
Title.

**To Reproduce**

1. Cast a Frost Trap (13809)
2. Trigger it on a Stealth rogue (important: outside of the vision of the Trap caster)
3. Trap will expire prematurely or will expire prematurely when the triggering player is destroyed for the trap caster.

**Expected behavior**
Trap should last its full intended duration.

**Comment by kelno** [comment]
Fixed
