### ISSUE TITLE
Flare effect ignores line of sight.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1382]
**Describe the bug**
Flare (1543) ignores Line of Sight restrictions when it's casted on the ground.
The effect extends through walls and pillars.

Screenshots of current incorrect behaviour:

https://cdn.discordapp.com/attachments/525320741420531742/620237230992130048/unknown.png

https://cdn.discordapp.com/attachments/525320741420531742/620237676553175041/unknown.png

**Expected behavior**
It should not extend through line of sight from the starting point.

**Comment by woiwoz** [comment]
Let me check this.

**Comment by kelno** [comment]
I'll ask a source for this one

**Comment by woiwoz** [comment]
Don't look. It's the right thing to do. Including snowstorms. Nor should we attack targets behind walls.

**Comment by kelno** [comment]
Some spells to check, should all those ignore LoS?

https://db.endless.gg/?spell=27173
https://db.endless.gg/?spell=16914
https://db.endless.gg/?spell=4629
https://db.endless.gg/?spell=1510

**Comment by Jerrythemagicdog** [comment]
None of the other spells you have listed should ignore LoS.
Not sure if Frost Trap should, this is just something common on private servers, need actual proof.

**Comment by Jerrythemagicdog** [comment]
Frost Trap going over pillar: https://youtu.be/VhCI3DDvGGU?t=72 (pretty much the entire video)

**Comment by kelno** [comment]
Okay so conclusion of our research:

Visual on retail doesn't matter and should be ignored, only the debuff should be looked at.
Frost trap currently isn't affected by LoS and should be.
Earthbind totem currently is and should be.
Flare currently isn't affected and should.
Blizzard currently is and should.

So what's wrong here is: spell that triggers other spells are correctly affected but area aura spells directly applying an aura are broken.

**Comment by kelno** [comment]
Fixed
