### ISSUE TITLE
[Mage] Water Elemental doesn't want to attack targets with "CC breakable by damage".

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1384]
**Describe the bug**
Water Elemental (spell 31687) doesn't want to Waterbolt Polymorphed (spell 118) targets. 

**To Reproduce**
1. Cast Polymorph (118) on a target
2. Summon Water Elemental (31687) (or have him summoned before, the order doesn't matter here).
3. Order him to attack the target 
4. Watch him refuse to attack the target

**Expected behavior**
When I order my pet to attack I expect absolute subordination, nothing less.

**Comment by kelno** [comment]
Fixed
