### ISSUE TITLE
Wand damage type

### ISSUE THREAD

**Issue by ghost** [SunstriderEmu/BugTracker#1385]
**Describe the bug**
Wand damage seems to be physical instead of magic (common on pservers). It can trigger Backlash but not Nether Protection or consume Improved Shadow Bolt charges.

**Expected behavior**
Dealing magic damage.

Sunstrider rev. 12262 (57e85ace14b4) 2019-09-10 15:56:55 +0200 (dev branch) (Unix, Debug, Static)

**Comment by kelno** [comment]
Currently wand are a bit of a special case, they're more like a weapon with magic instead of physical damage types. 
I think the issue make sense here but I'm not 100% sure this is incorrect, can we try to find some proof that it should trigger spell related auras instead of melee/ranged ones?

**Comment by earthworm-jim** [comment]
> Direct damage shadow spells from priests and from wands with shadow damage consume a charge of the debuff Improved Shadow Bolt as well. [wowwiki](https://wowwiki.fandom.com/wiki/Improved_Shadow_Bolt?oldid=1432303)

**Comment by z5n** [comment]
issue has since been fixed
