### ISSUE TITLE
[Warlock][Talent]Nether Protection

### ISSUE THREAD

**Issue by ghost** [SunstriderEmu/BugTracker#1386]
**Describe the bug**
Triggered only by direct damage spells.

**Expected behavior**
Chance to proc from any shadow/fire aura applied (and direct damage).  
> NP can proc off everytime you take direct shadow damage or a shadow effect is applied onto you. so everytime a dot is applied it can proc. everytime shadow embrace is applied with a dot, it can proc from it, shadowbolt can proc it, shadowfury damage, shadow fury stun, improved shadowbolt, aftermath daze, pyroclasm stun, UA dispel damage, UA dispel silence etc....  
[allakhazam](http://wow.allakhazam.com/forum.html?forum=243&mid=1189545054292955086)

tooltip:  
> After being hit with a Shadow or Fire spell, you have a 30% chance to become immune to Shadow and Fire spells for 4 sec.  

[zUkUu duel guide](https://vimeo.com/5356030)
12:20 , 12:42 --- Curse of Tongues
13:04 --- Devour Magic
13:21 --- Siphon Life
13:46 --- Devouring Plague / Shadow Weaving
13:57 --- Shadow Word: Pain
15:36 --- Psychic Scream

[drakedawg (corruption)](https://youtu.be/A4NL-GEoKEY?t=505)  

> By Gnostik on 2008/05/15 at 3:37 AM (Patch 2.4.1)
I really feel bad when I fight Shadow Priests and most Warlocks. **Seems like _Nether Protection is always up_.** (Fire Mages I never see.) Fel Guard locks are obviously a bit different, and when I run into another Destruction Lock it's just silly.

Sunstrider rev. 12262 (57e85ace14b4) 2019-09-10 15:56:55 +0200 (dev branch) (Unix, Debug, Static)

**Comment by kelno** [comment]
Nether Protection Rank 1 https://db.endless.gg/?spell=30299

**Comment by earthworm-jim** [comment]
Just tested a bit. Seems to not proc at all from Hellfire, and super rarely from Rain of Fire.

**Comment by kelno** [comment]
earthwormgroovy: "there are still problems with NP. spells like hellfire can't proc the talent (disregard the RoF bit, it's fine)"

**Comment by kelno** [comment]
I tested right now, hellfire can proc it (on cast)
doesn't proc on ticks but I'm not sure it should, since it doesn't seem it should proc on dot ticks either (and hellfire is a dot on self)

**Comment by kelno** [comment]
Apparently Hellfire has some kind of exception.

https://www.wowhead.com/forums&topic=2962#p38306 wowhead comment:
"Nether Protection works amazing with Hellfire. Hellfire will proc Nether Protection, and then I dont take any damage from any casters, or myself for those 3 sec. I assume Bliz figured a Hellfire, with Nether Protection, and also the abliltiy to interupt casting and flag tagging was a bit too much. But despite this nerf, I still love Hellfire, and I will get used to this new era of Hellfire using the ablitly of Nether Protection." (the nerf he's talking about is other changes to Hellfire in 2.3)

(about Quagmirran's Eye on wowhead):
"it procs on casting dot (not on ticking) and on the explosion part of SoC, it also can proc of the first tick from Rain of Fire and each tick of Hellfire"

**Comment by kelno** [comment]
Updated, applied on next restart
