### ISSUE TITLE
When attacking a target affected by Cyclone or Ice Block the message says Miss.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1388]
**Describe the bug**
When attacking a target in Cyclone (33786) or Ice Block (45438) the message currently says Miss.
That's wrong and it should show "Immune".
This could have some proc implications perhaps if it's not only visual.

**Follow up**:
Affected procs that proc through Ice Block or Cyclone (and should not be procing) are for example Molten Armor (30482) or Ice Armor (27124).

Retail source:
https://www.youtube.com/watch?v=IAoe3akMZUE&feature=youtu.be&t=1017

The Ice Armor debuff (Chilled) does not get refreshed after the Rogue hits him in Ice Block (the proc rate is 100% on every attack).

To reproduce:
1. Cast Ice Armor (27124)
2. Cast Ice Block (45438)
3. Attack the player affected by both of those.

**Comment by kelno** [comment]
Ice Armor is unrelated completely to the first issue? If so move it to another issue

**Comment by kelno** [comment]
Can you move the "follow up" stuff to another issue?

**Comment by kelno** [comment]
Main issue is fixed
