### ISSUE TITLE
[Addons] When a Rogue Vanishes the combat log message is not sent to surrounding players

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1389]
**Describe the bug**
When a Rogue uses Vanish (26889) there is no trace of it in the combat log for the observing players. This messes with cooldown addons and other such inventions.

This is what the Rogue gets on his end (combat log is set to Everything tab):
https://imgur.com/a/jR9Nw0w
There is no trace of this on the observer's end.

This is what happens on other private servers for the observing player (combat log set to Everything tab):
https://imgur.com/O707kPz

**To Reproduce**
1. Have a cooldown tracking addon (Gladdy for example) or watch Combat Log
2. Watch the enemy target cast Vanish (26889)
3. There will be no track in your cooldown addon or combat log about the Vanish being used

_Perhaps it is because we are so fast that the message gets sent after the Rogue...
gets destroyed._

**Comment by kelno** [comment]
Fixed
