### ISSUE TITLE
Cast bars are incorrectly started when an effect is applied at a certain time of the previous cast.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1390]
**Describe the bug**
When interrupting a cast with an effect such as Blind (2094) or Death Coil (27223) at a certain time where the cast is about to finish the next cast starts visually and results in a weird visual bug where the character is still casting.
Here's how it looks: https://streamable.com/199t1

**To Reproduce**
1. Spam cast on a character
2. Cast Death Coil (27223) or Blind (2094) by the end of the cast
3. The next cast will start with a cast bar.

**Expected behavior**
The next cast should not start since we're already under the effect of the spell.

**Comment by kelno** [comment]
Fixed
