### ISSUE TITLE
Charges result in a teleport for the observer when spamming movement keys as the charge starts and during.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1391]
**Describe the bug**
When spamming movement keys / jump keys during a charge and when it starts it results in the charge becoming a teleport for the observers.

Here's how it looks
https://streamable.com/zm7v8

**To Reproduce**
1. Start a charge (for example Warrior's Intercept 25275)
2. Start spamming movement keys when it starts or jump or just hold right click on the mouse and spin around
3. The charge will result in a teleport visually

**Comment by kelno** [comment]
Fixed
