### ISSUE TITLE
[Warrior] Auto-attacking removes two Enrage stacks per attack.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1392]
**Describe the bug**
Warrior's talent Enrage (13048) in the Fury tree procs whenever a warrior is a victim of a critical strike. After that it gains 12 charges for attacks for the Warrior. Currently 2 charges are being consumed per attack instead of 1.
Only 1 charge is consumed when the target Dodges.

Spell ID of the proc the Warrior gains: 14204.

**To Reproduce**
1. Learn Enrage (fury Tree)
2. Get crit or .cast 14204
3. Observe that you lose 2 stacks per 1 attack

**Comment by Jerrythemagicdog** [comment]
To dev: spell_proc?

**Comment by kelno** [comment]
Didn't we hear the story of "old hack breaking stuff" like two days ago? Here's our culprit:  
![image](https://user-images.githubusercontent.com/3866946/64903426-c0e3ec80-d6b8-11e9-84fe-2bfeb095720e.png)

**Comment by kelno** [comment]
Fixed
