### ISSUE TITLE
Some quest credits are credited twice 

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1393]
**Describe the bug**
Some quest credits are handed out in a 2 for 1 manner.

For example quest "An Improper Burial" (10913) where the player is asked to burn bodies of Slain Sha'tari Vindicators and Slain Auchenai Warriors.
(
both done in SmartAI in the exact same manner 
Vindicator: http://dev.sunstrider.com.test/creature/entry/21859/smartai
Warrior: http://dev.sunstrider.com.test/creature/entry/21846/smartai
)
For some reason when we burn the Vindicator's body we are credited for two at once instead of 1 and when we burn the Warrior we are correctly credited for only one.
**To test**: 
1. .quest add 10913
2. .go crea 27595
3. /use Sha'tari Torch

Similar issue occurs in Blade's Edge Mountains with the quest Protecting Our Own (Alliance version - 10457)
When we use the quest item Rina's Bough (29952) we are credited for 2 instead of 1.

**To test**:
1. .quest add 10457
2. .go xyz 1870.427246, 6754.771973, 143.964432, 530
3. /use Rina's Bough

The spells connected to the items have 2 effects each and it feels as though we are credited for both of the casts (SmartAI event triggers on spell hit) - maybe a clue.

**Comment by kelno** [comment]
Fixed
