### ISSUE TITLE
Effects are not cleared properly when they expire if the target changes shapeshifts during them

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1394]
**Describe the bug**
Effects such as Fear (6215) or Entangling Roots (26989) are not expiring visually and remain on the target forever in very specific cases

**To Reproduce**
1. Death coil target
2. Fear (6215) a target, it has to land before death coil expire
3. Cast Fear again (6215) on the target

Here's a clip:
https://streamable.com/7x9wh

**Comment by kelno** [comment]
Fixed
