### ISSUE TITLE
[Spell] Seed of Corruption explosion ignore LoS

### ISSUE THREAD

**Issue by earthworm-jim** [SunstriderEmu/BugTracker#1395]
**Describe the bug**
Reflected SoC explosion deals damage to caster's enemies instead of allies.  
Doesn't obey line of sight.

**Expected behavior**
> Seed of Corruption does not deal damage to the caster's enemies but to the target's allies. This means that a reflected SoC will deal damage to its caster's pet and allies. [wowwiki](https://wowwiki.fandom.com/wiki/Reflect?oldid=1580129)

> By BloodScribe on 2010/05/10 at 2:36 PM (Patch 3.3.3)
when you used to be able to reflect seed of corruption, i don't know if you still can as I've never done it a second time and never really heard from anyone else doing it.
it was during a game of AV and we were fighting on the bridge, and large group was clustered togther, and few of my pvp friends were aoe away at them and I was targeting a mage that was casting pyro on me when i hit spell reflect, next thing I see is it wear off and watched as a lock in the middle of the group was ticking away and boom 9 killing blows appeared on my screen :S had to look at my combat log to confirm what i just saw lol
Last edited by BloodScribe on 2010/05/10 [wowhead](https://www.wowhead.com/forums&topic=151296.3)

> "Patch 2.3.0 (2007-11-13): Seed of Corruption detonation will now obey line of sight."

>"By littlidabbi (23,379 – 5·32·160) on 2007/06/18 (Patch 2.1.1)
Warning : Seed of Corruption explodes through floors and walls and can pull mobs from other levels and rooms(Common in Scholo pulling the basement and mobs in rooms below u at Gandling). So avoid using Seed of Corruption in instances with 2 levels or rooms close to each other.
  Tarquin on 2007/06/19 (Patch 2.1.2)
    Frequently happens in Kara outside the Maiden's section, too.
  Stryik on 2007/10/11 (Patch 2.2.3)
    Set to be fixed in 2.3.
  Lukrid on 2008/08/15 (Patch 2.4.3)
    yup currently the explosion effect on SoC follows LoS rules. Basically, no more pulling aggro from nearby rooms when the bomb goes off."

**Comment by kelno** [comment]
Fixed

**Comment by kelno** [comment]
The reflect part is fixed

**Comment by kelno** [comment]
Fixed for LoS
