### ISSUE TITLE
Invisibility and Hunter's Mark

### ISSUE THREAD

**Issue by earthworm-jim** [SunstriderEmu/BugTracker#1397]
**Describe the bug**
Invisible players affected by Hunter's Mark unable to see the hunter.

**Expected behavior**
> Patch 2.4.3: Invisible players with Hunter's Mark can see the hunter that put the mark on them.

Sunstrider rev. 12313 (cafbbcd86d81) 2019-09-17 12:30:10 +0800 (dev branch) (Unix, Debug, Static)

**Comment by kelno** [comment]
Fixed
