### ISSUE TITLE
Cloak of Shadows and Hunter's Mark

### ISSUE THREAD

**Issue by earthworm-jim** [SunstriderEmu/BugTracker#1398]
**Describe the bug**
CoS 90% resist chance applies to Hunter's Mark

**Expected behavior**
The chance to resist should not apply to Hunter's Mark

Sunstrider rev. 12349 (a0c1bb3b236f) 2019-09-20 12:24:32 +0200 (dev branch) (Unix, Debug, Static)

**Comment by earthworm-jim** [comment]
https://db.endless.gg/?spell=14325
School: Arcane
Dispel type: Magic

IIRC it was physical, magic dispel type

**Comment by kelno** [comment]
School and dispel type are probably correct, must be some rule about it being a non combat spell and not being able to miss

**Comment by kelno** [comment]
Fixed
