### ISSUE TITLE
[Hunter] Snake Trap snakes gain stamina from owner's stamina.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1400]
**Describe the bug**
Snake Trap's snakes gain stamina from owner's stamina. 

**To Reproduce**

1. Equip some stamina on a Hunter
2. /cast Snake Trap
3. Snake hp will skyrocket

**Expected behavior**
There should be no scaling going on for the snakes.

To dev: in the DB it's already modifier 0 for all types of snakes.

**Comment by hufsa** [comment]
StatSystem.cpp line ~1222

**Comment by kelno** [comment]
Fixed with a hacker :(((((
