### ISSUE TITLE
Player speed gets altered after they leave arena.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1402]
**Describe the bug**
Title

**To Reproduce**

Scenario 1 (slow):
1. Cast Hamstring on a target in arena (spell 7373)
2. Die with Hamstring present
3. Leave arena

Scenario 2 (rocket boost):
1. Die in arena and become a ghost - Release Spirit (so don't lose the game automatically)
2. Wait for the arena to end
3. You're now a rocket man outside of the arena.

**Comment by kelno** [comment]
Tried a fix, not sure it covers all cases

**Comment by Jerrythemagicdog** [comment]
Tested both cases, the fix works.
