### ISSUE TITLE
[Warlock] Sacrifice can't be canceled at all

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1403]
**Describe the bug**
~~A warlock(?) buff couldn't be canceled while affected by Sap.
The suspicion here is that it was Voidwalker pet's Sacrifice shield that couldn't be canceled.~~

**To Reproduce**
~~1. Cast Voidwaker's Sacrifice~~
~~2. Get Sapped~~
~~3. Can't right click it off~~

~~Apparently it was also Unending Breath and the other Warlock buffs.~~

Correction:
Warlock's Voidwalker's Sacrifice (27273 for rank 7) can't be canceled under any circumstances.

**Comment by ramadansteve** [comment]
pls give this some higher prio its really annoying when in arena the mage spellsteals your sacrifice and you can't do anything about it

**Comment by kelno** [comment]
Fixed
