### ISSUE TITLE
[Hunter] Snake Trap, Explosive Trap can be resisted or have no effect

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1404]
**Describe the bug**
Title.

**To Reproduce**
1. Log on a Hunter
2. /cast Snake Trap
3. Appears to have no effect from time to time

Apparently affects other traps as well.

**Comment by kelno** [comment]
Mele: "we find problem, all traps dissapear when hunter got any disable and enemy go in trap in this moment
stuns\fear\blind\goush\sap any disable"

**Comment by kelno** [comment]
Updated with c7b5fd9d451d396de2f874a80538f3bf4922f3c7 
It won't fail anymore if the hunter is controlled. BUT. Maybe there are other cases. Need to reopen if that's the case.
