### ISSUE TITLE
[Mage] Conjured Croissant replenishes HP instantly after sitting down.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1405]
**Describe the bug**
Title

**To Reproduce**
1. .additem 22019
2. /use Conjured Croissant
3. Observe how quickly the tick of food is given compared to other, "normal" food.

**Expected behavior**
Should be the same as other food.

**Comment by kelno** [comment]
After research it seems the arena drinks has some special handling that does not apply to food (or other drinks for that matter).
Closing for now.
