### ISSUE TITLE
Gladdy cast times are not updated out of Stealth.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1407]
**Describe the bug**
Cast bars on Gladdy and unit frames are not updated when the cast happens out of Stealth.

**To Reproduce**
1. Cast Prowl on a Druid
2. Cast Cyclone on a target out of Prowl
3. Observe Gladdy and unit frames not showing the cast times.

**Expected behavior**
The player should see the cast bar

**Comment by kelno** [comment]
Does the cyclone cast appear in combat log?

**Comment by Jerrythemagicdog** [comment]
It seems that it sometimes does appear and sometimes doesn't.

**Comment by kelno** [comment]
Fixed with https://github.com/kelno/sunstrider/commit/ca8c187fb69332a1abb7cd9687bd8addad5f327e
