### ISSUE TITLE
[Rogue] Vile Poisons doesn't increase Poison damage

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1410]
**Describe the bug**
Title.
Vile Poisons (Rank 5) (16720)
"Increases the damage dealt by your poisons and Envenom ability by 20% and gives your poisons an additional 40% chance to resist dispel effects."

Currently the damage is not increased. 
The dispel resist part works correctly (tested with over 60000 attempts in the automated test).

Tested with Wound Poison V

**Comment by kelno** [comment]
Related test: "talents rogue vile_poisons"

**Comment by Jerrythemagicdog** [comment]
Fixed, test passes now.
