### ISSUE TITLE
[Warrior] Focus Intercept switches attack target to the Intercepted target

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1411]
**Describe the bug**
Title.
Intercept (25275)
Intimidating Shout (5246)

**To Reproduce**
1. Attack Target A
2. Focus Intercept Target B with autto-attack on Target A (/cast [target=focus] Intercept). 
3. The attack target will switch to Target B

This apparently happens for more abilities such as Intimidating Shout

**Comment by kelno** [comment]
Fixed
