### ISSUE TITLE
Lower rank buff overwrites higher

### ISSUE THREAD

**Issue by earthworm-jim** [SunstriderEmu/BugTracker#1412]
**Describe the bug**
Title... e.g. Rank 1 Arcane Intellect overwrites max rank

**Expected behavior**
Should get an error msg "A more powerful spell is already active"

**Comment by Jerrythemagicdog** [comment]
Intended for your own spells.

**Comment by Jerrythemagicdog** [comment]
Intended for your own spells.

**Comment by kelno** [comment]
Yes it's intended

**Comment by ramadansteve** [comment]
if it's intended then please make it so that faerie fire (feral) last rank can be overwritten by your own regular faerie fire (rank 1) because right now it's not the case and it's annoying af

**Comment by kelno** [comment]
Indeed the current rule only covers ranks of the same spells.. I extended it to every spell that would be rejected. Will be applied next update.
