### ISSUE TITLE
Seal of Blood judgment self damage delay

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1413]
Problem :  
http://tbc.cavernoftime.com/spell=31892   SOB damage instantly backfire the paladin . Should have delay ~0.5 sec  . Very usefull in pvp !

How it should work :
Seal of blood backfire damage  should return with a delay, giving the chance to get out of control: sheep , gouge , scatter shot , Freezing trap etc...   (~same mechanic like SWD priests) .  

Proofs: 

https://www.youtube.com/watch?v=LgNguOcsuhM#t=1m38s   backslash damage remove blind (like swd)  

https://www.youtube.com/watch?v=IB7bUNWTlh4#t=30m51s  reuploaded video from Wacraftmovies (backslash damage remove pollymorph) 

https://youtu.be/LgNguOcsuhM?t=47   ~0,5 sec  delay after judgement sob 

1) some information about delay https://web.archive.org/web/20080515033854/http://forums.worldofwarcraft.com/thread.html?topicId=6417442321&sid=1&pageNo=8
"judging blood is a viable and encouraged way of dodging an incoming sheep; the backlash damage from it is delayed a good split second and will break CCs that have landed on you, so it's not some surgical precision thing only attainable with <30 ping."

http://www.arenajunkies.com/topic/42196-seal-of-blood-question/
"The secondary use of SoB is that it allows the paladin to mimic the use of SW: D that priests use to get out of Polymorphs and occasionally Blinds. SoB's backlash damage occurs about 0.5s-1.0s after the actual attack, which means its quite possible for you to make an attack (Auto or Judgement) get Polymorphed, then get broken out of the effect because of the backlash effect."
http://www.arenajunkies.com/topic/2839-seal-of-blood-work-like-swd/
http://www.arenajunkies.com/topic/56841-seal-of-martyrblood-judgement/

http://www.arenajunkies.com/topic/13289-seal-of-blood-versus-seal-of-command/
"Seal of blood is for breaking polymorph, not for PvP in general. "

https://www.reddit.com/r/wow/comments/1eb162/a_brief_history_of_paladin_seals/
"RIP Seal of Blood. Judging polymorphs was the best shit in pvp."

http://us.battle.net/wow/en/forum/topic/3196021591
"I remember using judgement of blood on a mage when they were at the end of casting polymorph and breaking out of polymorph because of the self damage."

If it's not enough you can go frame by frame through some old vids, for example in this https://www.youtube.com/watch?v=LgNguOcsuhM shitty vid at 0:48 you can see the delay between judgement and the backfire DMG.  

(same reports from other projects ) : 
https://www.warmane.com/bugtracker/report/51084
https://github.com/ccshiro/cc-buglist/issues/1598

**Comment by kelno** [comment]
This screams "SPELL BATCHING", but we discussed and agreed to add some delay. Fixed!
