### ISSUE TITLE
Seal of Vengeance - missing spell power bonus

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1417]
Problem :  
Spell http://tbc.cavernoftime.com/spell=31801  missing spell power bonus 

https://imgur.com/a/A8CwBmG

How it should work :  
https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=1549176  

" Seal of Vengeance (per tick, per application) | 3.4%" 

https://web.archive.org/web/20080525131414/http://www.wowwiki.com:80/Spell_Damage_Coefficients#Paladin_coefficients  

"Seal of Vengeance (per tick) | 17.0% " - here they mean coefficient with 5 charges 3.4*5

**Comment by Jerrythemagicdog** [comment]
Fixed
