### ISSUE TITLE
[Hunter] [Spell] Eagle Eye

### ISSUE THREAD

**Issue by ghost** [SunstriderEmu/BugTracker#1418]
**Describe the bug**
- Players are stuck running in place while Eagle Eye is being channeled
- Animation not looped (likely the same for Far Sight)

**Expected behavior**
https://youtu.be/db3sYKRf_AQ?t=119  

> The target area will have golden shimmers while you look around, so it is easily detectable in PvP unless you put it high in a tree or somewhere that won't be looked at. [wowwiki](https://wowwiki.fandom.com/wiki/Eagle_Eye?oldid=1444892)

Sunstrider rev. 12396 (6ade3a0482a0) 2019-09-22 21:37:26 +0200 (dev branch) (Unix, Debug, Static)

**Comment by kelno** [comment]
You have the Eagle Eye for details

**Comment by kelno** [comment]
Other bug: If you try to chain it using macro `/cast !Eagle Eye`, the vision stays linked to the first eagle eye.

**Comment by kelno** [comment]
Other bug: It seems you can't see creature movements with it?

**Comment by kelno** [comment]
Everything fixed but the animation loop

**Comment by kelno** [comment]
Woiwoz says:
```
1、Because both spells use the perspective of DynamicObject, we should send the perspective of DynamicObject synchronously.
2、We need to continue to improve. We need golden animations that can be recycled. And when we use macro commands (/ cast !Eagle Eye) to continuously observe distant destinations, we still can't refresh nearby NPCs and any game objects or players.
:persevere:
I mean, if we use the macro command (/ cast! Eagle Eye) to use Eagle Eye continuously, if the second distance has exceeded the Player caster's visual distance, we still can't see any objects around us.
```

**Comment by z5n** [comment]
all issues listed here have since been fixed
