### ISSUE TITLE
Can not be in Stealth (or Shadowmeld) and eat at the same time.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1419]
**Describe the bug**
Title.

**To Reproduce**
1. .additem 32453
2. Cast Shadowmeld (20580)
3. /use Star's Tears
4. Can't do it. 

Same issue occurs with Rogue Stealth and Food.

**Expected behavior**
Should be able to eat.

**Comment by earthworm-jim** [comment]
IIRC u have to eat before entering stealth/meld

**Comment by Jerrythemagicdog** [comment]
You're right, the issue is the same even if we follow the order though. Thanks!

**Comment by Jerrythemagicdog** [comment]
Fixed
