### ISSUE TITLE
Disoriented movement should take precedence over other movement.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1420]
**Describe the bug**
When a target is affected by a disorient effect it should take precedence over other (at least fleeing) movement.

Retail proof: https://youtu.be/a0h9-V4b9_g?t=59

Druid is Blinded, the priest walks over to Fear, Fears him, Druid still does disoriented movement until Blind expires, then proceeds to flee.

**To Reproduce**
1. Cast Scatter Shot or Blind on the target.
2. Fear the target.
3. Target is now running with disoriented movement (Fear takes precedence)

**Expected behavior**
According to retail disoriented movement should have priority.

**Comment by Jerrythemagicdog** [comment]
Semi- related: Targets affected by freezing trap are also moving while feared
https://www.twitch.tv/shivasdance/clip/JoyousPlumpTarsierCorgiDerp

**Comment by kelno** [comment]
I think I know why the second one happens, it's another unrelated issue

**Comment by kelno** [comment]
To dev: Priority logic happens in `MotionMaster::DirectAdd`. Currently same priority = replacing. Change it so same prio keep the current one running?

**Comment by Jerrythemagicdog** [comment]
> To dev: Priority logic happens in `MotionMaster::DirectAdd`. Currently same priority = replacing. Change it so same prio keep the current one running?

Sounds like we could try it and see if there is something wrong.

**Comment by kelno** [comment]
So we need proof for this. One where a fear is already applied and then only a blind/scatter shot is applied.

**Comment by ramadansteve** [comment]
my 2 cents: idk how it's supposed to be blizzlike but i think the only way it makes sense is when target that's affected by scatter and fear at the same time will move like it's scattered and not feared while scatter is up on that target

**Comment by kelno** [comment]
I agree but in those kind of details a lot of things 'make sense' but are actually non intuitive. I'd rather not spend time to implement something only to revert it later as it happened quite a few times already

**Comment by hufsa** [comment]
I am 100% sure this report is valid.
We can safely assume confused movement should take precedence over fleeing.
Confused Movement > Fleeing Movement, no matter the order of application.

**Comment by kelno** [comment]
Fixed
