### ISSUE TITLE
Thorns damage go through cloak of shadows

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1422]
thorns damage goes through cloak of shadows

it shouldn't?

**Comment by kelno** [comment]
Thorns is a "damage shield", like PW:S with talent can be. The cloak of shadows reduces hit chance by 95%.
So the question is, should those damage shield roll hit? I'm not so sure.

**Comment by ramadansteve** [comment]
https://youtu.be/eJWNMCD8SMU?t=134 you can see most thorns hits being resisted but 1 goes through
currently 100% of thorns hits ignore cloak

**Comment by kelno** [comment]
Thanks

**Comment by kelno** [comment]
Okay the issue was: the thorns spells was considered positive even for the returned damage, so it couldn't miss.
Fixed!

**Comment by ramadansteve** [comment]
reflective shield damage still ignores cloak, not sure about thorns and shields didnt test that

**Comment by kelno** [comment]
Okay I looked into it: I was wrong saying PW:S was affected.
This is fixed now.
