### ISSUE TITLE
'dodge' in combat text appears in white when being attacked by a melee ability

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1423]
when you dodge an attack 'dodge' in your combat text shows in white as if your attack got dodged instead of red

this is very confusing when you're playing warrior and u see 'dodge' in white and assume ur attack was dodged, u go battle stance and you can't overpower because it's you who actually dodged an attack

upd: apparently only happens when you dodge a special attack like kidney shot

**Comment by kelno** [comment]
This doesn't seem very consistent indeed but it seems it's just the way TBC client is, I don't think there is a way to fix it.
As always if you have a counter proof we can research this further.

**Comment by Jerrythemagicdog** [comment]
This was checked and compared to Warmane where it's exactly the same way: 
Dodge abilities appear in white, dodged white attacks appear in red.
