### ISSUE TITLE
summon water elemental

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1424]
water ele has too much hp (~5.5k). according to https://youtu.be/dbKaU_LMCCk?t=1544 it had ~2.2k in season 3, which imo is too little but 5.5k is defo too much, think it was around 3-4k on other pservers which was fine

upd: https://www.youtube.com/watch?v=ZV0LjkeanUE 0:25 chrille hits water ele for 1495+630=2125 and it's 58% of it's hp which would mean water ele has around 3664 hp

**Comment by earthworm-jim** [comment]
https://github.com/ccshiro/cc-buglist/issues/2052

**Comment by kelno** [comment]
Thanks for the CC source that helps a lot

**Comment by kelno** [comment]
Reduced it a bit, needs to be re tested

**Comment by Jerrythemagicdog** [comment]
With the season3 gear available on PTR the water elemental is currently at 4596 hp with owner's HP being 10073

**Comment by kelno** [comment]
Okay, scaling was fine but base HP wasn't, fixed!
