### ISSUE TITLE
[Request] crits denied by resilience

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1425]
critical attacks denied by resilience should still be considered crits and therefor trigger following talents: 'eye for an eye' 'blood craze' 'enrage' 'eye of the storm' 'blessed recovery' 'blessed resilience' 'focused will' 'natural perfection' 'martyrdom' and mby some others

im not sure this issue is present but since it's very common on pservers i assume it is and since it's hard for me to test im asking you

**Comment by Jerrythemagicdog** [comment]
> Any effect which benefits the victim of a critical strike will now trigger even if resilience converted the attack from a critical strike to a normal strike; this applies to melee, ranged, and spell. The affected talents, abilities, and items are: "Eye for an Eye", "Blessed Resilience", "Enrage", "Martyrdom", "Blood Craze", "Eye of the Storm", and "Bonespike Shoulder".

Patch 2.0.7

**Comment by kelno** [comment]
The issue is present for sure.
We researched this very recently. It's hard to implement correctly without major changes. (Making it lower on my prio list)

**Comment by Jumpka** [comment]
This might make the implementation easier. On retail, it wasn't really triggered from "converted" attacks, but probably just a chance equal to resilience crit chance reduction (or maybe scaled a bit taking into account opponents crit chance etc. to make it exactly same chance as with no resil). 
The proof of this can be seen in pretty much any warrior video, where wars often get enrage but no blood craze or vice versa from normal hits, which means every buff makes it's own roll on normal hits. If it triggered from "converted" crits, they would always go off at the same time. Implementing chance of triggering from normal hits equal to resilience might be easier andvery retail-like (if not exactly like retail).

**Comment by kelno** [comment]
I see thanks! Blizzard is very very dirty on that one

**Comment by Jerrythemagicdog** [comment]
moved to https://github.com/SunstriderEmu/BugTracker/issues/1425 with more details.
