### ISSUE TITLE
Shadowstep while being Feared or Scatter Shotted kicks the caster of Shadowstep

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1426]
sometimes when you shadowstep you get dc'ed
https://www.twitch.tv/videos/485404742 14:50

i think it happens when you get cc'ed at the same time as you use shadowstep or mid-air. notice how i got feared while stepping. similiar thing happened the other time when i was dueling a rogue and blinded him in the middle of step, he also got dc'ed

**Comment by Jerrythemagicdog** [comment]
Steps to reproduce:
Scenario 1:
1. Cast Scatter Shot on the target
2. While it's in flight, Shadowstep to the caster
3. The target is kicked.

Scenario 2:
1. Cast Fear on a target
2. As soon as cast is about to end, Shadowstep to the caster
3. The target is kicked.

Those two ways are 100% reliable to reproduce.

**Comment by kelno** [comment]
Fixed
