### ISSUE TITLE
feral charge

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1427]
feral charge shouldn't be a subject to DR.
https://youtu.be/IgR2eWXrQ9s?t=577 9:42 feral charge fades, 9:57 he charges again and it's full

p.s. jerry told me it's an intended game design, to which my reaction was ANGER. if this only affected resto druids i could see how it makes sense (sort of) but it also affects ferals which makes this 'game design' really questionable imo.

**Comment by kelno** [comment]
Thank you for the input! We're going to publish a list of those changes, they're very few for now. Hopefully that will help people be more aware of them and sparks more discussions, we'll be listening and see how the general reaction is.
As this is not the place for reporting those I'll be closing this issue.
