### ISSUE TITLE
Quick tick mana drink on arena (bug)

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1428]
Problem : mana drinking  on arena should have 4 sec delay for first tick . 

https://youtu.be/woZEIa4IZkw  on endless this like 0.5 sec 

Proofs :  

https://wowwiki.fandom.com/wiki/Patch_2.4.0  
"The benefits of drinking out of combat have been delayed while in the Arena. It will now take four seconds before the full benefit of the mana regeneration will come into effect. " 

1) https://youtu.be/NMkgJmSiMc4?t=989  Hydra movie patch 2.4+ druid with s4 head on frame . 

2) https://youtu.be/fpIPaX4xOcU?t=191   4+ sec for first mana tick .

**Comment by kelno** [comment]
More exactly the first tick is between 2.2 and 4s, randomly
