### ISSUE TITLE
[Black Temple] Mounted Dragonmaw NPCs (trash before Supremus) should be in the air.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#143]
**Description:**
Dragonmaw NPCs before Supremus:
- Dragonmaw Sky Stalker (23030)
and
- Dragonmaw Wind Reaver (23330)

should be flying in the air and descend to the players when aggroed.

**Current behaviour:**

**Some mobs (GUIDs: 53893, 53906, 53910, 53911, 1096569, 12743, 53917, 12742, 12741)** are on the ground or suspiciously close to the ground, mounted on the dragons, standing still.

**Expected behaviour:**

The mobs should be flying in the air on their mounts, then fly lower to fight or fly down to the ground and dismount to fight (depending on the target they're aggroed to).

**_Sources_**:
**Dragonmaw Sky Stalker wowhead**: https://www.wowhead.com/npc=23030/dragonmaw-sky-stalker#comments:id=221989

"Trash before Supremus. They fire down from the air, and probably won't descend to melee range, so they'll need to be tanked by a ranged DPSer. They fire an Immolation Arrow that creates a fiery patch on the ground; you probably shouldn't stand in that."

**Dragonmaw Wind Reaver wowhead**: https://www.wowhead.com/npc=23330/dragonmaw-wind-reaver#comments:id=221977

_"Trash before Supremus. They attack mostly with fireballs. They have a ranged (not point-blank) Frost Nova. They have caster AI, so they'll run away from melee while they're rooted, but it can be cleansed. Finally, they have a small-radius AoE around their primary aggro target that does 1.6k damage.

In the early pulls, they come on the ground, but later the ones in the air come down (they are linked to some of the melee pulls). If they don't descend to melee range, your raid has to be prepared to have a ranged DPS tank them. Any class should be fine."_

**Clips from retail:** 

Sky Stalkers and Wind Reavers seen flying around: https://youtu.be/dka5CmIoBgc?t=99
Combat clips: https://youtu.be/dka5CmIoBgc?t=362

**Comment by Kittnz** [comment]
tc has some waypoints for these, added them myself
