### ISSUE TITLE
Abuse forms for drinking

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1430]
Problem : Possible to drink in forms 
https://imgur.com/4h2O0Q9 

How reproduce :  (video from other project , but here same problem )
https://www.youtube.com/watch?v=INiaJv_TsSQ

**Comment by ramadansteve** [comment]
same applies for ghost wolf

**Comment by kelno** [comment]
Also
![image](https://user-images.githubusercontent.com/3866946/65604451-d2c26b00-dfa7-11e9-867e-9e4c191af8ac.png)

**Comment by kelno** [comment]
Fixed

**Comment by kelno** [comment]
It's still possible in ghost wolf and travel form though, can we confirm it's correct/incorrect?
