### ISSUE TITLE
Targets affected by Freezing Trap flee when Feared

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1432]
**Describe the bug**
Title.
https://www.twitch.tv/shivasdance/clip/JoyousPlumpTarsierCorgiDerp

**To Reproduce**
1. Cast Freezing Trap (14311) on a target
2. Cast Psychic Scream (10890)
3. The target will flee while being an ice cube

**Comment by woiwoz** [comment]
lol......

**Comment by woiwoz** [comment]
I think if the target is blinded. It will also lead to random walk of the target.

**Comment by kelno** [comment]
Possibly fixed indirecty, will close for now
