### ISSUE TITLE
[Hunter] [Talent] Bestial Swiftness remains active even after respec

### ISSUE THREAD

**Issue by earthworm-jim** [SunstriderEmu/BugTracker#1437]
**Describe the bug**
Seems to not increase the speed at all.

Sunstrider rev. 12396 (6ade3a0482a0) 2019-09-22 21:37:26 +0200 (dev branch) (Unix, Debug, Static)

**Comment by Jerrythemagicdog** [comment]
How was this tested? 
The speed is increased and can be easily observed with and without the talent by ordering the pet to attack a target dummy.
The pet adjusts its follow speed to the speed of the owner which is correct.

**Comment by earthworm-jim** [comment]
By attacking the dummy. Takes the same amount of time to reach it /w and w/o the talent.

**Comment by Jerrythemagicdog** [comment]
Wasn't the case for me, what was the pet used?

**Comment by earthworm-jim** [comment]
scorpid iirc

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by kelno** [comment]
Fixed

**Comment by kelno** [comment]
Feral Swiftness might also be affected by this
