### ISSUE TITLE
[Hunter] [Spell] Kill Command

### ISSUE THREAD

**Issue by earthworm-jim** [SunstriderEmu/BugTracker#1438]
**Describe the bug**
Using KC when pet has no target results in spent mana and cooldown but the ability does nothing.

**Expected behavior**
>  #show Steady Shot
    #showtooltip Steady Shot
    /cast Kill Command
    /cast Steady Shot 
It works.. but if (for some reason) **you’re fighting something but your pet isn’t fighting something..** if you get a crit, it’ll **trigger Kill command on your pet.. which will cause your pet to attack your target.** Sometimes that’s not what you want.

source: http://www.fibergeek.com/chicanery/2008/01/02/steady-shot-kill-command/

Sunstrider rev. 12418 (a377cdffdc5d) 2019-09-24 19:33:38 +0200 (dev branch) (Unix, Debug, Static)

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/448

**Comment by Jerrythemagicdog** [comment]
Sounds reasonable - mana and cooldown spent, considering Kill Command triggers Beast Lord (28228) 4-set bonus.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed!
