### ISSUE TITLE
[Warrior] Sweeping Strikes damage calculation 

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1440]
**Describe the bug**
Sweeping Strikes has a bunch of issues currently in regards to its damage:
2 targets: 
target A - main target of our attacks
target B - bystander on whom the attacks spill

1. Sweeping Strikes bounce damage (so on target B while targeting target A) ignores armor and resilience of target B

2. Sweeping Strikes damage also affects nearby totems (so does Blade Flurry currently - is that wrong?)

Here's a more detailed report by @sposobniy : https://pastebin.com/Ttsdyrt1

**Comment by kelno** [comment]
```
1) The Problem:
 
    Sweeping strikes cause full unreduced critical dmg on secondary targets, even though both main and secondary target have 20%
    reduction from resilience.
 
    https://youtu.be/L0b3JNFcJiI
 
    Both main and secondary target have very simillar amor and resilience, but secondary target recieves higher dmg on critical hits
    than main target. Thats because dmg on main target is reduced by resilience but on secondary target it is not.
 
    First hit on main target does 761 dmg. This dmg on main target was reduced by resilience, which i estimate about 20% dmg reduction
    (around 400 resil). So if 761 is 80% of unreduced dmg, then we get 951 as 100% of unreduced dmg. Secondary target recieved 958 so
    calculation was correct.
 
    Now im going to assume that this is correct behaviour and compare it to videos from retail, and then do same calculation as above
    to prove that dmg on warmane is higher than it should be.
 
2) Comparison
 
    A)
    https://youtu.be/3rbd02jJXy8?t=4m28s
    For your comfort see screen shots.
    https://imgur.com/a/zKgP4
 
    Warrior uses victory rush and cleave on main target.
    Combat log:
    Main target: Cleave 1928, Victory Rush 1760
    Secondary target: Cleave 2235. Demage from SS: Cleave 2011, Victory rush 1836.
 
    They are both hunters, and have similar armor with resilience. Im not going to include armor in my calculation and estimate
    resilience reduction at 15% (300 resil).
 
    Under warmane conditions:
    If 1928 is 85% of unreduced dmg, then 2331 is 100% of unreduced dmg. Yet he recieved 2011 dmg.
    If 1760 is 85% of unreduced dmg, then 2105 is 100% of unreduced dmg. Yet he recieved 1836
 
    As you can see difference is between 1928 and 2011 is not 15% as it would be on warmane, but 4.2% which is caused probably by armor
    differences.
 
    Note: If you disagree with any of my estimation for resilience, you can do the math for lower values too, it will always show
    difference. Note that epic pvp trinket was aviable in this video.
 
 
    B)
    https://youtu.be/3rbd02jJXy8?t=5m24s
    For your comfort see screen shot
    https://imgur.com/a/8Thry
 
    Warrior uses victory rush and melee swing on main target.
    Combat log:
    Main target: Melee swing 2234, Victory Rush 2338
    Secondary target: Demage from SS: Melee swing 2336, Victory rush 2444.
 
    They are both cloth users, but priest has higher armor due to inner fire and mark of wild. Note that warlock is affliction and has
    no soul link.
 
    Under warmane conditions:
    If 2234 is 85% of unreduced dmg, then 2628 is 100% of unreduced dmg. Yet he recieved 2336 dmg.
    If 2338 is 85% of unreduced dmg, then 2750 is 100% of unreduced dmg. Yet he recieved 2444
 
    As you can see difference is between 2234 and 2336 is not 15% as it would be on warmane, but 4.4% which is caused probably by armor
    differences.
 
    Note: If you disagree with any of my estimation for resilience, you can do the math for lower values too, it will always show
    difference. Note that epic pvp trinket was aviable in this video.
 
    C)
    https://youtu.be/pMg83CMEbys?t=5m12s
    For your comfort see screen shot
    https://imgur.com/a/hUTCD
 
    Warrior uses melee swing on main target.
    Main target:Melee swing 1029, 1254
    Secondary target: Demage from SS: 991, 1505
 
    They both have quite simillar armor and resilience. Im going to assume 15% resil reduction from both (300 resil). Amor difference
    can be calculated from SS caused by non criticals. I calculated 8% dmg reduction difference (including berserker stance).
 
    On first screen shot (With Armor+stance corrections)
    This is what happened on video
    If 1029 is 92% of unreduced dmg, then 1118 is 100% of unreduced dmg. Now, because warrior was in defensive stance we reduce this
    dmg by 10%. We get 1006, on vid warrior was hit for 991.
 
    This is what would happen on warmane
    If 1118 is 85% of unreduced dmg, then 1315 is 100% of unreduced dmg, then minus def stance we get 1183. Yet warrior got hit for
    991.
    On Second screen shot (With Armor+stance corrections)
 
    This is what happened on video
    If 1254 is 92% of unreduced dmg, then 1363 is 100% of unreduced dmg. Now, because warrior was in berserker stance we increase this
    dmg by 10%. We get 1499, on vid warrior was hit for 1505.
 
    This is what would happen on warmane
    If 1363 is 85% of unreduced dmg, then 1603 is 100% of unreduced dmg, then plus berserker stance we get 1763. Yet warrior got hit
    for 1505.
 
3) How it should work:
 
    I do not know exact formula for SS dmg, I only know that on warmane it does higher dmg on criticals then it did on retail. And the
    difference lies somehow in resilience. There are some options:
 
A)
 
    SS dmg caused by criticals is somehow still and handled as critical (only to get reduction from resil), even tho SS strikes appear
    as normal hits in combat log. This would make SS dmg to calculate from target armor+resil.
 
B)
 
    There is also option, where SS strikes would „copy“ dmg after the reduction from resilience of main target. One could argue that
    armor is rolled separately, why would it be different with resil. Argument to that is: Crit chance is affected by resilience of
    main target only, so should be the dmg reduction of critical.
 
C)
 
    Something other..
```

**Comment by Jerrythemagicdog** [comment]
The damage appears to be rolled on hit and is the same for both targets, only then we should roll for the potential target's armor and see what the reduction is.

https://hilbert.wordpress.com/sweeping-strikes-guide/

> I mentioned that SS will act as if your main attack would have hit your secondary target and thus predict how much damage it would have done. In order to do this in an accurate fashion, SS has to take armor into account. This tells us that main attacks on armored targets will do big SS damage on unarmored secondary targets, and vice versa.
> 
> This will usually work well. An easy test to verify this is finding two identical mobs (same level, armor and type), sunder one, pop SS and then hit them with your base fists. The sundered target will take the same amount of higher damage regardless of which mob you attack first. Your combat log would look something like this (with A having one sunder):
> 
> You hit A for 91.
> Your Sweeping Strikes hits B for 86.
> 
> You hit B for 86.
> Your Sweeping Strikes hits A for 91.

> 
> Before going too deep into the subject, you could say that the formula used by SS will consider three things when calculating the damage.
> 
> • The damage of the original attack (includes stat and % damage buffs)
> • The armor of the primary target (incl. buffed and reduced armor).
> • The armor of the secondary target (incl. buffed and reduced armor).

**Comment by kelno** [comment]
Fixed

**Comment by kelno** [comment]
So we know the damage on the two target is going to be different but:
- How does that interact with armor?
- How does that interact with resilience?
- How does that interact with various crit damage buffs/reduction from both units?

If I make 3000 crit damage on main target with 10% armor and 10% resilience, how much should that be on secondary target with 15% armor and 5% resilience?

**Comment by Rattacrash** [comment]
since a sweeping strike is not critically hit resilience on target B should not be taken into account at all. reduction due to resilience is a percent modifyer.
the patchnotes of patch 2.1.0 state:
"This ability will no longer be modified erroneously on additional targets by percent modifiers to your damage."
https://wowwiki.fandom.com/wiki/Sweeping_Strikes


sweeping strike should copy the damage aplyed to target A before armor and buffs/debuffs on target A that would increase or decrease damage on this target (any percent modifyers increasing or decreasing damage of the warrior performing the attacks need to be taken into account) and apply that on target B reduced only by target B's armor but not target B's resilience, since the sweeping strike hit is not a critical hit even tho its damage is the copy of a critical hit.
"Damage dealt from a Sweeping Strike will never crit. "
https://wowwiki.fandom.com/wiki/Sweeping_Strikes

btw currentl implementation is still not copying the damage of critical hits. if target A is hit critically the damage on target B is like, as if target A would not have been critically hit

**Comment by Rattacrash** [comment]
to play with ur example of 3000 damage it would be like:
damage on A= 3000x0.9x0.9 critical hit
damage on B= 3000x0.85 sweeping strike

**Comment by kelno** [comment]
Okay I've updated again

**Comment by Rattacrash** [comment]
when will this update be in effect?

**Comment by Jerrythemagicdog** [comment]
Issue still remains - crit damage is not copied to the secondary target(s)

**Comment by kelno** [comment]
Okay, for the future if someones tests this again: Make sure to test both white hits and abilities and they are handled completely differently

**Comment by kelno** [comment]
Aand updated again with revision 12562

**Comment by Jerrythemagicdog** [comment]
Fixed
