### ISSUE TITLE
mouseover target

### ISSUE THREAD

**Issue by earthworm-jim** [SunstriderEmu/BugTracker#1441]
**Bug description**
[Uncertain if this is a bug] Some abilities (e.g. Wing Clip), when used with target=mouseover condition, cause mouseover unit to become target.

**Steps to reproduce**
(hunter example)
1. Shoot at one unit while standing in melee range of another
2. Use a mouseover macro to Wing Clip the adjacent unit
I used the following:
```
/cast [nomod,harm]Raptor Strike
/cast [mod:RCTRL,target=mouseover,harm][nomod,harm]Wing Clip;[mod:LCTRL,target=mouseover,harm][mod:shift,harm]Concussive Shot
/castrandom [pet,target=pettarget,harm]Kill Command
```

Sunstrider rev. 12418 (a377cdffdc5d) 2019-09-24 19:33:38 +0200 (dev branch) (Unix, Debug, Static)

**Comment by kelno** [comment]
Some idea to test it:
If the same doesn't happen with focus, then it's probably just the client deciding to change target (and we can't change it)

**Comment by Jerrythemagicdog** [comment]
Maybe connected to the attribute "SPELL_ATTR1_MELEE_COMBAT_START"

**Comment by kelno** [comment]
As a note, we had the same issue for charge/intercept

**Comment by Jerrythemagicdog** [comment]
There's a similar one for Spell Lock currrently if I recall.

**Comment by kelno** [comment]
I tried here, client explicitly asks for a target change. I believe this can't be changed. I'll close it, unless we have proof some other servers somehow manage to avoid that
