### ISSUE TITLE
Personal rating in an arena team is not updated after flush until a player plays a game.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1442]
**Describe the bug**
Title.

**To Reproduce**
1. Play some games
2. .flusharenapoints
3. The personal rating is gone until a player plays one game

Screenshot of the problem:
https://cdn.discordapp.com/attachments/198080855833313290/626762050953150484/unknown.png

**Comment by hufsa** [comment]
Fixed
