### ISSUE TITLE
[Warrior] Intervene has no effect sometimes

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1444]
**Describe the bug**
Intervene seems to have no effect sometimes.

Clip 1: https://www.twitch.tv/videos/486279909?t=02h40m34s 
1. Rogue casts Blind on Shaman
2. Rogue Vanishes
3. Warrior Intervenes Shaman
4. Rogue Saps Shaman despite Intervene buff being up already

Clip 2: https://www.twitch.tv/videos/486279909?t=02h11m33s
Same scenario as Clip 1

**To Reproduce**
Unsure of reproduce steps as of now.

Worth noting is that Intervene does not work through LoS (the attack is not redirected to the Warrior if the recipient of the attack is not in LoS of the Warrior) but it doesn't seem to be the case in those clips.

**Comment by kelno** [comment]
Fixed
