### ISSUE TITLE
[Rogue] Entrapment doesn't get removed by Cloak of Shadows

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1445]
**Describe the bug**
Title.

**To Reproduce**
1. Cast Entrapment (19185) on a Rogue 
2. Attempt to CoS (31224) it 

Entrapment is a magical effect that can be dispeled.

**Comment by kelno** [comment]
Entrapment be physical my man

**Comment by kelno** [comment]
Entrapment is magic dispel type but of the physical school. Cloak of Shadows affect the school. Need proof it should be removed

**Comment by Jerrythemagicdog** [comment]
Only source I could find:

http://www.arenajunkies.com/topic/7244-what-type-of-cc-cant-you-cloak-out-of/

One person says you can, the other person says you can't. 

Person 1 (apparently a Hunter with some Gladiator titles)
> Cloak of skill will effectively remove entangling roots and frost nova / frost bite. I think it works on entrapment as well, but only the root effect, the snare effect from frost trap stays. 

Person 2 (apparently a Rogue with no attached info)
> entrapment effect hunters can produce is also a physical effect that you cannot cloak out of (however you can vanish out of it).

For whatever it's worth, _other projects_ had it cloakable, maybe it was a change introduced in WotLK. Also feels understandable as to why this appeared as a bug report - Magical root effect that can't be Cloaked (?).

**Comment by kelno** [comment]
A similar issue is discussed here on retail (2011) for a web spell that's shown as dispel type magic but is actually of the school physical :
https://us.battle.net/forums/en/wow/topic/2416113521#post-3
(that spell isn't dispellable by cloak either)

**Comment by kelno** [comment]
More from retail 2011:
https://us.battle.net/forums/en/wow/topic/2267585125
"I usually dont have too much trouble with traps as my situational awareness is pretty good, however with an entrapment spec'd hunter I really dont have a chance (cloak wont break entrapment immobilize)."

**Comment by kelno** [comment]
On top of that I'd say it's very consistent with how the spell works with is a proof in itself.

**Comment by kelno** [comment]
Closing for now, the current behavior is blizzlike. We might decide to make a custom rule there later on, maaaybe.
