### ISSUE TITLE
Charge effects appear as teleports if the speed was different before the charge

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1446]
**Describe the bug**
Whenever the warrior's speed changes during a charge, he takes a break during it to regain some vital energy and contemplate the imponderables.

https://www.twitch.tv/videos/486678417?t=26m03s

1. Cast Charge on player B as player A
2. Affect player A with a movement change during the charge
3. Player A will take his time and then start the charge again

**Comment by Jerrythemagicdog** [comment]
This is also very easily observable with any sort of speed effect that's present before the Charge.
For example:
Scenario 1:
1. Mount up on a Warrior (player A)
2. Run and charge player B
3. The charge will be a teleport

Scenario 2:
1. Travel form as a Druid (player A)
2. Run and use a Feral Charge macro on player B (that shifts you into form)
3. The charge will be a teleport

**Comment by kelno** [comment]
Did a fixie

**Comment by Jerrythemagicdog** [comment]
Tested with Scenario 1:

> Mount up on a Warrior (player A)
> Run and charge player B
> The charge will be a teleport

still results in a teleport.

**Comment by kelno** [comment]
Okay so:
What's ruining it is that:
1 - Player starts charge - Speed is changed so an ack is sent
2 - Charge movement is sent
3 - During charge, players answer the ack and a MSG_MOVE_SET_RUN_SPEED is propagated to everyone

MSG_MOVE_SET_RUN_SPEED contains a position and stops the movement visually.

**Comment by kelno** [comment]
Fixed
