### ISSUE TITLE
[Mage] Water Elemental doesn't get removed when it dies

### ISSUE THREAD

**Issue by somnu** [SunstriderEmu/BugTracker#1447]
**Describe the bug**
When someone kills the water elemental, it still displays as your pet but dead. Its portrait still appears under the player's portrait in the top left. UI somehow doesn't recognize it dead. The only time it disappears is when its timer runs out. This leads to macros like this not working properly:

/cast [nopet] Summon Water Elemental

**To Reproduce**
1. Make a mage
2. Summon pet
3. Get it killed
4. Try resummoning it using the macro.

**Expected behavior**
When your pet gets killed it should get removed from the game and its portrait should also disappear.

**Comment by Jerrythemagicdog** [comment]
Related commits: https://github.com/kelno/sunstrider/commit/ec43ce7d546af7458360ec4a05f344d245ee6128 and https://github.com/kelno/sunstrider/commit/c509b174d1a691863a04ddb2ea6c99972d08dc58 and https://github.com/kelno/sunstrider/commit/57c9bbaf0ded1e783d68e50f5e50016f54686fb1

**Comment by kelno** [comment]
Fixed
