### ISSUE TITLE
[Mage] Cone of Cold ignores line of sight

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1448]
**Describe the bug**
Mage's spell Cone of Cold (120) ignores line of sight completely.

https://imgur.com/1QUuCiT

**To Reproduce**
1. Have player A and player B line of sight each other.
2. Player A casts Cone of Cold (120) on player B.
3. Player B is afflicted by Cone of Cold through line of sight.

**Expected behavior**
Cone of Cold should not ignore line of sight.

**Comment by kelno** [comment]
Fixed
