### ISSUE TITLE
[Mage] Water Elemental spell damage Waterbolt scaling is too high.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1449]
**Describe the bug**
After recent changes (possibly https://github.com/kelno/sunstrider/commit/96b8a3f8f0da2907273671035b4b88a2a70cab35 or https://github.com/kelno/sunstrider/commit/fe4fee016cbaa5e9d985b26efea4789d4075db29) Mage's Water Elemental (spell 31687, creature 510) seems to be scaling 1:1 with the Mage's spell power. 

The correct scaling is 0.4 of Mage's frost spell damage (already in the core, seems to be ignored or something else is added to it.)

**Comment by kelno** [comment]
Update:
Pet uses correctly 0.4 spell power

**Comment by Jerrythemagicdog** [comment]
> Pet +dmg should be 40% of mage frost dmg. This value is being mentioned here:
> http://web.archive.org/web/20081013092849/http://elitistjerks.com:80/f15/t9363-damage_coefficients/
> 
> And also here:
> http://www.wowhead.com/spell=31687/summon-water-elemental#comments:id=6245:reply=10055
> 
> Retail, pet dmg at 900 ish player bonus spell dmg:
> https://imgur.com/a/iOzLYJ1
> 
> As you can see, on retail dmg dealt by waterbolt is higher even on lower player spell dmg.
> The calculation should be:
> (Player bonus frost dmg)*0,4*(2,5/3,5)+(waterbolt base dmg).

**Comment by kelno** [comment]
Not bugged, it's exactly how it works right now
