### ISSUE TITLE
Non combat spells being casted are not canceled on entering combat

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1451]
**Describe the bug**
Title.

**To Reproduce**
1. Start a Ressurection spell on your dead friend.
2. Enemy tries to stop it because you're stuck in a 1v1 for 20 years and he can't afford to lose that match.
3. He successfully attacks you but the Ressurect cast time doesn't stop!

**(The cast time and fails at the end - doesn't finish but it's very misleading.)**

**Comment by hufsa** [comment]
Same with casting mount spells

**Comment by Jerrythemagicdog** [comment]
Something about Attributes 0x10000000 | SPELL_ATTR0_CANT_USED_IN_COMBAT perhaps.

**Comment by kelno** [comment]
Fixed
