### ISSUE TITLE
[Rogue] Shadowstep provides too much bonus damage

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1452]
problem 1.
shadowstep doesn't increase damage of all damaging abilities (e.g. kick, deadly throw)

problem 2.
the damage increase % seems to be incorrect. in some cases it's less that 20% in some others it's close to 50% 
i did some tests and my gouge does 64 damage flat, it always hits for that much.
with shadowstep buff it hits for 92 (instead of 77)
for 1cp rupture 125>146 (instead of 150)
i also noticed how shs ghostly strike and eviscerate hit extremely hard, to the point where it's just ridiculous. this may be the reason why or one of the reasons

**Comment by Jerrythemagicdog** [comment]
problem 1:
Looking at the spell data (to dev: 36563, proc flag DONE_SPELL_MELEE_DMG_CLASS from dbc) it seems intended that it's only consumed on melee damaging abilities (Kick isn't considered that).

problem 2:
There is indeed a problem with Gouge that needs investigating, maybe affecting other spells too (strangely enough doesn't seem to be affecting Hemorrhage (?))

**Comment by ramadansteve** [comment]
according to my tests shs doesn't affect deadly throw, envenom and kick (well according to jerry it shouldn't so exclude this one i guess)

**Comment by kelno** [comment]
Fixed
