### ISSUE TITLE
[Priest] Inner Focus removes the cost from the spell even if it's dispeled during the cast

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1454]
if you begin to cast something (e.g. greater heal) with inner focus up and it gets dispelled during the cast, the cast will still succeed even if you dont have enough mana to cast that spell

**Comment by Jerrythemagicdog** [comment]
**To reproduce**:
1. Get the priest to be low on mana
2. .cast 14751 (Inner Focus)
3. Cast a Greater Heal
4. Cancel the Inner Focus / dispel it mid cast
5. The cast still goes through while it should be canceled

**Comment by kelno** [comment]
Fixed
