### ISSUE TITLE
[Warlock] Spell Lock cooldown is not correctly reset for a new pet if the old pet dies

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1456]
sometimes when you summon a new pet through fel domination the spell lock CD doesn't reset for the new pet. seems like it doesn't happen consistently, i can link a clip where it didn't reset for my warlock in  the arena if needed

**Comment by Jerrythemagicdog** [comment]
Yes please.

**Comment by ramadansteve** [comment]
https://www.twitch.tv/videos/487162949?t=02h41m02s first pet dies, he uses spell lock blanket before it dies, gets a new one and wants to lock shamans cast but it's on cd

**Comment by Jerrythemagicdog** [comment]
Possible clue: the warlock is stunned by Intercept at the same time maybe that prevents him to cast his pet's spell for some reason.

**Comment by ramadansteve** [comment]
> Possible clue: the warlock is stunned by Intercept at the same time maybe that prevents him to cast his pet's spell for some reason.

no that's not the case, cd didn't reset he specifically told me about it

**Comment by earthworm-jim** [comment]
http://www.arenajunkies.com/topic/33853-spell-lock-feldom-spell-lock-how/

**Comment by ramadansteve** [comment]
"Posted 17 August 2008 - 05:41 PM

How hard it is to realize that this "trick" only works in Arenas, and doesn't work in the outdoors. What Sickup said is what all those retards need to read before posting "Pet needs to die". "

**Comment by kelno** [comment]
Fixed with 13043

**Comment by Jerrythemagicdog** [comment]
I've been notified that the issue still happens "sometimes"

**Comment by kelno** [comment]
Will need to know how to reproduce then!

**Comment by Jerrythemagicdog** [comment]
I've tried locally and so far 10/10 times it's not reset.
Steps:
1. Summon a Felhunter
2. .debug arena
3. Enter with two characters
4. Order the Felhunter to Spell Lock the target
5. Use Fel Domination and summon another Felhunter
6. The Spell Lock cooldown is not reset

The same case has happened on two characters but I've also seen the opposite (it resets correctly) happen on the PTR in matches.

**Comment by kelno** [comment]
Thanks.
Fixed in 13136
