### ISSUE TITLE
[Rogue] Relentless Strikes provides 25 energy even when the ability is unsuccessful

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1459]
should only procc on hit not on use
e.g. i eviscerate with 5 cp (100% relentless strikes chance procc) and it gets dodged, i still get 25 energy

**Comment by Jerrythemagicdog** [comment]
Need proof.

**Comment by Jerrythemagicdog** [comment]
Some loose sources:
WM bugtracker (WoTLK): 

> "This is supposed to happen; it's oft. talked about for Mut PvE because of how it interacts with Envenom and energy capping. "Fixing" this is actually creating a bug."

But then, the status is changed to fixed so it was implemented in the end.

Neilyo 13:

https://youtu.be/eJWNMCD8SMU?t=417

Priest dodges a 5 CP Kidney Shot and the Rogue does not get 25 energy (blurry but still visible)

Then, some time later (like 10 seconds after) he uses Expose Armor on the same priest and does get the refund (confirming he has the talent in the first place).

**Comment by kelno** [comment]
Fixed
