### ISSUE TITLE
[Mage] Polymorph regens too much hp per tick

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1460]
currently regenerates 40% of target's max hp per tick. should be lower, but not sure how much around 10-20%

**Comment by hufsa** [comment]
RegenTimer while polymorphed should be 1s.
addValue = maxValue / 10;

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.

**Comment by kelno** [comment]
The regen timer isn't fixed though

**Comment by Jerrythemagicdog** [comment]
The regen timer is fine.
