### ISSUE TITLE
Crystal Spire of Karabor only procs off direct heals

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1462]
Problem :  Crystal Spire of Karabor proc only after direct heals . 

How it should work :  Should proc after : Earth Shield , Healing Grace , and heal trinket item "Vial of the sunwell" . 

Proofs :  

1) https://youtu.be/2ignGOGSeRU?t=2m10s  Earth Shield and Nature's guardian both with proc 

2) Wowhead comments :  

"The proc on this CAN proc on Nature's Guardian and Earth Shield if it is casted on yourself.  "    

"The mace proc now works if your target receives the heal and he is lower then 50 %. It doesn't matter if he ends up with +50% hp after. 

The mace is insane for PvP Shamans because when your hp goes below 50 % the proc will work on each Earthshield tick and Natures guardian proc.  

3) http://www.arenajunkies.com/topic/26591-pve-gear-in-the-arena/ 
 
"Crystal Spire of Karabor is easily the single, strongest, Resto Shaman PVP gear. Spire procs on each earth shield tick <50% are simply amazing.''

"Yes, and Nature's Guardian." 

About item  : item=34471   Also should generate proc mace  . Cos mechanic of this trinket work like any normal heal .  affected reduce/increase  healing effects , Spiritual Healing, increasing the healing provided by 10%. etc .

https://www.wowhead.com/item=34471/vial-of-the-sunwell&bonus=4080#dropped-by  

"I also found that it can trigger the effect of Crystal Spire of Karabor when target below 50% health." 

https://legacy-wow.com/tbc-shaman-guide/ 
"'8) The healing done by the trinket will activiate the healing proc from Illidan’s [Crystal Spire of Karabor] "

**Comment by Jerrythemagicdog** [comment]
Thanks for all the research!

**Comment by kelno** [comment]
Fixed
