### ISSUE TITLE
Overriding your own spells shouldn't always be allowed

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1465]
**Describe the bug**
Title.
Currently we always allow overriding our own spells which apparently shouldn't always be the case (for example Frostbite - Frost Nova: https://github.com/SunstriderEmu/BugTracker/issues/1464). 

Putting this on low priority as the implications are not big (in fact the linked issue is making the effect stronger rather than weaker).

Maybe some rule could be made for procs with < 100% chance.

**Comment by Jumpka** [comment]
I know it's paladin bias talking, but cleansing frost nova / frostbite and still taking the shatter damage because the other effect is up is really annoying. Because cleanse only removes one debuff, all those stacking rules make a pretty big difference for paladin.

**Comment by Jerrythemagicdog** [comment]
Players are also able to override their own slows with lesser slows currently (e.g. Mage overriding CoC with Frostbolt or orverriding Imp Blizz with Frostbolt).

**Comment by kelno** [comment]
@Jumpka I don't understand what you're saying. We don't allow them to stack currently, we just make it so the "a stronger effect is active" rule isn't active if it's your own spell so you can replace them.

**Comment by Jumpka** [comment]
Just tested in game, you can frostbite and frost nova someone at the same time, which means even if you land a cleanse on one, you'll still be frozen by the other one.

**Comment by kelno** [comment]
Okay thanks.
I fixed the main issue here. 
The frost nova/frostbite thing is another thing entirely.

**Comment by Jerrythemagicdog** [comment]
Tested the slows and the usual suspects - works.
The Frost Nova / Frostbite issue is moved here: https://github.com/SunstriderEmu/BugTracker/issues/1464
