### ISSUE TITLE
[Item]Magic Dust

### ISSUE THREAD

**Issue by earthworm-jim** [SunstriderEmu/BugTracker#1467]
**Bug description**
Duration in PvP reduced to 10 sec.

**Expected behavior**
> Noyomo on 2008/08/19 (Patch 2.4.3)
Actually this can last up to 30 seconds, unlike any other CC in PvP, though it's fairly rare, and if the target has like a mark of the wild or any resistances at all, it gets resisted a lot. [wowhead](https://www.wowhead.com/item=2091/magic-dust#comments:id=236994:reply=346625)

[drakedog7@6:05](https://youtu.be/kDbmRr6PsNA?t=363)
----
imo 30s is op, but the item is hard to come by and not usable in arena. i'd either reduce it to 15-20s or make it more obtainable and keep it as is (10s) (note: it shares cd with nades)

**Comment by Jerrythemagicdog** [comment]
Patch 3.1.0 (14-Apr-2009): Magic Dust now has a 10 second PvP duration.

**Comment by kelno** [comment]
Yeaaah I think we'll keep that one as a custom change
