### ISSUE TITLE
[Spell][Hunter]Scare Beast

### ISSUE THREAD

**Issue by ghost** [SunstriderEmu/BugTracker#1468]
**Bug description**
Higher rank replaces lower in the spellbook when learned, meaning only the highest rank can be used.

**Expected behavior**
All ranks displayed in the spellbook and usable.

**Comment by Jerrythemagicdog** [comment]
Is there any reason why it should be displayed? Many other abilities are like that too. I can see the mana cost difference is 40 mana between R1 and R3.

**Comment by hufsa** [comment]
Abilities does this, spells however, should not "stack" iirc.

**Comment by earthworm-jim** [comment]
Because in PvP you have no reason to use max rank, so rank1 saves mana...

**Comment by z5n** [comment]
still confirmed rev. 35257

**Comment by z5n** [comment]
fixed since
