### ISSUE TITLE
Fix mismatching spell_affect

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#1470]
spell_affect table should only contain rank 1.  Need to clean those that are of above ranks.
This has been mostly cleaned automatically but there is some data left where the ranks data were not matching.
Currently in those cases the core will only use the rank 1.

Here are the talents in need of clean/fix:

17323
29189
16130
17119
35396
31845
29191
17120
35397
16217

**Comment by Jerrythemagicdog** [comment]
Fixed
