### ISSUE TITLE
[Paladin] Libram of Zeal

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1473]
'increases melee attack power bonus by 68' - correct in the tooltip but in fact gives 20 AP less than it should
'holy damage increase of your judgement of the crusader by 47' - doesn't work, at least doesn't show in the tooltip

**Comment by Jerrythemagicdog** [comment]
The tooltip and attack power increase in the character panel are correct for the first effect, how was it determined that it's less attack power?

The second effect works but it's not displayed in the tooltip (tested the damage with Judgement of Righteousness)

**Comment by ramadansteve** [comment]
> The tooltip and attack power increase in the character panel are correct for the first effect, how was it determined that it's less attack power?
> 
> The second effect works but it's not displayed in the tooltip (tested the damage with Judgement of Righteousness) - the tooltip on the debuff will not be updated similarly to a Mage's Frostbolt with and without Permafrost.

well somehow when i checked it in the character panel it would give me 20 less AP that it was supposed to

**Comment by Jerrythemagicdog** [comment]
Fixed!
