### ISSUE TITLE
[Shaman] Chain Heal doesn't bounce off full health targets

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1475]
**Describe the bug**
Title.

**Expected behavior**
It should bounce off full health targets.

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1466

**Comment by kelno** [comment]
It doesn't prevent bouncing off a full health target, it just doesn't allow to bounce TO a full health target.
