### ISSUE TITLE
Pets that repeatedly auto cast move towards the target between casts

### ISSUE THREAD

**Issue by hufsa** [SunstriderEmu/BugTracker#1476]
**Describe the bug**
Pets will slide forward between each cast when you order your Water Elemental or Imp to start attacking with Waterbolt or Firebolt. 

**To Reproduce**
1. Cast Summon Water Elemental (.cast 31687)
2. Order the Water Elemental to attack a dummy
3. Observe the pet slide forward between each cast. Eventually, the pet will even start sliding backwards once it has reached the target.

**Expected behavior**
The pet should remain in place for all eternity if the target is in range/los.

**Screenshots/videos**
https://streamable.com/5illj

**Additional context**
This used to work for us before and regressed recently.

**Comment by Jerrythemagicdog** [comment]
Related to pets moving behind their target against PvE opponents perhaps (which maybe should be disabled for caster creatures?) or alternatively the "hug the opponent" change we did for Felhunter and Water Elemental

**Comment by kelno** [comment]
Seems fixed
