### ISSUE TITLE
[Hunter] Traps are invisible to players other than rogues even just after planting

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1477]
when hunter puts down a trap it should be visible for a while. i believe you should only be able to see them if you're close 
https://youtu.be/dc0WrORiHmM?t=250
currently only visible to rogues

you might consider to keep it working the way it currently does because with the way traps are working now (affect the closest target) it's gonna be easier to eat traps which may or may not make hunters' lives miserable

**Comment by Jerrythemagicdog** [comment]
I can add that they are also sometimes invisible to Rogues, for example when a Hunter sets up a trap at the start of the arena (maybe has to do with range or line of sight to the Rogue).

**Comment by Jerrythemagicdog** [comment]
Looks like it.

**Comment by kelno** [comment]
Fixed

**Comment by earthworm-jim** [comment]
are you sure traps should be visible while armed from any distance (they are currently) instead of only in melee range?  i remember reading how hunters used to move right after laying a trap to cancel the animation, so the opponent is unaware of it. @kelno

**Comment by earthworm-jim** [comment]
animation hiding was a thing until cata apparently:
https://www.wowhead.com/forums&topic=190303
https://eu.battle.net/forums/en/wow/topic/1622906599

**Comment by kelno** [comment]
"Animation hiding" seems the idea to jump to hide the kneeling animation and not related to the trap itself.
But other than, if animation hiding is even a thing it's very probable that the current implementation is wrong and we shouldn't see them far away. 
I'm not sure they actually become invisible at any point then, maybe they're visible only from very close?
Also we need to find/choose a distance then

**Comment by kelno** [comment]
New implementation just makes them visible when close.
Also rogues can see them from further thanks to "Detect Traps" passive.
