### ISSUE TITLE
Players get kicked to login screen when logging out to change characters

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1478]
**Describe the bug**
Title.

**To Reproduce**
1. Log on character A
2. Run around for a bit (not sure if needed)
3. Log out
4. Attempt to log in to another character / create a character
5. Server decides to kick you

I have heard reports from numerous people confirming this issue and I have experienced it myself on a number of occasions.

**Comment by InhumanGM** [comment]
Issue has since been resolved.
