### ISSUE TITLE
[Rogue] Hemorrhage benefits from the initial Hemorrhage debuff application

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1480]
**Describe the bug**
Title.

**To Reproduce**
1. .cast 26864
2. Observe that the stack amount is 9 instead of 10
3. Hemorrhage already consumed one charge

**Expected behavior**
It should not benefit from the initial application and apply the debuff with 10 charges.

For example:
https://youtu.be/fT_aZfg9AP0?t=204

We can see that the debuff is applied with 10 (0 on his UI) and then an offhand hit consumes it and the number goes down to 9.

**Comment by kelno** [comment]
Only happen on refresh apparently

**Comment by woiwoz** [comment]
I just came home from the hospital, translating and trying to understand the problem. Ha-ha

**Comment by Jerrythemagicdog** [comment]
Here's a case where the Rogue refreshes a Hemo: 
https://youtu.be/jHtAqPh4yVQ?t=343
The counter goes back to 10

**Comment by Jerrythemagicdog** [comment]
Fixed with next update.
