### ISSUE TITLE
[Paladin] Seal of the Crusader reduces the overall damage done by the paladin (wrongly includes abilities like Crusader Strike)

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1482]
**Describe the bug**
Title.
Spell ID: 27158
Tooltip states that the attacks should do reduced damage as a compensation for the faster attack speed. Currently not the case.
Less damage part is NYI.

**Comment by kelno** [comment]
Fixed! To clarify how this works:

Seal of the Crusader adds attack power, that part isn't affected by the reduction.
The 40% speed increase damage boost is canceled by the damage reduction so keep the same DPS as before speed increase.
So the weapon damage is simply divided by 1.4 to compensate.

**Comment by kelno** [comment]
Fixed

**Comment by Jerrythemagicdog** [comment]
Currently Seal of the Crusader also reduces damage done by abilities such as Crusader Strike. It should only reduce the damage of auto-swings (white damage).

**Comment by kelno** [comment]
(We're currently checking if it should just affects white swings or everything)

**Comment by Jerrythemagicdog** [comment]
First mention:
https://eu.forums.blizzard.com/en/wow/t/paladin-seal-of-the-crusader/91515/5

> On a side note, the seal is semi-useful in TBC since the damage reduction only applies to auto-attacks, so you can pop it and then use Crusader Strike for quite a bit of damage at the beginning of a fight (and then quickly judge and switch to Righteousness/Blood/Command). Doing this correctly without losing on damage from your next seal, however, required macros… which 90% of rets back then didn’t use.

**Comment by kelno** [comment]
Sooo, back on this:
The intent is to reduce melee damage to cancel the speed increase (and maintain same dps),
But we know blizzard did it in a hacky way by changing the weapon damage for real, so this damage reduction would also affects spells such as Crusader Strike, or twisting into Seal of Command. 
We decide here to doing it the way it was intended by reducing only white damage, that's less code and cleaner.
Blizzard hackfixed in 2.4.2 with: "Seal of the Crusader: This ability now increases the damage dealt by Crusader Strike by 40%." to cancel that bug. We don't need that fix here with the rule about only affecting white hits.

Effective starting 13035
