### ISSUE TITLE
[Paladin] Seal twisting mechanic

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1484]
**Describe the bug**
Seal twisting was a mechanic possible during TBC that increased the damage retribution paladins did in PvP and in PvE. One might say it's an essential part of playing a retribution paladin as without it the damage is fairly insignificant (even with that mechanic it still is compared to classes like Hunter and Rogue).

For this mechanic to work correctly:
 "Seal of command should have a 0.5 sec delay from the moment melee swing happens, this will allow the retail TBC ''seal twisting'' if you are fast enough ofc."

Some retail sources:
1. https://youtu.be/w5YpDd4z7gw
2. https://www.youtube.com/watch?v=1ud1KQvvs1M

YT comment under one of the videos:

> 1. SoB proc for ANY weapon damage. 
> 2. SoC proc - weapong damage. 
> 3. SoC have "fly time", its means when SoC proc - damage will inflict after 0.5 sec.
> 4. We see animation of SoC, change seal to seal of blood (sob) = we have SoC proc + SoB proc.

**Comment by kelno** [comment]
That's good old uncle spell batching in action here

**Comment by hufsa** [comment]
+1 for spell batching

**Comment by kelno** [comment]
Implemented a thing. It's a bit visually different from retail as you can see both aura up at the same time but it doesn't change how it plays.
The delay might need to be tweaked

**Comment by Jerrythemagicdog** [comment]
Tested, works as expected from the retail footage. 
The delay seems very fair and consistent in the current (250) implementation.

**Comment by Jumpka** [comment]
If you're trying to implement retail like twisting, then this is nothing like it. First of all, you have to make sure you can't twist SoC into different rank of SoC, since that is possible with the current workaround. Easy and probably correct way of fixing this is implementing short SoC internal CD, which is missing on this server and existed on retail https://theholylight.wordpress.com/2007/07/02/procs-per-minute/ (you can get auto + WF + 2x SoC on this server right now, that's a bug).
The normal SoC > SoB twist isn't retail like either. I wasn't able to get a single double SoB proc (pretty much every twist in those posted videos has double SoB procs).
The double SoB proc happened since SoC was treated as an auto-attack mechanics wise, that's why SoC could proc WF (at least that was the conclusion on EJ ret pally thread, unfortunately links aren't working anymore, unless someone knows about an archive, all I have is https://github.com/ccshiro/cc-buglist/issues/1629 ). This conclusion is also included in the latest release of TBC rawr: https://rawr.codeplex.com/releases/view/17339
If you switch from SoB to SoC, the DPS from WF totem increases.
If you implement short ICDs on both WF and SoC and make SoC be treated as an auto attack, everything should be pretty much retail-like.

**Comment by Jerrythemagicdog** [comment]
Thanks for testing!
There is a short ICD on Seal of Command (added pretty recently, 13th of October, so depends when you've tried that) could be wrong, though.

**Comment by Jumpka** [comment]
I haven't tried auto + WF proccing 2x SoC recently, but the double SoC twist is working right now, so maybe the ICD is not shared between different ranks.

**Comment by networm555** [comment]
cant seal twist. maybe im doing something wrong.

**Comment by Jerrythemagicdog** [comment]
The implementation is not complete yet!

**Comment by kelno** [comment]
Updated SoC to allow WF to proc

**Comment by kelno** [comment]
Updated SoB to allow proccing from yellow attacks. This allows for SoB to proc twice when twisting SoC > SoB

**Comment by kelno** [comment]
Current question:
Can SoB procs other melee effects like WF of SoC?

**Comment by kelno** [comment]
SoC already has a cooldown since 7 october, can it really happen currently?

**Comment by kelno** [comment]
Updated: Can't twist SoC into SoC anymore

**Comment by kelno** [comment]
To summarize

Current questions:
- SoC already has a cooldown of 1s since 7 october, can it really happen currently?
- Can SoB procs SoC?

To improve:
- Make seals linger a bit when judged as well (not only when replaced by another seal)
- Make it so Judgement takes the most recent one

**Comment by Jerrythemagicdog** [comment]
> [3:36 PM] B: You're saying its 2 seconds that command lingers after removal?
> [3:38 PM] B: or is it 0.2 seconds?
> [3:38 PM] A: oh 2 seconds? no
> [3:38 PM] A: I think you can see it visually on your buffs
> [3:38 PM] A: how long it lingers for
> [3:38 PM] B: hm
> [3:38 PM] B: oh
> [3:39 PM] B: That gives a problem if you're to judge Command before the twist.
> [3:39 PM] B: Because it removes it then.
> [3:41 PM] A: okay
> [3:41 PM] A: yeah, that makes sense
> [3:41 PM] B: no wonder it wasn't working then
> [3:42 PM] A: so you should be able to judge it then and benefit from its extra attack?
> [3:42 PM] B: yes
> [3:43 PM] B: you don't have to but its optimal if you want the command damage instead of the blood one. It depends which you want when.
> [3:43 PM] A: hmm okay
> [3:44 PM] A: let me forward that information
> [3:44 PM] B: hm
> [3:44 PM] B: a judge does the same as changing a seal, it removes the current seal.
> [3:45 PM] B: But you only changed the part where it lingers when changing the seal and not with a judge as well.
> [3:47 PM] A: okay I see
> [3:47 PM] A: thanks
> [3:51 PM] B: I found some other weird interaction due to the lingering seal.
> [3:51 PM] A: okay
> [3:53 PM] B: So I tried to switch to blood first and then judge, it judges the command after I swapped seal. It is giving two variations I think on the time I changed. One is Auto hit, command hit, command judge, blood hit.
> The other one is command judge, blood hit, auto hit, blood hit.
> [3:53 PM] B: There we go!

Afterthought:
> Ideally if we could have this lingering effect for the Judgements as well (meaning if we use a Judgement then the Seal doesn't get consumed instantly and then when we have two Seals at the same time (in this mid-twisting phase) then the new Seal should be consumed by the Judgement (currently is the old one).

**Comment by networm555** [comment]
any news about this topic? If you cant implement batching its a good idea to let seals stack for one- two global's its a radical decision but without twisting retards are utterly useless. Also it will make retards strong in pvp.  Also its a rng class. So not a big problem. It wont proc too often

**Comment by kelno** [comment]
We'll definitely work on this more soon

**Comment by kelno** [comment]
Also see: https://github.com/SunstriderEmu/BugTracker/issues/1795

**Comment by Rettiy** [comment]
> Also see: #1795

Actually managed to get around this weird current state with Cancelaura macros so do whatever.

**Comment by Jerrythemagicdog** [comment]
#1795 

That problem should be resolved if we implement this part of my previous post:

> Ideally if we could have this lingering effect for the Judgements as well (meaning if we use a Judgement then the Seal doesn't get consumed instantly and then when we have two Seals at the same time (in this mid-twisting phase) then the new Seal should be consumed by the Judgement (currently is the old one).

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1863

**Comment by kelno** [comment]
Updated, the newer aura will be prioritized now
