### ISSUE TITLE
[Warrior] Sweeping Strikes crit damage

### ISSUE THREAD

**Issue by Rattacrash** [SunstriderEmu/BugTracker#1486]
the problem:

as it is of now, a critical hit does not sweep the critical damage to the 2nd target.

if 2 mobs r fought at the same time, any critical hit that is sweped by sweeping strikes does not apply the damage of the actual hit on the 2nd target but the damage that would have happened if that critical hit would not have been a critical hit

https://ibb.co/nPN6F4q

how it should work:

tho sweeping strike cannot crit it self, it should copy the damage of the hit that triggered the sweeping strike, before the reduction of armor of the first target, on the 2nd target minus the reduction due to armor of the 2nd target. so if the first target recieves a critically hit, the ammount of damage, of that critical hit, before armor, should be applyed on the 2nd target minus the armor of the 2nd target, but the sweeping strike it self will not show as a critical hit. this should aply for any attacks that trigger a sweeping strike with the exeption of execute, execute has its own behaviour noted and fixed in a diffrent post here.

since i do not have access to wow classic i cannot show a picture of the combat logs there that will proof my statemeant to be right, maybe someone else can jump in and prove me right. finding information on the web of such particular matters is very mushy.

**Comment by Jerrythemagicdog** [comment]
It does indeed deal normal damage currently while critting the main target.

**Comment by kelno** [comment]
Okay... There is definitely something wrong in the current idea.
I'm going to reopen:
https://github.com/SunstriderEmu/BugTracker/issues/1440

I don't know what the exact behavior should be for now.
