### ISSUE TITLE
[Warrior] Sweeping Strikes + Cleave

### ISSUE THREAD

**Issue by Rattacrash** [SunstriderEmu/BugTracker#1487]
the problem:
if a cleave-attack on 2 targets is performed while sweeping strikes is active, only 1 of the 2 cleave-attacks will trigger 1 sweeping strike (3 hits in total)

https://ibb.co/3FJQqQn

how it should work:

both of the cleave attacks should trigger 1 sweeping strike attack on an additional target, so in sum 4 total hits should be aplyed after performing a cleave

"Stacks with Cleave, causing four attacks on two enemies every swing "
https://vanilla-wow.fandom.com/wiki/Sweeping_Strikes

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/165

**Comment by Rattacrash** [comment]
sry but whirlwind and cleave r 2 very diffrent animals
cleave needs to proc it twice
since cleave aint an instant attack but an "on next swinf attack" it has to proc it twice plz look at the refrence i brought up.
since the begiunning of world of warcraft cleave had always procced 2 sweeping strike hits, and that didnt change in TBC

**Comment by Jerrythemagicdog** [comment]
The issue I linked describes that the behavior for Cleave you describe in the issue is intended and it is currently bugged.

**Comment by Rattacrash** [comment]
oh sry i got u wrong than, somehow i thought u wernt agreeing with me

**Comment by kelno** [comment]
Okay I made the spell work correctly with Cleave and Whirlwind but I have a hard time finding the correct general rule. I guess the warrior doesn't have that many aoe spells so maybe we don't need it.

**Comment by Jerrythemagicdog** [comment]
Cleave does generate 2 additional attacks with Sweeping Strikes, Whirlwind one additional attack.
Confirmed fixed.
