### ISSUE TITLE
missing mob-type gan'arg analyzer

### ISSUE THREAD

**Issue by Rattacrash** [SunstriderEmu/BugTracker#1489]
in the blade's edge mountains, at ogri'la around the apexis monuments there, gan'arg analyzers should be guarding the monuments. theese mobs r missing entirely. it is kinda important that those mobs r there once ogri'la gets released becasue theese guys r the source of the schematic: field repair bot 110g

https://www.wowhead.com/npc=23385/simon-unit  (no idea why they r called simon unit on wowhead, their name is gan'arg analyzer, the wowhead-page for the gan'arg analyzer doesnt show locations or loot, i think there is soemthing messed up on the english translation page of wowhead, on the german wowhead-page for the "simon unit" they r called the german equivalent of gan'arg analyzer)

**Comment by Jerrythemagicdog** [comment]
Thanks for the report!
The missing NPC is linked to the Ogri'la event and will be correctly spawned once that event starts.
