### ISSUE TITLE
wrongly placed mob apexis guardian

### ISSUE THREAD

**Issue by Rattacrash** [SunstriderEmu/BugTracker#1490]
in the blade's edge mountains, at ogri'la, just south of the ogri'la-camp r mobs roaming called "apexis guardian" theese mobs should not be there raoming free. usually one of theese guys is spawning after finishing the apexis monument-event. not only r theese mobs way to powerfull and dangerous to just roam that area, especially in those numbers they r showing, they r meant to be summoned via the apexis monument to allow ppl to loot apexis crystals a blue quality resource needed to trade in some of the ogri'la reputation stuff. if those guys r just left there in the open to be killed and respawn u will allow ppl to have very easy and cheap access to an unlimited supply of large prismatic shards, once ogri'la is patched into the game in the server progression

https://www.wowhead.com/npc=22275/apexis-guardian

**Comment by Jerrythemagicdog** [comment]
Thanks for the sources, they are indeed wrongly spawned.
Their spawn positions and spawn conditions will change once the Ogri'la event starts.
