### ISSUE TITLE
[Druid] Ferocious Bite damage

### ISSUE THREAD

**Issue by uzbuzbuzb** [SunstriderEmu/BugTracker#1494]
i think ferocious bite damage is still too low.
https://youtu.be/HVfTsZNMTa8?t=737 he hits the warlock with 40energy 5cp FB for 1925.
the warlock has faerie fire feral, expose armor and hemo debuffs. lets assume his armor is 0  even tho that's not necessarily the case which ill talk about later. for now lets say armor is 0 and there's +42 damage from hemo. so 1883 ferocious bite on a target with 0 armor.
@ 12:45 he opens his character tab and even tho quality is scuffed you can see that he has 3334 attack power with 65 agility buff up and his attack for reference is 310-335
these are the stats i was able to get on PTR and they add up: https://i.gyazo.com/b0a2f422b02acb5d28c6016d91148c9a.png
so i copied his stats as close as i could and hit some 5cp 40 energy ferocious bites on a dummy with 0 armor and it was hitting 1550-1600. there's ofc the possibility that the guy had a talent for increased ferocious bite damage but really nobody ever used it, nobody uses it now and i doubt anyone was using it back then, like when i was researching this issue last time i actually talked to the fat cow himself, chrille, and he told me he wasn't using it. i can imagine how someone would go 3/5 in that talent instead of increased armor or stealth level, even though i highly doubt any halfdecent feral would ever do that. but alright lets say he had 3/5 thats +9% damage and lets assume he hit the highest roll of say 1620, that's still only 1766 5cp 40 energy bite on a target with 0 armor. with 5/5 bite talent it would be 1863 on a target with 0 armor, still doesn't quite add up.
now, i dont think this warlock had 0 armor even with expose and FF up because if you go back in the video when the guy was stacking his CPs for ferocious bite you can see that _with hemo debuff_ his mangle hit 932 and shred hit 1413. every single mangle of mine _without hemo_ hit for more than that averaging at 950 and shreds were averaging at 1500. so either warlock had some armor or shred/mangle damage is higher than it should be on ptr.

another example is @ 12:47 where feral had 65 agi buff up and his AP was @ 3334 and his 48 energy 5 cp ferocious bite crits the felhunter for 3036.
no hemo buff, no expose, faerie fire up. felhunter has around 5600 armor - 610 from FF thats around 5k = ~32% melee damage reduction. felhunter also had MOTW buff up which is 340 armor but thats about how much ARP feral has so lets assume it's nullified.
its safe to assume i guess that warlock had at least 400 resilience which would mean his felhunter had say 160 resi which is about 8% crit damage reduction.
let's assume he didn't have any points in demonic resilience (5/10/15% damage reduction on pets)
my bite crits with 3333 AP were averaging 3700 on a dummy with 0 armor and 0 resilience.

**Comment by Jerrythemagicdog** [comment]
The only sources I can find claim that it should scale 3% of AP per combo point - which we currently are using. If we can get a source claiming and proving otherwise it would be very welcome.

**Comment by ramadansteve** [comment]
okay i tried to test some more and reproduce this as accurately as i could.
i was hitting a felhunter with MOTW buff, FF (feral) debuff. i had 3331 AP (feral in the vid had 3334). warlock pet owner had 397 resilience and no demonic resilience talent. i had 5/5 ferocious bite talent (+15% damage).
my 48 energy 5cp bits were critting 2650 on the pet. so even assuming this guy had 5/5 bite talent (which i doubt he did), enemy warlock had 397 resi and no demonic armor (i dont think that was the case either) i still did 389 less damage.
realistically i think he might've had 3/5 imp bite and also warlock had some more resilience and mby 1 or 2 talents in demonic resilience
