### ISSUE TITLE
[Item] Vial of the Sunwell

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1495]
1. should be stacking off of hots like renew lifebloom rejuvenation etc, currently only stacks off of direct heals like regrowth, lesser healing wave, flash heal etc
proof:
https://youtu.be/HVfTsZNMTa8?t=801
2. Finrear on 2008/04/09 (Patch 2.4.1)

The buff also stays even after removing the triket, although sadly the /use effect isn't castable from your inventory.
currently not the case

**Comment by Jerrythemagicdog** [comment]
Fixed.
To dev:
It was procing from HoTs on targets that weren't full HP. (Phase was set to 0x2 after core changes, set back to 0x1 as we now have the correct logic).
Now it always procs from HoT casts.
