### ISSUE TITLE
[Rogue] Cold Blood doesn't affect Mutilate off-hand hit

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1496]
currently doesnt affect:
a. mutilate offhand hit
b. riposte

**Comment by Jerrythemagicdog** [comment]
Thanks!
The Riposte part is fixed.

To dev: it seems that the offhand Mutilate hit doesn't crit because the spell is immediately consumed by the main-hand crit. The spell_affect data is correct and includes the offhand hit.

**Comment by kelno** [comment]
Fixed with next update
