### ISSUE TITLE
[Druid] Abolish Poison expires on the target if it's no longer in caster's LoS

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1501]
**Describe the bug**
Title.

**To Reproduce**
https://www.twitch.tv/videos/494529395?t=04h23m10s
and again at 4:25
1. Cast Abolish Poison (2893) on a friendly target / party member
2. Leave the caster's LoS as the target (or as the caster, order doesn't matter)
3. Abolish expires.

To dev: 
maybe our understanding of attribute 0x800 is wrong, 
SpellInfo, line 1828

**Comment by kelno** [comment]
Fixed
