### ISSUE TITLE
[Rogue] Find Weakness doesn't increase the damage of Deadly Throw, Envenom and Kick

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1502]
doesn't increase the damage of deadly throw, envenom and kick.
also seems like it doesn't properly increase the damage of eviscerate

p.s. kick envenom and deadly throw damage not being increased when supposed to came up before when i was reporting ShS damage. i think it's a 'blizzlike bug' because when i was looking for a proof i found some clips where shadowstep didn't affect kick and deadly throw. i suggest you fix that and make all rogue damaging ability buffers (like find weakness and shadowstep) properly buff the damage of ALL damaging abilities. you know, like the tooltip says.

**Comment by Jerrythemagicdog** [comment]
Kick is intentionally left out, same as the case for Shadowstep.
Fixed Envenom and Deadly Throw missing.
