### ISSUE TITLE
Pathing on Karazhan stairs makes NPCs disappear under the ground

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1506]
**Describe the bug**
Title.

**To Reproduce**
https://streamable.com/utv7j
1. Pull any creature on the stairs
2. Go from top to bottom

Apparently can also happen to Mind Controlled players in that spot - the undermap system ports them back up but maybe the root of the problem is the same.

**Comment by kelno** [comment]
https://i.imgur.com/SyC5emu.png
It found valid ground just under the stairs :(

**Comment by kelno** [comment]
Fixed it. I'm not sure it covers all the cases though, this only affects the "chasing part". If there is a bug with players going undermap when following back it isn't fixed. But I couldn't reproduce the bug anymore.
