### ISSUE TITLE
Some creatures casting spells with "SPELL_EFFECT_APPLY_AREA_AURA_PARTY" seem to be refreshing the aura with other creatures in the area

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1507]
**Describe the bug**
Title.
The Aura is constantly replaced by another creature's aura that happens to be in the vicinity.
No real effect just looks weird.

Some affected spells are Devotion Aura (643) used by Dun Garok Mountaineer (2344)

It can be observed on nearby creatures that don't cast that aura themselves (for example .go crea 16164)

**Comment by kelno** [comment]
Also seen in karazhan before maiden with a seduction aura

**Comment by Jerrythemagicdog** [comment]
Doesn't seem to be the case anymore. Closing for now.
