### ISSUE TITLE
Unequipping any item will remove quiver haste effect

### ISSUE THREAD

**Issue by hufsa** [SunstriderEmu/BugTracker#1508]
**Describe the bug**
Title.

**To Reproduce**
1. Create a Hunter
2. Equip item 'Quiver of a Thousand Feathers' (34105)
3. Watch your ranged attack speed get increased by 15%
4. Unequip your shirt
5. Watch the ranged attack speed aura disappear (your attack speed is back to normal)

**Expected behavior**
The 'haste' aura (29414) from Quiver of a Thousand Feathers should remain until the item is no longer equipped.

**Additional context**
To dev: Player::RemoveItemDependentAurasAndCasts

**Comment by kelno** [comment]
It seems that quiver are restricted to bows and pouch to guns, this only happens if I try to combine gun and quiver.
So this is not a bug, but we got another bug: the gun is affected when I equip the quiver (until I change any item and it gets fixed)

**Comment by hufsa** [comment]
Suggestion for SpellInfo tool: Display spell requirements.

**Comment by kelno** [comment]
Actually the same bug as https://github.com/SunstriderEmu/BugTracker/issues/1415

**Comment by kelno** [comment]
Fixed
