### ISSUE TITLE
Undercity guard's problem

### ISSUE THREAD

**Issue by nicoday** [SunstriderEmu/BugTracker#1510]
**Description:**
When you ask the Undercity guards for specific directions, it shows a wrong icon. This happens no matter what option in the dialog you choose.

![WoWScrnShot_110119_204717](https://user-images.githubusercontent.com/57264818/68042014-ae1e8900-fcf3-11e9-9dde-113c731ac25a.jpg)
![WoWScrnShot_110119_204726](https://user-images.githubusercontent.com/57264818/68042013-ae1e8900-fcf3-11e9-9677-a75831653082.jpg)

**Comment by Jerrythemagicdog** [comment]
Thanks!
Fixed in rev. 12689
Make sure to clear your Cache when testing after the server is updated.
