### ISSUE TITLE
[Warlock] Soul Link bonus damage doesn't get applied if caster is currently in combat

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1511]
**Describe the bug**
Soul Link, in addition to sharing the damage, increases damage done by the pet and master by 5%.
Currently if we Corruption a target dummy without Soul Link active and then cast Soul Link and reapply Corruption the bonus damage part is not added. The Warlock has to drop combat and then cast a new Corruption for the bonus damage part to become active.

The issue happened on Target Dummies in the beta starting zone and didn't happen on players in a duel.

**Comment by kelno** [comment]
https://db.endless.gg/?spell=19028

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago.
