### ISSUE TITLE
Voidwalker spell Sacrifice can be resisted

### ISSUE THREAD

**Issue by hufsa** [SunstriderEmu/BugTracker#1512]
**Describe the bug**
Title

**To Reproduce**
1. Create a warlock
2. Learn Summon Voidwalker
3. Teach your voidwalker 'Sacrifice'
4. Use 'Sacrifice'
5. It can be resisted by the owner

**Expected behavior**
It should not resist -- it's a beneficial spell

**Comment by Jerrythemagicdog** [comment]
Spell id: 27273

**Comment by kelno** [comment]
I can't reproduce this, Sacrifice is considered as a positive spell by the core

**Comment by hufsa** [comment]
I dont know what to say. It happened and I’m 100% certain. It was in my combat log even.

**Comment by kelno** [comment]
Then I suggest trying to reproduce it in the same setup you were and trying to find reproduce steps there

**Comment by hufsa** [comment]
Better up -- write a test for it and call it a day if it doesn't happen there. :)

**Comment by kelno** [comment]
I'm pretty sure I'd get the exact same result there and it still wouldn't exclude a bug in some specific setup

**Comment by hufsa** [comment]
Closing as this might be invalid
