### ISSUE TITLE
AoE spells don't put caster or victim in combat after recent changes.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1513]
**Describe the bug**
Title.

**To Reproduce**
1. Use any AoE spell (Blizzard [27085], Rain of Fire [5740], Hellfire [1949]) on an enemy player
2. Both you and target don't enter combat

**Expected behavior**
Both parties should enter combat.

**Comment by kelno** [comment]
Fixed
