### ISSUE TITLE
Traps linked to chest gobs trigger regardless of the chest gob's state.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1514]
**Describe the bug**
Traps linked to chest gameobjects (for example `SELECT * FROM gameobject_template WHERE name = 'Rotten Arakkoa Egg' AND type = 3;` data7 holds the trap gob ID (184797 in this case)) trigger regardless of us opening the chest or not - it's enough to just walk over them and they trigger. That issue is prevalent all through the open world (the most obvious example being the herbs providing a buff that activate when walking over them).

To test: 
`.go xyz -4091.344238, 1888.348145, 75.806343, 530`
the trap triggers when we walk over one of the eggs rather than when we open it which should be the case.
(to open one of the eggs we need quest "
Of Thistleheads and Eggs..." (10547))

**Comment by kelno** [comment]
Objects with linked traps, having a non matching trap on the same pos
```SQL
SELECT m.*
FROM gameobject_template main
JOIN gameobject_template trap ON trap.type = 6 AND ((main.type = 3 AND main.data7 != trap.entry) OR (main.type = 8 AND main.data2 != trap.entry) OR (main.type = 10 AND main.data12 != trap.entry))
JOIN gameobject m ON m.id = main.entry
JOIN gameobject t ON t.id = trap.entry AND m.position_x = t.position_x AND m.position_y = t.position_y AND m.position_z = t.position_z
```

**Comment by kelno** [comment]
Updated this, but didn't test many cases yet.
Time to sleep!

**Comment by Jerrythemagicdog** [comment]
I've tried the one mentioned in the issue and the previously changed Rogue quest chain chests (for example "Mission: Possible But Not Probable" - 2478), they work. The herbs (Dreaming Glories) also work.
Also tried hunter traps, even though they shouldn't be affected - they work correctly after changes.
