### ISSUE TITLE
[Mage] Fire ward/Frost ward, Ice Barrier and Mana Shield damage absorption priority

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1515]
when fire or frost ward and ice barrier are active on a mage simultaneously, frost or fire damage taken by the mage should always be absorbed first by the ward and not ice barrier. 
currently its being absorbed by whatever shield was applied first, so like if i first used ice barrier then i use fire ward and after that i take fire damage it will break the ice barrier first, instead of fire ward. but if u use fire ward first and IB after then it will work properly.

works properly with mana shield though

**Comment by Jerrythemagicdog** [comment]
Sounds like the described behaviour would be something that makes sense, but doesn't seem to actually be a thing in the game. Maybe worth considering though.
https://youtu.be/IB7bUNWTlh4?t=1222
so what we can see here is:
> Fireblast>Missed Cone of Cold>blanket Counterspell>Frostbolt while Frost Ward up>Ice Barrier gone
More videos:
https://www.youtube.com/watch?v=-J55f0puu9A&feature=youtu.be&t=311

I'm not sure what the current behavior is exactly right now, maybe we could consider making a priority. The relevant cases that instantly come to mind seem to be mage v mage only.
