### ISSUE TITLE
Pet follow doesn't work correctly after recent changes

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1516]
**Describe the bug**
Title.

**To Reproduce**
1. Send pet to attack a target
2. Wait for it to reach the target
3. Order the pet to /petfollow to come back to the owner
4. Pet just sets his orientation to somewhere and stands there (we have to /petstay and /petfollow again for it to start coming back)

**Expected behavior**
Pet should come back when we order it to come back with /petfollow.

**Screenshots/videos**

Result of ordering a /petfollow when the pet is attacking a dummy:

![image](https://user-images.githubusercontent.com/46463908/69457654-75f3ee80-0d65-11ea-9803-110b98b43cf4.png)

**Comment by kelno** [comment]
Fixed
