### ISSUE TITLE
[Warlock] Felhunter doesn't auto cast Devour Magic on enemy targets with buffs

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1517]
**Describe the bug**
Title

**To Reproduce**
1. Get a Felhunter as a Warlock
2. Teach him Devour Magic
3. Tell him to auto cast Devour Magic on a hostile target with buffs (for example a Druid with Mark of the Wild)
4. The Felhunter doesn't cast Devour Magic unless he himself is affected by a negative buff.

Perhaps related to the logic changes in https://github.com/kelno/sunstrider/commit/40cb6429ed94c8d4274660ed9b5d3d02b62f91bf

**Comment by kelno** [comment]
We can't reproduce atm

**Comment by Jerrythemagicdog** [comment]
Can't reproduce seems to have been an issue with GM mode and duel zone.

**Comment by Jerrythemagicdog** [comment]
Can't reproduce seems to have been an issue with GM mode and duel zone.
