### ISSUE TITLE
[Hunter] Steady Shot and haste effects issue

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1520]
**Describe the bug**
Steady Shot doesn't always seem to benefit from haste effects(?). 
While testing the shot queueing rotation we found that our Steady Shot cast time is higher than expected (we capped out at 1.3). It seems as if haste from items (such as Blackened Naaru Silver item id 34427) doesn't reduce the cast time of Steady Shot which is wrong. Interestingly enough haste procs (such as DST proc - spell id 34774) seem to affect it and work correctly. Hard to make sense of it.

Additional info: https://www.youtube.com/watch?v=5oPveXRCXp8

Gamepedia: https://wow.gamepedia.com/Steady_Shot
"To understand how steady shot is affected by haste ratings it's important to understand how haste is calculated. A haste bonus is multiplied by frequency to achieve post-haste speed. World of Warcraft expresses all speeds as period rather than frequency, so the period must be divided by 1+bonus. "
"Steady Shot is affected by Haste bonuses including that granted by [Auto Shot] and [Serpent's Swiftness]. It is also affected by ranged attack speed bonuses including [Rapid Fire] and [Bloodlust].
Hunters are the only class whose GCD is unaffected by haste."

1. .additem 34427 (Blackened Naaru Silver)
2. Cast Steady Shot

**Comment by kelno** [comment]
With these reproduce steps cast time gets reduced to 1.466 correctly

**Comment by kelno** [comment]
Okay there was an error where Steady Shot actually has 1.0s cast time and 0.5 gets added later in the core, and only the first part was affected by haste

**Comment by Jerrythemagicdog** [comment]
Some retail sources for future reference (Steady Shot cast time with no procs):
https://youtu.be/_gAQjX1oK6E?t=108 (SK Gaming vs. Brutallus)
https://youtu.be/S6G8CH45cYk (flatline vs Kil'Jaeden - Strongmint)
https://youtu.be/h1g7jAD_IX8?t=113 (Iron Edge - Sunwell Plateau)
