### ISSUE TITLE
Berserking

### ISSUE THREAD

**Issue by ghost** [SunstriderEmu/BugTracker#1524]
**Bug description**
The haste bonus is calculated in the same manner as other haste effects.

**Expected behavior**
hasted_speed = weapon_speed / ( 1 / ( 1 - berserking% ) )

Sunstrider rev. 12842 (f0222eebbc38) 2019-12-05 23:23:16 +0100

**Comment by earthworm-jim** [comment]
Example:
2.9 Weapon, Rapid Fire, Quiver, Berserking(30%)
hastedspeed = 2.9 * ( 1.4 * 1.15 * 1.429 ) = 1.26

**Comment by Jerrythemagicdog** [comment]
Thanks, could you provide some sources?

**Comment by earthworm-jim** [comment]
```
2.9 ÷ ( [1 + 40%] × [1 + 15%] × [1 ÷ (1 - 30%)] )
2.9 ÷ ( 1.4 × 1.15 × [1 ÷ 0.7] )
2.9 ÷ ( 1.4 × 1.15 × 1.429 )
2.9 ÷ 2.3
1.26
```

https://web.archive.org/web/20080913174038/http://hunterguide.wikispaces.com/Theorycraft#GeneralHaste

**Comment by Jerrythemagicdog** [comment]
I'm having a hard time believing there is special handling for Berserking alone, it's relying on spell effects used in other spells (such as Rapid Fire or Aspect of the Hawk proc - Quick Shots), those would be working incorrectly as well if that was true. Is there some other source confirming this?

**Comment by earthworm-jim** [comment]
There's a good chance this info can be found burried somewhere in the ElitistJerks archive, since Lactose was active there. Maybe Cheeky's Spreadsheet too.

**Comment by earthworm-jim** [comment]
I'm not sure how to search Elitist Jerks threads through archive.org. Found this on wowhead:
> admielke on 2012/06/14 (Patch 4.3.4)
If your spell is 2.0 and you have 20% haste from gear that would make it 1.6. If you use Berserking then you'll have it changed to 1.28 and if you had Bloodlust then it would go from 2.0 to 1.2 (Bloodlust is counted first), and using Berserking makes 1.2 to 9.6 second cast. In short: Berserking takes your finished spell (after gear and buffs) and reduces it by 20%.

**Comment by test-1337** [comment]
https://web.archive.org/web/20110611202817/http://video.google.com/videoplay?docid=1153488157657416407#

video from patch 1.10.2 or earlier
> Troll Hunter with Hurricane .62 Attack Speed
This is what a Troll Hunter can do with Hurricane, Rapid Fire, Quick Shots and Berserking. He is at full health, so the berserking only adds 10% haste instead of 30%, which would be even faster. You can do this every 5 minutes.

``` ( 1.6 ÷ ( 1.4 × 1.3 ) ) × 0.7 = 0.615384... ```
