### ISSUE TITLE
[Paladin][Talent] Sanctified Seals - doesn't prevent the Mage from attempting to Spellsteal

### ISSUE THREAD

**Issue by earthworm-jim** [SunstriderEmu/BugTracker#1526]
**Bug description**
Dispel resistance isn't applied. Haven't tested the crit part.

**Expected behavior**
Besides the obvious,
Patch 2.4.3: Dispel effects will no longer attempt to remove effects that have 100% dispel resistance. 

Sunstrider rev. 12861 (6f0f4b887d8c) 2019-12-08 20:52:56 +0000

**Comment by Jerrythemagicdog** [comment]
How was this tested? 
During the in game tests with a Priest the Priest would correctly get a "Nothing to dispel" message when the paladin has 3/3 in Sanctified Seals and at lower talent points (1/3 and 2/3) it also has a dispel resist chance.
Will edit with a relevant sample size once we finish writing a test for this talent.

**Comment by earthworm-jim** [comment]
Dueled myself on 2nd account

**Comment by Jerrythemagicdog** [comment]
Still found an issue, thanks!

**Comment by kelno** [comment]
Fixed the message not showing. If there is nothing else here, closing!

**Comment by Lamberdo** [comment]
in duel other pal can disspel seal if we have 3 points in Sanctified Seals

**Comment by Jerrythemagicdog** [comment]
@Lamberdo how can the Paladin dispel the Seal?

**Comment by Lamberdo** [comment]
using cleanse we have that problem on duel.

**Comment by Jerrythemagicdog** [comment]
This is only about Seal spells not about Seals that are already Judged on the target.

**Comment by Lamberdo** [comment]
I use Jugement with seal of crusader on pally and he cleanse it when i have 3 points at this talent

**Comment by Jerrythemagicdog** [comment]
Please read the tooltip carefully. It prevents the Seal on the Paladin from being dispeled not the Judged Seal on the target.

**Comment by Lamberdo** [comment]
rly sorry:) im retarded hehe

**Comment by Jerrythemagicdog** [comment]
No worries, thanks!
