### ISSUE TITLE
Seal of Righteousness can Crit

### ISSUE THREAD

**Issue by Gorri-1** [SunstriderEmu/BugTracker#1527]
**Describe the bug**
Seal of Righteousness is able to critical hit. As far as i remember this was not the case in TBC.

![Seal](https://user-images.githubusercontent.com/58705786/70466373-43672700-1ac3-11ea-9f48-681f685b6553.PNG)

**To Reproduce**
autohit a dummy with Seal of Righteousness on you

**Comment by Jerrythemagicdog** [comment]
Thanks for the report, did the target of Judgement of Crusader with Improved Seal of the Crusader applied? 
If true then it's the same issue as https://github.com/SunstriderEmu/BugTracker/issues/1368

**Comment by Gorri-1** [comment]
No it does crit without Judgement of Crusader, too.

**Comment by Jerrythemagicdog** [comment]
Thank you!

**Comment by Gorri-1** [comment]
The chance to crit for Seal of Righteousness seems like to be calculated from meele crit, it is definitely not spell crit.

**Comment by kelno** [comment]
Fixed
