### ISSUE TITLE
Stormchops

### ISSUE THREAD

**Issue by Lamberdo** [SunstriderEmu/BugTracker#1528]
Stormchops right now is hitting only us not enemes.

**Comment by Jerrythemagicdog** [comment]
Thanks for the report, how was this tested? 
It appears to be zapping enemy creatures occasionally, as intended.

**Comment by Lamberdo** [comment]
I hit dummy for 5 mins and got 0 dmg from Stromchops... but if i use it neer dummys they got this buff and they hit me.

**Comment by Jerrythemagicdog** [comment]
Thank you!

**Comment by Lamberdo** [comment]
one more think i dont know for sure but stormchops works with other food buff? becouse now you can got buff from any food and then u can active stormchops.

**Comment by Jerrythemagicdog** [comment]
They should indeed not stack.
http://www.wowhead.com/spell=43758/stormchops#comments:id=279588

> Stormchops does overwrite any other Well-Fed buffs you might have, and Stormchops' buff can be overwritten by a Well-Fed buff.

Thanks!

**Comment by kelno** [comment]
Fixed
