### ISSUE TITLE
Crit chance reduction against higher level targets (creatures and players)

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1530]
This is a yet to be confirmed rule, but currently the way it works is that we differentiate between players and creatures when it comes to diminished critical strike chance against higher level targets.

For higher level creatures we currently use:
(https://wowwiki.fandom.com/wiki/Critical_strike?oldid=1548206)
Def > min (WS, attacker lvl * 5)    - 0.2% per point of difference

![unknown](https://user-images.githubusercontent.com/46463908/70554221-a5339980-1b74-11ea-8070-cadfe44825de.png)

**Comment by Jerrythemagicdog** [comment]
1.8% reduction now in total against a target 3 levels higher.

**Comment by kelno** [comment]
Note that this is only about melee
