### ISSUE TITLE
Really wonky charge in that one spot

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#1531]
.go xyz -4517.799805 717.195557 60.862839 1
Charging a mob located at:
-4515.440918 734.630371 60.918327 1

Makes you charge sloooow and suddenly end up in the stratosphere at the end
https://streamable.com/unqtt

**Comment by kelno** [comment]
Generated points :D
![image](https://user-images.githubusercontent.com/3866946/70558409-1f6c1a00-1b85-11ea-879f-3a4da2c1203d.png)

**Comment by kelno** [comment]
This is returned by the pathfinding library... definitely something wonky with the generated mmaps. Possible related to https://github.com/SunstriderEmu/BugTracker/issues/1314

**Comment by z5n** [comment]
unable to reproduce, issue has likely since been fixed
