### ISSUE TITLE
Spells go invisible on action bars

### ISSUE THREAD

**Issue by Gorri-1** [SunstriderEmu/BugTracker#1533]
**Describe the bug**
When i use a spell on my action bar and switch to a other action bar while global cool down is still on one or multiply spells on my action bar are invisible.

If i use action bar 1 and 3 for example: If there are no key binds on 2-6 on action bar 3, i cast a spell on action bar 3 and switch to action bar 1 with shift-1, while global cool down is still on, all spells on key binds 2-6 are invisible on action bar 1.

By invisible i mean i can still use them by pressing the key binding, but i can't see them or use them with the mouse.

When i drag some remaining non invisible spell, all spells, except the one i dragged, are visible again.

**To Reproduce**
1. Bind something to your 1. and 3. action bar
2. Switch to action bar 3
3. Cast the spell on action  bar 3
4. Switch to action bar 1 while global cool down is on

I used Shift-1 and Shift-3 for switching action bars.
You should fill your bars with spells so its better to reproduce.

**Additional context**
This happens on many tbc private servers, but not as often as here, it is like 90% here.

**Comment by Jerrythemagicdog** [comment]
Thanks, could you turn off all your addons and try again and then if it still happens provide a video of it happening? I'm unable to reproduce.

**Comment by Gorri-1** [comment]
Try one of these links.
https://youtu.be/xzhhAIwtF3k 
https://www.youtube.com/watch?v=xzhhAIwtF3k&feature=youtu.be

**Comment by Jerrythemagicdog** [comment]
Thanks, I'm still unable to reproduce though.

**Comment by Gorri-1** [comment]
Tried it with a other client, bug is gone now.
