### ISSUE TITLE
Various Bugs encountered while leveling

### ISSUE THREAD

**Issue by Zrg149** [SunstriderEmu/BugTracker#1534]
This is a list of various bugs I have encountered while leveling in the vanilla zones.
>Character name : Mokuro ; Orc Warrior

- [x] - When humanoid mobs enter the fleeing state (~35-10%hp) their run speed is dramatically increased

(https://github.com/SunstriderEmu/BugTracker/issues/608)

- [x] If a mob is engaged underwater, and the player character swims to the surface, the mob will reset hp and evade attacks until character is submerged again

- [x] Rare spawns do not have access to their intended loot tables, and instead have the normal equivalent of the mob's base type's loot table (ex. Giggler the Rare Hyena in Desolace has the loot table for a regular hyena in desolace)

- [x] - Mobs that have access to a Net ability, which roots you in place, use the ability ~2-3x more often than they should. This can lead to being chain netted for upwards of 20-25 seconds

- [x] - Various Feralas mobs incorrectly apply a disease effect (Contagion of Rot) This effect can stack

- [x] - Mob Leash range is Lower than usual. In some cases you cannot attack a mob from 41yards without the mob resetting while traveling towards the player character. I still need to test this more, and should have additional information in the near future.

**Comment by Jerrythemagicdog** [comment]
Thanks a lot. 
I'll edit the issue a little bit to reference issues that are already logged on the bugtracker.

**Comment by Jerrythemagicdog** [comment]
The only mob in Feralas that can apply "Contagion of Rot" is Woodpaw Mongrel (5249):
https://wow.gamepedia.com/Woodpaw_Mongrel
https://classicdb.ch/?npc=5249

**Comment by kelno** [comment]
Fixed fleeing speed + underwater combat
