### ISSUE TITLE
Item : Vengeful Gladiator's Totem of the Third Wind

### ISSUE THREAD

**Issue by Macumbafeh** [SunstriderEmu/BugTracker#1539]
**Describe the bug**

Vengeful Gladiator's Totem of the Third Wind : 
"Equip: Causes your Lesser Healing Wave to increase the target's Resilience rating by 34 for 6 sec."
This item proc with any heals

https://www.thegeekcrusade-serveur.com/db/?item=33843

**To Reproduce**
1. Equip the item
2. Cast Healing Wave / earth Shield / Chain heal, ect...
3. See totem proc on any heals

**Expected behavior**
This item have to proc just with Lesser Healing Wave.
Maybe it's the same with merciless / brutal totems.

**Screenshots/videos**

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by Jerrythemagicdog** [comment]
It was indeed wrong for other totems of the same kind as well.
Fixed in rev. 12928. You can check the current revision using .server info in game.
