### ISSUE TITLE
[Item] Vial of the Sunwell

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1540]
**Describe the bug**
You gain stacks by casting non-healing spells e.i. Concentration aura, Seals, Blessings

http://tbc.cavernoftime.com/item=34471

**Expected behavior**
Should be only able to proc from healing spells/procs.

**Comment by kelno** [comment]
Updated, to test!

**Comment by kelno** [comment]
Updated again and fixed with next restart
