### ISSUE TITLE
[Shaman] Mana free spell casts consume Clearcasting effect

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1541]
**Describe the bug**
Mana free spellcast e.i lightning bolt(Rank 2) in combination with Totem of the Pulsing Earth are still consuming Elemental Focus talent procs

**To Reproduce**
1. Spec Convection
2. use Totem of the Pulsing Earth
3. cast R2 lightning bolt that is free.
or
1. Use normal gear
2. Wait for clearcasting buff
3. Use elemental mastery and cast lightning bolt, you will see that one clearcasting was consumed even though EM makes the cast mana free

**Expected behavior**
Mana free spells are not supposed to consume buffs that (only) reduce manacost of said spells

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**
It is a general issue (probably) didnt test futher. Note that if the mana reducing buff has also some additional effect, it should be consumed regardless. (With an exception to Surge of Light proc & Inner Focus)

**Comment by kelno** [comment]
Simplified steps:
1. Spec Elemental Mastery + Elemental focus (Clearcasting)
2. Spam lightning bolt until Clearcasting proc
3. Use Elemental mastery to cast a new lightning bolt and see that you loose one Clearcasting stack

**Comment by kelno** [comment]
Fixed at next restart

**Comment by Jerrythemagicdog** [comment]
Not fixed yet:

https://youtu.be/doztT5hZQCY?t=6
