### ISSUE TITLE
Weird visual bug on blood elf bandit

### ISSUE THREAD

**Issue by KingKC612** [SunstriderEmu/BugTracker#1542]
![WoWScrnShot_121919_220310](https://user-images.githubusercontent.com/32748063/71229973-54771b80-22ad-11ea-91d7-f43f70c69dd4.jpg)

**Comment by Jerrythemagicdog** [comment]
I can't reproduce this exact effect.
To dev:
There's definitely a brief effect like this when a creature with Stealth casts it on respawn immediately (through SAI for example). This one in particular has it on reset. 
Perhaps we could try adding a little bit of delay on a creature respawn and when it does its first action, similarly to how we have it for summons currently.

**Comment by kelno** [comment]
That's kinda pretty !

**Comment by kelno** [comment]
Looks like he recast stealth many many times per second

**Comment by kelno** [comment]
Changed this guy AI completely, should be fixed
