### ISSUE TITLE
[pet] petpassive delayed by pet cast

### ISSUE THREAD

**Issue by test-1337** [SunstriderEmu/BugTracker#1543]
**Bug description**
petpassive is incorrectly applied after pet cast instead of immediately.

Sunstrider rev. 12940 (beac0bda2ae2) 2019-12-19

**Comment by kelno** [comment]
Thanks. I don't understand what's wrong here, why should setting a pet on passive interrupt its spell?
Since a passive can still have combat interactions if ordered to

**Comment by Jerrythemagicdog** [comment]
I think players usually use a `/petfollow` to stop casting or `/petpassive /petfollow` macro, but maybe we're in the wrong here, would be interesting to see how it should work.

**Comment by earthworm-jim** [comment]
How would you stop pet attack and have him stay at his petstay location, if he didn't move from that location?

**Comment by Jerrythemagicdog** [comment]
I suppose by making him move a little and ordering him to cast immediately.
All Water Elementals seem to start in Defensive Stance on retail, so I can imagine changing stances from Defensive to Passive does indeed interrupt the cast but setting it to Passive while it's already in Passive doesn't.

https://youtu.be/nDFTMph3gBY?t=125
https://youtu.be/IAoe3akMZUE?t=1141
https://youtu.be/IB7bUNWTlh4?t=1723

**Comment by earthworm-jim** [comment]
petfollow and petstay should interrupt petattack immediately. petpassive simply forces the pet to either follow or stay (return to the saved location) depending on what was commanded prior to the attack. not being able to stop your pet as you're trying to poly, for example, makes no sense.

**Comment by hufsa** [comment]
> All Water Elementals seem to start in Defensive Stance on retail

On retail they start with the saved state I suppose?

**Comment by kelno** [comment]
To dev: using pet passive sends a CMSG_PET_ACTION to the server even if already in passive so that's doable

**Comment by earthworm-jim** [comment]
petattack on target B while casting waterbolt on target A currently results in waterbolt being launched at target A. not sure if waterbolt should be interrupted and begin a new cast on B or just redirect it to B.

**Comment by Jerrythemagicdog** [comment]
I suppose doing this also works: 
https://streamable.com/brrhw
(courtesy of Magiciann)

**Comment by earthworm-jim** [comment]
petattack > petstay > petattack > petpassive
