### ISSUE TITLE
[Paladin][Talents] Redoubt

### ISSUE THREAD

**Issue by networm555** [SunstriderEmu/BugTracker#1544]
thats how it should work. https://www.youtube.com/watch?v=cJ5Gtkg951U
In current state its not procing whitout shield. it should. so when you swap you already can benefit from a talent.

**Comment by kelno** [comment]
Fixed

**Comment by networm555** [comment]
seems like its not working in pve. previous tests was in pvp encounter. Fire elem didnt popped talent for 2 minutes even with shield equipped.

**Comment by Jerrythemagicdog** [comment]
When was this tested? The fix is live for 57 minutes now on the PTR

**Comment by networm555** [comment]
it was tested with 17 mins uptime on a server

**Comment by kelno** [comment]
Updated again there was a typo in there, fixed with next restart for real this time

**Comment by networm555** [comment]
working perfectly
