### ISSUE TITLE
Raging Fire-Soul

### ISSUE THREAD

**Issue by networm555** [SunstriderEmu/BugTracker#1545]
Not using his abilities. This mob like all elementals on farm spots should not be easy prey. Recommend to check them all.

**Comment by kelno** [comment]
https://db.endless.gg/?npc=22311
https://www.wowhead.com/npc=22311/raging-fire-soul#comments

It currently casts immolation at low health, what's missing there?

**Comment by networm555** [comment]
killed like 6-8 of them. they just aa. what number in your code is set as a trigger?  
ps: your db is not opening on my end "DB eror"   Noticed "ruru" line there. Are you russians?

**Comment by kelno** [comment]
Okay that's a new. We don't region lock IP so I guess it's an internal issue with the db trying to display in russian, thanks for reporting

**Comment by networm555** [comment]
will try to squeeze some time to test it again . thanks

**Comment by networm555** [comment]
12950  still a dummy. kited him for 15 seconds he casted nothing with 20 -15-11-8% hp.

**Comment by Jerrythemagicdog** [comment]
Thanks.
The Raging Fire Soul was using the incorrect Immolate spell, changed it to the correct one and it's going to cast it on aggro now.
The Storming Wind-Ripper will correctly cast Lightning Bolt as well.
Live after next restart.

**Comment by networm555** [comment]
RFS still a dummy. Air elem is good.

**Comment by Jerrythemagicdog** [comment]
Raging Fire Soul only has an immolate aura and fire melee attacks (as mentioned in wowhead comments), we could consider adding something custom to make them on par with other elementals. 
If you have any suggestions feel free to let us know.

**Comment by networm555** [comment]
ye but now they doing nothing. you can spoil party for warlocks priests and mages by adding fireball spell for 500.  you can replicate fire aoe they inflicted on player by using warlock spell. fire elems immune to fire damage so they shouldnt harm and kill themselves.

**Comment by Jerrythemagicdog** [comment]
They are attacking with fire damage, are we talking about the same creature? 
Raging Fire-Soul (22311)
![rfs](https://user-images.githubusercontent.com/46463908/71323366-29b5de80-24ca-11ea-91bd-b26c66823044.png)

**Comment by networm555** [comment]
yes you right sorry. strange but i pretty sure some of them hit me with phys. 
![WoWScrnShot_122219_215111](https://user-images.githubusercontent.com/43811642/71323466-1d4f7700-2506-11ea-9011-116b25daca94.jpg)

**Comment by Jerrythemagicdog** [comment]
I think we're going to keep them immune to fire and keep the other elementals immune to their respective schools as well.
The Raging-Fire Soul will have an Immolate it casts on 50% hp on the target (only once per fight, nothing too crazy) after next restart.
