### ISSUE TITLE
[Hellfire peninsula] Dummy mobs found after short flyby

### ISSUE THREAD

**Issue by networm555** [SunstriderEmu/BugTracker#1546]
Unyelding Knight- should heal himself and his allies.
Wrathguard dont have his signature fire ability that wrecked people.
Netherbond and Fel Handler should be linked and always travel together. Its a pet and master just read their names.
Doomwhisperer just aa. To few of them around. This place will become aoe farm location till 64 if you wont do all mobs correctly. There should be anitcaster heavy mobs like FHwith pet that drains mana and anti melee mobs Dw and Wg. Blizzard did that for a reason.
Subjugator Shi'aziv - just aa
Forge camp legionnare - dont have cleave and mortal strike. They should kick ass. Was very dangerous mob and very hard quest zone.
PS: I found this just in a short observation. Pretty sure you will have to recheck all of outland mobs from what iv seen.... Seems like no one ever tested anything in open world. Probably alot of mobs with wrong spell ids with same names or something like this.  You can leave it like this its more or less playable. But there will be alot of people like me who will rage about this. And their mood will affect other players. People should see quality and love in every little thing. Just my few cents. No offence. I just want your server to be a valid option to play when every cd on classic is cleared.

**Comment by Jerrythemagicdog** [comment]
Thanks for the testing.
As a reminder this tracker is for issues only, please keep your opinions to Discord or other places, thanks!

**Comment by Jerrythemagicdog** [comment]
While fixing these, some things should be clarified:
> Unyelding Knight- should heal himself and his allies.
They will only heal allies as per the spell they use (Heal Other) and its attribute:
• Cannot cast on self
Previously they tried to heal themselves only and were failing.

> Doomwhisperer just aa
They cast Draining Bolt (33969) after 5 seconds of being in combat and then every 10 seconds, not sure why didn't they do it for you while testing.

> To few of them around.
Seems to be consistent with retail spawns, maybe some patrols missing which gives you that impression.

The rest of the issues are fixed and the fixes will be live after a restart later, thank you.
