### ISSUE TITLE
Hunter pets hit/resilience/penetration inheritance

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#1547]
Not a actually bug but a summary of what is, what is retail TBC and what we have/want (aka Endless behavior)

# Melee/Spell hit chance

Retail behavior: 
**2.4.3** - No inheritance
**3.2**- Pets inherit hit chance ("proportionally" but I think it's only relevant for lower level pets) (source: https://wowwiki.fandom.com/wiki/Patch_3.2.0#toc)

Endless behavior: 
No inheritance (neither on melee or spells). We might change this one.

# Spell penetration

Retail behavior: 
**2.4.3** - No inheritance
**3.2** - Pets inherit 100% (source: https://wowwiki.fandom.com/wiki/Patch_3.2.0)

Endless behavior: 
Inherit 100%

# Resilience

Retail behavior: 
**2.4.3** - No inheritance
**3.2**- Pets inherit 40% (source: https://wowwiki.fandom.com/wiki/Patch_3.2.0#toc)
**3.3** - Pets inherit 100% (source: https://wowwiki.fandom.com/wiki/Patch_3.3.0)

Endless behavior: 
Inherit 40%.

**Comment by earthworm-jim** [comment]
concerning the resilience change -  won't that make warlock pets super tanky, particularly felhunter/felguard vs casters?
