### ISSUE TITLE
Pet autocast abilities behave in a wrong manner in many cases.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1548]
**Describe the bug**
https://clips.twitch.tv/SourGlutenFreeJackalPipeHype

As we can see in the clip, the Felhunter has valid buffs to remove from the target (for example around 0:20 seconds mark) but doesn't devour them from the target, it has to be manually casted.
It also seems to prioritize friendly targets with auto cast on rather than targets it's currently attacking (so in this clip it would Devour debuffs from friends while chasing an enemy).

Hunters are also experiencing an issue where their auto cast can't be turned off on their pet (maybe after map change with it previously turned on? - to be reproduced).

To dev:
Probably `2ad32a11e406a3052a35d255f5bf4cd8f963467a` related.

**Comment by earthworm-jim** [comment]
#1553 related

**Comment by kelno** [comment]
So are we saying enemy target should always be prio on friendly targets?

**Comment by Jerrythemagicdog** [comment]
I suppose when it comes to targeted spells such as Spell Lock or Devour Magic and leaving them on auto cast it looks like this:

If pet is attacking a target and has auto-cast on it will cast on the target always.

If pet is in follow mode and not attacking anyone (or on its way to attack (?)) it should autocast on friendly targets

**Comment by kelno** [comment]
Fixed with https://github.com/SunstriderEmu/BugTracker/issues/1749
