### ISSUE TITLE
[Nagrand] Living Cyclone + Durn the hungerer

### ISSUE THREAD

**Issue by networm555** [SunstriderEmu/BugTracker#1549]
https://www.wowhead.com/npc=17160/living-cyclone#abilities
Another dummy.
https://www.wowhead.com/npc=18411/durn-the-hungerer#abilities
Not using his cleave.   Maybe 2nd target required.

**Comment by Jerrythemagicdog** [comment]
Living Cyclone has a Lightning Shield (changed now from "on respawn" to "when missing buff")
and a Magnetic Pull (where it pulls you to him if you're trying to run, only casted between 8 and 40 yards from target - https://www.wowhead.com/npc=17160/living-cyclone#abilities).
Durn the Hungerer has Arcing Smash and Force Punch.

**Comment by networm555** [comment]
Arcing Smash is a cleave. When i aggroed him he not used it for minute +_ 30 sec. Then i died :D

**Comment by Jerrythemagicdog** [comment]
He's supposed to use it 9 seconds into the fight, then every 9s to 15s - tested and it works
![rfs](https://user-images.githubusercontent.com/46463908/71324067-4a823200-24d2-11ea-8a9d-117feae99722.png)

**Comment by networm555** [comment]
hm lemme retest it again

**Comment by Jerrythemagicdog** [comment]
I see the spell has a range of 10 yards, is it possible you were further from him than that?

**Comment by networm555** [comment]
True. Maybe his hitbox has wrong value? He should cleave further. I got cleave when i walked right inside him.  https://www.youtube.com/watch?v=yt97mbJ-8AE  cant see shit on that video but pretty sure he got cleaved on max range as tank for 1500

**Comment by Jerrythemagicdog** [comment]
We can make him cheat a bit and cast it ignoring some restrictions.

**Comment by networm555** [comment]
Well thats for you to decide. The harder the better imho.

**Comment by Jerrythemagicdog** [comment]
Okay, changed after next restart. Thanks!
