### ISSUE TITLE
Formations with linked loot and respawn - issues.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1551]
**Describe the bug**
Formations with linked loot and respawn are causing troubles in the open world - if we pull any such formation (for example .go crea 15138) and pull one member away from the formation to kill it, it will disappear and respawn immediately and then try to catch up with the rest of the formation that might've already left resulting in a rather funny benny hill chase across the map. 
Perhaps we should restrict the introduced changes to the linked loot and respawn formation flag only to creatures inside instanced maps (?)

**Comment by kelno** [comment]
"pull one member away from the formation to kill it" that's because they're supposed to support each other and be in combat at the same time, you shouldn't use FLAG_ENCOUNTER_GROUP alone.
About the running back after a respawn maybe something can be done there.

**Comment by Jerrythemagicdog** [comment]
I pulled them away by continuously hitting one member of the formation and running away while the rest disengaged normally after a certain amount of time.

**Comment by z5n** [comment]
issue has since been fixed
