### ISSUE TITLE
First Aid: Triage quest issues

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1552]
The wounded NPCs seem to be unable to die as they don't seem to be on a timer respective to their injury type, instead they are being drained of health but at the same time it is being restored. This might cause issues for other players if someone decides to not complete it. The Quest giver becomes non interact able during the quest, even though it seems it restores its functions after a while. If 6 NPCs are spawned and you finish it at that point the others 5 NPCs die and their bodies will stay present, likely causing issues for the next person to do the quest.

To dev:
`npc_doctor`
`npc_injured_patient`

**Comment by kelno** [comment]
Updated, need testing

**Comment by Jerrythemagicdog** [comment]
Alliance version tested, works correctly.
