### ISSUE TITLE
[pet] auto-attack when certain abilities are used

### ISSUE THREAD

**Issue by earthworm-jim** [SunstriderEmu/BugTracker#1554]
some abilities cause pets to attack their target despite not being commanded to do so. (e.g. Spell Lock, Soothing Kiss..)

Sunstrider rev. 12978 (6a489daf1327) 2019-12-23

**Comment by kelno** [comment]
Fixed in 12982

**Comment by Jerrythemagicdog** [comment]
> [6:35 PM] Tester: k i just did a line of sight test with spell lock
> [6:35 PM] Tester: i spammed spell lock on my current target whilst my pet was out of line of sight of dummy
> [6:35 PM] Tester: and it decided to walk up and start attacking it aswell
> [6:36 PM] Tester: if i dont spam the spell lock button, it does not attack
> [6:36 PM] Jerry: hmm, okay
> [6:36 PM] Tester: yeh, same thing with focus spell lock
> [6:36 PM] Tester: if i spam the key, it will run to attack aswell

Something still there perhaps?

**Comment by kelno** [comment]
Okay I can look into this case as well
