### ISSUE TITLE
[Warrior] Spell Reflection doesn't display damage of reflected spells.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1557]
**Describe the bug**
Title.

**To Reproduce**
1. Reflect a spell targeted at you as a warrior
2. The damage done does not appear anywhere.

**Expected behavior**
Players see the damage done by Spell Reflection

**Comment by earthworm-jim** [comment]
also reflected spells should be regarded as a cast at self.
`22:47:16:083  Mucklebones suffers 13 Shadow damage from Hagane's Siphon Life.`
(=no healing from SL)

**Comment by Jerrythemagicdog** [comment]
Fixed with https://github.com/kelno/sunstrider/commit/a28027b6f7f3c49c89ebd8fb800ce2b06bfe6152
