### ISSUE TITLE
[Hunter][Spell][Pet] Kill Command #2

### ISSUE THREAD

**Issue by ghost** [SunstriderEmu/BugTracker#1559]
KC can be used only if pet is attacking and only @pettarget.

[[target=pettarget,exists] - Revision as of 21:08, September 27, 2008](https://wowwiki.fandom.com/wiki/Useful_macros_for_hunters?oldid=1615159#Auto_Shot_-.3E_Steady_Shot_.2B_Kill_Command)
#1438 

also auto shot somehow got stuck, shooting at the previous target while i was testing this... not sure what caused it
https://streamable.com/4twyb

Sunstrider rev. 12989 (8c1463ee61f7) 2019-12-26

**Comment by kelno** [comment]
Fixed in 13033

I've seen the auto shoot issue once as well, still needing a way to reproduce it, it should have it's own issue.

**Comment by earthworm-jim** [comment]
sorry, the op isn't very clear. kill command should by default hit player's target (without changing pet's target, ideally)

**Comment by Jerrythemagicdog** [comment]
That was the behavior before.

**Comment by earthworm-jim** [comment]
at the time of my test, it was unusable if playertarget =/= pettarget

**Comment by kelno** [comment]
I found some source saying if should attack pet current victim while looking into this, should have pasted them here. can we try to check what's retail jere then ?

**Comment by earthworm-jim** [comment]
what would be the purpose of [target=pettarget] in these old macros?

**Comment by earthworm-jim** [comment]
#showtooltip Steady Shot
/script UIErrorsFrame:Hide()
/castsequence reset=3 Steady Shot, Auto Shot
/cast [exists,target=pettarget] Kill Command
/script UIErrorsFrame:Clear(); UIErrorsFrame:Show()

that was the commonly used macro if im not mistaken

**Comment by earthworm-jim** [comment]
currently not possible to cast it on player's target or focus

**Comment by kelno** [comment]
Wowwiki: Kill Command directs your pet to your target, it does not order it to attack it's own target, if you meant to start attacking a new target and left your pet to finish off an almost dead one.

**Comment by kelno** [comment]
https://www.wowhead.com/spell=34026/kill-command#comments:id=1720762
says the reverse

**Comment by kelno** [comment]
Current retail behavior also attack player target https://us.forums.blizzard.com/en/wow/t/kill-command-my-pets-target/1049

**Comment by kelno** [comment]
Patch 2.2:  [Kill Command] no longer affects the Hunter’s current target.

Seems it changed a lot haha

**Comment by artieau** [comment]
Working correctly currently
