### ISSUE TITLE
[Hunter][Spell] Storming Wind-Ripper is immune to Hunter's Mark

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1563]
The Storming Wind-Rippers in Elemental Plateau, Nagrand are immune to Hunter's Mark although the rest of the elementals are not immune to Hunter's Mark.

**Comment by Jerrythemagicdog** [comment]
Thanks.
They're immune to arcane and Hunter's Mark's magic school is also arcane. 
Should the elementals not be immune to arcane?

**Comment by Varanak** [comment]
Ah ok. Didn't realize the Hunter's Mark was considered arcane. I'll close this.
