### ISSUE TITLE
[Hunter][Pet] Dismounting from flying mount and using pet attack causes the pet to fly through the air toward the enemy, sometimes the pet gets stuck in the air

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1564]
Using the pet attack ability while dropping from a flying mount causes the pet to fly through the air instead of teleporting to the ground and then running towards the enemy.

Dropping from a flying mount at a higher distance and ordering the pet to attack a target causes the pet to get stuck in the air.

**Comment by Varanak** [comment]
https://streamable.com/s7p27 illustrating both scenarios.

**Comment by kelno** [comment]
This should be somewhat improved now but still not idea

**Comment by Jerrythemagicdog** [comment]
https://www.youtube.com/watch?v=N4c6gZ1jpTA

Possibly related to the latest changes.

**Comment by Varanak** [comment]
The more I play hunter the more I feel the current pet pathing behaviour is better than what the fix would be. The floatiness ensures that in events of choppy terrain the pet doesn't just tele to the bottom and ass pull mobs, especially heroics/dungeons with ledges comes to mind immediately.

So I am going to close this issue as the current behaviour could be a lot worse and I am not sure if a "fix" is really necessary currently.
