### ISSUE TITLE
[Spell] Transform spells don't allow players to mount up and are treated like a shapeshift effect.

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1565]
During the Winter Veil event the PX-238 Winter Wondervolt transforms you into a festive gnome. During this transformation you are unable to mount up due to a "You are in shapeshift form" message, when you should be able to correctly mount up as a slick festive gnome during these holidays.

Other transformations may be affected aswell.

**Comment by Jerrythemagicdog** [comment]
Haha, indeed you're not allowed to mount while affected by this spell but you're able to mount up and run into the machine to get transformed. 
It is also a problem with e.g. "Ninja Costume" (spell: 24710) - player is not able to mount up while affected by this transform.

**Comment by kelno** [comment]
Dup https://github.com/SunstriderEmu/BugTracker/issues/1565

**Comment by kelno** [comment]
Fixed with 13004
