### ISSUE TITLE
[Quest] "Disrupt Their Reinforcements" radius for quest credit is very small

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1567]
~~The quest in Hellfire Peninsula named "Disrupt their Reinforcements" on horde side is currently uncompletable. The quest requires 4 "Demonic Rune Stone" to disrupt each portal to complete the quest, but the error "You have no target" is thrown.~~

https://streamable.com/eu97e

EDIT: It appears the quest is actually completable, but you must stand in the very middle of the portal to get credit. Radius might want to be increased 5-10 yards so players don't assume it is broken.

**Comment by Jerrythemagicdog** [comment]
The spell itself requires the player to move closer, it only has a range of 0-5 yards.

https://db.endless.gg/?spell=34387
