### ISSUE TITLE
Seed of corruption lacks its visual effect

### ISSUE THREAD

**Issue by Fettbergg** [SunstriderEmu/BugTracker#1569]
Right now, the explosion of a seed does not have a visual effect on the ptr.
It should have the same visual as Illidans attacks in demon form.

https://s.blogcdn.com/wow.joystiq.com/media/2007/02/soc03.jpg

**Comment by kelno** [comment]
Uh ho. Missing a dummy spell I suppose

**Comment by kelno** [comment]
Fixed in 13011
