### ISSUE TITLE
Shattered Halls Heroic Bugs

### ISSUE THREAD

**Issue by NeonicSupersonic** [SunstriderEmu/BugTracker#1570]
Kinda lazy scuffed report, since it made from 1 quick run without exsessive testing and mostly quick observations, but I thought it would be better to do it anyway.

- [x] 1)Right from the start first legionnare patrolling mob in 1st gallery missing his 6(4?) adds
- [x] 2)In 1st room one of the mobs have charge abillity with AoE knockabck. I wasnt been able to find any mobs with charge knockback in SHH in databases, but even if they should have it, knockback should be single target.
- [x] 3)Rain of Fire casted by Shadowmoon Darkcasters seems to do very little damage
- [x] 4)Execution timer should start once first person in a group crosses entrance to the gallery on the other side of grand warlock room which leads further into SHH, instead it starts in a middle of grand warlock room or sewers prior to it.
- [x] 5)Executioner himself should spawn and be untargetable untill last boss dies instead of not spawning untill last boss dies.
- [x] 6)Executioner captives shouldnt be in a cages unless I am misremembering it.
- [x] 7)Fire left on a ground by archers during event in a gallery leading to a 2nd boss seems to deal no damage.
- [x] 8)Archers seem to be not linked to a 2nd boss.
- [x] 9)Some assasins mobs seems to have incorrect pathing/placements.
- [x] 10)Adds coming to aid final boss chain aggro assasins in stealth spawned upon engaging boss. Those assasins should only aggro on players attempting to leave boss arena.
- [x] 11) Gladiator - centurions not linked if you pull glad first?
- [x] 12) Add a protection to prevent pulling Nethekurse from other room
- [x] 13) Increase a bit respawn timer in sewer gauntlet, or nerf it another way

**Comment by Jerrythemagicdog** [comment]
Thanks for the report!

> 2)In 1st room one of the mobs have charge abillity with AoE knockabck. I wasnt been able to find any mobs with charge knockback in SHH in databases, but even if they should have it, knockback should be single target.

This one was fixed earlier after your run.

> 4)Execution timer should start once first person in a group crosses entrance to the gallery on the other side of grand warlock room which leads further into SHH, instead it starts in a middle of grand warlock room or sewers prior to it.

This is working correctly, the timer was started by a Shaman in your run. He has crossed the place you've mentioned while you were fighting the Rogue in the Sewers.

> 5)Executioner himself should spawn and be untargetable untill last boss dies instead of not spawning untill last boss dies.

He's currently spawned but hidden, we could make him appear instead.

> 7)Fire left on a ground by archers during event in a gallery leading to a 2nd boss seems to deal no damage.

It does damage but doesn't appear in combat log, the Shaman tested it.

> 9)Some assasins mobs seems to have incorrect pathing/placements.

The Assassins are randomized all throughout the instance, different each run.

> 10)Adds coming to aid final boss chain aggro assasins in stealth spawned upon engaging boss. Those assasins should only aggro on players attempting to leave boss arena.

Fixed after your run earlier.

Thanks, I'll convert your original issue to a list.

**Comment by Jerrythemagicdog** [comment]
https://youtu.be/0phkTyrfzpo

The missing creatures should run out from the corridor and get in their positions

**Comment by NeonicSupersonic** [comment]
Nice job,
On a note of assasins I remember that some of them may path into ogre boss room and in retail tbc it wasnt uncommon to do half circle around boss room to body pull some if they are happen to be there to make actual boss fight save for ninjapulls. Anyway, I dont think it is possible to 100% determine where they should be if they havent retained their original placements in current retail client and issue itself is pretty minor.

**Comment by Jerrythemagicdog** [comment]
There are no assassins within pull range of Warbringer O'mrogg but there might or might not be some around the stairs area!

**Comment by kelno** [comment]
Also : 
- [ ] Gladiator - centurions not linked if you pull glad first?

**Comment by kelno** [comment]
Done
12) Add a protection to prevent pulling Nethekurse from other room
13) Increase a bit respawn timer in sewer gauntlet, or nerf it another way

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.
