### ISSUE TITLE
Bugged spawn in the Fungorr Cavern, Zangarmarsh

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1571]
https://streamable.com/odr9b

~~This issue may overlap with many cavern related areas. I have also noticed this pet attack pathing issue in water very rarely, however I am not able to reproduce it reliably to record.~~

~~#1358 related(?)~~

~~EDIT: Forgot to put in the clip that that area is fully LoS. Can't shoot arrows either.~~

Scratch that. The mob that is standing there is just bugged. It may fix itself after server restart ¯\\_(ツ)_/¯

**Comment by Varanak** [comment]
Went back to check after server restart. Can confirm that it is still standing there bugged.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by blblblaz** [comment]
looks like some weird line of sight problem in the cave in general, https://streamable.com/gylsl

**Comment by Varanak** [comment]
> 
> 
> looks like some weird line of sight problem in the cave in general, https://streamable.com/gylsl

Ya, there is definitely LoS bugs globally in various caves in the world. Mostly quite small, however the most bugged I have ran into so far was the furthermost right cavern entrance connecting Zangarmarsh and BEM for completing the spider kill quest.

**Comment by kelno** [comment]
@blblblaz Can I have some gps positions here?

**Comment by Varanak** [comment]
@kelno The coords are 74,94 Zangarmarsh inside of the cave near the entrance.

**Comment by z5n** [comment]
thanks, fixed with next update!
