### ISSUE TITLE
[Hunter][Pet] Pet attack pathing gets stuck while underwater occasionally and mob pathing underwater getting stuck and evades

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1572]
https://streamable.com/sgxfm

This is in the Serpent Lake, Zangarmarsh at the Fenclaw Thrashers. Exact coords was at 49.5, 39.

There is a certain angle in the water where pet attack pathing gets stuck. I didn't get it in the clip but hunter shots also evaded on the target while the pet attack pathing was stuck. It is a narrow angle it seems and can be fixed my maneuvering around a bit.

EDIT: https://streamable.com/0nd76 Another video(doesn't show the beginning where pet attack pathing gets stuck) after repositioning so pet attack pathing doesn't get stuck, illustrates the mobs underwater evading but gets itself unstuck with very odd pathing that can't reach me. Happened a few times while I completed the "Angling to Beat the Competiton" quest.

**Comment by z5n** [comment]
pet movement has since been reworked
