### ISSUE TITLE
Battlemaster trinkets and Duel Zone Aura

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1573]
**Describe the bug**
If a player is in a Duel in the Duel Zone (.tele beta) and uses the Battlemaster trinket on low HP but the buff then runs out, he will be forever stuck on 1hp in the duel

**To Reproduce**
1. Be in Duel Zone.
2. Duel a player with a Battlemaster trinket (for example .additem 33832).
3. Get the player with Battlemaster to low HP, lower than the HP provided by the trinket (1750hp).
3. Use Battlemaster on the player.
4. Wait for the buff to run out.
5. The player is now stuck on 1hp forever and is immortal until duel end

**Comment by kelno** [comment]
Fixed
