### ISSUE TITLE
[Quest] Thunderbrew Lager can't be completed or picked up - repeatable quests.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1574]
**Describe the bug**
After completing the quest chain "Sweet Amber" (quests: 48, 49, 50, 51, 53) the players are not able to pick up the repeatable quest "Thunderbrew Lager" (117), before that it works fine. The quests are not linked to each other in any way, Thunderbrew Lager should be repeatable to get more Lager by delivering Hops (1274) but even with the items present in the bag we can't press Continue on the page with the quest giver (only after completing the "Sweet Amber" chain, before that we are able to pick the quest up). 

**To Reproduce**
1. .go crea 62840
2. Complete the "Sweet Amber" quest chain (quest ids: 48, 49, 50, 51, 53)
3. Try completing "Thunderbrew Lager" (117)

To dev:
This might be an issue with repeatable quests in general that require items, I'll add more examples here if I run into any.
The creature also doesn't display its gossip menu after completing the chain and goes straight to the repeatable quest completion, maybe related as well.

**Comment by kelno** [comment]
Fixed with 13139
