### ISSUE TITLE
Mage elemental immune to nature's school spell damage

### ISSUE THREAD

**Issue by elsta0012** [SunstriderEmu/BugTracker#1575]
While dueling I noticed that mage elemental pet is immune to spell damage of nature's school. I also verified it inside the arena.
 
I was playing my druid, so you can reproduce it by using spell Wrath or Insect swarm on a frost mage's elemental pet --> damage will be immune. 

As far as I know , pet should only be immune to frost damage. I didn't get any screenshots but I verified it many times, thanks!

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.
