### ISSUE TITLE
[Quest] "Missing Friends" some cages when opened do not give credit for the quest.

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1576]
https://streamable.com/1pnhb

This particular cage is at 31,42 in Terokkar Forest

EDIT: Cages at 31,40 and 30,43 also not working. Currently the only working cage appears to be at 29,42.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in rev. 13019.
To check the current revision, write .server info in-game.
