### ISSUE TITLE
The captured Spirit Towers timer in Terokkar Forest is counting exceedingly slowly

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1578]
I had captured the Spirit Towers in Terokkar Forest roughly 6 hours from the posting of this issue, however the "Blessing of Auchindoun" buff remains and the timer remaining displays 5 hours and 40 minutes despite 6 hours having since passed. In this time the buff should have dropped and the Spirit Towers should have reset and been available for capture again.

**Comment by kelno** [comment]
Every Outdoors PvP objectives was affected. 
Fixed with 13047.
