### ISSUE TITLE
[Warlock] Infernal Immolation aura persists through death

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#1579]
**Describe the bug**
The warlocks Infernal has an Immolation Aura (cant find SpellID).
This aura still occurs from the corpse of the Infernal (when it is dead).

**To Reproduce**
1. Warlock summon Infernal
2.  Kill Infernal
3.  Stand by the corpse, take fire damage

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
Immolation aura should stop when the creature has died.

**Comment by kelno** [comment]
Summon spell: https://db.endless.gg/?spell=1122
Immolation aura: https://db.endless.gg/?spell=19483

**Comment by kelno** [comment]
Fixed in 13047
