### ISSUE TITLE
[Quest] "Wanted: Giselda the Crone" Kil'sorrow Cultists are not counting towards the Kil'sorrow Agent kill count

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1582]
https://streamable.com/csjsb

Currently Kil'sorrow Cultists are not counting for Kil'sorrow Agent kills required for "Wanted: Giselda the Crone" quest, while the Kil'sorrow Spellbinders and Deathsworns are counting for the quest as intended.

**Comment by Jerrythemagicdog** [comment]
Thank you, fixed with next restart!
