### ISSUE TITLE
Entering combat while eating disables the food's health regeneration

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1583]
https://streamable.com/26jrv

Drink mana regeneration in combat is working correctly, but health regeneration in combat isn't currently.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by kelno** [comment]
Fixed

**Comment by kelno** [comment]
Change has been reverted. After some research, previous behavior was actually correct.
Proof here: https://www.youtube.com/watch?v=wAFdoIStMZI&start=10070
(there is still a very small amount of regen due to troll racial)

**Comment by Varanak** [comment]
Good catch. Pservers have had it wrong this whole time haha.
