### ISSUE TITLE
[Quest] "Finding the Surivors" one of the cages in the cave is not giving credit for saving Mag'har prisoners

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1584]
https://streamable.com/lznl0

The location is 29, 25 Nagrand. As far as I can tell that is the only cage that is bugged, but the key drop rate is obnoxiously low so I didn't test every single one, however I was able to test most of them.

The drop rate of the keys may want to be increased because according to my kill logs I killed 200+ ogres to complete the quest, which will likely result in most players skipping the quest unless they get incredibly lucky with the keys.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in rev. 13020.
Updated the drop rate of the keys a bit as well, was at 10% now is at 33%.
