### ISSUE TITLE
Players are able to swap weapons while feared

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1585]
**Describe the bug**
Title.

**To Reproduce**
1. Use Fear on a target (e.g. Psychic Scream)
2. While under fear effects the player is able to swap weapons

**Expected behavior**
Players should not be able to swap weapons while CCed.

**Comment by kelno** [comment]
Could not reproduce because the client doesn't even try to send a weapon change while under a fear, but the server didn't check for it so anyway it's possible in theory (by using a bug or cheating).
Added the check server side, only stunned was checked before.

**Comment by artieau** [comment]
Tested, cant force swap when feared in rev. 13046 @kelno

**Comment by kelno** [comment]
Thanks
