### ISSUE TITLE
[NPC] Geoff's pathing is broken in Stormwind City

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1589]
https://streamable.com/7p6ql

Geoff is an NPC that pathes with Miss Diana and six other children, it appears Miss Diana has forgotten one of her children behind!

**Comment by Jerrythemagicdog** [comment]
Thanks!
We need to help little Geoff!

**Comment by Sheikthecatman** [comment]
Miss Danna found her lost Geoff and he is now a part of the Stormwind tour!

**Comment by kelno** [comment]
Ok but wer commit
