### ISSUE TITLE
Mechanar bugs

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#1593]
- [x] Unstable affliction dispelled doesn't deal damage (Bloodwarder Centurion)
- [ ] Stealing fire shield makes the damage to friendly (astromage npc) (probably generic issue)
- [x] Cache of the Legion re locked itself (probably generic issue)
- [x] Gatewatcher Iron-Hand, follows when doing the hammer thing, should be rooted
- [x] Mechanolord pulls for some reason through the wall when fighting close npcs on the elevator side
- [x] Pathaleon should make every adds explode when enraging. (adds already explode and die by themselves)
- [x] Mechanar Tinkerer should cast the explosion spell when he reaches the end of his charge (pointID 1005).

**Comment by SUN-Leekie** [comment]
Fix Gatewatcher Iron-Hand in a2aba0f5deaa9564c4c3dd7a29f74f01e76f78d2
Fix Patheleon's adds in acd9d1927edff53061edfd2fe924e3c2c604042f
Fix Mechanolord aggro range in a032da40a493bbb526893191a82c2c146be25ef2

**Comment by Jerrythemagicdog** [comment]
Unstable affliction fixed recently as well (77df3e9878f3e8c6884aaced4dba87762fb41e6a) (core)

**Comment by Jerrythemagicdog** [comment]
Fixed the charges

**Comment by kelno** [comment]
Last issue "Stealing fire shield makes the damage to friendly (astromage npc) (probably generic issue)" is already covered by https://github.com/SunstriderEmu/BugTracker/issues/431
