### ISSUE TITLE
Botanica bugs

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#1594]
- [x] First boss: double hit? She has Trash?
- [x] guys in front of first boss should be moved again to correct position + reduce assist range
- [x] (missing animation) -161.020416 471.562347 -17.824894 -> the two mobs there should run away from the room in front of players

**Comment by Jerrythemagicdog** [comment]
> First boss: double hit? She has Trash?

https://wow.gamepedia.com/Commander_Sarannis

"Double Attack — Commander Sarannis attacks twice. "

**Comment by z5n** [comment]
number 3 has since been fixed
