### ISSUE TITLE
Shadowlab bugs

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#1598]
- [ ] Shadow lab timer not starting when engaging the first pack?
- [x] murmur can crit with spell: Resonate (generic issue?)
- [x] murmur enter combat with the blackheart triggers ? Might be fixed already
- [x] vorpil rain of fire shouldn't be interruptible
- [x] vorpil should be taunt immune
- [ ] blackheart should yell "Time for fun!" before mass mind control. During mass MC he should emote "laugh" rather than staring at & following top threat target with his mace raised

**Comment by kelno** [comment]
Fixed crit with b039d5d2ee4ca30854f5739b3f41f9aa88540793

**Comment by SUN-Leekie** [comment]
Fixed rain of fire + taunt in 82bf216b1bedf06e798e5faadbe110908f555a05

**Comment by Varanak** [comment]
Another thing to add to the list that our heroic group noticed was the spellbinders in slabs have an infinite(?) fireball range and they are hitting through LoS(?).

**Comment by Sheikthecatman** [comment]
The spellbinder fireball spell fixed with d33f281d2ce8b3f6c3eef88908f88c8bdd376ccc
