### ISSUE TITLE
[Hunter] Aspect of the Viper doesn't regen enough mana

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1602]
**Describe the bug**
Aspect of the Viper provides too little mana back to the Hunter when on low mana.

Warmane: https://cdn.discordapp.com/attachments/655374360202182659/663451600324657154/unknown.png

Us before changes: https://cdn.discordapp.com/attachments/655374360202182659/663450599500808223/unknown.png

This is both incorrect as the Aspect of the Viper should not provide the entire effect as mp5 to the caster but run a hidden aura every 5 seconds that provides mana back.

**Expected behavior**
It should provide the correct amount of mana back (https://wowwiki.fandom.com/wiki/Aspect_of_the_Viper)

Patch notes:

> Patch 2.2.0 (25-Sep-2007): This ability has received a slight redesign. The amount of mana regained will increase as the Hunter’s percentage of mana remaining decreases. At about 60% mana, it is equivalent to the previous version of Aspect of the Viper. Below that margin, it is better (up to twice as much mana as the old version); while above that margin, it will be less effective. The mana regained never drops below 10% of intellect every 5 sec. or goes above 50% of intellect every 5 sec.

> Patch 2.3.2 (2008-01-08): Effect increased.

> Patch 2.4.2 (2008-05-13): This ability now grants an additional amount of mana each 5 seconds equal to 35% of the hunter's level.
>             (24.5 mp5 at lvl70)

**Comment by kelno** [comment]
Updated logic. The mana increase doesn't show as "mana regen" in the character sheet because it's not, this is mana given every 5s. This gain is not listed in combat log.

**Comment by Jerrythemagicdog** [comment]
Apparently it provides too much regen now on full mana:
Clip:
https://clips.twitch.tv/EagerHeartlessLegCorgiDerp

Additional context:
[9:53 PM] Tester: actually
[9:53 PM] Tester: the regen seems to not scale anymore
[9:53 PM] Tester: the low mana mp5 is fine now
[9:53 PM] Tester: but it seems to be as if I am always low mana
[9:53 PM] Tester: so even on max mana its high
[9:53 PM] Tester: and why I didnt realize it earlier
[9:53 PM] Tester: for some reason
[9:53 PM] Tester: it doesnt update
[9:54 PM] Tester: until I equip and unequip weapons
[9:54 PM] Tester: after swapping to viper

**Comment by Jerrythemagicdog** [comment]
Fixed in 13056.

**Comment by kelno** [comment]
Formula is as follow:
Restored mana every 5 sec = INT * (0.1 + (1.0 - manaPercent) * 0.45) + playerLevel * 0.35

Roughly translated for humans: We give 10 to 55% of your intelligence depending on our % of mana left + 35% of player level
