### ISSUE TITLE
[Pet] Pets don't switch back to aggressive stance once switched from passive to aggressive and back again.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1604]
**Describe the bug**
Title.

**To Reproduce**
1. Switch pet stance from passive to aggressive
2. Switch back to passive
3. Switch back to aggressive
4. Pet is not longer a blood hungry devouring destroyer.

**Expected behavior**
Pet should go back to being aggressive.

**Comment by kelno** [comment]
I can't reproduce this, need some more context.
I'm using a felhunter against a player and switching between the two modes endlessly didn't cause to have any issue.

**Comment by artieau** [comment]
Re-produce steps were correct per @Jerrythemagicdog original post.
IF YOU STAND STILL and spam aggressive/passive, eventually the pet will bug out and be confused and just stand there doing nothing.
As soon as you move, the pet updates and follows the most recent chosen stance.
related to guard/pvp behavior involving 'moving' ? @kelno
