### ISSUE TITLE
[SSC] Underbog Colossus death issues

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#1605]
**Describe the bug**
Death of Underbog Colossus (NPC#21251) 
a) mushroom spawns, do not despawn
b) mushroom buff granted to player Refreshing Mist  (Spell#38730) seems to duplicate on the player while standing in it. Buff only, not the mushroom itself like previous server rev which lead to server crash due to lag.

**To Reproduce**
1. Kill Underbog Colossus in SSC
2. Have mushrooms be chosen as the random death effect
3.  Stand in them

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
a) mushrooms should only last 20 seconds
b) proximity to mushrooms should not cause them to replicate itself or the buff

Server rev. 13051

**Comment by Jerrythemagicdog** [comment]
To dev -  some data:

SUMMON_MUSHROOM_TRAP = 38726,
summons gob (185199)
which casts a spell (38874) that summons a creature (22335) that casts Refreshing Mist (38730)

**Comment by artieau** [comment]
In addition, some mobs fall through the platforms when they spawn.
![image](https://user-images.githubusercontent.com/40563134/72150090-d106a100-33f8-11ea-80e1-df94ea9fe07f.png)
Colossus dies on platform, adds Colossus Rager spawned and fell through the platform and sunk to the bottom of the lake. (bottom of picture)
@kelno

**Comment by kelno** [comment]
Fixed since
