### ISSUE TITLE
[Shaman] Totems not linked to player aggro

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#1607]
**Describe the bug**
A Shamans totems do not keep aggro gained/transferred to the player who placed the totem.
Shaman drops totem A.
totem A aggros a mob in range.
Mob attacks totem and kills it.
Mob resets, not changing aggro state towards player.

**To Reproduce**
1. Stand outside aggro range of mob
2. Drop totem within aggro range
3. Watch mob kill totem then reset
This could be potentially abused to split pull linked trash in dungeons/raids currently. @kelno 

**Expected behavior**
Totem aggro should place player in combat.
Mob should then shift aggro to player after the totem, not reset.

**Screenshots/videos**
Dont have video capability currently,
@me on Disc to demonstrate.

Rev. 13055

**Comment by Jerrythemagicdog** [comment]
To dev:
This could be related to totems being killed by other players and not putting the shaman in combat which we want to keep.

**Comment by kelno** [comment]
Said commit https://github.com/kelno/sunstrider/commit/95da3cb9007aa9fadb88e9a7e4250ad2e5e60a16

**Comment by kelno** [comment]
Fixed with 13095
