### ISSUE TITLE
Mob Leashing - Implementation/Leash-extending Abilities

### ISSUE THREAD

**Issue by Drayo** [SunstriderEmu/BugTracker#1608]
**Describe the bug**

General Mob leashing seems to be based on a Timer, it shouldn't be.

Currently, when you regularly attack a mob, he will follow you forever and that is correct. When the mob left his initial leash radius and you stop to cast a few heals on yourself, he resets. This should not happen.

**Expected behavior**

Every mob has a leash range, each time a mob is hit by a melee attack or an active spell cast, his initial home radius moves to his current position. 
Imagine it like a flagpole and a circle around it if you want to, each time the mob gets attacked, the flag gets planted right where the mob stands.

As long as the creature itself does not leave it's leash area (x yards around the pole), or it's target is unreachable, it should NEVER reset!

**Source/Additions**

Can be tested on classic in starting zones right now.

I cannot be certain of the actual way it's implemented, just that the effects of the above mentioned implementation would properly reflect the retail behavior of normal mobs. 
Stuff like Cannons need special consideration, but this should fall under the evade system which should indeed work with a timer.

Currently, you can only extend the leash with direct attacks, however, the initial application of DoTs should also extend it (Curses/Insect Swarm etc.). Actual DoT damage, Thorn Effects or non damaging AoE spells should NOT extent the leash.

**Comment by Jerrythemagicdog** [comment]
Thanks, currently it is indeed a timer set to 5 seconds. If you don't attack a creature in that time frame it will reset when it's far from its home.

**Comment by Jerrythemagicdog** [comment]
Thanks, currently it is indeed a timer set to 5 seconds. If you don't attack a creature in that time frame it will reset when it's far from its home.

**Comment by maingaming** [comment]
Currently, this is especially frustrating as Shadow Priest or (Affliction) Warlock when trying to kite or multi-dotting 2+ targets. While you are busy applying DoTs on the 2nd target the 1st target will just reset if you walk too far. The Mobs also reset when they are running out of their home zone while feared with DoTs up but without doing direct damage attacks.

**Comment by mechanicsTBC** [comment]
bump, big issue.

**Comment by kelno** [comment]
Somewhat updated, most hostile actions (like putting dots) do reset the evade timer

**Comment by kelno** [comment]
Updated, need some testing before applying live
