### ISSUE TITLE
[Warlock][Spell] Shadow Embrace

### ISSUE THREAD

**Issue by Drayo** [SunstriderEmu/BugTracker#1610]
**Describe the bug**

Different Ranks of Shadow Embrace stack, thus granting up to 15% damage reduction instead of 5%.

**To Reproduce**
1. Get two Warlocks to put a different amount of Points into the Shadow Embrace Talent
2. Both cast Corruption on a Target
3. The Target can gets 2 versions of Shadow Embrace

https://tbc-twinhead.twinstar.cz/?spell=32388

**Expected behavior**
 
Only the highest Rank of the Spell should be applied, overwriting all others.

**Additional context**

It might just be a visual bug, but I think the devs can instantly see if that's the case.

**Comment by kelno** [comment]
To dev: Probably just have to add some spell ranks there

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in rev. 13063
To check the current revision you can write .server info on the PTR.
