### ISSUE TITLE
[Item] Incorrect purchase cost

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#1612]
**Describe the bug**
Reins of the Black War Elekk (Item#35906) sold by Lieutenant Karter (NPC#12783) currently offers this item for free instead of at its correct cost.
The same goes for Swift Warstrider (Item#34129) sold by Raider Bork (NPC#12796).

**To Reproduce**
1. Visit NPC in PvP Champions Hall in SW
2. Obtain free mount
3. Profit

**Expected behavior**
Item should have the same cost as the other items offered by the NPC.
That is, 30 x AB, AV and WSG marks.

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/40563134/71860835-67f90200-3148-11ea-8895-dab1d57e4dee.png)
![image](https://user-images.githubusercontent.com/40563134/71861585-f2426580-314a-11ea-8c26-3303be4508b7.png)

**Comment by Jerrythemagicdog** [comment]
Thank you, fixed with next restart
