### ISSUE TITLE
Quest reward window sometimes hangs up and doesn't let players click Complete Quest

### ISSUE THREAD

**Issue by Syfte-oss** [SunstriderEmu/BugTracker#1613]
After first arriving in the Draenei starting area as a level 1 I took the quest "You Survived!" from Megelon and moved down to Proenitus to turn it in.  As soon as I right-clicked Proenitus the window opened and I completed the quest/got the xp instantly before I could click Complete Quest.  Then I could not close the window with either the Complete Quest button nor the Cancel button.  I had to X out.

I wasn't recording when the instant-completion happened but did record the window refusing to close properly.

Taking the next two quests from Proenitus worked properly and turning in "Botanist Taerix" is working properly.

https://www.youtube.com/watch?v=5d2_BQ-ZaWw

**Comment by Syfte-oss** [comment]
I posted too soon.  Turning in "Botanist Taerix" has almost the same issue.  This time the quest did not complete until I clicked Complete Quest but again the window would not close.  So far every quest dialogue completes instantly without clicking 'Complete Quest'.

New video:  https://www.youtube.com/watch?v=KMWoCRHEYT0

**Comment by Jerrythemagicdog** [comment]
Thanks!
I can't reproduce with these quests, my window is closed correctly but some people have mentioned this issue on certain quests. These examples definitely help getting closer to fixing it though.

**Comment by Syfte-oss** [comment]
It seems to be happening on about 2/3 of my completions.  Is there something I can do to try to troubleshoot this further?  So far I haven't disabled any addons.  On my next session I could try running with none and see if it happens again.

**Comment by Jerrythemagicdog** [comment]
I don't think it's connected to the addons and is something on our end that I have a strong suspicion now about. Thanks though.

**Comment by kelno** [comment]
Fixed all cases we could find: That's 150 quests.
Also fixed A LOT (~2k) of missing links to next quests, now it will open the next quest automatically in many cases where it didn't before.
