### ISSUE TITLE
[Quest] "Inoculation" gives double credit for one success.

### ISSUE THREAD

**Issue by Syfte-oss** [SunstriderEmu/BugTracker#1614]
Using the Inoculating Crystal on an appropriate Nestlewood Owlkin gets two credits, one when the channeling begins and one when it ends.  A player needs to inoculate only 3 mobs to meet the quest's requirement for 6.

https://www.youtube.com/watch?v=_duOBKLBLxc

**Comment by Jerrythemagicdog** [comment]
Thanks!
Fixed in rev. 13056
To check the current revision you can use .server info in game.

Also fixed their wonky behavior after completing the channeling spell and added missing text lines.
