### ISSUE TITLE
Auto-attack sometimes gets stuck

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1615]
**Describe the bug**
Some more information about that:
https://gfycat.com/CheerfulRevolvingBasilisk

Seems to not be fixed entirely as detargeting a creature doesn't stop autoattacking it.

The person testing it said:

>     seems to just not register detarget as /stopattack
>     i didn't test if target=focus also bugs it
>     didn't use any macros at all
> 
>     Jerry: Okay, so in that clip you're autoattacking a creature and using any ability on the ones next to it? Or is it some specific one?
>     Tester: i dont have to i just simply left click away from the target to "detarget" or click escape
>     Tester: and auto will continue

https://gfycat.com/WideCharmingAmericanriverotter

>     i left click the second mob when it happens

**Additional context**
Possibly related to:
https://github.com/SunstriderEmu/BugTracker/issues/1566#issuecomment-571427942

EDIT:
Also easily noticable with attacking a target and then targeting yourself (which should stop the autoattack).

**Comment by artieau** [comment]
Relate to #629 possibly?
https://github.com/SunstriderEmu/BugTracker/issues/629

**Comment by Jerrythemagicdog** [comment]
Improved, but still happened one time, need reproduce steps.
