### ISSUE TITLE
Kara Mobs

### ISSUE THREAD

**Issue by Earjoke** [SunstriderEmu/BugTracker#1619]
Spider mobs Coldmist widow proccs her poison to often. Also when you leave the dungeon in combat the mobs will wait for you at the entrance. 
Cheers Earjoke!!

**Comment by Jerrythemagicdog** [comment]
Thanks!
Fixed in '44395f41217ca1d3e300cc89c864e20975f7007d' (scripts)

**Comment by Earjoke** [comment]
No problem, I am willing to help to make this project great. I am playing this patch now since around 14 years... I kinda know every mob from TBC and I am happy to help if pve testers are needed.




Von meinem Samsung Galaxy Smartphone gesendet.



-------- Ursprüngliche Nachricht --------
Von: Jerrythemagicdog <notifications@github.com>
Datum: 07.01.20 20:10 (GMT+01:00)
An: SunstriderEmu/BugTracker <BugTracker@noreply.github.com>
Cc: Earjoke <limbodancer2013@live.de>, Author <author@noreply.github.com>
Betreff: Re: [SunstriderEmu/BugTracker] Kara Mobs (#1619)


Thanks!
Fixed in '44395f41217ca1d3e300cc89c864e20975f7007d' (scripts)
