### ISSUE TITLE
[Karazhan] Shade of Aran issues.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1621]
**Describe the bug**
Shade of Aran:
- [x] 1. Doesn't cast Arcane Explosion when he pulls players in sometimes because he's casting one of his default rotation spells (such as Arcane Missiles or Fireball, he should stop those and cast Arcane - [ ] Explosion that shouldn't be overriden by that)
- [ ] 2. The Pyroblast he does out of Polymorph is instant.
- [ ] 3. He doesn't sit down to drink and fixates on the target he's at currently.
- [x] 4. All of Aran's Spells are not interruptible after his teleport + slow phase.

**To Reproduce**
1. Engage the boss and pay attention during phase switches.

**Comment by omentbc** [comment]
Adding some things here:

Frostbolt, Fireball and Arcane Missiles should be interruptable.

Blizzard and Flame Wreath should not, but does not have a cast time.

**Comment by Jerrythemagicdog** [comment]
How was this tested? All of those are interruptible currently, I tried on a warrior with Pummel.

**Comment by omentbc** [comment]
Maybe Kelno hotfixed it, as he was there. Just wanted to add it real quick since you had a thread open for Aran issues and it wasn’t in there. Our warrior might have only used Shield Bash and not Pummel though.

**Comment by Jerrythemagicdog** [comment]
Thanks, I'm testing it locally on an earlier version of the core, though. I'll try that!

**Comment by Jerrythemagicdog** [comment]
The spells are also interruptible with Shield Bash.

**Comment by kelno** [comment]
The uninterruptible thing is tied to arcane explosion not being cast as the interrupt immune is being reset at the end of it. It will resolve itself when we fix AE cast.

**Comment by kelno** [comment]
Fixed
"Doesn't cast Arcane Explosion when he pulls players in sometimes because he's casting one of his default rotation spells (such as Arcane Missiles or Fireball, he should stop those and cast Arcane Explosion that shouldn't be overriden by that)"
and 
"ll of Aran's Spells are not interruptible after his teleport + slow phase."
