### ISSUE TITLE
[Karazhan] Netherspite issues

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1622]
**Describe the bug**
- [x] 1. Red beam provides some extraordinary amount of health to the player (not the tooltip value).

- [x] 2. Players are not able to take other beams' stackable debuffs (with beneficial effects) from other beams while being affected by stackable debuffs from their previous beam (not the ones making them immune to pick up beams), so for example it's not not possible for players to go from Red Beam (collect a few charges there) to the Green Beam now because they're not getting any charges from it.

- [x] 3. The Netherbreath in Netherspite's shadow form should only be a frontal cone ability, he also turns around to breathe on people behind.

- [x] 4. The void zones do some weird autoattack sound on players inside of them.

- [x] 5. Added red beam threat never goes away

- [x] 6. void zones don't despawn on combat end (and keep players in combat)

- [ ] 7. void zones can spawn in the air when players jump around

- [x] 8. The red beam should set the current health to the amount of current max health each tick instead of increasing the max health but leaving the current health at what it was.

**Comment by kelno** [comment]
Added some. Also: Should reset threat after ending phase 2?

**Comment by kelno** [comment]
Fixed
"Players are not able to take other beams' stackable debuffs (with beneficial effects) from other beams while being affected by stackable debuffs from their previous beam (not the ones making them immune to pick up beams), so for example it's not not possible for players to go from Red Beam (collect a few charges there) to the Green Beam now because they're not getting any charges from it."

**Comment by kelno** [comment]
Is 3 wrong because the spell hits more than target in a cone or is that wrong because he should somehow not rotate anymore in shadow form?

**Comment by kelno** [comment]
Fixed "void zones don't despawn on combat end (and keep players in combat)"

**Comment by Jerrythemagicdog** [comment]
"Is 3 wrong because the spell hits more than target in a cone or is that wrong because he should somehow not rotate anymore in shadow form?" - one of the testers said he shouldn't rotate, he should just cast it in front of him.

**Comment by kelno** [comment]
3 is https://github.com/SunstriderEmu/BugTracker/issues/1652, not handling that here

**Comment by Jerrythemagicdog** [comment]
Added
"The red beam should set the current health to the amount of current max health each tick instead of increasing the max health but leaving the current health at what it was."
breaks the fight if it doesn't work correctly

**Comment by kelno** [comment]
Fixed "8. The red beam should set the current health to the amount of current max health each tick instead of increasing the max health but leaving the current health at what it was."

**Comment by kelno** [comment]
"6. void zones don't despawn on combat end (and keep players in combat)" as well
