### ISSUE TITLE
[Karazhan] Terestian Illhoof doors are not set to uninteractable when the fight starts.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1623]
**Describe the bug**
Title. The doors shouldn't be able to be interacted with once the fight starts.

**Comment by kelno** [comment]
need to add a gameobject flag to it, don't remember which one exactly but it's the same on most other instance doors (something about them not being selectable)

**Comment by Jerrythemagicdog** [comment]
It's not GO_FLAG_INTERACT_COND that's added on other doors (for example gob: 184281, flags 4 in gameobject_template_addon), this door should be interactable with at the start because players need to pass through it and not be interactable with once the fight starts.

**Comment by kelno** [comment]
Fixed at next restart
