### ISSUE TITLE
[pet] water elemental

### ISSUE THREAD

**Issue by earthworm-jim** [SunstriderEmu/BugTracker#1624]
freeze sometimes cannot be used for no apparent reason (usually the second one, once it's off cooldown). also the elemental randomly stops all activity and the mage loses control over it.

**Comment by Jerrythemagicdog** [comment]
Thanks, could you provide a clip of said behavior or try to narrow down the reproduce steps?
We haven't heard that before.

**Comment by earthworm-jim** [comment]
this happened in duels vs a rogue. tried to reproduce on my own, no success. the two issues are probably related - complete loss of pet control.

**Comment by earthworm-jim** [comment]
had a ton of duels in the last 2-3 days, it didn't happen once so i'm closing... will reopen if it occurs again.

**Comment by Jerrythemagicdog** [comment]
Thanks!
