### ISSUE TITLE
Time to get out of combat

### ISSUE THREAD

**Issue by Macumbafeh** [SunstriderEmu/BugTracker#1626]
**Describe the bug**
It seems Here it take 6+ sec to get out of combat

**To Reproduce**
1. For example take a druid
2. Cast cyclone on a player
3. Wait to stealth in cat form
4. You will see you can stealth just After cyclone

**Expected behavior**
You Can cast a cyclone and stealth just before the end of the cyclone

**Screenshots/videos**
.

**Additional context**
https://www.wowhead.com/forums&topic=23860
Here they Say it was 5 sec in retail.

https://www.wowhead.com/forums&topic=32289
Here too

**Comment by Jerrythemagicdog** [comment]
Yes, that's a custom change that we're sticking to.
The combat timer is 6.1 seconds (static), there's an upcoming page with custom changes like that.

**Comment by Macumbafeh** [comment]
will you keep this timer then? or it will removed at release?

**Comment by Jerrythemagicdog** [comment]
We're keeping it for now, we're going to make the public changes available for everyone to see and notify whenever something changes.
