### ISSUE TITLE
Gruul's Lair - Krosh Firehand fireball should ignore fire resistance

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#1627]
https://db.endless.gg/?spell=33051
Currently works as with usual spells and fire resistance works on it.

To dev:
have to try fixing this with SPELL_ATTR4_IGNORE_RESISTANCES

His fireball by-passes normal fire resistance so do not bother.
WoWHead:  https://www.wowhead.com/npc=18832/krosh-firehand#comments
"His fireball by-passes normal fire resistance so do not bother."
"I had always assumed FR gear would work, but our mage tried tanking him this week in almost 300 FR and said he noticed no difference. Strange since NR/AR triviliazes kiggler."
Note : fire resistance doesn't reduce the dmg taken from the fireballs .. but note this .. you ONLY can FULLY resist a fireball !!!! ;D"

WoWWiki: https://wowwiki.fandom.com/wiki/Krosh_Firehand
"his Greater Fireballs ignore fire resistance gear"

**Comment by Jerrythemagicdog** [comment]
Thanks for the sources. Fixed after next restart.
