### ISSUE TITLE
ranged weapon deals no damage to a target behind an object that doesn't block line of sight

### ISSUE THREAD

**Issue by earthworm-jim** [SunstriderEmu/BugTracker#1630]
https://streamable.com/291qw

thrown weapons seemed to work normally

**Comment by earthworm-jim** [comment]
just noticed from the clip, wand shoot puts trinkets on global. that's likely wrong, not sure.

**Comment by kelno** [comment]
Why shouldn't this pillar block line of sight?

**Comment by earthworm-jim** [comment]
spells can go through that pillar. tried with a different object in coilfang reservoir - bow/xbow/gun are blocked but spells/wands... are not. seems like a more general problem.

**Comment by kelno** [comment]
Nice thanks. It was indeed a general problem with some kind of spells only (and some kind of objects only).
Fixed with 13107

**Comment by Jerrythemagicdog** [comment]
This possibly could have affected this: https://github.com/SunstriderEmu/BugTracker/issues/1455
as well. Just so we're aware!
