### ISSUE TITLE
[Paladin] Illumination talent

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1631]
**Describe the bug**
While under effect of Divine Illumination, Illumination talent returns only half of the spell mana cost.

**To Reproduce**
1. Use Divine Illumination
2. Critical heals (e.g. max rank Holy light) refund 840*0,5*0,6=252 mana

**Expected behavior**
Illumination should not be affected by current mana cost of the spells, rather take in consideration only base mana cost of the spell.

That means critical heals (e.g. max rank Holy light) should refund 840*0,6=504 mana

https://youtu.be/IKGedFem0sQ?t=90
https://youtu.be/IKGedFem0sQ?t=454

Divine illumination used, mana refunded was not halved due to divine illumination.
Note: Video is from early tbc where illumination refunded 100% of spells mana cost. It was changed to 60% later on however it always refunded mana by base mana cost of spells.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed by woiwoz in 'b32e7cf3cb3d7db190b921b0262f7d4acdae08b8'

**Comment by oliverhusted** [comment]
I've been testing a bit myself and i do believe it's the talent point Illumination that's bugged - perhaps divine illumination is as well - haven't tested it yet.

My mana pool is maxed at 10833 mana. When i crit a holy shock (costs 650 mana) from full mana i drop down to 103xx mana which is far below what i should drop to. 

650 * 0,6=390
650 - 390 = 260
10833 - 260 = 10573 which means i shouldnt drop below 10573 mana.
I drop approximately 200 mana lower on ever critted holy shock which is huge for paladins as this is one of their best talents.

THE TALENT DOES NOT REFUND THE AMOUNT OF MANA IT SHOULD

Have a nice day.

**Comment by Jerrythemagicdog** [comment]
Last comment fixed in https://github.com/SunstriderEmu/BugTracker/issues/1886
