### ISSUE TITLE
[Paladin] Blessing of Light

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1632]
**Describe the bug**
Blessing of Light does work only if paladin has this blessing active. While you are yourself buffed by BoL your healing to any target (regardless if the target has or has not BoL itself) is increased. Same behavior goes for Libram of Souls Redeemed.

**To Reproduce**
1. Use Blessing of Light on yourself
2. Now every healing you do, even to others without BoL is increased.
3. Buff your target with BoL and cancel your own blessing
4. Target recieving healing does not benefit from BoL despite he has it active.

**Expected behavior**
Target recieving healing is supposed to be checked if it has BoL active, not the paladin. And if the target has BoL active then you check if the paladin had Libram of Souls Redeemed equipped while casting the heal.

**Screenshots/videos**
https://youtu.be/Oh1sV6EAOvY

**Comment by kelno** [comment]
Fixed in 13133
