### ISSUE TITLE
Line of Sight attacks

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#1633]
**Describe the bug**
Some assets cause LoS for player actions (correctly) but not for every NPC (incorrect).

**To Reproduce**
1. Agro mobs and drag near an object that can be placed between you and mob
2. move around to be out of LoS slowly
3. Player LoS, mob not

**Expected behavior**
The  NPC should  be unable to attack a player with LoS if the player can not attack back.

**Screenshots/videos**
In the below image, the player is unable to perform actions to the target due to LoS.
The mob is able to attack the player though.
![image](https://user-images.githubusercontent.com/40563134/71982707-40558700-3279-11ea-8f5f-ce17e33f652b.png)

rev. 13062

**Comment by Jerrythemagicdog** [comment]
We don't allow players to attack through line of sight in any case currently (seems to be well received in PvP situations, maybe could make a case when attacking creatures).

**Comment by kelno** [comment]
Thanks for the clean issue 
It's an antiabuse mechanic, this won't be changed
