### ISSUE TITLE
[Kara] Maiden of Virtue - Repentance

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#1634]
**Describe the bug**
Repentance (Spell#29511), cast by Maiden of Virtue (NPC#16457) persists on the player while they stand and take damage from Holy Ground (Spell#29512)

**To Reproduce**
1. Stand in melee of Maiden of Virtue to take consecrate damage
2. Boss apply Repentance to all players
3. Take damage tick from consecrate

**Expected behavior**
Damage (from the consecrate/Holy Ground) should break the Repentance.
Any damage should break it.

![image](https://user-images.githubusercontent.com/40563134/71985909-99281e00-327f-11ea-9d98-b40a9dc8f377.png)

rev. 13062

**Comment by artieau** [comment]
Im idiot

**Comment by kelno** [comment]
This tester has been fixed in 13063
