### ISSUE TITLE
[Kara] Spotlight is not visible to player

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#1635]
**Describe the bug**
Spotlight buff from trash before Opera event is not visible to player.
Appears to be under the floor as you can receive the buff if you happen to find it by accident.

Spell#29683

 "Description: Summons a spotlight at the caster's location for $d that buffs anyone inside it."

**To Reproduce**
1. Trash before Opera cast Spotlight
2. cant see it
3. Mob has buff, stand on mob and you get it too

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
A spotlight effect should be visible, so you know where to stand for buff or move mob out of buff.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.
![image](https://user-images.githubusercontent.com/40563134/71986827-39327700-3281-11ea-8157-3869e2015c44.png)

rev. 13062

**Comment by kelno** [comment]
Fixed with 5a0caa181cc5710ad6e033862e648665b764df0e
