### ISSUE TITLE
[Mage] Water Elemental

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1636]
**Describe the bug**
Water Elemental does not stop casting Water Bolt when casting Freeze (pet frost nova)

**To Reproduce**
1. Command pet to attack something
2. Midway through Water Bolt cast use Freeze
3. Water Elemental casts Freeze during the cast of Water bolt without any interruption.

**Expected behavior**
Water Elemental should stop casting Water Bolt when commanded to use Freeze. After casting freeze he should continue casting new Water Bolt.

**Comment by dogster39** [comment]
https://youtu.be/IAoe3akMZUE?t=871 , working as intended

**Comment by Jerrythemagicdog** [comment]
Thanks!
