### ISSUE TITLE
[Shaman] Grounding Totem and Arcane Missiles

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1637]
**Describe the bug**
Grounding Totem completely ignores Arcane missiles

**To Reproduce**
1. Use grounding totem
2. Let mage use AM
3. Nothing happens, Grounding totem effect is up but AM demages you normaly

**Expected behavior**
Grounding totem should ground all of the casted missiles until the first one reaches grounding totem and destroys it.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by Aeded** [comment]
Still relevant, still not fixed

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
