### ISSUE TITLE
[Warrior] Spell reflect

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1639]
**Describe the bug**
When warrior succesfuly spell reflects a spell, secondary procs to spell are not applied to original caster. For example Winter Chill, Shadow Weaving, Misery, Frostbite

**To Reproduce**
1. Play Shadow priest and spec Misery and Shadow Weaving.
2. Use SW:Pain into Spell Reflect
3. Priest gets only SW:Pain reflected, neither warrior nor priest is affected by Misery or Shadow Weaving

**Expected behavior**
When spell reflected spell has a secondary procs from talents, the talents should proc on the spell reflected target too.

https://youtu.be/kWeSvM1SIHk?t=846

Spell reflects Ice Lance, and mage gets affected by Winter Chill.

**Comment by Jerrythemagicdog** [comment]
Thanks!
In fact, Frostbite reflect works (confirmed locally with cheat 100% proc rate) but Winter's Chill doesn't. I would suspect Blackout also works but Misery and Shadow Weaving don't.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
