### ISSUE TITLE
[Shaman] Multiple Grounding Totems

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1640]
**Describe the bug**
When there are more Shamans in party and every one of them uses Grounding Totem, the Grounding Totem Effect Buff is only shown once, which makes unlear how many grounding totems there are

**To Reproduce**
1. Get two shamans into group
2. Both use grounding
3. Only one buff appears

![image](https://user-images.githubusercontent.com/45561230/71994409-f6e54780-3238-11ea-8c2c-d0503ecf9c23.png)

**Expected behavior**
Each grounding totem should have its own buff. And ofcourse they should get consumed one by one, not all at once but I have not tested that (assumed it works fine).
https://youtu.be/qTV_IcpawfI?t=30s

**Comment by SUN-Leekie** [comment]
Fixed in rev 13211.
