### ISSUE TITLE
[Shaman] Totem rank Stacking

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1641]
**Describe the bug**
You are able to stack (and gain effect) multiple ranks of same totems in party.

![image](https://user-images.githubusercontent.com/45561230/71995547-0e253480-323b-11ea-8ec7-b7c38d855439.png)

Futhermore, stacking multiple ranks of resistance totems works only visualy but the greatest effect is applied. (Should not be visualy stacking)

Also when multiple shamans use multiple ranks of Mana Spring Totem, only aura from the first totem is active and other (better) ranks of Mana Spring Totem are ignored.

1. Shaman A uses rank 1 Mana Spring
2. Shaman B uses max rank Mana Spring
3. Effect they have (atleast from the buff tooltip) is from the rank 1 totem, because it was placed first.

**Expected behavior**
There are only three stackable(visualy&with effect) totems (which gain aura effect) in the game: Grounding Totem, Totem of Wrath, and Healing Stream Totem.

If there are multiple ranks of same totem, only one aura should be displayed and highest value aura should be chosen (need to take consideration talents aswell). Rest of the untalented/low rank totems should be ignored.

**Comment by SUN-Leekie** [comment]
Fixed in rev 13210

**Comment by Jerrythemagicdog** [comment]
Fixed
