### ISSUE TITLE
[Shaman] Unleashed Rage stacking

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1642]
**Describe the bug**
Multimple shamans are able to stack multiple ranks of Unleashed Rage (visualy and with effect)

1. Spec shaman A with 2/5 Unleashed Rage
1. Spec shaman B with 4/5 Unleashed Rage
1. Spec shaman C with 5/5 Unleashed Rage

![image](https://user-images.githubusercontent.com/45561230/71997282-e71c3200-323d-11ea-9408-724175a14501.png)

**Expected behavior**
Only the strongest effect (5/5) should be applied.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in 13171.
