### ISSUE TITLE
[Shaman] Healing Stream Totem causes threat

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1643]
**Describe the bug**
Healing Stream Totem causes threat, forcing the mobs destroy it frequently

**To Reproduce**
1. Body pull mob
2. Place healing stream totem and wait for it to heal
3. Mob instantly gains agro and destroys totem

**Expected behavior**
Only Stoneclaw totem and all demaging Fire totems should be able to generate threat.
Healing Stream Totem should not generate threat.

**Comment by SUN-Leekie** [comment]
Fixed in rev 13212.
