### ISSUE TITLE
[Paladin] Seal of Righteousness "on hit" damage is not increased by buffs or talents.

### ISSUE THREAD

**Issue by GigilPiq** [SunstriderEmu/BugTracker#1644]
**Describe the bug**
When attacking a target with Seal of Righteousness active, the damage is not increased by having **Aura of Sanctity**, **Vengeance** stacks active or **Avenging Wrath**

**To Reproduce**

**Base damage**
1. Cast Seal of Righteousness only.
2. Attack a target, note the PER HIT holy damage amount (Keep removing any Vengeance stacks).

**Aura of Sanctity**
3. Cast Seal of Righteousness, Aura of Sanctity.
4. Attack a target, note the PER HIT holy damage amount is the same. (Keep removing any Vengeance stacks).

**Vengeance**
5. Cast Seal of Righteousness, keep Aura of Sanctity.
6. Attack a target, this time, keep Vengeance stacks up. Note the PER HIT holy damage amount is the same.

**Avenging Wrath**
5. Cast Seal of Righteousness and Avenging Wrath, keep Aura of Sanctity.
6. Attack a target, this time. Note the PER HIT holy damage amount is the same.

**Expected behavior**
The holy damage dealt should be increased by the talents or skills mentioned, the spell damage ratio of the "per hit" part is very low and wrong.

**Additional context**
I think the bug comes from the Seal of Right per hit damage. The 3 talents/skills that should increase its damage work for other holy abilities.

**Comment by GigilPiq** [comment]
Still bugged as today. Could you try and find a solution ? This is a spec breaking bug. I can't play with my char ATM thus cannot test any further.

**Comment by kelno** [comment]
Also to check: Spell bonus ratio

**Comment by GigilPiq** [comment]
Yes, spell bonus ratio is very likely wrong. Trying to hit with full +spell damage gear does almost no damage.

It does scale with *spell damage* but the scale seems too low.

**Comment by GigilPiq** [comment]
Trying to revive this. Can someone look into it please ? Thanks devs.

**Comment by kelno** [comment]
This is definitely high on the prio list.
We're currently busy with stability and more global issues but we'll soon get back to emptying this bugtracker, with this bug amongst the first ones

**Comment by Subzors** [comment]
Seal of righteosness also does way too much damage with crusader applied i think its benifitting from the full coefficient but its hitting very hard as far as i can tell this probably should be addressed as well

**Comment by GigilPiq** [comment]
> Seal of righteosness also does way too much damage with crusader applied i think its benifitting from the full coefficient but its hitting very hard as far as i can tell this probably should be addressed as well

Crusader ? The enchant ? Can you detail a bit more ?

**Comment by GigilPiq** [comment]
Old articles I have found on the subject, maybe it can help you : 

https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=1549180#Paladin_coefficients
https://wowwiki.fandom.com/wiki/Seal_of_Righteousness_(old)

**Comment by Ctave6** [comment]
It's not increased by Avenging Wrath either.

**Comment by GigilPiq** [comment]
> **Describe the bug**
> When attacking a target with Seal of Righteousness active, the damage is not increased by having **Aura of Sanctity**, **Vengeance** stacks active or **Avenging Wrath**

Yes, it is already stated in the description. It's the first thing i noticed ^^

**Comment by GigilPiq** [comment]
Devs, I am still waiting for this to be fixed so I can actually play my class in PvE and Arenas. This issue was created January 8th. Do you plan on fixing this someday or should I just quit playing ? I am kinda tired of waiting for my class core spells to be fixed, so just tell me now if I am going to wait another month or two.

**Comment by Bzmode** [comment]
many paladin spells are still broken. consecrate still does almost no damage will spellpower gear.

**Comment by GigilPiq** [comment]
> many paladin spells are still broken. consecrate still does almost no damage will spellpower gear.

https://github.com/SunstriderEmu/BugTracker/issues/1811

**Comment by ammopt** [comment]
@GigilPiq and @Subzors should the "SoR benefiting from 100% spell coefficient applied by SotC" be its own separate issue? Also if anyone can test, is this only happening with SoR, or holy damage in general?

**Comment by Ctave6** [comment]
> Also if anyone can test, is this only happening with SoR, or holy damage in general?

@ammopt Tested with Holy Shield & Avenger's Shield, can confirm it's not bugged with either of them.

For reference (Doc is dated mid-2008):
https://wow.allakhazam.com/wiki/spell_coefficient_(wow)

Particularly, my findings are:
SoR does scale with spell-power correctly. (Tested with Vibro Sword & Latro's Shifting Sword)
Most (if not all) percentile increases aren't applied (Sanc Aura, Imp. SoR, etc.)
Judgement of the Crusader applies 100% of it's bonus (Including bonuses to SoTC from items)
The judgement effect (Judgement of Righteousness) works fine with correct debuff interactions and scaling from percentile increases

Things I've tested a little by coincidence:
Debuffs that increase incoming and outgoing damage seem to function as intended with SoR, if someone wants to test this, test with the Berserk buff from WSG and Death Wish.

If anyone wants to discuss paladin class mechanics in game whisper Pallyfun (A).

**Comment by GigilPiq** [comment]
> > Also if anyone can test, is this only happening with SoR, or holy damage in general?
> 
> @ammopt Tested with Holy Shield & Avenger's Shield, can confirm it's not bugged with either of them.
> 
> For reference (Doc is dated mid-2008):
> https://wow.allakhazam.com/wiki/spell_coefficient_(wow)
> 
> Particularly, my findings are:
> SoR does scale with spell-power correctly. (Tested with Vibro Sword & Latro's Shifting Sword)
> Most (if not all) percentile increases aren't applied (Sanc Aura, Imp. SoR, etc.)
> Judgement of the Crusader applies 100% of it's bonus (Including bonuses to SoTC from items)
> The judgement effect (Judgement of Righteousness) works fine with correct debuff interactions and scaling from percentile increases
> 
> Things I've tested a little by coincidence:
> Debuffs that increase incoming and outgoing damage seem to function as intended with SoR, if someone wants to test this, test with the Berserk buff from WSG and Death Wish.
> 
> Things I didn't bother testing due to lack of weapons:
> Weapon speed normalization with spell damage, can confirm it does not work for Judgement of the Crusader.
> 
> If anyone wants to discuss paladin class mechanics in game whisper Pallyfun (A).

I really doubt the spell coefficient calcutation of the website you linked. It says that it depends on the cast time of the spell and I REALLY doubt Fireball and Shadowbolt have the same spell damage coefficient. Same for Fireblast and Moonfire. There is another coefficient added to them depending on the spell

You page just adds "Certain spells will also have various coefficient penalties associated with them." without giving them ^^ 

These pages say different things (not 2.4.3 version but the calculations should approx stay the same) :  

https://wowwiki.fandom.com/wiki/Spell_power_coefficient (WOTLK)
https://www.reddit.com/r/classicwow/comments/95abc8/list_of_spellcoefficients_1121/ (Classic)

SoR spell power does not scale correctly. The judgement part might be okay but the "on hit" part is bugged as fuck and way lower than it should be. It does scale with spell damage but very wrongly.

**Comment by Kevlarkent** [comment]
IDK if it was in the update today, but SoR do stack with +sp now

**Comment by kelno** [comment]
I made various improvements here, we'll update the server tomorrow morning.

**Comment by GigilPiq** [comment]
Please be working. /pray

**Comment by GigilPiq** [comment]
Ok good job, it's now taking Aura, AW and Vengeance buffs into account.

But it still seems to me the damage output is too low.
What damage calculation formula did you use ?

Is the % increase of the holy talent "Improved Seal of Righteousness" factored after +spell damage calculations ? (and not just base dmg + 15%) ? See the following post describing that it should : https://github.com/LightsHope/issues/issues/50

**Comment by kelno** [comment]
That's generally true for all spells, % increases are done after base damage & spell power calculations. This is also the case here.

The formula of base damage is taken from the tooltip itself. The spell power used is as WoWWiki describes:
9.2% per 1.0 weapon speed, One-handed Seal of Righteousness
10.8% per 1.0 weapon speed, Two-handed Seal of Righteousness

DrDamage formula also seem to roughly match the damage we have currently, though I didn't check what formula they used in the addon code.

**Comment by GigilPiq** [comment]
Could you link the website to the formula ? That's not the one I tried to find.

**Comment by Ctave6** [comment]
https://wowwiki.fandom.com/wiki/Seal_of_Righteousness_(old)?oldid=1432433
Here you go, got the old version of the wowwiki page circa June 27, 2008.
@GigilPiq

**Comment by GigilPiq** [comment]
Okay. I have done some testing and comparing the formulas you showed me with what I get hitting a mannequin and the values are very very close to the theorical values. You can close this bug. Thanks for finally fixing it =) !

**Comment by kelno** [comment]
Thanks
