### ISSUE TITLE
[Priest] Trainer offering untrainable spell.

### ISSUE THREAD

**Issue by Syfte-oss** [SunstriderEmu/BugTracker#1645]
I spec'd a fresh priest without taking Divine Spirit but the Priest trainer in IF is offering it.  Trying to train it does nothing.  Learning spells otherwise seems to be working properly.

https://i.imgur.com/cxlvqBc.jpg

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by woiwoz** [comment]
fixd
