### ISSUE TITLE
[Nagrand Mobs] 3 Windrocs flying too far above the ground.

### ISSUE THREAD

**Issue by Syfte-oss** [SunstriderEmu/BugTracker#1647]
There are 2 Windroc Hunters and 1 Windroc Huntress in the southeast corner of Nagrand that are flying well above the ground.  Afaik They are supposed to be flying just above the ground.

https://youtu.be/c4rFN5DONow

**Comment by Jerrythemagicdog** [comment]
Some of those are cosmetic and are supposed to be there, but thanks!
