### ISSUE TITLE
[Priest] Mind controlled mobs will not melee.

### ISSUE THREAD

**Issue by Syfte-oss** [SunstriderEmu/BugTracker#1648]
While mind controlling a humanoid mob spells and special abilities that are not tied to melee/attack work properly.  The controlled mob will not melee whether I right-click on a target, click the Attack keybind or press T.

Mobs tested so far:
Demon Hunter Initiate in the Ruins of Karabor above Black Temple,
Sunfury Blood Lord in the same location.
Ashtongue Worker in the Ruins of Baa'il.
Bonechewer Scavenger in Hellfire Peninsula.

Note that Bonechewer Bite, which buffs the next melee swing, refuses to activate.
https://youtu.be/K_iC1wvscwM

**Comment by kelno** [comment]
Thanks! 
Fixed in 13095
