### ISSUE TITLE
[Warrior] Sweeping Strikes interactions with Whirlwind.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#165]
**Description and current behaviour:**

Whirlwind (1680) currently behaves the same way as Cleave (25231) (intended for it), which means that whirlwind hit on secondary target causes SS proc on main target, resulting in 4 hits in total. Which results in 2 charges of SS used.

Screenshot of combat log: https://imgur.com/a/kJ91Z5L
Video of what's happening (same behavior): https://youtu.be/WLgXAdfcaP4

**Expected behaviour:**

Whirlwind should not proc SS from secondary target hit. There should be only 3 hits from Whirlwind+SS not 4 hits. WW should consume only 1 SS charge.

Meaning: Main target gets hit from WW, secondary target gets hit from WW, secondary target gets hit from SS caused by hit on main target. No additional SS hit on main target.

https://youtu.be/2tFLsUaxEIM?t=12s
After WW+SS there were 3 hits in total. 2k crit on main target (rogue) then 1.5k SS crit and 1.3k hit on warrior.

https://youtu.be/3rbd02jJXy8?t=4m32s

Main target dies on WW hit, but you can see the stacks of SS here. Before Whirlwind warrior had 7 stacks, after Whilrwind warrior had 6 stacks. So only 1 charge got consumed.

https://youtu.be/NKIGBZ0jjyc?t=1m4s

(play it on 0.25 speed)
After warrior used WW you can see it consumed only 1 charge, and then another charge was consumed by white attack.

_Official Patch 1.10 notes_ (http://wowwiki.wikia.com/wiki/Patch_1.10.0)

> Patch 1.10
> – Execute – This ability will now work with Sweeping Strikes again. If the second victim is below 20% health, they will be hit with the full Execute amount. If the second victim is not below 20% health, they will be hit with normal melee swing damage.
> **– Whirlwind – When this ability is used with Sweeping Strikes, it will burn only one charge of Sweeping Strikes and will generate only one additional attack.**

**Steps to reproduce**
1. On a Warrior get 2 enemies next to each other
2. Activate Sweeping Strikes (12328) and use Whirlwind (1680)
3. Two instances of Sweeping Strikes will be consumed and both enemies will take damage from SS and Whirlwind.

**rev. hash/commit:** 

Sunstrider rev. 10209 (6426fb604472) 2019-01-14 10:06:28 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by Jerrythemagicdog** [comment]
Discovery made by @woiwoz

When one of the Whirlwind hits is a crit only one stack gets consumed. When two of the Whirlwind hits are a crit no Sweeping Strikes stacks gets consumed.

**Comment by kelno** [comment]
Fixed
