### ISSUE TITLE
[Warlock] Curse of Exhaustion should stack with other, stronger slow effects

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1653]
**Describe the bug**
Title. This is a regression as it used to work after https://github.com/SunstriderEmu/BugTracker/issues/687

> Curse of Exhaustion (slows movement and has a hidden secondary effect, warlocks drain life (talented) heals more depending on warlock debuffs on the target) applied along with Crippling Poison here: https://www.youtube.com/watch?v=t8iiLNszJpU&feature=youtu.be&t=175

**To Reproduce**
1. Cast any slow on a player
2. Cast Curse of Exhaustion with Soul Siphon in the talents
3. They should stack

**Comment by SuddenDeath** [comment]
Unable to cast curse of exhaustion on stealthed druid: "More powerful spell already active"
probably related.

**Comment by Jerrythemagicdog** [comment]
Fixed with next update.
