### ISSUE TITLE
Used Adamantite Grenades do not disappear from bags and can be used again.

### ISSUE THREAD

**Issue by maidros** [SunstriderEmu/BugTracker#1654]
**Describe the bug**
When you use an adamantite grenade, it goes on cooldown but the grenade does not disappear from your bags. After the cooldown, you can use that same grenade again a second time. And a third. Etc.

**To Reproduce**
1. Put a single adamantite grenade into your bags.
2. Cast the grenade on the ground beside you.
3. Note the explosion but the grenade is still in your bags, on cooldown.

**Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.**
Affects adamantite grenade, item #23737. May affect all other grenades, like thorium grenade, item 15993, but I cannot test this because PTR vendors only sell this one. The bug does NOT occur however on a similar engineering grenade: frost grenade, item 32413.

**Expected behavior**
The grenade should disappear from your bags after use, or the stack of grenades should have one less number in its total.

**Screenshots/videos**
None.

**Additional context**
None.

**Comment by Jerrythemagicdog** [comment]
I just tried reproducing, can you provide a video clip of it? I can't reproduce, the grenade is consumed correctly.

**Comment by maidros** [comment]
https://www.youtube.com/watch?v=JQ_0FvUdwAM

**Comment by maidros** [comment]
After uploading this video, I wondered if maybe it only happened with stacks in your bags and not with singles, but no, the same result happened after i vendored 9 grenades and cast the last single grenade on the ground. It remained in my bags just like the stack in the video above.

**Comment by kelno** [comment]
Thank you for the video

**Comment by maidros** [comment]
i did more testing.

it happens in the winterspring beta camp, but if i run outside, it doesn't happen. the reason you guys can't reproduce it is because you're not trying it in the winterspring beta camp, like in the video. i tried it again in everlook, and it worked as intended. i ran back to the target dummies by the vendors and the grenades were unlimited again. so for some reason, the error only occurs in the ptr camp.

**Comment by Jerrythemagicdog** [comment]
That's intended for the duel zone (BETA camp and the surrounding lake areas), we don't consume reagents or any items there.
