### ISSUE TITLE
Shadow Sight removal

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#1655]
**Describe the bug**
Shadow Sight (34709) can currently be removed by hard removal spells such as Cloak of Shadow, Ice Block and Divine Shield.

**To Reproduce**
1. Pickup Shadow Sight in arena on Rogue/Mage/Paladin
2. Use Cloak/Block/Bubble
3. Debuff is removed 

**Expected behavior**
Nothing should be able to remove the debuff once collected by the player, besides duration.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in rev. 13097
