### ISSUE TITLE
[Hunter] Entrapment combat

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#1656]
**Describe the bug**
The activation of frost trap and its applications to enemy player causes the Hunter to be placed into combat.

**To Reproduce**
1. Hunter place frost trap out of combat
2. Rogue in stealth walk over frost trap
3. Rogue effected by frost trap, Hunter placed into combat

**Expected behavior**
hunter should not be placed into combat

**Comment by Jerrythemagicdog** [comment]
Can't reproduce being put in combat, it destealthes the Rogue after some time (not sure what exactly is going on here).
Entrapment, the trap proc removes Stealth from the Rogue (intended).
The fact that it puts both players in combat (victim of Entrapment and the Hunter) is not intended and is a bug (was dealt with during the summer but something changed).
