### ISSUE TITLE
Frost Trap should not pull enemy from stealth

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#1657]
**Describe the bug**
Hunters frost trap proc or area of effect tick currently pulls enemy from stealth.

**To Reproduce**
1. Hunter place frost trap
2.  Frost trap pop, area of effect on ground
3.  Stealth player run over area of frost and be pulled from stealth

**Expected behavior**
The stealthed player should be effected by the slow area, but not be pulled from stealth.

**Comment by kelno** [comment]
Does it still?

**Comment by artieau** [comment]
Yes it does still, rev. 15408 @kelno

**Comment by ghost** [comment]
> A Hunter’s Frost Trap ground effect will break Rogues out of stealth.

[WoW Classic “Not A Bug” List - Updated Dec 3, 2020](https://us.forums.blizzard.com/en/wow/t/wow-classic-%E2%80%9Cnot-a-bug%E2%80%9D-list-updated-dec-3-2020/175887)

**Comment by kelno** [comment]
Thanks, closing this then
