### ISSUE TITLE
Hunter pets should be able to eat conjured food

### ISSUE THREAD

**Issue by bjh368** [SunstriderEmu/BugTracker#1658]
All pets that are able to eat bread should be able to eat the conjured food from mages, currently my wind serpent can't eat it.

**Comment by NeonicSupersonic** [comment]
Nope

**Comment by bjh368** [comment]
They have been able to eat conjured food since vanilla, and can do in wow classic as well. 

https://web.archive.org/web/20080213032555/wowwiki.com/feed_pet

Check under Feeding Tips:
"Pets that eat bread can eat food conjured by mages."

**Comment by Ironjudgment** [comment]
Still not fixed

**Comment by SUN-Leekie** [comment]
It seems that every bread conjured is edible but not Conjured Manna Biscuit.
Will need a source for this one.

**Comment by Ironjudgment** [comment]
The only sources I could find:

- https://wow.gamepedia.com/index.php?title=Hunter_pet&oldid=1114018
Under Feeding 
> Pets eat up to six different types of food: meat, bread, fish, fruit, fungus, and cheese. Some pets, like wolves, will only eat meat, but bears and boars can eat any of the six food types. It is easiest to feed pets that eat meat, bread, and fish because mobs often drop meats, fish can be fished, **and bread can be conjured by a mage as pet food.** 

- Old addons for pet feeding like FeedIt
In the LUA you can spot "34062" ID which is Conjured Mana Biscuit
[FeedIt-1.0.zip](https://github.com/SunstriderEmu/BugTracker/files/4315578/FeedIt-1.0.zip)

- This is not conclusive but on most if not all private TBC servers Wind Serpents were feedable by mage food.

**Comment by bjh368** [comment]
All sources, both live and from web archive simply states that conjured food is valid for pet feeding, as long as the pet can eat bread. I cannot find a single source that separates the Conjured Manna Biscuit from the other conjured food with regards to pet food. This server is the only one I've played on (including live TBC) where this behavior is present.

**Comment by bjh368** [comment]
I just looked around for addons now because of  Ironjudgements post regarding FeedIt, and found a page for the old Feed-O-Matic addon. There is a support thread where people complained that they had to use a hotkey to use Conjured Manna Biscuit over other food. They're saying that pets can (and should) eat the biscuits, but that the addon was clunky about it.

_"I have two requests/bug reports. First, conjured mana bisquits require alt clicking (the “bypass” command) to feed to my wind serpent. They should be automatic TOP priority without any special treatment. ..."_

http://fizzwidget.com/gfw-feedomatic-2-4-1/

**Comment by Ironjudgment** [comment]
Sooo?

**Comment by SUN-Leekie** [comment]
Thank you for the sources!
It will be fixed at next restart.
