### ISSUE TITLE
[Paladin] Crusader strike does not refresh judgements from other paladins

### ISSUE THREAD

**Issue by NeonicSupersonic** [SunstriderEmu/BugTracker#1659]
**Describe the bug**
Crusader strike does not refresh judgements from other paladins (tested only with judgement of wisdom).

**To Reproduce**
Paladin A judges wisdom
Paladin B hits target with crusader
Wisdom is not refreshed

**Expected behavior**
Crusader strike should refresh all judgements on target to their full 20s duration

**Comment by kelno** [comment]
Probably fixed with 13122

**Comment by GigilPiq** [comment]
I'll try right now.

**Comment by GigilPiq** [comment]
Nope; still bugged with no changes.

**Comment by Jerrythemagicdog** [comment]
Fixed.
