### ISSUE TITLE
[Nagrand] Murkblood Invader patrol has player-induced pathing disruptions.

### ISSUE THREAD

**Issue by Syfte-oss** [SunstriderEmu/BugTracker#1660]
**Describe the bug**
The Murkblood Invader elephant patrol that circles around the map will stop and start depending the player's distance from it.  This does not seem to be a client issue as it can be observed from two different clients at once.

**To Reproduce**
1. Hold position with the patrol near the edge of your maximum draw distance.  If the patrol is moving away from you it will eventually stop and stay stopped.
2. Approach close to the patrol and it will begin moving again. 
3. Repeat.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://www.wowhead.com/npc=18238/murkblood-invader

**Expected behavior**
The patrol circles the map until it encounters something that aggroes it, including players and Consortium npcs.

**Screenshots/videos**
The issue viewed from one client:  https://youtu.be/Cu7unoNjsA8
The issue viewed simultaneously from two clients:  https://youtu.be/EjIdHXsT6TM

Note that there is a gap of roughly ten minutes between this videos during which the patrol did not move from the spot where it is halted as the second video begins.

**Additional context**
I can try shooting a new video of two clients at once if this one isn't usable.

**Comment by Jerrythemagicdog** [comment]
Thanks!
The visibility range is really large on the PTR right now and they don't get updated and don't start their patrol until you actually get closer to them, similar thing can be observed with the Fel Reaver in Hellfire Peninsula. As funny as it looks, this is not going to happen on the live server.

**Comment by Syfte-oss** [comment]
Okay, good to know.  I was intending to report Durn, Banthar and the Fel Reaver next.  :D
