### ISSUE TITLE
[Paladin] Crusader Strike doesn't trigger weapon procs

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1661]
**Describe the bug**
Title.

**To Reproduce**
1. Get Crusader Strike (35395) on a Paladin
2. Enchant your weapon with Mongoose / Lifesteal (.additem 22025 or .additem 35458)
3. Select a target and .cast batch 35395 200

Information:
https://www.wowhead.com/forums&topic=19182#p167846

**Expected behavior**
Crusader Strike should be able to proc weapon procs.

**Comment by kelno** [comment]
Damn paladins, can't they just behave like every other kids ? Always going on about their oh so special abilities

**Comment by kelno** [comment]
Fixed in 13142
