### ISSUE TITLE
[Slabs] Cabal Executioner not using Whirlwind.

### ISSUE THREAD

**Issue by Syfte-oss** [SunstriderEmu/BugTracker#1662]
**Describe the bug**
The Cabal Executioner's in the final room of Shadowlabs (on heroic) did not use their Whirlwind ability.

**To Reproduce**
1. Punch a Cabal Executioner in the face.
2. Wait. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://www.wowhead.com/npc=18632/cabal-executioner#abilities

**Expected behavior**
Occasional whirlwind attacks.

**Screenshots/videos**
This is the only video I took of a mob fight in the room.  3 Executioners are pulled (good job, tank ;p) and none of them use their Whirlwind.
https://youtu.be/OioPgm8s7yg

**Additional context**
On a side note, congratulations on Blackheart the Inciter.  His mind control worked perfectly.  On my previous private server a mind control just left players standing still until it wore off.

**Comment by Jerrythemagicdog** [comment]
Thank you, fixed after next restart!
https://github.com/kelno/sunstrider-scripts/commit/a831ca713db4179554dce0ced118986707bcf147
