### ISSUE TITLE
[Slabs] Void Travelers (Vorpil adds) spamming Shadow Nova without cooldown.

### ISSUE THREAD

**Issue by Syfte-oss** [SunstriderEmu/BugTracker#1663]
**Describe the bug**
During the fight with Vorpil (on heroic) if any one Void Traveler reaches Vorpil they spam Shadow Nova with no apparent cooldown.  They also spam their heal on Vorpil, quickly returning him to full health.

**To Reproduce**
1. Begin the Vorpil.
2. Allow a Void Traveler to reach Vorpil.
3. Release and run back.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://www.wowhead.com/npc=19226/void-traveler#abilities:mode=heroic

**Expected behavior**
The Shadow Nova should cast once, damaging all in range slightly and healing Vorpil slightly.

**Screenshots/videos**
Hit by Shadow Nova 8 times in .31 seconds on the previous attempt.
https://youtu.be/rmHzyr4mSnE

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks a lot for the video!
