### ISSUE TITLE
[hunter] Disappearing cast bar on Steady Shot

### ISSUE THREAD

**Issue by earthworm-jim** [SunstriderEmu/BugTracker#1664]
if used within the 0.5 autoshot cast time
https://streamable.com/jyy35

**Comment by Jerrythemagicdog** [comment]
Related: https://youtu.be/OPy4Loa2ZyU

**Comment by sposobniy** [comment]
https://www.twitch.tv/sposobniy/clip/CrunchyPricklyKiwiSpicyBoy  I am not sure this same bug , but looks similar.

**Comment by earthworm-jim** [comment]
that was arcane + auto (heroism gone, visual). also 'instant steady' briefly shows the casting bar.

**Comment by kelno** [comment]
It was broken one week ago by a new change. Fixed now, thanks!

**Comment by kelno** [comment]
6120fd38812842bf08afd4c7ca49811829f00ba4
