### ISSUE TITLE
Damage shields deal damage through damage absorb (Mana Shield effects or Ice Barrier) effects

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1665]
**Describe the bug**
Title.
Damage Shields such as Thorns (467) or Retribution Aura (7294) deal damage through absorb effects like Ice Barrier or Mana Shield (1463). This also applies to creatures like Arcane Anomaly (16488) and their Mana Shield (29880) which can be killed very easily when they're on one hp relying on their Mana Shield.

**To Reproduce**
1. Cast any of the absorb shields listed above.
2. Hit a target with any of the damage shields listed above.
3. Damage is done through the absorb shields.

**Comment by kelno** [comment]
Thanks for the IDs.
There's some evidence on the technical side that damage shield effects (such as thorns) should ignore absorb, so it would be nice to have some proof. But I realize it could be hard to get.

The Arcane Anomaly guy can be fixed regardless of that.

**Comment by kelno** [comment]
Nvm I'm stoned I can just make the damage appear normally, just without the "absorbed part".

**Comment by kelno** [comment]
Fixed.
Though the damage shield use a different packet to tell the client damage was reflected, and that packet doesn't support "absorbed" damage so I made it so it just shows the damage done even if it's in a shield.
