### ISSUE TITLE
[General] Chain dmg effect dont chain on kill

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1667]
**Describe the bug**
Chain effects like Chain lightning or multi-shot do not chain if the main target was killed and other targets are outside of LoS from shaman, but not from killed target

**To Reproduce**
https://youtu.be/eF-bqUOTdfk.

**Expected behavior**
It should chain normaly, regardless if the main target was killed or not. If this is one of your idiotic custom changes, get rid of it.

https://youtu.be/m8nOaNMHZIQ?t=331

**Comment by Jerrythemagicdog** [comment]
Thanks!
> If this is one of your idiotic custom changes, get rid of it.
Keep GitHub for issues not opinions please!

**Comment by Aeded** [comment]
spell chain animation is missing aswell https://youtu.be/eF-bqUOTdfk?t=21 Not going to make it as separate issue

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
