### ISSUE TITLE
[General] Chain effects should not chain behind caster

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1668]
**Describe the bug**
Dmg chain effects like chain lightning and multi shot can chain behind caster. (Chain heal still should be able to bounce behind casters)

**To Reproduce**
https://youtu.be/xB2CePPO--E

**Expected behavior**

1) https://youtu.be/lOHOp-s6__g?t=653
First chain lightning did not chain because other targets were behind the caster at that moment, then the second chain lightning from Lightning Overload finaly chained because the the rogue was no longer behind shaman

2) https://youtu.be/4okg6BmVoGM?t=15s
Chain effects should not go behind 180 degree cone infront of caster.

**Comment by kelno** [comment]
Doesn't seem to be an issue as of now
