### ISSUE TITLE
[Warrior] Sweeping strikes and cleave

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1670]
**Describe the bug**
Cleave on secondary target procs SS on main target, consuming an additional SS charge.

**To Reproduce**
https://youtu.be/zv0qvZdW-gU?t=15

**Expected behavior**
Hitting secondary target with cleave, should not proc SS on main target. Cleave should only consume one SS charge and only proc SS hit from the dmg on main target.

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1487

**Comment by Jerrythemagicdog** [comment]
Some (bad quality) retail footage:
https://youtu.be/-41Dgo6auCA?t=115
https://youtu.be/-41Dgo6auCA?t=282
