### ISSUE TITLE
Mage : Winter's Chill and Blizzard

### ISSUE THREAD

**Issue by Oliaxz** [SunstriderEmu/BugTracker#1671]
**Describe the bug**
I believe Winter's Chill should be applied on every tick of damage with Blizzard, according to the tooltip. You dont need imp blizzard either, cause winter chill doesnt require chill efffect to be applied. Currently it looks like the proc chance is reduced cause its an AoE spell. Like the warlock stun talent on Hellfire. Im no expert though.

**To Reproduce**
1. Spec 5/5 in Winter's Chill
2. Cast Blizzard on Dummy
3. Observe proc rate below 100% on Winter's Chill when damage sucessfully land (no resist).

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
Winter's Chill should proc on every tick of dmg.

**Comment by Aeded** [comment]
no, nextime come with some facts and not "I believe"

**Comment by Jerrythemagicdog** [comment]
This is indeed invalid and currently is only applied on the first cast of Blizzard (or I believe that was the intent, similarly to Clearcasting and other procs)

**Comment by Oliaxz** [comment]
> This is indeed invalid and currently is only applied on the first cast of Blizzard (or I believe that was the intent, similarly to Clearcasting and other procs)

Well its current behavor is really weird : 
1.  It does not always proc on first tick
2. It can proc on any tick
3. Im getting more than 1 proc per channel, rare, but it happens.

**Comment by kelno** [comment]
The way it should work right now is that the chance is equally divided across each tick
