### ISSUE TITLE
[The Mechanar] Fire Elementals not despawning after Nethermancer Sepethrea dies

### ISSUE THREAD

**Issue by franticx187** [SunstriderEmu/BugTracker#1674]
Raging Flames do not despawn after killing Nethermancer Sepethrea (npc ID 19221)

1. Kill Nethermancer
2. Kill Elementals?

**Expected behavior**
Elementals disappear after killing Nethermancer
https://youtu.be/y1ba49zAcRQ?t=116

**Screenshots/videos**
https://www.twitch.tv/videos/535093173

**Comment by Jerrythemagicdog** [comment]
Thank you, fixed.
