### ISSUE TITLE
[Kara] Huntsman does not use Berserker Charge.

### ISSUE THREAD

**Issue by Syfte-oss** [SunstriderEmu/BugTracker#1675]
**Describe the bug**
Attumen the Huntsman does not use his Berserker Charge at all during his fight.

**To Reproduce**
1. Pull Huntsman
2. Wait

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://wow.gamepedia.com/Attumen_the_Huntsman#Attacks_and_abilities
>>Berserker Charge: A charge that does 200 damage on cloth and applies a knockdown for a brief stun. It hits a random target at 8-40 yards. This charge frequently does only around 200 damage, but it is possible for Attumen to get an attack on the charged target, causing 6,000+ damage. Gained after mounting Midnight.

**Expected behavior**
Random charges against random raid members.

**Screenshots/videos**
https://www.twitch.tv/videos/535065746
Huntsman mounts at 02:08:07.

**Additional context**
On a side note, Attunmen died surprisingly fast.

**Comment by kelno** [comment]
Fixed
