### ISSUE TITLE
[Kara] Aggro spreads like a forest fire in The Grand Ballroom.

### ISSUE THREAD

**Issue by Syfte-oss** [SunstriderEmu/BugTracker#1677]
**Describe the bug**
Attempting to pull one pack in The Grand Ballroom results in pulling multiple packs and any nearby patrolling elites.

**To Reproduce**
1. Pull a pack from the stairs.
2. Watch a sea of red names charge in.
3. Release and run back.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
Not sure what to put here.
https://wow.gamepedia.com/Grand_Ballroom

**Expected behavior**
A tank should, with care, be able to pull one pack at a time to the stairs.

**Screenshots/videos**
https://www.twitch.tv/videos/535065746
First pull at 02:09:53.
Second pull at 02:13:07.

**Additional context**
This was also an issue on Excalibur that they improved but never quite fixed.

**Comment by kelno** [comment]
6355af54be58db49c09a709a09cfaddee8f64343

**Comment by Jerrythemagicdog** [comment]
Fixed, thanks!
