### ISSUE TITLE
[Mechanic] Channeling and casting leeway

### ISSUE THREAD

**Issue by SuddenDeath** [SunstriderEmu/BugTracker#1680]
**Describe the bug**
Channeling leeway is currently only 10% of the spells total range with a max limit of 3 yards.
Casting leeway is currently 10%(correct) with a max limit of 3 yards(incorrect).

**Expected behavior**
Channeling leeway should be 20% of the spells total range, with no additional limit
Casting leeway should be 10% of the spells total range, with no additional limit.

**Screenshots/videos**
https://www.youtube.com/watch?v=aJB2hUIK3To
https://www.youtube.com/watch?v=J65y7osMW5c
Retail testing during WoD, have verified this in classic as well but can re-test.

**Comment by kelno** [comment]
Thanks, the video are good source material. I liked the idea of using the barriers for reference.

The rule will stay as it is for now and is listed here: https://endless.gg/changes
