### ISSUE TITLE
Pets disappearing into the night after /petstay 

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1683]
**Describe the bug**
It seems to happen quite often after the pet being in /petfollow and then /petstay.
It's not very consistent but the first two clips are the best reproduce steps we have so far.
The clips:
https://streamable.com/r5v27
https://streamable.com/vylxx

More clips:
https://clips.twitch.tv/SavoryLightKimchiImGlitch
https://clips.twitch.tv/AgreeableIronicCobblerOptimizePrime
https://streamable.com/527j5

**To Reproduce**
1. Put the pet on follow
2. Put the pet on stay
3. Stop moving on your character (? - could be relevant)
4. Cast a spell on a target (Devour Magic seems to be in most cases but probably doesn't matter)
5. The pet will run away to Singapore (sometimes)

**Comment by kelno** [comment]
Not 100% sure this is fixed as I didn't reproduce it but probably fixed with 13137

**Comment by earthworm-jim** [comment]
one consistent way to reproduce is petattack > petstay > petattack > petpassive
two outcomes (so far):
1. runs to the target and stays there (should return to stay location)
2. as you say, runs away to Singapore ( [rev. 13127](https://streamable.com/834ak) )

**Comment by kelno** [comment]
Well nice! Now we have a way to test if it's fixed

**Comment by Jerrythemagicdog** [comment]
Tried with the provided reproduce steps, fixed.
