### ISSUE TITLE
[Spell] Demoralizing Shout interrupts channeling spells

### ISSUE THREAD

**Issue by SuddenDeath** [SunstriderEmu/BugTracker#1688]
**Describe the bug**
Demoralizing Shout interrupts channeling spells

**To Reproduce**
1. Cast hellfire, rain of fire, drain life etc
2. Have a warrior cast demo shout on you
3. interrupted

**Comment by hufsa** [comment]
Thanks. Fixed.
https://github.com/kelno/sunstrider/commit/e89c6c4b636e32453bf28fc286e11ede3a4b9901
