### ISSUE TITLE
[Mechanic] Unable to /duel someone while waiting for pending duel

### ISSUE THREAD

**Issue by SuddenDeath** [SunstriderEmu/BugTracker#1691]
**Describe the bug**
Currently unable to /duel someone while waiting for pending duel

**To Reproduce**
1. /Duel player A
2. Player A is AFK so he doesn't accept or decline
3. /Duel player B, nothing happens.

**Expected behavior**
When dueling player B it should automatically cancel previous duel and a new duel flag goes down.

**Comment by kelno** [comment]
Thanks.
As a workaround you can currently you can run out of range to cancel the duel

**Comment by InhumanGM** [comment]
> As a workaround you can currently run out of range to cancel the duel

_/forfeit_ works as well!

**Comment by kelno** [comment]
Fixed with next server update
