### ISSUE TITLE
Mana tide Doesn't regen through textures

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1694]
Spell : http://tbc.cavernoftime.com/spell=16190  

Problem : Regenerate mana only if you line of sight with totem. 

How reproduce : Drop totem , go for the any pillar  - you do not get mana 

 https://clips.twitch.tv/SuperHardMelonOptimizePrime  

How it Should work : https://youtu.be/L2gQi8Yd8R8?t=120

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed 13171
