### ISSUE TITLE
Grouding totems aura not not applicable to cyclone targets 

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1696]
Problem ; Grounding totems delayed , and dont buff cycloned target . Not possible sometimes grounding cast after cyclone from your teammate

When you or your teammate in cyclone , sometimes
https://www.twitch.tv/sposobniy/clip/AggressiveSourFishTakeNRG

**Comment by Jerrythemagicdog** [comment]
The Cyclone and your Grounding Totem most likely happen in the same server update and it leads to this. It's pretty visible when you slow down the clip to 0.25x.
