### ISSUE TITLE
[Quest] Benedict's Chest

### ISSUE THREAD

**Issue by Badarki** [SunstriderEmu/BugTracker#1698]
Benedict's Chest https://classic.wowhead.com/object=3239/benedicts-chest is an invalid target when we use Benedict's Key https://classic.wowhead.com/item=4882/benedicts-key.

**Comment by Jerrythemagicdog** [comment]
I'm not able to reproduce locally, could I ask you to provide some details?
What faction and level were you when you tried to open the chest?

**Comment by Jerrythemagicdog** [comment]
Quest works correctly, clear your Cache if you're experiencing issues.
