### ISSUE TITLE
[Karazhan] Library Teleport Non-Functional

### ISSUE THREAD

**Issue by RTTMsec** [SunstriderEmu/BugTracker#1700]
**Describe the bug**
After defeating the Shade of Aran, the doorman at the front entrance of Kara should provide the option for players to teleport to the library. Currently no interaction exists.

**To Reproduce**
1. Defeat Shade of Aran
2. Re-enter the front entrance and talk to the doorman. 
3. No option to teleport to the library should exist. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://www.wowhead.com/npc=16153/berthold

**Expected behavior**
The conversation prompts with Berthold, the doorman, should be updated after killing Aran to include the additional options.

**Comment by Jerrythemagicdog** [comment]
To dev:
Updated with 'da5e05d8b3a0d53b2eec68b53394fd29cdce73f0' (scripts) needs adjustment.

**Comment by kelno** [comment]
try this:
`REPLACE INTO `conditions` (`id`, `SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES (3231598, 15,20104,3,0,0,13,6,3,2,0,0,0,0,'','Show options for gossip only if Shade of Aran is done');`

**Comment by Jerrythemagicdog** [comment]
No worx

**Comment by kelno** [comment]
Fixed with 13276
