### ISSUE TITLE
[Karazhan] Netherspite Trash

### ISSUE THREAD

**Issue by RTTMsec** [SunstriderEmu/BugTracker#1701]
**Describe the bug**
The trash pack between Netherspite and Chess usually consists of three Ethereal Spellfilchers, however it currently only consists of one.

**To Reproduce**
1. Enter a new Karazhan raid ID.
2. Navigate to away from Aran towards Netherspite's room.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://www.wowhead.com/npc=16545/ethereal-spellfilcher

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/13806508/72407407-18f13500-3725-11ea-9773-b8648b485f9a.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, actually not necessarily true with this source of old Karazhan on retail https://youtu.be/NR1LdzZqxdM?t=1498

Added missing linking.
