### ISSUE TITLE
[Rogue] Dirty Deeds - affects Poison damage as well

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1704]
Describe the bug : Rogue tailent : Dirty Deeds - affected not only special abilites , works also with poisons  , flame cap , maybe weapon procs ? 

To Reproduce : 
Look at procs damage  Wounds poisons / Flame cap above and below 35% enemy HP . 

How it should work : should affected only special abilites . 

Proofs : 
1) tooltip 
2) https://youtu.be/8KBoaYrNt9c?t=305 Refreshing Wound Poisons below 35% HP , same damage  (77) like in during video before  

If you not sure , have rogue dirty deeds on this video  you can check moments 

https://youtu.be/8KBoaYrNt9c?t=20  above 35% HP 5 CP Rupture tick 222 
https://youtu.be/8KBoaYrNt9c?t=264 below 35 % HP   5 CP Rupture tick 267  - with Dirty deeds

**Comment by blblblaz** [comment]
confirmed, thanks

**Comment by kelno** [comment]
Probably fixed with 13194

**Comment by Jerrythemagicdog** [comment]
Not fixed, tested on 13196

**Comment by hufsa** [comment]
Thanks, fixed with next update!
