### ISSUE TITLE
[Item] Idol of the Emerald Queen 

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1705]
http://tbc.cavernoftime.com/item=27886 
Describe the bug :  Adds a full boost (+88)  to every Lifebloom.  Not reduced by spell power coefficient .

How it should work : 
Healing bonus from this idol should reduce  to 
https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=1492745
LifebloomHoT  : approx. 51.80% (~62.16% with Empowered Rejuvenation) 

Affected Empowered Rejuvenation)  works correctly- which makes the increase even more powerful.

Info about this : 

https://www.wowhead.com/item=27886/idol-of-the-emerald-queen#comments 

1)By TheKaz
"Just won this item last night in Shadow Lab. Based on my tests, it seems to add +8-9 to each tick of Lifebloom." 

2)By jfowle02 on 2007/02/05 (Patch 2.0.6)
"can confirm the increase of about 7-8 per tick on Lifebloom," 

3)By Anger on 2007/12/11 (Patch 2.3.0)
"This does NOT grant 88 to the HoT-Component of Lifebloom, only 55 (with 4/5 Empowered Rejuvenation and 5/5 Gift of Nature). This is 62.5%. Theoretically you would expect 58.3% (= 7s / 12s) untalented and 74.4% (= 7s / 12s * 1.1 * 1.16) with above mentioned spec. It seems quite clear that the Healing Bonus of this Idol does not benefit from Empowered Rejuvenation at all, but maybe half from Gift of Nature (2 component spell or something...). But since I seem to be doing ~60% of my healing in 2vs2 with Lifebloom (~2/3 from HoT), I will still be using this Idol frequently :)" 

4) also in this comment some tests results
By Anassar (1,195 – 15) on 2007/08/11 (Patch 2.1.3) 

"So thats ~20 healing per tick of Lifebloom once you have it stacked up."

**Comment by blblblaz** [comment]
On a DS druid with 5/5 Gift of nature Idol of the Emerald Queen currently gives +13 to the Lifebloom HoT, not 88

**Comment by sposobniy** [comment]
88/7 ~13 . Yes its wrong  , but should be 88*0.5180/7 - calculating without tailents and bonuses etc

**Comment by blblblaz** [comment]
yeah, I misunderstood the report, you're right, thanks

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in rev 13171
