### ISSUE TITLE
[Quest] Stones that bind us

### ISSUE THREAD

**Issue by NeonicSupersonic** [SunstriderEmu/BugTracker#1706]
**Describe the bug**
Breaking stone near any but Razelikh servants doesnt kill them thus making quest impossible to complete

**To Reproduce**
1.Pull any of 3/3 servants near stone
2. Hit them untill they banish on 0 hp
3. Break stone
4. Get animation
5. But they dont die

https://classic.wowhead.com/quest=2681/the-stones-that-bind-us
https://classic.wowhead.com/npc=7669/servant-of-grol
https://classic.wowhead.com/npc=7670/servant-of-allistarj
https://classic.wowhead.com/npc=7671/servant-of-sevine
https://classic.wowhead.com/object=141812/stone-of-binding (not sure)

**Expected behavior**
breaking any stone near banished servant should kill them

**Screenshots/videos**
[image](https://user-images.githubusercontent.com/45077198/72441450-c3b43280-37bb-11ea-82c4-6649081a2450.png)

**Comment by frastsytt** [comment]
Tested on 4/11/2020. Same results as described.

**Comment by Sheikthecatman** [comment]
Thanks! It should be fixed next server restart. The respawn timer for the stones has been decreased too.
