### ISSUE TITLE
[Quest] Bonechewer Blood impossible to complete

### ISSUE THREAD

**Issue by Badarki** [SunstriderEmu/BugTracker#1708]
I've collected all the quest items and it's impossible to complete Bonechewer Blood https://www.wowhead.com/quest=10450/bonechewer-blood ; when I interact with the NPC it only tells me to accept the quest while i've already completed it. Tried to DC etc but Nothing worked.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by Jerrythemagicdog** [comment]
Fixed in rev 13172
