### ISSUE TITLE
Rip (Feral) 

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1709]
http://tbc.cavernoftime.com/spell=27008

Describe the bug: 
Deal more DMG then should 

To Reproduce : 
My tests results  (no gear , and no tailents) 

Should be :  

Rank 7, 5 combo points: Damage = Attack Power * 0.24 + 1092  

https://imgur.com/dcSmKpi  
I was 1644 damage for full bleed time  (rank 7 Rip) 
Feral should have 0.24 bonus from Attack power (same like Rupture) if I remember this correctly .
Damage bonus should be 382*0.24=92  . 

Info about this : 
https://wowwiki.fandom.com/wiki/Rip?oldid=1524033  

 If I missed something, please correct . But if i am will using this bleed with "Mangle" (Without any gear)  . This ablility deal more then 2k damage lul

**Comment by kelno** [comment]
Fixed with 13193

**Comment by Felynda** [comment]
This is a false bug report. Damage formula before was correct. Please see my bug report: https://github.com/SunstriderEmu/BugTracker/issues/1924

proper calculation is 0.24*382+1092 * 1.1 * 1.3 = 1653.
Yes with talents Naturalist (10% damage) and Mangle up (30% bleed damage increase) it will hit for over 2k naked. 1653 * 1.1 * 1.3 = ~2364
