### ISSUE TITLE
[Item] Stonebreaker's Totem

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#1710]
**Describe the bug**
Stonebreaker's Totem http://tbc.cavernoftime.com/item=33507 is proccing on almost any "spell hit". Didn't test exhaustively for every possible thing, can for sure say it procs incorrectly (aside from shocks) from: Lightning Bolt, Chain Lightning, Frostbrand procs.

https://imgur.com/a/hWNkzvt shows a 100% proc chance from Chain Lightning
_this issue is not addressing proc chance_

**To Reproduce**
1. Equip the totem
2. Cast such spells/hit with Frostbrand
3. Benefit infinite 110 AP

**Expected behavior**
Should only proc from shocks, any kind.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in rev. 13191
