### ISSUE TITLE
[Spell] Shamanistic Rage

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#1711]
**Describe the bug**
Shamanistic Rage mana gains seem not to proc from Windfury procs (tested only with Windfury Weapon).

**To Reproduce**
1. Gain Windfury buff on your weapon(s)
2. Use Shamanistic Rage
3. Not gain any mana from WF procs

**Expected behavior**
Windfury hits should be able to proc Shamanistic rage mana gains.
http://blue.cardplace.com/newcache/en/394130313.htm
_"The two extra attacks can proc flurry, unleashed rage, and shamanistic rage. They do not consume flurry charges, and don't glance."_

https://wowwiki.fandom.com/wiki/Shamanistic_Rage?oldid=1580486
_There you can see that the tests for the proc chance include windfury hits (along stormstrike and classic white hits)._

Stormstrike however procs the Shamanistic rage just fine.

**Comment by Jerrythemagicdog** [comment]
Need to re-test again as some weapon procs got wrongly affected earlier.

**Comment by Jerrythemagicdog** [comment]
Tested, works correctly.
