### ISSUE TITLE
[Paladin] Refreshing Judgement on a target should be a separate Spell

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#1713]
**Describe the bug**
Alright this one is tricky and barely ever gets correctly implemented at first (if ever). I am gonna go slow and clearly about this one.

Majority of Judgements are Magic debuffs upon judging corresponding Seal (Justice, Crusader, Wisdom, Light). These Judgements are then refreshed by every white attack and Crusader Strike (and possibly Seal of Command proc as it is also treated as another "white attack" basically - but that aside).

When the Judgement gets refreshed on a target (from melee hit), a "Spell" is implicitly casted on the target. This spell is a non-damaging spell with its only purpose being the refreshment of the Judgement. Now this has big consequences:
- **Grounding Totem** should be detroyed by this spell, while the judgement remains on the shaman (it is not transferred to the GT), only the "refreshment spell" gets redirected, immediately destroying the GT.
- **Spell Reflect** should be treated just the same. If warrior has judgement on himself, then a simple melee hit should remove the Spell Reflect.
- possible side effects of correct implementation are Mark of Vindication http://tbc.cavernoftime.com/item=27926 boost in terms of many more spell hits, Darkmoon Card: Crusade http://tbc.cavernoftime.com/item=31856 allowing to keep both melee and spell damage up all the time, Insightful Earthstorm Diamond http://tbc.cavernoftime.com/item=25901 having chance to proc on each melee hit etc. I will test these items specifically after this gets implemented correctly.

**To Reproduce**
1. Cast Magic debuff Judgement on target
2. Let target use GT/Spell Reflect
3. Melee hit/Crusader Strike the target
4. GT/Spell Reflect doesn't get consumed, judgement is refreshed on the target as if it was no "spell cast"

**Expected behavior**
Thoroughly explained above. Judgement refreshment should be treated as a spellcast (and a harmful spell to the enemy), resulting in destroying GT, removing spell reflect and boosting ret overall in terms of PVP and PVE.

**Screenshots/videos**
https://youtu.be/dbKaU_LMCCk?t=680
_This is probably the clearest example, as you can see it from there during following 20 seconds, literally in the Combat Log._
https://youtu.be/tuH6FAJGdfI?t=935
_Same Thing._

**Additional context**
Right now it seems it is treated as something else than a "spell cast". Also please make sure it doesn't work so that the GT/Reflect is removed but primary Judgement is also gone from the target -- it should remain on the target. Should work for all Magic-debuff Judgements.

**The same applies to Vindication (paladin talent) which is currently also bugged, but I am gonna make a separate simple report.**

**Comment by Rettiy** [comment]
What research do you need here?

**Comment by Ibuprofeno** [comment]
I would like to add the comments I sourced for my Mark of Vindication report (https://github.com/SunstriderEmu/BugTracker/issues/2467)
2.3.3 comment
https://www.wowhead.com/item=27927/mark-of-vindication#comments:id=229254

  > Then it hit me. Refreshing a judgement counts too. As does procing vindication. I tried it and yes it does proc off those two. Finally, a use for it. So while it doesn't proc that often at all, it's nice to have as an add on to the other mana regens out there. Hammer of Destiny, Insightful Earthstorm Diamond, etc.. I have this and both the hammer and the meta gem and I get so much mana back now I don't even have to worry about it. :) My advice? Get all three if you can. The hammer, the meta gem and this trinket. Then you will definitely be ready for raids.

**Comment by kelno** [comment]
Fixed in 15401
