### ISSUE TITLE
[Paladin] Vindication proc should be a separate Spell

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#1714]
**Describe the bug**
The following is analogical to #1713 and has the same consequences in the end.

Vindication (paladin talent) - something like this http://tbc.cavernoftime.com/spell=26021 - should also be treated as another separate spell cast (harmful spell for GT and Spell Reflect).

**To Reproduce**
1. Spec into Vindication in Ret talent tree
2. Let Shaman use GT/Warr Spell reflect
3. Make Vindication proc
4. GT/Reflect doesn't get consumed

**Expected behavior**
Explained above.

**Screenshots/videos**
for example https://www.wowhead.com/forums&topic=18459/vindication
_"Vindication may work on trash mobs in PvE instances, however the best part is even though bosses are immune to Vindication, the Vindication procs can in turn proc Judgement of Wisdom/Light, even though the boss is immune to the spell."_

can provide more if needed

**Additional context**
This is a big thing for both PVP and PVE. In PVP for obvious reasons, in PVE so that the paladins would spec 1/3 just to simply get the proc (since the actual effect on the bosses is none). This proc would then have a chance to proc Judgement of Wisdom etc. on the boss. Therefore please make sure this gets implemented correctly for all "tiers" of the talent, not only 3/3.

**Comment by Jerrythemagicdog** [comment]
It is a separate spell cast and it can proc certain things.
As to it consuming Grounding Totems isn't the video from your other issue proving that it shouldn't?
https://youtu.be/tuH6FAJGdfI?t=939

```
Time stamp at 15:39

Shaman is affected by Vindication that's half way through its duration

At 15:41 Shaman casts Grounding Totem

After that the Vindication gets refreshed on the Shaman and the Grounding Totem is not consumed
```

**Comment by Rettiy** [comment]
That's funny, you might be right, which is probably even better. 
Then I don't know what it would be to be honest, a melee attack? Because the part about proccing on judgements has to be justified somewhat.

**Comment by Ibuprofeno** [comment]
I would like to add my report for Mark of Vindication as this is the real issue.
https://github.com/SunstriderEmu/BugTracker/issues/2467

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/4014
