### ISSUE TITLE
[Warlock] Siphon life&drain life ignores resilience

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1716]
**Describe the bug**
Siphon life and drain life ignores resilience

**To Reproduce**
1. Warrior has battle stance and 0 resilience
2. Shaman has 423 resilience (10.73% reduction)
3. https://youtu.be/8slpexRV4O0
4. Demage on both is same

**Expected behavior**
As any other periodic dmg, siphon life and drain life should be reduced by resilience

https://youtu.be/5YMrsc1NJYM?t=1192

S4 warlock, siphon life ticks 184 on druid. On endless in S3 gear siphon life ticks 202.

**Comment by hufsa** [comment]
Thank you! Fixed.
