### ISSUE TITLE
[Quest] Marking the Path

### ISSUE THREAD

**Issue by Badarki** [SunstriderEmu/BugTracker#1717]
During the quest "Marking the Path" https://www.wowhead.com/quest=9391/marking-the-path in Hellfire Peninsula; When we use our Lit Torch https://www.wowhead.com/item=23480/lit-torch on one of the Beacon, mobs around aren't attacking us. Moreover I Don't know if it's linked with PTR but I'm looting a lot of Blues during my Journey in Outland, maybe 8 in 3 levels, it's not even happening with x1 xp rate so it seems strange with x5 xp rate.

**Comment by Jerrythemagicdog** [comment]
Loot tables were before launch, I don't think we're going to engage into the RP here with aggroing nearby mobs, thanks for the issue!
