### ISSUE TITLE
[Karazhan] Issue with Molten Armor

### ISSUE THREAD

**Issue by diamadov** [SunstriderEmu/BugTracker#1720]
**Describe the bug**

Can't verify as I was not the mage - there is a trash mob between Curator and Illhoof / Aran that has a counter affect (robot that shoots arcane missiles at attackers). It seemed that one of our mages had molten armor that was triggering this effect, which triggered molten armor in an infinite loop (fireball triggered counter, counter triggered molten armor, molten armor triggered counter, counter triggered molten armor, etc.) This lead to a lot of damage.

This may also be triggered by Thorns, Blessing of Sanctuary, Retribution Aura, Lightning Shield, shield spikes, item buffs with counter effects, etc.

**To Reproduce**
1. Buff Molten Armor
2. Attack robot mob with counter buff

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

Counters should not trigger counters

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

We weren't sure if this is the actual cause of this. Perhaps it was ignite ticking? It seemed the mage was getting barraged by these though.

**Comment by Jerrythemagicdog** [comment]
Thanks for the details!

**Comment by Jerrythemagicdog** [comment]
Fixed with next update.
