### ISSUE TITLE
Auto attack+ switching weapons

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1723]
Describe the bug : 
(by Klimpb)
After changing weapons, the next attack comes faster than it should 

To Reproduce : 
https://youtu.be/k5l68G-arGg

1. Target X start attack on Y (you should have swing timer for check this) 
2.  After you hit , instant change weapon 
3.  Next attack comes sooner than it should

**Comment by Jerrythemagicdog** [comment]
Swapping weapons should reset swing timer.

**Comment by kelno** [comment]
Fixed with 13223.
Timer was wrongly set to 2.0 always.
