### ISSUE TITLE
Shadowfiend - incorrect HP number 

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1724]
Describe the bug :  

Shadowfiend have much ~80% more hp then should 

To Reproduce: 
Summon shadowfiend . look at number of HP  3836 on Endles 
https://clips.twitch.tv/PunchySoftButterflyDuDudu  

Some videos from retail : 

https://youtu.be/Fv_CJDCmGO8?t=454   2368 HP 
https://youtu.be/TYawfgVBSEc?t=289 ~2300 HP 
https://youtu.be/QyTyNaiEJKs?t=298

**Comment by Jerrythemagicdog** [comment]
Related: https://github.com/SunstriderEmu/BugTracker/issues/180

**Comment by z5n** [comment]
issue has since been fixed
