### ISSUE TITLE
Impale [Warrior tailent]

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1725]
Describe the bug : 
Warrior Tailent Impale (20% Critical damage bonus ) not affected warrior ability  Overpower (maybe something else)

To Reproduce : 
Differences with auto attacks should be 20 % more dmg , also Overpower have 35 more based damage . 
White hit damage : 
did ~200 hits 
https://imgur.com/4lEwXKR  
Crit numbers was  : 1051-1204-1395 max . 

Also did 30 Overpowers : should be   ((35*2)  based damage cos crit  + 20% bonus from impale ) 
https://imgur.com/fPfJFit

Crit number was : 1176-1322-1441 max .  

If its possible make automaticaly test , its will be great . If i am wrong , just cancel it .

**Comment by blblblaz** [comment]
https://imgur.com/HWR3kf9 - no impale

https://imgur.com/mohYGVg - with impale

Warrior's target in the screenshots is a target with 0 armor, 0 resi

As far as I understand the way it works - Warrior default crit damage is 100%, Impale simply adds another 20% to that. In the "with impale" screenshot you can see for example - Min hit is 901, 901 * 1.2 = 1081.2; 1081+901=1982, Min crit in the screenshot=1982
