### ISSUE TITLE
[Spell] Shamanistic Rage (again)

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#1727]
**Describe the bug**
As it is already described in #1711 the Shamanistic Rage doesn't give mana through Windfury attacks and the conclusion in the previous post is in my opinion false.

It has been clarified by Jerry that Shamanistic Rage on this server is working with 35 % stable proc chance, which is true.

**To Reproduce**
1. Enhance weapons with WF
2. Use Shamanistic Rage
3. Do not gain any mana from WF procs while the buff active

**Expected behavior**
Successful Windfury attacks should be along successful White auto attacks and Stormstrike also possible sources of Shamanistic Rage procs.

**Screenshots/videos**
I did some testing this morning, after the Server restart that occured like 1-2 hrs ago from this post. For this purpose I created fresh Shaman character where I went for max melee hit, intellect and weapon speed to get as many hits in during the Sham Rage. **No attack power modifiers (such as Unleashed Rage or trinket/ring procs) were included** in order to have a stable Attack power and therefore the same 30 % mana gains.

In total I did **10 "attack periods" with Shamanistic Rage** up where I beforehand always exhausted my mana and then for the 15 seconds long duration of Sham rage I would attack the Dummy including Stormstrike. I've also made sure no hits were dealt without Sham rage active.

All relevant screenshots are here https://imgur.com/a/OJ0o8Zu and I'll be referring to them as "SS1", "SS2" etc. for the results I've got.

The character pane showing stats is in SS1, important stats are:
- 1086 Attack Power which is unchanged for the whole time, resulting in 1086*0,3 = **325 Mana** Gain through Shamanistic Rage hits.

SS2 to SS5 show results after 10 Shamanistic Rage periods full of hits on the dummy. From these we can conclude the following:
- [SS5] Total mana gained back is 28275, that is 28275/325 = **87 procs of Shamanistic Rage in total**
- [SS2] Number of successful White auto attack hits was 105+59+49 = **213 successful AA** (not including any misses, dodges, parries because these have no chance to proc Shamanistic Rage)
- [SS3] Number of successful Windfury attacks was 64+12 = **76 successful WF** (same rules as above)
- [SS4] Number of successful Stormstrike attacks was 26+8 = **34 succesful SS** (same rules as above)

Now let's divide the Number of Sham Rage procs - that is 87 - by both:
- total number of attacks (AA+WF+SS) - that is 323 (213+76+34)
- number of attacks excluding WF (AA+SS) - that is 247 (213+34)

**For the first one, the results are 87/323 = 26,93 % total proc chance, which is much less than 35 %
For the second one, the results are 87/247 = 35,22 % total proc chance, which is acceptable deviation from the average desired 35 %.**

**I think this test clearly shows that Shamanistic Rage currently does not proc on Windfury Attacks, even though it should. Evidence for that it indeed should once again in #1711** 

**Additional context**
Another evidence for this not working currently is that the Combat Log never shows Shamanistic Rage procs after the WF, only after Autoattack and Stormstrike. You also never ever get 3 or 4 Sham Rage procs at once from dual wield hits + WF, which should be possible. Example is in SS6.

_Even though this is not the aim of this post, Windfury Weapon crit chance seems much lower than average, but this might be due to low number of procs. Still, where Autoattacks and Stormstrike were at 21 % crit chance (the character had 23 % from SS1), WF was only at 14 % crit chance. Leaving it here for anyone who would want to test it further._

**Comment by blblblaz** [comment]
I can't reproduce locally or on the PTR, in my tests Windfury attacks procced Shamanistic rage no problem, need reproduce steps if possible
![cOMBATLOG](https://user-images.githubusercontent.com/53877162/72671302-ce3b2a00-3a50-11ea-86dd-5d9dc11955dc.png)

**Comment by Rettiy** [comment]
Aren't you using Windfury from Windfury totem? Because this wording corresponds to it but it's obviously nonsense for Shaman. Otherwise I have no idea, but I think the big difference is that here it is even worded as "melee swing" because that's how Windfury totem is treated, while in my post it's "Windfury Attack". What I mean is Windfury Weapon.

**Comment by Jerrythemagicdog** [comment]
Some data:
Spell IDs  (rank 5)
The spell triggered from the temp enchant id from the shaman spell (2636)
Windfury Weapon (Passive) - 33727

The spell triggered from the temp enchant id from the totem (2639) 
Windfury Attack - 25584

**Comment by Rettiy** [comment]
Hello

**Comment by Rettiy** [comment]
Bump, especially relevant after all enh "nerfs".

**Comment by Jerrythemagicdog** [comment]
Works in my tests:
![image](https://user-images.githubusercontent.com/46463908/93654359-f7afb980-fa14-11ea-83a1-9857254382f9.png)

**Comment by Rettiy** [comment]
Well I wanted to let this go since you are disabling 2s again on the tournament realm but there is just something that doesn't convince me it works like this.

I did some basic tests this morning again https://imgur.com/a/CP1R6Sm and I just can't get a clear answer so that it really procs off WF attacks. Especially if you consider how many times it procced on these screens off normal attacks or SS, you would maybe see one proc off WF.

Moreover, after almost every arena I try to do Sham Rage with 2H on dummies to see atleast ONE double proc of Sham rage on hit + wf (whether its SS + WF or autoattack + WF) and I just can't see more than one proc - I did this many times so it's not just bad rng.

It might have to do something with how you isolate WF in your test and when it procs off autoattack or SS it works differently, but honestly I don't know at this point. But I am almost certain it just doesn't proc, the 2hander convinces me even more.

There is also another thing, if you use stormstrike with 2Hander (no WF), you still get sometimes 2 procs of Sham Rage even tho only one hit really occured - probably has to do something with how is SS treated with dual wield.

**Comment by Jerrythemagicdog** [comment]
If those labeled with orange were from the Stormstrike they would appear in between the Stormstrike and the next Windfury procs not that way.
The reason why you get double procs with a 2hander is probably because you also white swing?
