### ISSUE TITLE
Threat Tables

### ISSUE THREAD

**Issue by Dalrash** [SunstriderEmu/BugTracker#1729]
Is there something wrong withthe threat tables, i was in Ramps normal today with my gf as Feral Tank to test some things out. And a fully lacerated mob broke loose and ran towards me after one flash light, where a mob that was untoched by the tank stayed glued on her.

Yesterday i tanked Ramps HC and Shield Slam barely generated any rage, so the threat tables seem of to me.

Can you look in to this ?

Kind Regards,

**Comment by Jerrythemagicdog** [comment]
Sorry, but we can't do anything here without a clip or more context. Threat values are consistent with Omen libraries.
