### ISSUE TITLE
[Quest] "Thunderbrew Lager" can't be picked up.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#173]
**Description:**

'Thunderbrew Lager' (117) is one of "pick up and hand in with one click style" quests that's repeatable.
Right now it can't be picked up with required items present (Hops - 1274). 

**Expected behaviour:**

Quest should be pickable once the quest items are present.

**Steps to reproduce the problem:**

1. Go to NPC entry: 239
2. Try picking up the quest
3. Can't press continue to complete the quest.

**rev. hash/commit:** 

Sunstrider rev. 10253 (3cfd54b) 2019-01-18 18:02:17 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
Seems fixed
