### ISSUE TITLE
[enhancement] leveling weapon skill too slow, adjust for increased XP rates 

### ISSUE THREAD

**Issue by totaemoeggerli** [SunstriderEmu/BugTracker#1731]
**Current behavior**
Leveling weapon skill is extremely slow. It is possible to keep up with the current weapon skill but switching to another weapon requires considerable amount of time to catch up. Melee is already at a huge disadvantage compared to classes that don't depend as much on gear. 
Two-handed weapon progression during leveling is notoriously bad and requires switching to a lot of different weapon types. It is especially bad for shamans and paladins that don't have access to spamable abilities such as Wingclip or Hamstring.

**Expected behavior**
The chance to get a weapon skill-up should be increased by at least the same amount as the XP rate. Alternatively weapon skills could be granted on level up without causing significant balancing issues. Disable the feature after level 60 to create some blizzlike-ness.   

**Screenshots/videos**
https://gfycat.com/sorrowfulimpressionablefrogmouth-worldofwarcraft

**Comment by NeonicSupersonic** [comment]
Paladins have seal of crusader which is free 40% as, i am all for 5x weapon skills tho.

**Comment by kelno** [comment]
I'm curious about: Did you test with the current weapon skill formula we have? Are is this projecting with what happened on other servers

**Comment by totaemoeggerli** [comment]
The clip is from the sunstrider server, taken moments before posting here.

**Comment by kelno** [comment]
Okay thanks

**Comment by totaemoeggerli** [comment]
thanks for addressing the issue quickly. while I don't think it would hurt to increase it even more, but this will definitely make melee leveling a bit more enjoyable.

**Comment by Jerrythemagicdog** [comment]
I've seen people discussing it on Discord and saying they can keep up their weapon skills with their level. Seems to be the desired state?

**Comment by networm555** [comment]
x5 or x 10 ofc. this mechanic became obsolete with rate changes, it just dont have any sense to leave it even x2. Imagine mage aoeing 7 gnoll camp and paladin struggling to hit a gnoll with his 5 mace skill (blessed rng greed drop to use).

**Comment by maingaming** [comment]
> x5 or x 10 ofc. this mechanic became obsolete with rate changes, it just dont have any sense to leave it even x2. Imagine mage aoeing 7 gnoll camp and paladin struggling to hit a gnoll with his 5 mace skill (blessed rng green drop to use).

This. Weapon Skill served a point in Vanilla/TBC when it was about the long journey to the top but this is a 5x TBC server focused on endgame. Don't let people suffer through this complete waste of time and outdated mechanic. You've already made thoughtful non-blizzlike changes so I don't see any issues here.

**Comment by artieau** [comment]
Just tested leveling a weapon from 1 skill and its very fast now with just the 2x it seems.

**Comment by totaemoeggerli** [comment]
I leveled a character to 30 today. Spend 10 minutes to get 2h sword skill to 100/150. As it is right now, I'd rather buy a white weapon from the vendor instead of doing quest for a green one and having to level weapon skill. Please increase to 5x to match XP rates.

**Comment by kelno** [comment]
Upped to x3 for now

**Comment by totaemoeggerli** [comment]
a bit less then 15 min to get from 1 to 250 in "real" world environment with 3x
