### ISSUE TITLE
Arcane missiles & Arcane Focus

### ISSUE THREAD

**Issue by justheal** [SunstriderEmu/BugTracker#1733]
**Describe the bug**
Arcane missiles don't get spell hit bonus from Arcane Focus talent (10% spell hit)

**To Reproduce**
1. U know...

**Screenshots/videos**
there is two fights with 10,5% hit from items (boss dummy)

![WoWScrnShot_012020_232854](https://user-images.githubusercontent.com/53220855/72756860-a1694d00-3bdf-11ea-803c-6066a07f2d4d.jpg)
![WoWScrnShot_012020_223932](https://user-images.githubusercontent.com/53220855/72757122-310efb80-3be0-11ea-885a-dc71f8b9b0df.jpg)

**Additional context**
There is no same problem with Arcane blast/explosion so it's Arcane Missiles bugged, not Arcane Focus talent

**Comment by kelno** [comment]
Thanks!
Fixed with 13224
