### ISSUE TITLE
Insightful Earthstorm Diamond chance to double proc

### ISSUE THREAD

**Issue by Birkirr** [SunstriderEmu/BugTracker#1734]
**Describe the bug**
The meta gem Insightful Earthstorm Diamond (+12 intellect & chance to restore mana on spellcast) appears to have a chance to proc twice on the same spellcast; specifically, priest's mass dispel ability over a large number of players and NPC's. 

**To Reproduce**
1. Spam max rank Mass Dispel with said meta gem equipped and activated by required gems over large groups of people and NPC's in the beta camp in Winterspring. 

**Expected behavior**
Should only be able to proc once per cast.

**Comment by networm555** [comment]
It tripple proced for me today as priest while casting mass dispell on crowd. spell cost around 750 and 950 gained from meta :dancer:

**Comment by Birkirr** [comment]
> 
> 
> It tripple proced for me today as priest while casting mass dispell on crowd. spell cost around 750 and 950 gained from meta 💃

Yup, I have also seen a handful of triple procs.

**Comment by Jerrythemagicdog** [comment]
Fixed with next restart.
