### ISSUE TITLE
Imp quest for Orc starting area doesn't work

### ISSUE THREAD

**Issue by Arahnian** [SunstriderEmu/BugTracker#1735]
**The Problem**
The quest "Vile Familiars" in the orc starting area requires you to get 6 quest items from the Vile Familiars in that area to receive the "Summon Imp" spell. Even after killing more than 60 of them on 2 different characters I didn't get a single quest item to drop. I've tested the respective quests for Humans and Undead and those quests work as intended.

https://db.endless.gg/?quest=1485

Above is the link to the quest in question. I know it states that the quest is obsolete, but the same is stated for the undead/humans quest which do work properly.  

https://db.endless.gg/?quest=1470 -- The Undead equivalent.
https://db.endless.gg/?quest=1598 -- The Human equivalent.

The Vile Familiars Head also doesn't appear in the loot list like the Rattlecage Skull (Undead) does.
https://db.endless.gg/?npc=1890#drops -- Shows the quest item.
https://db.endless.gg/?npc=3101#drops -- Doesn't show the quest item.

**Comment by Jerrythemagicdog** [comment]
Thank you, fixed in rev. 13229
