### ISSUE TITLE
Poison Cleansing Totem

### ISSUE THREAD

**Issue by Cromas92** [SunstriderEmu/BugTracker#1736]
**Describe the bug**
Poison Cleansing Totem does not work at all.

**To Reproduce**
1. Cast X on target affected by ...
2. 
3. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Tested now, works on the PTR, can't work without more details.

**Comment by networm555** [comment]
worked for me in shaman rogue duels this week.
