### ISSUE TITLE
[Druid]Swiftmend - reduce healing effect  applied twice 

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1738]
Spell: http://tbc.cavernoftime.com/spell=18562

Describe the bug: 
(by Pacina)

Reduce healing effects like :Wounds poisons , Mortal Strike , Aimed shoot etc reduce healing from Swiftmend twice 

To Reproduce teps to reproduce the behavior: 
Cast Swiftmend with/without   for example  (Wound poisons ). Look at healing taken

**Comment by Jerrythemagicdog** [comment]
A response to his ticket in-game:
"Currently what I'm guessing happens is - Swiftmend is healing based on the amount that your Rejuvenation heals. So when there is a Mortal Strike effect, it calculates the amount healed by Rejuvenation under MS, so the healing gets reduced by that once, and then when you Swiftmend the heal also gets reduced by Mortal Strike."
Need more info

**Comment by kelno** [comment]
Dev:
In core, look for occurrences of AURA_STATE_SWIFTMEND

**Comment by sposobniy** [comment]
https://youtu.be/vpEa508cxGE?t=1011 
Heal from Swiftmend 2304 (with 3 Wound poisons debuff)
Moment on video : 18:17  [Rejuvenation]  without mortal tick 823 => full duration he will heal 3292 

3292x0.7

**Comment by blblblaz** [comment]
confirmed, https://youtu.be/vpEa508cxGE?t=937 - 2411 crit with Mortal Strike up

**Comment by kelno** [comment]
Fixed in 13276
