### ISSUE TITLE
Freezing trap -works instantly if set on target without a combat 

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1739]
Describe the bug: 

Works instantly if set on target without a combat 

To Reproduce : 
Drop trap on target without combat 

How it should work : 
https://wowwiki.fandom.com/wiki/Freezing_Trap
Always should have 2 sec arming time . 
https://www.warcraftmovies.com/movieview.php?id=122825 its Wotlk , but this not was changes after tbc

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/188

**Comment by sposobniy** [comment]
yes , i mean he dont have arming time against target without combat . Its some vanilla remains

**Comment by Jerrythemagicdog** [comment]
Maybe, seems correct though.

**Comment by sposobniy** [comment]
My bad i not  check oldid

**Comment by hotdogsteven** [comment]
> Maybe, seems correct though.

Was this changed in classic TBC?
https://youtu.be/RrYnEah1MTQ?t=142

https://youtu.be/RrYnEah1MTQ?t=175

(Watch Gladdy Rogue Frame)
https://youtu.be/RrYnEah1MTQ?t=215
