### ISSUE TITLE
Blessing of protection while CCed 

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1740]
Describe the bug : 
You can bop your teammates while you CCed 

How reproduce : 
https://clips.twitch.tv/SmellyPatientPuffinBleedPurple  
https://clips.twitch.tv/LitigiousKawaiiCougarDeIlluminati 

How it should work : 
You can use bop only for  youself for remove CC  

Some info : https://github.com/ccshiro/cc-buglist/issues/1114

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by Jerrythemagicdog** [comment]
Fixed after next restart.
