### ISSUE TITLE
You get stuck if you received СС  in moment Charge/Intercept 

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1741]
Describe the bug: 
If in moment charge you get proc (frostbite , entrapment root ) or just CC . You charge cooldown triggering but you stuck in same place . 

To Reproduce:

https://clips.twitch.tv/CooperativeEncouragingShieldPlanking   Entangling Roots

https://clips.twitch.tv/BenevolentPricklyCaribouBleedPurple Entrapment proc 

How it should work : 
You should always be at the end point. 

https://youtu.be/vpEa508cxGE?t=995

**Comment by Jerrythemagicdog** [comment]
This was changed yesterday: https://github.com/SunstriderEmu/BugTracker/issues/1344
clips are older than 5 days.

**Comment by sposobniy** [comment]
I have not played for several days, .  Maybe some new fixes have already been applied , but I looked at the last changelog .                                  
Just found time to describe bugs  that were noticed earlier . Sorry  if i paste same similar =/

**Comment by Jerrythemagicdog** [comment]
Okay, thanks.
