### ISSUE TITLE
[Spell] Blessing of Light

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#1742]
**Describe the bug**
Blessing of Light gives flat heal increase while ignoring the rank of the healing spells. Rank 1 Holy light gains 580 extra heal from the BoL, analogically for Flash of Light.

Possibly huge abuse potential in both PVP and PVE.

**To Reproduce**
1. Cast Blessing of Light
2. Cast lower ranks of Holy Light/Flash of Light
3. Notice full benefit of these

**Expected behavior**
There should be some (huge) reduce based on what rank of the spell is used, I don't know how much exactly but it should certainly not work like this.

**Screenshots/videos**
Current rank 1 heals of Holy Light and Flash of Light with full rank BoL buffed.
https://imgur.com/a/BSqdFMI

**Additional context**
Would be fair to look into other ranks of BoL as well (only tested for max rank and not for Greater BoL).

**Comment by kelno** [comment]
Added some downranking penalty, effective with next update
