### ISSUE TITLE
[Warrior] Spell Reflect and talent procs

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#1745]
**Describe the bug**
Reflected Frostbolt clearly has a chance to also proc Frostbite. To me this does not make sense since for years Mages would sometimes use Counterspell on warriors to just get the reflect off. The mage then would **not get** the 4 second silence from the reflected Counterspell, even though he is specced to it. If this improved CS talent is not applied to the reflect, why would frostbite -- also talent -- be an exception? 

This is probably wider question on how other similar things should be treated, such as how long duration should the reflected frostbolt have -- should the slow from the reflected frostbolt be longer due to mage's talent or not? Feel free to label it with "needs more research", but right now the application does not seem consistent and maybe people will find out more reflected spells that carry their specific class benefits even post-reflect.

**To Reproduce**
1. Create Mage, spec into Frostbite, cast Frostbolt into warrior
2. Use Spell reflect to reflect Frostbolt
3. Notice Frostbite sometimes applies from the reflected Frostbolt on the mage

**Expected behavior**
In my opinion the Spell Reflect should not take into consideration any specific talents the caster had. However I am not 100 % sure on this.

**Screenshots/videos**
Clip from Endless with reflected Frostbite
https://clips.twitch.tv/SparklingEnjoyableSheepUWot

**Comment by Jerrythemagicdog** [comment]
Duplicate: https://github.com/SunstriderEmu/BugTracker/issues/1639

**Comment by kelno** [comment]
Thanks though!
