### ISSUE TITLE
[Shaman] [Talent] Nature's Guardian proc chance too low

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#1746]
**Describe the bug**
The Proc Chance of Nature's Guardian is simply too low, causing resto shamans to play like cowards because they can't rely on this talent. IDs for each rank:
- rank 1 http://tbc.cavernoftime.com/spell=30881
- rank 2 http://tbc.cavernoftime.com/spell=30883
- rank 3 http://tbc.cavernoftime.com/spell=30884
- rank 4 http://tbc.cavernoftime.com/spell=30885
- rank 5 http://tbc.cavernoftime.com/spell=30886

This was dicussed a little in #1332 but the conclusion was that the internal Cooldown was too high. The issue in this case is different, as in my opinion the internal Cooldown is now working properly, while proc chance long-term is very much under the correct percentage. The biggest issue is that there are abnormally huge spikes between the procs, when sometimes it takes 7-10+ hits to get the proc. Of course this is an issue by nature of the talent, but the spikes should just not happen in such extent and that often. Everything is thoroughly explained in the following paragraphs.

This has huge impact on PVP as it's now an unreliable source of heal and stability for shaman and resto shaman therefore does feel different due to this. I also discussed this with other people and they mostly share the same opinion -- Nature's Guardian failing you way too often.

Right now I am not able specify what exactly is wrong, but the proc chance and the spikes are just not right. The talent should be able to proc from literally anything that damages you and puts you/leaves you under 30 % hp (dots, bleeds, classic hits) -- this is working fine too imo, although I can't specify whether the total percentage is incorrectly affected by procs already under 30 % or procs that bring the shaman from > 30 % to less than 30 % health. My guess is both.

**To Reproduce**
1. Create Shaman and spec X/5 points into the talent
2. Do Y hits that either bring the shaman under 30 % or leave the shaman under 30 %
3. Make sure the test is not influenced by internal CD
4. Notice incorrect amount of procs out of the total hits taken - with respect to current rank of the talent

**Expected behavior**
Long-term, the Nature's Guardian proc chance should be at the % that the talent states, that means 10/20/30/40/50 % for corresponding ranks 1-5.

**Screenshots/videos**
For this purpose I've carried out a test, that included two Shamans, one who would do damage with Lightning Bolts and other with Nature's Guardian to track the number of procs, detailed info:
- Nature's Guardian at 5/5, that is 50 % proc chance
- Every single Lightning Bolt either took the shaman under 30 % from >30 % (most of the full ranks) or left the shaman under 30 % (speaking before application of Nature's Guardian)
- After every Nature's Guardian proc, there was a period of 6+ seconds that made sure the internal cooldown is ready -- this was monitored by "leaving combat" on the damaging shaman
- Lightning Bolt was used as full rank and rank 1, both should obviously proc the talent. Thanks to rank 1 Bolts, no other healing was neccessary and all healing done is just Nature's Guardian

The linked screenshots are documenting the results of the test, I'll be referring to them as "SS1" to "SS8" https://imgur.com/a/KOb5buh

SS1 shows the shaman has 5/5 Nature's Guardian, 50% chance. The results were:
- out of 200 Lightning Bolt hits (SS2, ignoring resists because those would not proc Nature's Guardian) that hit the healing shaman in the way that Nature's Guardian should have a chance to proc, only 52 of them actually made Nature's Guardian proc (SS3)
- logically, if every single one of the bolts taken had a chance to proc the Nature's Guardian -- because the internal CD was always waited for -- the ideal outcome would be 100 Nature's Guardian procs, 50 % out of the 200 hits
- the result is that instead of 50 % proc chance, it's just a miserable 26 % (52/200)

I already tested this few times before with 100 Lightning Bolts and exactly same circumstances and I've come to 29 % and 31,2 %, which both are still heavily under 50 %. Also this feels even worse when playing with 4/5 or 3/5 Nature's Guardian.

**What in my opinion is causing these weird numbers are the unusually long intervals before the Nature's Guardian sometimes finally procs, documented on SS4 to SS8. There were moments where Nature's Guardian didn't proc from 10 hits (SS4, SS5 and SS6) or even 12 hits (SS8). This simply should not happen during "only" 200 Lightning Bolt hits, as these odds are just ridiculous.**

**Additional context**
I am willing to help in any way to get this right, because it's such a vital component of Resto Shaman it would certainly bury it even more for PVP.

Please don't just state it works correctly if you somehow get satisfactory results from tests, because the practice has shown it's not ideal.

P.S. I will do another test with same basic idea and record it if neccessary.

**Comment by Jerrythemagicdog** [comment]
Thanks for the numbers here, will have a look at Nature's Guardian in general soon and how it's supposed to behave, the hp check for us is currently still happening when under 30% and the tooltip indicates something else.

**Comment by kelno** [comment]
Super like on the way the test was conducted

**Comment by kelno** [comment]
I see that the proc chance is actually handled in two places... leading to 50%*50%, which exactly fits the data found in the provided test here!
That part is now fixed.
Now when I read this spell tooltip, I understand the following: The spell should only proc if the hit brought us under 30%. Subsequent hits when already under 30% shouldn't proc.

WoWWiki seems to contradict this saying: "Against a fast-attacking opponent like a rogue, it is effectively guaranteed to trigger any time you are below 30% health." which would be consistent with the current rule (can proc even if already under 30%).
So I guess it's probably already correct but I'd like to be sure about it.

**Comment by Rettiy** [comment]
Yeah anything that damages you and basically leaves you under 30 % (before the Nature's Guardian proc) is a source of a possible heal. That means whether or not you cross the 30 % line with that attack.

Also please make sure it's not 40%*40% etc. for the lower ranks, because this talent is usually downranked in pvp.

**Comment by kelno** [comment]
Alright then, we're good!
Lower ranks are also affected by the last change.
