### ISSUE TITLE
[Hunter][Pet] Pet disappears after sent to attack a target and cannot be called back even after a relog.

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1747]
~~https://streamable.com/vjg25~~

~~The clip does not contain the bit where the pet disappears, but it was a freshly tamed lvl 10 ravager specimen that after being sent to attack a nightsaber had appeared to phase out and disappear.~~ ~~This clip was recorded after a relog and shows that using "Call Pet" ability does not return the lost pet back to me.~~

~~This occurred at 49,29 Azuremyst Isle. Seems to be a pretty rare occurrence as I have not had this happen after many hours of hunter testing so far.~~

~~EDIT: The issue persists through character death, however I am able to tame another pet that fixes the problem, but the previous pet is lost to the shadow realm.~~

**Comment by kelno** [comment]
Could he have fled because of unhappiness?

**Comment by hufsa** [comment]
https://wowwiki.fandom.com/wiki/Loyalty

**Comment by Varanak** [comment]
It appears that was likely the case. I'll test more in a bit.

**Comment by kelno** [comment]
Thanks!
