### ISSUE TITLE
Hunter/Warlock pets are parrying melee attacks

### ISSUE THREAD

**Issue by teaNcrumpets** [SunstriderEmu/BugTracker#1748]
**Describe the bug**
Warlock and Hunter pets have the ability to parry melee attacks

**To Reproduce**
1. have rogue with worn dagger auto attack hunter/warlock pet in duel

**Expected behavior**
dont have proof that they are not meant to be able to parry but was told by Artie to post it here for investigation as it does sound wrong (you parry with a weapon, bear tanks and beasts in world do not parry)

**Screenshots/videos**

https://cdn.discordapp.com/attachments/475006977936850955/670222534557302814/unknown.png  -- warlock pet

https://cdn.discordapp.com/attachments/475006977936850955/670229179224031253/unknown.png -- hunter pet

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by kelno** [comment]
I don't know for pets but most creatures in the world can parry and that's blizzlike. If this is a bug pets would be an exception

**Comment by Aeded** [comment]
not a bug

**Comment by Jerrythemagicdog** [comment]
Thanks for the source @Aeded !
