### ISSUE TITLE
[Mechanic/Spell] Auto-cast pet spells

### ISSUE THREAD

**Issue by SuddenDeath** [SunstriderEmu/BugTracker#1749]
**Describe the bug**
Pet spells with "auto-cast" toggled aren't being used unless melee range

**To Reproduce**
https://streamable.com/owly5

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
In this case pet should use devour instantly when being able to within spell range

**Comment by Jerrythemagicdog** [comment]
Related: https://github.com/SunstriderEmu/BugTracker/issues/1548

**Comment by kelno** [comment]
Fixed with next server update
