### ISSUE TITLE
[Heroic] Mana-Tombs bugs 

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1752]
Bugs that my group had observed and that I had the pleasure to write down.

- [x] Sorcerers before Pandemonium were hitting through walls

- [x] This was a general issue and a question that the group couldn't agree on: gems aren't dropping off of bosses all the time(?), requires more research

- [x] Packs are not chaining correctly in the room after Pandemonium

- [x] Darkcaster's mana burn seems to be burning way too much mana, either being cast too often or the ability itself is burning too much, the healer was drained instantly after several seconds

- [x] Tavarok is missing arcing smash(?) and crystal prison(?) abilities and the fight in general felt way too easy(?)

- [x] Mana leeches felt very undertuned(?)

- [x] Nexus Terrors felt undertuned(?)

- [x] Packs before Nexus Prince Shaffar were not chain pulling correctly

**Comment by Jerrythemagicdog** [comment]
Thanks!
No tuning is live on the PTR but we'll add those to the list to double check.

**Comment by Jerrythemagicdog** [comment]
Gems shouldn't be dropping all the time but have a chance to drop.

**Comment by Jerrythemagicdog** [comment]
Would need some clarification on
> Sorcerers before Pandemonium were hitting through walls

If you mean Arcane Missiles after they are already channeling then that is correct.

> Tavarok is missing arcing smash(?) and crystal prison(?) abilities and the fight in general felt way too easy(?)

Tavarok has his abilities, but I suspect he has died pretty quickly with the current gear offered on the PTR.

**Comment by Jerrythemagicdog** [comment]
All the missing linking has been corrected, thanks!
