### ISSUE TITLE
On spell cast item procs

### ISSUE THREAD

**Issue by Dep-243** [SunstriderEmu/BugTracker#1757]
**Describe the bug**
Items with on spell cast proc effect get activated by skills/items which are not supposed to activate the effect.

**To Reproduce**
1. Equip Band of the Eternal Restorer (item: 29309)
2. Use Star's Tears (item: 32453) repeatedly
3. The effect from the ring will proc

The tooltip of [Band of the Eternal Restorer](https://tbc-twinhead.twinstar.cz/?item=29309) reads: _Your healing and damage spells have a chance to..._
But it also procs from things such as, drinking water, casting buffs and casting dispel.

[Memento of Tyrande](https://tbc-twinhead.twinstar.cz/?item=32496) also procs from drinking.

[Spellsurge](https://tbc-twinhead.twinstar.cz/?spell=46539) also procs from drinking.

**Expected behavior**
N/A

**Screenshots/videos**
https://imgur.com/a/Ipmmk0y

**Comment by Rettiy** [comment]
I think this is the same case as the Mana restore Meta etc. and therefore probably isn't a bug:

https://www.wowhead.com/item=29309/band-of-the-eternal-restorer#comments
_"I have had this proc off Cleanse (Paladin cure spell) as well. Funny story."_
_"It seems to proc on basicly everything, buffing, shielding, pom jumping. And on top of that the proc rate just seems immensly high (never seen anything proc this much). It's thé best ring to get for healers in my opinion."_

Tooltip is not always reliable sadly, however weird it may look in reality.

**Comment by Aeded** [comment]
> But it also procs from things such as, drinking water, casting buffs and casting dispel.
Not a bug, while on proc spells have some exceptions where they should not be able to proc you definetly cannot generalize it like that. It is definetly supposed to proc from buffing/dispeling/drinking water.

Common exceptions for on proc items/spells are for example shaman water shield and paladin auras.

**Comment by Jerrythemagicdog** [comment]
What @Rettiy and @Aeded are saying is correct, what's worth noting is that actions such as drinking are considered casting a spell. Thanks for the report though!
