### ISSUE TITLE
Relentless Earthstorm Diamond doesnt work

### ISSUE THREAD

**Issue by kamil-lada** [SunstriderEmu/BugTracker#1760]
I have hunter, 380 agi, 1128 ap
Steady Shot normal for 317 dmg
Steady Shot crit for 729
317 x 2,3 = 729
If meta gem works crit should be about 738 dmg (317 x 2,33), but bonus i have is only from talents (+30% crit dmg)

![2020-01-25 23_02_34-World of Warcraft](https://user-images.githubusercontent.com/56025389/73127826-9723c600-3fc6-11ea-8641-37da0109ed08.png)

**Comment by kamil-lada** [comment]
Tested with [Fine Light Crossbow ](https://classic.wowhead.com/item=15808/fine-light-crossbow) for consistent results

**Comment by Jerrythemagicdog** [comment]
To dev:
Item id: 32409
Spell id: 39957
has "SPELL_AURA_MOD_CRIT_DAMAGE_BONUS_MELEE"

Seems to be changed at some point on retail as well to affect ranged attacks:
https://www.wowhead.com/item=32409/relentless-earthstorm-diamond#comments:id=90904

**Comment by hufsa** [comment]
Patch 2.1.2: Relentless Earthstorm Diamond: The bonus damage to critical strikes from this metagem now applies to all types of damage, not just physical.

**Comment by kelno** [comment]
Spells with this effect were not working for ranged as they should, fixed with 13267!
