### ISSUE TITLE
[Shadow Lab] pathfinding concerns with 2 different named caster humanoids

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#1761]
**Describe the bug**
had 1 playthrough of shadow labs and noticed 2 oddities
- in the pillar room with 4 caster mobs around each pillar and the terrorguard patrols; the final 2 pillars we experienced buggy pathfinding on the caster humanoids when attempting to pull them back towards the middle of the room by being out of range.

- in the final room where the summoners/destroyers/and 3rd type of of humanoids are casting at murmur; the brain channeler humanoids also experience a sort of lag or delay in pathfinding if you try to run out of range (especially when they are already casting arcane missiles, and you run out of line of sight behind concrete walls)

I cannot yet return to SL for gathering more pertinent information at this time

**To Reproduce**
1. Cast X on target affected by ...
2. 
3. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks! Would love more details or a video here.

**Comment by artieau** [comment]
Fixed since
