### ISSUE TITLE
Not able to use PvP trinket if you get feared while mind controlling an enemy

### ISSUE THREAD

**Issue by leekzy** [SunstriderEmu/BugTracker#1763]
**Describe the bug**
Not able to use PvP trinket if you get feared while mind controlling an enemy, scenario:
I (Priest) Mind Control enemy rogue in arena, enemy priest fears me during my cast and I cannot press trinket to get rid of it (I can however trinket after the fear is over) 

**To Reproduce**
1. Cast Mind Control on one enemy
2. Second enemy uses psychic scream on you
3. Test

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
Being able to trinket CC

**Screenshots/videos**
N/A
**Additional context**
N/A

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago.
