### ISSUE TITLE
SmartAI - Follow target

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1764]
**Describe the bug**
Title - When a creature following a target (for example during Alliance quest Mist (.go crea 49625)) fights a creature during the follow movement it doesn't start its follow movement until the creature corpse despawns.

Similar problem occurs when interacting with a creature that has a gossip menu. The creature stands in place forever and never restarts its follow movement.

**Comment by kelno** [comment]
Fixed with next update
