### ISSUE TITLE
Boat from Azuremyst Isle to Auberdine is currently unusable, the npcs and boat are desynced and character gets stuck after loading into Auberdine

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1766]
https://streamable.com/oixs6

Skip to 1:00 as the first minute is just npcs floating in the air until the boat arrives.

The beginning of the video shows the npcs floating in the air before the desynced boat arrives, but after the boat arrives things get interesting after the boat loads into Auberdine. You will see that the character is immediately frozen and requires logout to do anything. Logging back in again shows the character still stuck, but as the desynced boat moves while logged out it appears to be pulling into Auberdine but then I enter another loading screen back into Azuremyst Isle, where I get disconnected from the server. The video is kind of long but speaks for itself.

What didn't get clipped before I started recording this video was the boat arrived at Azuremyst Isle, but since it is desynced I jumped through the boat into the water(instead of landing on the boat like in the clip) and the boat was long gone before I swam back to the dock again and is where I immediately started recording the clip above.

Related #445 

Let me know if you want this issue closed and instead have this posted in #445

**Comment by Jerrythemagicdog** [comment]
Thanks, going to move it there!
