### ISSUE TITLE
Hunter - Steady Shot - dmg formula broken

### ISSUE THREAD

**Issue by kamil-lada** [SunstriderEmu/BugTracker#1767]
My stats:
RAP: 1128
ArmorPene: 0
BowSpeed: 2.7
BowDmg: 29 ([Fine Light Crossbow](https://classic.wowhead.com/item=15808/fine-light-crossbow))
Target Dummy 7700 armor = 42.17% dmg reduction ([calc](http://rehfeld.us/wow/armor-penetration.html))

Proper formula with speed normalization to 2.8 only for Steady Shot:
(150 + 0.2 * RAP + (BowDMG / BowSpeed) * 2.8) * armor_ reduction
So for my stats it should go like this:
150 + 0.2 * 1128 + (29/2.7) * 2.8 * 0,5783 = 234,6012 dmg

But i deal 317 dmg, way too much.
Only legit source i have is from ElitIstJerks forum [link 1](https://web.archive.org/web/20080730131119/http://elitistjerks.com:80/f31/t13107-hunter_shot_rotation_illustrated/) and less legit Warmane forum (but its copy-paste from another source) [link 2](http://forum.warmane.com/showthread.php?t=351516)
![2020-01-26 11_54_00-World of Warcraft](https://user-images.githubusercontent.com/56025389/73134428-b6f2d280-4036-11ea-81cb-7f7661329981.png)

**Comment by test-1337** [comment]
``` SteadyShotDamage = DamageModifiers × (150 + (WeaponDamage ÷ WeaponSpeed) × 2.8 + 0.2 × RAP + [Dazed: 175]) ```

**Comment by kamil-lada** [comment]
> `SteadyShotDamage = DamageModifiers × (150 + (WeaponDamage ÷ WeaponSpeed) × 2.8 + 0.2 × RAP + [Dazed: 175])`

whats your point? did u copy-paste it from link 2?

**Comment by blblblaz** [comment]
Are you sure the calculation of your own stats is correct? because you counted WeaponDmg as 29 (which I assume is your bow's damage) instead of 389-390. Also I could be wrong but shouldn't you multiply by the armor reduction at the end? as in 0.4217, not 0.5783

**Comment by kamil-lada** [comment]
1. Yes, im sure.
2. Yes, 29 is bow dmg
3. 389-390 is a dmg calculation for auto shot without armor reduction
4. Reduction is 42% so 58% is dealt to target thats why I multiply result by 0.58

**Comment by kelno** [comment]
@kamil-lada you're correct in your calculations.
The issue here is that ammo dps was taken into account.
Fixed in 13266
