### ISSUE TITLE
[quest][Wetlands] War Banner doesn't require pre-quests

### ISSUE THREAD

**Issue by totaemoeggerli** [SunstriderEmu/BugTracker#1768]
**Current behavior**
[War Banners](https://classic.wowhead.com/quest=464/war-banners) requires [Report to Captain Stoutfist](https://classic.wowhead.com/quest=473/report-to-captain-stoutfist) which requires [The Algaz Gauntlet](https://classic.wowhead.com/quest=455/the-algaz-gauntlet).

**Expected behavior**
[War Banners](https://classic.wowhead.com/quest=464/war-banners) doesn't require the other two quests to be complete.

> "By Narrano (4,357 – 1·15·47) on 2019/09/04 (Classic)		
If you have completed The Algaz Gauntlet but you still can't see the quest from Valstag Ironjaw, drop the quest "War Banners". It appears as though if you've already talked to Captain Stoutfist and picked up the quest from him, you won't see the quest to report to him."

This confirms that you can pick up "War Banners" without doing "Report to Captain Stoutfist". While this comment is from Classic it seems reasonable to assume that this was true during TBC. There aren't any comments from TBC that this quest requires any pre-quest.
I understand that this server focuses on TBC but I hope that you guys can fix this issue because it leads to the most important quest reward in the Wetlands.

**Comment by Jerrythemagicdog** [comment]
I see that the quest does indeed require "Report to Captain Stoutfist" and that the completion for quest Report to Captain Stoutfist is 

> <name>.  Valstag briefed me on your past success with the Dragonmaw Orcs at Dun Algaz.  You're a <race> of worth. And I have a task for you. 

The provided source does indeed indicate that "Report to Captain Stoutfist" is a breadcrumb  quest and I agree that it would be painful to do the entire chain coming from elsewhere.

**Comment by Jerrythemagicdog** [comment]
Fixed with next restart, thanks!

**Comment by totaemoeggerli** [comment]
Thanks for addressing the issue. Where do you see that it is required? Because if wowhead list something in a series, it doesn't have to be a requirement. There are many quests that don't require the previous "carry mail" quest but are listed as series.

**Comment by Jerrythemagicdog** [comment]
Oh, what I meant by "does indeed require" was the current state for us at the time of me looking into it.
