### ISSUE TITLE
[quest][Wetlands] Can't start quest Young Crocolisk Skins 

### ISSUE THREAD

**Issue by totaemoeggerli** [SunstriderEmu/BugTracker#1769]
**Current behavior**
[James Halloran](https://classic.wowhead.com/npc=2094/james-halloran) doesn't want to give the quest [Jung Crocolisk Skins](https://classic.wowhead.com/quest=484/young-crocolisk-skins#comments). Tested on level appropriate Draenei Paladin. Before and after completing [Daily Delivery](https://classic.wowhead.com/quest=469/daily-delivery). This quest is not a requirement to start Jung Crocolisk Skins.

**Expected behavior**
The NPC should give the quest without any requirements.

**Comment by Jerrythemagicdog** [comment]
The quest requires being Honored with Ironforge - doesn't seem to make much sense.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart!
