### ISSUE TITLE
Elemental Shaman Fire Nova damage

### ISSUE THREAD

**Issue by AWIDIUS** [SunstriderEmu/BugTracker#1770]
Total joke of a damage done with Fire Nova by Elemental. He is supposed to deal around 1k with that spell.
![image](https://user-images.githubusercontent.com/45521546/73142569-88094a80-4090-11ea-8a65-5bedbf777502.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, will need sources here.

**Comment by Aeded** [comment]
Well first of all, neither of the elementals seem to scale with gear which is wrong. And if they scale then the coefficients are very incorrect. 

Fire ele has too much health and very little mana

I wasted lot of time on warmane to make this irrelevant spell work and they did get it very close in the end. 

https://youtu.be/9FNSYxBrLpI?t=3m17s

If anyone cares enough feel free to search on WM bugtracker "elemental" under TBC and shaman class and there is everything

**Comment by artieau** [comment]
Fire Elemental is working correctly
