### ISSUE TITLE
[Heroic] Arcatraz the mobs at the entrance to the room to Dalliah are chaining incorrectly(aggro range too large(?))

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1771]
Specifically the mobs that are pathing around the stealthed mob at the entrance to that room. The aggro range seems to be too large as, according to the group members you should be able to pull the single stealthed witch without pulling the other 2 mobs if timed correctly(?) however after several attempts at pulling only the final attempt were we able to barely pull 2 mobs instead of 3 in which wipes were a certainty each time.

At the very least it should be easier to pull 2 rather than 3 each time.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed after next restart
