### ISSUE TITLE
[Druid] Force of Nature visual

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#1773]
**Describe the bug**
The summoning visual of Force of Nature (Spell#33831) is showing on ALL nearby players/NPCs/objects instead of on the 3 x Treants that are spawned.

**To Reproduce**
1. Cast Force of Nature
2. Watch green swirlies cover everything around you
3. /scared

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
The visual should only show on the 3 x Treants that are spawned.

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/40563134/73149618-47541480-4116-11ea-8eeb-4a1d62f6b6e5.png)

**Additional context**
rev. 13233

**Comment by woiwoz** [comment]
test fixd done

**Comment by kelno** [comment]
Fixed by woiwoz
