### ISSUE TITLE
[Druid] Force of Nature death animation

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#1774]
**Describe the bug**
When the Treants (from Force of Nature (Spell#33831)) have reached their 30second life duration, they simply phase away instead of displaying their death animation.

**To Reproduce**
1. Cast Force of Nature
2. Wait 30 seconds
3. Watch treants phase out

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
At the end of the spell duration, the Treant should use its death animation instead.

rev.  13233

**Comment by z5n** [comment]
won't change
