### ISSUE TITLE
[Druid] Force of Nature - number of Treants

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#1775]
**Describe the bug**
Sometimes the number of Treants spawned from Force of Nature (Spell#33831) is only two.

**To Reproduce**
1. Cast Force of Nature
2. Count the number of cute trees
3. Stop counting at two

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
The spell should always summon three Treants.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.
![image](https://user-images.githubusercontent.com/40563134/73149792-07d9f800-4117-11ea-9050-689dbc11f07e.png)

Unsure how to replicate this every time, but it just happens sometimes.

**Comment by networm555** [comment]
maybe its terrain related?

**Comment by kelno** [comment]
Probably terrain related yes
