### ISSUE TITLE
[npc] Muckshell Snapclaw poison damage too high

### ISSUE THREAD

**Issue by totaemoeggerli** [SunstriderEmu/BugTracker#1777]
**Current behavior**
[Muckshell Snapclaw](https://classic.wowhead.com/npc=4402/muckshell-snapclaw) uses Poison that ticks for 280 damage at one stack and 530 at two stacks. The same mob melee hits for 40-50 damage with 22% physical damage reduction.

**Expected behavior**
The poison deals too much damage and killed my character within 10 seconds.
As comparison, the [Giant Darkfang Spider](https://classic.wowhead.com/npc=4415/giant-darkfang-spider) of the same level poison ticks for 28 damage. It almost seems as if there is a digit too much.

**Screenshots/videos**
https://gfycat.com/insignificantripeaustraliancattledog

**Comment by Sheikthecatman** [comment]
Thanks! 
Issue will be fixed in revision 13247
