### ISSUE TITLE
[Mechanic] Swapping offhand should reset mainhand swing

### ISSUE THREAD

**Issue by SuddenDeath** [SunstriderEmu/BugTracker#1778]
**Describe the bug**
Currently swapping offhand weapons doesn't reset mainhand swing timer.

**To Reproduce**
1. auto-attack
2. swap weapon

**Expected behavior**
Swapping offhand weapon should reset both offhand and mainhand swing timer.

**Screenshots/videos**
https://youtu.be/eJWNMCD8SMU?t=919 -> Swaps offhand and roughly 1.5-2 seconds later gets in an offhand auto-attack + shiv, no mainhand swing.

https://youtu.be/eJWNMCD8SMU?t=960 - He Shs+4CP KS druid and hits with MH only once on start and then nothing because he swapped offhand

**Comment by sposobniy** [comment]
https://youtu.be/VdMIA6QkgFk?t=764  When rogue  move to druid he switch weapon , when connect get only offhand hit first (btw with Slice of  Dice buff )

**Comment by kelno** [comment]
Fixed with 13262
