### ISSUE TITLE
Vindicator Aesom does not teach every rank of Seal of Righteousness

### ISSUE THREAD

**Issue by totaemoeggerli** [SunstriderEmu/BugTracker#1779]
**Current behavior**
[Vindicator Aesom](https://www.wowhead.com/npc=17844/vindicator-aesom) does not train Seal of Righteousness Rank 2 and 3. He does train rank 4.

**Expected behavior**
Class trainers should teach every rank.

**Screenshots/videos**
from level 1 character https://imgur.com/rKO2sgx

**Comment by Sheikthecatman** [comment]
Thanks and fixed!
