### ISSUE TITLE
[Hunter] Aimed Shot

### ISSUE THREAD

**Issue by networm555** [SunstriderEmu/BugTracker#1780]
Aimed shot do not have minimum range on this server. Hunter Aimed shot me in melee.
How to reproduce:  Stay at range and cast AS  tell your target to close up. Cast will not break up upon reaching minimum range. It will finish cast when your target will be in melee which is wrong. Imagine Aimed shooting rogue that shadow stepped you.

**Comment by Jerrythemagicdog** [comment]
Just tried and the Aimed Shot cast stops when a character runs into the min range (5 yards) Aimed Shot fails to complete the cast. Could you provide the scenario where it happened?

**Comment by networm555** [comment]
same as i described. i was killed in duel by hunter with AS when i stepped exactly into his model to save myself. He just finished AS. If you cant reproduce it seems like something more was involved in event scenario. Lets leave it like this, maybe someone will encounter similar issue.
