### ISSUE TITLE
[quest] Unleash the Raptors

### ISSUE THREAD

**Issue by totaemoeggerli** [SunstriderEmu/BugTracker#1782]
**Current behavior**
Quest [Unleash the Raptors](https://www.wowhead.com/quest=11147/deprecated-unleash-the-raptors) does not give credit for unleashing the raptors and can not be completed.

**Expected behavior**
Quest should be completed when raptors are unleashed.

**Screenshots/videos**
https://gfycat.com/shallowapprehensivebeardeddragon
video from 2015 not TBC: https://youtu.be/FeICxoUY3ZM?t=51

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart!
