### ISSUE TITLE
[Fire Mage] Dragon's Breath overwrites Blast Wave

### ISSUE THREAD

**Issue by Bigsm00th** [SunstriderEmu/BugTracker#1783]
**Describe the bug**
The Blast Wave daze debuff is cancelled by Dragon's Breath, regardless if it's applied before Dragon's Breath or after.

**To Reproduce**
1. Cast Dragon's Breath on target, then Blast Wave. The mob will not gain the daze effect. 
2. Cast Blast Wave on the mob, then Dragon's Breath. This will remove the Blast Wave daze effect. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
The debuffs should function independently from eachother. You should be able to Dragon's Breath > Blast Wave and daze the mob(s) for 6 seconds. You should also be able to Blast Wave, then Dragon's Breath with the daze effect remaining. 

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**
It only seems to be these two spells affecting eachother. E.g. if I Frost Nova > Blast Wave the mobs will keep the daze effect.

**Comment by Jerrythemagicdog** [comment]
Could you provide proof that it's not intended? Both slowing effects have the same value of 50%. Thanks!

**Comment by Ibuprofeno** [comment]
https://youtu.be/wvS3mm0JTv8?t=219 it should be removed
