### ISSUE TITLE
[Shaman] Windfury animation procs at totem

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1785]
**Describe the bug**
Under no clear conditions, WF proc animation can proc on totem and not on a player that proc WF.
Some ranks of WF totem proc the animation when they spawn.

**To Reproduce**
https://youtu.be/lZsnlesRzHU?t=41

I was not able to reproduce it today, but I know that atleast a week back when some party member procced WF, the animation would be displayed on totem and not the player.

Also different ranks of WF totem behave differently with this bug, R4 and R5 just flickers when dropped, but clone animation is not there. Other ranks display the WF animation on totem when used.

**Expected behavior**
WF animation should only be displayed when WF procs and it should be displayed only on the particular player that procced it.

**Comment by Rettiy** [comment]
The animation on the totem is kinda cool in terms of visuals tho.

**Comment by Jerrythemagicdog** [comment]
Looked pretty cool, maybe we should re-add the visual in some way.
Fixed along with other positive buffs being able to affect totems.
