### ISSUE TITLE
[Mage] Spellsteal

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1787]
**Describe the bug**
Spell stolen spells keep the spell power of the target, rather than scaling to mage´s own spell power.

**To Reproduce**
1. Spellsteal a lifebloom from naked druid
2. It ticks for same amout as on druid

**Expected behavior**
Spell stolen spells should scale with mage´s own spell power.

https://youtu.be/7UIEb7nXqgs

**Comment by Jerrythemagicdog** [comment]
Thanks for the source.
Maybe there is a different rule for healing spells: 
https://www.youtube.com/watch?v=IB7bUNWTlh4&feature=youtu.be&t=2226

We can see the healing amount of spellstolen Rejuvenation and Lifebloom here.
