### ISSUE TITLE
[Mage] Winter´s Chill procs on blizzard

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1788]
**Describe the bug**
Somehow and very inconsistently Winter Chill can proc on channeling blizzard

**To Reproduce**
https://youtu.be/9fvBwksK3bM
Mage has 5/5 Winter´s Chill (100% chance)

**Expected behavior**
Blizzard should never proc Winter´s Chill, perhaps your attempt to make the first tick have a chance to apply the winter´s chill is what made it so broken.

**Comment by Jerrythemagicdog** [comment]
Thanks, what's intended was the chance to be distributed evenly among all the ticks.

**Comment by Jerrythemagicdog** [comment]
Issue has been fixed since then, thanks for the report.
