### ISSUE TITLE
[wtf] Spell animation is delayed or not shown at all if attacker is not on your monitor

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1790]
**Describe the bug**
title

**To Reproduce**
https://streamable.com/g33w0

Probably caused by the latest optimization attempts?

**Comment by networm555** [comment]
i remember this behaviour on many servers. nw included. also my memory telling me it was on retail too. its probably how client works. when you run from mob in hopes it wont hit you first you get -health and then animation lands on your dead body.

**Comment by kelno** [comment]
Definitely client side, we can't affect that
