### ISSUE TITLE
[NPC] Enraged Ravagers', in Bloodmyst Isle, loot table is dropping level 67 "Dilapidated Cloth Shoulderpads"

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1791]
![Wow_F7c0gQMEOJ](https://user-images.githubusercontent.com/59293728/73325154-99766200-420a-11ea-88bf-2c210ed6364e.jpg)

EDIT: Also lvl 64 "Rusted Musket"

**Comment by kelno** [comment]
Thanks! Fixed with next update.
I found two creatures types affected.
