### ISSUE TITLE
[Hunter][Pet] Pet training points are being calculated incorrectly

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1792]
https://streamable.com/ys6f9

As shown in the clip my pet is lvl 20 with a loyalty level 3, and has learned Rank 2 Bite, Rank 2 Gore, and Rank 3 Growl, but has -44 training points.

According to https://wow.gamepedia.com/Training_point the formula for calculating training points is as follows: Training Points=(Pet Level) * (Loyalty Level - 1).

So calculating my pet's available training points would be: (20)*(3-1)=40 Training Points, but with Rank 2 Bite, Rank 2 Gore, and Rank 3 Growl would amount to a total of 32 training points remaining. Rank 2 Bite and Rank 2 Gore both costing 4 training points each, and Rank 3 Growl costing 0 training points.

**Comment by Jerrythemagicdog** [comment]
Thanks for the source!

**Comment by Liquidsoap** [comment]
This appears to still be an issue with all pets I have tamed. This is my current pet which i tamed at lvl62 and now at lvl70 with loyalty lvl6 I am unable to teach it any abilities.
[https://imgur.com/a/wo38vsE](url)

**Comment by kelno** [comment]
It should be fixed with next restart
