### ISSUE TITLE
[Shaman] Not all negative effects affect  Water and Lightning shields procs 

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1794]
Describe the bug:
Title .

https://www.twitch.tv/sposobniy/clip/EnticingCorrectPelicanKeepo Not triggering water shield proc after blind 
https://www.twitch.tv/sposobniy/clip/ClearAmazingKuduBudStar Water shield not proc after druid using Hurricane 

To Reproduce :  
Use Blind/Hurricane against shaman with Water or Lightning shields buff 

Some info : 
https://youtu.be/IFuGPWl2jDQ?t=9m7s   shield proc after Blind 
If necessary, I have a lot of videos with shield procs after Fears  , Cyclone , pollymorph etc etc . But this act works fine , i think just missing some spell categories 

Expected behavior : All negative effects should triggering shields procs.

**Comment by Jerrythemagicdog** [comment]
Thanks!
To dev:
'PROC_FLAG_TAKEN_SPELL_RANGED_DMG_CLASS' doesn't seem to have the correct logic in it.
Blind is correctly a ranged spell.

**Comment by Jalapan** [comment]
https://www.youtube.com/watch?v=0q-p4W3dJcM

Periodic auras such as netherspite dmg aura, wrath scryer soccrates etc shouldnt remove stacks.

Here is proof

**Comment by Jerrythemagicdog** [comment]
Issue with Netherspite's damage aura is fixed on next update, thanks for the proof!

**Comment by Jerrythemagicdog** [comment]
Water Shield issue fixed with next update as well.
