### ISSUE TITLE
[Paladin] [Mechanic] Seals overwrite each other too slow

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#1795]
**Describe the bug**
As a paladin, while swapping from one seal to another, there is a short period of time (like 0,5 sec) where both seals are still active. If you want to use judgement instantly after you use the new seal, the judgement comes from the old seal, that wasn't properly overwritten yet.

This might sound like a stupid bug but it's actually really annoying as I am just used to judge right after I use seal if I go for a specific one. Example situation:
- I HoJ druid with Seal of Command up, druid has Judgement of Justice on himself. Druid trinkets the HoJ while trinket also removes Judgement of Justice. I want to immediately reapply Judgement of Justice, but at that small time period, both Seal of Justice and Seal of Command are up and the Judgement then comes from the old seal -- Seal of Command. This ruins the game as druid just runs away.

**To Reproduce** [1]
1. Use one kind of Seal and have the seal buff active
2. Prepare to use Judgement but right before that use another seal, as if you wanted to judge the new seal
3. Notice it's the old seal that got judged

**To Reproduce** [2]
1. Use one kind of Seal and have the seal buff active
2. Use another Seal
3. Notice for short period of time, both of them are active

**Expected behavior**
Paladin should only have one seal active, as all seals literally say that. There shouldn't be any mid-period where if switching from one seal to another, both are active.

**Screenshots/videos**
https://imgur.com/a/onV3x6m referring to these as "SS1" to "SS3"

SS1 and SS2 show two seals active at the same time, which should never happen.
**SS3 shows what actually bothers me the most. As you can see, I try to go from Seal of Command to Seal of Justice and use Judgement of Justice. Instead, Judgement of Command happens after I already put the Seal of Justice up. The order of the events is clearly visible in Combat log on SS3.**

At this point it's a muscle memory for me and I can't really work around that. If this is a thing that is for some reason implemented for Seal Twisting, then I beg you to remove it and try to find another way to make seal twisting work.

**Comment by Msordet** [comment]
Seems to be related to the seal twisting implementation which will be worked on soon: https://github.com/SunstriderEmu/BugTracker/issues/1484

**Comment by SUN-Leekie** [comment]
Seems to be related to the seal twisting implementation which will be worked on soon. (https://github.com/SunstriderEmu/BugTracker/issues/1484)

**Comment by kelno** [comment]
Thanks for reporting!
I'll link this one on the other issue for the additional info and close this one as they are indeed the same issue.
