### ISSUE TITLE
Bloodscale Enchantress instant damage from Freezing Circle

### ISSUE THREAD

**Issue by totaemoeggerli** [SunstriderEmu/BugTracker#1797]
**Current behavior**
[Bloodscale Enchantress](https://www.wowhead.com/npc=18088/bloodscale-enchantress)'s [Freezing Circle](https://www.wowhead.com/spell=34787/freezing-circle#comments) deals its damage instantly without chance for the player to move away. The spell deals extremely high damage for a mob of that level. 
https://gfycat.com/remorsefulacrobatickouprey

**Expected behavior**
The spell should create a rune with ice blocks on the ground and deal damage after a short delay.

**Screenshots/videos**
from wowhead 2008: ![](https://wow.zamimg.com/uploads/screenshots/normal/69979-freezing-circle.jpg)

**Comment by Jerrythemagicdog** [comment]
Thanks, increased the delay a bit.
Live with next restart!
