### ISSUE TITLE
[quest] A Warm Welcome

### ISSUE THREAD

**Issue by totaemoeggerli** [SunstriderEmu/BugTracker#1798]
**Current behavior**
[Naga Claws](https://www.wowhead.com/item=24280/naga-claws#comments) needed for the quest [A Warm Welcome](https://www.wowhead.com/quest=9728/a-warm-welcome#comments) don't drop from [Bloodscale Slavedriver](https://www.wowhead.com/npc=18089/bloodscale-slavedriver) or [Bloodscale Enchantress](https://www.wowhead.com/npc=18088/bloodscale-enchantress). Additionally the drop chance from other Nagas isn't 100% as it should be.

**Expected behavior**
Multiple comments from 2.0-2.4 confirm that the quest item has 100% drop chance from any Naga in Zangarmarsh.

> By XxAvalanchexX (3,449 – 8·40) on 2007/09/07 (Patch 2.1.3)
This item has a 100% drop rate from any of the nagas in the zone while you are on the quest.

> By chonchu (7,452 – 2·24·57) on 2007/01/20 (Patch 2.0.5)
It is a 100% drop rate. ...

**Additional context**
Drop chance listed on wowhead are not reliable because they include kills from players that are not on the quest. Bloodscale Slavedriver/Enchantress are farmed for Sporegar rep via the repeatable [Now That We're Still Friends...](https://www.wowhead.com/quest=9727/now-that-were-still-friends) quest. This explains why the drop chance of Naga Claws is extremely low for these two mobs and not 100% for other.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.
