### ISSUE TITLE
[quest] The Hunter's Path (Dwarf)

### ISSUE THREAD

**Issue by Shmilowitz** [SunstriderEmu/BugTracker#1799]
**Describe the bug**
The hunter quests for taming a pet can't be obtained from ANY hunter trainer, only from Grif Wildheart in Kharanos.
Also the followup quests doesn't reward any experience. 

**To Reproduce**
1. Be level 10 dwarf hunter
2. Can only take The hunter's path from Grif Wildheart.

**Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.**
https://wowwiki.fandom.com/wiki/Quest:The_Hunter%27s_Path_(Dwarf) states:
"The Hunter's Path (Dwarf) is the starter quest for the Dwarf Hunter quest chain to get pet skills. It is acquired from class trainers."

**Expected behavior**
https://tbc.cavernoftime.com/quest=6064
Also shows that all the followups should reward 850 XP with x1 rates. Right now it gives nothing.

**A clear and concise description of what you expected to happen.**
That hunters can take the quest from any hunter trainer and that the chain gives experience.

**Additional context**
Not sure if any of the issues are effecting any other hunter races.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed after next restart

**Comment by Jerrythemagicdog** [comment]
Fixed in 8986f067146c9342060015bc9b3493f6514918cf (scripts)
