### ISSUE TITLE
Some gameobjects models are not disappearing immediately after collection (clientside only)

### ISSUE THREAD

**Issue by Klaceyes** [SunstriderEmu/BugTracker#18]
**Current behaviour:**

Some wood or metal pieces from the quest "I work… for the Horde !" aren't disappearing after looting for more than a second

**Expected behaviour:**

Any looted item from the world should disappear after one second or something like that

**Steps to reproduce the problem:**

Just looting a piece of wood or of metal

Quest ID: 10086
Quest Giver: Megzeg Nukklebust 21283
Wood gob: 182936
Metal gob: 182938

Note that quest " The Path of Glory " has the same issue:
https://github.com/thebarrensissues/Issues/issues/482

**Comment by talamortis** [comment]
Fix is here

https://github.com/talamortis/sunstrider-core/commit/4f878d376c63026f9f45f4323ae2a13d29802d9d

**Comment by kelno** [comment]
Dev note:
Can't find a rule to predict when is will bug.
In every case GameObject correctly calls AddObjectToRemoveList and SMSG_DESTROY_OBJECT is called.

**Comment by kelno** [comment]
Still happening?

**Comment by artieau** [comment]
![image](https://user-images.githubusercontent.com/40563134/56429511-842ce880-6306-11e9-89e5-436fea9d222e.png)
Still happens @kelno 
Can see the object which is still sparkling for about 20sec after

**Comment by kelno** [comment]
Confirming this, tried on the metal with spawnID: 23799

**Comment by kelno** [comment]
I'll close for now until proof there is actually a way to fix it, since it seems to be a client bug
