### ISSUE TITLE
[Priest] Shadowfiend's hp values.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#180]
**Description:**
Currently Shadowfiend (entry 19668) has too much hp - on a priest with no additional stats and base values it has 15123 hp. 
screenshot: https://imgur.com/a/foh6O6t

**Expected behaviour:**

The Shadowfiend should have way less hp (he has things like dodge rating and resistances to make up for his lower hp) than he has currently. The other issues (dodge and resistances) will be addressed in a separate report.

Some sources that point us to the reason HP values should be lower:

> This pet will now come into the game with full health and mana, including that gained from a percentage of its master’s stamina and intellect **from** http://wowwiki.wikia.com/wiki/Shadowfiend 

> Some brief things about Shadowfiend, taken from Elitist Jerks:
> - Attacks are melee shadow damage, using a normal melee attack table, with damage reduced based on armor of the target
> - Has ~1.5second attack speed (10 times per 15 second life)
> - Benefits from your +dmg with a ~65% coefficient (6.5% per hit)
> - Damage added from Shadowform, Darkness, Shadow Weaving, Misery, Curse of Shadow, and Improved Shadow Bolt, and so on.
> - Damage added from attack power bonuses (possibly double-dipping - the direct buff, and scaled with your stats), armor reductions on the target, and so on
> - Benefits from Bloodlust/Heroism and similar buffs IF the fiend is already out when it's cast.
> - Has extremely high dodge rating (in the vicinity of 75%) and significant resistances to most/all spell schools

from: https://www.wowhead.com/spell=34433/shadowfiend#comments:id=155304

**Some data points for shadowfiend's HP:**

- Post from early TLK###  (possibly irrelevant to our case as scaling changed):
https://www.wowhead.com/spell=34433/shadowfiend#comments:id=736777

> attacking a lvl64mob at lvl67 with 567 Spell Power:
> - 9 or 10 attacks of 356-357 shadow damage each,
> - curiously always giving 8-9 (one less than attacks) times 5% total mana
> - has 6378hp, 4478mana (but mostly it stays alive for full 15sec anyway)

- Hydra 5 Season 3 disc priest
1. https://youtu.be/RGaWU-iRXHk?t=158
    Owner's hp value: 11.6k
    Shadowfiend's hp value: 2300
2. https://youtu.be/RGaWU-iRXHk?t=306
    Owner's hp value: 11.6k
    Shadowfiend's hp value: 2300
- Hydra 4
3. https://youtu.be/KO7Ht29IqBE?t=79
    Owner's hp value: 10.7k
    Shadowfiend's hp value: 2196
4. https://youtu.be/KO7Ht29IqBE?t=264
    Owner's hp value: 9931
    Shadowfiend's hp value: 2100
- Hydra 6
5. https://youtu.be/NMkgJmSiMc4?t=156
    Owner's hp value: 12.2k
    Shadowfiend's hp value: 2368

**rev. hash/commit:** 
Sunstrider rev. 10269 (2e509ac) 2019-01-19 11:18:46 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
This is updated by
3b07f615e941517bba4bf8b8cfbcc3423bafe1a0 
And
b182a8dc30de49ca6b61d9429b22abfef5dee3c1 

Will need another test when server is updated

**Comment by Jerrythemagicdog** [comment]
After the updates Shadowfiend is at 9800 health with a 3800 health owner.

**Comment by Jerrythemagicdog** [comment]
Appears to be fixed, closing.
