### ISSUE TITLE
Murkblood Invader instant respawn

### ISSUE THREAD

**Issue by totaemoeggerli** [SunstriderEmu/BugTracker#1800]
**Current behavior**
[Murkblood Invader](https://www.wowhead.com/npc=18238/murkblood-invader#comments) corpse despawns without any chance to loot and respawns immediately.
First I split a single mob from the other two and pull it back to the others to have them engaged on killing blow but it still respawned instantly without me being able to loot: https://gfycat.com/grossfarflungirishwolfhound 
Another try with the mob respawning instantly quite far back: https://gfycat.com/agileacceptablehedgehog 

**Expected behavior**
Mobs shouldn't despawn/respawn instantly.

**Additional context**
There is a closed issue related to the mob but I doubt this is an issue of visibility range.
https://github.com/SunstriderEmu/BugTracker/issues/1660

**Comment by totaemoeggerli** [comment]
I managed to kill all of them in one go and they behaved normally: https://gfycat.com/ablereliableenglishsetter
However, I do think it should be possible to pull one away, kill and loot.
Sadly non of them dropped the quest item that should be a guaranteed.

> By Varmkorx (6,048 – 2·7·29) on 2008/04/24 (Patch 2.4.1)
It has a 100% drop chance of a Murkblood Invader, unless you already have it or finished it.

> By TheWafflian (1,214 – 8·17) on 2013/07/16 (Patch 5.3.0)
Drop rate is 100% if you've not already done it.
WoWhead displays it as a lower drop rate, because players who have already finished the quest have looted, and not obtained the drop.

The drop chance displayed on wowhead or similar sources is 33% because most players kill all 3 but only get one quest item.

**Comment by networm555** [comment]
can confirm its a 100% drop , no matter what one of them should contain quest item.

**Comment by Jerrythemagicdog** [comment]
Instant respawn - https://github.com/SunstriderEmu/BugTracker/issues/1551

Will fix the missing quest item soon, thanks!

**Comment by Jerrythemagicdog** [comment]
Fixed after next restart.
