### ISSUE TITLE
[Hellfire Peninsula] Starving Helboar wtf

### ISSUE THREAD

**Issue by networm555** [SunstriderEmu/BugTracker#1802]
em. are you serious? instant charge from kilometer away? It shouldn't have this ability at all.  It should have  Burning Spikes.  Not stock? Sure!

**Comment by Jerrythemagicdog** [comment]
https://www.wowhead.com/npc=16879/starving-helboar#comments

**Comment by Fettbergg** [comment]
Man 0 : 1 Pig

**Comment by networm555** [comment]
But where do you see charge? Even in comments people say nothing about charge. They can stun. But pretty sure they shouldn't headbutt you in ass.  Personally i think its fun, but trust me i am always  minority.
1. Very annoying, aggro from far away.
2. 25 damage every time you hit them in melee, making them tough for warriors/rogues/shamans/druids, etc.Seems like we need someone to check it on retail. (thats Burning spikes)
Too bad i deleted retail client :(

**Comment by Jerrythemagicdog** [comment]
It was referenced with retail when the creature was looked at.
I also find it funny and we decided to keep it!
Thanks.
