### ISSUE TITLE
Wrong mobs in Skettis (Mountain Colossus)

### ISSUE THREAD

**Issue by snurkh** [SunstriderEmu/BugTracker#1803]
**Describe the bug**
Wrong mob in the "Skettis" area in Terrokar Forest. 

**To Reproduce**
1. Go to Skettis.
2. See that Mountain Colossus are not the right mobs.
3. Correct mobs would be https://tbc-twinhead.twinstar.cz/?npc=23029 (Talonsworn Forest-Rager) that you can kill for herbs / motes of life and herb for similar drops.

**Expected behavior**
Elite trees ranging from Level 70-73 dropping herbs / motes of life on kill and more herbs and motes of life upon herbing them (Herbalism 375)

**Screenshots/videos**
2 videos from back in the day showing the Talonsworn Forest-Rager in Skettis with mob behavior and loot table. 

https://youtu.be/XXK8IgXyERc
https://youtu.be/tirxKZCD55k

**Additional context**
Found this herbalism guide from back in the day: (https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/134551-guide-wip-herbalism-you-complete-guide.html) 
Aside from a useful herbalism guide the author writes about the use of these elite trees and their strong drop tables to the additional ability to herbing them. Taking this as a relevant source, because what else, the static 15 minute respawn timer on the 5 different spawns is pretty realistic as well. I could not find any information about the exact spawnpoints aside from the video clips but since the "false databases" seemed to be pretty correct on most things regarding these mobs they might be correct as well. 

Edit: missing information and sources, new to this github thing..

**Comment by Jerrythemagicdog** [comment]
The PTR is currently set to patch 2.0, are you sure these shouldn't be there before?

**Comment by networm555** [comment]
in 2.0 there should be elite trees patrolling around.

**Comment by NeonicSupersonic** [comment]
How about doing some research instead of faslsereporting stuff cos you want cheap flasks?
![Wowheadishard](https://user-images.githubusercontent.com/45077198/73530869-60b4d380-442a-11ea-85e3-0b0d2af2a9c8.jpg)

**Comment by networm555** [comment]
please do not use wowhead or other db data as a proof. amount of mistakes there is unforgivable. What we can use is retail client and old videos. That's about it.  I deleted my client after classic release. 100% will not install it agian. 
There will be no cheap flasks no matter what if pop is at least 2k+ . Too few of them around to fill the market and competition is insane. Delay in killing them becаuse of the pvp will be pretty much big.

**Comment by SUN-Leekie** [comment]
@networm555 @snurkh Please provide sources.

**Comment by snurkh** [comment]
What do you mean by false reporting @NeonicSupersonic
I literally farmed these on 3 different private servers and they always had the same drop rates and you could herb them. I don't care about cheap flasks or anything because im gonna play a lot anyway. But you can literally google for the NPC that is roaming around the area in Skettis on PTR now and you literally don't find anything.

**Comment by snurkh** [comment]
a bit annoying to read through but you get the gist of it anyway.
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/134551-guide-wip-herbalism-you-complete-guide.html

**Comment by snurkh** [comment]
Found these 2 videos which both seem to be pretty relevant sources in my eyes.
Here you can see that both, the mobs are in the actual zone I referred to and that the drop table that various different databases provide are actually correct. I have never stated that these were non elite, i just literally stated that these are not the correct mobs.
Also if you read through the herbalism guide from 2007/8 that I linked the author says that there are 5 spawns on a static 15 minute respawn.
Videos for proof:
https://youtu.be/XXK8IgXyERc
https://youtu.be/tirxKZCD55k

**Comment by Morskitar** [comment]
Up ! 
snurkh is right, there was Skettis Trees on official. They were elites mob from the begening to the end of burning crusade. They used to be farmed for plants. 
They're a loooot of videos on youtube of people farming them. 
This should be patch because it's a huge mistake.

https://www.youtube.com/watch?v=eyuOowmef6E
https://www.youtube.com/watch?v=YsUshEfXay4
https://www.youtube.com/watch?v=0FG7tJtEEcE
