### ISSUE TITLE
Bugged quest - Supplies to Private Thorsen

### ISSUE THREAD

**Issue by yolohse** [SunstriderEmu/BugTracker#1804]
**Describe the bug**
Not able to turn in quest

**To Reproduce**
lvl 38 warlock not being able to turn in the quest

Should be quest id198.

**Comment by Jerrythemagicdog** [comment]
Possibly because he's on his patrol to the jungle and he is temporarily not a quest giver. In order to pick up "Jungle Secrets" and for him to become a quest giver you need to save him from an ambush in the jungle.
