### ISSUE TITLE
Boat in Booty Bay does not dock

### ISSUE THREAD

**Issue by yolohse** [SunstriderEmu/BugTracker#1806]
**Describe the bug**
The Boat to Ratchet does not dock in Booty Bay. It spawns out in the water and sails to Rathet, making it impossible to board. I think the same problem exists for all boats and zeppelins, but just a theory

**To Reproduce**
Stand at docks for 4 minutes and have a look.

![image](https://user-images.githubusercontent.com/59824709/73539023-b7231180-442c-11ea-92bb-f211b9bcffec.png)

**Comment by hufsa** [comment]
Thanks. Closing this as we have #445
