### ISSUE TITLE
[npc] Warp-Raider Nesaad

### ISSUE THREAD

**Issue by totaemoeggerli** [SunstriderEmu/BugTracker#1807]
**Current Behavior**
[Warp-Raider Nesaad](https://www.wowhead.com/npc=19641/warp-raider-nesaad#comments) uses his ability without CD and each explosion deals around 1400 damage.

**Expected behavior**
> By Amaranta (1,017 – 1·12) on 2007/05/06 (Patch 2.0.12)
... He has one special ability - A channeling arcane explotion which makes 4 arcane explotions of (to me 383dmg each blast - lvl 70 no arcane resistance) ...

400 damage is a lot more in line with mobs of this level.

I can't find any proof about the CD of the ability but it is very obvious that this is not as it should be.

**Screenshots/videos**
https://gfycat.com/insecuregorgeousafricanwilddog

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart!
