### ISSUE TITLE
[quest] Cohlien Frostweaver hostile RP-event

### ISSUE THREAD

**Issue by totaemoeggerli** [SunstriderEmu/BugTracker#1808]
**Current Behavior**
NPC spawned for [Cohlien Frostweaver](https://www.wowhead.com/quest=10307/cohlien-frostweaver ) RP-event is hostile: https://gfycat.com/unsteadyfrighteningethiopianwolf
There are 3 other similar quests. No issue with two of them but [Battle-Mage Dathric](https://www.wowhead.com/quest=10182/battle-mage-dathric) entered/dropped combat for a split second: https://gfycat.com/joyfulmemorablegonolek

**Expected behavior**
NPCs spawned for this RP-event shouldn't be hostile.

**Comment by Sheikthecatman** [comment]
Thanks!
This has been fixed in: 4b3b6a16870f32353385dbf9e8fcc49da0c84cc0
