### ISSUE TITLE
[Priest] Shadowfiend stats.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#181]
**Description:**

Shadowfiend (19668) needs resistances and dodge rating to make up for his lower hp values.

**Current behaviour:**

Right now Shadowfiend appears to have no dodge rating or much resistances.

**Expected behaviour:**
A lot of good research is done here so I'll just reference it: 
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2590

**Comment by kelno** [comment]
http://temp.arena-tournament.com/forum/viewtopic.php?f=41&t=14684&sid=9c3a04bd24936d015b6356cef348eef9

**Comment by Jerrythemagicdog** [comment]
https://wow.gamepedia.com/index.php?title=Shadowfiend&oldid=1427638

**Comment by kelno** [comment]
Fixed with 11400

**Comment by Jerrythemagicdog** [comment]
fixed

**Comment by Jerrythemagicdog** [comment]
This is apparently wrong, players attacking the Shadowfiend should have a chance to be missed rather than the attacks being dodged. This is an important distinction because Dodge allows Warriors to instantly Overpower it and kill it with one spell.

**Comment by kelno** [comment]
That explains why I couldn't find any spell to handle it before.
Fixed!
