### ISSUE TITLE
[Hunter] Draenei hunter pet quests in Azuremyst Isle are not rewarding xp and at lvl 10 are appearing grey in the quest log

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1810]
https://streamable.com/4hi0o is the handin for the first part of the hunter pet chain called "Seek Huntress Kella Nightbow" and according to [wowwiki](https://wowwiki.fandom.com/wiki/Quest:Seek_Huntress_Kella_Nightbow) the base xp reward is 85.

https://streamable.com/m0fp6 is the handin for the second part of the hunter pet chain for the first tamed beast(Barbed Crawler) called "Taming the Beast" and according to [wowwiki](https://wowwiki.fandom.com/wiki/Quest:Taming_the_Beast_(Draenei_1)) the base xp reward is 850.

https://streamable.com/vg3lm is the handin for the third part of the hunter pet chain for the second tamed beast(Greater Timberstrider) called "Taming the Beast" and according to [wowwiki](https://wowwiki.fandom.com/wiki/Quest:Taming_the_Beast_(Draenei_2)) the base xp reward is 850.

https://streamable.com/fl15m is the handin for the fourth part of the hunter pet chain for the third and final tamed beast(Nightstalker) called "Taming the Beast" and according to [wowwiki](https://wowwiki.fandom.com/wiki/Quest:Taming_the_Beast_(Draenei_3)) the base xp reward is 850.

https://streamable.com/5sa1g is the handin for the fifth and final part of the hunter pet chain called "Beast Training" and according to [wowwiki](https://wowwiki.fandom.com/wiki/Quest:Beast_Training_(Draenei)) the base xp reward is 420.

As can be seen in all the clips above there is no xp being rewarded for these hunter pet quests and despite these being lvl 10 quests the quest log is showing them as grey when they should be shown as yellow in the quest log.

I am assuming this is just an error in the database with the quests level values being incorrect(?) when they should be lvl 10, so that xp is being rewarded correctly? I could be way off here though.

EDIT: #1799 related. Maybe none of the hunter pet quests are giving xp as they should?

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed after next restart
