### ISSUE TITLE
Concecration wrong spellpower scaling

### ISSUE THREAD

**Issue by Felynda** [SunstriderEmu/BugTracker#1811]
**Describe the bug**
Currently concecration scales with spell damage at a ratio that is too low. See screennshot below:

![image](https://user-images.githubusercontent.com/45050227/73591143-40008280-44eb-11ea-933a-78f5c5b9ee13.png)

I am using gear with 809 damage on it. With this gear concecration is ticking for 99 times 8 for a total of 792. Naked concecration deals 512 damage total. an increase of 280. This means consecration only gets a 35%ish spell damage increase on live server. It is supposed to get 100% please see this detailed bug report from another server: https://github.com/Atlantiss/NetherwingBugtracker/issues/3402

**Comment by Jerrythemagicdog** [comment]
Thanks for the sources!

**Comment by GigilPiq** [comment]
Please devs, label this as **gamebreaking**. This is really hurting Paladin tanks and Paladins in general. Thank you.

**Comment by GigilPiq** [comment]
https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=1549180#Paladin_coefficients 

There is **Consecration** spell ratio.

**Comment by GigilPiq** [comment]
Devs, I am still waiting for this to be fixed so I can actually play my class in PvE and Arenas. This issue was created Feb 1st. Do you plan on fixing this someday or should I just quit playing ? I am kinda tired of waiting for my class core spells to be fixed, so just tell me now if I am going to wait another month or two.

**Comment by mchayes** [comment]
It seems like paladins is getting a bit of a short end of the stick here. Rare updates on some rather core issues. As can be seen in many other paladin related issues.

**Comment by kelno** [comment]
Fixed with next update
