### ISSUE TITLE
[npc] Shadowy Summoner Summon Succubus

### ISSUE THREAD

**Issue by totaemoeggerli** [SunstriderEmu/BugTracker#1814]
**Current behavior**
[Shadowy Summoner](https://www.wowhead.com/npc=17088/shadowy-summoner#abilities)'s [Summoned Succubus](https://classic.wowhead.com/spell=8722/summon-succubus#summons) does not engage in combat.

**Expected behavior**
Pets from NPCs should engage in combat when attacked.

**Screenshots/videos**
https://gfycat.com/dismalsleepybison

**Additional context**
Similar issue found here: https://github.com/SunstriderEmu/BugTracker/issues/538

**Comment by Sheikthecatman** [comment]
Thanks! 
Issue resolved in 98f53ac81a1ea77b7d8bf3669525e5eb95936ba4 (scripts)
