### ISSUE TITLE
Herbalism error when picking: "That is already being used".

### ISSUE THREAD

**Issue by maidros** [SunstriderEmu/BugTracker#1815]
**Describe the bug**
Whenever I try to pick an herb, I get the message "That is already being used". I went back to the beta camp, dropped herbalism, retrained it, and still the same message appeared whenever I tried to click on any herbs. Last week herbalism worked fine, but this week it gives this message. I made sure to click on herbs that I had never clicked on before today, still the same problem.

**To Reproduce**
1. Click on an herb.
2. ???
3. Do not profit.

**Expected behavior**
No message should appear, and an herb should be deposited into my bags.

**Screenshots/videos**
![WoWScrnShot_020220_170000](https://user-images.githubusercontent.com/45544250/73616237-eaa59d80-45de-11ea-816c-8c30ac895d13.jpg)

**Additional context**
I am in fact extremely handsome in real life, so you should factor that in, too.

**Comment by hufsa** [comment]
Same thing with Mining. Nodes don't have the "Requires Mining" text either

**Comment by Jerrythemagicdog** [comment]
Related to '38cb388a1bd11e11af6357bafbe4fe7ed06b326d' the state has to be set to 1 (currently 0)

**Comment by kelno** [comment]
Fixed at next restart
