### ISSUE TITLE
Bangalash respawn time

### ISSUE THREAD

**Issue by Shmilowitz** [SunstriderEmu/BugTracker#1817]
**Describe the bug**
Bangalash in stranglehorn vale has a 20min respawn time or something in that range. 

**To Reproduce**
1. Kill Bangalash (https://classic.wowhead.com/npc=731/king-bangalash)
2. Time the respawn

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
Only evidence that I could find about Bangalash respawn time is an old wowhead comment (https://classic.wowhead.com/npc=731/king-bangalash):
"Does anyone know what the respawn time is around?
Nevermind, it took around 10mins.

Edited, Mon May 23 02:38:55 2005"

**Comment by Sheikthecatman** [comment]
Thanks!
Fixed in 610dce82dc03395abed193cb4a141951a3130017
