### ISSUE TITLE
[Quest] Z'kral in Hellfire

### ISSUE THREAD

**Issue by Shmilowitz** [SunstriderEmu/BugTracker#1818]
**Describe the bug**
Z'kral's power charge ability works incorrectly. Currently he suicides whenever he uses power charge and the quest called "The Mastermind" (https://www.wowhead.com/quest=10099/the-mastermind) doesn't get completed if he suicides. 

**To Reproduce**
1. Pull Z'kral (https://www.wowhead.com/npc=18974/zkral#abilities)
2. Allow him to cast Power Burn(https://www.wowhead.com/spell=32003/power-burn)

**Expected behavior**
Power Burn on wowhead reads: 
"Hits an enemy with an anti power bolt that consumes up to 266% mana. For each point of mana consumed by the bolt, the target takes damage.".

Looking at any tbc database. Power Burn seems to be a mana burning ability. Not a suicide. 
I think the issue comes from the fact that you coded the Goblin sappers, that surrounds him, to suicide.

**Comment by Sheikthecatman** [comment]
Thanks!
Fixed in 3ae6109932f5b5d9863e35842ffb539714a301ec (scripts)
