### ISSUE TITLE
Helboars in hellfire pen aggros from 40-50 yards

### ISSUE THREAD

**Issue by Shmilowitz** [SunstriderEmu/BugTracker#1819]
**Describe the bug**
All helboars in hellfire pen aggros and charges from 40 yard range.

**To Reproduce**
1. Find a helboar
2. Check aggro-range 

**Expected behavior**
Normal aggro range instead of 40-50 yard

**Comment by Sheikthecatman** [comment]
https://www.wowhead.com/npc=16879/starving-helboar#comments
