### ISSUE TITLE
Quest bugged "The Mastermind"

### ISSUE THREAD

**Issue by yolohse** [SunstriderEmu/BugTracker#1821]
**Describe the bug**
The Outland quest "The Mastermind" seems bugged. Questid 10099.
When engageing with Z'kral he instantly dies when he is around 80% HP and the quest does not complete. I had this happen three times both with and without Void Walker in the fight.

![image](https://user-images.githubusercontent.com/59824709/73733657-a4665080-473c-11ea-9a0d-17c16b0c0eee.png)

**Comment by Sheikthecatman** [comment]
Thanks!
Same issue as #1818
