### ISSUE TITLE
[Quest] Cursed Talisman

### ISSUE THREAD

**Issue by Shmilowitz** [SunstriderEmu/BugTracker#1822]
**Describe the bug**
The cursed talisman quest doesn't seem to be effected by the alliance drop rate perks. Drop rate seems low, https://www.wowhead.com/quest=10484/cursed-talismans

**Expected behavior**
Not sure how the alliance perks are suppose to work exactly. But this one seems lower than all other quests I did.

**Comment by Jerrythemagicdog** [comment]
Fixed in
https://github.com/SunstriderEmu/BugTracker/issues/1809
Server not restarted yet!
