### ISSUE TITLE
Idol of the Raven Goddess Snapshotting

### ISSUE THREAD

**Issue by Zedlus** [SunstriderEmu/BugTracker#1823]
Current Behaviour:
Equipping Idol of the Raven Goddess and swapping into Dire Bear Form via the following macro
#showtooltip Dire Bear Form(Shapeshift)
/equip Idol of the Raven Goddess
/cast Dire Bear Form(Shapeshift)

Causes my character to receive the Idol of the Raven Goddess crit bonus on Leader of the Pack (which is talented with 1/2 Improved Leader of the Pack). However continuing to swap Idols via other macros such as 
#showtooltip Mangle (Bear)(Rank 3)
/equip Idol of Terror
/startattack
/cast Mangle (Bear)(Rank 3)

causes you to lose the crit chance bonus from the Idol of the Raven Goddess according to the character stats sheet.

Expected Behaviour:
Equipping Idol of the Raven Goddess and shifting into Cat or Dire Bear Form should snapshot the crit bonus from the idol onto Leader of the Pack, swapping idols while currently shapeshifted should have no impact on your overall crit chance. This is standard TBC snapshotting.

Steps to recreate issue:
1) Equip Idol of the Raven Goddess
2) Shapeshift into Dire Bear Form or Cat Form
3) Swap idols
4) Observe change to crit chance

I'm unsure of the exact ID's of all the items and spells so I won't link them in case it causes confusion.

**Comment by Jerrythemagicdog** [comment]
Thanks, could you provide some sources?

**Comment by Zedlus** [comment]
I've become unsure now. I recalled it from both my own memory and from other private servers. I found it additionally mentioned in this [Feral Guide](https://legacy-wow.com/druid-feral-level-70/). But as I can't find any more legitimate sources via google that aren't just my memory, other private servers and a guide my issue may be erroneous.

**Comment by artieau** [comment]
Closing but create a new issue if other evidence is found.
