### ISSUE TITLE
[Rogue] Find Weakness does not increase poison damage

### ISSUE THREAD

**Issue by Felynda** [SunstriderEmu/BugTracker#1824]
**Describe the bug**
Assasination rogue talent "Find Weakness" is supposed to increase all offensive ability damage by 10%. Currently this does not apply to poisons.

**To Reproduce**
1. Apply a poison on weapon
2. Gain "Find Weakness" buff
3. Observe poison damage not being increased

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
Poison damage increased by 10% when Find Weakness is active

**Screenshots/videos**
As can be seen  below this is me spamming shiv with instant poison with Find Weakness up. None of my 95 attacks went over the tooltip given max damage. Statistically atleast one should have done higher damage. The same thing can be done with deadly poison.
![image](https://user-images.githubusercontent.com/45050227/73793247-4bcb9d80-47a6-11ea-8571-45bcaf66d5f9.png)

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by hufsa** [comment]
Thanks, fixed with next restart.
