### ISSUE TITLE
Find Weakness does not benefit the attack that procced it

### ISSUE THREAD

**Issue by Felynda** [SunstriderEmu/BugTracker#1825]
**Describe the bug**
Assasination talent "Find Weakness" does not apply it's increased damage to the ability that procced it.

**To Reproduce**
1. build 5cp with and without the talent. 
2. Use Rupture ability
3. Observe damage being the exact same.

**Expected behavior**
The rupture with the talent is supposed to give 10% increased damage.

**Comment by Jerrythemagicdog** [comment]
Thanks!
Could you provide some proof that it's intended to work this way?
