### ISSUE TITLE
[Hunter] Aimed Shot - not reset auto-shot timer 

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1827]
Describe the bug
Aimed Shot - not reset auto-shot timer 

To Reproduce : 
Cast Aimed shot , auto shot will start instant after cast done 

How it should work : 
https://wowwiki.fandom.com/wiki/Aimed_Shot  
Patch 2.0.6 (23-Jan-2007): Auto Shot is now reset when casting Aimed Shot.
 
https://youtu.be/GCaLwOW_tIY?t=992  
https://youtu.be/GCaLwOW_tIY?t=515 
https://youtu.be/2jOKVdoPp7w?t=170

**Comment by Jerrythemagicdog** [comment]
First clip (https://youtu.be/GCaLwOW_tIY?t=992) - no auto-shot enabled at all
Second clip (https://youtu.be/GCaLwOW_tIY?t=515) - chains Steady Shot right after, no auto-shot enabled again
Third clip (https://youtu.be/2jOKVdoPp7w?t=170) - Steady Shot queued when Aimed Shot is still being casted.

Aimed Shot currently also has the same attribute (client data) that Steady Shot has which allows it to not reset Auto-Shot.
This however seems to be wrong as proven here:
https://www.youtube.com/watch?v=VhCI3DDvGGU&feature=youtu.be&t=877

**Comment by Jerrythemagicdog** [comment]
Fixed with '85fb7715d6f05d32720d3e65ad64e60c1966c6a5' (core)
