### ISSUE TITLE
[Hunter] Pet auras are saved on death and reapplied on pet revive

### ISSUE THREAD

**Issue by networm555** [SunstriderEmu/BugTracker#1828]
After pet resurrection it automatically cast bestial wrath sometimes. Sometimes pet resummons with debuff (in my case it was parasites in arca). Happened 4 times in arcatraz hc.  No idea what triggered it.
What we have:
1. Ressurrect pet spell auto triggering bestial wrath after pet appears(probably he appears already with buffand its triggers cast somehow)
2. Pet resummons and resurrects with dangerous debuffs.

**Comment by Jerrythemagicdog** [comment]
Pets buff and debuffs are currently saved when a player uses Dismiss Pet.

**Comment by networm555** [comment]
I didnt dismissed. i resurrected and it layed parasites and next time casted beastial wrath(on me and my pet).

**Comment by Varanak** [comment]
I have noticed that if you die while you were under the effects of Bestial Wrath, when you resurrect the hunter and pet will both still be under the effects of Bestial Wrath for the remaining time left from when you died. I have not ever seen a Bestial Wrath be "popped"(triggering a CD) from pet related actions. 

Related to what Jerry mentions about Dismiss Pet, Bestial Wrath is being saved and is currently incorrectly persisting through death for the remaining time left from before death.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by z5n** [comment]
issue has been since fixed
