### ISSUE TITLE
[Arcatraz] Dalliah the Doomsayer interrupts her Whirlwind

### ISSUE THREAD

**Issue by networm555** [SunstriderEmu/BugTracker#1829]
Whirlwind boss. You should not be able to kick whirlwind. Only heal.(whole point of encounter is to force melee away and then cast heal right after whirl.)
Charge boss. Fire voidzone after charge appears incorrectly. It should appear in line of his charge. Now it appears only where charge was casted.

**Comment by Jerrythemagicdog** [comment]
Thanks!
Whirlwind is not interruptible, she seems to interrupt herself sometimes, maybe due to the Double Attack proc she has.

The second one is indeed a bug

**Comment by Jerrythemagicdog** [comment]
Fixed the charge in da0b0d7905d9bf946cb300258f654fa5a823d7b9 (scripts)

**Comment by Jerrythemagicdog** [comment]
Whirlwind breaking fixed after next restart.
