### ISSUE TITLE
[Hunter] Traps lol

### ISSUE THREAD

**Issue by networm555** [SunstriderEmu/BugTracker#1830]
I cant trap anything when target out of combat. Trap just disappears. 
How to reproduce : place a trap in place where patrol will pass.

**Comment by Jerrythemagicdog** [comment]
Tried with your reproduce steps, trap worked as expected, must be something else going on.

**Comment by networm555** [comment]
It appeared on consortium packs in arca. There are patrol and stationary pack. i tried to place a trap at patrol route. Trap triggered mob that i already trapped before with distract pull.
