### ISSUE TITLE
[Mechanic] Shadowstep when back against edge

### ISSUE THREAD

**Issue by SuddenDeath** [SunstriderEmu/BugTracker#1832]
**Describe the bug**
Rogues should only land inside of you if you've got back against a wall or something similar, when it's against an edge they should simply fall down.

**To Reproduce**
https://streamable.com/yrc2r

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by hufsa** [comment]
Did something, please test how it works after next restart.

**Comment by kelno** [comment]
Updated again
