### ISSUE TITLE
[Quest] Low drop rate quest item list

### ISSUE THREAD

**Issue by Shmilowitz** [SunstriderEmu/BugTracker#1833]
* __Withered Flesh__ in Zangarmarsh seems to have really low drop rate. Killed about 15 of each as alliance and only got 1/5

* __Umgrafen Eel Filets__ has about 33% drop rate in my small sample size as alliance. Not sure if this is increased by alliance perks or correct drop rates.

**Comment by Jerrythemagicdog** [comment]
All quests have double the normal drop rate for Alliance with some exceptions which get special treatment.
