### ISSUE TITLE
Dire Maul: North gate uninteractable.

### ISSUE THREAD

**Issue by frastsytt** [SunstriderEmu/BugTracker#1834]
**Describe the bug**
In DMN the first closed gate is supposed to be interactable with and opened with a key. It's just a solid object rn. Killing the boss doesn't open the gate either.

**To Reproduce**
1. Go DMN
2. Loot Courtyard key from the box.
3. Approach door and realise "what the fuck, I can't open it".

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://classic.wowhead.com/item=18266/gordok-courtyard-key

**Expected behavior**
You get the key from the box, open the gate with it. (Killing the boss is optional)

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by filipele0** [comment]
ye i checked it now too and those doors can't be opened, but they should. Can't interact with them so can't complete dungeon.

i hope too They gonna fix it, cheers

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1111
