### ISSUE TITLE
Scorch debuff doesn't go up on hit  sometimes with 3/3 Improved talent

### ISSUE THREAD

**Issue by becike84** [SunstriderEmu/BugTracker#1835]
Hi there.  It happen like 5-10% chance or smth like that, the Improved Scorch doesn't add bonus stack on hit, or even when you have 5/5 on dummy and trying to "refresh it before the 5 stack debuff expires, you get the spel hit, but doesn't refresh, so not applying the debuff.

best regards.

B.

**Comment by Rettiy** [comment]
Possibly a resist of one component just like it happens for example on Frost Shock where you can resist the Slow Effect while the damage goes in and vice versa?
