### ISSUE TITLE
 [Graverobbers] [Quest]

### ISSUE THREAD

**Issue by testling1** [SunstriderEmu/BugTracker#1836]
**Describe the bug**
 [Embalming Ichor] for [Quest] [Graverobbers] drop rate is way too low. Getting maybe 1 every 20 mobs I kill.

 [Graverobbers]

**To Reproduce**
Do the quest.
https://classic.wowhead.com/item=2834/embalming-ichor

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
Droprate should be way higher.

**Additional context**
More in general, mobs don't stick to you a long time (no leash). Even with dots up they randomly reset.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart
