### ISSUE TITLE
[Quest] City of Light

### ISSUE THREAD

**Issue by Tyrannize999** [SunstriderEmu/BugTracker#1837]
**Describe the bug**
After we reached the scryer part of the walking, the guardian just disappear.

**To Reproduce**
1. Talk to Haggard War Veteran to get pre-quest 'A'dal'.
2. Talk to A'dal and turn in quest.
3. Talk to Khadgar and accept quest 'City of Light'.
4. Follow the guard all the way until Scryer and it will disappear.

**Expected behavior**
NPC should follow a set path around Shattrath than you can finish the quest.

**Additional context**
Important quest for choosing a side.

![WoWScrnShot_020920_112158](https://user-images.githubusercontent.com/60829714/74100453-68156480-4b2f-11ea-9fee-46f7302db2dd.jpg)

**Source**
https://db.excalibur.ws/

**IDs**
[Quest] City of Light (10211)
[Quest] A'dal (10210)
[NPC] Khadgar's Servant (19685)
[NPC] Khadgar (18166)
[NPC] A'dal (18481)
[NPC] Haggard War Veteran (19684)

**Comment by hufsa** [comment]
Thanks!

**Comment by Jerrythemagicdog** [comment]
Thanks, most likely fixed with next restart!

**Comment by hufsa** [comment]
Not fixed

**Comment by Jerrythemagicdog** [comment]
Thanks! Fixed with next restart.
