### ISSUE TITLE
[Quest] Escape from Umbrafen

### ISSUE THREAD

**Issue by Tyrannize999** [SunstriderEmu/BugTracker#1838]
**Describe the bug**
We are clearing the mobs around her tent and we starting the escort quest. She says: "Looks like we won't get away so easily. Get ready!" After this one wave from Umbrafen mobs are summoned. When we kill these mobs, she should be run to home but she is just walking slowly. And there is no more incoming wave until Cenarion refuge but there should be 1 more.

**To Reproduce**
1. Talk to Kayra Longmane to get quest 'Escape from Umbrafen'.
2. Kill the mobs outside (if there any left)
3. She starts walking (instead of running)
4. First wave is incoming
5. Walking until Cenarion Refuge ( no more wave, should be one more)

**Expected behavior**
She runs instead of walks. She takes a direct route to safety instead of meandering. She heals you and tries to help in combat. She will stop about 2 times for new mobs that will spawn cause of the quest.(Once at begin and once at half way).

**Source**
https://db.excalibur.ws/

**IDs**
[Quest] Escape from Umbrafen (9752)
[NPC] Kayra Longmane (17969)
[NPC] Ysiel Windsinger <Expedition Leader> (17841)

**Comment by beraus** [comment]
She should start running only after "Let's keep moving. We're not safe here!" (this line is missing also). 
Second wave is not spawning ([location](http://prntscr.com/u6jta9)). Quest credit works as it should. 
---
[video ](https://www.youtube.com/watch?v=hdaMvcpOt6Q)

**Comment by z5n** [comment]
unable to reproduce, issue has likely since been fixed
