### ISSUE TITLE
[Quest] Bonechewer Blood

### ISSUE THREAD

**Issue by Tyrannize999** [SunstriderEmu/BugTracker#1840]
A drop rate is very low for this quest. I killed around 60 mobs and I've got only 7 blood. 

**Expected behavior**
There are 4 mobs who can drop this item. The drop rate is around 80% so after 2 or 3 mobs there should be at least 1 blood drop.

**Source**
https://db.excalibur.ws/

**IDs**
[Quest] Bonechewer Blood (10450)
[Item] Bonechewer Blood (30327)
[NPC] Bonechewer Mutant (16876)
[NPC] Bonechewer Raider (16925)
[NPC] Bonechewer Scavenger (18952)
[NPC] Bonechewer Evoker (19701)

**Comment by Jerrythemagicdog** [comment]
Thanks for the report.
The drop rates are consistent with https://www.wowhead.com/item=30327/bonechewer-blood
We don't accept other private servers as source of information.
