### ISSUE TITLE
Demoralizing shout does not generate aggro

### ISSUE THREAD

**Issue by Tyrannize999** [SunstriderEmu/BugTracker#1841]
**Describe the bug**
Warrior's Demoralizing Shout should be generate a minimal threat, but it does not.

**To Reproduce**
1. Do body pull for 2-3 mobs
2.  Use Demoralizing Shout
3. You have a little threat in all mobs

**Expected behavior**
If anyone do body pull accidentally than you can aggro them on yourself if you casting Demoralizing shout. Not much threat but more than nothing and you don't have to use your aoe taunt.

**Screenshots/videos**
![WoWScrnShot_020920_174140](https://user-images.githubusercontent.com/60829714/74106599-99f6ed00-4b68-11ea-9f1e-6e7da3146281.jpg)

**Comment by Jerrythemagicdog** [comment]
Max rank of Demoralizing Shout (25203) awards 56 threat.

**Comment by kelno** [comment]
Omen does not show correct data, the server still does it
