### ISSUE TITLE
Hunter Pet abilities not autocasting correctly

### ISSUE THREAD

**Issue by endlesstbc** [SunstriderEmu/BugTracker#1842]
**Describe the bug**
Ravager pet trained with gore, bite, and dash. All on auto cast.

**To Reproduce**
1. Put gore bite and dash on auto cast on the pet bar.
2. When dash or bite is cast, gore no longer auto cast until the cooldown of dash or bite over.
3. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

The pet should auto cast and spam on cooldown the gore ability after using dash or bite even when those abilities are on cooldown.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Related: https://github.com/SunstriderEmu/BugTracker/issues/1548

**Comment by kelno** [comment]
I can't reproduce this, I've tried to get the same setup with a ravager with those 3 spells.
gore is correctly spammed, so much that bite is never used since gore is 25 focus points and bite is 35

**Comment by artieau** [comment]
Working correctly
