### ISSUE TITLE
Fire elemental mob immune to nature damage

### ISSUE THREAD

**Issue by hppy59** [SunstriderEmu/BugTracker#1845]
The fire elementals @ Elemental Plateau in Nagrand are immune to nature damage from Lightning Bolt, Lightning Chain and Earthshock

**Comment by networm555** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1545

**Comment by Sheikthecatman** [comment]
Thanks! 
Issue is fixed in cd758f9bb091ef32020012b9ce33968f5e87d3b5(scripts)
