### ISSUE TITLE
[Mage] Ignite -wrong damage calculating  

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1846]
Tailent : 
http://tbc.cavernoftime.com/spell=12848  
https://wowwiki.fandom.com/wiki/Ignite_(old)?oldid=1163298

Describe the bug:  
Wrong damage calculating : 
https://imgur.com/a/WHdROnw 

To Reproduce: 
There are two possible reasons why this happens. 
1) Same problem like with warriors tailent  "Deep Wounds" (effect not refreshed with every new critical strike and just stacked) 
https://github.com/SunstriderEmu/BugTracker/issues/1326 

2) Or  deal 40% per tick , except 40% per full duration (with 5/5 tailent)

**Comment by Jerrythemagicdog** [comment]
Ignite should be rolling so each new stack adds the damage to the previous stack.
