### ISSUE TITLE
[Item] Idol of the Emerald Queen part 2

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1847]
http://tbc.cavernoftime.com/item=27886
Describe the bug: 
Adding bonus for final direct heal of Lifebloom  
https://imgur.com/a/mVVh0CY  

To Reproduce: 

1. Cast Lifebloom with/without (Idol of the Emerald Queen) 
2. Look at number final direct heal 

How it should work : 
Should add bonus only for 7 sec hot (for final tick different idol)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed some time ago in 'ad24aab56eb1864e59d8f13402628b8c7871bc31' (core)
