### ISSUE TITLE
[Vanilla Item] Force Reactive Disk scales with Spell damage

### ISSUE THREAD

**Issue by AshamedPlayer** [SunstriderEmu/BugTracker#1850]
**Describe the bug**
Blacksmithing item for lvl60 "Force Reactive Disk" scales with spell damage. Tested on paladin with 1k dealing around 300dmg to every mob on proc.

**To Reproduce**
1. Equip given shield
2. Equip spell damage items
3. Fight!

**Expected behavior**
Shield should do stated amount of damage without extra scaling from spell damage.

**Proof**
https://classic.wowhead.com/item=18168/force-reactive-disk#comments:id=2710416

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
