### ISSUE TITLE
Player appears to be dead in UI while alive

### ISSUE THREAD

**Issue by AshamedPlayer** [SunstriderEmu/BugTracker#1851]
**Describe the bug**
Players that revived by entering the instance, but haven't got into range of players, keeps the "grayness" of death person while having their health/mana bars showing actual numbers. This happens with standart ui and also with X-perl/ElvUI, so we suppose its a server issue (that we met on other servers in the past).

**Screenshots/videos**
https://clips.twitch.tv/ExquisiteExquisiteCarrotCoolStoryBob

**Additional context**
Does not affect game play, but fix is huge QoL change.

**Comment by kelno** [comment]
Probably fixed with next server update, but need confirmation here!

**Comment by artieau** [comment]
Tested and works fine now.
