### ISSUE TITLE
[Karazhan] Opera Event - The Crone - Tinhead

### ISSUE THREAD

**Issue by AshamedPlayer** [SunstriderEmu/BugTracker#1852]
**Describe the bug**
Tinhead's (one add of The Crone of Opera Event) ability that slows him over time (rusting) is rewritten by other slowing spells.

**Expected behavior**
Slow effect on this mob should not be rewritten by stronger effects - he should be immune to them. Expect for that, there is missing Sunder mechanics mentioned in wowhead comment:
https://www.wowhead.com/npc=17547/tinhead#comments:id=80453

**Screenshots/videos**
https://clips.twitch.tv/BlatantPoliteCocoaCclamChamp

**Comment by Jerrythemagicdog** [comment]
To dev:
Override only happens with Mind Flay.
Not sure about the validity of this wowhead comment, there are also comments saying Frost spells make him rust which are disproven.
