### ISSUE TITLE
[Karazhan] Nightbane is not/late landing.

### ISSUE THREAD

**Issue by AshamedPlayer** [SunstriderEmu/BugTracker#1853]
**Describe the bug**
Three parties yet did not get to fight Nightbane, coz he did not land after being summoned via Urn. All three parties met Nightbane at/after Curator.

**To Reproduce**
1. Summon Nightbane
2. Watch him fly and give up
3. Meet him at/after Curator!

**Screenshots/videos**
https://clips.twitch.tv/BlatantPoliteCocoaCclamChamp

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in 30cbcde4ed2d55f8f078d662daccb032355ce490 (core)
