### ISSUE TITLE
[Karazhan] Netherspite does not reset threat after Banish phase

### ISSUE THREAD

**Issue by AshamedPlayer** [SunstriderEmu/BugTracker#1854]
**Describe the bug**
Netherspite does not reset threat after Banish phase.

**Expected behavior**
Once 30 seconds of Banish phase of Netherspite fight is over, he should reset threat.
Omen usually  does not show that, but it is supposed to happen so 2nd tank can start making threat on him. It is essential part of most popular tactic with 2 tanks stepping out of red beam (and losing guaranteed threat)

https://wowwiki.fandom.com/wiki/Netherspite#Banish_Phase

**Screenshots/videos**
https://clips.twitch.tv/PrettyLaconicPrariedogOSsloth
(Note: Ignore speaking, boss should not be tauntable.)

**Comment by Jerrythemagicdog** [comment]
Thanks! Fixed after your raid (commit 4d6af79c879e1aaa26d0a5461f943138189d7730 scripts)
