### ISSUE TITLE
Mobs don't crit while you sit.

### ISSUE THREAD

**Issue by AshamedPlayer** [SunstriderEmu/BugTracker#1855]
**Describe the bug**
Mobs (tested on Prince and first mobs in Ramparts HC) do not crit when you are sitting - you are even able to avoid dmg at all.

**Expected behavior**
If target is sitting, mobs should crit the target.
Even tho people wanna avoid this from happening, it is tactic for gaining more rage/mana for tanks.

**Additional context**
In PvP it works. While sitting you get hit by a crit every time.

**Comment by NeonicSupersonic** [comment]
Defence and resilence can make characters immune to crits in pve content(altho it should be overwritten by sitting still), sitting for crits works perfectly on my low level test leveling chars.

**Comment by kelno** [comment]
Fixed since
