### ISSUE TITLE
(Draenai Starting zone) Endless murloc spawning

### ISSUE THREAD

**Issue by Lilith-1** [SunstriderEmu/BugTracker#1856]
On the pathway to the next zone for the draenai there is a fishing quest to catch snappers, when you cast the net item it spawns 1 angry murloc and the net has a 0.1 second cooldown allowing you to spam it over and over creating a murloc every time, eventually ending up with tonnes of murlocs stuck inside eachother that oneshot you and other players nearby etc.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed after next restart.
