### ISSUE TITLE
Looting issue

### ISSUE THREAD

**Issue by Oopsee** [SunstriderEmu/BugTracker#1857]
**Describe the bug**

> Not sure exactly what causes it or how to reproduce it but my charecter got stuck in a loot animation (where the kneel on the ground) and now all corpses are unlootable and have grayed out loot icons even when im right next to them

**To Reproduce**

> Not sure how to reproduce it as it was random
> Im just questing in westfall killing defias

**Expected behavior**

> i expected to loot the mob normally

**Screenshots/videos**

**Additional context**

> Relogging seems to fix it but wouldnt hurt to have it fixed

**Comment by InhumanGM** [comment]
Upon attempting to reproduce the issue, I was not able to find any issues. Could you provide more information that could be used to try to reproduce the issue again?
