### ISSUE TITLE
Caster mobs doesnt run to melee if their cast is interupted.

### ISSUE THREAD

**Issue by AWIDIUS** [SunstriderEmu/BugTracker#1860]
![image](https://user-images.githubusercontent.com/45521546/74604296-c658bf00-50bc-11ea-9272-8eeecc48acca.png)

**Comment by AWIDIUS** [comment]
Also these warlocks doesnt spawning succubus by any chance

**Comment by Jerrythemagicdog** [comment]
Thanks! Both issues are fixed after next restart.
