### ISSUE TITLE
Turn in quest bug.

### ISSUE THREAD

**Issue by AWIDIUS** [SunstriderEmu/BugTracker#1861]
When I have full inventory and trying to turn in quest, turn in is denied, which is fine and normal. 
 But when I delete an item from inventory while I have opened quest window with a NPC and I try to turn in again Im not able to, I have to push escape so window will close and then again interract with NPC ![image](https://user-images.githubusercontent.com/45521546/74604450-7d096f00-50be-11ea-9058-c40626c17e86.png)

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by beraus** [comment]
This should be fixed now.

**Comment by AWIDIUS** [comment]
I have already stopped playing due to amount of bugs that were occuring. Keep fixing guys, GL.
