### ISSUE TITLE
Seal Twist Implementation

### ISSUE THREAD

**Issue by Cicinus** [SunstriderEmu/BugTracker#1863]
**Describe the bug**
Seal twisting allows twisting between any 2 seals

**To Reproduce**
Press buttons like normal seal switch

**Expected behavior**
Should only allow seal twist between SoC and any other seal

**Comment by Jerrythemagicdog** [comment]
Thanks for creating an issue, I'll move it here to keep the discussion and feedback in one place: https://github.com/SunstriderEmu/BugTracker/issues/1484
