### ISSUE TITLE
Consecration Partial Resist

### ISSUE THREAD

**Issue by Cicinus** [SunstriderEmu/BugTracker#1864]
**Describe the bug**
Cons Should Never Partial Resist
**To Reproduce**
Press Consecration wait for resist

**Expected behavior**
Application of  hidden cons debuff can resist. It will always do 8 full damage ticks

**Comment by Jerrythemagicdog** [comment]
This was tested on Classic and proven to partially resist, could you provide a source saying it shouldn't partially resist?
