### ISSUE TITLE
Greater Blessing of Kings Buffing Threat

### ISSUE THREAD

**Issue by Cicinus** [SunstriderEmu/BugTracker#1865]
**Describe the bug**
Blessing of Kings and Greater Blessing of Kings should generate threat on cast

**Expected behavior**
Generate Threat per target buffed. 60 Threat per Target Buffed. 114 per target with Righteous Fury
Threat is split among all mobs in combat 

https://us.forums.blizzard.com/en/wow/t/righteous-fury-mechanics-op-paladin-threat-1k-tps/318279

**Comment by Jerrythemagicdog** [comment]
Thanks for the source!

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
