### ISSUE TITLE
You can see players and mobs health in numeric values

### ISSUE THREAD

**Issue by Stevenseagal8** [SunstriderEmu/BugTracker#1868]
**Describe the bug**
As it is right now you can see players and mobs health in numeric values. You are not supposed to be able to do this. 
The only way you should be able to know someones health amount is by being in party with them,

**To Reproduce**
Target a player or a mob then you can see their health in numeric values. 

**Expected behavior**
You are not suppsed to be able to see players health nor mobs health in numeric values. The only way to see players health in numeric values is by being in party with them.

**Screenshots/videos**
Video as proof of how it is supposed to be. There you can only see health as a %
https://www.youtube.com/watch?v=ArS1w1jgKw8&feature=youtu.be&t=3m50s

**Comment by Jerrythemagicdog** [comment]
That's intended, but thanks for the report.
