### ISSUE TITLE
Ursangous, Shadumbra and Sharptalon missing their respective items.

### ISSUE THREAD

**Issue by AWIDIUS** [SunstriderEmu/BugTracker#1869]
Ursangous, Shadumbra and Sharptalon missing their respective items which will start quests.

https://classic.wowhead.com/item=16303/ursangouss-paw
https://classic.wowhead.com/item=16304/shadumbras-head
https://classic.wowhead.com/item=16305/sharptalons-claw

Droprate should be nearly 100%. I've killed all of them, bird twice and no Q item yet. In case of RNG and with over an 85% droprate, there is a 0,0005% of possible chance to not obtaining those ... If I'm lucky enough, then okay. 

EDIT: Killed bird for 3rd time.

**Comment by Jerrythemagicdog** [comment]
All three items require quest The Ashenvale Hunt (https://classic.wowhead.com/quest=6383/the-ashenvale-hunt) to be finished to drop. Is that incorrect?
