### ISSUE TITLE
Mana Tap + Arcane Torrent (bloodelf racial) for Rogue

### ISSUE THREAD

**Issue by emilionez** [SunstriderEmu/BugTracker#1871]
Arcane Torrent is bugged for BloodElf Rogue when is used to restore energy.
When you have 1, 2 or 3 stacks of Mana Tap you can use Arcane Torrent to restore 10 , 20 or 30 energy but doesn't restore.
I tested this on BloodElf Rogue which uses ENERGY but i don't know if this works for the rest of BloodElf classes that use MANA.

**Comment by NeonicSupersonic** [comment]
Mana returns and mana gains from using torrent/tap work correctly for casters

**Comment by woiwoz** [comment]
What's more, why do casters get mana immediately when we cast mana tap on targets? It's a mistake

**Comment by kelno** [comment]
Some changes have been done around this, this should be working now.
(with next server update)
