### ISSUE TITLE
Tooltip damage is wrong on a fresh character

### ISSUE THREAD

**Issue by Xinergie** [SunstriderEmu/BugTracker#1873]
When you do not boost your character, but you legit level a gnome mage from 1, the spelldamage for nearly every spell is wrong. 

Example: Blizzard rank 1 at lvl 20 tooltip says 120dmg over 8 sec. (Tested: 8x 15dmg)
In classic & TBC it should be 200dmg over 8sec.

I was able to succesfully replicate a difference in spelldamage by doing the following:

When you create a gnome mage, R1 fireball tooltip says 14-22 dmg and when you talk to the guard for the boost to lvl 58, your rank 1 fireball in the spellbook will be 16-25. This bug is affecting leveling really hard.

I saw someone streaming a gnome who's blizzard did more damage so I don't know if some trainers are maybe bugged? Me & a friend trained lvl 20 in Ironforge.

**Comment by AWIDIUS** [comment]
Spells are from client side. You might use different client than 2.4.3. or try to download purely Endless TBC, that would be the best option I'd say.

**Comment by kelno** [comment]
As AWIDIUS said this damage shown is only clientside, you always need to confirm it by casting the spells. I don't know why you don't see the correct value in the tooltip though, I see the same issue on my side.

Many spells have a "per level" dmg component, fireball for example has +2.4 dmg on level 58, so the spellbook value after using the Beta Camp manager is correct. Also I tried using a freshly created character and lvl it without the beta camp manager, the tooltip showed the old value but the spell actually did the new damage, so if there is an issue it's only visual.

**Comment by kelno** [comment]
Blizzard dmg indeed is wrong but it's another issue:
-> https://github.com/SunstriderEmu/BugTracker/issues/1875

**Comment by Xinergie** [comment]
FYI I am using the Endless client from scratch, no addons. Blizzard damage is indeed also another issue, but I wouldn't immediately exclude it from having 2 different bugs which affect it.

I'll do some more testing on this later. At work now :)

**Comment by Xinergie** [comment]
I don't agree with the claims of it being only tooltips. The blizzard issue with permafrost for example doesn't only change the tooltip or the spell's damage. It changed both. I'm pretty sure this will also be the case here, where the tooltip reflects the actual output.

**Comment by kelno** [comment]
I tested with the fireball case and the damage was the same even when the tooltip said it was reduced.
But those are two different cases though, the fireball one is about the "dmg per level" component of damage while Blizzard was about a talent wrongly affecting it.

**Comment by Xinergie** [comment]
I just don't understand why you didn't post your observations then. Here is proof:

![rank 1 dmg](https://user-images.githubusercontent.com/61210100/74886439-7574ef00-5378-11ea-8764-5c4a3fa56c0a.png)

35 casts, max damage is 22 and not 25, and you can also see in the combat log that it hits for 14 without resists. (the minimum 9 damage in recount is the minimum with partial resists)

**Comment by Xinergie** [comment]
![image](https://user-images.githubusercontent.com/61210100/74887002-f5e81f80-5379-11ea-8b55-2a14f3ed7f4a.png)
Here are the results when you upgrade to 58 and go naked. It's hitting 24 dmg alot.

**Comment by kelno** [comment]
About the test while lvl 1 -> Why do you expect 25 max dmg? Since the spell should do 14-22
The second one is interesting indeed, I don't know why the tooltip shows 25, from what I could see the damage should be 22+2.4 -> rounded to 24. So either tooltip is wrong, or more likely the wow client formula is slightly different.

**Comment by kelno** [comment]
Fixed that last bug

**Comment by Xinergie** [comment]
At this point I have no idea if you are trolling or something? Can some other dev maybe take a look at this issue? There should NOT be 2 different versions of the tooltip. This is not just an issue for one spell or class. Nearly every class and spell has the issue where they are not getting the right damage on their spells when you level with a new character.

**Comment by kelno** [comment]
I'm so sorry I'll ask for the main dev to come.

Okay main dev here:
- Your proof about wrong damage is off since you're trying to prove that you don't do max 25 dmg... while being lvl 1, where the max damage should be 22 (as per tooltip).
- When lvl 58, the max dmg was 24 for a fireball rank 1, the formula is now fixed and it will be max 25. This is a generic fix, not a per spell fix.
- Actual bug: If I lvl up a char without the beta npc I don't get the correct increase *in the tooltip*, but the spell damage gets increased correctly. That's why this issue is still open.

**Comment by Xinergie** [comment]
Okay thanks for explaining, sorry for the confusion then. I never knew about the per level thingy since all database sites show only one set of values. I automatically made the connection with the Blizzard bug aswell. Thanks for clearing it up and once again my apologies :D

**Comment by Xinergie** [comment]
Okay, compared it to classic client, where it seems to scale much faster. (already at level 2 it goes up 1 max dmg)

Here's a screenshot of level 10 mage on classic: 
![image](https://user-images.githubusercontent.com/61210100/74954234-13ad9700-5403-11ea-9a6c-47381e1d1b80.png)

And here's a level 27 on Endless which still has no scaling:
![image](https://user-images.githubusercontent.com/61210100/74954328-39d33700-5403-11ea-810a-3733e54a71b4.png)

**Comment by hufsa** [comment]
The scaling is the same. But as explained earlier, the tooltip is not updated properly, this is the **bug**. It's only visual.
