### ISSUE TITLE
Totem of the Plains - Not adding bonus healing to lesser healing wave

### ISSUE THREAD

**Issue by lbutler41** [SunstriderEmu/BugTracker#1874]
Totem of the Plains does not add bonus healing to lesser healing wave.

----------------------------------------------------

Link to item:

https://tbc-twinhead.twinstar.cz/?item=25645

----------------------------------------------------

Tested with multiple ranks of lesser healing wave. Successfully tested other relics to make sure the issue was specific to this relic.

**Comment by Jerrythemagicdog** [comment]
Fixed with next restart.
To check the server revision and uptime you can type `.server info` in game.
