### ISSUE TITLE
Permafrost reduces the damage of Blizzard

### ISSUE THREAD

**Issue by hufsa** [SunstriderEmu/BugTracker#1875]
**Describe the bug**
1 point spent in talent Permafrost will reduce the damage of Blizzard by 16%.
2 points reduces damage by 28%.
3 pointe reduces damage by 40%.

**To Reproduce**
1. Get a mage, learn Blizzard rank 1.
2. Spec points into talent Permafrost.
3. Observe modifiers be applied 4(?) times(?) to damage of Blizzard?(?). 

**Expected behavior**
Should not affect the damage of Blizzard at all. The talent should make the mages Chill effects reduce the target's speed by an additional 4/7/10%.

**Comment by kelno** [comment]
Fixed

**Comment by hufsa** [comment]
While we’re at it:
The slow component from Frostbolt rank 1 is 40% by default. With 3/3 permafrost (an additional 10%) the tooltip is updated and says 60%(?).

1 point (+4%) 40->48%. Feels like a ”double” application of mod. Not tested if its actually slowing by correct amount.

**Comment by kelno** [comment]
it's fixed by the same commit

**Comment by hufsa** [comment]
Okay nice. I read the SQL and only saw "Remove Blizzard".

**Comment by kelno** [comment]
Yes that was actually an unintended fix there.
