### ISSUE TITLE
KS imunne

### ISSUE THREAD

**Issue by Akioqq** [SunstriderEmu/BugTracker#1876]
Kidney Sshot after twice Cheap Shot is imunne ! Fixed!

**Comment by Jerrythemagicdog** [comment]
The Diminishing Returns timer is 18 seconds. Could you elaborate a bit on what you mean?

**Comment by Akioqq** [comment]
Hello ! What u mean ???

пт, 31 июля 2020 г. в 8:33, Bareus <notifications@github.com>:
