### ISSUE TITLE
Mobs fleeing mechanic is broken on reset

### ISSUE THREAD

**Issue by Xinergie** [SunstriderEmu/BugTracker#1877]
If you get a specific mob down to low HP, they will start running in fear. If you do not finish them but reset the fight, they will not attack you the next time you attack them. They will just stand still.

**Comment by AWIDIUS** [comment]
Can confirm similar situation, where mob was fleeing away, I died because of second mob and when I got back up, I was casting bolts on mobthat was previously fleeing and it didn't start to attack me. I was completely able to kill that mob without any harm done to me.

**Comment by Caydan** [comment]
I can confirm this too. There is something like `npc->setReactState(PASSIVE)` missing in the assigned combat ai, after the npc entered evade mode

**Comment by kelno** [comment]
Thanks for the research there

**Comment by kelno** [comment]
Seems fixed
