### ISSUE TITLE
General Aggro radius is way too big + Aggro behaviour

### ISSUE THREAD

**Issue by Xinergie** [SunstriderEmu/BugTracker#1879]
The general aggro radius is currently way too big. After leveling on classic WoW 3x to 60, I am doing some level sessions here from level 1 and can't stop noticing how insane the aggro range is.

Same for low lvl content on a 70 char. In SM for example the mobs still aggro from quite a distance compared to classic.

Also for the aggro behaviour: if you pull a mob, they will chainpull other mobs around it. But if you then run with those mobs over another pack, they will not chainpull this next pack.

**Comment by NeonicSupersonic** [comment]
Can you provide some examples, I think aggro range is pixel perfect

**Comment by Xinergie** [comment]
In classic WoW I can for example run with my mage lvl 60 past all mobs in SM Armory up to Herod (without blinking).

The only mobs you can't get past there are the very first 2 mobs (can still blink past without aggro).

On the PTR this is mission impossible. Unless TBC increased all aggro ranges, I'll try to get you guys some better evidence by comparing both clients with the same mobs.

**Comment by Xinergie** [comment]
Here are the comparisons of a level 2 gnome female aggro'ing the lvl 4 trogg in the starter zone tunnel:

ENDLESS distance:
![endless](https://user-images.githubusercontent.com/61210100/74964189-48c1e580-5413-11ea-8751-3d3da816c330.png)

CLASSIC distance:
![classic](https://user-images.githubusercontent.com/61210100/74964200-4e1f3000-5413-11ea-8ba5-133d976e4f88.png)

If screenshot isn't enough proof, here's a 6 sec recording of both tests:
Endless: https://www.youtube.com/watch?v=h8zmiA7leGI
Classic: https://www.youtube.com/watch?v=VaszXoIl4HM

**Comment by Macumbafeh** [comment]
+1

**Comment by EnterLarry** [comment]
This still seems to be an issue.
Easiest place to notice it is in areas where things are supposed to have huge agro ranges to begin with, but it just goes nuts on this server.
Throne of Kil'Jaeden in HFP for example.

Is it intended to be increased for "difficulty"?
