### ISSUE TITLE
(Hunter) Taiming pet quest + abilities

### ISSUE THREAD

**Issue by Plovpenning** [SunstriderEmu/BugTracker#1881]
The first issue that i came across was with the quest for taiming your pet. Here, the issue is that you can tame the pet right after you engaged the taiming process by cancelling the process. 
How this works: Taming bar in the process should run all the way down and then you have tamed it. 

A second issue i came across is that Feed Pet and Revive Pet was already available in the spellbook before you handed in the last quest in the taiming chain quest, granting you the ability of Feed Pet and Revive Pet. These abilities removed when you picked the last quest. 
How it should work: Hand in the last quest in the taiming chain to gain the mentioned abilities 

![WoWScrnShot_022020_092523](https://user-images.githubusercontent.com/61269991/74917280-91ec4800-53c7-11ea-952f-a698cc89ae66.jpg)
![WoWScrnShot_022020_092525](https://user-images.githubusercontent.com/61269991/74917285-931d7500-53c7-11ea-823c-6e130eec798a.jpg)
![WoWScrnShot_022020_092526](https://user-images.githubusercontent.com/61269991/74917291-94e73880-53c7-11ea-8bfe-ffe5cfee0e60.jpg)
![WoWScrnShot_022020_092617](https://user-images.githubusercontent.com/61269991/74917604-0cb56300-53c8-11ea-8a31-9cbcc6a9f16e.jpg)
![WoWScrnShot_022020_092631](https://user-images.githubusercontent.com/61269991/74917612-0f17bd00-53c8-11ea-9ab1-24a96f68f1a1.jpg)
![WoWScrnShot_022020_092643](https://user-images.githubusercontent.com/61269991/74917639-1a6ae880-53c8-11ea-93f6-39b6d1aff7cc.jpg)
![WoWScrnShot_022020_094723](https://user-images.githubusercontent.com/61269991/74917641-1c34ac00-53c8-11ea-9b27-470a6b0404c9.jpg)

I hope the many screenshots and the description is helpful to fix these issues :). 

Best wishes
Plovpenning

**Comment by z5n** [comment]
unable to reproduce
