### ISSUE TITLE
Diminishing return on reflected spells

### ISSUE THREAD

**Issue by Himeyo** [SunstriderEmu/BugTracker#1882]
Reflected spell don't take in consideration the DR.

Example : 

Player 1 (Druid) casts a cyclone on player 3 (Druid too), no DR it lasts ~6 seconds.
Player 3 (Druid) casts a cyclone on player 2 (Warrior) and get reflected, still no DR, it lasts ~6 seconds too.

The issue is actually running with every reflected spells having DR. ( cyclone, sheep, lock fear )

**Comment by Dominionpvp** [comment]
combat logs? screenshots? if tickets don't have provided documentation then they should just be closed because its a waste of time for developers and ticket managers to work through. Make it easier for the team to fix issues not complicate it more.

**Comment by Himeyo** [comment]
Well i'd like to bring screenshots but as long as it happen only in arena, it's kinda hard to screen anything. This is to my sense a big issue and it shouldn't be ignored.

**Comment by kelno** [comment]
Fixed with next server update
