### ISSUE TITLE
Deeprun Tram - 1 train instead of 2 trains + suddenly dissapears getting off  

### ISSUE THREAD

**Issue by Plovpenning** [SunstriderEmu/BugTracker#1883]
There is only 1 train within the Deeprun Tram that appears. Once you get off on one platform either i SW or IF, the train will suddenly  vanish and most likely spawn back to the other location so ex. if i take the train from SW to IF and get off, the train will dissapear and appear on the other platform approx. 1½-2 min later. 

How should it work: There is suppose to be 2 trains, 1 for each platform.
 
This is mostly an annoyance rather than gamebreaking. 
The last screenshot you can see is my pet on the train just as it dissapears. 

![WoWScrnShot_022020_113445](https://user-images.githubusercontent.com/61269991/74926534-55741880-53d6-11ea-955b-3d433fb76820.jpg)
![WoWScrnShot_022020_113448](https://user-images.githubusercontent.com/61269991/74926540-573ddc00-53d6-11ea-8f96-a928fbe89ac6.jpg)

**Comment by SUN-Leekie** [comment]
It this still happening?

**Comment by WVLeeuw** [comment]
Yes.

**Comment by kelno** [comment]
https://github.com/kelno/sunstrider/commit/7c7b8a5e7e0a19cce7b59e4c8e615d9a4d6d8db4
