### ISSUE TITLE
[NPC] Stonescythe Whelp, Stonescythe Alpha

### ISSUE THREAD

**Issue by Tyrannize999** [SunstriderEmu/BugTracker#1884]
**Describe the bug**
After the mobs are using their spell "Desperate Defense" and the time of this shield is over, they just standing, they are not attacking you. And they should be enrage when you hit them when they have this defense on themselves, but there is no enrage only after the shield expired.

**To Reproduce**
1. Attack the mob
2. At 50% he is using his spell "Desperate Defense", if you hit during the shield, they won't enrage
3. After this shield is over, he just standing, doesn't follow or attack you, random enrage

**Expected behavior**
After attacking him, at around 50% they will use their spell "Desperate Defense". It is a shield and they will absorb your damage . If you are attacking them during this shield, they will enrage ("Desperate Rage") and they will hit harder and faster.

**Screenshots/videos**
![WoWScrnShot_022020_114318](https://user-images.githubusercontent.com/60829714/74926913-f95dc400-53d6-11ea-9736-4f11cb735378.jpg)
![WoWScrnShot_022020_114323](https://user-images.githubusercontent.com/60829714/74926916-fb278780-53d6-11ea-8c6c-d128d176e0a3.jpg)

**Source**
https://www.wowhead.com/

**IDs**
[NPC] Stonescythe Whelp (16927)
[NPC] Stonescythe Alpha (16929)
[SPELL] Desperate Defense (33896)
[SPELL] Desperate Rage (33898)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in https://github.com/kelno/sunstrider-scripts/commit/e2a2af4a92c8b200c5490ad4c8fc14c842631603
