### ISSUE TITLE
ninjas

### ISSUE THREAD

**Issue by ghost** [SunstriderEmu/BugTracker#1885]
1) can gouge from behind
2) deadly throw can be used to interrupt multiple times w/o losing combo pts (vs a mage with imp.blink + arctic winds, this occurs quite often)
3) blind is sometimes not removed/immuned by iceblock. happened twice in the last two days. not sure in what order were the abilities used, but this can be easily tested.

**Comment by Dominionpvp** [comment]
if a ticket doesn't have pictured proof or documentation, then just close it. It's dumb to have these tickets where people state issues and have no proof or don't update their ticket with supporting evidence. waste of time
