### ISSUE TITLE
Holy Shock crits do not give proper amount of mana on crit (Illumination talent)

### ISSUE THREAD

**Issue by Felynda** [SunstriderEmu/BugTracker#1886]
**Describe the bug**
Holy Shock / Illumination bugged
Using max rank Holy Shock gives the mana of rank 1 HS:
![image](https://user-images.githubusercontent.com/45050227/74979750-87659900-542f-11ea-8d09-9bdce7cc55ed.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed after next restart.
