### ISSUE TITLE
Quest Vision Guide doesn't currently work.

### ISSUE THREAD

**Issue by Hustler495** [SunstriderEmu/BugTracker#1889]
Description:

Quest Vision Guide doesn't currently work.

Current behaviour:

Accepted quest, used the quest item and was flown to the location and the "Final Thunderlord Artifact" was not discovered.

Expected behaviour:

For the quest requirement "Final Thunderlord Artifact" be flagged as completed.

Steps to reproduce the problem:

Use quest item and have it fly to the location and not complete quest.
Quest item: http://db.hellfire-tbc.com/?item=30481

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed after next restart.
