### ISSUE TITLE
[Paladin] [Talent] Reckoning not proccing properly

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#1890]
**Describe the bug**
The Paladin Talent **Reckoning** http://tbc.cavernoftime.com/spell=20182 does not proc from Dot ticks.

The wording on this talent is very similar to Nature's Guardian and we all know that Nature's Guardian procs on literally any damage taken, including dots etc., that's why I assume the same should apply to Reckoning.

More evidence below.

**To Reproduce**
1. Create Paladin and spec into Reckoning
2. Use Dots on the Paladin
3. Notice Reckoning never procs
(I personally used Lock and dotted for over 2 minutes with no Reckoning procs, Drain Life included)

**Expected behavior**
Reckoning should have a chance to proc on any kind of damage taken, including dots (and even campfire):

_"Reckoning is triggered by any damage, including spells, melee attacks, ranged attacks, and environmental effects, such as campfire damage."_
https://wowwiki.fandom.com/wiki/Reckoning_(old)

_"It's an awesome talent for bosses that like to throw in a lot of magic damage, or cause dots or whatever. Reckoning can proc from any kind of damage, meaning every tick of a bleed and a dot."_
https://www.wowhead.com/forums&topic=24643 comment by user Dobbel

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed after next restart.
