### ISSUE TITLE
Shaman Call to Earth Quest

### ISSUE THREAD

**Issue by Kultarak** [SunstriderEmu/BugTracker#1891]
you cant interact with the Elemental for the Quest Call to Earth

**Comment by InhumanGM** [comment]
In order to replicate this issue, we need more information. Please follow the bug report template that way we can properly investigate this issue.

> **Describe the bug**
> 
> **To Reproduce**
> 
> 1. Cast X on target affected by ...
> 
> Item: https://wowhead.com?item=
> Quest: https://wowhead.com?quest=
> Spell: https://wowhead.com?spell=
> 
> **Expected behavior**
> 
> **Screenshots/videos**
> 
> **Additional context**
