### ISSUE TITLE
Paladins BoP is bugged

### ISSUE THREAD

**Issue by oliverhusted** [SunstriderEmu/BugTracker#1892]
I've come to notice that paladins can't use "Blessing of Protection" during stuns on the server endless.gg.

Paladins should be able to use their abillity "Blessing of Protection" during stuns. It works as a bubble for whenever "Divine Shield" is on cooldown. This is how it worked throughout every expansion on retail.

Here is a movie where "Blessing of Protection" is being used while in sap to remove to debuff. (6min 20seconds in)

https://www.youtube.com/watch?v=OveRM0T6_ls

Here is another video from the old server "Arena-Tournament" where the paladin uses BoP while being incapped aka. sapped. (9min 15 seconds in)

https://www.youtube.com/watch?v=ZgZ2mKca-Mk

Best regards

**Comment by Rettiy** [comment]
#1740 Might be related, if it's incorrectly implemented.

**Comment by AWIDIUS** [comment]
You should be able to use it on yourself but not on anybody else while you are in stun I think.

**Comment by Ibuprofeno** [comment]
> 
> 
> You should be able to use it on yourself but not on anybody else while you are in stun I think.

This.
