### ISSUE TITLE
Quest: Prisoners of the Grimtotems

### ISSUE THREAD

**Issue by Carneyy** [SunstriderEmu/BugTracker#1893]
**Describe the bug**
Super low drop rate of keys (https://db.excalibur.ws/?item=33061)  needed to have quest (https://db.excalibur.ws/?quest=11145) done compare (if not 0) to any other quest drops. You should also check if quest drop rate of notes(https://db.excalibur.ws/?item=33050) from other quest (https://db.excalibur.ws/?quest=11144) in same zone is also correct - I don't tested it.

**To Reproduce**
1. Take quest
2.  Kill mobs to check how low drop is.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by Jerrythemagicdog** [comment]
The drop rate is 40%.
