### ISSUE TITLE
{WARRIOR} {TALENT} {SWORD SPECIALIZATION}

### ISSUE THREAD

**Issue by bloodwindz** [SunstriderEmu/BugTracker#1894]
**Describe the bug**
Check this link it contains proof  https://github.com/Atlantiss/NetherwingBugtracker/issues/1365
in live netherwing and in classic  warr are the same (on first days of netherwing) sword spec proc from all attacks chain proc with chance on hit procs , proc off sunder thunderclap rend ticks hamstring etc and chain proc with chance on hit like wf with swordspec does  same worked in netherwing and it does in classic  and proof show it was like that back in the day in tbc
**To Reproduce**
try to use recount and count the sword specs from where it proc from  does it proc from rend or sunder etc etc?
1. Cast X on target affected by ...
2. 
3. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
sword spec proc from trinkets and weapon procs chance on hit this can potentialy trigger  an other sword spec and sword spec can trigger chance on hit procs , like hamstring sword spec >chance on hit>sword spec     or hamstring  >chance on hit >sword spec>chance on hit  also  it procs from the dots of rend and aplication of rend   aplication of sunder and hamstring  and even thunderclap
**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.
https://github.com/Atlantiss/NetherwingBugtracker/issues/1365 everything is here rest on classic test them it dint chance on tbc the swifty video is proof
**Additional context**

**Comment by Jerrythemagicdog** [comment]
Sword proc has a chance to proc on melee auto attacks or on melee abilities. Periodic ticks of Rend or trinket procs are not included and there is no evidence of that anywhere to support it. The Swifty video does not support that either. Thunder Clap has no requirement for a melee weapon to be equipped and is not a melee ability.

**Comment by bloodwindz** [comment]
go in classic and netherwing and test it the code support it  thunderclap is melee damage  any offensive abiltity that does or does not damage  proc it

**Comment by NeonicSupersonic** [comment]
Rend tick isnt even an attack, how it supposed to proc anything attack related? How do you even imagine it?

**Comment by Fettbergg** [comment]
You forgot to mention that mounting up should also generate sword procs.

**Comment by bloodwindz** [comment]
go check it in classic its same mechanics  you  dont know how warrior work yet you claim its not a attack is same attack type as sunder is  and  did you see the video  ret aura and thorns also proc it  are those melee attacks ?  they are  magic   also enchants in classic proc it and procs from trinkets or wep chance on hit  not buff  get your clues before posting ##@#@#Q

**Comment by NeonicSupersonic** [comment]
So far you proven nothing but complete lack of understanding of most basic and obvious aspects of the game.

Can you provide any proof of your claims? Mb a combat log with rend procing xtra attack?

**Comment by bloodwindz** [comment]
i can  but i wont bother ans so far you proven also  not able  to me why it proc from ret aura since ret aura its a magical  ? and non related to class buff? why it does proc from sunder? aplication?

**Comment by NeonicSupersonic** [comment]
Still waiting for at least 1 proof

**Comment by Dominionpvp** [comment]
close this ticket please. nonsense.
