### ISSUE TITLE
Nature's Swiftness with Ghost wolf

### ISSUE THREAD

**Issue by Ennelix44** [SunstriderEmu/BugTracker#1895]
Nature's Swiftness doesn't allow Ghost wolf to be casted instantly. 
Pretty self explanatory.

**Comment by woiwoz** [comment]
thanks
fixd

**Comment by Rettiy** [comment]
I hope that won't cause the Wolf to absorb the NS in case it's talented 2/2, because that was originally the reason why it was implemented and it's far more important than this stuff.

**Comment by InhumanGM** [comment]
It appears that this issue has been fixed, as upon attempting to reproduce the issue, everything works how it is supposed to.
