### ISSUE TITLE
Darkness - shadow priest

### ISSUE THREAD

**Issue by mtebry** [SunstriderEmu/BugTracker#1896]
**Describe the bug**
The Darkness in talent tree within shadow priest should give 10% increased shadow spell damage. Does not effect spell bonus damage

**To Reproduce**
1. should affect the total amount of spell bonus damage in shadow

**Comment by Jerrythemagicdog** [comment]
Thanks. Indeed the spell damage is not updated in the character sheet but the damage of spells is.

**Comment by mtebry** [comment]
True, after reseting and rebuilding same talent points, all spells takes effect from 'Darkness' except it does not get updated in the character sheet, which is not a big deal but hopefully its fixed for visual clearance.
