### ISSUE TITLE
Hunter Pet Quest

### ISSUE THREAD

**Issue by Bewxd** [SunstriderEmu/BugTracker#1897]
There is no hunter pet quest available at Thotar for level 10 orcs and trolls. At level 10 Orc and trolls should be able to pick up their Hunter pet taming quest from Thotar. The quest's name is The path of the hunter.

**Comment by artieau** [comment]
The quest is called the Hunter's Path and it starts from the Hunter trainer in your capital city.
Org, Darn etc.
That trainer sends you back to the lower level hunter trainer, for example Thotar.

Working correctly.
