### ISSUE TITLE
Galaen's Amulet doesn't drop at it's increased rates for alliance.

### ISSUE THREAD

**Issue by AWIDIUS** [SunstriderEmu/BugTracker#1898]
![image](https://user-images.githubusercontent.com/45521546/75091012-1f1ad280-5569-11ea-9941-333525f8c0ed.png)

https://db.excalibur.ws/?item=23873
https://www.wowhead.com/item=23873/galaens-amulet
There it claim to have 5% droprate, which is fine on normal servers, even though aliance have their Q items droprate increased I've killed 35 of these blood elves and still no Amulet.

**Comment by AWIDIUS** [comment]
![image](https://user-images.githubusercontent.com/45521546/75091186-c9dfc080-556a-11ea-8754-14d79211e02f.png)

Got it after 54 mobs. At 5% droprate.

**Comment by Jerrythemagicdog** [comment]
Thanks, increased the drop chance to 30 by default.
