### ISSUE TITLE
Barrens Kodos Falling Through World

### ISSUE THREAD

**Issue by najadoa** [SunstriderEmu/BugTracker#1900]
The passive kodos that walk around in the barrens fall through the world.

**Comment by InhumanGM** [comment]
In order to replicate this issue, we need more information. Please follow the bug report template that way we can properly reproduce and investigate this issue.

> **Describe the bug**
> 
> **To Reproduce**
> 
> 1. Cast X on target affected by ...
> 
> Item: https://wowhead.com?item=
> Quest: https://wowhead.com?quest=
> Spell: https://wowhead.com?spell=
> 
> **Expected behavior**
> 
> **Screenshots/videos**
> 
> **Additional context**
