### ISSUE TITLE
[Karazhan] Mana Feeder(s) are immune to physical damage

### ISSUE THREAD

**Issue by juansfb** [SunstriderEmu/BugTracker#1902]
**Describe the bug**
Mana Feeders in Karazhan, in the room after Curator, are immune to all kinds of damage. 

**To Reproduce**
1. Engage any Mana Feeder and try different damage sources.

ID: [16491](https://www.wowhead.com/npc=16491/mana-feeder)

**Expected behavior**
Mana feeders should be immune to magic but NOT melee (physical) damage.

**Sources**
https://wowwiki.fandom.com/wiki/Mana_Feeder
https://www.wowhead.com/npc=16491/mana-feeder#comments

**Comment by Jerrythemagicdog** [comment]
Oops!
Fixed with next restart.
