### ISSUE TITLE
Private Thorsen

### ISSUE THREAD

**Issue by AWIDIUS** [SunstriderEmu/BugTracker#1903]
Private Thorsen doesn't give me any quest even when he should. I can't turn in quest named Supplies for Private Thorsen aswell. He just do his RP down to the jungle and actually die to 2 Kurzens, then he respawns and he do his RP again. Once I helped him with 2 Kurzens and he didnt actually die, he just went straight path back to camp, no road, just through texture. Now he seems to not do his RP, stays still, probably bugged, cant turn or pick up quests.

**Comment by AWIDIUS** [comment]
Please, make it work. https://db.excalibur.ws/?quest=328
This is quest in the chain from Private Thorsen and I would need that wep for leveling on live once it drops.

**Comment by Jerrythemagicdog** [comment]
He does turn into a quest giver once he reaches the camp after he's saved.

**Comment by AWIDIUS** [comment]
I've saved him and couldn't pick up quest either.

**Comment by AWIDIUS** [comment]
Tested it now and it seems to work
