### ISSUE TITLE
[Item] Libram of Divine Judgement

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#1904]
**Describe the bug**
Libram of Divine Judgement http://tbc.cavernoftime.com/item=33503 procs off Judgement of Blood. Did not test other seals.

**To Reproduce**
1. Cast Seal of Blood
2. Equip the Libram
3. Cast Judgement
4. Notice a chance to proc from Judgement of Blood

**Expected behavior**
Libram is exclusive to Seal of Command (any rank of SoC).

**Screenshots/videos**
https://imgur.com/a/uAdhw47 and the buff "Crusader's Command"

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
