### ISSUE TITLE
Mobs fleeing in a fear.

### ISSUE THREAD

**Issue by AWIDIUS** [SunstriderEmu/BugTracker#1905]
If you slow mob by any spell and you down mob to certain percentages of HP so its starts fleeing away to find help. When slow ends and mob still fleeing away, mob wont gain its original movement speed.

Example : I slow mob with frostshock by 50%, mobs movement speed is reduced from 400 to 200, once it starts to flee away and frostshock effects ends, mob is still running away like its slowed.

**Comment by Jerrythemagicdog** [comment]
Creatures use 0.66% of their initial speed while running away in fear so they are always running a bit slower than their max speed.

**Comment by AWIDIUS** [comment]
Well, I will record that one for you once I will come back home :)

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by beraus** [comment]
This issue should be fixed now.
