### ISSUE TITLE
Mistvale Giblets alliance drop chance

### ISSUE THREAD

**Issue by AWIDIUS** [SunstriderEmu/BugTracker#1906]
![image](https://user-images.githubusercontent.com/45521546/75112435-1d720d00-5644-11ea-9a61-a8f1a4820e18.png)
Droprate of Mistvale Giblets for alliance is quite poor, I was testing this on horde character aswell and I might had some RNG floating around me, but I got it faster than on alliance. On screenshot there is all loot (on the bottom line) from these Gorillas. Also I looked into 2 databases and percetages are like this.

https://db.excalibur.ws/?item=3919
https://www.wowhead.com/item=3919/mistvale-giblets

Also :

From ThottbotBy fusioncon on 2006/11/04 (Patch 1.12.1)
Subject: "thott reported drop rates"
drop rates for quest items are always going to be off from reality, because thott is counting all kills of the mobs, and the drops of the quest items only happen for those who have the quests.

if the mob is a particularly popular grinding mob, the drop rates will appear much lower.

**Comment by AWIDIUS** [comment]
Also, we dont know how much are Q items drop chances boosted.

**Comment by Jerrythemagicdog** [comment]
Drop rates are doubled for Alliance of their default value.
