### ISSUE TITLE
Mage quest Investigate the Blue Recluse is bugged

### ISSUE THREAD

**Issue by Xinergie** [SunstriderEmu/BugTracker#1907]
You currently can't complete the mage quest '**Investigate the Blue Recluse**'

![image](https://user-images.githubusercontent.com/61210100/75112496-a5581700-5644-11ea-9ef9-b541b7ba32be.png)

Once you reveal them and bring the Rift spawn mobs down to 0 hp they don't get stunned, but instead it says 
_Rift Spawn escapes into the void!_ and then they disappear

Then when you use the quest item to reveal them again, they are friendly and just follow you everywhere. 

**Expected behavior:**
They should get stunned at 0 hp, at which point you can use the other quest item to extract their spirit:

![image](https://user-images.githubusercontent.com/61210100/75112537-29120380-5645-11ea-8035-ce5efb81be88.png)

**Comment by Xinergie** [comment]
Low priority bug

**Comment by Sheikthecatman** [comment]
Thanks!
Testfix in [BlueRecluse](https://github.com/kelno/sunstrider-scripts/tree/BlueRecluse)
Requires item fix to be pushed live.

**Comment by Sheikthecatman** [comment]
Fix pushed live, still missing item fix.

**Comment by Jerrythemagicdog** [comment]
Fixed with next update thanks.
