### ISSUE TITLE
[Warrior] Heroic Strike cancels (skips) autoattack if not enough rage at time of swing

### ISSUE THREAD

**Issue by mezei** [SunstriderEmu/BugTracker#1908]
When you queue up a Heroic Strike but the necessary rage for the ability is not available at the time of swing, the swing will not happen. (And autoattack timer seems reset.)

1. Attack a target, get Heroic Strike rage cost (15+ rage, or less depending on talents)
2. Queue up Heroic Strike
3. Deplete your rage to be less than Heroic Strike rage cost - before your next autoattack
4. Wait for your next autoattack swing
5. Not heroic nor even a normal swing will happen

**Expected behavior**
If there isn't enough rage for a queued Heroic Strike at an autoattack swing, a normal white hit should happen instead. (Currently the entire swing is just lost.)

**Comment by Pinju1** [comment]
It's the same with cleave, needs fixing!

**Comment by Pinju1** [comment]
I don't know if bumping is allowed, but bump?

**Comment by Jerrythemagicdog** [comment]
Fixed a long time ago, thanks for the issue.
