### ISSUE TITLE
Holy Resistance

### ISSUE THREAD

**Issue by Alarine** [SunstriderEmu/BugTracker#1909]
**Describe the bug**
Target dummies partially resist Holy damage.

**To Reproduce**
Consecration hits the Training Dummy for 89 damage 
Consecration hits the Training Dummy for 89 damage 
Consecration hits the Training Dummy for **76 damage (13 resisted)**

**Expected behavior**
The last time there was any Holy resistance at all, it was patch 0.7. Please remove, Thank you!
https://wowwiki.fandom.com/wiki/Holy_resistance

**Comment by Sheikthecatman** [comment]
Holy Resistance was only removed as a collectible stat for players. PvE creatures will still be able to have resistance against Holy spells.
