### ISSUE TITLE
Combo points when you attack or ability didn’t hit 

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1911]
Describe the bug:
Some spells and passive tailents , can proc when your spell being : dodge/parry/resiste/immune etc 

To Reproduce; 
1) Cheap shot adding combo points when he resiste or immune 
https://youtu.be/dwRQHat1fu0 

2) Tailent Ruthlessness - can proc after finisher  dodge/parry/miss 

https://youtu.be/vsOeVBH-Gt8 

How it should work : 

When you spell/tailent not applied or hit . Should not add combo extra cpmbo points on target 
https://youtu.be/NZbOZtqaxD0?t=1781

**Comment by blblblaz** [comment]
should be fixed with https://github.com/SunstriderEmu/BugTracker/issues/2584
