### ISSUE TITLE
Disconnect player on charge

### ISSUE THREAD

**Issue by Himeyo** [SunstriderEmu/BugTracker#1912]
Issue is : 

Sometimes, when and only when a player charge another player ( it can be warrior or druid with feral charge ), he got instant disconnect. 

I know it can be a hard issue as i dont bring any proofs and it's kinda rare, but maybe you have logs or something about it.

First we thought it could be link to some undermap > as the war charge he gets undermap then get disconnected? I don't know if it can help.

On like a 4 hours session it happened to us twice.

**Comment by Jerrythemagicdog** [comment]
Thanks!
Most likely: ee7a9e94c7f7b7c6b940c3171fd6b0b3501ad82b or e68c771b7f9b73aa9cb97c694802b8df6704ec86

It seems that it happens when the charging player gets stunned by the end of the charge

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago
