### ISSUE TITLE
Druid Bear quest not giving XP

### ISSUE THREAD

**Issue by zocks** [SunstriderEmu/BugTracker#1913]
The druid bear quest is not giving xp

**To Reproduce**
1. Do the druid bear quest

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
Druid bear quest is suppose to give xp

**Screenshots/videos**
Aliiance version:https://www.youtube.com/watch?v=Et7zuYWvS-s
Horde version:https://www.youtube.com/watch?v=yt_ThfRnA4Q

**Comment by revrox** [comment]
Can confirm quest is grey @ level 10 once picked up and no part of the chain gives any XP, tested yesterday - https://clips.twitch.tv/TameSaltyBatteryKappaRoss

**Comment by InhumanGM** [comment]
Upon attempting to reproduce the issue, I was not able to find any issues. XP was rewarded when I tried it. Can you provide more info so we can try to reproduce again?
