### ISSUE TITLE
Dreadsteed is gone lol

### ISSUE THREAD

**Issue by HeenrBTW** [SunstriderEmu/BugTracker#1914]
**Describe the bug**
I log out , then i log in then i dont have my dreadsteed anymore (Felsteed too)

**To Reproduce**
1. Cast X on target affected by ...
2. 
3. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by Sheikthecatman** [comment]
Hence there are no steps on how to reproduce this except for logging out and this not being a repeated issue, we cannot investigate the issue.

As for your case, please create an in-game ticket to get it solved.
