### ISSUE TITLE
[NPC] Dark Iron dwarfs

### ISSUE THREAD

**Issue by revrox** [SunstriderEmu/BugTracker#1916]
**Describe the bug**
Dark iron dwarfs in northern wetlands have an ability called Gift of Ragnaros which isn't working properly, the ability should be a melee attack but seems to be a huge range spell cast.

**To Reproduce**
Engage the mob @ range.
Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
https://classic.wowhead.com/spell=7891/gift-of-ragnaros

![image](https://user-images.githubusercontent.com/61465183/75257825-70cb9300-57dd-11ea-8929-8cedb5e5eda3.png)
**Screenshots/videos**
https://streamable.com/l6tk7

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks! Fixed after next restart.
