### ISSUE TITLE
PVP World Objectives do not grant Honor

### ISSUE THREAD

**Issue by thezorlul** [SunstriderEmu/BugTracker#1917]
Description: 
PVP World Objectives such as Hellfire Peninsula Towers, Eastern Plagueland Towers, Bone Wastes Towers and Zangamarsh Towers for example do not grant any Honor upon Capture.

All my TBC experience comes from Private Servers so if this was not a Retail thing my bad, i was not aware. But from my experience on mutliple private Servers over the years, capturing these did grant honor albeit a small amount, something around ~20. From a quick Google search i could only find a Forum Post from 2008 stating that these are supposed to grant "bonus Honor".

Quote from said Forum Post: 
World PvP
Azeroth and Outland provide ample opportunities for fighting other players in the great outdoors. World PvP objectives placed in strategic locations encourage such conflict, especially on PvE servers where the threat of PvP combat is not as pervasive as it is on PvP servers. These special objectives grant bonus honor much in the same way as Battlegrounds objectives.

* Outland World PvP
+ Hellfire Peninsula PvP
+ Zangarmarsh PvP
+ Bone Wastes PvP
+ Nagrand PvP
* Azeroth World PvP

**Comment by thezorlul** [comment]
![image](https://user-images.githubusercontent.com/61473923/75280066-0af6ff80-580d-11ea-86c5-b34c1dd4143f.png)

**Comment by z5n** [comment]
the honor is granted through completing one of the related quests regarding these towers, not the act of capturing the tower itself
