### ISSUE TITLE
Quest On Spirit's Wings doesn't currently work

### ISSUE THREAD

**Issue by Hustler495** [SunstriderEmu/BugTracker#1918]
1) When the sum of the spirit, it does not always appear.
2) When he appears, he flies to only one pair of mobs, and these quest pairs are more than 5
3) Having flown to a pair of mobs, nothing happens and the quest does not count
4) this is my already 4 reports on this chain,  please! check the efficiency of the entire chain, there are about 10 quests there

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed after next restart.
