### ISSUE TITLE
Таймер на главной странице

### ISSUE THREAD

**Issue by stepanalekseevich90** [SunstriderEmu/BugTracker#1919]
При входе на главную страницу сайта отсчёт показывает время по Гринвич, но при полной загрузке данных, таймер сокращается на 6 часов! Какая информация корректна?

**Comment by stepanalekseevich90** [comment]
https://youtu.be/oSKkNFhoZV0 check video

**Comment by Sheikthecatman** [comment]
The time localization issue is now resolved and you should be able to see the correct time no matter the region.
