### ISSUE TITLE
[NPC] Marsh Lurker

### ISSUE THREAD

**Issue by Tyrannize999** [SunstriderEmu/BugTracker#1920]
**Describe the bug**
The elemental is not moving and he stuck in text and he is not attackable. I know it's not an important bug.

![WoWScrnShot_022620_140145](https://user-images.githubusercontent.com/60829714/75347353-d92f7880-58a0-11ea-9c47-ea482ca07c76.jpg)

**ID**
[NPC] Marsh Lurker (18136)

**Comment by InhumanGM** [comment]
In order to replicate this issue, we need more information. Please follow the bug report template that way we can properly reproduce and investigate this issue.

> **Describe the bug**
> 
> **To Reproduce**
> 
> 1. Cast X on target affected by ...
> 
> Item: https://wowhead.com?item=
> Quest: https://wowhead.com?quest=
> Spell: https://wowhead.com?spell=
> 
> **Expected behavior**
> 
> **Screenshots/videos**
> 
> **Additional context**

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/1571
