### ISSUE TITLE
[Warrior] Intercept

### ISSUE THREAD

**Issue by Tyrannize999** [SunstriderEmu/BugTracker#1921]
**Describe the bug**
I used the ability "Intercept" on a mob, but my character didn't charge to him, just stunned the mob. After this my character started walk really slow to mob and I was unable to do anything (can't even jump). When my character arrived to mob he just started fall under the text and the fall was very slow too. It was jumping up-down under the text.

First picture shows it was like 30 secs until my character walked to mob. Like i said i can't do anything.
![WoWScrnShot_022620_142343](https://user-images.githubusercontent.com/60829714/75349262-bdc66c80-58a4-11ea-9278-be30027d322c.jpg)

The second shows my falling, but only fall a little under the text. I circled my buffs to show it took like a 30 secs to fall just a few frame. I know video would be better.
![WoWScrnShot_022620_142415](https://user-images.githubusercontent.com/60829714/75349448-16960500-58a5-11ea-97fb-1d002f37f2bd.jpg)

**Comment by kelno** [comment]
Fixed since
