### ISSUE TITLE
[Hunter] Hunter pet quest for orcs not rewarding XP

### ISSUE THREAD

**Issue by marcjeno1** [SunstriderEmu/BugTracker#1922]
All the taming the beast quest for Orc hunter are currently not rewarding any XP at level 10/11.

The quests also appear grey in the quest log. 

Could you have a look at this?

**Comment by AWIDIUS** [comment]
Same goes for totems for shamans

**Comment by Jerrythemagicdog** [comment]
Thanks, all Hunter quests fixed after next restart, looking into other classes next.
