### ISSUE TITLE
Young Panther's ability "CLAW" attacking outside of melee range

### ISSUE THREAD

**Issue by Buddyb419** [SunstriderEmu/BugTracker#1923]
**Describe the bug**
Young Panther's ability "CLAW" attacking outside of melee range

**To Reproduce**
1. AOE grinding Young Panthers for Panther Mastery Quest.
2. Getting hit with Claw at max range Blizzard

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
Young panther's should not be able to use melee abilities from 36 yards away.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed after next restart.
