### ISSUE TITLE
Rip not using correct damage formula

### ISSUE THREAD

**Issue by Felynda** [SunstriderEmu/BugTracker#1924]
**Describe the bug**
Rip not using the correct damage formula.
Currently on Endless using 5cp Rip with stats as in the screenshot:
![image](https://user-images.githubusercontent.com/45050227/75378530-22e58680-58d4-11ea-8f30-442e33c0e73d.png)

According to Elitist Jerks the formula should be like this for no talents: 
![image](https://user-images.githubusercontent.com/45050227/75376714-c6cd3300-58d0-11ea-91ac-cf80133f724d.png)
https://web.archive.org/web/20070922125148/http://elitistjerks.com/f31/t11338-feral_druid_dps/p11/

Using the formula with my stats:
5 cp: 0.24 * AP + (1092 * 1.1 *1 .3) (possibly x1.42 instead of 1.1 * 1.3)
0.24 * 2564 +1092 * 1.1 * 1.3= 2176,92 or 362 per tick

Mine only did 1704 or 284 per tick. A massive downgrade of 78 compared to what it is supposed to be.
He does state that this is an extremely close approximation. If more proof is needed I can search for some more.

EDIT: someone else marked this wrongly as a bug: https://github.com/SunstriderEmu/BugTracker/issues/1709. You had the proper formula before. Please revert to this old one

**Comment by Felynda** [comment]
Since I have seen no reply yet I will post some additional proof, please read Elitist Jerks discussing the issue on Rip damage here: https://web.archive.org/web/20071224194401/http://elitistjerks.com/f31/t11338-feral_druid_dps/p10/
https://web.archive.org/web/20071224035823/http://elitistjerks.com/f31/t11338-feral_druid_dps/p11/

**Comment by Felynda** [comment]
Once more for good measure: https://web.archive.org/web/20080504084526/http://elitistjerks.com/369792-post17.html
![image](https://user-images.githubusercontent.com/45050227/76168979-93ae5d80-6174-11ea-8fd5-f3ebffa69eb9.png)

With 2000 AP a Rip should do (with Naturalist and Mangle) :
(1092 x 130% x 110% + 24% x 2000) x 130% x 110% = 2919.4 (6 x 486.6 per tick)

On current server a Rip does:
(1092 + 2000 * 0,24) * 1,1 * 1,3 = 2247,96 ( 374,66 per tick)

Over 50 dps lost with this bug. A massive amount which hurts an already considered weak spec extra hard. There is even more dps lost when you factor in https://github.com/SunstriderEmu/BugTracker/issues/1931 also not working.

**Comment by beraus** [comment]
Fixed in https://github.com/SunstriderEmu/BugTracker/issues/3501
