### ISSUE TITLE
[NPC] Dulvi <Mining Trainer>missing completely from Azuremyst Isle .

### ISSUE THREAD

**Issue by revrox** [SunstriderEmu/BugTracker#1925]
**Describe the bug**
Dulvi <Mining Trainer> is not in the location she should be, unable to find her at all.
**To Reproduce**
Go to her location

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://www.wowhead.com/npc=17488/dulvi

**Additional context**

**Comment by Jerrythemagicdog** [comment]
She's in the middle of Azure Watch (screenshot taken from PTR)
![image](https://user-images.githubusercontent.com/46463908/75409673-5266b400-5911-11ea-935c-392f49e01e93.png)

**Comment by beraus** [comment]
Creature is in the game now. crea 84579
