### ISSUE TITLE
Windowed Mode Error

### ISSUE THREAD

**Issue by kakumeinokage** [SunstriderEmu/BugTracker#1926]
When ever i try to switch to Windowed mode the screen just goes black and nothing changes.

**Comment by Sheikthecatman** [comment]
This issue is not related to the Server but the interaction between the Client and your Gamma. 
To resolve the issue start with going to the Config.wtf file inside of your WTF Folder and edit it.
Add these two lines:
SET gxWindow "1"
SET gxMaximize "1"
