### ISSUE TITLE
[Rogue] Ruthlessness proc on focus

### ISSUE THREAD

**Issue by Macumbafeh** [SunstriderEmu/BugTracker#1927]
**Describe the bug**
If i had a combo point on my focus and i use a spell which use this combo point on my focus with a macro and at same Time i target an other target, if Ruthlessness (rogue's talent) proc, the combo point win will be on my target instead of my focus.

**To Reproduce**
1. Use /focus on "X" and hit him to get a combo point
2. Then target "Y"
3. Use a spell focus macro which use the combo point on "X" (ex : /use [target=focus] Slice and dice) and continue to target "Y"
4. If the talent Ruthlessness proc, the combo point win will be on "Y" instead of on "X"

Ruthlessness : https://www.thegeekcrusade-serveur.com/db/?spell=14161

**Expected behavior**
If i have a combo point on my focus and i use a spell on my focus which use my combo point and when i target an other target, if Ruthlessness proc at this Time, my combo point win have to be on my focus.

**Screenshots/videos**

**Additional context**

**Comment by blblblaz** [comment]
i think this is correct because the talent says "chance to add a combo point to your target", works the same way as the "Setup" talent in Subtlety, when these talents were created focus target didnt exist so it makes sense that it's not accounted for

**Comment by Macumbafeh** [comment]
Nah the talent Ruthlessness says = Gives your melee finishing moves a 60% chance to add a combo point to your target.
Then your "target" mean the target who had a combo point before to be used, not random target.
I wanna Say too that the melee finishing moves was not used on the target (it was used on focus), then the proc have to be on the focus and not on the target.

So it's a bug.
