### ISSUE TITLE
Druids not properly getting mana in Cat and Bear Forms

### ISSUE THREAD

**Issue by Felynda** [SunstriderEmu/BugTracker#1930]
**Describe the bug**
I tested with multiple sources of mana gained first fel mana potion:

**To Reproduce**
Use fel mana potion
Switch into Cat Form or Bear Form
Observe no mana being gained

Next i tried Judgement of wisdom also not getting any procs while attacking in Cat form. 

Both were working properly in caster form.

I also tested Blessing of Wisdom and Water Spring totem, these do not show up in the combat log at all but does affect charachter panel. I assume this works correctly.

**Comment by Jerrythemagicdog** [comment]
Thanks for the report, but it's invalid: https://github.com/SunstriderEmu/BugTracker/issues/1816
