### ISSUE TITLE
stun resist interrupts spell cast

### ISSUE THREAD

**Issue by Oliaxz** [SunstriderEmu/BugTracker#1932]
**Describe the bug**
When you resist a stun such as intercept, your spell cast is still interrupted.

**To Reproduce**
1. Make orc warlock to increase chance of sucess
2. Duel a warrior
3. Ask him to intercept as you drain life
4. If stun is resisted, the cast is interrupted.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
Spell cast shouldnt be interrupted by a resisted stun.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by blblblaz** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2584 should be fixed
