### ISSUE TITLE
Spell Reflection

### ISSUE THREAD

**Issue by Wandkeeper** [SunstriderEmu/BugTracker#1934]
**Describe the bug**
Spell Reflection (warrior) doesnt show damages in combat nor combat logs , it damage does work it just doesnt show its dmg, im pvp prot warr one trick pony and i wish this one was workin,
**To Reproduce**
1. Cast SPELL REFLECTION on target affected by ... MY SPELL REFLECTION! and doesnt show proced dmg by it.
2. 
3. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
DMG POPPIN OFF ON SCREEN... 
**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.
nothing to show when it doesnt show anything...
**Additional context**
i am pretty sure many warrior players would appreaciate this a lot to see those spell reflected crits poppin on screen.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1557
