### ISSUE TITLE
WOW ENDLESS

### ISSUE THREAD

**Issue by UNICObr** [SunstriderEmu/BugTracker#1935]
everything q was posted on the things page q was changed in the alliance and the seals I am in favor but therefore q the hordes stay in the right place to stay balanced because alliance has total benefit with honor / reputation among others, also wanted to say that immune paladin 5s should n have this ability as it makes the gameplay bad outside it should remain what it already is

**Comment by UNICObr** [comment]
things that do not make sense in my opinion and that the guys certainly believe that they will agree, remove the immune 5s paladin and do not think it fair for the rogue to use his skills and the error / miss (among others) and not add the (combo opoint) being that energy was spent, it is unnecessary for the magician to make mistakes, also being magic, stunning does not make any sense to resist a stunning, remembering that paladin has an angel that gives a lot of damage 2 immune being one of 5s a skill that heals his whole life having to choose between her and the immune and still have 2 stunning, minimum they can do is withdraw the immune from 5s, the shamas of 1% could receive a buf for 2% already this is great outside those things leaves the geito that was written on the site

**Comment by Jerrythemagicdog** [comment]
Thank you for suggestions!
