### ISSUE TITLE
Ban

### ISSUE THREAD

**Issue by Ozzy20044** [SunstriderEmu/BugTracker#1937]
I'm trying to log in on my ACC in-game and there is " This WoW accound has been close and is no longer available for use" I've got ban but dunno know why and what for, cuz I couldn't even log in once.

**Comment by Azurantine** [comment]
> I'm trying to log in on my ACC in-game and there is " This WoW accound has been close and is no longer available for use" I've got ban but dunno know why and what for, cuz I couldn't even log in once.

Exactly the same here, I suspect login server issues.

**Comment by gamerx1995** [comment]
i'm having the same problem but i see by checking the armory that some people are actually leveling so

**Comment by kakumeinokage** [comment]
Same for me as well, I checked my account on Endless website and it says I am in good standing so not sure what is wrong here, I even reset my password and still nothing.

**Comment by Mokochoco** [comment]
Hello, same problem to my account also. Any solution please ?
BR

**Comment by gamerx1995** [comment]
hopefully they fix it soon i would like to keep up with the other guys

**Comment by Wandkeeper** [comment]
hi, im banned too...  first i thought i got banned because i reserved " YASUO " name  for my self so some of admins banned me so they can delete char and take the name.. haha how sick that would be, but now i see more people get the same problem so im relief

**Comment by Azurantine** [comment]
@gamerx1995 No server firsts for us :(

**Comment by woiwoz** [comment]
The bans you're experiencing are temporary (5 min) and won't have any impact on your account. We're working as hard as we can on resolving the issues. Some stats before the shutdown: 1k players got on without issues, 5k attempted to log on at the same time. Thank you for your patience!

**Comment by gamerx1995** [comment]
thanks for the update <3

**Comment by Azurantine** [comment]
Awesome, thanks for the update @woiwoz, much appreciated :)

**Comment by Wandkeeper** [comment]
hypeeeeeeerz

**Comment by gamerx1995** [comment]
did everyone get the server reset message and after reset then couldn't log back in?

**Comment by Azurantine** [comment]
> did everyone get the server reset message and after reset then couldn't log back in?

Nope, just simply not been able to login since the 'launch'.

**Comment by Wandkeeper** [comment]
before it was banned message for me, now its just disconnected i think they workin on it

**Comment by chapaiko320** [comment]
То же не могу зайти, как же это печально, разработчики я в вас верю и с нетерпением жду решение проблемы)

**Comment by Azurantine** [comment]
> То же не могу зайти, как же это печально, разработчики я в вас верю и с нетерпением жду решение проблемы)

Мы все скоро повеселимся, я уверен.

**Comment by Jerrythemagicdog** [comment]
Resolved.
