### ISSUE TITLE
everytime i try to log in the realm list is empty

### ISSUE THREAD

**Issue by gamerx1995** [SunstriderEmu/BugTracker#1938]
everytime i try to log in the realm list is empty or it just disconnects me and sometimes it tells me that my account is banned but i was able to log in and play for a few mins when the server came up

**Comment by Azurantine** [comment]
Welcome to the club, a few of us have already presented this in a post below yours. So your not on your own.

**Comment by Jerrythemagicdog** [comment]
Resolved.
