### ISSUE TITLE
click login, then unable to connect for 30 mins now

### ISSUE THREAD

**Issue by sassmate** [SunstriderEmu/BugTracker#1940]
**Describe the bug**

**To Reproduce**
1. Cast X on target affected by ...
2. 
3. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Resolved,
