### ISSUE TITLE
Spell cost is not reduced for any paladin spells, 7s for lvl 16 spell Ret Aura, 9.5s for Righteous Defense

### ISSUE THREAD

**Issue by Putin1234** [SunstriderEmu/BugTracker#1941]
**Describe the bug**

**To Reproduce**
1. Cast X on target affected by ...
2. 
3. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Resolved,
