### ISSUE TITLE
CANT CREATE ACCOUNT

### ISSUE THREAD

**Issue by tirofijo9** [SunstriderEmu/BugTracker#1942]
**Describe the bug**
IM TRYING TO CREATE AN ACCOUNT ON ENDLESS WEBPAGE AND WHEN I CLICK CREATE ACC. AN ERROR APPEARS "500 ERROR , An error occurred while processing your request."

**Comment by Jerrythemagicdog** [comment]
We're working on resolving the issue. More info on discord.endless.gg
