### ISSUE TITLE
Game Crashes When I Change Graphics Settings

### ISSUE THREAD

**Issue by JCote75** [SunstriderEmu/BugTracker#1943]
Every time I try to put the game in 1920x1080 144hz and/or windowed it goes to a black screen and i have to close it through task manager.

**Comment by Jerrythemagicdog** [comment]
If you're getting a black screen when swapping to windowed mode - it's a GAMMA issue. Open up config.wtf inside of your WTF folder and add these 2 lines:
SET gxWindow "1"
SET gxMaximize "1"
