### ISSUE TITLE
Swing timer reset on spellcast

### ISSUE THREAD

**Issue by mucklebones** [SunstriderEmu/BugTracker#1946]
Seemingly all spells reset melee swing timer. Tested with Frost Nova, Frostbolt, Fireball. Only certain abilities should reset the swing timer

**Comment by Jerrythemagicdog** [comment]
This is the correct behavior for those spells, if you have proof of it behaving otherwise please provide it.

**Comment by Jerrythemagicdog** [comment]
This is the correct behavior for those spells, if you have proof of it behaving otherwise please provide it.
