### ISSUE TITLE
Drinking does not regenerate mana while in combat

### ISSUE THREAD

**Issue by Soerj** [SunstriderEmu/BugTracker#1947]
**Describe the bug**

**To Reproduce**
1. Cast X on target affected by ...
2. 
3. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by blblblaz** [comment]
could not reproduce
