### ISSUE TITLE
Pet renaming

### ISSUE THREAD

**Issue by emilavara** [SunstriderEmu/BugTracker#1948]
**Describe the bug**
Everytime you dismiss and summon your pet you can rename the pet.

**To Reproduce**
1. Name your newly tamed pet
2. Dismiss pet
3. Resummon pet
4. You can now name the pet again

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by z5n** [comment]
valid, however we will be turning off pet renaming for the foreseeable future


>That's intentional because players used rename to confuse AddOns like Gladius with renaming their pet to the same name as one of their teammates, bugging out the AddOn.
We're planning to keep it that way for the foreseeable future.

_Originally posted by @Jerrythemagicdog in https://github.com/SunstriderEmu/BugTracker/issues/5177#issuecomment-1659178806_
