### ISSUE TITLE
Blood Elf Paladin Class Quest "The Second Trial" NPC Bugged. Master Kelerun Bloodmourn

### ISSUE THREAD

**Issue by k1dsmoke** [SunstriderEmu/BugTracker#1949]
You can accept the first part of "The Second Trial" quest but you can't turn in to Master Kelerun Bloodmourn.

I was able to turn in, and accept the next part during the multiple server resets earlier, but after completion of the quest I was unable to turn in to Master Kelerun again.

I dropped the quest hoping to pick it back up, complete and then maybe turn in, but after abandoning the quest the "!" appeared above Kelerun's head but I could not accept the quest.

**Comment by k1dsmoke** [comment]
Went back to him to check and he still has a "!" above his head, but now offered Paladin training. Restarted game, spoke with him again and now he no longer offers the training and still doesn't give out the quest.

**Comment by k1dsmoke** [comment]
This is working now, thank you.

**Comment by lorant1992** [comment]
No, this quest still is not working. I can t summon the champions for the trial with the crystal.
