### ISSUE TITLE
Hunter's Pet happiness Drops insanely fast

### ISSUE THREAD

**Issue by Espranty** [SunstriderEmu/BugTracker#1951]
**Describe the bug**
Pet's having multiple issues 
One : Loyalty doesnt level pretty much
Two : Pets leveling exp gained is Very very very slow 
Three (And most important) : Pet's Happiness drops SUPER Fast , pretty much goes to Unhappy if Un-fed every 7 minutes or so ..

**To Reproduce**
Simply tame a pet and feed him / Kill mobs /keep him happy for a while and u'll notice its all bugged .

**Expected behavior**
Expecting pets to gain extra Exp as their masters
Expecting Pets Happiness to drop WAY Slower than what it's now .
Expecting Pets Loyalty to level Normally with the amount of time Your pet stays happy with you.

**Screenshots/videos**
No need , The Entire Server's Hunter community having same issues , Check PvE channel on Discord.

#Regards and Ty

**Comment by Plovpenning** [comment]
Couldn't agree more with this post! plz fix this asap Endless :)

**Comment by kelno** [comment]
Should be improved with next restart
