### ISSUE TITLE
Spirit Tap triggering on mobs that dont award experience (Totems)

### ISSUE THREAD

**Issue by nggggglqsph** [SunstriderEmu/BugTracker#1954]
**Describe the bug**
Killing an NPC's Totems (tested on Witherbark Witch Doctor's Magma Totem and Healing Ward) awards as well as refreshes Spirit Tap.

**To Reproduce**
1. Attack a Witherbark Witch Doctor or Boulderfist Shaman (probably any hostile NPC that spawns Totems),
2. Kill the spawned Totem,
3. Get the Spirit Tap buff upon killing said Totem.

**Expected behavior**
Spirit Tap is only supposed to be awarded upon killing an enemy that yields experience or honor.
As such, the expected behavior is no application of Spirit Tap upon killing a Totem.

**Screenshots/videos**
Witherbark Witch Doctor 
![WoWScrnShot_022920_142936](https://user-images.githubusercontent.com/59448926/75608701-37a76180-5b02-11ea-884c-684bd2ebb3ba.jpg)

Boulderfist Shaman
![WoWScrnShot_022920_152114](https://user-images.githubusercontent.com/59448926/75609451-e2bb1980-5b08-11ea-9f35-985e921febab.jpg)

See combat text. If required, I can provide video footage.

**Additional context**

NPC IDs in question: 
https://classic.wowhead.com/npc=2555/witherbark-witch-doctor
https://classic.wowhead.com/npc=2570/boulderfist-shaman

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2030

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
