### ISSUE TITLE
Rocket Chicken pet from store doesnt function

### ISSUE THREAD

**Issue by Phonebookhero** [SunstriderEmu/BugTracker#1955]
**Describe the bug**

Rocket chicken pet will run, blast into the air, and the model will disappear, the name remains. Does not move. Have to re summon him. Bought him to have something to run with me, but i havent been able to use him because he bugs out... 

**To Reproduce**
1. Buy Rocket Chicken for roughly $15
2. Summon it.
3. It flies into sky, and never returns, forcing a resummon.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

**Screenshots/videos**
https://imgur.com/a/imBrTRq

**Additional context**

**Comment by Simon-GM** [comment]
No issue found. Can't reproduce.
