### ISSUE TITLE
Quest: Ending Their World

### ISSUE THREAD

**Issue by Psyentific** [SunstriderEmu/BugTracker#1956]
Quest link: https://tbc-twinhead.twinstar.cz/?quest=9759
Retail: https://www.wowhead.com/quest=9759/ending-their-world

Expected behaviour: 
Player picks up quest, escorts Demolitionist Legoso to the top of the vector coil, stopping partway up for one RP event before continuing on. Once reaching the top, players encounter hostile mob Sironas, currently invulnerable. Demolitionist Legoso does a second RP event, this makes Sironas attackable, then Demolitionist Legoso and player kill Sironas. Quest completes.

Actual behaviour:
Second RP event does not fire; Legoso moves to the proper place (pathing correctly, etc.) but the RP event does not start, Sironas does not become vulnerable, and after a few minutes Legoso bugs out and resets position. Quest is not marked as complete, but also not marked as failed.

**Comment by Sheikthecatman** [comment]
Thanks! Fixed with the next update, Legoso should not have a gossip menu during the part where he escorts you,
