### ISSUE TITLE
Whirlwind dont procc Sweeping Strikes

### ISSUE THREAD

**Issue by hurley040** [SunstriderEmu/BugTracker#1957]
**Describe the bug**
Each hit with whirlwind should produce an damaging instance of sweeping strikes.
At the moment you only get one procc of sweeping strikes.

**To Reproduce**
1 cast sweeping strikes
2 cast whirlwind around 4 mobs
3 observe you only get one instance of sweeping strikes.

**Expected behavior**
If whirlwind hits four targets, it should produce 4 damage instances of sweeping strikes.
At the moment, you only get one instance from the initial hit.

**Additional context**
I.E look at WoW Classic for expected behaviour.

**Comment by Bzmode** [comment]
bump

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/165

**Comment by Jerrythemagicdog** [comment]
It shouldn't proc multiple times for multiple targets: https://github.com/magey/tbc-warrior/issues/7
