### ISSUE TITLE
Possible dual talent specialization bug

### ISSUE THREAD

**Issue by Stankara** [SunstriderEmu/BugTracker#1959]
All my spells do less damage in my primary talent specialization compared to my secondary one.

**To Reproduce**
1. Just swap from primary to secondary to see the difference (screenshots included)

**Expected behavior**
I expect my spells to have the same damage on both specializations.

**Screenshots/videos**
https://imgur.com/a/Jtoq5SJ (frostbolt tooltip with primary specialization)
https://imgur.com/a/fd3VJok (blizzard tooltip with primary specialization)
https://imgur.com/a/pCFmdgD (frostbolt tooltip with secondary specialization)
https://imgur.com/a/jjf0iDM (blizzard tooltip with secondary specialization)

**Comment by kodolol** [comment]
do you understand how dual spec works?

**Comment by Stankara** [comment]
> do you understand how dual spec works?

Please enlighten me, since I know how hard it is to just tell me what I'm missing

**Comment by kodolol** [comment]
> > do you understand how dual spec works?
> 
> Please enlighten me, since I know how hard it is to just tell me what I'm missing

the talents you chose in the secondary specialization do not affect spells after you have chosen the primary specialization.
