### ISSUE TITLE
Item becomes unlootable when party disbands while that item is up for open roll

### ISSUE THREAD

**Issue by floridaman1** [SunstriderEmu/BugTracker#1960]
When an item is up for roll and the team disbands mid roll, the roll is canceled and item becomes unlootable by anyone until decay.

![image](https://user-images.githubusercontent.com/61633405/75613651-3d9b4380-5afe-11ea-88a9-781aaa07a76b.png)

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2826
