### ISSUE TITLE
Parry haste

### ISSUE THREAD

**Issue by septembr** [SunstriderEmu/BugTracker#1961]
**Describe the bug**
Parry hasting does not work for the player, or at least not for anyone playing blood elf paladin. 

**To Reproduce**
1. Have auto attack on while attacking anything that attacks you back.
2. Parry an enemy's attack.
3. Watch if your swing timer is reduced (currently it is not, but it **should** be. 

**Expected behavior**
After parrying an attack, the time before my next swing should be reduced by some amount, depending on the remaining time on the swing timer prior to the parry.
More on this here: https://vanilla-wow.fandom.com/wiki/Parry

**Comment by Crackerbox123** [comment]
I also notice this behavior - Human warrior.
While tanking 4-5 mobs in stockades with a 2H axe I get many parries but no affect on swing timer.
Makes me wonder if boss mechanics are the same way.

**Comment by rico-zellmann** [comment]
Also no Parryhaste for my Dwarf Paladin

**Comment by SUN-Leekie** [comment]
A fix has been applied.
