### ISSUE TITLE
[Tirisfal Glades] Alliance Scarlet Monastery graveyard is in Western Plaguelands

### ISSUE THREAD

**Issue by tigglywuff** [SunstriderEmu/BugTracker#1962]
**Describe the bug**
I died at the Scarlet Monastery summoning stone and the graveyard put me in Western Plaguelands when I released. I'm Alliance.

**Expected behavior**
Should be at the Scarlet Monastery graveyard when you release here.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.
