### ISSUE TITLE
[Rogue] Level 20 class quest Deep Cover

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#1963]
**Describe the bug**
https://db.endless.gg/?quest=2458
The item, Flare Gun, https://db.endless.gg/?item=8051, seems to be linked to something else from Azuremyst Isle. So I ran allllllllll over the sludge fen area and venture co tower near (55.5, 06.4) and when I attempted to use the Flare Gun it told me for 1 use attempt:
![image](https://user-images.githubusercontent.com/45275285/75616675-637e1380-5b11-11ea-83b8-e023e574f0e7.png)
![image](https://user-images.githubusercontent.com/45275285/75616678-6a0c8b00-5b11-11ea-9991-01c9eaa78e40.png)

I just need to spawn the Taskmaster Fizzule so I can salute him and get the quest next step. This is rogue class specific so I can't do poisons and I'm going elsewhere now :/ Searched the issues and couldnt find this posted yet and lots of rogues running around not sure what is happening either

**Comment by kmayberry91** [comment]
I'm also Troll. I do not know if that makes a difference.

**Comment by kmayberry91** [comment]
I was able to use the Flare Gun properly after dropping the quest, saluting Shenathul troll rogue trainer in Orgrimmar, and accepting the quest again. Then the Flare Gun was usable in the same area without that red error text.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3370

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago, thanks for the issue.
