### ISSUE TITLE
Redridge Mountains - Resurrection Point is Incorrect

### ISSUE THREAD

**Issue by thenewblock** [SunstriderEmu/BugTracker#1964]
**Describe the bug**
When you "Release Spirit" in Redridge Mountains it puts you at the coordinates 33,48. The correct coordinates are 20, 56.

**To Reproduce**
1. Die in Redridge Mountains
2. Release Spirit

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://classic.wowhead.com/redridge-mountains#map

**Expected behavior**
What should happen is when you release it puts you at the coordinates of 20, 56.
**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by InhumanGM** [comment]
Upon reproducing this issue, I am relocated to the correct coordinates (_20, 56_).
