### ISSUE TITLE
Dark Pact can resist 

### ISSUE THREAD

**Issue by Oliaxz** [SunstriderEmu/BugTracker#1966]
**Describe the bug**
Dark Pack (the affliction warlock talent) can resist when used

**To Reproduce**
1. Be a warlock, spec deep affliction for Dark Pact
2. Cast Dark Pact
3. See it resisted, happens often with Felhunter

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by hufsa** [comment]
Fixed.
