### ISSUE TITLE
Can't do blood elf redemption quest

### ISSUE THREAD

**Issue by Nythlol** [SunstriderEmu/BugTracker#1967]
The quest "The First Trial" is unavailable from Knight-Lord Bloodvalor after returning to the NPC past level 20. The first quest he offers is "The Second Trial" and even after completing said quest, the NPC still didn't offer the prior quest.

**Comment by Jerrythemagicdog** [comment]
At the time the player was required to complete "Summons from Knight-Lord Bloodvalor" in order to receive the quest, it has been changed to be a breadcrumb at some point.
Thanks for the issue.
