### ISSUE TITLE
console port support

### ISSUE THREAD

**Issue by sam0x17** [SunstriderEmu/BugTracker#1968]
My husband needs to use the consoleport addon (which is fully supported on retail and on classic) in order to play because he suffers from a physical disability. I have tried manually installing the consoleport set of addons (both the retail and classic versions) however the addons do not show up in the list of addons in game and don't seem to be recognized. What can I do to get the addons working? I am in touch with the addon developer, so what information can I give them to get this working?

Thanks!

**Comment by kelno** [comment]
Interesting, but I very much doubt this addon works for this client version.
If that addon developer wants to adapt the addon to play ou our server (or other TBC servers), he needs to look into the WoW 2.4.3 API and rewrite his addon for it.
Sorry to not be able to help more!
