### ISSUE TITLE
Disciple of Naralex escort quest

### ISSUE THREAD

**Issue by tacotal** [SunstriderEmu/BugTracker#1969]
Hello,

I don't know if it happened to anyone else, but it happened to us so I figured might as well post it here.

We started the escort in wailing caverns and the mob (Disciple of Naralex) stopped moving at some point. We made him move all the way to the altar by using mob proximity aggro but even when he was close to the altar he would just stand there and do nothing so we couldn't complete the escort.

**Comment by z5n** [comment]
issue has since been fixed
