### ISSUE TITLE
Quest: Data Rescue

### ISSUE THREAD

**Issue by KosioB** [SunstriderEmu/BugTracker#1972]
Going in gnomeregan for the Data Rescue quest works at first but at the last 3005-D punchograph there is no option to get the last card after one of our party members got it. 2 more couldnt get it there is no option to.

**Comment by Pangoken** [comment]
WOW this is brief.. No screenshots no details. How the hell are the staff supposed to understand the issue?!

**Comment by Jerrythemagicdog** [comment]
Works when a player has a Red Punch Card.
