### ISSUE TITLE
Bestial Swiftness not working

### ISSUE THREAD

**Issue by Brutalpower** [SunstriderEmu/BugTracker#1973]
**Describe the bug**
Bestial Swiftness (hunter's talent in Bestial Mastery spec) not working.

**Comment by DonIncognit0** [comment]
Yeah I noticed the same Bug, Bestial Swiftness in the Beast Mastery tree does not seem to work. The outdoor movement speed of your pet does not increase by 30% after putting a point in that talent.

**Comment by Roaark** [comment]
+1

**Comment by Jerrythemagicdog** [comment]
Works in my tests now, thanks for the issue.
