### ISSUE TITLE
No levels when herb'ing

### ISSUE THREAD

**Issue by yolohse** [SunstriderEmu/BugTracker#1975]
Im leveling herbing and i don't get levels from orange nodes. quite annoying.

Briarthorn is orange for me and i picked two nodes and got no levels
![image](https://user-images.githubusercontent.com/59824709/75621507-881bcf00-5b95-11ea-9772-0504422e9617.png)

**Comment by krustan** [comment]
Have you trained yoursefl? As i see you are lvl75 :D

**Comment by yolohse** [comment]
....

**Comment by yolohse** [comment]
Please don't tell anyone <3
