### ISSUE TITLE
Lost Whelp in Wetlands hits way too hard

### ISSUE THREAD

**Issue by Zyin055** [SunstriderEmu/BugTracker#1976]
**Describe the bug**
[Lost Whelps](https://classic.wowhead.com/npc=1043/lost-whelp) in Wetlands, a level 24-25 mob, crit a 33 rogue for [608 damage](https://imgur.com/a/Kk4QTKB) with low/moderate gear. This is way more than than it should be, which is around 40-100 non crit. The other whelps in the area seem to be hitting the appropriate amount.

**Comment by Almentoe** [comment]
They also appear to be immune to at least shadow spells.

**Comment by Sheikthecatman** [comment]
Thanks! Damage numbers have been corrected, the fix will be live next server restart.

According to the Wowhead page, they are supposed to be immune to shadow spells.
