### ISSUE TITLE
Crashing When Attacking Highborne Spirits in Darkshore

### ISSUE THREAD

**Issue by ghgoodreau** [SunstriderEmu/BugTracker#1977]
**Describe the bug**

The game is crashing when I attack a highborne spirit in Darkshore at the Ameth'Aran ruins. I am a druid, but it crashes when I cast wrath and/or moonfire. I die instantly when the crash happens, too. I have attached a screenshot of the Windows error I get when the client closes. This crash was also experienced by other players in the area, and I found an instance of someone mentioning this in the discord early yesterday morning.

**To Reproduce**
1. Attack Highborne Spirit target OR be in vicinity when they aggro you.
2. I was on the quest Tools of the Highborne, if that helps.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

https://classic.wowhead.com/quest=958/tools-of-the-highborne
https://classic.wowhead.com/npc=2176/cursed-highborne

**Expected behavior**

I expected to complete the quest as normal.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

![image](https://user-images.githubusercontent.com/25194960/75622136-c77cf800-5b62-11ea-98d3-faf4b6a50f3c.png)

**Additional context**

**Comment by reli21** [comment]
this bug persists, every time i get hit by a highborne i encounter the same error

**Comment by beraus** [comment]
Couldn't reproduce this issue (tested with level 70):
Rushing: https://streamable.com/o1wh2w
Letting them attack: https://streamable.com/h3085d

If you have more info let us know.

**Comment by InhumanGM** [comment]
I have encountered this issue twice before, but only accidentally. Reproduction of the issue proves to be inconsistent, as sometimes I get crashed, and sometimes I can carry on fighting without any issue whatsoever.

**Comment by Nailchild** [comment]
Im experiencing the exact same issue on  15 dranei shaman. Same error as posted above

**Comment by InhumanGM** [comment]
Could you please provide the armory link to your character, @Nailchild?

**Comment by Nailchild** [comment]
https://endless.gg/armory/character/shahzam

**Comment by z5n** [comment]
Client issue - broken patch file
