### ISSUE TITLE
Call of Fire - Draenei - Missing Torch

### ISSUE THREAD

**Issue by Talimar** [SunstriderEmu/BugTracker#1979]
**Describe the bug**
The torch is supposed to be contained within the bag you get from Temper. But mine only had the Orb of Returning in it.
Worked on second attempt.
But it really sucked to find out torch was missing after running to other side of map.

https://www.wowhead.com/quest=9467/call-of-fire

**Comment by TorgusGitHub** [comment]
I had the exact same problem. Luckily for me I spotted it out on the start so abandoning the quest and picking it up again gave me another bag that contained missing torch.

**Comment by SUN-Leekie** [comment]
Cannot reproduce, need some information.
