### ISSUE TITLE
totally broken and bugged??

### ISSUE THREAD

**Issue by swisskapunk** [SunstriderEmu/BugTracker#1980]
hi team im totally broken and bugged....i play tbc my last 12 years so i think i know what im doing...the chat is totally broken i cant scroll the message and i cant write in noone chat room only in /say......i try to leave all my addons but im still broken...try to use the file repair wow but the repair system cant connect to the server so i cant repair too....gold drop is pretty shameless after 2 hours playng i make 5 silver with all what i sell and cant buy spell or buy water....how i should play with low rank spell??i cant target myself how is this possible??please beginn to fix this server or it will die in a week......greetings from switzerland.....

**Comment by snurkh** [comment]
u suck m8

**Comment by swisskapunk** [comment]
thanks.....

**Comment by swisskapunk** [comment]
i got a very good teacher...your mom and your sister.....

**Comment by SUN-Leekie** [comment]
Chat is fixed.
