### ISSUE TITLE
Quest Thwarting Kolkar Aggression

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#1982]
Quest requires acquiring the following 3 items:
Attack Plan: Valley of Trials destroyed 
Attack Plan: Sen'jin Village destroyed
Attack Plan: Orgrimmar destroyed

No quest items are spawned inside and around the tents for quest completion. 

wowhead page: https://classic.wowhead.com/quest=786/thwarting-kolkar-aggression

**Comment by Jerrythemagicdog** [comment]
Seems like there was either an issue with gameobject respawns at the time or someone already fixed it because they respawn pretty much immediately after being destroyed now. Thanks for the issue, closing.
