### ISSUE TITLE
Keep getting disconnected when trying to join the server

### ISSUE THREAD

**Issue by oomilktoastoo** [SunstriderEmu/BugTracker#1983]
I Keep getting disconnected when trying to join the server.

I played several hours earlier and I alt+F4, now when i try to log back in, I kept getting disconnected.
Did not even load the character list.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by hufsa** [comment]
The server is down currently. We are working on resolving the issues.
