### ISSUE TITLE
[Quest] Need for a cure timer bug

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#1984]
**Describe the bug**
The timer disappears after logging off and back in. Can still proceed to the next quest in chain "Finding the antidote" and getting the antidote. After acquiring the antidote, the original Need for a cure quest cannot be completed since timer is gone. 

**To Reproduce**
1. Taking the quest "Finding the antidote"
2. Logging off and back in after 12 hours (I logged off for 12 hours, maybe it doesn't take that long).
3. The count down timer disappears.
4. Complete the quest "Finding the antidote"
5. Return to quest giver with the antidote. Cannot complete quest. 
6. Drop quest. The antidote disappears from bag. Retake quest. 
7. Go to "Finding the antidote" quest giver. Cannot take quest again since it was completed.

link to the relevant wowhead-like page: https://classic.wowhead.com/quest=812/need-for-a-cure

**Expected behavior**
In the above step 3, either the timer resumes or mark quest as failed to stop quest chain progression.

**Comment by Lamberdo** [comment]
after complete quest "Finding the antidote" and retake quest "Need for a Cure" qitem from "Finding the antidote" gone and we cant complete one more time this one.. so we cant complete "Need for a Cure"

**Comment by Jerrythemagicdog** [comment]
Thanks, we changed the quest "Finding the Antidote" to be repeatable as long as "Need for a Cure" is not rewarded so this case can be solved by re-taking "Need for a Cure". "Finding the Antidote" will then become available for pick-up then.
