### ISSUE TITLE
Quest: Frostmane Hold

### ISSUE THREAD

**Issue by karlsbjorn** [SunstriderEmu/BugTracker#1985]
**Describe the bug**
While attempting to complete the "Fully explore Frostmane Hold" objective of the quest, walking to the spot that's supposed to complete the objective doesn't complete it and neither does any spot in the cave.

**To Reproduce**
1. Accept quest "Frostmane Hold"
2. Go into the Frostmane Hold cave
3. Walk around the entire cave
4. Quest objective doesn't complete

**Link to quest:**
https://tbc-twinhead.twinstar.cz/?quest=287

I experienced this before the [March 1st changelog](https://endless.gg/changelog/2020/03/01) but didn't see the quest mentioned in it so I'm posting this just in case.

**Comment by InhumanGM** [comment]
In order for the quest objective "[Fully explore Frostmane Hold](https://imgur.com/a/3PQRaMl)" to appear as completed in the quest log, the second objective "[Frostmane Headhunter slain: 0/5](https://imgur.com/a/0eq56qG)" must be completed as well.

For example, if you explore the cave before you kill the 5 headhunters, the quest objective "[Fully explore Frostmane Hold](https://imgur.com/a/3PQRaMl)" wont show up as [completed](https://imgur.com/a/icP7LHr).
