### ISSUE TITLE
[Item] Luffa not working

### ISSUE THREAD

**Issue by rico-zellmann** [SunstriderEmu/BugTracker#1986]
The Trinket [Luffa](https://tbcdb.com/?item=19141) doesnt work (goes on cooldown but doesnt remove debuff) on the Rend debuff that mobs cast on the player on Hellfire Peninsula in the Den of Haal'Esh

**To Reproduce**
1. Equip Luffa
2. acquire Rend debuff (on Hellfire Peninsula in the Den of Haal'Esh)
3. use Luffa

**Expected behavior**
Luffa should remove the buff per its description.

**Comment by hufsa** [comment]
"Will not work on bleeds cast by enemies over level 60."
Since you are in HFP, what level was the enemy?

**Comment by rico-zellmann** [comment]
These Kaliri alre lvl 60-63. I didnt check though.
https://tbcdb.com/?item=23588
Didnt know it doesnt work above lvl 60. Very possibly thats the answer. 
Next question would be if it should go on cd doing nothing. If you dont have a bleed debuff it doesnt go on cd either.
