### ISSUE TITLE
[Hellfire Peninsula] Mag'har Ancestral Beads dont drop

### ISSUE THREAD

**Issue by rico-zellmann** [SunstriderEmu/BugTracker#1987]
[Mag'har Ancestral Beads](https://tbcdb.com/?item=23589) dont drop. So the quest [Makuru's Vengeance](https://tbcdb.com/?quest=9424) and all followups cant be completed.

**Comment by Godmatik** [comment]
Confirmed.

**Comment by call69** [comment]
Please fix asap this is important pre-q for the kurenai , many quests in zanga an nagrand are not accesible because of this.

**Comment by SUN-Leekie** [comment]
A fix has been applied yesterday.
