### ISSUE TITLE
Earth Shock interrupt 

### ISSUE THREAD

**Issue by Tasressurect** [SunstriderEmu/BugTracker#1990]
When interrupting a spellcaster that only casts from one school of magic (i.e. Fire), instead of multiiple schools of magic where as if one is interrupted they could cast from their second school of magic, the NPC just stands still looking retarded at you, when instead they should begin advancing to melee their target (which greatly helps pulling mobs methodically to fight 1 at a time, as opposed to having to engage on them from melee range where you could body pull additional mobs)

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago, thanks for the issue.
