### ISSUE TITLE
Windroc Respawns Broken

### ISSUE THREAD

**Issue by grugbrain** [SunstriderEmu/BugTracker#1991]
**Describe the bug**
Windrocs in Nagrand are not respawning at all.

**To Reproduce**
Visit Nagrand, observe that Windrocs are not respawning. They are typically found North of The Ring of Trials.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

https://www.wowhead.com/npc=17128/windroc
https://www.wowhead.com/quest=9854/windroc-mastery

**Expected behavior**

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by InhumanGM** [comment]
I believe this issue has since been correct, as currently the respawn time on [Windroc](https://tbc-twinhead.twinstar.cz/?npc=17128) is approximately 5 minutes, and they are respawning as intended.
