### ISSUE TITLE
Video setting changes cause crash

### ISSUE THREAD

**Issue by spaullba** [SunstriderEmu/BugTracker#1992]
Hello-

I just downloaded the game and was very excited to play.  Unforunately the game defaults to a lower resolution 1240x something, and looks terrible.  When I try to switch it to a higher setting (or any setting for that matter) the game goes unresponsive, and actually freezes up my whole computer.  I have to ctrl+alt+delete => sign out to get the computer to work properly again.

Hoping for a solution here.

Thanks,

**Comment by kelno** [comment]
You can try to get people in Discord or support to help you, this is related to your own computer, while this bugtracker is reserved for server bugs.
