### ISSUE TITLE
Gorefiend's Truncheon Doesn't Drop

### ISSUE THREAD

**Issue by grugbrain** [SunstriderEmu/BugTracker#1997]
**Describe the bug**
The horsemen (Ghostrider of Karabor) do not drop the Truncheon for the quest "Divination: Gorefiend's Truncheon".

**To Reproduce**
1. Locate the Ghostrider pack
2. Kill one by one, by bringing one outside the other's leash range
3. Ghostrider of Karabor is not lootable when killed.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

https://www.wowhead.com/item=30800/gorefiends-truncheon#dropped-by
https://www.wowhead.com/npc=21784/ghostrider-of-karabor
https://www.wowhead.com/quest=10636/divination-gorefiends-truncheon

**Expected behavior**

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Their respawn and loot are linked and I believe all of them need to be killed. If you believe that's wrong please provide sources proving so.
