### ISSUE TITLE
[Rogue] Gouged caster NPCs can still turn in place following their target

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#1998]
Was able to replicate this on [Searing Hatchling's](https://db.endless.gg/?npc=4323) use of Fireballs. Since I would like to backstab from behind, I may gouge and then the mob would still be able to spin freely even while incapacitated.

I have gouge rank3 and cant downrank at this time, not sure if core related to incapacitate effects rather.

I couldnt get it to happen 100% of the time but it was happening fairly frequently, I am sure there was no rupture/garrote/poison/proc dots in my testing of grinding on these mobs with the gouge up still too.

Dustwallow Marsh @ Dunemaul ruins area was a good site all around in circles.
![image](https://user-images.githubusercontent.com/45275285/75640433-55ec8a80-5bf2-11ea-8269-e10de38317c0.png)

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago, thanks for the issue.
