### ISSUE TITLE
[Rogue] Stuck in combat technique found due to sap in feralas maybe elsewhere?

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#2001]
**Describe the bug**
A way to become stuck in combat due to fleeing from mobs that were sapped.

**To Reproduce**
1. Go to 72,57 feralas for woodpaw alpha, woodpaw mystic, woodpaw reaver camps (example)
2. Sap a target
3. Engage and kill 1 gnoll in the group
4. Run away with 2nd gnoll in group
5. Oops you aggrod more. Stay and fight now, roughly 25 yards from the sap about to wear off. Pop some cooldowns if you need to.
6. Kill all targets

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://db.endless.gg/?npc=5258
https://db.endless.gg/?npc=5254
https://db.endless.gg/?npc=5255

https://db.endless.gg/?spell=2070

**Expected behavior**
not be stuck in combat from the sapped target doing something weird after all mobs are dead.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.
N/A

**Additional context**
N/A

**Comment by z5n** [comment]
unable to reproduce
