### ISSUE TITLE
Grimtotem Naturalist

### ISSUE THREAD

**Issue by septembr** [SunstriderEmu/BugTracker#2003]
**Describe the bug**
Grimtotem Naturalist (https://tbcdb.com/?npc=7726) in Feralas show their mana bar even while they are in Bear Form, and they also cast spells (at least Wrath) while in Bear Form. 

**To Reproduce**
1. Go to Feralas and find Grimtotem Naturalist.
2. Attack and observe. 

**Expected behavior**
While in Bear Form Grimtotem Naturalist should not show their mana bar, and they should exit Bear Form to cast any spell.

**Additional context**
Because the mana bar is showing, it is also possible to use Mana Tap (BE racial) on them while they are in Bear Form.

**Comment by beraus** [comment]
Could see mana bar, can't see em casting anything, they are just vibing in bear form.

**Comment by beraus** [comment]
https://shadowlands.wowhead.com/npc=7726/grimtotem-naturalist#abilities

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago by Sheik.
