### ISSUE TITLE
Water elementals in Stranglethorn vale 

### ISSUE THREAD

**Issue by Lockydoo** [SunstriderEmu/BugTracker#2005]
**Describe the bug**
Water elementals in stranglethorn vale dealing the wrong type of damage.

**To Reproduce**
1. dampen magic gives 40 reduced magic damage
2.
3. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
When you use dampen magic on a mage and get hit by the elementals you should resist every attack because they deal pure magic damage.

**Screenshots/videos**
https://www.youtube.com/watch?time_continue=13&v=VfTFdYzYMYE&feature=emb_title
video of someone on classic world of Warcraft explaining it better than I could ever . 

**Additional context**

**Comment by z5n** [comment]
thanks, fixed with next update
