### ISSUE TITLE
Ironforge-Stormwind tram disappearing half way

### ISSUE THREAD

**Issue by TorgusGitHub** [SunstriderEmu/BugTracker#2007]
I was taking tram from IF to SW and tram vanished like 5 secs after start making my character fall on the ground. I had to go back distance it travelled and wait for another one.

**Comment by TorgusGitHub** [comment]
It happens when you move inside the tram so to reproduce it strafe left and right when it is moving

**Comment by z5n** [comment]
issue has since been fixed
