### ISSUE TITLE
Nagrand quest bug "Stopping the Spread"

### ISSUE THREAD

**Issue by Incarceron** [SunstriderEmu/BugTracker#2009]
**Describe the bug**

While doing the quest Stopping the Spread, the fire you use to burn the villagers can hurt your character and hits for around 2k damage per tick. I don't believe this is intended.

**To Reproduce**
1. Pick up the quest "Stopping the Spread"
2. Use the fire on a villager
3. Stand in the fire

**Comment by beraus** [comment]
https://www.wowhead.com/item=24560/torch-of-liquid-fire#provided-for

**Comment by Jerrythemagicdog** [comment]
Seems like it's intended. Don't stand in the fire!
