### ISSUE TITLE
Ragin Moonkin

### ISSUE THREAD

**Issue by suti95** [SunstriderEmu/BugTracker#2010]
Raging Moonkins in Darkshore use their "Enrage" ability immediatly when You attack them. Which is not a proper way. They should use only if they low on health.

**Comment by Sheikthecatman** [comment]
The raging moonkin are now less rage-filled. [aa6913905095ae3130d53caf10c550ee70e3beb3](https://github.com/kelno/sunstrider-scripts/commit/aa6913905095ae3130d53caf10c550ee70e3beb3)
