### ISSUE TITLE
Felwood vendor NPC missing cooking recipes

### ISSUE THREAD

**Issue by ammenvale** [SunstriderEmu/BugTracker#2011]
**Describe the bug**
Vendor in Felwood should sell 2 recipes that are important to progress cooking without fishing

NPC:
Horde
https://db.endless.gg/?npc=2806
Ally
https://db.endless.gg/?npc=2803

Recipes:
Recipe: Juicy Bear Burger
https://db.endless.gg/?item=35566
Recipe: Charred Bear Kabobs
https://db.endless.gg/?item=35564

**Comment by SUN-Leekie** [comment]
Both have been added in patch 2.4, as we are still in patch 2.0, you cannot buy them.
