### ISSUE TITLE
Rogue: Master Of Subtlety

### ISSUE THREAD

**Issue by Noodlerogue88** [SunstriderEmu/BugTracker#2012]
**Describe the bug**
the Subtlety talent "Master of Subtlety" isnt working, like ATALL
**To Reproduce**
1.Have Talent 1-2-3/3 of Master of Subtlety
2. Get No Buff
3. 
**Expected behavior**
When stealthed you gain a buff from the talent, which persists during stealth and 6 seconds AFTER stealth is left

**Comment by Jerrythemagicdog** [comment]
There's no buff in TBC for the client.
