### ISSUE TITLE
Cant complete [Dissesion Amongst the Ranks...]

### ISSUE THREAD

**Issue by Andwhat3101** [SunstriderEmu/BugTracker#2015]
**Describe the bug**
The quest chain, starting with https://www.wowhead.com/quest=10772/the-path-of-conquest , makkes use of an item called Wildhammer Flare Gun (https://www.wowhead.com/item=31310/wildhammer-flare-gun) , this item is used to summon an NPC that servers as the quest npc for this chain. If the flare gun is deleted, it is supposed to be re-obtainable from the NPC that starts the quest (https://www.wowhead.com/npc=21773/thane-yoregar). Unfortunately, I unknowingly deleted said flare gun, however I was able to get the quests via friends sharing them to me, but the flare gun needs to be handed back in at the end of the chain, so I am unable to finish the quest =/

**To Reproduce**
1. Pickup quest https://www.wowhead.com/quest=10772/the-path-of-conquest
2. Finish quest (so that the flare gun cannot be reobtained by starting it again)
3. Delete the flare gun
4. You are now unable to finish the chain

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
The NPC which starts the chain, Thane Yoregar (https://www.wowhead.com/npc=21773/thane-yoregar) is supposed to offer a replacement flare gun.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.
https://gyazo.com/b8f6d1d6bbfea5f30489bd1105fabede

**Additional context**

**Comment by kmayberry91** [comment]
drop the quest and pick it up again

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3370
