### ISSUE TITLE
out of sight of line isn't working for mobs! 

### ISSUE THREAD

**Issue by dzocespd** [SunstriderEmu/BugTracker#2017]
**Describe the bug**
I was in Loch Modan Lvling and doing the quest In defense of the king's lands, and i have to kill Stonesplinter Seer and Stonesplinter Skullthumper. The Stonesplinter Seer cast lighting bolt, and when I go "LOS" just to make the mob come to me, the mob continues to cast lighting bolt! 
![WoWScrnShot_030220_191112](https://user-images.githubusercontent.com/46450140/75704889-80097f80-5cba-11ea-83e9-4bd07e7b3ce3.jpg)

**To Reproduce**
1. Cast X on target affected by ...
2. 
3. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by Godmatik** [comment]
That's not an LoS object

**Comment by dzocespd** [comment]
> That's not an LoS object

How come it is not an los object man? :D
I even tried to hide behind boxes and stuff and still the mob casts through everything

**Comment by Godmatik** [comment]
Some objects in WoW are LoS, some are not.

**Comment by kelno** [comment]
Yes many objects are not considered by line of sight checks.
For example a building will block line of sight but a tree wont.
