### ISSUE TITLE
Deadmines after DC/Crash

### ISSUE THREAD

**Issue by suti95** [SunstriderEmu/BugTracker#2018]
We are in Deadmines right now. A DC happened (server-wide crash) and all the opened doors (like the one after the oggre boss) now closed. Moreover the bosses we already killed respawned. But only the bosses not the trash.

**Comment by kelno** [comment]
Boss respawns are now fixed.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.

**Comment by kelno** [comment]
https://github.com/kelno/sunstrider-scripts/commit/f3c88cdc01459a3c30771e7da695697fe7afdece
