### ISSUE TITLE
Contagion of Rot stacks

### ISSUE THREAD

**Issue by Salomonsterpvp1** [SunstriderEmu/BugTracker#2019]
Multiple debuffs of Contagion of Rot can be applied to a player by mobs. The effect also seem to stack. 
Spell is casted by various mobs, mainly ghouls. 

Also Duration seem to stay alot longer than 4 minutes. I think Duration on the 2nd applied debuff doesnt start to count down untill the first has expired. 

**To Reproduce**
1. Engage combat with multiple ghouls at any of the Cauldrons in WPL

https://classic.wowhead.com/spell=7102/contagion-of-rot

**Expected behavior**
Should only be aplied once
Should only be active debuff for 4 min duration

**Comment by SUN-Leekie** [comment]
Do you have a video/source of it not stacking?
