### ISSUE TITLE
Quest Lost But Not Forgotten

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#2020]
**Describe the bug**
Quest item (the amulet) is not spawned. I paced up and down the east bank of Southfury river twice between Orgrimmar and the north mountain edge of the Valley of the Trial and found nothing. 

link to the relevant wowhead-like page: https://classic.wowhead.com/quest=816/lost-but-not-forgotten

**Comment by SUN-Leekie** [comment]
The amulet has a 10% loot chance.
