### ISSUE TITLE
Quest: The Smallest Creatures

### ISSUE THREAD

**Issue by GenepoolWoW** [SunstriderEmu/BugTracker#2022]
**Describe the bug**
Using the Marmot pets, which you control during this quest to poison the kegs, the ability "Poison Keg" doesn't work on the kegs. The ability does go on cooldown but doesn't poison the kegs and therefore you do not get credit. Additionally, all the hostile ogres in the camp turn invisible once you have taken control of the pet.
Tried from different ranges, jumping around the keg, tried different kegs (none of them work), tried using out of the pet stealth but sadly nothing worked so far. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Obtain the quest: "The Smalles Creatures"
2. Walk to the location of the Marmot pets and take control of one using the quest item.
3. Walk to a keg and use the ability "Poison Keg"

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://www.wowhead.com/quest=10720/the-smallest-creatures

**Expected behavior**
Take control of the pet, use it's abilities to get to the kegs undetected. Use "Poison Keg" and get credit for poisoning one of the three kegs. Repeat until all the kegs have been poisoned.

**Edit with additional information**
You can complete the quest by just walking to the kegs with your character and clicking on them which is going to give you credit. The pet is not required in the current state of the quest.

**Comment by kelno** [comment]
Visibility part should be fixed with next server update.
The poison keg spell still needs fixing.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
