### ISSUE TITLE
LOS/Pathing in BF + Clips

### ISSUE THREAD

**Issue by tpageforfunzies** [SunstriderEmu/BugTracker#2023]
Hey all, lots of pathing/LOS issues in BF.  Posting clips to most of them (should have server time on clock for log finding).

Cheers

(Clips are fresh, if they don't load at first give 'em a few minutes)

https://clips.twitch.tv/UgliestHelpfulInternAllenHuhu
https://clips.twitch.tv/EncouragingCovertAntBudStar
https://clips.twitch.tv/BusyTangentialAniseCopyThis
https://clips.twitch.tv/PricklyDarkWasabiDuDudu

**Comment by z5n** [comment]
a lot of pathfinding issues have been fixed since launch, closing as unable to reproduce
