### ISSUE TITLE
warlock pet bug on stairs

### ISSUE THREAD

**Issue by tpageforfunzies** [SunstriderEmu/BugTracker#2025]
not sure what caused or fixed but i summoned my pet on some stairs and it fell through them then only cam eback out when i went back up them (or took it out of stealth/phase?)

https://clips.twitch.tv/FilthyRefinedWoodcockHumbleLife

**Comment by InhumanGM** [comment]
In order to replicate this issue, we need more information. Please follow the bug report template that way we can properly reproduce and investigate this issue.

> **Describe the bug**
> 
> **To Reproduce**
> 
> 1. Cast X on target affected by ...
> 
> Item: https://wowhead.com?item=
> Quest: https://wowhead.com?quest=
> Spell: https://wowhead.com?spell=
> 
> **Expected behavior**
> 
> **Screenshots/videos**
> 
> **Additional context**
