### ISSUE TITLE
Darnassus mount vendor

### ISSUE THREAD

**Issue by Keiz0r** [SunstriderEmu/BugTracker#2026]
Darnassus mount vendor has all 6 mounts requiring 150 riding skill.
Please fix, and less treatment as an idiot
![Bug](https://user-images.githubusercontent.com/54153876/75726545-4b61ec00-5ceb-11ea-9313-c229a0afe349.jpg)

**Comment by gcdurastanti** [comment]
I'm also seeing this issue. Any word on this?

**Comment by gcdurastanti** [comment]
Update: Deleting Cache folder fixes this. Suggest closing.

**Comment by InhumanGM** [comment]
> Update: Deleting Cache folder fixes this.

This is correct. The issue is caused by files in your cache folder, and removing these files fixes the issue.
