### ISSUE TITLE
[Karazhan] Chess Event

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#203]
**Description:**

Chess Event needs work - currently has multiple issues, adding this report to keep track of things to do in T4, will update.

- [ ] AoE spells affects dead (out of board) pieces
- [ ] Running everywhere!
- [ ] Out of board pieces still cast spells? (I've seen an Orc Necrolyte casting)
- [ ] Fires make no damage (to alliance piece at least)
- [ ] Reset looks WHAT???

**Comment by kelno** [comment]
Done since
