### ISSUE TITLE
Spirit Tap procs even on grey mobs.

### ISSUE THREAD

**Issue by callmesov** [SunstriderEmu/BugTracker#2030]
**Describe the bug**
The priest shadow talent Spirit Tap works even when you kill a grey mob that is worth no experience. 

**To Reproduce**
Kill a mob that is worth no experience to your character.

**Expected behavior**
Spirit Tap should only work on mobs that provide experience when killed.

**Comment by thezorlul** [comment]
To add to that, spirit tap only procs on mobs/player you deal the finishing blow to rather than every killed mob/player you're involved in fighting that grants exp/honor.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
