### ISSUE TITLE
Creeping Ooze in Shattered Halls

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2031]
"Sticky Ooze" debuff they put on you does not function, does not reduce your movement speed.

**Comment by Jerrythemagicdog** [comment]
Thanks, the slow component actually worked, just that there were multiple auras applied for different Creeping Oozes casting it.
With the next restart there will only be one stack that all of them will contribute to which will apply the full effect of the slow faster.
Thanks for the issue!
