### ISSUE TITLE
greed roll won gear over need roll

### ISSUE THREAD

**Issue by DepressionTheWarlock** [SunstriderEmu/BugTracker#2032]
**Describe the bug**
Loot rolled went to a greed roll over a need roll
From hellfire ramparts chest
**To Reproduce**
1. looted chest in hellfire ramparts
2. 
3. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
24063 went to greed roll over need roll

**Expected behavior**
need roll should be prioritized over greed rolls 

**Screenshots/videos**
https://imgur.com/a/6PzfyH6

**Additional context**

**Comment by SUN-Leekie** [comment]
The 92 need roll won it. You won another item.

**Comment by DepressionTheWarlock** [comment]
so the hunter rolled a need on the shifting sash of midnight but after the run i had that belt in my bags

**Comment by DepressionTheWarlock** [comment]
and the hunter did not

**Comment by SUN-Leekie** [comment]
Weird thing going on with everyone passed.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3532

**Comment by z5n** [comment]
looks related to #4599

**Comment by z5n** [comment]
closing in favor of #4599
