### ISSUE TITLE
Hunter Pet Has Negative Training Points At Max Loyalty

### ISSUE THREAD

**Issue by igotdatdingleberry** [SunstriderEmu/BugTracker#2033]
Describe the bug
Taming another pet causes the new pet to have negative loyalty points

To Reproduce

1. Stable/Abandon Original Hunter Pet
2. Tame a new one
3. Pet will have a large amount of negative training points

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
N/A

Expected behavior
Hunter pet should have spendable loyalty points at loyalty levels greater than 1

Screenshots/videos
https://imgur.com/rj9STh5

Additional context
Does not occure with first pet but occurs with ones after.

**Comment by lukas155** [comment]
Also having this issue. Pet has max loyalty and still has negative training points. Impossible to train new pets any new abilities past the ones they come with. Fairly high priority bug.

**Comment by Predestinator77** [comment]
Same problem here. Ravenger caught at outland has deep negative TP and I can't teach him anything else except the Growl. Please tell us how to fix.

**Comment by lukas155** [comment]
I believe this only happens when you tame a pet that has pre learnt abilities. I tried taming a pet with no abilities, and upon leveling up loyalty, had positive loyalty points.

**Comment by artieau** [comment]
Fixed in a previous update.
