### ISSUE TITLE
Chose Scryers as Drenei but Scryer camp still attacks eventho Neutral

### ISSUE THREAD

**Issue by adorj4n** [SunstriderEmu/BugTracker#2035]
**Describe the bug**
Drenei Shaman.  I chose to align with Scryers.  After becoming 'Neutral' I still cannot talk to anyone in Shattrath.  Additionally, in Shadowmoon Valley when you try to talk to NPC or use Flight Path, the arrow comes up as the attack cursor and you cannot talk to any npcs as they will attack you back.

**To Reproduce**
1. Cast X on target affected by ...
2. 
3. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by SUN-Leekie** [comment]
Is this still happening?

**Comment by adorj4n** [comment]
No, it’s been resolved.  After making this post, the following day I was no
longer at war with my own faction.  I was still set back a bit due to the
reputation error but it’s fixed now

**Comment by SUN-Leekie** [comment]
Thanks!
