### ISSUE TITLE
[Hunter] Gamebreaking Ranged Crit Chance Calculation?

### ISSUE THREAD

**Issue by Exorcista** [SunstriderEmu/BugTracker#2036]
**Describe the bug**
Ranged crit chance not shown properly on character window, maybe is only visual but it seems to not be the case.

**To Reproduce**
Steps to reproduce the behavior: literally dont know, it stoped working randomly

**Expected behavior**
Should remain constant in the window of the character and not be affected by anything randomly.

**Screenshots/videos**
So my gear as a hunter is almost everything with agi, yet this is my crit chance:

https://ibb.co/wpbYy0H
https://ibb.co/rmgFM37

**Additional context**
Tried: relogin, relogin + clearing cache folder, reloading ui. removing my gear and then putting it back in. Nothing seem to fix it

**Comment by Ironjudgment** [comment]
works fine for me
![image](https://user-images.githubusercontent.com/33090790/75763546-53924980-5d34-11ea-853e-a3d4d799de27.png)

**Comment by Exorcista** [comment]
Update: as your weapon (ranged) skill increases it reaches the number it should have. I've never seen this in any other server.
