### ISSUE TITLE
Quest: Voren'thal's Visions should be repeatable

### ISSUE THREAD

**Issue by adorj4n** [SunstriderEmu/BugTracker#2037]
**Describe the bug**
Completed quest to turn in 8 Basilisk Eyes from Arcanist Adyria (Scyer Rep while Neutral).  This quest is supposed to be repeatable but currently it is not.
**To Reproduce**
1. Cast X on target affected by ...
2. 
3. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by beraus** [comment]
This quest is only available to characters hostile to The Scryers

At hostile: http://prntscr.com/u6jyla
At neutral: http://prntscr.com/u6jyek
