### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by steffengo** [SunstriderEmu/BugTracker#2038]
Chat is broken. No matter what Account, Toon or Client of TBC I use (with and without addons) I can't chat in /1 etc. I did try to delete my main cache / Logs. I did reinstall the Client. I did delete chat cache. I did copy chat cache from a working client (friend). Nothing helped.

**Comment by bisquiit** [comment]
Evryone has the issue its a known problem

**Comment by kelno** [comment]
Duplicate https://github.com/SunstriderEmu/BugTracker/issues/2089
