### ISSUE TITLE
blessing of might is replaced by hand of freedom

### ISSUE THREAD

**Issue by Vandeanson** [SunstriderEmu/BugTracker#2039]
**Describe the bug**
blessing of might is replaced by BLESSING of freedom (at lvl 26)

**To Reproduce**
1. cast Blessing of Might on yourself
2. cast Hand of Freedom on yourself

blessing of might is removed

**Comment by Gotemniggadro** [comment]
Well considering it's called BLESSING of Freedom it replaces the blessing on the target.

**Comment by Godmatik** [comment]
Works as intended.

You can only have one blessing on at a time.

It's called Blessing of Freedom, not Hand of Freedom. They didn't transition to "hands" to not overwrite other buffs until WotLK.
