### ISSUE TITLE
Weird behaviour with quest status

### ISSUE THREAD

**Issue by SUN-Leekie** [SunstriderEmu/BugTracker#204]
Reproducing steps:
* `.quest add 10344`
* Give up the quest
* `.go c id 20234`
* See the "? Wing Commander Gryphongar", but that's the NPC giving the quest you just abandonned 🤔

**Comment by kelno** [comment]
Seems fixed.
If you're testing this, note that the quest only validates when properly accepted from the previous npc (id 20234) and not with a quest add.
