### ISSUE TITLE
STV zep to UC drops you off at the edge

### ISSUE THREAD

**Issue by nhthor** [SunstriderEmu/BugTracker#2041]
The zeppelin from STV to UC will drop off character at the very edge of STV causing players to fall off and die.

**Comment by SUN-Leekie** [comment]
Is it happening 100% of the time or you got unlucky somehow?

**Comment by bisquiit** [comment]
How is this not fixed its a known bugg since  opening of the server...

**Comment by SUN-Leekie** [comment]
It would help a lot to have more information on this.

**Comment by artieau** [comment]
Duplicate of #445
