### ISSUE TITLE
[NPC][Shattrath] Marksman Bova

### ISSUE THREAD

**Issue by Ironjudgment** [SunstriderEmu/BugTracker#2042]
**Describe the bug**
An NPC is missing in Aldor Rise which sells arrows/ammunition.

**Expected behavior**
There should be a vendor NPC at Aldor Rise with arrows and ammunition from various reputations for sale.

**Screenshots/videos**
NPC not being there.
![image](https://user-images.githubusercontent.com/33090790/75764547-eda6c180-5d35-11ea-91de-ad9be5fed133.png)

**Additional context**
https://wow.gamepedia.com/Marksman_Bova
![image](https://user-images.githubusercontent.com/33090790/75764605-031beb80-5d36-11ea-91f9-63b7c9f324e8.png)

**Comment by Ironjudgment** [comment]
On another note, I have also noticed that the repair npc beside the innkeeper is also missing but after further research I have found that he has only been added in 2.4 but perhaps for the sake of convenience he could be impemented early. 
https://wowwiki.fandom.com/wiki/Technician_Halmaha

**Comment by SUN-Leekie** [comment]
As you can see, he's supposed to spawn in patch 2.4.
We are still in patch 2.0 so working as intended.

**Comment by Ironjudgment** [comment]
He is supposed to change appearance in 2.4, not spawn. He has been added in 2.0.3.

**Comment by Ironjudgment** [comment]
It's literally in the picture.

**Comment by SUN-Leekie** [comment]
I read that too but if Marskman Bova is not implemented right now, neither will Technician Halmaha.

**Comment by Ironjudgment** [comment]
They are two diffrent NPCs? One is supposed to be there in 2.0.3, the other in 2.4?

**Comment by SUN-Leekie** [comment]
Am I not getting something right because I can read Technician Halmaha implemented in 2.4.2 which is the repair guy next to the innkeeper.

**Comment by Ironjudgment** [comment]
I was talking about two different NPCs. One, which is Marksman Bova which sells arrows/ammunition (impemented in 2.0.3) and second which was engineering supplies (repair guy beside innkeep). That one was implemented in 2.4

**Comment by Ironjudgment** [comment]
Sooo... this shouldn't be closed?

**Comment by SUN-Leekie** [comment]
Yes, just had to go to work at some point 😅

**Comment by Ironjudgment** [comment]
Bump

**Comment by Ironjudgment** [comment]
He is here. closing this :]
