### ISSUE TITLE
Mage quest: Investigate The Blue Recluse

### ISSUE THREAD

**Issue by Mirthios** [SunstriderEmu/BugTracker#2043]
Rift Spawns are expected to appear when using the Cantation of Manifestation near a rift in the Blue Recluse. The Rift Spawns don't appear.

**Comment by Sheikthecatman** [comment]
Duplicate thread, a testfix is live. [See my comment](https://github.com/SunstriderEmu/BugTracker/issues/1907#issuecomment-598924715)
