### ISSUE TITLE
[BRD dungeon]

### ISSUE THREAD

**Issue by Hoppy56** [SunstriderEmu/BugTracker#2044]
The 2nd boss in arene event from BRD doesn't show, only the first one. The problem is; you're stuck in the arene after the 1st boss cause the 3 gate's are close.

**Comment by Hoppy56** [comment]
"Ring of the law" 
He say after the 1st gate add pack -> " Good riddance "  and disapear (so dosnt open 2nd gate boss)

**Comment by Sheikthecatman** [comment]
Thanks!
Fixed in [15121f2c2c521408ad7184054b5d4496ca829db1](https://github.com/kelno/sunstrider-scripts/commit/15121f2c2c521408ad7184054b5d4496ca829db1 )

**Comment by steak-house** [comment]
This is still occuring, I'm currently stuck in Ring of Law as we speak. We tried relogging, unstucking then coming back, gate was still closed.

**Comment by EL100** [comment]
Confirmed. see #613
