### ISSUE TITLE
Pala Seal of Blood / Seal of Command / Seal of Crusade scaling

### ISSUE THREAD

**Issue by DerMyn** [SunstriderEmu/BugTracker#2045]
Hey guys :) i love your server pls keep the good work up ! But i discoverd a bug with Seal of Blood Scaling . It scales with the gear but they dont scale with the jugdt Seal of Crusader debuff. Pls fix is it as quick as possible haha.
I also found another Bug with Seal of Crusader ( or my memory is just wrong here and you dont see it ) but when you skill Improved Seal of the Crusader if should weakend the target with a flat 3% crit increase buff for the Raid but it dosnt.Edit: SoC scaling also feels off wiht crusader but atleast its there.

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2393
