### ISSUE TITLE
Log fixer asked me to report so here I am :)

### ISSUE THREAD

**Issue by GawainXL** [SunstriderEmu/BugTracker#2047]
[15:24] Log Fixer: 91 filtered/724 events found. Cleared combat log, as it broke. Please report this! 
[15:25] Log Fixer: 21 filtered/120 events found. Cleared combat log, as it broke. Please report this! 
This happened on a level 5 Human Mage, called Gewain.

I do DC alot though, dunno if it is tied or not.

**Comment by Aeded** [comment]
Log fixer is an addon which is in no way connected to Endless server.

**Comment by GawainXL** [comment]
It came preinstalled though. When I first logged in, it was in my addons section.

**Comment by Godmatik** [comment]
This github is for reporting bugs for Endless server, you'll want to visit the github for that particular addon creator instead.
