### ISSUE TITLE
DC/Relog Graveyard

### ISSUE THREAD

**Issue by Kratuzov** [SunstriderEmu/BugTracker#2048]
While in a dungeon, sometimes randomly we get ported alive to the graveyard after DC or relog.
1. Wait for DC in a dungeon or relog/alt f4
2. Sometimes get ported to graveyard for no reason.

**Comment by Godmatik** [comment]
Confirmed.

I once relogged while inside of an instance, and came back to find I was completely teleported to the instance GY.

**Comment by Trolltilla** [comment]
The last guy to log in an instance always gets ported outside. Very annoying

**Comment by z5n** [comment]
related to #1588
