### ISSUE TITLE
Paladin Talents broken

### ISSUE THREAD

**Issue by Nicholas96R** [SunstriderEmu/BugTracker#2049]
Both talents Sanctity Aura and improved seal of the crusader are not functional

Sanctity Aura does absolutely nothing when active.
And the talent for improved seal does not apply on the target.

**Comment by saltemporium** [comment]
Improved Blessing of Might is also not granting the bonus Attack Power for me.

**Comment by Jerrythemagicdog** [comment]
Fixed a long time ago, thanks for the issue.
