### ISSUE TITLE
350 skill engineering helms

### ISSUE THREAD

**Issue by Avishai97** [SunstriderEmu/BugTracker#2051]
**Describe the bug**
Engineering trainers don't have the Deathblow X11 Goggles that you said was gonna be available on this server.

**To Reproduce**

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://www.wowhead.com/item=32478/deathblow-x11-goggles

**Expected behavior**
Trainable at teacher

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by SUN-Leekie** [comment]
They have been added!
