### ISSUE TITLE
[Quest] Commander Ameer doesn't start next quest after completing A Mission of Mercy

### ISSUE THREAD

**Issue by Trolltilla** [SunstriderEmu/BugTracker#2052]
**Describe the bug**
After you complete A Mission of Mercy quest in netherstorm for Commander Ameer he doesn't start the next quest called Ethereum secrets

**To Reproduce**
1. Get Honored reputation with the consortium. 
2. Start a mission of mercy quest and complete it
3. You can't take the next quests in the chain

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

https://tbcdb.com/?quest=10971
https://www.wowhead.com/quest=10971/ethereum-secrets

**Expected behavior**
We should get the next quest in the quest line.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by SUN-Leekie** [comment]
The quest will be available when patch 2.1 hits.
