### ISSUE TITLE
[Dungeon][Boss] Pathaleon the Calculator [19220]

### ISSUE THREAD

**Issue by herodope** [SunstriderEmu/BugTracker#2054]
**Describe the bug**

You can stun and fear Pathaleon the Calculator (19220)

**To Reproduce**

1. Cast stun or fear on NPC ID 19220

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

19220

**Expected behavior**

This is a boss, so you shouldn't be able to CC him at all.

**Comment by SUN-Leekie** [comment]
Fixed, thanks!
