### ISSUE TITLE
[Dungeon][Boss] Warp Splinter [17977]

### ISSUE THREAD

**Issue by herodope** [SunstriderEmu/BugTracker#2055]
**Describe the bug**

You can stun Warp Splinter (17977).

**To Reproduce**
1. Stun, HoJ or Kidney the boss.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

17977

**Expected behavior**

This is a boss, should not be stunnable.

**Screenshots/videos**

N/A

**Additional context**

N/A

**Comment by Bzmode** [comment]
Also adds are way too fast and hit super hard.

**Comment by SUN-Leekie** [comment]
Confirmed for normal mode.

**Comment by SUN-Leekie** [comment]
Fixed at next restart.
