### ISSUE TITLE
[Gamebreaking][Priest] Mind Control

### ISSUE THREAD

**Issue by herodope** [SunstriderEmu/BugTracker#2056]
**Describe the bug**

Priest mind control disables the AI of any monster you use it on after it is removed.

**To Reproduce**
1. Cast mind control on any mob. 
2. Release the mind control.
3. It will then become passive but still attackable.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

Any creature that can be affected by Priest Mind Control.

**Expected behavior**

The mobs AI should not break.

**Screenshots/videos**

N/A easily reproduceable.

**Additional context**

**Comment by kelno** [comment]
Fixed
