### ISSUE TITLE
[Warlock] Enslave Demon

### ISSUE THREAD

**Issue by herodope** [SunstriderEmu/BugTracker#2057]
**Describe the bug**

You can enslave demon the demons outside the Dark Portal, which hit for incredibly high damage.

**To Reproduce**
1. Cast Enslave Demon on any NPC outside the Dark Portal.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

These should be immune to Enslave Demon, or not hit for thousands of damage.

**Comment by Sheikthecatman** [comment]
The issue should be resolved in 8a6bdf99e2c3d40e2fbea535d96846d2fbda3a1d (scripts)
If not, then please specify which creatures you are having issues with.
