### ISSUE TITLE
[Quest][Bug] Bloodgem Crystals [10204]

### ISSUE THREAD

**Issue by herodope** [SunstriderEmu/BugTracker#2058]
**Describe the bug**

The Blood Gem crystal has a fairly low drop rate. Once you do acquire one, it starts the channel animation, but instantly breaks and does not work.

**To Reproduce**
1. Begin quest 10204
2.  Use quest item 28452
3. ???

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

Quest [10204]
Quest Item [28452]

**Expected behavior**

When you drain a blood gem crystal, it should channel then complete the quest.

**Comment by Liirslo** [comment]
Tried this quest a few times. What I think happens is that when you start channeling if it turns you towards the crystal it immediately stops the channel, perhaps it registers as movement? The way I got it working I alligned myself with crystal straight in front of me and it channeled full duration.

**Comment by wiglefish** [comment]
Confirming what Liirslo said. Looking at 1 and alligning it with an inner crystal will make the q work.

**Comment by aqes55324** [comment]
fix it please

**Comment by Jerrythemagicdog** [comment]
Quest worked as long as you face the crystal at the beginning of channelling.
With next restart it won't interrupt you on turning anymore.
Thanks for the issue.
