### ISSUE TITLE
[Dungeon][Boss] Blackheart the Inciter [18667]

### ISSUE THREAD

**Issue by herodope** [SunstriderEmu/BugTracker#2059]
**Describe the bug**

Blackheart the Inciter [18667] can be stunned. His mind control is also a bit strange.

**To Reproduce**
1. Cast any stun, it should work

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

18667

**Expected behavior**

As a boss, he should be stun immune.

**Comment by SUN-Leekie** [comment]
Fixed, thanks!
