### ISSUE TITLE
[Dungeon][Question][Research Needed] Adds summoned in Dungeons

### ISSUE THREAD

**Issue by herodope** [SunstriderEmu/BugTracker#2060]
**Describe the bug**

Any add summoned in a dungeon appears to be using their heroic damage coefficient instead of normal damage coefficient. Examples include succubus summons, void walker summons, the mana beast summons from the first trash pack in Mechanar.

Please note I will update this bug report with more in depth creature IDs, examples etc. Need to gather more data

**To Reproduce**

1. Aggro the first pack in Mechanar on normal difficulty, the elementals the astromancer? nethermancer? summons are hitting incredibly hard.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

TBA

**Expected behavior**

TBA

**Comment by SUN-Leekie** [comment]
Can you provide some screenshots about your combat log with their damage? I don't see anything hitting super hard.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
