### ISSUE TITLE
Quest: Ashenvale Outrunners is not working?!

### ISSUE THREAD

**Issue by BigBratan** [SunstriderEmu/BugTracker#2061]
**Describe the bug**
I just took the quest "Ashenvale Outrunners" from Kuray'bin at the Splintertree Outpost. Goal is to slay 9 Ashenvale Outrunners. The Problem is, I can see the mobs but I can't attack them. I can take them into my target but I am not able to use attacks on them.
I guess this is bugged. Nothing big but I just wanted to let you know :)
Greetings
Icedout

**Comment by SUN-Leekie** [comment]
Is it still happening? I can't reproduce. :/

**Comment by InhumanGM** [comment]
Unable to reproduce.
