### ISSUE TITLE
Warlock Quest - Hearts of the Pure

### ISSUE THREAD

**Issue by AC619** [SunstriderEmu/BugTracker#2064]
**Describe the bug**
Unable to kill NPCs for the quest Hearts of the Pure

**To Reproduce**
1. The NPCs are unable to be attacked

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

https://classic.wowhead.com/quest=1476/hearts-of-the-pure

**Expected behavior**
Able to kill for quest items

**Additional context**

**Comment by SUN-Leekie** [comment]
Is it still happening? I can't reproduce.

**Comment by InhumanGM** [comment]
Unable to reproduce.
