### ISSUE TITLE
Shadowmoon elementals doesn't drop Plans: Ragesteel Shoulders.

### ISSUE THREAD

**Issue by AWIDIUS** [SunstriderEmu/BugTracker#2065]
![image](https://user-images.githubusercontent.com/45521546/75810224-7bac9780-5d8a-11ea-926b-c6a1d12283b4.png)
I've killed over 250 of these mobs that should drop Plans: Ragesteel Shoulders and yet still no pattern.

According to DB https://tbcdb.com/?item=33174 It should have 3% droprate which clearly doesn't correspond with what is on live server.

**Comment by SUN-Leekie** [comment]
Loot chance at 0.5-1% so you're unlucky :/
We do not consider tbcdb a valid source.

**Comment by AWIDIUS** [comment]
Do the mobs have this Pattern even in their loot table ? So i can be headlessly farming in hope i might get it.

**Comment by SUN-Leekie** [comment]
Yes, as I said it's 0.5-1%, good luck!

**Comment by SUN-Leekie** [comment]
However they were added in Patch 2.2 which is fixed now, so not lootable anymore.

**Comment by AWIDIUS** [comment]
Like Dragonstrike One Hand is 2.0 or goggles are right ?

**Comment by AWIDIUS** [comment]
2.2 patch was nothing but voice communication, few fixes and this pattern. I do not see any reason to not release this pattern yet is allowing players to skill up BS more easily, also adds preBIS shoulders for plate Dps

**Comment by AWIDIUS** [comment]
We can make server pure 2.0 clown fiesta with all shit restricted. Np

**Comment by AWIDIUS** [comment]
![image](https://user-images.githubusercontent.com/45521546/76154199-b0955300-60d8-11ea-9848-364c3429941a.png)
@SUN-Leekie  Yes, then it drops actually :)

**Comment by AWIDIUS** [comment]
So basically you telling us, that now you blocked whole chance of drop for this pattern although some people have it, so they can abuse it so hard, then they can make thousands of golds off it since the pattern is basically unobtainable right now. Well played.

**Comment by AWIDIUS** [comment]
Sorry for all accuses, pattern dropped off second mob once I went back there.
![image](https://user-images.githubusercontent.com/45521546/76154303-6dd47a80-60da-11ea-978f-583586dd5b4b.png)
