### ISSUE TITLE
Quest: Darnassian Intrusions 

### ISSUE THREAD

**Issue by Aerath318** [SunstriderEmu/BugTracker#2066]
**Describe the bug**
For the quest Darnassian Intrusions (Eversong Woods) kill one Darnassian Scout, to complete the quest. When found a stealthed Scout they are only targetable and not attackable. Cannot enter combat to complete the quest. 

**To Reproduce**
1. Accept quest from Aeldon Sunbrand at Falconwing Square
2. Go to the West Sanctum, and find a Darnassian Scout (They are stealthed)
3. Target it and try to attack

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://www.wowhead.com/quest=9352/darnassian-intrusions

**Expected behavior**
NPC should either aggro you to ambush, or be able to be hit out of stealth.

**Screenshots/videos**
![World Of Warcraft Screenshot 2020 03 03 - 22 41 56 95](https://user-images.githubusercontent.com/61760821/75823799-adc9f380-5da2-11ea-9b69-4ad9efccd7b2.png)

**Additional context**
I believe it's a part of a chain to unlock some new quest later. Might be wrong.

**Comment by SUN-Leekie** [comment]
Is it still hapenning? I can't reproduce.

**Comment by beraus** [comment]
[Couldn't reproduce.](http://prntscr.com/u6k0br)
