### ISSUE TITLE
a me 01 in ungoro

### ISSUE THREAD

**Issue by beryltech** [SunstriderEmu/BugTracker#2068]
a me 01 escort  in ungoro has to far pullrange, making the escort 10 min long, and it moves to slow

**Comment by SUN-Leekie** [comment]
Is that really off?
https://www.youtube.com/watch?v=fgCugD4O0Rg

**Comment by beryltech** [comment]
> 
> 
> Is that really off?
> https://www.youtube.com/watch?v=fgCugD4O0Rg

The respawn rate on the apes on classic is much slower
on sunstrider the escort ape nearly get stuck because of the cluster of mob apes

**Comment by SUN-Leekie** [comment]
Well that's a different problem then.
