### ISSUE TITLE
[General] Chain spells chain into critters

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#2069]
**Describe the bug**
Title. 

**Expected behavior**
Chain effects should not chain to critters.

"Critters: Ambient level 1 creatures will no longer be picked as subsequent targets by chaining spells and abilities."
https://wowwiki.fandom.com/wiki/Patch_2.4.0

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/4218
