### ISSUE TITLE
[Shaman] Elemental mastery when oom

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#2070]
**Describe the bug**
When you dont have enough mana to cast chain lightning, and you use macro
/use Elemental Mastery
/use Chain Lightning
you have to press the macro twice, because on first press you get an error message that you dont have enough mana. On second press you it works.

**Expected behavior**
Should be able to cast chain lightning on first use of the macro

**Comment by z5n** [comment]
still confirmed rev. 35257

**Comment by kelno** [comment]
I don't think that could ever work, the client itself doesn't even try to cast the spell.
