### ISSUE TITLE
[Dungeon] Shattered Halls Gladiator packs

### ISSUE THREAD

**Issue by eepoo** [SunstriderEmu/BugTracker#2071]
**Describe the bug**
Two of the gladiator packs in the area after the first boss are linked for some reason. If you pull either of the packs both of them will aggro. I've included a screenshot of the minimap showcasing the two packs that are linked.

**To Reproduce**
1. Clear the middle hallway in the gladiator area.
2. Pull either of the packs marked with blue on the screenshot.
3. Witness both of them aggroing on your party.

These are the mobs included in the packs.
https://tbcdb.com/?npc=17464
https://tbcdb.com/?npc=17465

**Expected behavior**
Only the 4 gladiators and the centurion should aggro.

**Screenshots/videos**
[https://cdn.discordapp.com/attachments/260378640494100480/684534832029499396/unknown.png](url)

**Comment by SabreValkyrn** [comment]
Can confirm, hit this yesterday.

**Comment by Godmatik** [comment]
Confirmed

**Comment by SUN-Leekie** [comment]
Fixed, thanks for the report!
