### ISSUE TITLE
Unable to tame pet: Quillfang Skitterer

### ISSUE THREAD

**Issue by lukas155** [SunstriderEmu/BugTracker#2074]
The lv 61 Quillfang Skitterers in HFP are untamable by hunters.

**To Reproduce**
1. Cast "tame Beast" on aforementioned mob
2. At end of cast, instead of pet becoming friendly, receive an error "that mob is hostile" or something to that effect.

https://www.wowhead.com/npc=19189/quillfang-skitterer

**Expected behavior**
Mob should become hunter's pet.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Works correctly, clear your Cache thanks.
