### ISSUE TITLE
mind controlling guards in cenarion refuge and using them to pvp

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#2075]
standing deep inside the inn at cenarion refuge.  guard walks in and attacks me.  first time i wasnt  sure what happened, second time it looked like MC.  3rd time looked like it agro'd on to me from outside somehow.  i was doing nothing at the time, no healing, no buffing, no casting of any kind.  no lightning shield or earth shield nothing.  

guards should not attack players who are not fighting.

**Comment by kelno** [comment]
Confirmed, getting MC'd count as hostile action for the guards

**Comment by kelno** [comment]
Did a quick fix, need more testing
