### ISSUE TITLE
Dead-tooth Jack quest bugged

### ISSUE THREAD

**Issue by namnamu97** [SunstriderEmu/BugTracker#2077]
Hi, 
Cannot open Dead-tooth strong box for the quest. The dead-tooth key disappear after my failed attempt

**Comment by kosperskij** [comment]
The same problem "Cannot open Dead-tooth strong box for the quest. The dead-tooth key disappears after my failed attempt".

**Comment by Jerrythemagicdog** [comment]
Can't reproduce, seems like a Cache issue.
