### ISSUE TITLE
You can walk past locked doors

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2078]
Logout in front of locked door.
Log back in, walk forward before door fully appears.

Works on doors such as Arcatraz

**Comment by alanparrish** [comment]
any upcoming fix for this? people abusing this basically 24/7 in any given instance, SHH/Arca/BF etc, please fix asap

**Comment by Godmatik** [comment]
Gonna bump again, people abusing this hard in heroics. You can skip right to the last boss in some as a result.

**Comment by beraus** [comment]
This issue should be fixed now.
