### ISSUE TITLE
Linking Crafting recipes from your own professions

### ISSUE THREAD

**Issue by Denagul** [SunstriderEmu/BugTracker#2079]
**Describe the bug:** Trying to shift-click to link a recipe from your professions cannot be typed into chat

**How to reproduce:** Shift click on a profession skill in your profession tab (not the item itself) while chatting to someone either in whisper/guild/say etc. then press enter.  It should be the yellow text saying something like [Leatherworking: Light Armor Kit].

**What should Happen:** We should be able to link profession crafting from our own profession indexes in any chat.

**Comment by kelno** [comment]
Should be fixed. Didn't test for each profession yet
