### ISSUE TITLE
Mindflay removes frostbolt slow

### ISSUE THREAD

**Issue by thezorlul** [SunstriderEmu/BugTracker#2081]
**Describe the bug**
Mind flay overrides and removes the slow effect of frostbolt, it makes no difference if the target has points in permafrost or not. Neither does it matter which rank of mind flay or Frostbolt is casted.

**To Reproduce**
1. Cast frostbolt on target.
2. Cast mind flay on target.
3. Frostbolt slow gets removed.

Like I said, it doesn't matter which rank of either its casted.

**Expected behavior**
Only the stronger slow should affect the target but neither should be removed.

**Screenshots/videos**
I can't make those RN but if necessary I'll add them later.

**Additional context**
I would assume this could be the case with more slow effects but this is just a guess.

**Comment by Jerrythemagicdog** [comment]
Mind Flay slow amount is 50%, Frostbolt with Permafrost is 50%, is there a reason why the same amount of slow should not be overriden by a new effect being applied?

**Comment by thezorlul** [comment]
I have never seen a slow with the same % actually remove another slow. That would mean piercing howl would remove hamstring or vice versa. The stronger slow should be active but not remove the other debuff. One slow might last longer than the other, like in this case with mindflay and frostbolt.

**Comment by Jerrythemagicdog** [comment]
That's wrong, current behaviour is consistent with how it worked on retail (and probably still does to this day).
