### ISSUE TITLE
Auction house filtering

### ISSUE THREAD

**Issue by septembr** [SunstriderEmu/BugTracker#2082]
**Describe the bug**
When filtering items in the auction house on for example 'uncommon' it only shows items from that quality. Filtering on 'rare' only shows rare items, etc. 

**To Reproduce**
1. Go to auction house and find a category that has both uncommon and rare quality items, and filter on 'uncommon', 'all', and 'rare'.
2. 
3. 

**Expected behavior**
When filtering on quality it should show "uncommon quality and above" if filtering on 'uncommon', ie showing uncommon, rare, epic, and legendary (lol) quality items. Now it **only** shows items of the quality that is filtered on.

**Comment by thezorlul** [comment]
To add to that, you can't search for suffixes like "of the x", no items come up if you do that

**Comment by mechanicsTBC** [comment]
can this be looked into.  the searching for specific suffixes in particular

**Comment by z5n** [comment]
when filtering by rarity, it should only return items that match the rarity you selected—i.e. if you filter for Uncommon items, it should and currently does only return Uncommon items
