### ISSUE TITLE
Scryers reputation/Sunfury Signets

### ISSUE THREAD

**Issue by Kratuzov** [SunstriderEmu/BugTracker#2083]
**Describe the bug**
After accepting quest to get reputation with Scryers, it is impossible to continue further. Magistrix Fyalenn should give out quest for delivering Sunfury Signets for level 70. Only thing she offer is quest for Firewing Signets which are for lvl 68-.

**To Reproduce**
1. Get first quest to be attuned for Scryers.
2. Go to Magistrix Fyalenn
3. Click on her to see she doesnt offer the quest

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://www.wowhead.com/npc=18531/magistrix-fyalenn

**Expected behavior**
Until level 68, Magistrix should offer Firewing Signets. After lvl 68 she shouldnt be able to give quest for Firewing Signets, instead she should give quest for Sunfury Signets.

**Screenshots/videos**
https://prnt.sc/rbcp42

**Comment by SUN-Leekie** [comment]
You need to be honored.
