### ISSUE TITLE
Defiance not working properly

### ISSUE THREAD

**Issue by Inyu** [SunstriderEmu/BugTracker#2084]
**Describe the bug**
Defiance doesn't add expertise in battle- and berserkerstance

**To Reproduce**
1. specc into Defiance https://tbcdb.com/?spell=12789

**Expected behavior**
the talent should provide expertise in all stances this was changed in 2.3.2
https://wowwiki.fandom.com/wiki/Patch_2.3.2

**Screenshots/videos**
can provide screenshot at a later date if needed

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
