### ISSUE TITLE
Spirit Totem (alliance shaman class quest)

### ISSUE THREAD

**Issue by Whiskeyx** [SunstriderEmu/BugTracker#2085]
**Describe the bug**
The drop rate for the quest items being Bloodshot Spider Eye and Thick Black Claw from the diseased black bear's and the venom mist lurker's in western plague lands are not benefiting from the increased quest item drop rate. I have been killing spiders and bears for over an hour and have only reached 4/8 and 5/8. 

**To Reproduce**
1. Just kill the enemies required and watch the quest item not drop consistently.

https://www.wowhead.com/quest=8412/deprecated-spirit-totem

**Expected behavior**
Should not take over an hour to complete quest.

**Screenshots/videos**

**Additional context**

Not problem related*** Keep up the good work! you guys are doing great!

**Comment by SUN-Leekie** [comment]
It's still a quite low loot drop of 20% so 40% for Alliance, would you say that corresponds to your experience?
