### ISSUE TITLE
stealth from prowl too week

### ISSUE THREAD

**Issue by ageerik** [SunstriderEmu/BugTracker#2086]
The range at which mobs detect you while in prowl is way too long, I am a night elf with stealth talents and I can still not run pass mobs at my own lvl. 
Been playing a lot of other private servers and live since vanilla and prowl is too week here.

**Comment by kelno** [comment]
Thanks for reporting!
Our stealth system has been very much researched, but it could still have issues.
We need proof and data to adjust the range if it's invalid. Other privates servers are definitely not a valid proof of what the range should be.
Retail videos can be valid proofs (either from TBC era or from Classic).

**Comment by miki-g** [comment]
prowl still broken, 10+ yards to detect is bug, prowl is here copmpletely useless
