### ISSUE TITLE
Dark Portal

### ISSUE THREAD

**Issue by septembr** [SunstriderEmu/BugTracker#2088]
**Describe the bug**
The Dark Portal (outlands version in Hellfire Peninsula) doesn't allow you to walk through it back to Azeroth and the Blasted Lands 

**To Reproduce**
1. Go to the Dark Portal in Hellfire Peninsula
2. Try to walk through it.

**Expected behavior**
When walking through the Dark Portal in Hellfire Peninsula you should end up in the Blasted Lands in Azeroth.

**Comment by SUN-Leekie** [comment]
Need more information as I cannot reproduce.
