### ISSUE TITLE
Quest: The Bloodcursed Naga

### ISSUE THREAD

**Issue by Ratmus** [SunstriderEmu/BugTracker#2090]
This questgiver must give buff for underwater breath and swiming speed!
https://www.wowhead.com/quest=9674/the-bloodcursed-naga 

Note: should also have a gossip option to retake the buff.

**Comment by Sheikthecatman** [comment]
The captain now kisses you on the cheeks upon accepting the quest. [d2b07c3c1467d07bd99842ff8d6028148dd705b5](https://github.com/kelno/sunstrider-scripts/commit/d2b07c3c1467d07bd99842ff8d6028148dd705b5)
