### ISSUE TITLE
Vampiric Embrace healing resist

### ISSUE THREAD

**Issue by Alccmtn** [SunstriderEmu/BugTracker#2091]
Friendly party members can resist healing gained through Vampiric Embrace. The chance to resist is apparently increased by shadow protection buffs.

**Comment by SUN-Leekie** [comment]
Tried it with a party member in full shadow resist gear and it didn't increase the chance.
From combat log:
> 19:58:51> Zumwa [Vampiric Embrace] missed lolol. (Resisted)

**Comment by Jerrythemagicdog** [comment]
Could've only happened if a player had an immunity effect (for example Divine Shield) which was fixed since then. Thanks for the issue.
