### ISSUE TITLE
Freedom removes Greater Blessings

### ISSUE THREAD

**Issue by Shyve** [SunstriderEmu/BugTracker#2094]
**Describe the bug**
Casting freedom on a friendly target with a Greater Blessing of x removes the Greater Blessing of x from the friendly target.

**To Reproduce**
1. Cast Greater Blessing Of X on friendly target
2. Cast Freedom on the friendly target
3. The greater blessing buff will then be removed

**Expected behavior**
Buff Greater Blessing of x > Buff Freedom on same target > Greater Blessing of x is gone

**Screenshots/videos**
https://youtu.be/IQKiVNN46QI

**Additional context**
Seems like Sacrifice also removes Freedom from a friendly target (see video).

**Comment by thezorlul** [comment]
thats how its always been in tbc, only 1 "blessing" per paladin per character, that inclused greater blessings

**Comment by Shyve** [comment]
Great. Just proves that i'm dumb. Thanks a lot, @thezorlul!
