### ISSUE TITLE
Melee monster doing ranged attack

### ISSUE THREAD

**Issue by VSteeph** [SunstriderEmu/BugTracker#2096]
**Describe the bug**
The following monster can do melee attack at range : 
- Panther (@Strangleronce Vale)
- Zanzil Naga (@Strangleronce Vale)

They can do normal attack, harmstring and kick at distance

**To Reproduce**
Attack one of the following monster at range with a mage ffor instance

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://classic.wowhead.com/npc=1491/zanzil-naga
https://classic.wowhead.com/npc=736/panther?classicRedirect

**Comment by VSteeph** [comment]
Dunemaul brute aswell (@tanaris)
https://classic.wowhead.com/npc=5474/dunemaul-brute

**Comment by InhumanGM** [comment]
Upon reproducing the issue, I was only able to verify the Zanzil Naga (_ID: 1491_) as the bugged creature, using a melee attack called Hamstring on me from ranges that it should not be able to hit me from.

I was not able to reproduce the issue with the Panther or the Dunemaul Brute.

**Comment by Sheikthecatman** [comment]
The AI for Zanzil Naga has been updated, The other ones do not have the same issue.
