### ISSUE TITLE
Can't use portal if mage already ported in it

### ISSUE THREAD

**Issue by b0rnless** [SunstriderEmu/BugTracker#2097]
**Describe the bug**

When you cast Portal: Theramore, your party members aren't able to click on it. 

**To Reproduce**
1. Be Alliance
2. Cast Portal: Theramore
3. See if party members are able to teleport to Theramore with it. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

Your party members should be able to teleport to Theramore by clicking on the portal.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by kelno** [comment]
Possible bug:
I hear the portal doesn't work anymore if the mage already ported in it

**Comment by kelno** [comment]
Should be fixed now

**Comment by hufsa** [comment]
To dev: the problem is the GetOwner() call only looking for owner in that map.

**Comment by artieau** [comment]
Tested and works fine now
