### ISSUE TITLE
Hunter pet disappeared

### ISSUE THREAD

**Issue by Aneko1** [SunstriderEmu/BugTracker#2098]
Hunter pet was completely removed from character.  Summoned & abandoned new pet. Attempted to summon old pet but old pet was not in stable. 

**To Reproduce**
1. Used Hearthstone(pet will despawn but do not resummon pet)
2. go to stable master to call new pet(There will be no current pet in the current pet spot)
3. Place new pet in the current pet spot.
4. Summon new pet
5. Open stable master again(old pet never returns)

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
I expected my ravager https://www.wowhead.com/npc=17199/ravager-specimen to still be in my stable. Now I have to wait until 60 to tame a new one. If you decide to restore it, I would not mind in the slightest if it was a cool color like blue & yellow or purple & green.  💃 

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**
My draenei hunter's name is Aneko.

**Comment by beraus** [comment]
This issue should be fixed now.
