### ISSUE TITLE
Seal of Command

### ISSUE THREAD

**Issue by DollpartsFTP** [SunstriderEmu/BugTracker#2100]
**Describe the bug**
Does completely pathetic damage. (For real, Seal of Righteousness does more, even on a stunned target)
**To Reproduce**
Spec into seal of command... Watch and laugh as it procs for 10 damage and does less than a righteousness judgement.

**Expected behavior**
----What the talent and ability say it should do----

**Comment by Subzors** [comment]
So a problem with the damage numbers you are seeing is because scaling on seal of righteousness with seal of the crusader is way too high so that may be addressed soon after they get stability down also seal of command is very weapon dependent
