### ISSUE TITLE
The Black Morass: Chrono-Beacon

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2102]
The dragon summoned from using Chrono-Beacon sits there and does not engage any mob, unless the mob is out of combat and engages the summoned dragon first.

**Comment by SUN-Leekie** [comment]
Confirmed but it doesn't happen everytime I tried.

**Comment by analshadow** [comment]
we had 3 runs in a row that had it happen 5 times in a row

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
