### ISSUE TITLE
Warchief Kargath Bladefist - Shattered Halls

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2103]
The fight is poorly scripted currently.

He does not do his Blade Dance ability at all it seems. 

Halfway through the fight, he sat there and stopped performing all actions, didn't even do white hits, making the rest of the fight trivial, however a bit later about 10 adds ran into the fight (from perhaps the gauntlet earlier?). 

So we were able to kill him, even though we wiped after.

**Comment by beraus** [comment]
Fixed in https://github.com/SunstriderEmu/BugTracker/issues/2575
