### ISSUE TITLE
Quest: Suppression

### ISSUE THREAD

**Issue by Denagul** [SunstriderEmu/BugTracker#2105]
**Describe the bug**
Suppression doesn't have any prerequisites (it should) and it cannot be completed as the quest item Glowing Crystal Prison doesn't properly capture the doomguard. 

**To Reproduce**
1. Pick up Suppression from Daio the Decrepit in Blasted Lands
2. Run up to a Doomguard Commander and use Glowing Crystal Prison
3. Wait for the 20 second buff to finish on the doomguard
4. Nothing happens.

[Suppression](https://db.endless.gg/?quest=7583)
[Doomguard Commander](https://db.endless.gg/?npc=12396)
[Glowing Crystal Prison](https://db.endless.gg/?item=18601)

**Expected behavior**
After a delay of using the crystal prison on a doomguard, there should be an enslaved doomguard that you must bring back to Daio

**Comment by bugreporterx** [comment]
Has this issue even been considered by the staff? I don't think it has been addressed yet. Please fix this issue.

**Comment by Denagul** [comment]
Likely they have but believe it's a minor thing (unfortunately I agree with them). We'll be patient and eventually they'll get around to this one.

**Comment by Ironjudgment** [comment]
Still an issue

**Comment by teachmetolose** [comment]
I aggree this quest does not work as it should. As only start using "Glowing Crystal Prison" on Doomguard Commander, channeling starting but stopped immediately but timer still going as crystal still active, after 20 sec when channeling ends - nothing happen. 
at endless.gg server
How to end this quest? only from of this I started play for warlock? it's main last quest for warlocks, please fix that bug...

**Comment by hashblaster** [comment]
I had this fixed by messaging a GM.   Make a ticket and ask them nicely to complete the quest for you.  Thanks Beraus

**Comment by loweri** [comment]
And how do I make a ticket?

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
