### ISSUE TITLE
Can't turn in Sprinkle's Secret Ingredient

### ISSUE THREAD

**Issue by yolohse** [SunstriderEmu/BugTracker#2106]
The Noggenfogger quest seems off. I have picked up Violet Targan but i cant turn it in. The quest is ofc out of my level range but I should still be able to turn in and get the quest right?

![image](https://user-images.githubusercontent.com/59824709/75961746-db0dc300-5ec2-11ea-87de-27ad436d05cc.png)

**Comment by beraus** [comment]
This issue should be fixed now.
