### ISSUE TITLE
Druid Hots not ticking when refreshed too soon.

### ISSUE THREAD

**Issue by wiglefish** [SunstriderEmu/BugTracker#2107]
**Describe the bug**
When re-applying heal over time effects, the heal can get cancelled/delayed if the re-apply is not exactly after a healing tick. This means that heals with a 3 second tick time could potentially not tick for almost 6 seconds if reapplied a certain way. 
This can be game breaking in PvP.

**To Reproduce**
1. Cast Rejuvenation
2. Less than 3 seconds later, cast rejuvenation again

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
I have tested this with multiple ranks of Rejuvenation and Regrowth

**Expected behavior**
Healing ticks should continue as if the duration was just extended.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by SUN-Leekie** [comment]
Not in TBC.
See the rejuvenation reapplied in this video:
https://youtu.be/UYbmUicK_NQ?t=243
