### ISSUE TITLE
Spirit of Redemption

### ISSUE THREAD

**Issue by MarL337** [SunstriderEmu/BugTracker#2109]
Upon death while in spirit of redemption u cant cast any heals.

Earlier this week it worked fine, but now it's totally broken and a useless talent pretty much.

Please fix

**Comment by SUN-Leekie** [comment]
Could this be you were silenced upon dying?

**Comment by MarL337** [comment]
It happends 100% of the time as of now. Regardless of death and positioning.

**Comment by SUN-Leekie** [comment]
I tried it and it was able to cast.
What's not working is trying to cast something on yourself which is intended.
