### ISSUE TITLE
[Warsong Gulch] No extra honor from capping flags

### ISSUE THREAD

**Issue by Trolltilla** [SunstriderEmu/BugTracker#2110]
**Describe the bug**
No extra honor for capping flags

**To Reproduce**
1. Cast X on target affected by ...
2. 
3. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by hufsa** [comment]
This was a visual bug that has now been fixed. Not yet live though.
