### ISSUE TITLE
Full inventory completing quests

### ISSUE THREAD

**Issue by deandyre** [SunstriderEmu/BugTracker#2113]
When you try to comlete a quests with a reward and your bags a full, it will tell you so. When you delete something from your back and complete again, it doesn't respond. Then you have to close the window and speak with the NPC anew.

**To Reproduce**
1. Have a full inventory.
2. Talk with your questgiver and press complete quest.
3. Delete something from your bag to make room.
4. Try and complete without closing the NPC window

**Expected behavior**
Getting the reward and complete the quest without reopening NPC window.

**Comment by Godmatik** [comment]
Confirmed

**Comment by AWIDIUS** [comment]
Ive reported this 14 days ago, yet not fix

**Comment by beraus** [comment]
This issue should be fixed now - you should be getting mail with the missing item.
