### ISSUE TITLE
Mage talent not working as intended (Frost warding)

### ISSUE THREAD

**Issue by elpell** [SunstriderEmu/BugTracker#2115]
**Describe the bug**

**To Reproduce**
1. Check Frostbolt damage.
2. Put 2 points in Frost Warding
3. Check Frostbolt damage

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
The damage should be the same, but the 2 talent points grants the mage 30% increased frost damage.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**
If you need any further info feel free to contact me (in game as Yorgen)

**Comment by kelno** [comment]
Thanks!
Fixed with next restart
