### ISSUE TITLE
The Missing Diplomat (last quest)

### ISSUE THREAD

**Issue by deandyre** [SunstriderEmu/BugTracker#2116]
**Describe the bug**
I can't pick up the last quest in the chain called 'The Missing Diplomat'.

**To Reproduce**
1. Complete the quest chain called 'The Missing Diplomat'.
2. Try and pick up the last one after Subduing Private Hendel. 

It is this quest I can't pick up: https://classic.wowhead.com/quest=1267/the-missing-diplomat

**Expected behavior**
Pick up quest, go speak to Jaina and get a ring (why I chose to do the chain)

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.
<img width="1270" alt="Screenshot 2020-03-05 at 22 20 26" src="https://user-images.githubusercontent.com/61846991/76026945-0b3f7b00-5f30-11ea-9b61-8aa7aa48b787.png">

**Comment by foxkrm** [comment]
As deandyre mentioned; the whole chain goes well till last quest. Quest giver does not give the quest in order to give it next and complete the chain.

It shows it at the list but if you click it is never being acquired.It remains as exclamation mark in the list, nothing happens.

**Comment by Nightshala** [comment]
This is still an isssue!! Please fix The Missing Diplomat!!

**Comment by Centuri0n123** [comment]
Still not working, please fix it =<

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
