### ISSUE TITLE
Blackheart the Inciter - Incite Chaos

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2118]
His MC ability (Incite Chaos )feels poorly scripted.

Every person MCed seems to follow a specific set of actions depending on their class. Some use melee abilities, others don't

For example:
Mages cast mana shield and sit there, doing nothing else
Shamans cast grounding totem and sit there, doing nothing else

**Comment by Jerrythemagicdog** [comment]
The issue has been fixed since then.
