### ISSUE TITLE
Charge

### ISSUE THREAD

**Issue by knitetrain** [SunstriderEmu/BugTracker#2119]
**Describe the bug**
charged eels in water in zangarmarsh and started to fall through earth and it disconnected me, has happened 3 times in the last 5 minutes.
**To Reproduce**
1. Cast X on target affected by ...
2. 
3. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed along with other charge related issues in the past.
