### ISSUE TITLE
Water Walking on Warriors

### ISSUE THREAD

**Issue by tazlash** [SunstriderEmu/BugTracker#2120]
**Describe the bug**
water walking from shamans cannot be cast on warriors, I expect this issue to be caused by Warriors being in a stance. I tried it with druids being shapeshifted and not, same result: shapeshifted -> invalid target, no form: works

**To Reproduce**
1. Warrior needs to be in any stance
2. cast water walking on Warrior -> invalid target\

**Expected behavior**
water walking should be able to affect Warriors

**Comment by Drilow** [comment]
This is still an issue as of April 6th, can we expect an ETA on this?

Regards,

Drilo

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed a few days ago.
