### ISSUE TITLE
[Rogue] leveling up doesnt grant me full energy

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#2125]
**Describe the bug**
Upon leveling up health and resource bar should be fully replenished, in a rogues case this is energy of 100/100 unless assination spec including Vigor. There are also some set bonuses of gear to increase energy pool.

**To Reproduce**
1. Level up while killing an NPC, not pooling any energy
2. Get screwed when you ding mid fight and can't go ham

**Expected behavior**
1. Level up while killing an NPC, not pooling any energy
2. Get a full focus bar back to continue the onslaught

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
