### ISSUE TITLE
Drums of Restoration

### ISSUE THREAD

**Issue by Kratuzov** [SunstriderEmu/BugTracker#2126]
**Describe the bug**
Drums of Restoration are not in game.

**To Reproduce**
1. Go to Trader Narasu
2. Open his goods
3. No Drums

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://tbc-twinhead.twinstar.cz/?item=34175

**Expected behavior**
Drums of Restoration should be as his goods since we are on 2.4.3

**Comment by SUN-Leekie** [comment]
There are 3 patterns in the game for Drums of Restoration.

1. World Drop, the one missing, ID 29714 (Patch 2.0-2.2), *extremely super rare*
2. Kurenai (Patch 2.3+)
3. Maghar (Patch 2.3+)

**Comment by Kratuzov** [comment]
Yes but the one from Kurenai is missing. We are on patch 2.4.3 no?

**Comment by SUN-Leekie** [comment]
No, the game/content is at patch 2.0 but the mechanics are 2.4.3
