### ISSUE TITLE
[Spell] [Talent] Setup (rogue subtlety) talent not working properly with multiple enemies

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#2127]
**Describe the bug**
When fighting 2+ enemies, the proc of Setup to add combo points to your target when dodging attacks should only apply to your primary target. Such as the case now, you can be fighting 2 mobs at the same time and lose all 5 points of combo points from your primary target you were building on, simply for dodging and proccing Setup from the second enemy.

**Expected behavior**
combo points should proc from Setup to the primary target of the player firstly. If the player is not targeting anything, and is dodging attacks still, setup should still have a chance to proc combo points... but it can only be for 1 enemy at a time, period.

**Comment by kmayberry91** [comment]
all ranks seem to be affected
https://db.endless.gg/?search=setup

**Comment by sitinanj** [comment]
Confirmed this also happens on my Rogue.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, any source that it should be working like that?
The talent description says _"Gives you a % chance to add a combo point to your target after dodging their attack or fully resisting one of their spells."_

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago, thanks for the issue.
