### ISSUE TITLE
Target dummies missing in capital cities

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#2128]
Currently affecting thunder bluff and orgrimmar to my knowledge
![image](https://user-images.githubusercontent.com/45275285/76055456-f31c2b80-5f30-11ea-87b7-fe62ac69acc2.png)
![image](https://user-images.githubusercontent.com/45275285/76055471-ffa08400-5f30-11ea-89e0-fd38bc2ea18b.png)

**Comment by AWIDIUS** [comment]
Dummies werent added until Wotlk

**Comment by Felynda** [comment]
They definitively should be added tho, we need some dummies to properly keep testing just like on the ptr.

**Comment by SUN-Leekie** [comment]
In Orgrimmar, dummies are on the right of the building with Warrior trainers, battlegrounds NPCs...
They will probably be relocated in the near future to a more obvious place.
