### ISSUE TITLE
Unable to finish Redeeming the Dead

### ISSUE THREAD

**Issue by standaloneghost** [SunstriderEmu/BugTracker#2129]
**Describe the bug**
Unable to finish Redeeming the Dead. Sangrias Silverblade's body won't appear on the top floor of the inn. Character name is Wys.

**To Reproduce**
 

**Expected behavior**
Body should be on the floor on the top floor.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Seems like the NPC didn't load properly due to an unrelated issue at the time. 
We've improved the script though for the future, thanks.
