### ISSUE TITLE
[Spell] [Rogue] Pick Lock breaks stealth

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#2130]
**Describe the bug**
Casting Pick Lock while in Stealth will cancel Stealth.

**To Reproduce**
1. Cast Stealth
2. Cast Pick Lock on Strong Junkbox or any gated door up to 350 skill

**Expected behavior**
**This should only break stealth if a failed attempt at lockpicking is made such as when the skill is lacking successful probability.**

**Comment by z5n** [comment]
stealth shouldn't persist through Pick Lock. if you find a valid source to prove otherwise please reply here and we'll take another look!
