### ISSUE TITLE
knothide quiver and knothide ammo pouch

### ISSUE THREAD

**Issue by Trollingbro** [SunstriderEmu/BugTracker#2131]
**Describe the bug**
Hello, i got an ask. Why i cant teach myself an KNOTHIDE QUIVER in trainer? Im lvl 330 of LW and item require 315 skill to teach in trainer. 

**To Reproduce**
1. Flying Thrallmar
2. Speak with LW trainer
3. There is no quiver to lern

Best regards, waiting for respond

**Comment by Shmilowitz** [comment]
To add on this. You can't learn Heavy Knothide Armor kit from any trainer either. 
https://tbc-twinhead.twinstar.cz/?item=34330#created-by

**Comment by SUN-Leekie** [comment]
All the items you are both mentioning were added in patch 2.3. We are still in patch 2.0 content-wise so it's not available yet.
