### ISSUE TITLE
[Dungeon][Boss] Pathaleon the Calculator [19220]

### ISSUE THREAD

**Issue by GeorgeLMac** [SunstriderEmu/BugTracker#2133]
**Describe the bug**
This boss drop table is completly fucked, he is dropping items from the cache of the legion instead of his actual drops, like tier pieces, i bet totem of the void drops from him too

**To Reproduce**
1. just go kill him and see for yourself

https://tbc-twinhead.twinstar.cz/?object=184465
cache of the legion, he is dropping those items instead LOL

**Comment by SUN-Leekie** [comment]
Thanks! Fixed on next restart.
