### ISSUE TITLE
Lack of Tin Veins.

### ISSUE THREAD

**Issue by Brylezor** [SunstriderEmu/BugTracker#2134]
**Describe the bug**
There is clear Lack of Tin veins in areas that should have plenty
tin veins should be at high end sides at 10-20 zones and starting to mid areas of 20-30 but there is more chance to find only copper in 10-20 zones and more chance to find copper in 20-30 and then skip to Iron and mithril (which should`t appear in those zones) i have went across the maps at 20-30 and there are more copper veins then tin by a fairly large amount. 

**Additional context**
After farming quite a few characters as miners recently in Classic this appears very odd, and creates an unreasonable amount of time spending trying to get from tin farming to iron. Esp if you need the Tin to continue leveling ur other profession.

**Comment by beraus** [comment]
This issue should be fixed now.
