### ISSUE TITLE
"At war" not working on netherwing rep

### ISSUE THREAD

**Issue by oothomiooendless** [SunstriderEmu/BugTracker#2136]
Netherwing rep is almost honored from questline in SMV.

All nether dragonscales skin from nether drakes of some sort on the netherwing rep.

When checking "at war" with netherwing rep, I still cannot attack any nether drakes to skin for nether dragonscales.

I've tried relogging/reloading/waiting for crash.

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/3182
