### ISSUE TITLE
Synthesis of Power

### ISSUE THREAD

**Issue by Kratuzov** [SunstriderEmu/BugTracker#2137]
**Describe the bug**
Quest should be available even from Neutral reputation.

**To Reproduce**
1. Go to VorenThal
2. Unable to pick up quest Synthesis of Power

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.
https://www.wowhead.com/quest=10416/synthesis-of-power

**Expected behavior**
Voren Thal should be able to give quest Synthesis of Power even as neutral reputation as stated https://wowwiki.fandom.com/wiki/Scryers

**Comment by Jerrythemagicdog** [comment]
Thanks, 2008 WoWWiki screenshots:
Scryers:
![image](https://user-images.githubusercontent.com/46463908/91769870-11a96980-ebd8-11ea-9978-ba54fd09f479.png)
Aldor:
![image](https://user-images.githubusercontent.com/46463908/91770017-56350500-ebd8-11ea-8232-72eb908c1d66.png)

Both corrected with the next restart.
