### ISSUE TITLE
Hunter Pet happiness

### ISSUE THREAD

**Issue by Fredd32** [SunstriderEmu/BugTracker#2138]
**Describe the bug**
Pets require vastly more food to sustain happiness compared to WoW Classic. If your pet dies in combat it goes from green to yellow happiness, if you don't resurrect it before it despawns it goes from yellow to red happiness. You essentially lose happiness twice from one death. Going from red to green happiness takes 5-7 food, which again, is way more then wow classic were it needed 1 high level food. Adding on this, in wow classic a pet can eat food from almost all levels when it's at max level, for instance, it can eat level 25 food at level 60, in Endless a pet can barely eat level 55 food at 70, and even then it doesn't gain much happiness at all. This feels wrong and I don't know the values, but I have  strong feeling this wasn't insanely nerfed from Wow classic to TBC.

**To Reproduce**
1. Let your pet die while at green happiness during a boss fight
2. Notice the happiness bar go to yellow
3. Wait until it despawns and re summon it again, now its red happiness. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
I expect the pet to gain much more happiness from food and not get hit twice with happiness reduction during death and then again during despawn.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by beraus** [comment]
Should be fixed long time ago.
