### ISSUE TITLE
Uncatalogued Species Issue

### ISSUE THREAD

**Issue by Noodlerogue88** [SunstriderEmu/BugTracker#2144]
**Describe the bug**
Starting quest given by item ID "24407" deletes the item out of your inventory, making it impossible to complete
**To Reproduce**
1. Start quest given by 24407
2. Watch item Disappear making the quest impossible
3. 

**Expected behavior**
Not Disappear

**Comment by SUN-Leekie** [comment]
Thanks! Fixed at next restart.
