### ISSUE TITLE
Seal of righteousness with Crusader applied

### ISSUE THREAD

**Issue by Subzors** [SunstriderEmu/BugTracker#2146]
**Describe the bug**
Seal of righteousness is doing a enormous amount of damage with crusader applied im seeing the full 219 damage bonus from crusader applied so its more effective to be ret and go 1h/shield you will do far more damage 

**To Reproduce**
1. judge crusader on target
2. auto attack target
3. Cast Seal of Righteousness
4. auto attack target
5. Profit

**Expected behavior**
Proper coefficent being applied to spells

**Additional context**
Any paladins that hate me cuz its alot of damage im sorry but id like to 2 hand weapon while retting it would make it alot more fun

**Comment by Ibuprofeno** [comment]
It seems that the Judgement of Seal of the Crusader is applying a full bonus for Seal of Righteousness without taking weapon speed into account. AFAIK the bonus should scale with Attack Speed as it does with SoR dmg. Also, I've never seen a -full bonus- applied to seals (not with 3.8 weaps).
On the other hand, it seems not to be affecting some seals? I already specced out of SoCommand but on my first test it didn't change the dmg (as Aura of Sanctity does). 
Also %DMG modifiers such as Vengeance, Aura of Sanctity, Crusade or One-handed Weapon Specialization don't seem to affect SoRighteousness.

**Comment by Pheroxis** [comment]
I have also noticed this issue and was about to report it. This causes the seal to be way to strong and really there isn't any reason to use other seals while tanking.

**Comment by Ibuprofeno** [comment]
I thought I'd update with a source I added to another thread regarding SoB not scaling with Jotc. It seems that it should increase +spdmg but SoR is getting straight +dmg 
"The Jotc tooltip is a little off, it says dmg taken by but really only increases your spellpower against the target so abilities without any or a low coefficient receive very little to no benefit."
https://www.wowhead.com/forums&topic=35733#p327974

**Comment by Ibuprofeno** [comment]
I decided to test this. I used a 1.5 weapon and max rank SoR. 
With 0 spellpower SoR deals 40 dmg.
With 0 spellpower and JotC SoR deals 312 dmg (exactly +272 as SotC tooltip states).
With 231 spellpower SoR deals 70 dmg which is REALLY FAR from judged SotC SoR dmg.
https://imgur.com/a/fCSmJ9K
