### ISSUE TITLE
[Heroic auchenai crypts] 

### ISSUE THREAD

**Issue by Bzmode** [SunstriderEmu/BugTracker#2148]
**Describe the bug**

First boss has no leash and is super slow. Also doesn't patrol before being pulled.

Can be soloed as is.

**Comment by SUN-Leekie** [comment]
Hello, can you provide more information for us to fix?
A video of what happened vs what should, etc.

**Comment by Bzmode** [comment]
https://www.youtube.com/watch?v=0G_YPDO7VfI&t=32s
(mute it jesus)

from 2007.

Smaller aggro range
faster movement
patrols from back of room to stairs before being pulled

**Comment by Jerrythemagicdog** [comment]
He shouldn't patrol back, he has a one and done path from the back of the room to the top of the stairs on retail.
