### ISSUE TITLE
Defencive stance

### ISSUE THREAD

**Issue by anatolym78** [SunstriderEmu/BugTracker#2149]
Greetings. My character (Furydwarf) cant obtain a quest from class trainer to getting a defensive stance. Help me, please.

**Comment by Jerrythemagicdog** [comment]
quest id: 1679 from npc: 1229

**Comment by SUN-Leekie** [comment]
Hello, were you able to get the quest with Jerry's indication?

**Comment by anatolym78** [comment]
Yes, I got it. Thank you.

вс, 8 мар. 2020 г. в 01:03, Leekie <notifications@github.com>:
