### ISSUE TITLE
[Botanica] Warp Splinter

### ISSUE THREAD

**Issue by Bzmode** [SunstriderEmu/BugTracker#2150]
**Describe the bug**
1. Can be stunned/missing immunes
2. Tree adds move way too fast.

**To Reproduce**
1. Engage warp splinter(last boss)
2. 
3. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
Slower Trees. immune to all cc.

**Screenshots/videos**
**https://www.youtube.com/watch?v=XpWhj3YdapQ**

**Additional context**

**Comment by SUN-Leekie** [comment]
Fixed at next restart.
