### ISSUE TITLE
Infinite Power Word: Shield

### ISSUE THREAD

**Issue by Juricho** [SunstriderEmu/BugTracker#2151]
You can have a Infinite Power Word: Shield. You Shield yourself in Shadowform, ''Weakend Soul'' applied. Switch back from Shadowform and the Debuff: ''Weakend Soul'' will be removed and you can Shield yourself again. Drains Mana.

**Comment by callmesov** [comment]
Confirmed.

**Comment by SUN-Leekie** [comment]
Fixed at next restart.
