### ISSUE TITLE
UNABLE TO CONNECT TO THIS REALM

### ISSUE THREAD

**Issue by Fefo96** [SunstriderEmu/BugTracker#2152]
Hello,

I tried several times to enter in this new server.
I downloaded the client, i've put the realmlist and i've created an account, none of this helped me to enter and start playing.
I have this issue only with this server, i tried to check if it was a global problem but warmane for example let me in.
Please help me find a solution, really hyped to join your Server!

**Comment by Jerrythemagicdog** [comment]
Hello, please contact a Support member on Discord and describe the issue further if it still persists.

**Comment by Jerrythemagicdog** [comment]
Hello, please contact a Support member on Discord and describe the issue further if it still persists.
