### ISSUE TITLE
'Deathblow to the Legion' gives no kill credit.

### ISSUE THREAD

**Issue by Simon-GM** [SunstriderEmu/BugTracker#2155]
In some cases **Socrethar** [npc ID: 20132] does not give kill credit when slain in order to complete quest '**Deathblow to the Legion**' [Quest ID: 10409].

**Comment by SUN-Leekie** [comment]
Did a player in your group land the killing blow?

**Comment by SUN-Leekie** [comment]
Should be fixed anyway.
