### ISSUE TITLE
Redeeming Firewing signet

### ISSUE THREAD

**Issue by Xacutor** [SunstriderEmu/BugTracker#2158]
I have the quest Firewing Signet given by Magistrix Fyalenn in Shattrath city (Scryers). I'm trying to redeem the signets i have in my bag (20+) but the continue button to continue the quest is greyed out. Pls help.

Ty

**Comment by SUN-Leekie** [comment]
Are you Honored with the Scryers? That would explain why you can't turn it in.

**Comment by Xacutor** [comment]
I am.
