### ISSUE TITLE
BEM Quest: Whelps of the Wyrmcult

### ISSUE THREAD

**Issue by Tasressurect** [SunstriderEmu/BugTracker#2159]
Quest gives you 12/13 snares to net 10 whelps, and it does not always reward a quest completion for each whelp snared. I have removed the quest and re-obtained it, and had unsuccessful completion in two attempts due to it not rewarding a partial quest completion per snare.

**Comment by tumulttransmuted** [comment]
Just want to confirm that I'm having the same issue. The quest doesn't seem to be completable in its current state due to not receiving credit on many of the item uses. You run out of charges before you can gather the requisite 10 whelps.

**Comment by Jerrythemagicdog** [comment]
Thanks for the details here.

**Comment by tyshies** [comment]
Bumped. Now it appears that when you go to use the net, and new error code pops that says "You can never use that item"

Screenshot Below.
![WoWScrnShot_040820_161823](https://user-images.githubusercontent.com/62031125/78829718-da31ea80-79b4-11ea-9158-afffda9399dc.jpg)

**Comment by tyshies** [comment]
Just did the Quest. Appears fixed :)

**Comment by bisquiit** [comment]
quest is still bugged got 12 nets used 4x times got 0 quest compleated... had to abandon redo  same  and again.. with 12 i get like 8-9 of them

**Comment by ugyanakkor** [comment]
Just use the nets on the whelps which was there, dont use them on it the whelps whose respawned from the egg

**Comment by EL100** [comment]
Still bugged. Same thing happened as described by tumulttransmuted.

**Comment by Jerrythemagicdog** [comment]
Thanks, we've cleaned up any potential issues with the quest spell (perhaps the spell could've been resisted before) and also increased the amount of charges (to 30) just in case. Live with next restart
