### ISSUE TITLE
[BUG][Spell][Shaman]Water Shield charge is consumed/affected by auras

### ISSUE THREAD

**Issue by Jalapan** [SunstriderEmu/BugTracker#2160]
**Describe the bug**

**To Reproduce**
Mobs periodic dmg aura consumes stacks from Water Shield.

**Expected behavior**
Water Shield and Lightning Shield should only consume stacks from direct spells or direct attacks, not by periodic dots or auras.

**Comment by Jerrythemagicdog** [comment]
Please refer to:
https://github.com/SunstriderEmu/BugTracker/issues/1328
