### ISSUE TITLE
OHF - Lieutenant Drake double- and triple-spawn.

### ISSUE THREAD

**Issue by Simon-GM** [SunstriderEmu/BugTracker#2161]
Lieutenant Drake (the first inside Caverns of Time: Old Hillsbrad Foothills) sometimes double-spawn or even triple-spawn making the encounter impossible to beat.

**Comment by SUN-Leekie** [comment]
Hello, can you please provide some pieces of information about what happened in the dungeon?

**Comment by Jalapan** [comment]
This happends with outdoor bosses aswell, there seems to be no check for spawning npcs so if a player starts an even or kite away a boss there is a new spawned.
