### ISSUE TITLE
Ghost form felt into nowhere and cant do anything 

### ISSUE THREAD

**Issue by Stavre95** [SunstriderEmu/BugTracker#2162]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Stavre95** [comment]
need help asap

**Comment by SUN-Leekie** [comment]
Please open an issue in game.
