### ISSUE TITLE
Falling via elevator when getting feared (tested in Freewind post)

### ISSUE THREAD

**Issue by Zergfest** [SunstriderEmu/BugTracker#2163]
**Describe the bug**
Feared by opposing faction while in an elevator -like transport makes you fall through world. Tested in Freewind Post (abused by opposing faction)

**To Reproduce**
See video.

Spell: https://classicdb.ch/?spell=8122

**Expected behavior**
...not fall through world.

**Screenshots/videos**
https://www.youtube.com/watch?v=Q1BryU3gJ4s

**Additional context**
Currently abused by player(s) of opposing faction.

**Comment by z5n** [comment]
#2603

**Comment by z5n** [comment]
still confirmed rev. 35219

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, players will now be immune to CC when on an elevator (or any other transport)
