### ISSUE TITLE
Umbrafen Eel stuck in their spawn positions 

### ISSUE THREAD

**Issue by Sinubis** [SunstriderEmu/BugTracker#2164]
Most of the Umbrafen Eels in Umbrafen Lake lack the ability to move towards the player if they are in range/been attacked. Makes them evade when attacked...
[Image](https://imgur.com/a/oA54Tyy) 
The problem seems to be applicable deeper into the lake.

**Comment by Sheikthecatman** [comment]
Unable to reproduce and will close the issue, if you see the bug occur again then please open the issue again.
