### ISSUE TITLE
Bloodmaul Brewmaster "Drunken Haze" Debuff

### ISSUE THREAD

**Issue by radhatter420** [SunstriderEmu/BugTracker#2165]
**Describe the bug**
The effect of the drunken haze debuff off of the bloodmaul brewmaster does not go away even after the debuff has worn off.

**To Reproduce**
Get the drunken haze debuff off of the bloodmaul brewmasters in outland. when the debuff runs out you still have the drunk effect (blurry screen, can't walk straight)

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Drunkenness effects don't go away with the effect expiring, they persist for some amount of time same as other alcoholic drinks in the game.
