### ISSUE TITLE
[Paladin] Seal of Vengeance

### ISSUE THREAD

**Issue by GigilPiq** [SunstriderEmu/BugTracker#2166]
**Describe the bug**

1) When 5 stacks of **Holy Vengeance** are applied to the target using the Paladin's **Seal of Vengeance**, reapplying a stack (resetting the 5 stacks) should take into account damage increase from skills and talents like **Avenging Wrath** and **Vengeance** (ret talent).

2) There is also a bug when some ticks do less damage than the other ticks. 

**To Reproduce**

First bug :
1. Cast **Seal of Vengeance**, melee hit a target until reaching 5 stacks of **Holy Vengeance**. Note down that tick damage.
2. Cast **Avenging Wrath**, keep hitting until reapplying **Holy Vengeance**. Note that the new tick damage is the same.

Second bug : 

1. Cast **Seal of Vengeance**, melee hit a target until reaching 5 stacks of **Holy Vengeance**. Keep hitting for some time and notice some tick damage are lower from the rest.

**Expected behavior**

From my experiences on a lot of BC private servers, using damage amplification (trinkets, talents, Avenging Wrath) at 4 stacks and then attaining 5stacks should increase all stacks damage.
It was also a known trick to use CDs (damage ampl, Avenging Wrath + Trinkets / Pots) at 4 stacks, going to 5 stacks and staying at the highest DoT dmg infinitly simply by refreshing the **Holy Vengeance** with **Seal of Vengeance** even when the amplification damage buffs are gone.

I wanted to find exact proof and I haven't. I have found old topic talking about this but nothing concrete to work with. 

I'll need other Paladin to help me on this one.

**Comment by Jerrythemagicdog** [comment]
Thanks!
Need more research here.

**Comment by GigilPiq** [comment]
@Jerrythemagicdog What we need is other experimented Paladins to come in and talk about it to confirm/infirm this. I tried to reach some horde side but no luck.

I'll try to dig goggle more in the meantime.

**Comment by mchayes** [comment]
I always took this for granted but, what happened to the 
- _As of Patch 2.2.0 Seal of Vengeance deals a small amount of Holy Damage if it strikes a target with 5 stacks of the debuff already applied_

portion of the ability. Can't seem to find a reason why this is not ingame at the moment. We're also running 6 sec crusader strike which is further down the line regarding patch updates. 

Anyone with supreme knowledge care to explain this? All I get is the following;

https://web.archive.org/web/20080913120506/http://elitistjerks.com/f31/t17193-paladin_retribution_dps_theorycraft/#post514109
an update to too low damage being dealt by melee hits extra holy damage, post 5stacks.
- _Seal of Vengeance: The bonus damage this ability dealt when the debuff is fully stacked on the target was incorrectly too low. It is now increased._

===

simple wowwiki
https://wowwiki.fandom.com/wiki/Seal_of_Vengeance
- _Patch 2.2.0 (25-Sep-2007):
Duration increased to 15 seconds. In addition, when Seal of Vengeance strikes a target that already has 5 applications you will cause instant Holy damage_

===

wowhead commentary
https://ptr.wowhead.com/forums&topic=20727#p184022
- _As of Patch 2.2.0 Seal of Vengeance deals a small amount of Holy Damage if it strikes a target with 5 stacks of the debuff already applied_
- _As of Patch 2.3: The bonus damage this ability dealt when the debuff is fully stacked on the target was incorrectly too low. It is now increased._

**Comment by GigilPiq** [comment]
> I always took this for granted but, what happened to the
> 
> * _As of Patch 2.2.0 Seal of Vengeance deals a small amount of Holy Damage if it strikes a target with 5 stacks of the debuff already applied_
> 
> portion of the ability. Can't seem to find a reason why this is not ingame at the moment. We're also running 6 sec crusader strike which is further down the line regarding patch updates.
> 
> Anyone with supreme knowledge care to explain this? All I get is the following;
> 
> https://web.archive.org/web/20080913120506/http://elitistjerks.com/f31/t17193-paladin_retribution_dps_theorycraft/#post514109
> an update to too low damage being dealt by melee hits extra holy damage, post 5stacks.
> 
> * _Seal of Vengeance: The bonus damage this ability dealt when the debuff is fully stacked on the target was incorrectly too low. It is now increased._
> 
> ===
> 
> simple wowwiki
> https://wowwiki.fandom.com/wiki/Seal_of_Vengeance
> 
> * _Patch 2.2.0 (25-Sep-2007):
>   Duration increased to 15 seconds. In addition, when Seal of Vengeance strikes a target that already has 5 applications you will cause instant Holy damage_
> 
> ===
> 
> wowhead commentary
> https://ptr.wowhead.com/forums&topic=20727#p184022
> 
> * _As of Patch 2.2.0 Seal of Vengeance deals a small amount of Holy Damage if it strikes a target with 5 stacks of the debuff already applied_
> * _As of Patch 2.3: The bonus damage this ability dealt when the debuff is fully stacked on the target was incorrectly too low. It is now increased._

This is not the problem I am talking about in this post.

**Comment by mchayes** [comment]
I am aware, just chipping in on the topic of seal of vengeance as a whole

**Comment by GigilPiq** [comment]
You are right tho, the bug does exist but the additionnal holy damage on 5 stacks is very very low anyway, and we pals honestly rarely still hit with SoV on 5 Vengeance stacks.

You might wanna create another topic for it or it'll get skip.

**Comment by GigilPiq** [comment]
Ok so I think the day I created this post I must have smoked too much weed because as of today it actually works the way it should and I think I was mistaken. 

Idk if you changed something but I am fine with it working as it is now.

Other pals, if you come across this post, correct me if I am wrong and if it SHOULD be working the way i described it in my first post. 

Piq.
