### ISSUE TITLE
The Hound-Master (druid signal)

### ISSUE THREAD

**Issue by alchemistBTW** [SunstriderEmu/BugTracker#2168]
**Describe the bug**
 During the quest I used the Druid signal to call down the druid from the sky for each quest turn in. On the last quest in the chain The Hound-Master since I didn't get the last hit on the hound master I didn't get credit for the kill and the item to summon the Evergrove Ancients has only one use I had to abandon the quest and call the druid down. After I called the druid down with the Druid signal it disappeared. Wouldn't be an issue if going back to Wildlord Antelarion had the option to replace the Druid signal which he does not and its required to turn in the quest. 

**To Reproduce**

1. Cast druid signal take quest The hound-master
2.Abandon the quest
3. Use druid signal again to call down druid.
4. if druid signal doesnt disappear from inventory try again maybe theres a cap on its uses.
5. If it doesnt disappear than im just unlucky and its not able to reproduce.
6. ??
7. Profit.

**Comment by alchemistBTW** [comment]
In game name is Alchemist if you'd like to send me a druid signal in the mail :)

**Comment by Jerrythemagicdog** [comment]
Resolved in game.
