### ISSUE TITLE
Wastewander Bandit in Tanaris can Gouge out of range / CC

### ISSUE THREAD

**Issue by terranaut1** [SunstriderEmu/BugTracker#2169]
**Describe the bug**
Wastewander Bandits in Tanaris can use Gouge when out of range, polymorphed or frozen in place (rooted). Presumably works disregarding any CC.

**To Reproduce**

1. Aggro Bandit
2. Move away / CC
3. Get gouged

https://classic.wowhead.com/npc=5618/wastewander-bandit

**Expected behavior**

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/48527763/76158242-0f2bf280-6114-11ea-93a0-0f94af80e2d1.png)
![image](https://user-images.githubusercontent.com/48527763/76158266-4bf7e980-6114-11ea-86e0-e7552169f64a.png)

**Additional context**

**Comment by Sheikthecatman** [comment]
Thank you!
This issue has been resolved in ([53bea58143de0dbd9385d0992dfa9e3da60d96ce ](https://github.com/kelno/sunstrider-scripts/commit/53bea58143de0dbd9385d0992dfa9e3da60d96ce))
