### ISSUE TITLE
Heroic Harbringer Skyriss

### ISSUE THREAD

**Issue by Bzmode** [SunstriderEmu/BugTracker#2170]
**Describe the bug**
1. Has 80k less health then normal mode and low damage.
2. Some times stuck in the ground under where he starts.

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by Jerrythemagicdog** [comment]
Falling through the ground was fixed in a general way, his damage and HP were corrected a long time ago.
