### ISSUE TITLE
[Mage] Presence of Mind

### ISSUE THREAD

**Issue by arcanecocaine** [SunstriderEmu/BugTracker#2173]
**Describe the bug**
<The talent Presence of Mind found within a Mage's arcane tree, when activated, renders the next Mage spell with a casting time less than 10 sec an instant cast spell. On Endless Sunstrider, the effect is not consumed by Flamestrike, which is not instantly cast. By way of contrast, the effect is consumed by instant spells, such as Cone of Cold or Frost Nova.>

**To Reproduce**

1. Cast Presence of Mind
2. Cast Flamestrike
3. Flamestrike is not instant but instead it is casted.
4. Cast Cone of Cold.
5. Notice that an instant cast consumes the effect.

**Expected behavior**
Following activation of Presence of Mind, Flamestrike should be an instant cast, much like a Water Elemental's Freeze. Following activation of Presence of Mind, casting an instant spell such as Frost Nova or Cone of Cold should not consume the effect.

**Screenshots/videos**

https://clips.twitch.tv/AwkwardElegantChamoisMingLee

Thanks in advance

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.

**Comment by kelno** [comment]
Presence of mind + Cone of Cold > fixed with next server update
