### ISSUE TITLE
Hunter pet talent Avoidance not working.

### ISSUE THREAD

**Issue by Endlesshunter** [SunstriderEmu/BugTracker#2174]
**Describe the bug**
The rank 2 avoidance pet trainer skill for lv 60 does not work. (at least not with my cat pet)
It takes full 100% damage of all aoe abilities. No exception on any ability of any kind.

**To Reproduce**
Send pet in against any boss with any aoe ability. For example first boss in Steamvaults. It gets instantly slaughtered for the full amount of lightning storm damage. Or try standing in the blizzard of the sorceresses in Steamvaults together with your pet. It takes same amount of damage as me.
Check for murmur. It deals the full amount of damage on pets too. Any aoe poisons on the ground in botanica, full damage. Any cleaves or whirlwind from the mobs at the end of Shadow Labs, full damage. There's thousands of examples.

**Expected behavior**
I expect it to take 50% less damage. So I have actually have time to call my pet back. IT's rather  game breaking that my pet gets killed in less than 1 second with 5k hp unbuffed by random aoe effects which should be halved. Since pets don't reach the same amount of hp as players I have to send him out before any aoe at all occurs, otherwise it'll die too fast.

**Comment by lukas155** [comment]
I seem to be experiencing this too

**Comment by Endlesshunter** [comment]
Any update on this issue? I saw you fixed some other minor inconvenience nonsense with the negative trainer points. Which actually doesn't affect us that much...It's 1 rank of greater stam at most in trainer points..This however cost us up to 40% of total dps in certain fights. Kinda gamebreaking no?

**Comment by promega01** [comment]
This is a CRITICAL bug for hunters that needs attention ASAP.  Once the community gets used to this hunters will be recognized as a broken dps class on any fight with AoE mechanics too intense for the healers to keep the pet up, and those fights are very common.  This will resulting in hunters being avoided for such PVE content.  Many aoe abilities especially on heroic will do close to 5k damage and one shot or nearly one shot the pet not to mention T4-6 content. Also in PVP the pet gets cleaved down FAR too easy from aoe.  Please bump this to the top of the priority  list, it is game breaking for hunters in both pve and pvp.

**Comment by SUN-Leekie** [comment]
Fixed at next restart.

**Comment by winex93** [comment]
Getting reports about this not working. Needs to be checked.
