### ISSUE TITLE
[Warlock] Succubus Quest

### ISSUE THREAD

**Issue by endlessggwarlock** [SunstriderEmu/BugTracker#2175]
**Describe the bug**

Level 70 Orc Warlock.
I can't accept the Quest for the Succubus. 
The Questgiver Gan'rul Bloodeye has no Quest for me.
I checked all follow up Quest-Npc's and none would have a Quest for me. 
Even went to Undercity and tried Undead Chain, nothing. 
Cleared cache, retrained, used Dual Specc, to no result.
Not possible to get my Succubus.

Quest: https://tbcdb.com/?quest=1507
Spell: https://tbcdb.com/?spell=712

**Comment by Rouvq** [comment]
Same for me. Have u solved the problem?

**Comment by faxaong** [comment]
the same for me

**Comment by Fittycal** [comment]
Same for me as well.  Has this been solved?

**Comment by faxaong** [comment]
Yes.. Ticket to GM and it's ok

A domingo, 26 de abr de 2020, 01:36, Fittycal <notifications@github.com>
escreveu:

**Comment by Jerrythemagicdog** [comment]
Thanks, you should be able to see the available quest after next updates.
