### ISSUE TITLE
[Battlegrounds] Honor gained is way too low

### ISSUE THREAD

**Issue by Trolltilla** [SunstriderEmu/BugTracker#2178]
**Describe the bug**
Honor gained from battlegrounds is too low. Currently you get approximate 200 honor per win even as alliance with 50% more honor gained.

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Godmatik** [comment]
Where is your reference to what amounts it should be?

If you are comparing it to classic, then it's not going to be accurate. Honor gains were lowered when TBC launched.
