### ISSUE TITLE
[Quest] Escape Firewing Point

### ISSUE THREAD

**Issue by dshgrove** [SunstriderEmu/BugTracker#2179]
**Describe the bug**
The NPC you escort should only attack mobs that attack her or the people doing the escort quest. Instead she aggros everything within a very large radius whenever it is attacked by a player. When all the mobs within her vicinity are dead, she starts rp-walking back to her original path instead of running, which causes the mobs she just killed to respawn before she is back at the start. Then she aggros something around her again, and you are stuck in a loop :)

**To Reproduce**
1. Start escort quest
2. Have someone outside the group attack a mob far away. NPC will run to them and attack their target.

Quest: https://www.wowhead.com/quest=10051/escape-from-firewing-point

**Expected behavior**
She should only attack NPCs aggroed by herself, NPCs attacking her or aggroed by a player on the quest.

**Additional context**
The quest is practically impossible to complete in its current state with dynamic respawn times. We attempted this lvl64 2-man quest as three level 70 players and were not able to complete it.

**Comment by Jalapan** [comment]
This is also the state of many other escort quests, the rangecheck/aggro for the npc being escorted is to long seems to be over 50yards

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2580
