### ISSUE TITLE
Battle Bear Mount

### ISSUE THREAD

**Issue by Neola88** [SunstriderEmu/BugTracker#2180]
I recently purchased a Big Battle Bear mount from the store, my blood elf does not sit on the mount and instead floats way above the saddle.
Is it possible to make it so the blood elves actually sit on top of the mount?

https://www.wowhead.com/item=38576/big-battle-bear

I'm expecting the issue is fixable, especially because it's a store mount. 

![image](https://user-images.githubusercontent.com/61941182/76165422-5a9eca80-612d-11ea-8868-775eb42dda59.png)

Thank you for your hard work Devs!

**Comment by Aeded** [comment]
> I'm expecting the issue is fixable, especially because it's a store mount.
lmao
No.. this is client side issue. Which means the way it is now is the way it was back then on retail and most likely still the case on BFA too if you had the mount there.

They cant fix it

**Comment by Jerrythemagicdog** [comment]
Sorry, we do not control the way your character is positioned on the mount.
