### ISSUE TITLE
Shaman Sentry Totem and Far Sight NOT working

### ISSUE THREAD

**Issue by kenshinh** [SunstriderEmu/BugTracker#2181]
Shaman Sentry Totem doesnt work... you must Right-Click on the buff to be able to switch back and forth between totem sight and shaman but when the player right click on buff it desapears like a regular buff.. this totem must not be removed by right clicking it.
Far sight: doesnt change sight, the player can cast it but it doesnt do anything more than that.

**Comment by z5n** [comment]
unable to reproduce, issues have likely since been fixed
