### ISSUE TITLE
Heroic Mechanar Badge of Justice from Cache

### ISSUE THREAD

**Issue by grifwow** [SunstriderEmu/BugTracker#2183]
The only person able to retrieve a badge of justice from Heroic Mechanar's Cache of the Legion is the person who unlocked it. After unlocking and looting, the Cache becomes locked again for the rest of the party members. I would like a badge of justice for this bug.

**Comment by Bzmode** [comment]
our group had the same problem. Possibly make the key actually unlock the chest instead of just opening it once for the keyholder

**Comment by beraus** [comment]
This issue should be fixed now.
