### ISSUE TITLE
A small group of people spammed the /global thread then the server when offline!

### ISSUE THREAD

**Issue by ElvenPrince** [SunstriderEmu/BugTracker#2184]
A few minutes ago a group of people from the horde stide started spamming the global thread then the server went offline.They used a macro! Many of us told them to stop! It's the small group of people who is constantly complaining about the server and spamming the thread! Please do something about this! Thank you! My Account ElvenPrince!

**Comment by Wandkeeper** [comment]
its funny... people complaining about server, yet they play on it 24/7 . why dont these mentaly ill people leave the server and play somewhere else then

**Comment by Jerrythemagicdog** [comment]
Thanks, we'll resolve the problems on our side and players will no longer be able to spam /leave the channels.
