### ISSUE TITLE
Murmur (Last boss in Shadow labyrinth) is casting Resonance too soon after Sonic Boom.

### ISSUE THREAD

**Issue by Calzeru** [SunstriderEmu/BugTracker#2185]
**Describe the bug**

Murmur is casting Resonance instantly after his Sonic Boom. There is supposed to be a small grace period after Sonic Boom to allow players to get back into melee range before he starts casting this.

Resonance is the spell that deals damage to the whole party if no one is in melee range and gives the party a 45 second stacking debuff that increases nature damage taken by 2000. It's supposed to work as some sort of soft enrage mechanic if there's no one in melee range, as Murmur is stuck in place and can't attack players outside his melee range.

Currently, warrior and druid tanks don't even have time to Intercept/Charge back to Murmur after Sonic Boom before Resonance is cast. (Most of the time you will just get "No path available" error when you try that anyway)

**To Reproduce**

1. Fight Murmur in Shadow Labyrinth.
2. Run out to avoid his Sonic Boom mechanic.
3. Notice that Sonic Boom is instantly followed up by Resonance with no grace period at all.

Boss: https://wow.gamepedia.com/Murmur

**Expected behavior**

Small grace period to allow the tank/melee back into melee range before Resonance kicks in.

**Screenshots/videos**

Video from actual TBC showing that they have time to move back in melee range to avoid Resonance: https://youtu.be/XYBRAMkTEAw?t=42

**Additional context**

**Comment by Jalapan** [comment]
Can confirm, the grace period should be increased by 0.5-1 second.

**Comment by Jerrythemagicdog** [comment]
Thanks, the fix should be live now.

771a22820877223c49a9e320ace25807bfd3f334 (scripts)
