### ISSUE TITLE
General Heroic Loot

### ISSUE THREAD

**Issue by Bzmode** [SunstriderEmu/BugTracker#2187]
**Describe the bug**
Heroic Ramparts / Blood Furnace / Mana Tombs / Auchenai Crypts / Sethekk Halls / Slave Pens / Underbog / Old Hillsbrad all drop loot that drops in the normal version instead of loot normally seen from level 70+ NPCs.

**Comment by Godmatik** [comment]
Confirmed... he is referring to loot from trash mobs by the way.

For example in Slave Pens, trash is dropping level 61/62 greens.
