### ISSUE TITLE
Pet soul-trader Beacon

### ISSUE THREAD

**Issue by Pallaladin** [SunstriderEmu/BugTracker#2188]
when i spawn the pet it follow me but when i talk to him he stop following.

**Comment by InhumanGM** [comment]
In order to replicate this issue, we need more information. Please follow the bug report template that way we can properly reproduce and investigate this issue.

> **Describe the bug**
> 
> **To Reproduce**
> 
> 1. Cast X on target affected by ...
> 
> Item: https://wowhead.com?item=
> Quest: https://wowhead.com?quest=
> Spell: https://wowhead.com?spell=
> 
> **Expected behavior**
> 
> **Screenshots/videos**
> 
> **Additional context**
