### ISSUE TITLE
Frankly, It Makes No Sence (quest)

### ISSUE THREAD

**Issue by jezzmaister** [SunstriderEmu/BugTracker#2190]
In this quest you need to take control of  Arcano-Scorp and to need Arcano Control Unit but when i click the control unit nothing happens.

**Comment by wiglefish** [comment]
still bugged as of 22/3

**Comment by Jerrythemagicdog** [comment]
Fixed a while ago, thanks.

**Comment by Shaacks** [comment]
Still bugged af
