### ISSUE TITLE
 [Linken's Boomerang]  [Linken's Boomerang] не работает аксесуар не работает вообще.. прошу исправить

### ISSUE THREAD

**Issue by apafeoz** [SunstriderEmu/BugTracker#2193]
[Linken's Boomerang] не работает аксесуар не работает вообще.. прошу исправить

**Comment by SUN-Leekie** [comment]
Please use english and provide some details.
https://www.deepl.com/en/translator

**Comment by Fireknight90** [comment]
> Please use english and provide some details.
> https://www.deepl.com/en/translator

" https://classic.wowhead.com/spell=15712/linkens-boomerang " This item not work. Please fix it. Thanks.

**Comment by SUN-Leekie** [comment]
The item is supposed to have a very low proc chance if you're using it on players higher than 60.

**Comment by apafeoz** [comment]
The question is not what equals the chance of proc against players 60 ... but the fact that the accessory does not work in general

**Comment by SUN-Leekie** [comment]
It does since <60 items doesnt work well after lvl 60. So if you could give a little more information about against who at you are using it, it help to narrow the issue.

**Comment by apafeoz** [comment]
[Linken's Boomerang 10.03.2020, 00:07, "Leekie" <notifications@github.com>:It does since So if you could give a little more information about against who you are at using it, it help to narrow the issue.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
