### ISSUE TITLE
Threat Issues for casters.

### ISSUE THREAD

**Issue by CrazyDoc90** [SunstriderEmu/BugTracker#2195]
I have noticed that threat is not generating properly for casters. When you cast a damagin spell you should only get aggro from the mob you attack. Instead of that after casting a spell mobs that I am not attacking turn to attack me and I have the same threat on them as the mob I am attacking. This should only happen with healing spells that generate threat on all targets

**To Reproduce**

1. Have someone bodypull 2 or 3 mobs and keep aggro on only one of them without any aoe
2.  Start attacking the same target with any kind of spell
3.  The other two mobs will attack you.

On a side note for shadowpriests, there is a chance that Shadow Affinity is not reducing the threat of shadow spells properly

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, this is however invalid.
