### ISSUE TITLE
Karazhan - Prince Malchezaar Flying Axes

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2198]
The damage done by Flying Axes in P3 feels severely under tuned, possibly missing [Demonic Frenzy] buff that slowly ramps up the damage they deal over time.

**Comment by Bzmode** [comment]
still feels the same, debuff still hitting everyone and the axes aren't ever switching off the top healer threat.

**Comment by Godmatik** [comment]
Gonna bump again cause we did Kara yet again and the flying axes seem to still hit for nothing. It's a major phase 3 mechanic that is really missing, making the final part of the fight a joke.

**Comment by kelno** [comment]
Fixed some time ago
