### ISSUE TITLE
Tome of Valor

### ISSUE THREAD

**Issue by NightWolf92** [SunstriderEmu/BugTracker#2201]
Failed Tome of Valor, unable to retake the quest after abandoning it and visiting the chapel. (alliance)

**Comment by SUN-Leekie** [comment]
#2093

**Comment by drizlo** [comment]
Failed Tom of Cabal after abandoning. Can't  retake quest

**Comment by InhumanGM** [comment]
This quest has to be reattained from [Daphne Stilwell](https://tbc-twinhead.twinstar.cz/?npc=6182) herself after she respawns (5 minute respawn time), not [Duthorian Rall](https://tbc-twinhead.twinstar.cz/?npc=6171) in Cathedral Square, Stormwind City. Upon testing, this quest can be reattained with no issue.
