### ISSUE TITLE
Loot bug

### ISSUE THREAD

**Issue by Binqs** [SunstriderEmu/BugTracker#2202]
Killed Arcanist Doan in Scarlet Monsastery, Lib. 
 [Illusionary Rod] dropped and i won the roll.
The item wasn't delivered to my bag, nor was i able to loot Arcanist Doan.

/Lexaeterna

**Comment by Binqs** [comment]
-(we had no issues with DC's during the run)

**Comment by SUN-Leekie** [comment]
Were you dead when you rolled the item?
