### ISSUE TITLE
Faerie Fire not working as intended.

### ISSUE THREAD

**Issue by Shifthappenz** [SunstriderEmu/BugTracker#2204]
**Describe the bug**
Winterfall Pathfinder are casting Faerie Fire, the armor decrease happens but I am still able to stealth

**To Reproduce**

1. Allow Faerie Fire to be cast on you as a stealth class. -->
2.  You are still able to stealth

https://classic.wowhead.com/npc=7442/winterfall-pathfinder#abilities
https://db.endless.gg/?spell=16498

**Expected behavior**

**Screenshots/videos**
https://imgur.com/a/memyW7f

**Additional context**

Thanks for the hard work guys.

**Comment by SUN-Leekie** [comment]
Thanks, fixed!
