### ISSUE TITLE
Helboar aggro radius

### ISSUE THREAD

**Issue by Heringer91** [SunstriderEmu/BugTracker#2205]
**Describe the bug**

**To Reproduce**

1. get within 50 yards of helboars (@level 60)
2. aggro helboar from over 50 yards
3. die
4. run back and rez
5. die again because you cant rez far enough away without 5 helboars charging you

**Expected behavior**

LOWER THE AGGRO RADIUS

**Comment by Godmatik** [comment]
As has been stated before, the long aggro range is intended, because the boars having larger than normal aggro radius was when TBC was first released.

**Comment by Heringer91** [comment]
Yes, it was bigger but this is crazy how big it is. I cant even cast a
wrath outside of its aggro range. I max ranged Rez'd and chain pulled 5
boars.

This is way "overturned". Its just annoying, it's not replicating TBC
release, it's not immersive its just purely annoying.

It should be lowered by 10-15 yards, still larger than your average mob,
but not so big that you sneeze in silithus and every helboar in hellfire
runs through the portal, to STV gets on the boat and charges from the STV
port to silithus

**Comment by Jonsse** [comment]
> As has been stated before, this is intended, because the boars having larger than normal aggro radius was how it was when TBC was first released.

You realize that it was fixed quite quickly after launch? Literally advocating for beta behaviour, what's wrong with you?

**Comment by Godmatik** [comment]
@Jonsse 
Then why do comments well into TBC release state otherwise? I don't advocate for it by the way, I am just stating what they have said.

https://www.wowhead.com/npc=16879/starving-helboar#comments

**Comment by beraus** [comment]
Working as intended.
