### ISSUE TITLE
Chaotic Skyfire Diamond

### ISSUE THREAD

**Issue by danelmore** [SunstriderEmu/BugTracker#2206]
Suppose to be on loot table for Coilfang Siren.  I have killed alot and not seen it yet.  Also whispered multiple other jc on server and no one has or has seen.  Can you confirm it actually is on the loot table.  I'm at 300 or so kills, should be around 2%.  Maybe really bad luck.

**Comment by Jerrythemagicdog** [comment]
Added earlier today, will be live after next server reboot. Thanks!
