### ISSUE TITLE
Account rep bug

### ISSUE THREAD

**Issue by Rockerito15** [SunstriderEmu/BugTracker#2207]
i cant get any quest for rup, especially lower city and faction aldor
[The Outcast's Plight] and [A Cleansing Light]. also quest Haggard War Veteran didn't give me any rep with aldor.

Quest: 
https://www.wowhead.com/quest=10420/a-cleansing-light
https://www.wowhead.com/quest=10917/the-outcasts-plight
https://www.wowhead.com/npc=19684/haggard-war-veteran

Fix my account or character. because i can't pick up any quest to mention.

**Comment by InhumanGM** [comment]
Have you completed the quest [[Allegiance to the Aldor]](https://tbc-twinhead.twinstar.cz/?quest=10551)?
