### ISSUE TITLE
Cold Blood + Evis doesn

### ISSUE THREAD

**Issue by littletricky** [SunstriderEmu/BugTracker#2211]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by SUN-Leekie** [comment]
Closing in favor of https://github.com/SunstriderEmu/BugTracker/issues/2212
