### ISSUE TITLE
Spinebreaker Post, Captain Darkhowl missing

### ISSUE THREAD

**Issue by Aqqe83** [SunstriderEmu/BugTracker#2218]
**Describe the bug**
Questhub NPC "Captain Darkhowl" located at Spinebreaker Post, Hellfire Peninsula seems to be located below the ground. She can be /target'ed, but she does not appear anywhere in the camp.

**Comment by Jerrythemagicdog** [comment]
Seems, to be located in its correct spot, perhaps players pulled it away, I'll make sure it returns home, thanks!
