### ISSUE TITLE
World Respawn Rates

### ISSUE THREAD

**Issue by Stolemyname1** [SunstriderEmu/BugTracker#2219]
Respawn rates of many creatures make certain quests extremely difficult or impossible based on the objectives of the quest.

Example: Escape from Firewing Point!
The escort NPC walks at the normal slow escort pace, but has an extremely aggressive aggro range, attacking any enemy in sight, especially if that enemy is already in combat. The path she walks is through around a dozen tightly packed enemies that kill her almost instantly. Attempting to clear the enemies out before she gets there also does not work, as they respawn faster than she can walk back to her spot to resume the escort.

https://www.wowhead.com/quest=10051/escape-from-firewing-point

While increased respawn rates of enemies is helpful, the current rate is far too high. This problem is much worse for classes with long downtimes between fights like warriors who are effectively unable to recover before the enemy they just killed respawns on top of them.

**Comment by Jalapan** [comment]
Can confirm. almost impossible to solo some quests in Shadowmoon valley and netherstorm, 1-2 seconds after a mob is killed a new one has respawned.

**Comment by Stolemyname1** [comment]
Another quest that is flagged as a solo quest, while still doable with a group is much more difficult that it should be. Fire at Will! (https://www.wowhead.com/quest=10911/fire-at-will) 

This quest is made difficult with a group for 3, and nearly impossible solo. The gate spawns a constant stream of enemies for the quest which is manageable, but with the added 4-5 respawns every 30 seconds you are very quickly overwhelmed and either the cannon is destroyed or you are killed trying to protect it. Yet another area that the respawn rate should be turned down.

**Comment by fruvel** [comment]
no one fixes this, this server just a money make server nothing else
