### ISSUE TITLE
Mob bug: Stonescythe Whelp\Alpha

### ISSUE THREAD

**Issue by wanttoq** [SunstriderEmu/BugTracker#2220]
Stonescythe Whelp\Alpha are stuck and don't attack after Desperate Defense.
![Bug](https://user-images.githubusercontent.com/62017849/76312102-603e1100-62e3-11ea-8a13-e2b06c884764.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in https://github.com/kelno/sunstrider-scripts/commit/e2a2af4a92c8b200c5490ad4c8fc14c842631603
