### ISSUE TITLE
[Arena] Arena points flushed yesterday even tho they were supposed to be flushed on saturday

### ISSUE THREAD

**Issue by Trolltilla** [SunstriderEmu/BugTracker#2222]
**Describe the bug**

Title

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Bzmode** [comment]
yea these should be wiped a lot of people played expecting it to happen on the time we were given

**Comment by Godmatik** [comment]
Arena points are also being awarded at 1.5x the rates that they should

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed!
