### ISSUE TITLE
Ressurect from Talent point

### ISSUE THREAD

**Issue by chaudgod** [SunstriderEmu/BugTracker#2223]
**Describe the bug**

I clicked Heart of the Wild talent to add a point and it ressurected my corpse where i stood.

**To Reproduce**

I clicked Heart of the Wild talent to add a point and it ressurected my corpse where i stood.

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

https://clips.twitch.tv/ObliviousPlayfulBobaTwitchRPG

**Additional context**

**Comment by SUN-Leekie** [comment]
Clip unavailable. Can't reproduce.
Closing until more proofs are provided.

**Comment by kelno** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2463
