### ISSUE TITLE
Vampiric touch doesnt give mana to party

### ISSUE THREAD

**Issue by KosioB** [SunstriderEmu/BugTracker#2224]
**Describe the bug**
Vampiric touch on shadow priests doesn't work as intended.
It should provide the party of the priest 5% mana back of the shadow damage done while it is on the target but it does not. I have enabled the energy gains combat scrolling text to ensure that it is not just my imagination - there is no mana gain at all.

**Comment by Godmatik** [comment]
I am definitely gaining mana back when a shadow priest is in my party...

**Comment by SUN-Leekie** [comment]
Please check your combat log for something like this:
> 20:00:50> Kashah gains 7 Mana from Kashah's Vampiric Touch.
