### ISSUE TITLE
Black Morass - Blackfang Tarantulas

### ISSUE THREAD

**Issue by BasedForfrost** [SunstriderEmu/BugTracker#2225]
**Describe the bug**
Blackfang Tarantulas have no loot tables whatsoever. Other than trash loot, they're normally a good source of Netherweb Spider Silk

**To Reproduce**
1. Kill Tarantulas in Black Morass.
2. Feel sad.
3. 

Item: https://www.wowhead.com/npc=18983/blackfang-tarantula

**Comment by Jerrythemagicdog** [comment]
The Netherweb Spider Silk was intentionally removed from the tarantulas.

**Comment by BasedForfrost** [comment]
Any reason for this or why it doesn't appear to be documented? Did their loot tables have to be removed entirely to accomplish this?
