### ISSUE TITLE
Mailbox Deleting Items

### ISSUE THREAD

**Issue by tyshies** [SunstriderEmu/BugTracker#2226]
**Describe the bug**
Sent items to my alt bank from my main for storage a few hours ago, and within the last 15 minutes, and the items were deleted/disappeared when I pulled them from my mailbox on the Alt toon. The first time it was 4 stacks of Knothide Leather Scraps, 2 stacks of Knothide Leather, and 8 Clefthoof Leather.

The second time I sent some of the same, lesser amount and got everything but the Clefthoof, which was deleted somehow

Character names available upon request.

**Comment by beraus** [comment]
It seems to take a while in some cases, especially when you have many items in your inventory.
I'll close this for now but we'll try improving the mail system to be faster in the future.

_Originally posted by @kelno in https://github.com/SunstriderEmu/BugTracker/issues/2953#issuecomment-622942994_
