### ISSUE TITLE
Whisper System is not working.

### ISSUE THREAD

**Issue by Ironjudgment** [SunstriderEmu/BugTracker#2228]
**Describe the bug**
The /whisper system isn't currently working. 

**To Reproduce**
Try whispering anyone. You will see your message but not the other person.

**Expected behavior**
Each party involved should see the message.

**Comment by Wielkorogi** [comment]
Can confirm

**Comment by Godmatik** [comment]
Confirmed

**Comment by Ironjudgment** [comment]
Fixed.
