### ISSUE TITLE
Mining nodes outland ( not sure if just outland ) again

### ISSUE THREAD

**Issue by fotren** [SunstriderEmu/BugTracker#2229]
**Describe the bug**
No mining nodes on Outland, or not respawning.
**To Reproduce**
Step 1 Turn on find minerals.
Step 2 Walk around a world without yellow spots.

**Expected behavior**
Yellow spots on the minimap with find minerals turned in.

**Screenshots/videos**
Rather hard to make one. 

**Additional context**
As with the screenshots, and videos, its hard to tell 100%. But haven't seen a single one in the past 3 hrs.

**Comment by AWIDIUS** [comment]
Yes, vein respawn rates are probably based on how many people are in location instead of how many people are Farming veins, that means, there are more likely only miners running across OL, so each individual seems to meet like 1-3 nodes per location, which is awful ...

**Comment by InhumanGM** [comment]
This issue appears to have been fixed. There are mining nodes throughout the world now.
