### ISSUE TITLE
Arena Letter lost bug

### ISSUE THREAD

**Issue by Coppraem** [SunstriderEmu/BugTracker#2230]
**Describe the bug**
The bug is that I did pay gold for 2v2 team and 3v3 had my signature letters in my bags ,but when I did relog to get addon on the letters were gone and the gold is gone as well.

**To Reproduce**

I don't really want to try to reproduce this as I already lost 200g ,which I hope I can get back.

Item: https://www.wowhead.com/item=23560/arena-team-charter-2v2
https://www.wowhead.com/item=23561/arena-team-charter-3v3

**Expected behavior**

When you relog / dc or anything the letters should not despawn from your bags !
**Screenshots/videos**
I don't have screenshots or videos as I was not expecting this ( I have never encountered it ).

**Comment by Sheikthecatman** [comment]
This issue has been fixed.
