### ISSUE TITLE
Deleted items

### ISSUE THREAD

**Issue by Mrweed420-hashh** [SunstriderEmu/BugTracker#2231]
**Bank Bug**

**To Reproduce**

1. Bought the 4. Bagslot in bank
2. Used Netherweave Bag
3. Right klick items to bank
4. All items are gone

Item: Netherweave Bag

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by InhumanGM** [comment]
Upon attempting to reproduce the issue, I was not able to find any issues. Could you provide more information that could be used to try to reproduce the issue again?
