### ISSUE TITLE
Abandoned quest requires Felsworn Gasmask

### ISSUE THREAD

**Issue by Jurfden** [SunstriderEmu/BugTracker#2233]
I abandoned a quest that requires the use of a specific item called "You're Fired!". It requires a Felsworn Gas Mask that is normally re-acquired by Wildlord Antelion at Evergrove in Blade's Edge Mountains. 

I submitted an in-game ticket and they told me to come here to submit a ticket. I need to  be reset on the quest line or given a felsworn gas mask. My in-game name is Jurfden. Please help!

Thank you very much,

Jurfden the Paladin

**Comment by Jerrythemagicdog** [comment]
Hey, it's going to be resolved after next server update, thanks!

f6535ccd72e4457f6e3b2c9b612483986cb98674 (scripts)
