### ISSUE TITLE
"Additional Runecloth" quest reputation gain 

### ISSUE THREAD

**Issue by ttpekkan** [SunstriderEmu/BugTracker#2236]
**Describe the bug**
Completing the "Additional Runecloth" quest in Stormwind is currently giving 18 reputation per turn-in for non-humans at level 70. I believe it should give the full reputation (75 + reputation gain bonuses) at level 70. 
https://db.endless.gg/?quest=7796

**To Reproduce**
Return runecloth stacks to the Clavicus Knavingham npc. 

**Expected behavior**
I expected the quest to give me full reputation gain. At level 66 the quest gave 90 reputation, which demonstrates that the quest is affected by "low level quest" penalties. 

**Screenshots/videos**

![reputationGain](https://user-images.githubusercontent.com/2089684/76382443-738fc180-6361-11ea-99b0-0dd3bde4c8ad.png)

**Comment by z5n** [comment]
Issue has since been fixed
