### ISSUE TITLE
Kara Attumen loot bug

### ISSUE THREAD

**Issue by mayday2013** [SunstriderEmu/BugTracker#2237]
**Describe the bug**
After our raid had killed the boss, we couldn't get the loot for error.

**To Reproduce**
Kill the boss and try to master loot the items.

Item: https://wowhead.com?item=28454/stalkers-war-bands

**Expected behavior**
Loot it with FFA enabled.

**Screenshots/videos**
https://www.youtube.com/watch?v=Q8h9VZ8Vg1g

**Additional context**
Had the same trouble with Moroes loot.

**Comment by Jerrythemagicdog** [comment]
Thanks, we've received some reports about this issue, do you think you know how to consistently make this happen?

**Comment by Jerrythemagicdog** [comment]
Fixed with master looter range restrictions.
