### ISSUE TITLE
Black screen on window mode

### ISSUE THREAD

**Issue by ipotuz** [SunstriderEmu/BugTracker#2238]
**Describe the bug**

When playing in Full screen everything is ok, when activating window mode the screen instantly turn black. I can hear the sound but I can not play as I don't see anything. The full screen do not turn into window and the only way to remove the black screen is to press escape. 
I play on a MSI MS60 with a Nvidia GTX 965M, I play with 2 screens. The external screen is the one with Wow running on and where the bug happens.

**To Reproduce**

1. Access video settings
2. Click on video mode
3. Bugg happen

None

**Expected behavior**

When clicking on video mode, the full screen turn into video mode.

**Screenshots/videos**

**Additional context**

I haven't tried to play on my laptop screen directly. I will try tonight.

**Comment by Godmatik** [comment]
Check pinned message in the Endless Discord #general channel, you have to modify your config file to get this to work properly.

**Comment by Jerrythemagicdog** [comment]
From Discord:
If you're getting a black screen when swapping to windowed mode - it's a GAMMA issue. Open up config.wtf inside of your WTF folder and add these 2 lines:
SET gxWindow "1"
SET gxMaximize "1"
