### ISSUE TITLE
Randomly changing spec on login

### ISSUE THREAD

**Issue by Heringer91** [SunstriderEmu/BugTracker#2241]
**Describe the bug**

Randomly i will be my secondary spec when i log in. It has happened 5 times now. Once when all I did was relog to turn on an addon

Also i lose skills on my bars when swaping specs (not sure if that cant be fixed)

**Comment by wiglefish** [comment]
I don't know whether this will ever be fixed but a temporary solution is to create a basic macro for the individual talent-specific skills. This keeps it on the action bar after respec.
I did notice however that 1 of my macros still gets removed from my action bars every couple of days. Not sure what the issue with this is though.

**Comment by Pindrought** [comment]
I use Action Bar Saver addon to save my layout.
