### ISSUE TITLE
Pendant of the Agate Shield recipe respawn timer

### ISSUE THREAD

**Issue by mmarkovic123** [SunstriderEmu/BugTracker#2243]
Decription:
The respawn timer is way too long.

How it works:
It takes a long time to respawn the next recipe in the vendor. I bought the recipe and i waited more than i should have for the next recipe on stock.

How it should work:
It should be back in the vendor's table 5 minutes after the previous purchase.

Source (you should point out proofs of your report, please give us some source):
"Only one recipe on stock, recipe repopped 5 minutes after buying." on 2009/10/22 (Patch 3.2.2)
http://www.wowhead.com/item=20970/design-pendant-of-the-agate-shield#comments

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next server update!
