### ISSUE TITLE
Karazhan

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#2244]
As far as I know, trash should not respawn when the boss its linked too is down.  

Trash respawning is a big issue especially early when people are learning new server/new tactics, please fix this very fast so other people don't get cancer from wiping on stuff they need to figure out for the first time on endless and then having to reclear/wipe on trash.

1.  Trash at the blacksmith near attunmen (first boss) respawned.  
2.  Trash in the room above the stairs (between moroes room and the stairs leading towards maiden).  other trash may have respawned but we didnt need to reclear.
3.  Trash after opera leading (spectres and the double golems),   syphoners in curators room (arcane anomalies did not respawn).  maybe it was linked to nightbane (we did not kill), but hopefully its linked to curator since most runs are 9/11 skipping nightbane/netherspite.
4.  spectres between aran and chess respawned after chess was down.  not 100% sure who that trash should be linked to (netherspite or chess, but hopefully chess since the usual run is 9/11 skipping NS).  

This is not an exhaustive list ... its just mobs i noticed that respawned that i could see or we had to re-kill during our 8/11 progression on 3/10.
  
Trash respawn also seemed fast, i think it should be 2 hours, maybe it was we were in there a long time but we never wiped for 2 hours on any single boss so we should've never had to reclear any trash.  we even did the animal boss 2nd so the trash should not have respawned.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in '168ab0b09c81f9310685405e175c12e5bbf8bd8c'
