### ISSUE TITLE
Karazhan - Netherspite

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2245]
A few bugs with this fight.

1 - During banish phase, the boss is not properly targeting or facing the person he is using nether breath on.

2 - During portal phase, aggro is being dropped and Netherspite targets people on his threat list. He should never drop aggro from the person who has red beam buff.

3 - After Banish phase ends, Netherspite's threat should reset, and I don't believe this is happening.

**Comment by Jerrythemagicdog** [comment]
1. Confirmed.
2. Would like to see a video of it happening if possible, the boss fixates on the target with the red beam. Unless the player steps out it won't change targets.
3. Is happening correctly.

**Comment by Godmatik** [comment]
Yes we noticed #3 was working fine.

As far as #2, we noticed that the person with the red beam buff was losing aggro a few seconds after exiting the beam. As far as I am aware, the boss should continue to fixate on the person with the red beam buff even if they step out of the beam but continue to have the buff. But I will try and find a video and some further proof.

**Comment by Jalapan** [comment]
Nethspite is hitting melee in his banish phase, this should not happen

**Comment by Bzmode** [comment]
confirmed attacking while banished and also still not targeting the person he's netherbreathing.

**Comment by Jerrythemagicdog** [comment]
The boss should now be targeting the correct person after recent changes.
