### ISSUE TITLE
Crusader enchant not working properly

### ISSUE THREAD

**Issue by storm4yyy** [SunstriderEmu/BugTracker#2246]
Crusader enchant gives 20 ap on effect of the buff when triggered please fix it / the other bug i seen today is final boss in SHH is falling down below the platform and bugging out maybe its because we tryed to reset the fight when running from him away pass the stairs

**Comment by Godmatik** [comment]
This is not a bug, 

Crusader enchant gives diminished effect after level 60, only providing 20 strength instead of 100 at level 70.

**Comment by Xinergie** [comment]
No idea how it should work, but 20 strength would be 40 AP. It might be giving 40 AP instead of 20 like OP said but worth checking I guess.

**Comment by Godmatik** [comment]
If he is a rogue, he only gets 1 AP per strength.

More than likely he was expecting the full 100 strength like on classic but didn't realize it was nerfed for TBC.

**Comment by AWIDIUS** [comment]
@Godmatik that is clear bulshit ... 5 mins of research + personal experience from other servers says it gives 60 strength at level 70, which should be even there (i haven't checked that one out yet ingame).
![Screenshot_20200312-091653](https://user-images.githubusercontent.com/45521546/76501391-7f06e980-6442-11ea-9d90-18749faa5404.png)

**Comment by Jerrythemagicdog** [comment]
The enchant provides 60 strength as described in the wowhead comment.
