### ISSUE TITLE
Priest Shadowform

### ISSUE THREAD

**Issue by Kronus271** [SunstriderEmu/BugTracker#2247]
When you are in shadowform as a priest and u cast a healing spell you will leave shadowform. But sometimes when you are still casting a heal or you are on global cooldown and spam the ability to go back into shadowform it bugs out. When the bug occurs the game thinks you are in shadowform (even tho u are not) and can not "leave" the shadowform or enter it again. In order to fix it u have to relog.
Sadly i dont know exactly how to produce this bug on purpose but for me atleast it happens most of the time when im doing pvp(BG/arena)

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by z5n** [comment]
related: #2782
issue has since been fixed
