### ISSUE TITLE
Master Looter / Looting problems in Karazhan

### ISSUE THREAD

**Issue by icjeffs** [SunstriderEmu/BugTracker#2248]
Hi, 
I was raid leading in Karazhan last night with Master looter turned on. 

Some problems I found withe masterloot / looting: 

- I had 'sparkles' on every single mob that died
- I couldnt see and thus couldnt loot some tailoring patterns and enchanting patterns. Others with the relevant profession could see the patterns. When i made them ML they were able to pickup the epic patterns. 
- I could see a leatherworkign pattern and could allocate it using ML which was odd considering i am not a LW.

Shanjeur
GM - Synergy

**Comment by Godmatik** [comment]
Confirmed, the looting was really annoying when master loot was enabled, all of us had sparkles on most mobs but with empty corpses.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2858
