### ISSUE TITLE
Karazahan blacksmith suggestion

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#2249]
The blacksmith next to attunmen not being active(allowing you to repair) on first time kara was really cancer, maybe its supposed to be reputation based (could not do it at friendly and havent been back since hitting honored), but with the # of wipes we had learning slightly different tactics and endless specific implementation of kara... its really cancer to summon back people for repair 2-3 times... especially with the warlock/summon stone bug (summon target changes mid summon without user doing it).  

please consider making the first blacksmith in kara available at neutral reputation

**Comment by Godmatik** [comment]
This is for reporting bugs, not suggestions.

Correct that the NPC does not allow repairs until honored, that's how it was during TBC retail.
