### ISSUE TITLE
Sunken Temple, Zolo: Doesn't summon his Atal'ai Skeleton Totem

### ISSUE THREAD

**Issue by Dract** [SunstriderEmu/BugTracker#2251]
**Describe the bug**
In Sunken Temple the Boss Zolo (https://db.endless.gg/?npc=5712) is meant to summon totems (https://db.endless.gg/?spell=12506) but he doesn't

**To Reproduce**

1. Engage Zolo
2. He doesn't use his totem at any point.

The spell exists in the database but he just doesn't seem to cast it, potentially an easy fix.

**Comment by Sheikthecatman** [comment]
Thanks! Zolo will now use his totem powers and skeletons shall rise from beneath empowering him in his battle.

Fix will be live next server restart.
