### ISSUE TITLE
Priest: Shadow: Mind Flay under water locks your camera

### ISSUE THREAD

**Issue by Mitchohh** [SunstriderEmu/BugTracker#2252]
**Describe the bug**
If you use Mind Flay under water (<=>while swimming), the camera is locked towards that position until you use it on another target. Even if you're done casting, the camera keeps turning towards your last mind flayed target.

**To Reproduce**
1. Cast Mind Flay on any target while swimming
2. Turn your camera
--> Camera turns back to where your last flayed target was.

Spell: https://wowhead.com?spell=15407

**Expected behavior**
Camera should snap to your mind flayed target once and never again, especially not after the target is dead.

**Comment by Jerrythemagicdog** [comment]
That's not something we control, your camera settings are stored in your client and never sent to the server. Please make sure your camera options are cleared such as "Smart Pivot" or Camera following style (most players use "Never").
