### ISSUE TITLE
Disenchanting BrightCloth Gloves Does Not Add Lesser Eternal Essence to the Inventory

### ISSUE THREAD

**Issue by bugreporterx** [SunstriderEmu/BugTracker#2255]
**Describe the bug**
When you disenchant Brightcloth Gloves[https://classic.wowhead.com/item=14101/brightcloth-gloves], you have a change to get Dream Dust and sometimes Lesser Eternal Essence[https://classicdb.ch/?item=16202]. The issue is in that the lesser eternal essences are not being added to one's inventory. They do appear in the loot table but for some reason are not being added to one's bags.

**To Reproduce**

1. Craft Brightcloth Gloves or buy them from the Auction House
2. Disenchant them while pressing the Shift key to be able to hold up the items in the loot table.
3. Add lesser eternal essence manually by clicking on it.
4. Check your bags

Item: https://classicdb.ch/?item=16202, https://classic.wowhead.com/item=14101/brightcloth-gloves

**Expected behavior**
When disenchanting these gloves, one should be able to get Dream Dust, Lesser Eternal Essence, or Small Brilliant Shard.

**Screenshots/videos**

**Additional context**
None.

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago, thanks.
