### ISSUE TITLE
Natural Remedies quest in hellfire bugged

### ISSUE THREAD

**Issue by Majst** [SunstriderEmu/BugTracker#2256]
**Describe the bug**
The interaction for the quest completion begins when you turn in the prequest, and not when you accept the actual quest.

**To Reproduce**
1.  Turn in "The Earthbinder" quest, and the quest mob immediately does the walk for the next quest where she summons an add you need to kill. If you did not accept "Natural Remedies" in time if you abandon the quest and regrab it she does not summon the creature.

NPC: https://tbc-twinhead.twinstar.cz/?npc=19294
Prequest: https://tbc-twinhead.twinstar.cz/?quest=10349
Quest: https://tbc-twinhead.twinstar.cz/?quest=10351

**Expected behavior**
The interaction should begin when you accept "Natural Remedies" and not begin when you turn in "The Earthbinder"

**Comment by Jerrythemagicdog** [comment]
The next quest requires you to Revitalize the Fallen Sky Ridge and requires a different creature to be killed. This RP event just spawns a Lured Colossus (https://db.endless.gg/?npc=20599) for no purpose whatsoever other than RP.
