### ISSUE TITLE
Mageslayer in Netherstorm (#18866) missing spell (#36096)

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2258]
Mageslayers in Netherstorm should have "Spell Reflection" but don't use it at all, and just white hit only.

**Comment by Godmatik** [comment]
Correction - he attempts to cast the spell on himself, but he is immune.

![Immune](https://user-images.githubusercontent.com/37913400/76483544-44bb2f00-63e5-11ea-8c8e-9c219f7df325.png)

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in [c35380469e9c3d9708578f05029c2c98ba1027b6](https://github.com/kelno/sunstrider-scripts/commit/c35380469e9c3d9708578f05029c2c98ba1027b6).

Fix will be live next server restart.
