### ISSUE TITLE
Naberius (NPC #20483)

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2260]
His melee hits seem accurate but his frostbolts are fairly weak, doing only 350ish damage when it should be closer to 500-800 damage range. Allows it to be soloed very easily as long as you kill him before he runs out of mana.

https://www.wowhead.com/npc=20483/naberius#comments

**Comment by Sheikthecatman** [comment]
Thanks! Most likely fixed in [c10eab6728447636a427136a02b4b925b26914e7](https://github.com/kelno/sunstrider-scripts/commit/c10eab6728447636a427136a02b4b925b26914e7)
