### ISSUE TITLE
Critical gruul bug

### ISSUE THREAD

**Issue by Bzmode** [SunstriderEmu/BugTracker#2261]
**Describe the bug**
if the person second on threat isn't in range he will not hateful anyone.

how it's supposed to work

Hateful 2nd highest threat that's in range.
if no one is in melee other then the tank then he hatefuls the tank.

**Comment by Jerrythemagicdog** [comment]
Thanks, could you provide proof of it happening as I see there is a check for that in the script?

**Comment by Bzmode** [comment]
Sorry, wasn't streaming it yesterday. During our multiple attempts when one of the warlocks/hunters would pass our second tank on threat there would never be another hateful unless they walked into melee range.

**Comment by Jerrythemagicdog** [comment]
Thanks, we added an additional check to make sure it doesn't happen.
