### ISSUE TITLE
Flask did not pertain thru death

### ISSUE THREAD

**Issue by Daedrenn** [SunstriderEmu/BugTracker#2262]
**Describe the bug**
The Flask of Relentless Assualt 120 atk power didnt not pertain thru threat

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by SUN-Leekie** [comment]
Cannot reproduce. Need more information.

**Comment by Godmatik** [comment]
Did you perhaps override the flasks with potions?
