### ISSUE TITLE
Heroic Quagmirran

### ISSUE THREAD

**Issue by Bzmode** [SunstriderEmu/BugTracker#2263]
When he uses his acid spray he just keeps targetting it on the tank no matter who gets the debuff.

how it should work:
It should face/hit the person who has the debuff.

**Comment by Godmatik** [comment]
Confirmed

**Comment by Ironjudgment** [comment]
Can confirm

**Comment by LevoDev** [comment]
can confirm

**Comment by SUN-Leekie** [comment]
Fixed at next restart.

**Comment by Bzmode** [comment]
The acid spray is targetting him Quag now, not sure if that's correct.
