### ISSUE TITLE
NPC backpedalling

### ISSUE THREAD

**Issue by Drilow** [SunstriderEmu/BugTracker#2264]
Hello,

more than a bug I would call it a missing feature.
The thing is when you're in combat with an NPC and you're in melee range with it and if you walk a bit forwards, so that you are 'inside' the NPC, the NPC should step back a little (at least, it's the case on classic WoW). This might not seem like much, but it changes a lot how you play as a tank.

Thanks for everything you do, despite a rocky start the server is very enjoyable to play on and wish you good luck on this journey :)

**Comment by Jerrythemagicdog** [comment]
Hello, the feature has been disabled as the client doesn't support the cool dark souls move mobs do in Classic and in older versions the creatures turn their back away which kind of defeats the purpose. Thanks for feedback!

**Comment by Drilow** [comment]
Ah that's sad, thanks for the reply :)
