### ISSUE TITLE
Reput from Nagas at Zangarmarsh

### ISSUE THREAD

**Issue by Macumbafeh** [SunstriderEmu/BugTracker#2267]
**Describe the bug**
all Nagas in Zangarmarsh don't give reputation when you kill one of them (like orcs in hellfire peninsula)

**To Reproduce**
Go in Zangarmarsh, kill Nagas there. You will not have reputation from them. 

**Expected behavior**
 Neutral to friendly, all Nagas in Zangarmarsh have to give 25 reputation when you kill one of them (like orcs in hellfire peninsula)

**Comment by Jerrythemagicdog** [comment]
Thanks, some creatures were missing the reputation kill reward. Fixed after next update!
