### ISSUE TITLE
Auction House Mail Bug

### ISSUE THREAD

**Issue by super33fungi** [SunstriderEmu/BugTracker#2268]
**Describe the bug**

As an Alliance player, I am receiving mail that says "Horde Auction House".
**To Reproduce**

1. Receive mail from the Alliance Auction House
2. Noice that it says "Horde Auction House"

Mail sent from the Alliance Auction House.
**Expected behavior**

Mail from the Alliance Auction House to say "Alliance Auction House".
**Screenshots/videos**

**Additional context**

**Comment by kelno** [comment]
Closed, I'll keep the now one
