### ISSUE TITLE
Crusader enchantment gives incorrect values.

### ISSUE THREAD

**Issue by AWIDIUS** [SunstriderEmu/BugTracker#2269]
As title says. Crusader enchantment gives 20 strength at 70lvl instead of 60 strength. 
![image](https://user-images.githubusercontent.com/45521546/76537335-eaba7800-647d-11ea-8566-0e0f133614e8.png) 
![image](https://user-images.githubusercontent.com/45521546/76538292-610baa00-647f-11ea-93ce-4254831f691c.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next server update (later today).
