### ISSUE TITLE
[Movement] Some creatures in formations near ramps go through them

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#227]
**Description:**

Some creatures that are part of a formation / patrol  near ramps fall through them.

For example: Murkblood Spearman (guid: 1101328) in heroic Underbog.

Video clip: https://streamable.com/1eb1c

rev: Sunstrider rev. 10353 (857762b7ebc2) 2019-02-01 17:28:52 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
To fix into creature formation system (wrong member target point)

**Comment by kelno** [comment]
Duplicate https://github.com/SunstriderEmu/BugTracker/issues/1280
