### ISSUE TITLE
[KARA] Nightbane - Skeletons

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2270]
The skeletons when landing during Nightbane's air phase are doing ~1k immolation ticks to anyone nearby. I don't show this as an ability they ever have had during TBC.

Is this a pre-nerf intentional or added mechanic?

They are also immune to all magic damage except holy.

**Comment by Jerrythemagicdog** [comment]
Although it was reverted rather quickly by Blizzard it was a thing on retail that we are using here:

https://wowwiki.fandom.com/wiki/Nightbane_(boss)
> Patch 2.0.10 (2007-03-06): Restless Skeletons no longer have immolation.
> Patch 2.0.10 (2007-03-06): Nightbane's Restless Skeletons are now immune to non-holy magical damage.

The spells used there match the patterns of other spells used in Karazhan so I would expect them to be the correct spells.

**Comment by Godmatik** [comment]
Thanks for the clarification!
