### ISSUE TITLE
[Priest] Improved Divine Spirit Not Working With Prayer of Spirit

### ISSUE THREAD

**Issue by Incarceron** [SunstriderEmu/BugTracker#2271]
**Describe the bug**
When specced into IDS, Prayer of Spirit will not give the bonus spell damage and healing power that is supposed to happen. Regular Divine Spirit works fine.

**To Reproduce**

1. Cast Divine Spirit to see improved buff.
2.  Remove Divine Spirit to see buff removed.
3.  Cast Prayer of Spirit to see improved buff not working

https://db.endless.gg/?spell=25312
https://db.endless.gg/?spell=32999

**Expected behavior**

Improved Divine Spirit should increase spell damage and healing by 10% of total Spirit. This is not happening with Prayer of Spirit

**Additional context**

I'm not sure if this is 100% reproduceable, sometimes it works with Prayer and sometimes it doesn't. I don't know what factors affect it, but in H SV it was not working correctly.

**Comment by Jerrythemagicdog** [comment]
Thanks, would need more details and reproduce steps here if possible.
