### ISSUE TITLE
Game Crashes in shattrah

### ISSUE THREAD

**Issue by stickandpoke** [SunstriderEmu/BugTracker#2272]
Sometimes in Shattrath city, my game crashes and i get an error report on the WoW client. It only happens in certain parts of the city and i noticed it also happens in the city in Zangarmarsh thats up high. 
below is the code in the error message

WoWBuild: 18606
Realm: Sunstrider [51.89.234.132:8085]
Local Zone: Shattrath City
Local Player: Stickandpoke, 0000000000003EBA, (-1842.38,5552.52,-12.4288)
Add Ons: 

=========================================================
Assertion Failed!

 App:         /Users/kevin/Downloads/World of Warcraft 2/World of Warcraft 2.app
 File:        /Volumes/F2/usrbuild/xb/build/WoW_8606patch2.4.3/WoW/Source/Mac/../ObjectMgrClient/ObjectMgrClient.cpp
 Line:        2025
 Error Code:  0x85100086
 Time:        2020-03-12 14.37.46 EDT

 Assertion:   Illegal client GUID dereference at /Volumes/F2/usrbuild/xb/build/WoW_8606patch2.4.3/WoW/Source/Mac/../Object/ObjectClient/Movement_C.cpp:73! Provided GUID 0xF11000000000007C

---------------------------------------------------------
Thread 0 (0x303) (Current)
  0 0x0004393a <unknown>
  1 0x00043f38 <unknown>
  2 0x000512e8 <unknown>
  3 0x000049c5 <unknown>
  4 0x000050f8 <unknown>
  5 0x0009aaf7 <unknown>
  6 0x0038b8de <unknown>
  7 0x0031e06f <unknown>
  8 0x0008ded3 <unknown>
  9 0x000946ad <unknown>
 10 0x00251fb7 <unknown>
 11 0x0025203f <unknown>
 12 0x0025349a <unknown>
 13 0x000f1159 <unknown>
 14 0x000a1be7 <unknown>
 15 0x000a1def <unknown>
 16 0x000a31b6 <unknown>
 17 0x003a33f6 <unknown>
 18 0x003a4972 <unknown>
 19 0x005dd68e <unknown>
 20 0x0017c905 <unknown>
 21 0x0000b5ea <unknown>
 22 0x002bb224 <unknown>
 23 0x002c05f7 <unknown>
 24 0x002c0882 <unknown>
 25 0x00011f05 <unknown>
 26 0x000036f9 <unknown>
 27 0x92e4cf28 _InvokeEventHandlerUPP(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*, long (*)(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*)) + 26
 28 0x92de685f DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 1970
 29 0x92de59f6 SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 376
 30 0x92de5872 _SendEventToEventTargetWithOptions + 40
 31 0x92e005fe ToolboxEventDispatcherHandler(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*) + 1303
 32 0x92de6cd9 DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 3116
 33 0x92de59f6 SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 376
 34 0x92e00ba9 _SendEventToEventTarget + 33
 35 0x92f80869 _ToolboxEventDispatcher + 82
 36 0x92f8072b _RunApplicationEventLoop + 192
 37 0x0000382a <unknown>
 38 0x000024fe <unknown>
 39 0x00002425 <unknown>
 40 0x00000001 <unknown>

Thread 1 (0xa03)
  0 0xa7bfaab6 ___workq_kernreturn + 10
  1 0xa7cab9c1 __pthread_wqthread + 415
  2 0xa7cab7aa _start_wqthread + 34
  3 0x00001200 <unknown>

Thread 2 (0x1c07)
  0 0xa7bfaab6 ___workq_kernreturn + 10
  1 0xa7caba74 __pthread_wqthread + 594
  2 0xa7cab7aa _start_wqthread + 34
  3 0x54485244 <unknown>

Thread 3 (0x4503)
  0 0xa7bfaab6 ___workq_kernreturn + 10
  1 0xa7cab9c1 __pthread_wqthread + 415
  2 0xa7cab7aa _start_wqthread + 34
  3 0x00000000 <unknown>

Thread 4 (0xa003)
  0 0xa7bf932e _mach_wait_until + 10
  1 0xa7b81b7d _nanosleep + 322
  2 0xa7b81a02 _usleep + 54
  3 0x0004e178 <unknown>
  4 0x00044a61 <unknown>
  5 0xa7cac5f8 __pthread_body + 137
  6 0xa7caf7f7 __pthread_start + 78
  7 0xa7cab7ce _thread_start + 34
  8 0x00000000 <unknown>

Thread 5 (0x6403)
  0 0x005ada63 <unknown>
  1 0x002b354d <unknown>
  2 0x0004c953 <unknown>
  3 0x0003dff3 <unknown>
  4 0x0003e46a <unknown>
  5 0x0079deef <unknown>
  6 0x0079e247 <unknown>
  7 0x000442ca <unknown>
  8 0x00044a61 <unknown>
  9 0xa7cac5f8 __pthread_body + 137
 10 0xa7caf7f7 __pthread_start + 78
 11 0xa7cab7ce _thread_start + 34
 12 0x00000000 <unknown>

Thread 6 (0x6503)
  0 0x005ad754 <unknown>
  1 0x002b354d <unknown>
  2 0x0004c953 <unknown>
  3 0x0003dff3 <unknown>
  4 0x0003e46a <unknown>
  5 0x0079deef <unknown>
  6 0x0079e247 <unknown>
  7 0x000442ca <unknown>
  8 0x00044a61 <unknown>
  9 0xa7cac5f8 __pthread_body + 137
 10 0xa7caf7f7 __pthread_start + 78
 11 0xa7cab7ce _thread_start + 34
 12 0x00000000 <unknown>

Thread 7 (0x6603)
  0 0x005ad927 <unknown>
  1 0x002b354d <unknown>
  2 0x0004c953 <unknown>
  3 0x0003dff3 <unknown>
  4 0x0003e46a <unknown>
  5 0x0079deef <unknown>
  6 0x0079e247 <unknown>
  7 0x000442ca <unknown>
  8 0x00044a61 <unknown>
  9 0xa7cac5f8 __pthread_body + 137
 10 0xa7caf7f7 __pthread_start + 78
 11 0xa7cab7ce _thread_start + 34
 12 0x00000000 <unknown>

Thread 8 (0x8e13)
  0 0xa7bf91d2 _mach_msg_trap + 10
  1 0xa7bf9713 _mach_msg + 47
  2 0x9a112b17 _glcDebugListener + 416
  3 0xa7cac5f8 __pthread_body + 137
  4 0xa7caf7f7 __pthread_start + 78
  5 0xa7cab7ce _thread_start + 34
  6 0x00000000 <unknown>

Thread 9 (0x8707)
  0 0xa7bf91d2 _mach_msg_trap + 10
  1 0xa7bf9713 _mach_msg + 47
  2 0xa7c11396 _mach_msg_server + 301
  3 0x0002c638 <unknown>
  4 0xa7cac5f8 __pthread_body + 137
  5 0xa7caf7f7 __pthread_start + 78
  6 0xa7cab7ce _thread_start + 34
  7 0x00000000 <unknown>

Thread 10 (0x8603)
  0 0xa7bfc11e _pread$NOCANCEL$UNIX2003 + 10
  1 0x0004d187 <unknown>
  2 0x0004d2dc <unknown>
  3 0x00035464 <unknown>
  4 0x00034800 <unknown>
  5 0x0079d8c9 <unknown>
  6 0x0079dc21 <unknown>
  7 0x0004edd4 <unknown>
  8 0x0004d770 <unknown>
  9 0x0004d92a <unknown>
 10 0x00045a3a <unknown>
 11 0x000330dc <unknown>
 12 0x000507d7 <unknown>
 13 0x000643a2 <unknown>
 14 0x000d7755 <unknown>
 15 0x0010ca43 <unknown>
 16 0x0010cc30 <unknown>
 17 0x95118a72 -[NSThread main] + 39
 18 0x9511891b ___NSThread__start__ + 1220
 19 0xa7cac5f8 __pthread_body + 137
 20 0xa7caf7f7 __pthread_start + 78
 21 0xa7cab7ce _thread_start + 34
 22 0x00000000 <unknown>

Thread 11 (0x8203)
  0 0xa7bfc7aa ___psynch_cvwait + 10
  1 0xa7cafb46 __pthread_cond_wait + 738
  2 0xa7cad5d5 _pthread_cond_wait + 25
  3 0x0028af73 <unknown>
  4 0x0006df0c <unknown>
  5 0x0010ca43 <unknown>
  6 0x0010cc30 <unknown>
  7 0x95118a72 -[NSThread main] + 39
  8 0x9511891b ___NSThread__start__ + 1220
  9 0xa7cac5f8 __pthread_body + 137
 10 0xa7caf7f7 __pthread_start + 78
 11 0xa7cab7ce _thread_start + 34
 12 0x00000000 <unknown>

Thread 12 (0xd103)
  0 0xa7bf91d2 _mach_msg_trap + 10
  1 0xa7bf9713 _mach_msg + 47
  2 0x933db899 HALB_MachPort::SendMessageWithReply(unsigned int, unsigned int, unsigned long, unsigned long, mach_msg_header_t*, bool, unsigned int) + 119
  3 0x933b6d41 HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 49
  4 0x933b3f25 HALC_ProxyIOContext::IOWorkLoop() + 1517
  5 0x933b372c HALC_ProxyIOContext::IOThreadEntry(void*) + 208
  6 0x933e3db6 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned long, unsigned int) + 20
  7 0x933b3403 HALB_IOThread::Entry(void*) + 71
  8 0xa7cac5f8 __pthread_body + 137
  9 0xa7caf7f7 __pthread_start + 78
 10 0xa7cab7ce _thread_start + 34
 11 0x00000000 <unknown>

Thread 13 (0xd203)
  0 0xa7bf932e _mach_wait_until + 10
  1 0x94860ec6 _MPDelayUntil + 22
  2 0x0068f807 <unknown>
  3 0x006b52a9 <unknown>
  4 0xa7cac5f8 __pthread_body + 137
  5 0xa7caf7f7 __pthread_start + 78
  6 0xa7cab7ce _thread_start + 34
  7 0x00000000 <unknown>

Thread 14 (0xd407)
  0 0xa7bf932e _mach_wait_until + 10
  1 0x94860ec6 _MPDelayUntil + 22
  2 0x0068f807 <unknown>
  3 0x006b52a9 <unknown>
  4 0xa7cac5f8 __pthread_body + 137
  5 0xa7caf7f7 __pthread_start + 78
  6 0xa7cab7ce _thread_start + 34
  7 0x00000000 <unknown>

Thread 15 (0xd503)
  0 0xa7bfc7aa ___psynch_cvwait + 10
  1 0xa7cafb46 __pthread_cond_wait + 738
  2 0xa7caf1fa _pthread_cond_timedwait + 27
  3 0x0028ae6d <unknown>
  4 0x002ab8f8 <unknown>
  5 0x002aba42 <unknown>
  6 0x0010ca43 <unknown>
  7 0x0010cc30 <unknown>
  8 0x95118a72 -[NSThread main] + 39
  9 0x9511891b ___NSThread__start__ + 1220
 10 0xa7cac5f8 __pthread_body + 137
 11 0xa7caf7f7 __pthread_start + 78
 12 0xa7cab7ce _thread_start + 34
 13 0x00000000 <unknown>

Thread 16 (0x13203)
  0 0xa7bfe3fe ___select_nocancel + 10
  1 0xa7bfc375 _select + 78
  2 0x002aae38 <unknown>
  3 0x002abdf6 <unknown>
  4 0x0010ca43 <unknown>
  5 0x0010cc30 <unknown>
  6 0x95118a72 -[NSThread main] + 39
  7 0x9511891b ___NSThread__start__ + 1220
  8 0xa7cac5f8 __pthread_body + 137
  9 0xa7caf7f7 __pthread_start + 78
 10 0xa7cab7ce _thread_start + 34
 11 0x00000000 <unknown>

Thread 17 (0xde0b)
  0 0xa7bf91d2 _mach_msg_trap + 10
  1 0xa7bf9713 _mach_msg + 47
  2 0x937c820b ___CFRunLoopServiceMachPort + 289
  3 0x937c7935 ___CFRunLoopRun + 2896
  4 0x937c6ae8 _CFRunLoopRunSpecific + 584
  5 0x937df8ad _CFRunLoopRunInMode + 82
  6 0x92a8ae04 -[__CoreSchedulingSetRunnable runForever] + 579
  7 0x92a8aa3d +[__CoreSchedulingSetRunnable _run:] + 129
  8 0x95118a72 -[NSThread main] + 39
  9 0x9511891b ___NSThread__start__ + 1220
 10 0xa7cac5f8 __pthread_body + 137
 11 0xa7caf7f7 __pthread_start + 78
 12 0xa7cab7ce _thread_start + 34
 13 0x00000000 <unknown>

Thread 18 (0xe317)
  0 0xa7c18542 ___sem_wait_nocancel + 10
  1 0x006b5275 <unknown>
  2 0xa7cac5f8 __pthread_body + 137
  3 0xa7caf7f7 __pthread_start + 78
  4 0xa7cab7ce _thread_start + 34
  5 0x00000000 <unknown>

Thread 19 (0x12a1b)
  0 0xa7c18542 ___sem_wait_nocancel + 10
  1 0x006b5275 <unknown>
  2 0xa7cac5f8 __pthread_body + 137
  3 0xa7caf7f7 __pthread_start + 78
  4 0xa7cab7ce _thread_start + 34
  5 0x00000000 <unknown>

Thread 20 (0x11417)
  0 0xa7bfc7aa ___psynch_cvwait + 10
  1 0xa7cafb46 __pthread_cond_wait + 738
  2 0xa7caf1fa _pthread_cond_timedwait + 27
  3 0x0028ae6d <unknown>
  4 0x00512f76 <unknown>
  5 0x0010ca43 <unknown>
  6 0x0010cc30 <unknown>
  7 0x95118a72 -[NSThread main] + 39
  8 0x9511891b ___NSThread__start__ + 1220
  9 0xa7cac5f8 __pthread_body + 137
 10 0xa7caf7f7 __pthread_start + 78
 11 0xa7cab7ce _thread_start + 34
 12 0x00000000 <unknown>

Thread 21 (0xf993)
  0 0xa7bf932e _mach_wait_until + 10
  1 0x94860ec6 _MPDelayUntil + 22
  2 0x0068f807 <unknown>
  3 0x006b52a9 <unknown>
  4 0xa7cac5f8 __pthread_body + 137
  5 0xa7caf7f7 __pthread_start + 78
  6 0xa7cab7ce _thread_start + 34
  7 0x00000000 <unknown>

Thread 22 (0x8f4f)
  0 0x00000000 <unknown>

Thread 23 (0xe41b)
  0 0xa7c18542 ___sem_wait_nocancel + 10
  1 0x00044a61 <unknown>
  2 0xa7cac5f8 __pthread_body + 137
  3 0xa7caf7f7 __pthread_start + 78
  4 0xa7cab7ce _thread_start + 34
  5 0x00000000 <unknown>

Thread 24 (0x911f)
  0 0xa7c18542 ___sem_wait_nocancel + 10
  1 0x00044a61 <unknown>
  2 0xa7cac5f8 __pthread_body + 137
  3 0xa7caf7f7 __pthread_start + 78
  4 0xa7cab7ce _thread_start + 34
  5 0x00000000 <unknown>

=========================================================

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Godmatik** [comment]
Your client is corrupt, remove it, need to start over with a fresh one.

**Comment by Jerrythemagicdog** [comment]
That's not something we control indeed, try with a fresh client. Third party Mac .apps are also not supported and are a big question mark when it comes to how they perform, sorry!
