### ISSUE TITLE
Can't turn in quest  [Nat Pagle, Angler Extreme]

### ISSUE THREAD

**Issue by Luttners** [SunstriderEmu/BugTracker#2273]
**Describe the bug**
I can't turn in the quest  [Nat Pagle, Angler Extreme], i got all of the dish in my bag but the **Continue** button is grayed out, when i run up to Nat Pagle he have the Yellow questionmark over his head indecating the quest is done and i cna see the Compleate mar in the quest log.

**To Reproduce**

1. Get the quest and fish up all the fishes

Item: https://classic.wowhead.com/item=16967/feralas-ahi
Item: https://classic.wowhead.com/item=16970/misty-reed-mahi-mahi
Item: https://classic.wowhead.com/item=16968/sartheris-striker
Item: https://classic.wowhead.com/item=16969/savage-coast-blue-sailfin

Quest: https://classic.wowhead.com/quest=6607/nat-pagle-angler-extreme

**Expected behavior**
Beeing able to turn in quest ;( 

**Screenshots/videos**
[![Screenshot from Gyazo](https://gyazo.com/32d994028d3bc50cbafd2074057b30ee/raw)](https://gyazo.com/32d994028d3bc50cbafd2074057b30ee)

**Additional context**
>

**Comment by Jerrythemagicdog** [comment]
Please try clearing your Cache and try to turn in the quest again.

**Comment by Luttners** [comment]
Tried to remvoe cash and everything, still nothing and when i removed the quest, i was not able to pick it up again :(
