### ISSUE TITLE
Epic engineering helmet causes active node tracking to disappear

### ISSUE THREAD

**Issue by Kraggenlord** [SunstriderEmu/BugTracker#2274]
While wearing the epic engineering helmet, tracking nodes (at least mining) disappears and is replaced by I guess the gas cloud tracking. This especially happens when you switch stances as a warrior.

**To Reproduce**

1. Track minerals
2. Equip epic engineering helm
3. Watch the track minerals disappear.
3,5. Swap stances as a warrior and watch it happen in real-time.

Item in question: https://tbcdb.com/?item=32473

**Expected behavior**
As far as I understand, wearing the helmet should not remove your current active node tracking group. It should show both the chosen group and the gas clouds, not forcing you to unequip your helmet in order to mine/herb properly.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed after next server restart, if there are still issues please comment here.

**Comment by Jerrythemagicdog** [comment]
Assuming it's fixed, closing the issue.
