### ISSUE TITLE
Skull of Impending Doom unusable

### ISSUE THREAD

**Issue by Pindrought** [SunstriderEmu/BugTracker#2275]
**Describe the bug**
When you try to use Skull of Impending doom, it says that you have no target.

**To Reproduce**
1. Equip Skull of Impending Doom.
2. Use Skull of Impending Doom.
Item: https://classic.wowhead.com/item=4984/skull-of-impending-doom

**Expected behavior**
The item should be usable.

**Comment by karleonroflWTF** [comment]
We are waiting for the fix and excellent work of the skull   ,,I hope"

**Comment by SuddenDeath** [comment]
Still unusable

**Comment by Aeonicz** [comment]
Could you fix this item by any chance? Amazing in BG's

**Comment by z5n** [comment]
Fixed some time ago
