### ISSUE TITLE
Remorseless Attacks triggers even if the target doesn't yield any experience or honor

### ISSUE THREAD

**Issue by emilavara** [SunstriderEmu/BugTracker#2276]
**Describe the bug**
Remorseless Attacks triggers even if the target doesn't yield any experience or honor.

**To Reproduce**
1. Talent into Remorseless Attacks
2. Kill gray target
3. Get "Remorseless" buff

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
