### ISSUE TITLE
No Spirit Healer In Darkshore for horde

### ISSUE THREAD

**Issue by Rumjunkie** [SunstriderEmu/BugTracker#2279]
Description: Graveyard/spirit healer north of Auberdine in Darkshore doesn't appear (for horde at least) while it should.

How it works: If you die at Darkshore as a horde, you will be ported back to graveyard at Splintree Post in Ashenvale (around 2 zones away)

How it should work: Graveyard north of Auberdine should work for horde

Source (you should point out proofs of your report, please give us some source):
multiple guides dating back to tbc (on topic how to get a ravager pet early as a horde hunter) like this one: https://2wowdoctors.wordpress.com/2008/03/18/the-more-than-complete-guide-on-how-to-get-a-ravager-pet-as-a-horde-hunter/

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
