### ISSUE TITLE
Petrified Lichen Guard doesn't proc

### ISSUE THREAD

**Issue by Rockbiter-shaman** [SunstriderEmu/BugTracker#2283]
**Describe the bug**
When shield successfully blocks, it is supposed to proc a stacking deadly poison effect. It does not do anything of the sort when it blocks

**To Reproduce**

1. used high block chance effects
2. blocked, didn't proc any sort of poison

Item: https://www.wowhead.com/item=25828/petrified-lichen-guard

**Expected behavior**
blocking an attack causes identical effect to a rogue's deadly poison, 12dmg per 3 secs stacking up to 5 for 60dmg per 3sec

**Additional context**
the poison from this shield is also supposed to generate threat

**Comment by SUN-Leekie** [comment]
> 22:16:36> Darkcrest Slaver's melee swing hits Gala for 79 Physical. (83 Blocked)
22:16:36> Darkcrest Slaver is afflicted by Spore Cloud.

Also generates threat.
Will need more information to reproduce. Closing in the meantime.

**Comment by Rockbiter-shaman** [comment]
nope. ur test is flawed, use it on non-zangarmarsh mobs. it won't proc. or just wait for alliance paladins to throw a fit about it later for AoE farming, as long as it eventually gets fixed.

**Comment by Sheikthecatman** [comment]
![image](https://user-images.githubusercontent.com/59149613/76799075-22ecee00-67d1-11ea-9dd0-bc730ab6df09.png)
