### ISSUE TITLE
Warrior - Rend skill not scaling with weapon damage

### ISSUE THREAD

**Issue by BOMBARE** [SunstriderEmu/BugTracker#2284]
Rend skill not scaling with weapon damage.
It ticks only for 31 damage with max rank

**Comment by Ibuprofeno** [comment]
It didn't scale with weapon dmg until LK. 
Source:
Wrath of the Lich King Patch 3.0.3 (2008-11-04): Damage has been adjusted to be less base and more weapon based. Ranks 9 and 10 now do 35% more damage when the target is above 75% health instead of 4 times damage when the target is enraged.
