### ISSUE TITLE
Warlock: Seed of Corruption damage severely reduced.

### ISSUE THREAD

**Issue by Haldihr** [SunstriderEmu/BugTracker#2287]
**Describe the bug**

When Seed of Corruption is cast and there are many mobs around(approx 30+ up to 70mobs)
the damage dealt upon explosion is serverely reduced to about 1/4- 1/3 of the damage. In my case it pops for around 400-500ish when it should be around 1600.

**To Reproduce**

1.  Go into an instance. ( Like Scarlet Monestary)
2. Aggro 30+ mobs with your pet. 
3. Then begin to cast Seed of Corruption on targets. 
 When they explode it wont be for normal damage.
1

Item: -
Quest: -
Spell: https://www.wowhead.com/spell=27243/seed-of-corruption

**Expected behavior**

It should explode for full damage, approx 1600damage instead of 400-500.

**Screenshots/videos**

![bild](https://user-images.githubusercontent.com/47000550/76615317-1858fd00-6522-11ea-9d9b-186cbd893af3.png)

**Additional context**

None that I can think of.

**Comment by AshamedPlayer** [comment]
AoE spells on TBC has cap of 10 targets for maximum damage. Only exception is consecration.
