### ISSUE TITLE
General (/1) and /2 /3 channels

### ISSUE THREAD

**Issue by Macumbafeh** [SunstriderEmu/BugTracker#2288]
**Describe the bug**
When you log in, General (/1) and /2 /3 channels don't work. You have to leave the area and back in to see/write in that channels.

**To Reproduce**
Log in. 
Try to write in /1 /2 /3 channels. 
You will see you can't write or see someone write in.

**Expected behavior**
When you log in, General (/1) and /2 /3 channels must be avalaible.

**Comment by Godmatik** [comment]
Confirmed.

**Comment by InhumanGM** [comment]
Are you still experiencing this issue?

**Comment by InhumanGM** [comment]
Until a fix is applied for this issue, you can join the global channel. _/join global_
