### ISSUE TITLE
Earthbind Totem not pulsing correctly

### ISSUE THREAD

**Issue by TheMoneyHater** [SunstriderEmu/BugTracker#2289]
How it's suppose to be:
https://wowwiki.fandom.com/wiki/Earthbind_Totem
under Tips
"It's helpful to drop a totem just before running from a fight to gain some distance between you and your pursuer, as well as just before your enemy is about to run away. It takes a second to have its first effect, so you should drop it a couple seconds before you need it for best effect."
1 second after the first pulse, but on endless it takes 3 seconds for it to pulse the first time.

Check this video https://streamable.com/l2n96 and look under the target frame and the timer I activate on the same button.

**Comment by SUN-Leekie** [comment]
Thanks! Fixed at next restart.

**Comment by TheMoneyHater** [comment]
Why did you make so it procs instant? It's suppose to take 1 second before the first pulse, not instant, or 3 sec as it was before!
