### ISSUE TITLE
Quest - Ulag the cleaver - Warrior lvl 10 quest

### ISSUE THREAD

**Issue by JesperStoico** [SunstriderEmu/BugTracker#2290]
**Describe the bug**
You are not able to activate the quest so the door opens in the graveyard and the mob spawn.

**To Reproduce**
Normally you touch the panel on the ground and the seal break on the door and he spawns.
You can press the panel, nothing happens. 
You can press the seal on the door, it removes/opens but nothing happens.
Mob never spawns.

Wowhead link for the quest - https://classic.wowhead.com/quest=1819/ulag-the-cleaver

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
Quest previously required the player to open the door by themselves.
