### ISSUE TITLE
Shutdown Mana Forge questline bugged

### ISSUE THREAD

**Issue by mgperera** [SunstriderEmu/BugTracker#2292]
I can't take the follow up for the Aldor questline in Netherstorm that leads to the Shutdown Manaforge quests. The last step I'm stuck at is B'naar Console Transcription. The last quest asked me to turn in at the console, okay i did it and i saw the next quest avaiable BUT someone started a later step, to shutdown that manaforge and somehow i couldnt take MY quest anymore.
Even after a couple of days, trying to take quest again from the aldor npc and from the console i'm sitll STUCK in one of the most important questlines in netherstorm!

I can actually see the Exclamation Mark in the console, but when i talk to it theres no quest!

**Comment by SUN-Leekie** [comment]
Thanks for the report.
Fixed at next restart.
