### ISSUE TITLE
Cant change specialization alchemy

### ISSUE THREAD

**Issue by wowjocke1337** [SunstriderEmu/BugTracker#2298]
I cant change my specialization in alchemy from elixir to pot master. It should be my specialization trainer (elixir) in shat that can help me with that. NPC name = Lorokeem.

Iven tryed to talk to alch trainer in Honor hold + pot master trainer in zanga.

**Comment by Godmatik** [comment]
Did you finish the Elixir master questline?

**Comment by blblblaz** [comment]
hello, this issue got fixed recently and you should be able to change spec now, I've just tested on the live server and it works. If there's something wrong that we've missed feel free to write in this issue again.
