### ISSUE TITLE
"Chasing the Moonstone" quest from Druid Swift Flight Form questline is bugged

### ISSUE THREAD

**Issue by Proclamer** [SunstriderEmu/BugTracker#2299]
Chasing the Moonstone is one of the final quests from the swift flight form questline. Basically u need to chase a goblin to hand over a moonstone that he stole. The problem is that even if u catch up with him and he says that he surrenders he still keeps swiming away when it should stop. Please look into it and try to fix it. Ty for your time

**Comment by InhumanGM** [comment]
When I attempt the quest, the NPC swims for about 6-7 minutes before getting rooted in place, allowing me to catch up and complete the quest. Do you have anymore information that could be used to reproduce the issue again?
