### ISSUE TITLE
[GRUUL RAID] - Kiggler the Crazed

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2306]
If whoever has aggro goes into melee range of Kiggler, he will stop casting lightning bolts and instead do weak melee white hits.

**Comment by Jerrythemagicdog** [comment]
His Lightning Bolt (36152) has a min range of 8 yards. His melee attacks deal nature damage (custom) which should be equivalent to the damage of his Lightning Bolt.

**Comment by Godmatik** [comment]
Gotcha. 

I don't have logs but the white hits were barely doing any damage to our tank. Can test again to see what exactly that damage is.
