### ISSUE TITLE
Quest "Bloodgem Crystals" In Netherstorm is bugged

### ISSUE THREAD

**Issue by FingerBlaster9000** [SunstriderEmu/BugTracker#2309]
<So for the quest you're supposed to kill mobs that gives you a bloodgem shard, you're supposed to use that shard to siphon a bloodgem crystal. But once you click it and start the siphon it instantly gets removed so you can't complete the quest.>

**Comment by michaelkittrell** [comment]
i agree, tried to complete it with 3 differenct scryer characters including trying 1 aldor toon.  none could channel the blood gem long enough to get completion flag.  Tried at 4-5 different crystals, instant cancel on the channeling.

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2058
