### ISSUE TITLE
Upper Black Rock Spire doors doesn`t work (not scripted?)

### ISSUE THREAD

**Issue by dwarfkac** [SunstriderEmu/BugTracker#2312]
How it should work : 
First door on the instance should open after clering 7 rooms of mobs and cliking on runes. First issue is - the runes are not clickable - therefore doors doesn`t open.
Second door (after opening first by GM) - should open with Seal of Ascension - they aren`t clickable either
Third door ( behind Pyroguard boss) also doesn`t open and whole even doesn`t work as intended. 
Boss should be summoned after killing mobs in room and channeling on altar nearby, not stand there all the time.
Fourth door (at arena) is not open so the only way to go to arena is jump on it. Arena doesn`t work either - even starts at random moment, probably induced by gm opening some of the doors for us, and after realy glitchy encounter...
Fifth Door (behind arena) doesn`t open after the event which should happen.

I am not into scripts and coding, but I found some thread which may help you understand the issue. Here is the link : https://github.com/TrinityCore/TrinityCore/issues/4414
Lower in the thread there is quote covering all the doors ... codes (?)
Anyway. I and my friends would love you to look into this awesome instance, and make it great again.

**Comment by Godmatik** [comment]
The runes don't need to be clickable, they should automatically light up after the mobs in each of the little areas are cleared.

**Comment by dwarfkac** [comment]
Nonetheless, doors remain closed.

**Comment by Sheikthecatman** [comment]
First three doors have since been fixed.
