### ISSUE TITLE
Quest The Raven Stones not work

### ISSUE THREAD

**Issue by Hustler495** [SunstriderEmu/BugTracker#2315]
I paid 5000 gold for riding. I’m doing a chain of quests for a flying form of 280%. The Raven Stones quest is not working. I can’t use the stones and put them in my bag

**Comment by blblblaz** [comment]
hello, they are usable on my end but it's hard to click on them because the bird is ontop of them, the quest is completable on my end, what exactly was your problem?

**Comment by InhumanGM** [comment]
Are you still having this issue?
