### ISSUE TITLE
Wild Fel Stalkers immune to ensalve

### ISSUE THREAD

**Issue by ageerik** [SunstriderEmu/BugTracker#2316]
Wild Fel Stalkers in gruul's lair should not be immune to enslave.
proof: https://wow.gamepedia.com/Krosh_Firehand
''The only exception to this maintained aggro is that it is a common strategy for Warlocks who are Enslaving Olm's Wild Fel Stalkers to place them on Krosh to have them disposed of.''

**Comment by blblblaz** [comment]
Would really like some reproduce steps or video footage if possible, because on my end they are enslave-able and if they're immune thats not intended by us
