### ISSUE TITLE
Ravager's thorns at Hellfire Peninsula

### ISSUE THREAD

**Issue by Macumbafeh** [SunstriderEmu/BugTracker#2318]
**Describe the bug**
The dps off Ravager's thorns buff at west of Hellfire Peninsula is too high.
The buff dps more than the mob.

**To Reproduce**
Go at West of Hellfire Peninsula and fight a Ravager.
You will see how this buff deal damage.

https://www.thegeekcrusade-serveur.com/db/?spell=25640

**Expected behavior**
Ravager's thorns have to deal like 40 damages.

**Comment by blblblaz** [comment]
thanks for the issue, the fix is live already
