### ISSUE TITLE
NPC Spell #38048 "Curse of Pain" 

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2320]
1. Lasts 60 seconds, should only last 15 seconds.
2. "This effect is removed if the target falls below 50% health" - does not occur, the curse remains even if you are below 50%
3. The damage also seems pretty low, only ticking for 79 shadow damage every 3 seconds, but I can't find a source to confirm if this is correct or not.

https://www.wowhead.com/spell=38048/curse-of-pain

**Comment by Jerrythemagicdog** [comment]
Spell was changed in a later expansion so the duration also changed.
Fixed the part where it wasn't correctly removed if the target crossed 50% hp (live with next update).
About damage the spell has an attribute that scales with the caster's level so maybe it's intended in some cases, depending on the caster's level.
Thanks for the issue.
