### ISSUE TITLE
Fel Lotus drop rate

### ISSUE THREAD

**Issue by wiglefish** [SunstriderEmu/BugTracker#2321]
**Describe the bug**
I know this might be a rate change more than a bug, but unlike many other profession items, the drop rate for Fel Lotus seems to be incredibly high to the point that I sometimes get them multiple times within 10-15 minutes and far too frequently in lots of 2-3. 

This is clearly (they cost 2g!) affecting the economy and will be very bad long term.

**To Reproduce**
Just herb for about an hour and have 5-10 of them.

**Expected behavior**
This should be a 1 in 30-50 herb with 99% of gatherings resulting in 1 lotus. The higher level herbs are the ones with about 1 in 20-25 chance.

**Additional context**
https://www.wowhead.com/item=22794/fel-lotus#gathered-from-object

**Comment by Godmatik** [comment]
I can't speak to the drop rate itself, wowhead says around 10-15% per plant.

But I believe they should only drop a maximum of one if you get it from a herb node, but you have the potential to loot 2-3 off a single plant.

**Comment by wiglefish** [comment]
> I can't speak to the drop rate itself, wowhead says around 10-15% per plant.
> 
> But I believe they should only drop a maximum of one if you get it from a herb node, but you have the potential to loot 2-3 off a single plant.

yes they say that it can drop in more than 1 off the skettis elite trees but no mention of it for normal herbs so this could potentially be a bug. 
Either ways, getting 3 almost every time I do get one is faaar too much. Also wowhead doesn't say 10-15%, it says 2-6% depending on the herb.

I just hope that this can be addressed asap because right now they cost almost nothing on auction.

**Comment by ulekki** [comment]
Can we actually have some attention to this issue? Normally the most expensive herb in TBC right now 
is some trash that no one needs and some even just vendor it away.
