### ISSUE TITLE
ALDOR Manaforge  Questline Bugged

### ISSUE THREAD

**Issue by Elwun** [SunstriderEmu/BugTracker#2324]
**Describe the bug**

If you are ALDOR you can accept the quests manaforge but when you get the crystal to use the consoles you can't.
SCRYERS can do it no problem.

**To Reproduce**

1. Be ALDOR
2. Loot Crystal to activate Event
3. Can't activate

Item: https://wowhead.com?item=29366
Quest: https://wowhead.com?quest=10299
Spell: https://wowhead.com?spell=

**Expected behavior**

After getting the crystla you cna interract with the event no problem

**Screenshots/videos**

**Additional context**

Any SCRYER can do it no problem

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart!
