### ISSUE TITLE
[BUG] Karazhan Books from Sealed Tomes

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2328]
Torment of the Worgen
Legacy of the Mountain King
Redemption of the Fallen
Wrath of the Titans

The buffs from using these books are supposed to go away when exiting Karazhan, but they don't. So you can use them in other dungeons/raids/outside world/etc.

**Comment by Godmatik** [comment]
Sorry for the bump, but I hope the devs are looking into this? 

People are popping their Kara books when doing Gruul and Mag.

**Comment by kelno** [comment]
https://db.endless.gg/?spell=30567
https://db.endless.gg/?spell=30564
https://db.endless.gg/?spell=30731

https://db.endless.gg/?spell=30562
https://db.endless.gg/?spell=30559

https://db.endless.gg/?spell=30550
https://db.endless.gg/?spell=30553

https://db.endless.gg/?spell=30557
https://db.endless.gg/?spell=30610

spell_template.areaId

**Comment by kelno** [comment]
Fixed with next update

**Comment by kelno** [comment]
Also 3249449c4a715ad58426c468d2b70eb7723096d9
