### ISSUE TITLE
Orc Ancestor in Nagrand

### ISSUE THREAD

**Issue by Macumbafeh** [SunstriderEmu/BugTracker#2329]
**Describe the bug**
Orc Ancestor in Nagrand around Oshu'gun are missing. There is just like 4-8 in Oshu'gun, but they have to be "around" Oshu'gun too to complete the quest "What the Soul Sees".

**To Reproduce**
Go In Nagrand at Oshu'gun Area, you will see there is no Orc Ancestor around.

https://www.wowhead.com/quest=10168/what-the-soul-sees

**Expected behavior**
Orc Ancestor have to be around Oshu'gun to complete the quest "What the Soul Sees".

**Comment by Macumbafeh** [comment]
You need the mirror from the quest to see them. but sometimes it bug and some player can't see them even if they have the mirror.

But imo you don't need the mirror to see them...

**Comment by blblblaz** [comment]
you need to complete this quest - https://www.wowhead.com/quest=10252/vision-of-the-dead in order to see the Ancient Orc Ancestors
