### ISSUE TITLE
[Research] Creature movement while chasing in combat

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#233]
**Description:**

Currently on Sunstrider when a creature follows a player or another unit in combat the movement looks jittery - it seems to stop and cancel it's moving animation while following the player and attacking him. My theory is that it's because of canceled attack animations being overriden by the movement animations.

In this issue I aim to gather sources proving what's the correct creature behavior while chasing other units.

1. Example 1
Classic WoW Demo: https://youtu.be/w3iYwCWPPEY?t=1529
Same mob on Sunstrider: https://streamable.com/lgowc

The difference is subtle and the source from classic demo is not long, but we can easily observe that the creature stops to perform an attack animation, while on Sunstrider we can't see the attack animation at all.

**Comment by Jerrythemagicdog** [comment]
> [11:08 AM] Kelno: I think the main difference from the already included example in the issue
> [11:08 AM] Kelno: Is that the retail creature does some target "leading"
> [11:08 AM] Kelno: It does try to predict the player movement and does advance a bit burther
> [11:09 AM] Kelno: Rather than the pserver logic where it does just come to the current player position will be obsolete by the time he gets there

**Comment by kelno** [comment]
Reworked with https://github.com/SunstriderEmu/BugTracker/issues/1282
