### ISSUE TITLE
 Quest - Chasing The Moonstone dont work now. I paid 5000 goldfor what?

### ISSUE THREAD

**Issue by Hustler495** [SunstriderEmu/BugTracker#2330]
Cant speal with NPC for complete Quest - Chasing The Moonstone. even when I catch up with him in the water he does not start a dialogue

**Comment by blblblaz** [comment]
that's weird, the quest is functional and there has been people that have completed it already, could you elaborate a bit more on exactly what happens when you catch up to the NPC?

**Comment by Hustler495** [comment]
The NPC does not stop when it says that it was burning. But even when I catch up with him completely, I can click on him, but he doesn’t start any dialogue but continues to swim to Orgrimmar.

**Comment by InhumanGM** [comment]
I was able to interact with the NPC after about 6-7 minutes of swimming trying to catch up. Are you still experiencing this issue?
