### ISSUE TITLE
[Suggestion] bg issue / organisation

### ISSUE THREAD

**Issue by Macumbafeh** [SunstriderEmu/BugTracker#2331]
There is no bug, i'm just making some suggestion.

First of all, i'm on horde side, and i'm seeing a lot of complaint about bg from allies and horde too.

Ally Fact is queue is too high cause horde don't queue.

Horde Fact is they don't queue anymore cause eveytime they queue alone it's a 14vs2. If they queue it's with premade, and that happen few Times. So atm horde just do Wpvp to get honor, because it's faster for them.

Suggestion : Need to make a rule : if 1 horde enter in bg, then 1 Ally Can enter to avoid 14 vs 2 and have at last balanced bgs.
It will change Allies' long queue a little bit, and atleast more bg will open because more horde poeple will queue bg with that system.

Suggestion 2 : Make a bg script to queue  bg remotely.

For example : 
.bg warsong / .bg arathi  ect....

It will enhance bg, and will open more bg to avoid allies' long queue.
It can enhance low bg too.

----------------------------------------------

So as i Said, PvP ATM is dead because of that bg issue. 
Allies have free 100% mount and Can easy farm horde poeple at hellfire peninsula. Horde Can have free 60% now at lvl 60 but it's not fair enough. Then horde waste Time to reach 70.

I don't know if i Can talk about free reput and honor for allies... Lot of them are already exalted and have better Gear than horde players and dominate arenas ATM.
Unfort, all of that ruined the PvP : /
Imo faction transfer can't be a good way.

Ty, Macumba

**Comment by dmtriblox** [comment]
in my opinion the best solution to this is to open faction transfert from ally to horde and make cross faction queue and enable the possibility to desable world pvp for players coz it's so annoying playing as a hord right now always 5 alliance vs 1 horde u can't even xp in strangth valley without dying every minut

**Comment by Macumbafeh** [comment]
I desagree about transfer... You can't give free 100%, reputation and other + go horde after... That's not fair for poeple who leveled  as horde since begining...
Rest i agree

**Comment by geraldoghc** [comment]
Add cross faction BG. This server will sadly die without it. Just do it fast.

**Comment by ageerik** [comment]
As ally I feel the pain the horde have. The only way to farm honor as ally is to world pvp, can't be fun to play as horde. Cross faction if the transfer doesn't solve the issue

**Comment by wiglefish** [comment]
+ for mercenary mode BGs 
+ for transfer with heavy restrictions (IE: Must have less than 2 days /played at 70 and/or can't transfer more than 2k gold / any valuable items (for obvious reasons)

**Comment by grabblesaur** [comment]
As a horde player i feel frustration: everytime bg becomes one-sided. 
Balancing factions is kinda hard, so cross bg sounds valid

**Comment by DiaWreckingball** [comment]
Cross BG is a bad idea - with cross bg player have no intention to roll horde. 

And no transfers - after getting those perks is it unfair to all horde players who started as horde.

**Comment by ageerik** [comment]
@diawreckingball ''with cross bg player have no intention to roll horde.'' - This is not true, horde have always had slightly better racials in pve which the majority of the people are playing.

''after getting those perks is it unfair to all horde players who started as horde.'' - Well, right now there is a problem, about 60 allys in queue with over 1 hour queue time. We need a solution and they will make this happen in the coming days. You can't stop making changes that is needed for the pvp to survive because someone have invested some more time in the game than others.

**Comment by DiaWreckingball** [comment]
@ageerik Why don't you remove those free riding perks for all new players/chars and the honor/rep bonuses for all players/chars?
Just adding cross BG and xfers is correcting mistakes by adding more mistakes.

**Comment by ageerik** [comment]
I been playing here for 3 weeks, I can't remove anything NickyQ. I broke down your arguments you had that everything is a bad idea. I also think they should add all pers to both factions.

**Comment by Macumbafeh** [comment]
@DiaWreckingball  i agree with you... You can't bring poeple who are full geared with honor / rep faster than horde... Need to fix "why horde don't queue anymore"
Because they are easy farmed. On Netherwing, if 1 horde enter in a bg then 1 Ally Can enter too. So if there is 6 horde, 6 allies Can enter, to avoid 14vs2. With that, more horde will queue bg

**Comment by Shatterer** [comment]
They must balance players in bgs, ally is already swarming and over geared so it is nice plan to make max 1 player difference in teams. You can turn off bonus honor stuff to ally already.

**Comment by geraldoghc** [comment]
> @DiaWreckingball i agree with you... You can't bring poeple who are full geared with honor / rep faster than horde... Need to fix "why horde don't queue anymore"
> Because they are easy farmed. On Netherwing, if 1 horde enter in a bg then 1 Ally Can enter too. So if there is 6 horde, 6 allies Can enter, to avoid 14vs2. With that, more horde will queue bg

The thing is in Netherwing BG sucks, and without the Classic the server was already dying. They did nothing meaningful to address the faction imbalance and ally got stomped every bg. Much like classic is right now. 

Add cross faction BG and perks for choosing Hord as well faction transfer, until it reach a balance, than you see what you can remove. If thing got desperate, you can add faction queue, as a final solution.

The time for action is NOW.

**Comment by Macumbafeh** [comment]
"Now" it's the word !
