### ISSUE TITLE
Shutting Down Manaforge B'naar

### ISSUE THREAD

**Issue by Stillspike** [SunstriderEmu/BugTracker#2332]
Got the access key to shut down B'naar but it is not letting me shut it down. I am horde but I have seen 5 different alliance groups complete this quest today. But every horde player I have talked to doing the quest cannot complete it.

https://www.wowhead.com/quest=10329/shutting-down-manaforge-bnaar

The console should let us shut down, but we get the gear shape for it but nothing pops up for us to shut down the console.

**Comment by michaelkittrell** [comment]
i completed it as both aldor and scryer around 48 hours ago with no problem.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.
