### ISSUE TITLE
Missing pattern.

### ISSUE THREAD

**Issue by AWIDIUS** [SunstriderEmu/BugTracker#2334]
https://tbcdb.com/?item=33205 Shadowprowler's Chestguard missing at its respective vendor. It's 2.2.0 patch, but this patch was more likely nothing but voice communication and few patterns, Ragesteel shoulders include, which are currently obtainable ingame.

**Comment by AWIDIUS** [comment]
![image](https://user-images.githubusercontent.com/45521546/76699690-48cea180-66b0-11ea-9553-910b2309f543.png)

**Comment by AWIDIUS** [comment]
Many of these recipes listed above are already obtainable ingame.

**Comment by blblblaz** [comment]
will be added with next server restart, thanks for the report!
