### ISSUE TITLE
[Warlock] Seed of corruption explosion reflectable

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#2336]
**Describe the bug**
When target already has seed of corruption debuff and uses spell reflect before the explosion, the explosion gets reflected on warlock.

**To Reproduce**
1. Cast Seed of corruption on warrior
2. Wait till its about to explode and use spell reflect
3. Explosion occured on warlock

**Expected behavior**
You should be only able to reflect initial seed of corruption cast to avoid the debuff. You should not be able to reflect the explosion

**Additional context**
Tested on mobs in botanica

**Comment by blblblaz** [comment]
thanks for the report, https://streamable.com/h3s5i

**Comment by beraus** [comment]
Prob related to https://github.com/SunstriderEmu/BugTracker/issues/1557

**Comment by kelno** [comment]
Fixed with next update
