### ISSUE TITLE
Chest at the end of Ramparts is Invalid Target

### ISSUE THREAD

**Issue by britonknowles** [SunstriderEmu/BugTracker#2337]
**Describe the bug**
The chest spawn at the end of hellfire ramparts that holds the end bosses loot occasionally will say invalid target. 

**To Reproduce**

https://www.wowhead.com/object=185168

**Expected behavior**
Open and pop windows for loot rolling.

**Screenshots/videos**

**Additional context**
Ticket Number #8319

**Comment by michaelkittrell** [comment]
ran ramparts 2x in a row on 3/28/2020.  not a single person in my group could loot the chest either time.

other guildies report same problem.  some report that they can never open chest with any group but others can in the same group / kill

**Comment by michaelkittrell** [comment]
did it a 3rd time this time killed the rider and the dragon pretty much on top of the chest.  still no one could activate and open the chest.

**Comment by Sheikthecatman** [comment]
This seems to be a client-side related issue. Try clearing your cache, if that does not solve the issue then try another client.
