### ISSUE TITLE
Formula: Runed Arcanite Rod respawn/restock timer

### ISSUE THREAD

**Issue by septembr** [SunstriderEmu/BugTracker#2338]
**Describe the bug**
The respawn/restock timer of the Formula: Runed Arcanite Rod seems to be off. Me and several other people have waited for more than 30 minutes, while sources on wowhead claim that it's supposed to be 15-20 minutes. 

**To Reproduce**
1. Go to Lorelae Wintersong in Moonglade.
2. Check the respawn timer of the item Formula: Runed Arcanite Rod.

Item: https://classic.wowhead.com/item=16243/formula-runed-arcanite-rod#comments
NPC: https://classic.wowhead.com/npc=12022/lorelae-wintersong

**Expected behavior**
The item in question is supposed to respawn in 15-20 minutes.

**Comment by blblblaz** [comment]
hey, it was indeed a ridiculously long respawn timer. it's been changed to a more reasonable time now, thanks for the report. the restock timer change will be live within the next few server restarts

**Comment by Godmatik** [comment]
@blblblaz I think most patterns have very long restock timers on this server, 20+ hours? 

Hoping you can check others as well. They get refreshed when the server crashes so someone sits on the NPC with a low level, and waits for server crash, then buys the pattern up instantly and sells on AH for absurd prices (Like Primal Might recipe)
