### ISSUE TITLE
Paladin skills buged Sancity Aura, Sor,Sob,Soc

### ISSUE THREAD

**Issue by meiji22** [SunstriderEmu/BugTracker#2339]
**Describe the bug**

Sancity aura not boosting holy damage.
Improved SoC not applying crit chance.
SoB not stacking with SoC at all.
SoC begind bugged or either SoR, SoR doing way more damage than SoC even with decent gear which shouldnt be the case, because SoC should be way stronger.

**Comment by Godmatik** [comment]
I can confirm Sanctity Aura currently doesn't do a single thing at all.
