### ISSUE TITLE
[NPC] [Reputation] Shattered Hand Assassin does not yield reputation

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#2342]
**Describe the bug**

Normal mode shattered halls this mob gives 0 rep on kill
https://db.endless.gg/?npc=17695

**Comment by InhumanGM** [comment]
Upon attempting to reproduce the issue, I was not able to find any issues. I received 17 reputation with Honor Hold per kill. Could you provide more information that could be used to try to reproduce the issue again?
