### ISSUE TITLE
Mend Pet doesn't generate threat.

### ISSUE THREAD

**Issue by PekelZoda** [SunstriderEmu/BugTracker#2343]
**Describe the bug**
Using Mend Pet rank 8 while droves of mobs in BRD and ZF does not cause mobs attacking my pet to turn and attack me.

**To Reproduce**
1. Send your hunter pet into a gang of mobs. Tell it to hit only 1 of them.
2. Let it take some damage as the mobs hit it.
3. Cast Mend Pet rank 8 on your pet. 
4. Note how you don't seem to get healing threat as your pet gets healed. All mobs keep striking your pet. 

Creature: https://tbc-twinhead.twinstar.cz/?npc=8912 (and more)
Spell: https://tbc-twinhead.twinstar.cz/?spell=27046

**Expected behavior**
As you heal any player or pet, you should gain threat from the mobs you're engaging. 
The untouched, but aggroed, mobs should leave your pet and aggro you, the hunter, instead after the first tick of Mend Pet.

**Comment by blblblaz** [comment]
yeah, you're correct, Mend Pet doesn't give any threat to the hunter when it heals the pet, thanks for the report!

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed after next server update.
