### ISSUE TITLE
Master loot and quest item in raid(karazhan)

### ISSUE THREAD

**Issue by ageerik** [SunstriderEmu/BugTracker#2345]
While having master loot on, the master looter can't loot items for the karazhan quest. This is easy to handle when for example looting books, just swap to group loot. But when I had master looter on and killed Shade or aran I couldn't loot him and changing to rgroup loot didn't help.

**Comment by Bzmode** [comment]
yea everyone else is getting the quest items except for the master looter.

**Comment by Godmatik** [comment]
confirmed, happened to us too

**Comment by Tomas-Lala** [comment]
Same for me with Nightbane(Blazing Signet).

**Comment by blblblaz** [comment]
fixed in 6ae90fc570b22eda870b5ba9f260034e2886791b (core)
