### ISSUE TITLE
AUTHENTICATING LOGGIN BUG

### ISSUE THREAD

**Issue by Xeede** [SunstriderEmu/BugTracker#2346]
Even when server is online, i cant log into the game, always stuck in "AUTHENTICATING" i already delete Cache folder, left the logging for 1 hour and still doesnt work, others servers working, what should i do ? :) 

https://imgur.com/a/5qrUe3Y

**Comment by popla22** [comment]
I have the same problem, give a solution

**Comment by Gax20** [comment]
I have the same problem for a the last hour now when I loggin  I see "connecting" then unable to connect anyone got a solution?

**Comment by Shamanlaman** [comment]
Same here, I think the servers are down right now. :/

**Comment by Gax20** [comment]
sadstory

**Comment by Wandkeeper** [comment]
servers are definitly down, i dont think we are the only unlucky people on the server

**Comment by Gax20** [comment]
does it still off?

**Comment by Jerrythemagicdog** [comment]
Issues should be resolved now.
