### ISSUE TITLE
AUTHENTICATING LOGGIN BUG

### ISSUE THREAD

**Issue by oldtotem** [SunstriderEmu/BugTracker#2347]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by oldtotem** [comment]
i can't log in fix it fast plz

**Comment by oldtotem** [comment]
ca't log in fix it fast

**Comment by Wandkeeper** [comment]
thats an order? dude... nice attitude

**Comment by Jerrythemagicdog** [comment]
Fixed now.
