### ISSUE TITLE
warlock soulwell not visible in karazhan

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#2348]
If you summon a soulwell on the ramp leading up to aran (like right before his room) it completes, but is invisible 2/2 times I've done it (last tuesday and today sunday).   You can click it for healthstones, but its just not visible for some reason.  the summon target (thing people clicks to channel the spell) appears to the left of me, pretty much off the ramp, instead of infront of on the ramp.  i assume its related.

**Comment by beraus** [comment]
Can't reproduce the issue.
