### ISSUE TITLE
[Spell] Searing Totem will break CC targets

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#2349]
**Describe the bug**

A searing totem will target and cast attacks at targets in range, even prioritizing targets affected by incapacitate effects such as Sap or Gouge; and Polymorph.

**To Reproduce**

1. Cast Sap on a NPC in shattered halls entrance
2. Cast Polymorph on a NPC in shattered halls entrance
3. Cast Searing Totem and watch in glory as the totem will magically choose the sapped and polymorph targets. Its not 100% of the time but its annoying af.

https://db.endless.gg/?spell=2070
https://db.endless.gg/?spell=12825
https://db.endless.gg/?spell=25533

**Expected behavior**

Searing Totem should not break CC targets, especially if there are other targets within range of the totem or its master.

**Screenshots/videos**

**Additional context**

Prioritization of searing totem targets within range is not happening at all?

**Comment by blblblaz** [comment]
currently the way it works is - it just locks on to the closest target at the time of casting Searing Totem, if that target dies or runs out of range it moves on to the next closest.

"When dropped, the totem randomly selects an enemy within range and continuously attacks until A.) the totem expires, B.) the target leaves range or C.) the target dies. If B or C occur, the totem randomly chooses another target in range and begins attacking it. If there are no targets within range, it does nothing until an enemy comes in range. Also note that the totem only engages hostile targets on its own; it ignores neutral targets, unless you engage them first."

thats from https://wowwiki.fandom.com/wiki/Searing_Totem, doesn't mean its 100% correct, but would need a source that it shouldn't break CC

**Comment by z5n** [comment]
stale
