### ISSUE TITLE
[Spell] Earthbind totem will cause aggro when debuff is applied to 0 threat table targets

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#2350]
**Describe the bug**

Running through forest. Aggro boar. Cast Earthbind Totem. Slowing debuff pulse is applied to boar. Boar decides to attack Earthbind Totem now as it has top threat.

https://db.endless.gg/?spell=2484

**Expected behavior**

Earthbind totem should not cause any threat whatsoever.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
