### ISSUE TITLE
(Warrior) SPELL REFLECTION

### ISSUE THREAD

**Issue by Wandkeeper** [SunstriderEmu/BugTracker#2351]
**Describe the bug**

warriors spell reflection doesnt show any information about how much DMG it reflects back on the target

**Expected behavior**

DMG's Should be visible for all warriors since spell reflection is huge spell in PvP ...  and im pretty sure many warriors would love this being visible to them when crits happen on that Chain Lighting reflected back at them .... 

pls fix this if you can.  i dont see any other problems in warrior class just this thing missin to be perfect... thanks for ur work tho

**Comment by blblblaz** [comment]
confirmed, there is no combat log message of damage done when spell gets reflected. it's just visual, the reflected spell does damage to the target.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1557
