### ISSUE TITLE
Hunter's Pet Bugged DMG and Resistance after Ressurection

### ISSUE THREAD

**Issue by mayday2013** [SunstriderEmu/BugTracker#2352]
**Describe the bug**
When your pet dies and you ressurect it, sometimes it's damage is lowered until you dismiss and call it back. Also, resistance you have as it's talents is gone untill dismiss. Sometimes a pet bar disappears so you can not properly control your pet until it is dismissed.

**To Reproduce**
1 Teach your pet some resistance perks. 
2 Kill the pet. 
3 Ressurect it and see if all the stats are normal.
4 Check if you have a pet bar after ressurection

**Expected behavior**
Pet should have 100% of it's usual resistance and damage and be fully controlable.
**Screenshots/videos**
https://www.youtube.com/watch?v=YRWnib_aGvE

**Additional context**

**Comment by Ironjudgment** [comment]
Can confirm

**Comment by reinart1** [comment]
can confirm also, only restart works

**Comment by artieau** [comment]
Confirmed this issue persists,  it is re-producible more often than not.
 - Pet dies
 - res pet
 - pet res without the spells/ranks taught via Beast Training points
 - dismiss pet
 - summon pet back, it has all the expected spells/ranks trained again properly.

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago, thanks for the issue.
