### ISSUE TITLE
Outland portal not working.

### ISSUE THREAD

**Issue by Endlesshunter** [SunstriderEmu/BugTracker#2354]
**Describe the bug**
Nothing happens when I enter the portal. It's not working, so it's not possible to get to Outland unless you have a your hearth set there and ready ,or by mage. Also, ALL the npc in blasted lands are gone near the portal. Don't know if that has something to do with it.

**To Reproduce**
Go into the portal on blasted lands side.

**Expected behavior**
I expect to get to hellfire peninsula

**Screenshots/videos**

![image](https://user-images.githubusercontent.com/61934274/76751048-599a1880-677f-11ea-9276-0222ac630b36.png)

**Comment by Endlesshunter** [comment]
No npcs:

**Comment by Endlesshunter** [comment]
Reloggin fixed it..Still a weird bug :S

**Comment by Sheikthecatman** [comment]
Client-side issue.
