### ISSUE TITLE
No arena points after playing 10 games

### ISSUE THREAD

**Issue by Kronus271** [SunstriderEmu/BugTracker#2356]
Before the reset on saturday i played 10 arena games(2vs2) but did not get any points

**Comment by mayday2013** [comment]
You'd better provide some screenshots of your weekly/season statisctics in 2v2. And your ingame name.

**Comment by Kronus271** [comment]
Sorry didnt see your answer. Here are the screenshots.
![WoWScrnShot_032220_163253](https://user-images.githubusercontent.com/61857261/77253525-2d890680-6c5b-11ea-9888-125dadff9a8c.jpg)
![WoWScrnShot_032220_163442](https://user-images.githubusercontent.com/61857261/77253528-2f52ca00-6c5b-11ea-8e29-4875ac5f2c1a.jpg)

**Comment by mayday2013** [comment]
Sorry for delay, here is the answer:

You get arena points if 30% of total weekly games are played the player.
You have 39 games in total during the week, that means you had to play at least 13 games out of 39 to get points.

Minimum required: 10 games a week and 3 out of 10 to get points.

You would have played 5 more games to reach 45 weekly /15 personal ratio (30%)

**Comment by Kronus271** [comment]
Ah okay thank u very much, i didnt know that
