### ISSUE TITLE
Shutting down manaforge duro

### ISSUE THREAD

**Issue by Kohjavel** [SunstriderEmu/BugTracker#2358]
**Describe the bug**

Have taken quest item(Duro Access Crystal) from overseer Athanel. When clicking on Duro Console, nothing happens.
There is no one else who have started the event, the Console have a bronze gear so it is clickable(like the first two quests) but nothig happens, dont get the dialoge to start the shutdown

Have abandoned, logged out, tryed to be in group, solo etc nothing works
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Sheikthecatman** [comment]
Thanks!
Fixed in next restart.

**Comment by Sheikthecatman** [comment]
Thanks!
Fixed in next restart.
