### ISSUE TITLE
[Hunter] - Talent Not working Correctly  [Ferocious Inspiration]

### ISSUE THREAD

**Issue by Espranty** [SunstriderEmu/BugTracker#2360]
**Describe the bug**
In beast mastery talent tree ,there's a Talent called  [Ferocious Inspiration] .. its in the bottom left of the talent tree , the issue is --> it should stack the more hunters you have in one group , but its bugged and it doesnt stack here , it only refreshes the buff here which isnt right  .

This is Major As Beast Mastery is the Main specc in TBC

**To Reproduce**

Get Multiple Beast mastery Hunters in one group .. Let them attack a target and When their pets Crit you will notce that you only get x1  [Ferocious Inspiration] and it refreshes ... it should be one buff per pet's Crit ,
 Meaning x3Hunters = x3 Buffs when pets do crit . 

Spell: https://wowwiki.fandom.com/wiki/Ferocious_Inspiration

**Expected behavior**
It should stack .

**Screenshots/videos**

Proof from SK-Gaming back on TBC Retail :
https://www.youtube.com/watch?v=_gAQjX1oK6E

@ (1:40 to 1:44) You will see it x2 on him  

**Additional context**
This is a Major major issue and i kindly Urge you to Top prio this .

Thank you in advance

**Comment by Ironjudgment** [comment]
I did Karazhan yesterday with two hunters present in the same group and it seems that the buff was working correctly, at least it was displaying two Ferocious Inspirations.

https://youtu.be/nvWgg_5k4g0?t=12494 -> You can see two Ferocious Inspirations on my pov (sorry the capture was a little off :/ )

**Comment by Highdps** [comment]
Atm it working correctly

**Comment by blblblaz** [comment]
this issue was fixed a few days ago, and in my test just now Ferocious Inspiration stacks correctly, closing the issue for now
