### ISSUE TITLE
Aldor Rise Specialty Ammunition Vendor Missing

### ISSUE THREAD

**Issue by Skuzzlez** [SunstriderEmu/BugTracker#2361]
**Describe the bug**
Scryer's Rise currently has their Specialty Ammunition Vendor implemented (Archer Delvinar), however Aldor Rise has no such NPC. There 'should' be an NPC called "Marksman Bova" in the game who does the exact same thing for Aldor, however he does not currently exist.

**To Reproduce**
N/A

https://www.wowhead.com/npc=25196/archer-delvinar
https://www.wowhead.com/npc=25195/marksman-bova

**Expected behavior**
Both NPCs should be in the game, however only Archer Delvinar is.

**Comment by blblblaz** [comment]
thanks for the report, should be fixed with next server restart
