### ISSUE TITLE
Torch of Retribution attack speed

### ISSUE THREAD

**Issue by analshadow** [SunstriderEmu/BugTracker#2362]
Describe the bug
The Torch of Retribution from the quest in Searing Gorge is suppose to have a VERY fast attack speed and low damage, but it instead has a higher damage and Extremely slow attack speed. This was typically used to level unarmed skill quickly, or for paladin shanigans.

To Reproduce
equip Torch of Retribution and look at attack speed compared to any other weapon or unarmed speed.

https://ptr.wowhead.com/quest=3454/the-torch-of-retribution

Expected behavior
equipping the torch should give a VERY low attack damage and VERY fast attack speed.

**Comment by Jerrythemagicdog** [comment]
Set to high attack speed on purpose.
