### ISSUE TITLE
[BUG] Mana Thistle

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2364]
You can currently loot 3 mana thistle from one node. Should yield a maximum of two.

https://wowwiki.fandom.com/wiki/Mana_Thistle

"Unlike normal herb nodes, you will only obtain one or two Mana Thistle per each node picked."

**Comment by blblblaz** [comment]
thanks for the report

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
