### ISSUE TITLE
Bug allowing players to fly

### ISSUE THREAD

**Issue by PilotXT** [SunstriderEmu/BugTracker#2365]
**Describe the bug**
While flying through the air on a flying mount, if the spell Entangling Roots (ID: 27010) and Cyclone (ID: 33786) is cast on you repetitively and you die, when you release spirit, you are able to fly. When you resurrect, you will still be able to fly.

**To Reproduce**
1. Cast Entangling Roots (ID: 27010) on target
2. Cast Cyclone (ID: 33786) on target
3. Kill target
Target will then be able to fly upon releasing spirit and resurrection.

Spell: https://tbc-twinhead.twinstar.cz/?spell=27010
Spell: https://tbc-twinhead.twinstar.cz/?spell=33786

**Expected behavior**
After releasing spirit, player should **not** be able to fly. After resurrection, player should **not** be able to fly.

**Screenshots/videos**
N/A

**Additional context**
N/A

**Comment by blblblaz** [comment]
I couldn't manage to reproduce the issue, but flying players should be immune to Entangling Roots in the first place (if player is on the ground but on a flying mount he should still be rootable), thanks for the report

**Comment by kelno** [comment]
Adding "question" as more specific reproduce steps are still very welcome
