### ISSUE TITLE
Trinket interaction

### ISSUE THREAD

**Issue by Moiree** [SunstriderEmu/BugTracker#2369]
Scryer's Bloodgem and Xi'ri's Gift share the full 1.5 min cooldown, probably due to the same exact on use effect.

**Comment by Woran123** [comment]
I am having the exact same problem with these 2 trinkets.

**Comment by knoxz** [comment]
you also get a super annoying animation bug and a constant humming effect after using the 2nd after the first one.
As the client thinks you should be able to use it after the first one expires.

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2087
