### ISSUE TITLE
Netherspite Red Beam agro

### ISSUE THREAD

**Issue by jamesdes18** [SunstriderEmu/BugTracker#2372]
**Describe the bug**
The Tank whose gets the active red beam generate unbreakable taunt.

**To Reproduce**
If the tank goes in and out of the beam he loses threat or can be out threated with the debuff still active

**Expected behavior**
Netherspite attacks the red beam user

**Screenshots/videos**
https://www.youtube.com/watch?v=JJID7e3FzMI

**Additional context**
The video from 2:12 and on shows the prot pally tank does nothing but auto attack the boss and resumes full threat table on the boss. Threat abilities are not required to maintain threat even without being in the red beam.

**Comment by Jerrythemagicdog** [comment]
Netherspite does attack the target who currently has the red beam active by fixating on that target, it does not add threat to the target.

**Comment by jamesdes18** [comment]
Okay so if your watching the video that I linked, 3 mins in the pally tank
is auto swinging and moving in and out of the beam having no threat issues.
Here on sunstrider being out of the beam means netherspite will attack
anyone highest on threat which is incorrect

**Comment by Ironjudgment** [comment]
Can confirm, currently normal aggro table still applies when tank is not directly standing in the beam. The beam debuff which lasts 20 secs should still hold tanks aggro. 

In my guild we still have to follow aggro table on DTM during the whole fight in fear of second highest threat holder dying when tank is not in beam.

Additionally, Netherspite does not face the targeted player when he is casting Netherbreath. Boss just stands still and the cone goes in a players direction, sometimes without even targeting the said player. Furthermore, standing in the green beam does not replenish mana, only reduces the total :/

**Comment by Morskitar** [comment]
_"Here on sunstrider being out of the beam means netherspite will attack
anyone highest on threat which is incorrect"_
That is exactly how it should work ! The player in red beam should keep the aggro even when he goes out until he lose the debuff.
Please fix this, this boss is so random to do with this bug.

**Comment by BasedForfrost** [comment]
Netherspite's tank aggro should be on whomever is presently standing in the beam. It is separate from the debuff the red beam applies. That said, unless Threat Meters are buggy with Netherspite, it appears as if aggro is not correctly resetting after a banish phase. We only did a few attempts today, but the first phase went off without a hitch with our druid tank dancing in and out of the beam so as not to stack too fast, but after banish phase, the paladin tank could only hold aggro while standing in the red beam. Any time he danced out, the DPS who were taking the blue beam from the previous phase had highest threat and pulling aggro immediately.

**Comment by Morskitar** [comment]
_"Any_ time he danced out, the DPS who were taking the blue beam from the previous phase had highest threat and pulling aggro immediately._" 
That's the problem. No one should take damage when tank are swaping in red beam. He should keep it until the end of the portal phase (unless he dies...)
