### ISSUE TITLE
Retune Escape From Firewing Point! Quest

### ISSUE THREAD

**Issue by Majst** [SunstriderEmu/BugTracker#2373]
**Describe the bug**
Quest is literally impossible to complete since the escort mob runs after anything aggro'd a million miles away, is such a low level that everything nearby aggros, the mobs have a 25 second respawn time, and the escort mob is unhealable. Literally the only escort I have been unable to do as a geared 70.

**Comment by Jerrythemagicdog** [comment]
Thanks, changes live after next restart!
