### ISSUE TITLE
Mana Thistle Respwan

### ISSUE THREAD

**Issue by Phoelol** [SunstriderEmu/BugTracker#2374]
I assume that the mana thistle respwan got broken like 2 days ago. 

Pls check this. The price development is really strange, as well as myself as a herb guy find a lot less spwans, even with epic fly.

I have no other evidence though.

**Comment by Jerrythemagicdog** [comment]
Nothing has changed in regards to herbs position or respawn rates.

**Comment by Phoelol** [comment]
I monitored the mana thistle spawn and auction house pricing during the last two weeks.

The amount of available mana thistles is below acceptable levels. I assume that the respawn is not dynamic. Please consider having a look at this. Every other herb even fel lotus is more accessible than mana thistles. The actual rate is not suited for such a big player base.

**Comment by tyshies** [comment]
Bumped for great justice.  Observed Skettis for a few hours, and I only saw 1 Mana Thistle node respawn a few times,  Sat next to location of another one for about an hour and a half and never saw the Herb node respawn.  

Considering that most people need these herbs for their flasks, the fact that there is no real way to farm the herbs in the current state is leading to outlandish prices for the herbs and flasks.
