### ISSUE TITLE
Spirit Bond generating threat for the hunter.

### ISSUE THREAD

**Issue by Skuzzlez** [SunstriderEmu/BugTracker#2375]
**Describe the bug**
Spirit Bond, a BM hunter talent which periodically heals the hunter and his pet - should not generate threat for the hunter if he/she is at full HP. It currently does, in seemingly all circumstances.

**To Reproduce**
Aggro multiple targets with a hunter pet. Those that the pet initially aggroes, but does not directly attack / generate more threat towards, will then switch to attack the hunter due to Spirit Bond healing threat.

**Expected behavior**
Spirit Bond should not generate threat for the hunter if he/she is at full HP (as it is technically doing no healing). I'm not sure it should generate threat even if it heals the hunter - it doesn't on classic or other TBC servers, as far as I recall.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
