### ISSUE TITLE
[Autoattack] melee autoattack BREAKING and sinister strike evade

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#2378]
**Describe the bug**

Noticing that if I am in stealth, and open with Sinister Strike, that my autoattack will be stuck "on" and I am searching for a target and even unsheathed and looking to attack, but do not attack anything. Using abilities work, but melee attacks are breaking.
I also saw the Sinister Strike openers produce a mob 'evade' bug. I tested vanishing on the same mobs as the cooldown allows and it seems very finicky.

**Comment by kmayberry91** [comment]
to clarify there is no white damage happening when this occurs and I am stuck bugged like this, even while eating. notice how it states I am too far away to attack and have no target selected.
![image](https://user-images.githubusercontent.com/45275285/76885717-494c7100-6845-11ea-80ca-efdcb2f086a6.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, there is a fix for this live right now, please tell us if the issue still occurs.
