### ISSUE TITLE
I cannot take the shaman quests, they dont exists for me.

### ISSUE THREAD

**Issue by Souty1997** [SunstriderEmu/BugTracker#2379]
**Describe the bug**
Hello, my trainers cant give me fire totem quest as a shaman. I did just deleted from quest log "Call of a Fire" then I couldn't pick it again.

**To Reproduce**
1. I took the quest
2. Then deleted it after some time from quest log

Item: https://classic.wowhead.com/item=5176/fire-totem
Quest: https://classic.wowhead.com/quest=1527/call-of-fire

**Expected behavior**
Be able to take the quest and complete it

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment]
Contact support in game.
