### ISSUE TITLE
Seal of Ascension

### ISSUE THREAD

**Issue by KrycuX** [SunstriderEmu/BugTracker#2382]
**Describe the bug**
I cant forging seal. Dragon havent 1 skill.

quest:
https://classic.wowhead.com/quest=4743/seal-of-ascension

screen
http://prntscr.com/rhznvd

**Comment by Thiazole** [comment]
Is there anyway we can obtain the Seal of Ascension? Maybe from GM if we managed to do all the prequests necessary?

**Comment by EL100** [comment]
Wish I had checked this before attempting the forge the seal. Confirmed. First attack on the pet bar was attack and second was flame. Attempted to forge with flame and of course didn't work.

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in [fae8fcea3bf1e1ffdd7e926a9577f6eb74406761](https://github.com/kelno/sunstrider-scripts/commit/fae8fcea3bf1e1ffdd7e926a9577f6eb74406761). It will be applied next server restart.
