### ISSUE TITLE
Magtheridon's Lair Cubs not fucking work

### ISSUE THREAD

**Issue by Hustler495** [SunstriderEmu/BugTracker#2383]
Hello! I am sorry - but WTF
cubs not working correctly. Its lottery. We wiped 4 hours because of this shit
Person who clicking it see that he click but it don't working, doing anything at all
Other person in raid didn't see the things from cub .
How to reproduce
Go second phase and click cubs from entrance .

It's not one situation we got this 4 times in a row with different persons clicking it ,

**Comment by Jerrythemagicdog** [comment]
When did it happen? There was a fix applied earlier today, if there are still issues then we'd need more details.

**Comment by Highdps** [comment]
Today, after fixes
One try was good with 3 times working cubs, then we got bugging cubs again and again

**Comment by Godmatik** [comment]
Did Mag yesterday, no issues with cubes, perhaps fixed now?
