### ISSUE TITLE
Guards at Cenarion Refuge in Zangarmarsh do not correctly protect players in the camp

### ISSUE THREAD

**Issue by Tritonis** [SunstriderEmu/BugTracker#2384]
**Describe the bug**
In Cenarion Refuge, there are multiple places where enemy players can stand(close by) where they can easily attack at range and kill people in Cenarion Refuge. The camp guards should respond to the attacks. 

**To Reproduce**

1. Stand behind rep vendor at Cenarion Refuge
2. Attack enemy players in the camp
3. Guards do nothing. 

NPC that is bugged: 
https://www.wowhead.com/npc=17855/expedition-warden

**Expected behavior**
Guards should react to players being attacked in the camp. The attackers are <10 yards from guards sometimes, but unless they cross some invisible line to get into the camp, the guards do nothing. 
**Screenshots/videos**
https://imgur.com/a/OshLiED

**Additional context**
Multiple players have been abusing this bug to attack people in the camp.

**Comment by wiglefish** [comment]
That was a problem on retail too. However, the storm crows which were added are doing nothing at all. They full on ignore people. See screenshot attached of warlock seconds after putting corruption on me.
![Useless defenders](https://user-images.githubusercontent.com/61839708/77116330-eebf3a80-6a27-11ea-90ee-b7a9faa7fc9b.png)

**Comment by beraus** [comment]
Should be fixed while ago, reopen the issue if you notice more cases like this one.
