### ISSUE TITLE
Dire Maul North Door not Interactable

### ISSUE THREAD

**Issue by britonknowles** [SunstriderEmu/BugTracker#2386]
**Describe the bug**
The door in DM:N in the Courtyard (GUID 29750 Gordok Courtyard Door) doesn't open up for players. They state that cogwheel doesn't display for them.

**To Reproduce**
1. Loot Key from Chest in Courtyard.
2. Stare at door and not be able to interact.

**Expected behavior**
Right Click or Interact to open door once key has been obtained.

**Comment by frastsytt** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1834
already reported :v)
