### ISSUE TITLE
Stuck on "Connected"

### ISSUE THREAD

**Issue by nhthor** [SunstriderEmu/BugTracker#2388]
**Describe the bug**

when i click on my application it pulls up, when i type in my username and password - goes all the way through and gets stuck on "connected". Was working fine up until 9:30 CST 3/17/2020.

**To Reproduce**

1. click on wow-tbc application
2. sign in
3. comes up with "connected"
4. tried on my second account - same issue
5. tried on another computer with the application - same issue
6. My internet works, restarted computers - same issue

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by kelno** [comment]
Thanks for reporting! 
There was an issue this night and many (or all) people couldn't connect. The issue has been resolved since.
