### ISSUE TITLE
Lost cooking recipe

### ISSUE THREAD

**Issue by nhthor** [SunstriderEmu/BugTracker#2389]
**Describe the bug**

I used the cooking recipe "crunchy spider leg surprise", bought some crunchy spider legs to cook. Server crashed, the recipe is not in my bank, not in my cooking skill list. But all of the auction that I bought came through,

**To Reproduce**

Learnt a cooking recipe, server crashed, skill missing and recipe not there

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

I should either have my recipe or have the skill in my list of cooking skills.

**Screenshots/videos**

**Additional context**

**Comment by blblblaz** [comment]
hey, that's a general issue with disconnects, not specific to your cooking recipe, I suggest you make a ticket in game if you already haven't and your issue will be resolved
