### ISSUE TITLE
I can't download the client with the torrent link that is on the web page "endless.gg". WHen I click on the link, nothing happens. Also I tried to open it on a different window, but still nothing happened

### ISSUE THREAD

**Issue by manuelsilva24** [SunstriderEmu/BugTracker#2390]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Godmatik** [comment]
You need to have a torrent client installed, like uTorrent
