### ISSUE TITLE
Lost chapter for team arena

### ISSUE THREAD

**Issue by Kiridmg** [SunstriderEmu/BugTracker#2391]
Hi!! After the reboot of server to maintance (about 8 oklock 18.03.2020) i lost arena team charter 2vs2, that is 80g. Team was named shattered hand. Please, return it gold to me
Thanks
Item: https://www.wowhead.com/item=23560/arena-team-charter-2v2

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by blblblaz** [comment]
we are aware of the issue and are working to solve it. for now just make a ticket in-game if you already haven't and it will get resolved

**Comment by Sheikthecatman** [comment]
Closing as it has been fixed.
