### ISSUE TITLE
Seal of Blood does not scale with Seal of the Crusader

### ISSUE THREAD

**Issue by DerMyn** [SunstriderEmu/BugTracker#2393]
Hey i am 99% thats a bug :) maybe it actually how it was back in the days but here is a small video where i showcase the problem 👍 : 
https://www.youtube.com/watch?v=e3upyV1bljA&feature=youtu.be

**Comment by blblblaz** [comment]
The seal only scales with weapon damage, not spell damage. It therefore heavily favors melee-geared Paladins (mostly Retribution Paladins), rather than spelldamage-geared Paladins. Note that the Judgement does scale with spell damage.

from https://wowwiki.fandom.com/wiki/Seal_of_Blood

**Comment by B0nisek** [comment]
yeah it should not scale with crusader

**Comment by DerMyn** [comment]
k ty :)

**Comment by Ibuprofeno** [comment]
Adding a source.
https://www.wowhead.com/forums&topic=35733#p327974
"The Jotc tooltip is a little off, it says dmg taken by but really only increases your spellpower against the target so abilities without any or a low coefficient receive very little to no benefit."
