### ISSUE TITLE
Guild gold sellers 

### ISSUE THREAD

**Issue by shrift1** [SunstriderEmu/BugTracker#2394]
Guild: Forhord spamming invites 
![WoWScrnShot_031820_144439](https://user-images.githubusercontent.com/31934397/76968490-4c209200-6929-11ea-929a-37ecb13a2ffb.jpg)
![WoWScrnShot_031820_144457](https://user-images.githubusercontent.com/31934397/76968495-4e82ec00-6929-11ea-9cd3-b962c6fb8d88.jpg)
![WoWScrnShot_031820_143121](https://user-images.githubusercontent.com/31934397/76968500-4fb41900-6929-11ea-8e04-a920db64add7.jpg)
![WoWScrnShot_031820_144509](https://user-images.githubusercontent.com/31934397/76968504-50e54600-6929-11ea-8613-a17e9d0b10fd.jpg)

**Comment by blblblaz** [comment]
thanks for letting us know, will take action!

**Comment by wiglefish** [comment]
Lol "will take action" 3 days later, my banker still receives invites from them every hour.

**Comment by shrift1** [comment]
Always, soon more to come :)
