### ISSUE TITLE
Stealth isn't strong enough.

### ISSUE THREAD

**Issue by Dringer113** [SunstriderEmu/BugTracker#2397]
I have Master of Deception at 5/5 and mobs my level or even green aggro me like I'm not even stealthed.

**Comment by Frixus** [comment]
This is still an issue as of 4/05/2020.  I have used MOD ranks 1-5 to test.  Each rank does not seem to make a difference.  Now I have noticed a slight difference with no MOD to having any rank of MOD.

Stealth in general is just too easily broken with line of sight.  I have mobs spotting me that are gray, or even green from yards away breaking me out of stealth.

**Comment by Dringer113** [comment]
Yup, had a warlock in AB see me at about 15 yards away. still have MOD at 5 ranks. Guess it's not important for them to fix it though.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3418
