### ISSUE TITLE
Draenei Shaman --> Call Of water quest

### ISSUE THREAD

**Issue by Cptzura** [SunstriderEmu/BugTracker#2399]
Call Of Water Quest Chain
**3th or 4th Quest to slain tel'athin**
<when use Skin of Purest Water tel'athin will appear but after 3s he will disappear and also if u attack him he will spam arcane missile which cant interrupted by earth shock and he one shoted me many times i asked a lvl70 to help me to kill if i just could interrupt it i could solo it without any problem plz fix it  >

Also quest removed from wowhead. so there is no link that i could share
thanks

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago, thanks.
