### ISSUE TITLE
Sancity Aura for Ret Palas not working

### ISSUE THREAD

**Issue by meiji22** [SunstriderEmu/BugTracker#2400]
**Describe the bug**

Sancity Aura from Ret Palas is not working. Infact doing absolutely nothing...
**To Reproduce**

Take Sancity Aura in Ret tree. Hit a dummy with Seal of Righteousness and watch the yellow damage number with and without Sancity Aura active.
1. Cast Sancity Aura
2. Cast Seal of Righteousness
3. attack dummy with auto hit and watch the yellow number ( SoR proc aka. holy damage)
4. Turn off sancity Aura and auto attack dummy again with SoR up, dmg is still same ( should be increased by 10%)

Spell: https://classic.wowhead.com/spell=20218/sanctity-aura

**Expected behavior**

Sancity Aura should increase all holy damage from all party members within range by 10%. for example if you SoR procs with 300 (yellow number) per hit, it should proc for 330 per hit with Sancity aura active.
**Screenshots/videos**

**Additional context**

SoR = Seal of Righteousness

**Comment by Godmatik** [comment]
Confirmed.

**Comment by Ctave6** [comment]
This is an existing issue with SoR, not Sanctity Aura, consider testing with another spell (such as SoV or SoC), take a look at issue 1644 for more information.

https://github.com/SunstriderEmu/BugTracker/issues/1644

**Comment by GigilPiq** [comment]
This is not 100% exact. The aura works, just not for SoR on hit damage. You shouldn't have stopped there and say the aura is bugged.
