### ISSUE TITLE
No way to learn Dark Iron smelting

### ISSUE THREAD

**Issue by unconsciousnesstime** [SunstriderEmu/BugTracker#2401]
**No way to learn Dark Iron smelting**
 When talking with Gloom'Rel, nothing happens, there is no further action - the appearance of the bowl necessary for the delivery of reagents and the further completion of the quest.

**To Reproduce**
Having come to the BRD, I found the necessary unit named Gloom'Rel, but talking with him does not start the necessary quest for training Dark Iron smelting.
1. Conversation with Gloom'Rel. After which a bowl appears.(This is not happening)
2. Put 2 Star Ruby, 10 Truesilver Bar, 20 Gold Bar in the bowl.(It should be like that. but due to a gap in the first paragraph - this is not possible)
3. Talk again with Gloom'Rel, who after this offering teaches us the smelting of Dark Iron.(It should be like that. but due to a gap in the first paragraph - this is not possible)

Item: https://classic.wowhead.com/item=11371/dark-iron-bar
Quest: https://classic.wowhead.com/quest=4083/the-spectral-chalice
Spell: https://classic.wowhead.com/spell=14891/smelt-dark-iron

**Expected behavior**
It should be like this - the penultimate boss in the BRD is an event in the tomb, where you can communicate with two spirits before the start of the battle, one starts the fight, and the second one by the name of Gloom'Rel teaches Dark Iron melting, after talking with him, a bowl should appear in which you need put 2 Star Ruby, 10 Truesilver Bar, 20 Gold Bar, then talk to him again and after this offering he teaches the 230+ miners his wisdom of casting Dark Iron, at least that’s how I did everything on about 5 servers, and on this server, after the conversation the bowl does not appear, the reagents have nowhere to hand over, and he doesn’t have anything IT.

**Screenshots/videos**
https://www.youtube.com/watch?v=WwxkP2pqRfA  

**Additional context**
I’m completely stuck with the quest for getting t0.5, because according to the quest https://classic.wowhead.com/quest=8947/anthions-strange-request, these ingots are needed, and it is impossible to get them on our server, because non-working object / quest, please fix this, and ideally check the operability of further quests along this chain, I would not want to stumble upon another insurmountable wall called "BUG" Investing a lot of time and gold in the quests, I would like to complete them, and not to tie in an endless series of tickets and reports in the game. which is already 15 years old, thanks in advance.

**Comment by Sheikthecatman** [comment]
Was fixed recently with the minor revamp of most BRD events.
