### ISSUE TITLE
Troll respawn time

### ISSUE THREAD

**Issue by elnium123** [SunstriderEmu/BugTracker#2402]
Hello, after the restart yesterday, the respawn of the troll(secret troll) mob are 5 mins now, but i check another farm spot and they not respawn like thats, nothing change, can you do something ?

**Comment by Sheikthecatman** [comment]
Which mob is it that is respawning faster?
Would be better for us to compare between them!

**Comment by elnium123** [comment]
All the mobs of all the map respawn faster than his trolls

**Comment by Jio5** [comment]
Hi, same issue, 5 minutes for the shatterspear trolls to respawn. A fix would be nice, since its a nice farming spot.

**Comment by elnium123** [comment]
Up pls
