### ISSUE TITLE
Advanced Target Dummy no loot

### ISSUE THREAD

**Issue by draexan** [SunstriderEmu/BugTracker#2403]
**Describe the bug**
Advanced Target Dummy's and probably even other Target Dummy's (not sure not tested) have way too much life compared to Blizzlike (around 8k with level being 74, with it being for Engineering Skill 185 they should have a level around 30+ and much less life), dont die after 15seconds like tooltip states and therefore not working as intended, and lastly they apparantly have no loot unlike official servers have (Should die with a loot and give back some engineering mats with a low chance of dropping Fused Wirings) therefore, with the Fused Wiring Recipe not added to the game, and the Ogri'la mobs not implemented yet there is no good way to obtain any Repair Bots as an engineer (maybe having luck on random recipe drop anywhere in the world for the tbc repair bots or running gnomeregan 24/7, but after 3 runs i had not a single Fused Wiring).

**To Reproduce**
1. Craft Advanced Target Dummy as an engineer
2. Place that Advanced Target Dummy
3. Realize its way too high level and doesnt die after 15 seconds
4. Place that Advanced Target Dummy near level 70 mobs
5. wait until it is killed and realize there is no loot

https://classic.wowhead.com/item=4392/advanced-target-dummy

**Expected behavior**
Advanced Target Dummy dies after 15 seconds, and you are able to loot it with a low chance of obtaining Fused Wirings

*maybe ive been just unlucky to get no loot out of 15 Target Dummy's Placed

Additional Information:
Patch 1.3.0 (patch date:2005-03-07): Fused Wiring will now drop more often from target dummies.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with the next update.
