### ISSUE TITLE
Mage Talent [Permafrost]

### ISSUE THREAD

**Issue by Saffuu** [SunstriderEmu/BugTracker#2404]
So the mage talent Permafrost when using 3 points into it, it increases chill effects by 3 sec and reduces slow by an additional 10%. The frostbolt tooltip and other frost spells show that the slow should be applied, but in reality only the increased 3 sec to chill effects is (i believe). The target (shown in the screenshots/ or any target not only this particular) receives a 40% slow instead of 50%. I dont know if its just a visual mistake or if its actually 40% instead of 50%.

To reproduce this you can cast a Frostbolt (any rank) on any target and its pretty easy to spot. You must have the [Permafrost] talent however if you want the tooltip of the spell to change.

Here are the screenshots:

![Bug1](https://user-images.githubusercontent.com/62372384/77040547-d1a35100-69c0-11ea-9a46-b6ab827d4de8.jpeg)

![bug2](https://user-images.githubusercontent.com/62372384/77040431-986ae100-69c0-11ea-96e8-039610472da3.jpeg)

![bug3](https://user-images.githubusercontent.com/62372384/77040436-9b65d180-69c0-11ea-810e-9b30bc981f77.jpeg)

**Comment by Saffuu** [comment]
*PLEASE DO REVISIT EVERY OTHER FROST SPELL LIKE CONE OF COLD ETC ITS THE SAME FOR THEM*

**Comment by Aeded** [comment]
tooltips of buffs and debuffs do not reflect talents, they never did. The slow is 50%, and the duration is 12s

**Comment by Godmatik** [comment]
It's a visual thing only that is a part of the vanilla and TBC client, improvements from talents don't show on the buffs/debuffs, but they are present.
