### ISSUE TITLE
Unable to take quests from Voren'thal the Seer Scryers

### ISSUE THREAD

**Issue by Sistabossenn** [SunstriderEmu/BugTracker#2407]
**Describe the bug**
I have done City of Light, I have chosen Scryers with A'dal. Khadgar does NOT give the followup quest that should lead me to Voren'thal. 

Item: https://www.wowhead.com/npc=18530/vorenthal-the-seer
Quest: https://www.wowhead.com/quest=10553/vorenthal-the-seer
Spell: https://wowhead.com?spell=

**Expected behavior**

I expected Khadgar to give me the followup quest which everyone else in the guild got.

**Screenshots/videos**

**Additional context**

**Comment by Godmatik** [comment]
You did the quest to take the tour around Shattrath?
