### ISSUE TITLE
water elemental always on passive

### ISSUE THREAD

**Issue by ayse33** [SunstriderEmu/BugTracker#2409]
so  basically every time i summon water elemental,he's on passive which is really annoying,even if you change it to defensive the next time you summon him he will be on passive again,it's getting really annoying please fix.

**Comment by Godmatik** [comment]
Duplicate https://github.com/SunstriderEmu/BugTracker/issues/2095

Basically, they likely won't fix it soon, there is a macro you can setup as a temporary work-around.
