### ISSUE TITLE
Quest to learn to smelt dark iron DOES NOT work

### ISSUE THREAD

**Issue by Swindellite** [SunstriderEmu/BugTracker#2413]
In Blackrock Depths there exists an NPC called Gloom'rel. Talking to him should make a chalice appear nearby which starts a quest. you complete the quest by providing some materials and then you learn to smelt dark iron. The chalice does not appear when you talk to Gloom'rel.

**Comment by MrJiraiya** [comment]
Can confirm that chalise doesn't spawn. Also doors are bugged in this room 
![WoWScrnShot_032920_145054](https://user-images.githubusercontent.com/62834115/77847204-abf22500-71d4-11ea-888e-cc1f07bc1e6f.jpg)
![WoWScrnShot_032920_145051](https://user-images.githubusercontent.com/62834115/77847206-adbbe880-71d4-11ea-8262-46502bb2d64d.jpg)

**Comment by MrJiraiya** [comment]
After Friday, 3 April 2020 fix:
-Fixed BRD's Tomb of the Seven event.
Spectral Chalise exists now as well as the quest.
Turned in materials (20 gold bars, 10 truesilver bars, 5 star ruby) and finished the quest but didn't get the spell to smelt Dark Iron Bars.
![Spectral Chalise 3](https://user-images.githubusercontent.com/62834115/78363433-2952d680-75d5-11ea-88c6-795e2aa9cf8c.gif)

**Comment by Sheikthecatman** [comment]
Thanks!
The issue with the skill not being taught should now be resolved.
Please create a ticket in-game as you are clearly now missing the skill.

**Comment by EL100** [comment]
Confirmed chalice didn't spawn. Spectral of Gloorm'rel also didn't spawn. Cannot learn the skill.
