### ISSUE TITLE
Lockpicking in trade Window Bugged

### ISSUE THREAD

**Issue by davedave1991** [SunstriderEmu/BugTracker#2414]
**Describe the bug**
When trying to lockpick someones lockbox I am unable to unless they trade it over, Both in the
''this item will not be traded'' and normal windows I can not lockpick it

**To Reproduce**
Tried with dif ppl , tried relogging and only way to lockpick for someone is if they trade the box over

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by Jerrythemagicdog** [comment]
Fixed a long time ago, thanks for the issue.
