### ISSUE TITLE
Health Leech and Periodic Leech incorrectly generate healing threat

### ISSUE THREAD

**Issue by mechanicsTBC** [SunstriderEmu/BugTracker#2415]
Health Leech and Periodic Leech auras generate healing threat.  The are a separate form of healing that should not generate healing threat.

Spells tested:
Drain Life spell=27220
Death Coil spell=27223
Siphon Life spell=30911

Have your pet pull 2 mobs and attack one of them.  Use a leech spell on the mob your pet is attacking and you will generate healing threat on the second mob.

There are other abilities and items that use Leech that I did not test that are more than likely generating healing threat.

Please note that Drain Life and Siphon Life were changed in patch 2.3 to have their healing effect reduced by healing reduction effects (not sure if this is working or not, just a note to not break with change). https://wowwiki.fandom.com/wiki/Patch_2.3.0

http://web.archive.org/web/20081109005958/http://elitistjerks.com/f31/t17008-warlock_pve_raiding_compendium/
https://www.mmo-champion.com/threads/632871-Warlock-Threat-Issues
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/13015-how-do-aggro-threat-work-wow.html
https://vanilla-wow.fandom.com/wiki/Drain

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
