### ISSUE TITLE
Pet Stay bugs

### ISSUE THREAD

**Issue by mechanicsTBC** [SunstriderEmu/BugTracker#2416]
Tested using a warlock.  Using default pet bar (no macros).

When using Stay after sending pet to Attack a mob, pet will continue to run to mob to attack instead of stopping on spot when the command was issues.  After reaching mob, pet will attack mob as long as it is within range while the pet holds it position.  After mob dies pet will Stay at mobs original position where the pet ran to initially.

When using Stay while pet is following, pet will Stay when it reaches the casters position (the player).

Pet Stay should cause the pet to Stay at the pets current position when the command is issued.

**Comment by Jerrythemagicdog** [comment]
Fixed a long time ago, thanks for the issue.
