### ISSUE TITLE
Alliance players are able to kill horde in horde zones without gaurds attacking

### ISSUE THREAD

**Issue by nhthor** [SunstriderEmu/BugTracker#2418]
**Describe the bug**

Alliance players are able to kill horde in horde zones without guards attacking
**To Reproduce**

I was in stonebreaker hold and no guard attacked the alliance players, they were able to run around but when I went to Honor hold or Allerian stronghold guards would charge/attack me

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

guards should attack the alliance scum
**Screenshots/videos**

**Additional context**

fix this please

**Comment by beraus** [comment]
Guards updates are now live, should be fixed. 
If you notice more issues - feel free to comment here and we'll check it further.
