### ISSUE TITLE
Magtheridon Blast Nova doesn't go on cooldown if banish is applied while he's casting but not yet channeling

### ISSUE THREAD

**Issue by Bzmode** [SunstriderEmu/BugTracker#2419]
**Describe the bug**
When Magtheridon begins casting Blast Nova if 4 cubes are clicked before the channel and 1 after he beings to cast it, the banish will go through as normal but he will instantly start to channel blast nova again right after he breaks out of banish.

**To Reproduce**
1. wait for blast nova cast.
2. have 4 of the 5 cubes click right away during the channel.
3. have a fifth person click the cube right after the channel ends and the cast it self begins.
4. watch as he gets banished, comes out and immediately starts casting a new blast nova.

**Expected behavior**

If at any point after the blast nova channel/cast he gets banished he should have to wait for blast nova to be off CD before trying again.

**Comment by kelno** [comment]
Thanks!
This has been discussed before and is blizzlike, the spell doesn't go on cooldown if it's not currently channeling.
We're considering removing that because some might say it's complete bullshit.

**Comment by Bzmode** [comment]
https://youtu.be/6fYOGFWucHA?t=159 you can see them click cubes right as the channel begins and he doesn't recast once the banish breaks.

You can also see from this video the quake is supposed to know people in random directions instead of away from mag every tick.

**Comment by kelno** [comment]
You seem to be right indeed, idk why that was our conclusion before then.
In any case, I'll remove that. Live with next reboot from now.
