### ISSUE TITLE
Bugged Zeppelin from Grom'gol Base Camp to UC

### ISSUE THREAD

**Issue by shrift1** [SunstriderEmu/BugTracker#2422]
Bugged Zeppelin
Zeppelin from Grom'gol Base Camp to Undercity
![WoWScrnShot_031820_153154](https://user-images.githubusercontent.com/31934397/77147125-e77e4800-6a8c-11ea-8db8-870a7560e71c.jpg)
![WoWScrnShot_031820_153150](https://user-images.githubusercontent.com/31934397/77147127-e9480b80-6a8c-11ea-888b-0069aaf8b1fc.jpg)

I fell twice and died from fall damage :(

**Comment by Jerrythemagicdog** [comment]
Thanks, working on it!

**Comment by artieau** [comment]
Duplicate of #445
