### ISSUE TITLE
Personal jewelcrafting epic gems

### ISSUE THREAD

**Issue by Speank123** [SunstriderEmu/BugTracker#2423]
**Describe the bug**

The soulbound jewelcrafting gems that jewelcrafters can use for themselfs are not at any of the reputation vendors
https://tbc-twinhead.twinstar.cz/?item=33156
https://tbc-twinhead.twinstar.cz/?item=33305
https://tbc-twinhead.twinstar.cz/?item=33160
https://tbc-twinhead.twinstar.cz/?item=33158
https://tbc-twinhead.twinstar.cz/?item=33157
https://tbc-twinhead.twinstar.cz/?item=33159
https://tbc-twinhead.twinstar.cz/?item=33155

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by bugreporterx** [comment]
This issue has not been addressed. Can we get an update please?

**Comment by beraus** [comment]
Not live before 2.2.

**Comment by Jerrythemagicdog** [comment]
Thanks, I've updated it as we mentioned we should have them out with T5 at some point and forgot about it. Live with next update.
