### ISSUE TITLE
Ethereal thieves reset threat in Karazhan

### ISSUE THREAD

**Issue by Edmondclassic** [SunstriderEmu/BugTracker#2424]
**Describe the bug**
Ethereal thieves reset their threat when you fight them, it usually coincides with the mob adding a stack to the tank.

**To Reproduce**
1. Be fighting an Ethereal Thief in Karazhan
2. Mob uses an ability that adds a debuff to the tank
3. Threat resets

Mob: https://tbc-twinhead.twinstar.cz/?npc=16544

**Expected behavior**
Threat does not reset

**Comment by Jerrythemagicdog** [comment]
The threat should only reset when the creature casts Disarm, if that's not the case please let us know:
https://www.wowhead.com/npc=16544/ethereal-thief#comments
