### ISSUE TITLE
Malygen missing 2 recepies

### ISSUE THREAD

**Issue by winex93** [SunstriderEmu/BugTracker#2425]
**Describe the bug**
NPC Malygen  (ID: 2803) is missing 2 recipes:
Recipe: Charred Bear Kabobs (ID: 35564)
Recipe: Juicy Bear Burger (ID: 35566)

**Comment by Seanieshotgunz** [comment]
https://tbcdb.com/?npc=2803

Database link for the NPC in question.

**Comment by Jerrythemagicdog** [comment]
Thanks, live with next restart.
