### ISSUE TITLE
Captain Dirgehammer Missing Items

### ISSUE THREAD

**Issue by Seanieshotgunz** [SunstriderEmu/BugTracker#2426]
**Describe the bug**
Captain Dirgehammer is missing most level 70 Blue Honor Sets. He currently only has Priest, Paladin and Shaman.

**To Reproduce**
Travel to Stormwind's Old Town.
Enter the Champion's Hall.
Walk upstairs to see Captain Dirgehammer.
Check his sell list.

NPC Corrected Sell List: http://tbc.cavernoftime.com/npc=12777#sells:100+1 

**Screenshots/videos**
Current sell list of the vendor in question.
Page 1: https://gyazo.com/7446467dd449aa61832ae5aeeb8ecb19
Page 2: https://gyazo.com/41e5acc4db4c0e447e8be0d0a0b1d5b3
Page 3: https://gyazo.com/55750ff015d73711ac0f147423731d34
Page 4: https://gyazo.com/58c516566bff9c2cb7bc90ee8bad91b8
Page 5: https://gyazo.com/ca8dfc9715d8e249a4fb746ef7a72b33
Page 6: https://gyazo.com/dc7f3e1a40d0a3641a96633da5b02d41

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart
