### ISSUE TITLE
Talonsworn Forest-Rager respawn time too long

### ISSUE THREAD

**Issue by columbolajos** [SunstriderEmu/BugTracker#2427]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
There isn't a single spawn of those that's currently active right now until Skettis is released.
