### ISSUE TITLE
Account ban

### ISSUE THREAD

**Issue by Alexc330** [SunstriderEmu/BugTracker#2432]
По достижению 51 уровня,получил автоматический бан аккаунта по причине "Выравнивающий бот" прошу разобраться ,что это за бот? Я ничего не устанавливал ,никаких аддонов и тд.  Ник в игре Alexc орда

**Comment by Jerrythemagicdog** [comment]
Upon reviewing the replay from the ban the character "Alexc" was definitely botting.

**Comment by Jerrythemagicdog** [comment]
Looks like a mistake on our part, sorry about that! Your account has been unbanned.
