### ISSUE TITLE
[Warrior] Deepthunder stun is on wrong DR

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#2435]
**Describe the bug**
Stun from Deepthunder/Stormherald is currently on Controlled stun DR category, which is wrong.

**Expected behavior**
Should be on rng stun DR, with mace stun specialization.

https://youtu.be/3z2nV3pRDS0?t=126

**Comment by Jerrythemagicdog** [comment]
Thanks, the fix is live.

dev:
 'd40a047' (core)
