### ISSUE TITLE
[Magtheridon] Hellfire Superiority

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2436]
You can have the Hellfire Superiority buff (5% extra damage when all 3 towers are captured) while inside the Mag raid. 

All you have to do after zoning in is either exit/re-enter or just relog, and then you'll have the damage buff.

**Comment by Jerrythemagicdog** [comment]
Thanks, is that proven to be incorrect?

**Comment by Godmatik** [comment]
"When all three points are controlled by a faction they will gain a zone-wide bonus of +5% Damage, applicable even within the Hellfire Citadel instances"

I can't find any source saying that this shouldn't be present in the Mag raid. It says 'instances', but that could or could not include Mag.

Closing this out for now.
