### ISSUE TITLE
"Pattern: Cloak of Darkness" not available

### ISSUE THREAD

**Issue by MeckieH** [SunstriderEmu/BugTracker#2437]
**Describe the bug**
[Pattern: Cloak of Darkness] is not available from the vendor "Apprentice Darius" outside Karazhan. This pattern is added in patch 2.2, so technically this is correct. However, [Pattern: Shadowprowlers Chestguard] and [Enchanting: 20 Agility Weapon] are available on the same vendor, both patterns that are also added in 2.2. There are several other inconsistencies in the item timeline, like Ragesteel Shoulders (added in 2.4) being available etc..

**To Reproduce**
Go to Apprentice Darius outside Karazhan and look for what he is selling.

Item: https://tbc-twinhead.twinstar.cz/?item=33124 https://www.wowhead.com/item=33124/pattern-cloak-of-darkness

**Expected behavior**
Considering other items and patterns available on Endless, this pattern should be aswell.

**Comment by Jerrythemagicdog** [comment]
Thanks, the item will be released with t5.
