### ISSUE TITLE
Crimson Hammersmith / Black Guard Swordsmith

### ISSUE THREAD

**Issue by Seanieshotgunz** [SunstriderEmu/BugTracker#2439]
**Describe the bug**
The Blacksmithing Plans are reversed.

**To Reproduce**
Using the plans spawns the opposite plans.

Crimson Hammersmith: Blacksmithing Plans inside Live Stratholme.
Black Guard Swordsmith: Blacksmithing Plans inside Undead Stratholme.

**Expected behavior**
Blacksmiths who choose Master Swordsmithing are supposed to travel to UD Strat to kill the Swordsmith, not Live Strat.
On the other side of the coin Blacksmiths who choose Hammersmith are left completely confused by not being able to spawn the Crimson Hammersmith.

**Screenshots/videos**
https://www.youtube.com/watch?v=deCi-ZW14nA&feature=youtu.be

**Comment by beraus** [comment]
> Thanks! Fixed in [68b0933bb204fe91288aab50a6c5637cae392457](https://github.com/kelno/sunstrider-scripts/commit/68b0933bb204fe91288aab50a6c5637cae392457). The fix will be applied next server restart.
