### ISSUE TITLE
Windfury Totem 5% proc instead of rightful 20%

### ISSUE THREAD

**Issue by Tasressurect** [SunstriderEmu/BugTracker#2440]
Have looked it for several weeks now and confirming that the totem's proc is approximately 5% instead of the tool tip which states it should be a 20% proc rate.

Windfury Weapon on the other hand, is working as intended.

**Comment by Godmatik** [comment]
Do you have screenshots with proof like from recount?

**Comment by TheMoneyHater** [comment]
20% proc rate don't mean 20% increase damage.

**Comment by Jerrythemagicdog** [comment]
Please record a video / provide screenshots of recount. It can be tested in front of major cities using training dummies. Thanks!
