### ISSUE TITLE
Elemental Seaforium Charge Missing from NPC

### ISSUE THREAD

**Issue by Seanieshotgunz** [SunstriderEmu/BugTracker#2442]
**Describe the bug**
Elemental Seaforium Charge Missing from Vendors Sell List

**To Reproduce**
Visit Karazz in Netherstorm or Paulsta'ats in Nagrand.
Karazz: https://www.wowhead.com/npc=20242/karaaz
Paulsta'ats: https://www.wowhead.com/npc=23007/paulstaats
Item: https://www.wowhead.com/item=23874/schematic-elemental-seaforium-charge

**Expected behavior**
Having the item in the sell list.

**Screenshots/videos**
Karazz Sell List:
Page 1: https://gyazo.com/e1b4add2a3af1dd35dd34ab1e01b5b9f
Page 2: https://gyazo.com/8b875a79a9b15fee47a67e2f04b1422a
Page 3: https://gyazo.com/3f4f1ebf8fb6125536d2516cd7831d21
Paulsta'ats Sell List
Page 1: https://gyazo.com/e1b4add2a3af1dd35dd34ab1e01b5b9f
Page 2: https://gyazo.com/8b875a79a9b15fee47a67e2f04b1422a
Page 3: https://gyazo.com/3f4f1ebf8fb6125536d2516cd7831d21

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next server update.
