### ISSUE TITLE
Parry haste not working

### ISSUE THREAD

**Issue by Swindellite** [SunstriderEmu/BugTracker#2443]
After a parry the player's next auto attack should be 50% faster. This does not work.

**Comment by Notmelody** [comment]
Confirmed for npc mobs

**Comment by oldspices** [comment]
not all are supposed to do that tho

**Comment by TheMoneyHater** [comment]
If anyone is playing a tank try it on bosses since not all normal mobs have a parry chance in the game.

**Comment by kelno** [comment]
Fixed with next update
