### ISSUE TITLE
first aid trainer Doctor Gustaf VanHowzen

### ISSUE THREAD

**Issue by suinotlim** [SunstriderEmu/BugTracker#2444]
When i was going to do the quest triage for first aid 225, i noticed that Doctor Gustaf VanHowzen in Dustwallow March, doesn't have any options available and his name doesn't appear when the courser is over him and u cant click him, so u cant get past level 225 on first aid.

**Comment by Godmatik** [comment]
What level are you?

**Comment by suinotlim** [comment]
65

**Comment by Krykutay** [comment]
I have the same problem, so do my friends

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart!
