### ISSUE TITLE
Badge of Justice issue

### ISSUE THREAD

**Issue by Phonebookhero** [SunstriderEmu/BugTracker#2446]
**Describe the bug**
Finished heroic ramps, did last boss, badge dropped, upon clicking "Invalid target"

**To Reproduce**
See above

ramps id 436

**Expected behavior**

**Screenshots/videos**

**Additional context**
ramps id 436 - Alliance side

**Comment by B0nisek** [comment]
yeah got this problem as well missed 6 bojs because of that so far

**Comment by mayday2013** [comment]
That's why I run shadowplay when playing xD

**Comment by B0nisek** [comment]
> That's why I'm using shadowplay when I play xD

what?

**Comment by mayday2013** [comment]
Nvidia Geforce exp. their vid capturing software

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2839
