### ISSUE TITLE
[Dual Spec] Used when on flight paths/NPC dislike you

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#2447]
If you change to secondary spec while on flight path, every NPC "That merchant doesn't like you" error/no interaction upon landing if used during flight path travel. Relogging again fixes the issue.

If possible to update this functionality, it would be a low priority feature request at most :)

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by z5n** [comment]
no longer an issue
