### ISSUE TITLE
The Hawk's Essence Quest Mob Bugged.  Needed for Swift Flight Form

### ISSUE THREAD

**Issue by Shifthappenz** [SunstriderEmu/BugTracker#2449]
![1](https://user-images.githubusercontent.com/61995578/77218558-ec7dde80-6b02-11ea-9aca-c990d2e82a41.jpg)
**Describe the bug**

**To Reproduce**

1. Summon Mob "Guardian of the Hawk" using the Hawk stone in Terokkar Forst (45.5 , 93.5)
2. Mob does not take increased damage
3. Mob despawns when kiting.

Mob: https://wotlk-twinhead.twinstar.cz/?npc=22992
Quest: https://www.wowhead.com/quest=10992/the-hawks-essence

**Expected behavior**

This mob should take about 5x damage from Arcane/Nature spells as mob has 50k HP

**Additional context**

This is part of the Druid Swift Flight Form quest chain.  Without these changes this quest cannot be completed solo.

https://imgur.com/a/8JzAr51

**Comment by wiglefish** [comment]
Confirming I also had this issue. Had to get dps helper to nuke it and still barely killed him with 2 people. Should be soloable as resto/balance.

**Comment by Jerrythemagicdog** [comment]
Thanks, should be resolved after next restart.

dev:
'fbd3db9' (scripts)
