### ISSUE TITLE
Arthorn Windsong at the Evergrove not giving replacement whistles for Druids swift flight form questline

### ISSUE THREAD

**Issue by kahelio** [SunstriderEmu/BugTracker#2450]
**Describe the bug**
NPC missing gossip and action

**To Reproduce**
Delete the whistle while doing the quest The Eagle's Essence

NPC: https://wowhead.com/npc=22924
Item: https://wowhead.com?item=32657
Quest: https://wowhead.com?quest=10990
Spell: https://wowhead.com?spell=40886

**Expected behavior**
NPC should have gossip to give an replacement whistle

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
