### ISSUE TITLE
Formula: Runed Arcanite Rod replenish rate at vendor is incorrect

### ISSUE THREAD

**Issue by vladimyrr** [SunstriderEmu/BugTracker#2451]
Formula: Runed Arcanite Rod sold by Loralae Wintersong in Moonglade is supposed to replenish stock ever 15-30 minutes. Currently have been waiting 2+ hours and it has not been restocked.

To Reproduce

1. Buy Formula
2. ???
3.  Keep waiting

Item: https://classic.wowhead.com/item=16243/formula-runed-arcanite-rod#comments
NPC: https://classic.wowhead.com/npc=12022/lorelae-wintersong

Expected Behavior: Should restock after 15-30 minutes

**Comment by Jerrythemagicdog** [comment]
The restock time on the live server is set to 25 minutes.

**Comment by oldspices** [comment]
you have to refresh the window to see it- you sure someone didnt just ninja it ?
