### ISSUE TITLE
Gan'arg Analyzer 

### ISSUE THREAD

**Issue by Snooper91** [SunstriderEmu/BugTracker#2452]
There are no of Gan'arg Analyzer npc, no spawn no nonething..

Gan'arg Analyzer
Item: https://tbcdb.com/?item=34114

They dont spawn or even exist where they should..
https://i.postimg.cc/HsybLB24/ripo.png

**Comment by wiglefish** [comment]
I think this is to do with Ogrila not being available yet. There are other NPCs including the consortium-like guys up in the north side of blades edge also missing.

**Comment by Jerrythemagicdog** [comment]
Those creatures will be released along with Ogri'la. The recipe for the Repair Bot which you're probably looking for is now available from the following creatures: Gan'arg Engineer (16948), Deathforge Tinkerer (19754) and Deathforge Technician (19979).
