### ISSUE TITLE
Earthbind Totem still not pulsing correctly

### ISSUE THREAD

**Issue by TheMoneyHater** [SunstriderEmu/BugTracker#2453]
How it's suppose to be:
https://wowwiki.fandom.com/wiki/Earthbind_Totem
under Tips
"It's helpful to drop a totem just before running from a fight to gain some distance between you and your pursuer, as well as just before your enemy is about to run away. It takes a second to have its first effect, so you should drop it a couple seconds before you need it for best effect."
1 second after the first pulse, but on endless it takes 3 seconds for it to pulse the first time.

Check this video https://streamable.com/l2n96 and look under the target frame and the timer I activate on the same button.

This was the old post I made earlier. It was changed to make it pulse on cast which is also wrong. It's suppose to have a 1 second delay!!!!!
https://i.imgur.com/HhVlDmX.png

**Comment by Rettiy** [comment]
What the hell are you even doing to shamans on this server?
**It's unthinkable to have Earthbind on anything but instant proc on drop.**
Stop ruining already ruined class in TBC jesus.

Proof: https://www.youtube.com/watch?v=SAB_zr3bJ20&feature=youtu.be&t=597 procs literally at the time it's cast.

**Comment by TheMoneyHater** [comment]
That video was recorded on a pserver also?
https://i.imgur.com/GukJhDx.jpg

Still, "It's helpful to drop a totem just before running from a fight to gain some distance between you and your pursuer, as well as just before your enemy is about to run away. **It takes a second to have its first effect, so you should drop it a couple seconds before you need it for best effect.**" on wowwiki I would say is proof enough.

**Comment by Aeded** [comment]
@TheMoneyHater You are clueless and you just waste everyone whos involved time. Stop making stupid reports if you have no clue how things work, thanks.

also wowwiki is miles from being legitimate source of info.

**Comment by TheMoneyHater** [comment]
Why are you being so mean/toxic? And why wouldn't wowwiki be a legitiamte source from 2007?

**Comment by Rettiy** [comment]
Probably because this is such a basic thing for players. 
I get when people mistake Dragon's Breath and CoC on same CD cuz it's TBC specialty but Earthbind works like this even on WOTLK so I guess you shouldn't be allowed to even report such nonsense in the first place. No offense.

**Comment by TheMoneyHater** [comment]
Haha, I know I am right though but okay
