### ISSUE TITLE
[Priest] Mind Soothe doesn't work. 

### ISSUE THREAD

**Issue by longereaven** [SunstriderEmu/BugTracker#2454]
Mind Soothe does not reduce the target's range from which it will attack/aggro onto you. It simply doesn't do anything.

**Comment by oldspices** [comment]
can confirm that we used priest mind soothe on those mobs in SL to skip them and they still pulled :3  I usually do this on other servers without pulling.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by Jerrythemagicdog** [comment]
Fixed after next server update!
