### ISSUE TITLE
[Priest] Vampiric Embrace does not heal from the killing blow.

### ISSUE THREAD

**Issue by longereaven** [SunstriderEmu/BugTracker#2455]
Problem: When you have Vampiric Embrace up on a target, the final killing blow does not heal you (as it should). 

Thoughts: I think the Vampiric Embrace doesn't register when the target is dying/dead, which makes it not heal you. 

How it should work: It should heal you from the spell that kills the target as well.

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2176
