### ISSUE TITLE
Doomwalker Earthquake Ability

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2457]
Doomwalker's Earthquake ability is supposed to stun you in addition to dealing damage, but it's not stunning at all.

**Comment by Jerrythemagicdog** [comment]
It's supposed to do a knockback is it not doing it?

**Comment by Godmatik** [comment]
There is no knockback either, is that a pre-nerf mechanic?

Per wowwiki and wowhead, his earthquake is just a stun.

https://wowwiki.fandom.com/wiki/Doomwalker
https://www.wowhead.com/npc=17711/doomwalker#comments

"Earthquake, which does 8k damage over 8 seconds (4 ticks of 2000) in a large radius around him. Everyone is knocked down/stunned for the duration of this effect, so everyone needs to be kept over 8000hp. Despite the ability being named earthquake it's simply anyone in a large radius around him, as folks on flying mounts got hit with it and killed when they never landed."

**Comment by NeonicSupersonic** [comment]
Theres no knockback, it just deals damage

**Comment by Godmatik** [comment]
Still no knockback by the way, fight is pretty trivial as a result.

**Comment by Jerrythemagicdog** [comment]
Seems like we forgot about this for some reason.
Thanks for the issue, fixed with next update.
