### ISSUE TITLE
[Alchemy] Mad Alchemist's Potion missing

### ISSUE THREAD

**Issue by zkillertheman** [SunstriderEmu/BugTracker#2459]
**Describe the bug**
Unable to learn Mad Alchemist's Potion from trainer, was added in 2.3. 
https://wow.gamepedia.com/Mad_Alchemist%27s_Potion
should be ingame since everything should be at 2.4.3

**To Reproduce**
Be alch at level 325

**Expected behavior**
able to learn from trainer at skill 325

**Comment by Godmatik** [comment]
The client is at 2.4.3, but the game is currently emulating to be at patch 2.0, so unlikely to see this pattern until ZA is released and such.
