### ISSUE TITLE
[Priest] Mind Control doesn't stop autoattacks on now friendly targets.

### ISSUE THREAD

**Issue by Ibuprofeno** [SunstriderEmu/BugTracker#2460]
**Describe the bug**
When a player is Mind Controlled anyone who was attacking them keeps auto-attacking even though they're now friendly.

**To Reproduce**

1. Player1 is part of a faction and Player2 is part of the opposite faction.
2. Player1 starts auto-attacking Player2.
3. A priest from the same faction as Player1 Mind Controls Player2.
4. Player1 will keep auto-attacking Player2 even though they're now friendly.

**Expected behavior**
Player1 stops auto-attacking Player2 as they're now friendly.

EDIT: This also happens with mobs.

**Comment by kelno** [comment]
Thanks, fixed with next restart

**Comment by kelno** [comment]
Updated again, this last fix wasn't working while in arena
