### ISSUE TITLE
Mage Blink is immune to stuns/roots for TOO long after blink :(

### ISSUE THREAD

**Issue by oldspices** [SunstriderEmu/BugTracker#2461]
**Describe the bug**

When a mage blinks, he is "immune" to all roots/stuns for too long afterwards
**To Reproduce**

Have a mage blink- then intercept or feral charge or cast roots 1-2 (or maybe even more) Seconds afterwards
1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=https://classic.wowhead.com/spell=1953/blink

**Expected behavior**

if you charge DURING a blink - it should indeed be immune- however if you see him land and the blink buff disappears- you should be able to intercept etc. 
**Screenshots/videos**

**Additional context**

this just kills pvp for me- it feels so sloppy and poor - im sure there could be old videos out there proving this aint how it should be.

**Comment by Jerrythemagicdog** [comment]
That's just the buff the player gets that you can see appear on their buff bar not something we control or add on our own.
![image](https://user-images.githubusercontent.com/46463908/77251145-9dd85d80-6c44-11ea-9535-4f6dea81c167.png)

**Comment by oldspices** [comment]
the buff is too long then. its crap. i guess ill dig through enormous amounts of old pvp videos to find proof :(
