### ISSUE TITLE
scryer rep quest bugged

### ISSUE THREAD

**Issue by xEnvoy** [SunstriderEmu/BugTracker#2462]
I bought some basilisk eyes last night and went to turn them in to get rep to go back to neutral rep with scryer and it increased the rep towards hated but the quest struggling supplies made it better but cant repeat the quest was 1 time turn in. used a ton of basilisk eyes and it went towards more hated

quest name is Voren'thal's visions

**Comment by xEnvoy** [comment]
![d5db209a9fb108352f79e39d9259b8f5](https://user-images.githubusercontent.com/29165493/77262436-24546580-6c6c-11ea-9287-4d1b295998ce.png)

**Comment by xEnvoy** [comment]
please fix my rep :c

**Comment by xEnvoy** [comment]
anyone?

**Comment by beraus** [comment]
[This quest is only available to characters hostile to The Scryers It is repeatable and used to switch over from The Aldor.](https://www.wowhead.com/quest=10024/vorenthals-visions#comments:id=22273)
