### ISSUE TITLE
Allocating a talent point while dead resurrects me

### ISSUE THREAD

**Issue by Zedlus** [SunstriderEmu/BugTracker#2463]
**Describe the bug**
While dead I allocated a point in Heart of the Wild and came back to life where my ghost had been running back to my corpse.

**To Reproduce**
1) Be dead
2) Have a talent point available
3) Allocate it, in my case I chose Heart of the Wild as a druid
4) Suddenly come back to life?

[](https://classic.wowhead.com/spell=24894/heart-of-the-wild)

**Expected behavior**
Allocating a talent point would give me a talent point, not res me

**Screenshots/videos**
Didn't take any

**Additional context**
I dinged from 52 to 53 but didn't allocate a talent, I had 4/5 HoTW. I died to some fast as fuck respawns (your respawns are way too fast to solo quest anywhere in WPL by the way) While running back to my corpse I put in the talent and went from 4/5 to 5/5 and suddenly came back to life where the ghost was running.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by Jerrythemagicdog** [comment]
Funnily enough the rank 4 of the spell has a self ressurect effect probably added by accident by Blizzard ages ago.
Fixed after next restart!
