### ISSUE TITLE
Armor/resistance check macro

### ISSUE THREAD

**Issue by Highdps** [SunstriderEmu/BugTracker#2464]
Hello 
Armor/resistance macro didn't works at all 
Here is macro
 /script u=UnitResistance y="target" a=u(y ,0) h=u(y ,1) f=u(y ,2) n=u(y ,3) fr=u(y ,4) s=u(y ,5) z=u(y ,6) SendChatMessage(UnitName(y).." has "..a.." Armor, "..h.." HR, "..f.." FR, "..n.." NR, "..fr.." FrR, "..s.." SR and "..z.." AR.", SAY)

How to reproduce 
Make macro and use on any mob in raid/outside 

Profs
https://imgur.com/a/vkZSBxK

**Comment by Ironjudgment** [comment]
https://wowwiki.fandom.com/wiki/World_of_Warcraft_API?oldid=1369045

May 2008 - UnitResistance is not a protected API
