### ISSUE TITLE
Zuluhed quest bugged

### ISSUE THREAD

**Issue by Joshuadelf** [SunstriderEmu/BugTracker#2465]
**Describe the bug**
Can't pick up the quest from the questgiver to get zuluhed to spawn.  There simply is no quest there.

**To Reproduce**
1. Had quest to kill zuluhed
2. Dropped quest to pick it back up
3. Quest has disappeared

Start NPC: https://www.wowhead.com/npc=22112/karynaku
Quest: https://www.wowhead.com/quest=10866/zuluhed-the-whacked

**Expected behavior**
I expected to be able to get the quest

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, should be fixed after next restart.

dev:
'2e9a8c8' (scripts)
