### ISSUE TITLE
[Item] Mark of Vindication doesn't proc off refreshing judgements/applying vindication.

### ISSUE THREAD

**Issue by Ibuprofeno** [SunstriderEmu/BugTracker#2467]
**Describe the bug**
This is related to https://github.com/SunstriderEmu/BugTracker/issues/1714 and https://github.com/SunstriderEmu/BugTracker/issues/1713 . Currently Mark of Vindication (https://www.wowhead.com/item=27927/mark-of-vindication) doesn't proc off either.
Sources are hard to find, best I can provide are wowhead comments from said items.

2.3.3 comment
https://www.wowhead.com/item=27927/mark-of-vindication#comments:id=229254

> Then it hit me. Refreshing a judgement counts too. As does procing vindication. I tried it and yes it does proc off those two. Finally, a use for it. So while it doesn't proc that often at all, it's nice to have as an add on to the other mana regens out there. Hammer of Destiny, Insightful Earthstorm Diamond, etc.. I have this and both the hammer and the meta gem and I get so much mana back now I don't even have to worry about it. :) My advice? Get all three if you can. The hammer, the meta gem and this trinket. Then you will definitely be ready for raids.

3.0.1 (I believe it's still relevant)
https://www.wowhead.com/item=27926/mark-of-vindication#comments:id=218758:reply=48721
> Actually I've been testing this for 30 minutes or so. I does NOT proc from Seal of Blood. However, it WILL proc from refreshing judgements. So if you have say, judgement of wisdom on the mob, and land a hit, it has the 15% chance to return mana back. Unforunately, in 3.0 judgements will not be refreshed from attacks, only the judgement spell.

2.3.0
https://www.wowhead.com/item=27927/mark-of-vindication#comments:id=64015:reply=22390
> This item will in fact proc off of a Seal of Command hit, that or it is proccing from vindication being reapplied. 

About this last comment: It does not proc off SoC/SoR/SoB hits, I added it because of the Vindication reference.

**Expected behavior**
Mark of Vindication should proc off refreshing Judgements (I can't tell if it should also proc off refreshing other paladin's judgements) and Vindication procs as they are separate spells.

**Screenshots/videos**
[https://imgur.com/a/7iUtVTR](url) Tested with target dummies refreshing JotC. Never got any mana from refreshing it or Vindication procs.

**Comment by Jerrythemagicdog** [comment]
Fixed in one of the linked issues, thanks for the issue.
