### ISSUE TITLE
[Item] Ravager doesn't proc off itself.

### ISSUE THREAD

**Issue by Ibuprofeno** [SunstriderEmu/BugTracker#2468]
**Describe the bug**
Ravager (https://classic.wowhead.com/item=7717/ravager) can't chain whirlwinds.
This might not be a serious issue but I was hoping to use this for large trash pulls as a ret paladin.
Proc rate also seems too low, I've been using it on classic and it's insane there.
 I tried to look for a changelog in case it was changed in TBC but have found nothing about it.
**Expected behavior**
Whirlwind can proc off itself.
https://youtu.be/b8P9b23SWJ8?t=114

**Comment by Jerrythemagicdog** [comment]
It can proc off of itself, thanks for the issue though.
