### ISSUE TITLE
High King Maulgar

### ISSUE THREAD

**Issue by Danke34** [SunstriderEmu/BugTracker#2473]
"Maulgar Boss Fight - Mage Boss and Shaman Boss 'bugged'"

After having wiped numerous times last night on the Maulgar fight in Gruul's Lair, we noticed that there are two flaws in the fight. One: The Mage Boss seems to be not as functional as he could be. When we engage the fight, he immediately casts shield, then proceeds to Greater Fireball our Mage tank. When the Mage tanks shield disappears after the first spell steal, the Mage Boss doesn't put up his shield again for another two and at times three Greater Fireballs. This leaves our Mage Tank to soak 18k damage (note our Mage Tank has got approximately 11.5-12k health and at this state of the game, a Mage Tank should have at max 10k with flask etc. because of the normally lack of stamina gear - we're just blessed to have early blue PVP vendor gear) and at times 26-27k damage, before the Mage Boss puts  his shield up again. We had way more healers than would seem needed (8 healers) for such a fight, and there was no way to keep up with the Mage Boss. Even pre-casting wasn't enough to keep our Mage Tank alive. Everyone knows that when the shield disappears on the Mage Tank, the Mage Tank is going to soak ONE big nasty Greater Fireball with his Fire Ward and then the rest has got to be outhealed, but two or more Greater Fireballs is not correct.

Second major thing: The Shaman/Hunter Boss (The guy wearing a staff throwing Lightning Bolts and Arcane Explosions (if you get too close)) decided to every now and again to just drop doing any Lightning Bolt and just engage in melee combat with his staff, setting off Arcane Explosions that could have been avoided. Our Moonkin and Hunter tanking the guy was never out of sight of the boss, so what causes him to just want to do melee combat?

**To Reproduce**
1) Figure out why the Shaman/Hunter boss randomly decides to drop casting Lightning Bolts at full mana and engage in melee. How to reproduce that I've no idea.
2) Tank the Mage Boss and figure out why he is not putting his shield up immediately after he has cast Greater Fireball one (when the Mage Tanks Spell-Shield that he stole disappears), and not after two Greater Fireballs or MORE.

Spell(s): https://www.wowhead.com/spell=33054/spell-shield / https://www.wowhead.com/spell=33051/greater-fireball

**Expected behavior**
He should only cast ONE Greater Fireball after the Mage Tanks shield goes down, and then put his shield back up and start recasting Greater Fireball.

https://gyazo.com/aff89baa6860b26f5d3020fb16d68f8e - Greater Fireball / Spell-Shield from wowhead

*On another note*
Trash also respawned once whilst the boss was engaged and in combat

**Comment by Jerrythemagicdog** [comment]
The Lightning Bolt has a minimum range of 8 yards, which is correct, he then engages in melee if someone is closer and he's unable to cast it. You can see that in his spell list here: https://www.wowhead.com/npc=18835/kiggler-the-crazed

The timing on the shield was intentionally increased so the mage has to gear for it and there has to be healing set up for at least two greater fire balls without a shield.

**Comment by krustan** [comment]
So you are telling us to have 10 healers. Am I right?

**Comment by Danke34** [comment]
@Jerrythemagicdog Absolutely incorrect. He'll only melee if a tank or another person in melee range overaggroes. Nobody ever went in melee range, 'cause we used a Boomkin all the time, he can't even polymorph him and "change tactics". 

Second: You can't just buff a boss and not ANNOUNCE it before the server goes live, that on this server - the admins believe that buffing raid bosses is the way to go. If you do that, you go the Warmane way and tell people that things are buffed or will be - or you do it another way and tell people that mechanics have been enhanced and where, so people can prepare for it. You don't just buff away a boss fight any way you like it, and then leave the players to figure out if it's a bug or not. Was it also intentional for the cubes not to work on Magtheridon, just so the healers had a challenge there when he did the mass AoE? Kinda like the Mage tank had to have 5k more HP to possibly survive two or three GFB?

**Comment by Godmatik** [comment]
They did announce encounters would be buffed before launch, healing the mage tank is not difficult at all assuming he is geared with the proper stamina set and your healers are not brain-dead.
