### ISSUE TITLE
Deadly Poison V crafting bug

### ISSUE THREAD

**Issue by Rachev7** [SunstriderEmu/BugTracker#2474]
Unable to craft
despite having the  required reagents the game doesn't allow the crafting of [Deadly Poison V] from the rogue poison profession. I spoke twice with GM Mallcop about this, I was told to delete catche folder, did so and still didn't work. I tried the options create all and create still didn't work. I tried relogging many times, still didnt work. It displays in the center of the screen an error in red:
 Item is not ready yet

https://classic.wowhead.com/spell=25347/deadly-poison-v

**Comment by Camper2D** [comment]
I can also confirm this. As a 60 Rogue with 300 Poisons and when I hit 61/305, I received this exact same error. "Item is not ready yet." in red letters across the middle of the screen.
![Image](https://user-images.githubusercontent.com/62540836/77299513-f2bab900-6cc2-11ea-80df-0bb86327c3c0.png)

**Comment by yobeske** [comment]
i"m getting the same problem?  Is there a fix for this yet?

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed a long time ago
