### ISSUE TITLE
Getting disconnected after 5 seconds of loging in

### ISSUE THREAD

**Issue by Ka7erica** [SunstriderEmu/BugTracker#2477]
**Describe the bug**
I login on the server and doesnt matter what i do i get disconnected in 10-15 seconds.

**To Reproduce**
My account name is Grissam

**Expected behavior**
I expect to play the game for more than 15 seconds without disconnect

**Comment by Godmatik** [comment]
Sounds like you might have a corrupt client, should start with a fresh one. The server is working fine for everyone else.

**Comment by Ka7erica** [comment]
> Sounds like you might have a corrupt client, should start with a fresh one. The server is working fine for everyone else.

i have downloaded several other clients and the problem is the same should i try to run the repair opiton?

**Comment by Jerrythemagicdog** [comment]
Really sounds like a problem on your end, but we could trouble shoot a bit if you provided a bit more info.

**Comment by Ka7erica** [comment]
> Really sounds like a problem on your end, but we could trouble shoot a bit if you provided a bit more info.

ok so i downloaded the client a couple of days ago from the endless.gg website and went online. 
i created a character and played till level 5. the next day i tried to login and when i select my character and go in the game i make a few steps (or whatever just sitting around its the same outcome) and it goes disconnecting me from the server. I tried different servers it works fine so i doubt its the client problem

**Comment by InhumanGM** [comment]
Are you still experiencing this issue?
