### ISSUE TITLE
Nightbane skeletons immune to magic damage

### ISSUE THREAD

**Issue by Kraggenlord** [SunstriderEmu/BugTracker#2478]
**Describe the bug**
The adds during P2 of Nightbane are immune to magic damage, making them borderline impossible to kill.

**To Reproduce**
1. Pull Nightbane.
2. Watch skeletons spawn. 
3. Wipe.

*Expected behavior**
They're not supposed to be immune to magic damage.

**Comment by Jerrythemagicdog** [comment]
They're supposed to be immune to magic damage other than Holy:
https://wowwiki.fandom.com/wiki/Nightbane_(boss)

> Patch 2.0.10 (2007-03-06): Nightbane's Restless Skeletons are now immune to non-holy magical damage.

Although it was reverted by Blizzard rather quickly we're sticking to using it (for now).

**Comment by babno** [comment]
@Jerrythemagicdog rather quickly is an understatement. It was hotfixed 3 days later. THREE. DAYS. Do you think that might be because it was unintentional and shouldn't be that way? https://wow.gamepedia.com/Nightbane_(tactics)
