### ISSUE TITLE
Naturalist Bite from Slave Pens

### ISSUE THREAD

**Issue by Bugadin** [SunstriderEmu/BugTracker#2479]
You CAN'T interact with Naturalist Bite so you can't complete the quest or recieve the nature buff. I also suppose that the wave event that occurs after release him doesnt work either. I have already tried 2 times. 

Thank you

**Comment by Jerrythemagicdog** [comment]
Is that tried in heroic or in normal?

**Comment by whispersz** [comment]
Just did a heroic SP now and i can confirm that i received the buff

**Comment by ageerik** [comment]
still not working, some mobs spawn after like 3 min but nothing happens

**Comment by Jerrythemagicdog** [comment]
No longer the case, thanks for the report.
