### ISSUE TITLE
[Shaman] Totem of Wrath not stacking

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#2480]
**Describe the bug**
Multiple totems of Wrath do not stack

**Expected behavior**
Totem of Wrath is supposed to be fully stackable

**Additional context**
https://github.com/SunstriderEmu/BugTracker/issues/1641

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by TheMoneyHater** [comment]
This still not fixed?

**Comment by Aeded** [comment]
Still not fixed, still relevant.

**Comment by Gloominator** [comment]
fix it already?

**Comment by Jerrythemagicdog** [comment]
Fixed with next update, thanks.
