### ISSUE TITLE
Blocks are being calculated before armor. This means blocks cause more damage from bosses than regular hits.

### ISSUE THREAD

**Issue by Shroomie111** [SunstriderEmu/BugTracker#2481]
**Describe the bug**

Blocks are calculated before armor. This should not be the case. For example: if a melee attack hits for 500 before armor, and a tank has 50% damage reduction and 200 block value. Normal attacks will hit for about 250 (after armor). Blocks are being calculated before armor, therefore blocked attacks will hit the tank for about 300 damage (greater than the 250 normal hits).

**To Reproduce**

1. Equip a shield and get attacked
2. Note the damage taken by normal attacks
3. Notice that on blocks, the total damage taken plus blocked damage equals the pre-armor total.

**Expected behavior**

Damage is blocked after armor reduction is calculated.

**Screenshots/videos**

![image](https://user-images.githubusercontent.com/62512462/77254085-3ff04980-6c35-11ea-99e8-fd42cbe48be0.png)
![image](https://user-images.githubusercontent.com/62512462/77254100-5ac2be00-6c35-11ea-802b-7cde0a610859.png)
Here's my combat log from tanking a mob in Netherstorm. First image shows blocked attacks, hitting for 473, 433, and 466 before adding block value of 233. Next image shows normal hits, hitting for 243, 299, and 283. This is very easy to reproduce and I can't believe no one has found this bug yet.

**Additional context**

http://web.archive.org/web/20070219045243/http://wowwiki.com/Block
"Damage reduced by blocking is calculated after other damage reducing factors, such as armor, which has the effect of increasing the effectiveness of blocking."

In its current state, blocks cause MORE damage to be taken from raid bosses due to ignoring armor reduction. This is a huge nerf to ALL TANKS, and changes tank itemization significantly if not fixed!!

**Comment by Bugadin** [comment]
Please, consider this

**Comment by sposobniy** [comment]
already been reported https://github.com/SunstriderEmu/BugTracker/issues/1843

**Comment by kelno** [comment]
Fixed with next update
