### ISSUE TITLE
Charge causing player to disconnect in Arena

### ISSUE THREAD

**Issue by Tappijalka** [SunstriderEmu/BugTracker#2483]
**Describe the bug**
<- You get disconnect when you CHARGE people that isn't on same ground as you, if you chase someone that jumped down from blade's edge arena and you charge them mid air you disconnect!
And the same on ruins of lorderan, if you charge people on the tomb you disconnect. >

Spell: https://wowhead.com?spell=100

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Fixed a long time ago, thanks for the issue.
