### ISSUE TITLE
[Spell] Ritual of Refreshment: Refreshment table doesn't fill up to 80 mana biscuits

### ISSUE THREAD

**Issue by Ibuprofeno** [SunstriderEmu/BugTracker#2484]
**Describe the bug**
Currently you can only get 20 Mana Biscuits for each click, so if you have more than 60 you won't get any more.
https://tbcdb.com/?spell=43987
https://tbcdb.com/?object=186812

**To Reproduce**

1. Get 80 mana biscuits.
2. Delete up to 19.
3. Click table again.
4. An error message pops up stating you can't have any more of those.

**Expected behavior**
It should get you max Mana biscuits (80)

**Comment by Ironjudgment** [comment]
Can confirm

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2994
