### ISSUE TITLE
Teleporter to Gnomeregan broken

### ISSUE THREAD

**Issue by Clamborghini** [SunstriderEmu/BugTracker#2485]
**Describe the bug**

Unable to teleport from Booty Bay to Gnomeregan with the Goblin Transponder and teleport pad

**To Reproduce**

1. Complete Gnomer-Gooooooone! for Goblin Transponder
2. Step on teleporter pad (no teleport)
3. Tried to log off and try again, no teleport
4. Tried to throw away Transponder and receive new one, could not receive new Transponder from Scooty

Item: https://classic.wowhead.com/item=9173/goblin-transponder
Quest: https://classic.wowhead.com/quest=2843/gnomer-gooooone

**Expected behavior**

If you complete the quest, then step on the pad with the transponder in your inventory, you should be teleported to Gnomeregan.
**Screenshots/videos**

**Additional context**

**Comment by EL100** [comment]
Confirmed. Nothing happens.
![InkedWoWScrnShot_041020_102820_LI](https://user-images.githubusercontent.com/61659496/78998575-e930ae00-7b16-11ea-8fbe-835b8fa66718.jpg)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed some time ago.
