### ISSUE TITLE
Bugged fall damage

### ISSUE THREAD

**Issue by mayday2013** [SunstriderEmu/BugTracker#2486]
**Describe the bug**
Sometimes after dismounting a flying mount you die.

**To Reproduce**

1. Fly up.
2. Dismount using any ability
3. Die from fall dmg.

**Expected behavior**
Correct calculations depending on distance to the ground.

**Screenshots/videos**
https://youtu.be/SAaWqYdBRsE

**Additional context**
You can just decrease fall damage by 99%.

**Comment by mayday2013** [comment]
still not fixed. happens always when you land on sloping ground

**Comment by Noirnine** [comment]
Still not fixed. I've died 3 times now flying around mining Warmaul Hill. If you land you'll die. If you click off the mount and try to fall you die.

**Comment by mayday2013** [comment]
I don't know how to reproduce it, but it happens when you fly towards the ground and dismount at 10y height for a node or gas cloud, etc.

You expect 0-200 damage from hitting the ground, but it kills you. 

I have a yt vid linked in the post, and it always looks like it. 


Have dismounted 20-30 times today and not dcs. Seems you did something - thanks!

**Comment by z5n** [comment]
unable to reproduce
