### ISSUE TITLE
NPC Succubus minions not attacking, set on passive?

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2489]
Any mob in the game that has a Succubus, the pet will not attack you when you engage the master, the succubus sits there and does not even do white hits, and will disappear after their master is dead. Will only engage if you attack the Succubus itself.

Example: Bloodsail Warlocks in Stranglethorn Vale.

**Comment by Jerrythemagicdog** [comment]
Resolved after latest changes to how owner & summon aggro are handled. Thanks for the issue!
