### ISSUE TITLE
Hunter's "revive pet" slightly bugged

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2490]
If you go out of range of where your pet died, you are unable to use 'revive pet', it says you have no pet.

You have to use 'call pet' first in order to bring up your dead pet's frame, only then can you use 'revive pet'

**Comment by mayday2013** [comment]
This is fine, because your pet is autodismissed when on long distance.

**Comment by Godmatik** [comment]
Yes it should be auto-dismissed when far away, but when reviving a pet, it doesn't matter if it is dismissed or not, it should just revive it without having to call the pet's dead body.
