### ISSUE TITLE
Hunter Talent "Focused Fire"

### ISSUE THREAD

**Issue by dedalo91** [SunstriderEmu/BugTracker#2491]
Describe the bug: Talent isn't working on the 2% improved dmg, still need to verify the improved crit on Kill Command

To Reproduce: on the character panel you can't see the x102% multiplier that you should see

Spell: https://tbcdb.com/?spell=35030

**Comment by Ironjudgment** [comment]
Well, I am too lazy to test this on my hunter but since you brought it up, you should do some testing eh?

**Comment by dedalo91** [comment]
As you can see from the screenshot, I have the talent, but next to the damage (when you mouseover it) there is no x102% green multiplier. Right now I can't reset my talent to show the difference (I'm low level, I'll upload a screenshot asap).

Could alsa be a graphical bug, that is, the talent is working properly but doesn't show up. But that's a little hard to test.
Hope this is enough to show, yesterday I was to lazy to do a screenshot, sorry.

![WoWScrnShot_032320_112818](https://user-images.githubusercontent.com/2235451/77307450-8e671c00-6cf9-11ea-9f57-798d6015e68d.jpg)

**Comment by The-Eyeful** [comment]
**Video Showing Working 2% Bonus**
https://streamable.com/ly6yb

Seems to be working fine (otuside testing KC crit modifier). I start with 313-315 (314 avg) with no pet, then summon my pet and go to 319-312 (320 avg). 2% of 314 is ~6, added, is 320. Works fine.
