### ISSUE TITLE
Weather beaten journal not in game

### ISSUE THREAD

**Issue by nhthor** [SunstriderEmu/BugTracker#2493]
**Describe the bug**

I've been fishing the floating wreckages and any outland pool, according to wowhead, it should be a 5% drop from an iron bound trunk and 43% from a curious crate. I've caught over 100 iron bound trunks, some of them were empty and some curious crates were empty and I believe they are carrying the item but if it hasn't been programmed they are showing as empty.
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Godmatik** [comment]
Was not added until patch 2.3

**Comment by InhumanGM** [comment]
> Was not added until patch 2.3

This is correct.
