### ISSUE TITLE
paladin seal of justice

### ISSUE THREAD

**Issue by mondotek619** [SunstriderEmu/BugTracker#2494]
**Describe the bug**
I apply the spell on some enemy target , for explemple when enemy is mounted and the spell no do nothing , the enemy still running at their normal speed

https://pt.classic.wowhead.com/spell=20164/selo-da-justi%C3%A7a

the enemy can run from me and he shouldnt

**Comment by NeonicSupersonic** [comment]
try using max rank

**Comment by mchayes** [comment]
Both ranks are identical, also; isn't that a wotlk feature?(guesswork)

**Comment by NeonicSupersonic** [comment]
Except rank 1 doesnt limit movement speed of a target, it just prevents npcs from fleeting. You know - like a thing you actually reported by mistake.
