### ISSUE TITLE
Warrior second wind procs on resists. 

### ISSUE THREAD

**Issue by oldspices** [SunstriderEmu/BugTracker#2497]
Warrior second wind talent is proccing on resists.

no stun= no buff.

**Comment by kelno** [comment]
Jerry:
"Effects that have two components (like stun and damage or root and damage for example Intercept or Frost Nova) when resisted in half by a mechanic (for example Surefooted) still cause to proc spells that require the resisted effect to go through (for example Second Wind, warrior's talent)
so in this case: Warrior has Second Wind talent and Surefooted enchant on boots, he resists the snare component of Frost Nova but takes damage and it procs Second Wind"

**Comment by kelno** [comment]
Blaze:
"Second Wind warrior talent is triggered by stuns/snares that are resisted, spells that do damage ontop of having an effect like - Frost Nova resisted by Surefooted, Intercept Stun, druid Pounce being resisted by stun resist talent/meta gem stuff like that"
https://www.youtube.com/watch?v=iP1XHdnwPsE

**Comment by kelno** [comment]
Second Wind spell id: 29838

**Comment by kelno** [comment]
Fixed with next update
