### ISSUE TITLE
To much health

### ISSUE THREAD

**Issue by Nim92** [SunstriderEmu/BugTracker#2498]
**Describe the bug**

The centipaar Worker mob have way to much health compared to the other mobs in the area of The Noxious Lair. It have around 7k health while all other mobs have around 2.5k hp.
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Sheikthecatman** [comment]
Thanks for the report!
For future cases, please add more information and maybe some links!
