### ISSUE TITLE
PallyPower Addon 

### ISSUE THREAD

**Issue by Ironjudgment** [SunstriderEmu/BugTracker#2499]
**Describe the bug**
Popular paladin addon which allows all paladins in raid to manage blessings does not synchronize correctly on endless.dc

I am writing this as a bug report since the exact same version of the addon has worked on all p.servers I've played on. This includes Atlantiss/Sunwell/Warmane.l 

**To Reproduce**
1. Get 2 or more paladins in the raid.
2. Try to set up blessings.
3. Others try to 'refresh' and in most cases does nothing.

**Expected behavior**
Once anyone with raid assist sets up PallyPower, others should get the updated allocation after pressing refresh.

[PallyPower.zip](https://github.com/SunstriderEmu/BugTracker/files/4368291/PallyPower.zip)

**Comment by Ibuprofeno** [comment]
Can confirm. It also doesn't track your own blessings when you are the only paladin the group/raid.

**Comment by beraus** [comment]
Works for me (PallyPower was the single one active addon).
