### ISSUE TITLE
Rocket Boots Xtreme

### ISSUE THREAD

**Issue by jonkarlsen93** [SunstriderEmu/BugTracker#2500]
Rocket Boots Xtreme malfunction 100% of the time.

You also drop the flag when you use rocket boots in WSG and EoTS.

**Comment by jonkarlsen93** [comment]
How they are supposed to work: https://www.youtube.com/watch?v=UIEHbNDOYII

**Comment by Ibuprofeno** [comment]
In 2.4 Rocket boots were changed to make players drop flags.
https://wowwiki.fandom.com/wiki/Patch_2.4.0
 [Rocket Boots Xtreme] now have all their stat points allocated toward Attack Power, and will no longer have Stamina.
[Rocket Boots Xtreme] and [Rocket Boots Xtreme Lite] will cause players to drop a PvP flag if used while carrying one (Warsong Gulch, Eye of the Storm, and Zangarmarsh).

**Comment by jonkarlsen93** [comment]
> 
> 
> In 2.4 Rocket boots were changed to make players drop flags.
> https://wowwiki.fandom.com/wiki/Patch_2.4.0
> 
> [Rocket Boots Xtreme] and [Rocket Boots Xtreme Lite] will cause players to drop a PvP flag if used while carrying one (Warsong Gulch, Eye of the Storm, and Zangarmarsh).

Yeah but they are not supposed to malfunction 100% of the time.

**Comment by Ibuprofeno** [comment]
> 
> 
> > In 2.4 Rocket boots were changed to make players drop flags.
> > https://wowwiki.fandom.com/wiki/Patch_2.4.0
> > [Rocket Boots Xtreme] and [Rocket Boots Xtreme Lite] will cause players to drop a PvP flag if used while carrying one (Warsong Gulch, Eye of the Storm, and Zangarmarsh).
> 
> Yeah but they are not supposed to malfunction 100% of the time.

I never said so)

**Comment by Jerrythemagicdog** [comment]
Fixed a long time ago, thanks for the issue.
