### ISSUE TITLE
[Quest] Summoning Yor in Mana-Tombs

### ISSUE THREAD

**Issue by Elwun** [SunstriderEmu/BugTracker#2501]
**Describe the bug**

After finishing the questline for NPC Commander Ameer ( A Mission of Mercy ) you can continue getting items Ethereum Prisoner I.Ds but can't turn them in because the questline finishes.

**To Reproduce**

1. You need to hit Honored reputation with "The Consortium" 
2.  Finish Commander Ameer's first questline A Mission of Mercy
3. Continue getting Ethereum Prisoner I.Ds  but can't turn in because no quest to turn in
4. Quest Ethereum Secrets won't start

Item: https://wowhead.com?item=31957
Quest: https://wowhead.com?quest=10971

**Expected behavior**

At honored reputation and finishing the first "A Mission of Mercy" you should start being able to turn in Ethereum Prisioner I.D. Tags  to continue the chain / reputation but we can't 

**Screenshots/videos**

**Additional context**

Without this we can only do quests/mana tombs/insignia turn ins for Rep with The Consortium and can't summon Yor in the Mana Tombs instance

**Comment by Gbbc** [comment]
Can confirm this is indeed not working.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
