### ISSUE TITLE
Dragon Breath & Cone of Cold on same CD

### ISSUE THREAD

**Issue by VSteeph** [SunstriderEmu/BugTracker#2502]
**Describe the bug**
When you use Dragon Breath or Cone of Cold, the other spell is now on CD for the duration of the spell Cooldown.  

Dragon Breath : 20s of cooldown
Cone of Cold : 10s of cooldown

If you use, Dragon Breath, both spell will be on a 20s cooldown and if you use Cone of cold, both spell will be on a 10s cooldown : 
![image](https://user-images.githubusercontent.com/58773222/77310900-6bd80180-6cff-11ea-849d-180138bc6833.png)
https://i.imgur.com/BKq78Uw.png

![image](https://user-images.githubusercontent.com/58773222/77310936-7abeb400-6cff-11ea-9e95-954ce31b444a.png)

**To Reproduce**
1) Spec Fire to take Dragon Breath
2) Use Cone of cold or Dragon Breath

https://www.wowhead.com/spell=31661/dragons-breath
https://www.wowhead.com/spell=120/cone-of-cold

**Expected behavior**
Each spell is not related, they are supposed to be on a different cooldown.

**Comment by Ibuprofeno** [comment]
Not a bug.

**Comment by mayday2013** [comment]
For 10 years these spells have been on the same CD.
