### ISSUE TITLE
Rogue poison quest bugged.

### ISSUE THREAD

**Issue by Tetillas** [SunstriderEmu/BugTracker#2503]
Ive started level 20 quest for rogue poisons in the Horde.

After going to north barrens where the elite is and you use your flare and salute, I´ve realised that I couldnt finished the quest by myself and I´ve abandoned it (I threw away the flare and the whistle too)

Now that I got enough level, I want to do the quest again, but apparently, there is no NPC that allows me to start the quest again or get the flare and the whistle, so no option I got left to start it again or continue it.

Thank you for your time

**Comment by LSD7** [comment]
lol

**Comment by InhumanGM** [comment]
Issue has been resubmitted with more detail - #3370.
