### ISSUE TITLE
The Absent Minded Prospector Quest bug

### ISSUE THREAD

**Issue by nightbe** [SunstriderEmu/BugTracker#2504]
**Describe the bug**

I cant submit the quest, as it says i dont have the "Mysterious Fossil. but it is in my bag.
**To Reproduce**

Quest: https://classic.wowhead.com/quest=741/the-absent-minded-prospector

**Expected behavior**

i expected that i could deliver this quest. 

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/62551685/77320450-dc3b4e80-6d10-11ea-923c-d865bea95d1f.png)

**Additional context**

**Comment by beraus** [comment]
This issue should be fixed now.
