### ISSUE TITLE
Chest in dungeon

### ISSUE THREAD

**Issue by elnium123** [SunstriderEmu/BugTracker#2505]
They are 2 chest lock in mechanar and on auchenai & setekh too on retail server, but they are not spawn here, can you do something mby?

https://www.youtube.com/watch?v=ShTe7aEwlOo&t=256s
https://www.youtube.com/watch?v=ld-NtQwWvG4&t=218s
https://www.youtube.com/watch?v=-upbUldmt38

Thx for mby fix that.

**Comment by elnium123** [comment]
?????????

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/1681
