### ISSUE TITLE
Engineering Gadgets lacking drops when destroyed

### ISSUE THREAD

**Issue by Malozar** [SunstriderEmu/BugTracker#2506]
**Describe the bug**
One of the engineering gadgets, called [Advanced Target Dummy] - Isnt producing any loot when it is broken. I have not checked the other engineering gadgets, but they are supposed to drop loot when they expire. (Furthermore, its supposed to last 15 seconds, but i had to get mobs to actually kill it, for it to expire)

I crafted 20 of these in hopes of getting some Fused Wired, but found out that no loot was given at all.

**To Reproduce**
1. Cast [Advanced Target Dummy], or probably any of the other mentioned items below, onto the ground
2. Observe it never it expiring if no mobs kill it - and see it drop nothing if destroyed by mobs

Based on my experience from Vanilla, and from my research of comments on WoWhead:
https://classic.wowhead.com/item=4392/advanced-target-dummy
https://classic.wowhead.com/item=4366/target-dummy
https://classic.wowhead.com/item=16023/masterwork-target-dummy
https://classic.wowhead.com/item=4391/compact-harvest-reaper-kit

**Expected behavior**
I expected the item to expire after the 15 seconds, and for it to be lootable with engineering materials.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2403
