### ISSUE TITLE
Hunter Revive Pet doesn't bring back Pet's Micro-Bar

### ISSUE THREAD

**Issue by Falathrin** [SunstriderEmu/BugTracker#2511]
As the title suggests, if your pet dies and you revive it, its micro-bar won't pop up making it more difficult to manage.
The only way to fix this is to dismiss and resummon your pet after you revive it.

I see this being a problem in Arenas.

**Comment by bisquiit** [comment]
yes this is true. but you can Press CTRL + 1  or 2 and it will come back.

**Comment by beraus** [comment]
Should be fixed now.
