### ISSUE TITLE
Trading lockpicked lockboxes

### ISSUE THREAD

**Issue by AgreeableNZ** [SunstriderEmu/BugTracker#2512]
**Describe the bug**
When unlocking lockboxes we must trade them currently and 90% of the time when they're traded back to the customer from the rogue they're empty.

I've tested this my self by opening my own lockboxes that i received from drops and they generally allways contain items.

**Reproduce **

Trade locked box to rogue, Rogue picks and trades back lockbox will likely be empty

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed after next update (0905b554a0bdc3122b6f969900c6823b649523a9)
