### ISSUE TITLE
[Mob] Dark Iron Bombardier respawns 2 seconds after dying.

### ISSUE THREAD

**Issue by Syfte-oss** [SunstriderEmu/BugTracker#2514]
**Describe the bug**
While trying to complete the first step in the quest The Thandol Span" I had to fight my way past Dark Iron Bombardiers and other named Dark Iron dwarves that were not connected to the quest.  One particular Dark Iron Bombardier on the east side would persistently respawn exactly 2 seconds after dying.  The only dwarf I killed before this one was on the stairs coming down and its respawn timer appeared to be normal.
In the linked video note that there was another dwarf standing behind the mounted gun that is beside the affected dwarf.  I had killed that other dwarf before I began recording and its timer also seems to be working properly.  Again, this was on the east side of the bridge.  I did not try to enter on the west side.

**To Reproduce**

1. Kill the dwarf.
2. Blink.
3. Kill it again.

Mob: https://classic.wowhead.com/npc=4062/dark-iron-bombardier
Quest: https://classic.wowhead.com/quest=631/the-thandol-span (technically unrelated but here it is anyway)

**Expected behavior**
A normal respawn time.

**Screenshots/videos**
https://youtu.be/GDHadxRRrco

**Comment by Sheikthecatman** [comment]
Thank you for the report! 
The dwarves will have a longer time out now-
