### ISSUE TITLE
TBC Patterns

### ISSUE THREAD

**Issue by europoor** [SunstriderEmu/BugTracker#2515]
TBC patterns that are needed for leveling professions are on a super long cool down (20-48hrs). They are never available and are ruining the game for many people seeing as how there isn’t enough patterns to go around and way too many players need these to skill.

The solution would be to make these patterns on a shorter cooldown (30mins or less) and make them bound on pick up. A few examples of this would be the heavy knothide leather and large prismatic shard patterns. I know that this solution seems rather obvious and probably makes too much sense, but this is what your playerbase wants.

**Comment by NeonicSupersonic** [comment]
The solution would be to stop whining about core game mechanics and get gud

**Comment by Ironjudgment** [comment]
By 'get gud' you mean to camp an NPC and quickly log in when there's DC? Yeah... people need to get gud.

QoL changes are good for a 13 year old game where EVERYTHING is already known and explained. Furthermore, if you don't have anything constructive to say it's better to not say anything.

**Comment by europoor** [comment]
People love to say “get gud” and complain about other people wanting QOL changes. We’re playing on a x5 server, having tbc patterns on a 30min cd and having them bop would change literally nothing.

**Comment by Sheikthecatman** [comment]
To further investigate this issue (as well as #2526 )
We will require more information on which patterns have long restock timers.

**Comment by europoor** [comment]
Primal Might Pattern, Heavy Knothide Leather, Runed Eternium Rod, Large Prismatic Shard, Superior Wizard Oil, Superior Mana oil. I'll try and check which other ones as well.

**Comment by Sheikthecatman** [comment]
As of a recent update, most recipes no longer have a limited quantity.
