### ISSUE TITLE
[Class] Hunter Pet Losing Health On Each Summon

### ISSUE THREAD

**Issue by Cooties-cc** [SunstriderEmu/BugTracker#2516]
**Describe the bug**

When resummoning a pet, either from mount-dismount or dismiss-call pet, the pet loses a portion of their health. The health lost does scale with talents (Endurance Training) and the players stamina (pets receive 30% of hunters total stamina). 

**_Currently, I have only tested this on a level 70 hunter, with a level 69 pet. I have also tested between Endurance Training, and no Endurance Training. This has not yet been tested with a much lower level pet, lower level hunter, or a combination of those two._** 

_Update_ : _I have now additionally tested with a level 41 hyena, level 62 wolf, 61 ravager, and a 63 warpstalker. Of those 4, only the ravager has lost health on resummon._ 

**To Reproduce**

Have the ability to dismiss pet, or mount, and repeat those spells. Each time, the pet will lose hp scaled to the hunters talents/stm when they are resummoned. 

_Update_: _Have so far only seen Ravagers losing health. Hyenas, wolves, warpstalkers so far have not shown health loss._ 

**Expected behavior**

When resummoned, the hunter's pet should be summoned with the last snapshot of health it had before it was desummoned. If it was desummoned with 100% total hp, it should be resummoned with 100% hp. 

**Screenshots/videos**
_69 Ravager (my main pet)_ **-hp lost**
https://streamable.com/3r2ex
_Wolf_ 
https://streamable.com/8ckot
_Ravager_ **-hp lost**
https://streamable.com/186zg
_Hyena_
https://streamable.com/i1clh
_Warpstalker_
https://streamable.com/zmsl1

**Additional context**

I didn't notice this problem until the last recent patch, which was 3/20/2020. That's not to say that's when it started, but it was noticeable when farming and having to mount-dismount frequently.

**Comment by mayday2013** [comment]
Happens from time to time.

**Comment by z5n** [comment]
issue has since been fixed, thank you!
