### ISSUE TITLE
Mage (Optional) quest chain for robe, low level

### ISSUE THREAD

**Issue by Guldurak** [SunstriderEmu/BugTracker#2517]
**Describe the bug**
After talking to Anastasia Hartwell in Undercity, she instructs you to the Apothecarium, to the alchemist shop, to deal with some rift disturbances. You pick up the scroll and the cases but when used, the scroll reveals nothing, thus resulting in failing to complete the quest.

Quest: https://wowhead.com?quest=https://classic.wowhead.com/quest=1959/report-to-anastasia#comments

**Comment by InhumanGM** [comment]
Expected Behavior:
When the scroll is used, it should reveal a Rift Spawn that has to be damaged to a certain health threshold. Once that threshold is reached, the Rift Spawn will then be stunned, and using an item from the quest, it then must be captured.

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago, thanks.
