### ISSUE TITLE
[Ability] Swing timers not resetting for incapacitate effects

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#2518]
**Describe the bug**
When a target is successfully gouge incapacitated, upon coming out they will INSTANTLY auto attack. Swing timer should be at 0 upon leaving gouge state. I am also curious if this affects more abilities. I only happened to notice this quirk with gouge in my own testing.

**To Reproduce**

1. Have 1 HP and blind a mob.
2. Gouge the Mob
3a. Wait for gouge to expire and watch as you instantly die when gouge wears off or;
3b. Cast sinister strike to break gouge state and you also instantly die when gouge fades from damage taken

Spell: https://db.endless.gg/?spell=38764

**Expected behavior**

Swing timers not resetting to 0 as incapactitate effects fade, or are removed from combat damage. I am wondering now if this is affecting more abilities too than just gouge.

**Screenshots/videos**

**Additional context**

**Comment by blblblaz** [comment]
first time I hear it should work this way. Do you have a source? I can't seem to find anything about this

**Comment by kelno** [comment]
That make sense to me gameplay wise, but same would need proof here

**Comment by kmayberry91** [comment]
I am taking a break from the server due to the amount of bots allowed to farm and sell things here
