### ISSUE TITLE
Leggings of beast mastery not working

### ISSUE THREAD

**Issue by hopeless-hue** [SunstriderEmu/BugTracker#2519]
**Describe the bug**
<Leggings of beast mastery is not the pet's attack power by 70, armor by 490 and Stamina by 52.>

**To Reproduce**
<equipping and unequipping the Leggings of Beast Mastery>

Item: https://tbc-twinhead.twinstar.cz/?item=31328
Spell: https://tbc-twinhead.twinstar.cz/?spell=38297

**Expected behavior**
<Increases your pet's attack power by 70, armor by 490 and Stamina by 52, in addition to the buffs from the hunter>

**Comment by blblblaz** [comment]
you are correct, thanks for the report!

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed after next server update.
