### ISSUE TITLE
Improved Mark of the Wild

### ISSUE THREAD

**Issue by Myszol1** [SunstriderEmu/BugTracker#2521]
**Describe the bug**
It's working with mark of the wild, and don't with gift of the wild.

**To Reproduce**

1. Always happens

Spell: https://wowhead.com?spell=17055/improved-mark-of-the-wild

**Expected behavior**

I expected it to work properly.
**Screenshots/videos**

**Additional context**

It just don't work, should be easy to fix

**Comment by blblblaz** [comment]
could not reproduce,works fine for me, are you sure you're using the max rank of Gift of the Wild?

**Comment by Myszol1** [comment]
Ye closed i'm stupid. Book: Gift of the Wild III exists. Sorry for your trouble
