### ISSUE TITLE
Scryer's Bloodgem. Xi'ri's Gift

### ISSUE THREAD

**Issue by apafeoz** [SunstriderEmu/BugTracker#2522]
триньки  Scryer's Bloodgem. Xi'ri's Gift . у них одно кд при использовании одной трини ,чтоб юзнуть вторую надо ждать не 15 сек а 1мин 30 сек ..

**Comment by artieau** [comment]
Can you please raise an issue in English for us to review?

**Comment by xEnvoy** [comment]
Thrills Scryer's Bloodgem. Xi'ri's Gift. they have one cd when using one trini, to use the second one must wait not 15 seconds but 1min 30 seconds
