### ISSUE TITLE
Can't revive myself

### ISSUE THREAD

**Issue by BigBratan** [SunstriderEmu/BugTracker#2523]
Hello Support,

yesterday I was inside Shadow Labyrinth normal. We wiped and the groupmembers left. I left the game because it was pretty late already. Today I logged in as a ghost and walked into Shadow Labyrinth. Instead of being alive inside the instance after the Loading Screen I still was a ghost. 

I know I can revive myself at the Spirit Healer but this shouldn't be the way. I get 10 min debuff and rep costs for nothing...

Is this a comon bug?

Greetings 
Icedout

**Comment by Sheikthecatman** [comment]
Please refer to in-game tickets about issues such as these!

**Comment by AWIDIUS** [comment]
Happened to me aswell, seems like something in core or like that. Wasn't unable to ressurect upon my corpse after I died in BB.
