### ISSUE TITLE
Quest: Vorsha the Lasher, unable to put of flame

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#2524]
**Describe the bug**
For the quest Vorsha the Lasher, after escorting NPC to the flame, you should be able to click on the flame to put it out. However, the flame is not usable/clickable. The escort quest cannot proceed.

**To Reproduce**
1. Take quest
2. Escort the NPC to the flame.
3. ...

https://classic.wowhead.com/quest=6641/vorsha-the-lasher

**Expected behavior**
After step 2, the flame should be clickable to be put out.

**Comment by joewoess** [comment]
I can confirm, brazier is not interactable.

**Comment by Sheikthecatman** [comment]
I just tested the quest and it worked. Try clearing your cache as it might stop you from interacting with the gameobject and would be a local issue if that's the case.
