### ISSUE TITLE
vendor patterns

### ISSUE THREAD

**Issue by okokokokokok1** [SunstriderEmu/BugTracker#2526]
vendor patterns are on 24 respawn and camped by 5+ level 1 afk dual boxers. decrease respawn to 30 min on em so people aren't fucked over by like 5 no lifers

**Comment by Godmatik** [comment]
Confirmed ... Primal Might recipe is especially really bad,

**Comment by Sheikthecatman** [comment]
To further investigate this issue (as well as #2515 )
We will require more information on which patterns have long restock timers.

**Comment by Godmatik** [comment]
Primal Might
Heavy Knothide Leather

These are the two most prominent that come to mind. The only time it gets restocked is after a server crash, and then several players on level 1s sit on the NPC and buy it up with a macro once the server is back up, eventually reselling on the AH for 100-150g+

**Comment by Bugadin** [comment]
Keep crying, turning the server into custom server. Recipes are fine, stop changing stuff and deal with real problems like faction balance.

**Comment by Sheikthecatman** [comment]
As of a recent update, most recipes no longer have a limited quantity.
