### ISSUE TITLE
ZF bug

### ISSUE THREAD

**Issue by helcon93** [SunstriderEmu/BugTracker#2528]
**Describe the bug**

In ZF its only possilbe to loot around 50% of the mobs in graveyard. 
Also is the spell "Blizzard" supposed to make significent less damage depending of the number of mobs in your pull? 
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Godmatik** [comment]
Your question on Blizzard - the answer is yes.
TBC introduced an AoE cap, if you are AoEing more than 10 mobs, than the amount of damage your spells do is reduced.

**Comment by helcon93** [comment]
> Your question on Blizzard - the answer is yes.
> TBC introduced an AoE cap, if you are AoEing more than 10 mobs, than the amount of damage your spells do is reduced.

Okey.
What about the look bug?
