### ISSUE TITLE
Problem me gold

### ISSUE THREAD

**Issue by Nicolas20201** [SunstriderEmu/BugTracker#2529]
Hello, I wanted to ask you a question, a few moments ago I had 190 gold or close to that I do not remember, I sold a layer at the auction for 89 gold and when I reconnected, I ran out of gold, I did not do anything illegal, I do not know why I They took away my gold, I had a hard time putting it together, please I need to know what happened to the gold. Thank you very much, this server is great and very good.

**Comment by yokitomimoko** [comment]
I'm in the same situation as him, my game was disconnected and when I went back in I was out of money, I hope you can help me, thanks.

**Comment by Godmatik** [comment]
you guys will likely have to open GM tickets and have them look into it.
