### ISSUE TITLE
Pet Talent Cobra Reflexes not reducing pet damage per hit

### ISSUE THREAD

**Issue by slightlyrandom** [SunstriderEmu/BugTracker#2530]
**Description**
The Hunter pet talent Cobra Reflexes has the following tooltip:
"Attack speed increased by 30%, but damage done is reduced."
The Attack speed increase is applied correctly, but the damage done is not reduced.

**To Reproduce**
1. On a hunter with a pet, reset pet talents and note pet damage on pet info sheet.
2. Teach pet Cobra Reflexes, note DPS and attack speed goes up on sheet, but damage per hit stays the same.

https://db.endless.gg/?spell=25077

**Expected behavior**
Pet damage done per hit should go down by something like 30%

**Comment by Ironjudgment** [comment]
Have you checked if it is actaully the same? It could just be a visual.

**Comment by slightlyrandom** [comment]
I did a small-scale test, sent my pet against the same kind and level of mob in the same zone with only difference under my control being whether it had Cobra Reflexes or not, and had it hit ~100 times.

Recount showed the average damage per hit to be close enough to be considered identical, maybe 1% different. Certainly not the expected 20-30%.

**Comment by Jerrythemagicdog** [comment]
Fixed around the time of the report, thanks.
