### ISSUE TITLE
Trial of the Lake druid seal form timed quest bugged

### ISSUE THREAD

**Issue by Mysticmojo** [SunstriderEmu/BugTracker#2532]
I couldn't use the Shrine Bauble quest item in Shrine of Remulos.

I tried clicking on it in several locations in the Shrine of Remulos. It made the green glowing circle around my character and made the thundering noises, but it didn't complete. Which means I can't complete the quest for my druid seal form.

**Comment by beraus** [comment]
You need to get deep in the tree, but it's doable.
