### ISSUE TITLE
[Race] Troll Regen Passive. As a troll hunter, I noticed the regeneration passive does not work while in combat as intended.

### ISSUE THREAD

**Issue by mustpotatoes** [SunstriderEmu/BugTracker#2533]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by blblblaz** [comment]
could not reproduce, the racial works fine for me, would like more information/footage if possible
