### ISSUE TITLE
BG: warlock pet respawn

### ISSUE THREAD

**Issue by iluminatix** [SunstriderEmu/BugTracker#2538]
if my pet was killed, it wont respawn when with me, and i have to resummon it again. 

when i do summon it while i have preparation buff from res, it will still cost shards, would be convinient and fair if it didnt. not sure about what is blizzlike - ive seen servers with both solutions.

best regards

**Comment by Jerrythemagicdog** [comment]
Fixed a long time ago, thanks for the issue.
