### ISSUE TITLE
Fearing lowlevel mobs

### ISSUE THREAD

**Issue by iluminatix** [SunstriderEmu/BugTracker#2539]
when i try to fear low level mobs, i get error message "target is too low level" same as if i try to buff a lowlevel with say lifebloom or something simular that is to powerful to their level.

cant be right that locks have to downrank their fear to fear lower level targets in pve.

NB: this dont apply to aoe fears.

**Comment by blblblaz** [comment]
that does seem wrong yes. as far as I know these rules should only apply to "Friendly" buffs, as in if low level player gets buffed by lvl 70 player with full rank spell,  the buff automatically gets scaled down to the appropriate level based on the target's level. not sure how should this work with spells that are trained at lvl 70 or so and have only 1 rank like Lifebloom and Prayer of Mending, but yes these rules should not affect offensive spells most definitely

**Comment by z5n** [comment]
unable to reproduce, issue has likely since been fixed
