### ISSUE TITLE
Bug: Khorium lockbox disappear after opened

### ISSUE THREAD

**Issue by sventhelegend** [SunstriderEmu/BugTracker#2540]
**Describe the bug**
I traded a Khorium lockbox to a rogue and then he traded it back to me after he unlocked it. When i clicked to open it in my inventory it just disappeared.

Item: https://wowhead.com?item=31952/khorium-lockbox

**Comment by blblblaz** [comment]
there is a known issue with lockboxes - it's not guaranteed that you're going to get an item when one gets opened. i suspect that's what happened in your case, your lockbox had no items inside so it just disappeared when you opened it.

**Comment by beraus** [comment]
This should be fixed now.
