### ISSUE TITLE
Warpwood pod not interactable.

### ISSUE THREAD

**Issue by mamer123** [SunstriderEmu/BugTracker#2541]
**Describe the bug**
Warpwood bug, a plant from Dire Maul east, is there, inside instance, spawned, even when hovered over it sparkes, there is little mechanism and it says the name of plant, however you cannot click on it, nothing happens, whereas you should be able to open it like container and loot it, or there should be random poison or root effect beforehand.

**To Reproduce**

I dont much understand this:
1. Click on Warpwood Pod
2. Should either let you open it like container, or sprawl posion or roots, it is random effect.
3. Nothing happens.

wowhead doesn't have any useful information
https://classic.wowhead.com/object=179526/warpwood-pod
https://wow.gamepedia.com/Warpwood_Pod

**Expected behavior**
When you approach it: 
1. Chance to cast Entangling roots/Sprawl poison
2. Open it and loot its contents

**Screenshots/videos**
https://ibb.co/svdvMY5

**Additional context**
This is mandatory for Cooking skill leveling, without this cannot progress past 275.

**Comment by Thiazole** [comment]
Still not resolved, i can confirm

**Comment by z5n** [comment]
thanks for the issue! fixed with next restart
