### ISSUE TITLE
Combat lasts 6 seconds after healing a party member in PVE

### ISSUE THREAD

**Issue by flowwaves** [SunstriderEmu/BugTracker#2542]
Instead combat should drop instantly like it does when you are doing DPS or tanking, but it seems on endless that when healing, cleansing (and maybe even buffing, not tested) a friendly target while in combat, if the enemy NPC dies shortly thereafter the healer/buffer/cleanser does not drop combat instantly like it should. 

this is really annoying in dungeons especially when you need to drink between pulls.

**Comment by blblblaz** [comment]
thanks for the report

**Comment by kelno** [comment]
Thanks, fixed with next update!
Every support spell was affected here.
