### ISSUE TITLE
'Consecration' Spell Animation Issue

### ISSUE THREAD

**Issue by Wyrmfire123** [SunstriderEmu/BugTracker#2543]
The paladin skill 'Consecration' shows the correct animation on cast, and begins doing the damage the skill calculates for, but the cracked earth part of the skill is not visible like it was in TBC originally. 

In this first photo, you can see the skill being used properly.
![WoWScrnShot_032520_124816](https://user-images.githubusercontent.com/62665852/77568860-4aaa1900-6e97-11ea-863b-a1877a7701dd.jpg)

In this shot, you see the skill start to do damage correctly in the combat log.
![WoWScrnShot_032520_124903](https://user-images.githubusercontent.com/62665852/77568862-4bdb4600-6e97-11ea-9932-a9d7f28c2d47.jpg)

However what you do not see is the signature consecrated earth underneath the paladin. As evidence by this part of this video: https://youtu.be/oGuFZBMXmKs?t=7079

This could translate to being a problem whenever a paladin is tanking, and consecration is one of the main sources of generating threat in packs of mobs. If you can't see the outline of the consecrated ground, it's hard to know exactly where you must stand to ensure that all the mobs are inside of that radius.

**Comment by Ironjudgment** [comment]
I don't see this problem during my guild raids. Consecrations visible: https://youtu.be/uiolUl42sTA?t=688

**Comment by Wyrmfire123** [comment]
> I don't see this problem during my guild raids. Visible consecration: https://youtu.be/uiolUl42sTA?t=688

I looked into it further and was able to resolve it within my own game's settings. Something got turned off somehow that I never turn off/down.

Thanks for bringing it to my attention!
