### ISSUE TITLE
(NOGGENFOGGER) Impossible to mount up using the Skeleton Costume by NF elixir.

### ISSUE THREAD

**Issue by MrChooser** [SunstriderEmu/BugTracker#2545]
Hello again.
I found that you cant mount up after using the skeleton magic from NF elixir.
It only says "You're in shapeshift form" when you try to mount,
NF elixir ain't a shapeshift, its just a magic buff.
Fix it please !!
We have a lot of NF lovers !!

**Comment by blblblaz** [comment]
Patch 5.0.4 (28-August-2012): Players may now use mounts while under the skeleton effect.

What we have is correct, you can't mount up in "Skeleton" form. However there is a workaround you can do which is using Noggenfogger Elixir, becoming a skeleton, then using Savory Deviate Delight, becoming a pirate/ninja, mounting up, then cancelling the pirate/ninja form and now you're a mounted skeleton!
