### ISSUE TITLE
Pet ability Cower does not work.

### ISSUE THREAD

**Issue by Skuzzlez** [SunstriderEmu/BugTracker#2546]
**Describe the bug**
1. Hunter pets do WAY too much threat on this server (I hope this can be investigated as well as to why, but I'm not sure). As a compensatory measure I decided to tame a pet with Cower Rank 7 (Grovestalker Lynx in BEM) and to my surprise - He has the ability but doesn't actually ever cast it, wheteher on autocast or not. He can't use the ability. I'd imagine this will probably be the case for other ranks too. It just gives the error message: Invalid Target.

**To Reproduce**
1. Tame Grovestalker Lynx in Blade's Edge Mountains
2.  Attempt to use Cower Rank 7 both manually cast and auto-cast.
3. Enjoy your "Invalid Target" error message.

Cower Rank 7: https://tbc-twinhead.twinstar.cz/?spell=27048
Grovestalker Lynx: https://www.wowhead.com/npc=21022/grovestalker-lynx

**Expected behavior**
Cower should be able to be cast - as far as i'm aware both manually and on autocast. It can't be used in either situation.

**Additional context**
As mentioned - I investigated this because hunter pets are doing WAY too much threat - literally out aggro-ing fully geared main tanks with windfury in raids occasionally. Please investigate this too.

**Comment by blblblaz** [comment]
thanks for the report, there is indeed an error "Invalid Target" when pet uses Cower.

About hunter pets doing too much threat - that should go into a separate issue with more information including video footage with a Threat Meter addon enabled if possible

**Comment by kelno** [comment]
Thanks!
Fixed with next update
