### ISSUE TITLE
Pet Abilities will not learn, despite using ability 100s of times.

### ISSUE THREAD

**Issue by Skuzzlez** [SunstriderEmu/BugTracker#2547]
**Describe the bug**
After taming a Dire Raven in Blade's Edge Mountains with the highest ranks of Dive and Screech, I am unable to learn the abilities permanently to my character, despite having used both abilities now potentially hundreds of times. This process should usually be VERY quick, if not almost instant.

**To Reproduce**

1. Tame Dire Raven in Blade's Edge Mountains
2. Use Dive Rank 3 and Screech Rank 5 repeatedly.
3. 

Dire Raven: https://www.wowhead.com/npc=21042/dire-raven
Screech Rank 5: https://tbc-twinhead.twinstar.cz/?spell=27051
Dive Rank 3: https://tbc-twinhead.twinstar.cz/?spell=23148

**Expected behavior**
The hunter should learn these skills, and others, almost immediately - within a few uses usually.

**Comment by lukas155** [comment]
I believe this is a specific issue with the Dire Raven pet, not in general. I was trying to learn Dive myself yesterday using a Dire raven, refused to learn, then tamed another pet from HFP and instantly learnt the spell.

**Comment by Skuzzlez** [comment]
To the above, definitely not. I've been attempting to train Dive rank 3 even more today. Tamed the Kaliris in HFP to no avail. And the Shadowwing Owls in SMV who also have it with no luck. Something is definitely wrong with multiple pets.

**Comment by Skuzzlez** [comment]
Finally just got it from a Shadowwing Owl to my surprise. But yeah, it shouldn't take this long.

**Comment by bisquiit** [comment]
am trying this out for few days now to get dive rank 3 to no luck with different pets now willing to try with shadowwing owl...

**Comment by kelno** [comment]
Not applicable anymore with our new pet talent system
