### ISSUE TITLE
Incendicite Ore in Thelgan Rock, Wetlands.

### ISSUE THREAD

**Issue by europoor** [SunstriderEmu/BugTracker#2548]
Incendicite veins are supposed to be fast spawning due to them being part of a quest, and should spawn in a cave called Thelgan Rock in the Wetlands. This is currently not the case (:

Here is a link of the mineral veins and their respawn time state on there as well 
https://tbc-twinhead.twinstar.cz/?object=1610

**Comment by InhumanGM** [comment]
Upon visiting the aforementioned cave, I can see that the veins do indeed spawn.
