### ISSUE TITLE
[dual spec] Buffs from a spec remain after switching talents

### ISSUE THREAD

**Issue by Ibuprofeno** [SunstriderEmu/BugTracker#2551]
**Describe the bug**
Buffs remain when changing talents through dual spec. Particularly strong for some classes.

**To Reproduce**

1. Get any talented buff. IE: Demonic Sacrifice, Combustion, Divine Spirit
2. Change to another spec without said talent.
3. The buff will remain at full effect.

**Expected behavior**
ALL self buffs should be removed when switching specs. This prevents improved buffs (ie: imp paladin buffs) from remaining.

**Comment by blblblaz** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2572
