### ISSUE TITLE
Pattern: Runecloth Gloves missing at Qia

### ISSUE THREAD

**Issue by winex93** [SunstriderEmu/BugTracker#2552]
**To Reproduce**

1. Go to the Qia (crea 42277)
2. Check her patters
3. Notice that Pattern: Runecloth Gloves is missing

Qia: https://classic.wowhead.com/npc=11189/qia
Pattern: Runecloth Gloves: https://classic.wowhead.com/item=14481/pattern-runecloth-gloves

**Screenshots/videos**

Page 1: http://prntscr.com/rmxm7d
Page 2: http://prntscr.com/rmxm4r
Page 3: http://prntscr.com/rmxlx9
Page 4: http://prntscr.com/rmxm0d

**Comment by tactivity** [comment]
This is not a bug. As of 2.0.1 Runecloth Gloves can be trained at the Tailoring trainer whilst in Vanilla they were only available in Everlook, sold by Qia in a limited quantity.

**Comment by winex93** [comment]
Thanks.
