### ISSUE TITLE
Limited item buys respawns.

### ISSUE THREAD

**Issue by Draggeth** [SunstriderEmu/BugTracker#2553]
People buying out Limited items from vendor since they have a high respawn time, then they post them in Ah for 200+ gold. All high end profession Patterns/Recipes are like this from Primal Might, enchanting, knothide leather...there are other but can;t think of them at top of my head.

https://wowhead.com?item=25720/pattern-heavy-knothide-leather
https://www.wowhead.com/item=23574/recipe-transmute-primal-might

For a fix, reducing the restock time on vendors should resolve this

**Comment by Draggeth** [comment]
![lul](https://user-images.githubusercontent.com/62690260/77660614-8ef4f200-6f47-11ea-8344-01e97d66e97a.JPG)

**Comment by blblblaz** [comment]
the restock time of all patterns has been greatly reduced with the most recent server restart.
please reply here if the issue still persists!
