### ISSUE TITLE
Horde can't get into Gnomeregan

### ISSUE THREAD

**Issue by Lorivel** [SunstriderEmu/BugTracker#2554]
**Describe the bug**
As a horde player i can't get into Gnomeregan with the use of teleport in Booty Bay.

**To Reproduce**
1. Take two quests in Ogrimmar from two goblins in north-east part of tent-city. (second becomes available only after taking the first)
2. Speak with engineer in Booty Bay, wait a little, speak again, recive Goblin Transponder for teleport.
3. Try to step into teleport.

Quest: https://classic.wowhead.com/quest=2843/gnomer-gooooone

**Expected behavior**
The usuall path is to take two quests in the Ogrimmar wich will lead you to Booty Bay, where you have to speak with engineer near teleporter, he will give you special rod (Goblin Transponder) wich will allow you to use teleporter to get into Gnomeregan.
I did all steps, recived a Goblin Transponder, engineer have nothing more to say but i can't interract with teleporter in any way possible - it can't be activated and walking inside it don't trigger teleport.

**Comment by blblblaz** [comment]
thanks for the report!

**Comment by Lorivel** [comment]
Update: walked to Gnomeregan by main entrance and checked NPC goblin Sprok near teleporter on the other end - he is hostile for some reason, while he had to be friendly.

**Comment by EL100** [comment]
Confirmed. Related to this other issue: https://github.com/SunstriderEmu/BugTracker/issues/2485

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed some time ago.
