### ISSUE TITLE
Omen is not working at all

### ISSUE THREAD

**Issue by darknessangelo** [SunstriderEmu/BugTracker#2556]
Omen addon is not working. It shows only mine threat. Even if everyone in party/raid has the same version. DTM v1.7 is working normally.

**Comment by Godmatik** [comment]
Everyone in your party/raid need to use combat log fixer addon if you want to use Omen on any TBC server.

**Comment by darknessangelo** [comment]
everyone is and yet still the same result :/
If you got any working combination please let me know.

**Comment by Godmatik** [comment]
I would recommend Diamond Threat Meter, as you indicated above, it's always been more reliable on TBC clients.

**Comment by blblblaz** [comment]
Thanks for the report, the issue will be fixed with the next server update
