### ISSUE TITLE
Gold guild sellers 

### ISSUE THREAD

**Issue by shrift1** [SunstriderEmu/BugTracker#2557]
GOLD SELLERS 
![WoWScrnShot_032620_204847](https://user-images.githubusercontent.com/31934397/77690284-5a168880-6fa3-11ea-90c4-d1be85b80d0f.jpg)
![WoWScrnShot_032620_204827](https://user-images.githubusercontent.com/31934397/77690298-5daa0f80-6fa3-11ea-8f1c-68b0196ee9de.jpg)

**Comment by Sheikthecatman** [comment]
Thanks!
We would appreciate in-game tickets regarding these gold seller guilds.
