### ISSUE TITLE
[Quest - Nagrand] Stealing from Thieves unable to complete

### ISSUE THREAD

**Issue by tthierolf** [SunstriderEmu/BugTracker#2558]
**Describe the bug**
Unable to complete Stealing from Thieves when talking to Gezhe with the required 10 [Oshu'gun Crystal Fragment] in inventory. NPC shows a yellow ? icon however the Continue button is disabled.

**To Reproduce**
1. Acquire 10 [Oshu'gun Crystal Fragment]
2. Go to Gezhe in Nagrand
3. Attempt to turn in the quest

Item: https://www.wowhead.com/item=25416/oshugun-crystal-fragment
Quest: https://www.wowhead.com/quest=9882/stealing-from-thieves
NPC : https://www.wowhead.com/npc=18265/gezhe

**Expected behavior**
Quest should be completable with the required items in the player's inventory.

**Screenshots/videos**
![WoWScrnShot_032620_155441](https://user-images.githubusercontent.com/10607520/77690719-283cfc00-6f7a-11ea-8109-03ac333797f8.jpg)

**Additional context**
Ran into the exact same issue with https://www.wowhead.com/quest=9914/a-head-full-of-ivory and needed a GM to complete the quest for me.

**Comment by Godmatik** [comment]
If your rep is friendly or higher, you won't be able to turn it in.

**Comment by blblblaz** [comment]
This quest is only available at neutral reputation with the Consortium.

from wow-wiki - in the screenshot you are clearly friendly with The Consortium

About https://www.wowhead.com/quest=9914/a-head-full-of-ivory I believe that's a general issue that we're having, not specific to that quest
