### ISSUE TITLE
Low lvl instances camera bug

### ISSUE THREAD

**Issue by shrift1** [SunstriderEmu/BugTracker#2560]
![WoWScrnShot_032520_215539](https://user-images.githubusercontent.com/31934397/77701535-d9618780-6fb6-11ea-9d40-d6e70b6874d5.jpg)
This is happening in some low level instances that are made like in caves 
RFK in one example

**Comment by shrift1** [comment]
Usually happens when you go up with your mouse

**Comment by Takaminara** [comment]
This has always happened on official servers aswell, even on classic now.
RFK in particular.

**Comment by artieau** [comment]
This is a graphical/asset issue with the game created by Blizzard - not a bug with this server.
