### ISSUE TITLE
Gruul trash bug

### ISSUE THREAD

**Issue by tactivity** [SunstriderEmu/BugTracker#2562]
The trash mobs that are in front of Gruuls room respawned while we were killing Gruul mid fight and after a shatter a player was thrown towards the gate which is closed during which in turn made the 2 priests aggro and somehow they managed to get through the closed gate and started killing the whole raid. I don't have a screenshot nor did we stream the boss fight. I don't know if anybody else experienced this as I can see no reports of that sort.

**Comment by blblblaz** [comment]
yeah there is indeed an issue there, thanks for the report. we have fixed it already, they will now not spawn while the boss is engaged. the fix will be live in the next server restart, thanks for the report!
