### ISSUE TITLE
Paladin Tier 4 set bonus not working

### ISSUE THREAD

**Issue by Gavrilovsky** [SunstriderEmu/BugTracker#2563]
I must report a problem with non-working set bonus. As as Holy pala i won two pieces of Tier 4 set. Bonus for wearing two sets of Tier 4 for healing spec says: Increases amount of healed by Judgement of Light by 20. Without this bonus, Judgement of Light heals for 95 per hit. With bonus, it should heal for 115. But it doesn't. It still heals for 95 for some reason. The screenshot below shows the problem:
![image](https://user-images.githubusercontent.com/62728560/77707966-fe5df680-6fc6-11ea-893e-5b3b72cf6fe2.png)

As you can see, the set is on, but it isnt working, because it still heals for 95, instead of 115. Now , ill show you description of the spell, telling that it heals for 95 regularly. Bonus should increase it by 20, but it doesnt. 
![image](https://user-images.githubusercontent.com/62728560/77708065-4e3cbd80-6fc7-11ea-8ace-92baf196ee2e.png)

So, with bonus, it should heal for 115. And it isn't. So please, GMs, fix this if it is possibe. Thank you!

**Comment by blblblaz** [comment]
you are correct, thanks for the report

**Comment by beraus** [comment]
Fixed in https://github.com/SunstriderEmu/BugTracker/issues/3571
