### ISSUE TITLE
Herobs not showing in Minimap

### ISSUE THREAD

**Issue by qetsohukare** [SunstriderEmu/BugTracker#2564]
My ingame name is Byca and i can't see the Herbalism nods in the minimap.
Even when i get close, they don't flash like they used to.

**Comment by Godmatik** [comment]
Sounds like a client problem or addon interference

**Comment by blblblaz** [comment]
need more details if possible, cannot reproduce, they flash for me and show up on my minimap on the live server right now.

**Comment by qetsohukare** [comment]
I found the bugg, when you move from one northren place to the other in blade edge, the item that you have placed to find on minimap resets to nothing

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
