### ISSUE TITLE
Fishing - empty loot window

### ISSUE THREAD

**Issue by blacktouff** [SunstriderEmu/BugTracker#2565]
you can have empty window when fishing (happened for me in Azshara and fellwood

**To Reproduce**

1. Go to any fishing zone
2. Fish 20-30 times, you will have at least once an empty loot windows who will open

**Expected behavior**
Lootbox, when they appear during fishing, should never be empty

**Screenshots/videos**

https://ibb.co/vm3gbxz
https://ibb.co/WvsLFZ6
https://ibb.co/Y7LCW29

**Additional context**

**Comment by z5n** [comment]
unable to reproduce
