### ISSUE TITLE
Deadwood Ritual Totem

### ISSUE THREAD

**Issue by Erlenkeel** [SunstriderEmu/BugTracker#2566]
Deadwood Ritual Totem with drop rate approx 3% can be dropped only for 1 party member, this item starting quest for good exp. Please fix it up and make it looteable for all party members.

**Comment by Godmatik** [comment]
In addition, the quest NPC you turn it into inside the cave isn't present.

**Comment by Erlenkeel** [comment]
You must have curtain reputation to turn it up, neutral or friendly. Worked for me 2 quest starting items

**Comment by Godmatik** [comment]
I was friendly, it's just the person you turn it into wasn't at his normal spot. This was a few days ago and I haven't checked since then since I moved on to Outland, so maybe it was fixed.

**Comment by Jerrythemagicdog** [comment]
Thanks, increased the drop rate and reduced respawn timer on the quest giver.
