### ISSUE TITLE
Primal Mooncloth Set bonus doesn't work

### ISSUE THREAD

**Issue by o-hN** [SunstriderEmu/BugTracker#2567]
Primal Mooncloth set bonus doesn't work.  If I re-equip one of the set items, it works for about 10 seconds and then goes away.

(3) Set: Allow 5% of your Mana regeneration to continue while casting.
https://tbcdb.com/?itemset=554

Right after re-equipping (works here):
![WoWScrnShot_032620_210244](https://user-images.githubusercontent.com/62734802/77720706-efb31780-6fa5-11ea-8bed-36ec6a5d678f.jpg)

After standing around for ~10 seconds:
![WoWScrnShot_032620_210259](https://user-images.githubusercontent.com/62734802/77720719-fb064300-6fa5-11ea-85ef-add55b7ff64a.jpg)

Checking the mana manually, during casting I regen 100 mana per tick after re-equipping.
Afterwards I regen 89 mana per tick.

250 * (2/5) = 100 mana per 2s tick
223 * (2/5) = 89 mana per 2s tick

Re-logging and going in/out of combat doesn't fix it.

**Comment by blblblaz** [comment]
exactly the same thing happens in my tests - 10 seconds after re-equipping an item from the set the 5% bonus disappears, thanks for the report

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
