### ISSUE TITLE
 after trying to cancel a bid

### ISSUE THREAD

**Issue by moonkins1r** [SunstriderEmu/BugTracker#2569]
This happens. 
![WoWScrnShot_032720_125138](https://user-images.githubusercontent.com/62745551/77744064-131fa600-702a-11ea-8365-90d9f53840ac.jpg)

**Comment by blblblaz** [comment]
could not reproduce, although other people had this issue so there's clearly something wrong. Need some more information if possible - Did you get the item off the Auction House and then re-list it, did you already list it once and it didn't sell so you listed it again, did someone mail it to you and then you listed it, details like that can be very helpful!
