### ISSUE TITLE
Loot bug ZF

### ISSUE THREAD

**Issue by helcon93** [SunstriderEmu/BugTracker#2570]
**Describe the bug**

When killing the mobs in ZF graveyard is not always lootable. Some are not possible to even click. I´m positive that its a bug and the corpses are not "empty". This I know because The Zombies 9/10 (if not 10/10) should drop gold, but only around 60% of those mobs are possible to loot.
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by helcon93** [comment]
And also, The zombies does NOT drop any silver at all.

**Comment by Worldwide03** [comment]
Similar issue here, as I just cleared ZF with a group on horde and the bosses dropped no bop loot. Only quest items were dropped. I don't think we made any silver either. Saw some BoE's drop, but no regular loot from bosses.

**Comment by z5n** [comment]
thanks, fixed with next update!
