### ISSUE TITLE
Thwart the Dark Conclave (quest bug)

### ISSUE THREAD

**Issue by nottreal** [SunstriderEmu/BugTracker#2571]
Quest have two parts:
1. Kill 4 dark conclave ritualists
2. Use q item provided at summoning ritual place

Part 1 dosent accepts kill counts. tryed couple times with no luck. tryed abadon q, relog, but looks like nothing helps.

Part 2 works fine.

But by talking with some ppls in curent area i managed to complete this q.
Even q says thats u need to kill 4 dark conclave ritualists, u can complete, and deliver q with 0/4 of those kills.

**Comment by Jalapan** [comment]
Same for me bugged and mobs dont count.only 1 player per restart can complete

**Comment by aqes55324** [comment]
same proble fix it please!

**Comment by Jerrythemagicdog** [comment]
You don't need to kill any of the ritualists, you just need to use the quest item in the correct place.
https://www.wowhead.com/quest=10808/thwart-the-dark-conclave#comments:id=26785
https://www.wowhead.com/quest=10808/thwart-the-dark-conclave#comments:id=414487
