### ISSUE TITLE
Combustion/Demonic sacrifice stays if swaping specs

### ISSUE THREAD

**Issue by coder3838** [SunstriderEmu/BugTracker#2572]
**Describe the bug**
On mages and warlocks spells like combustion or demonic sacrifice stay after you swap specs so you can have a frost mage with 5 stacks of combustion and also a fire mage with permanent X amount of combustion so having a mage with 70%+ crit is kind of broken. Affliction warlocks with all talents can also have Demonic sacrifice

**To Reproduce**

Mage case
1. Cast Combustion and get some stacks on random mob, let say 5
2. Change to 2nd spec, doesnt matter if fire/frost/arcane
3. Change back to fire and never use combustion again unless you die to repeat above steps
4. Have fire mage with 5-6-7-8-9 combustion stacks which means max crit

Spell: https://classic.wowhead.com/spell=11129/combustion
https://classic.wowhead.com/spell=18788/demonic-sacrifice

**Expected behavior**
When swaping specs removing buffs that belong to the old spec

**Screenshots/videos**
![5perma comb stacks](https://user-images.githubusercontent.com/62749997/77754919-8cb89380-702c-11ea-9f3d-1f17920b63f9.PNG)
That combustion is there until death, never runs off so its 50% crit extra always

**Comment by blblblaz** [comment]
that is indeed a problem, thanks for the report

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed a long time ago.
