### ISSUE TITLE
Auction House Scanning

### ISSUE THREAD

**Issue by rychersky** [SunstriderEmu/BugTracker#2573]
**Describe the bug**
There's about a 5 second delay before you are able to move to the next page of search results. This makes searching/scanning for things with many pages of listings (such as Netherweave Cloth) really tedious and time-consuming.

**To Reproduce**

Search the auction house. Immediately scroll to the bottom of the results for each page and notice the couple-second-delay before you can go to the next page.

**Expected behavior**
Should be able to immediately access next page.

**Additional context**
This happens with zero addons enabled.

**Comment by AWIDIUS** [comment]
Yep it's anoying and it's intended as far as I know, because scanning pages so fast by multiple players doesn't make server to run anyhow smoothier and lagfree than with delay. It pisses me aswell, but I can't do sh*t 'bout that m8, sorry.

**Comment by kelno** [comment]
Yes this is intended for now as the scanning is actually very heavy for the server. We're still working on performance and will reduce this later on if we see it's impact has been diminished enough.
