### ISSUE TITLE
[feral druid]threat with swipe

### ISSUE THREAD

**Issue by Pingou29** [SunstriderEmu/BugTracker#2574]
**Describe the bug**
Feral swipe don't do the real thrat

1. Cast 3 time swipe on 3 add kz  and Hdruid take the aggo with 2 hots! i playing feral druid on a lot of tbc servers on it's the first time i can't keep 3 adds . All the instance and raid i have less agro on multi target than a war prot it's not normal. Can you check this plz

**Comment by kelno** [comment]
Thanks for reporting.
It seems indeed we don't have any extra bonus threat on swipe, it just does the same as any damage spell right now.
We'll look into this.

**Comment by kelno** [comment]
Fixed with next update

**Comment by Jerrythemagicdog** [comment]
https://wow.gamepedia.com/Patch_2.0.3

[Swipe]" has had its threat bonus multiplier removed.

Removing it then!
