### ISSUE TITLE
Warbringer O'mrogg - Shattered Halls (Heroic)

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2576]
The heroic version of Warbringer hits extremely weak and feels incredibly undertuned, making the fight trivial.

His blast wave/burning weapon also doesn't appear to be scripted, or he isn't using it at all.

https://wowwiki.fandom.com/wiki/Warbringer_O%27mrogg

**Comment by Godmatik** [comment]
Ok we ran SHH again, he did the blast wave but only after he left the center platform and went up the steps toward us after chasing. Maybe we don't see it very often and it isn't bugged.

Regardless, his normal melee attacks feel very untuned.

**Comment by blblblaz** [comment]
thanks for the report! fix will be live with next server update
