### ISSUE TITLE
Escape From Firewing Point

### ISSUE THREAD

**Issue by Pecka69** [SunstriderEmu/BugTracker#2580]
The escort quest in Firewing Point is actualy imposible to coplete due to insane aggro range of the escort NPC and the respawn time of the enemy NPC'S. The escorting NPC can't even get to his position when he just agro everything around

**Comment by Godmatik** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2373

This was supposed to be fixed but apparently was not.

**Comment by nottreal** [comment]
its not just this escort, its all escort quests like that. 1000y agro range.

**Comment by aleksandr073** [comment]
UP this quest insane.

**Comment by Jerrythemagicdog** [comment]
Thanks, we've changed the aggro range and made her react state to be "defensive".
