### ISSUE TITLE
Skywing

### ISSUE THREAD

**Issue by Pecka69** [SunstriderEmu/BugTracker#2581]
https://www.wowhead.com/quest=10898/skywing

Skywing NPC stand in the right place, but doesn't give the quest.

**Comment by blblblaz** [comment]
yeah confirmed, the issue is related to someone failing the quest and Skywing not resetting properly, thanks for the report

**Comment by Macumbafeh** [comment]
+1, wanted to do the quest and couldn't : /

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
