### ISSUE TITLE
[Critical] Resiste or immune stun effects interrupt cast timer 

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#2584]
Describe the bug : 
Stun effects interrunpt  cast even if they were resist or immune (DR) .  

Much critical issue , every  warrior have  Deep Thunder with 11% chanche to stun  (tailent ) , After you already got immune to   stuns  full  (DR) , and fake?  Pummel you still cant heal cos just rng stun procs into immune interrupt casts . 

To Reproduce : 
Use cheap shot against target with full DR 
https://youtu.be/6Tvyo3n317c

**Comment by blblblaz** [comment]
yeah that is a huge problem, thanks a lot for the report

**Comment by kelno** [comment]
Fixed with next update
