### ISSUE TITLE
Outland Mining nodes

### ISSUE THREAD

**Issue by Wallfulls** [SunstriderEmu/BugTracker#2585]
**Describe the bug**
 After the server software move mining nodes in outland have a 3x-4x times longer respwan rate than before.  
You can see this in a cave in Zangramarsh at 74.7, 91.2.  
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment]
Should be fixed now.
