### ISSUE TITLE
Arena bug LOS/Teleporting

### ISSUE THREAD

**Issue by Nomoremana** [SunstriderEmu/BugTracker#2586]
Constant bug in arena that won't let you cast on teammate right on top of you due to los and also teleporting around the map

**Comment by artieau** [comment]
Are you able to share more information here, possibly reproduce steps? @Nomoremana

**Comment by Nomoremana** [comment]
It's not something I'd know how to or attempt to reproduce. It seems very random, as if the server isn't updating where my character is located compared to my screen.
