### ISSUE TITLE
More Basilisk Eyes Quest Bugged

### ISSUE THREAD

**Issue by xEnvoy** [SunstriderEmu/BugTracker#2587]
Turning in Basilisk eyes puts me more towards hated instead of moving it back down to neutral. ive already turned in like 300 or more eyes and didn't even notice would be nice to fix the quest and my rep please thanks.

Quest: https://www.wowhead.com/quest=10025/more-basilisk-eyes

**Expected behavior**
should put my Scryer rep down towards neutral not more towards hated.

**Screenshots/videos**
https://streamable.com/pc6ld

**Additional context**
other people are saying they dont have this issue but I do?

**Comment by Jerrythemagicdog** [comment]
Thanks, the issue was fixed some time ago.
Keep in mind that the reputation will appear as going "further into Hated" on your progress bar but that's expected and is moving you closer towards Neutral.
