### ISSUE TITLE
Skyguard Scouts at Blackwing Landing

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2588]
Three Skyguard scouts just chilling here at Blackwing Landing near Skettis ...  don't think they supposed to be in the game until patch 2.1

![WoWScrnShot_032720_232426](https://user-images.githubusercontent.com/37913400/77814803-7d643500-7082-11ea-87b8-be0dab36b2b9.jpg)

**Comment by beraus** [comment]
crea 78998, 78999, 79000

**Comment by beraus** [comment]
Fixed.
