### ISSUE TITLE
Boiling Blood

### ISSUE THREAD

**Issue by AWIDIUS** [SunstriderEmu/BugTracker#2593]
Droprate of Bleeding Hollow Blood is like 5%, need to be fixed ASAP, players are in need of 12 of these.

**Comment by Sheikthecatman** [comment]
Thanks!
Fixed in [3082cd9ab36995e6acfeb53cb92d2366e8aa13f5](https://github.com/kelno/sunstrider-scripts/commit/3082cd9ab36995e6acfeb53cb92d2366e8aa13f5)
