### ISSUE TITLE
Captain Dirgehammer:  Unable to buy certain items

### ISSUE THREAD

**Issue by Huhtamo** [SunstriderEmu/BugTracker#2595]
Describe the bug

Unable to buy Marshal's Kodohide belt with 10 098 honor and 20 alterac valley marks.
I have over 13k honor and more than 20 Av marks still get the error message " You don't have enough honor points"

To Reproduce

Travel to Stormwind's Old Town.
Enter the Champion's Hall.
Walk upstairs to see Captain Dirgehammer and try to buy above mentioned item.

Below is a picture showing that I have enough honor and marks.

![image](https://user-images.githubusercontent.com/54472650/77828247-edc29300-7122-11ea-8eaf-1712352842b1.png)

**Comment by winex93** [comment]
You need 14280 honor and Arathi Basin marks. Delete your cache and you'll be able to see real prices.
