### ISSUE TITLE
Murmur - Heroic Shadow Labyrinth - Missing abilities

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2596]
Murmur is missing some abilities in heroic mode.

He does not have "Thundering Storm" ability, which deals damage to anyone further than 25 yards from him.

In addition, he is not using his "Magnetic Pull" ability right before his Sonic Boom

Source:
https://wowwiki.fandom.com/wiki/Murmur

>Thundering Storm — Murmur throws sonic bolts at any player further than 25 yards from him, inflicting 2125 to 2875 Nature damage.
>Heroic mode 
>Everyone must position themselves completely within Murmur's raised inner circle to avoid his Thundering Storm—if you're on the raised ledge or outside you will be hit by Thundering Storm.

**Comment by blblblaz** [comment]
that's really weird, he casts Thundering Storm properly on my end, cannot reproduce that one. would like some footage if possible

About Magnetic Pull I can't find a Source saying he should do it exactly before every Sonic Boom so not sure about that one

**Comment by Godmatik** [comment]
I was running far away and not taking damage, but maybe I didn't notice or wasn't running far enough, or something...

I'll close this for now, not sure when I'll be doing Heroic Slabs again to re-test, thanks for checking
