### ISSUE TITLE
Blackfang Tarantulas in Black Morass don't drop loot

### ISSUE THREAD

**Issue by Ricecakebunny** [SunstriderEmu/BugTracker#2597]
Hello,

The Blackfang Tarantulas in Black Morass don't drop any loot. I was trying to farm Netherweb Spider Silk that should have a drop percent of 78.5% from those tarantulas based on your database information (https://db.endless.gg/?npc=18983#drops), but after killing dozens of them, not one spider silk dropped. Not even one piece of any kind of loot dropped from them. Please fix the issue or if it's intended that they don't drop loot, change the information on database. Thank you in advance.

**Comment by Godmatik** [comment]
Devs took away loot form those spiders intentionally.

see: #2225

**Comment by Ricecakebunny** [comment]
And yet, the database information is what it is atm.
