### ISSUE TITLE
Quest items that channel instantly interrupt themselves

### ISSUE THREAD

**Issue by cropcell** [SunstriderEmu/BugTracker#2598]
**Describe the bug**
Happens with both the quests "Bloodgem Crystals" and the warlock quest for ritual of sacrifice where you must channel the quest object and enslave a doomguard.  Both quests result in the item beginning to channel, then a split second later it interrupts itself despite no movement, combat, etc from interrupting.  This issue is stopping both quests from being complete.

**To Reproduce**
Try to complete the one of the above 2 quests.

Quest: "Bloodgem Crystals" and "Suppression"

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2058
