### ISSUE TITLE
[Mage][Spell] Ritual of refreshment.

### ISSUE THREAD

**Issue by juanjosx** [SunstriderEmu/BugTracker#2599]
Describe the bug:

When you are inside any dungeon (i don´t tested in any instance but i guess it is the same) if you use the ritual of refreshment and it get cancelled before complete you can not used it again until you leave the dungeon, even passed the 5 min CD.

To Reproduce
1. Make a party and get in any instance.
2. Cast Ritual of refreshment and cancel it by move.
3. You can not used again because the CD timer never start.

Spell: https://www.wowhead.com/spell=43987/conjure-refreshment-table

Expected behavior:

After being cancelled it should have a 5 min CD.

**Comment by blblblaz** [comment]
confirmed, if Ritual of Refreshment cast doesn't get completed the spell never goes on cooldown until relog

**Comment by Jerrythemagicdog** [comment]
Fixed with next update, thanks,
