### ISSUE TITLE
Quest: The Sacred Flame

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#2600]
**Describe the bug**
The quest item doesn't appear after you click on the flame. Tried twice.

**To Reproduce**
1. Go into the cave to where the flame is. 
2. Click on the flame.
3. The provided quest item "Filled Etched Phial" disappears, but the quest objective item: Cloven Hoof didn't appear.

https://classic.wowhead.com/quest=1197/the-sacred-flame

**Expected behavior**
Quest object item should appear to be looted after step 2.

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in [8932b4d4f98ad335aa7e000bb54e82c28ee92b0f](https://github.com/kelno/sunstrider/commit/8932b4d4f98ad335aa7e000bb54e82c28ee92b0f)
