### ISSUE TITLE
horde xp rate is fake :(

### ISSUE THREAD

**Issue by uryuutbc** [SunstriderEmu/BugTracker#2601]
hi 🗡  im not polemic but on the server site said x5 ally x6 horde xp but is the same x5 for both fix or change and say 5x for all thk

**Comment by blblblaz** [comment]
hey, that's a mistake on our part, thanks for letting us know. after next server restart it will be back to x6. sorry about that!

**Comment by uryuutbc** [comment]
thk a lot my friend will be happy to join horde thk

**Comment by uryuutbc** [comment]
ur a good GM and stuff is real nice server :)
