### ISSUE TITLE
[Rogue] Kidney Shot & Gouge causes mobs to change direction

### ISSUE THREAD

**Issue by hashblaster** [SunstriderEmu/BugTracker#2602]
**Describe the bug**
Kidney shot & gouge will rotate the target 180 degrees on your screen when you use them, and you will have to use 'from behind' abilities from the front.

**To Reproduce**
1. Cheap shot on target X
2. Right as cheap shot is ending, Kidney Shot on target X
3. Watch mob change direction, and watch backstab fizzle.

**Expected behavior**  Kidney shot & gouge should not cause the enemy mob to change direction.

**Screenshots/videos**
https://imgur.com/a/rXG7Fxu

**Comment by blblblaz** [comment]
thanks for the issue, I managed to reproduce it, it seems like it's only visual - even though the mob changes direction it's still technically facing the same way as it did before, so if you kidney shot it while it was facing you and it changes direction you still have to go through it to be able to backstab/mutilate

**Comment by hashblaster** [comment]
It is very annoying when you keep track of multiple targets & what direction they are facing (or appear to be facing)

**Comment by Jerrythemagicdog** [comment]
Fixed a long time ago, thanks for the issue.
