### ISSUE TITLE
[PVP] PVP on elevators & lifts is broken.

### ISSUE THREAD

**Issue by hashblaster** [SunstriderEmu/BugTracker#2603]
**Describe the bug**
If you CC an enemy on an elevator unpredictable things will happen.  Sometimes they will take falling damage, sometimes they will fall thru the elevator, sometimes they will fall off and take 0 damage.  Often times you get 'out of range' bugs when you are on an elevator.  Once in a while, you will get stuck completely and fall thru the map.

Unable to consistently reproduce.

**Comment by z5n** [comment]
closing in favor of #2163
