### ISSUE TITLE
Gorilla bug 

### ISSUE THREAD

**Issue by Mikesmare99** [SunstriderEmu/BugTracker#2605]
**Elder Mistvale Gorilla**
Is near Booty Bay .
The problem is ...you can  hit gorilla with auto atack ...only with spells. if you auto atack you got only misss shots.
Thx

**Comment by InhumanGM** [comment]
Upon attempting to reproduce the issue, I was not able to find any issues. Could you provide more  information that could be used to try to reproduce the issue again?
