### ISSUE TITLE
Healing stream totem #1329 (Was not fixed)

### ISSUE THREAD

**Issue by kraftea** [SunstriderEmu/BugTracker#2606]
**Describe the bug**
Please see bug #1329.  Doesn't seem the +healing co-efficient affects healing stream totem.

**To Reproduce**
Simply put on some +healing gear and cast healing totem. You will see that the base healing does not change.

**Comment by blblblaz** [comment]
that's weird, could not reproduce, works fine for me. if you are spawning a totem and then equipping healing gear the totem's healing isn't going to update, you have to recast the totem after you change gear. also keep in mind it has very low scaling with healing (4.5% according to this table - https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=1492745)

**Comment by kraftea** [comment]
I will see if I can get a video at some point today.  I'll make it brief and include as much detail as possible.

With around 300 to healing I believe I should be getting an extra 14ish per tick if it's 4.5% yeah?  It seems not to change from base value.

I'll update with video asap.

Thanks

**Comment by kraftea** [comment]
Please disregard, yesterday it was only giving me the base +18 every 2 seconds, now i'm getting 34 (which makes sense).  Maybe it had something to do with getting a new rank?  I'm not sure.  Closing
