### ISSUE TITLE
[Quest] Barbecued Buzzard Wings - %n instead of player name in completion msg.

### ISSUE THREAD

**Issue by Syfte-oss** [SunstriderEmu/BugTracker#2607]
**Describe the bug**
The Badlands quest 'Barbecued Buzzard Wings' posts the message, "Rigglefuzz cooks up a batch of spicy hot buzzard wings for $n."

**To Reproduce**
1. Complete the quest.
2. Get your wings.
3. So what if the cook got your name wrong?  We're busy, go away.

Quest: https://classic.wowhead.com/quest=703/barbecued-buzzard-wings

**Expected behavior**
Rigglefuzz cooks up a batch of spicy hot buzzard wings for [player name].

**Screenshots/videos**
https://i.imgur.com/L57MfuS.jpg

**Additional context**
Not enough napkins and the waitress was rude.

**Comment by Sheikthecatman** [comment]
Thanks!
Rigglefuzz will now pronounce your name correctly, hopefully the service will be much better next time!
[a2f658c95a81324f688b99dfce7dccd55f319f96](https://github.com/kelno/sunstrider-scripts/commit/a2f658c95a81324f688b99dfce7dccd55f319f96)
