### ISSUE TITLE
[Tracking] Reagents vendors do not show when tracking reagents vendors.

### ISSUE THREAD

**Issue by Syfte-oss** [SunstriderEmu/BugTracker#2608]
**Describe the bug**
Title says it all.

**To Reproduce**
1. Switch on Reagents tracking.
2. Run around.
3. Give up and Google the vendor's co-ordinates.

I could not find an entry for this on Classic Wowhead.  The closest I got was:
https://wow.gamepedia.com/Tracking

**Expected behavior**
A nice, shiny, golden dot where the vendor is standing.

**Screenshots/videos**
https://i.imgur.com/ewMvkQK.jpg

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago, thanks for the issue.
