### ISSUE TITLE
The Cipher Of Damnation - Grom'Tors Charge

### ISSUE THREAD

**Issue by Folgrum** [SunstriderEmu/BugTracker#2609]
Trying to get the first fragment is stupid.

I spent almost an hour killing nagas to get a key just to open a chest that doesnt contain the quest item. 

If it is this hard to get a key than the chests should be guaranteed to contain the quest item. or make the keys drop more often. One or the other, I shouldn't have to farm that many to have a chance at a key and then have a chance at getting the quest item.

**Comment by Ironjudgment** [comment]
I did this quest yesterday or the day before and the keys dropped from almost every single naga, and the quest item was in the third chest I have had opened.

Perhaps you were in a raid, or just really bad luck?

**Comment by Folgrum** [comment]
Nope, was doing it solo. Took over an hour to complete because I rarely got keys and never got item from chests.

**Comment by Simon-GM** [comment]
I have attempted to reproduce the issue, but without luck.
I had 10x fragments drop from 35 chests, and 9x keys dropping from 35 nagas.
Based on the reproduction, there does not seem to be an issue in this case.

**Comment by DaturoDewitt** [comment]
I'm having the same problem key drops are fine but i opend 20+ chests and counting and just no luck....
Guildmate said he was on the quest for over an hour when we arrived toing it too
