### ISSUE TITLE
I cannot see the duration of spell

### ISSUE THREAD

**Issue by Torcosx** [SunstriderEmu/BugTracker#2613]
**Describe the bug**
I cannot see the duration of a spell when it is from someone else on a competitor. 
For example, when i'm in arena with a rogue, when he bind someone, i see the bind but not the duration of this one ...

So it is very complicate to play in this conditions ...

Thanks,

**Comment by blblblaz** [comment]
hey, that's just how TBC is, the way people usually deal with it is by downloading an addon called "BuffLib", if you and your partner have this addon enabled you will see the durations of your cc spells and such
