### ISSUE TITLE
Lock dungeon

### ISSUE THREAD

**Issue by elnium123** [SunstriderEmu/BugTracker#2614]
I get lock in dungeon without reset any dongeon, just when i leave the dungeon that auto reset so i get stuck all time, can you fix it ? (thats after the fix karazhan reset ID)

**Comment by blblblaz** [comment]
not sure if I understand correctly, you haven't been in the dungeon but you are somehow saved?

**Comment by elnium123** [comment]
When im in dungeon, if i go out then i re goin, thats reset the dungeon

**Comment by elnium123** [comment]
So if you die 5 times you're lock
