### ISSUE TITLE
[Engineering] Gnomish Engineering Items Broken

### ISSUE THREAD

**Issue by hashblaster** [SunstriderEmu/BugTracker#2615]
**Describe the bug** 

Tested not working: Gnomish death ray, gnomish mind control cap, and gnomish battle chicken all seem to be not working.    Death ray & MC cap do nothing, and battle chicken does not properly enrage.

**Comment by blblblaz** [comment]
Battle Chicken works fine on my end, the enrage has a certain chance on hit to proc so it's not going to happen every single time especially if your chicken is low level and misses a lot

however I can clearly see the issue with Gnomish Death Ray and Gnomish Mind Control cap, thanks for the report

**Comment by hashblaster** [comment]
Chicken does enrage, but the damage is not correct.   Even when enraged, he is doing 2 damage non crit, 4 damage crits to a lvl 8 boar.    

https://imgur.com/a/JppL3Fo

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/799

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
