### ISSUE TITLE
Bug reset mouse

### ISSUE THREAD

**Issue by ipotuz** [SunstriderEmu/BugTracker#2618]
**Describe the bug**
Sometimes randomly my mouse stop working and "reset" meaning it goes under my character and reset the view completely.

**To Reproduce**
Happens randomly, in auto run for example that will change direction, in combat I will loose the target as I don't aim in the good direction.

**Expected behavior**
Mouse works normally and do not reset

**Screenshots/videos**
none
**Additional context**
I have the logitech g502

**Comment by Godmatik** [comment]
It's not a bug with the server, but the fact that these old clients can't deal with the new mouse drivers properly.

Some solutions listed here:
https://www.reddit.com/r/wow/comments/9mp41t/can_we_address_the_mouse_cursor_bug_that_exist/

**Comment by blblblaz** [comment]
as far as I know this is a client issue and there is nothing we can do from the server's end
