### ISSUE TITLE
Cenarion War Hippogryph does not have the ground running/walking animations.

### ISSUE THREAD

**Issue by ArisTheGod2** [SunstriderEmu/BugTracker#2620]
**Describe the bug**
Cenarion War Hippogryph does not have the ground running/walking animations.

**To Reproduce**
Use Cenarion War Hippogryph to mount up. Walk or run on the ground.

**Expected behavior**
Cenarion War Hippogryph is supposed to use his legs to walk or run around on the ground. Instead he is just flying at 100% speed or walking speed, at the ground level.

**Screenshots/videos**
https://www.youtube.com/watch?v=5l_ag_TXt4M

watch the first few second of this video to see which is the animation it is supposed to be using at ground level. On Sunstrider, it is NOT using this animation at the ground level.

**Additional context**

**Comment by Jerrythemagicdog** [comment]
This is not something we control, your source is also from a newer expansion.

**Comment by ArisTheGod2** [comment]
@Jerrythemagicdog Just out of curiosity what do you mean you cannot control this?

Also I know it is from a diff expansion but i figured this was trivial enough and it demonstrates my point well.

**Comment by Godmatik** [comment]
In TBC client, the hippogryph never did walk properly, and it wasn't fixed until WotLK
