### ISSUE TITLE
Flamewrought Key - Thrallmar Reputation Honored

### ISSUE THREAD

**Issue by Catarroarmato89** [SunstriderEmu/BugTracker#2621]
Cannot Buy Flamewrought Key from Thrallmar's Quartermaster even if i've turned Honored as write in the key's description. It make it appear buyable but if you try it states "You don't have the required reputation for that item".

**To Reproduce**
1. Being Honored with Thrallmar
2. Go to Quartermaster Urgronn in Thrallmar
3. Try to buy Flamewrought Key

https://www.wowhead.com/item=30637/flamewrought-key
https://www.wowhead.com/npc=17585/quartermaster-urgronn (link not for TBC in order to find the NPC on the map or at least identify it with his code)

**Expected behavior**
The merchant sells the items, as it wrote on items description.

**Screenshots/videos**
![Immagine](https://user-images.githubusercontent.com/62849410/77856102-1ca93980-71f5-11ea-86ca-29050d2b2bb3.jpg)

**Comment by Naebu** [comment]
bc client is on patch 2.4.3 - and with this patch you get it with honored. but ingame we´re a t patch 2.1 i think and there you need reviered for the heroic keys

**Comment by blblblaz** [comment]
I believe this is a cache issue, try restarting your game and clearing your cache folder and it should have Revered Requirement, the thing you see is only visual

**Comment by whispersz** [comment]
It happened to me because i was playing on another server where it was available at honored. After deleting the cache it show properly at revered on this server,
