### ISSUE TITLE
ZF GY

### ISSUE THREAD

**Issue by Wallfulls** [SunstriderEmu/BugTracker#2623]
**Describe the bug**

In Zul Farrak there is a bug where u click on the mounds to spawn zombies You can multi clock to spawn unlimited amount from 1 mound.   there are found in front of witch Doctorzum'rah.
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment]
It should be fixed now.
