### ISSUE TITLE
[Quest] Manaforge Questline Netherstorm

### ISSUE THREAD

**Issue by Nijako** [SunstriderEmu/BugTracker#2624]
**Describe the bug**
After turning in the quest (Aldor) "Naaru Technology" at Manaforge B'naar the following quest
"B'naar Console Transcription" don't show up and I can't continue the questline whilst my party member could take the follow up just fine.

https://www.wowhead.com/quest=10243/naaru-technology
https://www.wowhead.com/quest=10245/bnaar-console-transcription

**Comment by blblblaz** [comment]
yeah, that has happened a few times, not sure what the exact cause is right now, I suggest you make a ticket in-game if you already haven't

**Comment by Nijako** [comment]
That's what I did first and got asked to make a bug report here

**Comment by Jerrythemagicdog** [comment]
Fixed a long time ago.
