### ISSUE TITLE
 [Frankly, It Makes No Sense...] Quest SMV

### ISSUE THREAD

**Issue by bisquiit** [SunstriderEmu/BugTracker#2625]
Hello there the quest  [Frankly, It Makes No Sense...] is SMV is bugged 
1) the respawn timer is huge. (if they respawn at all)
2) If you are any class with pet you wont be able to controll  the scorpion.
for that reson so many people are comlaining its bugged.
can any fix be donne there with the pet?

**Comment by Jerrythemagicdog** [comment]
Fixed a long time ago, Arcano-Scrops have a 30 sec respawn timer now as well.
The issue before was that they were never returning home from the place that the controlling player abandoned them in.
