### ISSUE TITLE
[Hunter] Mend Pet not granting Hunter Combat

### ISSUE THREAD

**Issue by bluemanguy112** [SunstriderEmu/BugTracker#2628]
**Describe the bug**
Applying Mend Pet to an in Combat Pet does not grant the Hunter Combat

**To Reproduce**
Let Pet attack e.g. a Mob/Target-Dummy and use Mend Pet

**Expected behavior**
Like any other Buff to an InCombat Entity the application of the Mend Pet Buff should grant the Hunter Combat (only the application of the Buff and not the Healing 'ticks')

**Comment by blblblaz** [comment]
thanks for the report!

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed after next server update.
