### ISSUE TITLE
[Hunter] Revive Pet only usable when Pet summoned

### ISSUE THREAD

**Issue by bluemanguy112** [SunstriderEmu/BugTracker#2631]
**Describe the bug**
"You do not have a Pet" Error Message when trying to revive a dead Pet whose corpse has despawned. This results in some ridiculous failed Revives due to Pet despawning in the middle of the Revive Pet cast. Currently the Pet's Corpse has to be visible (usually requiring to resummon the dead Pet before being able to resummon).

**To Reproduce**
Let Pet die and run away till its Frame disappears and then attempt to revive it.

**Expected behavior**
The Pet's dead body should not be a requirement for a successful revive Pet; preventing ludicrous situations like the above mentioned one.

**Comment by Balanarr** [comment]
I think this is the actual behavior. Anyone with a hunter on classic to chexk?

**Comment by bluemanguy112** [comment]
https://clips.twitch.tv/FrozenAltruisticHedgehogKappa

Proof^

**Comment by Godmatik** [comment]
It is 100% not intended behavior.

In addition, I think the pet's happiness gets hit a second time when you 'call' the pet to revive it. So basically their happiness is going down as if it died twice in a row.

**Comment by blblblaz** [comment]
that's an annoying one for sure, currently it takes about 1 minute for the pet's corpse to despawn or the hunter running away around 100 yards from the corpse or so, so it's clearly bound to happen in arena sometimes and that's bad

also pet happiness indeed gets reduced when Call Pet is used - that one is also confirmed, thanks for the reports
