### ISSUE TITLE
Paladin resistance aura doesnt stack with other buffs

### ISSUE THREAD

**Issue by Hahabg** [SunstriderEmu/BugTracker#2634]

**Comment by Godmatik** [comment]
Not a bug.

**Comment by blblblaz** [comment]
Note: Player-cast group buffs do not stack. This includes Druid's Mark of the Wild, Paladin's resistance auras, Shaman's resistance totems, Priest's Shadow Protection and Hunter's Aspect of the Wild. Solo buffs, such as Mage Armor and Warlock's Demon Armor, and non-player-cast buffs do stack, however.

from - https://wowwiki.fandom.com/wiki/Resistance_buffs?oldid=1285296
