### ISSUE TITLE
[Hunter] global cooldown not scaling with haste

### ISSUE THREAD

**Issue by ado7e** [SunstriderEmu/BugTracker#2637]
**Describe the bug**

**To Reproduce**
Global cooldown for steady shot is not scaling (at all or not properly ?) With haste effects.
1. Get under haste effect
2. Try to cast steady with speed quicker than 1.5 without clipping the auto

Https://www.wowhead.com/spell=61304/global-cooldown

**Expected behavior**
Based on active haste effects gcd should scale Down to 1.0sec,.but its staying on 1.5sec

**Screenshots/videos**
https://youtu.be/_gAQjX1oK6E
@2:51 you can see hunter getting under haste effect w nich is getting him down to 1.2 aa speed, but still he is able to cast steady without clipping the autoshot.

**Comment by blblblaz** [comment]
going to need a source on this one, in the example you showed he gets a dragonspine trophy proc, his auto shot becomes 1.2 and because of that he doesn't even get a steady shot off

**Comment by Highdps** [comment]
Check DST tab, dst+hawk proc u still should be able to cast auto-steady 1:1 according to retail spreadsheet

**Comment by Juliettesqt** [comment]
Hi,
Hunter's GCDs doesn't scale with Haste.
It will be 1.5s no matter the procs.

**Comment by TheMoneyHater** [comment]
![image](https://user-images.githubusercontent.com/11985642/87110792-261c5600-c268-11ea-8dce-1f149d20d330.png)
You can just cancel this issue @Highdps ur showing evidence against urself
