### ISSUE TITLE
"Sale Pending" mails

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2638]
Everytime an auction is sold, a separate 'sale pending' mail is accompanied by it. 

These are not necessary since payouts are sent instantly to the mailbox and there is no one hour delay.

**Comment by wiglefish** [comment]
+1 to removing those, quite annoying and this doesnt even happen on Classic which is based on older version of the game.

**Comment by z5n** [comment]
thanks for the request, this was removed a few months after this issue was created.
