### ISSUE TITLE
Nodes/Herbs Bug and Spawn rate

### ISSUE THREAD

**Issue by nottreal** [SunstriderEmu/BugTracker#2640]
![Untitled](https://user-images.githubusercontent.com/62747393/77965506-08d70380-72d9-11ea-8312-b2220f4dd761.png)
I managed to do a picture where u can see on picture 1 that radar detecting nodes when using fly from town to town, but on picture 2 when standing other side, u can see there is no nodes.

A week ago when i started to play this server i mentioned that sometimes nodes disapearing when u geting close to it, same persist today.
Second thing that some nodes cant handle fast fly mount speed, they are not fast enought to apear on the screen ans radar. But this looks fine with herbs.

While lvling i managed to find much more nodes/herbs than last 2days when farming with fast fly mount, it looks like someting been changed, as most of the time in whole route (10min+-) i cant find any single herb or node in Nagrand/Netherstorm/Shadowmoon. 

For example in like 1h of farm (Shadowmoon) i managed to find 3 adamantite +2 Rich adamantite nodes and 2 Nightmare Vines.

ty.

**Comment by nottreal** [comment]
updated. After todays midnight server crash herbs/nodes start spam and whole zone was full with them. looks like server uptime effects their respawn time

**Comment by beraus** [comment]
Should be fixed now.
