### ISSUE TITLE
Flametongue / Frostbrand not benefiting from talent Elemental Fury

### ISSUE THREAD

**Issue by Felynda** [SunstriderEmu/BugTracker#2643]
**Describe the bug**
Flametongue / Frostbrand not benefiting from talent Elemental Fury.
This talent in should make spell crits deal double damage instead of 150%.
Currently damage from weapon imbues is not affected:
![image](https://user-images.githubusercontent.com/45050227/77964828-12179e80-72e0-11ea-9d63-48a364de97e8.png)

**Expected behavior**
Damage being double on a crit

**Additional context**
Proof:
http://urbad.net/blue/eu/394130313-TBC_Enhancement_Shaman_FAQ

**Comment by blblblaz** [comment]
thanks for the report and the source!

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with '32ed559dc241b1a4523c3d8b34c0a4efe5cb1b2d'. Live with next update.
