### ISSUE TITLE
Mana Feed not affected by Drain Mana

### ISSUE THREAD

**Issue by steak-house** [SunstriderEmu/BugTracker#2644]
**Describe the bug**
The tier 6 Demonology Warlock Talent Mana Feed does not restore Mana to the Demon through Drain Mana.

**To Reproduce**

1. Cast Drain Mana on a target while having at least one talent point in Mana Feed and a summoned demon
2. Observe that the demon's mana is not restored

https://wowwiki.fandom.com/wiki/Mana_Feed

**Expected behavior**

When gaining Mana through Drain Mana, your Demon should receive mana as well from the Drain Mana talent

**Additional context**
My guess is that the game doesn't detect Drain Mana as a ressource gain since the floating combat text doesn't show any mana gain, despite your mana being restored. Due to this, the Talent doesn't detect a mana gain to replicate on the demon.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
