### ISSUE TITLE
[Rogue] Master of Deception 5/5 not work

### ISSUE THREAD

**Issue by Kass1a** [SunstriderEmu/BugTracker#2648]
**Describe the bug**
Mobs same lvl see stealth rogue in 8+ range if have Master of Deception 5/5 . 

**To Reproduce**
1. Teach Master of Deception 5/5
2. Go mob same lvl in 8-10 range and he see you in stealth

**Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page**
I see this problem starting with 15 lvl.  All mobs in game 15-70 lvl

**Expected behavior**
I play in wow too much years!  If have full talent Master of Deception mob same lvl should not SEE YOU in 1-3 range!

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2397
