### ISSUE TITLE
Tank toy - funny and dangerous grieving tool.

### ISSUE THREAD

**Issue by slavotyk** [SunstriderEmu/BugTracker#2649]
**Describe the bug**

After Terror forest quest making receive quest reward - tank toy with 10 charges. Used it first in in Shattrah city. - shoot Adal and notice that he got dmg (24 dmg). After that - moved to human start location - kill 5 players with this toy. Durothar was visited as well. 

I think its a grief tool. 

But Im not sure that its a bug, not a feature. 

**To Reproduce**

1. Complete quest in Terrokar Forest "Missing Friends"
2. Use Battered Steam Tonk Controller toy on someone
3. Try to kill it

Item: https://www.wowhead.com/item=31666/battered-steam-tonk-controller
Quest: https://www.wowhead.com/quest=10852/missing-friends

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by InhumanGM** [comment]
The only ability it has that can do damage to players is [Drop Mine](https://tbc-twinhead.twinstar.cz/?spell=25024) (_ID: 25024_), and that spell should only do damage against [other tonks](https://imgur.com/a/F4RNZj0).

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
