### ISSUE TITLE
Force of Nature

### ISSUE THREAD

**Issue by imetik** [SunstriderEmu/BugTracker#2650]
**Describe the bug**
Force of Nature (Balance Druid 41 point talent) does not spawn Treants at the casting circle location. Instead, it spawns them next to the player every time.

**To Reproduce**
1. Cast Force of Nature to bring up the green targeting circle
2. Choose a location away from the player and finish casting the spell.
3. The Treants will spawn next to the player, instead of the location you selected

Spell: https://db.endless.gg/?spell=33831

**Expected behavior**
The Treants should spawn near the location that the player chooses with the target circle.

**Screenshots/videos**
https://gyazo.com/eaefd089fb34c8aa6abfad1dd7967df6

**Comment by blblblaz** [comment]
thanks for the report and the video!

**Comment by z5n** [comment]
issue has since been fixed!
