### ISSUE TITLE
Hunter Ice Trap. I can still autoattack while trapped.

### ISSUE THREAD

**Issue by MixusDruid** [SunstriderEmu/BugTracker#2652]
When a hunter traps me in their Ice Trap, im still able to autoattack. (Feral druid here).

**Comment by PhilipH3ro** [comment]
Use software like ShareX to easily record it and use it as proof :)

**Comment by blblblaz** [comment]
could not reproduce, a video of it happening would be really helpful if possible

**Comment by Ironjudgment** [comment]
Yeah, I couldn't get it to work either. Video: https://youtu.be/YCjukMJnVjE
