### ISSUE TITLE
[Arathi Basin] Resurrection in Arathi Basin doesn't work correctly

### ISSUE THREAD

**Issue by Trolltilla** [SunstriderEmu/BugTracker#2653]
**Describe the bug**

When you are getting ressed in a base and an enemy caps the base you will just stand still without getting teleported to another nearest resurrection base.
**To Reproduce**

1. Die in Arathi Basin
2. While on the resurrection timer cap the base with another faction
3.  You should get ported to the nearest resurrection base but instead you will just stand still

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

You should get ported to the nearest resurrection base instead of standing still as a ghost
**Screenshots/videos**

**Additional context**

**Comment by Ironjudgment** [comment]
Its a problem in AV aswell.

**Comment by Balanarr** [comment]
And in eots

**Comment by Jerrythemagicdog** [comment]
Fixed a long time ago, thanks for the issue, we hear that AV issue still happens sometimes for certain graveyeards but will need steps in the separate issue for AV.
