### ISSUE TITLE
Guild seller Guilds

### ISSUE THREAD

**Issue by Folgrum** [SunstriderEmu/BugTracker#2654]
Hey, Just wondering if you can put a "block all guild invites" button in the game or something? I get spammed by guild farming guilds and well it may be a simple thing as to join a guild I think that button would be appreciated by all. Or you could make the level requirement be 40 to make a guild.

**Comment by Sheikthecatman** [comment]
Report Guild seller guilds through tickets in-game if you would want to see the guilds gone!
