### ISSUE TITLE
Cannot unlearn Potion Master Alchemy spec

### ISSUE THREAD

**Issue by pirkagia** [SunstriderEmu/BugTracker#2655]
I cannot unlearn the Potion Master specialization as an Alchemist.

Lauranna Thar'well in Zangarmarsh will not give you the choice to unlearn Potion Mastery for 150g,
as she should do. I am an Alchemist (325 skill) with Potion Master quest done. 
Is she bugged? 
![handshake-clipart-partnership-16](https://user-images.githubusercontent.com/62960571/78065549-1dc89b00-739c-11ea-80b0-51cdcb9a6be2.png)

**Comment by pirkagia** [comment]
Fixed. Seems like I had to skill my alchemy more or use my potion mastery skills

**Comment by blblblaz** [comment]
looks like an issue nonetheless, I had to craft a potion in order to be able to unlearn the Specialization

**Comment by kelno** [comment]
The condition was to be at least 350 for some reason. I've reworked the trainers now, applied with next update.
As a custom change, you can also unlearn your older spec at any spec trainer.
