### ISSUE TITLE
Shaman Water Walk 

### ISSUE THREAD

**Issue by Thiazole** [SunstriderEmu/BugTracker#2656]
**Describe the bug**
Water walk won't work on my player friend.
**To Reproduce**
We were both in a party and I tried to use water walk on him. Doesn't let me. I could use underwater breathing though.
**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by PhilipH3ro** [comment]
Was your partymember on a mount?

**Comment by Thiazole** [comment]
No, he was in water.




Obțineți Outlook pentru Android







On Wed, Apr 1, 2020 at 10:17 AM +0300, "PhilipH3ro" <notifications@github.com> wrote:















Was your partymember on a mount?

**Comment by steak-house** [comment]
This bug occurs when casting Water Walk on characters with stances, so any warrior, a shapeshifted druid, a stealthed rogue, or a shadowform priest.

**Comment by z5n** [comment]
unable to reproduce
