### ISSUE TITLE
Fleeing humanoid mobs can be dispelled, debuff visible to players

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2658]
Some mobs in the game, mostly humanoid ones, flee at a low health %. On this server, this debuff is visible to the player once it happens. It is also a magic debuff and thus can be dispelled, once done, the mob stops fleeing and returns to you.

The debuff should not be visible to the player, nor should you be able to dispel it.

![Flee](https://user-images.githubusercontent.com/37913400/78085719-6161db80-7381-11ea-8c32-0ca08aa75934.png)

**Comment by blblblaz** [comment]
yeah, this only happens when they have friends nearby to flee to

**Comment by Syfte-oss** [comment]
> yeah, this only happens when they have friends nearby to flee to

And when that happens they run straight to that friend without pausing even if it's unusually far.  Another bug.

**Comment by steak-house** [comment]
while yall fixing this, sometimes mobs will run outside of their reset range, causing them to instantly reset when their self-fear ends

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
