### ISSUE TITLE
Herb nodes re-spawning extremely slow or not at all after high server uptime.

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2659]
No I don't have any evidence, but I still think you should look into it. This is for TBC herbalism nodes, I can't speak to Mining nodes or pre-TBC things. The respawn rate of nodes was decent and you could find plenty in the last few weeks I have done lots of rounds on zones and know this server's herbalism patterns quite well at this point.

These past few days have been much more difficult, I've done several rounds around an entire zone of Terokkar (a low farm zone) and found zero herb nodes. 

Only thing I can come up with is the high server uptime lately, because last night I noticed the same thing, circling a zone for an hour with zero herbs to show, but a server crash happened and the herb spawns went back to normal.

**Comment by jaydeebre96** [comment]
Can only approve same goes for mining veins this needs a fix asap

**Comment by wiglefish** [comment]
+1 on this. Driving the Mana Thistle price through the roof.

**Comment by Godmatik** [comment]
Closing, appears fixed after latest restart.
