### ISSUE TITLE
Bugged death animation

### ISSUE THREAD

**Issue by Equalsthr33** [SunstriderEmu/BugTracker#2660]
**Describe the bug**

When an enraged earth spirit in Shadowmoon Valley dies (and is mined?) the body continues "rolling" without despawning. 

**To Reproduce**
 Kill an enraged earth spirit and mine the body.

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

body despawns
**Screenshots/videos**

https://gyazo.com/423f7449e812917c9577a25691a8a9ab
**Additional context**

**Comment by z5n** [comment]
working as intended
