### ISSUE TITLE
Engineering Target Dummy

### ISSUE THREAD

**Issue by Fixed7** [SunstriderEmu/BugTracker#2661]
**Describe the bug**

The engineering item "Target Dummy" is supposed to be able to drop "Fused Wiring", but the dummy is unlootable.
**To Reproduce**

1. Use "Target Dummy" on ground.
2. Wait 15 seconds. 
3. Should be able to loot corpse, but no corpse appears.

Item: https://classic.wowhead.com/item=4366/target-dummy

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2403
