### ISSUE TITLE
Gas cloud respawn

### ISSUE THREAD

**Issue by arky94** [SunstriderEmu/BugTracker#2662]
It seems like gas cloud in nagrand for instance are at 8min timer but sometimes after extracting them a few times they disapear and don't respawn for like 24 min + witch is not normal…

I would appreciate a fix

Thanks

**Comment by blblblaz** [comment]
they are "pooled" which means that when you extract one it's not guaranteed to spawn in the exact same place, were you camping the same spawn?

**Comment by arky94** [comment]
yes the same spawn, but isn't it intended to spawn always at the same ?

**Comment by beraus** [comment]
This issue should be fixed now.
