### ISSUE TITLE
Ghost Wolf Shaman Bug

### ISSUE THREAD

**Issue by victorcalarasu** [SunstriderEmu/BugTracker#2663]
**Describe the bug**

Sometimes when I activate Ghost Wolf on my shaman i get transformed into a zebra, not a ghost wolf.

**To Reproduce**

1. When cast on myself.

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://classic.wowhead.com/spell=2645/ghost-wolf

**Expected behavior**

I think it should transform me into a ghost wolf.

**Screenshots/videos**

![91495315_2529771457339872_3929816336204562432_n](https://user-images.githubusercontent.com/58118772/78121204-c49c4e00-7413-11ea-8682-6ed486956bfa.jpg)
![91803590_533648500907325_8305081550496595968_n](https://user-images.githubusercontent.com/58118772/78121214-c8c86b80-7413-11ea-9808-630ebe227b1e.jpg)

**Additional context**

**Comment by Rettiy** [comment]
Not sure if this is a meme but it's beautiful.

**Comment by Smashyxgod** [comment]
este 1 aprilie , d'aia te face zebra lol.

**Comment by victorcalarasu** [comment]
> este 1 aprilie , d'aia te face zebra lol.
> April Fools' Day

Ar fi super amuzant sa fie asa dar mi s-a mai intamplat si zilele trecute lol

**Comment by blblblaz** [comment]
april fools!
