### ISSUE TITLE
Heroic Strike Rank 11

### ISSUE THREAD

**Issue by Smashyxgod** [SunstriderEmu/BugTracker#2664]
Well Heroic Strike on Endless.gg it's rank 10 which is for lvl 66 but the rank 11 that is for lvl 70 it not avaiable / can't be learned from trainers.

Proof : 
https://tbc-twinhead.twinstar.cz/?spell=78

**Comment by blblblaz** [comment]
it appears rank 11 heroic strike might be in the game files but it wasn't available to players in TBC


https://wow.gamepedia.com/index.php?title=Heroic_Strike&oldid=1431978#Rank_Table

https://www.wowhead.com/forums&topic=23257/heroic-strike-rank-11-etc
