### ISSUE TITLE
Mining Veins

### ISSUE THREAD

**Issue by jaydeebre96** [SunstriderEmu/BugTracker#2666]
**Describe the bug**
Something is clearly wrong with the spawn/respawn time of veins 

**To Reproduce**
Just go to any of the open world zones and you will soon realize that you wont find anything

**Expected behavior**
There should be an "appropriate" amount of mineable veins and a reasonable respawn time that is clearly not the case right now

**Comment by nottreal** [comment]
As far what i saw in last couple days of farming nodes/herbs that they stuck or get invisible after some times. As now we have good uptime on the server thats makes nodes/herbs problems. 
Yesterday after server crash, all zones was full of nodes/herbs thats makes a prof that uptame makes them bug.

**Comment by Godmatik** [comment]
Confirmed for herb nodes as well, only a server crash or restart fixes things

**Comment by Mojigam** [comment]
Same problem, sometimes it just disappear from map and appear when your are flying. Can't find nodes at all, specially at caves where should be a lot of them.

**Comment by beraus** [comment]
This issue should be fixed now.
