### ISSUE TITLE
Cannot complete some AV quests

### ISSUE THREAD

**Issue by wombo2u** [SunstriderEmu/BugTracker#2667]
**Describe the bug**
Capture a mine <pvp> quest does not give credit from either mine in AV even when you claim it.
Proving Grounds quest is impossible to complete as the banner says <that is already being used> when you try to click it.

**To Reproduce**
Start quests and test inside AV

**Screenshots/videos**

**Additional context**

**Comment by InhumanGM** [comment]
**Video of Issue:**
https://youtu.be/DG4cemsAAF4

**Comment by beraus** [comment]
Should be working now.
