### ISSUE TITLE
Horde Paladin's quest "True Masters of the Light" 

### ISSUE THREAD

**Issue by AndrewMZ6** [SunstriderEmu/BugTracker#2669]
**Describe the bug**
The horde (blood elves) quest "True Masters of the Light" that is the last quest in quest chain for getting blood knight tabard and pala mount "charger". The quest requires you to use quest item "Extinguishing Mixture" in the Alonsus chapel wich is a church looking building that you will see in undead part of Stratholme, right after you pass the gate. After using the quest item thereby burning the church, the guy inside the church should turn hostile and you should kill him. But he doesn't. He just stays friendly.
After using the quest item 5 mobs spawn right outside the church. They work fine but the problem is that you can spawn infinite amount of that mobs by using quest item again and again. it's like 5 mobs, 10, 15, ...

**To Reproduce**

1. Get the quest "True Masters of the Light" from Lady Liadrin in Silvermoon City
2. Go to stratholme dungeon (undead part that requires a key from the city)
3. Enter the Alonsus Chapel and use quest item on eternal flame (the gloing thing inside) 
4. To spawn more mobs just use quest item again

Quest Item: https://wowhead.com?item=24287/extinguishing-mixture
Quest: https://wowhead.com?quest=9737/true-masters-of-the-light
Spell: https://wowhead.com?spell=

**Expected behavior**
The mob inside the church should turn hostile and attack the player for burning his church. No more mobs should spawn after there are already 5 guys spwaned

**Screenshots/videos**
Cannot upload screenshots here for some reason, so https://imgur.com/a/6aipWfv

**Additional context**
This quest is actually important for horde paladins mostly because of unique and cool looking blood knight tabard

**Comment by kealthas06** [comment]
Any improvement On the quest?

**Comment by kealthas06** [comment]
it is a very easy fix

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in [482374923e3c13ab1407c298028943db3d147bbe](https://github.com/kelno/sunstrider-scripts/commit/482374923e3c13ab1407c298028943db3d147bbe).
