### ISSUE TITLE
Shaman talent Elemental Devastation and Flametongue Wepon working issue

### ISSUE THREAD

**Issue by Harvel218** [SunstriderEmu/BugTracker#2670]
[Elemental Devastation] (ele tree)
Talent descritpion: 
Your offensive spell crits will increase your chance to get a critical strike with melee attacks by (3%/6%/9%) for 10 sec.

The problem: Talent is not working properly becosue flametongue wepon crits should proc it (but they dont).

it was working on every server i have played in the past, flametongue wepon dmg is depending on wepon speed, bonus spell damage, and spell crit (and this is offensive spell), i want u to Fix it or to tell anything about it, (I want to use it, but getting to know that You wont fix this would be better than nothing...)

If flametongue wepon procs are not SPELL and not a MEELE attacks, then what is it ? (its fire dmg)
And with that begin said, this talent is completely uselles on this server without any reason to exist...(but it shouldnt be like that... as i said on every server such as warmane or NB it was working properly)

Thanks for your attention, i wish the problem will be fixed soon and i will be able to play my favourite spec <3
Peace!

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
