### ISSUE TITLE
carachter stuck in constant sickness fix@!!

### ISSUE THREAD

**Issue by bazsycus** [SunstriderEmu/BugTracker#2672]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Godmatik** [comment]
you need to give further information, are you crashing or just stuck? Didn't even provide your character name ...
