### ISSUE TITLE
Can't herb from flying form

### ISSUE THREAD

**Issue by Kotchimotchi** [SunstriderEmu/BugTracker#2673]
**Describe the bug**

After update 1/4/2020 you can't collect herbs from flying form anymore you get error msg "You are flying." when trying to collect herbs.
**To Reproduce**

Enter flying form, try to collect herbs, get error msg.

**Expected behavior**
You should be able to collect herbs from flying form.

**Screenshots/videos**

Flight Form has a few specific advantages over a Flying Mount.
"Although you cannot use items such as healing and mana potions while in Flight Form, you can interact with the world in ways that a flying mount doesn't allow: you can loot, pick herbs, and skin (but not mine) in Flight Form. This means you are able to avoid danger by increasing your altitude if caught unaware."
- https://wowwiki.fandom.com/wiki/Flight_Form

**Comment by Godmatik** [comment]
Per GM in discord, this was an intentional change.

**Comment by TheMoneyHater** [comment]
https://thedruidsgrove.org/archive/wow/t-12099.html
"There was a previous patch that completely removed the ability to herb while in flight form, but it did not cancel the form if you attempted to do it, instead it simply would not let you. With 2.2 they brought it back, but made it so you had to be on the ground. With odd clipping issues sometimes it is just easier to swap forms and herb :("

**Comment by TheMoneyHater** [comment]
If it wasn't in 2.1.2. Then please show me proof of when they changes it to how it is in retail right now.

**Comment by Lazerwow** [comment]
https://wow.gamepedia.com/Patch_2.2.0_(undocumented_changes)
UI & Game Mechanics ------>  Druids in flight form can now perform herbalism provided they are on the ground.

**Comment by TheMoneyHater** [comment]
https://wow.gamepedia.com/Patch_2.2.0_(undocumented_changes)
UI & Game Mechanics ------> Druids in flight form can now perform herbalism provided they are on the ground.
