### ISSUE TITLE
Druid cat form, is worgen?!?

### ISSUE THREAD

**Issue by bukowywowwe** [SunstriderEmu/BugTracker#2674]
Had a friend playing a druid who Everytime he used cat form, instead of a cat he was a worgen?  Just wanted to let you all know. Also seems that ghost wolf form shows up as a zevra?!? Thanks for the amazing server!

**Comment by Godmatik** [comment]
It's an April Fools joke

**Comment by bukowywowwe** [comment]
Lol my bad. That's fucking hilarious.

**Comment by Sheikthecatman** [comment]
The original forms called it a night.
