### ISSUE TITLE
No Sound In game

### ISSUE THREAD

**Issue by Reknokh** [SunstriderEmu/BugTracker#2675]
**Describe the bug**
Hello !

I juste installed the game, and I have no sound at all. I tried to active and desactivate the setting, in game and outside. I Have reinstalled the game aswell... Nothing work, I still have no sound.

**Additional context**
The sound work in every other programmes/games. It only doesn't work with this one.

Thank you,

**Comment by Sheikthecatman** [comment]
This is a client-side issue and not a server side one. I cannot assist you in this case, sorry.
