### ISSUE TITLE
Can't get the confirmartion e-mail 

### ISSUE THREAD

**Issue by MikeQC** [SunstriderEmu/BugTracker#2676]
Hi, i try to make an account but cant get the confirmation e-mail, i resend it a couple time and still dont get it ! Whats going on, i've try with an other e-mail and still cant get my confirmation e-mail, plz help !

**Comment by Godmatik** [comment]
Check spam folders.
Also - I heard there are issues with hotmail and other providers, try with gmail

**Comment by MikeQC** [comment]
I dont have a gmail adress bro !

**Comment by Godmatik** [comment]
just make one ... ?

**Comment by MikeQC** [comment]
Well, i made one and still dont get that e-mail lol, weird !

**Comment by MikeQC** [comment]
So can anyone help me ?! Cant fix that issue myself

**Comment by Godmatik** [comment]
maybe message a GM on discord or something, this place is only really for in-game bugs.

**Comment by MikeQC** [comment]
Can you link me the discord, i dont know the adress. thx

**Comment by Godmatik** [comment]
https://endless.gg/faq

**Comment by MikeQC** [comment]
Thx bro

**Comment by MikeQC** [comment]
Well, i've try to connect to the discord but cant its dosent work, so i sent a e-mail to endless but its dosent work either !!!! mta-1.mta.xion.oxcs.net rejected your message to the following email addresses:

hello@endless.gg (hello@endless.gg)
We were unable to deliver your mail because the destination mail system rejected your mail for security or policy reasons. For example, the mail address may only accept mail from certain senders, or may not accept certain types of mail, such as those larger than a given value.

Contact the recipient (for example, by phone) and try to identify with them and their mail administrator the policy or setting that blocked your mail and what you should do to prevent rejection of future mail.

For more information, see State Code 5.7.1.


Whats going on over here ??? Never had this issue before and i've played wow on private server a lots of time !

**Comment by Godmatik** [comment]
how can you possibly not connect to discord? lol ...

**Comment by Godmatik** [comment]
try this
https://discord.gg/StJUcW

**Comment by Sheikthecatman** [comment]
The mail issue might be on our side, I suggest using gmail or wait until we can fix it.
