### ISSUE TITLE
Unable to summon Wind Trader Marid if you abandon quest

### ISSUE THREAD

**Issue by ThePettsoN** [SunstriderEmu/BugTracker#2677]
You are supposed to summon [Wind Trader Marid](https://www.wowhead.com/npc=20071/wind-trader-marid) by activating the Ethernal Teleport Pad in Netherstorm (71.1 39.0) and select a dialog option (after you've completed [A Not-So-Modest Proposal](https://www.wowhead.com/quest=10270/a-not-so-modest-proposal)).

If you do this and pick up the [Getting Down to Business](https://www.wowhead.com/quest=10271/getting-down-to-business) quest and then abandon it, you will no longer get the dialog option to summon him from the Ethernal Teleport Pad, making it impossible to continue on with the quest chain.

How to reproduce:
1. Start Quest [A Not-So-Modest Proposal](https://www.wowhead.com/quest=10270/a-not-so-modest-proposal).
2. Pick up the [Teleporter Power Pack](https://www.wowhead.com/item=28969/teleporter-power-pack)
3. Run to the Ethernal Teleport Pad (71.1 39.0) and use it.
4. Select the dialog option and start the [Getting Down to Business](https://www.wowhead.com/quest=10271/getting-down-to-business) quest.
5. Abandon [Getting Down to Business](https://www.wowhead.com/quest=10271/getting-down-to-business)
6. Use the Ethernal Teleport Pad again.
7. Notice there is no longer an dialog option

**Comment by InhumanGM** [comment]
Upon attempting to reproduce the issue, I was not able to find any issues. Upon abandoning the quest and using the pad again, I am still able to attain the quest. Could you provide more information that could be used to try to reproduce the issue again?
