### ISSUE TITLE
Worgen books used by hunters in karazan

### ISSUE THREAD

**Issue by magicborne** [SunstriderEmu/BugTracker#2678]
Hello,

In karazan you can get books from the ground.

With the worgen book, it should give a chance to proc on melee and ranged attacks. Well on hunters, its not working at all. NEVER proc when it should on ranged attacks too.

And the titans books proc chance is extremely low, from 170 cast, it procced 3 times.

Please look into it.

**Comment by TheMoneyHater** [comment]
It worked in Karazhan 1 week ago what I saw on recount.
