### ISSUE TITLE
Warrior Defensive Stance and Hunter Taming a Beast quest not working

### ISSUE THREAD

**Issue by Joerpa24** [SunstriderEmu/BugTracker#2680]
**Describe the bug**
The Quest for the Warrior Defensive Stance is not there and now i don't have my defensive stance, Also the Hunter taming a beast quest isn't showing up and now we can't tame a beast.

**To Reproduce**
Please give us the defensive stance and Tame a beast spell

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Godmatik** [comment]
Go to the main city to get the hunter quest, the warrior quest might be there also.
