### ISSUE TITLE
Blueleaf Tubers

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#2681]
**Describe the bug**
After I released the Gopher, didn't matter where I tried, it didn't do anything. I tried in various places in the trenches, at the place where the comment by kreghx indicated (re link), on the main and top levels, etc. 

**To Reproduce**

1. Release a Gopher by clicking on the crate with holes near a vine.
2. Use the command stick at a spot where the tuber is supposed to be.
3. Gopher didn't sniff nor did anything.

https://classic.wowhead.com/quest=1221/blueleaf-tubers#comments

**Expected behavior**
At step 3, if it's at a right location, the Gopher would sniff out a tuber for the user to interact with/obtain.

On an unrelated issue (possibly another bug) in RFK, Roogug didn't drop any loot, not even a trash loot. Maybe he's missing a loot table.

**Comment by Jerrythemagicdog** [comment]
Thanks, both issues fixed with the next update.
