### ISSUE TITLE
Druids unable to farm herbs in flight form

### ISSUE THREAD

**Issue by lukas155** [SunstriderEmu/BugTracker#2684]
Druids are unable to farm in Flight form.

Step 1: Be in flight form
Step 2: Attempt to herb a node.
Step 3: Error message "you are flying".

All herbs.

Should be able to herb in flight form provided you are on the ground.

While in 2.1 the flight form gathering WAS nerfed, it was re implemented in 2.2, provided you were on the ground when gathering.

Source: https://wow.gamepedia.com/Patch_2.2.0_(undocumented_changes)

**Comment by blacktouff** [comment]
!important

**Comment by urmomtoppedme** [comment]
https://wow.gamepedia.com/Patch_2.2.0_(undocumented_changes)

literally reverted

**Comment by Lazerwow** [comment]
Please fix this ridiculous change

**Comment by TheMoneyHater** [comment]
https://wow.gamepedia.com/Patch_2.2.0_(undocumented_changes)
UI & Game Mechanics ------> Druids in flight form can now perform herbalism provided they are on the ground.

**Comment by lukiecz** [comment]
from your website faq:
"Will stats on items and spells be subject to patch progression?
No, all item stats and spells will be in their 2.4.3 state."
-------
what you did is NOT 2.4.3 state and NOT blizzlike... what you did is really short period of time between 2.1.2 and 2.2.0
----
If you think druids gathering herbs in flight form was a bug you are dead wrong... So please dont call this change you did "bugfix" ...

**Comment by Ironjudgment** [comment]
This is not new, many servers made flight form less overpowered by not allowing harbing/mining while in it. Warmane/Sunwell did this and it was a correct decision in my opinion.

**Comment by Cachirla** [comment]
> This is not new, many servers made flight form less overpowered by not allowing harbing/mining while in it. Warmane/Sunwell did this and it was a correct decision in my opinion.

if u allow custom nerfs they will keep nerfing/buffing every thing they want, some day warloks may lose soul link, warriors the stun mace, etc.

FIX IT ASAP AND STOP DOING CUSTOM NERFS PLEASE.

!important

**Comment by Jerrythemagicdog** [comment]
Thanks, updated to the 2.2 state with next server update: 
Can't herb if flying and in flight form, can herb if in flight form and not flying.
