### ISSUE TITLE
Crystal of Zin-Malor Trinket not working correctly

### ISSUE THREAD

**Issue by Ticketdudu** [SunstriderEmu/BugTracker#2686]
The [Crystal of Zin-Malor] Trinket does not deal any damage to myself. It should do 100-500 damage and manadrain per second if i have it equipped.

I accepted the "Tormented by the past" questchain to get that trinket.

Item: https://classic.wowhead.com/item=13347/crystal-of-zin-malor
Quest: https://classic.wowhead.com/quest=5248/tormented-by-the-past

Screenshot:
![Screenshot_14](https://user-images.githubusercontent.com/63036537/78216299-cf112300-74b9-11ea-83cd-9c4db8657fa5.png)

I would be happy if it gets fixed :)

Greetings, 
Dudula

**Comment by z5n** [comment]
unable to reproduce
