### ISSUE TITLE
Darkmoon Card: Blue Dragon (lvl60 darkmoon trinket)

### ISSUE THREAD

**Issue by Luciferonx** [SunstriderEmu/BugTracker#2687]
**Describe the bug**
Finally I've made that trinked, wasted a lot of gold. While being in raid (Gruuls Raid), Ive made more that 200 heals and there was no a single proc of that trinket. Later on I thought I was just unlucky and decided to test it for 15 minutes. I was using the most mana efficient healing spells (low ranks) for 15 minutes. Guess? Right, no procs.

**To Reproduce**
Get Darkmoon Card: Blue Dragon (combine 2,3,4,5,6,7,8 and ace of beasts)
1. cast healing spells and track yours buffs
2. start being upset
3. put the trinket in bank and get back to bugtracker

https://classic.wowhead.com/item=19288/darkmoon-card-blue-dragon
https://classic.wowhead.com/quest=7907/darkmoon-beast-deck

**Expected behavior**
I expected it to proc as it supposed to do.

**Additional context**
Please fix it, I beg you :D

**Comment by ABDisciple3** [comment]
trinket procs.. just sounds like horrible rng. source: guildie has trinket and it has proc'd.

**Comment by Luciferonx** [comment]
still the proc rate is insanely low then

**Comment by limah-beans** [comment]
Should be a 2% proc rate in combat. Do you have any combat logs Luciferonx?

**Comment by Luciferonx** [comment]
No. I dont have combat logs. But no procs out of 200 heals is not 2% proc rate :D

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed after next server update.

**Comment by jketch** [comment]
@Jerrythemagicdog Any details on the change you made here?
