### ISSUE TITLE
Dont receive verification emails.

### ISSUE THREAD

**Issue by Makeitanart** [SunstriderEmu/BugTracker#2691]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Makeitanart** [comment]
Accountname: makeitanart ive waited since yesterday evening, tried to resend email like 10 times but dont receive ive checked trash etc

**Comment by kuukivilol** [comment]
Experiencing the same exact problem.

**Comment by Godmatik** [comment]
On discord, GMs are saying it is an issue with hotmail/outlook.

Try using gmail.
