### ISSUE TITLE
Greathmother Geyah

### ISSUE THREAD

**Issue by mmarkovic123** [SunstriderEmu/BugTracker#2692]
**Describe the bug**
I am not able to talk to an NPC in Nagrand "Greatmother Geyah", she starts a big quest chain. GM was able to help by killing her and re-spawning her again, it worked fine but after I took the next quest in line it bugged out again.

**To Reproduce**
I assume it would be enough to try the quest chain. "A Visit With the Greatmother". To be able to start this quest, you need to complete few other questlines:

1) blademaster chain http://www.wowhead.com/?quest=10107
2) altruis the demon hunter chain http://www.wowhead.com/?quest=9983
3) the murkblood quests (murkblood invaders http://www.wowhead.com/?quest=9872 as well as the escort quest out of sunspring village)

**Expected behavior**
Talk, take and turn in quests.

**Screenshots/videos**
![WoWScrnShot_040220_150216](https://user-images.githubusercontent.com/62065152/78253066-1a482780-74f4-11ea-9b5f-04dde8338d94.jpg)

**Additional context**
This is in fact bugged for other players too.

**Comment by Thiazole** [comment]
I can confirm this, I completed the chain till Mother Geyah. 

https://imgur.com/a/TRdBU1V

**Comment by InhumanGM** [comment]
Greatmother Geyah seems to be non-interactive whenever she is still stuck in the script for her event with Thrall.

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago.
