### ISSUE TITLE
Blood Fury

### ISSUE THREAD

**Issue by Zinbl4** [SunstriderEmu/BugTracker#2694]
Blood Fury tooltip is incorrect at high lvl.
![1](https://user-images.githubusercontent.com/63056321/78257060-0a374480-7502-11ea-87e7-d2de70ba8ca6.PNG)
![2](https://user-images.githubusercontent.com/63056321/78257067-0d323500-7502-11ea-84e0-f26a95267845.PNG)

**Comment by z5n** [comment]
clear cache
