### ISSUE TITLE
I just lost all the mails that were waiting in my mailbox, several pages, how to recover it ?

### ISSUE THREAD

**Issue by Kasparrr** [SunstriderEmu/BugTracker#2697]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Godmatik** [comment]
Close client and reboot

**Comment by Kasparrr** [comment]
worked ! thanks
