### ISSUE TITLE
Aimed Shot

### ISSUE THREAD

**Issue by Villpusen** [SunstriderEmu/BugTracker#2699]
Hello, 
Whenever you do aimed shot as a hunter, it doesn't seem to qeueue up the next auto attack.
It waits for the aimed shot to go off, then it starts the full "new" timer for the weapon before it shoots the auto attack. 

For example, if you have a weapon with 2,5 seconds auto swing, and do Aimed shot, it will go like this.

1. Cast aimed shot - 3 Sec cast 
2. Wait - 2,5 sec for auto attack.

When it should be:

1. Cast aimed shot - 3 Sec cast 
2. Auto attack goes off instantly.
3. Now wait 2,5 seconds for the next auto attack.

From what I can remember, it should queue up the next auto attack even if you are casting an aimed shot?

Best Regards,

Villpusen.

**Comment by Jerrythemagicdog** [comment]
This is intended and correct: https://github.com/SunstriderEmu/BugTracker/issues/1827
