### ISSUE TITLE
quest  The Ward of Wakening

### ISSUE THREAD

**Issue by ageerik** [SunstriderEmu/BugTracker#2702]
When you pick the bogblossom flowers they should sometimes explode and knock you off.  Instead you only get a debuff on you for 2 sec and nothing happend.

**Comment by InhumanGM** [comment]
The debuff is called _Bogblossom Pollen_ (_ID: 39558_), and it should apply a knock-back effect to the player.

https://imgur.com/a/o6FlWPY
https://tbc-twinhead.twinstar.cz/?spell=39558

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in [c95707fa9c5293ebfba5cb960cc6a275240d7535](https://github.com/kelno/sunstrider-scripts/commit/c95707fa9c5293ebfba5cb960cc6a275240d7535).

Fix will be live next server restart.
