### ISSUE TITLE
Critical Chance After Disarm

### ISSUE THREAD

**Issue by Mojigam** [SunstriderEmu/BugTracker#2704]
Whenever you get disarm by a mob for example, your crit chance is reduced because you lose stats from your weapon, BUT, it should go back when the debuff expires, which is not what is happening.
If you equip an item after this, the % gets back to normal.

**Comment by Jerrythemagicdog** [comment]
Crit chance doesn't go down after disarm you just don't have a weapon for a certain amount of time.
