### ISSUE TITLE
Cant create Deadly Poison V

### ISSUE THREAD

**Issue by Martyn27** [SunstriderEmu/BugTracker#2707]
**Describe the bug**
I reached level 60 and learned Deadly Poison V. It is available in my poisons menu. When I try to "Create" it says "Item is not ready yet.

**To Reproduce**
Attempt to create Deadly Poison V

**Screenshots/videos**

![image](https://user-images.githubusercontent.com/63094158/78337024-339ab380-7588-11ea-8f88-bbba81546b46.png)

**Comment by Godmatik** [comment]
Duplicate. https://github.com/SunstriderEmu/BugTracker/issues/2474
