### ISSUE TITLE
Selling and using spells on creature and selecting quest rewards.

### ISSUE THREAD

**Issue by maxkiller13** [SunstriderEmu/BugTracker#2711]
i cannot sell, nor use spells on creatures or anything nor choose quest rewards. i am an undead warlock level 7 rn and cant progress at all. i have some good gear and a lot of coin that i would rather not go throiugh again

**Comment by Sheikthecatman** [comment]
This seems to be a client-side issue. I suggest clearing cache and restarting the game.
