### ISSUE TITLE
Rip-Blade Ravager Appearance change

### ISSUE THREAD

**Issue by Rumjunkie** [SunstriderEmu/BugTracker#2715]
After taming a Rip-Blade Ravager in Blade's Edge, and then mounting (de-summing the pet obviously) the appearance changed back to that of the Ravager I had tamed in the Bloodmyst Isle at level 12.

To reproduce: Tame a Ravager in Bloodmyst Isle, then tame a Rip-Blade ravager in Blade's Edge, mount and dismount the appearance changes and DOES NOT revert back, it remains as the base Ravager in Bloodmyst Isle.

Expected behaviour: I expected the Ravager to retain it's colour scheme and appearance after taming.

Screenshots:

![WoWScrnShot_040320_210147](https://user-images.githubusercontent.com/61786483/78354864-611f4580-75f8-11ea-87fe-3b446ec5e17a.jpg)    This is before the change

![WoWScrnShot_040320_221813](https://user-images.githubusercontent.com/61786483/78355196-0b976880-75f9-11ea-88c9-e63023bee097.jpg)

This is after I dismounted after riding to Zangarmarsh, post change.
I have tried several things, re-summoning, logging out, restarting WoW, re-mounting etc, nothing works to revert the appearance.

**Comment by Jerrythemagicdog** [comment]
Probably fixed along with other pet issues in the past, this re-summoned the wrong pet.
