### ISSUE TITLE
Clefthoof Bull gone from Nagrand

### ISSUE THREAD

**Issue by screwdriver66** [SunstriderEmu/BugTracker#2716]
**Describe the bug**

Hello, it seems that all Clefthoof Bulls are gone from Nagrand, yesterday there were plenty, and now i cannot find any.
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Azmodeane** [comment]
This is accurate. I was killing them before the Reset. I have been waiting outside Telaar for the same spawn for 20minutes(DB says 5min respawn). After no spawns, I traveled north. They were not spawning. In the south, Bulls spawn with the rest of their "Herd;" however, it seems the single spawn Clefthoof Bulls have stopped. The locations on the database: 
https://db.endless.gg/?npc=17132
shows they should be outside Telaar to the East. This DB entry is also missing health and other stats. Has the respawn rate been removed, or is this some sort of strange phasing?
These bulls have a VERY important skinning item for leveling up leatherworking to 350 and beyond. Please fix this before the leather market inflates and burns holes into my pockets.
Thank you!

**Comment by Azmodeane** [comment]
After killing the Bulls that are with their herd, it causes them to immediately respawn and become unable to skin since the body disappears.

**Comment by Sheikthecatman** [comment]
Seems to be fixed.

**Comment by lukas155** [comment]
Not fixed, still VERY few cleft hoofs around.
