### ISSUE TITLE
[Shaman] Flametongue weapon

### ISSUE THREAD

**Issue by notsofamous** [SunstriderEmu/BugTracker#2721]
The effect hits the target even if the weapon attack misses.

> Imbue the Shaman's weapon with fire. **Each hit** causes X to X additional Fire damage, based on the speed of the weapon. Slower weapons cause more fire damage per swing. Lasts 30 minutes.

https://tbcdb.com/?spell=25489

**Comment by Syfte-oss** [comment]
Tried testing this on a 7700 dummy outside Ironforge.  Flametongues did not hit when my weapon missed.  Flametongue did hit when my weapon was dodged.

https://i.imgur.com/D62XVws.jpg
