### ISSUE TITLE
activation email

### ISSUE THREAD

**Issue by Bach321** [SunstriderEmu/BugTracker#2724]
I do not recieve any activation mail?

did check the spam folder nothing there.. Been trying for several days now?

Regards

**Comment by beraus** [comment]
Try with a gmail.

**Comment by Bach321** [comment]
My other account is on an outlook and works fine? :(

**Comment by Godmatik** [comment]
i heard hotmail and outlook aren't working right now.

**Comment by shadowweaver94** [comment]
Hey guys i have a problem with recive message . I try to createa acount from some different IP addres but no one is working .
