### ISSUE TITLE
[Shaman] Far Sight

### ISSUE THREAD

**Issue by notsofamous** [SunstriderEmu/BugTracker#2725]
Using Far Sight to look at players who would normally be too far away too see makes their movement super glitchy. Everyone is stuck running in place.

https://tbcdb.com/?spell=6196

**Comment by Syfte-oss** [comment]
I went to check this out and it's a thing.  Using it in Ironforge, players and the vendor npc stop in place but the guards continues to path for a short distance.  Swinging the camera back and forth seems to let some players update as ones will appear who weren't there before.  You can see this inside the auction house.

https://youtu.be/oMCGq2yJG48

**Comment by z5n** [comment]
unable to reproduce, issue has likely since been fixed
