### ISSUE TITLE
No herbs/Mining veins inside Steamvault

### ISSUE THREAD

**Issue by HysjHysj** [SunstriderEmu/BugTracker#2726]
There is no Mining veins or Herbs inside Steamvault 3th of april.

**Comment by Godmatik** [comment]
There's none in any TBC dungeon.

This means zero Ancient Lichen, since that is the only place it is found, critical component for tank flask.

**Comment by elnium123** [comment]
As always, no one will take the time to answer, sad .. and btw on retail TBC 12 years ago, node are inside steamvault lel

**Comment by beraus** [comment]
This issue should be fixed now.
