### ISSUE TITLE
Alliance First Aid from 225 --> 300 is not possible.

### ISSUE THREAD

**Issue by Krykutay** [SunstriderEmu/BugTracker#2727]
I'm level 70 with 225 First Aid skills. However, the npc Doctor Gustaf VanHowzen isn't targettable. Thus, I can't take the first aid quest from him. I've been seeing a lot of people not being able to speak with this guy.

**Comment by beraus** [comment]
Temp fixed.

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2444.
Temp fixed.

**Comment by tamerechien** [comment]
Still bugged.

**Comment by tamerechien** [comment]
yeah and killing him dosen't help with the problem to be honest.

**Comment by reli21** [comment]
how to raise FA without talking to him?

**Comment by reli21** [comment]
Fixed

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart!
