### ISSUE TITLE
[Seal of Righteousness] is not working properly. (all bugs included) - Verdict

### ISSUE THREAD

**Issue by svepi123** [SunstriderEmu/BugTracker#2728]
1. [Seal of Righteousness] is not having it's scaling as it should be.
2. Current behavior is 1:1 scaling from the **HOLY** damage granted by [Judgement of the Crusader].
3. [Vengeance] - Retribution tree: +5% Holy and Physical damage, stacks up the 3 times **DOES NOT** increase the damage.
4. [Sanctity Aura] - Retribution tree: 10% Increased holy damage **DOES NOT** increase the damage.
5. [Improved Seal of Righteousness] - Holy Tree: Not tested. Please do so if you may.
6. [One-Handed Weapons Specialization] - Protection Tree: Not tested. Please do so if you may.

**To Reproduce**
1. Cast [Seal of the Crusader]
2. Judge [Seal of the Crusader]
3. Cast [Seal of Righteousness]
4. Land hits.

For vengeance and sanctity aura just keep on auto attacking to see no results.

**Expected behavior**
[Seal of Righteousness] is a "two part" seal. Scales differently with One-Handers and Two-Handers.
In The Burning Crusade the seal has:
1h: 9.2% scaling for each 1.0 of weapon speed.
2h: 10.8% scaling for each 1.0 of weapon speed.
- If a weapon speed is of 1.9, it will not give scaling properly for the 0.9 of weapon speed that is left out. It will scale per 1.0 of speed.
- If a weapon is 2.1 it will scale as if it was 2.0 and so on... the numbers are always round.

**Screenshots/videos**
**OFFICIAL SCREENSHOT BY BLIZZARD'S DEVS FROM 2008**
![image](https://user-images.githubusercontent.com/37677233/78401729-0f7bb880-7602-11ea-9dae-335587fefb6e.png)

**Additional context**
There are A LOT of paladin bugs which I'll be covering asap, please look an eye out!

**Comment by mchayes** [comment]
Thanks for the hard work, recently rerolled away from tankadin/retri because of the severe amount of bugs. Was quite excited to play because of SoB on ally as well.

**Comment by Kevlarkent** [comment]
SoC stacks with 29% holy spell power (for example JotC)

**Comment by kealthas06** [comment]
At This Rate Paladin is literally Unplayable i am not sure [Argent Defender] Works as well you never see the icon Please Give Us a satisfying answer about this topic
