### ISSUE TITLE
Highland Mixed Schools in Terokkar not Spawning

### ISSUE THREAD

**Issue by tyshies** [SunstriderEmu/BugTracker#2730]
**Describe the bug**
Highland Mixed Schools pools in Terokkar Forest (45.3, 40.5) (46.3,40.0) and (47.9,402) are not Spawning at or and/or Respawning at their 3 minute respawn in accordance with https://db.endless.gg/?object=182957. Stood around for ~15 minutes while fishing and none spawned as they should.

**To Reproduce**
Stand at Lake Jorune for 10 minutes to observe 3 missed respawn cycles
**Expected behaviour**
Highland Mixed Schools should respawn in accordance with their 3 minute respawn timer with the Endless Database.

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago, thanks for the issue.
