### ISSUE TITLE
Client stops at connecing

### ISSUE THREAD

**Issue by bespidderen** [SunstriderEmu/BugTracker#2733]
**Describe the bug**
When i try and log in the client stops at connecting.

I've tried to download the client again. I've tried to turn off the firewall. Nothing works.
I had no problem logging in yesterday evening but this morning i the client stops at connecting at tells me it's unable to connect.

Can you help me with this?

**Comment by beraus** [comment]
As a temporary workaround you can use:
`set realmlist logon.endless.gg:6666`
or
`set realmlist 163.172.21.111`
