### ISSUE TITLE
Mage spellstealing lifebloom does not bloom

### ISSUE THREAD

**Issue by oldspices** [SunstriderEmu/BugTracker#2734]
**Describe the bug**

Mage spellstealing lifebloom does not bloom 
**To Reproduce**

go in bg, lifebloom yourself, watch mage steal it with no bloom effect.
1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

should bloom. 
**Screenshots/videos**

**Additional context**

pretty obv bug :)

**Comment by oldspices** [comment]
bump

**Comment by oldspices** [comment]
clear bug

**Comment by InhumanGM** [comment]
Upon attempting to reproduce the issue, I was not able to find any issues. Could you provide more information that could be used to try to reproduce the issue again?

**Comment by Kraizn** [comment]
Just adding a "proof" to this if someone is sceptical.
https://youtu.be/IB7bUNWTlh4?t=2370
