### ISSUE TITLE
Can't reset dungeons

### ISSUE THREAD

**Issue by Avatarstate** [SunstriderEmu/BugTracker#2736]
**Describe the bug**

Can't reset dungeons using the "Reset Dungeon" right click interface. When you attempt to reset, nothing happens. No error message, no nothing. 
**To Reproduce**

1. Attempt to reset dungeon by right clicking character portrait

**Expected behavior**

Dungeon should either reset or be returned with an error message if a player is currently in the dungeon.

**Comment by Godmatik** [comment]
Make sure your dungeon difficulty isn't set to heroic.

**Comment by Avatarstate** [comment]
Thank you! I think that was it :)
