### ISSUE TITLE
Wailing Caverns Naralex event doesnt spawn in waves 

### ISSUE THREAD

**Issue by robbom88** [SunstriderEmu/BugTracker#2738]
**Describe the bug**
After defeating all of the required bosses to activate the Naralex phase of wailing caverns, the two initial waves and the boss all spawn at once as opposed to two waves of enemies followed by the boss. 

**To Reproduce**
As far as I know, defeating the bosses in any order will cause this to happen when the final event is triggered. Not sure on any specific circumstances that trigger it.

Dungeon: https://classic.wowhead.com/wailing-caverns

Enemies:
https://classic.wowhead.com/npc=3654/mutanus-the-devourer

**Expected behavior**
The enemies are supposed to spawn in timed waves before the final boss appears.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
https://github.com/kelno/sunstrider/commit/381d08f4d9da0091ba932ed56b2a23ab899011de
