### ISSUE TITLE
[Shattered Halls] Can do Relog and run through the door to 1st boss

### ISSUE THREAD

**Issue by Fester90** [SunstriderEmu/BugTracker#2739]
**Describe the bug**

People can do relog being near door and after login they can run through door

****To Reproduce**
**

1. Stand near door to first boss on Shattered Halls
2. Do log out
3. Log in to the game 
4. immediately after log in try to run through door
5. [Bug] You're in on the other side at 1st boss chamber

****Expected behavior**
**

1. People shoudlnt be able to do shortcut by doing relog and start running through the door

**Screenshots/videos**

![WoWScrnShot_040420_153153](https://user-images.githubusercontent.com/63154384/78452713-22879a80-768d-11ea-89a0-776225956bc1.jpg)
![WoWScrnShot_040420_153059](https://user-images.githubusercontent.com/63154384/78452716-287d7b80-768d-11ea-92fb-83710739d327.jpg)
![WoWScrnShot_040420_153111](https://user-images.githubusercontent.com/63154384/78452718-29161200-768d-11ea-82e1-e6f58316a694.jpg)
![WoWScrnShot_040420_153128](https://user-images.githubusercontent.com/63154384/78452719-29161200-768d-11ea-9ea4-7b81941c0990.jpg)
![WoWScrnShot_040420_153157](https://user-images.githubusercontent.com/63154384/78452720-2a473f00-768d-11ea-9d60-8d0a019d7776.jpg)

**Comment by beraus** [comment]
This issue should be fixed now.
