### ISSUE TITLE
Insect Swarm not stacking

### ISSUE THREAD

**Issue by TheMoneyHater** [SunstriderEmu/BugTracker#2740]
**Describe the bug**
Insect Swarm from Balance druids dot don't stack.

**To Reproduce**
Cast Insect Swarm on the same target with two boomkins

**Expected behavior**
https://wowwiki.fandom.com/wiki/Insect_Swarm?oldid=1407337
The actual dot should be stackable just not the "miss % of other insect swarm." on the same target that is.

**Comment by z5n** [comment]
issue has since been fixed
