### ISSUE TITLE
Broken resp time rare elite Marticar (Zangarmarsh)

### ISSUE THREAD

**Issue by Faux12345** [SunstriderEmu/BugTracker#2741]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Faux12345** [comment]
His resp time about 2-3 min

**Comment by Sheikthecatman** [comment]
Thanks!
The issue has been resolved in [95e23309838950d61a0eec13c3bfc1c243230484](https://github.com/kelno/sunstrider-scripts/commit/95e23309838950d61a0eec13c3bfc1c243230484)
