### ISSUE TITLE
problem pet hunter

### ISSUE THREAD

**Issue by sanmorti** [SunstriderEmu/BugTracker#2744]
**Describe the bug**
I havent growl i was the pet trainer and nothing the same my pet the level down cant up level i have 30minutes kill mobs and nothing please help iam hunter beast master!--- Steps to reproduce the behavior. Note that providing as much details as possible will help us fix it faster! -->
1. Cast X on target affected by ...
2. hunter: sancaza 
3. 

Spell: https://classic.wowhead.com/spell=2649/growl

*Expected behavior**

i hope i can have the additional growl talent to be able to upload from nv to my pet
**Screenshots/videos**

https://ibb.co/BVDtKwD    
https://ibb.co/8j2vMNv
aditional context**

**Comment by Ironjudgment** [comment]
Use 'Beast Training':
![image](https://user-images.githubusercontent.com/33090790/78506506-cd718480-7771-11ea-82f8-9da5e86ad86e.png)

**Comment by Simon-GM** [comment]
Growl should be working as intended.
Please attempt to use the 'Beast Training' option as @Ironjudgment linked a picture of above.
