### ISSUE TITLE
Incorrect herbalism nodes in low level zones

### ISSUE THREAD

**Issue by marcindobry** [SunstriderEmu/BugTracker#2745]
**Describe the bug**
The herbalism nodes in low level areas are incorrect. In the alliance starting areas (seen in Teldrassil, Elwynn Forest) it's possible to find Mageroyal, which is only supposed to exist in the second zones like Westfall and Darkshore. In Westfall and Darkshore, the only herbs you can find are mainly Bruiseweed and sometimes Briarthorn. This makes it almost impossible to level herbalism past around level 60.

**To Reproduce**
Try and level herbalism using progression on blizz-like servers, it's almost impossible.

**Expected behavior**
You're not supposed to be able to find Mageroyal in starting areas. You're supposed to be able to find sub-100 level herbs in the second leveling areas.

**Comment by simuloid** [comment]
Can confirm peacebloom, silverleaf, and earthroot seem to be about 1/2 as common as they ought to be in Teldrassil.  I don't mind seeing a mageroyal in early zone, it rewards people for leveling their herbalism quickly.

**Comment by beraus** [comment]
This is should be fixed now.
