### ISSUE TITLE
[Quest] "The Challenge" can't obtain an item (Top Piece of Lord Valthalak's Amulet) 

### ISSUE THREAD

**Issue by MrJiraiya** [SunstriderEmu/BugTracker#2746]
**Describe the bug**
Can't get item (Top Piece of Lord Valthalak's Amulet) for "The Challenge" quest. 
Neither you can loot Theldren's corpse nor Chest with blue gear/quest item after the fight. 
Theldren (and other guys from his team) despawns immediately after killing him and you can't loot him. Chest dosn't spawn at all.

**To Reproduce**
1. After using banner and killing first wave of non-elites Theldren spawns in a specific place while his team run through the gates. Theldren's team despawns quickly after not joining combat and you can fight only Theldren.
2. After defeating Theldren he despawns immediately without leaving a corpse, so you can't loot him. After defeating all enemies their corpses despawn too.
3. No chest with loot spwaned in the end.
4. You get credit for defeating Theldren's Team, but you don't get Amulet to finish the quest.

Item: https://classic.wowhead.com/item=22047/top-piece-of-lord-valthalaks-amulet
Quest: https://classic.wowhead.com/quest=9015/the-challenge

**Expected behavior**
You should be able to loot Theldren's corpse for quest item; 
Or chest should be spawned and contain quest item after finishing the fight.

**Screenshots/videos**
video: https://www.youtube.com/watch?v=K9A01BQuLhw

**Comment by Sheikthecatman** [comment]
The item should now be obtainable in [ddc780eca69ad5a3c2f5d1a64ce429f6d29c66b4](https://github.com/kelno/sunstrider-scripts/commit/ddc780eca69ad5a3c2f5d1a64ce429f6d29c66b4)

**Comment by MrJiraiya** [comment]
Link doesn't work, but now you are able to loot Theldren
