### ISSUE TITLE
[General] food and drink

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#2747]
**Describe the bug**
Drinking or eating triggers on-use cd (0,5s) only for the particular food/drink item. Drinking or eating should trigger on-use cd for ALL items that grant you "Drink" or "Eat" buff. (respectively)

**To Reproduce**
1. Make macro with 3 different waters
2. Use macro and all 3 waters get used.

**Expected behavior**
Drinking or eating should trigger on-use cd (0,5s) for ALL items that grant you "Drink" or "Eat" buff.

**Additional context**
Ive seen this working correctly on classic and on warmane, but I will not look for a proof to support this, it is a minor thing and even if it was to be incorrect I still think its a great enhancement to the game.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by Jerrythemagicdog** [comment]
Thanks again for the report, issue appears to have been fixed since then (can't reproduce now, only one type of e.g. health-restoring food is used when put in a macro with multiple ones).
