### ISSUE TITLE
Potential for Brain Damage = High

### ISSUE THREAD

**Issue by Morphelin90** [SunstriderEmu/BugTracker#2748]
**Describe the bug**
The quest doesn't give you the quest item Ethereum Essence, when you abandon the quest to take it again and receive the quest items, you simply can't take it anymore.

**To Reproduce**

1. Take the quest "Potential for Brain Damage = High"
2. Abandon quest
3. Try to take it again

Item: https://wowhead.com?item=29482
Quest: https://wowhead.com?quest=10385

**Expected behavior**
The quest should give the items.

**Screenshots/videos**
Can't show it since I just can't take it the quest anymore

**Additional context**
/

**Comment by Navashed** [comment]
Wrong. Read the quest text. Ethereum Essence drops from the mobs in the area.

**Comment by InhumanGM** [comment]
> Wrong. Read the quest text. Ethereum Essence drops from the mobs in the area.

This is correct.
