### ISSUE TITLE
[Hunter] Pet Movement Speed

### ISSUE THREAD

**Issue by Lokajin** [SunstriderEmu/BugTracker#2749]
Pets are moving at a speed well under the player character when tamed. Pets movement speed at a minimum should be equal or greater than player characters. Tested it with player tames and quest tames through hunter class quest. All the pets were moving at a speed well under the player characters speed. Which causes the issue if you auto run to far ahead of your pet for it to get dismissed.

**Comment by Ironjudgment** [comment]
Can confirm. Without the 'Bestial Swiftness' pets do not keep up with normal running speed (outdoors and inside) and if the talent is spent, they still do not keep up while Aspect is active. However, I don't know if others have noticed but sometimes pets get like a slight boost to movement speed when sent to attack (I don't mean Dash/Dive).

**Comment by Jerrythemagicdog** [comment]
Perhaps the pet uses the available focus as soon as it becomes available and this is the result.
