### ISSUE TITLE
Hunter pet focus does not display correct focus amount - visual bug

### ISSUE THREAD

**Issue by lukas155** [SunstriderEmu/BugTracker#2751]
**Describe the bug**
Hunter pet focus will slowly tick down 2 at a time while in combat. Only gains focus through "Go for the throat" talent.

To Reproduce:
Send pet into combat.
Pet's focus will slowly tick down 2 focus per tick, and never passively regain focus.
Affects all hunter pets (that I'm aware of - only tested wind serpent and ravager)

**Expected behavior**
Pet's focus should regen, rather than degen. I cannot find a primary source for normal focus regen rate, but most secondary sources claim ~24 focus per 'tick' (every 5 seconds). This is increased by the Bestial Discipline talent.

**Comment by Ironjudgment** [comment]
I can't see this happening on my pet.

**Comment by lukas155** [comment]
I've only experienced this in 25 and 10 man raids. Will upload video tonight if I experience it again.

**Comment by lukas155** [comment]
Tested further - Visual bug only. Does not seem to affect pet abilities in any way.

https://youtu.be/1jqCSOiWMr0

As you can see, the pet is still casting lightning breath despite having less than the required amount of focus.
