### ISSUE TITLE
[World] Tram between Ironforge and Stormwind occasionally vanishes, leaving player in the middle of the tunnel.

### ISSUE THREAD

**Issue by Syfte-oss** [SunstriderEmu/BugTracker#2752]
**Describe the bug**
The title says it all.  Two days ago I was traveling from Stormwind to Ironforge when I suddenly fell through the train, which vanished.  This was shortly after leaving SW so it was a short run back.  Then today I saw someone complaining in /global about it happening to them (they didn't say what direction they had been traveling in) so I went back to try to record it.  The trip to SW was normal.  Then roughly 3/4 of the way to IF the tram vanished.

On a related note, I have never seen the second tram at either station.

**To Reproduce**
1. Get on the tram.
2. Get kicked off the tram at random.
3. The tram is still better a better deal than United Airlines.

**Screenshots/videos**
https://www.youtube.com/watch?v=h1GQkOgkhQs

**Comment by AgreeableNZ** [comment]
It only kicks you off if you move.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2007
