### ISSUE TITLE
Swift Flight Form 

### ISSUE THREAD

**Issue by frztw** [SunstriderEmu/BugTracker#2754]
Can't pick herbs in shapeshift flight form.
 

1. > Druid [https://endless.gg/changelog/2020/04/03](url)
> 
>     Fixed Druids being able to pick herbs while in Swift Flight Form and in the air - Druids will still be able to pick herbs if they're on the ground while shapeshifted. 

2. 

> **Release WOTL - Release date(s) November 13, 2008**
>  [https://wowwiki.fandom.com/wiki/World_of_Warcraft:_Wrath_of_the_Lich_King](url)

3. 

> Flight Form Revision as of **20:33, September 29, 2008 - it is TBC REVISION**
> 
> **you can loot, pick herbs and skin (but not mine!)** while 'sticking to the ground', when you're not 'flying'.
> [https://wowwiki.fandom.com/wiki/Flight_Form?oldid=1617441](url)

**Comment by TheMoneyHater** [comment]
This is already changed?

**Comment by Sheikthecatman** [comment]
Druids in Swift Flight Form are able to stand on the ground and pick herbs on the live server.
