### ISSUE TITLE
Swimming with a blood elf

### ISSUE THREAD

**Issue by knuper** [SunstriderEmu/BugTracker#2756]
Playing a paladin bloodelf, when swimming and after going deep into a lake or sea, the character can't swim up when using the space bar. It should reproduce the same behavior achieved when pressing both mouse buttons and aiming it at the surface. Instead it jumps as it would do on solid ground and in order to get out of the water you have to press the space bar multiple times.

**Comment by kelno** [comment]
Thanks for reporting!
That's definitely something client side and not something that no server can ever change
