### ISSUE TITLE
Bug reputation Sha'tar

### ISSUE THREAD

**Issue by champiipeipei** [SunstriderEmu/BugTracker#2757]
**Describe the bug**
Hello,
I have a problem with my Sha'tar reputation, i used 70+ fell aramament and sargeras mark like 250+ to get friendly to exalted so 6k+ 12k + 21k = 39k reputation.
In alliance it gave 424 reputation per fell armament on Aldor and 212 to sha'tar.

My problem is when i pop honored with sha'tar my reputation didnt move or change when i used marks + armament. So finaly im stuck at 155 honored its not normal i would be revered becose im missing 19 500 reputation.
You can look my character : https://endless.gg/armory/character/annhepburne

https://tbc-twinhead.twinstar.cz/?quest=10653 (Marks of sargeras)
https://tbc-twinhead.twinstar.cz/?item=29740 (Fell armament)

**Expected behavior**
I just want you gave me my missing reputation the 19 500 reputation on sha'tar or gave me back all the marks + fell Armament to use it again and upgrade sha'tar reputation. 

Thx

**Screenshots/videos**
https://zupimages.net/up/20/14/74ut.jpg

**Comment by Felynda** [comment]
"Until Honored
Reputation can be gained from Scryer/Aldor signet/mark turn-ins. The following will only grant Sha'tar reputation until you achieve Honored status:  Firewing Signet,  Sunfury Signet, and  Arcane Tome for the Scryers;  Mark of Kil'jaeden,  Mark of Sargeras, and  Fel Armament for the Aldor. In addition, these will require more turn-ins to produce equable Sha'tar reputation to the main faction. Note that this reputation gain does not show up in the combat log, but can be verified by looking at your reputation panel."

From: https://www.wowhead.com/faction=935/the-shatar

**Comment by champiipeipei** [comment]
> 
> 
> "Until Honored
> Reputation can be gained from Scryer/Aldor signet/mark turn-ins. The following will only grant Sha'tar reputation until you achieve Honored status: Firewing Signet, Sunfury Signet, and Arcane Tome for the Scryers; Mark of Kil'jaeden, Mark of Sargeras, and Fel Armament for the Aldor. In addition, these will require more turn-ins to produce equable Sha'tar reputation to the main faction. Note that this reputation gain does not show up in the combat log, but can be verified by looking at your reputation panel."
> 
> From: https://www.wowhead.com/faction=935/the-shatar

Plz watch my message, it didnt gave me reputation anymore. Im stuck at 155 honored when i gave Fell armament + sargeras marks. Look screenshot plz :)

**Comment by champiipeipei** [comment]
Any news from devs ?

**Comment by hufsa** [comment]
This only works until honored as stated in the answer above.

**Comment by AWIDIUS** [comment]
You can't obtain reputation with Sha'tar past honored with completing Fel armaments for Aldor. That works only to honored for Sha'tar.
