### ISSUE TITLE
Perception does not work properly

### ISSUE THREAD

**Issue by lorhdaron** [SunstriderEmu/BugTracker#2762]
This increases your detection by 10 levels (or close to that). Which means, if you're level 60 and a level 70 Rogue is prowling around, you will be able to see them if they come within 10yds of you.

This racial passive add to you +50 to your stealth skill ability

Actually, perception is too weak: 
- in arena/Bgs/Worldpvp, u can't even find a simple druid in stealth
- it works slightly in hand to hand fight 
- if you suceed to find someone in stealth, he constantly disappears for no reason

movies that shows it:

https://www.youtube.com/watch?v=eJWNMCD8SMU&feature=youtu.be&t=5m59s
( nelyo )
https://www.youtube.com/watch?v=dUVDBT9v66U&feature=youtu.be&t=2m55s
( here, he is able to see 15/20 yards behind pillars )

You can easily find externals topics from 2008 > Wowhead
(goggles/spec rogue pvp not included in this issue)

**Comment by Jerrythemagicdog** [comment]
Here's how stealth mechanics work on the server: https://wowwiki.fandom.com/wiki/Stealth_(mechanic)?oldid=1512438

You can easily test them by following the rules explained in the link.
