### ISSUE TITLE
Warlock pet gets despawned when logging off, hearthstonening etc.

### ISSUE THREAD

**Issue by Balanarr** [SunstriderEmu/BugTracker#2763]
**Describe the bug**
Warlock pet gets despawned when logging off, hearthstonening etc.

**To Reproduce**
Have a pet summoned
1. Relog
2. Use hearthstone
3. etc.

Pet gets despawned

**Expected behavior**
Pets should stay summoned

**Comment by Godmatik** [comment]
Same with Hunter pets

**Comment by z5n** [comment]
unable to reproduce
