### ISSUE TITLE
Pets (warlock at least) fall behind and don't stop next to the owner

### ISSUE THREAD

**Issue by Balanarr** [SunstriderEmu/BugTracker#2764]
**Describe the bug**
When the owner starts moving, pets follow from too far behind and don't catch up
When the owner stops moving, they don't stop right next to the left of the owner, the stop ~5 yards behind

**To Reproduce**
Have a pet summoned (at least the behavior for the warlock pets) and on follow
1. Move forward for a while and then stop

**Expected behavior**
Pets should follow closely the owner (if out of combat and fell behind should even speed up a bit to catch up with the owner)
Pets should stop right next to the left of the owner and not to the left and behind of him. If the pet was too far behind or forward should readjust to be to the left of the owner

**Screenshots from Classic**
https://imgur.com/a/U6moHo8

**Screenshots from Endless**
https://imgur.com/a/dgpHA7m

**Comment by Balanarr** [comment]
This could use some attention as the slow reaction of pets makes it harder to get them out of harm, leotheras for example if you move to not get hit by ww with pet following.

Also sometimes it's harder to pull some things off, like calling felguard back to use intercept. Because he stops a few yards away from the owner, if not far enough to account for this, you can't do it.

**Comment by z5n** [comment]
thanks for the issue, pet movement is being reworked and will be live after the next restart.
