### ISSUE TITLE
Certain actions remove shapeshift

### ISSUE THREAD

**Issue by thebuster** [SunstriderEmu/BugTracker#2765]
**Describe the bug**
Looting a container, using a potion or a buff scroll, looting a herb etc. removes druid's shapeshift skill

**To Reproduce**

1. Click on a quest container or use a potion whilst in cat or bear form
2. See the shapeshift being removed

**Expected behavior**
Shapeshift should not be lost when performing these actions

**Comment by oldspices** [comment]
potions 1000% should remove form when used, sigh.

**Comment by thebuster** [comment]
What about containers, herbing, mining etc.

**Comment by InhumanGM** [comment]
While mining, you will be removed from all shapeshift forms.
While gathering herbs, you must be on the ground, but you will not be removed from any shapeshift forms.
While opening a container, you will be removed from all shapeshift forms.
