### ISSUE TITLE
Cipher of Damnation chain

### ISSUE THREAD

**Issue by Jhasso123** [SunstriderEmu/BugTracker#2766]
Unable to speak to Oronok or Borak to begin the third fragment part of the quest chain. GM also sent me the quest but it will not let me complete it.

**Comment by AlastorTheBloody** [comment]
I would like to add to this. Completed all three cipher parts, handed in. Was unable to get last "The Cipher of Damnation" quest from Oronok.

**Comment by beraus** [comment]
Make a ticket in game and we'll check your progress.
