### ISSUE TITLE
[Warrior] Victory Rush does not grant killing blow

### ISSUE THREAD

**Issue by Denagul** [SunstriderEmu/BugTracker#2770]
**Describe the bug**
Killing a target using victory rush ~~or a victory rush hit from sweeping strikes~~ does not grant access to victory rush

**To Reproduce**
1. Kill target using victory rush
~~2. Kill target with secondary hit via sweeping strikes using victory rush~~
~~3. Neither of the two above methods will yield the ability to use victory rush~~

Spell: https://db.endless.gg/?spell=34428
https://db.endless.gg/?spell=12328

**Expected behavior**
Any killing blow should grant access to use victory rush regardless of ability used.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by Denagul** [comment]
Any word on this? Is there some further testing I could do to help?

**Comment by Bouargg** [comment]
Still nothing about this issue ? Any further requirement?

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
