### ISSUE TITLE
Hunter's Mark stacking

### ISSUE THREAD

**Issue by frztw** [SunstriderEmu/BugTracker#2772]
Hunter's Mark stacking with not full improving other hunter marks. Such as 5 hunters can use 5 marks : 0 improved, 1 , 2 ,3 ,4 , 5.  Please hotfix those shit.

**Comment by frztw** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/31289782/78510607-2f94ae80-779f-11ea-90d5-2f9ac03a8754.png)

**Comment by frztw** [comment]
[https://wowwiki.fandom.com/wiki/Improved_Hunter%27s_Mark?oldid=1536393](url)

**Comment by frztw** [comment]
Improved Hunter's Mark benefits all classes that use attack power when they attack the target the hunter has marked with it. Since it is low in the tree for a benefit that isn't limited to the hunter's party it is almost always preferred to Efficiency on the same tier. **There is no further benefit from having multiple hunters mark the same target since it does not stack. An Improved Hunter's Mark will overwrite a Hunter's Mark that is not improved by this talent. A higher talent Improved Hunter's Mark will overwrite a lower version.**

**Comment by Ironjudgment** [comment]
Are the marks actually active? It could just be a visual

**Comment by frztw** [comment]
![wo 2 marks](https://user-images.githubusercontent.com/31289782/78787696-6a6f3000-79b3-11ea-90d5-3eb231365936.png)
![with 2 marks](https://user-images.githubusercontent.com/31289782/78787703-6cd18a00-79b3-11ea-874b-e517fa1eaed0.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed after next server update.
