### ISSUE TITLE
The Big Bone Worm

### ISSUE THREAD

**Issue by Stolemyname1** [SunstriderEmu/BugTracker#2773]
While attempting to complete the quest The Big Bone Worm, only two of the three options appear when using the drum. Either the three gnomes appear, or the 3 worms, but never the required quest monster. After about 2 hours of attempts and nearly 100 monster spawns I have yet to see it. This problem was previously reported in Spetember so unsure what the cause is or how to reproduce.

Previously closed topic on this bug: [Quest] The Big Bone Worm #1175

**Comment by Godmatik** [comment]
Sounds like you got very unlucky. It spawned for me, but took about 20 tries. The success rate does seem very low.

**Comment by Jerrythemagicdog** [comment]
The chance is pretty low, we'll increase it, thanks.
