### ISSUE TITLE
Darnassus Silverwing Emissaries

### ISSUE THREAD

**Issue by Raizagal** [SunstriderEmu/BugTracker#2775]
**Describe the bug**
The Darnassus Silverwing Emissaries that patrol from the Temple of the Moon and back sink into the floor of the bridge.

**To Reproduce**
Periodically watch the NPC's patrol around the city.

**Expected behavior**
To not sink into the path they walk on. 

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago along with other pathing issues, thanks for the report.
