### ISSUE TITLE
Darkmoon Faire not open when it should be

### ISSUE THREAD

**Issue by limah-beans** [SunstriderEmu/BugTracker#2778]
**Describe the bug**
Darkmoon Faire is not active in either Mulgore, Stormwind, or Shattrath at the beginning of every month.

**Expected behavior**
The Darkmoon Faire is an event that appears in the game. The location of the Faire rotates monthly among three locations: Elwynn Forest, Mulgore, and Shattrath.

Setup takes the carnies three days; and the Faire opens early that Monday, and remains there for one week. Heralds in Ironforge and Orgrimmar announce the arrival of the Faire.

**Screenshots/videos**
Current view from Mulgore: https://i.gyazo.com/0ce755cb26fcf57a1ce19ba2a559d4dc.jpg
Current view from Elwynn: https://i.gyazo.com/1a4b092591e03b4237426ca5a3ff3f4a.jpg
Current view from Shattrath: https://i.gyazo.com/5fed06dfd33b4a4eff73bb6ac03eb678.jpg

**Comment by beraus** [comment]
This event is live in Terokkar forest at the moment.
