### ISSUE TITLE
Bug Paladin abilities

### ISSUE THREAD

**Issue by chorizogrande** [SunstriderEmu/BugTracker#2779]
**Describe the bug**
Exorcism and turn dead abilites does not work versus undead hordas , I am no sure if there are more of this problems yet

**To Reproduce**
I tried to use against  an undead horda and  it did not work 

**Screenshots/videos**
I did not take a screenshot when i was fighting  and i did not see another horda undead later

**Additional context
Those skills say you can use against any undead, so to me  suppose to work versus undead horda.

Thank you so much for you time

I hope this help to improve the game 

Thanks you  again

regards

**Comment by Godmatik** [comment]
Horde that are Undead are considered humanolds, it was set this way way back in Vanilla Beta.

Not a bug.

**Comment by chorizogrande** [comment]
So why they are call undead instead of humanoids? In that case the Pala is in disadvantage .
Never mind. Thanks

**Comment by chorizogrande** [comment]
It’s just strong enough to play pve

**Comment by Godmatik** [comment]
Ask Blizzard, that is the way it was designed.
