### ISSUE TITLE
[MAGE - TRINKET] Linken's boomerang cannot be used

### ISSUE THREAD

**Issue by Xze6431** [SunstriderEmu/BugTracker#2781]
**Describe the bug**
I'm actually trying to use a trinket : "Linken's boomerang"
But when I try to use it, I get an error message : "The spell is not available to you"
You can see it in below image 

I'm Mage level 70, frost spec, char name is Zxe (horde side).

**To Reproduce**
1. Equip "Linken's boomerang" item
2. Target an ennemy (can be any NPC as long as you can "attack" him).
3. You get the error message

Item: https://fr.classic.wowhead.com/item=11905/boomerang-de-linken
Quest: https://classic.wowhead.com/quest=3962/its-dangerous-to-go-alone

**Expected behavior**
The item can be used

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/63242239/78566571-b4bfa800-781f-11ea-9c71-9ab3ceef9297.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next server restart.
