### ISSUE TITLE
Unable to cast shadowform

### ISSUE THREAD

**Issue by Shablaya** [SunstriderEmu/BugTracker#2782]
sometimes when i cast holy spells during shadowform, and then i want to return into it, i got the "spell is not ready yet" message. Shadowform's icon become darker, making it not usable. Actually it happens only during bg or arenas. Also dying in bg doesn't fix that. Happened both when i used prayer of healing and binding heal.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by z5n** [comment]
issue has since been fixed
