### ISSUE TITLE
Mass Dispel

### ISSUE THREAD

**Issue by davidblainee** [SunstriderEmu/BugTracker#2783]
Mass Dispel currently has a .5 second cast time which wasn't the case until mists of pandaria.  Mass dispel should have a cast time of 1.5 seconds.
https://wowwiki.fandom.com/wiki/Mass_Dispel
As you can see here the only time the spell was a .5 second cast speed was in 5.3 and even then they removed mass dispel's ability to remove immunity effects like divine shield and ice block. This is making iceblock and divine shield extremely weak as you are globalled by the cast and can't do anything to prevent mass dispel from occuring.

**Comment by Godmatik** [comment]
Do you have the talent that reduces the cast time?
