### ISSUE TITLE
[Dungeon]  Mind control trotem in Sethekk does not work

### ISSUE THREAD

**Issue by Morskitar** [SunstriderEmu/BugTracker#2786]
**Describe the bug**
Mind Control totems casted by Time-Lost Controller does not work

**To Reproduce**
Fight with Time-Lost Controller in Sethekk

http://tbc.cavernoftime.com/spell=32764 (I know it's a private server but it use to works like this)

**Comment by Godmatik** [comment]
Confirmed, they don't do anything.

**Comment by Jerrythemagicdog** [comment]
Thanks, I've tried it locally after the fix and it works, please post here if there are still issues after a server update.
