### ISSUE TITLE
Combat log problem

### ISSUE THREAD

**Issue by JohnKelt** [SunstriderEmu/BugTracker#2787]
Hi, I have a strange problem. After using weapon chants (windfury, flametongue, etc.) information about the received and inflicted damage and heal received is no longer received in the combat log . This is not related to add-ons, data of the WTF and WDB folders, everything was deleted and turned off, and it is not a server bug since other shamans do not have such a problem. The most interesting thing is that this happens even if other people go to my character. The problem concerns only the character Lineage

**Comment by Godmatik** [comment]
Combat log is buggy in version 2.4.3 TBC client, make sure you are using a combat log fixer add-on.

**Comment by Jerrythemagicdog** [comment]
https://github.com/Schaka/CombatLogFix
