### ISSUE TITLE
Bugged pet pathing on arenas

### ISSUE THREAD

**Issue by mayday2013** [SunstriderEmu/BugTracker#2789]
**Describe the bug**
Pet cant follow the target on vertical obstacles like middle of ruins of lordaeron
**To Reproduce**

1. Enter RoLD arena
2. Run from one to other side of central pillar
3. Send pet to attack that target and see it running in circles

**Expected behavior**
Pet should be able to chase the target easily with no invisible obstacles
**Screenshots/videos**
https://www.youtube.com/watch?v=AnEFnsdDIGk&feature=youtu.be
**Additional context**
It happens on BEA also when you're attacking the target that jumps down or is running from ground floor to the bridge.

You can't properly dps with that pet pathing and can't stop the target from drinking, etc.

**Comment by Ironjudgment** [comment]
Can confirm, annoying :]

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago, thanks for the issue.
