### ISSUE TITLE
Mage Blizzard 

### ISSUE THREAD

**Issue by daft93230** [SunstriderEmu/BugTracker#2790]
Blizzard damage is split among targets in the blizzard instead of inflicting all blizzard damage to all targets in the blizzard
Doing a rank 7 blizzard on 40 targets deals only 60 damage per target, it's less damage than on wow classic

**Comment by daft93230** [comment]
Looks like it only happen on 20+ target , maybe its a normal things , someone know it ?

**Comment by Godmatik** [comment]
This is because of an AoE cap that all TBC servers have. 

Blizzard implemented a cap on how much damage you can put through AoE starting in TBC. The more targets you AoEing, the less damage you will do.

**Comment by daft93230** [comment]
thanks bro
