### ISSUE TITLE
Target swap as hunter auto shot issue

### ISSUE THREAD

**Issue by bjh368** [SunstriderEmu/BugTracker#2792]
When I am auto attacking something, and tab target (or left click) to attack a different target, my auto shot stays on the previous target, so only my steady shot is on the new target. Happens basically all the time. Very noticeable when I did Steamvaults and I couldn't dps the tanks properly on last boss. If I completely clear my target before I chose a new one, the problem is gone. It's only when I am attacking a target, and swap to a new one while my auto shot is active.

**Comment by Ironjudgment** [comment]
It doesn't really happen to me :S Have a video?

**Comment by bjh368** [comment]
Here is a clip https://clips.twitch.tv/TardyFriendlyPresidentMcaT

I start attacking the further one, then click once on the close one, while spamming a standard 3:2 macro. Notice how my white hits remain on the further one (the projectile is hard to see). And I hover the mouse over it to show that it really is taking damage, so no graphical bug. Excuse my absolute dogshit UI. It's a work in progress...

This is super easy to reproduce on my end, either by using alt tab or simply targeting with mouse as I did in the clip.

**Comment by Ironjudgment** [comment]
huh, intresting :D Whats the addon you use for the timing of shots?

**Comment by mchayes** [comment]
Still a big issue, it seems to occur when swapping targets and casting. Something like this. Really insane

**Comment by Ironjudgment** [comment]
Scrap that. Still an issue today.

**Comment by JoseMiguel15** [comment]
Still a big issue for raids.
Night Elf female hunter.

**Comment by kelno** [comment]
Fixed with next server update
