### ISSUE TITLE
[Horde] Deep Cover (Rogue Poison Quest) Taskmaster Fizzule Not Spawning

### ISSUE THREAD

**Issue by Dedryk** [SunstriderEmu/BugTracker#2795]
Taskmaster Fizzule is not spawning at the Venture Co. Tower. As a result, you cannot use the Flare Gun to complete the quest. I've waited an hour for the mob to spawn and it is definitely not spawning (at least after the latest server restart). When attempting the use the Flare Gun it says you cannot use that item without a target.

![Deep Cover Bug](https://user-images.githubusercontent.com/63270976/78619671-efd7d080-784b-11ea-8d8d-c26b7b2a6b99.png)

Related Information:

Item: https://classic.wowhead.com/item=8051/flare-gun
Quest: https://classic.wowhead.com/quest=2458/deep-cover

**Comment by beraus** [comment]
Should be fixed now.
