### ISSUE TITLE
Stratholme Dungeon Baron Event bugged

### ISSUE THREAD

**Issue by layalaa** [SunstriderEmu/BugTracker#2796]
1) The Bonespewer Adds infront of the Baron Endboss are wierdly connected to each other. Sometimes 3 Mobs coming at once and there is no time for recover after defeat, because new spewers are coming.

2) Once you killed all Adds the Door still won't open

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/3569
