### ISSUE TITLE
Stealth Level too low for Druids / Engineer Goggles Stealth detection too high

### ISSUE THREAD

**Issue by layalaa** [SunstriderEmu/BugTracker#2799]
As a Nelf Druid even with Improved Stealth through Spec and Racial Improvement its easily possible for a guy with engineer goggles to spot a druid in stealth around the big Pillar in Nagrand without losing sight. Which makes it impossible to open for a druid in stealth

**Comment by Jerrythemagicdog** [comment]
Please provide proof. Stealth mechanics are consistent with https://wowwiki.fandom.com/wiki/Stealth_(mechanic)?oldid=1512438
