### ISSUE TITLE
PvP Mage Dmg too high in general / too many Nova Procs

### ISSUE THREAD

**Issue by layalaa** [SunstriderEmu/BugTracker#2800]
Mage Damage in PvP is too high in general. Makes it Possible to Shatter oneshot crit a warrior with over 200 resilience.  Shatter crit even without Nova with 2,7k and 1,9k.

Nova Procs happen too often in general
1) while hitting the mage 
2) by abilities like blizzard  ect..

**Comment by Godmatik** [comment]
You offer zero evidence
