### ISSUE TITLE
Actual % crit seems lower than sheet % crit.

### ISSUE THREAD

**Issue by Shmilowitz** [SunstriderEmu/BugTracker#2802]
Did 3000 auto shots to test sheet % crit on ranged attack. I have 23.73% crit in sheet and ended with 18.5% crit after 3000 shots. 
![image](https://user-images.githubusercontent.com/14735830/78637793-63f59100-78ab-11ea-88a1-48b2df1bbd7a.png)

**Comment by Thorzovic** [comment]
Not only hunters... my rogue have 31% crit and sheets show like 24%...

**Comment by Thorzovic** [comment]
Not only hunters, its something wrong with melee and ranged crit chance. My rogue have 31% crit chance but recount shows something around 24-25% maybe feral crit aura is broken? idk.

**Comment by Kationt** [comment]
Not only hunter's problem, but when i tested it with my feral druid, I had same problem.
I had aprox 5% less crit, than I should have.

**Comment by Thorzovic** [comment]
Same with my rogue, adding screenshot from training dummy. 
23,30% crit chance / sheet shows something around 15% crit chance after 3000 swings. 
![crit rogue](https://user-images.githubusercontent.com/45541638/78654621-1423c380-78c5-11ea-82e9-05785444bd4f.png)

**Comment by Ironjudgment** [comment]
I did x2 1000 shots tests on my hunter:
![image](https://user-images.githubusercontent.com/33090790/78660346-d6bf3600-78c4-11ea-846f-ab6940e1058e.png)
![image](https://user-images.githubusercontent.com/33090790/78660373-dde64400-78c4-11ea-9cce-78f02ec07bed.png)

**Comment by Thorzovic** [comment]
Hi, result of my rogue with fully skilled weapons with no enchants like mongoose etc.  // 4000 autoattacks to training dummy. 
![ddddddd](https://user-images.githubusercontent.com/45541638/78674115-670c7380-78e3-11ea-9297-6871bd2bb41a.png)

**Comment by mayday2013** [comment]
Getting a crit as BM hunter with 18% of crit...Sometimes cant get it in 20 seconds, kek

**Comment by mchayes** [comment]
> Getting a crit as BM hunter with 18% of crit...Sometimes cant get it in 20 seconds, kek

"im unlucky" is anecdotal but yes, hard evidence is showing that crit is definitely bugged.

![image](https://user-images.githubusercontent.com/20542656/78757129-45ab9600-797c-11ea-916f-cd0d324bce27.png)

**Comment by Highdps** [comment]
![roga1](https://user-images.githubusercontent.com/47473127/78803067-d6a36100-79be-11ea-895e-31d14a220ebe.png)
![fury](https://user-images.githubusercontent.com/47473127/78803069-d905bb00-79be-11ea-938b-ceed0f34db09.jpg)
Rogue and Fury testing

**Comment by Highdps** [comment]
![WoWScrnShot_040820_174446](https://user-images.githubusercontent.com/47473127/78804683-bd9baf80-79c0-11ea-884b-029cc2480b62.jpg)

**Comment by Highdps** [comment]
I will update it by enh and feral screens when i force guildies to do tests

**Comment by Ironjudgment** [comment]
Another round of testing: 
![image](https://user-images.githubusercontent.com/33090790/78806128-30edf300-79ba-11ea-9369-84eab2858c61.png)

**Comment by Highdps** [comment]
![WoWScrnShot_040820_181127](https://user-images.githubusercontent.com/47473127/78807458-63045280-79c4-11ea-8760-16065af05750.jpg)

Seems like flat crit chance from LVL is not correct

**Comment by Highdps** [comment]
![retri](https://user-images.githubusercontent.com/47473127/78808617-fe49f780-79c5-11ea-9ea7-0200f2f9ebff.png)

**Comment by Jerrythemagicdog** [comment]
Please refer to: https://github.com/SunstriderEmu/BugTracker/issues/1530
keeping in mind that you're testing on a boss level target.

**Comment by kelno** [comment]
Current behavior is -4.8% for a target 3 level above you, which fits the observation here. 
I remember we researched that and didn't find any super strong proof for anything, so research is very welcome.

**Comment by Highdps** [comment]
mob lvl dosn't matter in crit roll dice.

**Comment by kelno** [comment]
After discussion we've decided to change it to a more reasonable 1.8% reduction. Applied with next restart.

I'll close this issue for now but if someones finds proof about how much it should be, don't hesitate to open a new one.
