### ISSUE TITLE
High King Maulgar Blindeye Heal

### ISSUE THREAD

**Issue by Mythogit** [SunstriderEmu/BugTracker#2803]
**Describe the bug**
For the High King Maulgar fight, the pattern the priest was casting his heals would go like this... Heal -> Shield -> Heal -> Prayer of Healing. We were having issues with interrupting the base heal because he is casting it right after the shield comes up. The Sequence is suppose to be Shield -> Prayer of Healing. The issue only happens on the 2nd Heal, everything else we had no problems interrupting.  

We tried using stuns to offset the timers, though that did not work. Best way to overcome this is to zerg through the shield and hope someone hits the interrupt right at 1.4s.

Mind-Numbing had not effect on the cast times of Heal or Prayer of Healing.

**To Reproduce**

1. Pull Blindeye
2. He cast first heal
3. Wait for Shield
4. He cast Heal right after shield

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
After he cast his Shield he should immediately always cast Prayer of Healing.

**Screenshots/videos**

**Additional context**

**Comment by Phoelol** [comment]
we had the same bug, thanks for the report

**Comment by Jerrythemagicdog** [comment]
Thanks, we've added more delay on the Heal after Shield, let me know if that solved the issue.
