### ISSUE TITLE
Healing part of drain life is causing threat

### ISSUE THREAD

**Issue by Balanarr** [SunstriderEmu/BugTracker#2804]
**Describe the bug**
The heaaling part of the drain life spell is causing threat to all mobs around

**To Reproduce**
1. Pull a pack of mobs with a pet. Have the pet only attack and have threat on 1 mob.
2.Cast drain life on the mob that the pet is damaging

Drain life healing causes threat on all mobs and they will come to attack the player.

**Expected behavior**
The healing portion of drain life shouls not cause threat or at least not to mobs that drain life is not damaging. Tested on classic too.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by Jerrythemagicdog** [comment]
Also: https://worldofwarcraft.fandom.com/et/wiki/Drain

> They heal as much as they damage the target, and only for as much as they actually caused. So even when the combat log says that your Drain Life hit for 100, the player may only had 50 health left, hence you will be healed for 50. Absorb effects, such as Shadow Ward, Ice Barrier, and Power Word: Shield, will cause life drains to do no healing, although they do damage the target. This form of healing is now affected by healing reducing effects such as Mortal Strike. **Their damage causes normal threat, whereas their healing does not generate any threat at all.**

**Comment by steak-house** [comment]
Related : drain life's heal is affected by bonus healing. It shouldn't be.

**Comment by Godmatik** [comment]
Confirmed.

https://www.wowhead.com/forums&topic=4250

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update. Regarding bonus healing: https://github.com/SunstriderEmu/BugTracker/issues/2415
