### ISSUE TITLE
Recipe: Insane Strength Potion

### ISSUE THREAD

**Issue by frastsytt** [SunstriderEmu/BugTracker#2806]
The recipe of Insane Strength is either ineligible to drop right now or it's pool of mobs that it drops from is incorrect. There hasn't been a single listing on it on the AH on both alliance and horde in the last two weeks. I've asked dozens of guilds and guild alchemists if they have it or have seen it, everyone is saying they haven't.
![image](https://user-images.githubusercontent.com/57603552/78681717-c1aecb00-78f5-11ea-855c-379b0c2d7591.png)
It's drop table should be **same as Haste Potion's**, but they are clearly not.

**Comment by Godmatik** [comment]
I think it is an incredibly low drop rate

**Comment by frastsytt** [comment]
![image](https://user-images.githubusercontent.com/57603552/78703264-8a024c00-7912-11ea-9460-68d66cde2a40.png)
Endless database shows these mobs are able to drop it, I don't know if they actually do. Either way it's only 10 mobs listed there when it should be possible to drop it from high level open world outland mobs, 5man normal mobs, 5man heroic mobs and raid trash.

**Comment by Jerrythemagicdog** [comment]
These are the drop chances from the following creatures on the live server:

```
ENTRY	CHANCE
16530	0.025
18420	0.03
19747	0.04
20864	0.01
21047	0.04
21301	0.07092
22291	0.04
23355	0.5
```

**Comment by frastsytt** [comment]
Right-o, I've done some autistic digging through web archives and I've found these website snapshots (Dated 2007/2008) suggesting the kind of mobs this recipe should be able to drop off.

The current droptable has:
3x 5-man mobs
1x Karazhan trash mob
2x Open world elite
2x Open world normal mob

https://web.archive.org/web/20071028071104/http://wow.allakhazam.com/db/item.html?witem=22903

![image](https://user-images.githubusercontent.com/57603552/78869473-5415b280-7a4d-11ea-8f49-71e5dd9f8c6a.png)


(Also note the comments where someone's said that they got it as a drop from a demon in Nagrand)

https://web.archive.org/web/20111202150043/http://www.wowhead.com/item=22903#comments

![image](https://user-images.githubusercontent.com/57603552/78869428-44966980-7a4d-11ea-949d-47aa4c05d688.png)

My point being, it shouldn't only be able to drop from *8* mobs only. Looks like it should be dropping from various open world mobs from Nagrand and up, both 5man normal and heroic trash and raid trash.

**Comment by frastsytt** [comment]
Also upon further investigation I'd like to note that npc Furnace Guards(22291) aren't even spawned yet since they are Ogri'la mobs. 
The total count of current mobs being able to drop it is really 7.

**Comment by Godmatik** [comment]
Great research, hope it gets updated.

**Comment by Jerrythemagicdog** [comment]
Thanks, increased the drop rate further.
