### ISSUE TITLE
[Quest] Captain Tyralius

### ISSUE THREAD

**Issue by Lysychooj** [SunstriderEmu/BugTracker#2807]
**Describe the bug**
Quest dont get done status after unlocking Captain.

Item: https://www.wowhead.com/item=29742/the-wardens-key
Quest: https://www.wowhead.com/quest=10422/captain-tyralius

**Expected behavior**
After looting that specyfic key, im heading to locked in prison captain Tryalius, and from now i can only use him and he **instantly** get unlocked yelling at me that he thanks but the status quest is still 0/1 . Today (07.04.2020) im do that like five time and always same reaction, relog log on nothing change, addon off/on nothing change. 
Watched like warrior do that quest and when he tried to unlock him , he started **casting** something like (unlock captain) and he telling me that he is done. 
When im try i dont cast , cant use key on that prison and cant done that quest. Just instanty unlocking him and 0/1 quest status.
Nick in game : Lysychooj
im a priest , my friend warlock got the same bug

**Comment by Jerrythemagicdog** [comment]
Thanks, could you try after next server update and see if the issue is resolved?

**Comment by Lysychooj** [comment]
13.04.2020 Still the same. Cant do that quest

**Comment by Navashed** [comment]
Had the same problem. I deleted my Cache folder in my TBC folder and it worked.
