### ISSUE TITLE
cant unlearn special shadowweave tailoring

### ISSUE THREAD

**Issue by erkmage** [SunstriderEmu/BugTracker#2808]
I cant unlearn my ability to craft shadowweave.

**Comment by Jerrythemagicdog** [comment]
Have you went to the trainer who taught you shadoweave tailoring originally? What's the name of your character in game? Thanks.

**Comment by erkmage** [comment]
Hi, my in game name is Erkmage, and yes i´ve been to the shadowweave tailor
specialist and i press unlearn and it says "cant do that right now!"

thanks!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfritt.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Den tors 9 apr. 2020 kl 06:10 skrev Jerrythemagicdog <
notifications@github.com>:
