### ISSUE TITLE
Lady Vashj quest item (possibly) not dropping again

### ISSUE THREAD

**Issue by aleksa0803** [SunstriderEmu/BugTracker#2809]
I got the questitem "Orders from Lady Vashj", started and accepted the quest, but abandoned it before I delivered it. Now the item appearantly wont drop again - it is said to have a very high droprate in Steam Vautls, but I haven't gotten it again after 3-4 runs. 

https://www.wowhead.com/item=24367/orders-from-lady-vashj
https://www.wowhead.com/quest=9764/orders-from-lady-vashj

**Comment by Godmatik** [comment]
Not sure where you read it has a high drop rate, I believe it is 1%

**Comment by aleksa0803** [comment]
It is definately not one percent. Every group I have done this with get it within the first 5 mob kills. Same with me, and that's my same experience from retail. See comments on: https://www.wowhead.com/item=24367/orders-from-lady-vashj

**Comment by Jerrythemagicdog** [comment]
The drop rate is at 2% for all of the nagas currently.

**Comment by Balanarr** [comment]
Seen it twice in 4 runs, last time was a few hours ago
