### ISSUE TITLE
Quest:´Getting Down to Business´ in Netherstorm CAN´T be finished

### ISSUE THREAD

**Issue by Skorlaa** [SunstriderEmu/BugTracker#2810]
As the title said - the Quest: Getting Down to Business in Netherstorm cant be finished if you did the Netherwind Questchain first.. got friendly with Netherwing and now i´m not able to collect the 8 Nether Dragon Essence from Netherdragons.. they are friendly.
I should be able to attack/kill these Dragons after set ´at war´ in reputation window.. but still not possible => Quest can´t be completed,

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/3182
