### ISSUE TITLE
School of Psychic Scream 

### ISSUE THREAD

**Issue by scriptpriest** [SunstriderEmu/BugTracker#2811]
Psychic Scream is a shadow spell on Sunstrider. 

**To Reproduce**
1. Cast Psychic Scream on a target with a lot of shadow resistance.
2. Note he resisted many times.

Proof of Sunstrider DB 
https://db.endless.gg/?spell=10890

**Expected behavior**
Psychic Scream must be a physical spell. It must therefore not take into account the target's shadow resistance.

**Screenshots/videos**
Archive WoWHead 
https://web.archive.org/web/20080307124021/http://www.wowhead.com/?spell=10891

**Comment by Ironjudgment** [comment]
https://wow.gamepedia.com/index.php?title=Psychic_Scream&oldid=1422242
Revision as of 17:36, 23 June 2008

**Comment by Ironjudgment** [comment]
https://wow.gamepedia.com/index.php?title=Psychic_Scream&oldid=434528
Revision as of 23:36, 20 January 2007

**Comment by Ironjudgment** [comment]
https://classic.wowhead.com/spell=8122/psychic-scream
Classic version is Shadow even.

**Comment by Ironjudgment** [comment]
https://wowwiki.fandom.com/wiki/Psychic_Scream?oldid=1418560 -> Shadow
Different source from wowiki
Revision as of 22:29, June 20, 2008

**Comment by scriptpriest** [comment]
https://youtu.be/PJl45upwiHE
At 3:52, Why did all the fears work on retail demo pet even with a shadow resistance buff then?

Your sources are no more reliable than mine.  Wowhead was always one of the references back then.

And i don't think that classic DB is'nt reliable.

**Comment by Ironjudgment** [comment]
Well, you posted the wrong link mate. You have posted the, I think, the trainer learn ability. Look at the 100yrd range and the effect is 

>Effect | Learn Spell  | Psychic Scream |  Psychic Scream 

 This is the actual skill: https://web.archive.org/web/20071216055422/http://www.wowhead.com/?spell=10890

It has corrrect range/mana cost/cooldown etc.

**Comment by scriptpriest** [comment]
You're right. But retail video remains a mystery.
