### ISSUE TITLE
I've been robbed

### ISSUE THREAD

**Issue by Nicolas20201** [SunstriderEmu/BugTracker#2812]
hello gms good night this cucked person stole my materials to love me mongoose, I spent 600 gold buying the materials and when I gave him the materials by trade, he ignored me and disconnected. Please I need to be banned or things returned to me please, I had a hard time putting everything together, I have photos if you need, thank you very much, I need an urgent response.
![WoWScrnShot_040720_232845](https://user-images.githubusercontent.com/62623540/78740009-f178c580-792b-11ea-9c63-1f763ac6cbcf.jpg)
![WoWScrnShot_040720_235349](https://user-images.githubusercontent.com/62623540/78740012-f473b600-792b-11ea-90df-f388afe7257a.jpg)
![WoWScrnShot_040720_235352](https://user-images.githubusercontent.com/62623540/78740014-f6d61000-792b-11ea-8ff6-928fcbe89ebb.jpg)
![WoWScrnShot_040720_235409](https://user-images.githubusercontent.com/62623540/78740018-f89fd380-792b-11ea-952c-c9407121df3e.jpg)
![WoWScrnShot_040720_235413](https://user-images.githubusercontent.com/62623540/78740020-f9d10080-792b-11ea-8dc0-e1dfdb01fbb0.jpg)
![WoWScrnShot_040720_235422](https://user-images.githubusercontent.com/62623540/78740023-fb9ac400-792b-11ea-9266-382d7cedc693.jpg)
![WoWScrnShot_040720_235424](https://user-images.githubusercontent.com/62623540/78740028-fd648780-792b-11ea-8e54-2a2664e29388.jpg)

**Comment by xEnvoy** [comment]
they wont do anything about ingame interactions

**Comment by Godmatik** [comment]
He's been doing the same thing to people wanting spellstrike, scamming them out of materials. Someone had clear video proof of it too: 

https://www.youtube.com/watch?v=-ZeHOUd9vQQ

A literal cancer individual, it's a shame GMs won't do anything about it.

**Comment by Nicolas20201** [comment]
> Ha estado haciendo lo mismo con las personas que quieren un hechizo, estafándolas con materiales. Alguien tenía una prueba clara en video de eso también:
> 
> https://www.youtube.com/watch?v=-ZeHOUd9vQQ
> 
> Un individuo con cáncer literal, es una lástima que los GM no hagan nada al respecto.

If you watch the video, it's the same person who steals my Cucked, they should ban him.

**Comment by Nicolas20201** [comment]
https://endless.gg/armory/character/cucked 

this is the pj that steals

**Comment by Godmatik** [comment]
Some good news, he was banned.

**Comment by Nicolas20201** [comment]
> Algunas buenas noticias, fue prohibido.

good to know, he deserved it

**Comment by Jerrythemagicdog** [comment]
Please keep this board to in-game issues not player interaction problems.
