### ISSUE TITLE
PET COMMAND SCREEN BUG

### ISSUE THREAD

**Issue by burakiyaniki** [SunstriderEmu/BugTracker#2813]
**Describe the bug**
 My pet bar skills are disappeared.  I cannot control my pet he is on passive now. And there is not any command at my pet bar screen for like follow  , defend , agressive 
![WoWScrnShot_040820_095143](https://user-images.githubusercontent.com/63337218/78753940-54e01300-797f-11ea-9233-db49dbbadc08.jpg)

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by mayday2013** [comment]
happens sometimes, should have been fixed a while ago, but still happens. dismiss pet and call it back

**Comment by burakiyaniki** [comment]
bro I'm not a fucking dump. I already done this 50 times before opening a post here. It is serious problem. I cannot play with my hunter now. Also my pet's are gaining focus also. Please stop nonesense comments.

**Comment by Jerrythemagicdog** [comment]
Do you remember at all how this happened? Did you stable your pet? Any details would help, thanks.

**Comment by mayday2013** [comment]
okay, BRO, liste, BRO, go to the stable master BRO and put your pet in there BRO, did you try this, BRO?

**Comment by burakiyaniki** [comment]
I did I puted my pet stable master , then taken him back. It is not worked.  When I tame the new pet , commands are coming , but the pet that I tamed is not earning focus , a bit weird. Pet system of my character is totally bugged.  This is happened 2 days ago. Alliance killed me near of area52 I released my corpse then all my pet commands are disappeared.

**Comment by bisquiit** [comment]
press CTRL + 2 by default 
and u can see it. 

ctrl 1 is attack 2 come back 3 stay.

**Comment by burakiyaniki** [comment]
Man don't u see that my ctrl - 2 command there is a growl. Where is others ???!!! . Please stop write nonesense comments.

**Comment by bisquiit** [comment]
people trying to help you but you cant help someone who is like this. This is not an issue for evryone who has a bit of XP in the game.
its not gamebreaking.

**Comment by burakiyaniki** [comment]
I understand I thank them for their help but I'm already asked about this in general chat and people like you already gave all advices that you guys gonna gave. None of them worked this is why I opened a post here. You cannot help about this only game masters can fix it. Now I cannot play with my hunter.

**Comment by burakiyaniki** [comment]
https://www.reddit.com/r/lightshope/comments/as1o40/experiencing_a_very_weird_bug_with_hunter_pet_bar/egr4fd0/?context=8&depth=9 , there is someone who had this problem at official forums.

**Comment by burakiyaniki** [comment]
5 days past and I cannot play with my hunter please help!!!!!!!!!!!!!!!!!!!

**Comment by mayday2013** [comment]
Sorry, but I don't have any idea how to help you.

I'd say - tame new pet if you don't have any problems with other of your pets.

**Comment by kelno** [comment]
Thanks for reporting:
I didn't find the actual cause but I made a failsafe to reload the default pet bar if that happens for any reason.
Applied with next update.
