### ISSUE TITLE
Sweeping strikes armor calculations on auto attacks

### ISSUE THREAD

**Issue by Pinju1** [SunstriderEmu/BugTracker#2814]
Current behavior: 
Sweeping strike damage from auto attacks seem to have a secondary armor calculation on the sweeped target (lower damage on alternate target of same armor value). Which makes me believe that sweeping strikes damage from auto attacks gets a double armor penalty.

Expected behavior: 
Sweeping strike damage should be the same on both targets (considering equal armor values). 

Steps to recreate issue: 
Pull 2 mobs as a warrior with sweeping strikes, auto attack for sweeping strikes duration, see that the secondary target receives way lower damage (around 30-40%, depending on the mob armor values).

id's:
https://tbc-twinhead.twinstar.cz/?spell=12328

Notes: This double penalty does not apply to Cleave or Heroic strike (auto attack replacements)

**Comment by Smashyxgod** [comment]
Also execute is doing 0 damage even if both targets are 20%

**Comment by kelno** [comment]
I see it, there seems to be a new issue there.

**Comment by kelno** [comment]
Broken with https://github.com/kelno/sunstrider/commit/8aa47321104a0205065d498626b28f4b02682551

**Comment by kelno** [comment]
Fixed with next update tomorrow morning
