### ISSUE TITLE
Parry haste for players does not work

### ISSUE THREAD

**Issue by Pinju1** [SunstriderEmu/BugTracker#2815]
**Describe the bug**
After parrying an attack, a person's next auto attack swing should be up to 40% faster (if there's less than 40% of the swing timer left, after parrying an incoming attack, the outgoing attack should be instant). This currently does not work for players.

**To Reproduce**
Play a melee class with the ability to parry, track your weapon swing timers, see that parrying attacks by no way change your swing timer. 

Spell: https://tbc-twinhead.twinstar.cz/?spell=3127

**Expected behavior**
After parrying an attack, a person's next auto attack swing should be up to 40% faster (if there's less than 40% of the swing timer left, after parrying an incoming attack, the outgoing attack should be instant). This currently does not work for players.

**Additional context**
This makes melee classes, especially warriors much weaker than they should be in melee combat.

**Comment by Denagul** [comment]
This worked for a while after it was enabled in the Tuesday March 3rd changelog, but has been broken for about 1-2 weeks now.

**Comment by kelno** [comment]
Thanks!
Fixed with next update

**Comment by Pinju1** [comment]
Still doesn't work after today's update (04-10)

**Comment by kelno** [comment]
Can you detail what test you're doing there?

**Comment by Pinju1** [comment]
I didn't bother using any swing timer because when you're using a slow 2hander, the parry haste should be VERY apparent, and it's not happening at all, even e.g when I farmed multiple low level mobs at once where parries are abundant

**Comment by kelno** [comment]
Okay I'll check again, thanks

**Comment by kelno** [comment]
It's definitely way faster when you parry.

**Comment by Pinju1** [comment]
https://www.youtube.com/watch?v=msmpkZawsEY&feature=youtu.be

In this video parryhaste is apparent, now it's happening. However, it doesn't seem to be reducing as many swing times as it should be, assuming the mob count and the amount of parries.

https://www.youtube.com/watch?v=Qn2lNVdAse4

In this video, with a smaller amount of mobs, you can notice the parries individually more. However, parryhaste isn't happening on every parry, and only seemed to happen once at the 45th second mark (right before I stopped the video)

**Comment by Pinju1** [comment]
Actually, rewatching the videos, I've noticed that parryhaste only activates once the swing timer has less than 40% remaining, this is probably the issue.

**Comment by kelno** [comment]
The way it currently works is the following
At more than 60% swing left : **remove 40% of total swing time**
Between 40% and 20%: **remove 20% of total swing time**
Under 20%: **no effect**

The example you give seems correct to me as well and fits the current rules.

**Comment by Pinju1** [comment]
https://youtu.be/msmpkZawsEY?t=39
If you pause the video at 39 secs, you can see a parry happening on the scrolling combat text. However, the swing still goes it's full duration.

**Comment by Pinju1** [comment]
There's still something weird, it doesn't always work

**Comment by kelno** [comment]
Okay, I really don't see an obvious issue right now but we can re open this one until more data is provided.
I think testing could be done in a more obvious case with less attacks being done to make it easier to analyze.

**Comment by Pinju1** [comment]
Sorry, i forgot to add a video last night. https://youtu.be/EebLw3Opec8?t=77

New recording, at 1:17 onwards, you can see 2 attacks being parried with no swing timer reduction whatsoever.

**Comment by Pinju1** [comment]
https://www.youtube.com/watch?v=VZ0zkuji9uA&feature=youtu.be

**Comment by kelno** [comment]
Thanks it's very obvious on that first video, I can work with that!

**Comment by kelno** [comment]
I found another big issue, fixed with next restart!

**Comment by Pinju1** [comment]
Seems to work fine now, thank you:)

**Comment by Pinju1** [comment]
I've noticed that parries from special attacks do not trigger parryhaste, only works on white attacks right now.

**Comment by kelno** [comment]
Thanks, updated again

**Comment by Pinju1** [comment]
I don't know if this was supposed to be fixed already, but still doesn't work when parrying special attacks

**Comment by kelno** [comment]
Alright we'll check again

**Comment by kelno** [comment]
Updated again with next server update

**Comment by Pinju1** [comment]
Broke after last update:
https://www.youtube.com/watch?v=Ib9axLewGeM&feature=youtu.be
