### ISSUE TITLE
QUEST: Klaven's tower (rogue quest)

### ISSUE THREAD

**Issue by thepatokbreado** [SunstriderEmu/BugTracker#2816]
**Describe the bug**
I've the Key for the chest in the top of the tower and i can't use the key.

Item: https://classic.wowhead.com/item=7923/defias-tower-key
Quest: https://classic.wowhead.com/quest=2359/klavens-tower

**Expected behavior**

Open the chest and get the "Klaven Morthwake's journal". https://classic.wowhead.com/item=7908/klaven-mortwakes-journal

**Additional context**

It suposes to click the Key and open the chest. But the chest is always locked.

**Comment by Jerrythemagicdog** [comment]
Did you still have the quest active at the time of trying to open up the chest or did you maybe end up abandoning it?

**Comment by barrycann** [comment]
Heads up. You need to use your "Pick Lock" skill to open the chest and the skill must be at 70. It's incredibly misleading that they have you get pickpocket the key. You don't need the key at all.
