### ISSUE TITLE
Disconnected from the serv

### ISSUE THREAD

**Issue by Macumbafeh** [SunstriderEmu/BugTracker#2817]
I have experienced 2 disconnections : 
- enterring in a bg when you are on fly path

- Use drood's fly form fastly when you just finished the fly path

Just wanna tell you that.

Macumba

**Comment by Ironjudgment** [comment]
Can confirm that while you are flying via flight master and try to enter BGs, you get disconnected. Additionally, you are dismounted when you leave BG and you can fall to your death if you were on your flying mount.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by Jerrythemagicdog** [comment]
Resolved some time ago.
