### ISSUE TITLE
Account ban

### ISSUE THREAD

**Issue by Desistonboard** [SunstriderEmu/BugTracker#2818]
Since i reached level 70, i have been spaming BGs. This morning (04/08/2020) i received an automatic ban account for the reason "Botting in BG", when I was playing normally.
I don't know if it could be due to some kind of addon that I use:

![Addons-1](https://user-images.githubusercontent.com/63353869/78790818-5aede800-79af-11ea-8ba2-e33d35d5e5cc.PNG)

![Addons-2](https://user-images.githubusercontent.com/63353869/78790823-5de8d880-79af-11ea-994f-3240ff9b5ee6.PNG)

If it is possible, I would like to know what the proofs or reasons for the ban are.

Nick in the game Desist.

Regards.

**Comment by Godmatik** [comment]
This place is for reporting in-game bugs, your better option is to contact a GM on discord or through ticket in-game

**Comment by Phoelol** [comment]
I remember the char desist being active in bgs. Nevertheless the bug tracker is the wrong platform to address this issue.
I assume u are writing someone directly in Discord and asking for these details.
