### ISSUE TITLE
Tablet of the Seven

### ISSUE THREAD

**Issue by EndLee** [SunstriderEmu/BugTracker#2820]
**Describe the bug**

There is supposed to be a tablet to pick up in the Ruins of Thaurissan but after spending quite some time waiting for it to spawn, it doesn't.

**To Reproduce**

1. Grab the quest from Maxwort Uberglint in Burning Steppes
2. Go to 54,40
3. There is no tablet to click in front of the statue.

Item: https://classic.wowhead.com/item=11470/tablet-transcript
Quest: https://classic.wowhead.com/quest=4296/tablet-of-the-seven

**Expected behavior**

There is supposed to be a tablet in front of the statue to click to be able to complete the quest.

**Screenshots/videos**

https://i.imgur.com/30pRq7i.jpg

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2458

**Comment by Jerrythemagicdog** [comment]
Fixed on next restart, thanks!
