### ISSUE TITLE
Paladin's "Light's Grace" bugged

### ISSUE THREAD

**Issue by Luigizzor** [SunstriderEmu/BugTracker#2824]
When not fully talented, the Paladin's Holy tab's "Light's Grace" is not working properly. When casting Holy Light and the talent proc's and give the buff, and if the next cast would NOT proc the buff, it REMOVES the previous one.

Steps to Reproduction:
-Talent 2/3 on Light's grace
-Cast Holy Light until Light's Grace buff proc's
-Upon next Cast if it wouldnt trigger talent buff, it WILL remove the buff as it is. 

It ruins the talent if it is not fully talented.

**Comment by Aeded** [comment]
XD
