### ISSUE TITLE
(QUEST) Investigate the Alchemist Shop Mage quest

### ISSUE THREAD

**Issue by sorryouken** [SunstriderEmu/BugTracker#2825]
I'm not sure if it is bugged or I'm just doing it wrong. I'm using the cantation of  manifestation and nothing is spawning.

**Comment by Simon-GM** [comment]
**1st video shows how it should work:**
https://youtu.be/Prtyv4cTvd8

**2nd video shows how it currently works:**
https://youtu.be/xyrM6ZE4QIA

**Comment by miazbikowski** [comment]
I'm hitting the same bug. Can't advance on my mage since this quest won't spawn any enemies.

**Comment by Zsadist85** [comment]
Is there a fix for this?

**Comment by Jerrythemagicdog** [comment]
Fixed with next update thanks.
