### ISSUE TITLE
[Quest] A Thousand Worlds

### ISSUE THREAD

**Issue by beraus** [SunstriderEmu/BugTracker#2829]
**Describe the bug**

Quest not available.

**To Reproduce**

1. Take starting quest "Seek Out Ameer"
2. Get a Consortium reputation to Revered
3. Try to get "A Thousand Worlds" 

**Expected behavior**

Should be able to take "A Thousand Worlds" at revered with Consortium

**Additional context**

Quest progression: 
https://wow.gamepedia.com/Ethereum_Secrets

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2501

**Comment by Jerrythemagicdog** [comment]
Quest wasn't available until a few months ago when daily quest hubs were released. The quest progression mistake was also corrected in: https://github.com/SunstriderEmu/BugTracker/issues/4040
