### ISSUE TITLE
[Botanica] High Botanist Freywinn

### ISSUE THREAD

**Issue by Denagul** [SunstriderEmu/BugTracker#2830]
**Describe the bug**
The Bridge leading up to the boss has poor pathing and collision causing any NPCs to go under the bridge resulting in evasions and hunter pets not helping out often.

**To Reproduce**
1. Pull High Botanist Freywinn
2. Tank him on the closer half of the bridge
3. Let him spawn plant adds (both small periodic ones and the adds spawned in tranquility phase)
3. Plant adds + hunter/warlock pets cannot find proper pathing about 70% of the time.

https://db.endless.gg/?npc=17975
https://db.endless.gg/?npc=21558

**Expected behavior**
The bridge should be solid ground to stand on for NPCs, not just for players.

**Additional context**
Likely Heroic mode is affected as well, i included IDs of him on both normal and heroic, sorry if it's just normal mode that is bugged.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed a long time ago along with other pathing issues.
