### ISSUE TITLE
Creatures chase you regardless of flying

### ISSUE THREAD

**Issue by Denagul** [SunstriderEmu/BugTracker#2832]
**Describe the bug**
Hostile creatures aggroing to you while flying follow you through the air, glitching.

**To Reproduce**
1. Be on a flying mount
2. Come close enough to aggro melee/ranged creatures
3. Run away from them by gaining altitude and/or moving away while at higher altitude than their melee/ranged range

Seems like all creatures

**Expected behavior**
Melee creatures should follow lightly by staying on the ground and never flying to you.
Ranged creatures should try and attack you if you are in range of their Shoot or signature spell such as fireball, then, if out of range, they should follow same rules as melee creatures, until they get back in range 

**Additional context**
This wasn't a bug before, it now is as of April 9th 2020.

**Comment by artieau** [comment]
Fixed
