### ISSUE TITLE
[Botanica] Plants before Warp Splinter

### ISSUE THREAD

**Issue by Denagul** [SunstriderEmu/BugTracker#2833]
**Describe the bug**
Non-elite plants just before Warp Splinter often have bad pathing/evading patterns when aggroed to anyone on the bridge going to Warp Splinter's room

**To Reproduce**
1. Pull one pack of plants
2. Healer or any other ranged aggro on a few plants
3. Try hitting some plants that stand still and are aggroed to healer

**Expected behavior**
The creatures should find the proper pathing to get to people standing on the bridge

**Additional context**
They become unstuck if the person the plants are aggroed to comes directly on top of each of the plants, until then, they evade.
PS: Forgot the exact name or ID of the creatures.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed some time ago along with other movement issues.
