### ISSUE TITLE
Holy resistance PVP due to #1909

### ISSUE THREAD

**Issue by Atrecom** [SunstriderEmu/BugTracker#2834]
Okey. Hello ppl.
Let`s start a discussion should Holy spells be resisted or not?
Ofc in PVP

#1909 is written it`s not. What do u think?
https://sun9-71.userapi.com/c858220/v858220461/1bf069/AE6UtwZb_4U.jpg
https://endless.gg/armory/character/trollwarrog

**Comment by Jerrythemagicdog** [comment]
You're mistaking fully resisting a spell (for example due to not being hit capped) and partially resisting a spell's damage which is what https://github.com/SunstriderEmu/BugTracker/issues/1909 is about.

**Comment by Atrecom** [comment]
Okay. U r wrong

**Comment by kelno** [comment]
What's special with Holy is that you can't have holy resistance stats, which means you shouldn't see partial resists of holy spells in PvP.
The base spell hit chance still applies.
