### ISSUE TITLE
[The Steamvaults] Bad pathing before 1st boss

### ISSUE THREAD

**Issue by Denagul** [SunstriderEmu/BugTracker#2835]
**Describe the bug**
NPCs hostile + friendly pets sometimes go underneath the texture on the ramp before the 1st boss

**To Reproduce**
1. Pull naga and tank them around the ramp leading to the 1st boss room
2. Walk/kite them around until 1 or 2 of them go underneath textures

Any NPC seems to be affected.

**Expected behavior**
The ground should be solid to walk on

**Comment by Jerrythemagicdog** [comment]
Fixed a long time ago, thanks for the issue.
