### ISSUE TITLE
Arena Treasure Chest

### ISSUE THREAD

**Issue by Ownedbyimba** [SunstriderEmu/BugTracker#2836]
А chest does not appear in the Gurubashi Arena (Arena Treasure Chest), which gives the quest.
https://classic.wowhead.com/object=179697

The chest should appear every 3 hours (0-3-6-9-12 AM / PM).
Today there was even a disconnect just at 6:00, the chest also did not appear.

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/3384
