### ISSUE TITLE
In Hellfire Ramparts dungeon i can't open the box after last boss. It said "invalid target". So i have lost my budget of justice for a second time :(

### ISSUE THREAD

**Issue by Corya0519** [SunstriderEmu/BugTracker#2839]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
I'm not able to reproduce, could you provide more details? Did you wipe during the fight? What race is your character?

I've removed something that could potentially cause issues, please let me know here if the issue still happens.

**Comment by Corya0519** [comment]
I did not die during the fight. I'm a tauren druid tank. Thank you! I will
test it soon!

Jerrythemagicdog <notifications@github.com> ezt írta (időpont: 2020. ápr.
10., P 8:36):

**Comment by michaelkittrell** [comment]
i multiboxed ramparts 3x in a row none of my chars could ever loot the chest.  Thats 15 chances not once could i loot.  I cleared my caches on all 3 pc's.
