### ISSUE TITLE
Issues with Allegiance to Scryer rep reward

### ISSUE THREAD

**Issue by krotlum** [SunstriderEmu/BugTracker#2841]
**Describe the bug**
Missing the reputation with Scryers from the quest Allegiance to the Scyers

**To Reproduce**
I just noticed that I'm not friendly as expected even though I've done the quest-chain to pick an allegiance with aldor/scryer.

Double checked Haggard war veteran, Khadgar and A'dal and none of them can give me a quest.

https://www.wowhead.com/quest=10552/allegiance-to-the-scryers

**Expected behavior**
Expect to be friendly with scryers after having done the chain

**Comment by krotlum** [comment]
This is on the character "Rymdkossa"

**Comment by Jerrythemagicdog** [comment]
Your character is a Draenei which means you get bonus reputation with Aldor (as a racial bonus) and more negative starting reputation with Scryers. This result is expected.
