### ISSUE TITLE
the quest 'Kindness" BUG

### ISSUE THREAD

**Issue by doommonster** [SunstriderEmu/BugTracker#2843]
**Describe the bug**

no matter how many corpses you put on the ground doesn`t work i know at least 20 ppl with the same problem
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2549
