### ISSUE TITLE
Bug with <Made by (character_name> on crafted items

### ISSUE THREAD

**Issue by atmichalak** [SunstriderEmu/BugTracker#2845]
**Describe the bug**
My soulbound crafted hammer, Drakefist Hammer, is missing the <Made by (character_name)> affix.
I have two of them, one of which has the affix while the other does not.

**To Reproduce**
Craft Drakefist Hammer and discover it may or may not apply the affix.

Item: https://www.wowhead.com/item=28437/drakefist-hammer
Spell: https://www.wowhead.com/spell=34545/drakefist-hammer

**Expected behavior**
After crafting the hammer, I expected to see the affix of <Made by (character_name)> applied to the newly crafted weapon.

**Screenshots/videos**
https://imgur.com/a/TWZaqQg

**Additional context**
One hammer has the affix and the other does not.

**Comment by z5n** [comment]
issue has since been fixed
