### ISSUE TITLE
Premade BG que times.

### ISSUE THREAD

**Issue by yougocry** [SunstriderEmu/BugTracker#2847]
**Describe the bug**
Hey there!

It seems like something got messed up with raid group BG que's.

We tried to que as full, as 10, as 12, ques just not popping.
Also it sais  AVG wait time: 1 day 21 hours?! 
Possibly something got bugged, bg's unplayable on horde side like this.

Please have a look it might just needs a restart or so. :)

Thank You in advance,
Yougocry

**To Reproduce**
https://i.imgur.com/eVdGkim.jpg
https://i.imgur.com/kz6w98A.jpg

**Expected behavior**
BG ques were always poppin in less than 1 minute, 

**Screenshots/videos**
https://i.imgur.com/eVdGkim.jpg
https://i.imgur.com/kz6w98A.jpg

**Additional context**
fix it please, bg's are unenjoyable without premade joins.

**Comment by yougocry** [comment]
https://i.imgur.com/rJ0BWHr.jpg
still nothing changed.

**Comment by kelno** [comment]
Thanks for reporting.
The average wait time is a new bug that's going to be fixed next crash.
About groups, the server tries to match you with other bg groups, this might have been broken before and started working with a new change. I disabled this feature, active as of now (no restart needed).

If there is still issues wait for next crash, and update me here if it still an issue.

**Comment by hanbi-wow** [comment]
Still broken, no pops for premade.

**Comment by Ticketdudu** [comment]
I queed many times as 5-10 player premade on alliance side. It works perfectly (ofc it takes a bit longer). I did 2 13 and 15 player premades, it took way longer but bg still popped.

I dont know if there are any bugs on horde side that causes these slow pops, but maybe it was just late and not many players queed bgs?

**Comment by Godmatik** [comment]
I read up from a GM on discord that now it is matching premade vs premade and that is the reason for the longer queues

**Comment by Cachirla** [comment]
well if horde don't matches as a premade its 90% of the times 4 hordes vs 15 alliances so... plz let horde play premades....

also plz turn of alterac and let us buy the marks with gold, AV just sink players from other battlegrounds and destroy the experience.

**Comment by whispersz** [comment]
How about you solo que as horde? God forbid you que a BG without  2 3 pocket healers.
NO, i am not alliance. I am sick of playing 4 horde vs 15 alliance

**Comment by wickedsouls** [comment]
Premade bgs don't work anymore, so basically just play ally, you get: 1. free bg wins, 2. extra 25% honor for afking basically, 3. extra 25% rep. 
Play horde if you want to be farmed at gy, with 15v4. "Sean"
--------------------------------------------------------------------------------------------------
Is it that hard to script BG's that you don't get games 15v4? 
And now you kill premades. Looks like developers never play this game. 
PvP will be dead here.

**Comment by yougocry** [comment]
all agree with the above, @kelno , you asked me to let you know if it's still broken, It is. Im sorry but the server was perfect as it was, please dont fix something thats working perfectly, there are many other things to fix. Just put it back as it was normally. please.... im begging you as a pvp player who doesnt want to leave a well populated server. thank you.

**Comment by kelno** [comment]
Thanks for updating me. I'll take a look again then.

To expand a bit about this last comment, the dev process is a bit more complicated than that. We did fix a bug somewhat related to queues in general, that bug had the side effect of breaking all kind of limitations on bg groups. Now that bug is fixed and we have this new behavior appearing. It's not like we intended to disallow groups to queue or that we even directly touched the code about it.

Now I understand this is important and that's why I'm looking into this now. I'll update you guys again on this issue when I'm done.

**Comment by kelno** [comment]
I found a big issue with it, fixed with next restart. You can notify me again here if there is still an issue.

**Comment by yougocry** [comment]
Thank You @kelno  for all your efforts making pvp life better on the server.

**Comment by yougocry** [comment]
https://i.imgur.com/HHV9dg0.jpg
@kelno  an update, but to be honest, I did not try it, as I cba to play bg's here anyomre unless I hear that from the pvp community premades are fixed and popping properly with low que time.

Thank You

**Comment by kelno** [comment]
This is from two days ago though? So the last fix shouldn't have been applied yet at that time

**Comment by BawayNico** [comment]
Hey,

For the 4 hordes vs 15 alliances, I totaly agree with Kelno, this is only due to players not joining or jumping into other BGs, that's an other topic.

Concerning the premade queue, this is nice that now the server tries to match you with other bg groups but in reallity, queue take so long.
The main issue here is that the server TRIES to match an other group, but if it can't immediatly (or in 1mn), it should just proc the group into normal BG.

Sorry if I did English mistakes
Thanks a lot

**Comment by yougocry** [comment]
it was just fine as it was, alliance winning every single random bg, they get +25% honor, if horde groups up and wins they mess up the que system so you either sit in 30 min que with another 14 ppl wich is impossible but that would be the only way to win bg's or you go in with random and feed the alliance mulltiple times +25% honor + etc ... please just put it back as it was, trust me it was all good. @kelno

**Comment by kelno** [comment]
I'll close for now as this seems fixed

**Comment by yougocry** [comment]
yes I can confirm that, the que times are being fixed for Premade BG ques, thanks to @kelno ! <3
