### ISSUE TITLE
Blackfang Tarantulas in Black Morass don't drop any loot.

### ISSUE THREAD

**Issue by leylandpaladin** [SunstriderEmu/BugTracker#2849]
**Describe the bug**

Blackfang Tarantulas in Black Morass drops no loot.

**To Reproduce**

1. Teleport to black morass.
2. Find Blackfang Tarantulas.
3. Kill Blackfang Tarantulas.
4. Try to find any loot on them.

Blackfang Tarantula:  

https://www.wowhead.com/npc=18983/blackfang-tarantula

**Expected behavior**

Expected to get some https://www.wowhead.com/item=21881/netherweb-spider-silk
from them

**Screenshots/videos**

Sure, I even recorded a small video

https://youtu.be/9aDfuBgpOIw

**Why it's important?**

Well, because I'm losing alot of gold when AoE farming black morass!

**Comment by Godmatik** [comment]
Devs removed the loot from the spiders on purpose.
https://github.com/SunstriderEmu/BugTracker/issues/2597

**Comment by leylandpaladin** [comment]
Okay, it's pretty stupid to me, like removing motes of water from fishing things or removing gas from nagrand gas clouds.  From all the abusive ways of getting gold, they desided to shut this one. 
I should say thanks for skinnable crocolisks then... I guess.
Thanks for answer Godmatik!

Bring at least gray items back in...
