### ISSUE TITLE
Quest Tanaris Field Sampling not working

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#2852]
**Describe the bug**
The quest item Untested Basilisk/Scorpid/Hyena Samples don't drop. No matter how many of those you kill. I killed about 40 of those. The suggested drop rates are from 36% to 63%. I don't think I'm that unlucky.

**To Reproduce**
1. Start the chain from Undercity till you get to the quest Tanaris Field Sampling
2. Activate the power source and start the 2 hour timer. Start killing Starving Blisterpaws/Scorpid Tail Lashers/Glasshide Basilisks and Gazers. The quest item Untested samples just don't drop.

Item: https://classic.wowhead.com/item=9442/untested-scorpid-sample
https://classic.wowhead.com/item=9437/untested-basilisk-sample
https://classic.wowhead.com/item=9439/untested-hyena-sample
Quest: https://classic.wowhead.com/quest=654/tanaris-field-sampling#comments

**Expected behavior**
The quest items should drop per the suggested drop %.

**Comment by Jerrythemagicdog** [comment]
Currently the chance is set to 100% for the following mobs:

> Glasshide Basilisk
> Glasshide Gazer
> Glasshide Petrifier
> Scorpid Hunter
> Scorpid Tail Lasher
> Scorpid Dunestalker
> Starving Blisterpaw
> Blisterpaw Hyena
> Rabid Blisterpaw
> Scorpid Duneburrower
> Murderous Blisterpaw

**Comment by EL100** [comment]
I did. I also just tried. The drop rate is still 0. Maybe the quest marker /timer marker is incorrect.
![WoWScrnShot_041120_104707](https://user-images.githubusercontent.com/61659496/79047000-11d1aa00-7be2-11ea-9726-5805b9f646c6.jpg)

**Comment by Sheikthecatman** [comment]
Thanks!
Fixed in [0eaf3522e950e4999184f0c91ecbde9897cc7c2f](https://github.com/kelno/sunstrider-scripts/commit/0eaf3522e950e4999184f0c91ecbde9897cc7c2f)
