### ISSUE TITLE
Nagrand Pure Water Bug

### ISSUE THREAD

**Issue by maverickyo** [SunstriderEmu/BugTracker#2855]
At location 37.5, 47.2 there is a unfishable Pure Water that is stuck on the shallows. I believe this is messing up the Pure Water Spawn as only 1 has been available at any given time all day which is not correct. There is also an inaccurate amount of fishing nodes in Nagrand as of 4/9/2020 It has not been like this on other days. At this current moment there is only 5 spawning at any given time.

**Comment by Jerrythemagicdog** [comment]
Thanks, moved after next restart.
