### ISSUE TITLE
Quest : Digging up the past 

### ISSUE THREAD

**Issue by AgreeableNZ** [SunstriderEmu/BugTracker#2857]
**Describe the bug**
Charred bone spawn timer of >13 Minutes retail states should be <1minute

**To Reproduce**
Loot the charred bone. Wait many minutes.

<!--- Please include ids of affected creatures / items / quests with a link to the relevant wowhead-https://www.wowhead.com/quest=9680/digging-up-the-past#comments

**Expected behavior**
Shorter spawn timer.

**Comment by Jerrythemagicdog** [comment]
Fixed with next update.
