### ISSUE TITLE
Masterlooter with patterns

### ISSUE THREAD

**Issue by AgreeableNZ** [SunstriderEmu/BugTracker#2858]
**Describe the bug**
Masterlooter is unable to loot patterns to raid members / party members unless masterlooter has that profession.

**To Reproduce**
Have pattern drop try to ML to player you wont be able to see the pattern but players with said profession will be able to see the patter.

Have found a sometimes working work around where you set to FFA and then set back to ML or pass ML to the player who can see it but this only sometimes works.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by AgreeableNZ** [comment]
@Jerrythemagicdog  This also happens with all BOE patterns in a dungeon if there is no player with the recipe everyone auto passes when they have a vendor value

**Comment by Jerrythemagicdog** [comment]
@AgreeableNZ which pattern was this a problem with? I've tried with some BoP ones (like Mongoose or Major Spellpower) and I'm having no issues seeing / assigning loot as a master looter.

**Comment by AgreeableNZ** [comment]
@Jerrythemagicdog  I'll paint the scene so hopefully something jumps out at you.

10man raid, My self i have Jewlcrafting and Mining professions.

We were clearing the trash in the party room before moroes, a tailoring pattern dropped ( i'm unsure of which exact pattern ) Priest in group 2 of the raid ( i was in group 1 of the raid ) Detected the pattern drop but the loot was not visible to me. Perhaps the issue lies within groups? as its just occoured to me now that a blacksmithing pattern dropped and our warrior in same group as me detected it i could see it but not masterloot it to him as so i passed him Masterloot and he managed to pass it to him self.

**Comment by Jerrythemagicdog** [comment]
Fixed last update.
