### ISSUE TITLE
Hunter. Attack speed pets not working

### ISSUE THREAD

**Issue by buitrio** [SunstriderEmu/BugTracker#2859]
The beast Broken Tooth, has an attack speed of 2.0, when it should have an attack speed of 1.0, after being tamed

The beast Humar The Pridelord, has an attack speed of 2.0 when it should have an attack speed of 1.3 after being tamed

**Comment by Skorlaa** [comment]
With patch 2.0.3 all Hunter Pets got normalized - all attacks peed of 2.0 basic.
