### ISSUE TITLE
Distract Bug

### ISSUE THREAD

**Issue by Malozar** [SunstriderEmu/BugTracker#2860]
**Describe the bug**
Mobs stay immobilized by distract, even after being pulled

**To Reproduce**

1. Cast [Distract] on one enemy or more
2. Pull the mobs before the distract timer run out with any sort of ranged attack
3. Observe mobs not moving till the 10 sec duration from distract has ended.

Any creature who can be distracted is affected by this
Spell is: https://www.wowhead.com/spell=219677/distract

**Expected behavior**
If mobs are aggroed while distracted, the distract effect should break immediately.

**Comment by beraus** [comment]
https://streamable.com/fwns2k

**Comment by Jerrythemagicdog** [comment]
This was fixed some time ago, forgot to close the issue, reopen if there are still problems, thanks!
