### ISSUE TITLE
Lair Brutes in Gruul's Lair drop threat repeatedly without charging anyone

### ISSUE THREAD

**Issue by tthierolf** [SunstriderEmu/BugTracker#2863]
**Describe the bug**
https://github.com/SunstriderEmu/BugTracker/issues/731

This is not fixed, the Lair Brutes will drop aggro every few seconds without charging.

**To Reproduce**
Try tanking the mob and realize it's untankable because it drops aggro every few seconds without charging.

**Expected behavior**
The mob should respect threat tables and only drop aggro when charging someone outside of melee range.

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Yes, the Ogre will wipe threat at the same time as he would normally cast charge regardless of if he casts it.
