### ISSUE TITLE
mage aoe / probably others going through bridge in arena and hitting below

### ISSUE THREAD

**Issue by oldspices** [SunstriderEmu/BugTracker#2864]
**Describe the bug**

mage was casting blizzard ontop of the bridge in arena- team mate was sneaking below near the pillar- aoe from above hits below. 
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by artieau** [comment]
This is working as intended, as described in your example.

**Comment by Jerrythemagicdog** [comment]
![image](https://user-images.githubusercontent.com/46463908/79000010-bd77ed00-7b43-11ea-9e35-30cf923bdf4d.png)

Is this perhaps what you meant in the issue?
