### ISSUE TITLE
Prospecting ores with full inventory

### ISSUE THREAD

**Issue by AgreeableNZ** [SunstriderEmu/BugTracker#2866]
**Describe the bug**
When prospecting ore if your inventory is full on prospect and you try to delete an item from bag to make space the gem you received from prospect will vanis.

**To Reproduce**
Prospect ore with no inventory space and try to make room with prospect loot window open it will close the window and the prospect ores will vanish along with any gems/dust.

**Comment by kelno** [comment]
Fixed since
