### ISSUE TITLE
Aldor/Scryer not teleporting you off their platform

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2868]
When you choose either Aldor or Scryer faction, you should not be able to access the other's faction area in Shattrath. 

I went Scryer but was able to enter the Aldor side with no repercussions. The guards there should kick you off the terrace and teleport you to the bottom of the elevator.

Edit: just tested also on my other character who is Aldor, and hated with Scryer faction. Can run around in the Scryer area with no problems.

**Comment by z5n** [comment]
unable to reproduce, currently getting teleported out as intended
