### ISSUE TITLE
Shaman Drinking Bug (Delayed time to get out of combat)

### ISSUE THREAD

**Issue by garlandx23** [SunstriderEmu/BugTracker#2870]
In dungeons shaman is very late to leave combat to be able to eat/drink. All other classes are seen eating/drinking after killing mobs and my shaman will still show in combat for about three or four extra seconds on every pack of mobs.

**Comment by Jerrythemagicdog** [comment]
Most likely fixed in 898aa139d6072f7e55f11cb0f565f76de776128d, thanks for the issue.
