### ISSUE TITLE
Mage aoe

### ISSUE THREAD

**Issue by schurupik** [SunstriderEmu/BugTracker#2872]
**Describe the bug**
for mage aoe damage splitted with count of mobs hit

**To Reproduce**
Aoe spells(blizzard/AE/flamestrike) does less damage when hits group of mobs 
If i use blizzard on 1 mob it hits ~350 per tick 
If i use blizzard on 10 mobs it hits ~50

**Expected behavior**
This mechanic shouldnt work like this, and this makes mages very weak in farming

Didnt check on other classes but for mage it works like this
problem rate is 10/10. fix it plz

**Comment by Godmatik** [comment]
TBC has an AoE cap, at a certain damage threshold it is capped and you will do less total damage.

**Comment by schurupik** [comment]
https://www.youtube.com/watch?v=lhEQ8iGSwgA
is that enough? or i have to look for blizzard tbc video?

**Comment by Godmatik** [comment]
Videos aren't going to be considered evidence if they are not from the TBC era, and using info from other private servers don't work either.

All TBC clients have an AoE cap that Blizzard implemented (which didn't exist in classic). The cap was eventually changed in later expansions.

Read more about it here:
https://wowwiki.fandom.com/wiki/Area_damage_caps

**Comment by Godmatik** [comment]
You should be able to produce normal AoE damage if you only doing it to a few mobs. Once you get past 10 or so, you'll notice the damage get lowered.

**Comment by schurupik** [comment]
ok, thanks
