### ISSUE TITLE
Targetting bug (causes the summon bug maybe)

### ISSUE THREAD

**Issue by Ticketdudu** [SunstriderEmu/BugTracker#2876]
Other players will always see your Mouseover-target as your target...

Lets say i am Dudula and i am targetting Logo.

Other players should see Logo in my target (If i dont mouseover on another player!)

If i mouseover another player(Lets say Inspirator) , while my "real target" is still logo, other players will see Inspirator on my target because my cursor is hovering on Inspirator.
(Dudula, Logo and Inspirator are characters btw :D)

Thats why AFK players always switch the targets in citys, because random players are walking around and sometimes hitting the cursor on the afk player's screen.

I hope some1 can understand my shitty english and this bug will get fixed ;)

**Comment by Jalapan** [comment]
You are right, afk players mouseover when afk is strange, and i really hope this can help fix summoning stones and ritual of summoning @Jerrythemagicdog

**Comment by InhumanGM** [comment]
Do you have an addon that alters your tooltip (i.e. GearScoreLite)? When you mouse-over a player, the addon registers it as you clicking on the player, and thus targeting the player, instead of just mousing-over. Disabling any addons that display information on the tooltip should fix the issue.

**Comment by Sheikthecatman** [comment]
Most likely fixed in [3f53477c8e68954fcddd14f64eb5908ecdc60855](https://github.com/kelno/sunstrider/commit/3f53477c8e68954fcddd14f64eb5908ecdc60855) which should be live.
