### ISSUE TITLE
What the souls see? quest bug

### ISSUE THREAD

**Issue by jonabl** [SunstriderEmu/BugTracker#2878]
I cant see the mobs spawning in this quest. i have seen vids on how the quest is done and im the right place.
I can see the mobs talking in the chat but they dont spawn and i cant target them
The mobs is called: Ancient Orc Ancestors

Quest: https://www.wowhead.com/quest=10168/what-the-soul-sees

**Comment by hashblaster** [comment]
I cannot complete this either.

**Comment by bjh368** [comment]
worked fine for me today

**Comment by Sheikthecatman** [comment]
You need to complete [Vision of the Dead](https://www.wowhead.com/quest=10252/vision-of-the-dead)

If an issue persists, it's the same as #3054

**Comment by Sheikthecatman** [comment]
Fixed in [32948668ce04c51a61d62bea890955d1e43dec77](https://github.com/kelno/sunstrider-scripts/commit/32948668ce04c51a61d62bea890955d1e43dec77)
