### ISSUE TITLE
We can't Dismound and Stealth same time with rogue.

### ISSUE THREAD

**Issue by Akaqt** [SunstriderEmu/BugTracker#2879]
Hi we can't Dismound and Stealth same time with my rogue. I need to press my touch 1 time for dismount and a second time Stealth.

Before your patch of 10/04/20 is work but now i need to press my touch x2 times for do this...

**Comment by Macumbafeh** [comment]
+1 it's a recent bug, and it affect all spells. It Say "your in a mount" you have to use spell again... It's a bit annoying...

**Comment by Godmatik** [comment]
This is for any action. 
Even trying to herb.
Anything that dismounts you have to use it twice for it to go through.

**Comment by nottreal** [comment]
druids have similar thing. u cant use macro for going cat stealth. never seen that u cant do it. even classic had this. but there u have to press twice

**Comment by kelno** [comment]
It's indeed a new bug, I fixed it yesterday and it's live right now. Should be fixed!
