### ISSUE TITLE
Shadow Labyrinth - Blackheart the Inciter

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2881]
When a shaman is mind-controlled during the fight, he only drops grounding totem then sits there and does nothing, doesn't even try and attack.

I noticed some other classes also don't really attack or engage very often, but haven't paid too much attention, just noticed very little action happens during all of it.

**Comment by Godmatik** [comment]
Warlock only uses Howl of Terror than does nothing else.
Priest only heals the boss.

Feels like these MC abilities are never randomized.

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2118
