### ISSUE TITLE
[Warlock] Demonic Sacrifice animation

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2885]
When you use Demonic Sacrifice, it's supposed to give a death animation for the pet and they should lay dead next to you.

On this server, it just de-spawns them.

**Comment by Balanarr** [comment]
Related to pets despawning instead of actually dying.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, we're not going to change this particular case.
