### ISSUE TITLE
Dire Maul (North) Tribute run, cant open first door and cant get crown buff

### ISSUE THREAD

**Issue by Ticketdudu** [SunstriderEmu/BugTracker#2888]
**Describe the bug**
I was about to do a dire maul north tribute run to get all the buffs.

**To Reproduce**
1. Go into dire maul north (u will need the Crescent Key to open the door in front of dungeon to get inside)
2. Kill the first boss and loot the key
3. Get to the big second room and loot the key inside the chest in the mid of the room
4. Go to the big door behind the chest
5. Now u see the door, but u cant open it with the looted key because its not even clickable

I can explain the next steps just because i wrote an ingame ticket and a kind GM opened the door for me (<3). And because i did it on Classic many times.

6. Skip all bosses (stealth is the best way)
7. Kill the Endboss (King Gordok)
8. Now a ogre should spawn (Mizzle the Crafty). U can talk to him to let the tribute chest spawn and to get the crown buff ("King of the Gordok"), but he doesnt spawn
9. If u have the buff, run back to the skipped bosses, talk to them and get the buffs

**Expected behavior**
Normally the first door inside the dungeon should be able to open with the key from the chest. Then (after u skipped the bosses) u should be able to talk to Mizzle the Crafty after killing the endboss. Chest should spawn and u should get the buff. Then u should be able to run back to the skipped bosses to get some buffs like +200 attack power and  % spellcrit chance.

**Screenshots/videos**
Tribute run video from Soupasoka:
https://www.youtube.com/watch?v=gXg_KBx-yNQ

**Additional context**
I think its fine if the bugged door gets removed and the npc that u have to talk to after killing the endboss is already spawned till the dungeon gets fixed correctly. I would be very happy if im able to get these tribute buffs :)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
Per patch 2.1 the buffs won't be available to players above level 63 though.
"Fengus' Ferocity, Mol'dar's Moxie, [[Rallying Cry of the Dragonslayer]](https://wowpedia.fandom.com/wiki/Rallying_Cry_of_the_Dragonslayer), Slip'kik's Savvy and  [[Spirit of Zandalar]](https://wowpedia.fandom.com/wiki/Spirit_of_Zandalar) these buffs will no longer work on targets over level 63."
