### ISSUE TITLE
Hunter attack speed (After re equip wep)

### ISSUE THREAD

**Issue by Sonny860661** [SunstriderEmu/BugTracker#2889]
**Describe the bug**

Attack speed goes up when i re equip gun, i have to relog in order for my gun to go back to normal. 

**To Reproduce**

1.  Look at your attack speed and un equip gun/bow
2.  Re equip gun/bow 
3. Attack speed is now different to how it was originally. 

**Expected behavior**

Attack speed value should not change if i re equip wepon.
**Screenshots/videos**

**Comment by Sonny860661** [comment]
Attack speed before i unequip wepon is 1.99

When i re equip it it goes up to 2.25

**Comment by Ironjudgment** [comment]
Can confirm. It's not just a visual. https://youtu.be/pIbf-IaLCxU

**Comment by mchayes** [comment]
Haven't tested with death, but atleast re-equip bug is fixed when relogging/change spec

**Comment by bjh368** [comment]
You can also fix this by re-equipping your quiver/ammo pouch

**Comment by z5n** [comment]
issue has since been fixed
