### ISSUE TITLE
Flying monsters

### ISSUE THREAD

**Issue by Kotchimotchi** [SunstriderEmu/BugTracker#2893]
**Describe the bug**
When you fly close to mobs they chase after you in the air, swimming after you etc.

**To Reproduce**
Fly close to ground, aggro mobs, fly up in air, watch them follow you

**Expected behavior**
I expect the mobs to stay on the ground.

**Comment by lukas155** [comment]
Confirmed. Has been introduced in one of the latest updates.

**Comment by kelno** [comment]
Can you give me an example of a creature doing that? The few ones I looked didn't seem to do that.

**Comment by Kotchimotchi** [comment]
Warp Chasers in Netherstorm chases you in air atleast, my friend told me Ogres in Nagrand chased him midair yasterday.

**Comment by Godmatik** [comment]
Yes, Ogres on barrier hills are doing this, especially if they are walking down a slope or hill

**Comment by Nim92** [comment]
almost all mobs in shadowmoon vally does this too, the felboars, mobs at illidari point etc.

**Comment by Balanarr** [comment]
Pets also seem to be able to fly in the air and chase players

**Comment by kelno** [comment]
Thanks, this should be fixed with next restart

**Comment by kelno** [comment]
Fix should be live now.
https://github.com/kelno/sunstrider/commit/ec829f12d8d1bad6dbd048e9de6c9274ed56d7fc
