### ISSUE TITLE
"Tooga's Quest" quest does not work

### ISSUE THREAD

**Issue by DiaWreckingball** [SunstriderEmu/BugTracker#2898]
**Describe the bug**
Tooga follows you to his wife, this is normal. But as soon as you get into a fight, he walks back to his starting position.

**To Reproduce**
1. Start the quest
2. Get near a mob
3. ?????
4. Profit (you see, that he walks back)

https://classic.wowhead.com/quest=1560/toogas-quest

**Expected behavior**
He should follow you.

**Comment by beckerp86** [comment]
I also encountered this.

**Comment by Godmatik** [comment]
confirmed

**Comment by Sheikthecatman** [comment]
Thanks! Escort quest should be fixed in [09bbc1cd4ad10c84eef38ddbb7aeffdea86ba898](https://github.com/kelno/sunstrider-scripts/commit/09bbc1cd4ad10c84eef38ddbb7aeffdea86ba898).

Tooga will now require your help to find his wife, whom displays hatred for him.
