### ISSUE TITLE
 [Curing the Sick]

### ISSUE THREAD

**Issue by ageerik** [SunstriderEmu/BugTracker#2903]
quest  Curing the Sick does not cure them, so you can spam the item on the same deer multiple times

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in [9c052d7277b56b5221cc926f693bd5cda0072d4b](https://github.com/kelno/sunstrider-scripts/commit/9c052d7277b56b5221cc926f693bd5cda0072d4b)
