### ISSUE TITLE
Improved Scorch sometimes fail

### ISSUE THREAD

**Issue by Zorbakk** [SunstriderEmu/BugTracker#2909]
The talent Improved Scorch sometimes fail and does not apply a stack of Imp. Scorch. See the attached video. In the video you can clearly see that the fourth cast do not apply a stack of Imp. Scorch. Also, you can see that it's not resisted and therefore should count as a stack.

https://www.youtube.com/watch?v=fM6hhcaIfJY&feature=youtu.be (video)

**Comment by Jerrythemagicdog** [comment]
The spell has a separate chance to resist, same as Winter's Chill.
