### ISSUE TITLE
Missing hearthstone from inventory

### ISSUE THREAD

**Issue by danielkozik** [SunstriderEmu/BugTracker#2910]
**Describe the bug**
Missing hearthstone from inventory.

**To Reproduce**

1.  I think I accidentally remove my hearthstone from inventory, going to the innkeeper and requesting for making inn new home doesn't bring hearthstone back
2. User name: Kyrltonbynks
3. 

Item: https://classic.wowhead.com/item=6948/hearthstone

**Expected behavior**
I would like to have my hearthstone back in my inventory.

**Screenshots/videos**

**Additional context**

**Comment by Godmatik** [comment]
ask an innkeeper, they will give you a new one

**Comment by danielkozik** [comment]
That's the problem. I asked. I choose the option for making ogrimmar my
home. There should be another option except makin this place my home and
browse goods?

**Comment by Godmatik** [comment]
have you checked to see if you can 'buy' one from the innkeeper?

**Comment by danielkozik** [comment]
Yes, I search for it also. In ogrimmar they didn't have it. I will try in
another cites also.

**Comment by danielkozik** [comment]
I tried multiple cities and multiple innkeepers. No one had hearthstone. Is
it possible for you guys fix it please?

**Comment by Godmatik** [comment]
You probably should ticket a GM in game to help you

**Comment by danielkozik** [comment]
Thank you very much for your help!
Have a good day and take care!



niedz., 12 kwi 2020 o 18:21 Godmatik <notifications@github.com> napisał(a):
