### ISSUE TITLE
Molten Armor never crits and doesn't proc Clearcasting

### ISSUE THREAD

**Issue by boxitooo** [SunstriderEmu/BugTracker#2911]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by oldspices** [comment]
from what ive seen the stun proc wont proc off it either in pvp.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3906
