### ISSUE TITLE
[Shattered Halls] Creeping Ooze

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2914]
Creeping Ooze NPC #17536 casts Sticky Ooze, spell #30494

The spell is supposed to reduce your movement and attack speed, but it doesn't work.

https://db.endless.gg/?spell=30494

Also, you can have more than one debuff on you from multiple oozes:

![2020-04-11 16_23_39-World of Warcraft](https://user-images.githubusercontent.com/37913400/79055829-a6093480-7c15-11ea-886c-ca0f83925cb2.png)

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2031
