### ISSUE TITLE
Accepting summon sometimes doesn't work

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2917]
If you wait too long to accept a summon that was sent out, it will not work. 

Not sure the exact amount of time but it's about 20-30 seconds or so, wait that long then click accept, nothing happens.

**Comment by Ticketdudu** [comment]
Everytime u alt+tab out of wow, the summon will not work if u switch back into wow. Idk if it bugs if u just wait too long without tabbing out of wow :/

**Comment by Godmatik** [comment]
Actually you are correct, this happens when I alt-tab out.

**Comment by oldspices** [comment]
i think whats most likely happening is youre getting summoned twice becausse you didnt accept the summon because you are afk-= if you get summoned twice that bugs it out

**Comment by beraus** [comment]
Let us know if this issue is still active after latest changes.
