### ISSUE TITLE
Raene Wolfrunner doesn't offer the Raene's Cleansing quest chain

### ISSUE THREAD

**Issue by steak-house** [SunstriderEmu/BugTracker#2918]
**Describe the bug**
Raene Wolfrunner, the 60 elite in Astranaar, Ashenvale, doesn't offer the Raene's Cleansing quest chain

**To Reproduce**
1. Go to Astranaar with an alliance character that is at least level 18 (tested with a 35 Draenei shaman)
2. Observe that Raene only offers Culling the Threat, and is missing Raene's Cleansing

NPC : https://classicdb.ch/?npc=3691#starts

**Comment by Raistlin1** [comment]
Can confirm the bug (lvl 70 human). Will be happy if fixed...

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, the quest was requiring "Onward to Ashenvale" (10752) to be completed before this one became available, it's changed to be a breadcrumb quest instead now.
