### ISSUE TITLE
Arcane Tome no rep @ friendly

### ISSUE THREAD

**Issue by ItsNauty** [SunstriderEmu/BugTracker#2919]
![arcane tome](https://user-images.githubusercontent.com/63532144/79061716-b0442680-7c47-11ea-8f8a-378d74159312.PNG)

I turned in 10 arcane tomes and i noticed after my shatar rep didnt go up and im only friendly with shatar

**Comment by Balanarr** [comment]
The rep you get with sha'tar when turning in aldor/scryer items is half of the rep you get you get with aldor/scryer.
It's also not displayed in the chat that you gained it. It's how it always worked

**Comment by reinart1** [comment]
i have the same problem, not getting shatar rep with arcane tomes and yes ive looked specifically on the shatar rep bar and not the notificatiron, no change after u hand in arcane tomes

**Comment by reinart1** [comment]
i did the same thing on my main char about a month ago and then there were no problems with it

**Comment by Jerrythemagicdog** [comment]
Some time ago the max reputation with Sha'tar through handing in Tomes was fixed and is now capped at Honored.
