### ISSUE TITLE
"Invalid Target" when trying to cast water walking on a friend

### ISSUE THREAD

**Issue by steak-house** [SunstriderEmu/BugTracker#2920]
**Describe the bug**
See title.

**To Reproduce**

1. Cast Water Walking on friendly target (done with level 35 draenei shaman on level 34 draenei warrior I was grouped with)
2. Get "Invalid Target" error message

https://classicdb.ch/?spell=546

**Expected behavior**
Water Walking should be castable on all friendly targets: https://wowwiki.fandom.com/wiki/Water_Walking

**Comment by LewysEze** [comment]
Get the same "Invalid target" error message on:
-Warriors
-Stealthed Rogues
-Shapeshifted Druids

**Comment by steak-house** [comment]
Seems like it's related to people being in a stance, then. I imagine the same would occur on a shadowformed priest.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
