### ISSUE TITLE
Квест на яды у альянса не работает 

### ISSUE THREAD

**Issue by antislif** [SunstriderEmu/BugTracker#2923]
Взял ключ и не могу открыть сундук 
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by LSD7** [comment]
you should use your lockpicking skill and not the key

**Comment by mayday2013** [comment]
you'd better ask for help in the chat.

но да, ключ вообще не для того) юзай локпик
