### ISSUE TITLE
Hello! I knocked out two items for ssc attune. Passed the hero of SP, and came to mob to pass the quest! The question mark was gray! BUT two items were in my bag. I deleted the quest, I thought that it would work. I deleted, and two items from the bag disappeared !! What to do?

### ISSUE THREAD

**Issue by Beweslolxd** [SunstriderEmu/BugTracker#2925]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Godmatik** [comment]
Open GM ticket in-game they might be able to get your items back.

**Comment by beraus** [comment]
Fixed in game.
