### ISSUE TITLE
Druid  [Subtlety] talent

### ISSUE THREAD

**Issue by avclol** [SunstriderEmu/BugTracker#2929]
Hi. I'd like to report the druid talent  [Subtlety] ( restoration)  ( reduce the chance that your spell will be dispelled) is not working at all (0 chance even with x5 talents) (had multiple test. I was able to take the spells with zéro resist on my druid.

**Comment by mayday2013** [comment]
Playing priest I hardly ever can dispel blooms from a druid.

When it comes to paladins anti-dispel...RNG gets me.
