### ISSUE TITLE
UBRS Rend

### ISSUE THREAD

**Issue by Bormarr** [SunstriderEmu/BugTracker#2930]
**Describe the bug**
 UBRS Rend encounter doesnt work. When you jump down from balcony onto floor and move into middle of floor the encounter is supposed to start. The large gate is supposed to open and you have to fight waves of mobs until finally Rend comes in on his dragon Gyth. Nothing happens here, you can however pull Rend from balcony with a ranged attack wich makes him run through the back gate and attack you but his dragon is not with him and Rend hits way too hard then what hes supposed to. The same goes for the mobs through the large gate, you can pull them through the gate but they all hit too hard.

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Sheikthecatman** [comment]
Was fixed in [84d37200f5613681665c3f5a44e5a7d199f8f055](https://github.com/kelno/sunstrider-scripts/commit/84d37200f5613681665c3f5a44e5a7d199f8f055)
