### ISSUE TITLE
Timing on "7 Dwarves" event in BRD is off

### ISSUE THREAD

**Issue by Felthorn10** [SunstriderEmu/BugTracker#2933]
The 7 Dwarves event in Blackrock Depths has a timed boss fight where sub-bosses come at certain intervals. The correct timing is ~25-30 seconds and it appears they come now about every 10-15 seconds which is wayyyy to fast.

**Comment by Sheikthecatman** [comment]
Could you provide something to help with the claim on the timer?

**Comment by Felthorn10** [comment]
I just watched  https://www.youtube.com/watch?v=QoEwUz7Bdq8, and about 25
minutes in is the 7 Dwarves fight. This appears to be on the actual WoW
classic live server and as you can see the timing is wayyyy longer than
what Sunstrider's is. In fact I think the Dwarves either come on a longer
timer or upon death of the previous dwarf here. Let me know your thoughts.

**Comment by Sheikthecatman** [comment]
Alright, timers have been increased slightly.

**Comment by Felthorn10** [comment]
Awesome! Thank you so much!
