### ISSUE TITLE
Rarespawn Marticar in Zangarmarsh keeps respawning every 1-5 minutes!

### ISSUE THREAD

**Issue by Skorlaa** [SunstriderEmu/BugTracker#2936]
As the title said - the rarespawn Marticar in Zangarmarsh keeps respawning every few Minutes.. 1-5minutes max. Sometimes it respawned instantly!

**Comment by Godmatik** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2741
looks like it wasn't fixed

**Comment by Sheikthecatman** [comment]
Respawn time is 5 minutes currently, yes.
