### ISSUE TITLE
NPC despawn

### ISSUE THREAD

**Issue by krbroten** [SunstriderEmu/BugTracker#2938]
as I quest in the open world NPC's continuously keep fading in and out. To the point I can be in combat with an add and have it vanish on me.

Not a tethering issue! It seems when other players enter/leave my visual field range all the npcs shift to a new set of npc's. Kind of like behavior of phasing or shifting layers as seen on retail.

As a prot paladin I kill npc's slowly, and many fights get the npc vanished before kill completed. This slows down my questing greatly. Has only been happening this last week.

**Comment by kelno** [comment]
It's related to creature pooling, it should be resolved by now
