### ISSUE TITLE
Stormwind Rendezvous

### ISSUE THREAD

**Issue by EneaMapelli** [SunstriderEmu/BugTracker#2939]
After freeing Windsor from brd I should be able to summon him to stormwind by talking to Squire Rowe at the gates of the city. Squire Rowe does not present the line of dialogue needed to invoke Windsor.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2592

**Comment by z5n** [comment]
duplicate of #5153
