### ISSUE TITLE
autoattack animation bug

### ISSUE THREAD

**Issue by mayday2013** [SunstriderEmu/BugTracker#2940]
**Describe the bug**
when you go from melee autoattacks to ranged, you can't shoot, have to retarget or cancel autoattacks and start again

**To Reproduce**
1. make a hunter, go to melee range 
2. jump away for ranged autos
3. you can't shoot

**Expected behavior**
--
**Screenshots/videos**
https://www.youtube.com/watch?v=gHdx62i1ahU

**Additional context**
I have autoswitching between melee/shoot autoattacks ON in my setttings and "stop autoattack on switching targets" - OFF

**Comment by kelno** [comment]
Thanks!
Fixed with next server update

**Comment by mayday2013** [comment]
thanks for response!
