### ISSUE TITLE
Herbs spawning under map

### ISSUE THREAD

**Issue by septembr** [SunstriderEmu/BugTracker#2943]
**Describe the bug**
At coordinates 55.0 24.1 in Barrens there's a Goldthorn stuck under the map, making it impossible to herb it. 

**To Reproduce**

1. Go to coordinates mentioned.
2. Find the herb under the map.
3. Attempt to herb it. 

**Expected behavior**
Herbs should not spawn under the map.

**Comment by Sheikthecatman** [comment]
Thanks!
Fixed in [15da8797c8ef01404482917d5c258229d397f191](https://github.com/kelno/sunstrider-scripts/commit/15da8797c8ef01404482917d5c258229d397f191)
