### ISSUE TITLE
Warlock pets in bg's retain the hp they had when the owner died or don't spawn at all

### ISSUE THREAD

**Issue by Balanarr** [SunstriderEmu/BugTracker#2945]
**Describe the bug**
Warlock pets in bg's retain the hp they had when the owner died or don't spawn at all

**To Reproduce**
1 Have pet out that has taken some damage and the owner is killed
2 Release and wait to resurrect

When resurrecting the pet has the same hp it had when the warlock died. If the pet died before the warlock it doesn't respawn at all.

**Expected behavior**
Last pet the warlock had out in the bg should always respawn and with full hp when getting resurrected by the spirit

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago, thanks for the issue.
