### ISSUE TITLE
The Black Morass NPCs not droping loot 

### ISSUE THREAD

**Issue by shrift1** [SunstriderEmu/BugTracker#2948]
Blackfang Tarantula NPC in instance The Black Morass doesn't drop any loot. 
They are not dropping any loot while they should in client 2.4.3

their loot table is:
    Netherweb Spider Silk | 60 |   | Cloth | 78 |  
  | Eroded Axe | 69 | 64 | One-Handed Axe | 0.3623 | 1 [100%]
  | Stone Reaper | 69 | 64 | Two-Handed Axe | 0.3623 | 1 [100%]
  | Deteriorating Blade | 69 | 64 | One-Handed Sword | 0.3623 | 1 [100%]
  | Tarnished Claymore | 69 | 64 | Two-Handed Sword | 0.3623 | 1 [100%]
  | Corroded Mace | 69 | 64 | One-Handed Mace | 0.3623 | 1 [100%]
  | The Stoppable Force | 69 | 64 | Two-Handed Mace | 0.3623 | 1 [100%]
  | Sharpened Stilleto | 69 | 64 | Dagger | 0.3623 | 1 [100%]
  | Dense War Staff | 69 | 64 | Staff | 0.3623 | 1 [100%]
  | Rusted Musket | 69 | 64 | Gun | 0.3623 | 1 [100%]
  | Broken Longbow | 69 | 64 | Bow | 0.3623 | 1 [100%]
  | Dilapidated Cloth Belt | 72 | 67 | Cloth | 0.3623 | 1 [100%]
  | Dilapidated Cloth Boots | 72 | 67 | Cloth | 0.3623 | 1 [100%]
  | Dilapidated Cloth Bracers | 72 | 67 | Cloth | 0.3623 | 1 [100%]
  | Dilapidated Cloth Gloves | 72 | 67 | Cloth | 0.3623 | 1 [100%]
  | Dilapidated Cloth Hat | 72 | 67 | Cloth | 0.3623 | 1 [100%]
  | Dilapidated Cloth Pants | 72 | 67 | Cloth | 0.3623 | 1 [100%]
  | Dilapidated Cloth Shoulderpads | 72 | 67 | Cloth | 0.3623 | 1 [100%]
  | Dilapidated Cloth Vest | 72 | 67 | Cloth | 0.3623 | 1 [100%]
  | Decaying Leather Armor | 72 | 67 | Leather | 0.3623 | 1 [100%]
  | Decaying Leather Belt | 72 | 67 | Leather | 0.3623 | 1 [100%]
  | Decaying Leather Boots | 72 | 67 | Leather | 0.3623 | 1 [100%]
  | Decaying Leather Bracers | 72 | 67 | Leather | 0.3623 | 1 [100%]
  | Decaying Leather Gloves | 72 | 67 | Leather | 0.3623 | 1 [100%]
  | Decaying Leather Helmet | 72 | 67 | Leather | 0.3623 | 1 [100%]
  | Decaying Leather Pants | 72 | 67 | Leather | 0.3623 | 1 [100%]
  | Decaying Leather Shoulderpads | 72 | 67 | Leather | 0.3623 | 1 [100%]
  | Corroded Mail Armor | 72 | 67 | Mail | 0.3623 | 1 [100%]
  | Corroded Mail Belt | 72 | 67 | Mail | 0.3623 | 1 [100%]
  | Corroded Mail Boots | 72 | 67 | Mail | 0.3623 | 1 [100%]
  | Corroded Mail Bracers | 72 | 67 | Mail | 0.3623 | 1 [100%]
  | Corroded Mail Circlet | 72 | 67 | Mail | 0.3623 | 1 [100%]
  | Corroded Mail Gloves | 72 | 67 | Mail | 0.3623 | 1 [100%]
  | Corroded Mail Pants | 72 | 67 | Mail | 0.3623 | 1 [100%]
  | Corroded Mail Shoulderpads | 72 | 67 | Mail | 0.3623 | 1 [100%]
  | Deteriorating Plate Belt | 72 | 67 | Plate | 0.3623 | 1 [100%]
  | Deteriorating Plate Boots | 72 | 67 | Plate | 0.3623 | 1 [100%]
  | Deteriorating Plate Bracers | 72 | 67 | Plate | 0.3623 | 1 [100%]
  | Deteriorating Plate Chestpiece | 72 | 67 | Plate | 0.3623 | 1 [100%]
  | Deteriorating Plate Gloves | 72 | 67 | Plate | 0.3623 | 1 [100%]
  | Deteriorating Plate Helmet | 72 | 67 | Plate | 0.3623 | 1 [100%]
  | Deteriorating Plate Pants | 72 | 67 | Plate | 0.3623 | 1 [100%]
  | Deteriorating Plate Shoulderpads | 72 | 67 | Plate | 0.3623 | 1 [100%]
  | Mistyreed Belt | 102 | 64 | Cloth | 0.3623 | 1 [100%]
  | Mistyreed Boot | 102 | 64 | Cloth | 0.3623 | 1 [100%]
  | Mistyreed Tunic | 102 | 64 | Cloth | 0.3623 | 1 [100%]
  | Mistyreed Gloves | 102 | 64 | Cloth | 0.3623 | 1 [100%]
  | Mistyreed Hood | 102 | 64 | Cloth | 0.3623 | 1 [100%]
  | Mistyreed Pants | 102 | 64 | Cloth | 0.3623 | 1 [100%]
  | Mistyreed Shoulderpads | 102 | 64 | Cloth | 0.3623 | 1 [100%]

**Comment by Godmatik** [comment]
Devs removed the loot from the spiders on purpose.
https://github.com/SunstriderEmu/BugTracker/issues/2225

**Comment by shrift1** [comment]
lul
