### ISSUE TITLE
[Felstriker] proc not working/implemented

### ISSUE THREAD

**Issue by Malozar** [SunstriderEmu/BugTracker#2949]
**Describe the bug**
The proc from [Felstriker] isnt working

**To Reproduce**
1. Equip [Felstriker]
2. Attack a target
3. Observe no proc 

Item: https://classic.wowhead.com/item=12590/felstriker
Spell: https://classic.wowhead.com/spell=16551/felstriker#comments

**Expected behavior**
Im not sure about the exact procrate, but i know that it is supposed to proc, thats for sure, remember people experimenting with the procrate even as late as in MoP, should it should be functioning.

**Comment by Jerrythemagicdog** [comment]
The spell lasts 3 seconds and is hidden from your aura bar, you can see the animation similar to Rogue's "Sprint" ability happening when it procs. I've tried to see if it doesn't work but it procs and affects the character's crit chance correctly.
