### ISSUE TITLE
spellstealing the firebuff in botanica

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#2951]
after the 1st and 2nd boss there is a mob with a fire shield and a large pack of plants.  

the fireshield incorrectly damages your party also the damage also isn't very substantial which is good and maybe less fun.

**Comment by beraus** [comment]
Prob related to spell reflect issue.

**Comment by Jerrythemagicdog** [comment]
Fixed a long time ago, thanks for the issue.
