### ISSUE TITLE
[Rogue] Movement impairing effects should be removed by casting Vanish even when not entering Stealth.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#2955]
**Describe the bug**
Title.

Source: https://youtu.be/ArS1w1jgKw8?t=503

**To Reproduce**
1. Get slowed on top of a Flare
2. Cast Vanish
3. Slows / root / movement impairing effects don't get removed

**Comment by kelno** [comment]
Fixed with next restart
