### ISSUE TITLE
[Druid] [talent] Omen of Clarity

### ISSUE THREAD

**Issue by jmee90** [SunstriderEmu/BugTracker#2956]
Omen of Clarity never procs the clearcasting state

https://it.classic.wowhead.com/spell=16864/omen-of-clarity

**Comment by notsofamous** [comment]
Works fine, just a low proc rate.

**Comment by jmee90** [comment]
Mh.... i did a test with a friend in a duel... never procs... tomorrow i will test again.

**Comment by jmee90** [comment]
yeah u are right @notsofamous ... closed
