### ISSUE TITLE
Clipping issues - female human

### ISSUE THREAD

**Issue by ABDisciple3** [SunstriderEmu/BugTracker#2958]
**Describe the bug**
 Female humans can't properly walk up stairs/steps. They get clipped and run in place forcing the player to jump in order to go up. 

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
 Walk normally like other races.

**Screenshots/videos**

https://gyazo.com/2e6d5697b5b917122e03ccf5c31d5899
**Additional context**

**Comment by Godmatik** [comment]
Confirmed, very annoying

**Comment by TheMoneyHater** [comment]
This is not a serverside issue.

**Comment by Grizoor** [comment]
clipping bug must be a serverside issue

**Comment by Sheikthecatman** [comment]
This is not something we can control.
