### ISSUE TITLE
layering issues elevator

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#2959]
followed 1 char with another not in a group.  went on an elevator, walked off at the bottom.  2nd toon must've been desync'd because he fell off the elevator and died.  Have not killed myself doing this before, but have noticed multiple times, even in same group, elevators are in different up/down positions for each toon.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3099
