### ISSUE TITLE
Players not receiving my whispers when Im in raid group

### ISSUE THREAD

**Issue by Niylah** [SunstriderEmu/BugTracker#2960]
Most players wont receive my whispers, Seems that if a player is whispering me FIRST I can answer and he will receive the message. But if I type first he wont see it.  

Can't really give you any more info then that :/

Ingame name: Eremyn

**Comment by kelno** [comment]
Please include your character name

**Comment by Niylah** [comment]
Eremyn

**Comment by kelno** [comment]
Can't see an issue, is this still happening?
