### ISSUE TITLE
Seal Of Justice Buggs

### ISSUE THREAD

**Issue by uncertainly95** [SunstriderEmu/BugTracker#2961]
**Describe the bug**

Seal of Justice ruining Psychic Scream (gets the target out of fear)
**To Reproduce**
 just unleash the Seal of Justice on a player in arena and then try to fear it *psychic scream* with a Priest
1. Cast Seal of Justice. on a Player in Arena
2. Try to fear it with Psychic Scream
3. Target moves freely

**Comment by Rettiy** [comment]
Sadly this nonsense is intended.

**Comment by oldspices** [comment]
read the tooltip? ROFL
