### ISSUE TITLE
Socrethar is or becomes unattackable

### ISSUE THREAD

**Issue by Balanarr** [SunstriderEmu/BugTracker#2963]
**Describe the bug**
Socrethar is or becomes unattackable

**To Reproduce**
Attempt to kill Socrethar for quest Turning Point by flying or using the portal
Maybe need to have Aldor people attempt to complete the quest before

**Expected behavior**
Socrethar is unattackble. He is just standing there with some Aldor npc's around staring at each other endlessly

**Comment by Simon-GM** [comment]
This has been fixed already.

Quote from changelog (Tuesday, 5 May 2020):
> Fixed issues with Kaylaan not resetting correctly during Deathblow to the Legion.

**Comment by EL100** [comment]
Looks to be bugged still. There are 3 groups in front of Socrethar now and he's not doing a thing.

**Comment by YakubSix** [comment]
Now is quest again bugged , socrethar is unattackable
