### ISSUE TITLE
Well Fed not stacking as it is supposed to

### ISSUE THREAD

**Issue by kyeda** [SunstriderEmu/BugTracker#2965]
Description:

Blessed Sunfruit Juice (10spirit) and Blessed Sunfruit (10strength) which require Argent Dawn revered does not stack with each other, nor with other well fed buffs from TBC as it is supposed to. 

Current behaviour:

Only one buff can be active at a time, wether it is the well fed or one Argent Dawn. 

Expected behaviour:

Both buffs from Argent Dawn are supposed to stack with each other, and also with a well fed from TBC. 

Steps to reproduce the problem:

Consume 1 buff from Argent Dawn, then consume another. The second buff will replace the previous one, instead of stacking, add a well fed from TBC and the same thing happens. 

Proof of the stacking: 

https://fr.classic.wowhead.com/item=13810/fruit-solaire-b%C3%A9ni#english-comments

It was only in Wrath that they changed it.

**Comment by NeonicSupersonic** [comment]
Your proof is prior to 2.1; all consumes stacked before that, including vanilla and tbc tank flasks and so on.
