### ISSUE TITLE
Client Crash when logging on character

### ISSUE THREAD

**Issue by LuciusLancer** [SunstriderEmu/BugTracker#2966]
When I try to log onto my shaman character name "Hghar" my client crashes immediately. This was happening more and more frequently since Saturday. Today, Tuesday (14/4/20), it closes right after I log in.

I tried a different character and it seems to work fine.

I am playing on a Mac client. Tried on two different computers and the same problem is happening. Seems to be isolated to this one character. 

I'll be happy to provide links to the client I'm using and OS information for the computers if needed.

I can also provide the terminal logs immediately following the crash.

Please help! This character is my main and suddenly I can't play it!

**Comment by Smashyxgod** [comment]
happens to me too , specially when playing windowed full screen mode and i alt tab to my google chrome , 1 month ago didn't happen but now it does. i think this happens because of some update.

**Comment by Godmatik** [comment]
@LuciusLancer 

Sounds like you have a corrupt client is having trouble with where your character is located, if you contact a GM they can move your character, but when you go back to that location it will crash again

**Comment by beraus** [comment]
Contact us via ticket or on discord. Thanks!
