### ISSUE TITLE
Lost items from auction house

### ISSUE THREAD

**Issue by wyogiw** [SunstriderEmu/BugTracker#2967]
Hello there endless crew :) im having an issue with auction house for last two days. Couldnt see items in my auction and also lost some items without getting money or actual item back. i recived about 10 blank mails without single word in em. But i was still able to sell few thing. Strange never happend before.  Dont know if its gone for good or its gonna show up. 

Thank you

**Comment by Godmatik** [comment]
This mail bug has been around for a while. 

If you completely close and re-open your client, it's a temporary fix and you should be able to receive and send mail again.
