### ISSUE TITLE
Clefthoof Bulls Despawning

### ISSUE THREAD

**Issue by Ruek123** [SunstriderEmu/BugTracker#2968]
**Describe the bug**
Clefthoof Bulls in nagrand despawning mid-fight frequently. Appears to be when another one spawns somewhere else.

**To Reproduce**
Farming the clefthoof bulls in nagrand in various locations netted same results. Intermittently despawn and lose the mob altogether. This h as happened upwards of 100x for me while farming the leather.
1. Respawns causing currently spawned to despawn.
2. 
3. 

https://www.wowhead.com/npc=17132/clefthoof-bull

**Expected behavior**
Mob shoudl stay

**Screenshots/videos**

**Additional context**

**Comment by Sheikthecatman** [comment]
Seems to be fixed.
