### ISSUE TITLE
[MINING] FEL IRON

### ISSUE THREAD

**Issue by Baliang47** [SunstriderEmu/BugTracker#2969]
**Describe the bug**
File Iron Deposite not respawning
**To Reproduce**
Today on a period of 2 hours i stayed closed to Falcon Point where a lot of Fel Iron Deposit spawn and not any of them respawned. I think there is something wrong with the respawn timer for those mines. I couldn't find any mines in Hellfire Peninsula in 2 hours.*

https://tbcdb.com/?object=181555

Thanks

**Comment by LacerD85** [comment]
Its not only fel iron
zangar = 1 deposit after 1h searching for minerals
hellfire = 2 deposit after 3h searching for minerals
nagrand = 2 deposit after 3h searching for minerals

it feels very broken, no minerals after hours of riding true the lands and u see sothing...

please fix it fast

**Comment by Smashyxgod** [comment]
Truth , many players farm , impossible to level blacksmith or craft any items .
A lot of players farm with ground mount 100% and others got 280% and you never find a vein.
Auction House is very expensive too , primal fire in my case .

**Comment by Jerrythemagicdog** [comment]
Mining nodes are receiving an overhaul after next restart. Thanks!
