### ISSUE TITLE
Not working battlegear improvements

### ISSUE THREAD

**Issue by djayna** [SunstriderEmu/BugTracker#2970]
Dear developers, I faced the problem of improving the characteristics when collecting a certain type of equipment. My nickname in the game Djayna. I have collected the complete Evoker's Silk Battlegear. This set should add 35 resistance Rating and reduce blink cooldown by 2 seconds, but this improvement does not occur. Please pay your attention to this problem and correct the error if possible, since the Horde is already strong due to its racial abilities, so it still does not work improvements from sets. Thank you very much!
![image](https://user-images.githubusercontent.com/63679815/79278872-5d6fa680-7eb5-11ea-9fbc-c20545bf6b6f.png)
![image](https://user-images.githubusercontent.com/63679815/79278920-7e37fc00-7eb5-11ea-9ae0-fb1258bb0093.png)

**Comment by Jerrythemagicdog** [comment]
Both bonuses work, issue is invalid.
