### ISSUE TITLE
Whipper Root Tuber Quest Broken

### ISSUE THREAD

**Issue by Piarsse** [SunstriderEmu/BugTracker#2972]
**Describe the bug**
Corrupted Whipper Roots in Felwood are broken, upon turning in the 3 Cenarion Plant Salves necessary to cleanse them to receive Whipper Root Tubers, nothing happens. From what I know, Songflowers, similar to the quest format of the Whipper Roots, work properly as I've seen people in raids with the buff they provide when consumed. 

**To Reproduce**

1. Replicate format of other Felwood repeatable quests, whatever that means in terms of scripting.
2. If that doesn't work, find way to reward players with instant quest reward upon completion instead of spawning new NPC object to interact with to receive rewards.

Item: https://classic.wowhead.com/item=11951/whipper-root-tuber
Quest: https://classic.wowhead.com/quest=4117/corrupted-whipper-root#comments
Quest: https://classic.wowhead.com/object=164883/cleansed-whipper-root#same-model-as

**Expected behavior**

I believe a "cleansed" version of the NPC Object is supposed to spawn in place of the corrupted root, however the corrupted version does not disappear upon quest completion.
**Screenshots/videos**

https://imgur.com/a/UCpAIkg
**Additional context**

**Comment by P5vRU** [comment]
When you deal with this problem, please note that a similar failure is present in other flowers in Felwood. There are several types of flowers in this location. I just ran into this breakdown when I tried to get https://classic.wowhead.com/item=11952/night-dragons-breath#created-by-spell

**Comment by TheMoneyHater** [comment]
Please fix this!

**Comment by TheMoneyHater** [comment]
plz

**Comment by TheMoneyHater** [comment]
please2

**Comment by TheMoneyHater** [comment]
please3

**Comment by TheMoneyHater** [comment]
please4

**Comment by Sheikthecatman** [comment]
Thanks! All Corrupted Flowers have been fixed in [3a6dac4a1b43db0290e815de6fa27463a2cad9e8](https://github.com/kelno/sunstrider-scripts/commit/3a6dac4a1b43db0290e815de6fa27463a2cad9e8).

The behavior should be corrected, the fix will be live next server restart.
