### ISSUE TITLE
Voidshriekers in Netherstorm

### ISSUE THREAD

**Issue by ABDisciple3** [SunstriderEmu/BugTracker#2974]
**Describe the bug**

Mob not dropping +15 shadow resistance to cloak enchant. Been farming nearly 5 hours on multiple occasions.

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Navashed** [comment]
I also farmed them for awhile with no drop.

**Comment by pinkisnotgay** [comment]
![enchant](https://user-images.githubusercontent.com/44933866/79549568-7041d100-8097-11ea-92a2-8b274bcc6b24.jpg)

**Comment by ABDisciple3** [comment]
Just got it on 2nd mob, looks like the drop table was fixed between opening the ticket and now.
