### ISSUE TITLE
[Druid] [Talent] improved mark of the wild

### ISSUE THREAD

**Issue by jmee90** [SunstriderEmu/BugTracker#2975]
**Describe the bug**
bonus of Improved mark of the wild isen't applyed 

**To Reproduce**
1. take 5 point on talent Improved mark of the wild
2.  cast Mark of the wild on a target (or Gift of the wild)

**Expected behavior**
the spell should gives +18 attributes and +33 resistence (but it gives +14 attributes  and +25 resistence)

**Comment by Ellissay** [comment]
I can confirm it and the mark/gift of the wild stats are applyed after other buffs to improve stats like the paladin's blessing of kings

**Comment by notsofamous** [comment]
Tooltip on targets dont update in TBC, spell works as intended. (make the target reply with his actual stats before and after buff is applied)

**Comment by jmee90** [comment]
Right , @notsofamous +1 its only a problem of tooltips.
Closed
