### ISSUE TITLE
Dungeon adjustment: Old Hillsbrad Foothills

### ISSUE THREAD

**Issue by DiaWreckingball** [SunstriderEmu/BugTracker#2976]
**Describe the bug**
Aggro range is way too high (pulling mobs behind the houses) and slightly overtuned mob strength (hitting a too hard - looking at old videos from this dungeon.

**To Reproduce**
Pulling mobs in front of the houses - the pats behind the houses should come too.

**Expected behavior**
Mobs from behind the houses should not pull aggro, when mobs are attacked in front of the houses.
And mobs hitting too hard - for a dungeon for under lvl 70.

**Additional context**

**Comment by kelno** [comment]
Thanks for reporting.
The npcs in houses are linked together, this is intentional.
The difficulty is also tuned and not meant to be like retail was back then.
