### ISSUE TITLE
"Soothsaying for Dummies" doesnt work

### ISSUE THREAD

**Issue by Pataton** [SunstriderEmu/BugTracker#2977]
**Describe the bug**
So yesterday I wanted to change from gnomish engi to goblin after I crafted some gnomish stuff. So i went to tanaris but the book that should offer me the unlearning option doesnt work, unfortunately it didnt show any dialogue.

**To Reproduce**

1. 
2. 
3. 

Item: https://classic.wowhead.com/object=177226/book-soothsaying-for-dummies
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**
https://legacy-wow.com/tbc-engineering-guide/

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
