### ISSUE TITLE
Pet losing health once dismounting

### ISSUE THREAD

**Issue by affysis** [SunstriderEmu/BugTracker#2979]
**Describe the bug**

Every time i've been mounted and then dismount a portion of my pets health is missing, this seems to increase every time i dismount in sucession

**To Reproduce**

1. Mount up, dismount - repeat
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

Expectation were that it was going to lose health each time I dismount. In this case it should actually have full HP or the HP that you earlier dismissed/mounted your pet with.

**Screenshots/videos**

**Additional context**

I've done to little testing if this is something that just happens with my current pet or if it is something with my current mount.

**Comment by z5n** [comment]
issue has since been fixed
