### ISSUE TITLE
enh shamy fist weapon not skilling up

### ISSUE THREAD

**Issue by nohope1978** [SunstriderEmu/BugTracker#2981]
i learn the skill  and it say i learn it   but it not in my skill book and  i cant skill  it  but i have a fist weapon equiped 
![1](https://user-images.githubusercontent.com/63739122/79363967-a1df5e80-7f16-11ea-856f-8afe674669a8.png)
![2](https://user-images.githubusercontent.com/63739122/79363980-a6a41280-7f16-11ea-8369-9922d53e461f.png)
![3](https://user-images.githubusercontent.com/63739122/79363985-a9066c80-7f16-11ea-9e87-29c5e8beae6a.png)

**Comment by notsofamous** [comment]
Fist weapons = unarmed skill

**Comment by nohope1978** [comment]
i dont get it  i remember  it was call fist weapon

**Comment by kelno** [comment]
Yes it's using unarmed skill, no issue here!
