### ISSUE TITLE
quality of life:  repair @aldor inn in shat

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#2983]
this may not be blizlike, but there really should be a repair at the aldor inn in shattrath.  warmane loaded a random blacksmith next to the mailbox... and i just don't think its necessary to make people run all the way up into aldor temple or all the way to LC for repair.

**Comment by hashblaster** [comment]
This is a bug tracker, not a suggestion box.

**Comment by Sheikthecatman** [comment]
There's an Engineering Supplier outside Aldor Inn that's there after patch 2.4.2
[Technician Halmaha](https://www.wowhead.com/npc=27711/technician-halmaha)
