### ISSUE TITLE
Can't whisper and talk in guild chat, as well as see whispers and guild chat

### ISSUE THREAD

**Issue by Endorssi** [SunstriderEmu/BugTracker#2984]
<I logged into my character. There is a complete reset of my interface settings. I have to re-join global chat again. Suspociously, nobody is chatting in guild. I try to chat - nothing happens, and I dont see my own message. I try to whisper a guildie, and see no response, as well as typing into guild for people to /w me if they see my message, which they dont.

I can chat in the global, though.

This happened after me having to force shut - down laptop due to freezing.

Also, this isnt the first time this happened, and the first time I deleted wow and re-downloaded it again, which seemed to solve the issue, but I'd like to not have to wait for download every few days.>

**Comment by kelno** [comment]
Can you include your character name?
