### ISSUE TITLE
[Warlock] Soul link doesn't work with enslaved demon

### ISSUE THREAD

**Issue by hashblaster** [SunstriderEmu/BugTracker#2987]
**Describe the bug**

Soul link should work when you control an enslaved demon.

**Comment by bagarebagare** [comment]
It should not

**Comment by hashblaster** [comment]
Soul Link
16% of base mana 100 yd range
Instant cast
When active, 20% of all damage taken by the caster is taken by your Imp, Voidwalker, Succubus, Felhunter, Felguard, **or enslaved demon instead.** That damage cannot be prevented. Lasts as long as the demon is active and controlled.

**Comment by hashblaster** [comment]
"The Burning Crusade Patch 2.1.0 (2007-05-22): Adjusted tooltip to explain that the damage transferred to the pet cannot be prevented. The functionality remains unchanged. This ability will now work with enslaved demons. "

https://wow.gamepedia.com/Soul_Link

**Comment by z5n** [comment]
thanks, fixed with next restart
