### ISSUE TITLE
underbog ghaz'an an acid debuff 

### ISSUE THREAD

**Issue by nainphoman** [SunstriderEmu/BugTracker#2988]
underbog ghaz'an doing is debuff on everybody even if they dont face the boss but i read on all the forums i found and hes supposed to to the debuff only in front of him

**Comment by psioniczombie** [comment]
Ran Underbog this morning and experienced this same bug. Acid Spray(frontal cone) was hitting the whole party even tho we were not in front of the boss. Happened both times we attempted the boss and we checked the combat log.

**Comment by itsjessedme** [comment]
This is also happening to my groups as well on Normal difficulty. The acid spray was hitting in a 360 degree arc and killing our group within 2 spits. My first group had enough damage to kill it before it killed everyone but my second group consisting of 64-66 players was unable to kill it.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
The boss has two spells that have the "Acid" word in them.
Acid Breath (34268) is a frontal cone attack that can be dodged by being outside of the 53 degree angle.
Acid Spit (34290) is a regular AoE attack that can hit anyone in range.
Which one are we talking about here?

**Comment by itsjessedme** [comment]
The acid Spit on normal difficulty seemed to hit the entire group, even
those standing at max range.

Thanks for replying and clarifying.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with the next update.
