### ISSUE TITLE
Unable to Connect into OWN Account - Others Work -

### ISSUE THREAD

**Issue by Usarag33** [SunstriderEmu/BugTracker#2989]
**This Problem first occured some hours ago, around 2am MESZ.**

So i start the game, fill in my Account Data and somehow get handed off to choosing a realm again. After successfully choosing my existing Account and Entering, i get instantly "Disconnected from server". This happened after a full server-disconnect about 9 or so hours ago. My friends could reconnect just fine, problem persisted on my end.

**Friend of mine succeeds to log in to my account** and somehow i can even log in to HIS account. I even created a new Account on endless just to try a new setup, but it didnt work. 

Maybe useful: Getting disconnected was kinda normal to me by now. It happened around 10 times a day. But i was able to reconnect instantly without fail. 

Reinstalled everything fresh and still no changes. Mystery how i can log into my friends accounts, but not my own. 

**To Reproduce**
Enter Account Data -> Choose Language and Realm -> Select existing (x) Characters -> Disconnected from server
>be me
>get fkd

**Expected behavior**
Entering Account Data -> Logging in and Connecting -> Fun

**Comment by Usarag33** [comment]
Edit *2am UTC+2 - Dont know if thats relevant. Just wanted to add the timezone for general understanding.

**Comment by Blenkus** [comment]
I have the same problem.

**Comment by Blenkus** [comment]
works normally on other servers

**Comment by Blenkus** [comment]
https://photos.app.goo.gl/QfgzNQLoMR16DThH7

**Comment by Usarag33** [comment]
> https://photos.app.goo.gl/QfgzNQLoMR16DThH7

exactly what i am experiencing. did you also have a windows update before restarting ?

**Comment by kelno** [comment]
Did you have other characters connected already from the same computer?

**Comment by Usarag33** [comment]
> Did you have other characters from other accounts connected at the same time from the same computer?

No i did not. The thing is, it just works again.. Tried to log in and works. Just like that. i fixed nothing. Just tried an earlier windows backup, but that didnt go fully thru. So cant say that i took any measures. I would leave this thread open tho, for the ones, who still have the same problem, as theres no real solution for it by now.

**Comment by kelno** [comment]
Alright, thanks for answering
