### ISSUE TITLE
second wind (Warrior talent) Procs even on resists. 

### ISSUE THREAD

**Issue by oldspices** [SunstriderEmu/BugTracker#2990]
**Describe the bug**

I pounced a warrior in arena and he resisted the stun but still got second wind
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by kelno** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2497
