### ISSUE TITLE
Tanaris Field Sampling

### ISSUE THREAD

**Issue by Ministr564** [SunstriderEmu/BugTracker#2992]
When I do quest Tanaris Field Sampling, mobs just won't drop untested samples, even though I have Field testing kit and also I have 1 hour and 45 minutes left to finnish the quest so please, help me with this.
At endless.gg my acount is called Ministr and in game my character is called Cadaver.
Thank you

**Comment by EL100** [comment]
I had the same issue, which was posted in https://github.com/SunstriderEmu/BugTracker/issues/2852

**Comment by Ministr564** [comment]
> I had the same issue, which was posted in #2852

But as I can see, noone really helped you with it, right? :/

**Comment by Sheikthecatman** [comment]
Issue was resolved in the thread mentioned above.
