### ISSUE TITLE
Hellfire ramparts Vazruden the herald / Nazan

### ISSUE THREAD

**Issue by hirexnoob** [SunstriderEmu/BugTracker#2995]
By pulling the Hellfire sentries back from the platform where the boss circles around and you kill the them the boss bugs out and does not land. You end up having to reset the instance.

Vazruden The Herald : https://www.wowhead.com/npc=17307/vazruden-the-herald
Nazan : https://www.wowhead.com/npc=17536/nazan

As far as i know the boss has always landed no matter where you kill the hellfire sentries. First time i see this bug.

**Comment by Jerrythemagicdog** [comment]
Fixed with next restart, thanks!
