### ISSUE TITLE
Fel Mana potion not working (in feral form- for cat dps) likely judgement bug too-

### ISSUE THREAD

**Issue by oldspices** [SunstriderEmu/BugTracker#2996]
**Describe the bug**

Fel Mana potion is not returning mana when you are in cat form ( and probably bear form too) 
**To Reproduce**

Get a certain amount of mana- say 2k mana, pop potion. wait- leave form and you will be at less mana than you started with
1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=  https://tbcdb.com/?item=31677
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

It is supposed to return lots of mana over a short time- this is necessary for CAT DPS~ as finding enough mana to powershift is very difficult, regular mana pots dont give as much as these should.

**Screenshots/videos**

**Additional context**

I havent tested it yet but its likely that ferals are not returning mana when attacking paladins judgement of wisdom, too :(

**Comment by Aeded** [comment]
not a bug, next time use search function on github it has been already reported

**Comment by kelno** [comment]
Thanks for reporting.
Can you provide proof of how it should work there?
