### ISSUE TITLE
Quest Badlands Reagent Run II bugged

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#2997]
**Describe the bug**
Quest description says: "This lockbox contains three empty thaumaturgy vessels; they are imbued with an attunement aura that will drain the blood of a scorched guardian dragon. Using one on the beast will anger it greatly, so be warned. Once you have all three filled, bring them to me."  First of all, only 1 vessel is inside the lockbox. When I tried to use the vessel on the dragon, 2 of the filled vessels were produced and the original vessel disappeared. Tried again later, same thing. When I read the comments on wowhead, the quest should only be available if you have a 210 alchemy skill, which I don't. I don't even have alchemy.

**To Reproduce**
1. Take quest after completing Badlands Reagent Run.
2. Open up the lockbox. Voila, only one vessel.
3. Use the vessel on one of the guardian dragons. 2 filled vessels were produced.

https://classic.wowhead.com/quest=2203/badlands-reagent-run-ii#comments

**Expected behavior**
Check player alchemy skills. If lower than 210, the quest shouldn't be available. If so, the lockbox should contain 3 vessels, or upon using the empty vessel, 3 filled vessels should be produced.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
Seems like you not being an Alchemist prevented you from getting the correct amount of vessels from the lockbox.
