### ISSUE TITLE
Defense skill broken on Prot pally

### ISSUE THREAD

**Issue by Wesleycash82** [SunstriderEmu/BugTracker#2998]
The defense skill has been stuck at 351/370 for a long time.  After tanking several instances it has not budged.  Tried unlearning anticipation and seeing if that had anything to do with it.  However, then defense just stayed stuck at 331/350.  Not sure if this is because my char leveled as prot.  Maybe if that skill had not been selected it would have leveled to 350 (and therefore 370 with the skill 5/5 Anticipation).  Please advise.

**Comment by kelno** [comment]
If this is still happening please include your character name

**Comment by cjbreeze** [comment]
I am actually having this same issue im stuck at 352 for awhile now character name Palabreeze

**Comment by Godmatik** [comment]
Heard it happens if you spec Anticipation (talent that increases defense) before you naturally get defense capped from mobs hitting you.

**Comment by cjbreeze** [comment]
> Heard it happens if you spec Anticipation (talent that increases defense) before you naturally get defense capped from mobs hitting you.

So if I drop the talent it should fix the issue?

**Comment by kelno** [comment]
Confirmed, it takes your gear into account and decides you're maxed out already.

**Comment by kelno** [comment]
Fixed with next update
