### ISSUE TITLE
Quest Necklace Recovery, Take 3 is not available to me after Deliver the Gems

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#3000]
**Describe the bug**
I turned in the quest Deliver the Gems with Dran Droffers. I received the quest reward (gold) in the status window, but the quest window wouldn't close when hitting "complete" button. Therefore I clicked on the X box on the top right. I watched the dialog between Dran and his son, but the next quest in chain "Necklace Recovery, Take 3" was not available to take. I went back to Jarkal in Kargath and it was the same. 

**To Reproduce**

1. Get the quest Deliver the Gems from Jarkal in Kargath.
2. Go to Dran Droffers in Orgrimmar to turn in the quest. 
3. ....

https://classic.wowhead.com/quest=2341/necklace-recovery-take-3

**Expected behavior**
The next quest in chain "Necklace Recoery, Take 3" should be available to take at step 3.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
