### ISSUE TITLE
 [Dukes of the Council] quest bugged / missing quest option to spawn Dukes

### ISSUE THREAD

**Issue by bagarebagare** [SunstriderEmu/BugTracker#3001]
**Describe the bug**
The quest "Dukes of the council" can't be finished because the stones around every Twilight base camp aren't scripted. There is no option to summon the Dukes or Lords even when applying the 3 set off; Twilight Cultist Mantle, Twilight Cultist Robe, Twilight Cultist Cowl.

**To Reproduce**
1. Equip Twilight Cultist Mantle, Twilight Cultist Robe, Twilight Cultist Cowl.
2. Talk to Lesser Wind Stone.
3. Get a questlog with no option to chose to spawn a Duke.

Item: https://classic.wowhead.com/item-set=492/twilight-trappings
Quest: https://classic.wowhead.com/quest=8332/dukes-of-the-council

**Expected behavior**
Should Bestow the wearer with the evil aura of a Twilight's Hammer Cultist and be able to spawn a Duke with the set equipped and the 3 set should be consumed when the Duke spawns.

**Screenshots/videos**
https://www.youtube.com/watch?v=txu7kl4N_Pc

**Additional context**
This is also the same for Lords that you spawn by getting the right materials at the same area!

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed some time ago.
