### ISSUE TITLE
Hunter target switch

### ISSUE THREAD

**Issue by Abrith** [SunstriderEmu/BugTracker#3003]
Hello there!,

I have noticed that when I change target as hunter from one to another hunter is drawing arrows very quickly and endlessly but never releases arrow until first target is dead or hunter is moved.
This problem is lowering DPS in PVE and often giving advantage to enemies in PVP and you need to keep in mind all time that you need to 'move' after switching target. It happens all the time and to show what I mean I have recorded whole situation. hope you can solve this problem ASAP,

Kind Regards,

Gahar

[World Of Warcraft 2020.04.17 - 01.44.13.04_Trim (2).zip](https://github.com/SunstriderEmu/BugTracker/files/4490483/World.Of.Warcraft.2020.04.17.-.01.44.13.04_Trim.2.zip)

**Comment by mayday2013** [comment]
confirmed. already created the same issue.

**Comment by kelno** [comment]
Thanks!
Duplicate https://github.com/SunstriderEmu/BugTracker/issues/2940
Fixed and applied since this morning
