### ISSUE TITLE
jewel crafting statues

### ISSUE THREAD

**Issue by JUSTANDY1993** [SunstriderEmu/BugTracker#3005]
jewel crafting statue do not work correctly 50% of the time they do not work at all and the other 50% of the time they only work when you are not taking any damage but the reason for having these is to heal yourself without having to use potions or heals on artantis netherwing and tbc retail when you cast this they start to flow heals per second into the caster the statue only has 1 hp and if the caster does not do damage to npc before placing this npc should attack and kill it but the reason for me to spend 500 gold training up jewelcrafting for my level 45 twink enchance shammy is so i dont have to cast heal on myself while doing world pvp but everytime i have used it in pvp it has never worked never onces healed me instead it literally stand there like a statue not firing out blue beam with heals please can this be fixed as its extremmly frustrating that i have farmed for countless hours to be able to afford to train jewel crafting for the 1 item i wanted not to even work thanks

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2377
