### ISSUE TITLE
Mobs despawning

### ISSUE THREAD

**Issue by Shamelessmob** [SunstriderEmu/BugTracker#3006]
Mobs despawning in front of you. Either you're attacking them or just getting close to them, for no good reason they despawn. It get really annoying if you're are farming those mobs for reagents and they despawn at 10% of health.
Mobs i'am having problems with right now are Clefthoof Bulls to the left of Garadar.

https://tbc-twinhead.twinstar.cz/?npc=17132

I belive mobs do not despawn in front of you or when you attack them.

https://sun9-40.userapi.com/y9ophT_auuujWxN_DHDk-UME6jGDkJFszsQaTA/5SGnuA4bNy0.jpg
https://sun9-13.userapi.com/h5NMQDDi2iB_6VDgUuF0CkOw5KUuiqTHpfRFPA/H_-uvKXwaiQ.jpg
https://sun9-23.userapi.com/IHZPrSSaAaIJBcX99TTMMfrbHBD7Vok02cpb5g/1SWDz3pOIac.jpg

**Comment by Sheikthecatman** [comment]
Seems to be fixed.
