### ISSUE TITLE
 [Firewing Signets] quest bug

### ISSUE THREAD

**Issue by controlledlab** [SunstriderEmu/BugTracker#3007]
Hello,

I have 10/10 Firewing Signets quest items for the quest [65] Firewing Signets . The NPC is showing question mark highlighted in yellow, but "continue" option is inactive. Here I send screenshot of the issue:  
![WoWScrnShot_041720_103940](https://user-images.githubusercontent.com/63841481/79544627-fd852580-8097-11ea-937f-c1c194fc8bd9.jpg)

**Comment by beraus** [comment]
You're probably honored - you need to hand in Sunfury Signets now.
