### ISSUE TITLE
Elite Val'zareq the Conqueror  bugged

### ISSUE THREAD

**Issue by Ownitup** [SunstriderEmu/BugTracker#3008]
Val'zareq the Conqueror in Shadowmoon Valley is currently bugged . After you kill him he de spawns and you can't loot his body. He drop's a quest item [The Journal of Val'zareq] which lead's to a quest for the Tabard of the Illidari .

**Comment by beraus** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/16673248/82965078-73e64300-9fc7-11ea-83ce-9ab4fc7fb666.png)
