### ISSUE TITLE
Charm of Swift Flight

### ISSUE THREAD

**Issue by druiddon** [SunstriderEmu/BugTracker#3009]
**Describe the bug**
Trinket from Swift Flying form questline doesn't increase flying speed in swift flying form

**To Reproduce**
Equipping / Unequipping doesn't change the fying speed. Tested with a hunter with 280% Speed flying mount that has a talent with +8% riding speed. The hunter was always faster than the druid, even with +10% Charm of Swift Flight

Tested with 

**Expected behavior**

Increased flying speed by +10%

**Comment by z5n** [comment]
unable to reproduce
