### ISSUE TITLE
Writhing Highborne, Darkshore

### ISSUE THREAD

**Issue by asketao** [SunstriderEmu/BugTracker#3010]
**Describe the bug**
Attacking or killing Writhing Highborne gives you a wow error and when you relog, you're dead

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by asketao** [comment]
Even just getting attacked by them gives a WoW error

**Comment by Nymera** [comment]
![WowError](https://user-images.githubusercontent.com/63877481/79607752-616c1600-80b9-11ea-956a-724e2e23a5fd.png)

Can confirm it happens every time when interacting (attacking or being attacked by) with Writhing Highborne mob.  It also happens upon interacting with Anaya Dawnrunner for the "For Love Eternal" quest.

**Comment by Sheikthecatman** [comment]
Cannot reproduce, seems to be client-side.
Try clearing cache and installing another client.
