### ISSUE TITLE
Items gone from bank account mail

### ISSUE THREAD

**Issue by reinart1** [SunstriderEmu/BugTracker#3012]
Ive sent a lot of items during the past month to my bank accounts mail (around 50 stacks and more of netherweave clot, loads and loads of green items and so on), but they are all gone, only the most recent 10 days worth of mail is still there.
Yes, some of the mails were sent back after 30 days like it should happen, but most of the items are lost, only the recent 20 days worth of items are still in bank accs mail .. please help me

I have no other way to contact you guys, couldnt find any GM support on site.

**To Reproduce**

1. I have no way of reproducing mail bugs.

Item: farmable items like netherweave cloth and green/blue items 10s and 10s if not close to hundred green items

**Screenshots/videos**
no screenshots of my items since i thought they cant get lost in mail .. 

Hopefully someone can help me out. 

Character name is : Pank

**Comment by reinart1** [comment]
Turns out all the items are still there, seems they lowered the amount of mail you can see at one time, once i took mail from mailbox older mail spawned back

**Comment by beraus** [comment]
Thanks!
