### ISSUE TITLE
Escort quests suck in this realm

### ISSUE THREAD

**Issue by whakahemo** [SunstriderEmu/BugTracker#3017]
In particular Escape from Firewing point

The NPC you are escorting runs off trying to fight everything that other players are fighting - there is no way you can even finish this quest with people farming for rep and the fast respawn rate

Please fix very irritating

**Comment by beraus** [comment]
You must've been too far from the quest giver, she credited me correctly on both Alliance and Horde.

_Originally posted by @Jerrythemagicdog in https://github.com/SunstriderEmu/BugTracker/issues/3791#issuecomment-652995103_
