### ISSUE TITLE
no fel iron ore

### ISSUE THREAD

**Issue by saauuccee** [SunstriderEmu/BugTracker#3020]
**Describe the bug**

there is literally no fel iron ore iv been farming fel iron and found none 3 days in a row for a few hours
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

more fel iron ore will be availlable or the bug will be fix
**Screenshots/videos**

**Additional context**

its been more then a week with this problem i cant get any fel iron ore

**Comment by artieau** [comment]
Fixed.
