### ISSUE TITLE
global and world channel problem

### ISSUE THREAD

**Issue by plaste12** [SunstriderEmu/BugTracker#3021]
i joined at global channel for inv people to dungeon but nobody answered  me for it, then i asked in guild if people see my message in global and they say not, why people dont see my message when i write in global or world channel?

**Comment by Sensoger** [comment]
well i ticket yesterday explaining a similiar problem with /global and GM sent a mail telling "I suggest you to join and use /global". Today ticket explaining what i just comment and another GM tells me come to post the bug. Im still waiting for a fix.

**Comment by kelno** [comment]
Can you include your character names her?
