### ISSUE TITLE
damage balance druid

### ISSUE THREAD

**Issue by friban** [SunstriderEmu/BugTracker#3022]
i dont know what is the problem, but  my character "friban" a balance druid, is making less damage that it should with "moonfire" and " wrath"

**Comment by mayday2013** [comment]
Would be nice to see detailed info about it.

As I can say from your armory, you have ~600 spell damage bonus and tonns of crit.

**Comment by friban** [comment]
the moonfire is doing 400-450 of damage and wrath between 750-850 with almost 600 spell damage i dont think that is correct...

**Comment by mayday2013** [comment]
Looks fine. I remember hitting 1200 in full s4 gear with 1100 spell damage bonus.

You benefit from crit chance, not from spell damage.
