### ISSUE TITLE
Prayer of mending should ignore line of sight. It will not bounce to people on the other side of the pillar

### ISSUE THREAD

**Issue by quezacotl12** [SunstriderEmu/BugTracker#3023]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by mayday2013** [comment]
And it doesn't jump to people out of LoS.

**Comment by sposobniy** [comment]
Pom should not bounce when people not in your line of sight . Works like it should be 
https://youtu.be/QyTyNaiEJKs?t=76  Hydra s4 momemt at 1.21 pom heal only himself 
https://youtu.be/6JjgpeS0YDU?t=10m43s

**Comment by artieau** [comment]
Closing unless you have evidence on how you believe it should work.
