### ISSUE TITLE
Quest: Guardians of the Altar

### ISSUE THREAD

**Issue by Elunekin** [SunstriderEmu/BugTracker#3025]
**Quest Event does Not Start**

NPC: https://www.wowhead.com/npc=10300/ranshalla
Quest: https://www.wowhead.com/quest=4901/guardians-of-the-altar

*Expected to see the lore event start when Ranshalla begins to channel her spell at the altar in Owl Wing Thicket, Winterspring. She channels for several minutes without effect. Nothing to be activated around the altar nor mention of an item to be used.*

**Screenshots/videos**
![Screenshot (119)](https://user-images.githubusercontent.com/63893426/79628341-22b47b00-810e-11ea-8f17-7934963a7575.png)

**Comment by Sheikthecatman** [comment]
Just tested the quest locally and it worked without an issue.
I suggest clearing cache and re-doing the whole quest.
