### ISSUE TITLE
Disconnect timer too short during character creation

### ISSUE THREAD

**Issue by simuloid** [SunstriderEmu/BugTracker#3026]
**Describe the bug**
When creating a character, I get disconnected if I take more than about 60 seconds customizing my character.

**To Reproduce**

1. Login.
2. Create new character.
3. Choose race, class, and customize appearance.  If you take more than about a minute, you'll get logged off.

N/A

**Expected behavior**

The timeout for character creation should be more like 5 minutes.  Some of us like to get the look and name just right.

**Screenshots/videos**

**Additional context**

**Comment by Jorgepvp** [comment]
+1
But it's not the character creation, try join to your acc and open the window about your addons to mark or unmark. it will remove you in 5-10 secs aprox...

**Comment by TidyComment** [comment]
+1
I'm having the same problem.

**Comment by knuper** [comment]
+1
Same

**Comment by kelno** [comment]
Seems to happen after a minute

**Comment by kelno** [comment]
Fixed with update tomorrow morning
