### ISSUE TITLE
I abandonned Rogue poison quest in SW, and can't find NPC to restart it, Mathias (SI:7) is bugged?

### ISSUE THREAD

**Issue by Mancyanix** [SunstriderEmu/BugTracker#3027]
**Describe the bug**
I started Rogue poison Quest in Stormwind with Mathias (SI:7). I couldn't finish it, so i abandonned it, and now, i want to do it again, but Mathias doesn't give me any quest, i think there is a bug

https://fr.classic.wowhead.com/npc=332/ma%C3%AEtre-mathias-shaw. -->
Quest: https://fr.classic.wowhead.com/quest=2360/mathias-et-les-d%C3%A9fias

**Expected behavior**
Quest begin

**Comment by Mancyanix** [comment]
<img width="1120" alt="Capture d’écran 2020-04-18 à 10 06 36" src="https://user-images.githubusercontent.com/63899699/79631910-55856000-815c-11ea-81b9-247f32b3df19.png">

**Comment by Cocio21** [comment]
Are you sure you didnt drop the quest on part 2?  By the tower is your 2nd NPC hiding where this quest sends you.

If you completed the quest at https://fr.classic.wowhead.com/quest=2359/la-tour-de-klaven this is where you need to repick the quest, not at Mathias
