### ISSUE TITLE
Entrapment talent PvP

### ISSUE THREAD

**Issue by mayday2013** [SunstriderEmu/BugTracker#3028]
**Describe the bug**
Tested it proc mechanics from explosive and snake traps - this talent doesn't proc on ticks of these traps.
Immolation and snake trap seems to trigger roots only on initial tick.

**To Reproduce**

1. Set any of mentioned traps on player in a duel
2. Watch this talent not proccing on 3 sec ticks

**Expected behavior**
Each 3 sec tick of immolation, explosive, snake traps

**Screenshots/videos**

**Additional context**
I see issue #187 that says that it procs from all traps, but I can't say that it works now.

**Comment by Jerrythemagicdog** [comment]
Procs from other traps, fixed some time ago, thanks for the issue.
