### ISSUE TITLE
[Quest] Gathering the Reagents - low drop chance

### ISSUE THREAD

**Issue by Cocio21** [SunstriderEmu/BugTracker#3029]
**Describe the bug**
Simply a bad droprate, Fen Strider Tentacle does not drop at 80% ish as it should, its more like 2 drops pr 50 kills ~ 0.04% rate

**To Reproduce**
Kill a bunch of Fen Striders while doing the quest.

Wowhead is shit for this client version, alot of missing/removed items and misinfomation as Wowhead uses DB version for later clients rather than version 2.4.3

Item: https://tbcdb.com/?item=24427
Quest: https://tbcdb.com/?quest=9801
NPC: https://tbcdb.com/?npc=18134

**Expected behavior**
Expected a decent drop rate on Tentacle´s, didnt expect using 45mins solely on this part of the quest grinding Fen Striders.

**Screenshots/videos**
Shouldnt be needed, its not a complex problem

**Additional context**
None.

**Comment by beraus** [comment]
This item drop chance is indeed <15%.
