### ISSUE TITLE
Automatically C.O.D. return bugged

### ISSUE THREAD

**Issue by Valdix** [SunstriderEmu/BugTracker#3033]
Hi,

I'd like to report a issue regarding automatically C.O.D. return after 72h period.
After 72h, if someone doesn't pick up the item, it is just stuck in the mailbox, it's not send back properly to the owner.

I've sent someone the C.O.D. and after 5 days, he had to manually return it.
Also I've tried same thing between my chars and it was with the same result, item is just stuck and doesn't return automatically to the owner.

Could You please take a look at this case?

Thank You and Best regards.

**Comment by kelno** [comment]
Doesn't seem to happen for me, keeping open in case it actually does in some cases. Maybe it's just fixed since.
