### ISSUE TITLE
Blood elf Paladin class quest #2 [ The Second Trial ]

### ISSUE THREAD

**Issue by Grimbase** [SunstriderEmu/BugTracker#3034]
The quest has you go into a gazebo next to the quest giver and interact with a crystal in there. Once you do that, 4 enemies are supposed to appear and you fight them. The enemies never appear after interacting with the crystal.

To reproduce this effect all you need to do is have the second portion of the quest and walk into the gazebo north of the ruins of silvermoon.

https://tbc-twinhead.twinstar.cz/?quest=9686

I expected mobs to attack me after interacting with the crystal

**Comment by saltemporium** [comment]
Quest is broken again.

Click the crystal, it disappears and nothing happens.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
