### ISSUE TITLE
Cant finish quest - Everything will be fine.

### ISSUE THREAD

**Issue by Hustler495** [SunstriderEmu/BugTracker#3035]
I completed the quest - Everything will be alright. Exited from insta and do not see the NPC to finish the quest, another player finished the quest. Now I am at the place of the quest

**Comment by beraus** [comment]
Fixed in [32948668ce04c51a61d62bea890955d1e43dec77](https://github.com/kelno/sunstrider-scripts/commit/32948668ce04c51a61d62bea890955d1e43dec77)

_Originally posted by @Sheikthecatman in https://github.com/SunstriderEmu/BugTracker/issues/2878#issuecomment-623563878_
