### ISSUE TITLE
[Quest] [NPC] Emmithue Smails has not spawned in Stormwind. 

### ISSUE THREAD

**Issue by TidyComment** [SunstriderEmu/BugTracker#3038]
**Describe the Bug**
Since the Children's Week questline has opened, Emmithue Smails, a gnome that sells ice cream, should have appeared temporarily in Stormwind. He is not there. Without him, players will be forced to go to Shimmering Flats to complete the quest "You Scream, I Scream..."

**To Reproduce**
1. Adopt a ward from the orphanage in Stormwind.
2. Accept the "You Scream. I Scream..." quest from your ward. 
3. Go to the location where Emmithue Smails _should_ be.

**Expected Behavior**
Emmithue Smails should be located just to the left of the inn in Stormwind, as depicted [here](https://classic.wowhead.com/npc=14481/emmithue-smails).

**Screenshots**
![Bug1_Photo](https://user-images.githubusercontent.com/57652280/79669279-71066000-8188-11ea-9757-b6c23c2e9733.jpg)
![Bug1_Map](https://user-images.githubusercontent.com/57652280/79669282-75327d80-8188-11ea-9171-c0fc0dfefac0.jpg)

**Additional Context**
I have the addon [Quest Helper](https://legacy-wow.com/tbc-addons/quest-helper/), which is what tells me the location of Emmithue Snails. At least, where he should be.

**Comment by Jerrythemagicdog** [comment]
Thanks, he's there now after some changes to game events.
