### ISSUE TITLE
Seal of Righteousness hitting like a wet Noodle

### ISSUE THREAD

**Issue by davedave1991** [SunstriderEmu/BugTracker#3039]
Seal of righteousness is hitting like a wet Noodle, and judgement of the crusader not working right

If I'm right this ability should scale with spellpower. Even if it doesn't it still hits rlly low. I'm even using Sancity aura (+10% holy dmg) Improved seal of righteousness (+15% dmg), Judgement of the crusader (+127 holy dmg) and the highest I hit is 224..
https://imgur.com/a/WGKrzAY
Without crusader I hit 188 (so the judgement of crusader is only increasing it by 36 not 127 like the tooltip says and just being really low on damage in general)
https://imgur.com/a/Lnm039N
 I have 613 spellpower (shockadin) so that's more than most tankadins and I imagine them having alot of trouble keeping threat now aswell
https://imgur.com/a/VFmuuPi

**Comment by kelno** [comment]
Thanks!

Duplicate https://github.com/SunstriderEmu/BugTracker/issues/1644
