### ISSUE TITLE
After the serwer reset when i was in an instance ( BF ) i got kicked out and after that i cannot log backi in.

### ISSUE THREAD

**Issue by Cipkek** [SunstriderEmu/BugTracker#3040]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by gonxiluti** [comment]
Same with me...

**Comment by cilezile** [comment]
if you resolve it please tell me how.

**Comment by gonxiluti** [comment]
Change the realmlist to : set realmlist logon.endless.gg.
