### ISSUE TITLE
Login Disconect

### ISSUE THREAD

**Issue by gonxiluti** [SunstriderEmu/BugTracker#3041]
Everytime I login, I get insta disconect! 
![dd](https://user-images.githubusercontent.com/63929351/79670225-5b5d5e80-81b9-11ea-98c9-98a940138599.png)
![aa](https://user-images.githubusercontent.com/63929351/79670237-6e702e80-81b9-11ea-978a-934ec47eecf9.png)

Can someone help me?

**Comment by Wrathfull** [comment]
Im Gettin the same problem and i was on friggin RAID

**Comment by gonxiluti** [comment]
Don't know what happened...

**Comment by gonxiluti** [comment]
Change the realmlist to : set realmlist logon.endless.gg.

**Comment by kelno** [comment]
That particular issue should be resolved now
