### ISSUE TITLE
Impossible to res after a disconnect on Arathi

### ISSUE THREAD

**Issue by shaksh** [SunstriderEmu/BugTracker#3042]
**Describe the bug**
I died at Arathi Basin and then got disconnected. After I logged in I appeared as a ghost in the Hall of Brave, Orgrimmar. My grave is located in there and if I click "Accept" on "Resurrect now?" window it doesn't resurrect me. Tried logging out a bunch of times but it didn't help one bit.
Was forced to res at spirit healer.

**To Reproduce**

1. Die on Arathi Basin
2. Disconnect your Internet
3. Log in after around 10-15 min

**Comment by gonxiluti** [comment]
well, i cant even login back

**Comment by InhumanGM** [comment]
Upon attempting to reproduce the issue, I was not able to find any issues. Could you provide more information that could be used to try to reproduce the issue again?
