### ISSUE TITLE
Quest: What The Soul Sees bugged

### ISSUE THREAD

**Issue by Monaqua123** [SunstriderEmu/BugTracker#3045]
The quest What The Soul Seed isn't working. The Darkened Spirits aren't anywhere. They should be near Oshu'gun, but they aren't. 
![WoWScrnShot_041920_023221](https://user-images.githubusercontent.com/63914001/79673902-a772c800-81e6-11ea-9d2d-b47b447c6705.jpg)

**Comment by hashblaster** [comment]
Page a GM ingame, they will fix for you

**Comment by beraus** [comment]
Fixed in [32948668ce04c51a61d62bea890955d1e43dec77](https://github.com/kelno/sunstrider-scripts/commit/32948668ce04c51a61d62bea890955d1e43dec77)

_Originally posted by @Sheikthecatman in https://github.com/SunstriderEmu/BugTracker/issues/2878#issuecomment-623563878_
