### ISSUE TITLE
With ZG closed please provide a way to get Brilliant Wizard Oil

### ISSUE THREAD

**Issue by yolohse** [SunstriderEmu/BugTracker#3047]
So Zul'Gurub is closed as it requires level 71 to get in apparently. This means that it is impossible to farm rep for the weapon oil you can buy from Zandalar Tribe. But I see people selling it on AH so how did they get the recipe? When asking GM I'm told there is no other way to get it? 
![image](https://user-images.githubusercontent.com/59824709/79674425-6b8a3380-81e3-11ea-98a9-81ecdfccf08d.png)

**Comment by artieau** [comment]
ZG will reopen soon.
