### ISSUE TITLE
Auctions Disapearing in AH

### ISSUE THREAD

**Issue by Captnam** [SunstriderEmu/BugTracker#3051]
I wanted to set up 17 Auchtions In The Ah yesterday.
I i Paid the ah fee got the notification`Auchtion created`in the Chat window and the items i tried to sell where no longer in my inventory but when ich checked my auchtions instead of 17 Auctions there where only 8. that means i lost approx 400g which is properly annoying.
I really hope you can help me resolve this issue.
Sincerely Captnam

**Comment by artieau** [comment]
Please raise a ticket in game with the details.
