### ISSUE TITLE
Cauldrons of major arcane and fire protection

### ISSUE THREAD

**Issue by Hustler495** [SunstriderEmu/BugTracker#3052]
I have question about the profession of alchemy, are there Cauldrons of major arcane and fire protection in the game now? made over 50 pots and did not receive a prescription on Cauldron. Can you tell when this will be added?

**Comment by artieau** [comment]
Not a TBC item.

**Comment by Denagul** [comment]
Arcane Cauldron: https://www.wowhead.com/item=32839/cauldron-of-major-arcane-protection
patch 2.1
Fire cauldron: https://www.wowhead.com/item=32849/cauldron-of-major-fire-protection
also patch 2.1

Not sure how it's "Not a TBC item."

**Comment by Jerrythemagicdog** [comment]
Thanks, live with next update.
