### ISSUE TITLE
Hello my player fell in lava in Ironforge at The Great Forge. As soon as i ressurect i die because i do not have enough health untill i cast hearthstone

### ISSUE THREAD

**Issue by Travest** [SunstriderEmu/BugTracker#3053]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by mayday2013** [comment]
Hello!

You can use unstuck option on website. Look for it in Services window.

You will be teleported to the nearest GY and ressurected.

**Comment by kelno** [comment]
Thanks for answering mayday!
