### ISSUE TITLE
SMV Akama quest chain Aldor Scryer allegiance change

### ISSUE THREAD

**Issue by Evilonion2** [SunstriderEmu/BugTracker#3055]
I changed my allegiance from Scryers to Aldor after completing the first two steps of the Akama quest chain: "Tablets of Baa'ri" and "Oronu the Elder". Now I can't restart or continue the quest chain for the Aldor.

**Comment by Jerrythemagicdog** [comment]
This probably requires a ticket to a Game Master to solve.
