### ISSUE TITLE
Reputation with Undercity in Western Plaguelands

### ISSUE THREAD

**Issue by Ministr564** [SunstriderEmu/BugTracker#3058]
I am on my way to exalted reputation with UC, now I do quests in West Plaguelands given by undead, which should give me reputation with undercity but they don't. For example among the other I completed quest called All Along The Watch Tower and it told me + 250 reputation with Horde but none reputation with UC was gain! Its just and example, but every quest there was bugged like this, before I noticed it I could have already lost around 1250 reputation with UC, because I think I already completed 5 or 6 quests there... Please I really need this issue to be solved, because I wont be able to finnish the exalted reputation with UC like this. Thank you
My character is called Cadaver EDIT: Now I also didnt get any reputation for quests in Eastern Plaguelands called "The Corpulent One" and "The Ranger Lord's Behest" I can send screenshots as a prove for this if you wanted to. I am now 6000 reputation from exalted but I wont be able to finnish it like this, and I already lost a lot of hours with it so please solve it and don't let it destroy the game for me :( Thank you

**Comment by z5n** [comment]
issue has since been fixed
