### ISSUE TITLE
COD Didn't give me items i paid for? 

### ISSUE THREAD

**Issue by thegreatestqb** [SunstriderEmu/BugTracker#3059]
Hello,

My characters name is Flebourne i purchased a COD in game mail of 32 Fel Armaments from Venommonst and i paid 384 total gold for the 32 Fel Armaments, however the gold was taken and i received no Fel Armaments? is this a bug ?? 

Need help!!

**Comment by artieau** [comment]
Please raise a ticket in game

**Comment by thegreatestqb** [comment]
> Please raise a ticket in game

I have just created the in game ticket!
