### ISSUE TITLE
The Cudgel of Kar'desh

### ISSUE THREAD

**Issue by iklop2209** [SunstriderEmu/BugTracker#3061]
cant complete https://www.wowhead.com/quest=10901/the-cudgel-of-kardesh
have all items
https://priscree.ru/img/4b9cd047d516a3.jpg
https://priscree.ru/img/4b9cde352431b8.jpg
https://priscree.ru/img/4b9cdab0851f42.jpg

**Comment by beraus** [comment]
Create a ticket and someone will help you.

**Comment by Simon-GM** [comment]
Please submit an in-game ticket.
