### ISSUE TITLE
Quests in Shadowglen

### ISSUE THREAD

**Issue by skinnycasp** [SunstriderEmu/BugTracker#3062]
Cant pass quests in Shadowglen .
1.Webwood venom
2.The Balance of Nature

**Comment by InhumanGM** [comment]
In order to replicate this issue, we need more information. Please follow the bug report template that way we can properly reproduce and investigate this issue.

> **Describe the bug**
> 
> **To Reproduce**
> 
> 1. Cast X on target affected by ...
> 
> Item: https://wowhead.com?item=
> Quest: https://wowhead.com?quest=
> Spell: https://wowhead.com?spell=
> 
> **Expected behavior**
> 
> **Screenshots/videos**
> 
> **Additional context**
