### ISSUE TITLE
Karazhan / Reputation reward.

### ISSUE THREAD

**Issue by leincz** [SunstriderEmu/BugTracker#3064]
I'm revered after going 2x times trough Karazhan, when i picked up the quest gave me the ring then after same again. Logged in next day the ring disappeared, i went to the NPC to check. The ring is wrong what he showed me at the quest and i can't pick it up without the other ring. (He want to give me spell ring but I'm a ret paladin and had the Path of the violent assasin one but its missing. Username : leincz

**Comment by kelno** [comment]
Fixed with next update.
(You need to be exalted to switch again though)
