### ISSUE TITLE
Disconnected 

### ISSUE THREAD

**Issue by Damene96** [SunstriderEmu/BugTracker#3067]
So , i'm getting disconnected from server like 3 or 4 times per hour ; while i'm in dungeons or bg or even just afk at shattrath ; and thats lead to whype my group or raid cause i'm healer ; so i tried to play in another server tbc to try if its my connection doing this but i didnt get disconnected at all in other servers and others extension like wotlk and BFA ; my internet connection is fine i tested it i pathpinged a lot of server i have no packet loss ; please help me to solve this problem its annoying and im not the only one having this issue 

    Thanks
Damene.

**Comment by Damene96** [comment]
So i re tested the packets with Pingplotter i pinged the server at 163.172.21.111 ( i think this is the IP for the endless server ) and i found that all good with my PC Router and my companie 

I played wow while pingplotter is running and when i crashed i saw that i had a packet loss i tried to locate where the packet loss i found that its starts losing at  149.14.125.9 ( Marseille ) then going until the server ip 
I will join a screen of the result 

So if this test is true please fix this issue cause we are a lot suffering from this Disconnections  
![20200421_101206](https://user-images.githubusercontent.com/64046090/79851227-eeb2b180-83bc-11ea-8262-5e003401d102.jpg)

**Comment by yikesdude25** [comment]
i get exact same problem , i think im even gonna take break from this game , if they dont fix it.its not kinda of little issue its big one , caus if you are doing your quest or leveling still ok but when it comes to raiding or arena its start realy beeing big ISSUE . PLEAS FIX THIS .

**Comment by piratebaylyf** [comment]
Same issue here, I tried to contact a gm ingame and he said "issue is not on our end", but this problem started after that last last update 3 days ago on the 18th.
Also people from Iran need a vpn to loggin now too I don't know if that problem is related to ours tho.

**Comment by InhumanGM** [comment]
Is anyone still having this issue?
