### ISSUE TITLE
Horde Trauma quest bugged

### ISSUE THREAD

**Issue by Tourmaline830** [SunstriderEmu/BugTracker#3068]
**Describe the bug**
There is no way to select Doctor Gregory Victor to complete the quest and start the next one in the chain.

**To Reproduce**
Hit First Aid 225. Talk to the First Aid trainer in Orgrimmar to receive the quest. Travel to Hammerfall and attempt to click on Doctor Gregory Victor.
2. 
3. 

Creature: https://classic.wowhead.com/npc=12920/doctor-gregory-victor
Quest: https://classic.wowhead.com/quest=6623/horde-trauma

**Expected behavior**
Victor should end the First Aid quest and grant the Triage quest. https://classic.wowhead.com/quest=6622/triage After that is done, he should offer more advanced First Aid recipes.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart!
