### ISSUE TITLE
Horde quest " The Fel and the Furious" does not working (buged) pls fix it :D 

### ISSUE THREAD

**Issue by darpi005** [SunstriderEmu/BugTracker#3069]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Thiazole** [comment]
Quest appears to be completed on quest log, but it can't be turned in at NPC.

**Comment by InhumanGM** [comment]
In order to replicate this issue, we need more information @darpi005. Please follow the bug report template that way we can properly reproduce and investigate this issue.

> **Describe the bug**
> 
> **To Reproduce**
> 
> 1. Cast X on target affected by ...
> 
> Item: https://wowhead.com?item=
> Quest: https://wowhead.com?quest=
> Spell: https://wowhead.com?spell=
> 
> **Expected behavior**
> 
> **Screenshots/videos**
> 
> **Additional context**
