### ISSUE TITLE
No queue priority for people who get randomly DC'd 

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3070]
when the server is running in maintenance / "low population mode"  if you get dc'd you could easily get a 30m queue on reconnect which is just ass if you are doing anything with anyone else (like a 5 man dungeon).  Should consider adding some sort of queue priority for people who were already connected or those already connected who are in groups/dungeons.

**Comment by kelno** [comment]
Thanks for the suggestion.
The maintenance are rare enough for now, if this becomes a more common issue we'll consider implement that kind of solution
