### ISSUE TITLE
lost all the mails that were waiting in my mailbox

### ISSUE THREAD

**Issue by SiN420** [SunstriderEmu/BugTracker#3073]
When i sell something on the auction house i receive a mail that confirm the transaction and let me know that the money will be avaible in the next 5 hours for example. When I come back to my mailbox that being said email disapeared. I happened 5-6 times recently. Thanks for letting me know what to do because im scared to sell something pricey.

1. Sell something on the AH
2. Receice email confirmation
3. email disapeared

I would like to this dont happend again

**Comment by SiN420** [comment]
Can someone help me ?

**Comment by InhumanGM** [comment]
What confirmation mail are you referring to? When selling an item, the only mail you should receive is the mail saying "[Auction successful](https://imgur.com/a/G9VBEo9)".
