### ISSUE TITLE
Clefthoof set bonus not working

### ISSUE THREAD

**Issue by Yellosvk** [SunstriderEmu/BugTracker#3079]
I am not getting the +20 strength bonus from the Clefthoof set.

There is a set of the 3 items:
Heavy Clefthoof Vest
Heavy Chelfthoof Leggings
Heavy Clefthoof Boots

It is expected that this set will give a set bonus +20 strength, which it currentl doesn't.

![image](https://user-images.githubusercontent.com/64085975/79874481-b628cd00-83e8-11ea-837d-909e53fee0a4.png)

Can you please have a look and fix it? Thank you.

**Comment by aidsi** [comment]
The set bonus requires 350 Leatherworking to function. It's working as intended since you don't have LW.

**Comment by Yellosvk** [comment]
ahaaa :) I haven not noticed that, thanks :)
