### ISSUE TITLE
Eye of Gruul trinket not working correctly

### ISSUE THREAD

**Issue by joemamaweet1234** [SunstriderEmu/BugTracker#3081]
**Describe the bug**
The Eye of Gruul trinket does not proc its Healing Trance effect from the casts of Lifebloom or Rejuvenation when it should. I tested by casting all druid heals many hundreds, even a thousand times, and it only procs from casting Healing Touch or Regrowth. The trinket should be able to proc from casting ANY healing spell (including Lifebloom or Rejuvenation). This makes a BiS druid trinket really bad. 

**To Reproduce**
1. Equip the trinket "Eye of Gruul"
2. Cast Lifebloom or Rejuvenation multiple times
3. No procs ever happen no matter how many times they are cast
4. Cast Regrowth or Healing Touch multiple times
5. Procs happen after casting them a decent amount of times

Item: https://tbc-twinhead.twinstar.cz/?item=28823

**Expected behavior**
Trinket should proc occasionally from any healing spell cast, including Lifebloom or Rejuvenation, like how it worked in retail TBC. 

**Additional context**
I believe the bug might be caused because Lifebloom and Rejuvenation do not cause a heal to instantly happen when they are initially cast, but instead the heal happens either after 1 second or after 3 seconds respectively. This may have confused the way you coded the trinket.

**Comment by ulekki** [comment]
You shouldn't even use this on a druid

**Comment by beraus** [comment]
Fixed in https://github.com/SunstriderEmu/BugTracker/issues/3468
