### ISSUE TITLE
GEETING DISCONNECTED alot of times in a day ( its realy frustrating )  .

### ISSUE THREAD

**Issue by yikesdude25** [SunstriderEmu/BugTracker#3082]
the problem is im geeting randomly dced from server like alot of time then when i try to connect it stuck on connecting then i sapm like 10 times close my world of warcraft window and try again , etc its happening alot of times , i just wanted to say that , the problem is not on my internet connexion caus when it happens its first this i check , and i tried other gamed and other world of warcfract expasion like BFA and legion even Cataclysm everything is ok OR EVEN if i log on on my old server ' warmane ' i dont have this problem , it come's to one conclusion problem is from you guys , your server , and i ask my fiend playing on this server from same region they get exact same problem , can you guys pleas work on this and fix it , caus when you level up or do quests ITS Ok ( not realy caus its and up on ALT F4 TBH )  , but when it come's to raiding or arena  its just unacceptable so pleas FIX THIS .
thanks for reading this and good luck guys .

**Comment by InhumanGM** [comment]
Are you still having this issue?

**Comment by yikesdude25** [comment]
Hi i just openned my mails sorry to answer now , no il done with this Booring dc's since like 10 days i would say .
Have nice one
________________________________
De : Inhuman <notifications@github.com>
Envoyé : jeudi 14 mai 2020 07:04
À : SunstriderEmu/BugTracker <BugTracker@noreply.github.com>
Cc : yikesdude25 <kore18@outlook.fr>; Author <author@noreply.github.com>
Objet : Re: [SunstriderEmu/BugTracker] GEETING DISCONNECTED alot of times in a day ( its realy frustrating ) . (#3082)


Are you still having this issue?
