### ISSUE TITLE
The Shrine of Dath'Remar Quest

### ISSUE THREAD

**Issue by notmrcer** [SunstriderEmu/BugTracker#3083]
**Describe the bug**
When you reach level two, The Shrine of Dath'Remar quest is unavailable without completing a chain quest.

**To Reproduce**
1. Reach level 2
2. Talk to Well Watcher Solanian
3. The only quest available is Solanian's Belongings from this NPC
4. Pick up Solanian's Belongings quest and complete it. 
5. Once you turn in Solanian's Belongings to Well Watcher Solanian, The Shrine of Dath'Remar becomes available.

NPC: Well Watcher Solanian(npc=15295) https://tbc-twinhead.twinstar.cz/?npc=15295
Quest: Solanian's Belongings(quest=8330) https://tbc-twinhead.twinstar.cz/?quest=8330
Quest: The Shrine of Dath'Remar(quest=8345) https://tbc-twinhead.twinstar.cz/?quest=8345

**Expected behavior**
Once you reach level 2, Solanian's Belongings and The Shrine of Dath'Remar should be available to pick up without doing any previous quests. 

**Screenshots/videos**
https://youtu.be/J3H_p7HfLAE
https://gyazo.com/b8596b90ffef0acb01d7e7dc61fb886b

[master-shrinebug addons.zip](https://github.com/SunstriderEmu/BugTracker/files/4511833/master-shrinebug.addons.zip)

**Additional context**
I discovered this while planning out my leveling route. Using a backported Zygor's leveling guide from 2008, that was when I noticed I couldn't pick up The Shrine of Dath'Remar without completing 
Solanian's Belongings. Please reach out to me on discord. MrCer#3375

I uploaded the backported zygor's guide for tbc as well as the addons needed to view it in-game.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
