### ISSUE TITLE
[Combat log] Reactive spells like execute & hammer of wrath

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#3084]
**Describe the bug**
When you have enabled blizzards floating combat text with reactive spells&abilities, targeting dead corpse sends combat log message that spell such as Hammer of Wrath or Execute is useable.

**To Reproduce**
1. Target dead mob/player
2. Combatlog still sends message that a spell like Execute is useable

**Expected behavior**
These messages are only supposed to appear when the target is alive, not when you are looting bunch of corpses

and no its not an addon issue, its fixable serverside

**Comment by kelno** [comment]
Thanks, probably fixed with next server update, but have to confirm that it works the same for every addon.
