### ISSUE TITLE
BM portals bugged

### ISSUE THREAD

**Issue by sharya** [SunstriderEmu/BugTracker#3086]
Third time I've run Black Morass and after a while the portals are all over the place. Doing the 4th portal, waiting for the 5th and suddenly the boss spawns as well or last boss fight starts at the same time with the 15th portal.  
![WoWScrnShot_042020_004535](https://user-images.githubusercontent.com/17204247/79922477-3f192600-8434-11ea-84f8-59b79aa0c95f.jpg)
![WoWScrnShot_041720_234003](https://user-images.githubusercontent.com/17204247/79922520-4809f780-8434-11ea-9015-724da18d4fd1.jpg)

**Comment by Simon-GM** [comment]
Issue causing double portals to spawn should be fixed now! 

Quote from changelog (Friday, 22 May 2020):
> Fixed Black Morass sometimes summoning two portals at the same time.
