### ISSUE TITLE
Initial application of dots triggering daze with aspect of the cheetah

### ISSUE THREAD

**Issue by bingbongx** [SunstriderEmu/BugTracker#3087]
**Describe the bug**
If a caster applies a dot to a hunter while they are in aspect of the cheetah the initial application triggers daze

**To Reproduce**
Put dots on a hunter with aspect of the cheetah

**Expected behavior**
Dots shouldn't procc the daze, only direct attacks

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in 0a36b7a59094ec7663e8fdc25a7f2ee5ba3744fb
