### ISSUE TITLE
Quest Corrupted Sabers bugged

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#3089]
**Describe the bug**
After you released the cat in the moonwell, it stayed in the moonwell and didn't follow you back to quest giver. Unable to turn in quest.

**To Reproduce**

1. Take quest and the kitten's cage.
2. Go to the moonwell, release the kitten.
3. Kitten turns into a corrupted kitten.
4. Kitten stays in the moonwell.

https://classic.wowhead.com/quest=4506/corrupted-sabers

**Expected behavior**
At step 4 above, kitten should follow the player.

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in [6743113c36500494f02f29cb6b069cedcbb73ac5](https://github.com/kelno/sunstrider-scripts/commit/6743113c36500494f02f29cb6b069cedcbb73ac5)

**Comment by Lamberdo** [comment]
when we come back with corrupted kitten we cant speek with npc/cat... so quest unable to turn in quest;/

**Comment by kelno** [comment]
Fixed with next update
