### ISSUE TITLE
Stealth won't work after duels

### ISSUE THREAD

**Issue by Navashed** [SunstriderEmu/BugTracker#3090]
After a duel ends, often Stealth becomes unusable. Starting another duel doesn't fix the issue. Vanishing is the only way to get back into stealth. This seems to happen when a duel ends while Stealth is on cooldown or you are in Stealth.

**To Reproduce**
1. Start a duel
2. Enter Stealth
3. Break Stealth (by attacking them, etc)
4. End the duel before Stealth comes off cooldown (/forfeit, /concede, etc)

Now you are stuck unable to Stealth.

**Comment by kelno** [comment]
Thanks for reporting!
Fixed with next server update
