### ISSUE TITLE
Ranged Weapon Damage 

### ISSUE THREAD

**Issue by Chogret** [SunstriderEmu/BugTracker#3091]
**Describe the bug**
Adamantite Sharpening Stone adds ranged weapon damage instead of just melee.

**To Reproduce**
1.Cast Adamantite Sharpening Stone to melee weapons.
2.Watch the ranged damage increase in the character stats tab.

Item: https://tbc-twinhead.twinstar.cz/?spell=29656

**Expected behavior**
Must only increase melee weapon damage.

**Screenshots/videos**

**Additional context**
There is 1 more sharpening stone that has the same bug.

**Comment by bjh368** [comment]
This has been discussed on many bug reports on tbc servers previously, and the conclusion after digging up old wowhead/elitistjerks comments is that the sharpening stones and weightstones are **both** increasing ranged dmg, and the weightstone also increases _ranged crit_, where the sharpening stone only increases _melee crit_.
