### ISSUE TITLE
Ressurrection quest paladin alliance bugued

### ISSUE THREAD

**Issue by Timbigot** [SunstriderEmu/BugTracker#3092]
Hello,

As said in the Title :) My paladin is Human 70 named Riful, and I have a bug with my Ressurrection quest : I started it low level, it asked me to go in the Stormwind Cathedral to speak to a guy for a book, which I did, and then he's supposed to send me give 10 Cloth to a woman in Stormwind, but he doesnt give me the quest.

Could anyone help me please ? 
Thanks, have a good day :)

**Comment by Simon-GM** [comment]
Please open an ingame ticket with this issue.
