### ISSUE TITLE
Seer's Ringmail blue resto pvp set for rep- set bonus is not working

### ISSUE THREAD

**Issue by Unhak** [SunstriderEmu/BugTracker#3093]
**Describe the bug**

Seer's Ringmail blue resto pvp set 4 piece set bonus supposed to cut **24 seconds** from the cool-down of **Nature's Swiftness spell**. Unfortunately, it is not working and also the skill description is not reflecting the 4 piece set bonus (**still says 3 min cd**). I believe this is very much critical for pvp resto shamans, please fix it!

Thank you
Unhak

**To Reproduce**

1. Put on 4 pieces of the Seer's Ringmail blue resto pvp set ( bought from Reputation Vendors)
2.  Check the spell description (not reflecting the set bonus)
3.  Use Nature's Swiftness and time the cool-down (will be 3 min **instead of 2.36**)

Item: https://70.wowfan.net/en/?itemset=747

Spell: https://tbc-twinhead.twinstar.cz/?spell=17116

**Expected behavior**
 cool-down will be 2.36 min **instead of 3**

**Screenshots/videos**
1) https://imgur.com/a/DImGNI4
2) https://imgur.com/a/elP5QQJ

Thank you !

**Comment by shaksh** [comment]
One of my resto friends also mentioned this issue. It's really weird

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
