### ISSUE TITLE
Runecloth in Outland

### ISSUE THREAD

**Issue by Macumbafeh** [SunstriderEmu/BugTracker#3095]
**Describe the bug**
It seems Orcs in Peninsula and maybe other Humanoid mobs don't drop Runecloth. I have leveled up 4 char here, and when i would skill up first aid on 1 char, i had no enough Runecloth O_o.
With my 4 chars, i did all the quests in Peninsula.

**To Reproduce**
Go in Hellfire Peninsula and kill lot of orcs, you will see they give not much Runecloth.

https://www.thegeekcrusade-serveur.com/db/?npc=16907

**Comment by Macumbafeh** [comment]
I win more Netherweave cloth than Runecloth : /

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3833
