### ISSUE TITLE
Blood Elf Racial 

### ISSUE THREAD

**Issue by conradwarnes** [SunstriderEmu/BugTracker#3096]
Blood Elf racial not giving back correct mana scaling for 70.

**Comment by Jerrythemagicdog** [comment]
Could you provide some sources showing that the amount is incorrect?

**Comment by Plxi66** [comment]
I dunno if it is right but from what i could find on the spell it should be. " (50 + level) "

Source: https://wow.gamepedia.com/Mana_Tap
