### ISSUE TITLE
Hunter Pet ability Cobra Reflexes doesn't correctly adjust tooltip damage

### ISSUE THREAD

**Issue by Shadowfury957** [SunstriderEmu/BugTracker#3098]
**Describe the bug**

Cobra Reflexes is an ability you can teach your hunter pet that is supposed to increase attack speed by 30% and also reduces damage. It does do this, however the way it adjusts the tooltip information is bugged and incorrect. It correctly increases the tooltip attack speed by 30%, however it doesn't reduce the damage like it should. This makes it so the tooltip dps shows wayyy higher than it should be.

**To Reproduce**

1.  Have hunter at least lv 30, for example lv 35. Learn Cobra Reflexes from the hunter pet trainer.
2.  Look at Hunter pet tooltip damage, attack speed, and dps before you teach your pet the ability with the Beast Training ability
3. Teach the pet Cobra Reflexes
4. Notice that the tooltip attack speed is in fact 30% faster, but the tooltip damage did not change, and the tooltip dps is wayy higher than it should be.

https://tbc-twinhead.twinstar.cz/?spell=25077

**Expected behavior**

Tooltip damage and tooltip dps for pet should be 30% lower. The actual damage the pet does is correctly affected.

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Same as every other tooltip then.
