### ISSUE TITLE
Uncatalogued Species

### ISSUE THREAD

**Issue by Kori-lk** [SunstriderEmu/BugTracker#3100]
**Describe the bug**
The Uncatalogued Species quest is unavailable to start, stating "You don't meet the requirements for this quest." 

**To Reproduce**

1. Attempt to accept Uncatalogued Species quest.

Item: https://wowhead.com?item=https://www.wowhead.com/item=24407/uncatalogued-species
Quest: https://wowhead.com?quest=https://www.wowhead.com/quest=9875/uncatalogued-species

**Expected behavior**
This should be applicable up until all the way to Exalted; not Revered; this has been the case since Patch 2.0.6, and continually so up until 2020's Patch 8.3.0.

**Screenshots/videos**
https://i.imgur.com/tK6tVUD.png

**Additional context**
WoWWiki's information is deprecated and continually unreliable in lieu of WoWPedia's release, and has continually been debunked across several servers (w/ the reputation bracket requirements for this time) - it states is needed; even during the original Patch 2.0.6 cycle on retail.

https://i.imgur.com/AFZZaRB.png
https://i.imgur.com/5ncUJ04.png
https://i.imgur.com/kaZW3B1.png

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1206#issuecomment-488339185
