### ISSUE TITLE
Unable to take Venom Bottles quest

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#3101]
**Describe the bug**
Quest should start after clicking on the object. Nothing happens when you click on the object. It only tells me "Greetings, [player]". Tried with both items at both troll bases and neither worked.

**To Reproduce**
1. Go to either location described in the link below. Click on the venom bottles.
2. It greets you.

https://classic.wowhead.com/quest=2933/venom-bottles

**Expected behavior**
At step 2 above, instead of greeting me, it should start the quest chain.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.
Even though it probably shouldn't be this way, all of the Venom Bottles will start the quest now.
