### ISSUE TITLE
Haris Pilton don't sell anything

### ISSUE THREAD

**Issue by Steinsgate00** [SunstriderEmu/BugTracker#3103]
Hello gentlemen ! All is in the title ! 
Haris Pilton is here, you can talk to her, open the shop menu, but her shop is empty, no stupidly expensive jewels or bags :'( 

![WoWScrnShot_042420_000337](https://user-images.githubusercontent.com/46298873/80154046-14a7a400-85bf-11ea-8ef2-21d012b69550.jpg)

**Comment by Jerrythemagicdog** [comment]
I see that the creature was moved to patch 2.2 and is no longer spawned on the live server currently.
