### ISSUE TITLE
Cant start Paladin redemption quest 

### ISSUE THREAD

**Issue by 32Stories** [SunstriderEmu/BugTracker#3106]
**Describe the bug**
I am a lvl 35 Paladin Draenei and I realized i never did the redemption quest line starting from Jol in the Exodar. Now when i go there I have no quest to except, I also tried to see if i could start from the human or dwarf zones but I cannot

**To Reproduce**

Quest: https://www.wowhead.com/quest=9600/redemption

**Expected behavior**
to start the quest line regardless of level 

**Screenshots/videos**
![Capture](https://user-images.githubusercontent.com/64234382/80160962-96cea300-8594-11ea-84b8-ed60a3c3d68a.PNG)
![Capture1](https://user-images.githubusercontent.com/64234382/80160967-9930fd00-8594-11ea-8e5f-5cc1fd57edb0.PNG)
![Capture2](https://user-images.githubusercontent.com/64234382/80160968-9a622a00-8594-11ea-9e97-098b49bee312.PNG)

**Additional context**
I have done the quest to learn sense undead, not sure if doing that first caused an issue

**Comment by Jerrythemagicdog** [comment]
Have you tried going back to Azure Watch to check if you've done all the Paladin quests there?
