### ISSUE TITLE
[Warlock] Enslave Demon pet bar breaks if you use mount.

### ISSUE THREAD

**Issue by hashblaster** [SunstriderEmu/BugTracker#3107]
**Describe the bug**

If you mount with a demon enslaved, it bugs out and you can't dismiss it or use the pet bar.

**Comment by Jerrythemagicdog** [comment]
Thanks!

Steps:
enslave a demon,
mount up,
the cast bar is greyed out permanently after that.

**Comment by Jerrythemagicdog** [comment]
Still an issue.

**Comment by hufsa** [comment]
Thanks, fixed with next update.
