### ISSUE TITLE
Paladin judgement of justice wrongly removed by PvP trinket

### ISSUE THREAD

**Issue by palapala-pala** [SunstriderEmu/BugTracker#3108]
**Describe the bug**
As described in the title, when you judgement of justice a target as Paladin, their PvP trinket removes the effect which is not working as intended as the judgement indeed does not allow your movement speed increases to work, but is not a speed reduction or a spell that prevents you to control your char

**To Reproduce**

1. Cast Judgement of justice on a target 
2. Use PvP trinket with the affected target 

**Expected behavior**
The judgement of justice shall not be removed upon PvP trinket usage.

**Screenshots/videos**
https://www.youtube.com/watch?v=ZgZ2mKca-Mk at 8:23 you can see the druid trinketing while the JoJ remains. 

**Additional context**

**Comment by Rettiy** [comment]
https://wowwiki.fandom.com/wiki/Patch_2.3.0

_"PvP Trinkets: [Insignia of the Alliance], [Insignia of the Horde], [Medallion of the Alliance], and [Medallion of the Horde] now clear the debuff from Judgment of Justice."_

**Comment by palapala-pala** [comment]
> https://wowwiki.fandom.com/wiki/Patch_2.3.0
> 
> _"PvP Trinkets: [Insignia of the Alliance], [Insignia of the Horde], [Medallion of the Alliance], and [Medallion of the Horde] now clear the debuff from Judgment of Justice."_

:(

**Comment by Jerrythemagicdog** [comment]
Thanks for the source!
