### ISSUE TITLE
Unlimited Veins Spawns + Mana Thistle Respawn destroys the Market

### ISSUE THREAD

**Issue by myeox123** [SunstriderEmu/BugTracker#3109]
**Describe the bug**
Hey there are bugged Adamantite Veins at "The Barrier Hills" directly above Shattrath an "which respawn all 10 - 50 seconds non stopp 24/7.
There are several normal Players which gather Ore 24/7.
Would be nice if you could fix this Problem.
Ore and Gems are dropping 50% and even lower as npc Price.
Same but not so "instant" respawn on the same place with the "Manathistle".

**To Reproduce**

1. Go to the Barrier Hills
2. Look for the Veins at the middle Tower oder near the House nearest to Shatt
3. See ppl gathering and mining non stopp

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**
https://imgur.com/a/34RBOue

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed a few days ago.
