### ISSUE TITLE
Hunter pet abilties on Autocast doesn't autocast.

### ISSUE THREAD

**Issue by Shmilowitz** [SunstriderEmu/BugTracker#3110]
**Describe the bug**
While having hunter pet abilties on autocast, the pet doesn't autocast the ability. Have to macro the pet ability or click on the actual pet ability. 

**To Reproduce**

This bug appeared out of nowhere. I have asked guildies and it seems like only 2/4 hunters are affected by this. 

**Expected behavior**
Pet ability should autocast while right-clicked. It is "glowing" in the bar.

**Additional context**
I tried everything I could think of:
Stable pet and take it out.
Use other pet.
Disable all addons.
Relog.
Restart client.
Toggle autocast on and off.
Relearn ability by resetting pet talents

**Comment by DwarvenJoe** [comment]
I've noticed this happening off and on aswell most times it seems to be linked to training your pet with a new level of a certain skill it seems to go away if you dismiss and recall your pet after training for me, but I'm not certain if that will solve it for everyone, try it though and let us know.

**Comment by Shmilowitz** [comment]
Thanks for your reply. 
That doesn't fix it for me. My pet doesn't auto-cast it's abilties.
Additional info: I am using a wind serpent with max ranked Lightning Breath. It has Dive and Growl as well, but not toggled to auto-cast.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in bf9e5b920248e526fe38eb367661c46d25599dbc
