### ISSUE TITLE
Skullflame Shield does not scale

### ISSUE THREAD

**Issue by mafista** [SunstriderEmu/BugTracker#3112]
**Describe the bug**
Lifesteal (and flamestrike) procc on Skullflame Shield does not scale with spellpower.

**To Reproduce**
Fight any mob with spellpower gear and skullflame shield equiped

Item: https://shadowlands.wowhead.com/item=1168/skullflame-shield

**Expected behavior**
Several comments state that during tbc skullflame shield proccs scaled 1:1 with spellpower, including data from Recount addon.

**Screenshots/videos**
Here is screenshot of my testing.
https://imgur.com/KQqWega

**Comment by Jerrythemagicdog** [comment]
Thanks, scaling was intentionally removed.
