### ISSUE TITLE
Honourable Kills At Halaa Not Rewarding Halaa Battle Tokens

### ISSUE THREAD

**Issue by Philcollinsx** [SunstriderEmu/BugTracker#3113]
Upon getting an Honourable Kill in or around Halaa in Nagrand, you should be awarded with 1x Halaa Battle Token. 

These are not being awarded. I have tried this inside Halaa, and outside. I have also checked if this works while Guards inside Halaa are alive, or not. Neither provides a Halaa Battle Token.

**Comment by Jerrythemagicdog** [comment]
Which faction are you on? Was Halaa controlled at that moment?
I've tried to reproduce locally with both Alliance and Horde characters and in both cases I've received the token.

**Comment by Philcollinsx** [comment]
I was Horde, Halaa was controlled by the Alliance, didnt get a token.

I was mid capturing Halaa while standing at the flag, didnt get token.

When Horde controlled it, I killed two players at the Wyvern / Griffyn
camps at the edges, no token.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by z5n** [comment]
unable to reproduce
