### ISSUE TITLE
Warrior damage is higher than it should be in pvp

### ISSUE THREAD

**Issue by lastnoob** [SunstriderEmu/BugTracker#3115]
**Describe the bug**
Warrior damage is just out of control. It's s1 and they hit like a truck. Brooxz hit a 3000+ Mortal Strike on stream (in arena), without any sunders or armor decrease on the target, and he didn't even have BIS gear.

**To Reproduce**

1. Watch a warrior annihilate someone during a single mace stun from 90% hp.
2. See step 1.

**Expected behavior**

In s1 warrior damage should be lower.

**Additional context**

 We are talking about the most gear dependent class in the game. The reason why they are not that rampant at the very top of the ladder is that there are so many mage rogue teams and such. Also, the very top teams are so good that it doesn't matter if the warriors damage is out of control, as it will be CCed 24/7. This doesn't mean that the game should be balanced around the top 10 arena teams.

**Comment by Jerrythemagicdog** [comment]
Please provide numbers to back up your claims, thanks.

**Comment by lastnoob** [comment]
What should I do exactly? Just talk to any high level pvp player about it. If I provide screenshots, you will just say it works as intended as I have no proof from retail TBC, from a same geared and same skilled player. 

Here you go, a screenshot of a warrior dealing 5332 damage (not even bis geared btw) in 1 second (see timestamps in combat log), into 300 resilience and barkskin. This is definitely not normal.

![github](https://user-images.githubusercontent.com/1821091/80540075-88232a00-89a0-11ea-9c07-cb7f0c2a2717.jpg)

**Comment by networm555** [comment]
You wont prove anything here. They are deluded idiots. fel lotus price on ah tells everything about this server.

**Comment by avclol** [comment]
Indeed they are making x3 more damage than Normal I have 380 resi with my priest I took 3k x3 last game we cant pvp anymore. and also I want to talk about WF shaman its infinite  it procs x5 more than it should. I've been playing BC since 2010 everywhere i've never experienced such bugged warrior.

**Comment by lastnoob** [comment]
Here's a retail video from season 4 (so s3+ geared warrior with at least s4 offparts) doing less damage with death wish up than warriors on endless without death wish.
https://www.warcraftmovies.com/movieview.php?id=81505

**Comment by babushkah** [comment]
Can confirm. 

300 resilience restodruid, got critted for 2000 with a casual melee swing. No sunders or anything. This rarely should happen even in s4 BIS


![image](https://user-images.githubusercontent.com/64655307/80823678-f94b2300-8bd4-11ea-8a73-8c786aace987.png)

**Comment by lastnoob** [comment]
@Jerrythemagicdog 

what else do you need?

**Comment by lastnoob** [comment]
hello?

**Comment by bugmaster01** [comment]
i dont see any issue of warriors demage as of now. my self playing PVP 2031 rating currently. 
didnt ever get so much demage to question it.

**Comment by lastnoob** [comment]
@bugmaster01 found the warrior player. Seriously stop trolling. There's no way this damage is normal in s1 when warriors on ALL other servers (yes every single server including retail) do the same amount or even less in s3-s4. Look at the videos linked, both from retail TBC and warmane. 

![warrlol](https://user-images.githubusercontent.com/1821091/81514562-bbae6e80-9327-11ea-89de-03070ab453a2.jpg)
3.5k crit into 300 resilience

**Comment by avclol** [comment]
people who say that warrior are not broken are just  PVE Retards, the damage are insane and killing the pvp in the server. also mage damage should be fixed as soon as possible we can't stay like that, action should be taken the pvp isn't balanced any more please admins take a moment and check all classes. Its fondamental !

**Comment by lastnoob** [comment]
@avclol At this point I'm pretty sure they don't care about it or deny that there's anything wrong with it. They just included 2 scenes of high rated, high resilience people getting literally globaled in their "top moments of the month" movie, like its the epitome of pvp skill and the best showcase of the server.

**Comment by lastnoob** [comment]
RIP

**Comment by Jerrythemagicdog** [comment]
This is completely invalid and off the rails, closing. I suggest everyone here takes some time to read tooltips.
