### ISSUE TITLE
Rogue Poison BUG QUEST(HELP PLEASE) 

### ISSUE THREAD

**Issue by dufino92** [SunstriderEmu/BugTracker#3116]
**Describe the bug**
Hello,
I tried yesterday to do quest for a rogue's poison. I did as researched on wowhead. Fired out flare, got another quest, killed few mobs, stole a key a killed an elite. There is a part when you suppose to open a chest with the key you previously used Pick Pocket on. BUT When I got my Sizzling key, , tried repeatedly to open the chest. Never worked. Always wrote Failed attempt. So I did thought to myself. Probably some mess up on the way, I should RE DO the quest line. glitch. So I abandoned the Quest and went to NPC to take it again, QUEST IS GONE. Now I am Rogue without a poison spell. PLEASE HELP ME 

**To Reproduce**
1. Pick pocked key from https://classic.wowhead.com/npc=7287/foreman-silixiz
2. Could't open the chest for https://classic.wowhead.com/item=8073/cache-of-zanzils-altered-mixture

Item: https://classic.wowhead.com/item=8073/cache-of-zanzils-altered-mixture
Quest: https://classic.wowhead.com/guides/rogue-class-quests-classic-wow

**Expected behavior**
To open the chest and loot it.

**Screenshots/videos**
https://prnt.sc/s5q598
https://prnt.sc/s5q5if
https://prnt.sc/s5q5ow

**Additional context**

Thank you very much for your time.
Kind Regards

In game name: Ondrej

**Comment by Jerrythemagicdog** [comment]
Resolved in game.
