### ISSUE TITLE
Swoop and Wiry Swoop in Mulgore running animation is broken

### ISSUE THREAD

**Issue by toinetoine** [SunstriderEmu/BugTracker#3117]
**Describe the bug**
The running animation of the Swoop and Wiry Swoop in Mulgore is broken

**To Reproduce**
Engage in combat with them 

Swoop and Wiry Swoop

[Youtube Recording](https://youtu.be/OZ_wtWZ3G7I)

**Comment by Jerrythemagicdog** [comment]
Thanks for the video, fixed with next update!
