### ISSUE TITLE
I can't take my gold in the mailbox that I receive from AH.

### ISSUE THREAD

**Issue by Krmacha** [SunstriderEmu/BugTracker#3118]
![WoWScrnShot_042420_230137](https://user-images.githubusercontent.com/64297655/80270975-58afad00-8682-11ea-8e52-f72f6fe3d980.jpg)

I wrote so many tickets, but GM's don't give me any specific answer why is this happening. I already lost so much gold, by not being able to pick it up from the mailbox, and after few hours, mail just disappear.

**Comment by Krmacha** [comment]
I wrote so many tickets, but y'all don't give me any specific answer why is this happening. I already lost so much gold, by not being able to pick it up from the mailbox, and after few hours, mail just disappear.

**Comment by Jerrythemagicdog** [comment]
Does the issue still persist after logging in and out of the account?

**Comment by BarmyDwarf** [comment]
It says sale pending.  Not sale successful.

**Comment by Straums** [comment]
Having same problems, losing a lot of gold on this and it is making AH sales a hit or miss.

**Comment by Godmatik** [comment]
close client and re-open

**Comment by Straums** [comment]
client has been closed and reopened on several occasions and this problem persists.

**Comment by Straums** [comment]
Currently 8 auctions are pending. Some from yesterday.

**Comment by Godmatik** [comment]
open GM ticket only they can help you for now
