### ISSUE TITLE
SSC Release.

### ISSUE THREAD

**Issue by mchayes** [SunstriderEmu/BugTracker#3119]
Are we really gonna be the tbc version of icecrown warmane? God this is gonna be nothing but skip/abuse trash. Seems like a great idea to inform about this ridiculous buff to "new" content. 

Only PTR-testers know this and got rid of all their melee dps as you could see on their streams.

GJ.

edit; I guess we're only using bear tanks for meat shield :-)

![image](https://user-images.githubusercontent.com/20542656/80276190-38660980-86e7-11ea-8beb-b73b3d776025.png)

**Comment by bjh368** [comment]
Imagine thinking trash difficulty is the reason to not bring melee :^)

**Comment by NeonicSupersonic** [comment]
Welcome to TBC. You ALWAYS disadvantaged by having melee comps in any pre-SWP tier, which is common knowledge. Have fun.
