### ISSUE TITLE
[SSC]  The Lurker Below - spawns

### ISSUE THREAD

**Issue by darknessangelo** [SunstriderEmu/BugTracker#3120]
**Describe the bug**
Keeping spawned nagas in CC prevent them to spawn again. Makes fight significantly easier.

**Expected behavior**
_"Each time the Lurker submerges, he spawns a total of nine adds: two ranged Coilfang Ambushers on each outer platform, and three melee Coilfang Guardians on the inner ring. All these adds can be Crowd Controlled."_
**source:** https://wowwiki.fandom.com/wiki/The_Lurker_Below

**Screenshots/videos**
**Nihilum VS The Lurker Below:** https://www.youtube.com/watch?v=eZJNTmHA7Cg

**Comment by mchayes** [comment]
**a total**

^
capping out at .. etc

**Comment by Jerrythemagicdog** [comment]
Yes, the Lurker despawns the adds and resummons new ones requiring them to be CCed again. This was an intentional change on our part. Thanks for the sources.
