### ISSUE TITLE
Spell hit bug

### ISSUE THREAD

**Issue by Sh1k999** [SunstriderEmu/BugTracker#3121]
Spells have 100% hit nad never resist in PvE

**Comment by ghostart** [comment]
Yep, this one really take place.

**Comment by Jerrythemagicdog** [comment]
If your character is hit capped your spells will never miss, we have removed the innate 1% resist chance - https://endless.gg/changes.

**Comment by Sh1k999** [comment]
My character is not hit capped. I just haven't seen a signgle miss from 1 to 70 lvl and in dungeons as well. Just check it
