### ISSUE TITLE
Missing Spell after reset

### ISSUE THREAD

**Issue by artharhys** [SunstriderEmu/BugTracker#3122]
My "Teleport: Moonglade" spell is not showing up after reset.

Character name: Aoruhn (Tauren Druid)

I found this list (https://tbcdb.com/?spells=7.11) with the spell "Teleport: Moonglade"(https://tbcdb.com/?spell=18960) learnt at level 10 (https://imgur.com/a/ctykmIp).

**Comment by Jerrythemagicdog** [comment]
Please reach out to a member of Support on Discord the next time you're online in game and open a ticket in game.
