### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by Soutie001** [SunstriderEmu/BugTracker#3125]
Good Day
Please assist as i cant login into the endless server with my login details, keeps telling me to authenticating, i can lgoin on the warmane server but not the endless one.

gavinsmith53@gmail.com 

**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Please reach out to a member of the Staff on Discord.

**Comment by Soutie001** [comment]
i didn't authorized anything
