### ISSUE TITLE
Goblin Jumper Cables XL never work

### ISSUE THREAD

**Issue by DwarvenJoe** [SunstriderEmu/BugTracker#3126]
Goblin Jumper Cables XL never ever work, I had the lower level ones that seemed to function occasionally so I "upgraded" to the XL ones wich from my research should have somewhere around 75% success rate, I have attempted to use these probably a 100times over the course of a month or so and they have never worked not even once so something is not right with these even if you imagine me being the unluckiest player on the server this shouldnt be possible.

**Comment by Malozar** [comment]
Are you using it on players before they have released? Because im pretty sure the chances are extremely low, if not impossible, once the target has already released.

**Comment by Jerrythemagicdog** [comment]
The previous chance was 50%, I've updated it to 75% chance. Wasn't able to reproduce the case where a player who already released spirit wasn't able to receive the ressurection - it worked in both cases. 
Please get back to us in this issue after the next update.

**Comment by DwarvenJoe** [comment]
> The previous chance was 50%, I've updated it to 75% chance. Wasn't able to reproduce the case where a player who already released spirit wasn't able to receive the ressurection - it worked in both cases.
> Please get back to us in this issue after the next update.

I dont know what you did but they function perfectly now, thumbs up!

As for the previous comment I've of course tried on players that have and havent released both.

I should have reported this sooner I guess better late than never.
