### ISSUE TITLE
Loot Roll Bug

### ISSUE THREAD

**Issue by Kedaa1904** [SunstriderEmu/BugTracker#3127]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Kedaa1904** [comment]
We killed the last Boss in Slave Pens Heroic and a Plate Belt dropped. Everybody rolled greed for it and i rolled need. The Leader kicked me out of GRP and a Player with a Greed Roll get the Item. Thats must be bug, cause i rolled need and should get the item. What can i do now?

**Comment by Kedaa1904** [comment]
https://www.wowhead.com/item=27672/girdle-of-the-immovable&bonus=4105   is was the Belt

**Comment by Jerrythemagicdog** [comment]
Please reach out to a member of Staff on Discord.
