### ISSUE TITLE
Combat Log Entries Disappear for Shaman

### ISSUE THREAD

**Issue by Myhx77** [SunstriderEmu/BugTracker#3128]
**Describe the bug**
When putting on rockbiter as a draenei shaman (or any other weapon enhancement) the combat lot stops working, and in turn so do custom mods for scrolling battle text.  The only way to get it to work again is to relog.  Reloading the UI does not work.

**To Reproduce**

1. Put rockbiter weapon on
2. Attack something
3. Look at combat log - empty

Spell: https://wowhead.com?spell=159974/rockbiter-weapon

**Expected behavior**
Combat text shouldn't disappear when rockbiter or other weapon enhancements are applied.

**Comment by Jerrythemagicdog** [comment]
Thanks, are you using any combat log clearing addons or macros?

**Comment by Myhx77** [comment]
Thanks for the reply.  I do have Mik's Scrolling Battle Text, but from what I understood that reads from the combat log.  I will try disabling all of my other addons and see if it still does the same thing.

**Comment by Myhx77** [comment]
Update - I disabled all addons including Mik's and still noticed that when i first log in (even with a weapon enhancement applied) if I attack something the combat log still produces messages.  But as soon as I add rockbiter weapon or any other weapon enhancement that i've tested for Shaman, the combat log stops generating messages other than experience gained.

Also, just as an FYI, the default scrolling text still shows, but the combat log is empty.

**Comment by Jerrythemagicdog** [comment]
Try using https://github.com/Schaka/CombatLogFix
Click on "Clone or download", move the unzipped file to WoWfolder/Interface/Addons and remove the "-master" suffix. 
Let us know if anything changes.

**Comment by Myhx77** [comment]
Thanks!  Interesting results: The combat log still breaks, but only for the very initial thing I do after applying the weapon enhancement (I noticed it on my druid too, I think it was from Gift of the Wild oddly enough).  Once I do an action that generates something in the combat log, the log fixer reports "4 filtered/6 events found.  Cleared combat log, as it broke.  Please report this!".  After that though it starts working just fine again, it's always just the initial action after applying the buff.
