### ISSUE TITLE
Ferelas: Against Lord Shalzaru Quest --- NPC Respawn Timer Issue

### ISSUE THREAD

**Issue by BarmyDwarf** [SunstriderEmu/BugTracker#3130]
Bug Description:
Respawn timer for npc's listed below is too quick, making it too difficult to progress and complete the quest.  The current respawn rate is approximately 30 seconds give or take.  Which is too soon considering some of them are in close proximity to one another and fights can last forever because they respawn before you can kill the whole group.

To Reproduce:
1. Kill any of the Hatecrest Naga's.

NPC's Affected:
1. https://classic.wowhead.com/npc=5334/hatecrest-myrmidon
2. https://classic.wowhead.com/npc=5331/hatecrest-warrior
3. https://classic.wowhead.com/npc=5335/hatecrest-screamer
4. https://classic.wowhead.com/npc=5336/hatecrest-sorceress

Region: Ferelas
Sub Region: Isle of Dread
Quest: https://classic.wowhead.com/quest=2870/against-lord-shalzaru

**Comment by Sheikthecatman** [comment]
The respawn timer is 5 minutes, shortened by dynamic respawn timer.

**Comment by BarmyDwarf** [comment]
> The respawn timer is 5 minutes, shortened by dynamic respawn timer.

Not sure I understand the purpose of the dynamic respawn timer.  It's making it impossible for me to complete the quest because the npc's respawn before I can finish killing the next enemy.
