### ISSUE TITLE
Scarlet Monastery Mob Pathing

### ISSUE THREAD

**Issue by Chuubers** [SunstriderEmu/BugTracker#3131]
**Describe the bug**
All of mobs in Scarlet Monastery (Graveyard, Library, Armory and Cathedral) ignore the correct pathing for the ledges throughout the dungeon. Instead of going around them, they will walk straight over them. Also, in Cathedral, they will drop jump off the waterfall instead of going to the stairs. 

**To Reproduce**
Pull any mob in Scarlet Monastery and walk around the pillars in any of the courtyards. Mobs will run over the ledges.

https://classic.wowhead.com/scarlet-monastery#npcs

**Expected behavior**
Mobs should abide by Line of Sight and pathing that NPCs should take to reach their target. ie. Go around a ledge to make it to the target. Instead of flying through the air straight through a pillar.

**Screenshots/videos**
This is how mobs pathing SHOULD work:
https://www.youtube.com/watch?v=QoeXrFJq4ug&t=1525s

This is how it currently works on Endless:
**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed some time ago!
