### ISSUE TITLE
Ravager counts as debuff and don't proc of itself

### ISSUE THREAD

**Issue by TheMoneyHater** [SunstriderEmu/BugTracker#3132]
**Describe the bug**
The Bladestorm effect given by the weapon "Ravager" counts as a debuff for some reason and can't proc of itself.

**To Reproduce**
Equip Ravager
Auto attack

1:
https://www.youtube.com/watch?v=b8P9b23SWJ8&feature=youtu.be&t=114
2:
https://classic.wowhead.com/item=7717/ravager#comments
51 upvotes "I believe you can click off the "buff" and make it stop."
3:
https://wowwiki.fandom.com/wiki/Ravager_(axe)?oldid=1616094
"The liablity can be countered by immediately canceling the Bladestorm buff."
"This is a great weapon for runthroughs. Warriors — just pull as much as you feel comfortable with, then let it proc away."

**Expected behavior**
It's suppose to be a buff and can proc infinite on itself.

**Comment by Jerrythemagicdog** [comment]
It can proc off itself, we corrected the spell's positivity. Thanks for the issue!
Fixed with next update.
