### ISSUE TITLE
[Quest] 'Cleansing the eye' cannot be completed

### ISSUE THREAD

**Issue by eviktve** [SunstriderEmu/BugTracker#3135]
**Describe the bug**
'Cleansing the eye' quest cannot be turned in at NPC Archbishop Benedictus.

**To Reproduce**
Previously i moved quest item 'Cursed Eye of Paleth' to my bank for some time. Now it is in my backpack, but the ? is still gray above the Q NPC.

Item: https://wowhead.com?item=2944/cursed-eye-of-paleth
Quest: https://wowhead.com?quest=293/cleansing-the-eye

**Expected behavior**
Archbishop Benedictus should accept Cursed Eye of Paleth from my inventory.

**Screenshots/videos**

**Additional context**
Character: Justicia

**Comment by beraus** [comment]
This issue should be resolved after server reset.
