### ISSUE TITLE
Warlock pet doesn't respawn with full health in battlegrounds

### ISSUE THREAD

**Issue by endlesswarlock** [SunstriderEmu/BugTracker#3137]
If you die in a battleground and your pet was damaged prior to dying, the pet will not spawn with full hp and mana like the correct behaviour in all versions of wow.

To reproduce, die in a battleground with your pet damaged.

All warlock pets are affected.

Expected behaviour is for the warlock pet to be ressurected by the bg healer with full hp and mana.

**Comment by hufsa** [comment]
Thanks! Fixed with next update.
