### ISSUE TITLE
Warlock pet does not persist when taking a portal

### ISSUE THREAD

**Issue by endlesswarlock** [SunstriderEmu/BugTracker#3138]
**Describe the bug**
Warlock pets do not persist when taking portals to cities and battleground queues, like they should do.

**To Reproduce**
To reproduce simply take a portal or battleground queue.

All warlock pets are affected.

**Expected behavior**
In all versions of wow, warlock pets persist through portals and battleground queues.

**Comment by Jerrythemagicdog** [comment]
To dev: only happens if you teleport within the same MapID (e.g. Thrallmar -> Cenarion Refuge, but if you teleport from Thrallmar to Orgrimmar the pet is correctly resummoned).

**Comment by kelno** [comment]
Probably fixed now with https://github.com/kelno/sunstrider/commit/b5011ebb833dae281bf86def010c27957f36c58c

**Comment by Jerrythemagicdog** [comment]
Fixed with kelno/sunstrider@b5011eb
