### ISSUE TITLE
Hit rating problem Shaman

### ISSUE THREAD

**Issue by maylersaid** [SunstriderEmu/BugTracker#3142]
**Describe the bug**

Hit Rating from Shaman Tree or Totem of Wrath does not increses any bonus % in Spell Status. (C)

**To Reproduce**

1. Equipe a item with Spell hit ( FlameHandler's gloves)
2. My hit rating on spell status increases to 16 and 1,71% to hit mobs 64.
3. Put my last point in Nature's Guidance (Chance to hit in 3% 3/3)
4. Does not increases with the step 2.
5.  I tested with my Totem of Wrath (3% hit) and foes not increases with the step 2.

Item: https://tbc-twinhead.twinstar.cz/?item=25503
Spell: https://tbc-twinhead.twinstar.cz/?spell=30706
Spell: https://tbc-twinhead.twinstar.cz/?spell=16198

**Expected behavior**

increases the hit rating from these spells.

**Screenshots/videos**

No TOTEM
![image](https://user-images.githubusercontent.com/54895599/80312274-adeeda00-87ba-11ea-9ec1-a01b7f5d5481.png)

WITH TOTEM
![image](https://user-images.githubusercontent.com/54895599/80312303-e4c4f000-87ba-11ea-89f2-ee4c280b420e.png)

The Critical chance works with totem, but hit rating no.

**Comment by TheMoneyHater** [comment]
It works, it just don't update the window since it gives 3% hit chance and not hit rating like many other spells in the game.
