### ISSUE TITLE
Marshal Kodohide Boots

### ISSUE THREAD

**Issue by Dannyjoon23** [SunstriderEmu/BugTracker#3144]
The Marshal Kodohide Boots are bugged. It shows i need 16,065 Honor and 30 AV marks. I have 17,300 honor and 30 AV marks and it says "You do not have the required items for that purchase". Many druids have reported the same thing to me. 

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://tbc-twinhead.twinstar.cz/?item=31597
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment]
This should be fixed now.
