### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Moregath** [SunstriderEmu/BugTracker#3145]

**Comment by Godmatik** [comment]
the dailies aren't out yet

**Comment by Moregath** [comment]
then how do ppl have the +40 Sp enchant already

**Comment by Lysychooj** [comment]
Before patch 2.1 the formula dropped from Razaani Spell-Thief (level 67-68 mobs), found in Blade's Edge Mountains (around 66,44 area)

**Comment by Moregath** [comment]
They are not there see pics
