### ISSUE TITLE
Corki missing home

### ISSUE THREAD

**Issue by amacleod979** [SunstriderEmu/BugTracker#3146]
The quest giver of the HELP! quest in Nagrand, Corki, is currently bugged. He is no longer in his cage, but instead in the center of the road nearby. What seems to have happened is after another alliance player released him from his cage a Horde player attacked Corki and dragged him away from his normal location, instead of resetting in his cage he is now a statue unable to be interacted with.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
