### ISSUE TITLE
Xiri's gift trinket bugged.

### ISSUE THREAD

**Issue by cazzro** [SunstriderEmu/BugTracker#3147]
**Describe the bug**

When i use the trinket, the effect doesnt work. My hands light up blue and a casting noise will keep going until i relog.
**To Reproduce**

1. Cast X on target affected by ... Buy trinket from Sha'tar quartermaster 
2. Use trinket
3. Its v strange other people with it dont have it

Item: https://wowhead.com?item=https://www.wowhead.com/item=29179/xiris-gift
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

Trinket to work
**Screenshots/videos**

**Additional context**

**Comment by knoxz** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2087
