### ISSUE TITLE
Warlock Felhunter able to learn Felguard Ability

### ISSUE THREAD

**Issue by Greatham871** [SunstriderEmu/BugTracker#3155]
Whilst learning all warlock pets i bought all the Grimoire's at 70, without looking i summoned each pet and learnt the Grimoire's.

I didn't notice but you can actually use Grimoire of Anguish (Rank 3) (https://www.wowhead.com/item=28073/grimoire-of-anguish-rank-3) on your Felhunter, as a result i cannot teach it Spell Lock as it currently has learnt 'too many skills'.

Summon a Felhunter with 1 spare ability - I think 4 spells is max (?) 
1.  Teach your Felhunter 3 of the 4 abilities it should be able to learn; Grimoire of Devour Magic / Tainted Blood / Paranoia
2Use the Grimoire of Anguish (Rank 3)
3. Felhunter learns the Felguard ability
4.  Attempt to use Grimoire of Spell Lock

Affected Pet: Felhunter
Item: Grimoire of Anguish (Rank 3)
Spell: (https://www.wowhead.com/item=28073/grimoire-of-anguish-rank-3) 

Felhunter should not be able to learn Felguard spell 'Anguish'

**Comment by Simon-GM** [comment]
I have not been able to reproduce this. 
Could you take a few pictures enlightening the situation?

**Comment by Greatham871** [comment]
Hi Simon,

See attached screenshots.
![WarlockBug](https://user-images.githubusercontent.com/64416125/80683622-6ae37e00-8abc-11ea-8a98-1ed64583ad8f.jpg)

**Comment by z5n** [comment]
unable to reproduce
