### ISSUE TITLE
No increase in defence skill

### ISSUE THREAD

**Issue by krist748r** [SunstriderEmu/BugTracker#3156]
**Describe the bug**
My draenei Paladin _Sealandheal_ wont get increased defence skill in combat. Im stuck at 337 defence skill point at level 70.

**Additional context**
Ive been in contact with _Game Master Bareus_ ingame by the mailsystem and Help Request.

**Comment by kelno** [comment]
Thanks for reporting!
It's just very slow near the end and the rule is the same for everyone. If you believe the increase chance formula is wrong this is another issue and you can open a ticket about it with more info
