### ISSUE TITLE
"Eyes of The Beast Hunter" Ability Kicks you from the server

### ISSUE THREAD

**Issue by BarmyDwarf** [SunstriderEmu/BugTracker#3157]
"Eyes of The Beast Hunter" Ability Kicks you from the server

**To Reproduce**
Cast Eyes of The Beast and run around.

Spell: https://classic.wowhead.com/spell=1002/eyes-of-the-beast

**Comment by Rockbiter-shaman** [comment]
I just tested this, it's true. You disconnect shortly after casting

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3173
