### ISSUE TITLE
Disconnects from the game when mind control gets interrupted in arena match.

### ISSUE THREAD

**Issue by guesswho654089** [SunstriderEmu/BugTracker#3158]
As a discipline priest when I use mind control in arena games and it gets interrupted (sometimes it happens without interruption - just when mind control ends), I get disconnected and cannot log back in into the arena match. For example I mind control a warrior and a druid charges me in bear form, which interrupts my channeling cast, I get instantly disconnected. This happened every time I tried it - 3 or 4 times. This is a very significant bug in my opinion that influences a gameplay a lot.

Thank you in advance for your help on the issue.
Best regards.

**Comment by Jerrythemagicdog** [comment]
Fixed with next update.
