### ISSUE TITLE
Cannot use ground mounts in Booty Bay

### ISSUE THREAD

**Issue by seastranger** [SunstriderEmu/BugTracker#3159]
**Describe the bug**
Cannot mount when in booty bay

**To Reproduce**
Attempt to use ground mount in booty bay

**Expected behavior**
Able to use ground mounts inside booty bay

**Screenshots/videos**
self explanatory

**Comment by pinkisnotgay** [comment]
Mounting in Booty Bay was introduced for the first time in Wrath Beta
https://www.engadget.com/2008-08-12-mounts-now-welcome-in-booty-bay.html

**Comment by artieau** [comment]
Working as intended
