### ISSUE TITLE
Frequent disconnects and can't log back in

### ISSUE THREAD

**Issue by Soulwrath** [SunstriderEmu/BugTracker#3160]
**Describe the bug**
Often times I will get disconnected from the server, after which I will be stuck at "Authenticating" or "Logging in game screen" all the while I will have no connectivity issues or drops (I've checked every time) 

**To Reproduce**
Not sure what causes or how it gets fixed (Usually I can log back in some time after 5-10 min with no changes on my end)

![WoWScrnShot_042820_011046](https://user-images.githubusercontent.com/64443081/80425886-41282c80-88ed-11ea-9f4b-45d338f898c0.jpg)

If there are any files or info I can share to assist, please let me know.

Thank you in advance

**Comment by InhumanGM** [comment]
Are you still experiencing this issue?
