### ISSUE TITLE
Zepplin from Grom'gol to Undercity is bugged

### ISSUE THREAD

**Issue by whakahemo** [SunstriderEmu/BugTracker#3161]
**Describe the bug**

When taking the Zepplin to Undercity from Grom'gol when it should show the map and the dotted line to UC the Zepplin disappears and drops you from the air and you die

Tried a couple times and it failed everytime - Also had other friends mention this as well

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/445

**Comment by artieau** [comment]
Duplicate of #445

**Comment by whakahemo** [comment]
So is this going to be fixed as it is still happening
