### ISSUE TITLE
[SERPENTSHRINE CAVERN] - [T5 OVERBUFF]

### ISSUE THREAD

**Issue by Baliang47** [SunstriderEmu/BugTracker#3163]
Dear admins,

I Baliang will speak for the french guild <Cheh> and give some comments after one week on T5. My comments only apply to **trash mobs, Hydros and Luker** as this is the only things we tried until now.

I have 3 points that I would like to discuss:

**- Overbuffing the content
- Roster configuration (Which depend on overbuffing content)
- Trash loots**

**Overbuffing content:**
We saw that you applied a really high buff on the global content, which is similar to what other servers did such as warmane/Netherwing/Sunwell and this is a good point to make something that is clean since more than 10 years a little bit more difficult. My point is that I think you over buffed the content. Let me explain with some stats that we got:

- Hydros: Endless 8.14 Mhp/Retail 3.7 Mhp (Pure Spawn 143khp/retail 55khp)

- Void Reaver: Endless 12.57 Mhp/ Retail 4.5 Mhp

**Roster Configuration**
We saw the content is clearly feasable as Next Fresh When (GG to them btw) cleaned most of it during the first week. 
My point is all the guilds are not Hardcore guild as they are with a huge turn over on the roster making possible as they did on Hydros to have 6 warlocks, 4 hunters 3 mages that drives the DPS. 

We, as french guild (and I bet many other guilds) do not have the same pool player as they do as we have to recruit french speaking players which drastically reduce the possibility to have such a turn over on our Roster. 

My concerns is that you made the T5 content only for Hardcore guilds which is to me a big mistake as most of the guilds are not hardcore.

**Trash Loots**
Last comment is about the trash loots, we cleaned trash from entrance to hydros 2 times, all the platform from lurker once and we got no thrash, no vortex, did you intentionnally reduce the loot chance on trashes?

I would like to discuss with you guys on discord about this
Kind Regards
Baliang

**Comment by frastsytt** [comment]
Trash loots it sounds like u probably got a little bit unlucky, seen plenty of drops from all mobs including the ones u mentioned.

**Comment by kelno** [comment]
Thanks for your input. I can't disclose much of what's planned but we're discussing a lot content buffing and what we want to do with it.
Be sure we read this kind of comments and take them into consideration while deciding what to do next.
