### ISSUE TITLE
Incorrect arena matchmaking

### ISSUE THREAD

**Issue by SuddenDeath** [SunstriderEmu/BugTracker#3164]
**Describe the bug**
Queueing arenas always matches you with team rating, should only match with team rating if the players who queue average personal rating is within 150 rating of team rating.

**proof**
http://web.archive.org/web/20151230002958/http://www.arenajunkies.com/topic/21769-blizzard-arena-rating-calculations/

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.
