### ISSUE TITLE
Curse of Elements %  damage taken wrong.

### ISSUE THREAD

**Issue by maylersaid** [SunstriderEmu/BugTracker#3165]
**Describe the bug**

The spell says: Rank 1 reduces 45 all elements and increasing 9% all elements on the target.
                        Rank 2 reduces 60 all elements and increasing 11% all elements on the target.

When i cast on a target says: Rank 1 reduces 45 all elements and increasing 6% all elements on the target.
                                               Rank 2 reduces 60 all elements and increasing 9% all elements on the target.

-----------------------------
Fatcs

Rank 1 on mouse
![image](https://user-images.githubusercontent.com/54895599/80503800-c1c84680-8948-11ea-835e-f696ccf0a89d.png)

Rank 1 on mob 
![image](https://user-images.githubusercontent.com/54895599/80503823-cb51ae80-8948-11ea-843d-291418b620ac.png)

rank 2 on mouse 
![image](https://user-images.githubusercontent.com/54895599/80503867-d6a4da00-8948-11ea-82a6-1d70dad6df5f.png)

rank 2 on mob
![image](https://user-images.githubusercontent.com/54895599/80503893-ddcbe800-8948-11ea-8038-4168648d42be.png)

**Comment by Jerrythemagicdog** [comment]
You're specced Affliction, the tooltip of the actual debuff is never updated for any spell (contrary to your own tooltip you see in the Spellbook).
