### ISSUE TITLE
Unable to download the client

### ISSUE THREAD

**Issue by ivanraja** [SunstriderEmu/BugTracker#3166]
Not exactly a bug, but the client is currently unavailable for download through the magnet link due to 0 seeds.

Is there any alternative out there I can make use of? Let's say a MEGA link or something similar.

Thanks in advance.

**Comment by beraus** [comment]
You can try here: https://download.wowlibrary.com/tbc/TBC-2.4.3.8606-enGB-Repack.7z
Use discord for questions like this one.
