### ISSUE TITLE
(Shaman) Flametongue Weapon doesn't get bonus critical strike damage from elemental talent "Elemental Fury"

### ISSUE THREAD

**Issue by LugerTypeA** [SunstriderEmu/BugTracker#3167]
Flametongue Weapon critical strikes right now deal only 150% damage, but they should deal 200% damage with Elemental Fury. Notably, Frostbrand Weapon gains this bonus correctly, so must be a local issue related specifically to Flametongue Weapon's interaction with aforementioned talent. Please, deliver a fix on this, this is a major issue.

**Comment by LugerTypeA** [comment]
This post didn't get a response, and the bug is still in the game. I can provide screenshots of Flametongue Weapon normal and critical strikes (and Frostbrand too for comparison). Will this help to get the attention? This issue heavily messes with my build, please, respond.

**Comment by beraus** [comment]
No need to open multiple reports, you could add images to this one. Closing this, will leave another one. Thanks.
