### ISSUE TITLE
mailbox

### ISSUE THREAD

**Issue by syme84us** [SunstriderEmu/BugTracker#3168]
**Describe the bug**
not able to retrieve mail from the mailbox

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Godmatik** [comment]
close your client and reboot

**Comment by syme84us** [comment]
> close your client and reboot

I did and still have the same issue

**Comment by Godmatik** [comment]
you need to completely close your client, not just log out.
