### ISSUE TITLE
Bestial Swiftness Talent not working

### ISSUE THREAD

**Issue by Chuggernut** [SunstriderEmu/BugTracker#3170]
**Describe the bug**

The Beastial Swiftness talent in the Hunter Beast Mastery tree is clearly not working. After getting it pet still runs towards me and things I tell it to attack at the same speed. Tested it multiple time and tried dismissing and recalling the pet after getting the talent, also tried taming a new pet. Nothing makes it run the 30% faster that it should. 
**To Reproduce**

1. Watch your pet run towards something
2. Put a talent point in Bestial Swiftness
3. Watch your pet run towards something at the same speed that it did before

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://classic.wowhead.com/spell=19596/bestial-swiftness

**Expected behavior**

I expected my pet to run 30% faster when it's outside, but it definitely does not

**Screenshots/videos**

**Additional context**

Seems like the melee range of your pet is smaller than it should be when enemies are Fleeing from it

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/1973
