### ISSUE TITLE
Hunter dissconect

### ISSUE THREAD

**Issue by pampam217** [SunstriderEmu/BugTracker#3173]
Class:Hunter
Race;Night elf
Bug:disconnect after using a spell(Eyes of the Beast)

**Comment by BarmyDwarf** [comment]
Hey, my gf is having the same issue.  I've made a post about it too.  No response for about 4-5 days now.  Don't know how long it should take to get affirmation of the bug.

**Comment by kelno** [comment]
I'm Kelno and I affirm this bug

**Comment by kelno** [comment]
Fixed since afaik
