### ISSUE TITLE
Nethercobra Leg Armor never showed up in mailbox

### ISSUE THREAD

**Issue by storpiknrg** [SunstriderEmu/BugTracker#3174]
**Describe the bug**

This happened yesterday and i wrote a ticket about it that suggested i went on here and reported it as a bug. 
Character details: Storpiknrg - Blood elf Rogue
I spent 390g on the Nethercobra Leg Armor on AH - Auction won and the gold dissappeared from my bag.. Went and checked my mailbox but i didn't recieve anything. Then i tried reopening the game and i had recieved a mail - the mail was empty however..
**To Reproduce**

1. Bought Nethercobra Leg Armor on ah for 390g
2. Nothing recieved in mailbox.
3. Relogged
4. Still nothing in mailbox.

Item: https://wowhead.com?item=29535

**Expected behavior**

I expected to recieve the item bought since it said 'Auction won' and i lost 390g from my inventory.

**Screenshots/videos**

**Additional context**

I really hope you can either recover my lost item or the lost gold - since i can't afford to buy the item again.

EDIT: Since making this post i have also lost 3 auctions of Linen Cloth and 3 auctions of Rough Stone.

**Comment by beraus** [comment]
We need more info if this was the issue, but mailing system was improved since. 
If you have more recent data feel free to open a new issue with details. Thanks!
