### ISSUE TITLE
Bug in ZG ( Zul'Gurub )

### ISSUE THREAD

**Issue by yesyes12** [SunstriderEmu/BugTracker#3175]
The Zulian Crocolisk are frost immune but it only says immune 5% of the time but you cant hit em

Zulian Crocolisk should not be frost immune.

plz fix

**Comment by Sheikthecatman** [comment]
![image](https://user-images.githubusercontent.com/59149613/81986584-5bc20b80-9638-11ea-97e9-9403726b5415.png)
No immunities or resistances.
