### ISSUE TITLE
Auction house items not appearing up the last few days on main 

### ISSUE THREAD

**Issue by jsaden** [SunstriderEmu/BugTracker#3176]
My main, a draenai shaman, is unable to see most items on auction house. If I just hit bags under containers, nothing will show up. Like nobody has posted any bags. But when I go over to my alt on the same account, I can see everything. My main CAN see some random things. Like if I search for all axes, i'll show up like, 2 blue axes, but that's it. Happened a couple days ago after an update it seemed

**Comment by beraus** [comment]
Can you confirm if this is still happening?
