### ISSUE TITLE
Can't continue farming Netherwing reputation

### ISSUE THREAD

**Issue by Jsanzo97** [SunstriderEmu/BugTracker#3177]
After finish the first chain quest to be neutral with the Netherwing faction, i learn the 300 riding skill. When i go to the Dragonmaw Fortress or the Netherwing ledge i receive the Dragonmaw Illusion so all is correct. The problem is that when i go to talk with Mordenai npc to continue with the quest i cant talk with him, i search and i see that i don't need anymore requisites to start this chain so i think is bugged or something, sorry if i have bad english

**Comment by beraus** [comment]
This is not live yet.
