### ISSUE TITLE
Horde Quest Items droprate is not increased in Outlands as stated on Homepage, Alliance works!

### ISSUE THREAD

**Issue by illmore** [SunstriderEmu/BugTracker#3178]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by kelno** [comment]
I've checked again, it's correctly working with x2 rate
