### ISSUE TITLE
Darkmoon Cards not dropping

### ISSUE THREAD

**Issue by devo6969** [SunstriderEmu/BugTracker#3179]
**Describe the bug**

Are level 70 Darkmoon Cards going to be released with T5?
Yes. Each creature that has a chance to drop a card will be able to drop any of the cards. Aces will be reserved to heroic end bosses as usual. (There is legit none of the AH and I've only seen it drop in T5)
(This is not the case at all. The only mobs that drop this is Tier 5 mobs)
**To Reproduce**
 Your database has only a selective few mobs that have "this card" and i been farming it for 6 hours now wasting my time when the database isnt even accurate. Give all mobs a chance to drop the cards, as it states simple fix. 
1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

After like 4 hours of farming, or an lucky unexpected drop, you should get at least a 2-4 darkmoon cards cause usually 5-8 are the hard ones. Please... 
**Screenshots/videos**

**Additional context**

**Comment by TOgilvie19** [comment]
I agree, this needs to be looked into. Could just be unlucky but I've been spamming for Blessings cards in global, haven't received one whisper. Check AH periodically throughout the day (NA, working from home), only seen a couple. The couple that I have seen, we've also seen drop in T5.

From what I can find, Aces drop from end bosses of instances (normal or heroic, depending on their level, 68+), 2, 3, 4 and 5 drop from the world (we've seen a 2, 3 and 5 from SSC and ONLY 2, 3 and 5 on the AH), but 6, 7 and 8 I believe only drop from elites in instances. Haven't seen the 6, 7 and 8 in T5 yet, but I imagine these should be more plentiful as they should be dropping in normals and heroics and we're just not seeing any.

**Comment by dadshers** [comment]
I agree, this needs to be looked into. Could just be unlucky but I've been spamming for Blessings cards in global, haven't received one whisper. Check AH periodically throughout the day (NA, working from home), only seen a couple. The couple that I have seen, we've also seen drop in T5.

From what I can find, Aces drop from end bosses of instances (normal or heroic, depending on their level, 68+), 2, 3, 4 and 5 drop from the world (we've seen a 2, 3 and 5 from SSC and ONLY 2, 3 and 5 on the AH), but 6, 7 and 8 I believe only drop from elites in instances. Haven't seen the 6, 7 and 8 in T5 yet, but I imagine these should be more plentiful as they should be dropping in normals and heroics and we're just not seeing any.

**Comment by devo6969** [comment]
According to their "database" select few mobs drop the cards and some are in Black temple lmfao... its just an awful database and the mobs in SMV for the Netherwing drakes arnt even there to farm.  but yes 100% needs to be fixed. Otherwise we gonna see Two of Blessing for like 2k gold

**Comment by Jerrythemagicdog** [comment]
Thanks, chances will be updated with next restart. All hostile creatures in Outland above level 68 will have a chance to drop one of the cards. All heroic end bosses will have a chance to drop one Ace.
'976388c16f03bea30956df4289441c1735089de4' (s)
