### ISSUE TITLE
UI Bug: Dartboard Radar looking on screen

### ISSUE THREAD

**Issue by jspoilers33** [SunstriderEmu/BugTracker#3181]
**Describe the bug**
On my screen to the right there's a circle dart board looking bug that is present on the login screen and in game. I tried deleting the game and reinstalling and still did not fix the issue. Please see screenshot below. 

![Screenshot (8)](https://user-images.githubusercontent.com/64555937/80639268-9f046380-8a16-11ea-9bc2-361eceab0111.png)

![Screenshot (9)](https://user-images.githubusercontent.com/64555937/80639475-ec80d080-8a16-11ea-866d-65d6715e1f00.png)

**Comment by Jerrythemagicdog** [comment]
This is not something we control and it must be some third party software you have running in the background. Check the processes you're running with Task Manager, hopefully that leads you to finding the issue.
