### ISSUE TITLE
Teron Gorefiend, I am...

### ISSUE THREAD

**Issue by elNebba** [SunstriderEmu/BugTracker#3184]
**Describe the bug**
the quest doesn't work properly : when i get possessed by Teron , I don't see the enemy to kill , which is Krasius the ancient watcher. Thus, i have no one to kill to complete the quest

**To Reproduce**
<!--- Accept the quest , listen to the speech for 5 seconds , you get transformed into Teron , and you should find the target to kill , Krasius the ancient watcher

Quest: https://www.wowhead.com/quest=10639/teron-gorefiend-i-am#storyline
Spell: https://wowhead.com?spell=

**Expected behavior**
<!--- the target should appear after i get possessed by Teron

**Screenshots/videos**
<!--- 
![WoWScrnShot_042920_223919](https://user-images.githubusercontent.com/64557197/80650097-2bd90c80-8a6b-11ea-8dc5-f8e3bbd391a7.jpg)

**Additional context**
<!--- no addtional context

**Comment by Jerrythemagicdog** [comment]
You need to be wearing Spectrecles to see the NPC you need to kill.

**Comment by elNebba** [comment]
I am an idiot . thanks !
