### ISSUE TITLE
Warrior Heroic Strike/Cleave queueing if no rage.

### ISSUE THREAD

**Issue by frastsytt** [SunstriderEmu/BugTracker#3187]
So if you happen to queue up a HS/cleave as a warrior and while the spell is queued you happen to use another spell that spends your rage so you won't have enough for the HS/cleave to come, your autoattack completely skips. It should just do a **regular white attack** if you have a HS/cleave queued with no rage.

https://streamable.com/m5jcel - current interaction

Notice how I:
**1**. Whiteswing into 14 rage
**2**. Queue up HS
**3**. Use battleshout so my rage drops below the required amount for HS
**4**. End up not doing anything when swingtimer ends and going for a new cycle.

This bug severely affects warrior gameplay and as a result I have become a crippled alcoholic. Thank you for reading.

**Comment by mechanicsTBC** [comment]
https://www.youtube.com/watch?v=77ZvVYQEjCk
if proof is required that this is indeed a bug you can watch this video.  go to 1:53.  put the playback speed to X0.25
> taunts boss 
> shield blocks
> ques up heroic strike
> shield slams
> 1:56 shield slam hits boss and a white attack as well since he doesnt have enough rage for heroic strike

**Comment by Bugadin** [comment]
up.

**Comment by kelno** [comment]
Fixed with next server update
