### ISSUE TITLE
Morogrim Tidewalker hit box = microscopic

### ISSUE THREAD

**Issue by frastsytt** [SunstriderEmu/BugTracker#3188]
Morogrim's melee hitbox is alot, alot tinier than it should be. Yeah, nothing gamebreaking but pretty annoying.

Added assistive artistic drawing of the situation.
![image](https://user-images.githubusercontent.com/57603552/80678350-6a021a80-8ac3-11ea-8d5e-463e5ed2925d.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update!
