### ISSUE TITLE
[HUNTER] Auto Shot Target Swapping Bug -GAMEBREAKING-

### ISSUE THREAD

**Issue by hyesuneex** [SunstriderEmu/BugTracker#3189]
Auto Shot bugs on Target Swapping, you have to reset Auto to make it work again which is in itself a direct DPS loss. This should be considered a high priority bug to be fixed therefore as it's just frustrating and uncomfortable to play bosses in T5 where Target Swapping for adds is a necessity. Sadly there are a lot of those bosses that require Hunter Add Focus in T5... this bug has been active for weeks now.

FOOTAGE
https://www.youtube.com/watch?v=h6UEMGG3dvA

When seeing the footage it should be self explanatory how bugged and annoying target swapping is ATM, still in T5. Therefore the preset bug report was not used. 
Again, please make this a high priority fix, I consider Hunter simply a broken class like this.

**Comment by kelno** [comment]
Duplicate https://github.com/SunstriderEmu/BugTracker/issues/2940
