### ISSUE TITLE
Auction House spam

### ISSUE THREAD

**Issue by hidvegigabor** [SunstriderEmu/BugTracker#3191]
In the past few days a character called "Biromapiat" flooded the Auction House with about 1000 items of Netherweave Cloth.

One problem is with it that he set very high prices (usual price is around 20 silver each, he posted around 90-99 silver each), so he can rip off players not paying enough attention.

The other problem is that because of the five second delay between pagination in the Auction House, now it takes more than three minutes to scan all pages of these clothes. And because new items are usually around the last pages, it became very frustrating to browse.

I opened a ticket, and Game Master Nori asked me to open an issue here with suggestion.

I think that it might be better if one could not post more than say 200 items (full or not full stacks) of the same item.

**Comment by networm555** [comment]
That wont solve this problem. Restrict non consumable auctions to post lesser than 10. If you want to sell 1-9 cloth use trade channel. The only logic for posting 1-9 item is a scam.

**Comment by hidvegigabor** [comment]
You cannot solve this problem really, just make spammers' job harder, so they will be less active.
