### ISSUE TITLE
Shadow Labs "Entry Into Karazhan" key did not appear after final boss

### ISSUE THREAD

**Issue by Abschatten** [SunstriderEmu/BugTracker#3194]
**Describe the bug**
The item to get for the Entry into Karazhan quest did not show after killing the final boss, a Heroic reset took place mid Dungeon. 

**To Reproduce**
Go into Shadow Labs and kill all bosses prior to final boss, wait for a instance reset

Dungeon: https://www.wowhead.com/shadow-labyrinth
Quest: https://www.wowhead.com/quest=9831/entry-into-karazhan

**Expected behavior**
Key spawns, and able to take

**Screenshots/videos**

![WoWScrnShot_043020_001742](https://user-images.githubusercontent.com/11303717/80737930-7ab98d00-8ad1-11ea-8801-9edd50ecd97a.jpg)

**Additional context**

**Comment by beraus** [comment]
Prob related to HC and NM dung reset time, thanks.
