### ISSUE TITLE
The Stone That Bind Us stone not working.

### ISSUE THREAD

**Issue by Txholy** [SunstriderEmu/BugTracker#3196]
**Describe the bug**
<The Stones That Bind Us a follow up quest from NPC Fallen Hero, it requires you to bring the creature under 10% hp which at that point he becomes Spirit Shocked, and once you activate the stone the creature is supposed to die. I've tried doing the Servants of Razelikh which worked fine but all other Servants seemed to be bugged. -->

**To Reproduce**

1.After stone is triggered the Servant doesn't die, he remains in Spirit Shock state.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Simon-GM** [comment]
Reproducing the issue provides me the same results as you are mentioning in your report.

Servants of Razelikh can be freed upon bringing them close to the ''Stone of Binding'', damaging them until their physical form is weakened and then clicking the ''Stone of Binding'', before finishing the Servant off.

Servants of Grol, Servants of Allistarj and Servants of Sevine does not become killable by following those steps. Instead they will remain at 1hp, which causes players not to receive credit.
![Servant](https://user-images.githubusercontent.com/61908478/81128166-c42a3200-8f40-11ea-8a28-961dba3d0770.png)

**Comment by frastsytt** [comment]
Duplicate #1706

**Comment by Sheikthecatman** [comment]
Thanks! It should be fixed next server restart. The respawn timer for the stones has been decreased too.
