### ISSUE TITLE
Cant loot items from mailbox

### ISSUE THREAD

**Issue by mathh17** [SunstriderEmu/BugTracker#3197]
**Describe the bug**

I bought an item from AH, it shows i have mail from AH, it doesnt show when i open Mailbox

**Expected behavior**
To be able to loot my item

**Screenshots/videos**

![image](https://user-images.githubusercontent.com/32058578/80763053-f6512380-8b3d-11ea-81a1-de6f47788766.png)

**Additional context**

**Comment by Godmatik** [comment]
close client and reboot, it's a temporary fix

**Comment by beraus** [comment]
It seems to take a while in some cases, especially when you have many items in your inventory.
I'll close this for now but we'll try improving the mail system to be faster in the future.

_Originally posted by @kelno in https://github.com/SunstriderEmu/BugTracker/issues/2953#issuecomment-622942994_
