### ISSUE TITLE
BOORING disconnecting PLEASE FIX THIS

### ISSUE THREAD

**Issue by jesus777777** [SunstriderEmu/BugTracker#3198]
hi , im playing in this server since day one and im geeting dced like 50 times day its not even my internet connexion caus im geeting dc only from game and discord and other windowns open o my pc keep runing normally and some players from my guilde and irl friends get same frobleme we are from same region we are 100% sure its from u SO PLEAS CAN u do something about this and take it seriously my friend and me did request from this problem , and we are about to leav server tbh if it continue caus its just not fun and cant do anything , i hope you will do something about this , im from algeria

**Comment by Godmatik** [comment]
You're the only one with these issues... it's on your end

**Comment by Soulwrath** [comment]
Actually he is not ... I've had the same issue for weeks and it's really random and nothing related to my connection, also had a post to no avail

**Comment by beraus** [comment]
Contact us on Discord.

**Comment by Nightshala** [comment]
I get disconnected it seems every time I play. Then i try to log back in and stays at authenticating doing nothing. Then the next day, I go to log back in, I get in, play for a couple hours then get disconnected , then same thing happens stays at authenticating.
![WoWScrnShot_050920_124229](https://user-images.githubusercontent.com/58376372/81482250-cf0bed80-91f2-11ea-8176-bed724d5992d.jpg)
