### ISSUE TITLE
Reporting Major pvp bugs in this server.

### ISSUE THREAD

**Issue by avclol** [SunstriderEmu/BugTracker#3199]
Hello everyone I'd like to report some serious bug in this server which are killing the PVP in this server.
First of all I'd like to start with the most dangerous bug which is ( WF Totem of shaman) it proc x10 times than it should. Second bug, its Mage pet ( its makes 50 % more damage than it should.( warlock pet is making exaggerated damage too.
Third bug which everyone is crying over, its warrior damage which are obviously doubled. I will provide videos about it. Number 4, Rogue blind miss is getting toxic even with 160 Hit rate you can miss 4 blinds out of 10. ( even behind the target ). Number 5 Hunters aspect of the viper, This spell should restore mana pts to hunter based on his intellect. In official server we were able to see mana regeneration on Character list /spell. when you are near to oum, you jum from 80 mana reg per second to 300 and more ( depends on your intellect) in addition  Frost trap is a disaster the ranged of the effect is obviously reduced and enemy can walk freely in it ( they can jump and walk without being slowed .Finally the biggest issue is that you can receive some spells behind pillar ( if the enemy cast something and you get behind a pillar you'll receive that spell anyway, and also when playing a druid or any ranged class you will receive melee dps even if you stand faraway from that melee dps . Im sorry to right a lot of things at the same time,but this major bugs are killing pvp in the Server. Still other bugs exists I forgot to mention hope we get a patch for next season.

**Comment by lastnoob** [comment]
Regarding Blind miss, isn't Endless supposed to have the 1% innate miss chance removed anyways? It's very annoying.
