### ISSUE TITLE
Auto Shot bug

### ISSUE THREAD

**Issue by reeses1080** [SunstriderEmu/BugTracker#3200]
**Describe the bug**

99.9% of the time when i change target as a hunter whether it is with tab or right click my auto shot bugs out. Constantly interrupted or Invalid target, over and over every .1 second until I use/cast a skill or cancel Auto Shot and and recast Auto Shot

**To Reproduce**

example
1. attack curator , add spawns
2. tab or right click add
3. get locked out of auto attacks

Item: https://wowhead.com?item= every gun or bow i have used
Quest: https://wowhead.com?quest= n/a
Spell: https://wowhead.com?spell= Auto Shot

**Expected behavior**

fix please  : D

**Screenshots/videos**

https://puu.sh/FEMm8/6fc9189ed9.jpg
https://puu.sh/FEMvE/1d08a02790.jpg
 note the "Interrupted" in red text
it will happen on any mob any time i switch targets. no matter if i right click or tab target.

**Additional context**

i need to be top dps as hunter all the time please halp :P jk... but for real though. whatever is happening is extremely annoying. please fix :)

![WoWScrnShot_043020_205000](https://user-images.githubusercontent.com/64622892/80781974-35c14500-8b29-11ea-985c-c91fabd2539d.jpg)
![WoWScrnShot_043020_203023](https://user-images.githubusercontent.com/64622892/80781994-45d92480-8b29-11ea-9b96-b7d7cfb7ba5c.jpg)

**Comment by xopheus** [comment]
Seconded - happens every time target is changed. Looks like cast starts but gets interrupted after .01 seconds and character just stands there jerking without shooting.

**Comment by kelno** [comment]
Thanks!
Duplicate https://github.com/SunstriderEmu/BugTracker/issues/2940
(now fixed)
