### ISSUE TITLE
arena personal rating 

### ISSUE THREAD

**Issue by lovro22** [SunstriderEmu/BugTracker#3202]
Hello...i was doing 2v2 today with my partner and we won games and lost in the same time personal rating...what is going on?

**Comment by sposobniy** [comment]
I saw this report https://github.com/SunstriderEmu/BugTracker/issues/3164  
But my opinion better finish this season with old system rating calculating ,2 weeks till season will end

**Comment by MalenkiiMuqq** [comment]
> I saw this report #3164
> But my opinion better finish this season with old system rating calculating ,2 weeks till season will end

can I get an answer to my post that was created a day ago? This is very important, a lot of time and money was spent. Please, help
https://github.com/SunstriderEmu/BugTracker/issues/3192

**Comment by kelno** [comment]
There has been some update to the rating system which introduced some issues.
Those should be fixed with next server update
