### ISSUE TITLE
[Quest] Cyclonian - Bloodscalp Tusks

### ISSUE THREAD

**Issue by ukiee101** [SunstriderEmu/BugTracker#3203]
**Describe the bug**
Bloodscalp Tusks don't seem to drop beyond 20. (I got 21 due to 2 dropping from last mob I think)

**To Reproduce**
Before they stopped dropping I turned in the Bloodscalp Bone Necklace and Bloodscalp Ears quests.
I have tried killing all types of Bloodscalp Trolls, none kept dropping after the 21.

Item: https://tbcdb.com/?item=3901
Quest: https://tbcdb.com/?quest=1712

**Expected behavior**
To get 30 Tusks so I can complete the quest and get my WW axe.

**Screenshots/videos**
Can screenshot the 21 Tusks but seems pointless.

**Additional context**
Ukie on the server, if more info is needed.

**Comment by Simon-GM** [comment]
I have attempted to reproduce the issue, following your explanation of the event.
I have been unable to get the same results.
The tusks does indeed keep dropping, even after turning in the other quests.

If you have anymore information, in order for me to be able to reproduce your situation, please let me know.

**Comment by spinelust** [comment]
I have the same problem. Also stopped dropping at 21 after I turned in the 9 tusk quest.

**Comment by spinelust** [comment]
Managed to trick the game with placing tusks in the bank. If they are not in your bag, trolls start to drop tusks again

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
