### ISSUE TITLE
[NPC] Bloodscalp Witch Doctor's Earthgrab Totem

### ISSUE THREAD

**Issue by ukiee101** [SunstriderEmu/BugTracker#3204]
**Describe the bug**
Bloodscalp Witch Doctor's Earthgrab Totem despawns after the troll's death but keeps spam rooting the player(s)

**To Reproduce**
1. Wait for the Witch Doctor to summon the Earthgrab Totem
2. Kill the troll (with totem being alive)
3. Totem vanishes but keeps rooting

NPC: https://tbcdb.com/?npc=660
Spell: https://tbcdb.com/?spell=8376

**Expected behavior**
EIther the totem despawns on troll's death and doesn't root or it stays alive and you have to kill it.

**Screenshots/videos**

**Comment by Simon-GM** [comment]
There is definitely something going on with the totem you are mentioning.
Totem stays alive after Bloodscalp Witch Doctor has died, but it also keeps casting roots after the totem itself has been slain.
![totemyes](https://user-images.githubusercontent.com/61908478/81130446-16228600-8f48-11ea-8230-8bfb00c4d9d9.png)

**Comment by Rockbiter-shaman** [comment]
This also happens in southwest tanaris with the rootshapers

**Comment by steak-house** [comment]
In addition to Thistleshrub Rootshapers, it seems it happens with any Earthgrab totem, as is the case with some trash mobs in Kraul whose name I forgot, and Jamalan in Sunken Temple

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in [5be755900463ede96525805c6d98388adfc16368](https://github.com/kelno/sunstrider-scripts/commit/5be755900463ede96525805c6d98388adfc16368)
