### ISSUE TITLE
Problem with Website

### ISSUE THREAD

**Issue by Crixiouss** [SunstriderEmu/BugTracker#3205]
Hey, I have an issue with something I did on Endless.GG and I didn't see a support page or anything. 

I bought that Soul trader Pet from the store on my one character. Then I wanted another on my alt but accidentally bought it for my Warlock who already had one. Is there a way I can go about moving one of them to my Alt Rogue on the same account.? I didn' tmeant to buy two for the same toon lol

**Comment by Godmatik** [comment]
your best bet is to open a GM ticket in-game

**Comment by Crixiouss** [comment]
> your best bet is to open a GM ticket in-game

I can't find in game where to put in a ticket. </3

**Comment by hufsa** [comment]
Resolved.
