### ISSUE TITLE
Can not invite anyone to my guild

### ISSUE THREAD

**Issue by radardl4** [SunstriderEmu/BugTracker#3206]
**Describe the bug**

In in guild panel I can not invite anyone to my guild. 
**To Reproduce**

after key in player name, it says "you can not guild invite until you become level 0"

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

![image](https://user-images.githubusercontent.com/64666742/80846202-bd11c580-8bc8-11ea-918d-e8e1451c4a27.png)
**Additional context**

Please let me why it happening, and how to you or i fix it, thank you.

**Comment by beraus** [comment]
You need to be level 12.

**Comment by radardl4** [comment]
than you

**Comment by radardl4** [comment]
Thank you
