### ISSUE TITLE
Big Bad Wolf in Kara loot table is incorrect

### ISSUE THREAD

**Issue by ahahenf** [SunstriderEmu/BugTracker#3208]
We just got a big bad wolf kill but two items from the shared dropped when its supposed to drop one shared item & one big bad wolf item 
![big wolf](https://user-images.githubusercontent.com/19628490/80852541-53041b00-8bde-11ea-9cd4-00356b9577ef.PNG)

**Comment by Skorlaa** [comment]
Can confirm. Killed him yesterday.. Got 2 items from shared loot table..
