### ISSUE TITLE
[Warrior] - Fury - Hit capped and still miss specials attacks

### ISSUE THREAD

**Issue by Bowell44** [SunstriderEmu/BugTracker#3210]
Hello,
BUG (?)
I'm currently at 109 hit score (which is 6,91% hit chance) with the precision talent 3/3 , I am at 9,91%. The cap for special attacks and yellow hits is normally at 9% and it appears I'm still missing some... it just happened with Bloodthirst on a lvl60 mob. 

**To Reproduce**
Use special attacks on mobs while hit capped. (9% hit chance)

**Expected behavior**
No more 'miss' yellow attacks while hit capped

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/64686366/80861838-657b6480-8c71-11ea-8a73-549ecacdf1b7.png)

Cheers.

**Comment by Skuzzlez** [comment]
I had a similar issue where I missed an arcane shot on a frost mage in arena despite being well over the hit cap. Something is definitely funky with hit rates.

**Comment by RyanBerge** [comment]
The text on Precision says it increases your chance to hit "with weapons".  Is it possible that it doesn't apply to Bloodthirst, because Bloodthirst doesn't use your weapon?

**Comment by Jerrythemagicdog** [comment]
Thanks, could you provide more details as to what target you were attacking at the time and if it's happened to you since that moment?

**Comment by Smashyxgod** [comment]
I had 199 hit same thing. Many misses.

**Comment by Bowell44** [comment]
Hi again,
So yes it happened once more on Attumen (KZ) just yesterday with Bloodthirst, I'm currently at 139 hit score + 3% precision talent which should avoid any misses on special attacks. As mentioned above I don't know if Bloodthirst is considered as a "spell" or a weapon attack... or If the hit cap (9% hit score) is enough for ALL yellow hit.

**Comment by kelno** [comment]
Yes 9% should be enough for Bloodthirst, there must be some issue.
