### ISSUE TITLE
Cant log in

### ISSUE THREAD

**Issue by Wrauxor** [SunstriderEmu/BugTracker#3211]
**Describe the bug**

I created account a while ago started playing yesterday i got in but today i cant log in it says i have invalid password or name tried to change password multiple times but doesnt let me in

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

![kuva](https://user-images.githubusercontent.com/64690933/80864333-a0d65d00-8c8a-11ea-971d-78b9f4d7fd20.png)

**Comment by beraus** [comment]
Contact us on discord.
