### ISSUE TITLE
[Quest] Proof of Allegiance - NPC Never Spawns

### ISSUE THREAD

**Issue by Isklar** [SunstriderEmu/BugTracker#3212]
**Describe the bug**
[Proof of Allegiance](https://www.wowhead.com/quest=10622/proof-of-allegiance) is bugged. [Zandras](https://www.wowhead.com/npc=21827/zandras) never spawns after being killed once. Only seems to appear on on a server restart.

NPC: https://www.wowhead.com/npc=21827/zandras
Quest: https://www.wowhead.com/quest=10622/proof-of-allegiance

**Expected behavior**
NPC should spawn in less than 15 mins.

**Screenshots/videos**
1) Showing time of arrival

<img src="https://dl.dropboxusercontent.com/s/44ocymthiec1p3a/NYCZIF5Oqt.jpg" alt="img"/>

2) Showing 15 minutes later at same spot (didnt leave). Imp seems to spawn alone, Zandras should spawn with 2 patrolling imps.
<img src="https://dl.dropboxusercontent.com/s/ost576wtxly0df8/OA06ExkTBJ.jpg" alt="img"/>

https://www.youtube.com/watch?v=0bo8bGZQzfw

**Comment by Simon-GM** [comment]
I have attempted to reproduce the issue, but without luck.
Zandras does indeed respawn short time after being killed.

I have also tried to force it into a bugged state, where Zandras wont respawn, but that did not work for me either.

I will be closing this issue, as Zandras' respawn is not bugged as described in the report.
