### ISSUE TITLE
Stratholme - Baron Rivendare Gate / Abomination Gauntlet

### ISSUE THREAD

**Issue by rsmoove6** [SunstriderEmu/BugTracker#3213]
**Describe the bug**
The entire Abomination Gauntlet before the Baron Rivendare boss in Stratholme "undead side" is completely bugged. 
Firstly, the gauntlet, the abominations are supposed to slowly run at you in time. Currently, the abominations just auto target and run at you the second the gauntlet starts.

Secondly, after you wipe or leave the dungeon during this gauntlet, the gate behind you, which locks you into the gauntlet, is supposed to raise and let you restart. This is currently not the case. The gate stays locked and never resets. I had to contact a GM to help me raise the gate one time and the second time around after waiting for 3 hours for a GM to do it again, they never showed.

**To Reproduce**
Go to do the Abomination Gauntlet in Stratholme before Baron Rivendare.

**Expected behavior**
Abominations are supposed to slowly run at you, not all auto target you and charge you.
Gate that locks you in is supposed to reset if you wipe.

**Comment by Massie323** [comment]
I would like to add to this, that even after you finish the entire gauntlet including Rivendare, the first gate remains closed, forcing you to either /unstuck, hearthstone, or leave the dungeon group to teleport out.

The abominations seem to work fine at this point though, but I'm unsure if they are supposed to sometimes chain-aggro 3 at the same time.

If anyone is trying to farm for the mount; I advise you to set your hearthstone to Light's Hope Chapel and just ghetto port after clearing. While tedious, it helps you kill time to avoid the 5 dungeons/hour lock.

**Comment by beraus** [comment]
Duplicate  of https://github.com/SunstriderEmu/BugTracker/issues/3569
