### ISSUE TITLE
BUG - Dire brew Transform

### ISSUE THREAD

**Issue by Eyon933** [SunstriderEmu/BugTracker#3214]
**Describe the bug**
Dire brew doesnt give you the Dark iron dwarf model

 https://tbcdb.com/?item=38320

**Expected behavior**
you drink the Dire brew and become a Dwarf for 1hour

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.

**Comment by Eyon933** [comment]
Update happend, wasnt fixed yet.
