### ISSUE TITLE
To long respawn time on Clefthoof Bull

### ISSUE THREAD

**Issue by Niylah** [SunstriderEmu/BugTracker#3215]
The respawn on Clefthoof Bull is insanly high. Up to 15 minutes while other animals like "Talbuk Thorngazer" have less then 2 minutes respawn. 

This varies ALOT. Sometimes the respawn is instant, sometimes 1-2 minutes and now its 10-15minutes. These mobs SHOULD have the same respawn time always. 

Ingame name: Mantikor

**Comment by ageerik** [comment]
bump

**Comment by Ownitup** [comment]
i have noticed this as well

**Comment by mdeluca0** [comment]
BUMP

**Comment by beraus** [comment]
This issue should be fixed now.
