### ISSUE TITLE
HUGE PRIEST MC BUG - Mindcontrol -> kicked -> DC -> Dead

### ISSUE THREAD

**Issue by JoyyNefarian** [SunstriderEmu/BugTracker#3216]
I mean, idk how this is not fixed, yet. It has been months now.
Whenever i mindcontrol someone in BG/Arena, and i get kicked on it (e.g. feral charge), i INSTA disconnect and die and it obv results in an arena loss...

Pls fix this, i opened a ticket 3 months ago and nobody cared. So i'm just not gonna use MC anymore or what...
Pls, fix the important stuff.
Thanks

**Comment by kelno** [comment]
Thanks for reporting.
Duplicate https://github.com/SunstriderEmu/BugTracker/issues/3216
