### ISSUE TITLE
Not joining channels

### ISSUE THREAD

**Issue by hidvegigabor** [SunstriderEmu/BugTracker#3217]
In the past days many times when I log in with a character, the client doesn't write that I join the common channels (trade, local defense, etc.), and I cannot write on them, but I can read them. I need to log off and on many times with the character to join and be able to write.

**Comment by patmanpost** [comment]
Having simular problems here aswell, sometimes i cant write in /1 or other chat. for me it was more thow that it wouldnt let me join the chat at all. I couldnt read or write in the common chat ( /1  /3 /4). I noticed this in outland.

**Comment by InhumanGM** [comment]
Are you still experiencing this issue?

**Comment by hidvegigabor** [comment]
Yes.

**Comment by InhumanGM** [comment]
I wasn't able to reproduce the issue, is there anymore information you could provide that could be used to try to reproduce the issue again?

**Comment by beraus** [comment]
Known issue, we're working on fix, /join global meanwhile.
