### ISSUE TITLE
The Cudgel of Kar'desh quest

### ISSUE THREAD

**Issue by Hon11111** [SunstriderEmu/BugTracker#3219]
**Describe the bug**
When i killed Nighbane and gruul, pick up Earthen and Blazing signet, next go to slave pens heroic for return quest and suprise, cant "continue" and complete.

Here is screenshot:
https://imgur.com/a/qlrG9Vb

I have 7 days open ticket with that bug and cant get answer. 
All can raid T5 conent, but not me.
Kind regards Hon

**Comment by NeonicSupersonic** [comment]
Bank items
Unbank items
Complete quest

**Comment by Hon11111** [comment]
i make that.. still buged :)
