### ISSUE TITLE
Brilliant Glass - Jewelcrafting (350)

### ISSUE THREAD

**Issue by Nefogazz** [SunstriderEmu/BugTracker#3221]
**Describe the bug**
I'm missing the Brilliant Glass training form outland jewelcrafting trainers.

**To Reproduce**
In Thrallmar and in Netherstorm i can't learn this from the trainers (i'm scryer).

https://wow.gamepedia.com/Brilliant_Glass

**Expected behavior**
I would like to train this to my character.
The link states, this is on the original servers from patch 2.4.0.

**Comment by NeonicSupersonic** [comment]
Its 2.4.0 item, as you mentioned. And it drops epic gems. I think jc economy ruined enough with majority gems selling under 10g (mining fix when?)

**Comment by Nefogazz** [comment]
> 
> 
> Its 2.4.0 item, as you mentioned. And it drops epic gems. I think jc economy ruined enough with majority gems selling under 10g (mining fix when?)

As you see at the bottom of the link, when it first added didn't drop epic gems.
![kép](https://user-images.githubusercontent.com/64729707/80918007-f0885780-8d62-11ea-958f-511cf729e1c5.png)

**Comment by Simon-GM** [comment]
This wont be added to the game before at a later state of content.
