### ISSUE TITLE
Recharging the Batteries

### ISSUE THREAD

**Issue by kev51** [SunstriderEmu/BugTracker#3222]
**Describe the bug**

Credit aren't allowed when successfully drained from phaser. I spoke with a couple of players around me and It didn't work for them as well.

**To Reproduce**

1. Get to the location north from arena 52
2. Use the blaster as soon as the emote trigger. "the phase hunter is very weak"
3. The phaser transform and we receive no credit for it.

![WoWScrnShot_050320_064311](https://user-images.githubusercontent.com/6617507/80912215-6d86e300-8d09-11ea-84f1-a433389c10fd.jpg)

**Comment by kev51** [comment]
https://www.wowhead.com/quest=10190/recharging-the-batteries

**Comment by kev51** [comment]
https://www.youtube.com/watch?v=TAUaQm25P34

**Comment by elNebba** [comment]
Hello , same here , tested it yesterday and today . Still same issue . 
Once you click on the quest item when the target is very weak , we don't get credit for it

**Comment by kelno** [comment]
Thanks, fixed with next update
