### ISSUE TITLE
chat

### ISSUE THREAD

**Issue by Hannos97** [SunstriderEmu/BugTracker#3224]
hello I'm writing because my character got stuck in world of warcraft I can't write to anyone and I don't see what they write in chat

**Comment by Hannos97** [comment]
.

**Comment by kelno** [comment]
You can use the "Unstuck" function on the website to move your character to the graveyard.
If you have more issues with chat please contact support in game or on discord.

**Comment by Hannos97** [comment]
Bug track didn't help

Kelno <notifications@github.com> ezt írta (időpont: 2020. máj. 3., V,
19:00):
