### ISSUE TITLE
Lack of rage in the druid tank

### ISSUE THREAD

**Issue by ezzo300** [SunstriderEmu/BugTracker#3227]
**Describe the bug**
when pulling mobs in any dung the gaining rage in the druid is not enough at all almost 
after my experience in the previous wowmania 
the druid is buged by low rage  

**To Reproduce**

1. Enrage
2. pull with luc
3. when mobs attack you  u still  get low rage (  which causes low agro as tank since u cant cast ur spells without rage as druid )

**Expected behavior**
Must have enouygh rage to cast all ur spells to Up enough aggro.

**Comment by beraus** [comment]
Sorry, but we can't do anything here without a clip or more context. Threat values are consistent with Omen libraries.

_Originally posted by @Jerrythemagicdog in https://github.com/SunstriderEmu/BugTracker/issues/1729#issuecomment-576029021_
