### ISSUE TITLE
Can not reamove corrupted guild member please help

### ISSUE THREAD

**Issue by Gisa1** [SunstriderEmu/BugTracker#3228]
Hi i am GM of guild The Eternals

Can not reamove guild memeber

i can't remove guild memeber with blank name, i have error "you must specify a target:/<command><target's name>
 Please help me endless.org :)
![WoWScrnShot_050320_190305](https://user-images.githubusercontent.com/63876075/80920628-4ebc3700-8d71-11ea-9ca3-de72037b8081.jpg)

**Comment by kelno** [comment]
I've fixed this particular case, this is a deleted character that didn't get removed from your guild correctly.
This usually works correctly and I didn't find the exact cause of this case yet.
