### ISSUE TITLE
Leotheras Insidious Whisper spell [ SSC ]

### ISSUE THREAD

**Issue by Bugadin** [SunstriderEmu/BugTracker#3229]
**Describe the bug**
Insidious demons cast shadow bolt and can't be reflected by warrior tanks so it makes REALLY difficult to kill the demons. Well, technically, it can be reflected but it deals 20 DAMAGE.

**To Reproduce**
Use spell reflection with warr when insidious copy cast shadow bolt

**Proofs**
Inner Demon capabilities:

~11,000 health
melee damage: ~1000
**spell damage: Shadow Bolt for ~3500 (reflectable)**
take increased damage (+65%) from arcane, nature, and holy spells
take slightly reduced damage (-20%) from shadow and fire spells
vulnerable to most forms of CC like daze, stun, disorient, fear and even banish (not recommended)

https://wowwiki.fandom.com/wiki/Leotheras_the_Blind

I don't get why no one has reported this when it's impossible to deal with the insidious whisper being a warrior tank.

**Comment by Bugadin** [comment]
up

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1557
