### ISSUE TITLE
Bestial Wrath does not break sap nor fear.

### ISSUE THREAD

**Issue by mierzyk** [SunstriderEmu/BugTracker#3231]
**Bestial Wrath does not break fearl & sap**

**To Reproduce**

0. Make sure that hunter has talent points in Bestial Wrath & The Beast Within 
1. Set pet on passive.
2. Sap Hunter, owner of pet.
3. Cast bestial wrath and see, that it does not break CC effect.

Same applies when replacing sap with fear.
When replacing sap with stun, eg. cheap shot, then bestial wrath properly breaks effect.
I'm not quite sure, but I do believe that bestial Wrath should also break Cyclone.

**Comment by Simon-GM** [comment]
Bestial Wrath and The Beast Within does not work as a CC-breaker in TBC.
In patch 3.2.2 **(WotLK)** this is changed to function like PvP trinkets.
