### ISSUE TITLE
Naxxramas: Trash mobs and bosses not dropping loot

### ISSUE THREAD

**Issue by bugreporterx** [SunstriderEmu/BugTracker#3233]
**Describe the bug**
If you go inside Naxxramas, you will find out that after killing many packs of mobs, they do not drop any loot at all. I do not know if the trash drops were disabled intentionally, but they should be enabled for people who are willing to collect gear for sets and memorabilia.

**To Reproduce**

1. Go inside Naxxramas (no attunement required) and kill any pack of mobs.
2. Some of the mobs do not even drop currency. Some do but most do not drop anything at all.
3. Attempt to kill any of the first bosses to see if they drop loot. They only drop gold but no loot whatsoever.

Item: https://classic.wowhead.com/naxxramas#drops 

**Expected behavior**
All mobs should drop at least currency and/or junk items and have a chance to drop epic items and items which are used for exchanging tokens for tier items.

**Screenshots/videos**
I did forget to record footage/take screenshots of killling mobs but it's something that is easy to check.

**Comment by bugreporterx** [comment]
Bump

**Comment by bugreporterx** [comment]
Are there any plans to script Naxxramas in the near future for those of us who want to clear it just to collect transmogs and/or just kill the bosses for fun? @Jerrythemagicdog.

**Comment by bugreporterx** [comment]
Bump

**Comment by beraus** [comment]
We can look into it soon, I can't make any promises but it shouldn't take long and this is long overdue.

_Originally posted by @Jerrythemagicdog in https://github.com/SunstriderEmu/BugTracker/issues/4369#issuecomment-714661477_
