### ISSUE TITLE
Druids can auto attack in flight form.

### ISSUE THREAD

**Issue by hashblaster** [SunstriderEmu/BugTracker#3237]
https://imgur.com/a/EZyCCj6

nice

**Comment by Simon-GM** [comment]
![druiddmg](https://user-images.githubusercontent.com/61908478/81072203-17bb6200-8ee6-11ea-9234-8ebe65c15435.png)

**Comment by hashblaster** [comment]
If you check my combat log he was hitting me for 10-15x that amount

**Comment by Simon-GM** [comment]
> If you check my combat log he was hitting me for 10-15x that amount

I did not wear any gear in that picture. Simply done for testing the issue.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
