### ISSUE TITLE
Lesser Invisibility Potion works incorrectly

### ISSUE THREAD

**Issue by LugerTypeA** [SunstriderEmu/BugTracker#3238]
Lesser Invisibility Potion should totally hide you from enemies - neither they see you nor you see them. And nevertheless sometimes you just lose invisibility. When walking through enemy mobs in invisibility you shouldn't get any aggro at all yet I always somehow enter combat as if they can still see me. And as I mentioned before sometimes without any visible reason I simply lose invisibility. That's not how this potion should work, neither you should get any aggro nor you shouldn't lose invisibility for no reason.

**Comment by Simon-GM** [comment]
I have attempted to reproduce the scenario, but without luck.
Some mobs does have stealth detection, and will see you even when using this type of potions.
Using the potion while having a damaging debuff, will remove the potion-effect upon damage tick. 

If you have anymore steps for me to follow, in order to reproduce the situation, please let me know.

**Comment by LugerTypeA** [comment]
Yes, I can provide steps. This happens to me in Scholomance. The sequence is the following: you go to Scholomance and reach the room full of ghouls, skeletons and a few nerubians. That room is locked by a door which leads to the second half of the instance, and the key is dropped from the boss in the catacomb. The boss with the key, the key itself and the door work perfectly. It is that room full of mobs which gives me troubles. When I use Lesser Invisibility Potion there, while passing to the door to unlock it while being invisible, I almost always get aggro though these specific mobs do not have any stealth or invisibility detection. I managed to not get aggro only once. And sometimes, approximately 20% of the time based on ~20-25 potion uses I lose invisibility while crossing the room. 
Also, I have another bug report which is worth a separate post actually, but I'll also mention it here. Hunter's Feign Death is bugged. When I cross the room in invisibility and open the door, I cannot drop aggro by FD and leave combat, even though I'm already standing in the next room and none of the mobs rush to me. And what is far more important, FD doesn't correctly let you out of combat, if you used it while mobs where casting spells and you at the moment you used FD. An important moment: FD doesn't drop combat only if the cast projectile is flying to you while you use FD, and it hits you while you're already lying pretending to be dead. If you use FD when mobs still not finished the cast, FD works correctly.

**Comment by z5n** [comment]
issue has since been fixed
