### ISSUE TITLE
Quest Portals of the Legion

### ISSUE THREAD

**Issue by najhorsi** [SunstriderEmu/BugTracker#3240]
**Describe the bug**
There are missing portals in quest **Portals of the Legion**

**Expected behavior**
There should be portals with guards, wait about an hour but still no portals.
I have already tried to relog.

**Comment by Simon-GM** [comment]
There does seem to be a potential issue with demon portals respawning, after they have been closed once already.

**Comment by EL100** [comment]
I can confirm. Couldn't find any portals nor guards.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.
