### ISSUE TITLE
Char turns invisible in Shadowlabs

### ISSUE THREAD

**Issue by illmore** [SunstriderEmu/BugTracker#3241]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Simon-GM** [comment]
Not enough info for us to investigate the issue. 
Please submit another bugreport, if you got more information for us.
