### ISSUE TITLE
tel athion the impuure get be kicked 

### ISSUE THREAD

**Issue by jowennl** [SunstriderEmu/BugTracker#3244]
shamen qeust that you need kill tel athion the impuure but you cant kick him that must be bug bic it caster ab and not aa atack spell

**Comment by hashblaster** [comment]
https://www.wowhead.com/quest=9508/call-of-water

" By 78471 (187 –  1)  on 2007/09/21 (Patch 2.1.3) | 
He's spell hits hard and aren't interuptable, just spam heal urself and throw in some shocks =)
i did it with 500hp and 1200mana as a 22 shammy... had to heal myself quite alot.. had around 400 mana when he was dead... Hint, Lesser healing wave =P "

**Comment by Simon-GM** [comment]
Not a bug.
