### ISSUE TITLE
Mining Veins spawning in unreachable locations

### ISSUE THREAD

**Issue by Greatham871** [SunstriderEmu/BugTracker#3245]
**Describe the bug**
Ore Veins stuck under the map / unreachable locations in BEM, maybe other zones too.

**To Reproduce**
Self explanatory

Multiple Veins

**Expected behavior**
Veins should be spawning in reachable locations

**Comment by Sheikthecatman** [comment]
If you provide examples I will be able to investigate these cases.

**Comment by ageerik** [comment]
Yes please fix this, you can only mine like 30% of them. Devs should find these super easy

**Comment by InhumanGM** [comment]
Can you please provide coordinates for the node(s) you are referring to?
