### ISSUE TITLE
Prisoner of the Bladespire quest 

### ISSUE THREAD

**Issue by ragnoren** [SunstriderEmu/BugTracker#3246]
The key required for the quest just doesnt seem to drop. We've killed over 60 bladespire orcs and no drops yet. If its not a bug can you atleast say what are the chances for key to drop?

**Comment by bjh368** [comment]
droprate is low but the quest works

**Comment by Simon-GM** [comment]
After reproducing the situation, I can confirm that the key does indeed drop from the Bladespire Orcs.
However, the drop rate might need a slight adjustment, as the drop rate currently seems too low.

**Comment by NightmareCGX** [comment]
> After reproducing the situation, I can confirm that the key does indeed drop from the Bladespire Orcs.
> However, the drop rate might need a slight adjustment, as the drop rate currently seems too low.

Have you already adjusted the drop rate? Yesterday, I and my friend have farmed bladespire's ogres over 1 hour, but still no drop.

**Comment by sitinanj** [comment]
Just grinded this as well with a party for more than an hour, still no drop. I don't think this is normal.

**Comment by ChuckFerrera** [comment]
I received the key, however I get the error "Requires Locked Wyvern Cage" whenever I try and use the item 'Spirit's Whistle'. I have tried using the item on the ground in front of the cage Leokk is in, on top of the cage, behind the cage, but it never works.
![Prisoner of the Bladespire Error](https://user-images.githubusercontent.com/65261502/86154828-9a6d3180-bad1-11ea-81fb-c29a2ea69fb9.png)

**Comment by ChuckFerrera** [comment]
@Simon-GM, I believe I have discovered another issue with this quest. Please see my comment above.

**Comment by ChuckFerrera** [comment]
I was finally able to get the cage to open. I found you need to stand directly underneath the cage and blow Spirit's Whistle.

**Comment by Jerrythemagicdog** [comment]
Increased the drop rates a bit, other than that the quest works as intended.
Thanks for the issue.
