### ISSUE TITLE
WElcoming the Wolf spirit Q

### ISSUE THREAD

**Issue by ShadyyXX** [SunstriderEmu/BugTracker#3249]
**Describe the bug**
After using Q item at right place, nothing happens

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=10791
Spell: https://wowhead.com?spell=

**Expected behavior**
After using Q item , Malukaz call a spirit wolf, then Q complete

**Comment by Simon-GM** [comment]
After reproducing the issue, I can confirm that this quest is not working as intended.

The quest-giver _(Malukaz - creature id: 18384)_, will begin the spirit summoning ceremony, as soon as the quest _(Welcoming the Wolf Spirit - quest id: 10791)_ is accepted by the player. He finishes the RP event, but no credit is awarded.

When the player uses the quest-item _(Ceremonial Incense - item id: 31344)_ it does not start the spirit summoning ceremony.

**Conclusion:**
The spirit summoning ceremony should not begin before the player have used the quest item.

**Comment by Jerrythemagicdog** [comment]
Can't reproduce, the quest was intentionally changed so the event starts when a player accepts the quest to work around certain issues, however the quest completes correctly once the event plays out (without using the Ceremonial Incense)
