### ISSUE TITLE
Clefthoof Bull 20+ Minutes to Respawn

### ISSUE THREAD

**Issue by Ownitup** [SunstriderEmu/BugTracker#3250]
Clefthoof Bull  NPC in Nagrand which is skinned for Thick Clefthoof Leather take 20+ minutes to respawn while the other mobs around them re spawn in under 2 minutes i stayed 20 minuets going around looking.

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/3215
