### ISSUE TITLE
The Big Bone Worm

### ISSUE THREAD

**Issue by VeydJade** [SunstriderEmu/BugTracker#3251]
**Describe the bug**
The boss is not called. After using the drum, spawn constantly then 3 gnomes, then 3 worms

Item: https://www.wowhead.com/item=31825/fumper  https://www.wowhead.com/item=31826/enormous-bone-worm-organs
Quest: https://www.wowhead.com/quest=10930/the-big-bone-worm

All actions are in the correct order and working. But the quest boss is not called up

**Comment by bjh368** [comment]
The quest works, but the chance of spawning boss is super low. It takes a loong time to complete it

**Comment by Simon-GM** [comment]
I have attempted to reproduce the issue.
Sometimes it does indeed take longer than others, but I did also get several worms within 5 casts of each other.

I think patience is your best tool in this situation.
