### ISSUE TITLE
High Astromancer Solarian

### ISSUE THREAD

**Issue by DanielA86** [SunstriderEmu/BugTracker#3252]
Date:2020-05-04	Server:Endless-Live
Reporter: Zenjarla

**Issue:**
After doing a few tries with a few different tactics and analyse the value, we have come to a few conclusions and question regarding how you want the fight to work and what the desired outcome you desire. 
**#001 – Wrath of the Astromancer**
The debuff that jumps around, currenty it release all 4 on pull, which is fine but it gives a challange to right from the pull instead of gradius increase the difficulty during the fight.
Currently i found it works like this in rule set:

- 1. After X second removes the DOT from current target but keeps Arcane dmg increase debuff
- 2. Once expired, jumps to nearest (alive) player
- 3. If the player have an Active DOT of the spell, Chose a NEW random target regardless of range
- 4. Applys the DOT and debuff to the new target, starsover from 1.

Becuse of this behavior and the slow travel time of the spell, its very hard (not imposible) to make a tank group of AR to ”soak” the debuff during the fight. Becuse if the debuff jumps to 1 melee player in start, and 1 range person. The melee player will have the debuff starting to countdown and getting ready to jump to a new target before the debuff have even reach the range person. This makes it (becuse of behavior nr 3) it almost imposible to have 2 tanks standing next to each other sharing the debuff jumping between. 

**Sugestion/Solution:**
Ether you change the behavior of the debuff soo the behavior 3 dont apply, IE 1 ”tank” can have 2 debuffs on him at the sametime. This would result that having AR Tanks would work and incase of ”bad rng” 1 tank could have all 4 dots on him at the sametime (which is a bit unlikly) but also would mean that the raid have a choice to ether use 2, 3 or more tanks to split/share the dmg. I think this opens up for good design and each guilds with different tank setup can chose.
Another option is to force the debuff have the same duration time regardless of travel distance, ie make it reach the target at sametime regardless of distance or make it instantly jumps. This will however force (most likly) the use of 4 AR Tanks to stand and dealing with the debuff and less room of ”own” setup design. 

**#002 - Blinding Light**
There is a issue here with making the damage (Arcane dmg) not being effected by resistance. If the ”AR Tanks” stacks AR they will still almost being 1 shoted by this during the fight. This makes AR (arcane resistance) stacking almost obsolete. The debuff should allways applie, but the dmg need to be effected by AR.

**#003 – Summoned Priests**
Issue of them not being interuptable except stun, but this was fixed. 

**Summary;**
I would say in the current state its near imposible to deal this boss without doing extreme cordinations to just deal with the jumping debuff. Even if changed the numbers of it, the issue still will be pressent of the ”RNG” traveltime and overall nature of the fight.

**Comment by Jerrythemagicdog** [comment]
Thanks for the feedback, the fight was changed a couple of times since then.
