### ISSUE TITLE
Rogue class quest for Poison, unable to finish.

### ISSUE THREAD

**Issue by Enrier** [SunstriderEmu/BugTracker#3254]
Hello, there's an issue with the Rogue class quest for getting Poison called [Kalven's Tower]. Unable to get the item [Defias Tower Key] from pickpocketing the mob [Malformed Defias Drone]. Which result in not being able to finish the quest for some reason. 

IGN: Swordowl Time: 9:05 realm time 06/05/2020

Quest: https://classic.wowhead.com/quest=2359/klavens-tower

**Comment by Enrier** [comment]
Okay so, was able to get the key by using ability [Sap] and then using [Pickpocket] thrice: 1st Time it gives money, 2nd time it is empty and on the 3rd one it provides the key. 
Might test this on another character later. This is still an issue, as the key and money should be in the same loot-table and you should be able to get both at the same time.

**Comment by InhumanGM** [comment]
Thank you for the information!
