### ISSUE TITLE
Paladin Quest Human The Tome of Divinity

### ISSUE THREAD

**Issue by lukss** [SunstriderEmu/BugTracker#3255]
Current behaviour:
After taking the quest The Tome of Divinity (Pala Class Quest for Redemption) once and abandoning it, it can not be accepted again.

Expected behaviour: 
Quest should be available from quest giver after abandoning it

IDN: Laids

Can you please make the quest available for me or make the Redemption Spell available for this character?

**Comment by InhumanGM** [comment]
After attaining and completing _The Tome of Divinity (2998)_ (given by Brother Wilhelm) and _The Tome of Divinity (1641)_ (given by Duthorian Rall), you are rewarded the item _Tome of Divinity (6775)_. This item then starts the quest _The Tome of Divinity (1642)_. Upon starting this quest, the item disappears from your inventory. If this quest is abandoned, there is no way to reattain the quest or put yourself back on this quest chain without GM assistance.

Video of Issue:
https://www.youtube.com/watch?v=67tKQccV6Pg

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update for Humans and Dwarves.
