### ISSUE TITLE
This is not a bug report just a humble request

### ISSUE THREAD

**Issue by Overdaze** [SunstriderEmu/BugTracker#3256]
My daughter deleted my characters. I really want to play my character. Sure the exp rates are high but i don't want to make a new one because it had really nice items and it wasn't far away from Outland. Wanted to make a donation to restore my chars, but the donation page is not available. Is there any other option to restore just one? Or can you give me some information when will be the donation page back online?

**Comment by Simon-GM** [comment]
The donation option is available again.
