### ISSUE TITLE
No aldor quests at neutral bug

### ISSUE THREAD

**Issue by BowStache** [SunstriderEmu/BugTracker#3257]
Aldor quest bug

I am a draenei who accidentially chose to side with the scryers, I did the repeatable quest to get aldor rep and now aldor is at neutral, even with neutral rep there is not a single quest for aldor I can do except the turn in for "Mark of Kil'jaeden", according to alot of wow wikis you would have unlocked way more quests at neutral rep for the aldor, but at the moment for me I only have the mark turn in

IGN: BowStache

**Comment by Simon-GM** [comment]
As far as I am aware, that is the way it should work.
Could you please add links to the information you are referring to?
