### ISSUE TITLE
Stuck at Authenticating

### ISSUE THREAD

**Issue by Nightshala** [SunstriderEmu/BugTracker#3259]
Can't log in.
![WoWScrnShot_050420_190136](https://user-images.githubusercontent.com/58376372/81212113-9a4d2b80-8f91-11ea-9a08-d97099dd2259.jpg)

Screen stuck at Authenticating.

**Comment by InhumanGM** [comment]
Are you still having this issue?

**Comment by Nightshala** [comment]
yes

**Comment by Nightshala** [comment]
Sometimes if I wait until the next day i can log in, but that sucks.

**Comment by InhumanGM** [comment]
What realmlist are you using?

**Comment by Nightshala** [comment]
Set realmlist logon.endless.gg

**Comment by Nightshala** [comment]
I got on today, but if I log off or get disconnected I won't be able to log
on until the next day.

**Comment by Nightshala** [comment]
Hello???
