### ISSUE TITLE
Romulo's Poison Vial

### ISSUE THREAD

**Issue by Mercantius** [SunstriderEmu/BugTracker#3260]
Dear GM,

It seems like Romulo's Poison Vial is bugged! I have tracked the amount of times the item procs (should be around 4-6 times per minute, with a 3% proc rate per hit) and it does not seem to proc at all. Moreover, after I was using the item I seemed to miss more hits (with hit cap of 8% on special abilities) than without using this trinket even though it has 35 hit rating on it. Could you please take a look at this item? Thanks in advance!

Kind regards,

A concerned player named Archmee

**Comment by beraus** [comment]
If you have a video of this issue - how it works, and how it should - would be great. Thanks
