### ISSUE TITLE
Grim Guzzler door can't be unlocked

### ISSUE THREAD

**Issue by joemamaweet1234** [SunstriderEmu/BugTracker#3261]
**Describe the bug**
The Grim Guzzler door cannot be unlocked by doing the quest for Mistress Nagmara or by giving Private Rocknot the ale he wants.

**To Reproduce**
1. Enter Blackrock Depths and go to the Grim Guzzler
2. Complete the quest given by Mistress Nagmara
3. No text option appears to make her open the door
4. Complete the quest to give Private Rocknot the drinks he wants
5. He does not open the door either

Quest: https://classic.wowhead.com/quest=4201/the-love-potion
Quest: https://classic.wowhead.com/quest=4295/rocknots-ale

**Expected behavior**
Completing the quest "The Love Potion" should give the text option to tell MIstress Nagmara to open the Grim Guzzler Door, but there is no option.
Completing the quest for Rocknot's Ale should have him cause a fight and get the door to open after fighting the boss Phalanx, but it does not. 

**Screenshots/videos**
https://imgur.com/3IlmcKf

**Additional context**
Without being able to open the Grim Guzzler door, you cannot access the rest of BRD without swimming through lava, and then you cannot access 3 of the bosses even when you do swim, plus you are stuck if you swim to Thaurissan with no way out.

**Comment by LugerTypeA** [comment]
That's wrong. I am an ordinary player and I myself managed to complete the Ale quest and the mob successfully opened the door by the known scenario sequence (slamming the door with the barrel's cork). Although I used the ale on the table in the Grim Guzzler tavern, I haven't tried buying the ale yet, maybe the bought ale is bugged, though I doubt it. As for the quest with the succubus, I can't speak, haven't tried to complete it.

**Comment by joemamaweet1234** [comment]
I only tried the bought ale which didn't work, have not tried using ale on a table as I didn't know you could do that. But the succubus quest definitely does not work as can be seen in the picture.

**Comment by EL100** [comment]
I bought the guy 3 rounds of ale and he went around to smash the beer barrels. The jet from the last barrel blasted the door open.
