### ISSUE TITLE
 issue with Allegiance to the Aldor

### ISSUE THREAD

**Issue by scheisshure** [SunstriderEmu/BugTracker#3262]
**Describe the bug**

**To Reproduce**

1. After i end q to improve reputation with aldor and decrease with scryers was confused couse it decrease me both of them not like is q working .Atm i am unfriendly with both fraction. 
2. https://ibb.co/GQqVLJt screen
3. 

Item: https://wowhead.com?item=
Quest: https://www.wowhead.com/quest=10551/allegiance-to-the-aldor
Spell: https://wowhead.com?spell=

**Screenshots/videos**

**Comment by Simon-GM** [comment]
Please open a ticket in-game, next time you are online.
