### ISSUE TITLE
Unable to access general chat

### ISSUE THREAD

**Issue by Neostune** [SunstriderEmu/BugTracker#3263]
Hello, on my character Skade I cannot access the general chat or any other chat for that matter.
I already tried pressing "O" and chat and the chats there are gray, indicating that they cannot be activated. I also tried writing /join general chat /join generalchat and nothing works.
In some areas it will work, but most of them not. 
This while I see other people writing in general chat, so I know its up an running.

Please help me fix this, since its very needed sometimes for special mobs or other kinds of inquieries for the genral crowd. 

Many thanks // Alicia

**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by InhumanGM** [comment]
Are you still having this issue?

**Comment by beraus** [comment]
Known issue, we're working on fix, /join global meanwhile.
