### ISSUE TITLE
MARA

### ISSUE THREAD

**Issue by uzmon123321** [SunstriderEmu/BugTracker#3264]
**Describe the bug**
 MARA IS LAGGING SO BAD THAT IT DROPS IN FRAMES IT IS UNPLAYABLE

**To Reproduce**

1. Cast X on target affected by ...
2. walk around mara
3. you skip frames the rest of the games are fine

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Simon-GM** [comment]
I haven't been able to reproduce the issue. 
Getting no frame rate drops what so ever.
