### ISSUE TITLE
Molten Armor is proccing damage on ranged attacks without Molten Shields talent

### ISSUE THREAD

**Issue by Rockbiter-shaman** [SunstriderEmu/BugTracker#3265]
**Describe the bug**
Molten Armor causes damage on incoming ranged attacks without the necessary talent, which is necessary to do this

**To Reproduce**

1. Cast molten armor
2. do not talent into Molten Shields
3. bug occurs when receiving ranged attack

WoWhead page on this talent deleted entirely. The talent's info regarding this can be seen by mousing over it

**Expected behavior**

Molten Armor only reflects damage to melee attacks, unless at least 1 talent point is spent on Molten Shields
**Screenshots/videos**

![WoWScrnShot_050720_034631](https://user-images.githubusercontent.com/62133692/81270560-e98a6f00-9018-11ea-8b19-91d8cb8e2f7d.jpg)
__
**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
