### ISSUE TITLE
[Warrior] Intimidating Shout

### ISSUE THREAD

**Issue by Smashyxgod** [SunstriderEmu/BugTracker#3266]
Intimidating Shout breaks from a tick of rend (63 dmg) / druid roots dmg (40 dmg) / any low dmg  like a throw.
While the warlock's fear dosen't break for 3-4 rounds of 500 dmg dots.

**Comment by Massie323** [comment]
The primary target fear is supposed to act like a sap and break from any damage. Only the other targets have a chance to break on damage similar to a warlock fear.

**Comment by Smashyxgod** [comment]
> The primary target fear is supposed to act like a sap and break from any damage. Only the other targets have a chance to break on damage similar to a warlock fear.
> Can you clarify if you mean that it breaks on all Intimi fears? Or did you only notice it on primary target?

I do know about the primary target should break faster...but this happens to the other targets aswell, i will try to get some footage.

**Comment by Simon-GM** [comment]
The fleeing targets should have a lower chance of breaking upon damage. 
However, they should not be immune to breaking upon damage.

I have attempted to reproduce the issue, you are referring to, but without luck.

Do you have anymore information to share about the situation?

**Comment by Jerrythemagicdog** [comment]
Intimidating Shout has two effects:
One Incapacitating effect (casted on the main target)
Fear effect casted on potential targets around the Warrior.

The first effect breaks on any damage, the others follow regular fear breaking rules, the same as Warlock's Fear break rules.
