### ISSUE TITLE
[Bug] - Guild information 

### ISSUE THREAD

**Issue by Ghostivan** [SunstriderEmu/BugTracker#3267]
Currently the guild information window is empty and my officers, members and me as a guild master we are not able to see what people is going out of the guild and the latest recruitment.

Correct way : Guild master, officers and specific members who have roles to see this kind of information must have to see all the information in "Guild info" window.

**Comment by Ironjudgment** [comment]
I am not sure what causes these issues but a simple solution is to use this macro while viewing event log.

`/run GuildEventLog_Update()`

**Comment by Ghostivan** [comment]
Thanks
