### ISSUE TITLE
Trouble holding Aggro as Prot Paladin

### ISSUE THREAD

**Issue by BarmyDwarf** [SunstriderEmu/BugTracker#3268]
Is anybody else having trouble holding aggro?

I have all the talents necessary to be able to hold aggro effectively and it seems that I just can't do enough holy damage with Righteous Fury to keep aggro and the only way I can keep aggro is if pull out all the stops and drain my mana on one group pull.

**Comment by Ironjudgment** [comment]
There doesn't seem to be any issues for paladin tank within our guild. Manages to hold agro and with enough mana is even able to outperform other classes on single mob fights.

**Comment by Rockbiter-shaman** [comment]
in trash pulls, you must use only seal of wisdom and dont ever judge. make sure you have autoattack always enabled, and spam consecration and holy shield. Accept that you will lose the skull and ignore it after it leaves you, assuming it's a mob that doesn't have abnormally high damage or high health. If the mob is too dangerous, stun and/or taunt it. With this method, you will consistently regain mana from seal of wisdom and from being healed, which will leave you free to spam consecration+holy shield, and you should never lose aggro on more than one mob. using damage seals on trash pulls is not necessary, except on things like the UB bog lords.

**Comment by Jerrythemagicdog** [comment]
This doesn't seem like a bug, if you have any evidence of anything being wrong with Paladin threat please open an issue.
