### ISSUE TITLE
Hellfire Peninsula Boar aggro range

### ISSUE THREAD

**Issue by Manderson1992** [SunstriderEmu/BugTracker#3271]
In Hellfire Peninsula the boars outside of Honour Hold carry out a charge attack upon aggroing, this is not supposed to happen at around 50-60 yards. 

This makes questing almost impossible and really ruins the experience.

Please address the range at which they aggro to a normal amount.

**Comment by NeonicSupersonic** [comment]
Its a correct pre-2.1 behavior

**Comment by Sheikthecatman** [comment]
#1915
