### ISSUE TITLE
Jewel of Charismatic Mystique

### ISSUE THREAD

**Issue by LugerTypeA** [SunstriderEmu/BugTracker#3272]
https://wowwiki.fandom.com/wiki/Jewel_of_Charismatic_Mystique
This trinket is supposed you reduce your threat to all enemy targets around you. Instead, it literally pulls all enemies within 30 yards. This is a funny interaction, but it's clearly not how this trinket is supposed to work. Can't use it for its intended purposes.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
