### ISSUE TITLE
Lurker in SSC dropping double librams

### ISSUE THREAD

**Issue by europoor** [SunstriderEmu/BugTracker#3274]
This should only be possible with TIER tokens. Every other piece of boss loot in WoW works like this. There are 2 categories when it comes to loot, Armor pieces (trinkets included) and weapon slot pieces (librams/idols/ranged weapons and melee weapons). A boss should NEVER be able to drop 2 items from the same category unless its a TIER token.

I know wow is a complicated game so im just trying to help you guys you make the server blizzlike, thanks.

**Comment by Skuzzlez** [comment]
Our guild also had 2x trinkets from Lurker on our first kill, and 2x Resto shaman bracers on our first kill of Hydross. This isn't exclusive to Lurker, it seems.

**Comment by NeonicSupersonic** [comment]
All t5 bosses have fucked up loot tables with a potential to drop same two items where it possible.

**Comment by Jerrythemagicdog** [comment]
Not a bug here, bosses during TBC had a chance to drop two of the same item.
