### ISSUE TITLE
Bijou in LBRS gives the Alliance version of her quest to both factions

### ISSUE THREAD

**Issue by steak-house** [SunstriderEmu/BugTracker#3276]
**To Reproduce**
1. As a horde player, take quest Bijou's belongings and complete it.
2. The followup asks you to talk to an Alliance NPC, Marshall Maxwell

NPC : https://classic.wowhead.com/npc=10257/bijou

**Expected behavior**
Bijou should give the Horde version of Bijou's belongings to Horde players : https://classic.wowhead.com/quest=4982/bijous-belongings

**Comment by Sheikthecatman** [comment]
Thanks!
Fixed in [56b5c72770b9e0f8d77615ae33e2d618152f01ff](https://github.com/kelno/sunstrider-scripts/commit/56b5c72770b9e0f8d77615ae33e2d618152f01ff)
