### ISSUE TITLE
99% of Gold after Logout gone

### ISSUE THREAD

**Issue by Papastiffey** [SunstriderEmu/BugTracker#3277]
Hello,

after I logged in today at 8.30 i received some mails from auction house which I captured. After using HS to Shat I lost 99% of my Gold, nothing left in my Bags or on the whole server. In numbers:

Gold before HS: 123 g 23 s
Gold after HS: 16s 15kc
Afterwards logout and login again after like 10 min.

What happened? Can you check the log because I have no screen or something because i didnt expect something like this to happen.
Please contact me ingame: Papastiffi - or via my Account Papastiffey

Thanks in advance,

**Comment by Simon-GM** [comment]
This should be submitted in an ingame ticket.
