### ISSUE TITLE
Spawn time

### ISSUE THREAD

**Issue by Sveskesovs** [SunstriderEmu/BugTracker#3278]
**Describe the bug**
Nobody is really addressing the spawn time. I die all the time because of very high spawn time. 

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by steak-house** [comment]
everyone complains about it please change it to retail values it makes some quests nigh-impossible

**Comment by kelno** [comment]
I've reduced the respawn time scaling a bit not that the wave of people leveling receded a bit.
