### ISSUE TITLE
Friends Tab Messed

### ISSUE THREAD

**Issue by pavanmu** [SunstriderEmu/BugTracker#3279]
This happened a few weeks back after a update i suppose....The online friends are not shown at the top and are scattered randomly . At first i tought it was everybody's issue and dint bother...But few days back came to know its happened only to me.
Opened a ingame ticket and got a reply saying i should report it here.
![WoWScrnShot_050820_152010](https://user-images.githubusercontent.com/65016294/81395042-927fb980-9140-11ea-9fad-08c79b6398dc.jpg)
![WoWScrnShot_050820_152016](https://user-images.githubusercontent.com/65016294/81395049-957aaa00-9140-11ea-8c7e-691a6fff14c7.jpg)

**Comment by Smashyxgod** [comment]
happens to me aswell , it's not from addons , it's a bug i think . trying delete cache didn't work but now it works fine for the momment.

**Comment by pavanmu** [comment]
Ok will try deleting cache

**Comment by pavanmu** [comment]
Like you said....Deleting cache doesnt work.

**Comment by kelno** [comment]
Seemingly fixed with ef58f8ed01574813f6cf0a25e7641ab8ee5b1d68
