### ISSUE TITLE
[NPC]The Ancients in Felwood

### ISSUE THREAD

**Issue by Ironjudgment** [SunstriderEmu/BugTracker#3281]
**Describe the bug**
NPCs named Hastat the Ancient, Stoma the Ancient and Vartrus the Ancient do not appear in the game world.

**To Reproduce**
Go to the Irontree Woods in Felwood, there is an island in the middle of the green sludge with a little hill on it, when climbing this hill nothing happens. 

https://tbcdb.com/?quest=7632 -> Quest
https://tbcdb.com/?npc=14524 -> Vartrus the Ancient
https://tbcdb.com/?npc=14526 -> Hastat the Ancient
https://tbcdb.com/?npc=14525 -> Stoma the Ancient

**Expected behavior**
When going up the little hill, these Ancients should appear in ghost form in front of their tree forms.

**Screenshots/videos**
Endless
![image](https://user-images.githubusercontent.com/33090790/81401050-60615e00-9126-11ea-9c73-37b3ab0da765.png)
Live
![image](https://user-images.githubusercontent.com/33090790/81401115-838c0d80-9126-11ea-9c0d-98b9154d3d6d.png)

**Additional context**
https://youtu.be/CDXJgNWm0nA -> Video of them appearing when you climb the little hill.

**Comment by z5n** [comment]
thanks, fixed with next restart
