### ISSUE TITLE
my account ended up in Ban, valid until 2020-05-08 11:57  Ban has expired at the moment, but I can’t log into my account . name account : Davi536

### ISSUE THREAD

**Issue by haffy536** [SunstriderEmu/BugTracker#3282]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by haffy536** [comment]
my account ended up in Ban, valid until 2020-05-08 11:57

Ban has expired at the moment, but I can’t log into my account

**Comment by haffy536** [comment]
my accaunt : Davi536

**Comment by Simon-GM** [comment]
I see that you are online.
