### ISSUE TITLE
Quest Precarious Predicament doesn't work

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#3284]
**Describe the bug**
When you use the shakles on him, he falls and gets up...then nothing happens.

**To Reproduce**
1. Turn in quest Grark Lorkrub
2. Take quest Precarious Predicament
3. Use quest item Thorium Shakles
4. Grark falls to the ground and gets up. 
5. ........... nothing happens. He resumes pacing on spot.

**Expected behavior**
At step 5, he should follow you and start the escort quest.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
