### ISSUE TITLE
Corrupted Night Dragon in Felwood

### ISSUE THREAD

**Issue by SychoticAbby** [SunstriderEmu/BugTracker#3285]
**Describe the bug**
To cleanse the corrupted plants in felwood you must complete a prior quest to get the Cenarion Beacon, after which you can collect Corrupted Soul Shards from mobs that can be turned in to get Cenarion Plant Salve. Turning into x4 Cenarion Plant Salve to the Corrupted Night Dragon "should" cleanse it and allow it to be lootable, dropping 4-5 Night Dragon's Breath. As of right now when turned it, the plant remains corrupted and is unlootable while also using the salve. 

https://classic.wowhead.com/item=11952/night-dragons-breath

**Comment by Sheikthecatman** [comment]
Thanks! All Corrupted Flowers have been fixed in [3a6dac4a1b43db0290e815de6fa27463a2cad9e8](https://github.com/kelno/sunstrider-scripts/commit/3a6dac4a1b43db0290e815de6fa27463a2cad9e8).

The behavior should be corrected, the fix will be live next server restart.
