### ISSUE TITLE
Skinning bug with mobs which drop quest items

### ISSUE THREAD

**Issue by tnikolow23** [SunstriderEmu/BugTracker#3287]
Hello, 

I have problem on my player Ishak. Its kinda loot/skin problem. When a mob drops quest item for a quest, after looting it I am not able to skin it. In case the mob isnt part of the quest, there's no problem at looting and skinning it.

So its just smth like that. I loot the corpse and after that instead of seeing the icon for skin I see the icon for loot and opening the mobs again its empty and still cant skin it.

I attached some photos. 

Have a nice day!
![WoWScrnShot_050820_192929](https://user-images.githubusercontent.com/65033584/81426792-607f4f00-9162-11ea-84e7-71eda88eca7e.jpg)
![WoWScrnShot_050820_192933](https://user-images.githubusercontent.com/65033584/81426803-62e1a900-9162-11ea-9fe0-64de5f5a77a6.jpg)
![WoWScrnShot_050820_192937](https://user-images.githubusercontent.com/65033584/81426810-6412d600-9162-11ea-9766-28b8f5986b9f.jpg)

![WoWScrnShot_050820_192401](https://user-images.githubusercontent.com/65033584/81426767-53626000-9162-11ea-96b9-f43a92f7b56f.jpg)
![WoWScrnShot_050820_192926](https://user-images.githubusercontent.com/65033584/81426786-5bba9b00-9162-11ea-82b2-992fc3e832f9.jpg)

![WoWScrnShot_050820_192352](https://user-images.githubusercontent.com/65033584/81426751-4e051580-9162-11ea-8843-2b0425bad893.jpg)

**Comment by Simon-GM** [comment]
It is now working correctly agian.
