### ISSUE TITLE
Quest [Consult Master Gadrin] is not available

### ISSUE THREAD

**Issue by Dokandree** [SunstriderEmu/BugTracker#3288]
**Describe the bug**

The quest [Consult Master Gadrin] (ID 2935) Cannot be picked up once the pre-requisite is turned in [Undamaged Venom Sac] (ID 2934).

--

**To Reproduce**

1. Begin chain quest with [Venom Bottles] (ID 2933)
2. Get following quest [Undamaged Venom Sac] (ID 2934), complete and turn it in.
3. [Consult Master Gadrin] (ID 2935) should become available once the previous quest is turned in from the same NPC. However, it is not.

Quests: https://wowhead.com?quest=2934
https://wowhead.com?quest=2935

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by InhumanGM** [comment]
Upon following the steps you provided to reproduce the issue, I was not able to find any problems with this. I was able to attain [Consult Master Gadrin] without a problem.
