### ISSUE TITLE
I was a lot of Things

### ISSUE THREAD

**Issue by Gafafaf** [SunstriderEmu/BugTracker#3289]
The shadowmoon tuber mounds that you are supposed to use the whistle (Oronok's boar whistle) at are constantly being used and leaving behind shadowmoon tuber lootable objects behind that do not despawn and cannot be looted. In other words the quest is not possible to do anymore.
This bug must have occured due to a very recent update this week.

Quest: https://www.wowhead.com/quest=10514/i-was-a-lot-of-things
Shadowmoon tuber mounds: https://www.wowhead.com/item=30356/shadowmoon-tuber
shadowmoon tuber that it spawns: https://www.wowhead.com/object=184691/shadowmoon-tuber

Screenshot of multiple non-lootable shadowmoon tuber's:
https://gyazo.com/ed8062ca01f426e6d55cf7dec477bc5a

This quest has been kind of clunky to do in the past but it was do-able with some patience. Hopefully the quest can be reverted to its old state or fixed :) thank you

**Comment by kelno** [comment]
Thanks!
This was due to a very recent bug concerning all quest containers like this one, this has been fixed since
