### ISSUE TITLE
Hellfire Fortifications bug

### ISSUE THREAD

**Issue by Dalarok** [SunstriderEmu/BugTracker#3290]
**Describe the bug**
 I was doing the daily quest Hellfire Fortifications, after it reset, I picked up a new quest, I completed 1 tower obejective and a few hours later completed the remaining two objectives. When the quest showed completed, I returned to the NPC to hand it in, but the quest giver acted as though I had not completed the quest. I tried to abandon the quest to re-take it and do the quest again but it would not let me.

**To Reproduce**

1. Accept Hellfire Fortifications daily quest
2. Try and complete the quest objective over a period of time and log ins
3. Attempt to hand in the quest

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=10110/hellfire-fortifications
Spell: https://wowhead.com?spell=

**Expected behavior**

I expected to be able to hand the quest in
**Screenshots/videos**

None available 
**Additional context**

None

**Comment by z5n** [comment]
unable to reproduce
