### ISSUE TITLE
The heart of the mountain quest bugged

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#3291]
**Describe the bug**
The event for obtaining the heart of the mountain is bugged. When entering the vault, all the 4 golems are active with the dwarf and the hound. Killing them all didn't drop heart of the mountain. After opening all the coffers (yes, with 12 keys), nothing heppens.

**To Reproduce**

1. Obtain quest The Heart of the Mountain.
2. Go to BRD the vault area where the coffers are.
3. Kill all the trash in the outer vault.
4. Kill the dwarf, hound and the 4 golems in the inner vault.
5. open up all 12 coffers. nothing happens.

https://classic.wowhead.com/quest=4123/the-heart-of-the-mountain#comments

**Expected behavior**
At step 4, the 4 golems should be inactive. They would activate one by one as you open up the coffers. After killing all 4 golems, the item Heart of the Mountain should be lootable on the ground.

**Comment by Sheikthecatman** [comment]
Thanks! The quest is now doable, the golems become attackable after each coffer is opened. The Secret Door with the Heart ouf the Mountain should open when all golems die.
