### ISSUE TITLE
Creature is not skinnable

### ISSUE THREAD

**Issue by Paun86** [SunstriderEmu/BugTracker#3293]
When you are doing Frostsaber Provisions quest in Winterspring for reputation to get mount, you need to kill 5 bears and 5 chimeras. If you have quest you cant skin them, and as soon as you done quest you can. Please fix this problem.

**Comment by babno** [comment]
This seems to be an issue with all quest mobs. You will always get the loot icon even if there is nothing to loot, and thus cannot skin them.

**Comment by Paun86** [comment]
I did this quest 1 day ago and there was no problem at all. Today its exactly how you describe.

**Comment by Simon-GM** [comment]
Just attempted to reproduce the situation.
It should be working **correctly** again.

Thank you for the report! :-)
