### ISSUE TITLE
Nazgrel's Fervor does not work in Hellfire Citadel

### ISSUE THREAD

**Issue by steak-house** [SunstriderEmu/BugTracker#3294]
**Describe the bug**
Nazgrel's Fervor works correctly in Hellfire Peninsula, but does not affect players in Hellfire Citadel instances. I imagine Trollbane's Command has the same problem.

**To Reproduce**
1. While Nazgrel's Fervor is active, as a Horde player, enter any Hellfire Citadel instance (tested with Ramparts)
2. Observe that you no longer have Nazgrel's Fervor

Spell: https://www.wowhead.com/spell=39913/nazgrels-fervor

**Expected behavior**
Nazgrel's Fervor should be available both in Hellfire Peninsula and the Hellfire Citadel instances

**Comment by kelno** [comment]
Fix unapplied for now, need rework
https://github.com/kelno/sunstrider/commit/b2caa38402458f21b231425c1a22621aa556be34

**Comment by steak-house** [comment]
what does this mean ?

**Comment by kelno** [comment]
That's just dev mumba jumbo, I made a for this but I had to unapply it for now.

**Comment by steak-house** [comment]
Thanks for your work !

**Comment by kelno** [comment]
Fixed with next update
