### ISSUE TITLE
World Boss Spawn (Suggestion)

### ISSUE THREAD

**Issue by dadshers** [SunstriderEmu/BugTracker#3296]
**Describe the bug**
Hope this is the right place to make this suggestion. I asked on Discord and was directed to the bugtracker.

I could be wrong, but the World Bosses (Doom Lord Kazzak and Doomwalker) are currently on a presumed 48-96 hour respawn. There's nothing inherently wrong with the respawn timer, just that the spawn time could or should be adjusted so that both EU & NA guilds have equal opportunities to kill it. Perhaps you have evidence that suggests that # of kills is fairly equal, I don't know. What we have been seeing is a boss like Doomwalker killed during EU prime time the last 3 or so spawns?

My suggestion would be to keep the random spawn timer, but have World Bosses alternate their spawn times after each kill. If the spawn happens to be on a weekend, have it be middle of the day or something, so that there's competition.

If you have better ideas for how these should spawn, I'm all ears, but either way, I feel this should be adjusted.

**To Reproduce**
N/A, not a bug report

**Expected behavior**
N/A

**Screenshots/videos**
N/A

**Additional context**
N/A

**Comment by NeonicSupersonic** [comment]
Yeah and 3/4/5 dw spawns were all literally 3-5am eu time
Game aint fair, deal with it

**Comment by dadshers** [comment]
I mean, that's literally my point. Spawns should be alternated so that they aren't happening at inopportune times, several spawns in a row.

This has happened to both EU and NA guilds. This isn't me pointing the finger at EU or NA and saying that one has the advantage over the other.
