### ISSUE TITLE
Hunter PK'ing from Illegal Position in Cenarion Refuge

### ISSUE THREAD

**Issue by blueberries1** [SunstriderEmu/BugTracker#3297]
> This hunter is sniping me from a tower where the guards cannot attack her, and camping my location in Cenarion Refuge, this is against terms of service and is anti-fun.
![Abusing Location](https://user-images.githubusercontent.com/31331370/81464997-bb756e00-9183-11ea-8e33-d6a10a9fe7ce.PNG)

**Comment by kelno** [comment]
Thanks, fixed with next server update
