### ISSUE TITLE
Can't level up lockpicking skills

### ISSUE THREAD

**Issue by JacoZwarts** [SunstriderEmu/BugTracker#3298]
**Describe the bug**
Can't level up lock picking skills when opening Practice Lock boxes at Alter's Mill. Require lock picking level to be high enough to lock pick poison quest for rogue.

**To Reproduce**
1. Cast Pick lock on Practice lock box.

**Expected behavior**
Lock picking skill should increase, once a lock box is opened it should re-spawn.

**Comment by vadawd** [comment]
I have also encountered this problem. The boxes in The Barrens do not work either.

**Comment by JacoZwarts** [comment]
Fixed after last update.
