### ISSUE TITLE
Mage's Blink spell

### ISSUE THREAD

**Issue by lolproxoxo** [SunstriderEmu/BugTracker#3299]
Hello, there is an issue with a mage Blink spell.
It has to move mage to the ground w/o falling damage when u use it in air. but it attached to the nearest terrain objects, like on the screenshot.
Another problem is a blink have a shorter distance when obstacles or bumps occur, that have to be passed with blink.
![WoWScrnShot_050920_133028](https://user-images.githubusercontent.com/45545402/81471497-219cd800-91fa-11ea-9095-91583c967637.jpg)

**Comment by Simon-GM** [comment]
Hello Lolproxoxo! Thank you for the issue report!

It is correct, that the mage spell '[Blink](https://classic.wowhead.com/spell=1953/blink)' can be used to avoid fall damage if timed correctly.
However, it should **not** 'port' you to the ground, when used mid-air.

_Wowwiki quote:_
> The line of sight calculations experience severe problems when leaving or entering buildings, caves, and bridges, or even when passing a change in terrain texture. This can result in Blink moving you a much shorter distance than it should, or not moving you at all.

I think that is what you mean, when mentioning the part with obstacles or bumps.

Am I missing your point?

**Comment by Simon-GM** [comment]
Closing issue due to no further steps to follow.
