### ISSUE TITLE
Sunseeker Netherbinder in Mechanar

### ISSUE THREAD

**Issue by sifiuocz** [SunstriderEmu/BugTracker#3301]
**Describe the bug**

Sunseeker Netherbinder (https://www.wowhead.com/npc=20059/) summons two Arcane servants (https://www.wowhead.com/npc=20478/)  multiple times.

**To Reproduce**

1. Go into Mechanar normal
2. pull the first humanoid pack on the left
3. observer Sunseeker Netherbinder summon more than 2 adds

**Expected behavior**
 Netherbinder should only summon these adds once resulting in two adds. There should never be more than 2 adds from a singular Netherbinder at the same time.

**Screenshots/videos**

**Additional context**

comment in https://www.wowhead.com/npc=20478/arcane-servant#comments says Netherbinder summons two, not more than two of those adds.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
