### ISSUE TITLE
Mailbox Disfunction

### ISSUE THREAD

**Issue by Maxipayne** [SunstriderEmu/BugTracker#3302]
**Describe the bug**

When you buy a stack of food off the auction house and take it out of the mailbox some of the items in the stack will be missing this has happened to me twice now.
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Simon-GM** [comment]
I have attempted to reproduce it, by the little information you've provided in your report.
That did not work.

Do you have any more information for me, that would be useful, in the process of reproducing the situation? _(name of item, amount bought, amount received, auction addons used etc.)_
