### ISSUE TITLE
Improved kidney shot does not work properly

### ISSUE THREAD

**Issue by Jyudo** [SunstriderEmu/BugTracker#3304]
**Describe the bug**
Improved Kidney Shot doesn't deal extra damage to the target.

**To Reproduce**
1. Kidney Shot with talent "Improved Kidney Shot" on target X
2. During the stun, there's no additional 3/6/9% damage to the target with talent.

https://classic.wowhead.com/spell=14176/improved-kidney-shot

**Expected behavior**
While affected by Kidney Shot ability, the target receives an additional 3/6/9% damage from all sources.

**To add**
I've tested it on training dummy. That's why there's no single mut rogue at this server. They are useless without this talent not working.

**Comment by Jerrythemagicdog** [comment]
Tested on a player in a duel: 
![image](https://user-images.githubusercontent.com/46463908/82616242-9392fb00-9bc4-11ea-84a4-461d177afeb3.png)

178 damage Sinister Strike without Kidney Shot
194 damage Sinister Strike after Kidney Shot is applied with the talent (9% more).
