### ISSUE TITLE
 [Goblin Transponder]

### ISSUE THREAD

**Issue by shockpullan** [SunstriderEmu/BugTracker#3306]
**Describe the bug**

 [Goblin Transponder] dont teleport you to gnomer
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

 [Goblin Transponder] should teleport you at the entrence of gnomer and then use  [Goblin Transponder] to get back to BB
**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, the fix was deployed a few days ago.
