### ISSUE TITLE
Feral druid clearcasting bug?

### ISSUE THREAD

**Issue by max3hand** [SunstriderEmu/BugTracker#3307]
Hallo, there is one thing that feels pretty wierd to me.
While i have clearcasting buff and cast  [Ferocious Bite] it consumes all my energy and also the clearcasting buff. It cant be right imo 🙏  it should probably consume energy because of dmg scale and keep up the clearcasting buff.
thanks for any reply

**Comment by Jerrythemagicdog** [comment]
https://www.reddit.com/r/classicwow/comments/d9abzt/omen_of_clarity_bug/

> "Ferocious Bite costs 35 energy which is what clearcasting will pay for. Part of ferocious bite's effect is that it will burn up whatever energy you have left to deal additional damage."

**Comment by Loitta** [comment]
You are wrong. @Jerrythemagicdog there's no "additional damage".

**Comment by max3hand** [comment]
That means it should not burn clearcasting, right?

st 10. 3. 2021 v 15:17 odesílatel Loitta ***@***.***> napsal:
