### ISSUE TITLE
[Item] [Spell] Druid PvP idols doesnt increase Lifebloom

### ISSUE THREAD

**Issue by pakon3** [SunstriderEmu/BugTracker#3308]
**Describe the bug**
Druid's PVP idol - Gladiator's Idol of Tenacity do nothing.
I think that problem will be same for S2, S3, S4 idols (can´t test since it is season 1)

**To Reproduce**
Equip idol, cast Lifebloom final tick is the same like without the idol.

Item: https://tbc-twinhead.twinstar.cz/?item=28355
Spell: https://tbc-twinhead.twinstar.cz/?spell=33763

**Expected behavior**
Lifebloom final tick/heal should be increased.

**Additional context**
It is similar to still open issue: https://github.com/SunstriderEmu/BugTracker/issues/1847
where another idol - Idol of the Emerald Queen should increase only periodical heal and not the final tick.
Please repair. It makes gladiator idol completly useless. It is gamebreaking bug for PVP when u waste arena points on it.

**Comment by Simon-GM** [comment]
[Click here](https://www.youtube.com/watch?v=dldO7JA_HsQ) to see video of reproduction.

**Comment by kelno** [comment]
Thanks, fixed with next server update
