### ISSUE TITLE
Cabal Ritualist staff users use Gouge

### ISSUE THREAD

**Issue by TheRealZaroua** [SunstriderEmu/BugTracker#3309]
Cabal Ritualist in Shadow Labyrinth are using Gouge inappropriately. There are 4 different types of Cabal Ritualists: fire caster that uses Fireball and Flame Buffet, arcane caster that uses Arcane Missiles and Addle Humanoid, frost caster that uses Frost Bolt and Frost Nova, and melee that dual wields daggers and uses Gouge. Only the melee Cabal Ritualist are supposed to use Gouge, but right now the 3 caster types are also using it.

Steps to reproduce:
Fight Cabal Ritualist that uses a staff and it will cast Gouge frequently

What should happen:
Cabal Ritualist that use staves should either use fire spells, OR frost spells, OR arcane spells. Cabal Ritualist that use daggers should only use Gouge, but not cast any spells.

**Comment by NeonicSupersonic** [comment]
Also they able to gouge even if you tank them while facing away and mobs hit you in the back, pretty ebin 10/10 interaction.

**Comment by Sheikthecatman** [comment]
Thanks, fixed in [a12f419d264f24c885b02fd73fa811004b9dcfb4](https://github.com/kelno/sunstrider-scripts/commit/a12f419d264f24c885b02fd73fa811004b9dcfb4)
