### ISSUE TITLE
Combustion < GAME BREAKING BUG

### ISSUE THREAD

**Issue by bugmaster01** [SunstriderEmu/BugTracker#3310]
if mage uses Combustion and stacks it few times and gets someone to dispell it from him the criticals stay up on the target resoulting in a mage having 70+ % crit on his spells. 

This is a serious bug since evryone can replicate it ez:

All you do is you stack it up and get a shaman to purge, or hunter to arcane shot or priest to dispell
and you get the stacks permanent. 
Resoults in a mage being the moust op class on this server since they can do 2k demage with d3 gear.

**Comment by blblblaz** [comment]
could not reproduce, maybe I misunderstood or did something wrong, https://streamable.com/tkukpr - I should have around 74% crit here according to what you described but as you can see it's clearly not the case, need some more information if possible

**Comment by bugmaster01** [comment]
give your self a buff then dispell it 2 times and you will have it permanently try dpsing then again with mage and you will see your Buff does not fell off

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
