### ISSUE TITLE
[Quest] The Ruins of Stardust

### ISSUE THREAD

**Issue by Cayman91** [SunstriderEmu/BugTracker#3311]
**Describe the bug**

After collecting 5 Handful of Stardust, the quest shows as completed in quest log but when you approach the NPC the question mark is still on gray and you are unable to return the quest.

**To Reproduce**

1. Collect 5 items of Handful of Stardust
2. Return to quest npc.

Item: https://tbcdb.com/?item=5494 / https://classic.wowhead.com/item=5494/handful-of-stardust
Quest: https://tbcdb.com/?quest=1034 / https://classic.wowhead.com/quest=1034/the-ruins-of-stardust

**Expected behavior**

After collecting the quest item you have to return it to npc and finish the quest.

**Screenshots/videos**
https://i.postimg.cc/X71c1Hmm/Wo-WScrn-Shot-051020-205008.jpg
https://i.postimg.cc/zGLwsw1B/Wo-WScrn-Shot-051020-205023.jpg

**Additional context**

N/A

**Comment by Sheikthecatman** [comment]
![image](https://user-images.githubusercontent.com/59149613/81982066-7d6bc480-9631-11ea-8af2-33d58e077e43.png)

Worked for me on a local server, it might be cache related. If it's not cache related create a ticket in-game.

**Comment by InhumanGM** [comment]
Unable to reproduce.
