### ISSUE TITLE
Warlock fear breaks too easily (pve)

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3312]
I'm leveling still, currently 54, but i've noticed that fear breaks extremely easily. With just dots and doing nothing else it will almost always break within 5 seconds. I don't think I've ever seen fear last its full duration. Dot damage should have a very low chance to break fear, it's direct damage that has a large chance to break fear. I suspect that the high chance for direct damage is erroneously being used for dot damage.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2539
