### ISSUE TITLE
Druid's aura Track humanoids with ing goggles

### ISSUE THREAD

**Issue by Macumbafeh** [SunstriderEmu/BugTracker#3314]
**Describe the bug**
When you go cat form and have ing goggles (Deathblow X11 Goggles) it remove everytime Track humanoids Aura and you have to activate it manually everytime...

**To Reproduce**

1. Go cat form without ing goggles and turn on Track humanoids aura
2.  Remove form and back in cat form you will see the aura stay.
3. Equip ing goggles and go in cat form.
4. Turn on Track humanoids aura
5. Remove form and back in cat form you will see the aura is always removed

Item: https://www.wowhead.com/item=32478/deathblow-x11-goggles
Spell: https://classic.wowhead.com/spell=19883/track-humanoids

**Expected behavior**!
When you go cat form and have ing goggles (Deathblow X11 Goggles) it don't have to remove Track humanoids Aura everytime you shapeshift.

**Comment by InhumanGM** [comment]
I'm confused as to what the issue is. The [Track Humanoids](https://tbc-twinhead.twinstar.cz/?spell=5225) _should_ be removed automatically when exiting [Cat Form](https://tbc-twinhead.twinstar.cz/?spell=768), and based on my testing, the [[Deathblow X11 Goggles]](https://tbc-twinhead.twinstar.cz/?item=32478) seem to have no effect on this. Could you provide more information that could be used to try to reproduce the issue again?

**Comment by Macumbafeh** [comment]
Yes.
If i have the goggles, everytime i cast cat form, i have to cast Track Humanoids again and again if i go human form and back to cat form.

It's not about when i leave cat form. It's about when i gain cat form : Track Humanoids don't have to be removed and the [Deathblow X11 Goggles] seem to have effect on this.

**Comment by InhumanGM** [comment]
So you're saying that when you enter Cat Form with the goggles on, Track Humanoids doesn't automatically turn on?

**Comment by Macumbafeh** [comment]
Yes that's it !

**Comment by InhumanGM** [comment]
I didn’t experience that issue when I was testing, Track Humanoids was enabled automatically as it should.

**Comment by Macumbafeh** [comment]
With goggles equipped?

I will make a video then, to show you.

**Comment by Macumbafeh** [comment]
Here it is. 
https://www.youtube.com/watch?v=DY3_aa2E8Uc

It freezed a bit at beginning ^^' but you can see, without goggles, there is no problem. With goggles i have to activate it everytime. (And it's engGB client)

**Comment by beraus** [comment]
Any update on this issue? Is it working as it should now?

**Comment by Macumbafeh** [comment]
It seems not. Same issue, or if you made an update few days ago i'll try again

**Comment by artieau** [comment]
Should it even turn track humanoids on?
The goggles have their own tracking on the item itself, so that becomes your tracking when you leave cat form in the first instance.
It wont change until you cast a new tracking, right?

**Comment by Macumbafeh** [comment]
Nop even if i track humanoid, i Can track cloud via goggles also. So it make no sense to not keep humanoid track spell when i go in cat form

**Comment by Macumbafeh** [comment]
i give you an example here : I can track water cloud, and when i go in cat form and activate Track Humanoids spells, i still can track water cloud. So why Track Humanoids is not automatically activated?
![cloud 1](https://user-images.githubusercontent.com/47739411/92606539-578abf80-f2b3-11ea-8945-50d8e6076069.jpg)
![cloud 2](https://user-images.githubusercontent.com/47739411/92606552-5b1e4680-f2b3-11ea-9ed2-14d074c76b97.jpg)
![cloud 3](https://user-images.githubusercontent.com/47739411/92606565-5e193700-f2b3-11ea-8dca-1f5a32148e1a.jpg)

**Comment by Macumbafeh** [comment]
Up, this bug is still here.... and annoying

**Comment by z5n** [comment]
issue has since been fixed
