### ISSUE TITLE
Crystalweave Bracers

### ISSUE THREAD

**Issue by Emotap** [SunstriderEmu/BugTracker#3315]
I have been using said bracers for over a week now and when i log on today I got them back in my mail saying there was an issue equipping them. When I try to use them it says requires lvl 71

**Comment by mechanicsTBC** [comment]
These should not have been in the game yet.  Should only be available when ogrila dailies are released.  I assume they were available beforehand, then removed when it was brought to the devs attention.  The level 71 requirement is just a quick fix to make them unusable for people who have them already.

**Comment by InhumanGM** [comment]
> These should not have been in the game yet. Should only be available when ogrila dailies are released. I assume they were available beforehand, then removed when it was brought to the devs attention. The level 71 requirement is just a quick fix to make them unusable for people who have them already.

This is correct. This item was not supposed to be in the game, thus the level requirement was increased to prevent people from using it.
