### ISSUE TITLE
Can't recover Archmage Vargoth's Staff

### ISSUE THREAD

**Issue by LugerTypeA** [SunstriderEmu/BugTracker#3316]
If you lose https://www.wowhead.com/item=28455 mid-chain, you should be able to get a new one from Ravandwyr in Area 52. I somehow lost mine before completing the chain, but Ravandwyr doesn't offer me the recovery for the staff, thus I cannot complete the quest chain.
![WoWScrnShot_051120_083208](https://user-images.githubusercontent.com/64495843/81527234-6a6fa080-9362-11ea-932e-8eb404c8bacb.jpg)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update, let usknow if you get the chance!
