### ISSUE TITLE
Incandescent Fel Spark

### ISSUE THREAD

**Issue by Denagul** [SunstriderEmu/BugTracker#3317]
**Describe the bug**
These Elementals have a limited loot table unlike most creatures

**To Reproduce**
1. Kill 100-1000 elementals (alternatively, just spawn 100-1000 loot tables)
2. Should find 0 uncommon/rare world drop items

Creature: https://db.endless.gg/?npc=22323

**Expected behavior**
Eventually we should have some greens/blues drop from them, but I suspect it doesn't exist in their loot table yet.

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/60157396/81529650-2190fb00-9314-11ea-8b45-b79adddd3d96.png)

**Additional context**
Is this intended? Your database at least says it should have greens/blues drop from them. Possibly all other outland elementals are affected as well.

**Comment by Simon-GM** [comment]
Might be correct.
However the droprate is supposed to be really low.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
