### ISSUE TITLE
[Quest] "Ethereum Prisoner I.D. Catalogue" is not in the game

### ISSUE THREAD

**Issue by blumepo** [SunstriderEmu/BugTracker#3319]
**Describe the bug**
The quest to turn in [Ethereum Prisoner I.D. Tag] repeatedly, "Ethereum Prisoner I.D. Catalogue" given by Commander Ameer is not currently in the game. Since both the quest and the tags were added in 2.1, and you are currently able to obtain the tags by unlocking the prisons, it would make sense for us to be able to turn them in for rep.

**To Reproduce**
1. Finish all Ethereum quests in the Netherstorm.
2. Use looted keys to free prisoners, loot tags.
3. Feel bummed because you cant use the tags for their intended purpose :(

Item: https://www.wowhead.com/item=31957/ethereum-prisoner-i-d-tag
https://www.wowhead.com/quest=10972/ethereum-prisoner-i-d-catalogue
https://www.wowhead.com/quest=10971/ethereum-secrets

**Comment by InhumanGM** [comment]
> The quest will be available when patch 2.1 hits. 

Originally posted by: _SUN-Leekie_ - [Link to comment](https://github.com/SunstriderEmu/BugTracker/issues/2052#issuecomment-594994157)
