### ISSUE TITLE
Idol of the Raven Goddess is not working properly

### ISSUE THREAD

**Issue by Valdix** [SunstriderEmu/BugTracker#3321]
**Describe the bug**
Idol of the Raven Goddess is not working properly, it doesn't give you an extra healing done buff to your Tree of Life aura (I'm assuming it is the same for Moonkin aura and Leader of the Pack aura, didn't test it however).

**To Reproduce**
1. Cast Rejuvenation/Lifebloom/Regrowth on target affected by Tree of Life aura without Idol of the Raven Goddess
2. Cast Rejuvenation/Lifebloom/Regrowth on target affected by Tree of Life aura with Idol of the Raven Goddess
3. Compare the numbers, they are the same with and without the idol equipped

Item: https://www.wowhead.com/item=32387/idol-of-the-raven-goddess
Spell: https://www.wowhead.com/spell=70691/rejuvenation

**Expected behavior**
Idol of the Raven Goddess should increase healing done on the targets affected by Tree of Life aura.
(same for Moonkin and Feral aura)

**Screenshots/videos**
https://prnt.sc/seofu6  -> Healing without the idol
https://prnt.sc/seoggx  -> Healing with the idol

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
