### ISSUE TITLE
Normal blood furnace only giving 1 rep per kill

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3322]
https://imgur.com/a/LyZvhrb

I am friendly btw.

**Comment by bjh368** [comment]
![image](https://user-images.githubusercontent.com/59749446/81705995-f9b6aa00-946f-11ea-8a5e-851ddab6b4ff.png)

**Comment by InhumanGM** [comment]
This is correct. The amount of reputation rewarded per kill should only be 1.
