### ISSUE TITLE
A listing of 7 bugs in UBRS

### ISSUE THREAD

**Issue by steak-house** [SunstriderEmu/BugTracker#3323]
**Describe the bug**

~~1. Sometimes, the runes in the first room don't extinguish after clearing the pack that guards them, forcing the group to reset the instance~~
~~2. Pyroguard Emberseer's jailors don't respawn on a raid wype, so the fight can be done in two tries : one where you kill the jailors, then another where you kill the boss alone, making it trivial.~~
~~3. Eggs in the rookery respawn instantly, meaning they'll spawn an infinity of dragon babies. We had to get a GM to port us to skip that part, thank god they were online.~~
4. Solakar Flamewreath is present when entering the Rookery. He should spawn at the end of an add rush after clicking the Father Flame item present in the Rookery.
5. The Arena restarts after clearing it. The door correctly opens however, so we were able to run away from it. Also Rend Blackhand doesn't disapear from the balcony when he spawns in the arena so there are 2 Rend Blackhands in the instance while he's being fought and present on the balcony.
~~6. Rend Blackhand's Whirlwind lacks an animation. We had to check our combat logs to figure out what killed our melee.~~
~~7. General Drakkisath's adds, Chromatic Elite Guards, can be pulled seperately from him by pulling another mob at just the right distance : close enough to the Elite Guard, yet far enough from Drakkisath that only the Elite Guard will aggro.~~

**To Reproduce**
 
1. Not sure what causes this, but someone on global confirmed the bug and told us to reset the instance. This did not occur on any of the 7 runes the second run.
2. Kill Pyroguard Emberseer's jailors then interrupt the fight (wype, vanish ...). Jailors don't respawn
3. Hatch an egg. Stay close to it. Watch it hatch again. Repeat.
4. Enter the Rookery. Observe that boss is present.
5. Clear the arena. Get close to the gate where the mobs spawn from. Notice that dialogue starts again. This might need a few minutes before triggering again.
6. Engage Rend Blackhand at the end of the arena. Observe that when he whirls, he stays in his auto-attack animation.
7. Pull one of the mobs closest to a Chromatic Elite Guard in Drakkisath's chamber. Observe that the Elite Guard "assist aggros", but not Drakkisath.

2. boss is https://classic.wowhead.com/npc=9816/pyroguard-emberseer the add is https://classic.wowhead.com/npc=10316/blackhand-incarcerator
3. https://classic.wowhead.com/spell=15745/summon-rookery-whelp is the spell that summons the whelp, not sure if it should destroy the egg as well or if that's handled elsewhere. Wowhead doesn't have IDs for doodads such as the eggs, unfortunately.
4. https://classic.wowhead.com/npc=10264/solakar-flamewreath
6. https://classic.wowhead.com/npc=10429/warchief-rend-blackhand
7. https://classic.wowhead.com/npc=10814/chromatic-elite-guard are the adds, https://classic.wowhead.com/npc=10363/general-drakkisath is the boss they should be linked to

**Expected behavior**
1. When a pack of orcs is cleared, Rune should always extinguish. A fix to the bug would be to check on orc deaths if enough have been killed to open the door, rather than checking for rune extinguishes.
2. Blackrock Incarcerators should respawn, and Pyroguard Emberseer should be unattackable, upon raid wype.
3. When a dragon spawns, egg should disapear.
4. Solakar flamewreath should appear at the end of the Father Flame rookery event : clicking the Father Flame object should cause an add rush, at the end of which Solakar Flamewreath spawns.
5. Once arena is cleared (ie Rend Blackhand dies), the event should no longer be able to be triggered.
6. Rend Blackhand should use the whirlwind animation when whirling, like Herod does in Scarlet Monastery.
7. When a Chromatic Elite Guard is aggroed, Drakkisath and the second Chromatic Elite Guard should also aggro. Likewise, when Drakkisath is aggroed, the two Chromatic Elite Guards should always aggro with him

**Comment by Sheikthecatman** [comment]
#2 fixed in [afbc8be29f8f772cc76ca4ce2c0bd0bf1e4c2e51](https://github.com/kelno/sunstrider-scripts/commit/afbc8be29f8f772cc76ca4ce2c0bd0bf1e4c2e51)

**Comment by Sheikthecatman** [comment]
1 and 5 are supposedly rare occurances and I would need steps on how to reproduce these.

**Comment by Sheikthecatman** [comment]
**6** fixed in [c4f5ebc329f24635f78eafafc84ce8fccafb3afe](https://github.com/kelno/sunstrider-scripts/commit/c4f5ebc329f24635f78eafafc84ce8fccafb3afe)

**Comment by steak-house** [comment]
I can't see the links to the commits, but just to be clear these bugs were all observed yesterday.

1 I can't provide sufficient steps. We just go to the door, noticed it wasn't opening, and saw that one of the runes was still glimmering.

5 happened to us twice in a single run so I definitely wouldn't call it rare. 
The first time, we pulled a pack in the room directly after the arena, right after clearing it, and brought them into the arena to have better visibility. This triggered the arena event and led to a wipe (because we hadn't noticed it and the adds rushed our healer who was in the back, ie closest to the adds gate), but be dove into the following room so that our DI allowed us to res outside the arena. 
The second time was after a full-on wipe on Drakkisath which forced us to corpse run. When we got to the arena balconies, right before jumping in it which would normally trigger the arena event, we all coordinated to jump as close to the wall as possible (so we arrived from the west, and jumped to the south), and hugged the wall as closely as possible. The event still triggered and the first wave of adds followed us to Drakkisath's room, where we cleared them, and we weren't attacked by additional waves after that.

I also forgot to mention an additional issue, but am not sure if it's a bug : in most raids, trash mobs stop respawning once you kill the boss that is after them. That wasn't our case, as mobs kept respawning on our way to the Beast Den to attempt Valthalak after we downed Drakki.

**Comment by steak-house** [comment]
And a last issue which I also don't know if it's a bug : 
~~9. Drakkisath's Chromatic Elite Guards don't respawn on a wipe so he can be attempted in multiple attempts of lowering difficulty : kill guards, wipe, attempt Drakki without his guards (removes a mortal strike which is a huge difference)~~

**Comment by Sheikthecatman** [comment]
**7** and **9** fixed in [419b63bdfa4149773ca8765c2fdc5728fba0015b](https://github.com/kelno/sunstrider-scripts/commit/419b63bdfa4149773ca8765c2fdc5728fba0015b)

**Comment by Sheikthecatman** [comment]
**1** fixed in commit [7672c05f695d2495383eb611d4a09807d06a0692](https://github.com/kelno/sunstrider/commit/7672c05f695d2495383eb611d4a09807d06a0692). Issue was that the mobs wouldn't reset/evade properly. Live next server restart

**Comment by steak-house** [comment]
Any news on #3 ?

**Comment by Sheikthecatman** [comment]
3 was fixed a couple of months ago, however no commit was pushed that updated this issue.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
