### ISSUE TITLE
The Dukes and windstones are bugged in sillithus

### ISSUE THREAD

**Issue by xxfortnitexd** [SunstriderEmu/BugTracker#3324]
So In Sillithus im trying to farm wrath of cenarius.  And in order to do that i need to summon the templar and elementals from the wind stones by farming the twilight 3/3 set. Normally they give a buff and you can talk to the windstone and yo ucan summon it. here they dont give oyu the buff and you cant summon the dukes or the elementals even when you have the 3/3 set on. Hope this gets fixed fast i really want the ring .

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3346
