### ISSUE TITLE
Alliance guards at honor point don't attack horde

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3325]
https://imgur.com/a/aRcxgHj

The NPCs which are all alliance flagged and should agro to the horde are
honor hold scout
field marshal brock
gryphoneer leafbeard

**Comment by InhumanGM** [comment]
**Expected Behavior:**
The guards should attack players of the opposite faction.

**Comment by Jerrythemagicdog** [comment]
Looks to be intended judging by the factions.
