### ISSUE TITLE
Auction House is charging a deposit for items with no deposit

### ISSUE THREAD

**Issue by Navashed** [SunstriderEmu/BugTracker#3328]
Items with no vendor price (i.e. enchanting mats) are supposed to require no deposit at the auction house. See image below:
https://i.gyazo.com/e306b3814b23ff80286c581c99741bf8.png

Where it says "deposit" is correctly blank. However, when you create the auction it charges you a hidden 1 silver deposit anyway.

**To Reproduce**
1. Post an auction of enchanting mats
2. Observe blank deposit field
3. Watch your money go down when you post the auction

**Comment by mr-krustev** [comment]
Can confirm this is true.

**Comment by InhumanGM** [comment]
Video of Issue:
https://www.youtube.com/watch?v=Vb1kgOb3Ww0

**Comment by kelno** [comment]
Thanks, fixed with next update
