### ISSUE TITLE
Scryers Hostile

### ISSUE THREAD

**Issue by Smitty44445** [SunstriderEmu/BugTracker#3329]
*i completed the first quest for the scryers to kill the basilisks and it gave me Aldor rep and made me hostile with the Scryers

**Comment by Simon-GM** [comment]
I have attempted to complete '[Voren'thal's Visions](https://www.wowhead.com/quest=10024/vorenthals-visions)', but it worked as intended.
![bug3329](https://user-images.githubusercontent.com/61908478/81617257-63d63d00-93e5-11ea-97ea-5794f589e55b.png)

The little information you are providing, in your report, does not give me many guidelines of how to reproduce the situation.

Do you have anything else to add, in order for me to attempt the reproduction again?
