### ISSUE TITLE
ARENA ISSUE: All Diminishing Returns on CC have incorrect timer

### ISSUE THREAD

**Issue by Navashed** [SunstriderEmu/BugTracker#3330]
The timer on diminishing returns for all CC categories in PvP is supposed to be 15 seconds from the end of the CC. After testing, it is observed to be 18 seconds. This is very disruptive to high-level arena play.

**To Reproduce**
1. Duel someone
2. Cast any CC (I tested with kidney shot, cheap shot, mind control, but you can test with Fear or Polymorph)
3. Wait 15 seconds from the end of the CC
4. Cast it again
5. Observe that diminishing returns have reduced the duration by half even though you have waited the full 15 seconds for DRs to reset

You can test again, this time waiting 18 seconds, and see the spell is not affected by diminishing returns.

**Comment by Jerrythemagicdog** [comment]
Thanks. Retail timer was random (15-21 sec if I recall correctly). We decided to go for static 18 seconds rather than a random value.

**Comment by Navashed** [comment]
Retail TBC DR timer was absolutely NOT random.

**Comment by Navashed** [comment]
The random DR timer was added at some point after TBC. Earliest mention of a random DR timer is from May 10, 2011 (5 months in Cataclysm) when it was added to wowwiki by user "TheDesertDragon."
May 10 before the edit: https://wowwiki.fandom.com/wiki/Diminishing_returns?oldid=2496168
May 10 after the edit: https://wowwiki.fandom.com/wiki/Diminishing_returns?oldid=2496239
Removed in 2015 in patch 6.1: https://blue.mmo-champion.com/topic/425259-recent-cc-diminishing-returns-changes/

You can watch this entire video from TBC (Neilyo 14) and see there is no DR on anything after 15 sec (Cyclone, Roots, Kidney Shot, Mace Stun, Intercept all being spammed): https://www.youtube.com/watch?v=fT_aZfg9AP0

I will provide some timestamps using video editor to see exact frame. Note this is from the moment the buffs appear/disappear, so **the Rogue's considerable latency is included in these times**.

Mace Stun at 23:56 (full); wears off at 23:59.271
Mace Stun at 24:14.986 **(full)**; 15.715 seconds

5pt Kidney at 16:59; trinketed at 17:03.022
5pt Kidney **(full)** at 17:19.905; 16.883 seconds

Cheap Shot at 16:45 (full); wears off at 16:49.771 (using video editor to see exact frame)
Bash at 17:04.623 **(DR'd)**; 14.852 seconds

The Rogue is also playing like DR is 15 seconds.
4pt Kidney at 18:19. Kidney Shot has a 20 sec cooldown and a 4pt Kidney lasts 5 seconds. 20-5 = exactly 15.00 seconds, minimum time for DR to reset.
18:39 He is spamming Kidney with 5 combo points so it goes off the instant its cooldown is up (exactly 15.00 seconds since last one ended). He even says so in an on-screen note ("spamming ks.."). If it were true that DRs reset anywhere from 15-20 sec, then he would 100% be fucking his own Kidney with DR here. This is a top player; he would not do that. He knows the DR reset is exactly 15 seconds.
