### ISSUE TITLE
Paladin Precision talent

### ISSUE THREAD

**Issue by gorzsi98** [SunstriderEmu/BugTracker#3332]
The Precision talent (+3% hit rating) in the 2nd row of Protection tree doesn't seem to work at all.

**Comment by Jerrythemagicdog** [comment]
How was this tested?

**Comment by gorzsi98** [comment]
Well, i put 3 points in that talent and it didn't show on the Character
melee stats panel. I could be wrong though, i am not sure if it should show.

Jerrythemagicdog <notifications@github.com> ezt írta (időpont: 2020. máj.
12., K, 14:22):

**Comment by ztkay** [comment]
It's not supposed to. But it works

**Comment by Jerrythemagicdog** [comment]
The added amount of hit will not show up in your character melee stats panel.
