### ISSUE TITLE
The Sacred Flame - Thousand Needles Quest Bug

### ISSUE THREAD

**Issue by carloberd** [SunstriderEmu/BugTracker#3333]
**Describe the bug**
Can't obtain cloven hoof in Sacred flame quest 

**To Reproduce**
Once you obtain the "Filled Etched Phial" from Rau Cliffrunner in Thousand Needles, you have to use it on the ancient brazier in Splithoof Hold. But once you used that phial, it dissapear and if you try to interact again with the brazier an error pops out saying "Requires Filled Etched Phial". 
I tried two times, abandoning and restarting the quest but i've got the same result both time.
1. Interact with Ancient Brazier
2. Doing so, use the Filled Etched Phial
3. Can't interact again to get Cloven Hoof 'cause i don't have Filled Etched Phial

Object: https://wowhead.com/object=20807/ancient-brazier
Item: https://wowhead.com?item=5868/filled-etched-phial
Item: https://classic.wowhead.com/item=5869/cloven-hoof
Quest: https://wowhead.com?quest=1197/the-sacred-flame

**Expected behavior**
Interaction 1: use phial on brazier.
Interaction 2: obtain Cloven Hoof from brazier

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in [8932b4d4f98ad335aa7e000bb54e82c28ee92b0f](https://github.com/kelno/sunstrider/commit/8932b4d4f98ad335aa7e000bb54e82c28ee92b0f)
