### ISSUE TITLE
Stealth does not work as intended

### ISSUE THREAD

**Issue by laxplr10** [SunstriderEmu/BugTracker#3334]
**Describe the bug**
Literally as the title says - @ Level 65 while questing I first started to notice issues - I would be ~5 yds away from a mob 2 levels below me (63) - it would target, aggro & pull me out of stealth - Which should **NEVER EVER** happen unless I am standing on top of the mob, especially if I am higher level than said mob.

Now I am level 70 - running SHH (N) - Level 70 mobs. While being ~5 yds away from mobs I can not get close enough to a NPC to sap without them turning in my direction and aggroing - Again should not be happening 

While AFK and **IN STEALTH** in Netherstorm - Manaforge blood elves are targeting me 5+ yards away while in stealth - This is unfathomable to come back and be dead.

**To Reproduce**

1. Literally, play a rogue.
2. 
3. 

**Expected behavior**
Mobs not targeting me while in stealth.

**Screenshots/videos**
Not necessary - All you need to do is play a rogue, stealth and go try to attack a mob without it targeting you first and it pulling you out of stealth. 

**Additional context**
I have played rogue for over 7 years - Stealth effectiveness is not correct - The mobs are acting as if I am not in stealth

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3418
