### ISSUE TITLE
[Serpentshrine Cavern][Vashj'ir Honor Guard][Spell]

### ISSUE THREAD

**Issue by mechanicsTBC** [SunstriderEmu/BugTracker#3339]
https://db.endless.gg/?npc=21218
NPC is missing Frightening Shout ability.  Should cast once when the NPC reaches 40% HP.

https://wow.allakhazam.com/wiki/Trash_Mobs_%28SSC%29
https://www.wowhead.com/npc=21218/vashjir-honor-guard#abilities
https://wowwiki.fandom.com/wiki/Vashj%27ir_Honor_Guard
https://wow.gamepedia.com/Vashj%27ir_Honor_Guard
http://tbc.cavernoftime.com/npc=21218#abilities

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
