### ISSUE TITLE
[Serpentshrine Cavern][Leotheras the Blind]

### ISSUE THREAD

**Issue by mechanicsTBC** [SunstriderEmu/BugTracker#3341]
https://db.endless.gg/?npc=21215
At 15% health, Leotheras transitions into phase 3 and both demon and human forms are out at the same time.  Currently, if you reach that 15% health and transition to phase 3 while Leotheras is in demon form, his human form will no longer cast whirlwind https://db.endless.gg/?spell=37640.  Leotheras should continue to cast whirlwind regardless of which form he was in upon reaching 15% health and transitioning.

https://db.endless.gg/?npc=21845
Currently has a few issues with demon form in phase 2 and phase 3.
https://db.endless.gg/?spell=37674
https://db.endless.gg/?spell=37675
The boss currently can be kited.  Kiting the boss out of the room should cause it to reset.  Currently you can just build a little threat and kite it completely out of the room and don't have to deal with it.
https://www.twitch.tv/videos/607614432?t=2h51m28s
both bugs can be seen from this video.  no whirlwinds in last phase because transition occured during demon phase and demon form gets kited out of tunnel, essentially removing it mechanically from the fight.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
