### ISSUE TITLE
[Serpentshrine Cavern][Fathom-Lord Karathress][Enrage]

### ISSUE THREAD

**Issue by mechanicsTBC** [SunstriderEmu/BugTracker#3342]
Boss is currently using the wrong enrage spell.  Boss did almost no additional damage when hard enraged.  This is referring to the hard enrage after 10 minutes, not the temporary enrage from the beastial wrath ability the boss gains.
https://www.twitch.tv/videos/615580326?t=1h46m4s
Also, at 1 hour 47 minutes 53 seconds streamer hovers over the buff.  Enrage buff is only increasing damage done by a flat 50.  I assume this enrage is the wrong spell ID and should instead be something that increases damage by something like 500%.

**Comment by Jerrythemagicdog** [comment]
Found something more appropriate, fixed with next update.
