### ISSUE TITLE
Paladin Class Quest is not working!!

### ISSUE THREAD

**Issue by kealthas06** [SunstriderEmu/BugTracker#3343]
Paladin Last quest For Mount And Blood knight Tabard 

https://www.wowhead.com/quest=9737/true-masters-of-the-light

Problem is that when you kill the npcs it doesn't count your quest as succes and one of the npcs that you have to kill which is a quest giver doesn't become an enemy  ive spent over 400g for the quest line to have the tabard

**Comment by kealthas06** [comment]
ANy improvement going on ?

**Comment by InhumanGM** [comment]
Duplicate of #2669
