### ISSUE TITLE
[Warrior][Spells][Threat] Spell Reflection

### ISSUE THREAD

**Issue by mechanicsTBC** [SunstriderEmu/BugTracker#3344]
https://db.endless.gg/?spell=23920
Warrior spell reflect currently has a few bugs.
1.  The damage does not show up in combat logs or floating combat text.
2.  The reflected damage does not generate threat.
![WoWScrnShot_051220_114204](https://user-images.githubusercontent.com/62405847/81733199-7765c000-9446-11ea-8d8b-1496a8e6f43f.jpg)
![WoWScrnShot_051220_114207](https://user-images.githubusercontent.com/62405847/81733218-7e8cce00-9446-11ea-9039-f9c7471967db.jpg)
![WoWScrnShot_051220_114213](https://user-images.githubusercontent.com/62405847/81733230-864c7280-9446-11ea-869c-d3858c77f73b.jpg)
0 threat before and after the reflect using .debug threat command.  NPC took damage from the reflect, but that damage was not shown in floating combat text or in combat log.  The reflected spell generated 0 threat.  Works the same in both battle and defensive stance.

**Comment by mechanicsTBC** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2351

**Comment by mechanicsTBC** [comment]
#1639

**Comment by mechanicsTBC** [comment]
#1557

**Comment by astrateslol** [comment]
Hello, is it going to be fixed?
