### ISSUE TITLE
Alar evades at 2nd phase

### ISSUE THREAD

**Issue by LSD7** [SunstriderEmu/BugTracker#3345]
**Describe the bug**
Alar evades at 2nd phase

**To Reproduce**
1. Protpall is tanking small phoenixes
2.   Small phoenixes are bump up protpall 
3.  Alar is charging to ProtPall
4.  Alar is evading

**Comment by Jerrythemagicdog** [comment]
Thanks, does the boss reset or is he soft evading for a moment?

**Comment by LSD7** [comment]
reset

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by michaelkittrell** [comment]
ive seen it too, when alar charges someone standing at the wall below the ramps.  couple times on the left side, not sure if ive seen it on the right

**Comment by Jerrythemagicdog** [comment]
The boss has a boundary in P2 so if someone goes up on the ramps or very close to them / under them he will evade.
