### ISSUE TITLE
Cannot get my Ring becuase the Windstones are bugged.

### ISSUE THREAD

**Issue by xxfortnitexd** [SunstriderEmu/BugTracker#3346]
**Describe the bug**
 Summoning the The templars /elementals in Silithus by equiping the 3/3 Twilight set and clicking on the Lesser Windstone and higher does not work. (The text if you right click on it doesnt appear at all

**To Reproduce**
Normally if you farm the 3/3 Twilight set you can right click on a lesser windstone and higher and you can click on a text to summon The elemental/dukes.

Item: https://de.classic.wowhead.com/item=20407/twilightkultistenrobe
https://de.classic.wowhead.com/item=20408/twilightkultistenkutte
https://de.classic.wowhead.com/item=20406/twilightkultistenmantel

Quest: https://classic.wowhead.com/quest=8332/dukes-of-the-council

**Expected behavior**
If you farm the Twilight 3/3 set you should be able to right click a lesser windstone and summon a templar.

**Screenshots/videos**
- https://imgur.com/a/T6HQV5C.

**Additional context**
THe problem is that iam farming the ring "Wrath of Cenarius" I already have all the Cenarion battle, tactical, and logistic badges farmed. The only thing left is the "Mark of Cenarius" to get that 
i need to kill the 4 dukes and i can only summon them by killing the templars first but neither can be summoned right now. . I put a lot of effort to farm all the things needed and its VERY Likley that iam the only one on the entire server to farm this ring since its to min max my dmg and its a classic item.

![WoWScrnShot_051220_231059](https://user-images.githubusercontent.com/65184215/81746081-2ab1d180-94a6-11ea-862b-8d6750b20f24.jpg)

 -->

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago, thanks for the issue.
