### ISSUE TITLE
Game chat issue

### ISSUE THREAD

**Issue by justheal** [SunstriderEmu/BugTracker#3347]
Hello. Sorry, it's not a bug but I just can't find on website where I can write this...
Global chat becomes a floodwall every evening - it's even worse than goldsellers now =/
For example - 
![WoWScrnShot_051320_000119](https://user-images.githubusercontent.com/53220855/81746590-7321bd00-94af-11ea-808d-e7004b466444.jpg)
 few messages _every second_ and it nearly impossible to understand anything

There is easy decision - just make few global channels (3 at least) - trade, GuildRecruitment and Global itself... so players can make different windows for each channel (or remove GuildRecruitment at all for example) and it will reduce spam a lot.
of course will need a rule to not trade in global and not LF guildies in trade etc... with not long mutes there everyone will learn it quickly

I'm finished

**Comment by Jerrythemagicdog** [comment]
Thanks, we'll consider it.
