### ISSUE TITLE
orc racial tanlent

### ISSUE THREAD

**Issue by 952137326** [SunstriderEmu/BugTracker#3348]
**Describe the bug**
My orc shaman is always stuned in the arena, and his racial talent has no ordinary chance, or even a series stuns . Please help me check if there is a bug, and then help fix it

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
just make  the original chance 

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
How was this tested? The racial works as expected. Please provide more details, thanks.
