### ISSUE TITLE
City of Light

### ISSUE THREAD

**Issue by ChuckFerrera** [SunstriderEmu/BugTracker#3349]
**Describe the bug**

The Quest 'City of Light' was not available to me in Shattrath after completing a few Lower City Quests. Now, my allegiance has been made for me to the Scryers. I wanted to go with Aldor because I am a Jewelcrafter.

**To Reproduce**

1. Came to Shattrath. Did not accept 'City of Light' quest due to time constraints.
2. Left Shattrath.
3. Came back, accepted some quests from Lower City, completed them and turned them in.
4. When I came back to Archmage Khadgar, he no longer offered the quest to me.
5. My allegiance was somehow made to the Scryers.

Quest Giver: https://www.wowhead.com/npc=18166/archmage-khadgar
Quest: https://www.wowhead.com/quest=10211/city-of-light

**Expected behavior**

Expected I would be able to still complete the City of Light quest and pledge allegiance to Aldor after doing some Lower City Quests.

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Did you pick up the quest "A'dal" from Haggard War Veteran?
https://db.endless.gg/?npc=19684

**Comment by ChuckFerrera** [comment]
That did it. Thank you Jerrythemagicdog for your help!

Best,

Ian Geis
