### ISSUE TITLE
Arena partner is considered enemy

### ISSUE THREAD

**Issue by mbouffardcegepba** [SunstriderEmu/BugTracker#3350]
**Describe the bug**
For some reason I encountered a bug where my 2v2 partner was considered an enemy, so I could attack him and couldn't cast any helpful spell on him. It is the first time I see this so I belive it is rare.

**To Reproduce**
The reproduction steps are unknown, I just joined arena as usual when Q popped.

**Expected behavior**
Partner being an ally.

**Screenshots/videos**
I didn't have reflex to take screenshot but if I ever encounter it again, I will take one and post it as comment.

**Comment by Jerrythemagicdog** [comment]
Thanks and please do!
