### ISSUE TITLE
Mails

### ISSUE THREAD

**Issue by Bobanhanzz** [SunstriderEmu/BugTracker#3356]
**Describe the bug**

I cannot take any mails on my lvl 40 tauren warrior Spraetteren. I can see that there's mail from yesterday auctions and my main (Bobanhanzz) but it wont show up when i open mailbox.

**Comment by MorKsQC** [comment]
Bump. This is happening to me as well, no matter which mailbox I go to, whether I disconnect or not

**Comment by MorKsQC** [comment]
![image](https://user-images.githubusercontent.com/65310903/81858938-86c23780-9532-11ea-99d1-d2aac6c86b31.png)

**Comment by MorKsQC** [comment]
Potential fix : Logging in and out doesn't work, but exiting the game and coming back seems to fix it

**Comment by Jerrythemagicdog** [comment]
You'll need to log in and out of the account completely for this to work and receive your mail faster. We're working on a fix, sorry for the inconvenience.
