### ISSUE TITLE
[QUEST] A pawn on the eternal board

### ISSUE THREAD

**Issue by S4ZZ** [SunstriderEmu/BugTracker#3357]
**Describe the bug**
When i take the quest there is strange animation movie after which the quest is not completing

**To Reproduce**

1. Take the quest https://db.endless.gg/?quest=8519

Quest: https://db.endless.gg/?quest=8519

**Expected behavior**
Quest is completing after animation movie

**Comment by InhumanGM** [comment]
This issue more so fits the description of #2616.
