### ISSUE TITLE
Black Qiraji Resonating crystal 

### ISSUE THREAD

**Issue by ztkay** [SunstriderEmu/BugTracker#3358]
Hey, this mount isn't working as intended. Which it probably should considering you put the price for 200 dollars
First of all you should have the ability to start summoning the mount while still in combat as long as the player was out of combat at the completion of the summon.

That's how it worked on retail up on till Patch 3.0.3 (2008-11-04)

Furthermore you should be able to mount up while falling. (Because its supposed to be instant) But that was changed in a TBC patch.

**Comment by Jerrythemagicdog** [comment]
Sorry, we won't be making the mount usable while in combat, that would be completely overpowered. The item is a cool collectible cosmetic and we'd like to keep it like that.
