### ISSUE TITLE
Macroed Nature's Swiftness with a spell is dispellable without the second spell actually going through

### ISSUE THREAD

**Issue by lastnoob** [SunstriderEmu/BugTracker#3360]
**Describe the bug**
If you macro a spellcast with Nature's Swiftness, NS is dispellable without the second spell going through. Since [patch 2.3](https://wowwiki.fandom.com/wiki/Patch_2.3.0), the delay from the latency is eliminated, thus the cast should be instant, resulting in the following if someone wants to dispel it: The 2nd spell goes through but so does the dispel (the dispeller gets the GCD but the shaman/druid gets the heal off as well). 

**To Reproduce**

1. Make a macro
E.g. 
```
/cast Nature's Swiftness
/cast Healing Touch(Rank 13)
```
2. Have no magic buffs on shaman/druid 
3. Spam dispel on them while they use the macro

Spell https://classic.wowhead.com/spell=17116/natures-swiftness

**Expected behavior**
Since [patch 2.3](https://wowwiki.fandom.com/wiki/Patch_2.3.0), the delay from the latency is eliminated, and the macro and spellcasts are sent to the server instantly, thus the cast should be instant (Nature's Swiftness has no GCD or anything like that), resulting in the following if someone wants to dispel it: The 2nd spell (e.g. the heal) goes through but so does the dispel (the dispeller gets the GCD but the shaman/druid gets the heal off as well). 

**Additional context**
It's the same mechanic with POM and other similar spells.

**Comment by Jerrythemagicdog** [comment]
Depends on the update time and when your spell cast happens, you might get unlucky and it might get dispelled, not much to do here for us.
