### ISSUE TITLE
[Quest] Get the Scoop

### ISSUE THREAD

**Issue by Bbyface** [SunstriderEmu/BugTracker#3361]
This quest is bugged, as I cannot speak to the "beholder" of the secret phrase, "Plucky" Johnson in Thousand Needles.

**Comment by InhumanGM** [comment]
After turning the NPC from a chicken to a human by using _/chicken_ on him, you should be able to talk to him, but the NPC remains non-interactive.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
