### ISSUE TITLE
Mana Tap Does not Return Mana

### ISSUE THREAD

**Issue by mr-krustev** [SunstriderEmu/BugTracker#3362]
Mana tap should steal mana from target and give you back. Does not do that on Blood Elf Female Retri  Paladin.

Atenazh is my character, no mana is returned.

**Comment by mr-krustev** [comment]
Don't know how to show this, but this did work before, and has stopped for about 1 week now.

**Comment by Godmatik** [comment]
Mana Tap only takes the mana and gives you a charge, you then need to use Arcane torrent to release your charges and restore mana.

**Comment by mr-krustev** [comment]
Looking through a lot of stuff for TBC, this seems to be true, so it appears it worked wrong for some time.

Cheers.
