### ISSUE TITLE
Can't find NPC Ontuvo <Jewelcrafting Supplies>

### ISSUE THREAD

**Issue by ChuckFerrera** [SunstriderEmu/BugTracker#3363]
**Describe the bug**

According to Wowhead, NPC Ontuvo <Jewelcrafting Supplies> was added in Patch 2.4.2.8278 and is located inside Shattrath's Terrace of Light at coordinates 48, 41. I am not able to locate him.

NPC: https://www.wowhead.com/npc=27666/ontuvo

**Comment by Jerrythemagicdog** [comment]
Server is releasing content in a progressive manner, this NPC won't be available at this time.

**Comment by ChuckFerrera** [comment]
Ahhh. I see. Thank you for the reply!
