### ISSUE TITLE
Mech Normal and Heroic mode

### ISSUE THREAD

**Issue by Dokmai321** [SunstriderEmu/BugTracker#3365]
**Describe the bug**
<We have cleared Mech N over 40+ times over 2 days and 1 item will not drop for both players who have been farming it. BeastLord helm will not drop and never has. Something is buggy with it should not take over 40+ times in normal mode to not see a drop!--- A clear and concise description of what the bug is. -->

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=https://www.wowhead.com/item=28275/beast-lord-helm&bonus=4101
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
The chance is 1/6 to get that item, you must have unfortunately gotten very unlucky.
