### ISSUE TITLE
Warlock pet issues:

### ISSUE THREAD

**Issue by Kalzin** [SunstriderEmu/BugTracker#3366]
Voidwalker pet: 
Mode issue: randomly seems to go passive (doesn't attack mobs that attack the warlock) despite being in defensive mode. - This seems apparent when the pet is attacking something and gets attacked by another mob.

Skills: Doesn't use torment automatically while attacking; i have to click the ability and puppet him almost entirely.

**Comment by Simon-GM** [comment]
Reproduction did not show anything not working as intended.

Voidwalker is correctly targeting and attacking creatures while set to 'defensive' mode.
The voidwalker also correctly uses 'torment', when the spell is set to be auto used.
