### ISSUE TITLE
Warp Splinter didn't drop quest item

### ISSUE THREAD

**Issue by hbr101** [SunstriderEmu/BugTracker#3369]
**Describe the bug**
In Botanica Warp Splinter didn't drop quest item for  [How to Break Into the Arcatraz] quest.

**To Reproduce**
Slay Warp Splinter in Botanica.

**Expected behavior**
Warp Splinter should drop Top Shard.

**Screenshots/videos**
Warp Splinter was slain but didnt drop Top Shard.
https://imgur.com/a/OHcZ1wO

**Comment by InhumanGM** [comment]
Was your inventory full at the time? If so, it should have been sent automatically to your mailbox.

**Comment by hbr101** [comment]
Same bug happened to my friend Flashtherapy who was in the same run with me. And no our inventory wasn't full. We didn't see Top Shard drop.

**Comment by InhumanGM** [comment]
Upon attempting to reproduce the issue, I was not able to find any issues. Could you provide more information that could be used to try to reproduce the issue again?

**Comment by hbr101** [comment]
Thank you for looking into this. It was regular dungeon run and so I don't have additional details which could help you.
