### ISSUE TITLE
[Quest] Mission: Possible But Not Probable

### ISSUE THREAD

**Issue by InhumanGM** [SunstriderEmu/BugTracker#3370]
**Describe the bug**
[[Mission: Possible But Not Probable]](https://tbc-twinhead.twinstar.cz/?quest=2478) if abandoned cannot be re-attained.

**To Reproduce**

1. Obtain [[The Shattered Salute]](https://tbc-twinhead.twinstar.cz/?quest=2460).
2. _/salute_ while targeting NPC [Shenthul](https://tbc-twinhead.twinstar.cz/?npc=3401).
3. Turn in [[The Shattered Salute]](https://tbc-twinhead.twinstar.cz/?quest=2460) to [Shenthul](https://tbc-twinhead.twinstar.cz/?npc=3401).
4. Obtain [[Deep Cover]](https://tbc-twinhead.twinstar.cz/?quest=2458) from [Shenthul](https://tbc-twinhead.twinstar.cz/?npc=3401).
5. Travel to NPC [Taskmaster Fizzule](https://tbc-twinhead.twinstar.cz/?npc=7233).
6. Use the provided item from [[Deep Cover]](https://tbc-twinhead.twinstar.cz/?quest=2458), [[Flare Gun]](https://tbc-twinhead.twinstar.cz/?item=8051), to turn [Taskmaster Fizzule](https://tbc-twinhead.twinstar.cz/?npc=7233) from hostile to friendly, then _/salute_ while targeting him to make the quest available to you.
7. Turn in [[Deep Cover]](https://tbc-twinhead.twinstar.cz/?quest=2458) to [Taskmaster Fizzule](https://tbc-twinhead.twinstar.cz/?npc=7233) and obtain item [[Fizzule's Whistle]](https://tbc-twinhead.twinstar.cz/?item=8066).
8. Obtain [[Mission: Possible But Not Probable]](https://tbc-twinhead.twinstar.cz/?quest=2478) from [Taskmaster Fizzule](https://tbc-twinhead.twinstar.cz/?npc=7233).
9. When this quest is abandoned, and the items [[Flare Gun]](https://tbc-twinhead.twinstar.cz/?item=8051) & [[Fizzule's Whistle]](https://tbc-twinhead.twinstar.cz/?item=8066) are removed from your inventory, there is no way to re-attain [[Mission: Possible But Not Probable]](https://tbc-twinhead.twinstar.cz/?quest=2478), even if you _/salute_ at [Taskmaster Fizzule](https://tbc-twinhead.twinstar.cz/?npc=7233) again, or go back to [Shenthul](https://tbc-twinhead.twinstar.cz/?npc=3401) and _/salute_ at him again.

Creature(s):
https://tbc-twinhead.twinstar.cz/?npc=3401
https://tbc-twinhead.twinstar.cz/?npc=7233

Item(s):
https://tbc-twinhead.twinstar.cz/?item=8051
https://tbc-twinhead.twinstar.cz/?item=8066

Quest(s):
https://tbc-twinhead.twinstar.cz/?quest=2460
https://tbc-twinhead.twinstar.cz/?quest=2458
https://tbc-twinhead.twinstar.cz/?quest=2478

Spell(s):
https://tbc-twinhead.twinstar.cz/?spell=2995

**Expected behavior**

When [[Mission: Possible But Not Probable]](https://tbc-twinhead.twinstar.cz/?quest=2478) is abandoned and items [[Flare Gun]](https://tbc-twinhead.twinstar.cz/?item=8051) & [[Fizzule's Whistle]](https://tbc-twinhead.twinstar.cz/?item=8066) are no longer in your inventory, it is not possible to re-attain the quest.

**Screenshots/videos**

https://www.youtube.com/watch?v=v4kimmMAkvc

**Additional context**

This is a quest chain for Rogues to get the [Poisons](https://tbc-twinhead.twinstar.cz/?spell=2995) ability.

**Comment by utagol4** [comment]
happening for me as well

**Comment by InhumanGM** [comment]
Did you _/salute_ at [Taskmaster Fizzule](https://tbc-twinhead.twinstar.cz/?npc=7233)?

**Comment by andrewjohnson167** [comment]
Bump, same issue

**Comment by andrewjohnson167** [comment]
so. is this in the works to be fixed? still unable to learn poisons on my rogue

**Comment by utagol4** [comment]
Also would like to know. I'm closing in on 60 and wondering if I should have re-rolled? Can someone help?

**Comment by quentinsrr** [comment]
The whistle works but the quest is not displayed

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago with an additional gossip provided to get a Whistle if a player abandons the quest mid way.
