### ISSUE TITLE
Mass Dispel

### ISSUE THREAD

**Issue by Demetorione** [SunstriderEmu/BugTracker#3371]
**Describe the bug**
Mass Dispel usable on enemy faction members in Shattrath.

**To Reproduce**
1. Have Alliance character with buffs stand in Shattrath.
2. Have Horde Priest cast Mass Dispel on them.
3. Remove 1 buff with each cast.

**Expected behavior**
This shit shouldn't happen as Shattrath is a sanctuary.

**Screenshots/videos**
https://i.imgur.com/Ma9hhst.png

**Additional context**
Fuck you Dunja.

**Comment by kelno** [comment]
Thanks.
Fixed with next server update.
