### ISSUE TITLE
Cant loot the chest from hellfire ramparts heroic last boss

### ISSUE THREAD

**Issue by chudzi** [SunstriderEmu/BugTracker#3374]
**Describe the bug**

**To Reproduce**

Item: badge of justice

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Sheikthecatman** [comment]
Unable to investigate this issue as there is no information provided, if the issue is "invalid target" then I suggest clearing your cache, if that does not solve the issue then try another client as it seems to be client-side.

I will re-open the issue if it does not work.
