### ISSUE TITLE
Quest "Concerted Efforts" (Repeatable) doesnt give double Honor while saying it does

### ISSUE THREAD

**Issue by sadlogic** [SunstriderEmu/BugTracker#3375]
https://db.endless.gg/?quest=8385 makes two entries of +314 honor in the combarlog and puts it on screen twice, but you dont get 628 honor but 314.

**Comment by InhumanGM** [comment]
**Video of Issue:**
https://youtu.be/EV7WWNJCDrk

**Comment by sadlogic** [comment]
So just to make sure, because i dont know:
Is the bug visual, so the amount of honor resieved is correct but its wrongly showing honor gained to be double.
Or is the amount of honor gained wrong and the visual correct?

Can anyone test the horde version of the quest?

**Comment by InhumanGM** [comment]
I'm not sure about what the correct value to be rewarded is, but I can confirm that the same thing happens on the Horde version of the quest.

**Comment by sukablyater** [comment]
So, will there be a fix? I can't find any definitive response from the devs here

**Comment by hufsa** [comment]
Visual problem only, resolved with next update.
