### ISSUE TITLE
Prot Paladin Talent (Anticipation)

### ISSUE THREAD

**Issue by nwiest** [SunstriderEmu/BugTracker#3376]
**Describe the bug**
I have all 5 points spent on the talent anticipation that grants +20 defense skill. My defense skill has been 350/370 for an extremely long time without me getting a single defense skill from combat. I am convinced it is broken and basically a waste of 5 of my talent points.

**To Reproduce**

1. Spend 5 talents on Anticipation
2. Level to 70
3. Sit at 350/370 for way too long 0.o

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
I was expecting to use the talent to reach defense cap..

**Screenshots/videos**
![talents and skills](https://user-images.githubusercontent.com/65403528/82052899-65745f00-968a-11ea-9b08-93f90a429ba9.png)

**Additional context**

**Comment by nwiest** [comment]
![image](https://user-images.githubusercontent.com/65403528/82055176-1e886880-968e-11ea-91a8-05a57b30cd0c.png)
just to show I have been level 70 for more than enough time, actively doing dungeons and such

**Comment by InhumanGM** [comment]
Upon attempting to reproduce the issue, I was not able to find any issues. I was able to get +20 skill points towards Defense. Could you provide more information that could be used to try to reproduce the issue again?

**Comment by nwiest** [comment]
Hmm I am unsure to be honest, I dont really remember what level I got the talents at or anything. I did put my /played to show I have been level 70 for almost 7 days of play time and I am still stuck at 350

**Comment by nwiest** [comment]
However I leveled as prot so the best guess I could give is I got all 5 as soon as they were possible for me to get. That would make it level 16-20? I noticed as I was leveling I could never reach any higher than the defense skill that is set for each level. I just ignored it to be honest but now I am getting rejected from hcs because I am under defense cap, so I am kinda mad about that haha

**Comment by nwiest** [comment]
I am going to cave and try to respec, if that fixes the issue would you like me to close this?

**Comment by nwiest** [comment]
Respec did not work, please advise!

**Comment by mechanicsTBC** [comment]
This is bugged if you do not have max defense skill when you take the talent.  if you are 330/350 defense skill and then take the talent you will be at 350/370 and unable to gain defense skills past 350 since the scripting thinks you are maxed.  To avoid this, untalent ability, level defense skill to max, relearn talent.  Common private server bug with the improved defense talents.  Most likely bugged in the same manor for the warrior talent as well.

**Comment by nwiest** [comment]
Ok will try this, thank you!

**Comment by nwiest** [comment]
Thanks a ton I am trying that now!

**Comment by nwiest** [comment]
Seems to have worked, really appreciate the input!!
