### ISSUE TITLE
Shadowform Bug

### ISSUE THREAD

**Issue by ganzulah** [SunstriderEmu/BugTracker#3378]
Cant go (sometimes) in Shadow Form

**To Reproduce**
Go in and out of Shadowform (noticed it happend often if u join a instance, bg or arena and ur first spell u press is shadowform)
sometimes it wont go back in Shadowform (says spell not rdy yet and its "greyed out" in spellbook
![shadowform](https://user-images.githubusercontent.com/65410595/82069490-a9d81d00-96d3-11ea-8173-d801ff4989ea.jpg)

**Expected behavior**
U should be able to cast Shadowform allways if u out of combat and have enogh mana

**Comment by ganzulah** [comment]
Relog will fix the problem only temporary

**Comment by Skelson** [comment]
I've experienced this a few times myself in the open world without entering any sort of instanced pve/pvp

**Comment by InhumanGM** [comment]
@ganzulah, I see that you use a macro for Shadowform, could you please provide the contents of your macro? And @Skelson, do you use a macro for Shadowform as well?

**Comment by kelno** [comment]
Thanks, fixed with next update
