### ISSUE TITLE
Floating Harvest Node

### ISSUE THREAD

**Issue by marchiris** [SunstriderEmu/BugTracker#3379]
**Describe the bug**
There seem to be inaccessible floating harvest node at this location. I don't know how common it is but sometimes I try to find the node and not find it. It seems this one is floating midair. 

**Screenshots/videos**
![Screen Shot 2020-05-15 at 3 10 15 AM](https://user-images.githubusercontent.com/65411195/82069841-25fd4100-9691-11ea-9b06-72643f76246c.png)

**Comment by beraus** [comment]
In order to check this, we need coords and zone.
