### ISSUE TITLE
Devastate's application of Sunder Armor stacks are affected by the combat table

### ISSUE THREAD

**Issue by TheRealZaroua** [SunstriderEmu/BugTracker#3380]
Warrior talent Devastate can have its application of the Sunder Armor debuff is affected by the attack table, and can thus be parried, dodged, blocked, and can miss.

What happens:
Devastate is on the combat table and can be parried, dodged, blocked, and can miss. The Sunder Armor application is also on the combat table and can be parried, dodged, blocked, and can miss.

What should happen:
Only Devastate should be on the combat table. If Devastate lands a hit or a crit, the Sunder Armor application should be automatic.

**Comment by TheRealZaroua** [comment]
https://db.endless.gg/?spell=30022
https://db.endless.gg/?spell=25225

Since I realize this is trying to prove a negative, I tried finding a decent retail TBC Prot Warrior POV video. I failed, so instead I went and looked other private servers. Here are 5 videos from 5 different private servers without this bug.

https://youtu.be/WHyEZZsPnUY?t=825
https://youtu.be/mVeqihsbvRU?t=62
https://youtu.be/5hI-8RhwhGU?t=147
https://youtu.be/wxgpTWbF2Io?t=676
https://youtu.be/FTefD5wYvd0?t=480

This is how it looks like on this server. Notice the timestamp, both Devastate and Sunder Armor go off. Only Devastate should go off, if it does Sunder Armor should be automatic, not an extra attack.
![devastate](https://user-images.githubusercontent.com/46357935/84614903-784e9f00-ae95-11ea-9eb1-e65ac0a1507e.png)

**Comment by mechanicsTBC** [comment]
@kelno

**Comment by kelno** [comment]
Okay yes, I noticed that before, will look into this

**Comment by kelno** [comment]
Fixed with next server update
