### ISSUE TITLE
MasterLoot Bug - Soulfrost

### ISSUE THREAD

**Issue by Zukai55** [SunstriderEmu/BugTracker#3381]
**Describe the bug**
Bugged loot in yesterday's Kara run where I was unable to receive the Soul frost enchant loot on my character Zaiku.

Photo Screenshot is the best reference for this: https://imgur.com/a/8B1t73H

**To Reproduce**
Masterlooter did not have access to enchanting and could not distribute it. When ML was given to me and another player, neither of us could delegate it to another player, nor pick it up ourselves. We also tried to Free For All loot it, but to no avail.

Item: https://www.wowhead.com/spell=27982/soulfrost

**Expected behavior**
Loot item into winning player's inventory

**Screenshots/videos**
https://imgur.com/a/8B1t73H

![Soulfrost ML Bug](https://user-images.githubusercontent.com/65418393/82088010-1563bf80-96bf-11ea-9da0-f683d0078ab3.JPG)

**Additional context**
Note the time is displayed at the bottom right of the screenshot, 21:51 EST on 5/14/2020. Kara ID is 4544.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2858
