### ISSUE TITLE
Paladins can use both seal

### ISSUE THREAD

**Issue by Rotbrut** [SunstriderEmu/BugTracker#3382]
**Describe the bug**
 Paladins can stack both corruption and vengeance to increase their dps by a lot.Since both sides are having the both  seals every paladin can use this.

**To Reproduce**
Use seal of vengeance stack to 5,switch to corruption stack 5,refresh vengenace,repeat

**Expected behavior**
Only one debuff can be stacked,since  ally has vengeance,horde has corruption

**Comment by Jerrythemagicdog** [comment]
There is no Seal of Corruption in the game, there is only Seal of Vengeance which is the exact same spell Alliance gets. Seal of Corruption is introduced in WoTLK.

Talking about it before the expansion gets released:
https://www.wowhead.com/forums&topic=32159
