### ISSUE TITLE
Arena Chest 

### ISSUE THREAD

**Issue by Thugzwithplugz** [SunstriderEmu/BugTracker#3384]
The timer for the arena chest timer is off by 30 minutes to an hour.

**Comment by InhumanGM** [comment]
What chest are you referring to? Do you have a source detailing what the correct time should be?

**Comment by Sheikthecatman** [comment]
The [Arena Chest](https://classic.wowhead.com/object=179697/arena-treasure-chest). The timer is 3 hours, but it may be off because of dynamic respawn.
