### ISSUE TITLE
Felstalker Quest

### ISSUE THREAD

**Issue by xEnvoy** [SunstriderEmu/BugTracker#3385]
**Describe the bug**
Last part of the Felstalker quest you summon it and kill it and it doesn't complete quest.

**To Reproduce**
Idk

https://classic.wowhead.com/quest=1795/the-binding
**Expected behavior**
Kill felstalker and the quest completes

**Comment by InhumanGM** [comment]
Upon attempting to reproduce the issue, I was not able to find any issues. Could you provide more information that could be used to try to reproduce the issue again?

**Comment by xEnvoy** [comment]
I dont think so i just accepted the quest and summoned it killed it and its not completing it.
________________________________

**Comment by InhumanGM** [comment]
Are you able to try again?

**Comment by xEnvoy** [comment]
worked that time, after the 10th try :p thank you
________________________________

**Comment by InhumanGM** [comment]
Sounds good, I'll be closing this as the issue is unable to be reproduced.
