### ISSUE TITLE
Magtheridon Boss - Mind Exhaustion debuff duration not correct

### ISSUE THREAD

**Issue by Ghostivan** [SunstriderEmu/BugTracker#3386]
**Describe the bug**
In Magtheridon strategy, when the channel breaks, the player receives the 30 sec Mind Exhaustion debuff. Actually, we can note that we have 2 min of Mind Exhaustion debuff.

**To Reproduce**
1. Kill the five Hellfire Channelers.
2. 5 players click on the cube in Phase 2 when Magtheridon cast Blast Nova to decast.
2. The Mind Exhaustion debuff is appearing on the five players with 2 min.

Boss: https://wow.gamepedia.com/Magtheridon_(tactics)
Spell: https://www.wowhead.com/spell=55481/mind-exhaustion

**Expected behavior**
In Magtheridon strategy, when the channel breaks, the player receives the 30 sec Mind Exhaustion debuff.

**Screenshots/videos**
https://youtu.be/2Xq0YVYHsVY?t=1718

**Additional context**
In the Youtube video you can see, the druid click on the cube and the Mind Exhaustion with 2 minutes while normally is 30 sec.

**Comment by mechanicsTBC** [comment]
2 minutes is prenerf debuff duration and is intended.

**Comment by Ghostivan** [comment]
Where did you find this information ? All tactics i found concerning this debuff duration is 30 sec

**Comment by Denagul** [comment]
https://youtu.be/v0PNXZYuAnU?t=296 Funny it's even supposed to be 3min and require 4 teams of clickers. But i think Endless found a good balance when setting it at 2 min requiring 3 teams of clickers :)
