### ISSUE TITLE
dark pact can be resisted by your demon and award no mana

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3387]
https://imgur.com/a/TFfcZnc

**Comment by InhumanGM** [comment]
In order to replicate this issue, we need more information. Please follow the bug report template that way we can properly reproduce and investigate this issue.

> **Describe the bug**
> 
> **To Reproduce**
> 
> 1. Cast X on target affected by ...
> 
> Item: https://wowhead.com?item=
> Quest: https://wowhead.com?quest=
> Spell: https://wowhead.com?spell=
> 
> **Expected behavior**
> 
> **Screenshots/videos**
> 
> **Additional context**

**Comment by babno** [comment]
cast dark pact on a pet, has chance to resist as shown in screen shot. I have seen it occur with imp and felhunter.

https://tbc-twinhead.twinstar.cz/?spell=18937

**Comment by babno** [comment]
It seems to be affected by hit chance/rating, as the -hit chance debuff from the huntsman in kara made almost every one resist.

**Comment by Jerrythemagicdog** [comment]
Seems to have been resolved some time ago (dev: spell has "ignore resistances" now)
