### ISSUE TITLE
Hearthstone vanished from character

### ISSUE THREAD

**Issue by devLesage** [SunstriderEmu/BugTracker#3389]
**Can't find my Hearthstone**

My hearthstone it's not on my bag or in the bank. I tried to pick up on a In Keeper, but it's says that I already have one. But theres nothing on my bag.

**Nickname of my char**
Lesage

**Here an image of my bag**

![image](https://user-images.githubusercontent.com/65437003/82111226-fe9e8680-9719-11ea-9469-800cfb3a6c32.png)

**Comment by InhumanGM** [comment]
Try disabling your bag addon. I have checked your character and I can see in our database that there is  a Hearthstone in your bags.

**Comment by InhumanGM** [comment]
As your issue has already been resolved due to guidance from another staff member, here is the fix for anyone else experiencing this issue: disable your bag addon.
