### ISSUE TITLE
Eye of the storm with no opposing players we were 12 alliance and 0 horde

### ISSUE THREAD

**Issue by andreasxen** [SunstriderEmu/BugTracker#3390]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by xxfortnitexd** [comment]
They just left bro

**Comment by Jerrythemagicdog** [comment]
> They just left

Yes, that's what happened.
