### ISSUE TITLE
Login unavailable

### ISSUE THREAD

**Issue by ArbitrumRU** [SunstriderEmu/BugTracker#3391]
When trying to enter the server, it gives an error
![WoWScrnShot_051620_125058](https://user-images.githubusercontent.com/63263113/82117083-7d291180-9776-11ea-9ae3-900dc1592da4.jpg)

**Comment by InhumanGM** [comment]
What is your set realmlist?

**Comment by ArbitrumRU** [comment]
Ohh ... rly. Sorry )))

**Comment by Ekspoo** [comment]
i have the same error but set realmlist is correct
![image](https://user-images.githubusercontent.com/68948579/88785994-96990180-d19a-11ea-999d-0fa99627e3b3.png)

**Comment by Ekspoo** [comment]
i have the same error but set realmlist is correct ((((
