### ISSUE TITLE
Ore Veins in Blade Edge Mountains are not obtainable in 50% cases

### ISSUE THREAD

**Issue by Noire86** [SunstriderEmu/BugTracker#3392]
**Describe the bug**
Ore veins in BEM are not obtainable or visible in game, but still visible at the minimap.

**To Reproduce**
Just fly around ore spawns in BEM and you will find at least 40-50% of the ores being everywhere but not in the right spot. Lots of bugged veins to the southeast of Toshley Station, and all around the BEM. 
![WoWScrnShot_051620_144533](https://user-images.githubusercontent.com/9317997/82119043-ec593280-9783-11ea-9a7f-2630c54b3f36.jpg)

As seen at screenshot, there are no any veins at the minimap spot.

**Screenshots/videos**

**Comment by Sheikthecatman** [comment]
If you could list or screenshot the ores that you've had issues with I could take a look and solve the issue. 

The screenshot provided only has one ore that is below the ground, I have moved it upwards.
