### ISSUE TITLE
Warrior Defiance talent doesn't work?

### ISSUE THREAD

**Issue by ludkobrz** [SunstriderEmu/BugTracker#3393]
I think war defiance talent doesn't work. I got print screen, 
![defiance](https://user-images.githubusercontent.com/39470213/82120600-9d150100-9787-11ea-80e9-5e35bbbd2e28.jpg)
You can see that i have all 3 points in this talent and 0 expertise. And i have issuse with threat, so i think this talent dosen't work properly.

**Comment by xxfortnitexd** [comment]
Talent buffs like hit / spellcrit / expertise , are often not shown on your character stats. Same with Warrior hit, shaman hit, warlock spellcrit, warlock spell hit. You get it but it doesnt show on your stats.

**Comment by Mihai930** [comment]
It clearly says that you get the expertise while in defensive stance, in the screenshot you are in battle stance. It works fine.

if you think there are issues with the threat part you need to bring proof.

**Comment by mechanicsTBC** [comment]
The threat part of the spell is only in defensive stance.  The expertise is suppose to be given in any stance.  This has already been reported and confirmed #2084

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
