### ISSUE TITLE
Fishing Bug - 

### ISSUE THREAD

**Issue by tyshies** [SunstriderEmu/BugTracker#3394]
**Describe the bug**
While Fishing in the Bay of Storms in Azshara, many successful catch's yield nothing.  Clicking the bobber after a catch sometimes just ends the fishing cast, doesn't produce an error message, or anything.  Sometimes I have gone ten catches in a row without it happening, sometimes i get "empty" catches in a row.

Uploaded Video is below.

**Screenshots/videos**
https://www.youtube.com/watch?v=Gr3u0EnYaAk

**Comment by tyshies** [comment]
-Edit-
It appears this is happening in other places than Azshara.  Fishing in Tanaris and the same thing is happening

**Comment by babno** [comment]
also happening in dun morogh

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2565
