### ISSUE TITLE
Track Humanoids (feral)

### ISSUE THREAD

**Issue by PapaOurs22** [SunstriderEmu/BugTracker#3396]
Hello,

I have a problem with my druid, when I morph into a cat, my tracking of humanoids no longer activates automatically. This has been the case for a few days and I have searched the internet for a similar problem but to no avail. I cleared my cache, deactivated my addons, I tried from another pc and I even downloaded 3 other different wow clients, it's always the same. I have a druid reroll on which tracking is working properly. I think it's a server problem but I don't know what else to do; (
Thank you

**Comment by Godmatik** [comment]
Sadly I think this is the case for TBC, track humanoids does not turn on by default when shifting.

**Comment by PapaOurs22** [comment]
Its works on tbc

**Comment by InhumanGM** [comment]
Upon attempting to reproduce the issue, I was not able to find any issues. Could you provide more information that could be used to try to reproduce the issue again?
