### ISSUE TITLE
Battlegrounds: Bonus Honor Visual

### ISSUE THREAD

**Issue by nexumus** [SunstriderEmu/BugTracker#3398]
**Describe the bug**
In Battlegrounds you obtain Honor Points by killing enemy players and by playing the Battleground's objectives. Also, when the Battleground ends, if your faction has won, you will be awarded with extra Honor Points. 

**Expected behavior**
Battlegrounds should award additional honor for objective completion and winning, i does in combat log, but in battleground frame bonus honor is zero for everyone

**Additional context**
after each battleground at endless - bonus honor visually equals zero unfortunately

**Comment by Balanarr** [comment]
You are awarded honor, toggle it from chat settings to get notified when gaining honor.

The scoreboard is bugged and does not display it.

**Comment by hufsa** [comment]
Thanks, this has been fixed now. Not live yet though.
