### ISSUE TITLE
RazorMane Hunter Pet 

### ISSUE THREAD

**Issue by CasianZuga** [SunstriderEmu/BugTracker#3399]
**Razormane Hunter Pet not attacking you upon combat*

**To Reproduce**
![Capture](https://user-images.githubusercontent.com/35381971/82135170-5828b300-97f7-11ea-8bb5-c52f986a6616.PNG)

**Comment by Simon-GM** [comment]
Did not manage to reproduce.
Razormane Wolf attacked everytime.
