### ISSUE TITLE
A lot iron nodes are mithril

### ISSUE THREAD

**Issue by Lionseye** [SunstriderEmu/BugTracker#3400]
Short version: Mithril is spawning in iron node spots.

Long version:
So essentially I'll just come out and say it.  I think a lot of spots iron is spawning mithril is in its place. Places that should not have mithril at all are spawning it.  Like Hillsbrad and arathi should have low to minimal mithril.  In fact I have to go to higher lvl areas to even find iron as there is so much mithril so I can go back to a lvl 31 area to find mithril.

This is confusing and would definitely make the lvling experience downright strange.  I'm having to farm blood shards just to avoid iron.

X x X To verify X x X
To check this simply check the spawn locations of hillsbrad and you'll find a disproportionate amount of mithril when there should be very little if any.

X x X
Useful links:

Iron nodes
https://classic.wowhead.com/object=1735/iron-deposit

vs mithril nodes

https://classic.wowhead.com/object=2040/mithril-deposit

X x X
Submitted in game it was suggested I put this here.

Lionseye can talk to you more on the subject on discord or game if you wish.

**Comment by beraus** [comment]
Include coords and zone names and we'll check this further. Closing for now.
