### ISSUE TITLE
Freezing trap rank 1 doesnt work. 

### ISSUE THREAD

**Issue by Soviethammer** [SunstriderEmu/BugTracker#3402]
Freezing trap rank 1 doesnt work. It should trigger like any other trap but its just gone when it triggers (like a resist)

1. Cast scatter shot on your target
2. Cast Freezing trap rank 1.

Should be trapped for X seconds depending if you specc or not. 

Video of the bug 👍 
https://streamable.com/d8tfwc

**Comment by Jerrythemagicdog** [comment]
Seems to resist because of the spell being a low level spell (level 20). Is there any reason why it shouldn't resist?

**Comment by Soviethammer** [comment]
That doesnt make any sence, that would mean that mages rank 1 frostbolts to cover their poly also should have 100% resist? or their rank 1 blizzard, or warlocks rank 1 rain of fire or any rank 1 spell which every class use.. This is clearly a bug for the trap. Resist shouldnt be based on the spells lvl but the target and the players lvl, right?

**Comment by Jerrythemagicdog** [comment]
In this case the spell is casted by the gameobject you set (the actual trap) not by you (the level 70 player) so it's different.

**Comment by bluemanguy112** [comment]
Patch 1.7.0 (patch date:2005-09-22): The resist rate for hunter traps is now based on the hunter's skill rather than the level of the trap. 

Also Shaman Totems are always same Level as Shaman too. This holds no merit whatsoever and is just a huge nerf to Hunters. Remove this ASAP.

**Comment by Skuzzlez** [comment]
To provide a link for the above:

https://wowwiki.fandom.com/wiki/Patch_1.7.0
> The resist rate for hunter traps is now based on the hunter's skill rather than the level of the trap.

Any chance of getting this fixed somewhat soon? Freezing Traps are resisting a huge amount, and the skill is pretty integral to Hunter PvP.

**Comment by Jerrythemagicdog** [comment]
Seems like I made a mistake explaining, the level of the caster is used when casting the trap.
I can't get Freezing Trap(Rank 1) to fail, testing against a level 70 Shaman with no talents. 
Need reproduce steps.

**Comment by artieau** [comment]
Working correctly
