### ISSUE TITLE
Mail gone while Cache cleared

### ISSUE THREAD

**Issue by Pushet95** [SunstriderEmu/BugTracker#3403]
Wrong item descriptions made me clear my cache folder. Relogged into WoW, remembered i had mail through bought items / canceled auctions.
Looking at the mail it said "retrieving item information" - wasnt really sure but still clicked mail anyway - the mail went away, no items were received.

After a while all items and information were finally received, but the items in that mails seem to be lost. I have no mails and the items are neither still in the auction house or in my inventory.

To reproduce this, all you have to do is basically buy some items through the auction house and dont receive those mails yet, then clear your cache, log back in and poof you succesfully deleted some items.
1. Get items in your mail
2. Clear Cache
3. Log back in and open said mails
4. Items gone

Item: https://wowhead.com?item=23436

**Expected behavior**
Not sure what exactly is supposed to happen, but probably the mails not disappearing without the item being received,

**Comment by nexumus** [comment]
![WoWScrnShot_052120_133051](https://user-images.githubusercontent.com/63930775/82594487-777f6180-9ba4-11ea-85a5-b51116858dba.jpg)
had same issue, bought an auction for 200g, got something like this screenshot, cleared catche, loged in - nothing in mailbox

**Comment by Godmatik** [comment]
try closing game completely and reboot

**Comment by Pushet95** [comment]
> 
> 
> try closing game completely and reboot

i have tried closing the game completly&rebooting multiple times, even cleared cache again, the mail seems to be just deleted without a trace

**Comment by beraus** [comment]
This issue should be resolved now.
