### ISSUE TITLE
quest=10144 Portal Grimh and Portal Kaalez can't be disrupted

### ISSUE THREAD

**Issue by Eon046** [SunstriderEmu/BugTracker#3404]
**Describe the bug**
Portal Grimh and Portal Kaalez can't be disrupted

**To Reproduce**
1. Get quest **Disrupt Their Reinforcements** https://tbc-twinhead.twinstar.cz/?quest=10144
2. Have 4+ Demonic Runes Stones
3. Click Portal Grimh and Portal Kaalez

**Expected behavior**
Portal Grimh and Portal Kaalez should be disrupted, giving you quest credit

**Additional context**
Good job with running Endless <3
![WoWScrnShot_051720_115558](https://user-images.githubusercontent.com/65491812/82143334-0144cd00-983b-11ea-89b7-1d7a124f6663.jpg)

**Comment by Sheikthecatman** [comment]
You have to stand in the middle of the portal to use the [Primer](https://db.endless.gg/?item=28106). 

I just tested now and there are no issues, if it doesn't work for you then I suggest clearing cache.
