### ISSUE TITLE
hunters pet aura bugged

### ISSUE THREAD

**Issue by ghost** [SunstriderEmu/BugTracker#3405]
1. Use [Intimidation] than [Bestial Wrath], or macro [Intimidation]+[Bestial Wrath]
2. Sit at mount and pull it with sit at mount ~2min need to up CD [Intimidation]+[Bestial Wrath]
3. Start attack when u sit at mount - pet have auras(Intimidation]+[Bestial Wrath]) after they end u can use again Intimidation]+[Bestial Wrath].

**Comment by z5n** [comment]
issue has since been fixed
