### ISSUE TITLE
Return to Andormu Quest

### ISSUE THREAD

**Issue by Umbaku** [SunstriderEmu/BugTracker#3406]
**Describe the bug**
Return to Andormu

**To Reproduce**
We did the OHF dungeon quest, after we killed the boss we got the new quest " Return to Andormu". Once we went to Andormu some of handed in the quest but some of us couldnt. When I click on Andormu I can just buy arrows and can not hand in the quest.

**Comment by Jerrythemagicdog** [comment]
There are two versions of the NPC in Caverns of time, one adult, one child. The quest requires you to talk to the child ("Return to the child Andormu..."). 
![image](https://user-images.githubusercontent.com/46463908/82257930-cfbe2580-9950-11ea-9959-c42877dafc61.png)
