### ISSUE TITLE
Resistance buffs doesnt stack proberly

### ISSUE THREAD

**Issue by gemabora** [SunstriderEmu/BugTracker#3410]
**Describe the bug**

Mark of the wild/ Gift of the wild doest stack their resistance with other buffs where it otherwise should do
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by steak-house** [comment]
not a bug, resistance player buffs aren't supposed to stack

**Comment by mechanicsTBC** [comment]
only the strongest resistance buff takes effect
