### ISSUE TITLE
Flute of the Ancients

### ISSUE THREAD

**Issue by brunojesus86** [SunstriderEmu/BugTracker#3411]
**Describe the bug**
Using the flute summons arei but he falls off the ground and can't be targetted.

**To Reproduce**
Get close to the pillar (49,30)
Use item flute of the ancients

1. Cast X on target affected by ...
2. 
3. 

Item: https://classic.wowhead.com/item=11445/flute-of-the-ancients
Quest: https://classic.wowhead.com/quest=4442/purified

**Expected behavior**
Arei falls off the ground and cant be targetted to start the quest Purified
**Screenshots/videos**
Don't use software to record

**Additional context**
Nothing more to add, pretty start forward bug

**Comment by Sheikthecatman** [comment]
![image](https://user-images.githubusercontent.com/59149613/82574512-8c99c780-9b87-11ea-926e-c38886354478.png)

**Comment by brunojesus86** [comment]
Apriciated looking at the bug and ill try again see if he shows up to me
