### ISSUE TITLE
What The Soul Sees Quest Bug 

### ISSUE THREAD

**Issue by xxoceanmanxx420** [SunstriderEmu/BugTracker#3412]
Hello, I'm submitting this bug request for the quest "What The Soul Sees". It is a part of a long quest chain in Nagrand and ends with Hero Of The Mag' har. In the quest, it asks that you use the soul mirror found in Auchindoun Crypts and go to north side of Oshu' gun to call forth a darkened spirit from Ancient orc ancestors found walking around and kill them. The bug i that the Ancient Orc ancestors for the quest aren't spawning at all and the quest cannot be completed.

**Comment by Sheikthecatman** [comment]
You need to complete [Vision of the Dead](https://db.endless.gg/?quest=10252) to see the Ancestors.

**Comment by InhumanGM** [comment]
Are you still experiencing this issue?
