### ISSUE TITLE
Cannot complete mision Stopping the Spread

### ISSUE THREAD

**Issue by scraw12** [SunstriderEmu/BugTracker#3413]
**Describe the bug**
I have completed the mission Stopping the Spread with my character Caimanaco but i don't can complete the quest.

**To Reproduce**
1. Get the mission Stopping the Spread in Nagrand
2. Burn the corpses
3. Try to complete the quest(Here is the bug)

Quest: https://www.wowhead.com/quest=9874/stopping-the-spread

**Expected behavior**
Only need be able to complete the mission.

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/28588159/82158828-86a39e00-988a-11ea-8174-e1345feb9e53.png)
![image](https://user-images.githubusercontent.com/28588159/82158834-98854100-988a-11ea-890f-f05573515bce.png)

**Additional context**

**Comment by Sheikthecatman** [comment]
I had no issue completing this quest locally. Try clearing your cache and taking the item out of your inventory (put into a bank) and then taking the item again. 

Will close the issue unless there is an actual issue that shows up.
