### ISSUE TITLE
High King Maulgar

### ISSUE THREAD

**Issue by bmwmuch** [SunstriderEmu/BugTracker#3415]
Hello again,here like it,Im mag tank on High king Maulgar at Gruul lair
i tank fire mag,that cast fireball and i must spellsteal his shield to stand 30 second with his shield
so when my shield is over i need few second to leave without shield
i get 365 fire resist its exelent resist
but no fireball was resisted For 2 Cd
plz tell me is it ok,cause our warlock tank Leothras the blind in shadow form,and he have resist.
meanwhile i dont have it on high king maulgar
Ty

**Comment by Balanarr** [comment]
High king's Fireball ignores all resistances. Learn to document yourself

**Comment by Godmatik** [comment]
@bmwmuch 
Fire resist has no effect on the fireballs during that fight.
You need to instead build a pure stamina set.
