### ISSUE TITLE
Arcane Missiles does not gain the critical strike bonus chance from arcane potency

### ISSUE THREAD

**Issue by Aprilane** [SunstriderEmu/BugTracker#3416]
**Describe the bug**
Arcane Missiles should gain 30% critical strike chance when arcane potency is procced. Instead it only gains the bonus critical strike chance if arcane missiles procs it during the channel.

**To Reproduce**

1. cast any spell until clearcasting procs while having arcane potency
2.  cast arcane missiles
3. 

Item: https://wowhead.com?item= 
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell= https://wowwiki.fandom.com/wiki/Patch_1.9.0 https://wowwiki.fandom.com/wiki/Patch_2.2.0

**Expected behavior**
 Arcane missiles should gain the 30% crit bonus for the entire channel duration when arcane potency from clearcasting is procced

**Screenshots/videos**

![WoWScrnShot_051720_143624](https://user-images.githubusercontent.com/62498143/82160865-132f6b80-984d-11ea-8bee-a93e15b2d155.jpg)

**Additional context**
 I only used arcane missiles when i had clear casting proced , my crit chance should be 50% for missiles fired with the buff.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2510
