### ISSUE TITLE
Gruul the Dragonkiller evade at 1% hp then refill 30%hp

### ISSUE THREAD

**Issue by turumaji** [SunstriderEmu/BugTracker#3417]
Gruul is reset to 30% hp at 1%

if main tank dies, instanlly it uses shatter skill then throw somebody to entrance(door) of instance then immediately regen 30-32% hp.
_if i get videos from my guildies i will add them here._

**Comment by Godmatik** [comment]
what likely happened is that the target he had aggro on that went flying went to a spot that Gruul temporarily couldn't reach, this caused him to evade bug. While evading, mobs restore their health.

**Comment by turumaji** [comment]
No actually gruul can reach this target. Because our hunter already attack him on here

**Comment by Jerrythemagicdog** [comment]
Would love to see a video of this happening.

**Comment by Mihai930** [comment]
not gruul but saw something similar happening here.
https://clips.twitch.tv/SpunkyCharmingCakeSMOrc

**Comment by Rotbrut** [comment]
We had similar happend at fathomlord's hunter add boss,he got almost full healed by a 0,1 sec evade
