### ISSUE TITLE
Feathermoon and Rut'theran Ships

### ISSUE THREAD

**Issue by Raizagal** [SunstriderEmu/BugTracker#3420]
**Describe the bug**
Feathermoon Stronhold and Rut'theran Village ships glitch and drop players into the water. 

**To Reproduce**

1. Ride the ship to Rut'theran Village and the ship going from Feathermoon Stronghold. 

**Expected behavior**

1. A safe trip to and from. 
2. To not be killed by FATIGUE when dropped so far from shore that shallows could not be reached in time by swimming.

**Comment by z5n** [comment]
issue has since been fixed
