### ISSUE TITLE
Ramps Heroic - Invalid chest target - can't loot, get last badge

### ISSUE THREAD

**Issue by Zukai55** [SunstriderEmu/BugTracker#3424]
**Describe the bug**
Ramps Heroic - Invalid chest target - can't loot, get last badge

**To Reproduce**
Kill final boss in Heroic Ramparts, Hellfire Peninsula.
Attempt to loot box in a party of 5.

 

A couple members were able to open, however 2 or 3 of us were not able to open and simply had to leave it there.

**Expected behavior**
Opening chest individually, loot Heroic badge.

**Screenshots/videos**

![Ramps Heroic Invalid chest target - can't loot, get last badge](https://user-images.githubusercontent.com/65418393/82211212-7f0de480-98de-11ea-998f-377c8f006727.JPG)

**Additional context**

 This wouldn't work before or after the first member looted the chest. This was our first attempt, so no bugs occurred during reset. Tried to change to Free for All but still no fix.

**Comment by Sheikthecatman** [comment]
Refer to #2337 as it may have a solution, this issue seems to be client side.
