### ISSUE TITLE
[mechanare] sunseeker astromage's fire shield damages after being dispelled or death

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3428]
title. even if its dead on the floor it'll continue damaging you until the buff "expires"

**Comment by Simon-GM** [comment]
I have attempted to reproduce the issue but without luck.
There does not seem to be any issue with Sunseeker Astromages.

They're self-buff (Fire Shield) will not damage you after they're dead.
However, you will still take damage for the DoT debuff 'Solarburn' until the time runs out.
