### ISSUE TITLE
Paladin Seal of Righteousness and Crusader still bugged

### ISSUE THREAD

**Issue by davedave1991** [SunstriderEmu/BugTracker#3429]
Holy dmg/ dmg bonus from SoC and SoR is not correct its waaaay too low and SoR is not scaling with spell power at all

https://imgur.com/a/OCYG1e6
As you can see in the screenshots SoR should do 47 holy dmg on melee hit w/o any buffs at all

https://imgur.com/gHS5T4Q
Judgement of crusader should increase the damage by 219
Simple math will tell you that 219+47=266 damage and that's with 0 spellpower yet I hit 245... 

https://imgur.com/vCbnGpt
So not only do I hit below the 266, its not adding any damage from spellpower either while mines at 613... I heard that it had to do with sor taking 100% from the spellpower previously but now its not taking any bonus from spellpiower at all and hitting even lower then it should without any
Please explain to me how this is fixed and how tankadins and shockadins are supposed to play their class with such a major bugg

**Comment by kelno** [comment]
All your calculations are based on the misconception that Seal of the Crusader should add flat 219 dmg, while it's actually adding spell power to spell attacking that target ("up to" is the usual tooltip expression for this).
