### ISSUE TITLE
Missing items at Weapon and Armor quartermaster Alliance

### ISSUE THREAD

**Issue by nozicek** [SunstriderEmu/BugTracker#3430]
**Describe the bug**
When i want to buy pvp gear or weapons I cant see them , there are just empty slots I Can see just Gladiators leather set (rogue)and Marshals Kodohide boots and bracers (druid items )

I am Quizzy , alliance night elf rogue

**Comment by Jerrythemagicdog** [comment]
There are no Gladiator weapons available for honor, you need to spend arena points for those in Area 52, which are available at a discounted price with no rating requirement.
