### ISSUE TITLE
flying pvp with a werebear

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3431]
i was flying above botanica in netherstorm and an ally druid flew up to me and i started taking damage from a "werebear".  300-400 melee swings 200 yards above the ground.  when i flew away from teh druid i stopped taking damage, when he moved back adjacent to me, i started taking the werebear hits again.  14 hits, some crits, before i zoned into botanica.

**Comment by michaelkittrell** [comment]
druid was in flight form the whole time.  just hovering.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next server update.
