### ISSUE TITLE
Armor and Weapon Bug in champions hall 

### ISSUE THREAD

**Issue by nozicek** [SunstriderEmu/BugTracker#3432]
Captain O'Neal - Weapons Quartermaster
Cant see any items for sale (two weeks ago ive seen)
![15898357019713133958441602111401](https://user-images.githubusercontent.com/65566452/82259284-96d77e00-995b-11ea-9639-2c86ab96e7fc.jpg)

Also

Captain Dirgehammer - Armor Quartermaster
I Can see Gladiators leather armor set 

Gloves
Legguards
Helm
Spaulders
Tunic
*Thats normal i am rogue, i see rogue items*
But there are 
Marshals Kodohide boots - druid item , no rogue items
And 
Marshals Kodohide Bracers -also cant see rogue but druid items
![15898359644811171851445520906946](https://user-images.githubusercontent.com/65566452/82259614-33018500-995c-11ea-872f-4bae4c1f5284.jpg)

Quizzy n.elf rogue 

sorry for spam .

**Comment by Jerrythemagicdog** [comment]
This vendor has everything you need 
![image](https://user-images.githubusercontent.com/46463908/82260176-ae5f3880-9954-11ea-8a60-e296a130dfcd.png)
