### ISSUE TITLE
Call of Water Shaman

### ISSUE THREAD

**Issue by sraniewbanie** [SunstriderEmu/BugTracker#3433]
**Describe the bug**
Was doing the quest Call of Water. Went to Tarren mill etc. Finally, got the water sapta from tauren under Ratchet and then weird thing happened. The quest did not show. First time play as Shaman (im a newbie), watched the guide for the quest on YT and moved to silverpine forest. Then found that place with water shrine, used the water sapta and killed all the elementals that showed and respawned for 30min. No one drop anything. Somebody came, killed one elemental and took a loot. Then the big elemental guy showed, but i couldn't proceed the quest (didn't even have one). The sapta ended and now i cannot even start the quest, neither have water totem. Been again to Shaman trainer, tauren guy under Ratchet, been to the guy under Camp Taurajo (or something), been to silverpine forest, talked to the troll, basecamp and no one can give me quest again.
**Expected behavior**
Can somebody give me the quest again or water totem please? Got already enough of traveling from orgri to undercity...

**Comment by sraniewbanie** [comment]
@up

Can someone give me water totem please?

**Comment by Simon-GM** [comment]
Please open an ingame ticket with this issue.
You can mention my name (Simon) in the ticket, to make sure that it will get forwarded to me.

Then I'll assist you with your inquiry.
