### ISSUE TITLE
Slow and root immune trash mobs in ZG

### ISSUE THREAD

**Issue by Venzg** [SunstriderEmu/BugTracker#3434]
**Describe the bug**

The crocodiles and tigers in ZG are not slowable or rootable, which makes them unfarmable for your fellow mage who has interest in Zandalari rep. 
**To Reproduce**
 The crocodiles and tigers are meant to be CC'able, although they arent on this server.

 https://classic.wowhead.com/npc=15043/zulian-crocolisk 
 https://classic.wowhead.com/npc=11361/zulian-tiger

**Expected behavior**

On a blizzlike server, they are not immune to cc

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in [3f8069318233fec919ec373154b3ac34c21e9f13](https://github.com/kelno/sunstrider-scripts/commit/3f8069318233fec919ec373154b3ac34c21e9f13)

**Comment by Venzg** [comment]
I just tested it, and they are still immune

**Comment by Sheikthecatman** [comment]
The update is not live yet, it will be live next restart. Sorry for the misinformation!
