### ISSUE TITLE
Ribbon of Sacrifice

### ISSUE THREAD

**Issue by Niylah** [SunstriderEmu/BugTracker#3436]
The USE ability on this trinket does not longer work since 1-2 days ago. It says "The spell is not available to you"

Tried to unequiped, but in bank but nothing works. A guildie have the same problem.

Ingame Name: Eremyn

**Comment by Godmatik** [comment]
GM on discord said it'll be fixed on next update.

**Comment by Jerrythemagicdog** [comment]
Fixed with next restart.
