### ISSUE TITLE
Fathom-Lord Karathress Evade Bug

### ISSUE THREAD

**Issue by Mythogit** [SunstriderEmu/BugTracker#3437]
**Describe the bug**
While doing the Fathom-Lord Karathress fight, multiple times we had the bosses bug out/evade bug. So what happens is if the tanks get hit with the tornado,their mob will evade and heal back to full. This has cause some issues. We still got the kill though its frustrating having to play around this.

Main problem is if our tank gets hit with the slow from Priest and he is targeted by the tornado and cannot get away. He will get lifted in the air and the mob will evade bug.

**To Reproduce**
Pull the Bosses and have the tornado target you, have it lift you in the air and as you are floating their the bosses will evade bug and heal up.

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
I would expect the bosses to not evade bug if the tanks get lifted into the air.

**Screenshots/videos**

**Additional context**

**Comment by Jaraxus** [comment]
Same heppen last karathress kill
