### ISSUE TITLE
Karazhan trinket bug  [Ribbon of Sacrifice]

### ISSUE THREAD

**Issue by arabxq88** [SunstriderEmu/BugTracker#3441]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://www.wowhead.com/item=28590/ribbon-of-sacrifice
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by arabxq88** [comment]
![unknown (1)](https://user-images.githubusercontent.com/65602377/82323388-a64cda80-99e0-11ea-9bbd-2d47f35c7cb8.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.
