### ISSUE TITLE
Lack of Negative Range

### ISSUE THREAD

**Issue by SuddenDeath** [SunstriderEmu/BugTracker#3442]
Current behavior: There currently is no negative range for melee and ranged spells/abilities

Expected behavior:
If close enough to an enemy, all orientation checks should be ignored for your spells and auto-attacks.

Example:
https://clips.twitch.tv/BlushingAbnegateMetalANELE before he turned around, he was able to gouge in that position. After he turned around, he's able to backstab. In addition to this, you're also able to cast spells behind the target
https://clips.twitch.tv/AnimatedLachrymoseMangoPipeHype

vmangos fix: https://github.com/vmangos/core/commit/0edcb3709c9dc2e7ff6fdf97bc99d843c44e83a0

**Comment by Jerrythemagicdog** [comment]
We've decided against having this some time ago, thanks.
