### ISSUE TITLE
Talents of mages: [impact] and [molten shields]

### ISSUE THREAD

**Issue by Sochifornia** [SunstriderEmu/BugTracker#3444]
Describe the bug
1. Molten armor damage does not have a chance to trigger the stun from the talent Impact.
2. Molten Armor causes damage on incoming ranged attacks without the necessary talent, which is necessary to do this

To Reproduce
1. Steps to reproduce the behavior:

Cast Molten armor.
Get hit by a mob or a player multiple times.
The stun from the talent Impact will never trigger.
Expected behavior
Every time Molten armor deals damage (meaning every time the mage gets hit by something and Molten armor deals damage to it in return) there should be a 10% chance (if the mage put 5 points into the talent Impact) for the Molten armor damage to stun aswell.

2. Steps to reproduce the behavior:
Cast Molten armor.
Don't put talent into Molten Shields.
Get range or spell hit by a mob or a player multiple times.
Molten armor deals damage (meaning every time the mage gets range or spell hit by something and Molten armor deals damage to it in return) there should be a 0% chance (if the mage don't put 2 points into the talent Molten Shields).

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3906
