### ISSUE TITLE
bleed

### ISSUE THREAD

**Issue by alandrarcy** [SunstriderEmu/BugTracker#3445]
**Describe the bug**
some NPCs are immune to bleed DMG even they shouldn't, i guess it's cause of their narute immune

**To Reproduce**
for example adds at hydross (nature phase) are immune

1. Cast rip on tainted spawn of hydross ...
2.  Cast rip on serpentshrine
3. 

Spell: https://classic.wowhead.com/spell=9896/rip

**Expected behavior**
those NPCs shouldn't be immune to bleed

**Comment by Jerrythemagicdog** [comment]
It's because they're Elementals and Elementals are usually immune to bleed effects.
