### ISSUE TITLE
I die whern got disconect

### ISSUE THREAD

**Issue by maylersaid** [SunstriderEmu/BugTracker#3446]
**Describe the bug**
everytime when i was in combat and i get DC, i reconect in less than 10 sec and die. Now, i was full life, and when i got dc and reconect, i was died.

![image](https://user-images.githubusercontent.com/54895599/82373501-09943800-99f4-11ea-92be-968daad80863.png)

**Comment by maylersaid** [comment]
i have a video here. Start a combat, with full life, press alt f4 and when i reconect, i was die. And i did this fast and never a mob would kill-me in less than 10 sec. 

https://drive.google.com/file/d/1Q5-a6WmLLDMVAhgv7yIJ0Uwod_NQ3BE6/view

**Comment by Jerrythemagicdog** [comment]
The server will kill you if you're in PvE combat at the time of disconnecting.
