### ISSUE TITLE
Quest "you're fired" bugged

### ISSUE THREAD

**Issue by quietdeception** [SunstriderEmu/BugTracker#3450]
Quest "you're fired" would not complete. after aborting quest to try and re-start, the quest giving item had the exclamation mark to give a quest, but was unable to be clicked on

https://www.wowhead.com/quest=10821/youre-fired

https://www.wowhead.com/object=185165/legion-communicator

I completed the quest and just want to be able to turn it in and continue with the quest chain.

**Comment by Jerrythemagicdog** [comment]
Do you have the Felsworn Gas Mas equipped? It's needed to pick up the quest.
https://www.wowhead.com/quest=10821/youre-fired#comments:id=2329123

**Comment by quietdeception** [comment]
it was deleted from my inventory after aborting the quest.i tried to re-start the chain, and it wouldnt work. i also had a friend do the beginning quests to see if i could join. that didnt work either



    On Wednesday, May 20, 2020, 01:14:38 PM CDT, Jerrythemagicdog <notifications@github.com> wrote:  
 
 


Do you have the Felsworn Gas Mas equipped? It's needed to pick up the quest.
https://www.wowhead.com/quest=10821/youre-fired#comments:id=2329123

**Comment by Jerrythemagicdog** [comment]
You need to talk to the NPC in Evergrove then to obtain a new Felsworn Gas Mask to be able to continue with the quest.

**Comment by quietdeception** [comment]
it seems to have worked. thank you
    On Thursday, May 21, 2020, 08:52:36 AM CDT, Jerrythemagicdog <notifications@github.com> wrote:  
 
 


You need to talk to the NPC in Evergrove then to obtain a new Felsworn Gas Mask to be able to continue with the quest.
