### ISSUE TITLE
[Hunter] feign death + Trap in PvP

### ISSUE THREAD

**Issue by disis24** [SunstriderEmu/BugTracker#3451]
Actually you can't instant trap a PvP player by using :  feign death + trap.

But works in a PvE environnement.

**To Reproduce**

1. Engage a pvp combat
2. put petpassive and  cast /petfollow
3. /cast feign death
4. /cast anytrap

**Comment by Jerrythemagicdog** [comment]
Traps have an arming time depending on the victim's combat state, not yours.
https://github.com/SunstriderEmu/BugTracker/issues/1739
