### ISSUE TITLE
Warlock Succubus Quest problem

### ISSUE THREAD

**Issue by Lixion1** [SunstriderEmu/BugTracker#3453]
**Describe the bug**

_I can't find my Succubus Quest, anywhere._

**Expected behavior**

_I have backtracked the Quest, multiple time, without any luck. (with help from wowwiki etc.)
couldt you either reset my Quest chain, or give me directions on where to go and who to talk to (if i have started it, witch i doubt), or give me the quest in my Questlog._

_don't know if any of this is possible, it is just frustrating, when you aren't able to find the Quest you need._

**Screenshots/videos**

**Additional context**

_avatar name: Lixion 70, Bloodelf Warlock_

**Comment by Godmatik** [comment]
you should try opening a GM ticket in-game

**Comment by Simon-GM** [comment]
The warlock minion quest chains are working as intended.
I assume you've done a part of the chain early on, and now you forgot where you got to.

Please open an ingame ticket ingame regarding this issue. A Game Master will assist you as soon as possible!
