### ISSUE TITLE
Quest :  [70] Teron Gorefiend - Lore and Legend: isn't working properly for me!

### ISSUE THREAD

**Issue by Golliwogg** [SunstriderEmu/BugTracker#3454]
**Describe the bug**
There is no npc to turn in the quest.

3.Quest ID : https://www.wowhead.com/quest=10644/teron-gorefiend-lore-and-legend 

So the quest seems reaally simple, talk to the ancient shadowmoon spirit- turn in the quest and pick up the following ones, well the only thing being is that there is no that npc only the spectre of Teron Gorefiend himself lingers there. I did equip my goggles, it did not work, even tried dying cause i've read in ghost form you can see the npc. Let's just say that was a waste of time. I waited for an hour or so in hopes the npc will spawn or something... Pls halp. 
![bug](https://user-images.githubusercontent.com/65692098/82513366-16f41400-9b13-11ea-92bc-e44d677643f3.png)

**Comment by InhumanGM** [comment]
The NPC Ancient Shadowmoon Spirit is currently there in its correct spot. It is possible that the NPC wasn't there when you attempted this because someone else started the quest.

**Comment by Golliwogg** [comment]
I came back bit earlier today, I've waited almost 2h the npc still isn't there. There obviously is something wrong here for it to remain like this for such a long time. I don't know man... seems wrong at this point.

**Comment by Golliwogg** [comment]
Update: 2h12min of wait time after i wrote Teron's ghost disappeared and the spirit spawned. Wierd it took that long,
