### ISSUE TITLE
Triage not working 

### ISSUE THREAD

**Issue by RyckyCozzy** [SunstriderEmu/BugTracker#3457]
**Describe the bug**
The triage quest does not work properly

**To Reproduce**
When trying to complete the quest it doesn't do anything but at the same time it doesn't fail the quest either 

Item: https://wowhead.com?item=
Quest: https://classic.wowhead.com/quest=6624/triage
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**
https://imgur.com/a/Dv0R0f3

**Additional context**

**Comment by nexumus** [comment]
did u... try to save those 15 patients? -.-'

**Comment by RyckyCozzy** [comment]
yeah of course i tried the mission like 3 times, the first time i actually failed it, then i retried 2 times the injured soldier stop spamming but the quest wasn't neither failed or completed. i'm here in front of the bank becuase one gm suggest to tried to bank the item to see if something change so here we are.

**Comment by Jerrythemagicdog** [comment]
So what's exactly the issue here? You're not being credited for saving injured soldiers using the quest item?
