### ISSUE TITLE
Sethekk Halls (H) - Anzu fight

### ISSUE THREAD

**Issue by BasedForfrost** [SunstriderEmu/BugTracker#3458]
**Describe the bug**
The spirits (Eagle, Hawk, and Falcon) do not appear to provide any of their buffs for healing them as they should. 

**To Reproduce**
1. Cast a healing spell on one of the three spirits
2. Benefit from their powers for a short duration until they banish again
3. Repeat

Eagle Spirit - https://tbc-twinhead.twinstar.cz/?npc=23136
Hawk Spirit - https://tbc-twinhead.twinstar.cz/?npc=23134
Falcon Spirit - https://tbc-twinhead.twinstar.cz/?npc=23135

**Expected behavior**
Eagle Spirit should deal AoE damage to Anzu and the birds he summons during banish phase
Hawk Spirit should provide a mitigation buff (Damage taken reduced by 500)
Falcon Spirit should provide a haste buff (like a mini Bloodlust)

Did not take a SS during the run. My mistake

**Comment by Jerrythemagicdog** [comment]
They should only grant those buffs when healed by a Druid, are you a Druid healing those?

**Comment by BasedForfrost** [comment]
Mm, you know I did not find any info that would have confirmed it being exclusive to Druids but that would explain alot. We were not healing with a druid. My mistake let's close this bad boy up then xD
