### ISSUE TITLE
[Warrior] [Spell] Spell Reflection: Freezing Trap

### ISSUE THREAD

**Issue by nexumus** [SunstriderEmu/BugTracker#3459]
**Describe the bug**
When using Spell Reflection at hunter's Freezing Trap - there appears no entry in combat log if the trap was reflected. 

**To Reproduce**
duel hunter, put down freezing trap, use spell reflection, enter the trap:
- trap is disabled
- but no info about it anywhere

**Expected behavior**
Even should be registered in combat log.

**Screenshots/videos**
![frap reflect](https://user-images.githubusercontent.com/63930775/82619559-8e3eac00-9bd6-11ea-95ea-2a587d0733c0.jpg)

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1557
