### ISSUE TITLE
[Quest] Return to Apothecary Zinge

### ISSUE THREAD

**Issue by Torgaun** [SunstriderEmu/BugTracker#3460]
**Describe the bug**
The Quest "Return to Apothecary Zinge" does not appear on NPC "Chief Engineer Bilgewhizzle" after you have turned in the quest "Tanaris Field Sampling"

**To Reproduce**

1. Turn in quest "Tanaris Field Sampling"
2. Talk to NPC "Chief Engineer Bilgewhizzle"
3. Not see Quest

NPC:  https://classic.wowhead.com/npc=7407/chief-engineer-bilgewhizzle
Quest: https://classic.wowhead.com/quest=864/return-to-apothecary-zinge

**Expected behavior**
The quest should appear after quest "Tanaris Field Sampling" is turned in

**Comment by beraus** [comment]
https://streamable.com/oe7fho

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
