### ISSUE TITLE
Bonus Elixir Master rate....

### ISSUE THREAD

**Issue by Coruna987** [SunstriderEmu/BugTracker#3462]
I have only 2 Flask bonus after craft 57 Flask ??????
Wtf is this rate ?? where is 5% ??
It's a bug or a troll ?

**Comment by Balanarr** [comment]
0.05 * 57 = 2.85

**Comment by NeonicSupersonic** [comment]
learn how random chances work

**Comment by Coruna987** [comment]
Mmh thx xD
