### ISSUE TITLE
Eye of Gruul trinket broken (again)

### ISSUE THREAD

**Issue by joemamaweet1234** [SunstriderEmu/BugTracker#3468]
**Describe the bug**
The Eye of Gruul trinket does not proc its Healing Trance effect from the casts of Lifebloom or Rejuvenation when it should. I tested by casting all druid heals many hundreds, even a thousand times, and it only procs from casting Healing Touch or Regrowth. The trinket should be able to proc from casting ANY healing spell (including Lifebloom or Rejuvenation). This makes a BiS druid trinket really bad. 

This bug was fixed for a period of time, but now the bug is back again and broken in the same way.

**To Reproduce**
1. Equip the trinket "Eye of Gruul"
2. Cast Lifebloom or Rejuvenation multiple times
3. No procs ever happen no matter how many times they are cast
4. Cast Regrowth or Healing Touch multiple times
5. Procs happen after casting them a decent amount of times

Item: https://tbc-twinhead.twinstar.cz/?item=28823

**Expected behavior**
Trinket should proc occasionally from any healing spell cast, including Lifebloom or Rejuvenation, like how it worked in retail TBC.

**Additional context**
This bug was fixed by your team before, but now it is broken and not working again. 

I believe the bug might be caused because Lifebloom and Rejuvenation do not cause a heal to instantly happen when they are initially cast, but instead the heal happens either after 1 second or after 3 seconds respectively. This may have confused the way you coded the trinket.

**Comment by kelno** [comment]
Thanks for the clean report

**Comment by kelno** [comment]
It does proc from Lifebloom and Rejuv but it only does if the target isn't already at full health.
After reviewing we've removed that rule, fixed with next update
