### ISSUE TITLE
BRD: Princess Moira Bronzebeard still aggroed after Emperor is killed

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#3469]
**Describe the bug**
Go to BRD, kill Emperor Dagran Thaurissan and without killing Princess Moira. She should break free from the mind control and become friendly after the Emperor dies. Instead she remains hostile and aggro'ed. The Quest The Royal Quest is marked as completed but cannot be turned in at the princess. [https://classic.wowhead.com/quest=4003/the-royal-rescue]

![WoWScrnShot_052220_153405](https://user-images.githubusercontent.com/61659496/82703451-e363d780-9c41-11ea-9dce-637da89660da.jpg)

**Comment by Sheikthecatman** [comment]
The quest is now completable. You are able to summon High Priestess of Thaurissan by having all the members of the group accept the quest after you hand in.
