### ISSUE TITLE
Locked After Less than 1 minute into Raid

### ISSUE THREAD

**Issue by TheBoogan** [SunstriderEmu/BugTracker#3470]
Our Raid Leader was creating our Group 2 Karazhan Raid. He was already saved. 2 of us walked in and got saved, even though we walked out within 10 seconds, let alone a full minute in the dungeon. 

Saved Group Leader not inside the zone. Players walk into raid and out of raid within 1 minute. 

Raid ID: 5296 Karazhan. This should not be Applied to Character "Boogan" Night elf druid, and well As Vu A hunter. 

Please remove this lock from us as there was no indicator message, nor was the hard 1 minute lock timer actually applied.

**Comment by Jerrythemagicdog** [comment]
There is no warning in TBC about being saved, we were playing with an idea of having a custom warning and giving you a grace period to leave the instance but it wasn't fully implemented in the end. 
We might go back to the idea in the future, though.
Whenever you enter a saved player's ID you will get bound to that same ID, sorry!
