### ISSUE TITLE
BUG [WARRIOR][TALENT][DEFIANCE]

### ISSUE THREAD

**Issue by PetroleUzzi** [SunstriderEmu/BugTracker#3472]
**Describe the bug**

Defiance doesn't increase expertise while in combat or berserker stance.

**To Reproduce**

switch stance with defiance talent and you will have the +6 expertise in defensive stance but not in the other stances.

**Expected behavior**

The talent says he upgrade threat in defensive stance only but the expertise is for all stances.

**Additional context**

The bug is "fixed" on the latest changeling but it was not fixed in game.

**Comment by Jerrythemagicdog** [comment]
The server is just not updated with the latest changes, it will be updated soon.
