### ISSUE TITLE
Got saved to an raid id of a person who was not in the raid

### ISSUE THREAD

**Issue by Vuendlessgg** [SunstriderEmu/BugTracker#3473]
i joined a "Fresh" raid for karazhan today with the guild Paradox. i got invited and went to the dungeon, horde was there trying to kill me I ran inside kara healed up and got saved to an id(id:5296) please fix this. iwas suppose to kill nightbane and raid 25man tomorrow.. I reportet it to GM and he sendt me here..........................................................................................… 
ingame name Vu 
please respond

**Comment by Godmatik** [comment]
Someone in your raid had a saved ID and didn't realize it.

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3470
