### ISSUE TITLE
[Shaman] [Talent] Healing Grace talent not working

### ISSUE THREAD

**Issue by Dayliex** [SunstriderEmu/BugTracker#3474]
Healing Grace talent not working

1. Cast any shaman spell
2. Friend/Enemy cast dispel
3. Dispels every time, out of 100 dispels, only max 5 resists -- it should be at least 20 or 30!

https://tbc-twinhead.twinstar.cz/?spell=29187

I expected for the enemy to have at least 20-30 resists out of 100 dispels on me

**Comment by Jerrythemagicdog** [comment]
100 dispels is not a big enough sample size to determine whether the dispel chance is correct or not. 
We have an automated testing system that allows two bots to cast the spells over (at least) hundreds of thousands of attempts and we were able to confirm that the chance is correct.
Thanks for the issue though!
