### ISSUE TITLE
Cannot auction Items with Charges

### ISSUE THREAD

**Issue by codcw** [SunstriderEmu/BugTracker#3475]
**Describe the bug**
It's impossible to put a [Thick Felsteel Necklace](https://db.endless.gg/?item=24106) on Auction House, due to error "Cannot auction item with used charges", but none of the charges on item is used.

**To Reproduce**
1. Obtain [Thick Felsteel Necklace](https://db.endless.gg/?item=24106).
2. Try to put in on AH.
3. Get an error.

Item: [Thick Felsteel Necklace](https://db.endless.gg/?item=24106)
Wowhead link: https://www.wowhead.com/item=24106/thick-felsteel-necklace

**Expected behavior**
I expect that i can just put that item on AH like i did with other similar items, with no problem.

**Screenshots/videos**
![2020-05-23 01_58_26-World of Warcraft](https://user-images.githubusercontent.com/48095466/82714826-15ecef00-9c99-11ea-83cb-9cde99568696.png)

**Additional context**
-

**Comment by zecke345** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3812

same here.

**Comment by hufsa** [comment]
Thanks for the report, this seems to be a client bug unfortunately and there's nothing we can do about that.
