### ISSUE TITLE
Problem with Aldor questline in Shadowmoon Valley.

### ISSUE THREAD

**Issue by MedZiSk** [SunstriderEmu/BugTracker#3476]
**Describe the bug**
I cant continue with questline because i changed faction.

**To Reproduce**

1. I started questline as Scryer and did 4 quests from here.
2. Then i changed reputation to Aldor because i googled reputation rewards. (1st time playing, so i didnt know there is something like Scryer/Aldor)
3. Now i cant continue/start quest line with Aldor. I should now continue with quest Proof of Allegiance.

Quest: 
https://www.wowhead.com/quest=10685/the-ashtongue-corruptors --> last quest done
https://www.wowhead.com/quest=10622/proof-of-allegiance    -->cant continue/pick up
https://www.wowhead.com/quest=10568/tablets-of-baari  -->cant pick up/start Aldor questline

**Expected behavior**
I dont know what to do now.  I dont want to change reputation back to Scryer since im already exalted with Aldor. I hope there is way to give that quest to my quest log or reset quest line for character (MedZi).

**Comment by beraus** [comment]
[Strained Supplies](https://www.wowhead.com/quest=10017/strained-supplies)
