### ISSUE TITLE
[QUEST] Azuregos's Magical Ledger

### ISSUE THREAD

**Issue by LSD7** [SunstriderEmu/BugTracker#3477]
**Describe the bug**
Spirit of Azuregos (https://classic.wowhead.com/npc=15481/spirit-of-azuregos) shoud be able to provide a quest Azuregos's Magical Ledger, but now he doesn't provide.
Source: https://wow.gamepedia.com/Azuregos%27s_Magical_Ledger

**To Reproduce**

1. Complete prequest https://classic.wowhead.com/quest=8555/the-charge-of-the-dragonflights
2. Go to Azshara. Find Spirit of Azuregos and try to get the quest.

Item: https://classic.wowhead.com/item=20949/magical-ledger
Quest: https://classic.wowhead.com/quest=8575/azuregoss-magical-ledger

**Expected behavior**
Spirit of azuregos provides quest.

How it should works:
https://www.youtube.com/watch?time_continue=11&v=b2_3XxeuyLI&feature=emb_logo

**Comment by LSD7** [comment]
Azuregos also doesn't start the quest

**Comment by LSD7** [comment]
Also i tried to kill Azuregos and then speak with Spirit of Azuregos and nothing changes.

**Comment by LSD7** [comment]
bump :C

**Comment by z5n** [comment]
Invalid, quest starts from [Magical Ledger] not NPC
