### ISSUE TITLE
Insect Swarm ending prematurely

### ISSUE THREAD

**Issue by leejeffrey08** [SunstriderEmu/BugTracker#3479]
**Describe the bug**

Before the stated duration runs it's course, Insect Swarm (max rank) ends prematurely, as denoted by the lack of an appropriate debuff on the enemy NPCs.

**To Reproduce**

Cast Insect Swarm on some mob in a dungeon.
Look at the debuff.
Profit occasionally.
Or be disappointed because you hoped for another response.

Dungeon mobs, bosses, whatever.

**Expected behavior**

I expect the insect swarm to work as intended.

**Screenshots/videos**

No screenshot.

**Additional context**

Yep.

**Comment by Jerrythemagicdog** [comment]
Need some specific examples here, maybe the debuff is dispelled or moved further down the visible debuffs list so you just can't see it's up anymore.
