### ISSUE TITLE
[Karazhan] Nightbane Terrace Doors

### ISSUE THREAD

**Issue by Ironjudgment** [SunstriderEmu/BugTracker#3480]
**Describe the bug**
Once you close the doors, it is impossible to open them without GM intervention.

**To Reproduce**
1.  Go to Nightbane Terrace
2.  Close doors

**Expected behavior**
You should either be unable to close them at all, or be able to open them again after you close them.

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in [17e639ab0997b89e640529b56279378fd6b383f0](https://github.com/kelno/sunstrider-scripts/commit/17e639ab0997b89e640529b56279378fd6b383f0).
The fix will be live next restart.
