### ISSUE TITLE
Kindness Quest not working. 

### ISSUE THREAD

**Issue by Dellas25** [SunstriderEmu/BugTracker#3481]
**Describe the bug**

1. Kill flayer to get corpse.
2. Place on ground as quest tells you to do.
3. Nothing happens.

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2549
