### ISSUE TITLE
[Battered Steam Tonk Controller] disconnects me when used

### ISSUE THREAD

**Issue by kevin-chowanski** [SunstriderEmu/BugTracker#3482]
**Describe the bug**
When I use the toy item Battered Steam Tonk Controller, I get disconnected from the game after 3 or maybe 4 seconds.

**To Reproduce**
Use the item Battered Steam Tonk Controller
Item ID is 31666
https://db.endless.gg/?item=31666

**Expected behavior**
The toy working :(

**Screenshots/videos**
//

**Additional context**
I'm very sad because it's an unique item and you only receive 10 charges. Lost 3 of them because this bug :(

**Comment by Simon-GM** [comment]
I can't reproduce the issue. This does not sound like a server-side issue.
Do you have any more steps for me, in order to reproduce this situation?

**Comment by kevin-chowanski** [comment]
I disabled all my addons and the item works as expected so you're right, it's client-side.
Unfortunately, I don't have enough charges to know which addon is causing the disconnection.

However, by messing around with the toy, I found a gamebreaking bug and I'll make another ticket for that :)

Thank you !
