### ISSUE TITLE
+10 Haste Rating Glove Enchant

### ISSUE THREAD

**Issue by SychoticAbby** [SunstriderEmu/BugTracker#3487]
My level 19 twink priest "Priestqt" has the +10 haste rating enchant on her gloves, yet the stats aren't applied to her stats along with the effect not decreasing cast time as seen from the 2 images below.
![WoWScrnShot_052420_122218](https://user-images.githubusercontent.com/65032532/82759198-c225f700-9db9-11ea-8c26-09d3b99493b4.jpg)

![WoWScrnShot_052420_122223](https://user-images.githubusercontent.com/65032532/82759199-c5b97e00-9db9-11ea-9634-dfced3b76751.jpg)

**Comment by NeonicSupersonic** [comment]
should have checked melee tab

**Comment by SabreValkyrn** [comment]
"Haste Rating" applies to melee and ranged, not spells.

https://db.endless.gg/?spell=13948

>Permanently enchant gloves to increase melee and ranged haste rating by 10.

**Comment by pinkisnotgay** [comment]
rek
