### ISSUE TITLE
[Quest]Tremors of the Earth

### ISSUE THREAD

**Issue by Centuri0n123** [SunstriderEmu/BugTracker#3488]
**Describe the bug**
I was doing the quest line of this, I recovered all the items required and when I have to summon the 02 NPC I need to kill to complete the quest, It summoned 04 NPC, 02 of each one 

Quest: https://classic.wowhead.com/quest=717/tremors-of-the-earth

**Expected behavior**
just 02 dragons summoned, only 01 of each one

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/65864019/82759800-22666a00-9db5-11ea-984c-654dad931cc2.png)
![image](https://user-images.githubusercontent.com/65864019/82759869-8e48d280-9db5-11ea-8854-4793fa6796f4.png)

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago, works correctly now.
