### ISSUE TITLE
Item bugged: [Skull of Impending Doom]

### ISSUE THREAD

**Issue by Centuri0n123** [SunstriderEmu/BugTracker#3489]
**Describe the bug**
Cannot Use the item Skull of Impending Doom, it says "you have no target"

**To Reproduce**
1. Equip in Off hand slot
2. Use the item, and it says "you have no target" 
3  It doesn't work.

Item: https://classic.wowhead.com/item=4984/skull-of-impending-doom#reward-from-q
Spell: https://classic.wowhead.com/spell=5024/flee

**Expected behavior**

**Screenshots/videos**

![image](https://user-images.githubusercontent.com/65864019/82760092-fd72f680-9db6-11ea-8c59-df298b4e5846.png)

**Comment by Godmatik** [comment]
I think it was disabled on purpose because it's overpowered in Arena

**Comment by NeonicSupersonic** [comment]
it drains 70% of total mana and health in tbc, gl using it in arena

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2275
