### ISSUE TITLE
Minor Recombobulator for Horde

### ISSUE THREAD

**Issue by SychoticAbby** [SunstriderEmu/BugTracker#3490]
On my level 19 rogue "Close" I travelled to Gnomeragon and did all the steps required to get the yellow punch card, when used on a Punchograph 3005-B inside the dungeon it should let you learn the crafting recipe to make Minor Recombobulator. 
When I went inside and used the Punchograph 3005-B, the option was presented to me to learn the recipe but upon clicking it I was just given the text "greetings close" and was not given the recipe nor was it put in my engineering spellbook.

https://wowwiki.fandom.com/wiki/Minor_Recombobulator

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2890
