### ISSUE TITLE
Blade Twisting

### ISSUE THREAD

**Issue by Ch33z0r** [SunstriderEmu/BugTracker#3491]
**Describe the bug**
The Rogue Talent Blade Twisting should give a DAZE effect on the Target with a 20% chance for Sinister Strike, Shiv and other attacks.
The Daze effect is overwritten by other slow effects, should not be the case, since its not a slow but a daze.

**To Reproduce**
I can Shiv a Target until its Dazed and can apply crippling Poison. The Daze effect gets overwritten.

https://tbc-twinhead.twinstar.cz/?spell=31126

**Expected behavior**
Daze Effects and Slow effects can be on the same Target at the same Time.

**Screenshots/videos**

**Additional context**
Proc Chance seems to be fine since i thought this was the Problem at first.
Thank you for Fixing <3

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
