### ISSUE TITLE
[Quest] Gather the Orbs 

### ISSUE THREAD

**Issue by Pavel418890** [SunstriderEmu/BugTracker#3492]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Pavel418890** [comment]
I put a totem and nothing is going to

**Comment by InhumanGM** [comment]
In order to replicate this issue, we need more information. Please follow the bug report template that way we can properly reproduce and investigate this issue.

> **Describe the bug**
> 
> **To Reproduce**
> 
> 1. Cast X on target affected by ...
> 
> Item: https://wowhead.com?item=
> Quest: https://wowhead.com?quest=
> Spell: https://wowhead.com?spell=
> 
> **Expected behavior**
> 
> **Screenshots/videos**
> 
> **Additional context**

**Comment by maylersaid** [comment]
im on this quest, follow the video. The totem need suck all purple balls.
https://drive.google.com/file/d/1Vit5nHiSgd3of9pvwLek66WGlx5XqmRL/view

**Comment by Jerrythemagicdog** [comment]
Quest works as intended.
