### ISSUE TITLE
Constant Exploration Looping Sound

### ISSUE THREAD

**Issue by peanb** [SunstriderEmu/BugTracker#3493]
**Describe the bug**
After playing for a while, I got this "you have discovered" -sound on constant loop. The sound that the game plays when you explore a new area. But it is constant, and plays on an endless loop. Relogging, changing client or account does not make a difference. It still plays everytime im ingame... really annoying. Could not find any information regarding this on google so far and i dont know what causes it. Can record some of it if needed

**Comment by Simon-GM** [comment]
This does not sound like a server-side issue.
I'll advice you to clear the cache folder in your game folder to begin with.
If that does not solve your issue, please attempt to re-install your client.
