### ISSUE TITLE
A few issues with buffing NPCs (mostly important with escort mobs)

### ISSUE THREAD

**Issue by steak-house** [SunstriderEmu/BugTracker#3496]
**Describe the bug**
Some +stats buffs don't seem to have any effect on NPCs. In addition, when NPCs leave combat, they lose all their buffs, so I'd need to rebuff after every fight, which is very mana inefficient

**To Reproduce**
1. Give Mark of the Wild to Thrall in OHF
2. Observe that his health doesn't change, despite the stam part of the buff
3. At the end of a pack, observe that his buffs all dispell

**Comment by Jerrythemagicdog** [comment]
Creatures don't have stats, other than attack power, that's why there is no difference when buffing them. They also wipe all of their buffs and debuffs when they reset (leave combat). There could be something done to change that maybe.

**Comment by steak-house** [comment]
I'm certain that mobs didn't lose all their buffs when they left combat on retail - there's no reason for that to happen.

Thanks for the explanation for stats.
