### ISSUE TITLE
Quest disconnects from server

### ISSUE THREAD

**Issue by lumieri** [SunstriderEmu/BugTracker#3497]
**Describe the bug**
Quest named "A Dip in the Moonwell" in Thousand Needles disconnects you from the server when you activate the robot and start running towards the well.

**To Reproduce**
1. Activate the robot and start running towards the well.

Item: https://tbcdb.com/?item=23675
Quest: https://tbcdb.com/?quest=9433

**Expected behavior**
Not get disconnected at all.

**Screenshots/videos**
- https://www.youtube.com/watch?v=loAIeZbYC8s

**Additional context**
-

**Comment by kelno** [comment]
Thanks, can you provide your character name?

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, could you provide more details as to what class you're playing? (armory link would be best).

**Comment by lumieri** [comment]
https://endless.gg/armory/character/Lumier

There you go :)

**Comment by Jerrythemagicdog** [comment]
Disconnects on possessing were fixed some time ago, thanks for the issue.
