### ISSUE TITLE
Stealthed while mounted

### ISSUE THREAD

**Issue by Gnigge** [SunstriderEmu/BugTracker#3498]
**Describe the bug**
Ability to stealth while mounted.

**To Reproduce**
1. Enter BG Arathi Basin while mounted on [Reins of the Swift Spectral Tiger].
2. Leave finished battleground in Stealth.
3. Appear stealthed while mounted, tested twice and worked both times.

Item: https://www.wowhead.com/item=33225/reins-of-the-swift-spectral-tiger
Quest: N/A
Spell: https://classic.wowhead.com/spell=1787/stealth

**Expected behavior**
You should not be able to stealth while being mounted.

**Screenshots/videos**
https://streamable.com/j6xnps

**Additional context**
N/A

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update!
