### ISSUE TITLE
In Arc, Spiteful Temptress' Spiteful Fury spell is a buff, and as such can be right-clicked to dispell it

### ISSUE THREAD

**Issue by steak-house** [SunstriderEmu/BugTracker#3499]
**Describe the bug**
See title

**To Reproduce**
1. Get attacked by a Spiteful Temptress in Arcatraz until she debuffs you with Spiteful Fury (note that she won't do that on the main tank, so at least two people must be there. Both times that I got affected by it, I was healing)
2. Observe that it's a buff, and as such, can be rightclicked to dispell it

NPC : https://www.wowhead.com/npc=20883/spiteful-temptress#abilities
Spell: https://www.wowhead.com/spell=36886/spiteful-fury

**Expected behavior**
Should be an undispellable debuff

**Comment by kelno** [comment]
Thanks for reports and providing ids

**Comment by kelno** [comment]
Fixed with next server update
