### ISSUE TITLE
Druid - ability RIP incorrect scaling

### ISSUE THREAD

**Issue by Stevenseagal8** [SunstriderEmu/BugTracker#3501]
Druids RIP ability incorrect scaling when picking talent "Naturalist" (Increase all physical damage by 10%)

Correct scaling of RIP without talent "Naturalist" (This part works as intended)

1 Combo point tick damage:
(300 + AP * 0,06)/6 = damage per 1 tick 
2 Combo point tick damage:
(498 + AP * 0,12)/6 = damage per 1 tick
3 Combo point tick damage:
(696 + AP * 0,18)/6 = damage per 1 tick
4 Combo point tick damage:
(894 + AP * 0,24)/6 = damage per 1 tick
5 Combo point tick damage:
(1092 + AP * 0,24)/6 = damage per 1 tick

Correct scaling of RIP with talent "Naturalist" (This part does not work correctly)
I will skip directly to 5 combo point rip example

5 Combo point tick damage:
(1092 + AP * 0,24)*1,1/6 = tick damage per 1 tick

Above it how it should be and below example is how it acts on Endless

5 Combo point tick damage:
((1092 * 1,1) + AP * 0,24))/6 = tick damage per 1 tick

The thing that is going wrong is that talent Naturalist is only being calculated into the base ability damage itself and not the damage of the ability as a whole inclusive the AP scaling component.

It is easy to reproduce. Just use above fomulas and try use rip with and without talent "Naturalist" and use different amount of AP. 

https://wowwiki.fandom.com/wiki/Rip

![image](https://user-images.githubusercontent.com/61162040/82837581-ca6d5780-9ec9-11ea-8144-0e06b5b59867.png)

**Comment by kelno** [comment]
Naturalist rank 5: 17073

**Comment by kelno** [comment]
Well, nice find and thanks for the very specific details here, that helped!
Fixed with next server update
