### ISSUE TITLE
Stratholm: Postmaster Malown doesn't spawn after opening 3 mailboxes

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#3502]
**Describe the bug**
In my case, the Fras Siabi, Crusaders' Square and the Festival Lane keys were dropped. After opening all 3 (Crusaders' was my last), nothing happens. 

Possibly another bug, Timmy the Cruel was missing in dungeon too.

https://classic.wowhead.com/npc=11143/postmaster-malown#comments

**Comment by z5n** [comment]
unable to reproduce, he spawned correctly during testing

**Comment by kelno** [comment]
That was fixed recently during instance rework
