### ISSUE TITLE
Classic Enchants for Twinking

### ISSUE THREAD

**Issue by SychoticAbby** [SunstriderEmu/BugTracker#3503]
1.) [Enchant Weapon - Spell Power](https://www.wowdb.com/items/18260-formula-enchant-weapon-healing-power) dropped by Molton Core bosses 
2.) [Enchant Weapon - Healing Power](https://www.wowdb.com/items/18260-formula-enchant-weapon-healing-power) dropped by Molton Core bosses.
3.) [Enchant Gloves - Frost Power](https://www.wowdb.com/items/20728-formula-enchant-gloves-frost-power) dropped by Ruins of Ahn'Qiraj & Temple of Ahn'Qiraj bosses.
4.) [Enchant Gloves - Superior Agility](https://www.wowdb.com/items/20731-formula-enchant-gloves-superior-agility) dropped by Ruins of Ahn'Qiraj & Temple of Ahn'Qiraj  bosses.
5. [Enchant Cloak - Stealth](https://www.wowdb.com/items/20734-formula-enchant-cloak-stealth) Dropped by Ruins of Ahn'Qiraj & Temple of Ahn'Qiraj  bosses.
6.) [Enchant Gloves - Fire Power](https://www.wowdb.com/items/20729-formula-enchant-gloves-fire-power) Dropped by Ruins of Ahn'Qiraj & Temple of Ahn'Qiraj  bosses
7.) [Enchant Cloak - Dodge](https://www.wowdb.com/items/20736-formula-enchant-cloak-dodge) Dropped by Ruins of Ahn'Qiraj & Temple of Ahn'Qiraj  bosses.
8.) [Enchant Gloves - Healing Power](https://www.wowdb.com/items/20730-formula-enchant-gloves-healing-power) Dropped by Ruins of Ahn'Qiraj & Temple of Ahn'Qiraj  bosses.
9.) [Enchant Gloves - Shadow Power](https://www.wowdb.com/items/20727-formula-enchant-gloves-shadow-power) Dropped by Ruins of Ahn'Qiraj & Temple of Ahn'Qiraj  bosses.
10.) [Enchant Bracers - Mana Regeneration](https://wowwiki.fandom.com/wiki/Enchant_Bracer_-_Mana_Regeneration) Sold by Argent Dawn Quartermaster at Honored Reputation.
11.) [Enchant Bracer - Healing](https://www.wowdb.com/items/19447-formula-enchant-bracer-healing-power) Sold by Argent Dawn Quartermaster at Revered Reputation.
12.) [Enchant Weapon - Strength](https://www.wowdb.com/items/19444-formula-enchant-weapon-strength) Sold by Thorium Brotherhood Quartermaster at Friendly Reputation.
13.) [Enchant Weapon - Mighty Spirit](https://wowwiki.fandom.com/wiki/Enchant_Weapon_-_Mighty_Spirit) Sold by Thorium Brotherhood Quartermaster at Honored Reputation.
14.) [Enchant Weapon - Mighty Intellect](https://www.wowdb.com/items/19449-formula-enchant-weapon-mighty-intellect) Sold by Thorium Brotherhood Quartermaster at Revered Reputation.
15.) [Enchant Chest - Greater Stats](https://classicdb.ch/?item=16253) Dropped by Vanilla World Bosses.

For the enchants that were not on wowdb.com, I have provided links to the same enchant from either classicdb.com or wowwiki.com

In my personal opinion, I would like to see these items added to either a vendor, or put in the drop table of level 60 elites out in the world, since most of these enchants are from old raids which are impossible to find a group for as of right now, or from lengthy reputation grinds from classic that require some kind of raid material or rep from low level dungeons.

**Comment by NeonicSupersonic** [comment]
Can I have free swp gear cos I cba to grind bosses?
