### ISSUE TITLE
Stratholme : Shadowcraft Pants

### ISSUE THREAD

**Issue by avalord186** [SunstriderEmu/BugTracker#3504]
https://classic.wowhead.com/item=16709/shadowcraft-pants

Good day, I farm Stratholme for the whole day, there were more than 50 races on the Baron Rivendare boss and the pants didn’t drop, namely Shadowcraft Pants. Fix it, please

**Comment by Simon-GM** [comment]
No issue was found. This item is indeed dropping as intended.
