### ISSUE TITLE
Familiar Fungi doesnt work from the first time

### ISSUE THREAD

**Issue by Jekenius** [SunstriderEmu/BugTracker#3505]
**Describe the bug**

I've done quest by gathering mushroom samples but couldnt turn quest in. I abandoned that quest and regathered quest items and quest became turnable in.

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

I dont know how to reproduce that situation.

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

https://www.wowhead.com/quest=9708/familiar-fungi

https://www.wowhead.com/item=24238/mushroom-sample

**Expected behavior**

Quest should be doable from the first time.

**Screenshots/videos**

First time
![WoWScrnShot_052620_131742](https://user-images.githubusercontent.com/45003723/82869759-013e7e80-9f59-11ea-9aad-d1ad8299442b.jpg)
![WoWScrnShot_052620_131746](https://user-images.githubusercontent.com/45003723/82869770-04d20580-9f59-11ea-9189-db8d81ebaa29.jpg)
Second time

![WoWScrnShot_052620_134834](https://user-images.githubusercontent.com/45003723/82869845-216e3d80-9f59-11ea-85e0-647e55745584.jpg)
![WoWScrnShot_052620_134832](https://user-images.githubusercontent.com/45003723/82869849-23380100-9f59-11ea-880d-07b5fd65f19b.jpg)

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed some time ago.
