### ISSUE TITLE
Heroic instance keys require revered reputation instead of honored

### ISSUE THREAD

**Issue by Lebzon** [SunstriderEmu/BugTracker#3507]
Hello,

Short bug report:
As the title sais, heroic instance keys require revered reputation, instead of honored.
This was changed in 2.4.3 to honored to help quicker progression.

If this is the intended state of the keys I'll rest my case, however in that case you need to change your FAQ page:
![image](https://user-images.githubusercontent.com/65962623/82911199-e32e4980-9f6b-11ea-92f8-5cb3ac623e76.png)

**Comment by Jerrythemagicdog** [comment]
That's intended.
