### ISSUE TITLE
No Resist

### ISSUE THREAD

**Issue by bmwmuch** [SunstriderEmu/BugTracker#3508]
Hello,there is no fire resist on mag tank on Gruuls lair,high king maulgar,i have 375 fire resist,but its doesnt resist eve 1 damage

**Comment by bjh368** [comment]
If you mean Krosh Firehand, his Greater Fireball is not possible to resist with fire resistance. 

![image](https://user-images.githubusercontent.com/59749446/82940412-0f11f500-9f95-11ea-8705-6904cd498135.png)
from https://wowwiki.fandom.com/wiki/Krosh_Firehand

**Comment by Simon-GM** [comment]
The answer @bjh368 is giving you is correct.
