### ISSUE TITLE
[Quest] Redemption can't be completed

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#3509]
**Describe the bug**
Accepted quest at Tirion Fordring and nothing happens.

**To Reproduce**
1. Completed the 3 pre-quests.
2. Take quest Redemption.
3. ....

https://classic.wowhead.com/quest=5742/redemption#comments

**Expected behavior**
At step 3, the dialogs should be setup to listen to his story and at the end, quest completed.

**Screenshots/videos**

![WoWScrnShot_052620_153742](https://user-images.githubusercontent.com/61659496/82943223-436ebc80-9f67-11ea-893a-0c6a9533a20a.jpg)
![WoWScrnShot_052620_153926](https://user-images.githubusercontent.com/61659496/82943235-48337080-9f67-11ea-9a29-d97078aef595.jpg)

**Comment by Jerrythemagicdog** [comment]
https://classic.wowhead.com/quest=5742/redemption#comments:id=2743175

You have to be seated to listen to his story.
