### ISSUE TITLE
Fantom-Lord Karathress

### ISSUE THREAD

**Issue by frztw** [SunstriderEmu/BugTracker#3511]
enrage 10min, we have 100% more dmg and 50% attack speed

we need:
[The standard hard enrage mechanic for many bosses in TBC is:](https://wowwiki.fandom.com/wiki/Enrage_(mechanic)?oldid=1426939)

    10 minutes after the pull
    damage done increases by 500% (= six times the standard damage)
    cast and attack speed increase by 150% (= 2.5 times faster than normal)

**Comment by mechanicsTBC** [comment]
yes the current enrage isnt that great.  the current one (100% damage) was added because the original one on endless was only a flat 50 damage increase.
