### ISSUE TITLE
[NPC] Baron Geddon casts Armageddon when being pulled

### ISSUE THREAD

**Issue by kuskmen** [SunstriderEmu/BugTracker#3512]
**Describe the bug**
Baron Geddon (12056) casts Armageddon (20478) when he is pulled.

**To Reproduce**

1. Go to Molten Core, Baron Geddon.
2. Pull him.
3. Check combat log.

NPC: https://classic.wowhead.com/npc=12056
Spell: https://classic.wowhead.com/spell=20478

**Expected behavior**
He should cast it when he is nearly dead.

**Comment by Randalierer** [comment]
I was there yesterday with a small group and this issue is still there.
Geddon just explode on pull and the tragic thing about it: you can't loot him.
How do I get my TF now?

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.
