### ISSUE TITLE
Herbs not accessible

### ISSUE THREAD

**Issue by Keritous** [SunstriderEmu/BugTracker#3513]
[Bruiseweed] - The Barrens
 [Bruiseweed] @41 ,27 is not accessible.
![WoWScrnShot_052720_151554](https://user-images.githubusercontent.com/66011356/83010959-58625300-a02e-11ea-8fe7-04fc9c96bcc8.jpg)

**Comment by Keritous** [comment]
Stranglethorn Vale
Goldthorn @43 ,11, the same issue

**Comment by Sheikthecatman** [comment]
Thank you! Those two previously stated herb nodes are fixed and will be positioned correctly next server restart.

I will not close the issue in-case you find more nodes that need to be fixed. If you do not find any more feel free to close the issue.
