### ISSUE TITLE
Thrall despawned from OHF HC after two wipes

### ISSUE THREAD

**Issue by blackouths** [SunstriderEmu/BugTracker#3516]
Thrall despawned in our OHF HC after two wipes. He died during the second boss fight and then was not present in the prison cell after the wipe.

The second bosses' mount was in the middle of the path leading to the keep. We checked Tarren Mill after this and he was not situated inside the barn - it appeared he had totally despawned from the instance.

I'm unsure how you would replicate this other than letting Thrall die inside OHF multiple times and waiting for him to despawn. After the first wipe everything was fine inside the instance.

I unfortunately do not have screenshots as this was several hours ago.

**Comment by blackouths** [comment]
HC ID 8668 27/05/2020

**Comment by Godmatik** [comment]
It's intended that after a certain amount of wipes in heroic, Thrall will not respawn, and the instance is over.

**Comment by beraus** [comment]
Event stops after 3rd wipe, couldn't reproduce with info given.
