### ISSUE TITLE
db.endless.gg drop rates

### ISSUE THREAD

**Issue by diamadov** [SunstriderEmu/BugTracker#3517]
I'm sure devs are aware of this, but figured I'd make a formal bug report.

**Describe the bug**
db.endless.gg drop rates do not correspond to live server drop rates. Based on comment on [#2806](https://github.com/SunstriderEmu/BugTracker/issues/2806):

> These are the drop chances from the following creatures on the live server:

```
ENTRY	CHANCE
16530	0.025
18420	0.03
19747	0.04
20864	0.01
21047	0.04
21301	0.07092
22291	0.04
23355	0.5
```

_Originally posted by @Jerrythemagicdog in https://github.com/SunstriderEmu/BugTracker/issues/2806#issuecomment-611318934_

I'm wondering if there is any way for players to query / view live drop rates or if the db.endless.gg site could be linked / updated to live drop rates. Any help would be appreciated.

Thanks!

**Comment by beraus** [comment]
db.endless.gg is used for linking purposes only (armory and changelogs).

**Comment by diamadov** [comment]
No worries. I figured it can't hurt to ask. Also, as an edit, I went back and these drop chances for this item appear to correspond with db.endless.gg - was just curious if there was any way to get live drop rates as is referenced in the above quote.

**Comment by kelno** [comment]
Thanks, indeed the DB isn't really "official" and doesn't always reflect the current values of the live server.
