### ISSUE TITLE
Crystal Yield not working

### ISSUE THREAD

**Issue by yepvinkel** [SunstriderEmu/BugTracker#3519]
When i use Crystal Yield it says it is a soulbound item and cannot be used. while it is in fact a soulbound item, it has to be used on a enemy target in order to work. To reproduce the bug it should sufixe to use it on a enemy npc.

This is my first bug report ever, i hope the information provided is enough to fix this bug.

https://classic.wowhead.com/item=11565/crystal-yield

**Comment by beraus** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/16673248/83053451-03840400-a051-11ea-80fa-e0363cc7737d.png)

**Comment by NeonicSupersonic** [comment]
it doesnt stack with sunders anyway

**Comment by Jerrythemagicdog** [comment]
It doesn't stack with Faerie Fire and was intentionally removed.
