### ISSUE TITLE
SSC, LURKER BELOW SPOUTING DURING WHIRL

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3520]
There is a bug with spout.  It is supposed to spout in a clockwise or counterclockwise direction a predictable and steady, easily avoidable speed.

We are sometimes seeing extremely experienced people randomly killed by spout... all claiming it wasn't anywhere close to them.

In our first attempt on 5/27/2020, towards the end of a spout around 50%, 4-5 people died in very different directions in 1s, recount says all died to spout.  Some of us saw a visual that seemed to show the boss spouting in 5 different directions, changing facing impossibly fast (obv targetting players), in 360 degrees in about 0.5s.  It almost looked like boss did a whirl while still spouting.  Some people saw nothing, some people saw 1 or 2, a couple saw spouts going in 5 different directions extremely quickly.  

This may be 2 different issues? spouting while whirling, randomly changing facing and randomly 1 shotting someone with spout that shouldn't?

**Comment by Balanarr** [comment]
Yup, as of this reset Lurker is now broken.

**Comment by Balanarr** [comment]
His breath also seems to be hitting some people that are in the water.

**Comment by turumaji** [comment]
yea also maggys cubes are broken last week, sometime clicks doesnt work

**Comment by kelno** [comment]
Okay so there is some confusion here before the spout animation takes some time to disappear, so when the boss does the whirl after that he often appear as spouting in every direction at the very end, but it doesn't actually.
I'll increase the delay before the whirl at the end of the spout phase, this should make it less confusing.
If you got more issues there, please include clips!
