### ISSUE TITLE
Cannot open my Bank inventory anymore.

### ISSUE THREAD

**Issue by Pakans101** [SunstriderEmu/BugTracker#3521]
**Describe the bug**
I cannot open my bank inventory on one of my characters wierdly (Pescobar). Never had this issue before and somehow it 'appeared' I click the humanoid, he talks back, but nothing happens. Bothers me since i have alot of stuff in my bank :/
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Godmatik** [comment]
close game client and reboot.
try with all add-ons disabled.
