### ISSUE TITLE
Bug [Meeting at the Blackwing Coven]

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#3522]
**Describe the bug**
The disguise lasted no more than 5 seconds. Insufficient to complete the quest. Half way during the dialog, I turned back to myself and the target became hostile. Tried twice. Took too long to get all the costume scraps.

**Comment by Ironjudgment** [comment]
Can confirm, happened to me but months ago.

**Comment by Jerrythemagicdog** [comment]
Can't reproduce, maybe you've gotten in combat or ran into the mobs that can see past the illusion.
