### ISSUE TITLE
[Quest] Commander Ameer doesn't start next quest after completing A Mission of Mercy

### ISSUE THREAD

**Issue by Watsegwan** [SunstriderEmu/BugTracker#3524]
**Describe the bug**
After you complete A Mission of Mercy quest in netherstorm for Commander Ameer he doesn't start the next quest called Ethereum secrets

**To Reproduce**

    Get Honored reputation with the consortium.
    Start a mission of mercy quest and complete it
    You can't take the next quests in the chain which is supposed to be on in the 2.1 version.

https://tbcdb.com/?quest=10971
https://www.wowhead.com/quest=10971/ethereum-secrets

**Expected behavior**
We should get the next quest in the quest line as we are in 2.1

**Additional context**
The Ethereum Prisoner I.D can be looted but cannot be used

**Comment by Ironjudgment** [comment]
We are still in patch 2.0+ state. That's why you aren't able to pick those quests up.

**Comment by Jerrythemagicdog** [comment]
> We are still in patch 2.0+ state. That's why you aren't able to pick those quests up.
that's correct, thanks!
