### ISSUE TITLE
Respawn time is too short in general

### ISSUE THREAD

**Issue by ezequielavilagarcia** [SunstriderEmu/BugTracker#3525]
Respawn time for creeps in all the game is really short, I'm playing experience rate x1, I need to do a lot of quest, and when I should go inside a cave it's really frustrated, creeps respawn I think each 3 minutes, you don't have time to clean the way...

Please fix this, at least 6 minutes or 7 minutes..

Thanks!

**Comment by steak-house** [comment]
respawn issues arise routinely on the bugtracker but they don't seem to get addressed. According to @kelno , they increased respawn time with the last batch of bug fixes, but some areas are still just impossible to solo because of how quick things respawn.

**Comment by beraus** [comment]
Thanks, we will take this into consideration
