### ISSUE TITLE
Marticar

### ISSUE THREAD

**Issue by woofic** [SunstriderEmu/BugTracker#3526]
Marticar (rare mob in zangramash)
spawn time is not correct reborn like a regular mob
![WoWScrnShot_051720_085430](https://user-images.githubusercontent.com/66053712/83103960-724c7600-a0c0-11ea-89da-e80fbdc2b192.jpg)

**Comment by Sheikthecatman** [comment]
Thanks! The Marticar respawn time has been adjusted to be more correct.
