### ISSUE TITLE
Trollbane's Command not working in Hellfire Citadel on Alliance

### ISSUE THREAD

**Issue by McGossy** [SunstriderEmu/BugTracker#3527]
**Describe the bug**
Trollbane's Command (In Hellfire Peninsula and Hellfire Citadel, increases Honor Hold reputation gained from killing monsters by 10%) is not working inside of Hellfire Citadel. The buff doesn't show up or apply to kills inside any dungeons there.

**To Reproduce**

1) Obtain Trollbane's Command buff
2) Enter Hellfire Citadel dungeon
3) Kill something and see if rep increases

Spell: https://www.wowhead.com/spell=39911/trollbanes-command

**Comment by kelno** [comment]
Thanks for reporting!

**Comment by kelno** [comment]
Fixed with next server update

**Comment by kelno** [comment]
duplicate https://github.com/SunstriderEmu/BugTracker/issues/3294
