### ISSUE TITLE
wepon smith Blacksmithing

### ISSUE THREAD

**Issue by bugmaster01** [SunstriderEmu/BugTracker#3528]
so since relese we were able to craft maces x2 for evryone that was macesmith 
on retail this was not the thing till SSO came out.

so is this a thing you guys wanted to be fun or?

**Comment by Watsegwan** [comment]
If you read the server description, it says that the game is in 2.4.3 mod, only the content is progressif.

**Comment by bugmaster01** [comment]
ok so why cant hunters make the 24 slot bags? why cant other classes benefit from it just Warriors. since moustly will they craft  wepons from bs.
