### ISSUE TITLE
[WoW API][Lua Scripting] UnitResistance method does not work?

### ISSUE THREAD

**Issue by kuskmen** [SunstriderEmu/BugTracker#3530]
**Describe the bug**
There should be a UnitResistance WoW API method that returns resistances of given npc.

**To Reproduce**
1.Create the following macro
```
/script u=UnitResistance y="target" a=u(y ,0) h=u(y ,1) f=u(y ,2) n=u(y ,3) fr=u(y ,4) s=u(y ,5) z=u(y ,6) SendChatMessage(UnitName(y).." has "..a.." Armor, "..h.." HR, "..f.." FR, "..n.." NR, "..fr.." FrR, "..s.." SR and "..z.." AR.", SAY)
```
2. Use it on some npc.

Info for the method:
https://wowwiki.fandom.com/wiki/API_UnitResistance

**Expected behavior**
When you use the macro(hence the method as well) you should get the real resistances of the mob instead of returning 0 all the time.

**Comment by kelno** [comment]
Thanks for reporting!
I'm 99% sure it's not supposed to work on npcs or even other players. If you got any evidence it should, you can post it here or open a new issues.

**Comment by kuskmen** [comment]
I am sorry, did you say WoW API have **unit** resistance method and it should not work for **units**?

**Comment by kelno** [comment]
Yes. Accepting unit parameter doesn't mean it should work on every unit. A valid target other than the player would probably be his pet.

The reason I know it shouldn't work on enemy players for example is that your client simply doesn't ever receive that information from the server.
