### ISSUE TITLE
Weird looting bug

### ISSUE THREAD

**Issue by McGossy** [SunstriderEmu/BugTracker#3532]
**Describe the bug**
Was in a run of Blood Furnance (norm) doing the 2nd boss. Tank(me) and healer died while others took it down. Boss dropped an item for our healer and the healer needed while everyone else greeded. I released spirit so didn't get to vote on the item. Healer then released spirit before the timer was up. Once the timer ran down I somehow got the item as well as someone who greeded. Somehow it dupped the item and we got 2 of them while our healer got nothing. Really weird glitch & not sure what happened here or if it's dungeon/item specific or reproducible. 

**To Reproduce**

Haven't tried reproducing but I'll try to list the steps the best I can.
1) Be in a dungeon
2) Clear a boss & start a roll for an item
3) Have two people die before the roll starts
4) Have the three alive people roll greed on item
5) Have 1 of the dead release spirit without need/greed/passing on item
6) Have other dead person select need on item & release spirit before item timer runs out
7) See what happens next

Item: https://wowhead.com?item=https://www.wowhead.com/item=24390/ausleses-light-channeler&bonus=4097
Boss: https://www.wowhead.com/npc=17380/broggok

**Expected behavior**

The person who needed should of gotten the item, and we shouldn't of gotten two of said item

**Screenshots/videos**

https://imgur.com/a/cRDpg6o
![1_wowGlitch](https://user-images.githubusercontent.com/53105381/83168725-c8bcb300-a0c6-11ea-92a6-12227128a6d2.png)

**Comment by beraus** [comment]
Should be fixed with last update.
