### ISSUE TITLE
Iceblock / blizzard bug?

### ISSUE THREAD

**Issue by Rindback** [SunstriderEmu/BugTracker#3535]
**Describe the bug**

I do less damage with blizzard after I used iceblock. I do 71 damage per tick on blizzard without iceblock and between 39-41 damage per tick if I used iceblock.

It's like it changing the rank by it self from using rank 3 blizzard to rank 2 blizzard. Ive spoken with another mage and he has it aswell. Is it suppose to do that or what?

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Godmatik** [comment]
Never has happened to me...

Screenshots? What mobs you fighting?

**Comment by Jerrythemagicdog** [comment]
Damage is shared the more targets you Blizzard. This is different from Classic.
