### ISSUE TITLE
Unable to pick up Skywing escort quest after dropping

### ISSUE THREAD

**Issue by Superdragon59** [SunstriderEmu/BugTracker#3536]
**Describe the bug**
While attempting to complete Skywing escort quest in Terokkar forrest, Skywing disappeared before completion. I dropped the quest since it would not complete, expecting to pick it up again.

**To Reproduce**
Start Skywing quest.
Upon fighting the elite mob at the end, Skywing *may* disappear (I believe to fight mobs below platform).
Drop quest and attempt to pick back up.

https://www.wowhead.com/quest=10898/skywing

**Expected behavior**
Should be able to accept quest again after dropping.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2581
