### ISSUE TITLE
Scorpid Sting/Insect Swarm not stacking

### ISSUE THREAD

**Issue by mechanicsTBC** [SunstriderEmu/BugTracker#3537]
https://db.endless.gg/?spell=3043
https://db.endless.gg/?search=insect+swarm#abilities
Currently these abilities do not stack with each other.  If one of the two debuffs is on the target, applying the other one will remove the current debuff.  Both debuffs should be able to be applied to the boss at one time, but only the strongest % hit reduction debuff should take effect.  The % hit reduction portion of the debuffs should not stack, scorpid stings 5% should apply over insect swarms 2%.

missing something such as:
spell_group_stack_rules` SET `stack_rule`

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
