### ISSUE TITLE
Gas Cloud not reachable

### ISSUE THREAD

**Issue by Keritous** [SunstriderEmu/BugTracker#3538]
[Felmist](https://db.endless.gg/?npc=17407)  in Shadowmoon Valley @27, 40 is not accessible.
![WoWScrnShot_052920_113747](https://user-images.githubusercontent.com/66011356/83231741-3f2de380-a1a1-11ea-90c6-185d92574b55.jpg)

**Comment by Jerrythemagicdog** [comment]
Is it standing still? All of them have random movement so it should eventually path back to walkable terrain.

**Comment by Keritous** [comment]
> Is it standing still? All of them have random movement so it should eventually path back to walkable terrain.

Yes, It doesn't move at all.
