### ISSUE TITLE
Skettis // mobs

### ISSUE THREAD

**Issue by Tween00** [SunstriderEmu/BugTracker#3540]
Hi there,

I am sure you are aware, but in Terrokar Forest, in SKettis, there are no more water elementals / mobs around, except the tigers.
They disappeared a few days ago. A few people told me the same.
Any chance to fix it ? (It's definitely the best place to farm primal water for ex...)

Thanks and have a good one

**Comment by kelno** [comment]
Thanks for reporting.
They've been linked to the Sketti event, but I'll re add them with next update
