### ISSUE TITLE
[Arena] Merciless Gladiator's Right Ripper AP cost is too high

### ISSUE THREAD

**Issue by hanbi-wow** [SunstriderEmu/BugTracker#3541]
Merciless Gladiator's Right Ripper costs 3150 Arena Points.
All the other melee One-Hands at 2.6s speed cost 2625 Arena Points. 
The Fist OH is correctly priced at 1125 like the other off-hands.

![Cost](https://i.imgur.com/cBKk3pz.png)

The Fist is MH-only so its cost gets lumped in with the Spell Caster Mainhands (which cost 3150), even though it should have the same cost as the melee onehands (2625) for anything to make sense.

It's a melee weapon, it should have the same cost as the other melee 1h.

Wiki page on arena costs: 
https://wowwiki.fandom.com/wiki/Season_2_Arena_rewards#Price_history

> Merciless Gladiator's Melee Main Hand | 2625 
> Merciless Gladiator's Melee One Hand | 2625

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
