### ISSUE TITLE
[Item] The Medallion of Faith missing in the strongbox by Malor

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#3542]
**Describe the bug**
At step 3 below, Medallion of Faith should be inside the strongbox for completing the quest.

**To Reproduce**
1. Go and kill Malor the Zealous
2. Open up the strongbox
3. strongbox is empty

https://classic.wowhead.com/quest=5122/the-medallion-of-faith

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
