### ISSUE TITLE
4 piece set bonus on mana-etched doesn't work

### ISSUE THREAD

**Issue by lapleski** [SunstriderEmu/BugTracker#3543]
It said that this is a chance to gain 110 spd for 15 sec, but I didn't get it.
Check it please.

**Comment by Jerrythemagicdog** [comment]
![image](https://user-images.githubusercontent.com/46463908/83305512-d40ffb80-a1f8-11ea-9f7d-ba2caa2a901b.png)
Tested on a mage with Frostbolt.
What class are you playing?

**Comment by lapleski** [comment]
Got proc. It is very rare tho.
