### ISSUE TITLE
Al'ar: Dive Bomb

### ISSUE THREAD

**Issue by mechanicsTBC** [SunstriderEmu/BugTracker#3544]
Phase 2: After the meteor, Al'ar should spawn in the center of the room, not on the place the meteor hits.  Currently spawns on the place the meteor lands and casts rebirth, knocking people back.  Rebirth should only be used once when Al'ar revives at the start of Phase 2.

On prenerf Al'ar, he does not spawn on the dive bomb location, only in the center of the room and does not cast rebirth every time he appears.  

https://www.youtube.com/watch?v=_mSnUlSgigQ&feature=youtu.be&t=9m3s
https://www.youtube.com/watch?v=jDRA935sJ9A&feature=youtu.be&t=5m53s

Most likely when dive bomb got nerfed and no longer needed to be soaked by the raid, Al'ar was changed to also spawn at the location of the dive bomb.  The embers of alar should still continue to spawn at the location of the dive bomb.  This is not a big problem as the boss is still being killed easily, it's just not correct for prenerf version but adds additional difficult (which is fine if intended).

**Comment by Jerrythemagicdog** [comment]
Thanks, we're keeping it the way it is.
