### ISSUE TITLE
Void Reaver: Movement speed

### ISSUE THREAD

**Issue by mechanicsTBC** [SunstriderEmu/BugTracker#3545]
Void Reaver currently has too low base movement speed.  It is very easy for a range DPS to kite him if they over aggro or tanks die.  We had a tank die and I was able to kite the boss easily as a warlock only using 8% movement speed enchant on boots (no aspect, no potions, nothing special).  I am not referring to the enrage which has movement speed added to it.  Perhaps when he casts arcane orb he is standing still for a second? (can't recall), or his base movement speed is too low.

**Comment by Sheikthecatman** [comment]
Thanks! Void Reaver's movement speed has now been adjusted and has similar movement speed as other bosses do. 
Fix will be live next server restart.
