### ISSUE TITLE
Astromancer Lord: Mind Control

### ISSUE THREAD

**Issue by mechanicsTBC** [SunstriderEmu/BugTracker#3546]
https://db.endless.gg/?npc=20046
Astromancer Lord is currently casting Mind Control.  Should not be using mind control at all.
https://www.wowhead.com/npc=20046/astromancer-lord#abilities (post nerf, dragon breath was removed).
https://wowhead.project-nemesis.cz/?npc=20046
https://github.com/kelno/TBC-research/issues/20
https://db.endless.gg/?npc=20046#abilities

An educated guess is that https://db.endless.gg/?spell=37135 was incorrectly added to this mob.  Copied from https://db.endless.gg/?npc=20045#abilities NPC.  Astromancer Lord should not be casting any form of mind control.

**Comment by Jerrythemagicdog** [comment]
Intended, but thanks.
