### ISSUE TITLE
Seed of corruption explosion can be spell reflected

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3547]
1. Cast seed on mob A
2. Mob B casts spell reflect
3. Seed explodes
4. The warlock takes damage

I specifically noticed this behavior with bloodwarder protector in botanica, but spell reflect seems bugged as hell this server. but anywho spell reflect should not be able to reflect any aoe.

https://imgur.com/a/Cl1YxWU

**Comment by beraus** [comment]
Thanks, duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2336

**Comment by babno** [comment]
march 15th, wow.
