### ISSUE TITLE
[warlock] [imp] AI makes it run to melee

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3548]
It seems to delay casting for ~.5 seconds between each firebolt, using that time to run into melee range. It doesn't have a melee attack, and even if oom shouldnt run towards the target unless they're outside the 30 yard range for firebolt.

**Comment by Jerrythemagicdog** [comment]
The imp runs to the "optimal" spell range (max range of the spell -5y in our logic).

**Comment by babno** [comment]
That would be acceptable, but it'll run into melee range.

**Comment by Jerrythemagicdog** [comment]
Thanks, we'll look into it!

**Comment by babno** [comment]
![image](https://user-images.githubusercontent.com/244626/83702427-ab15af00-a5da-11ea-8662-49f8df419c39.png)

**Comment by Jerrythemagicdog** [comment]
Tested now, seems to have been fixed and the issue wasn't closed, thanks!
