### ISSUE TITLE
Grand Astromancer Capernian: Nether Protection 

### ISSUE THREAD

**Issue by mechanicsTBC** [SunstriderEmu/BugTracker#3549]
https://db.endless.gg/?npc=20062
Currently she can be tanked by a warlock using nether protection talent.  If nether protection procs on a warlock tanking her, she should stop casting on that warlock and attempt to melee attack the warlock.  Currently, she will continue to cast on the warlock that has nether protection up.

https://remedyguild.wordpress.com/tk-boss-strats/
https://forum.twguild.org/index.php?topic=4777.0
http://wowraidguide.blogspot.com/2008/05/prince-kaelthas-sunstrider-tactics-lord.html
https://authors.curseforge.com/forums/world-of-warcraft/official-addon-threads/general-addons/218225-freeme-mod-that-removes-buffs

This is more-so a server wide problem.  Nether protection should act as a "caster version" of blessing of protection.  If an NPC is casting fire/shadow spells on you and you gain nether protection, the NPC should attempt to physically attack (melee/ranged), if possible.  If the NPC can not physically attack (such as Illidan during demon form), then they will change targets.  

For that matter, it would be worth testing blessing of protection on a pure caster mob (Krosh Firehand would be good).  Blessing of protection should only make physical attacks not possible.  A pure casting only mob, such as Krosh Firehand, should not be effected by blessing of protection on his target at all.  I assume on endless that BoP will remove all threat.  Not really sure about BoP, but it's in the same category as nether protection and worth testing on while on the subject.

**Comment by kelno** [comment]
Thanks, that's interesting.
For the record BoP doesn't remove all threat but just suspend the player temporarily in the treat list.

This is indeed a general AI problem, one that I don't think we can fix soon without some very major rewrites. However if this mechanic is very important in some fights, we can add some checks for those.

**Comment by Jerrythemagicdog** [comment]
First three posts are copy pastes of each other, the fourth post seems to contradict those as well.
From what I understand the boss shouldn't run into melee but swap targets instead.

**Comment by kelno** [comment]
Fixed since in July
https://github.com/kelno/sunstrider/commit/45d3334685ab340dfa88c43224b20453ba5cb5fd
