### ISSUE TITLE
Vindication does not trigger Judgement of Wisdom

### ISSUE THREAD

**Issue by ZophosTheSavage** [SunstriderEmu/BugTracker#3553]
Vindication [](https://db.endless.gg/?spell=26021) has a physical trigger but the proc is a spell. This means that Vindication will not trigger the Seal a paladin is currently using like Seal of Command. It would however, for the entirety of TBC untill the makeover of Seal mechanics in WotLK, result in mana gains if the target was under the effect of Judgement of Wisdom since JoW works with spells as well.

I have been monitoring my mana gains with 3/3 Vindication and noticed no overall increase with this talent. I was also looking for double "+74 Mana" notifications when Vindication procs but saw none.

I played Paladin on retail and spending at least 1 point in Vindication for the extra mana was a common practice. Many of the posts on wowhead forums are gone because the authors have deleted their accounts.

I've managed to dig up a piece from Feb 2008 that mentions this mechanic.
https://imgur.com/zNcZlaf

This particular Retribution Paladin PoV from a Brutalus fight might also come in handy. 
There are a lot of "+74 Mana" pop-ups but you can clearly see multiple times in the video that without an Extra Attack from Windfury there are 2 or more +74 Mana notifications. For example when Arikah uses Crusader Strike and lands a Melee Attack there are two "+74 Mana" notifications and 0.5s after (on retail SoC and Vindication would proc 0.5s after the attack) while still on global cooldown, meaning no mana gains from any skills, we can see a yellow Immune (to Vindication) and another +74 Mana.

https://www.youtube.com/watch?v=UyooXkH6mT8

During a 9min boss fight Vindication can proc on average 15 times. This adds up to ~1110 mana. This may not seem like much but Retribution Paladins already have it hard without bugged talents.

**Comment by Rettiy** [comment]
#1714

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/4014
