### ISSUE TITLE
[gruuls lair] gronn-priest has extra ability, shadow shock

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3554]
https://imgur.com/a/b3cIM8v

Everything I can find says they have only 3 abilities. Fear, heal, and renew

https://70.wowfan.net/en/?npc=21350#abilities
https://www.wowdb.com/npcs/21350-gronn-priest#related:casts
https://wow.gamepedia.com/Gronn-Priest
https://www.wowhead.com/npc=21350/gronn-priest
https://wowwiki.fandom.com/wiki/Gronn-Priest

**Comment by Jerrythemagicdog** [comment]
Yes, they do, that's intentional.
