### ISSUE TITLE
[gruul's lair] Blindeye the Seer heals for too much

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3555]
https://wow.gamepedia.com/Blindeye_the_Seer
https://wowwiki.fandom.com/wiki/Blindeye_the_Seer

His heal should do ~50k and PoH does 100k. The heal instead is a full heal.

**Comment by kelno** [comment]
Thanks for reporting.
This is intended for content tuning, many heals in raid have been changed to be more dangerous to players.
