### ISSUE TITLE
[gruul's lair] agro dumping constantly with failed charge

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3557]
https://wowwiki.fandom.com/wiki/Lair_Brute

The strategy should be to have everyone inside the minimum range for charge, therefor he never charges and never drops agro. However when attempting this he seemed to drop agro every second or so. What I suspect is happening is the function for charge is called, first he drops agro, then attempts to find a target to charge, cannot find one, ability fails and no cooldown is triggered enabling him to attempt to charge again, but still dropping agro each time.

**Comment by kelno** [comment]
Thanks for reporting.
After investigating, he just drop threats every time he would cast a charge, regardless if the cast was successful. That's just it.

**Comment by kelno** [comment]
Fixed with next server update
