### ISSUE TITLE
[QUEST] Nefarius's Corruption

### ISSUE THREAD

**Issue by LSD7** [SunstriderEmu/BugTracker#3559]
**Describe the bug**
Vaelastrasz the Corrupt https://classic.wowhead.com/npc=13020/vaelastrasz-the-corrupt in BWL doesn't give the quest Nefarius's Corruption https://classic.wowhead.com/quest=8730/nefariuss-corruption

**To Reproduce**
1. Complete prequest https://classic.wowhead.com/quest=8555/the-charge-of-the-dragonflights
2.  Go to BWL and try to take quest https://classic.wowhead.com/quest=8730/nefariuss-corruption

**Expected behavior**
https://www.youtube.com/watch?v=3wKtj1KcH24

**Comment by Jerrythemagicdog** [comment]
Thanks fixed last update!

**Comment by LSD7** [comment]
@Jerrythemagicdog oh, thanks. There is similary bug https://github.com/SunstriderEmu/BugTracker/issues/3477. It would be pretty good, if you have enough time for fixing. Thanks.
