### ISSUE TITLE
Incorrect mob weapon sounds

### ISSUE THREAD

**Issue by steak-house** [SunstriderEmu/BugTracker#3565]
**Describe the bug**
Some mob weapons don't make the correct sound when they hit the player.
Examples : 
Staves make the 1h sword sound (test with Shattered Hand Neophyte : https://www.wowhead.com/npc=19410/shattered-hand-neophyte)
1h swords make the 1h axe sound (test with Unyielding Footman https://www.wowhead.com/npc=16904/unyielding-footman)
2h swords make the 2h axe sound (test with Durnholde Sentry : https://www.wowhead.com/npc=17819/durnholde-sentry)

I imagine there are others but I couldn't find a mob with a dagger, a polearm, or maces. Please do test it though !

Axes work fine.

**Comment by steak-house** [comment]
Update on this : "slicing" fist weapons, like the claws used by Shienor Talonite (https://www.wowhead.com/npc=18449/shienor-talonite) make the 2h axe sound

**Comment by steak-house** [comment]
Polearms also make the 2H axe sound, tested with Sand Gnome https://www.wowhead.com/npc=22483/sand-gnome#comments

**Comment by steak-house** [comment]
Daggers also make the 2H axe sound, tested with Tuurem Scavenger https://www.wowhead.com/npc=18456/tuurem-scavenger

**Comment by hufsa** [comment]
Thanks, fixed with next update.
