### ISSUE TITLE
Deadly Throw -> Ruthlessness

### ISSUE THREAD

**Issue by Ch33z0r** [SunstriderEmu/BugTracker#3566]
**Describe the bug**
The rogue talent ruthlessness from assassination which should give with 60 % chance a combo point back after using any finishing move does not occur on deadly throw. Relentless Strikes on the other hand (which gives per Combo Point 20% Chance to give 25 Energy back) does work.

**To Reproduce**
Build a Combo Point on  your Target
Use Deadly Throw
did 20+ throws to test and never got a combo Point back.

**Expected behavior**
60% of the time i should get a Combo Point back

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1129
