### ISSUE TITLE
Mobs have no gcd

### ISSUE THREAD

**Issue by NeonicSupersonic** [SunstriderEmu/BugTracker#3568]
Mobs can use their abilities ignoring things such as swing timers and gcd rules.

I dont have logs in my disposal but you can pull any mob  with notable amount of abilities to see  for yourself how it uses multiple abilities in less than 1 second window, which shouldnt be possible.

While this bug is bad overall, it especially bad in raid environment. Since not all trash was born equal trash mobs which have 2+ different damaging abilities recieve most benefits from being able to use them without gcd. Fighting such trash presents nonsensical situations of t5 geared tanks dying in 1(**one**) global on bad avoidance rolls as well as low hp raid members facing unavoidable death from instant raid-damaging ability combos.

Notable examples are:
https://db.endless.gg/?npc=20046
(Combo of melee, fire blast, dragon breath, volley all in 1 gcd dropping tanks to 10% hp on pull)
https://db.endless.gg/?npc=20031
(melee, cleave, thirst 1 global raping tanks. I am fairly certain that cleave supposed to be exclusive with melee swing as well in a similar way it functions for players, even mag cleave has "on next swing" tag https://www.wowhead.com/spell=30619/cleave).
https://db.endless.gg/?npc=21228
(shock, bolt. melee 1 global). Due to damage being mostly magical tanks can die to this instantly the moment they are breaking mob from sheep.
https://db.endless.gg/?npc=21230
(volley, blink into the raid, lightning oneshots low hp targets on pull)

While I dont mind difficult trash, gcd bug makes some trash much more difficult compared to how it supposed to be (keeping tuning in mind), entirely changing raid approach to some packs. For example, moro murloc trash cant be aoe tanked -AT ALL- even when you overgear content. And its not a problem of tuning, since even with current buffed damage numbers AoE tanking murlocs should be possible. If they had correct gcd to limit their burst potential, that is.

It also causes random mostly unavoidable deaths from spikes of raid damage and random wipes to tanks dying from full to zero on bad avoidance rolls (which, while fairly rare, happen).

Fix that crap or nerf trash with multiple damaging abilities into the ground.

**Comment by NeonicSupersonic** [comment]
![anynogcd](https://user-images.githubusercontent.com/45077198/83705850-ad99f800-a61e-11ea-9218-a4b385e2c432.jpg)

Some graphical illustration

**Comment by frastsytt** [comment]
Alot of the player complaints about raid difficulty etc. can be rooted down to this faulty mechanic tbh. Should be a top priority.

**Comment by dadshers** [comment]
Adding to this
![image](https://user-images.githubusercontent.com/61527914/84615943-9c0ae880-ae87-11ea-8d2e-6ce3a13dcb7d.png)

**Comment by kelno** [comment]
Experimentally made a change here to add a GCD to most creatures, applied with next server update
