### ISSUE TITLE
Stratholm: Ramstein didn't spawn

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#3569]
**Describe the bug**
In Stratholm, after clearing the Slaughter Square spewers and belchers, Ramstein didn't spawn. The door to Baron Rivendare(?) didn't open. The gate back out was still down. Unable to do quest Ramstein. Happened twice to me.

**To Reproduce**
1. Clear the Slaughter Square free of spewers and belchers.
2. .........

![WoWScrnShot_053020_194342](https://user-images.githubusercontent.com/61659496/83341194-69b99280-a2ae-11ea-9465-607b3bc3f7bc.jpg)

![WoWScrnShot_053020_194346](https://user-images.githubusercontent.com/61659496/83341195-6f16dd00-a2ae-11ea-8ae0-ae700ee4939c.jpg)

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in next server restart.

**Comment by EL100** [comment]
Just tried again. Ramstein didn't spawn. The outer door to Baron was opened, but the inner door was still closed. I sent in pet to draw baron out was able to kill him. The gate back out to the square was still down.

**Comment by Sheikthecatman** [comment]
I just attempted this and it worked fine.

**Comment by EL100** [comment]
So far it's happened to me 3 times. Trust me I really want to get rid of the quest. Maybe it's got to do with I'm soloing this as a hunter and FD'ed a couple of times in the encounter? My pet kept the aggro though.

**Comment by Sheikthecatman** [comment]
I attempted this on my local again, as a hunter and using FD while clearing the abominations surrounding the Slaughterhouse, I was able to get Ramstein to spawn without any issues. You have to kill every single abomination in the area for him to spawn and when he dies he opens the door to baron.

**Comment by Sheikthecatman** [comment]
If you are able to, could you supply a video of you clearing everything to this event? That way I could get a better view of what might be going wrong.

**Comment by matejchi** [comment]
Ramstein didn't spawn 3 runs in a row for me, can you please make it so it opens once you kill the abominations, if you cant fix it?
