### ISSUE TITLE
[QUEST] The Spider God

### ISSUE THREAD

**Issue by Lamberdo** [SunstriderEmu/BugTracker#3572]
When we kill Theka the Martyr we cant read from the Tablet of Theka name need to coplete the quest

**Comment by InhumanGM** [comment]
I was able to read the tablet without any issues, is there any further information you can provide to reproduce the issue?

**Comment by Lamberdo** [comment]
i can click on the tablet but quest want be complete;/

**Comment by InhumanGM** [comment]
I'm still unable to reproduce this issue. Have you tried relogging?

**Comment by Jerrythemagicdog** [comment]
Unable to reproduce.
