### ISSUE TITLE
Quest broken: The Root of All Evil

### ISSUE THREAD

**Issue by Randalierer** [SunstriderEmu/BugTracker#3574]
**Describe the bug**

I kill the demon, but i cant loot Essence of Xandivious.
I'm not in a raid group

**To Reproduce**

1. Kill demon
2. Still Cant loot.

Item: https://wowhead.com/item=21145/essence-of-xandivious
Mob: https://wowhead.com/npc=15623/xandivious

**Expected behavior**

corpse of demon should contain the essence of xandivious

**Screenshots/videos**

**Additional context**

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in [8fcafe7b1918b5e3f22222007e8e33f48b6dabf8](https://github.com/kelno/sunstrider-scripts/commit/8fcafe7b1918b5e3f22222007e8e33f48b6dabf8).
The fix will be live next server update.
