### ISSUE TITLE
Rating needed to buy s3/s4 from next update  1550 leg 1600 chest 1700 head etc 1800 weaps

### ISSUE THREAD

**Issue by modzel1414** [SunstriderEmu/BugTracker#3576]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by modzel1414** [comment]
is it a good idea or not?

**Comment by steak-house** [comment]
I really don't understand what you're trying to say here. Are you suggesting that S3 and S4 be released early, but be kept behind rating requirements ?

**Comment by modzel1414** [comment]
> I really don't understand what you're trying to say here. Are you suggesting that S3 and S4 be released early, but be kept behind rating requirements ?
I want to s3 and s4 be for rating. In PvP u have only rating to make it fun, so lets make gearing a bit harder.

**Comment by Jerrythemagicdog** [comment]
This is really not the place or time for suggestions like these, but thanks anyway, we'll see what's ahead of us!
