### ISSUE TITLE
High level arrows on low level characters.

### ISSUE THREAD

**Issue by Chise-Hatorii** [SunstriderEmu/BugTracker#3577]
1. Go to outpost town where you can kite and attack a mob that has a mailbox (I used Camp Turajo since you can kite mobs without them dying to guards or alternatively duel someone)
2. Have 1 arrow (of a specific type, rough arrow being the cheapest to buy)
3. Open mailbox, hold left click but do not take the arrows
4. Use last arrow (with auto shot, as this can only be done with a hunter)
5. Take arrows immediately from the mailbox so it goes into the same arrow slot as the original arrow you were using. 
I don't know what happened, but I'm guessing since it went into the same inventory slot as the old arrows, It thought it should keep using the same location in the code? I ended up with Thorium Arrows on level 34 and it lasted until i ran out.

**Comment by z5n** [comment]
unable to reproduce
