### ISSUE TITLE
Rogue combo points using Evasion and Setup

### ISSUE THREAD

**Issue by CoffeeTeaPat** [SunstriderEmu/BugTracker#3579]
Bug using Evasion with the Subtlety talent Setup.

When using Evasion with Setup and once the target reaches 5 combo points, if another combo point is earned the total combo points on the target resets to 0.

If Evasion is not used the combo points do not reset if another combo point is gained after 5, the combo points remain at 5.

Only Evasion resets the combo points if another combo point is earned after 5 points.

**Comment by hufsa** [comment]
Thanks, fixed with next update.
