### ISSUE TITLE
Shortsword of Vengeance

### ISSUE THREAD

**Issue by CoffeeTeaPat** [SunstriderEmu/BugTracker#3580]
Chance on hit: Smites the enemy for 30 holy damage.

There is a bug with the smite, 95% of enemies resist the smite. Low, equal or high level.

**Comment by steak-house** [comment]
It's noteworthy that that seems like a core bug as Holy damage is supposed to be unresistable.

**Comment by mchayes** [comment]
I'll have to dig some combatlog, but last kara on my paladin I've seen consecrate partially resisting, not sure if there is some specific mob in there that should but hey..

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3461
