### ISSUE TITLE
Mob respawn timer is too low, ensues a bad time for solo leveling

### ISSUE THREAD

**Issue by Ryquard** [SunstriderEmu/BugTracker#3583]
**Describe the bug**
I'm at level 30 with some friends, we **need** to quest together because otherwise all nearby mobs will stomp us to the ground as the respawn timer is too quick, im not sure how quick is it, but it feels like less than a minute, which in closed places makes a huge deal, as they tend to be packed toghether which add to the aggro issues and chain pull that i've seen in other's reports as this seem to cause a snowball effect. Other issue this quick respawn causes is that is futile to do current content (killing mobs at you level) due to being overwhelmed by quantity, as you are fighting with one and then a couple of them respawn quick and then you are dead

**To Reproduce**

1. Go to any mob pack specially in a closed space, as any cave or building in Hillsbrad Foothills and kill some of them. Try to do this at the same level range as your character.
2. Try to survive the wave of angry humans, or dwarves or spider or naga in a futile endeavor to survive as the one that you killed a first is already alive while its old corpse is still there
3. Get mad that you have to walk all over again from the spirit healer and try again with some friends, and still happens, you need at least a 4 man party to survive some escenarios

**Expected behavior**
All that is needed to dampen this is to match the respawn timer to be a bit over 30 seconds after the corpse dissapears as ive notticed that all times the old corpse is still there and the monster has already respawned, you can pile up to 2 corpses in the same spot.
In resume mobs should respawn only after their old corpse has despawned. Corpse despawn rate is ok,

**Additional context**
This combined with the extended aggro and aggro from low level monsters can make difficult even helping a friend with a 10 level difference

**Comment by steak-house** [comment]
People complain about the respawn timer being too short almost every day, please increase it !!
