### ISSUE TITLE
Bug Loot on Gruul

### ISSUE THREAD

**Issue by Terobore** [SunstriderEmu/BugTracker#3584]
HI, we killed gruul with guilde. We looted the gloves for hunter. But our hunt was not in the list to get the loot.

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

ITEM  = https://www.thegeekcrusade-serveur.com/db/?item=28827
PLayer = https://endless.gg/armory/character/tinelonf

I took the gloves. Is it possible to give theme to Tinelonf ? 

https://media.discordapp.net/attachments/699618703012266086/717117950204706927/unknown.png
Here you can see that we can't find Tinelonf in the list.

Thanks for your help.

**Comment by beraus** [comment]
The player needs to be in range and online.
