### ISSUE TITLE
Mage Food table - the limit

### ISSUE THREAD

**Issue by Keritous** [SunstriderEmu/BugTracker#3585]
[Conjured Manna Biscuit](https://db.endless.gg/?item=34062)
the limit (unique) is 80.
![WoWScrnShot_060120_232258](https://user-images.githubusercontent.com/66011356/83455605-763b1800-a473-11ea-80c9-0ae3bae50e88.jpg)
In situation like this, (I have 65x) when I click I should be able to get that amount of food(15) until reaching the  limit which is 80, but here it says "You can't carry any more of those items"

**Comment by InhumanGM** [comment]
The table only adds this item to your inventory in stacks of 20, so it shouldn't fill your inventory by clicking when you have 65 already. Instead, you would have to destroy the stack of 5, then click on the table for the last stack of 20.
