### ISSUE TITLE
Warlord Kalitresh's use of Impale is very inconsistent, making the fight trivial

### ISSUE THREAD

**Issue by steak-house** [SunstriderEmu/BugTracker#3586]
**Describe the bug**
I ran Steamvault normal mode 5 times in the past two days, as the main healer. In these 5 runs, Warlord Kalitresh, the final boss, only cast his Impale bleed attack twice : both times were on the last try. Every other try I finished the fight with more mana than what I started with despite having garbage healing gear.
To illustrate this, I didn't even know Kalitresh had Impale until this very last run.

**To Reproduce**
1. Engage Warlord Kalitresh in Steamvault Normal.
2. Observe his infrequent use of Impale
Note : I usualy stay in melee range for this fight to try to proc Omen of Clarity, and this might be why he never hit me with Impale til my last try (where I stayed far away). Nevertheless, even if Impale has a minimum range (which i don't think it does), it shouldn't always aim for the healer.

Mob : https://www.wowhead.com/npc=17798/warlord-kalithresh#comments
I couldn't find the ID of his Impale :(

**Expected behavior**
Impale should be cast periodically, on any group member that isn't the tank, every few seconds ; frequently enough that it should stack if cast twice on the same party member.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
