### ISSUE TITLE
"Withered Flesh" quest drop rate

### ISSUE THREAD

**Issue by hidvegigabor** [SunstriderEmu/BugTracker#3587]
The quest "Withered Flesh" in Zangarmarsh has a very low quest item drop rate compared to other quests. Usually quest items have around 100% drop rates.

I've done this quest several times on different characters. Yesterday it took 45 minutes to collect the 5 parched hydra samples and boglord samples. It doesn't help as well that many people farm the area for motes of life.

To balance, either all other quest items' drop rate should be lowered, or these items' drop late should be raised.

**Comment by beraus** [comment]
[WowHead](https://www.wowhead.com/quest=10355/withered-flesh#comments:id=22854)
[Jerry](https://github.com/SunstriderEmu/BugTracker/issues/1833)

**Comment by TheGreyMouser** [comment]
wowhead states boglord tendrils 30% drop rate.  At this time I have 14 while doing this quest.  Wowhead also states, withered boglord tendrils 16% drop rate.  I have ONE!  Random numbers alone should have yielded 7 out of aprox 30 withered bog lords killed.  Mote of life have a  higher drop rate!  https://www.wowhead.com/item=29481/withered-bog-lord-sample
