### ISSUE TITLE
"Disrupt their reinforcements" quest difficulties

### ISSUE THREAD

**Issue by hidvegigabor** [SunstriderEmu/BugTracker#3588]
In Hellfire Peninsula the "Disrupt their reinforcements" quest is really hard to solo. Not only the Wrathguards have a very high respawn rate, they have an extremely powerful spell, which has a damage of several hundred hit points per second, lasts about 10 seconds. Character classes without interrupt (for example, druids get incapacitate at level 62) can be devastated with it in a few seconds.

I think it would be advisable to lower the damage of the spell to the tenth, and lower the respawn rate in the area.

**Comment by beraus** [comment]
Thanks, we'll take this into consideration
