### ISSUE TITLE
the Destro warlock problem

### ISSUE THREAD

**Issue by SifoDyas123** [SunstriderEmu/BugTracker#3589]
Almost no one plays for Destro warlocks.
Please fix the spells Shadowburn and Soul Fire that would have them in the arena, battlegrounds and duels are not spent shards of souls, as it is real after 2-3 duels are spent on 12-15 shards of souls

**Comment by Jerrythemagicdog** [comment]
Arenas and Battlegrounds already don't consume Soul Shards, neither do duels in the duel area.

**Comment by SifoDyas123** [comment]
> Арены и поля сражений уже не потребляют Осколки души, как и дуэли в дуэльных зонах (перед Оргриммаром и Штормградом).
Have you used these two spells for a long time? go to the game and check again. Don't talk about what you don't know
