### ISSUE TITLE
Investigate the Blue Recluse

### ISSUE THREAD

**Issue by bigbeansjm18** [SunstriderEmu/BugTracker#3590]
I use the cantation to summon 2 rift spawns. Once depleting their health they are stunned. I click on the Chest to bring out the device to capture them but it says I cannot use it yet. I have looked at videos online and I am doing it correct.

**Comment by bigbeansjm18** [comment]
Also after dying and abandoning the quest the spawns still follow me. 
https://ibb.co/vXxT398

**Comment by InhumanGM** [comment]
Duplicate of #1907
