### ISSUE TITLE
Help Tavara Quest

### ISSUE THREAD

**Issue by mamicatamu** [SunstriderEmu/BugTracker#3591]
Tavara is already at full hp, not needing any healing at all.

https://www.wowhead.com/quest=9586/help-tavara

Tavara should be low on hp and should accept heals from the player.

**Comment by Hanamizu33** [comment]
It's not working for me :( tried everything already and it's not working for me

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in [8fbff3f8dcfd7bbc2752e2b82cafc98c00e96aa0](https://github.com/kelno/sunstrider-scripts/commit/8fbff3f8dcfd7bbc2752e2b82cafc98c00e96aa0). The fix will be live next restart!
