### ISSUE TITLE
Rogue Shiv school 

### ISSUE THREAD

**Issue by yolobugger** [SunstriderEmu/BugTracker#3592]
**Describe the bug**
Rogue shiv ability seems to be a magic school rather than physical, getting too many resist in a row(up to3) with 10% hit rating. Or maybe there’s too many resists in general for shiv.

https://tbcdb.com/?spell=5938

**Comment by Jerrythemagicdog** [comment]
Poisons are rolled on spell hit rating which explains why you encounter resists (3% to resist right off the bat), especially against Warlocks with higher resistances. Some players choose to use spell penetration to counter that. For better or worse it's a part of the game. 
Shiv only guarantees a proc of the poison, the poison then still can be resisted.
Thanks for the issue though.
