### ISSUE TITLE
Pet autocast abilities stops working after trying to manually use any pet ability when it's on CD.

### ISSUE THREAD

**Issue by bjh368** [SunstriderEmu/BugTracker#3594]
When I send my pet in to attack I've macroed it to use Dive/Dash as it runs in, but I don't have them on autocast in order to not waste focus while pet is attacking stationary. 

If my pet has Dive/Dash on cooldown when I tell it to attack something, using the same pet macro with Dive/Dash, it will stop autocasting abilities completely, until I either; use the attack macro when Dive/Dash is available again, if I use normal Petattack without the Dive/Dash macroed together, or if I _manually_ tell it to use an ability (any ability will fix it, as long as it is successful) just enabling an autocast does not fix it.

If I have Dive/Dash on autocast as well, It will simply stop using abilities until Dive/Dash is off cooldown and gets autocasted, and will then continue to use Dive/Dash on CD, but will still ignore _the other_ autocasted abilities.

Testing further; this behavior also happens if I tell it to use Bite instead of Dive/Dash (as it has a CD as well). **So the issue seems to be that it gets stuck trying to cast something that is on CD and it just breaks the whole autocast system.**

This issue is minor _if the player is aware_ of it happening. It requires some awareness, and on fights with a lot of target swapping, such as attacking the elementals on Vashj, you need to adjust your Dive/Dash and Petattack usage. If the player is _not_ aware of this, they will _lose_ a bunch of dps if they try to _gain_ dps by not wasting focus. 

Putting focus dumps in your steady shot macro works as a band-aid IF you are attacking the same target as your pet. If the pet is on a different target it will instantly swap to your current target if you tell it to use a focus dump ability. **Don't do this, see update below**

(This issue should be easy to reproduce, just manually cast Dive/Dash/Bite when its on CD, and your pet is attacking something, and you will notice that it stops autocasting abilities.)

**Comment by bjh368** [comment]
Just a little update:

Double tapping an ability without CD, such as Claw, can also stop the Autocast from working in the same way. So putting focus dump in your spam macro is NOT a good idea.

**Comment by bjh368** [comment]
Update2:

The easy and (should've been more) obvious player side band-aid fix is to put /petattack after Dash/Dive in your macro. 

But hey I wouldn't have noticed this bug otherwise ¯\\\_(ツ)_/¯

**Comment by Jerrythemagicdog** [comment]
Thanks for the details here, very well described!

**Comment by DwarvenJoe** [comment]
> Update2:
> 
> The easy and (should've been more) obvious player side band-aid fix is to put /petattack after Dash/Dive in your macro.
> 
> But hey I wouldn't have noticed this bug otherwise ¯\_(ツ)_/¯

Had the same issue, could also mention if you add /petattack both before and after dive/dash you also get rid of the pets slow/jerky reaction when using it so they move right away.

**Comment by kelno** [comment]
Thanks for the very specific report.
Fixed with next server update
