### ISSUE TITLE
Curing the Sick Quest not progressing

### ISSUE THREAD

**Issue by WVLeeuw** [SunstriderEmu/BugTracker#3595]
**Describe the bug**
No progression can be gained toward Curing the Sick, a level 14 Druid quest. The objective of the quest is to cure 10 sickly deer, though whenever you cure a deer given the quest item, no progress will be gained toward the quest objective.

**To Reproduce**
1. Start Curing the Sick on a Druid after completing Lessons Anew, The Principal Source, and Gathering the Cure, in that order and attempt to cure a deer.

Quest: https://classic.wowhead.com/quest=6124/curing-the-sick 

**Expected behavior**
After curing a deer, the player should gain progression toward the quest objective.

**Screenshots/videos**
Omitted. The description should be clear as is.

**Additional context**
Not applicable.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
