### ISSUE TITLE
Inner fire charges get consumed by wrong abilities

### ISSUE THREAD

**Issue by Kraizn** [SunstriderEmu/BugTracker#3597]
**Describe the bug**
The Priest armor buff "Inner Fire" get stacks consumed by abilties other then melee/ranged weapon hits. For example Rogue Rupture and Garrote application consume one charge of inner fire before even any damage was dealt. But these abilities are not supposed to consume charges of inner fire at all.

**To Reproduce**

1. Priest cast Inner fire so it has fresh 20 charges.
2. Priest cast Power Word: Shield
3. Rogue cast garrote on Priest
4. See Inner Fire charge instantly lose a charge on garrote application before even the shield got destroyed by auto attacks.
5. Same story for rupture.

**Expected behavior**
Inner fire Tooltip says: "... Each melee or ranged damage hit against the priest will remove one charge. ..." .So just applying a dot without doing damage with melee weapon is not supposed to consume a charge, specially not through a shield....

**Screenshots/videos**

**Additional context**
I only recognized this issue for these 2 rogue abilties. Maybe there are more abilties that causes this issue though.

**Comment by Jerrythemagicdog** [comment]
Thanks, just in case there is any doubt, proof: https://youtu.be/QyTyNaiEJKs?t=162

**Comment by kelno** [comment]
Thanks for reporting, fixed with next server update
