### ISSUE TITLE
Corpse after releasing

### ISSUE THREAD

**Issue by Keritous** [SunstriderEmu/BugTracker#3598]
These two have released and are alive but the corpses are still on the ground.
![WoWScrnShot_060320_000837](https://user-images.githubusercontent.com/66011356/83617001-ba2a3c00-a59d-11ea-8b97-c5086cef7782.jpg)

**Comment by kelno** [comment]
Any idea how that happens? We tried before but couldn't find reproduce steps

**Comment by Keritous** [comment]
> Any idea how that happens? We tried before but couldn't find reproduce steps

I think those people had quitted the game by pressing Alt+F4 to survive the wipe but they died.

**Comment by kelno** [comment]
Can't reproduce, please open a new issue if you see this one again.
