### ISSUE TITLE
Darkmoon Faire Agility Buff

### ISSUE THREAD

**Issue by Mikex840** [SunstriderEmu/BugTracker#3599]
When talking to Sayge, selecting the 3rd option twice should grant the "Sayge's Dark Fortune of Agility" buff. This worked multiple times during May's Faire but does not seem to be working this month. When selecting the 3rd option twice, a fortune item is given but the buff is not.

I tried selecting the first option twice in order to get "Sayge's Dark Fortune of Damage" and that provided and buff and item as intended. I tried to get the Agility buff later on after that but the same issue occurred so the issue seems to be specific to Agility.

**Comment by Mikex840** [comment]
Problem is still going on, it seems like stat-related buffs are being resisted when Sayge casts them onto a player. Dark Fortune of Damage never resists, but Agility seems to every time.

![Darkmoon Faire Buff Resisted](https://user-images.githubusercontent.com/66372240/91987165-b1abe380-ecfb-11ea-8f6a-e10de36bb034.PNG)

**Comment by Jerrythemagicdog** [comment]
Thanks!
Fixed with next update.
