### ISSUE TITLE
Horrible Druid Epic Flightform Quest Bug! HELP!!!

### ISSUE THREAD

**Issue by Nekx-drOOd** [SunstriderEmu/BugTracker#3600]
![WoW The Hawk's Essence](https://user-images.githubusercontent.com/66377940/83659443-8cd79100-a591-11ea-8a51-8b12d78762c1.jpg)

I am trying to complete the epic flightform quest chain for my druid. I finally finished the 3rd trial (Hawk's Essence) and have both the whistle & essence in my bag, with the quest tracker showing it as complete, as you can see in the screenshot.

The server disconnected me right after I looted the mob. When I returned to the game and flew back to the quest giver (with both items in my bag) she has a grayed out "?" over her head and won't let me turn it in to get the next quest in the chain. That was a VERY difficult encounter as my two specs are feral & resto and you have to defeat the boss as a damage spell caster, so I died a couple times.

Can you **PLEASE** help me? I'd **REALLY** like to move on to the end of the quest chain ASAP!!!

Thanks!
Mike (Nekx) on Endless.gg TBC server

**Comment by Jerrythemagicdog** [comment]
Resolved in game.

**Comment by Nekx-drOOd** [comment]
Lifesaver! Thanks so much!
