### ISSUE TITLE
Mage mana shield bug

### ISSUE THREAD

**Issue by xatheros** [SunstriderEmu/BugTracker#3601]
Mana shield rank 7 (last one) should absorb 715 damage and burn 2.0 mana per point of damage absorbed (1430 total mana). I tested it in both pve and pvp and it burns like 4500 total mana and does not seem to be absorbing damage at all

**Comment by Jerrythemagicdog** [comment]
Mana shield scales with your spell damage (at a 0.5 coefficient) so it's expected that it absorbs and consumes more mana than the tooltip value.
