### ISSUE TITLE
Shaman Fire,Air,Water Totem

### ISSUE THREAD

**Issue by Keritous** [SunstriderEmu/BugTracker#3602]
haven't done the quests so don't have the Totems yet I'm able to put the totem.
![WoWScrnShot_060320_212140](https://user-images.githubusercontent.com/66011356/83665910-5cb7de80-a5e1-11ea-9729-d24a4066247d.jpg)
![WoWScrnShot_060320_212137](https://user-images.githubusercontent.com/66011356/83665918-5e81a200-a5e1-11ea-911a-750e3011002e.jpg)
![WoWScrnShot_060320_212158](https://user-images.githubusercontent.com/66011356/83665920-5f1a3880-a5e1-11ea-9ac8-770e739f4825.jpg)

**Comment by Jerrythemagicdog** [comment]
Yes, because of a totem you have equipped in your Totem slot in your character's inventory. It's a WotLK leftover we have but we've decided to let it be there for convenience's sake. Thanks for the report though!
