### ISSUE TITLE
Problem with a succubus on BG

### ISSUE THREAD

**Issue by SifoDyas123** [SunstriderEmu/BugTracker#3604]
1. When resurrected on BG, very often, the succubus is resurrected without mana.
fix it to be complete
2. On BG if warlock on mount with daemon, then daemon for him not has time and under Dismounting daemon it turns out far from warlock.
Fix that the demon did not run after the mount, and appeared when the warlock dismounts.

**Comment by kelno** [comment]
Should be fixed with https://github.com/kelno/sunstrider/commit/e907bcc7598d7f0e99d7946988694b5dfb6c103b
