### ISSUE TITLE
Martyrdom procc focused casting doesnt effect the causing critical hit

### ISSUE THREAD

**Issue by Kraizn** [SunstriderEmu/BugTracker#3605]
**Describe the bug**
Martyrdom procc wich gains focused casting buff to the priest doesnt effect the pushback of the swing that actually caused the procc. 

**To Reproduce**

1. Priest (2/2 Martyrdom specced) casts greater Heal
2. Priest Enemy (Rogue, Warrior) melee hit Priest until crit happens while priest casts the greater Heal (optional: apply mindnumb poison by rogue)
3. Observe the pushback on the casts when crit happens

Spell: https://classic.wowhead.com/spell=14774/martyrdom

**Expected behavior**
The critical hit that causes focused casting buff from martyrdom is already supposed to be effected by that buff so it should not pushback the cast.

**Screenshots/videos**
https://youtu.be/w0CrmZygCuY?t=453
Priest is casting massdispel (at min7:34) and gets a pushback by a non critical hit for 846 dmg  (u can see in the unit frame portrait) - after that a critical strike for 1548 dmg lands and the massdispel cast didnt get another pushback because focused casting already is taken into account for this hit.

https://youtu.be/6JjgpeS0YDU?t=364
Here at min 6:07 Druid is hiting the priest for 633 non crit which push back the mindflay channeling for a tick and after a crit for 559 dmg is not pushing back the cast further.

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Any source on that as to why it would work that way?

**Comment by Kraizn** [comment]
> Any source on that as to why it would work that way?

yes i did link one

**Comment by Kraizn** [comment]
https://youtu.be/tudgj2UXYVg?t=151

This issue can be closed. The other scence i linked were most likely effected by the hidden crit calculation (https://github.com/SunstriderEmu/BugTracker/issues/1425) and proccing martyrdom from a non-crit before actualy crit happened. Would be nice to see a fix on issue #1425 though.

**Comment by kelno** [comment]
Thanks
