### ISSUE TITLE
Not able to cast on stealthed target when mindvision channeling

### ISSUE THREAD

**Issue by Kraizn** [SunstriderEmu/BugTracker#3606]
**Describe the bug**
Channeling mind vision cast on stealthed enemy is not allowing to cast on enemy with instant spell.

**To Reproduce**

1. Priest casts mind vision on rogue while he is visible
2. Rogue stealths while mind vision channeling
3. Priest try to cast a harmfull instant spell on enemy rogue (tested with shadow word:pain)
4. Mind vision will break channeling but no effect of the cast will happen

Spell: https://classic.wowhead.com/spell=10909/mind-vision

**Expected behavior**
It should be possible to cast instant spells out of the mind vision channeling as long as the enemy is targeted and in range even if stealth is active.

**Screenshots/videos**
https://youtu.be/QyTyNaiEJKs?t=604

**Additional context**
Casting out of mind vision channeling against nostealth targets has no issues.

**Comment by z5n** [comment]
duplicate of #1697
