### ISSUE TITLE
Rogue talent "Find weakness" doesn't work on envenom

### ISSUE THREAD

**Issue by tbxgame** [SunstriderEmu/BugTracker#3608]
Rogue assasin talent:Find weakness,doesnt work on envenom,eviscerate.
cold blood not working on mutilate,cant crit both hand.
and when mutilat crit both hand ,rogue get 4 CP ,it should be 3 CP no matter crit 1 hand or both hands.seems like mutilate spell is made of 2 spells that cast in the same moment.
i think this is why u cant fix mutilat,u may made a algorithm that separate 2 hands,but its one spell, should be calculate together.
hope this is helpful.
best wishes to you!

**Comment by kelno** [comment]
For cold blood : https://github.com/SunstriderEmu/BugTracker/issues/1496

**Comment by kelno** [comment]
Fixed with next server update
