### ISSUE TITLE
warlock pet bar dissappears after using non-permenant pet

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3609]
Most notable is eye of killrog, but things like karazahn chess will also cause it to happen. As you can see I still get the blood pact buff, and I can dark pact, but can't tell it to attack or buff with fire shield as the pet bar is gone

![image](https://user-images.githubusercontent.com/244626/83708410-364a7100-a5ea-11ea-9d24-71cdae6f45f9.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with 09099c8e5771c13c0deceb3a760b21d3dff6c23b
https://github.com/SunstriderEmu/BugTracker/issues/2813
