### ISSUE TITLE
Cant join local chat channel or other ones

### ISSUE THREAD

**Issue by Slackerjohn** [SunstriderEmu/BugTracker#3610]
**Describe the bug**

Cant join local chat channel or other ones.
i have tryed to relog multiply times, this does not work.
i have HS to a inn, still dont work
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment]
Known issue, we're working on fix, thanks. /join global meanwhile
