### ISSUE TITLE
Priests Spirit Tap

### ISSUE THREAD

**Issue by Never6** [SunstriderEmu/BugTracker#3611]
Spirit Tap in its current state can proc of mobs that do not reward XP.

**Comment by Sumie734** [comment]
When solo it doesn't seem to for me, but if the mob grants experience to anyone (like say, a grey mob that an appropriate level player has tagged), Spirit tap will be granted to the priest if they land the killing blow.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2030
