### ISSUE TITLE
Flametongue Weapon not receiving bonus critical strike damage from Elemental Fury talent

### ISSUE THREAD

**Issue by LugerTypeA** [SunstriderEmu/BugTracker#3612]
[Flametongue Weapon](https://db.endless.gg/?spell=25489) doesn't receive bonus critical strike damage from [Elemental Fury](https://db.endless.gg/?spell=16089) talent, despite it should. For example, [Frostbrand Weapon](https://db.endless.gg/?spell=25500) receives this bonus correctly and deals 2x critical damage instead of base 1,5x.
Here are the screenshots of both Flametongue and Frostbrand procs:
![WoWScrnShot_060420_194741](https://user-images.githubusercontent.com/64495843/83787595-b3ceb980-a69c-11ea-94b3-ab43104f8192.jpg)
![WoWScrnShot_060420_194738](https://user-images.githubusercontent.com/64495843/83787599-b4ffe680-a69c-11ea-9bc6-0a41c0b2953e.jpg)
![WoWScrnShot_060420_193236](https://user-images.githubusercontent.com/64495843/83787600-b4ffe680-a69c-11ea-833c-a4ae51a26d54.jpg)
![WoWScrnShot_060420_193221](https://user-images.githubusercontent.com/64495843/83787602-b5987d00-a69c-11ea-8c0d-9d57a7fe5e46.jpg)

I reported this issue more than [a month ago](https://github.com/SunstriderEmu/BugTracker/issues/3167), but didn't add screenshots of damage procs, now I do. Please, look into it, this issue is very relevant.

**Comment by LugerTypeA** [comment]
Any response?

**Comment by Sumie734** [comment]
Yes, this issue screws with the way I want to play my shaman (Double Flametongue) and is quite irritating that FB works correctly and is still useless.

I have confirmed the same above just now.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
