### ISSUE TITLE
Coldsnap resets global cooldown

### ISSUE THREAD

**Issue by Kraizn** [SunstriderEmu/BugTracker#3613]
**Describe the bug**
Coldsnap resets the global cooldown of all spells if it was triggered by a spell that is affected by cold snap talent like Frost Nova, Cone of Cold or Ice Barrier.

**To Reproduce**
1. cast frostnova
2. cast Coldsnap within global cooldown that was triggered by the previous frostnova
3. cast ice lance within global cooldown that was triggered by the previous frostnova

alternative 1:
1. cast cone of cold
2. cast cold snap within global cooldown that was triggered by the previous cone of cold
3. cast cone of cold within global cooldown that was triggered by the previous cone of cold

alternative 2:
1. cast cone of cold
2. cast cold snap within global cooldown that was triggered by the previous cone of cold
3. cast fire blast within global cooldown that was triggered by the previous cone of cold

Spell: https://db.endless.gg/?spell=11958

**Expected behavior**
"When activated, this spell finishes the cooldown on all Frost spells you recently cast."
Global cooldown should be untouched.

**Screenshots/videos**
https://youtu.be/eTn2PwnB9p0?t=430
This is a scene recorded on endless.gg which shows the bug in action.
In min 7:11 the mage casts frost nova which triggers a global cooldown (visible on the action bars). Before that global cooldown is finished Cold Snap is activated and allowes the mage to cast an ice lance pretty much right after that frost nova which should not be possible. (All spells used are visible on the spell replay icons on the buttom right side of the ui)

https://youtu.be/wNkr4YLNRKE?t=197
https://youtu.be/wNkr4YLNRKE?t=583
Another 2 scenes from endless.gg: 2x Cone of Cold within one single GCD.

https://youtu.be/462JFev7AE4?t=635
Here is an example of how it is supposed to work(min 10:37) - when u click frame by frame u can see that there is no reset on global.

https://youtu.be/K4WR0JW5jWM?t=192
https://ibb.co/cQfSLXp
This is a Screenshot from the exact moment after the Coldsnap is used in the scene above.

https://youtu.be/sg5Kdn6KSNs?t=118
This is a scene from current classic wow where the visual bug seems to be fixed.
At min 2:00 Venruki is using Cold Snap and the Global Cooldown isnt affected at all.

https://youtu.be/EqrvXdhpHZs?t=1132
Here the mage tries to cast frost nova right after cold snap (Button starts glowing) but it doesnt go off instantaneously but he need to press several times to hit the gcd.

https://youtu.be/IB7bUNWTlh4?t=2124
The mage casts ice barrier --> cold snap --> Summon water elemental. When he tries summoning water elemental after cold snap within the GCD of the previous Ice Barrier though, the UI indicates an new "Spell is not ready yet" and the spell doesnt go off before the gcd is over. U can verify that by comparing time frame of a single GCD to the time frame between casting ice barrier and successful summon water elemental which is indicated by ui showing fresh cooldown on water elemental.

https://youtu.be/3ch2-SDxxHw?t=636
(min 10:37)  Frostnova --> coldsnap --> cone of cold with delay because of GCD

https://www.twitch.tv/videos/643853943
Here is a scence from current classic wow: at min 06:11:53 the mage uses forst nova --> cone of cold --> cold snap and there is no effect on global cooldown.

https://youtu.be/1iM4oncpo34?t=45
Mist of Pandaria seems to get rid of the visual bug finally.

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, introduced with https://github.com/SunstriderEmu/BugTracker/issues/764

**Comment by Jerrythemagicdog** [comment]
Actually, funnily enough it does seem to happen on retail, maybe it's just a visual bug or maybe that's what it did: https://www.youtube.com/watch?v=MuhBMXySj-s&feature=youtu.be&t=837 (the player here doesn't seem to realize or take advantage of it for on reason or another)

**Comment by Kraizn** [comment]
> Actually, funnily enough it does seem to happen on retail, maybe it's just a visual bug or maybe that's what it did: https://www.youtube.com/watch?v=MuhBMXySj-s&feature=youtu.be&t=837 (the player here doesn't seem to realize or take advantage of it for one reason or another)

It must be a visiual issue.
https://youtu.be/K4WR0JW5jWM?t=192
Here at min 3:14 the mage uses coldsnap and this effect doesnt show up. Infact it shows the global cooldown clearly after cold snap is activated by big yellow number.

**Comment by Jerrythemagicdog** [comment]
The difference is that in the previous clip from Shaitann the mage casts a Frost spell (Frost Nova) while in your clip from Noone 2 the mage uses Will of the Forsaken right before using Cold Snap. Not sure if this makes a difference, but that's something we can observe by watching those two clips.

**Comment by Kraizn** [comment]
> The difference is that in the previous clip from Shaitann the mage casts a Frost spell (Frost Nova) while in your clip from Noone 2 the mage uses Will of the Forsaken right before using Cold Snap. Not sure if this makes a difference, but that's something we can observe by watching those two clips.

There is no difference of global cooldown of will of forsaken an other spells. The important thing to notice is to see how the cooldown addon (omnicc) shows the remaining duration of the global cooldown after using cold snap while the default ui doesnt. Its obviously a visual bug by the ui. And by the way - every mage can confirm that coldsnap is not supposed to reset global cooldown. I think we discussing an obvious fact.

**Comment by Jerrythemagicdog** [comment]
Most mages I ask say that you can do frost spell->cold snap into frost spell, replicating the clip from the Noone video you've linked yields the same result for us right now.

This is a clip from WotLK, but the same principle stands (DF->Snap->DF) and no patch notes indicating changes are to be found: 
https://www.youtube.com/watch?v=7FdeDKeHVjg&feature=youtu.be&t=424

**Comment by Kraizn** [comment]
> Most mages I ask say that you can do a frost spell->cold snap into a frost spell, replicating the clip from the Noone video you've linked (with WotF) yields the same result for us right now.
> 
> This is a clip from WotLK, but the same principle stands (DF->Snap->DF) and no patch notes indicating changes are to be found:
> https://www.youtube.com/watch?v=7FdeDKeHVjg&feature=youtu.be&t=424

https://wowwiki.fandom.com/wiki/Glyph_of_Deep_Freeze

**Comment by Jerrythemagicdog** [comment]
I would agree if he was actually playing with it, but he's not in that clip (few seconds earlier): https://youtu.be/7FdeDKeHVjg?t=417

**Comment by Kraizn** [comment]
> I would agree if he was actually playing with it, but he's not in that clip (few seconds earlier): https://youtu.be/7FdeDKeHVjg?t=417

hm its hard to tell for me which glyph setup hes using because i dont have good insight into wotlk but i also find it hard to tell if he is actually casting into his previous global at all because there are some frames after using cold snap on 50% global cooldown already gone without anything casting.

I added a screenshot into the original report from the moment after noone used cold snap showing a remaining cooldown of the spells that are affected by cold snap.

**Comment by Kraizn** [comment]
Would be nice to see a hotfix on this one before the arena tournament because of its high abusive potential.

**Comment by Kraizn** [comment]
> The difference is that in the previous clip from Shaitann the mage casts a Frost spell (Frost Nova) while in your clip from Noone 2 the mage uses Will of the Forsaken right before using Cold Snap. Not sure if this makes a difference, but that's something we can observe by watching those two clips.

I linked another scene into the report where the mage uses cold snap within a global cooldown which was triggered by the previous casted Frost spell Cone of Cold. Right after the cooldown reset he tries to cast Frost Nova but it doesnt go off for a few attempts until his global cooldown is finished (better watch it at 0.25 speed).

**Comment by Notmelody** [comment]
https://www.youtube.com/watch?v=IB7bUNWTlh4&feature=youtu.be&t=320

**Comment by Kraizn** [comment]
https://www.twitch.tv/videos/643853943
Here is a scence from current classic wow: at min 06:11:53 the mage uses forst nova --> cone of cold --> cold snap and there is no effect on global cooldown. Can this bug finally getting fixed. Its a shame that no mage comments here to clarify how this mechanic really behaved back in the original game. Instead this bug gets abused alot.

**Comment by Notmelody** [comment]
https://youtu.be/Zuz8460IaEA?t=694

sometime between "season 4 week 1" and the wotlk pre-patch
cold-snap would reset the GCD for frost spells

https://youtu.be/nIm_p5q_wIA?t=124

**Comment by Notmelody** [comment]
It is very likely that the change to the GCD recet was an anticipation to wotlk, to pinpoint exactly when this change was introduced sometime in season 4 would require more research.

however it is upto the endless staff to decide whether to allow this mechanic or not.

**Comment by Kraizn** [comment]
> https://youtu.be/Zuz8460IaEA?t=694
> 
> sometime between "season 4 week 1" and the wotlk pre-patch
> cold-snap would reset the GCD
> 
> https://youtu.be/nIm_p5q_wIA?t=124

The second scene shows nothing but the same visual bug that was present since vanilla wow as shown in many clips that were linked before. The only valid proof that it was not a visual issue is to show a scene when a mage actually casts within the global cooldown after using cold snap. But this doesnt excists - i have shown examples (from retail season 4) where mage tries to do that but it was never possible to cast before the triggered global cooldown from the previous (frost) cast wasnt over even though the UI was showing a global cooldown reset - and this is the bug we are discussing. And this bug has nothing to do with changes made in wotlk because the bug was present since the vanilla days as u can see in many clips that were mentioned in this threat.

**Comment by Kraizn** [comment]
https://youtu.be/1iM4oncpo34?t=45

Infact here is a scene from Mist of Pandaria where the visual bug seemed to be fixed finally. At min 0:47 the mage casts Ice-Block(which is a frost spell with cooldown and would trigger the visual bug  in the previous states of the game) which triggers a GCD. Within this GCD he uses cold snap and u can see no visual bug happens. The behavior is like it should be: the cooldown of the frost nova and cone of cold gets set down to the current GCD-value and the other spells GCD doesnt reset anymore aswell visually.

This is the proof that this bug was priviously only a visual issue. Please fix it or declare it as a custom change to buff mages (for no reason).

**Comment by Jerrythemagicdog** [comment]
This seems to have no impact at all (it's been this way on many other servers and players were conscious of it). Whether or not it's supposed to reset the GCD is unclear, can clearly see in videos that it does, the client also believes it does for some reason (the reason we have it working this way in the first place). Classic is not a source for anything class-mechanic related sadly, other than some very general things. 
Closing the issue, if anyone has anything else to contribute we'll reopen it, thanks for the discussion here!

**Comment by Kraizn** [comment]
> Whether or not it's supposed to reset the GCD is unclear, can clearly see in videos that it does, the client also believes it does for some reason (the reason we have it working this way in the first place).

 I have linked scenes where mages try to cast within the global but didnt work even though it was shown as a gcd reset visually. In addtion i have shown that the visual reset was fixed in a later expansion (Mist of Pandaria) without noting any functional changes and cold snap works without reseting the global cooldown in the current classic vanilla - without any visual issue.

Let me ask you: what would be a valid proof to convince u that it always was just a visual issue?

**Comment by Kraizn** [comment]
Maybe this helps:

https://youtu.be/IB7bUNWTlh4?t=2122

![Trig_Cold_Snap_Visual_Bug](https://user-images.githubusercontent.com/66084110/84966989-3337a080-b113-11ea-967a-d4f8453f958a.png)

I documented the moment after he casted Ice Barrier, used cold snap on the triggered global cooldown and tried to summon the water elemental before the GCD was over.

It shows that he wasnt able to summon the water elemental right after cold snap because the GCD was still active even though the ui showed a GCD-reset. How else can u explain that behavior?? If the cold snap would have reset the GCD of the Ice Barrier in a functional way (not just visually) there would have been no problem to summon the water elemental right after.

**Comment by Kraizn** [comment]
https://youtu.be/6CkYaF8EKb0?t=557

Watch this (in 0.25 speed) and explain how the ice lance doesn't go off on the first attempt. Another proof that GCD reset was just a visual bug and never reset functionally.

**Comment by Kraizn** [comment]
https://youtu.be/K4WR0JW5jWM?t=528

here is a scene where a visual GCD reset happens even without using Cold Snap. The mage cast Counter Spell into frost nova and there is no GCD visible.
