### ISSUE TITLE
Priest Improved Power Word: Fortitude not working

### ISSUE THREAD

**Issue by slane9539** [SunstriderEmu/BugTracker#3614]
**Describe the bug**
The discipline talent Improved Power Word: Fortitude appears to be bugged. After putting 1 talent point into it, I noticed a stamina increase on the buff. However after maxing it with 2 talent points, I have lost all bonuses the talent provides. The spell description reads that fortitude should be giving me 70 stamina at rank 6, but when I cast it the buff only gives 54 stamina.

**To Reproduce**
Put 2 talent points into Improved Power Word: Fortitude and cast it on yourself.

https://classic.wowhead.com/spell=14767/improved-power-word-fortitude#see-also-ability

**Expected behavior**
I expected to receive the amount of stamina given in the spell description from the buff.

**Screenshots/videos**
Here are screenshots of the spell as it reads in my spellbook, and how it reads when cast on me.

![priest bug 1](https://user-images.githubusercontent.com/66437853/83796140-8703ad80-a66e-11ea-96aa-5339b329eece.png)

![priest bug 2](https://user-images.githubusercontent.com/66437853/83796172-9551c980-a66e-11ea-887b-cb94699c5997.png)

**Comment by Jerrythemagicdog** [comment]
The tooltip will not update depending on the talent points spent, however you can see that your amount of total Stamina increases correctly in your character panel depending on the amount of talent points spent in "Improved Power Word: Fortitude".
