### ISSUE TITLE
G'eras missing items

### ISSUE THREAD

**Issue by rinosuke0** [SunstriderEmu/BugTracker#3615]
G'eras isn't selling some items with badges of justice like "Primal Nether" and "Nether Vortex" despite we are in 2.4.3 this NPC isn't selling these items
![bffc84fd-d961-4695-a085-abe84d3d4b7b](https://user-images.githubusercontent.com/66446860/83818478-14ee9100-a68d-11ea-90cd-36d98086230d.jpg)

**Comment by Jerrythemagicdog** [comment]
We're not in 2.4.3 other than spells, the server's content is released in a progressive manner along with available items.
