### ISSUE TITLE
Mindflay vs Shaman

### ISSUE THREAD

**Issue by Kraizn** [SunstriderEmu/BugTracker#3616]
**Describe the bug**
Something causes mindflay to only channeling  1.5sec for one tick only total when fighting against a shaman.

**To Reproduce**
1. Cast mindflay on shaman

Spell: https://classic.wowhead.com/spell=15407/mind-flay

**Expected behavior**
There should be no effect that causes mindflay to skip 2 of the 3 ticks from nothing.

edit: Talents or abilities (like thoughness from shaman) that effects movement impairing effects are not supposed to manipulate mindflay damage-channeling.

**Screenshots/videos**
https://youtu.be/sALZHCmAMVo?t=82
Here is an old video from vanilla wow where u can see that rogue uses pvp-trinket while mindflay is channeled (min 1:24) (Use: Removes all movement impairing effects and all effects which cause loss of control of your character.). You can see the mindflay keeps channeling.

https://youtu.be/8bpGU4lh4QI?t=341
Here another situation where a druid shapeshifts into bear while mindflay is channeling. Its strong indicator that mindflay channeling was not supposed to be affected by snare-breakers.

**Additional context**
https://github.com/ccshiro/cc-buglist/issues/66
here is a report from 2015 on another server

**Comment by Jerrythemagicdog** [comment]
Perhaps an interaction with https://db.endless.gg/?spell=16309

**Comment by Kraizn** [comment]
> Perhaps an interaction with https://db.endless.gg/?spell=16309

ye that seems to be the issue. The mindflay slow effect is supposed to be independed from the damage channeling.

**Comment by Jerrythemagicdog** [comment]
Live with next update (Toughness fix that is), thanks!
