### ISSUE TITLE
Rogue unable to obtain poison quest

### ISSUE THREAD

**Issue by andrewjohnson167** [SunstriderEmu/BugTracker#3618]
after abandoning the completed quest for poisons im unable to retake it.
Thus leaving me being unable to learn any poison spell
https://i.gyazo.com/4aab6741b2c62d0f50ac349f12aef6c1.jpg
https://i.gyazo.com/6e3965e73ee72f21112a5ccd9f3bb1fa.png

**Comment by InhumanGM** [comment]
Duplicate of #3370
