### ISSUE TITLE
Demonic Knowledge bug (doesn't work)

### ISSUE THREAD

**Issue by OSamouel** [SunstriderEmu/BugTracker#3619]
**Describe the bug**
when my pet (warlock) is buff (stam/motw/intel) i dont get the 12% spell dmg i should get from teh talents : Demonic Knowledge
**To Reproduce**
take warlock lvl44+ take Demonic knowledge Talents in demonology talents tree summon a pet buff him with intel/stam/motw/bok look your bonus damage. you get nothing from his gain of intel/stam

**Expected behavior**
12% of the intel/stam should be add to the Bonus damage (spell) to the summoner
**Screenshots/videos**
intel buff 31intel+80stam+motw+bok(10%) : 100+ bonus damage to spell (with demonic knowledge)
https://imgur.com/ks3rc9E
WITHOUT intel buff (no change)
https://imgur.com/mEeyHYH

** source **
https://db.endless.gg/?spell=35693
**Additional context**
that something that totaly ruins the spec and gamebreaking when you want to play demonology spec
thx to fix this in advance!

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1522
