### ISSUE TITLE
Applying Hunter's mark use a charge of Misdirection 

### ISSUE THREAD

**Issue by ericpare1** [SunstriderEmu/BugTracker#3621]
**Describe the bug**
Applying Hunter's mark use a charge of Misdirection

**To Reproduce**
1. Cast Misdirection on pet
2. Target a mob
3. Cast hunter's mark

**Expected behavior**
Hunter's Mark doesn't cause threat, it should not use a Misdirection charge.

**Comment by bjh368** [comment]
Slow trap also eats charges, and also Expose weakness procs (survival talent)

**Comment by beraus** [comment]
Noted in https://github.com/SunstriderEmu/BugTracker/issues/2701, thanks.
