### ISSUE TITLE
Auctioneer addon not working properly.

### ISSUE THREAD

**Issue by Keritous** [SunstriderEmu/BugTracker#3623]
I just noticed it doesn't work properly on this server, I tried clear db but it didn't help.
 The issue with  price:
For example: mote of mana ~ 1g each but addon says 7g each
![WoWScrnShot_060520_185346](https://user-images.githubusercontent.com/66011356/83887967-6c106680-a75e-11ea-82d6-05d4a8a6c619.jpg)

Addon not showing all auctions:
![WoWScrnShot_060520_185229](https://user-images.githubusercontent.com/66011356/83888041-8b0ef880-a75e-11ea-93ff-459b46d373c7.jpg)
meanwhile in AH
![WoWScrnShot_060520_185233](https://user-images.githubusercontent.com/66011356/83888080-995d1480-a75e-11ea-9139-f2dab4a9ceb2.jpg)

**Comment by cdguard** [comment]
thats more likely issue of the addon and not the server

**Comment by Jerrythemagicdog** [comment]
Sorry, can't troubleshoot issues with addons, there are many things that could be wrong, as long as the information is correct without the addon that's as far as we're willing to usually go.
