### ISSUE TITLE
cant unlearn shadoweave tailoring 

### ISSUE THREAD

**Issue by imperialmuff** [SunstriderEmu/BugTracker#3624]
**Describe the bug**
cannot unlearn shadoweave tailoring from npc Andrion Darkspinner in shat

after clicking unlearn shadoweave tailoring and pay the 150g it says "you cant do that right now" i also have no cooldowns left on any cloth

**Comment by kelno** [comment]
Hey, thanks for reporting.
You first have to unequip any items you have that requires shadowweave tailoring.

**Comment by kelno** [comment]
I'll improve the error message there.
