### ISSUE TITLE
Quest: Varedis Must Be Stopped

### ISSUE THREAD

**Issue by Nekx-drOOd** [SunstriderEmu/BugTracker#3626]
![Varedis Must Be Stopped](https://user-images.githubusercontent.com/66377940/83930869-c104aa80-a767-11ea-962b-fe8885b8d77d.jpg)

I made a huge mistake, I finished the quest the other day & never turned it in. I upgraded all new larger bags today and was cleaning out lotsa junk & already used old quest items etc and deleted Book of Fel Names thinking it wasn't needed anymore.

Ugh! Is there anything I can do to fix this? I think I got the book off a boss in Shadowlabs or something, a few quests ago.

Thanks!
Mike (Nekx) on endless.gg

**Comment by Jerrythemagicdog** [comment]
Resolved in game.
