### ISSUE TITLE
bug: Levixus reset after he casts dominant mind on you when you try to solo him

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#3628]
**To Reproduce**
1. Engage Levixus solo
2. Wait for Levixus to cast dominant mind on you (pet was also dominated)
3. After the effect is gone. Levixus resets and aggros you since you were right next to him when you were mind controlled.

**Expected Behaviour**
After dominant mind fades, you should be able to pick up where you were.

**Comment by Balanarr** [comment]
I remember that behavior being correct from back in the day for creatures with mind control when attempting with a pet.
You were not soloing him, you were with your pet.

**Comment by Jerrythemagicdog** [comment]
This only happens if you have a pet and you're not the top threat target (because your pet is tanking it), @Balanarr is correct here.
