### ISSUE TITLE
PVP Flag not working.

### ISSUE THREAD

**Issue by hashblaster** [SunstriderEmu/BugTracker#3630]
**Describe the bug**
After exiting a battleground/contested area you should be PVP flagged for 5 minutes.  This is not working.

Plz fix I want to gank Alliance in Stormwind.

**Comment by kelno** [comment]
Thanks for reporting.
I don't think we want to add a PvP flag upon leaving bgs (regardless of blizzlike or not).
Can you provide proof it should stay upon leaving contested area + it doesn't actually ?

**Comment by hashblaster** [comment]
That's a bummer.  Why wouldn't you want to stay blizzlike?

When you are PVP flagged, for any reason, it remains for 5 minutes.   Rogues can't gank in capital cities, for example.

https://www.youtube.com/watch?v=57h2zD4LuBM

**Comment by artieau** [comment]
This is specifically about when leaving a BG though and this server is not blizzlike.
