### ISSUE TITLE
[Gruul's Lair] - [Lair Brute]

### ISSUE THREAD

**Issue by Keritous** [SunstriderEmu/BugTracker#3631]
[Lair Brute](https://www.wowhead.com/npc=19389/lair-brute)
1. These mobs target deads.
2. Can be pulled 1 by 1 by using FD or Totem, but they shouldn't be.

> 

on 2007/02/25 (Patch 2.0.8) |   |  
-- | -- | --

> Immune to:

Sap, sheep, hunter slowing, MC, and **FD pull will not only pull a single**

**Comment by Jerrythemagicdog** [comment]
Thanks, the pull is a general issue being worked on and reported in another issue, targetting dead players is fixed with next restart.
