### ISSUE TITLE
Onyxia has wrong loot 

### ISSUE THREAD

**Issue by LSD7** [SunstriderEmu/BugTracker#3633]
Onyxia doesn't have any items in the loot, except 18 slot bag and Head of Onyxia. We killed her twice and get the same loot.
![WoWScrnShot_060720_145001](https://user-images.githubusercontent.com/31816578/83964422-e2cc7180-a8ce-11ea-9a40-9b1016f0c21d.jpg)

**Comment by Sheikthecatman** [comment]
Thanks! Onyxia should drop the rest of her items next server restart.
