### ISSUE TITLE
problem with connecting

### ISSUE THREAD

**Issue by vourdoulakas** [SunstriderEmu/BugTracker#3634]
today we have problem with connecting to the server.
all of Iran isp cant connect to the server just with VPN we can connect.
we have same problem in the Atlantic server and have to leave that server. and I just can say u have a lot of people from Iran in this server.
I report this issue in wow freaks. I report this issue and they solve the problem with another connecting for Iranian people to connect without VPN. please solve this problem for us

best regard

**Comment by beraus** [comment]
Try to use this as a realmlist:
`set realmlist 163.172.21.111`
