### ISSUE TITLE
Appearance change not working on website service

### ISSUE THREAD

**Issue by vik881** [SunstriderEmu/BugTracker#3635]
Purchased the service and it didnt work, but deducted the coins. GM ticket has been up for 3 days, discord no response, so I'll post it here.

**Comment by Jerrythemagicdog** [comment]
Did you maybe select a character with the exact same appearance as your previous one?

**Comment by vik881** [comment]
no, the change was for my main which is the only char on the account. so the second char was definitely the appearance source.

**Comment by Jerrythemagicdog** [comment]
Contact me on Discord please: Jerry#9132 with your character name.
