### ISSUE TITLE
TK, MC and wipe

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3639]
in TK, fighjting KT.  When a raid wipes with people MC and Kael thas resets, the MC's reset with him and then trigger the event (5-10s waiting for MC to fade.  20-30s of talking when he re-agro, then waiting for thaladred to kill the 1-2 people who were MC).  

Can you just have the MC people insta die or insta lose mc... when KT resets.

**Comment by NeonicSupersonic** [comment]
2nd window log into heart

**Comment by kelno** [comment]
Any idea what should happen there? Should KT attack the MC'd target?

**Comment by NeonicSupersonic** [comment]
Probably correct interaction, but you can make mcs instantly die when he resets and theres no hostile targets to attack (was like that on retail yogg 0).

**Comment by kelno** [comment]
Okay, that's probably the simplest as well

**Comment by kelno** [comment]
Fixed with next server update
