### ISSUE TITLE
KT, staff buff

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3641]
it seems that if you put on the buff, then someone else activates teh buff near you.  it overwrites your buff.  if they then move out of range, you no longer have the buff.

if you hvae the staff, and activate the buff, it shouldn't be removed by someone else activating it.

**Comment by InhumanGM** [comment]
Please specify which buff and what staff you are referring to.

**Comment by michaelkittrell** [comment]
"Staff of Disintegration"

tk, kael thas fight.  its the legendary weapon you loot from the staff of disintegration corpse.

**Comment by artieau** [comment]
Works fine now
