### ISSUE TITLE
human female gets "stuck" in stairs running

### ISSUE THREAD

**Issue by Bobson1337** [SunstriderEmu/BugTracker#3642]
**Describe the bug**
The race and gender Human female is having issues running up stairs or similar objects without getting stuck and not coming up, resulting in the user having to press space to jump or wiggle using arrow keys. 

**To Reproduce**
100% Reproducible. Easiest example would be stairs in to AH in Stormwind. Place character in front of stairs, run up the stairs. The character glitches up and sometimes gets stuck just running towards a step in the stairs.

**Expected behavior**
Not getting stuck and getting up the stairs without glitching.

**Screenshots/videos**
Youtube link:
https://www.youtube.com/watch?v=u0p-IPzjKoI&feature=youtu.be

**Additional context**
This is not just the stairs up AH, this happens all around the world with different objects. Have not encountered this issue with other characters not human female.

**Comment by Jerrythemagicdog** [comment]
Yes, it's an issue in TBC, old client, not the greatest care at the time to details like these. There are some third party patches you can apply (which we do not officially recommend, but some players choose to use them) that solve this problem.
