### ISSUE TITLE
Netherskate mobs not dropping motes of mana

### ISSUE THREAD

**Issue by alistairaxd** [SunstriderEmu/BugTracker#3644]
**Describe the bug**

**To Reproduce**

1. Shadowmoon valley  66.1 66.7 Netherskate mobs ID: https://www.wowhead.com/npc=21901/netherskate
2. Mobs are supposed to drop Motes of Mana at a rate of 26% chance to drop.
3. After killing 11 Netherskates not a single Mote of Mana drop registered

**Expected behavior**
 Mobs are supposed to drop Motes of Mana at a rate of 26% chance to drop.
After killing 11 Netherskates not a single Mote of Mana drop registered

**Screenshots/videos**

**Additional context**

**Comment by z5n** [comment]
unable to reproduce
