### ISSUE TITLE
Clearcasting can't back-to-back proc while spamming Arcane Blast

### ISSUE THREAD

**Issue by TheRealZaroua** [SunstriderEmu/BugTracker#3648]
Mage talent Arcane Concentration cannot proc Clearclasting while Clearcasting is already active and the Mage casts Arcane Blast.

Mage gets Clearcasting proc. Mage casts Arcane Blast and gets another Clearcasting proc. The sound and visual effect will go off, the first Clearcasting will be consumed properly, but the second proc will not activate.

https://db.endless.gg/?spell=12577
https://db.endless.gg/?spell=12536
https://db.endless.gg/?spell=30451

Clearcasting procs should be able to happen back to back while using Arcane Blast.

The talent seems to work fine with Fireball.

**Comment by TheRealZaroua** [comment]
This also happens with Fire Blast https://db.endless.gg/?spell=27079 so it might also happen with other instant spells as well.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/433

**Comment by ghost** [comment]
hump de bump

**Comment by Jerrythemagicdog** [comment]
In other words: Arcane Concentration should proc when a spell is cast not when it hits.

http://wowwiki.wikia.com/wiki/Arcane_Concentration?oldid=1432055
https://www.youtube.com/watch?v=beyRXulvycI&feature=youtu.be&t=2m50s

**Comment by Jerrythemagicdog** [comment]
Fixed with next update, thanks for the issue.
