### ISSUE TITLE
[Quest] Lost! 

### ISSUE THREAD

**Issue by alex1994xcx** [SunstriderEmu/BugTracker#3649]
https://classic.wowhead.com/quest=4492/lost
Spraggle Frock doesnt need the water at all. Youre supposed to use "Spraggle's Canteen (Provided)" but at the current state there no need to.

**Comment by Balanarr** [comment]
Seems to be an RNG if it feints or not. I needed to use the water on 2 out of 5 characters on which I've done the quest.
