### ISSUE TITLE
Quwest :The Symbol of Life

### ISSUE THREAD

**Issue by SQWIZ** [SunstriderEmu/BugTracker#3650]
after accepting the quest, I didn’t see Symbol of Life in my inventory. If you cancel the quest, it’s not possible to take it. I’ll ask you to fix this bug. My nickname is Rexonaman
 quest:https://classic.wowhead.com/quest=1790/the-symbol-of-life

**Comment by Jerrythemagicdog** [comment]
Can't reproduce, the quest is repeatable and the quest giver can you provide you with a new Symbol of Life if necessary at any point.
