### ISSUE TITLE
(Shaman) Water Totem Quest doesn't start

### ISSUE THREAD

**Issue by Xerxes789** [SunstriderEmu/BugTracker#3651]
On my final shaman questline, i usualy get my water totem in silverpine forest. But I have done all the Prequests and the last one doesn't start, so i can't get my water totem :(
Can you help me plz?

**Comment by Keritous** [comment]
You don't need to do chain quests to obtain totems. You can summon any totem.

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/3654
