### ISSUE TITLE
[SHAMAN] Flametongue Weapon and Spell crit issue

### ISSUE THREAD

**Issue by Harvel218** [SunstriderEmu/BugTracker#3652]
**Bugg description:**
Flametongue weapon is not criting as it should, with 4% spell crit chance, it crit only 1,6% times (as in SS)
![WoWScrnShot_060820_171950](https://user-images.githubusercontent.com/59796176/84049643-fa7a2780-a9ac-11ea-8136-c70bcae55464.jpg)

I have checked that with higher ammount of crit, and with 22% spell crit it usualy crit around 16-18% (i can check again and add screenshoots),
![WoWScrnShot_060820_173552](https://user-images.githubusercontent.com/59796176/84050822-89d40a80-a9ae-11ea-93cc-3e3036f17eb2.jpg)

a lot of crits are missing and i dont know what is the reason

Another try :  550+ hits 

![WoWScrnShot_060820_174549](https://user-images.githubusercontent.com/59796176/84051823-f56aa780-a9af-11ea-9951-00b4d83ad1aa.jpg)

Another 2000+ hits 
![WoWScrnShot_060820_180451](https://user-images.githubusercontent.com/59796176/84053715-9c504300-a9b2-11ea-97fa-e10ca78feea2.jpg)

**Comment by Jerrythemagicdog** [comment]
Thanks, should be resolved with next restart. '32ed559dc241b1a4523c3d8b34c0a4efe5cb1b2d'
