### ISSUE TITLE
Spell slowing effects don't increase NPC's spell channel time

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3653]
I noticed it with arcane missles. It should increase the time between each missle and the total channel time.

**Comment by Jerrythemagicdog** [comment]
Doesn't seem to be the case:
https://streamable.com/nksukq

**Comment by babno** [comment]
Maybe it's just npc channeled abilities then, should have clarified that. I've noticed it on the casters in MT and SL.

**Comment by pinkisnotgay** [comment]
@Jerrythemagicdog track id?

**Comment by kelno** [comment]
Some npcs are immune to spell slows, please include npc ids here

**Comment by babno** [comment]
https://www.wowhead.com/npc=18637/cabal-shadow-priest
https://www.wowhead.com/npc=18313/ethereal-sorcerer

**Comment by Jerrythemagicdog** [comment]
Tested, when those NPCs are affected by a Curse of Tongues (11719) their channeled spells (e.g. Mind Flay 17165) the channel time is not increased. Those NPCs are not immune to spell slow effects.

**Comment by kelno** [comment]
Seeing how this works... Curse of tongue is basically giving the target negative haste, and channels are by default unaffected by haste, unless they have some specific flag for it. The player "Mind Flay" spell has the flag, but the creature shadow priest mind flay spell doesn't. So I'm not sure it should even work on them.
I'll do something experimental there, making this flag only prevent positive spell haste but let negative haste apply.

**Comment by Jerrythemagicdog** [comment]
Fixed, live with next restart.
