### ISSUE TITLE
Drek Thar resetting/evading randomly in Alterac Valley

### ISSUE THREAD

**Issue by Felthorn10** [SunstriderEmu/BugTracker#3655]
During the fight with Drek Thar, he will sometimes randomly reset while still having plenty of people on the aggro table and without being kited outside his keep. He'll be inside the keep's main area. This has typically happened when he reaches a low % HP. Just happened within the last 10 minutes if you need to check logs.

**Comment by mechanicsTBC** [comment]
pretty sure this happens if one of the tower masters gets kited/feared outside of his room

**Comment by Felthorn10** [comment]
I didn't notice any warmasters still up when we were fighting, and his two wolves were dead.

**Comment by kelno** [comment]
It should only happen when a warmaster is kitted out of the room, they all evade together.

**Comment by Felthorn10** [comment]
And that's the issue, there's no warmaster, no pets, and he is evading still. That's why I opened this bug.

**Comment by Felthorn10** [comment]
This literally just happened again, all warmasters were down, fight was in full swing in the middle of the room, this IS a bug, please address
