### ISSUE TITLE
Interface - Show cloak/helm

### ISSUE THREAD

**Issue by B0nisek** [SunstriderEmu/BugTracker#3656]
If you hide your cloak/helm it doesn't remember and after another UI reload it will be displayed.

Repro.
1. Hide cloak/helm in interface tab.
2. Reload UI (enter dungeon, bg, arena, relog)
3. Cloak/helm is displayed

https://www.twitch.tv/videos/645664232 - with addons enabled
https://www.twitch.tv/videos/645675373 - with addons disabled

**Comment by kelno** [comment]
That's a new bug indeed

**Comment by kelno** [comment]
Fixed with next update
