### ISSUE TITLE
UB doesn't give Sporeggar rep

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3657]
**Describe the bug**
UB doesn't give Sporeggar rep. also apparently @kelno needs a detailed description of what this means

**To Reproduce**

1. Kill something in UB
2. Note what faction/s it gives rep for
3. See if Sporeggar is one of the factions

location: https://www.wowhead.com/the-underbog

**Expected behavior**
Killing mobs in the underbog should increase the players reputation with the Sporeggar faction, causing the number associated with it to become bigger.

**Additional context**

#3629

**Comment by NeonicSupersonic** [comment]
It should only work like that on normal, heroic UB supposed to give 0 sporeggar rep.

**Comment by babno** [comment]
That makes zero sense. Obviously heroic should give spore rep if normal does.

**Comment by NeonicSupersonic** [comment]
retail video, was probably changed later at some point

**Comment by kelno** [comment]
"[...] should increase [...] causing the number associated with it to become bigger." Nice

**Comment by kelno** [comment]
Thank for you the very detailed step, but can you prove that increasing a number should make it become bigger? What if it's a negative number?

**Comment by MianLavanAelin** [comment]
UB should absolutely not give sporregar rep on any difficulty. This was added in WOTLK/CATA and for some reason it was added to CMANGOS and probably trinity as well during ports. 
https://www.wowhead.com/faction=970/sporeggar#comments guide at the top of the page + tbc comments do not mention UB absolutely anywhere and videos where it gives sporregar rep can only be seen from later XPACs.
The only thing you should do in UB is to farm Sanguine Hibiscus
