### ISSUE TITLE
Drek Thar continues to reset randomly without warmasters up and without being kited out

### ISSUE THREAD

**Issue by Felthorn10** [SunstriderEmu/BugTracker#3658]
During the fight with Drek Thar, he will sometimes randomly reset while still having plenty of people on the aggro table and without being kited outside his keep. He'll be inside the keep's main area. This has typically happened when he reaches a low % HP. Just happened within the last 10 minutes if you need to check logs.

There are no warmasters up and no pets up when this happens. This is a bug, please address. This is the second time reporting this, first time was dismissed as if I was stupid. This literally just happened again within 5 minutes. Please check the relevant logs.

**Comment by mechanicsTBC** [comment]
can confirm.  just had it happen as well with all 4 towers down, both wolves dead.  perhaps drek is targeting people outside of his room with a spell or a check of some sort? #3655

**Comment by kelno** [comment]
I found the issue: Some fuckery happened when the alliance boss evaded, the horde one would evade too.
Fixed with next update

**Comment by Felthorn10** [comment]
Sweet! Thanks a ton for this.
