### ISSUE TITLE
Serpent Sting being resisted.

### ISSUE THREAD

**Issue by ferron12** [SunstriderEmu/BugTracker#3660]
Serpent sting is being resisted.  It makes me think that it is being tested against spell hit% rather than hit%.  It should say "miss" instead of "resisted".  I'm assuming that this is the case with all hunter stings.

**Comment by ferron12** [comment]
Scorpid Sting is not being resisted.  Only Serpent Sting.

**Comment by kelno** [comment]
Thanks for reporting!
Fixed with next server update
