### ISSUE TITLE
I can not log in to the server

### ISSUE THREAD

**Issue by mrazfat** [SunstriderEmu/BugTracker#3661]
I had a disconnect last night, and so far I can’t access the server. I changed the client, deleted the cache folder, rebooted the Internet, nothing helps. I can’t log into any of the accounts. solve the problem. Thanks.

I also attach screenshots of what happens at the time of launch.
![WoWScrnShot_061020_080514](https://user-images.githubusercontent.com/66706940/84215870-e724a480-aaf1-11ea-8f20-b2c905851893.jpg)
![WoWScrnShot_061020_080534](https://user-images.githubusercontent.com/66706940/84215873-e8ee6800-aaf1-11ea-991d-54368bd33740.jpg)
![WoWScrnShot_061020_080555](https://user-images.githubusercontent.com/66706940/84215875-e986fe80-aaf1-11ea-90ef-b7272224c7e7.jpg)

**Comment by beraus** [comment]
Try to use `set realmlist 163.172.21.111`
