### ISSUE TITLE
Quest: Varedis Must Be Stopped (Bugged Turn-in)

### ISSUE THREAD

**Issue by Nekx-drOOd** [SunstriderEmu/BugTracker#3662]
![Varedis](https://user-images.githubusercontent.com/66377940/84231652-99417980-aabc-11ea-924e-03e391506e21.jpg)

Have the book (mouseover in bag) and the quest log shows all 4 kills completed but questgiver is a grayed out "?" with no turn in available...please help!

Thanks!
Mike (Nekx) @endless.gg TBC server

**Comment by beraus** [comment]
Make a ticket in game, and someone will help you with this issue.
