### ISSUE TITLE
All itens that I buyout from AH come as BID

### ISSUE THREAD

**Issue by maylersaid** [SunstriderEmu/BugTracker#3666]
I Buy same itens with buyout option, and when i go to the mail, its not there the itens.  All my gold was used to buy as buyout but nothing happn.

Follow the video

https://drive.google.com/file/d/1yJXQEJPs7MxNjV7KgRZlLhMD4NmviBs9/view

**Comment by kelno** [comment]
Thanks, fixed with next server update
