### ISSUE TITLE
[Important] Hunters Expose Weakness

### ISSUE THREAD

**Issue by TheMoneyHater** [SunstriderEmu/BugTracker#3668]
**Describe the bug**
Survival Hunters talent Expose Weakness is not working correctly.

**To Reproduce**
1. Get a hunter with the talent Expose Weakness
2. Get the debuff on a training dummy
3. See the difference between a old recount and new recount average autoattack damage with a feral druid for example

https://i.imgur.com/CxYLJTY.png

https://wowwiki.fandom.com/wiki/Expose_Weakness
Was added December 29 - 2019 which is 1 year after wrath was released.
"This used to give 25% more AP for all raid members, but now is limited to hunter only."

https://wow.gamepedia.com/Talk:Expose_Weakness
Since 3.0.2, EW only affects self (hunter). —The preceding unsigned comment was added by Repaxan47660 (talk · contr).

**Expected behavior**
The spell is using data from WOTLK and not TBC because it should increase all physical damage done by the target with the debuff not just hunter or hunters.

**Comment by TheMoneyHater** [comment]
Do you mind see if hunter pets are getting it? Away from my computer atm

**Comment by bjh368** [comment]
Further testing, pets don't get any ap, not even your own 
![image](https://user-images.githubusercontent.com/59749446/84326235-c6556100-ab7c-11ea-9f53-314b31914d93.png)

**Comment by TheMoneyHater** [comment]
Haha what a sync :D Yeah that is also really scuffed.

**Comment by bjh368** [comment]
Yeah, FeelsBadMan 

So until this gets fixed, its only worth bringing surv if you run like 10 hunters, preferably MM spec :^) Big yikes

**Comment by kelno** [comment]
Made a fixie, applied with next update

**Comment by TheMoneyHater** [comment]
Still not working

**Comment by mchayes** [comment]
Re-open issue? It's still bugged.

**Comment by frastsytt** [comment]
Still broken.

**Comment by kelno** [comment]
Be patient, it's not live yet. We only update the server every few days.

**Comment by bjh368** [comment]
Seems to work now Poggers
