### ISSUE TITLE
Quest: Resupplying the Excavation

### ISSUE THREAD

**Issue by Sibrica** [SunstriderEmu/BugTracker#3672]
Resupplying the Excavation
-https://classic.wowhead.com/quest=273/resupplying-the-excavation

"Speak with Huldar"

- Unfortunately, you can't talk to the Huldar (silver question mark above)
  I was waiting for an hour to make sure if escort quest have any CD

**Comment by Jerrythemagicdog** [comment]
I believe you might've come from the east side of the lake rather than from the west side, which is unfortunately how the quest is credited (even on retail), by entering an areatrigger.
