### ISSUE TITLE
saying no divxdecoder.dll

### ISSUE THREAD

**Issue by Kronus3** [SunstriderEmu/BugTracker#3674]
So I just started playing on the server, and every time that I close out the client, and try to open it back up again, it says that I have no divxdecoder.dll... And I have no idea on how to fix this, so I have been just downloading the whole client over again. Anyone know what is going wrong? and how I can fix this issue? Thanks.

**Comment by Jerrythemagicdog** [comment]
Have you tried running WoW as an administrator?

**Comment by kelno** [comment]
That file should be in the wow root folder, if it's indeed missing: downloading a new client or asking someone to send you that file should work.
