### ISSUE TITLE
ssc lurker spouting in random directions still

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3675]
Lurker still spouting in random directions.  At least 1 or 2 pulls tonight were fubar due to this.  In the most obvious case, spout was going normally for 3-4s then boss rotated about 60 degrees instantly, killed someone, then continued with spout from the correct spot.

6/10/2020

From previous ticket since closed:

There is a bug with spout. It is supposed to spout in a clockwise or counterclockwise direction a predictable and steady, easily avoidable speed.

We are sometimes seeing extremely experienced people randomly killed by spout... all claiming it wasn't anywhere close to them.

In our first attempt on 5/27/2020, towards the end of a spout around 50%, 4-5 people died in very different directions in 1s, recount says all died to spout. Some of us saw a visual that seemed to show the boss spouting in 5 different directions, changing facing impossibly fast (obv targetting players), in 360 degrees in about 0.5s. It almost looked like boss did a whirl while still spouting. Some people saw nothing, some people saw 1 or 2, a couple saw spouts going in 5 different directions extremely quickly.

This may be 2 different issues? spouting while whirling, randomly changing facing and randomly 1 shotting someone with spout that shouldn't?

**Comment by Balanarr** [comment]
Happened to us last week and this week. Due to this we just have everyone in the water.

The dirwction switch seems to be aggro related

**Comment by kelno** [comment]
Thanks, some video could help a lot here

**Comment by mchayes** [comment]
its 100% agro related, our bear got spout direction twice on him, first by accident. Second time we 'tried' it by having him pumping threat.

**Comment by hufsa** [comment]
https://www.twitch.tv/cherryxo/clip/AstuteCourageousCobraEleGiggle

**Comment by mechanicsTBC** [comment]
https://clips.twitch.tv/StylishVibrantPeachAllenHuhu

You can see the tank drops from the threat table randomly for a second or two.  As this happens lurker turns around and kills the arms warrior, then the tank reappears.  The spout issue is most likely related to this.  Lurker randomly seems to "lose" the main tank from the threat table and begin attacking the next highest threat person in his melee range #1188.

If I had to guess, I would assume it has something to do with https://db.endless.gg/?spell=37478
targeting.  Most likely ignores highest threat from being a target of this spell, which temporarily removes them from the threat table.

This CONSTANTLY happens with melee DPS on this boss if you don't spam taunt rotations on the boss between multiple tanks.

**Comment by mechanicsTBC** [comment]
@kelno

**Comment by beraus** [comment]
Should be fixed now.
