### ISSUE TITLE
ssc morrogrimtidwalker

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3676]
watery grave not doing damage on grave, and no toss up or fall damage.

worked correctly last wednesday, broken at least as of 6/10/2020

**Comment by michaelkittrell** [comment]
you can also basically move immeidatley after being teleported to the grave even though the bubble graphic is surrounding your char.

**Comment by bjh368** [comment]
![image](https://user-images.githubusercontent.com/59749446/84357687-5ff53080-abc6-11ea-8a77-0b4b6defadd8.png)

**Comment by Jerrythemagicdog** [comment]
Morogrim should be fine now after the last restart.
