### ISSUE TITLE
ssc morrogrim tidewalker, murlock adds sometimes show idle after wipe

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3677]
sometimes after a morrogrim wipe, a bunch of murlocks will show spawned standing at the north entrance looking north... but are not actually there.  some people see them, some people apparently dont see them.  they do not agro or affect play, visual bug.

**Comment by frastsytt** [comment]
Can confirm, the mobs don't actually exist, is a visual bug.

**Comment by kelno** [comment]
Are you dead while having this visual bug?

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
