### ISSUE TITLE
can't use general chat

### ISSUE THREAD

**Issue by Vintaro** [SunstriderEmu/BugTracker#3678]
**Describe the bug**

cannot post in general chat /1 does nothing
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by EL100** [comment]
Can confirm this. Happened to me a couple of times before.

**Comment by Vintaro** [comment]
seems to come and go, working for the moment now.

I got a message in game from a GM saying it was a server side issue that they are resolving currently

**Comment by beraus** [comment]
Know issue, thanks for the report. Use /join global meanwhile.
