### ISSUE TITLE
Low gold from quests.

### ISSUE THREAD

**Issue by Louzuz** [SunstriderEmu/BugTracker#3679]
I'am getting a low amount of gold (5Gold ~) from the Outland Quests, even though I already hit lvl70 for a while. Which is weird because that's my second character and I already did them all on my Main and I got way more gold there.

So at first I thought it might be just for the grey Quests, but I also got low gold from some SMV and NS quests too. So I asked some people if it might got changed but they said no. So I dont know if something might be bugged for my character.

InGame character : Oneandonly

**Comment by Jerrythemagicdog** [comment]
Thanks for the report, could you provide some details about which quests exactly you've done?

**Comment by Louzuz** [comment]
Oh man, I cant remember all of the Quests, but I did the Cipher of Damnation QuestChain in SMV (Except the final one), and I also did some parts of the "Teron Gorefiend, I am..." quest chain.
I also did some quests in BEM, most of them in Evergrove.
