### ISSUE TITLE
Sunfury Signets

### ISSUE THREAD

**Issue by cjbreeze** [SunstriderEmu/BugTracker#3680]
Picked up quest for Sunfury Signets and obtained Signets and would not allow me to turn in quest. Dropped the quest and now the quest disappeared and i am unable to begin it again.

**Comment by kelno** [comment]
Could you check if you're not revered already? That quest only works up to honored.

**Comment by cjbreeze** [comment]
I am still honored

**Comment by kelno** [comment]
My bad I was thinking about Firewing signets, which only works if you're not honored yet. Sunfury signets should work all the way to exalted.
Please try creating a ticket in game, they do handle a lot of similar cases.
