### ISSUE TITLE
Misdirect not consuming proper stacks on Multi-Shot

### ISSUE THREAD

**Issue by ferron12** [SunstriderEmu/BugTracker#3686]
Hitting all 3 targets with Multi-Shot with Misdirection up should consume all 3 stacks of Misdirection.  Currently it's displaying it as only consuming one stack.

**Comment by kelno** [comment]
Thanks for reporting!
I remember this was changed because some players stated (proved?) that it should be one stack per spell, regardless of the number of targets. So I'm going to ask for some proof on this one

**Comment by ferron12** [comment]
Update:  It's consuming only 1 stack for the multi-shot, but the threat doesn't seem to be transferring correctly for all of the shots.  Used multi-shot on nightbane skeletons and one of them started running straight at me while I still had the misdirection buff up.

**Comment by TheMoneyHater** [comment]
Good find, I knew something was wrong during al'ar adds misdirects :D

**Comment by pinkisnotgay** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2701
