### ISSUE TITLE
Master of potion. Can't give back the quest

### ISSUE THREAD

**Issue by Shannash-lang** [SunstriderEmu/BugTracker#3687]
**Describe the bug**
Hello, I want to become à Master of potion but I can't give back the quest despite the fact I have the 15 potions needed and the book of second boss of Botanica.

Url Quest:
https://fr.wowhead.com/quest=10897/ma%C3%AEtre-des-potions

Items Url:
https://fr.wowhead.com/item=22829
https://fr.wowhead.com/item=22836
https://fr.wowhead.com/item=31744
https://fr.wowhead.com/item=22832

Normally, I can give back the quest when I've got all of this item. I can not

Picture:
https://goopics.net/i/poeKN

**Comment by beraus** [comment]
Make the ticket in-game, and include a screenshot (same as you provided here) and someone will help you.
