### ISSUE TITLE
Directx error only se

### ISSUE THREAD

**Issue by Delacoal** [SunstriderEmu/BugTracker#3688]
I get this error the second time I try to launch the client after starting my computer.

I have tried deleting and updating my drivers.

![image](https://user-images.githubusercontent.com/50711583/84505472-ac6b6980-acb5-11ea-954b-431bbe78ddbd.png)

This only happens the second time I launch the client. The client will not launch until i restart my computer.

**Comment by Godmatik** [comment]
Is your WoW.exe outside the game folder?

**Comment by Delacoal** [comment]
No, it's inside the game folder.

**Comment by beraus** [comment]
Try to install dx9
