### ISSUE TITLE
improved blizzard applying slow instantly

### ISSUE THREAD

**Issue by markinspencer** [SunstriderEmu/BugTracker#3689]
**Describe the bug**

improved blizzard is applying slow instantly. Should be applied on the second tick.
 
**To Reproduce**

1. Cast improved blizzard on target
2. Observe slow being applied instantly

Spell: https://classic.wowhead.com/spell=12488/improved-blizzard

**Expected behavior**

slow should be applied on the second tick of blizzard 

**Screenshots/videos**

https://youtu.be/3WOlDCBcjKc?t=477

**Comment by Jerrythemagicdog** [comment]
Spell delay, not really interested in implementing this, thanks though.
