### ISSUE TITLE
Seal of Command

### ISSUE THREAD

**Issue by shortstack1709** [SunstriderEmu/BugTracker#3690]
Seal of Command PPM is not correct (way lower than it is suppose to be). Should have a proc of 6.8-7 PPM. With a 3.5 speed that is 40% proc chance.

1. Equip a slow weapon (tested with 3.5 speed)
2. Auto attack an enemy continuously to see the proc percentage.

WEBSITE stating that seal of Command should be around 6.8-7 PPM
https://www.engadget.com/2007-11-27-the-light-and-how-to-swing-it-command-vs-blood.htm

![Seal of Command](https://user-images.githubusercontent.com/66842377/84532673-a2953680-acb4-11ea-97ec-a7014d110859.JPG)

**Comment by Jerrythemagicdog** [comment]
It is currently at 7 PPM.
