### ISSUE TITLE
Dumphry's Request quest in HP won't turn in.

### ISSUE THREAD

**Issue by Drgnspell** [SunstriderEmu/BugTracker#3692]
**Describe the bug**

I am unable to turn in the quest Dumphry's Request in Hellfire Peninsula. I have collected the 4 Motes of Fire, 2 Arcane Dust, & 4 Fel Iron Bar's. I am standing right next to him and I am unable to click the "Continue" button when I click on him to finish the quest. Please see screenshot [:)](url)

Quest: https://www.wowhead.com/quest=10763/dumphrys-request

**Expected behavior**

I am expecting to be able to complete the quest so I can get the key to Shattered Halls.

**Screenshots/videos**

![ArroganceDumphrys](https://user-images.githubusercontent.com/66854479/84556244-cffad800-ace6-11ea-8260-18000a5c047e.png)

**Additional context**

**Comment by beraus** [comment]
Make a ticket in game, please, and someone will help you. It's a known issue.

**Comment by Drgnspell** [comment]
Thanks Beraus for looking into this. I am not sure how to submit a ticket in-game. Where do I do that?

**Comment by beraus** [comment]
![image](https://user-images.githubusercontent.com/16673248/84673223-b4cbda80-af29-11ea-9c80-298a68712fe3.png)

**Comment by Drgnspell** [comment]
Thank you!
