### ISSUE TITLE
No difference in Xp gains between x8 boost and normal x5

### ISSUE THREAD

**Issue by Snootie** [SunstriderEmu/BugTracker#3694]
**Describe the bug**

Hi, 
I paid a x8 XP boost on my character and checked that in was enabled.
I had a doubt so I manually set it (on endless.gg -> Characters) to x5.
As I logged in on my character and got a message : Your xp boost is now 5.000. I killed a mob and witnessed that the xp I gained from a lv 2 mob, being lv 2 was the same.
That is : between a x8 XP boost and a x5 XP boost, I gain the same xp. 

So either the x5 is automatically set to x8 in game if I buy a boost, or the x8 does not work.

Thanks,

Snoot
**To Reproduce**

1. Set x5 XP Boost on your Character.
2. Kill a mob, write down the XP gained.
3. Set x8 XP Boost on your Character
4. Repeat. Same XP gains.

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, it was a visual error on the website in the message you received, sorry for the confusion!
