### ISSUE TITLE
Wool cloth

### ISSUE THREAD

**Issue by Roshidon** [SunstriderEmu/BugTracker#3695]
**Describe the bug**

Wool cloth drop rate at Bael Modan (barrens) is not right. It seems to be about 15% when described on wowhead it is 50%. I havn't tested other places but since there is practically none on the AH I'm guessing the drop rate is bad all over. 

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3833
