### ISSUE TITLE
Wrapping paper

### ISSUE THREAD

**Issue by ragnoren** [SunstriderEmu/BugTracker#3696]
**Describe the bug**
Wrapping Paper doesnt work and i need to gift something to my WoW gf. 
When i try using it on any item it says "item not found".

**To Reproduce**
Buy wrapping paper and try using it, it wont work.

**Expected behavior**
It should make a gift with the wrapped item in it.

**Screenshots/videos**
https://prnt.sc/sz1m7j

**Comment by z5n** [comment]
fixed
