### ISSUE TITLE
Bottled Nethergon Energy missing

### ISSUE THREAD

**Issue by mechanicsTBC** [SunstriderEmu/BugTracker#3698]
https://db.endless.gg/?item=32902
Item was added in patch 2.1, should drop from Tempest Keep and all TK dungeons.  Not sure if intentionally disabled or not.

**Comment by pinkisnotgay** [comment]
Same for https://db.endless.gg/?item=32905
Would be nice if it was added to the loot tables, since we have the vendor outside of SSC that was also added in 2.1 who also offers dungeon/raid specific potions.

**Comment by NeonicSupersonic** [comment]
It was 2.1 while we technically playing 2.0 Thought adding dailies would be a good time to add tk mana pots since after t6 release they are practically useless

**Comment by mechanicsTBC** [comment]
was added
