### ISSUE TITLE
Druid Quest: Curing the Sick [Not Working]

### ISSUE THREAD

**Issue by deptisaurus** [SunstriderEmu/BugTracker#3702]
**Describe the bug**

Hello, I picked up the quest Curing the Sick and when I salve a druid it says cured but I dont get credit. the deer has a level up animation when i cure him. a salve is used. his name changes from sick deer to cured dder. no credit.

**To Reproduce**

pick up the quest and go to a sick deer 
use the salve
it doesnt work

Item: https://wowhead.com?item= https://classic.wowhead.com/item=15826/curative-animal-salve
Quest: https://wowhead.com?quest= https://classic.wowhead.com/quest=6124/curing-the-sick
Spell: https://wowhead.com?spell= 

**Expected behavior**

when i use the salve it should cleanse the deer and i get quest credit. 

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart, for now try killing the Sickly Deer.

**Comment by deptisaurus** [comment]
At level 70 i tried both 1 shotting the sick deer and naked melee punching them for a few hits and both ways didnt give me any quest credit. Waiting for reset to try it.
