### ISSUE TITLE
teleport to HS upon entering dungeon instance

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3708]
1.  4 toons in a group enter scholomance.
2.  1 toon  entered before being invited.  
3.  1 toon invited, received message not in your instance.
4.  1 toon leave their instance, reinvited to group.
5.  1 toon zone in insta teleported to HS upon zoning.  
6.  warlock summon outside of instance, exact same problem.
7.  1 toon leave group, reset instances, reinvited.  enter same problem 2-3x
8.  1 toon exit client, relog can enter correctly.

repeated 1-8 (except step 3 & 7).  same result different toon in the same group of 5 (the party instance was never changed so the toon teleported to HS this time had previously been in the scholomance instance).

all 5 toons logged from the same ip, no more than 2 per computer per the multiboxing rules.  i dont think this is a multiboxing issue.  ive had this issue before when playing a single char, just never saw it be so persistent and repeatable.

**Comment by michaelkittrell** [comment]
issue still exists...

enter scholomance with a 4 person party
enter scholomance with person A not in any party
leave scholomance with person A
invite person A to the 4 person party
person A enter scholomance and get teleported to HS
summon person A back, enter scholomance get teleported to HS.
leave scholomance, disband the party, reform the party... zone in with 5 people, 4 people enter scholo, Person A teleported to hearthstone.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, seems like some of your characters had different dungeon reset timers based on when they entered the dungeon.
