### ISSUE TITLE
Scholomance, vectus fireshield

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3710]
killed vectus
after killing vectus, rounded up about 20-30 of the students (3/4 of the room), killed them.
after killing the last student, started getting hit by "Vectus's Fire shield" for 20-30s on multiple toons before it just stopped.  Resist almost all of the damage, but vectus had been dead for at least 60s.  did not see any debuffs/buffs related to this, just seemed to randomly start taking fireshield damage after killing students.
then killed marduk (unrelated)

**Comment by michaelkittrell** [comment]
it seems to be location based.  the fire shield effect seems to persist well beyond the death of the mob that had the fireshield.

**Comment by michaelkittrell** [comment]
if you don't loot hte corpse, fireshield continues to hit you 4+ minutes after you have killed vectus

**Comment by Sheikthecatman** [comment]
Thanks! Fixed.
