### ISSUE TITLE
The smallest Creatures quest

### ISSUE THREAD

**Issue by Phatmeme** [SunstriderEmu/BugTracker#3711]
**after using the kodohide drum and controlling the marmot all enemies are invisible. second, when trying to use the marmot ability to poison the kegs, nothing happens. trying to click on the kegs themselves it just says "you are to far away"**

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2022

**Comment by Lamberdo** [comment]
not working at this time ;/ same reason
