### ISSUE TITLE
Listing Stream at Endless.gg

### ISSUE THREAD

**Issue by AcidScytheZ** [SunstriderEmu/BugTracker#3712]
**Describe the bug**
esterday I tried to use the function in the website and it worked for like 10-20 mins... and since then I'm getting the massage "Your stream seems to be offline or just recently went live. Please wait a few minutes and try again."
**Additional context**
I've tried to unlink my twitch and link again -  didn't work.
Tried stream restarting, tried changing titles and whatnot.
Been waiting for more than just few minutes... actually gave it a day and guess what... today its the same thing again.

**Comment by Jerrythemagicdog** [comment]
Do you have the keyword endless in your title and are you changing your title?

**Comment by hufsa** [comment]
The streams page was updated recently. Could you try again to see if the error is still there?
