### ISSUE TITLE
Guild Repairs

### ISSUE THREAD

**Issue by Denagul** [SunstriderEmu/BugTracker#3713]
**Describe the bug**
Guild Repairs do not use up guild bank funds, rather just your own gold, regardless of which of the 2 repair buttons you use.

**To Reproduce**
1. Have Permission to use guild gold for repair
2. Have a repair bill
3. Use the guild repair instead of the normal repair

**Expected behavior**
Guild repair money allotted for that day should be used up instead of your own gold.

**Screenshots/videos**
https://www.youtube.com/watch?v=goGiW_9mLbg

**Additional context**
Other members of the guild who have guild repair funds can use this, however i am not alone in this bug at least within my guild, not sure if other guilds are affected. I also tested both leaving and getting kicked out of the guild then get invited again and the bug persisted.

**Comment by kelno** [comment]
Thanks for the video, we tried reproducing but we didn't manage to do it so far, if anyone got any idea or details there it's welcomed.

**Comment by mechanicsTBC** [comment]
It's caused by an addon.  Can't remember which but had the same issue on last TBC server as well.  Some people seem to think its vendor value.

**Comment by michaelkittrell** [comment]
i agree, its addon bug.  i also believe it is the vendor values addon.

**Comment by Denagul** [comment]
Thanks for the suggesion, it was indeed vendor values. An interesting interaction that happens with guild repairs is that each individual item repaired generates an entry into the money log of the guild bank...I mention this as it may lead to a clue as to what's causing this addon to bug out guild repairs. 
![image](https://user-images.githubusercontent.com/60157396/85108979-781c0f80-b1c5-11ea-88dc-2a835983de76.png)

**Comment by artieau** [comment]
Guild repair is working correctly
