### ISSUE TITLE
Stuck on loadingscreen, might need to move the character?

### ISSUE THREAD

**Issue by chooff123** [SunstriderEmu/BugTracker#3714]
**Describe the bug**
Wow crashes on the loading screen, every time I try to log on my character Chooff

**To Reproduce**
I was flying from Stormwind to Ironforge, about to land in ironforge when it crashed
**Expected behavior**
Be able to log in

**Screenshots/videos**
-
**Additional context**
If you could move my character to ironforge where I am able to log in I would appreciate it!
Thanks

**Comment by beraus** [comment]
Write a ticket in-game and we'll move you to another location as a temp fix, but it sounds like you'll need to download new game client.

**Comment by InhumanGM** [comment]
I have moved your character. Not sure what causes this to happen, but it tends to happen a lot in Shattrath as well.

**Comment by chooff123** [comment]
Thanks for the help!
