### ISSUE TITLE
[NPC] Sar'this stuck in animation 

### ISSUE THREAD

**Issue by lifterfans001** [SunstriderEmu/BugTracker#3718]
druid swift flyform pre-quest [The Eagle's Essence]  bugged.when i talk to npc:sar'this and he cant summon mob the guardian of the eagle failed.process stoped.npc stucked.can u fix it?

![image](https://user-images.githubusercontent.com/66994309/84752215-09d22400-aff0-11ea-8a41-e4d07d3b19cb.png)

**Comment by lifterfans001** [comment]
npc Sar'this stuck again ;P
![image](https://user-images.githubusercontent.com/66994309/84832367-b1d30600-b05f-11ea-877f-c083032d1489.png)

**Comment by Keritous** [comment]
I have done it yesterday and never engaged with this NPC. Quests worked fine and I got my flight form.

**Comment by Jerrythemagicdog** [comment]
Pushed a fix, NPC will reset itself if it gets stuck after 15 minutes.
Thanks for the issue.
