### ISSUE TITLE
Rogue: Enveloping Shadows bugged

### ISSUE THREAD

**Issue by becike84** [SunstriderEmu/BugTracker#3719]
Fully resisting frost novas with talent breaks your stealth, even u not get damaged or snared by it.
Pls check out. My rog has also surefooted, but then i would get damaged by nova and break stealth and resist the snare.

But actually i fully resisted frost nova by combat log, and didnt get any damage due to Enveloping Shadows talent, and still breaking my stealth.

When you use Cloak of Shadows as stealthed, u may resist spells avoiding breaking your stealth, so in this case Enveloping shadows resisting aoe effect should not break stealth also.

pls check it out,   best regards. B.

**Comment by blblblaz** [comment]
couldn't reproduce, fully resisted Frost Nova by Enveloping Shadows didn't break stealth in my case - https://streamable.com/vc3wkq

about surefooted, as far as we're aware that's how it's supposed to work, only the snare/root effect of the spell gets resisted but the damage goes through

need more information/video if possible, thanks for the issue!
