### ISSUE TITLE
Trial of the Naaru: Mercy - Wrong timer bug

### ISSUE THREAD

**Issue by richardszanyi** [SunstriderEmu/BugTracker#3721]
**Trial of the Naaru: Mercy quest should be able to be completed after the executioner killed 1 or 2 prisoners or until 80 minutes of time.**

**To Reproduce**

1. Pick up trial quest
2. Go to SHH HC, and start the gauntlet.
3. Wait until the first prisoner is executed.
4. Kill the Executioneer at the end of the dungeon
5. It does not drop the quest item anymore.

Item: https://www.wowhead.com/item=31716/unused-axe-of-the-executioner
Quest: https://www.wowhead.com/quest=10884/trial-of-the-naaru-mercy

**Expected behavior**

Quest item should drop after the executioneer kills 1 or 2 guards. [Wowwiki](https://wowwiki.fandom.com/wiki/Quest:Trial_of_the_Naaru:_Mercy) states: 

> ...your group has 80 minutes to reach Combat 15 Warchief Kargath Bladefist. The quest description is misleading, as a prisoner or two may be killed and you can still get the quest item - so don't be quick to give up if you miss the deadline, or even a few kills.

**Comment by Jerrythemagicdog** [comment]
> Within the Shattered Halls of Hellfire Citadel are three of your people. They are held there by the merciless one, Kargath Bladefist. He seeks to execute them as a sign of his virility and power. You must save these prisoners before such an atrocity can come to pass. As proof of deed, bring me the unused axe of the executioner. It must not have a drop of blood on its blade!

Sounds like a retail bug, doesn't look like something we should look into doing.
Thanks for the issue though!

**Comment by richardszanyi** [comment]
Okay, so I suppose this emulator - is not "blizzlike" is it?
If so - any changes from the retail TBC server would be considered a bug, or an issue in the emu. 
Just my two cents here.
