### ISSUE TITLE
 [The Cipher of Damnation - Borak's Charge] Issue problem

### ISSUE THREAD

**Issue by Asteroweed** [SunstriderEmu/BugTracker#3724]
**Describe the bug**
I can"t ending  [The Cipher of Damnation - Borak's Charge] quest in Shadowmoon Valley even with the "Third Fragment of The Cipher of Damantion" in my bag.

Item: https://www.wowhead.com/item=30645/third-fragment-of-the-cipher-of-damnation
Quest: https://www.wowhead.com/quest=10578/the-cipher-of-damnation-boraks-charge

**Expected behavior**
Ending the quest

**Screenshots/videos**
Screenshots in this mail

Character's name : Azgaaroth (Orc hunter)
![WoWScrnShot_061620_181910](https://user-images.githubusercontent.com/67016272/84801640-b798ff00-afff-11ea-81c8-e33390dcd8d4.jpg)
![WoWScrnShot_061620_181850](https://user-images.githubusercontent.com/67016272/84801644-b8319580-afff-11ea-8c35-62c61da87209.jpg)

**Comment by InhumanGM** [comment]
Please create an in-game ticket so we can further assist you with this issue!
