### ISSUE TITLE
Shadowpriest talent SW Death not available at lvl 63

### ISSUE THREAD

**Issue by zecke345** [SunstriderEmu/BugTracker#3726]
i dont get the talent "SW death" lvl 1 from the priest trainer. i am lvl 63. and its a lvl 62 talent
its not even in the trainers list, normally u see whats unavailable. i only see (in red) SW death lvl 2 (for lvl 70).  clearly i should be getting this talent at lvl 62 , looked it up. plz fix this

https://tbc-twinhead.twinstar.cz/?spell=32409

i definitely dont continue without it, 
ingame char:    Bona

**Comment by Jerrythemagicdog** [comment]
Not every trainer seems to have that spell, please try with a higher level trainer, thanks.

**Comment by zecke345** [comment]
i can skill up to lvl 70 from the trainer i got to.
the support answered and said its a known bug and needs to be fixed.
as i wrote: its not even in the (red unavailable) list at all. i should get it at lvl 62.
