### ISSUE TITLE
Rogue: combo points disappearing randomly

### ISSUE THREAD

**Issue by Felthorn10** [SunstriderEmu/BugTracker#3727]
Up until recently the last week or so I wasn't experiencing this, but a lot of the time when I reach 5 combo points they will disappear upon use of my next special move, be it a finisher or a normal(hemo for example). Sometimes they disappear without me doing anything at all. No entry exists in my combat log if, for example, I try to use eviscerate. The combo points seem to be consumed by it but no attack is made. This seems completely random and it's both in PvE and PvP. It just happened to my toon within the last 10 minutes in an eye of the storm.

Toon name: Fapplejuice

**Comment by Jerrythemagicdog** [comment]
Thanks for the detail here, the character name was very helpful!
It seems you have the "Setup" talent on your character in Subtlety tree that adds combo points to an attacker after you dodge or fully resist one of your attacks, which would explain your combo points being added to a different target when fighting multiple enemies and wiped from your main target.
Let us know if that sounds familiar, thanks.

**Comment by Felthorn10** [comment]
It shouldn't work that way though based on the wording. It says "your target" which means the player/enemy I currently have targeted, not a different one that is in combat with me.

**Comment by Felthorn10** [comment]
I'm now noticing this happens the most frequently when I'm fighting a warlock, not sure if you can check. Toon name Fapplejuice, just happened within the last 3 minutes in alterac valley.

**Comment by Felthorn10** [comment]
This is still occurring, happened during a solo fight with a shaman about 5 minutes ago, toon name Fapplejuice. I didn't use a finishing move and my combo points disappeared.

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago.
