### ISSUE TITLE
Recipe: Flask of Supreme Power missing from Ras Frostwhisper's loot table?

### ISSUE THREAD

**Issue by tyshies** [SunstriderEmu/BugTracker#3728]
-General Question-
Currently, in around 35-40 kills (12 today), I have seen the entire loot table from Ras Frostwhisper at least once, if not twice (ive seen the Epic Robe twice, which has a 2% lower drop chance), except for the Flask recipe.

Is it just missing as a bug, or was it removed from his loot table, or am i just really unlucky?

**Comment by Jerrythemagicdog** [comment]
The recipe is currently at 4% drop chance, you seem to be getting really unlucky!
Thanks for the issue.
