### ISSUE TITLE
Burning Steppes hole in terrain.

### ISSUE THREAD

**Issue by SimoTheInsane** [SunstriderEmu/BugTracker#3730]
**Describe the bug**
Terrain in Burning Steppes (cords visible on Screenshot) have little hole inside just enough size to get stuck inside if you fall in.

**To Reproduce**
1. Jump into a hole.
2. ...
3. No Profit.

**Expected behavior**
No hole in terrain.

**Screenshots/videos**
![WoWScrnShot_061720_173433](https://user-images.githubusercontent.com/9005549/84918916-884ac680-b0c1-11ea-884a-e0f78e203fe7.jpg)
![WoWScrnShot_061720_173445](https://user-images.githubusercontent.com/9005549/84918920-897bf380-b0c1-11ea-8e01-4cadd0bef11f.jpg)

**Comment by Jerrythemagicdog** [comment]
Thank you, we'll send our best men to patch up the hole with some sort of sheet metal!

**Comment by Jerrythemagicdog** [comment]
It seems the situation is under control now 
![image](https://user-images.githubusercontent.com/46463908/84934174-de723680-b0ce-11ea-8f87-1d50599d1525.png)
Live with next restart.
