### ISSUE TITLE
Rogue Poisons do not benefit from Spell Damage

### ISSUE THREAD

**Issue by afilipov93** [SunstriderEmu/BugTracker#3731]
Hello,

Poisons don't benefit from Spell Damage. I have done testing and it seems that there is no damage increase whatsoever. Could you please check on your side and if so add Wound, Deadly and Instant Poison to the Spell Power table?

N.B: I can record my testing if need be but I think it will be easier to just check on the server side.

Thank you and regards,
Alex

**Comment by babno** [comment]
Can you provide any evidence that they should benefit from spellpower?
