### ISSUE TITLE
[Quest] The vengeful Harbinger

### ISSUE THREAD

**Issue by Shol4891** [SunstriderEmu/BugTracker#3732]
This quest seems bugged

The draeneis adds come really really fast by waves and they focus their attacks on the the Tomb Guardian, so its almost impossible to defend him

**Comment by AdrianSorrow** [comment]
the mobs also ignore all and focus in the Guardian, i try to taunt em and nothing happen

**Comment by Sheikthecatman** [comment]
Issue was fixed in [1ad1eecf68bdcaafae184b36f52a2ed14ec199db](https://github.com/kelno/sunstrider/commit/1ad1eecf68bdcaafae184b36f52a2ed14ec199db) and the fix is already live.
