### ISSUE TITLE
Magtheridon's Lair adds before boss

### ISSUE THREAD

**Issue by Creeves0** [SunstriderEmu/BugTracker#3733]
**Describe the bug**
The packs of mobs before the boss are stacking the shadow damage debuff really fast and with a very far range (as well as the fear).
**To Reproduce**
1. Tanks pull adds
2. Ranged are max range and still getting multiple debuffs

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, that's intended, we might change it in the near future though!

**Comment by Creeves0** [comment]
The issue is that it was happening super fast and stacking multiple times at once. It definitely didn’t do that last week.
