### ISSUE TITLE
Battle of the Crimson Watch completed, but shows up as failed

### ISSUE THREAD

**Issue by andrewf29** [SunstriderEmu/BugTracker#3734]
**Describe the bug**
My group and I completed the Battle of the Crimson Watch quest successfully. My group members got credit for the quest but it showed up as Failed in my quest log, even though the objective itself shows up as completed (image attached below). 
Character: Drewmeda, lvl 70 tauren warrior

**To Reproduce**
Not sure, but I think it has to do with us failing the quest in previous attempts. I made sure to abandon the quest every time we wiped then start it again with my group (using the prompt that asks you if you want to accept and start the group quest), so it wasn't the result of me just not correctly picking up the quest.

Quest: https://www.wowhead.com/quest=10781/battle-of-the-crimson-watch

**Expected behavior**
After killing the few waves of mobs and the final elite NPC, I had expected the quest to appear as complete and to be able to turn it in to Adal.

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/51676430/84994573-7d6b5280-b110-11ea-989e-431f53da5bb3.png)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue. I'm not sure what we can do here, it seems that the script must've failed it for you at some point. 
These are the conditions under which the quest is marked as failed:
1. Stepping out of the event area (moving out of the main platform).
2. Dying during the event.
