### ISSUE TITLE
Items that shouldn't be in game yet

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3737]
According to #2493 and #3716 you apparently don't want items from future patches to be available yet. So I compiled a quick (and incomplete) list of some items that are available and shouldn't be.

Engineering goggles, 2.1 https://www.wowhead.com/item=32495/powerheal-4000-lens
great dawnstone, 2.1 https://wow.gamepedia.com/Great_Dawnstone
honor pvp gear, 2.4 https://www.wowhead.com/item=35329/dreadweave-hood
cloak of darkness, 2.2 https://www.wowhead.com/item=33122/cloak-of-darkness
elixir of draenic wisdom and major fort, 2.1 https://www.wowhead.com/item=32067/elixir-of-draenic-wisdom
enchant shield resiliance, 2.3 https://wowwiki.fandom.com/wiki/Enchant_Shield_-_Resilience
I especially like the last one, because you can see both the enchant and the fish finding book are just a few lines apart in the same patch notes

So that's about 100 items that you will surely be removing from the game as they shouldn't be available yet, should be a good start as there are plenty more that'll need to be removed as well. Or is fish finding just too game altering compared to the above?

**Comment by Jerrythemagicdog** [comment]
The "Weather-beaten Journal" has a 1% drop chance from "Bag of Fishing Treasures" which is a reward from fishing dailies, which will be available when Ogri'la and other hubs come out (soon).
I see that the Journal should be available from other sources as well though and we'll add it there too.
Some sources: https://wowwiki.fandom.com/wiki/Weather-Beaten_Journal
Thanks for the issue, live with next restart.

**Comment by babno** [comment]
@Jerrythemagicdog Thank you. Can you confirm when it's been added? Already wasted many hours  trying to get it in vain when it was unavailable.

**Comment by Jerrythemagicdog** [comment]
Sure, when the next changelog comes out you can be sure that it's live.
