### ISSUE TITLE
NPC Jadefire Trickster cast Cause Insanity and instantly kills

### ISSUE THREAD

**Issue by kimurin** [SunstriderEmu/BugTracker#3738]
**Describe the bug**
Jadefire Trickster in Fellwood (43.5 17.0) cast spell Cause Insanity, which instantly kills player (probably, only if he has no pets or not in group).

**To Reproduce**
1. Attack the mob.
2. Wait 10 seconds.
3. Mob cast the spell.
4. Player is dead.

NPC: https://classic.wowhead.com/npc=7107
Spell: https://classic.wowhead.com/search?q=cause+insanity
Drives an enemy target temporarily insane, speeding its attacks by 100% and its movement by 150%, **as well as causing it to attack its own allies for 10 sec.**

**Screenshots/videos**
![cause_insanity](https://user-images.githubusercontent.com/924688/85056802-860f6780-b1a8-11ea-9389-ff46b55f4aa4.jpg)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
