### ISSUE TITLE
Shadowpriest talent SW Death not available at lvl 63   #2 (URGENT)

### ISSUE THREAD

**Issue by zecke345** [SunstriderEmu/BugTracker#3739]
WHY THE HELL DO YOU CLOSE THIS ISSUE? ARE U SERIOUS??? 

I WAS AT EVERY PRIEST TRAINER ALREADY!!!!!!!!!!!!!!!!!!!!!!!!!!!! The support confirmed it's a known bug. 
It's just pointless to continue on this server, bugfestival deluxe. This just is ridicolous. 
Whats your explanation, that i dont get lvl 1 SW death, but EVERY other talent up to lvl 70 from same trainers? Makes 0 sense. 

https://github.com/SunstriderEmu/BugTracker/issues/3726

i dont get the talent "SW death" lvl 1 from the priest trainer. i am lvl 63. and its a lvl 62 talent
its not even in the trainers list, normally u see whats unavailable. i only see (in red) SW death lvl 2 (for lvl 70). clearly i should be getting this talent at lvl 62 , looked it up. plz fix this

https://tbc-twinhead.twinstar.cz/?spell=32409

i definitely dont continue without it,
ingame char: Bona

**Comment by Jerrythemagicdog** [comment]
The spell is a level 62 spell and your character already has it (I just checked in game). Please check your spell book's shadow school. Thanks!

**Comment by Jerrythemagicdog** [comment]
What must've happened here is you learned it without realizing it.

**Comment by zecke345** [comment]
Ok sorry for my tone, i got explosive. Idk what really happened. U did not fix it ingame?! I always look very carefully what the trainer gives me each lvl. I checked the spellbook numerous times.
The symbol of pain and death look almost the same. It must have been there all the time then?
Hard to believe, but it was always there wtf lol ? Bc the support told me its a known bug.

I have it in my spellbook now, thanks for help
u can close the issue

**Comment by Jerrythemagicdog** [comment]
No problem, I haven't done anything, only checked if you already had the spell.
