### ISSUE TITLE
The Lurker

### ISSUE THREAD

**Issue by Dayghini** [SunstriderEmu/BugTracker#3740]
Tonight we did Lurker and it did a whirlwind while he was sprouting and killed some people. It was super strange because it happened so fast even for a whirl but it showed that he was going to whirl in the timer as it happened. The most strange thing of all is that it happened only once while sprout was rotating and it moved like 30-40 degrees only before the bug occured.

**Expected behavior**
I expected that sprout will rotate 360 degrees from when it started and then whirlwinds should trigger

**Screenshots/videos**
https://clips.twitch.tv/SmilingBitterBottleBleedPurple

**Comment by Ironjudgment** [comment]
Can confirm, happened to my guild as well.

**Comment by michaelkittrell** [comment]
confirm, happened to my na guild as well.  opened a similar ticket 1-2 weeks ago for same/similar problem.

**Comment by mechanicsTBC** [comment]
#3675 @Jerrythemagicdog

**Comment by michaelkittrell** [comment]
still happening.  
in the 3rd or so resurface, it rotated about 15 degrees, then rotated 180 degrees instantly and continued to spout from there.

someone said "it only happens on the first pull"  not sure if that's true.

**Comment by Keritous** [comment]
https://clips.twitch.tv/FrailViscousMelonSeemsGood
had the issue in 1st try.

**Comment by beraus** [comment]
Should be fixed with https://github.com/SunstriderEmu/BugTracker/issues/3675
Let us know if you notice any other issues, please.
