### ISSUE TITLE
TK alar patrol

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3742]
patrol going to alar.

after zoning in, you have to be standing at the doorway just before the first pack or the patrol isn't active and doesn't patrol.  once you activate it (by moving far enough forward), it seems to continue to patrol for a while

also, sometimes the patrol captain desyncs with its squires (after some wipes?).  the squires somehow end up standing with the first trash pack (of 6 mobs) and the captain is solo patrolling in the back until he reaches the front then he picks up his squries again.  no idea if this is a visual bug.

**Comment by bjh368** [comment]
this server has some issues in general with mobs being outside render distance in instances stop moving, most notably patrols in TK, wandering bog lords in ssc and the elementals walking in front of hydross

**Comment by Jerrythemagicdog** [comment]
Resolved a long time ago, thanks for the issue.
