### ISSUE TITLE
tk devastator patrol going to void reaver 

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3743]
the devastator patrolling the corridor going to void reaver initially doesn't seem to move at all until you pull the first pack... so you can't pull right after it paths away.  though the initial time you pull the patrol does seem to come at a predictable time, subsequent pulls are less predictable... like it stops patrolling when you wipe and starts from that (random location) the next time you pull.  there doesn't seem to be any place (even stealthed) that you can be to force the patrol to start moving.  

would be perhaps better if the behavior of the patrol was consistent/predictable or moved always so you could decide how/when you want to pull.

**Comment by mechanicsTBC** [comment]
this is a problem with both patrols on the way to void reaver and towards solarian due to the very short view distance on the server.

**Comment by mpuryear** [comment]
There is a temporary workaround you can do. There is a sweet spot to the left/right that you can stand that will trigger their pathing as you are close enough to them. Then once they path all the way to you, you can pull them before pulling the other mobs. 

/tar the mob and put a mark on it to see when it starts moving.

**Comment by michaelkittrell** [comment]
thanks for the tip, we'll try it out

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3742
