### ISSUE TITLE
The Exorcism of Colonel Jules

### ISSUE THREAD

**Issue by Fahad123456** [SunstriderEmu/BugTracker#3745]
**Describe the bug**

The quest is bugged it says it's completed but i can't turn it in, tried restarting, abandoning then trying again, abandoning restarting then trying again same result .
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=The Exorcism of Colonel Jules

Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Who are you trying to turn it in to?

**Comment by Fahad123456** [comment]
The golden question mark is above Assistant klatu's head, in the quest it says to talk to jules but nothing happens.
