### ISSUE TITLE
Alterac Valley - Graveyard being tagged causes dead players to not teleport to another graveyard

### ISSUE THREAD

**Issue by Felthorn10** [SunstriderEmu/BugTracker#3746]
If a player dies in AV and is dead while an enemy player tags the graveyard they are waiting to rez at, the spirit healer disappears and the player does not get teleported to another graveyard like they are supposed to.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, is that any graveyard in AV or some particular graveyard?

**Comment by Felthorn10** [comment]
It appears to be any. I've experienced it at Aid Station, Stormpike, Frostwolf and Relief Hut

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by ageerik** [comment]
Still as ally on stonehearth gy. When horde caps it you jsut stand there dead.

**Comment by Cayman91** [comment]
The same issue still exists. Checked on ally side. Especially the GY next to Vann

**Comment by kelno** [comment]
Fixed since
