### ISSUE TITLE
Scalding Water in SSC activates molten armor to self damage mage

### ISSUE THREAD

**Issue by RighteousSloth** [SunstriderEmu/BugTracker#3748]
After clearing all adds on platforms around Lurker to activate Scalding Water if a mage has molten armor on it will trigger the damage of molten armor if they take a tick of the damage, and that damage will self damage the mage.
Please check image linked to see an example from combat logs:
![image](https://user-images.githubusercontent.com/46618625/85188562-98a3a280-b275-11ea-9bb7-6bef2e1b3683.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
