### ISSUE TITLE
increase respawn time

### ISSUE THREAD

**Issue by vfilipovsky** [SunstriderEmu/BugTracker#3750]
Hello! Its not a bug, but please, increase mob respawns time. A lot of places are unreachable... Im talking about leveling in classic zones.

**Comment by vfilipovsky** [comment]
I will expand my problem: its very hard to complete some quests like in Hillsbrad where a lot of mobs are located close to each other by 2-4 in pack. When u killed pack, you have to restore mana/health and when you start killing next pack, previous one just respawned :D even in party with 2 ppl we were unable to complete this.

**Comment by beraus** [comment]
Thanks, we'll take this into consideration
