### ISSUE TITLE
Shadowfiend has too slow runspeed.

### ISSUE THREAD

**Issue by Kraizn** [SunstriderEmu/BugTracker#3752]
**Describe the bug**
Shadowfiend can be kited by just running away with slightly higher speed than the default value.

**To Reproduce**
1. Summon Shadowfiend and let it attack an enemy (with speed enchant on boots or run speed meta gem)
2. Enemy run straight in one direction away from the shadowfiend
3. Shadowfiend cant catch-up after a few seconds

Spell: https://db.endless.gg/?spell=34433

**Expected behavior**
The Shadowfiend should be able to catch up to a certain degree.

**Screenshots/videos**
https://youtu.be/ukgAf3MVRM4?t=372
Here the shadowfiend only slightly slower then druid in travelform for example.

**Additional context**
I found this note:
Patch 3.1.0 (14-Apr-2009): Health scaling increased. Now receives 30% of the master's spell power. Mana return increased to 5%, up from 4%. The Shadowfiend now returns mana when its melee attacks land, rather than when it deals damage. **Movement speed normalized to player movement speed.** Tooltip revised.

So it seemed not to be normalized before wotlk. And had a fixed value ?

**Comment by kelno** [comment]
Thanks for the source, fixed with next server update.

**Comment by kelno** [comment]
Reverted for now, staff not convinced by evidence + "shadowfiend is speed 1 on classic btw"
