### ISSUE TITLE
[Quest] Purification Mixture bug in the quest Helboar, the Other White Meat 

### ISSUE THREAD

**Issue by kimurin** [SunstriderEmu/BugTracker#3753]
**Describe the bug**
Purification Mixture in the quest Helboar, the Other White Meat uses two Tainted Helboar Meat instead of one. One on use and one after cast.

**To Reproduce**
1. Kill Deranged Helboar.
2. Get two Tainted Helboar Meat.
3. Use Purification Mixture.
4. One Tainted Helboar Meat is used immediately.
5. Second Tainted Helboar Meat is used after cast time.

Item: https://www.wowhead.com/item=23248
Item2: https://www.wowhead.com/item=23268
Quest: https://www.wowhead.com/quest=9361

**Expected behavior**
Tainted Helboar Meat must be consumed after cast time.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
