### ISSUE TITLE
Endless.gg coin store issue?

### ISSUE THREAD

**Issue by Nekx-drOOd** [SunstriderEmu/BugTracker#3754]
Is this fasterpay thing bugged or broke? Been trying to buy some coins for a race change for two days but it just makes the buffering sign when I click pay. I also tried to go on their website to make an actual account, thats FUBAR as well. Can you add something simple like Paypal to the coin store?

**Comment by Jerrythemagicdog** [comment]
Hello, thanks for the suggestion, we'll look into it, for now we're sticking with the current solution.
