### ISSUE TITLE
The Final Code

### ISSUE THREAD

**Issue by Roshidon** [SunstriderEmu/BugTracker#3755]
This quest is basically impossible to do solo with the respawn rate the way it is. You have to set off a mana bomb in the center of the village that is surrounded by about 8 blood elves and there is a cast time to set it off. Not to mention the mobs are packed so close together that if they get low they can run off and easily grab a friend.

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
This is a respawn rate suggestion not an issue with the quest. Thanks though, we'll consider it!
