### ISSUE TITLE
Quest Call Of Fire 

### ISSUE THREAD

**Issue by stormfuryz** [SunstriderEmu/BugTracker#3756]
Second part of the quest chain is to get Fire Tar from razormane casters in the barrons.
The item dosen't drop.
Its for shammy fire totem.

**Comment by beraus** [comment]
https://classic.wowhead.com/quest=1525/call-of-fire#comments

**Comment by Jerrythemagicdog** [comment]
Couldn't reproduce either, got mine on the first kill. We've buffed the drop rate slightly though, thanks for the issue.
