### ISSUE TITLE
judgement of the crusader  ,seal of blood. [major]

### ISSUE THREAD

**Issue by tbxgame** [SunstriderEmu/BugTracker#3757]
[ judgement of the crusader ] increase holy damage, not working on [ seal of blood ].
 [ seal of blood ] : all melee attacks deal holy damage equal to 35% of normal weapon damage,
[ crusader strike ] is a melee attack,it should triger the seal of blood ,not sure if [judgement] is a melee attack, but i do remember it is in patch 3.0.
and   should [ crusader strike ] triger [ seal of command ]?

**Comment by tbxgame** [comment]
and spell power should work on [ seal of blood ],its holy damage,based on normal attack,and spell power

**Comment by Taunted** [comment]
Crusader strike shoud not apply seals But yes crusade shoud add more holy dmg to the seals. Also t4 bonus 2 if i remember correct also increase 15% of bonus dmg from crusade associate to holy dmg.

**Comment by Jerrythemagicdog** [comment]
[ judgement of the crusader ] increase holy damage, not working on [ seal of blood ].

https://github.com/SunstriderEmu/BugTracker/issues/2393

> The seal only scales with weapon damage, not spell damage. It therefore heavily favors melee-geared Paladins (mostly Retribution Paladins), rather than spelldamage-geared Paladins. Note that the Judgement does scale with spell damage.

from https://wowwiki.fandom.com/wiki/Seal_of_Blood


https://www.wowhead.com/forums&topic=35733#p327974

> "The Jotc tooltip is a little off, it says dmg taken by but really only increases your spellpower against the target so abilities without any or a low coefficient receive very little to no benefit."

**Comment by Jerrythemagicdog** [comment]
Crusader Strike can trigger weapon procs (like enchants) but doesn't proc Seal of Blood which is correct.
Some details here: https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3482

**Comment by tbxgame** [comment]
> 
> 
> Crusader Strike can trigger weapon procs (like enchants) but doesn't proc Seal of Blood which is correct.
> Some details here: [FeenixServerProject/Archangel_2.4.3_Bugtracker#3482](https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3482)

 judgement of crusader should increase all holy damge include seal of blood,and spell powers does it too,its not wlks seal of blood,in wlk paladins need no more spell power,cus attack power gives pell power in talent tree.

**Comment by tbxgame** [comment]
> 
> 
> Crusader Strike can trigger weapon procs (like enchants) but doesn't proc Seal of Blood which is correct.
> Some details here: [FeenixServerProject/Archangel_2.4.3_Bugtracker#3482](https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3482)

if spell power shouldn't increase dmg from seal of blood,at least judgement of crusader should do.cus its written there. if judgement of crusader is not working on seal of blood,why it can increase the dmg from seal of command?
[ seal of command ]:gives the paladin a chance to deal additional holy damage equal to 70% of normal weapon damage.
[ seal of blood ]:all melee attacks deal additional holy damage equal to 35% of normal weapon damage.
tell me the different from them, its nothing else but only "chance" --"all melee"  and "70%"--"35%"
and , if judgement of crusader cant increase dmg from seal of blood and seal of command,whats the point this ability exist. its not logical.
 wowwiki is not always correct,what wowwiki describe seal of blood is not for 2.43,it says"Melee attacks deal additional Holy damage at the cost of health.Duration: 30 minutes. "
and  2.43 ret paladins need spell power or whats the differences between TBC and WLK.
the blz designs so many plate with strength and spell power,thats for paladins.
talk about WLK, the crusader strike do proc seal of righteouseness,we dont talk about judgement and seal of command,they are totaly not same in WLK.you can find out in WARMANE's WLK server.
and feenix not fixing server very well you know that.
