### ISSUE TITLE
weird hunters mark x10 in undercity?

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3762]
came out of the silvercity tp above undercity and saw what looks like a hunters mark repeatedly being applied to an invisible/untargetable mob?  also can't see any hunter around.  looks strange.

location: 68.43, 08.74  undercity ruins of lordaeon

![image](https://user-images.githubusercontent.com/5479930/85227939-3a6de100-b395-11ea-9c92-51336ceba473.png)

**Comment by Taunted** [comment]
Also have one of these in Shatt. Not sure why xD

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
