### ISSUE TITLE
Druid Aura BUG next respec in website

### ISSUE THREAD

**Issue by cssarto** [SunstriderEmu/BugTracker#3763]
after using the website's respect logged in the game for the dual boomkin specialization for restoration, a 5% critical aura is still active.

![WhatsApp Image 2020-06-21 at 12 22 01](https://user-images.githubusercontent.com/17818760/85228563-710a2280-b3ba-11ea-8038-a91ae11a6a81.jpeg)
![WhatsApp Image 2020-06-21 at 12 22 01 (1)](https://user-images.githubusercontent.com/17818760/85228567-736c7c80-b3ba-11ea-8e3a-f2f726a4a9fe.jpeg)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.

**Comment by cssarto** [comment]
No problem...

Ajust bug of Shaman enhance please.
