### ISSUE TITLE
Hit rating not adding up correclty.

### ISSUE THREAD

**Issue by Lilillium** [SunstriderEmu/BugTracker#3765]
Hello,

The hit rating on my gear adds up to 195 but it's showing and it's listed at 175 in the Spell tab. I've re-gemed my gear and no change or goes down because it's not adding the new gem hit to my hit rating total. I believe it has to do with gems because when I swap gear the hit rating total changes.

Any assistance would be greatly appreciated.

Thanks,
-Lilillium

Item: Rigid Dawnstone, Veiled Noble Topaz

**Comment by Jerrythemagicdog** [comment]
You're gemming Hit Rating gems not Spell Hit rating gems. Those are two different stats in TBC.
You will need to use a few "Great Dawnstone".
