### ISSUE TITLE
Power word: Fortitude

### ISSUE THREAD

**Issue by Havvehaff** [SunstriderEmu/BugTracker#3773]
**Describe the bug**

Rank 7 PWF shows when buffed that stamina is increased by 79, when it should be 102. (This is the values with 2/2 improved PWF talent.

**To Reproduce**

1. Cast PWF on self
2.  Hover over it
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
The tooltip is not updated with the talent.
