### ISSUE TITLE
Default chat

### ISSUE THREAD

**Issue by Keritous** [SunstriderEmu/BugTracker#3774]
Default chat channel should be among of ( guild chat, raid, party, say) which used last but here whisper, global channels, /yell and even /e are included too and shouldn't be.

**To Reproduce**
type /yell Hello press enter then press enter again and you see default chat is /yell.

**Comment by Jerrythemagicdog** [comment]
Sounds like an addon issue.

**Comment by InhumanGM** [comment]
This definitely could be an addon issue, I don't seem to run into the problem upon testing.
