### ISSUE TITLE
target dummies in ogrimar

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3775]
all target dummies in valley of honor around 69.3 and 15.75 ( (all of them?) are missing in ogrimar

**Comment by michaelkittrell** [comment]
and the ones in hunter rise in thunderbluff.  

probably other places too

**Comment by michaelkittrell** [comment]
found some in tb @25.92, 49.79   never noticed these before.  not sure if they're supposed to be here or not.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2128
