### ISSUE TITLE
50% honor boost does not apply for Concerted Efforts quest

### ISSUE THREAD

**Issue by sukablyater** [SunstriderEmu/BugTracker#3777]
Hey!

The quest Concerted Efforts gives honor according to the normal 1x honor rate, altough on the website it says there is 50% boost in honor for alliance, so it should give 1.5x in the quest reward as well.

**To Reproduce**

1. Accept Concerted Efforts 
2. Read quest log for reward details
3. See that it gives normal honor instead of 1.5x

**Comment by beraus** [comment]
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/3375
