### ISSUE TITLE
unstable affliction dispell damage doesn't benefit from spellpower

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3778]
For reference, the base value of the dispel damage before any modifiers like CoE, shadow mastery, or improved shadow bolt is 1728-1737. The aforementioned talents/debuffs account for the marginally higher damage. Note I actually have 858 bonus shadow damage.

![image](https://user-images.githubusercontent.com/244626/85326790-d5e97980-b49b-11ea-9674-bf6d06e3a334.png)

I realize this is patch 3.3 but it's the oldest source i could find for specific spell coefficients, and the value of 180% seem reasonable. If anyone has another source I'd be most interested.

https://wowwiki.fandom.com/wiki/Spell_power_coefficient

with my spellpower and no CoE/imp shadow bolt but yes shadow mastery, it should hit for about 3600.

**Comment by TheMoneyHater** [comment]
https://i.imgur.com/ELQdNXs.png

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
