### ISSUE TITLE
Reputation Spillover

### ISSUE THREAD

**Issue by Drokmon** [SunstriderEmu/BugTracker#3779]
General reputation spillover between factions in the same grouping (ie. Horde factions) does not seem to occur.  For example, one can complete a quest for Undercity (outside of the level 1-10 areas) for 200 UC rep but not gain the 50 spillover rep with the other Horde factions.  Is this intended?

**Comment by Drokmon** [comment]
More detail as follows:

Went to quest in Silverpine Forest with the following Horde faction reputation levels:
  Darkspear Trolls: 4485/6000 Friendly
  Orgrimmar: 5335/6000 Friendly
  Silvermoon: 550/12000 Honored
  Thunder Bluff: 4310/12000 Honored
  Undercity: 2610/6000 Friendly

Completed the following quests:
  Prove Your Worth: 250 UC rep
  Border Crossings: 250 UC rep
  Maps and Runes: 150 UC rep
  Dalar's Analysis: 10 UC rep
  Dalaran's Intentions: 10 UC rep
    Total: 670 UC rep

Changed reputation levels after completing the quests above (which should have spillover rep):
  Darkspear Trolls: 4485/6000 Friendly (difference of 0)
  Orgrimmar: 5335/6000 Friendly (difference of 0)
  Silvermoon: 550/12000 Honored (difference of 0)
  Thunder Bluff: 4310/12000 Honored (difference of 0)
  Undercity: 3280/6000 Friendly (difference of 670, as above)

Possible explanation for results:
- Adjusted rep rewards for quests does not account for spillover rep, by accident or design.
- These quests take place in a level 10-20 zone, which may not count for spillover rep (though, according to original TBC, they should count for spillover.  Can anyone confirm?)

Looking for confirmation on what is happening.  I'm trying to build Silvermoon rep for their exalted mount, so I need to know if spillover rep is a thing on Endless Sunstrider server.

**Comment by hufsa** [comment]
Thanks! Fixed with next server update.
