### ISSUE TITLE
Quest [Kindness] can't be done

### ISSUE THREAD

**Issue by findrys** [SunstriderEmu/BugTracker#3783]
**Describe the bug**
The nether drakes won't eat the carcasses. No credit is given, no drakes are coming down to eat.

**To Reproduce**

1. Use carcass
2. Mob won't fly down
3. 

https://www.wowhead.com/quest=10804/kindness
https://www.wowhead.com/item=31372/rocknail-flayer-carcass
https://www.wowhead.com/npc=21648/mature-netherwing-drake
https://www.wowhead.com/npc=22131/netherwing-event-pinger

**Expected behavior**
To get the feeding credit.

**Screenshots/videos**

**Additional context**
Many players have stated in-game that it doesn't work.

**Comment by babno** [comment]
duplicate #2549
