### ISSUE TITLE
Paladin class Quest: Chillwind Point

### ISSUE THREAD

**Issue by Panzarpaddan** [SunstriderEmu/BugTracker#3786]
The level 50 class quest for Paladins (the sunken temple one), cant be picked up.
Neither in SW, IF or at Western Plaguelands where you are sent by the trainer.

**Comment by Panzarpaddan** [comment]
https://vanillawowdb.com/?quest=8415

**Comment by DMpunk1** [comment]
I have the same problem. I'm already lvl 57 Paladin, and the quest never popped up at Lord Grayson Shadowbreaker.

**Comment by Sheikthecatman** [comment]
Thanks! The quest should now be attainable by either Lord Grayson Shadowbreaker or Commander Ashlam Valorfist ([Dispelling Evil](https://db.endless.gg/?quest=8414)).
The fix will be live next restart.
