### ISSUE TITLE
NPC Ethereum Nullifier Not Found - Formula: Enchant Bracer - Major Defense

### ISSUE THREAD

**Issue by cssarto** [SunstriderEmu/BugTracker#3788]
hello i'm already looking for a few days for the NPC Ethereum Nullifier that drops the recipe for this enchant and i can't find it, some GM could check if this NPC is present on the map please.

https://db.endless.gg/?item=22530

![image](https://user-images.githubusercontent.com/17818760/85456309-37c9e200-b575-11ea-87e8-7aa2efe92c01.png)

**Comment by Jerrythemagicdog** [comment]
As Ethereum Nullifiers are not in the game yet (they come with Ogri'la, soon) you can find the enchant dropping from 
Ethereum Researcher(s)
