### ISSUE TITLE
Hit rating not adding up correclty

### ISSUE THREAD

**Issue by Lilillium** [SunstriderEmu/BugTracker#3789]
The hit rating on my gear is not adding up correctly. I should have about 20 more hit rating than what's showing under the spell tab. I've swapped gems and gear and I think it's the gems causing the issue because after swapping a +4 hit with a +8 i lose the 4 and gain nothing. Any help would be greatly appreciated. 

Thanks,
-Lil

**Comment by beraus** [comment]
![image](https://user-images.githubusercontent.com/16673248/85488063-f44f9200-b5cd-11ea-877a-aec22933ba8a.png)
You need spell hit rating.

**Comment by Lilillium** [comment]
Wait. wtf. I have like 195 spell hit but within the spell hit tab it shows 175. How do you link one piece and mark as invalid?

**Comment by Jerrythemagicdog** [comment]
You're using "HIT RATING" gems not "SPELL HIT RATING" gems, as explained in the other issue. Those are two different things in TBC.
