### ISSUE TITLE
Spell hit rating is not adding up properly

### ISSUE THREAD

**Issue by Lilillium** [SunstriderEmu/BugTracker#3790]
Hello,

The spell hit is not adding up properly on my character. In the spell hit tab it's showing 175 hit however when gear is added up it should be closer to 193. I've swapped Trinkets and it shows the difference but I think it's the gems because when I swapped gems no change. I've swapped a +4 hit gem with +8 and I no only don't get the +8 i lose the +4 from the other gem. Any assistance would be greatly appreciated. 

Head: 8
Neck: 0
shoulders; 7
Back: 10
Chest: 33 + 6 to all stats enchant
Bracers: 8
Gloves: 8 +15 hit enchant
Belt: 0
Legs: 17
Boots: 11
Rings: 21
Trinks: 32
Weap: 23
Total equipped: 193 w/out +6 to all stats chest enchant. 175 hit shown in spell book

Please assist
Thanks,
-Lilillium

**Comment by Jerrythemagicdog** [comment]
You're using the wrong gems.
I've composed a graphic for you, hope this helps!
![myhitrating](https://user-images.githubusercontent.com/46463908/85490804-560dfd00-b5ca-11ea-9efc-8ac1cd4f1450.png)

**Comment by Lilillium** [comment]
Yeah. Didn't know that was a thing

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3789
https://github.com/SunstriderEmu/BugTracker/issues/3765

**Comment by Lilillium** [comment]
Ehhh. Appreciate the response and the help!

**Comment by Jerrythemagicdog** [comment]
No problem, have a good day!
