### ISSUE TITLE
Escape from Firewing Point

### ISSUE THREAD

**Issue by N7Nosk** [SunstriderEmu/BugTracker#3791]
**Describe the bug**
I have done this quest, but somehow it hasnt counted as completed.

https://www.wowhead.com/quest=10051/escape-from-firewing-point

![WoWScrnShot_062420_142519](https://user-images.githubusercontent.com/45974071/85551925-27743e80-b62b-11ea-8cef-b11c9ebfda75.jpg)

**Comment by Jerrythemagicdog** [comment]
You must've been too far from the quest giver, she credited me correctly on both Alliance and Horde.
