### ISSUE TITLE
SetRaidSubGroup and SwapRaidSubGroup doesnt work in combat

### ISSUE THREAD

**Issue by jebossue** [SunstriderEmu/BugTracker#3800]
Initial post :
My issue is more an open question :
I was trying a macro to be able to switch people between groups (warrior shout).
Worked perfectly but not in combat. I know we could use /script in combat but maybe not in tbc ?

EDIT : 
/script work in combat its just SetRaidSubGroup and SwapRaidSubGroup that dont.
I dont see where you could abuse those calls, therefore why they are protected.
It will be good for warriors and Raidleader for BL management.
To test it : inv someone to raid put him G2, get in combat, use this macro /script SwapRaidSubgroup(2,1); see that this is not working.

**Comment by mpuryear** [comment]
What ever function you are using to change groups might be combat protected.
/script is not limited to out of combat. You can test this by getting into combat and using the following command:

/script SendChatMessage(UnitName("target"), "SAY")

Neither SetRaidSubgroup, nor SwapRaidSubgroup should be limited, but they do require you to be in a raid, not a party, to work.

**Comment by jebossue** [comment]
Hey thanks for you asnwer men,
So in fact /script does work in combat but setraidsubgroup and swapraidsubgroup does not.

**Comment by jebossue** [comment]
To test it : inv someone to raid, get in combat, use this macro /script SwapRaidSubgroup(2,1); see that this is not working.

**Comment by mpuryear** [comment]
> SetRaidSubgroup

While I mentioned these shouldn't be protected, I have no basis beyond the wow api docs not listing them as protected until 4.0.1.

I just found this from 2007 that indicates all raid swapping in combat must be done by hand though: https://authors.curseforge.com/forums/world-of-warcraft/addon-chat/addon-ideas/207302-api-funktion-swapraidsubgroup-incombat
