### ISSUE TITLE
pets losing target if they stealth

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3802]
If a pet is currently targeting and attempting to get to and attack a player, it should continue doing so even if that player enters stealth/prowl/shadowmeld. The only exception is if the target vanishes, then the pet should lose it's target. Otherwise it should chase them down even in stealth unless it's pulled back by the pet owner.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, we're not doing this though.
