### ISSUE TITLE
Issue disenchanting.

### ISSUE THREAD

**Issue by Lucence1535** [SunstriderEmu/BugTracker#3803]
**Describe the bug**

When disenchanting sometimes it does not yield EXP or dust.
I didn't notice it at first but then after about 10 runs through stockades I realized what was happening. This happens for at least stockade items. 

**To Reproduce**
On my character just disenchanting sometimes destroys the item
Sometimes does not yield dust
Sometimes does not yield experience
This is all below level 70 enchanting

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
I expect to get dust.

**Screenshots/videos**
https://streamable.com/0xy3zn
https://streamable.com/kdc80q

**Additional context**

**Comment by michaelkittrell** [comment]
ive had a similar experience, i believe it happens when i DE something, it goes into the loot window instead of my bag (addon mistake?  auto loot mistake?) and then i move far enough from the location where I performed the DE

**Comment by michaelkittrell** [comment]
to clarify, this happens to me in shat with anything i de

**Comment by beraus** [comment]
Can you disable all addons, try again and record it?

**Comment by Lucence1535** [comment]
It's resolved now, thank you.
