### ISSUE TITLE
A Hearty Thanks!

### ISSUE THREAD

**Issue by Pangoken** [SunstriderEmu/BugTracker#3804]
A Hearty Thanks! is not available due to Draenei Youngling inability to be aggresive towards hostile creatures.
Because of that the Gift of the Naaru doesn't trigger a trigger which forces the Draenei Youngling to give the quest.

**To Reproduce**

1. There are no steps as the problem is that they are missing.
2. 
3. 

Item: -
Quest: https://wowhead.com?quest=9612
Spell: https://wowhead.com?spell=59548

**Expected behavior**

The Draenei Youngling is supposed to give quest A Hearty Thanks! for using Gift of the Naaru on him during combat with a hostile NPC.

**Screenshots/videos**

![WoWScrnShot_062620_035234](https://user-images.githubusercontent.com/50700937/85812405-c9e20e00-b760-11ea-8b5f-75ed2a28197a.jpg)
![WoWScrnShot_062620_035238](https://user-images.githubusercontent.com/50700937/85812414-d0708580-b760-11ea-8eb6-318bfe6bd38a.jpg)

**Additional context**

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in [924ee413b27cd581294f0c298f0c21635cc18bdb](https://github.com/kelno/sunstrider-scripts/commit/924ee413b27cd581294f0c298f0c21635cc18bdb). The Draenei Youngling needs to be in combat for the event to occur. The fix will be live next server restart.
