### ISSUE TITLE
Post/mailbox bug

### ISSUE THREAD

**Issue by raketa99** [SunstriderEmu/BugTracker#3806]
Hey dear Endless.gg staff and community!

My name is Raketa IG and I wrote a ticket about missing mails around 2 weeks ago then my problem were solved by a nice GM. Last night when I bought a few stuff from AH they begin to disappear once again so I wrote a ticket again where the GM adviced me to let it know the developers of the server and the community. So guys watch out when you buy things on AH don’t hesitate to ask help since this is how the staff will know this problem occurs for many people. Asked a few guy from my guild and it’s happened to others as well. It’s not the “bug” when you have to relog or reload or teleport to another city and it’s solved in this case if you have addon called Postal (which is for help you loot all the mails you got) will show the squares where you have to select which ones should be opened and you could see how many letters disappeared even the minimap icon shows that you got mails from auction house but still the problem exist until you ask for GM help.

**Comment by Xeraro** [comment]
I also have this problem, I bought 2 bags at AH and they didn't arrive in the mail. my nick is Xerado.

**Comment by Jerrythemagicdog** [comment]
Please log out of your account completely and log back in, the mail should arrive then.

**Comment by raketa99** [comment]
As I said did full log out and log back not solved it. Waited hours long.
