### ISSUE TITLE
Frost Nova effect is instantanious

### ISSUE THREAD

**Issue by Kraizn** [SunstriderEmu/BugTracker#3808]
**Describe the bug**
Frost Nova effect has no delay time which means the debuff and the damage are instantaniously.

**To Reproduce**
1. Mage stand within 10m range to target
2. Mage cast frost nova
3. Watch the moment when debuff effect and damage on enemy 

Spell:
Frost nova: 	(https://db.endless.gg/?spell=27088)

**Expected behavior**
There is supposed to be some kind of delay after casting the frostnova and the actual effect taking place on the enemy.

**Screenshots/videos**
Here 3 examples of how it worked in the original game:

https://youtu.be/6CkYaF8EKb0?t=556
https://youtu.be/iNM_7flC-PI?t=814
https://youtu.be/iNM_7flC-PI?t=225

**Additional context**

**Comment by Jerrythemagicdog** [comment]
We're not particularly interested in replicating spell delay mechanics, the spell has its own travel time from the spell data and that's about it.

**Comment by Kraizn** [comment]
Well then "its own travel time from the spell data" is too short ... it is exactly zero.
