### ISSUE TITLE
[Rogue] Kidney Shot cannot affect low lvl mobs

### ISSUE THREAD

**Issue by Killko448** [SunstriderEmu/BugTracker#3809]
Kidney Shot(rank 2) cannot affect low lvl mobs
Screenshot shows more
![WoWScrnShot_062620_151655](https://user-images.githubusercontent.com/52464742/85889144-44db1100-b7c1-11ea-909a-4a6ff6679a91.jpg)

**Comment by hufsa** [comment]
Thanks, fixed with next update.
