### ISSUE TITLE
[Rogue] Talent 'Setup' (Yes i read other reports)

### ISSUE THREAD

**Issue by Killko448** [SunstriderEmu/BugTracker#3810]
**Describe the bug**
Rogue with talent Setup(45% to gain combo point on dodge) reseting your combo when fighting multiple targets.

**To Reproduce**

1. Just get a rogue. Get a Setup talent in Subtlety
2. Pull more than one mob. Use evasion to increase dodge chance
3. So when you build combos on your target you dodge other targets attacks which add combos to them, thus reseting your combo on current target.

Hope thats clear enough.

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: Setup, Evasion

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by hufsa** [comment]
Thank you, fixed with next update.
