### ISSUE TITLE
The orphan quest reward doesnt work

### ISSUE THREAD

**Issue by ranscapture** [SunstriderEmu/BugTracker#3814]
i chose Curmudgeon Sack of 5 gold, i got the item, and when i clicken on it to open it, the item disappeared and i didnt get 5g. i only had 9g so it was more beneficial than a pet. i feel pretty ripped off.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update. We've also sent the missing 5 gold to your character Raeon.
