### ISSUE TITLE
Macro: unexpected behavior

### ISSUE THREAD

**Issue by gl00m3r** [SunstriderEmu/BugTracker#3815]
**Describe the bug**
Tried to create macro for switch weapons: two-hand -> one-hand + shield. It's doesn't work if the weapon has same name with other gear in bag like the axe [Warbringer](https://tbc-twinhead.twinstar.cz/?item=29165) and Tier 4 warrior stuff [Warbringer Battle-Helm](https://tbc-twinhead.twinstar.cz/?item=29021).

**To Reproduce**

1. Have items with the same name in bag ([Warbringer](https://tbc-twinhead.twinstar.cz/?item=29165) and [Warbringer Battle-Helm](https://tbc-twinhead.twinstar.cz/?item=29021)).
2. Try to equip items with use macro.

```
/equip Warbringer
/equip Azure-Shield of Coldarra
/equip Deep Thunder
```
also doesn't work if used number of slot
```
/equipslot 16 Warbringer
/equipslot 17 Azure-Shield of Coldarra
/equipslot 16 Deep Thunder
```

**Solution**
I think need to highlight item name in macro like:
```
/equip 'Warbringer'
/equip "Warbringer"
/equip [Warbringer]
```

**Comment by Jerrythemagicdog** [comment]
That's something the client does and unfortunately nothing we can do anything about. Thanks for the report though, players with a similar issue will definitely find this useful in the future.
