### ISSUE TITLE
HEROIC BLOOD FURNACE LAST BOSS BUGGED

### ISSUE THREAD

**Issue by cyclones123** [SunstriderEmu/BugTracker#3816]
When the last boss pulls you in for the AOE  attack. Me  as the tank get sent flying outside the dungeon and then teleport to the graveyard.

**Comment by Jerrythemagicdog** [comment]
Thanks for the report, do you maybe remember a specific spot you were standing in or perhaps have a clip of it happening? We've heard of one other player having this issue but it's not been possible to reproduce because we're missing some details.

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3193
