### ISSUE TITLE
[NPC] Fishing extravagance - Riggle Bassbait not appearing

### ISSUE THREAD

**Issue by miqlliot** [SunstriderEmu/BugTracker#3817]
The NPC did not appear to turn in the fishing extravaganca quest. Pools did appear, however, but the lucky guy to catch 40 fish first (me) was not able to get a reward.

**Comment by Jerrythemagicdog** [comment]
![image](https://user-images.githubusercontent.com/46463908/85953236-d46df480-b966-11ea-9b66-92e02629c955.png)
Seems like the timing is off with the start of the event and the NPC spawning. He's up right now, we'll correct it for the next week, thanks!
