### ISSUE TITLE
Assist Exarch Orelis

### ISSUE THREAD

**Issue by rodrigomsr2** [SunstriderEmu/BugTracker#3819]
**Describe the bug**
The mission "Assist Exarch Orelis" is not showing up. I'm playing with the Alliance character: Anaopistola

**To Reproduce**

1. Got the initial mission on the bridge
2. Choose Aldor as my faction
3. Did the "Fel Armaments" mission
4. I'm friendly with both "The Aldor" and "The Sha'tar"

Quest: https://www.wowhead.com/quest=11038/assist-exarch-orelis

**Expected behavior**

The missions should appear.

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Perhaps you've done the Netherstorm quests before? Assist Exarch Orelis is a breadcrumb quest that's not necessary to start the chain in Netherstorm.

**Comment by rodrigomsr2** [comment]
I've made some quest in netherstorm, but they are too so i can't afirm this. Idk if you guys can check by some log or database of my character.

**Comment by Jerrythemagicdog** [comment]
Okay, you don't need this quest to continue with the chain and if you have completed any of the next quests this one becomes unavailable.
