### ISSUE TITLE
[Quest] Badlands Reagent Run II Horde version.

### ISSUE THREAD

**Issue by dinocrisis** [SunstriderEmu/BugTracker#3821]
**Describe the bug**
Quest does not give appropriate number of quest items. Only give one Vial instead of described three.

**To Reproduce**

Attempting to cast Vial on scorched guardian dragon on nets 2 of 3 required quest item. 

Item: https://classic.wowhead.com/item=7870/thaumaturgy-vessel-lockbox
https://classic.wowhead.com/quest=2203/badlands-reagent-run-ii
Spell: https://classic.wowhead.com/item=7867/vessel-of-dragons-blood

**Expected behavior**
Quest is impossible to finish without required 3 vials.

**Screenshots/videos**
![WoWScrnShot_062820_131952](https://user-images.githubusercontent.com/67556791/85955437-28b3ad00-b944-11ea-98d6-92310e60814a.jpg)

![WoWScrnShot_062820_132359](https://user-images.githubusercontent.com/67556791/85955416-04f06700-b944-11ea-9f69-359e6f071b0d.jpg)

**Additional context**

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in [b4f38d6fa0857eeb03caf631950b6dbff309ed20](https://github.com/kelno/sunstrider-scripts/commit/b4f38d6fa0857eeb03caf631950b6dbff309ed20)! The fix will be live after next server restart.
