### ISSUE TITLE
[Profession] Formula: Enchant Ring - Stats incorrect faction for 2.4.3

### ISSUE THREAD

**Issue by dinocrisis** [SunstriderEmu/BugTracker#3822]
**Describe the bug**
Formula: Enchant Ring - Stats required faction rep set to The Scales of The Shifting Sands rep revered instead of Lower city honored.

**To Reproduce**
Formula: Enchant Ring - Stats required faction rep set to The Scales of The Shifting Sands rep revered instead of Lower city 
2. 
3. 

Item: https://wowwiki.fandom.com/wiki/Formula:_Enchant_Ring_-_Stats
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**
![1 WoWScrnShot_061420_181210 scaleofthesands](https://user-images.githubusercontent.com/67556791/85955771-ad072f80-b946-11ea-8e01-81be4e947bef.jpg)

**Additional context**

**Comment by Jerrythemagicdog** [comment]
It's a Cache issue because of the previous server you've played on. Clear your Cache and try again, thanks.
![Uploading image.png…]()
