### ISSUE TITLE
[Warlock] Felhunter can parry?

### ISSUE THREAD

**Issue by braide** [SunstriderEmu/BugTracker#3823]
**Describe the bug**
Felhunters can parry melee strikes, maybe block as well? Haven't really seen that on other servers and I don't recall that they could on retail. Don't really have proof but it doesn't make sense imo.

**To Reproduce**
Just stand in front of a felhunter and hit it.

**Expected behavior**
I don't think felhunter should be able to parry and (block?).

**Comment by Jerrythemagicdog** [comment]
https://youtu.be/-41Dgo6auCA?t=250

You can slow it down, he also hits the Felhunter some more throughout the video.
