### ISSUE TITLE
Deathblow To The Legion Quest

### ISSUE THREAD

**Issue by Tyreeq** [SunstriderEmu/BugTracker#3825]
The boss fight that is meant to start after the group teleports to Socrethar's seat isnt starting, a total of 3 aldor npc's are present, one by the teleporter, 2 infront of Sorcrethar himself, but the fight wont start, every npc is just idle infront of each other, any advice on what to do? been here for a while trying to reset by teleporting out and back in but it just wouldnt start. Any help is appreciated, Thank you!

**Comment by beraus** [comment]
This is a know issues, thanks. Event is working now.
