### ISSUE TITLE
Pets are able to auto-attack through LoS, causes issues with spells.

### ISSUE THREAD

**Issue by SuddenDeath** [SunstriderEmu/BugTracker#3826]
**Describe the bug**
Pets are able to auto-attack through LoS, this allows clever positioning to make spell casts from pets become unusable(because they require LoS)

**To Reproduce**
1. Petattack a target in blade's edge arena
2. position target around the small pillars below the bridge, eventually you'll get it right.
3. Attempt to cast spell lock or other spell with pet, won't be able to instantly use it.

**Expected behavior**
https://endless.gg/changes
*No hitting through pillars.

**Comment by beraus** [comment]
Should be fixed now, @kelno

**Comment by kelno** [comment]
Thanks didn't see that issue, should be fixed now indeed, since last changes pets do try to reposition as soon as they are out of los
