### ISSUE TITLE
bugged SWORD SPEC + Hand of Justice

### ISSUE THREAD

**Issue by nechy111** [SunstriderEmu/BugTracker#3827]
**Describe the bug**

**To Reproduce**

1. Sword is 5% extra hit
2. HoJ 2% extra hit
3. 

Item: https://classic.wowhead.com/item=11815/hand-of-justice =
Spell: cant find Sword spec =

**Expected behavior**

**Screenshots/videos**

**Comment by Jerrythemagicdog** [comment]
I'm not sure what you're trying to say here.

**Comment by nechy111** [comment]
![C66FB55F-93AD-4072-8583-9BF653DC3B7B](https://user-images.githubusercontent.com/67140011/86211372-9515f280-bb76-11ea-9e05-94b487a7f4ae.jpeg)


Extra hit is low

**Comment by nechy111** [comment]
Critical is too low. Have 32%
