### ISSUE TITLE
[Quest] Hints of a New Plague?

### ISSUE THREAD

**Issue by marchewiczd** [SunstriderEmu/BugTracker#3828]
**Describe the bug**
[Sealed Folder](https://classic.wowhead.com/item=4482/sealed-folder) required for quest [Hints of a New Plague?](https://classic.wowhead.com/quest=658/hints-of-a-new-plague) does not drop from [Forsaken Courier](https://classic.wowhead.com/npc=2714/forsaken-courier).

**To Reproduce**
1. Kill the Forsaken Courier
2. Notice that Sealed Folder does not drop at all, while it should have a drop rate of 100%.

Item: https://classic.wowhead.com/item=4482/sealed-folder
Quest: https://classic.wowhead.com/quest=658/hints-of-a-new-plague

**Expected behavior**
Sealed Folder should drop 100% of the time.

**Comment by Jerrythemagicdog** [comment]
Can't reproduce, drops for me every time, the data we have is also the expected 100% drop rate.
