### ISSUE TITLE
Ban without reason

### ISSUE THREAD

**Issue by ghostmau123** [SunstriderEmu/BugTracker#3830]
name in game : Pichimon
was farming primal life in zangarmash and was disconnnected and i see that i was banned  by cheating software ? there is no way really?i have two more accounts and that has not happened  to me ban for no reason

**Comment by Jerrythemagicdog** [comment]
You've been banned for botting. If you'd like to dispute your ban you can send us an email at hello@endless.gg with your character's name and password or contact a member of Support on Discord.
