### ISSUE TITLE
Unable to log into the game

### ISSUE THREAD

**Issue by 11367940** [SunstriderEmu/BugTracker#3832]
**Describe the bug**
I am a chinese player.I come from chinese. I have to use agents to play games. 

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Sounds like a problem on your end, not sure what we're able to do here, sorry!
