### ISSUE TITLE
Cloth drops from 0-60 are way off

### ISSUE THREAD

**Issue by Kiratin24** [SunstriderEmu/BugTracker#3833]
I've noticed the drop rates on cloth are very low and don't match with the level from the mobs. I'm getting wool from 15-30 and silk from 15-30 but the drops are very low. Not sure if this is intended or a bug. But It's not like TBC. I didn't find any silk in SM runs and that is supposed to be the place to farm silk.

**Comment by Istaryu** [comment]
I can confirm this.

Loot from 31 enemis can be seen here (Note that i only looted the money, cloth, and green/blue items):
https://i.imgur.com/HH1CTmBh.jpg

As it can be seen, only 4 of them dropped any cloth.

According to wowhead, they have 77-78% chance to drop mageweave cloth.
https://i.imgur.com/mNM97beh.jpg

**Comment by z5n** [comment]
Issue has been since fixed
