### ISSUE TITLE
Changing dual specialization removes macro from bars

### ISSUE THREAD

**Issue by chrmol** [SunstriderEmu/BugTracker#3834]
When I change dual specialization there are two specific macros that end up being removed from my bars, every single time.

Macro 1:
#showtooltip Blessing of Kings
/cast Blessing of Kings

Macro 2:
#showtooltip Greater Blessing of Kings
/cast Greater Blessing of King

I have many other talent specific macros as well, but none of them are removed from my bars.
I have tried having these macros in both the "Personal" and "General" macro tabs without any luck.

One suspision I have is that it might be related to the fact that the Kings macros is the only talent-specific macro I have that I have on both talent specializations.

**Comment by Jerrythemagicdog** [comment]
That's expected, players use an addon called Action Bar Saver to restore their keybinds after changing specs.

**Comment by chrmol** [comment]
> 
> 
> That's expected, players use an addon called Action Bar Saver to restore their keybinds after changing specs.

I am not talking about the skills themselves, but macros. And every single other macro (including ones from talents) **except** for kings.
