### ISSUE TITLE
Riding Skill On Boosted Character Not Working Properly

### ISSUE THREAD

**Issue by lukasfotog** [SunstriderEmu/BugTracker#3835]
On my boosted Paladin I am trying to purchase 225 riding skill but it is making me buy 150 skill for 600g even though that skill already came with the boost. 

![Annotation 2020-06-30 092015](https://user-images.githubusercontent.com/67649990/86151119-2754c280-bab3-11ea-9ffe-2d9cbc3da4c8.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, resolved in game and fixed with next update.
