### ISSUE TITLE
Your payment Method sucks

### ISSUE THREAD

**Issue by DGRSH** [SunstriderEmu/BugTracker#3836]
Why not use paypal?
This Paymentwall is crap.

They dont accept my Credit cards and also not my bank account. 

So i cant donate.

Very easy to use paypal, amazon payment or whatever but not this noname payment provider is not mass compatible.

**Comment by InhumanGM** [comment]
Closing this as it is not a bug. Please reach out to one of our staff members via Discord regarding your concern.
