### ISSUE TITLE
Arena Charter 3v3 - cannot turn in or request sign ups

### ISSUE THREAD

**Issue by Jodemaster** [SunstriderEmu/BugTracker#3838]
Unable to request sign ups or turn in Arena 3v3 team charter.

Tried clearing cache twice - does not work.
Tried deleting WTF folder - does not work.

![3v3 arena](https://user-images.githubusercontent.com/67653341/86159410-5acb3780-bb1b-11ea-884b-ae67a6682371.jpg)

**Comment by beraus** [comment]
Open a ticket and we'll refund the cost of buying charter.
