### ISSUE TITLE
ssc, leotheras hunter FD

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3839]
if a hunter FD with inner demon, the demon despawns and the hunter will get MC at the end of the phase.

**Comment by mechanicsTBC** [comment]
working properly

**Comment by michaelkittrell** [comment]
working properly?  why should inner demon despawn because you fd.  that makes no sense

**Comment by NeonicSupersonic** [comment]
why should mob reset if it has no target to attack? :big think:
