### ISSUE TITLE
Hunter pets dying in PVP (by player or in battlegrounds to NPC) lowers pet happiness.

### ISSUE THREAD

**Issue by tonisjwhite** [SunstriderEmu/BugTracker#3840]
**Describe the bug**
Anytime a hunter's pet dies in a BG or by a player in open world, the pet's happiness drops.

**To Reproduce**
Have a hunter pet, have a player of the opposing faction (or Alterac Valley NPC) kill the pet.

**Expected behavior**
Maybe not 'expected behavior' since pet happiness was removed in patch 3.0.1, but removing pet happiness reduction from pvp combat will reduce griefing in pvp and lower level hunters having their pets chased away by higher level players.

**Comment by kelno** [comment]
We're not removing happiness in BG or arena anymore
