### ISSUE TITLE
[Quest] Seasoned Wolf Kabobs

### ISSUE THREAD

**Issue by monie95** [SunstriderEmu/BugTracker#3841]
Cannot hand in quest "Seasoned Wolf Kabobs"

1. Got all mats in bag, see attached picture.

Item: https://classic.wowhead.com/item=1015/lean-wolf-flank
Item: https://classic.wowhead.com/item=2665/stormwind-seasoning-herbs
Quest: https://classic.wowhead.com/quest=90/seasoned-wolf-kabobs
![Seasoned Wolf Kabobs](https://user-images.githubusercontent.com/67656589/86167534-fefeaf80-bb16-11ea-8d9c-7ad71ee12b36.png)

**Comment by beraus** [comment]
Open a ticket in game, please.
