### ISSUE TITLE
Brother against brother Q

### ISSUE THREAD

**Issue by klucznik2406** [SunstriderEmu/BugTracker#3844]
**Describe the bug**
Brother Against Brother Q is not available to be picked

**To Reproduce**
Quest not available from NPC

https://www.wowhead.com/quest=10097/brother-against-brother

**Expected behavior**
Quest available to be finished

**Comment by Sheikthecatman** [comment]
You need to complete the pre-requisite quest [Can't Stay Away](https://db.endless.gg/?quest=10180)
