### ISSUE TITLE
Quest:  [Master of Potions]

### ISSUE THREAD

**Issue by Ezann3** [SunstriderEmu/BugTracker#3845]
quest unable to be submitted even thou i have all the quest items in my bag. 

![WoWScrnShot_063020_231207](https://user-images.githubusercontent.com/64969328/86196796-951dee80-bb86-11ea-8bf8-c16db2d7b30d.jpg)

![image](https://user-images.githubusercontent.com/64969328/86196899-ca2a4100-bb86-11ea-842a-966b6a25b5a6.png)

**Comment by beraus** [comment]
Open a ticket in game, please.
