### ISSUE TITLE
Quest: [Firewing Signets]

### ISSUE THREAD

**Issue by Glorind** [SunstriderEmu/BugTracker#3846]
Can't complete the quest
![WoWScrnShot_070120_124325](https://user-images.githubusercontent.com/26395158/86232940-5fd0cb00-bb9d-11ea-88de-5aeabae4e949.jpg)

**Comment by beraus** [comment]
You're honored with Scryers, so you need to do [Sunfury Signets](https://www.wowhead.com/quest=10656/sunfury-signets)
