### ISSUE TITLE
Eye of the storm information text

### ISSUE THREAD

**Issue by Imbarawr** [SunstriderEmu/BugTracker#3849]
**Describe the bug**
When in Eye of the storm and Draenei Ruins is being capped by, for example, alliance, the message will say "The Horde has taken control of Draenei Ruins".

Other way around aswell, when horde caps it it says alliance capped it.

**To Reproduce**

1. Enter EOTS
2. Cap Draenei Ruins

**Expected behavior**
The text should be accurate regarging who is capping Draenei Ruins.

**Comment by hufsa** [comment]
Thanks! Fixed with next server update.
