### ISSUE TITLE
[Mage] Blizzard Debuff should not be applied instantly

### ISSUE THREAD

**Issue by bluemanguy112** [SunstriderEmu/BugTracker#3850]
**Describe the bug**
Blizzard applying Snare instantly instead of a delay to sync with actual animation and casttime.

Just play Classic (im aware of spellbatching there) and see for yourself. The ability wasn't subject to any changes in TBC.

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3689
