### ISSUE TITLE
Balance druid t5 4-set bonus not applying

### ISSUE THREAD

**Issue by lolqopp** [SunstriderEmu/BugTracker#3851]
**Describe the bug**
Balance druid T5 4-set bonus not working properly. Should give 10% dmg increase to Starfire if Moonfire or insect swarm is on target. Dmg buff does not seem to apply.

**To Reproduce**
1. Cast Starfire on target without insect swarm
2. Cast Starfire on target with insect swarm up

**Expected behavior**
Expected a noticeable dmg increase.

**Screenshots/videos**
![1](https://user-images.githubusercontent.com/67715113/86297068-aaccfb80-bbfa-11ea-9537-fa83154dfaf6.jpg)
![2](https://user-images.githubusercontent.com/67715113/86297074-ae608280-bbfa-11ea-938d-148273ec709f.jpg)

**Additional context**
Tested using legs, shoulder, chest, gloves.

**Comment by lolqopp** [comment]
Hey! 
Any news on when this issue is to be fixed?:) @Jerrythemagicdog

**Comment by chubstarbabyrawr** [comment]
Help the support classes out!

**Comment by Dalvaniaa** [comment]
We still need it !

**Comment by Jerrythemagicdog** [comment]
The damage is increased by 10% before the spell damage is applied, so only the base damage of Starfire benefits from this set bonus. If that's working incorrectly then we'll need to see some sources showing how it's supposed to work. Sorry for the delayed response!

**Comment by mpuryear** [comment]
> The damage is increased by 10% before the spell damage is applied, so only the base damage of Starfire benefits from this set bonus. If that's working incorrectly then we'll need to see some sources showing how it's supposed to work. Sorry for the delayed response!

This is asking to prove a negative. What other tier/item/spell has the description "increases <spell name> damage by x%" but only applies the to the pre-modified spell? Does the warriors t6 +10% shield slam damage only apply to the pre bv modified amount? Who would have ever written a proof that shows a spell actually does what the tooltip states?

I'll take a weak stab at it though so you have "proof". 
I pulled the EJ boomkin 2.4.3 dps spreadsheet as it is likely the most accurate we can get: https://drive.google.com/file/d/1g_azbaozbR9rZG1q91AICiql433sFDWX/view?usp=sharing

You can look at Projected Total Damage on Character Sheet_Buffs, and trace that back to the Cast Cycles page.
There we can see the formula used to determine starfire damage when t5 4p is applied if you select one of the DPS values.

![image](https://user-images.githubusercontent.com/17075809/87925093-a5faab00-ca34-11ea-95aa-63514a4e3873.png)

If you can't understand that picture, it clearly does an "if t5 4p then add 10% damage to all starfire damage". This is the last step before displaying the values to the user, so there isn't another step after this that adds in the spell damage modifier.
