### ISSUE TITLE
Random Flying Mobs Floating upward

### ISSUE THREAD

**Issue by mypetmonster81** [SunstriderEmu/BugTracker#3853]
**Describe the bug**
Random flying mobs floating upwards when fighting. 

**To Reproduce**
Standing stationary while fight a flying mob will sometimes reproduce this effect 

**Screenshots/videos**
https://imgur.com/a/B21J1FK

**Comment by Jerrythemagicdog** [comment]
Thanks, issue started happening after latest changes and affects flying creatures.

**Comment by kelno** [comment]
Fixed with next server update
