### ISSUE TITLE
hydross tainted water elementals accumulate

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3854]
These were all stacked ontop of eachother and when initially pulled looked like one.

![image](https://user-images.githubusercontent.com/244626/86393227-bfe17300-bc6a-11ea-8515-9f8ddaa83cca.png)

**Comment by michaelkittrell** [comment]
agree.  same problem existed since ptr.  saw it yesterday as well although usually its only the first one that is stacked, and yesterday it looked like the first 2 had more than 1 mob stacked on them.

**Comment by mechanicsTBC** [comment]
its a problem with the server overall; mobs outside of view distance don't patrol or move at all.  view distance is reduced on this server, the elementals continue to spawn and stack up in 1 spot.  then you get in range of where they spawn and they move, but theres potentially hundreds of them stacked up as "one"

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
