### ISSUE TITLE
I made a detailed video with errors that need to be corrected, please pay special attention to the bugs with succubus

### ISSUE THREAD

**Issue by SifoDyas123** [SunstriderEmu/BugTracker#3856]
I made a detailed video with errors that need to be corrected, please pay special attention to the bugs with succubus.
(Я сделал подробное видео с ошибками, которые нужно исправить, пожалуйста, обратите особое внимание на ошибки с суккубом)
Вот Ссылка на подробный обзор багов Endless https://www.youtube.com/watch?v=IlJuEHhpHZg

**Comment by Jerrythemagicdog** [comment]
This is a 13 minute video in Russian, sorry, nobody here will watch that, write an actual bug report or at least provide time stamps.
