### ISSUE TITLE
Couple of bugs in Blade´s Edge Mountains

### ISSUE THREAD

**Issue by Noznd** [SunstriderEmu/BugTracker#3859]
**Describe the bug**
Drunken haze spell not showing as debuff and effects much longer then it should we are talking 5 mins somtimes only death can remove it

**To Reproduce**

im a shadowpriest and i start with debuffing the mob and as soon as he hits me i get im drunk and debuff doesnt show and doesnt go off 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page
Item: 
Quest: 
Spell: https://www.wowhead.com/spell=37591/drunken-haze
Mob: https://www.wowhead.com/npc=19957/bloodmaul-brewmaster

----------------------------------------------------------------------------------------------------------------------------------

**Describe the bug**
Kick spell of the mob doenst have CD he kicks every time i cast a spell

**To Reproduce**
im a shadowpriest and can only cast instant spell or Meele him 

Item: 
Quest: 
Spell: https://www.wowhead.com/spell=34802/kick
Mob: https://www.wowhead.com/npc=19948/bloodmaul-skirmisher

**Comment by Sheikthecatman** [comment]
Bloodmaul Brewmaster doesn't cast kick.

**Comment by Noznd** [comment]
> Bloodmaul Brewmaster doesn't cast kick.

Sry its the Bloodmaul skirmisher

**Comment by Sheikthecatman** [comment]
Thanks! The angry ogre will give you a break before kicking again.

**Comment by z5n** [comment]
issues have since been fixed
