### ISSUE TITLE
Balance Druid. Balance of Power Talent not working properly 

### ISSUE THREAD

**Issue by chubstarbabyrawr** [SunstriderEmu/BugTracker#3861]
At 12% hit, balance druid spells shouldn't be resisted even in part if they have 2/2 in the "Balance of Power" talent. "Balance of Power" talent is supposed to provide 4% spell hit.

1. Cast several Starefires on dummies, had occasional partial resists. 

**Expected behavior**
Expected not to miss at 12% plus hit. 

**Screenshots/videos**
![Hitbug](https://user-images.githubusercontent.com/67809930/86501368-28088580-bd4d-11ea-9703-2147f19f9b76.png)

**Additional context**
This was done on Target Dummy in Stormwind.

**Comment by Jerrythemagicdog** [comment]
Being hit capped and your spells being partially resisted are two different things. 
Partial resists come from your target's resistances and that can be mitigated by spell penetration or effects reducing the target's resistances (such as Curse of Elements).
