### ISSUE TITLE
Quest: "Stones of Binding" not turning in

### ISSUE THREAD

**Issue by holiday914** [SunstriderEmu/BugTracker#3862]
**Describe the bug**

When doing the quest "[Stones of Binding](https://classic.wowhead.com/quest=651/stones-of-binding)" where you must collect the three elemental keys (Burning, Cresting, Thundering) and turn them in at the Keystone (36,57; Arathi Highlands), Keystone is blank and you cannot turn in the quest.

**To Reproduce**

1. Accept quest "Stones of Binding"
2. Collect the Burning Key, Cresting Key, and Thundering Key
3. Travel to coordinates (36,57; Arathi Highlands)
4. Click on Keystone
5. Keystone interface is blank

Quest: https://classic.wowhead.com/quest=651/stones-of-binding

**Expected behavior**

Quest "Stones of Binding" turn in complete at Keystone.

**Screenshots/videos**

![WoWScrnShot_070320_173002](https://user-images.githubusercontent.com/67810638/86501976-0d390f80-bd53-11ea-80ce-336800707dac.jpg)
![WoWScrnShot_070320_172955](https://user-images.githubusercontent.com/67810638/86501977-0f02d300-bd53-11ea-86f2-df8671feae2f.jpg)

**Additional context**

**Comment by Sheikthecatman** [comment]
![image](https://user-images.githubusercontent.com/59149613/86524278-e4ab3580-be78-11ea-8644-28a01ee66961.png)
The quest is turned in at the Stone of Inner Binding next to the Keystone.
