### ISSUE TITLE
My Karazhan Rep Ring dissapeared

### ISSUE THREAD

**Issue by Brusquini** [SunstriderEmu/BugTracker#3863]
I don't know when or what I did, I just looked at my char sheet and noticed that my Revered Violet Eye / Karazhan rep ring was gone and I don't find it anywhere.

Alydrieth 70 Feral Druid

**Comment by Jerrythemagicdog** [comment]
Perhaps because you've abandoned the quest associated with that ring. You can visit the NPC in front of Karazhan and pick up your quest and ring.
