### ISSUE TITLE
Human Rogue character stucks on stairs

### ISSUE THREAD

**Issue by finger2121** [SunstriderEmu/BugTracker#3864]
**Describe the bug**
Human Rogue character stucks on stairs

**To Reproduce**
<!--- Steps on any 
protruding surface cause to stuck on it sometimes for 10 sec to go further . Need to jump every time. Never saw such thing in WoW. Happens on every i repeat every stair. HEEEELP

**Comment by Jerrythemagicdog** [comment]
That's the client, we can't do much about that, sorry!
