### ISSUE TITLE
[OHF] - Epoch Hunter - Out of range and no melee damage when flying.

### ISSUE THREAD

**Issue by Keritous** [SunstriderEmu/BugTracker#3865]
After recent updates, it's impossible to tank it, he is flying and melee range can't reach him.

![WoWScrnShot_070420_143357](https://user-images.githubusercontent.com/66011356/86510366-45e4f180-be04-11ea-9981-c3280682a148.jpg)
 *Can be abused since it doesn't do melee attack on target (7k hp mage tanked it in the whole fight)
![WoWScrnShot_070420_143404](https://user-images.githubusercontent.com/66011356/86510333-04544680-be04-11ea-8c12-42b0212c4312.jpg)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update!
