### ISSUE TITLE
Arcane Missiles Clearcasting bug

### ISSUE THREAD

**Issue by darimachine** [SunstriderEmu/BugTracker#3866]
For one, it has a 50% chance to proc clearcasting per cast, where Fireball or Frostbolt only have 10% chance per cast. You get 1 clearcasting every 10 seconds with AM, every 25 seconds with Frostbolt and every 30 seconds with Fireball. And then, you get more damage per clearcast with AM than you do with either of the other options.  it should be so but AM dont have 50% chance to proc clearcasting on this server maybe only have 10% with one AM i tried i cast 21 AM and didnt proc on 22 AM is proced clearcasting can you solve this bug

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/433
