### ISSUE TITLE
Ferocious Inspiration Not Activating

### ISSUE THREAD

**Issue by Ellev1** [SunstriderEmu/BugTracker#3867]
Ferocious Inspiration talent in the Beast Master tree no longer activated when the pet scores a critical strike against a target. It can be activated by a normal pet melee critical strike, or a Kill Command critical strike. 

1. Go to any mob and have your pet attack it. Wait for a Critical Strike.
2. On critical strike, Ferocious Inspiration should proc. You'll notice that it doesn't. 

Ferocious Inspiration should give the party 3% more damage, and stacks with other Beast Master hunters in the group.

**Comment by Jerrythemagicdog** [comment]
Need some reproduce steps here, pet applies the buff immediately after critting in my tests.
