### ISSUE TITLE
Blacksmith mace spec quest

### ISSUE THREAD

**Issue by sunstriderbugreporter** [SunstriderEmu/BugTracker#3868]
Blacksmith plans in Stratholme spawn a wrong mob making players unable to complete [Mace specialization blacksmithing quest](https://db.endless.gg/?quest=5305).

**To Reproduce**
Get to Stratholme and open up [Blacksmith plans](https://db.endless.gg/?object=176325) in the scarlet part next to [Cannon Master Willey](https://db.endless.gg/?npc=10997) Plans spawn [this boi](https://db.endless.gg/?npc=11121) instead of [the correct one](https://db.endless.gg/?npc=11120)

**Expected behavior**
Those particular [Blacksmith plans](https://db.endless.gg/?object=176325) should spawn [Crimson Hammersmith](https://db.endless.gg/?npc=11120)

**Screenshots/videos**
Dunno why would you need those, but here you go
![se1](https://user-images.githubusercontent.com/67846415/86523658-fd671b80-be77-11ea-8a61-0b0c70ac57bc.jpg)
![se2](https://user-images.githubusercontent.com/67846415/86523659-ff30df00-be77-11ea-8b75-676b0db19ac0.jpg)
And yeah, [Plans: Serenity](https://db.endless.gg/?item=12827) should be a 100% drop visible to blacksmith only i guess.

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in [68b0933bb204fe91288aab50a6c5637cae392457](https://github.com/kelno/sunstrider-scripts/commit/68b0933bb204fe91288aab50a6c5637cae392457). The fix will be applied next server restart.
