### ISSUE TITLE
Deserter doesn't expire while you are offline

### ISSUE THREAD

**Issue by Mastercry** [SunstriderEmu/BugTracker#3869]
https://wowwiki.fandom.com/wiki/Deserter

Hope if you confirm this to be careful while fixing it, because buffs like other player's, poisons on weapon etc. does not expire while offline also, so they are working properly atm. Just Deserter debuff should expire I think.

**Comment by michaelkittrell** [comment]
so when you screw over your bg by deserting, you should suffer no consequences if you just log off?  if this is a "bug", don't fix it lol.

**Comment by Rettiy** [comment]
https://wowwiki.fandom.com/wiki/Deserter

Patch Changes
_"Patch 1.12.1 (26-Sep-2006): The deserter debuff will now continue to expire even while you are offline."_

Kinda obvious one - possibly check Ress Sickness too.

**Comment by hufsa** [comment]
Thanks! Fixed with next update.
