### ISSUE TITLE
Flying mobs rise too high. Can't attack in melee.

### ISSUE THREAD

**Issue by kimurin** [SunstriderEmu/BugTracker#3870]
**Describe the bug**
If player attacks flying mobs (Teremoth, for example, Terokkar Forest 44.6 30.3) and he's moves, than mob will rise too high. So player can't attack him in melee.

**To Reproduce**
1. Aggro Teremoth from range.
2. Wait until he's moves close to you.
3. He will rise up too high. Can't attack in melee.

https://www.wowhead.com/npc=18468

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/924688/86530934-c0c21100-bec5-11ea-9e0c-b6da0ed91e18.png)

**Additional context**
Issue persists with most flying mobs in Outland.

**Comment by Jerrythemagicdog** [comment]
Fixed with this update, thanks.
