### ISSUE TITLE
Area 52 inn not flagged as inn

### ISSUE THREAD

**Issue by mechanicsTBC** [SunstriderEmu/BugTracker#3871]
Current behavior:
Its as if I'm not in an inn

Expected behaviour:
When im in an inn I should get rest xp and be able to log out instantly

Steps to reproduce the problem:

Step 1: Go to the inn; try to log out

#423

**Comment by kelno** [comment]
Thanks for reporting

**Comment by kelno** [comment]
To dev: That's just a missing entry in areatrigger_tavern table

**Comment by Sheikthecatman** [comment]
To kelno: It is not missing in aretrigger_tavern table

**Comment by kelno** [comment]
To sheik: okay thanks

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
