### ISSUE TITLE
Netherspite Green beam does not restore mana

### ISSUE THREAD

**Issue by Flamelol** [SunstriderEmu/BugTracker#3872]
Just like in title - when player takes blue beam on netherspite his mana should be restored to 100%. 
https://wowwiki.fandom.com/wiki/Netherspite

**Comment by mechanicsTBC** [comment]
i believe you mean the green beam.  and yes, it should put mana at the new maximum after taking each tick (similar to how red beam does with health).

**Comment by Flamelol** [comment]
Yeah sorry - green beam. I was tired when i opened a new issue on
bugtracker

pon., 6 lip 2020, 04:36 użytkownik mechanicsTBC <notifications@github.com>
napisał:

**Comment by Flamelol** [comment]
As u said - it should put mana at the new maximum after taking each tick and it doesnt. So everyone who is taking 1 tick from green beam - his mana should be restored to 100% also reducted by percentage dependent from how much time someone spend in green beam

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
