### ISSUE TITLE
[Quest][Westfall] Captain Sander's Hidden Treasure

### ISSUE THREAD

**Issue by Nougmage** [SunstriderEmu/BugTracker#3874]
Westfall treasure discovery chain is not implemented 
Related quests and objects:
https://classic.wowhead.com/quest=136/captain-sanders-hidden-treasure
https://classic.wowhead.com/object=35/captains-footlocker
https://classic.wowhead.com/quest=138/captain-sanders-hidden-treasure
https://classic.wowhead.com/object=36/broken-barrel
https://classic.wowhead.com/quest=139/captain-sanders-hidden-treasure
https://classic.wowhead.com/object=34/old-jug
https://classic.wowhead.com/quest=140/captain-sanders-hidden-treasure
https://classic.wowhead.com/object=33/locked-chest

**Comment by Jerrythemagicdog** [comment]
Not sure what do you mean by not implemented, quest works as expected. 
Item that starts the quest (1357) has ~1% drop chance from the following creatures:
```
Murloc Coastrunner
Murloc Tidehunter
Murloc Warrior
Old Murk-Eye
Murloc Minor Oracle
Murloc Hunter
Murloc Netter
Murloc Raider
Murloc Oracle
Slark
Brack
```
