### ISSUE TITLE
Ogrila pre-quest not working

### ISSUE THREAD

**Issue by pinkisnotgay** [SunstriderEmu/BugTracker#3876]
Nothing happens after you complete the
https://wowwiki.fandom.com/wiki/Quest:Mog%27dorg_the_Wizened
There should be a 3 quest follow up, but the npc does not give anything.

On top of that there should be alternative way of begging the pre-quest in Shattrath ( https://wowwiki.fandom.com/wiki/Quest:Speak_with_the_Ogre ), but as of right now you can only start it in BEM
![ogrila](https://user-images.githubusercontent.com/44933866/86545131-fcdc8c80-bf2c-11ea-950b-5896c55f6dba.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
