### ISSUE TITLE
Warlock Imp Not Attacking

### ISSUE THREAD

**Issue by WillowWhisps** [SunstriderEmu/BugTracker#3877]
**Describe the bug**

The Imp, the first Warlock summon available, does not attack as it should. Whether it's in the Aggressive or Defensive stances, it will not attack, unless prompted. What this means is that the imp will only attack when the "firebolt" command is given. But even with this, it only attacks once instead of in a recurring auto-attack fashion. 

Right-clicking a target or clicking the "attack" command, regardless of the combat stance, does not cause the Imp to attack. Furthermore, it will not attack any target that attacks it directly.

**To Reproduce**

1. Place imp into either "Aggressive" or "Defensive" combat stances.
2. Order to attack an attackable target via the "attack" button.
3. Right click on an attackable target.
4. Attack an attackable target yourself.
5. Make an aggressive target attack the imp.

The imp won't attack. At most it will follow the target.

6. Order the imp to use "firebolt" on an attackable target.

It will attack, but only once, and not again, until it's ordered to use "firebolt" once more. 

Item: https://classic.wowhead.com/npc=416/imp
Quest: https://wowhead.com?quest=
Spell: https://classic.wowhead.com/spell=688/summon-imp
https://tbcdb.com/?spell=688

**Expected behavior**

When in the aggressive stance, the Imp is expected to attack any target the player attacks, as well as attack any target attacking the player and/or itself.
When in defensive mode, the imp is expected to only attack any target attacking the player and/or itself.
When in passive, the imp is expected to never attack.
The imp is expected to continue attacking until there is no applicable target to attack, depending on the combat stance.

**Additional context**

Another Warlock, lvl 70 Gnome named Missdot, helped me confirm this issue was present, as they experienced the same issues with their imp.

**Comment by LeandroSMatos-dev** [comment]
Adding to the bug: His way of attacking with the Firebolt is making the Imp go to the melee range, whereas with the Firebolt it is for him to attack in the ranged melee.

**Comment by kelno** [comment]
Thank you, should be fixed with next server update

**Comment by WillowWhisps** [comment]
This was from 9 months ago. And I totally forgot about it.

Bro I don't even play WoW anymore. Not even on private servers. Lol

I'm playin Final Fantasy 14, homeskillet. Consider joining. It's free to
play up through the first expansion (lvl 60) for as long as you want. And
it's not supporting Blizzard in any way. Because fuck Blizz. :P


Kind regards,
Confused ex-WoW player
