### ISSUE TITLE
Missing mobs in skettis

### ISSUE THREAD

**Issue by powme56** [SunstriderEmu/BugTracker#3879]
hello ! 

With the addition of Skettis quest HUB and the new mobs it includes, it's missing the 4 big elite trees spawns :  Talonsworn Forest-Rager ( https://www.wowhead.com/npc=23029/talonsworn-forest-rager ), which replace the old Moutain colossus that where here before the add of skettis ( https://www.wowhead.com/npc=21844/mountain-colossus ) .

Thx in advance for your answer !

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
