### ISSUE TITLE
Ogri'la quest chain is bugged for migrated characters

### ISSUE THREAD

**Issue by Penethor** [SunstriderEmu/BugTracker#3880]
**Describe the bug**
It seems that for migrated characters the the NPC Mog'dorg the Wizened doesn't give any quest at all. Which makes it impossible to acces all of the daily quests in Ogri'la.

**To Reproduce**
With a migrated character try to speak to all Ogri'la related NPCs and check the quest you have acces to.

**Expected behavior**
Mog'dorg the Wizened should give you the elite quests needed to unlock all the dailies.

**Comment by Jerrythemagicdog** [comment]
Going to need some details here, can I have your character name?

**Comment by Penethor** [comment]
Sure. My bugged character is Penethor. I have another character leveled entirely on Horde and I can get the quests without trouble.

**Comment by Penethor** [comment]
I don't know what you did but now I can get the 3 quests. Thanks for that, I am closing this now.
