### ISSUE TITLE
Quest broken: Sweet Serenity

### ISSUE THREAD

**Issue by Randalierer** [SunstriderEmu/BugTracker#3881]
**Describe the bug**

There should be two different "blacksmithing plans" in Stratholme. When you loot one of them a NPC spawns. On the living site should spawn "Crimson Hammersmith" which is needed for the quest "Sweet Serenity". The other will spawn "Black Guard Swordsmith". Here, both plans let spawn the black guard and not the hammersmith.

BS-plans of Hammersmith: https://classic.wowhead.com/object=176325/blacksmithing-plans#contains
BS-plans of Swordsmith: https://classic.wowhead.com/object=176327/blacksmithing-plans#contains

Quest: https://classic.wowhead.com/quest=8869/sweet-serenity
Questitem: https://classic.wowhead.com/item=13351/crimson-hammersmiths-apron
Questmob that doesnt spawn: https://classic.wowhead.com/npc=11120/crimson-hammersmith

**Comment by Jerrythemagicdog** [comment]
Thanks for the details here, really makes it much easier.
Fixed with next update.
