### ISSUE TITLE
Dragonmaw transporters are bugged

### ISSUE THREAD

**Issue by Balanarr** [SunstriderEmu/BugTracker#3882]
**Describe the bug**
Dragonmaw transporters and I assume all flying mobs are not where they appear to be

**To Reproduce**
Attempt to attack dragonmaw transporter mobs with range attacks
Even tried on top of them

Almost always out of range, when lucky enough to have a cast go through the run to another position

**Expected behavior**
Mobs to actually be where they appear to be

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.
