### ISSUE TITLE
SP and crit neck buff removed when swapping form - Balance druid

### ISSUE THREAD

**Issue by lolqopp** [SunstriderEmu/BugTracker#3886]
**Describe the bug**
When using Eye of the night and Chain of the twilight owl the effect is removed if I swap to bear or cat form. Moonkin form works fine.

**To Reproduce**
1. Use Eye of the night or Chain of the twilight owl
2. Go to cat or bear form

Items; 
https://www.wowhead.com/item=24116/eye-of-the-night
https://www.wowhead.com/item=24121/chain-of-the-twilight-owl

**Expected behavior**
Expected buff to stay until time runs out or removed.

**Comment by beraus** [comment]
Can't reproduce, can you provide a video of this issue?

**Comment by lolqopp** [comment]
Here is test using chain of the twilight owl;
https://imgur.com/a/i3PPfiP

**Comment by lolqopp** [comment]
You want a video of other neck as well, exact same issue.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
