### ISSUE TITLE
Grulloc Has Two Skulls quest doesn't work.

### ISSUE THREAD

**Issue by mdeluca0** [SunstriderEmu/BugTracker#3890]
**Describe the bug**
Grulloc Has Two Skulls Quest doesn't spawn the skull for quest completion.

**To Reproduce**
1. Kill Grulloc
2. See that the lootable skull doesn't spawn.

https://www.wowhead.com/quest=10995/grulloc-has-two-skulls

**Expected behavior**
Skull should drop to loot for quest completion.

**Screenshots/videos**
![WoWScrnShot_070720_002105](https://user-images.githubusercontent.com/32890117/86726542-e21b1e00-bfe7-11ea-8856-eb55b851e2b9.jpg)

**Additional context**
Video of the quest: https://www.youtube.com/watch?v=9a4KqS1ty7k

**Comment by Penethor** [comment]
I can confirm it doesn't work on most cases. For me it dropped in 1/4 kills...

**Comment by AndreyMinenko** [comment]
kill him 3 times and dont drop

**Comment by Facelessconsumer** [comment]
Killed twice yesterday. No skull spawn.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
