### ISSUE TITLE
Slow effects on feral druid while in cat form with Feral swiftness & dragonhide set bonus

### ISSUE THREAD

**Issue by cyclones123** [SunstriderEmu/BugTracker#3891]
i play feral druid pvp, and i think the slows that i get are bugged while in cat form (having feral swiftness talent 30% movement speed and dragonhide 4set bonus 15% movement speed) .for example, warlock slows curse of exhaustion slows me by 30% and when i read the curse on me it actually says 30% and it looks like its a 30% slow. however, getting slowed by mage's ice armor, even though it says 30% on me it looks like im slowed by much more than  30% feels like 70% while the debuff still says 30%. similar things with shamans earth  bind slows etc.

i would like to add that there are slows which says by (percentage%) like shamans earthbind slow, and slows from frost shock which says by (percentage% of normal speed) also warriors hamstring, this  means that those type of slows are not the same! since if you press Dash while slowed by percentage slow, you should overcome that slow. however, pressing dash while in hamstring, doesn't do anything. i  think there is a critical error here somewhere.

**Comment by Jerrythemagicdog** [comment]
Makes sense that Ice Armor is not 30% because most mages play with Permafrost which increases the slow further by another 10%. There's pretty much not a single frost talent build for mages in PvP that doesn't include that talent.

**Comment by cyclones123** [comment]
> Makes sense that Ice Armor is not 30% because most mages play with Permafrost which increases the slow further by another 10%. There's pretty much not a single frost talent build for mages in PvP that doesn't include that talent.

that is  what im saying, you did  not completely understand me it is not the added 10% that is the issue, because it doesn't slow for 40% it slows for much  more! also you completely skipped the second paragraph of what i wrote.
