### ISSUE TITLE
Dailies in Skettis not giving rep

### ISSUE THREAD

**Issue by mrhultin** [SunstriderEmu/BugTracker#3892]
**Describe the bug**
Doing dailies in Skettis (Fires over Skettis & Escape from Skettis) do not reward the 350 rep they should. This makes the grind really hard. 

**To Reproduce**
Do dailies in Skettis

https://www.wowhead.com/quest=11008/fires-over-skettis & https://www.wowhead.com/quest=11085/escape-from-skettis

**Expected behavior**
Quest seems to work as intended, except not rewarding reputation.

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
