### ISSUE TITLE
Damage from melee adds in instants?

### ISSUE THREAD

**Issue by kjaer88** [SunstriderEmu/BugTracker#3894]
Are you aware of that melee adds do insane amount of damage?

For example, a druid with 14.500 health and with 430 defense (defense cap is 415) dies in few seconds with 4 mobs at him in normal such as Botanica WHAT THE HELL?

And TBC druids relay at resilience (103 resil = crit immune), that do not work either.

This makes it a pain to tank -.-, do not know if you would look in to…

**Comment by NeonicSupersonic** [comment]
Thats how tbc is, you kill mobs 1 by 1 using cc unless you have t6 gear
