### ISSUE TITLE
Quest: I Was a Lot of Things (oronok tuber quest)

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#3895]
**Describe the bug**

shadowmoon tuber mounds do not always interact with quest item; regardless if a boar is nearby to the mound or not.
the lootable spawns are less than 50% spawn when using the whistle. 
sometimes even standing on top of a seen tooltip of shadowmoon tuber it says you do not have one nearby to use whistle.

**To Reproduce**

1. Be on quest for 10 tubers
2. Use whistle near shadowmoon tube mounds for less than 50% success rate

Item: https://db.endless.gg/?item=30462 https://db.endless.gg/?item=30356
Quest: https://db.endless.gg/?quest=10514

**Expected behavior**

Shadow moon tube mounds should interact from a https://db.endless.gg/?npc=21195
Also to note the domesticated felboar are being obliterated by the flayers - which is normal - but when the flayers kill them they are marked skinnable but do not yield any skins. They should not be skinnable period when slain by an NPC.

Talk to you soon,
Silth

**Comment by hismama** [comment]
I just completed this quest myself. It looks like there is a second CD controlling whether the boar comes to the tuber. The tubers will respawn very quickly but the boar is not ready. After about 3min waiting on a tuber, the boar will eventually come when whistled.

**Comment by Jerrythemagicdog** [comment]
Thanks, the cooldown was reduced some time ago.
