### ISSUE TITLE
"Apexis Emanations" Buff working outside of Blade's Edge Plateau's

### ISSUE THREAD

**Issue by aidsi** [SunstriderEmu/BugTracker#3896]
**Describe the bug**
The buff "Apexis Emanations" which you get from the daily quest "The Relic's Emanation" is currently working outside of Blade's Edge. The movement speed portion should be limited to BEM.

**To Reproduce**

1. Get the dailyquest "The Relic's Emanation" from Ogrila.
2. Finish the Simon event on crystals to receive the buff "Apexis Emanation"
3. Leave Blade's Edge. 

Quest: https://db.endless.gg/?quest=11080
Spell: https://db.endless.gg/?spell=40625

**Expected behavior**

The movement speed -portion of the buff should only work while in Blade's Edge Plateau's.

**Screenshots/videos**

**Additional context**

The movement speed percentage might stack up if you finnish the Simon -event, the speed seems more than the intended 15%. Not certain about this one since I didn't do more testing regarding this.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
