### ISSUE TITLE
The NPC does not issue The Cudgel of Kar'desh

### ISSUE THREAD

**Issue by Gudwen911** [SunstriderEmu/BugTracker#3898]
The NPC does not issue The Cudgel of Kar'desh.
there is an exclamation mark above the NPC, but it does not give out the task itself.

https://www.wowhead.com/quest=10901/the-cudgel-of-kardesh

![WoWScrnShot_070720_132412](https://user-images.githubusercontent.com/67995329/86882145-71175b80-c0f8-11ea-9d33-782986bf74d3.jpg)
![WoWScrnShot_070720_132419](https://user-images.githubusercontent.com/67995329/86882151-72e11f00-c0f8-11ea-84ad-782431a2ef01.jpg)

game nickname Gudwin

**Comment by Jerrythemagicdog** [comment]
He does so after you accept and complete this quest (which is an autocomplete quest).

**Comment by Gudwen911** [comment]
do I understand you correctly that there will be 2 items on the quest without its presence in the list of tasks?
