### ISSUE TITLE
Client closes after clicking on mailbox !!

### ISSUE THREAD

**Issue by zecke345** [SunstriderEmu/BugTracker#3899]
It happened now the  2nd time (yesterday first time). When i click on the mailbox. the client closes instantly 
So i have to login again!  Not much to say in addition, just to inform you in order to fix this somehow

**Comment by mrhultin** [comment]
This seems like a addon issue, I open and close the mailbox ATLEAST 2k times per day, has never once had this happen. Try disabling addons.

**Comment by zecke345** [comment]
i need my addons. not only for raid.  and had no problems until this day for 5 week.s

**Comment by Jerrythemagicdog** [comment]
Try disabling the addons and trying again.
