### ISSUE TITLE
Reputation being splitt in open-world.

### ISSUE THREAD

**Issue by mrhultin** [SunstriderEmu/BugTracker#3900]
**Describe the bug**
Currently, reputation gains in the openworld are splitt, meaning if you're 2 players killing a  mob giving 10 rep, you get 5 each. This is inconsistent with how it was on all versions of retail, where each player would recieve 10rep each.

**To Reproduce**
Kill any mob in party and without, compare results.

**Comment by NeonicSupersonic** [comment]
Thats how it was in retail

**Comment by mrhultin** [comment]
> 
> 
> Thats how it was in retail

This is incorrect. I tested in Classic and it does not get split the way described.

**Comment by Jerrythemagicdog** [comment]
We're hearing some conflicting information from other players, similar to this thread. Would be great to get a definitive TBC source.

**Comment by NeonicSupersonic** [comment]
Classic is not a tbc. It worked that way on every single tbc server I have ever played, but you free to find actual retail tbc source to prove me wrong.

**Comment by Jerrythemagicdog** [comment]
We found something randomly:

> Patch 2.1: Players will experience diminished gains in reputation from killing outdoor mobs while in raids larger than five players.

https://wow.gamepedia.com/Patch_2.1.0

Perhaps we're diminishing when not in raid as well?

**Comment by hotdogsteven** [comment]
[Beta Hunter Questing Solo = 5 rep a kill](https://youtu.be/ZnfsxnD-0MU?t=216 )
[TBCC Live Hunter 5 man group farming mobs for rep = 5 rep a kill](https://youtu.be/rdS-OlJFTxo?t=352)
There might be a reduction based on group size past 5 but does it really mater in TBC instead of vanilla?

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
