### ISSUE TITLE
Sha'tari Skyguard Rep

### ISSUE THREAD

**Issue by Pyrichiel** [SunstriderEmu/BugTracker#3901]
I am under the impression that "Fires over Skettis" is a repeatable daily for rep gain. I have done this every day since the patch release and it only have gave me the rep once for the initial completion of the quest. I am currently missing out on days of rep.

Also in Blades Edge Mountains i have done all the quests for the Sha'tari Skyguard and the ones for Ogri'lar but i am still unable to do "Wrangle some Aether Rays". I am getting rep for the bombing daily everyday but that's it. 

Could it be that the Wrangle quest opens up at revered?

![No Rep from Daily](https://user-images.githubusercontent.com/68012409/86918334-74254280-c11e-11ea-92f5-42555f943db5.jpg)

**Comment by mrhultin** [comment]
This has been reported, and fixed just needs to be pushed to the server.

**Comment by hufsa** [comment]
Indeed fixed but server has not been restarted yet.
