### ISSUE TITLE
Quest Bug: Dumphry's Request (Turn In)

### ISSUE THREAD

**Issue by deptisaurus** [SunstriderEmu/BugTracker#3902]
**Describe the bug**

Dumphry's Request Quest Turn in Broken.
I have 4 Fel Iron Bars, 2 Arcane Dust, and 4 Motes of Fire. The npc says he wants these things but wont let me click continue on the quest dialogue. 
**To Reproduce**

1. Get quest materials 
2. Walk up to Dumphry in hellfire 
3. right click him and click the quest
4. next page continue is still greyed out even though I have mats. 

Item: https://wowhead.com?item= 
Quest: https://wowhead.com?quest= https://www.wowhead.com/quest=10763/dumphrys-request
Spell: https://wowhead.com?spell=
npc: https://www.wowhead.com/npc=21209/dumphry
**Expected behavior**

to be able to turn in the quest as I have all the items. 
**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with the next update.
If your issue is not fixed then (in the next 24hrs) please open a support ticket in game.
