### ISSUE TITLE
Spellstrike Patterns drop rate are not accurate

### ISSUE THREAD

**Issue by artharhys** [SunstriderEmu/BugTracker#3903]
Current Behavior
[Pattern: Spellstrike Hood] and [Pattern: Spellstrike Pants] are at a decreased drop rate.

Steps to recreate the issue
1.- Level tailoring to required skill to loot the item (375 required to learn)
2.- Repeatedly kill Grand Warlock Nethekurse (Shattered Halls first boss) and Murmur (Shadow Labyrinth last boss) and determine drop rate

ID's
Item (Head):            https://www.wowhead.com/item=24312/pattern-spellstrike-hood
Item (Legs):             https://www.wowhead.com/item=24309/pattern-spellstrike-pants
Nethekurse (Head): https://www.wowhead.com/npc=16807/grand-warlock-nethekurse
Murmur (Legs):        https://www.wowhead.com/npc=18708/murmur

Expected behavior
Drop rate from profession exclusive drops is significantly reduced on databases due to the fact that, if there is nobody to loot the item the drop will not occur.
Wowhead comment link from 2007: https://www.wowhead.com/item=24309/pattern-spellstrike-pants#comments:id=54748

Source(s)
https://www.wowhead.com

**Comment by mrhultin** [comment]
It is quite possible they are off compared to real values, however drop rates of stuff like this has always been notoriously bad. It will not drop if there isn't a tailor in the party, for example. 

According to sources you linked, they have a 1.2% drop chance, according to db.endless.gg (which I assume pulls information from the same db the server does) lists it at 10%

**Comment by LeandroSMatos-dev** [comment]
"According to sources you linked, they have a 1.2% drop chance, according to db.endless.gg (which I assume pulls information from the same db the server does) lists it at 10%"

No way it's 10%.I am farming this recipe in both heroic and normal mods and only saw it drop once in about 4 weeks of farm, and i have 375 tailor.  The endless website may be showing 10% but the chance should be less. 10% is a high chance for a recipe and even more for one that has the condition of having someone with the profession in the group at the time of the kill.

Just observe the number of groups building reputation in SHH until the first boss, how many times the recipe dropped when there was someone with a 375 tail in the group.

**Comment by Jerrythemagicdog** [comment]
> According to sources you linked, they have a 1.2% drop chance, according to db.endless.gg (which I assume pulls information from the same db the server does) lists it at 10%

The website database is not consistent with the in-game database, we've not really meant to use it in that capacity, it's mostly for tooltips on the main page and displaying stats in the Armory, however it would be a good idea to have it consistent with the game db. If we do go with that idea it we'll make sure to let players know.

We've udpated the drop chance for normal difficulty Murmur to 5% as the comment suggested, heroic difficulty remains at 10%.
