### ISSUE TITLE
Hunter 4 Piece Tier 5 Set Bonus Not Working

### ISSUE THREAD

**Issue by Fishcowduck** [SunstriderEmu/BugTracker#3904]
**Describe the bug**
The Hunter Tier 5 Set Bonus is not applying the 5% crit rating to your steady shot

**To Reproduce**
1. Equip 4 items of the Rift Stalker set
2. Cast steady shot on target

https://db.endless.gg/?itemset=652

**Expected behavior**
Upon equip of 4 pieces of Rift Stalker your steady shot crit chance is meant to be 5% higher than your base character sheet.

**Screenshots/videos**
https://imgur.com/a/SS4FOtM
To clarify the two screenshots are both with 4 piece T5 equipped just two different tests

**Comment by bjh368** [comment]
As far as I can tell the set bonus seems to work, compare my auto shot crits and steady shot crits over 2.8k shots of each attack. 

![image](https://user-images.githubusercontent.com/59749446/87061904-a2814b80-c20c-11ea-824b-4b5f60e9ce5f.png)

**Comment by Fishcowduck** [comment]
![hunter test 3](https://user-images.githubusercontent.com/68053772/87078936-5544b000-c1f3-11ea-9058-23cbcf19306d.png)
![Hunter test 3 1](https://user-images.githubusercontent.com/68053772/87079164-a2c11d00-c1f3-11ea-89f3-a2a1bb40e158.png)
Over 1000 more shots, my third test shows a more true result. However if you average all 3 of my attempts with the same exact setup it still falls short of the 5%.
Perhaps more testing and maybe with different combinations of the tier. I do not have helm and that is my current offpiece.

**Comment by bjh368** [comment]
Apart from that 28.4% crit attempt you have it's all giving reasonably expected number, and if you include it and the others together, account for crit supression against boss level target dummy, you are about 0.5% short of the expected result. I can't see auto shot crit % in your first tests so I have to compare to sheet crit. Your final test, with the biggest sample size, gives the same result as mine: it works. 

Seems to me that your testing confirms that it is working properly.

**Comment by Fishcowduck** [comment]
![hunter test 4](https://user-images.githubusercontent.com/68053772/87087469-25040e00-c201-11ea-9ecc-9f8787012a16.png)
![hunter test 4 1](https://user-images.githubusercontent.com/68053772/87087472-27fefe80-c201-11ea-8dbe-f3e60e294af3.png)
Here is the last test I'll be doing. It does seem to be working as intended and is extremely time consuming to provide larger sample sizes.
