### ISSUE TITLE
The NPC does not issue The Cudgel of Kar'desh

### ISSUE THREAD

**Issue by Gudwen911** [SunstriderEmu/BugTracker#3905]
The NPC does not issue The Cudgel of Kar'desh.
there is an exclamation mark above the NPC, but it does not give out the task itself.

https://www.wowhead.com/quest=10901/the-cudgel-of-kardesh

![WoWScrnShot_070720_132412](https://user-images.githubusercontent.com/67995329/87060780-98af1680-c213-11ea-86c5-1814b1ff4953.jpg)
![WoWScrnShot_070720_132419](https://user-images.githubusercontent.com/67995329/87060787-99e04380-c213-11ea-87f1-980b363174a9.jpg)

don't close as https://github.com/SunstriderEmu/BugTracker/issues/3898
give the task or make it complete

game nickname Gudwin

**Comment by Jerrythemagicdog** [comment]
Try clearing you Cache, there are no other players with this issue, if a problem persists open a ticket in game.
