### ISSUE TITLE
Molten Armor doesn't proc Impact

### ISSUE THREAD

**Issue by boxitooo6629** [SunstriderEmu/BugTracker#3906]
**Describe the bug**
 Rouges can remove slow with vanish, molten armor doesn't proc ignite and clearcasting, impact doesn't proc from molten armor. Pom pyro mage is unpossible to be played in this server...

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
The issue here is Molten Armor not being able to trigger Impact.
Rogues can of course remove any slow with Vanish.
Molten Armor can't proc Ignite since 2.3(https://vanilla-wow.fandom.com/wiki/Molten_Armor):

> As of patch 2.3 Molten Armor will no longer trigger Ignite. This is significant because an unexpected DoT from this talent could cause problems when trying to polymorph a mob.

https://classic.wowhead.com/forums&topic=3375#p34433

> i think its a good thing it doesnt proc ignite b/c then you would have a pesky dot you cant controll on ur target sometimes screwing up your sheep and wasting a DR charge if you even have time to cast sheep again

**Comment by boxitooo6629** [comment]
What about clearcasting?

Molten armor should proc it...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by izidn** [comment]
One month and since no change on molten armor who doesnt make proc IMPACT or clearcasting ?!!!

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
