### ISSUE TITLE
Druid aquatic form quest, cannot loot first half of the pendant.

### ISSUE THREAD

**Issue by Fnug1** [SunstriderEmu/BugTracker#3907]
When doing the quest "Trial of the sea lion" the first half of the pendant found in a chest in Darkshore cannot be done since the chest cannot be opened.

**Comment by beraus** [comment]
Need a video or screenshot, quest is working fine for me,

**Comment by Fnug1** [comment]
Tried to abandon quest and do it over again, same result i cannot loot the chest in Auberdine.
Screenshot: 
![WoWScrnShot_080220_202526](https://user-images.githubusercontent.com/68082979/89130385-cc284c80-d504-11ea-8841-b7d12fa85954.jpg)
![WoWScrnShot_080220_202532](https://user-images.githubusercontent.com/68082979/89130386-cd597980-d504-11ea-8b29-5f7a30d88030.jpg)

**Comment by z5n** [comment]
Unable to reproduce
