### ISSUE TITLE
 Manalicious spawn rate

### ISSUE THREAD

**Issue by ageerik** [SunstriderEmu/BugTracker#3910]
Been at the place for 15 min only seen one that someone else picked, took 2h and 15 min for another from the guild to complete the quest.

**Comment by Penethor** [comment]
The plants should have a much faster spawn rate. You can read comments in Wowhead of people taking 4 minutes to complete it.

**Comment by Jerrythemagicdog** [comment]
Thanks, changed to 30s with next restart.
