### ISSUE TITLE
Not able to assign loot to one of my raiders

### ISSUE THREAD

**Issue by Strawbs91** [SunstriderEmu/BugTracker#3911]
I cant assign loot to one of my raiders. i have provided screenshts. The players name is "zerokaze"  and he is not on the drop down option for me to assign helmet to??

I now have the helm in my bag "lottadots" PLEASE can this be moved to zerokaze character?

Thanks 
![WoWScrnShot_070920_232458](https://user-images.githubusercontent.com/65979674/87151834-72898500-c2ac-11ea-8144-60e1e826e4d1.jpg)
![WoWScrnShot_070920_232501](https://user-images.githubusercontent.com/65979674/87151859-7b7a5680-c2ac-11ea-9c33-08e1e2419c57.jpg)

**Comment by beraus** [comment]
Please make the ticket in game (include link to this report) and we'll sort it out.
