### ISSUE TITLE
Stuck in Blood Furnace (H)

### ISSUE THREAD

**Issue by MarkusMarkusH** [SunstriderEmu/BugTracker#3912]
Hi,

I tried to enter Blood Furnace (H) and i got stuck while entering. In the loading screen i just received an error message and now i can't log in. The characters name is Totemly. The same thing happened like a month ago when i tried to enter the dungeon on normal.

Would appriciate if you could help me with this!

I don't blame you all for this and it's not a demand of course, but since I lost out on my group due to this and have lost a lot of play-time, would it be possible to be compensated in heroic badges? 

Also; since this has happened twice now it would be great if you could try to examine the problem!
But for now; getting me out of the instance so i can log in on my char would be great!

Thank you!

Kindest regards,
Totemly

**Comment by beraus** [comment]
Resolved in game.
