### ISSUE TITLE
Help me with one questline!

### ISSUE THREAD

**Issue by gogramannn** [SunstriderEmu/BugTracker#3913]
Good day. I have a problem with this quest line - 
https://tbcdb.com/?quest=10946
After update https://endless.gg/changelog/2020/06/30 - this quest line is missed. I cant get it again, all parts of this questline is gone. But i have amulet from 1 of the previous quest. Please help me. What i need to do? 
![1213](https://user-images.githubusercontent.com/68083370/87156683-be94f380-c2c5-11ea-9e69-5509869cf247.png)

**Comment by beraus** [comment]
Please make the ticket in game (include link to this report) and we'll sort it out.

**Comment by gogramannn** [comment]
Good day. Sorry, I am a little confused. What do you mean by «ticket»? Write to you in the game or what? I am newbee in this case. 
Link for complaint —  https://github.com/SunstriderEmu/BugTracker/issues/3913

**Comment by gogramannn** [comment]
I found and sent a ticket. Sorry to bother you. 


  
>Суббота, 11 июля 2020, 12:54 +03:00 от Павел малык <gograma369369@mail.ru>:
> 
>
>Good day. Sorry, I am a little confused. What do you mean by «ticket»? Write to you in the game or what? I am newbee in this case. 
>Link for complaint —  https://github.com/SunstriderEmu/BugTracker/issues/3913
>>Суббота, 11 июля 2020, 5:26 +03:00 от Bareus < notifications@github.com >:
>> 
>> 
>>Please make the ticket in game (include link to this report) and we'll sort it out.
>>—
>>You are receiving this because you authored the thread.
>>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
> 
> 
>  
 
 
С уважением,
Павел малык
gograma369369@mail.ru
