### ISSUE TITLE
Undercity Auction House

### ISSUE THREAD

**Issue by twistedjt** [SunstriderEmu/BugTracker#3914]
**Describe the bug**
I just deposited a bunch of items into the bank in the undercity and when they left my item bag they did not enter the bank.

**To Reproduce**

1. I right clicked the item in my bag and it left but did not show up in the bank bag.

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

I would just like my items back. I deposited several stacks of different types of cloths, scrolls, and bandages. I am not sure if you can see what I deposited and lost or not.
**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment]
What's your char name?
