### ISSUE TITLE
The Bloodsail Buccaneers

### ISSUE THREAD

**Issue by Randalierer** [SunstriderEmu/BugTracker#3915]
**Describe the bug**

There should be a faction called "bloodsail buccaneers", but there isnt. Killing pirates or booty bay bruisers just in- or decrease reputation with booty bay but not with the buccaneers. Same is for quests in Booty Bay, they should also decrease reputation with the pirates.

Faction: https://classic.wowhead.com/faction=87/bloodsail-buccaneers

**Comment by kelno** [comment]
Fixed with next update
https://github.com/kelno/sunstrider/commit/70c311a2ff1c4fed7f0c268861959abbcdc1d652
