### ISSUE TITLE
#1 People cant see my messages

### ISSUE THREAD

**Issue by Dialyza** [SunstriderEmu/BugTracker#3916]
**Describe the bug**

#1
So, any time I try to say/whisp something ingame (I am lvl 70), people just dont see it. Tried it with other player from discord, he sent me "123", I saw that, I replied "456", he didnt get anything. I joined "global" of course, but cant do any normals/hc because ppl just dont see me asking for that. I tried to disable all addons, rejoin global, delete Cachce file, didnt help any of it. Tried to whisp with other char, same problem. 
Any advices please?

**Comment by beraus** [comment]
In game name?

**Comment by Dialyza** [comment]
Working now, thank you
