### ISSUE TITLE
disenchanting bug

### ISSUE THREAD

**Issue by DMN7** [SunstriderEmu/BugTracker#3917]
**Describe the bug**
disenchanting is just destroying my item and not giving mats. happening on multiple items, various item levels.

**Screenshots/videos**
https://www.youtube.com/watch?v=O3dBXF--GYI&feature=youtu.be

**Additional context**
i made an ingame ticket and was told to post here by nori, i was also told i would receive back lost items by bareus.
i lost 5 level 70 blues and 4 greens before i made the video :(

**Comment by DMN7** [comment]
i tried upgrading my enchanting rod to runed arcanite rod, and learning master level enchanting. but the issue still happens when i try to disenchant.

i wonder if my enchanting is just bugged on my toon and i have to unlearn it and relearn it again?? i spent way too much gold just to unlearn it tho :(

**Comment by beraus** [comment]
Disable auto loot, and that addon and try again.

**Comment by DMN7** [comment]
> Disable auto loot, and that addon and try again.

i can confirm it is an addon, im not sure which one as i just clicked disable all and tried again.

i didnt know an addon can do this. thanks for your help beraus!
