### ISSUE TITLE
priest: consume magic can dispell resurrection sickness

### ISSUE THREAD

**Issue by Player1222** [SunstriderEmu/BugTracker#3918]
**Describe the bug**
As a priest after death Resurrection Sickness can be dispell by Consume Magic spell.

**To Reproduce**
1. die
2. resurrect by Spirit Healer
3. use Consume Magic spell

Resurrection Sickness: https://classic.wowhead.com/spell=15007/resurrection-sickness
Consume Magic: https://wow.gamepedia.com/Consume_Magic_(priest_ability)

**Expected behavior**
Since Consume Magic should dispell only "one beneficial Magic effect" it shouldn't be happening because Resurrection Sickness is not beneficial

**Comment by hufsa** [comment]
Thanks! Fixed with next update.
