### ISSUE TITLE
Ogri'la daily quest bug

### ISSUE THREAD

**Issue by Navhavalo** [SunstriderEmu/BugTracker#3920]
Description:
'The Relic's Emanation' daily quest is bugged, sometimes colored buttons are just inactive

Steps to reproduce

1. Take 'The Relic's Emanation' quest
2. Start the quest at appointed place
3. Follow the colored and sound combinations

ER: you can easily press needed buttons
AR: sometimes buttons you need to press to complete the daily q are just inactive, q can not be completed

**Comment by Penethor** [comment]
Some plataforms are currently bugged. You should try a few and stick with one that works completely.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
