### ISSUE TITLE
Watertight Trunks disappearing

### ISSUE THREAD

**Issue by AskAverie** [SunstriderEmu/BugTracker#3921]
**Describe the bug**
Watertight trunk fished from Wetlands disappears on right click

**To Reproduce**
Fish wreckage in Wetlands to procure Watertight Trunk
Attempt to open trunk on bridge out of Menethil Harbor
Item disappears instead of dispensing leveled loot

<ids of affected creatures / items / quests with a link to the relevant wowhead-like page. -->
Item: https://classic.wowhead.com/item=21113/watertight-trunk

**Expected behavior**
Trunk should open as container with leveled loot for area

**Comment by beraus** [comment]
Disable addons and try again.

**Comment by chestermjr** [comment]
@beraus This happens to me too. I don't think it is addon-related. I think it is related to the Weather-Beaten Journal. I think the item is bugged. The item should appear, but for some reason it is not appearing. I have opened hundreds of Curious Crates, dozens of Watertight Trunks, in search of the Weather-Beaten Journal, and many of my containers are empty, yet I still can't find the Weather-Beaten journal.

**Comment by AskAverie** [comment]
I agree, Chester. Plus it's a little hard to "try again" on an item that literally disappears from your inventory

**Comment by Jerrythemagicdog** [comment]
Weather-Beaten Journal was not available until a few months ago due to patch restrictions, thanks for the issue.
