### ISSUE TITLE
soul link damage on pets isn't healed on bg ress

### ISSUE THREAD

**Issue by lardaoc** [SunstriderEmu/BugTracker#3922]
Describe the bug
Whenever you die in a BG as a sl/sl lock your pet will be rezzed with whatever hp it had left after you died

To Reproduce
Die in a BG with soul link and pet up

Expected behavior
Pet should rezz with full health

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3137
