### ISSUE TITLE
Pure Water (Nagrand pools) 

### ISSUE THREAD

**Issue by ColunWaton** [SunstriderEmu/BugTracker#3923]
Some ''Pure Water'' are bugged from Nagrand. The error message says: ''You have no target'' ''You can't use that here''. 
I saw 3 times this bug and reduces de farming of primal water. Ty!

**Comment by bjh368** [comment]
Never had any issue with fishing primal water in nagrand, are there specific pools bugging or just random?

**Comment by powme56** [comment]
Yeah had the same the last few days, really tricky to fish some of them

**Comment by babno** [comment]
Was it the one in the river just east and very close to halaa? If so I don't think it's a pool issue, I think just a lot of the water is just misflagged as not fishable water.

**Comment by Jerrythemagicdog** [comment]
Going to need some specific places here, thanks for the issue.
