### ISSUE TITLE
Eternium ore droprate

### ISSUE THREAD

**Issue by N7Nosk** [SunstriderEmu/BugTracker#3924]
Droprate of eternium ore is somehow too low.
Farming all the nodes of fel iron, adamantite, rich adamantite and khorium in nagrand and after all bags are full there is not even 1 stack of eternium, more often less then 10

Item: https://www.wowhead.com/item=23427/eternium-ore#mined-from-object

Droprates for eternium here is about 5 to 10% for all nodes, but according to wowhead must me a lot more, etc.:
Rich adamantite - 44-49%
Khorium - 30%
Adamantite - 30%
Fel iron 6%
data from wowhead

**Comment by NeonicSupersonic** [comment]
Those are values which were buffed like 10 times after tbc
If you want to see actual droprates, use internet archive databases
https://web.archive.org/web/20070624010323/http://www.wowhead.com/?item=23427#z0oz
