### ISSUE TITLE
Gorgrom the Dragon-Eater

### ISSUE THREAD

**Issue by funkeytown** [SunstriderEmu/BugTracker#3925]
During the Gorgrom quest, when attempting to summon Gorgrom with the Sablemane's Trap, the trap does not function. 

The trap's /use action currently sets your cursor to select something to use it on rather than summoning Gorgrom at the Alter of Goc.  The alter itself is not selectable by this action either.

![IMG_20200712_105550](https://user-images.githubusercontent.com/22035120/87251127-fff4e280-c42e-11ea-9c40-7272a56cc95b.jpg)

**Comment by N7Nosk** [comment]
Stand atop of the altar

**Comment by funkeytown** [comment]
That's been tested as well.  The problem is that the Sablemane's Trap doesnt activate

**Comment by Jerrythemagicdog** [comment]
You're in the wrong place. You're on "Gorgrom the Dragon-Eater" (10802) but you're at the wrong altar. Gorgrom's Altar is located in Boulder'mok near Raven's Wood.
