### ISSUE TITLE
Demonic Knowledge (warlock talent) not working properly. 

### ISSUE THREAD

**Issue by Anderstegnel** [SunstriderEmu/BugTracker#3926]
**Describe the bug**

The demonic knowledge talent does not work correctly, it says Increases your spell damage by an amount equal to 12% of the total of your active demon's stamina plus intellect,  the values is not correct, I will show in screenshots below.
**To Reproduce**

1. Summon felguard, spelldmg should now be 65+ if ur human but its 71,  if I equip all my gear it gives me 95+ spelldmg from demonic knowledge, however my demons stats with buffs was 793 without my gear 12% is 95 spelldmg, but with my gear and fully buffed my pet stats int + stam is 1020 and should give me 122+ sp but still only give me 95 + spelldmg
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

[](https://imgur.com/09bVHWu)
[](https://imgur.com/zUsaPfq)
[]https://imgur.com/KoqSarX)
[](https://imgur.com/KpsO9bl)
**Additional context**

even thought my demons stats increase and if im naked or wear gear I still only get 95 spelldmg, while on the last picture the spelldmg given to me should be 122sp and not 95sp. There is something scuffed with the values behind this talent.

**Comment by Anderstegnel** [comment]
[]https://imgur.com/09bVHWu)
[]https://imgur.com/zUsaPfq)
[]https://imgur.com/KoqSarX)
[]https://imgur.com/KpsO9bl)

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1522
