### ISSUE TITLE
Nagrand Arena Quest i buggy nobody can get Quest.

### ISSUE THREAD

**Issue by sfaoxao** [SunstriderEmu/BugTracker#3928]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment]
Known issue, should be fixed on live now.
