### ISSUE TITLE
Dragonscale LW trainer doesnt work?

### ISSUE THREAD

**Issue by Secspistols** [SunstriderEmu/BugTracker#3929]
**Describe the bug**
Impossible to train recipe from Dragonscale Leatherwork in the badlands

**To Reproduce**

1. Start LW but dont reach 375
2. Get the quest for dragonscale lw, complete it, and THEN cap LW at 375
3.  go back to the trainer, and you wont be able to learn the recipes

**Screenshots/videos**
![WoWScrnShot_071320_133044](https://user-images.githubusercontent.com/68228146/87300047-72d48b00-c50d-11ea-8e57-9cd723d9444e.jpg)

**Comment by lolqopp** [comment]
@Secspistols You sir have 373 LW in that picture...

**Comment by kelno** [comment]
Thanks for resolving this lolqopp
