### ISSUE TITLE
No experience from turning in quests!

### ISSUE THREAD

**Issue by LundstromA** [SunstriderEmu/BugTracker#3931]
**Describe the bug**

When i turn in a quest, I don't receive any experience at all - although in the chat log, it said i received a certain amount of experience. Neither the experience counter nor the UI of the XP bar changes. Experience from zone discovery and mob killing works perfectly fine though. Receiving quest rewards also works, such as gold or items. 

Experienced this while questing on my 60/61 character Beasthandler in Hellfire Peninsula on my orc warrior.
It occurred right after today's (2020-07-14) server reset.

**To Reproduce**

1. Complete quest objectives (works fine)
2. Hand in quest (currently in Hellfire Peninsula).
3. Receive quest rewards, but no experience.

Some quests i completed include, but are not limited to:

https://www.wowhead.com/quest=10442/helping-the-cenarion-post
https://www.wowhead.com/quest=10895/zethgor-must-burn
https://www.wowhead.com/quest=9498/falcon-watch

**Expected behavior**

I expected to receive experience that counted towards my level progression when turning in quests.

**Screenshots/videos**

Unfortunately I can't provide any screenshots, as I don't want to turn in anymore quests to lose experience at this time.

**Additional context**

**Comment by oskollum** [comment]
I have the same problem ... done 5 quest's and did not receive experience

**Comment by oskollum** [comment]
please refund my experience for the assignments ... 5 quests is not a little experience in my case ... nick Avin

**Comment by Jerrythemagicdog** [comment]
Fixed with last update, sorry for trouble!
