### ISSUE TITLE
smv, aldor town (61.97, 30.08) something weird probably bug abuse

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3932]
ally paladin nosferaty standing at the steps, some kind of dragon flying in every 5-10s (from the south and getting killed by the guards.  

saw at least 10 dragons with riders fly in and get killed not sure what he was doing, but im sure it wasn't legit.  he left after i tagged one trying to figure out what he was getting out of it.

**Comment by michaelkittrell** [comment]
probably something related to netherwing faction?

**Comment by Jerrythemagicdog** [comment]
It's a daily quest.
