### ISSUE TITLE
tk, trash oddities with los

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3933]
tk squires and astromancers (and probably other mobs) ignore line of sight in many places especially the protrusions that break the first hallway and the hallway to solarian/vr into "rooms"

the squires heal without anything approaching los and the astromancers shoot through walls.  

the falcon watchers in alar's room also shoot through the walls i believe (also hard to move them sometimes, they just get stuck and shoot instead of moving in to attack/shot the md'd target as expected)

we find ways to kill the trash in tk, but players should be rewarded for using mechanics like los to make encounters easier instead of mobs ignoring los and other oddities.

**Comment by Jerrythemagicdog** [comment]
That's intended by Blizzard and is in the spells themselves.
