### ISSUE TITLE
Quest : The fel and the furious doesn't work ALLY SIDE

### ISSUE THREAD

**Issue by YakubSix** [SunstriderEmu/BugTracker#3934]
Quest : The fel and the furious at Shadowmoon Valley does not work (ALLY SIDE)

Quest giver : Plexi

1. Accept Quest and player have 5 mins time on complete Q (works)
2. Player click on Fel Reaver console to control Fel Reaver Sentinel (works)
3. Player now control Fel Reaver Sentinel but does not work spells for completing quest

Quest : https://www.wowhead.com/quest=10612/the-fel-and-the-furious
NPC : https://www.wowhead.com/npc=21959/fel-reaver-sentinel-credit

**Comment by Jerrythemagicdog** [comment]
Can't reproduce, need more details. Please try clearing Cache and attempting the quest again.

**Comment by YakubSix** [comment]
Cache cleared , and however, spells only work with a mouse click, spells cannot be used by pressing binds.

BTW: Now is quest completed.

**Comment by Jerrythemagicdog** [comment]
Could be some action bar addon you're using, without any addons enabled the spells are usable through keybinds as expected.
Thanks for getting back to us!
