### ISSUE TITLE
Data Rescue

### ISSUE THREAD

**Issue by Pangoken** [SunstriderEmu/BugTracker#3937]
**Describe the bug**
The last Matrix Punchograph 3005 (3005-D) is not giving out the Prismatic Punch Card

**To Reproduce**

1. There are no steps. The issue is that they are missing.
2. 
3. 

Item: -
Quest: https://db.endless.gg/?quest=2930
Spell: https://db.endless.gg/?spell=11545

**Expected behavior**
Matrix Punchograph 3005-D is supposed to exchange the Red Punch Card into a Prismatic Punch Card via interaction.

**Screenshots/videos**
![WoWScrnShot_071420_224840](https://user-images.githubusercontent.com/50700937/87486609-ed032d80-c63b-11ea-9cc1-7f16233cc777.jpg)

**Additional context**

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1972
