### ISSUE TITLE
Quest : The Final Code

### ISSUE THREAD

**Issue by fcamargovalencia** [SunstriderEmu/BugTracker#3938]
Describe the bug

Quest The Final Code, dont know why but it didnt complete on my character. I tried many times and nothing. I take the quest item and activate Mana Bomb many times. Dont know what to do. I asked another people and they said what all is working, but why i cant complete this quest?...
To Reproduce

Cast X on target affected by ...
Item: https://www.wowhead.com/item=29912/the-final-code
Quest: https://www.wowhead.com/quest=10447/the-final-code
Spell: https://wowhead.com?spell=

Expected behavior

Complete the quest.
Screenshots/videos

![image](https://user-images.githubusercontent.com/18369495/87500895-575ba400-c623-11ea-8714-e9f1debc4ffa.png)

in the chat you can see the countdown of the bomb

Additional context

Character : Ultear human warlock lvl 70

**Comment by fcamargovalencia** [comment]
you can complete the quest although the requeriment in your quest lost isn't complete

**Comment by Jerrythemagicdog** [comment]
Try clearing your Cache and seeing if that helps, maybe the addon doesn't display information correctly.
