### ISSUE TITLE
Keli'dan's image in lower city started attacking me.

### ISSUE THREAD

**Issue by Keritous** [SunstriderEmu/BugTracker#3939]
[Keli'dan the Breaker Image](https://db.endless.gg/?npc=24413)
the image beside daily heroic quest giver started attacking me. (it can be pulled by stepping in the circle it is standing in)
![WoWScrnShot_071520_105736](https://user-images.githubusercontent.com/66011356/87511409-7fcab900-c68a-11ea-8d03-7ac5ba4716e7.jpg)
![WoWScrnShot_071520_105741](https://user-images.githubusercontent.com/66011356/87511459-9113c580-c68a-11ea-9444-298a79a5c4a3.jpg)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.
