### ISSUE TITLE
Netherwing(Nether Drakes) "At War" bug

### ISSUE THREAD

**Issue by NikyuuVl** [SunstriderEmu/BugTracker#3940]
Hello! I have skinning 375(max) which allows me to skin all animals and beasts in Outland. I am friendly with Netherwing so I to kill and skin Nether Drakes for Nether Dragonscales I need to have "At War" option enabled. The problem is that even though I have it enabled I cant still attack them and therefore I cant skin them to get the scales needed for crafting my gear.

Expected:
1.When "At War" is enabled to be able to attack Nether Drakes (Netherwing) without any problems so I can be able to skin them.

Thanks in advance!

**Comment by Morrigan83** [comment]
I have the same problem. this bug has been reported quite some times and needs to be fixed please. how are we supposed to craft our armor if we can't farm our mats

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
