### ISSUE TITLE
BF heroic last boss does not spawn after adds are killed

### ISSUE THREAD

**Issue by diederik89** [SunstriderEmu/BugTracker#3941]
Hi There,

We were this morning at the last boss in heroic BF daily dungeon, 4031 ID

I talked to a Gm and he told me to create a ticket on the bugtracker

Im a paladin tank called Tipzy,

and i was pulling the mobs LoS in the room before you go in to to kill the boss,
after the last mob was killed the boss did not spawn.
He was just standing still and we could not target him or anything, 
we used unstuck, Alt+F4 and tried alot of other things to reset the boss but nothing worked out.

**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, this most likely happened because the range check in the script was shorter than the distance you have pulled the channelers to.
We've increased the range now, fixed with next update.
