### ISSUE TITLE
Can't buy rare lv 30 mount from Night Elf mount vendor

### ISSUE THREAD

**Issue by jeremybaxman** [SunstriderEmu/BugTracker#3942]
I bought lv 30 apprentice riding. When I went to Lelanai, the nelf mount vendor, she was only selling epic mounts that require level 60 and journeyman riding. She sold the usual lv 60 mounts but in the place of the rare mounts were epic items called [Reins of the Tiger],  [Reins of the Goldsaber] and  [Reins of the Leopard]. These each cost 9g50s as if they were the rare mounts they had replaced.

I asked another player to check the vendor and they said that for him the rare mounts were there as normal.

**Comment by Jerrythemagicdog** [comment]
Clear your Cache and talk to the vendor again.
