### ISSUE TITLE
Blackheart the inciter +  mage polymorph

### ISSUE THREAD

**Issue by Istaryu** [SunstriderEmu/BugTracker#3943]
When the [Blackheart the Inciter](https://db.endless.gg/?npc=20637) casts [Incite chaos](https://db.endless.gg/?spell=33676), and a mage polymorphs you, you will be polymorphed for the full duration. I could not find any information about this, whether this is a bug or not, but it feels like it should not be the case.

Needless to say we had no dispels or anyone else that could heal, so it was a wipe. I stayed polymorphed for like 30 seconds after the mind control ended, and i slowly watched the tank die.

**Comment by babno** [comment]
Bugged like this for all cases where a mob MCs someone.

**Comment by kelno** [comment]
Fixed with next server update 
https://github.com/kelno/sunstrider/commit/020664cef8e557eafe45831abd0cc1c03349cfc0
