### ISSUE TITLE
Streams on endless.gg not working ?

### ISSUE THREAD

**Issue by Kirurgen** [SunstriderEmu/BugTracker#3946]
**Describe the bug**
Cannot watch streams on endless.gg/streams   screenshot: https://gyazo.com/a1ee8a73159aa0a3c13f0d1e68f6d893 all streams i get this error on, and idk how to fix that, any tips? 

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Sounds like an issue on your end, not sure what we can do about that, sorry!
Try clearing your browser's cache and disabling your browser's plug-ins if you have any.
