### ISSUE TITLE
How did I die?

### ISSUE THREAD

**Issue by bojanges** [SunstriderEmu/BugTracker#3947]
**Describe the bug**

My character suddenly died from full health.

**To Reproduce**

1. I have no idea that's why I'm here
2. 
3. 

No affected items etc I think?

**Expected behavior**

Not dying?
**Screenshots/videos**

![WoWScrnShot_071520_122048](https://user-images.githubusercontent.com/68350506/87586982-5021ae00-c696-11ea-8ed1-f469102d3a8e.jpg)

**Additional context**

I was running through Azuremyst Isle as a level 11 Draenei Shaman, I had just run from a furbolg camp, but I had taken less than 100 damage and I even healed myself, then as I was searching for a totem to turn in my quest the "You have died" box popped up and my character keeled over.  There is no explanation or description in the combat log aside from the non-helpful "you died" line.

**Comment by TheMoneyHater** [comment]
I blame 
![image](https://user-images.githubusercontent.com/11985642/87588671-56d71200-c6e4-11ea-89c1-82e9f2ae9998.png) but idk

**Comment by bojanges** [comment]
That sneaky bastard...
