### ISSUE TITLE
Fishing daily quest 'Crocolisks in the City' only contains gold

### ISSUE THREAD

**Issue by Earshelh** [SunstriderEmu/BugTracker#3948]
I had previously opened a report indicating that the fishing daily reward only contained gold. I closed the issue after I received items from the bag, thinking it had been solved. Turns out, there is a different item ID (https://www.wowhead.com/item=35348/bag-of-fishing-treasures#comments)  for the quest reward from the quest 'Crocolisks in the City' (https://www.wowhead.com/quest=11665/crocolisks-in-the-city). The reward for this quest is different because it is supposed to have a chance to drop a few unique items that the other dailies do not have a chance to drop. The comments on wowhead go in to good detail on the contents of each bag.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
