### ISSUE TITLE
Netherwing Daily: Disrupting the Twilight Portal progress

### ISSUE THREAD

**Issue by elseeth** [SunstriderEmu/BugTracker#3949]
It's not possible to do the Netherwing Daily: Disrupting the Twilight Portal.
Killing the "Deathshadow Agents" on Twilight Ridge on NW Nagrand does not progress the quest as intended.

Still 0/20 after MANY kills.

**Comment by Jerrythemagicdog** [comment]
Leave your party if you're in a party with someone who's offline or not there. The quest credit is shared and if the party members aren't present or offline you won't get credit.
