### ISSUE TITLE
Deviate Hides

### ISSUE THREAD

**Issue by Pangoken** [SunstriderEmu/BugTracker#3950]
**Describe the bug**
Nalpak is not giving the quest "Deviate Hides"

**To Reproduce**
1. There are no steps, the issue it that they are missing.
2. 
3. 

Item: -
Quest: https://db.endless.gg/?quest=1486
Spell: -

**Expected behavior**
For Nalpak to give out the "Deviate Hides" quest.

**Screenshots/videos**
![WoWScrnShot_071620_173846](https://user-images.githubusercontent.com/50700937/87692021-8bea6f80-c78b-11ea-9726-c6d2162e05ed.jpg)

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
