### ISSUE TITLE
Bugged Rogue (BF) quest: [Combining Forces]

### ISSUE THREAD

**Issue by katfalco** [SunstriderEmu/BugTracker#3951]
Rogue quest (Blood Elf) [Combining Forces] is bugged. Keltus Darkleaf gives a quest to to pickpocket the Lacy Handkerchief from the Sentinel Leader and bring it to him. However, the Sentinel Leader is nowhere to be found at An'daroth, so the quest cannot be completed.

**Comment by Jerrythemagicdog** [comment]
She's spawned in the northern area, maybe someone else has killed her.
