### ISSUE TITLE
Wrangle Daily for Sha'tari skyguard rep

### ISSUE THREAD

**Issue by Pyrichiel** [SunstriderEmu/BugTracker#3952]
I have done all of the quest chains for the sha'tari skyguard and i am 7.9k into honored. 

I am NOT able to do the Wrangle daily as it has not opened for me. 

I am able to do both the bombing quest in Skettis and in BEM. 

I do not understand why this quest is still locked out. 

I am really unhappy that i am missing out on thousands of rep because of this.. been like this since the release...

Please fix this for me and id appreciate a rep boost to compensate for the rep lost.

Cheers

**Comment by Jerrythemagicdog** [comment]
Perhaps you haven't done the Ogri'la quests: 
https://www.wowhead.com/quest=11065/wrangle-some-aether-rays#comments:id=129830
