### ISSUE TITLE
Small Prismatic Shard

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#3954]
**Describe the bug**
An "Enchant" which transforms **Large Prismatic Shard** to three **Small Prismatic Shards** is currently missing at Enchanting trainers.
https://tbc.cavernoftime.com/spell=42615

**To Reproduce**
Check Enchanting trainer in Thrallmar (didn't check alli side and can't check Scryers).

**Expected behavior**
Should be able to learn it at 335 skill.

https://wowwiki.fandom.com/wiki/Small_Prismatic_Shard?oldid=1468559
_"This item can also be crafted by enchanters with a skill level of 335 (...)"_

**Comment by NeonicSupersonic** [comment]
added in 2.3

**Comment by Rettiy** [comment]
The sources rather say 2.2 than 2.3 plus it's weak argument - see Eng goggles.

Then for example https://wowwiki.fandom.com/wiki/Enchant_Gloves_-_Superior_Agility is 2.2 but is at vendor already. It's more likely it's just missing than actual intention. Adding it wouldn't hurt anything and would be more consistent.

**Comment by Jerrythemagicdog** [comment]
Sure, no reason not to have it with other things out.
Live with next server update.
