### ISSUE TITLE
silver Vein spawn chance

### ISSUE THREAD

**Issue by sevkav2000** [SunstriderEmu/BugTracker#3955]
In Alterac Mountains i tried to farm some iron, but after mining Iron Vein, with high chance spawn silver Vein.
I farmed like an hour and got MORE silver than iron, i guess silver vein spawn is more rare than mythril or iron.
Let me know if its not a bug. Very dissapointed with that.

**Comment by beraus** [comment]
Would help if you can provide coords or/and screenshot/vide.

**Comment by sevkav2000** [comment]
There is some screens i didnt found any other vein eхept silver or gold today


https://imgur.com/a/VT9fXqi

**Comment by z5n** [comment]
issue has since been fixed
