### ISSUE TITLE
Cannot type in general chat 

### ISSUE THREAD

**Issue by Bowpra** [SunstriderEmu/BugTracker#3956]
**Describe the bug**
i can view all chat in windows but i cant respond to any i can slash g s but if i slash and number for a channel like local global or any other i can talk in it. 

**To Reproduce**

1. i log in and have all addons turned off and i have reloaded ui 
2. i try to / and number and it doesnt work
3. i can click on the chat name and whisper them but i can auto reply with /r 

Chat

**Expected behavior**
i expected to be able to chat and respond in all channels

**Screenshots/videos**

**Additional context**
if anyone can help with steps to get it fixed please send me a message or respond on here.

**Comment by Jerrythemagicdog** [comment]
What's the character name?

**Comment by kelno** [comment]
That's true for everyone currently, general channel sometime are broken on connect.

**Comment by z5n** [comment]
issue has since been fixed
