### ISSUE TITLE
Bladefist fist weapon from Heroic SHattered Halls bug

### ISSUE THREAD

**Issue by emeriss23** [SunstriderEmu/BugTracker#3958]
The proc rate is bugged, procs way too often clost to 100% uptime

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
The PPM is set to 3, same as retail sources indicate:
https://www.wowhead.com/item=29348/the-bladefist&bonus=4103#comments:id=60668

**Comment by TheMoneyHater** [comment]
This is working as intended, people keep complaining about it. Even saw a vid from retail proofing it.
