### ISSUE TITLE
problem with rogue quest for poisons(and thistle tea recepie)on Aliance

### ISSUE THREAD

**Issue by EternalAg0nY** [SunstriderEmu/BugTracker#3960]
As i tried to both pickpocket and kill the mob the outcome was the same,when I go up the tower to open the chest,the chest itself is there but i cant click on it to open(I got the item for opening the box a few times both ways).Quest was from SI:7(Stormwind) about poisons and thistle tea recepie(class quest).

**Comment by Jerrythemagicdog** [comment]
You need to have lock picking to open that chest on at least 70 skill.
https://www.youtube.com/watch?v=FkJZkvylBOE
