### ISSUE TITLE
Ranged attack speed

### ISSUE THREAD

**Issue by Shol4891** [SunstriderEmu/BugTracker#3961]
When i log/relog, my ranged weapon speed is at 1.99, but when i put my gun in my bag and re-equip it, speed goes at 2.25.

I spoke to Sincord, a hunter from "Zero integrity", he noticed the same bug.

**Comment by NeonicSupersonic** [comment]
Probably tooltip update bug related to quivers/talents as. Perhaps check actual attack timers in game to confirm/deny it?

**Comment by TheMoneyHater** [comment]
It's the quiver bonus that is not updated after a new equiped ranged weapon.

**Comment by bjh368** [comment]
Yeah its the quiver bug, and it is actual attack speed, not just tooltip.

Easiest self fix you can do is to move quiver to another bag slot, by dragging the equipped quiver onto another equipped bag. This way you don't have to relog or empty the quiver.

**Comment by z5n** [comment]
issue has since been fixed
