### ISSUE TITLE
Mining Veins

### ISSUE THREAD

**Issue by Quarthu** [SunstriderEmu/BugTracker#3962]
**Describe the bug**
Bugged rocks respown. In some locations there are none at all. I noticed that after a few H running around and digging the same rocks in their place instead of welding the same they will randomly weld from the list in this location. We have tin / iron / mithril / gold / silver in arathi. When I took all the iron in its place tin / gold / silver mithril welded. I didn't need these minerals so I didn't collect them just iron. It was a very late hour when I collected them and I was alone at the location. I noticed that other places of iron are respected and after a few minutes of hours I practically did not see iron in arathi at all. After traveling the map, I found 5 rocks. I decided to collect everything to check my thesis. And after I collected tin silver gold in their place iron also randomly welded. And in some places like Winterspring "Darkwhisper Gorge" where there should be a lot of thorium there was not a single 1. In my opinion there is a pool of rocks that are poorly balanced respawn. Let's take an example that there are 5 types of rocks out of which tin / iron / mithril / gold / silver should be 20% percentage because there are 5 of them that the maximum amount should be no more than 20%. Not random. Also it is very strange when in the Arathi Highlands where the level is 30-40 that 80% of the rocks were tin. So I have no idea how the percentage should be, but this is not the first server I play on TBC and only here I encountered such a problem with rocks.

**To Reproduce**

**Expected behavior**
It seems to me that it should be resolved as a percentage for a given land. But so that tin in arathi at 30-40 lvl would have 20% or gold. When everyone knows that tin is a mineral for low level lands. And gold is found in very small amounts. In my opinion this should be improved. Just like a lot of new rocks should be added. And their respown increased depending on the number of players per land. Because it can't be that there are 20 players in the land and the rocks appear with the same frequency.

**Screenshots/videos**
https://wowwiki.fandom.com/wiki/Darkwhisper_Gorge

"Notes of interest

    Despite the hazards, this area possessed several valuable resources, especially rich thorium veins. One could also find truesilver here. "

**Additional context**

**Comment by sevkav2000** [comment]
UP

**Comment by beraus** [comment]
If you can provide coords and/or screenshots/video that would help a lot.

**Comment by kelno** [comment]
Fixed since
