### ISSUE TITLE
pet behavior while mounted

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3963]
Firstly, pets should only run alongside their owners **when in arenas**. They should despawn when the warlock/hunter mounts in battlegrounds or the world.

Secondly, pets should only **run alongside** their owners when in arenas. They should be permanently set to passive follow, and should not run away, attacking and casting abilities, potentially getting despawned from distance. They also shouldn't slow down if in combat, but maintain the same speed unless snared.

**Comment by Jerrythemagicdog** [comment]
The second behaviour is already how it's worked, is there an issue about that?

**Comment by babno** [comment]
No, my pet will run away from me trying to attack people while I am mounted.

**Comment by artieau** [comment]
Can we get a video of this and further detail?
I've never seen this happen and tried numerous ways to reproduce it

**Comment by kelno** [comment]
Reworked those follow rules in https://github.com/kelno/sunstrider/commit/41da60dcf618689c59655580f5730bd0cc753bfb a while ago
