### ISSUE TITLE
Quests not working 

### ISSUE THREAD

**Issue by Thory1** [SunstriderEmu/BugTracker#3964]
Every attempted quest kill was not awarded to me nor a friend of mine. We tried in nagrand, bem, and ns.
Collecting q worked fine.

**Comment by beraus** [comment]
We need the name of a specific quest in order to test it. 
Also, your and your friend's in-game name would help.

**Comment by Thory1** [comment]
Hi,We tried a few, e.g. Gava'xi.Our names are Gwally and Berculli. Best regards Thory Am 19.07.2020 05:45 schrieb Bareus <notifications@github.com>:
We need the name of a specific quest in order to test it.
Also, your and your friend's in-game name would help.

**Comment by babno** [comment]
Were you in a party together? Any chance that party was actually a raid?

**Comment by Thory1** [comment]
Yes, we were in a party. I'm not sure, but it could be that we were in a raid. Thanks for the quick responses! Keep up the good work! Best regardsThory Am 20.07.2020 15:06 schrieb babno <notifications@github.com>:
Were you in a party together? Any chance that party was actually a raid?
