### ISSUE TITLE
I cant cap any banner in AV

### ISSUE THREAD

**Issue by Santiago744** [SunstriderEmu/BugTracker#3965]
**Describe the bug**

Since I joined the server I cannot cap any graveyard, banner or tower during the battleground Alterac Valley. I also cannot capture the banner in the cave for the Stormpike insignia quest. When I click on the banner it breaks and can even become unconquerable. I cannot click on the banner in the AV cave at all either. This problem has been persistent and does not go away when i re-log.

**To Reproduce**

Right click on banner --> banner breaks

https://classic.wowhead.com/quest=7162/proving-grounds
is affected by this 

**Expected behavior**

I except to be able to contest the banners, graveyards and towers.

**Screenshots/videos**

https://www.youtube.com/watch?v=zWZhIKFfvZE&feature=youtu.be

I made a crappy video showing the problem 

**Additional context**

as far as i can tell i might be the only person who has encountered this problem. not sure what went wrong.

**Comment by beraus** [comment]
Delete your cache for start and let us know if that helps.

**Comment by beraus** [comment]
Thanks, fixed with next update.

_Originally posted by @Jerrythemagicdog in https://github.com/SunstriderEmu/BugTracker/issues/4016#issuecomment-665743832_
