### ISSUE TITLE
Wanted: Rift Lords Daily Dungeon 

### ISSUE THREAD

**Issue by hismama** [SunstriderEmu/BugTracker#3966]
**Describe the bug**
Many Rift Lords that are killed within BM do not count towards the 4 total required. Typically only 3 are earned for an entire run even after killing 6 or 7.

**To Reproduce**
Any run of BM normal with the Wanted: Rift Lords quest.

Quest: https://www.wowhead.com/quest=11383/wanted-rift-lords

**Expected behavior**
The expected behavior is that every Rift Lord counts towards this total and it can usually be completed in a single run of BM. 

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update. We've also added the kill credit to Rift Keepers since sometimes you might get unlucky and not get the required amount of Rift Lords as they are interchangeable.
