### ISSUE TITLE
Eye of Magtheridon and Quagmirrin's eye trinket procs not working on shadow priest

### ISSUE THREAD

**Issue by Shadowweaver1** [SunstriderEmu/BugTracker#3967]
**Describe the bug**
On shadowpriest the Eye of Magtheridon and Quagmarrin's eye trinkets do not proc !

**To Reproduce**
1. cast anything untill the proc of Quagmarrins eye and cast Mind blast to verify if the haste is applied to the cast time (it is not)

2.  Cast rank 1 shadow word: pain to try and get a resist of the talent Shadow weaving. The resist of this debuff (80% hit with 4/5 talent points into shadow weaving) should proc the spell power proc. It does not work

Item: https://www.wowhead.com/item=27683/quagmirrans-eye&bonus=4105
item: https://www.wowhead.com/item=28789/eye-of-magtheridon

**Comment by kelno** [comment]
Thanks for reporting.
1. Tested now: Mind blast does proc it and the cast time is correctly affected.
2. Also seems to work, I can proc that trinket when resisting shadow word pain.

I'll close this for now, if you got some more evidence please re open another issue.
