### ISSUE TITLE
Windowed mode broke my client

### ISSUE THREAD

**Issue by ccarlzen** [SunstriderEmu/BugTracker#3970]
**Describe the bug**
I changed resolution to 1080p and that worked fine. Then I changed to window mode and the client is just a black screen with no cursor. When I alt-tab out of the client I briefly see the game as its closing. When I tab back in its completely black.  Now restarting the client is just a black screen and I can't get out of windowed mode to get it back

**To Reproduce**
I am running 2 monitors, not sure if that is effecting these results.  I am currently trying it with 1 monitor

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
"
f you're getting a black screen when swapping to windowed mode - it's a GAMMA issue. Open up config.wtf inside of your WTF folder and add these 2 lines:
SET gxWindow "1"
SET gxMaximize "1"
"

**Comment by ccarlzen** [comment]
Solved!  Thanks
