### ISSUE TITLE
Shaman Enh Spell Crit BIG issue

### ISSUE THREAD

**Issue by Harvel218** [SunstriderEmu/BugTracker#3971]
**Describe the bug**
 I have been testing spell crit procs for enh shaman, and spell crit value is MUCH less than it should be,
i had 4,2% spell crit chance, i attacked (screens) with 288 Flame wep procs, 25 Flame shocks, 26 Earth shocks = overall 339 spells, and i crit 3 times so its 0,88% spell crit chance, instead of 4,2 % 

**To Reproduce**
 Fight dummy with shocks + flametongue wep and watch recount... 
1. Cast earth and flame shocks ...
2.  Use flametongue wep enchants
3.  watch recount

**Expected behavior**
expected to spell crit work properly, thats all

**Screenshots/videos**
![WoWScrnShot_072020_213843](https://user-images.githubusercontent.com/59796176/87979458-64204200-cad2-11ea-9eca-5eb93c80f15e.jpg)
![WoWScrnShot_072020_213835](https://user-images.githubusercontent.com/59796176/87979478-697d8c80-cad2-11ea-8e62-a1e16e273281.jpg)
![WoWScrnShot_072020_213830](https://user-images.githubusercontent.com/59796176/87979486-6e424080-cad2-11ea-9be4-8bb4f1882692.jpg)

another try 455:
![WoWScrnShot_072020_220048](https://user-images.githubusercontent.com/59796176/87980891-9763d080-cad4-11ea-92a8-f9d3ca0e9a47.jpg)

**Comment by TheMoneyHater** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1530

**Comment by Harvel218** [comment]
@TheMoneyHater 

I understand, but in #1530, only MEELE hits are mentioned, not SPELL (as u know, flame procs are based on spell crit chance), and even if it work the same (but i dont think so becouse bosses deff values are not influencing spells?), it should be 1.8% lower (but with quick math, this should be around +/- 2.3% spell crit procs, but its lower than 1%...)

**Comment by kelno** [comment]
Thanks for reporting!

#1530 and the 1.8% are only about melee hits, so you can forget all that.
But Crit suppression also exists for spells and is currently set to 0.7% per level difference. 
This is consistent with the testing I did right now with 5000 earth shocks against a dummy, it's working as intended.

If you think that this value (0.7%) is incorrect you can open another issue specifically about this, though it's hard to find source about this.
