### ISSUE TITLE
Inappropriate Behaviour for Yellow Power Crystal (Container)

### ISSUE THREAD

**Issue by Ben-Millions** [SunstriderEmu/BugTracker#3972]
**Description**
There is a Yellow Power Crystal located at 72.95, 46.75 in Un Goro Crater that does not provide items when opened. It appears to fail to load the contents of the container.

**Steps To Reproduce**
1. go to 72.95, 46.75 in Un Goro Crater.
2. right click the Yellow Power Crystal.

unsure which container
container: https://classic.wowhead.com/object=164661/yellow-power-crystal
container: https://classic.wowhead.com/object=164781/yellow-power-crystal

**Expected behavior**
The container should open and provide 1-3 yellow power crystals.
item: https://classic.wowhead.com/item=11188/yellow-power-crystal

**Screenshots/videos**
Video is asking too much of a minor bug, if you have difficulty reproducing I'll just be happy that other people are not impacted by the bug.

**Comment by z5n** [comment]
unable to reproduce
