### ISSUE TITLE
Missing items!

### ISSUE THREAD

**Issue by wcz16** [SunstriderEmu/BugTracker#3973]
Two times now I have lost the same item (large prismatic shardx20) from my bank. I keep two slots open for them and both times I lost the item it was from the same bank slot. please please please recover my items they are very expensive.

**Comment by Jerrythemagicdog** [comment]
Need your character name, items don't just disappear.

**Comment by wcz16** [comment]
Waterwhippin is my char name. yes items have been disappearing our tank lost half his gear set after a talent relog. GM told me to relog and they would be in the mail. they were not. so i resubmitted a ticket and was told to post the bug here.
