### ISSUE TITLE
Mail BUG

### ISSUE THREAD

**Issue by zecke345** [SunstriderEmu/BugTracker#3974]
Suddenly i can't send items to my bankchar.

It says: you have reached the ingame cap of unique mail recipients"

... wtf.  also cant send from another char to a different one.  idk why this happens now, never accured

**Comment by Jerrythemagicdog** [comment]
Try making space on your bank alt's mailbox, maybe that's the issue and the message is wrong.

**Comment by zecke345** [comment]
it works again, the mailbox is often full, maybe it was the issue idk. ty
