### ISSUE TITLE
Hellfire Fortifications daily constantly breaking.

### ISSUE THREAD

**Issue by Oliiidee** [SunstriderEmu/BugTracker#3976]
On multiple occasions I have completed the hellfire fortifications daily in order to get 30 marks for my trinket. This has taken way too long causing me to give up on multiple occasions. After completion I go back to the quest giver which has a yellow question mark over there head as there should but when you talk to her it asks to come back when its complete. Iv tried abandoning it but then i cannot pick it up again. It should have taken only 10 days of dailies but its been months now as every time i try it seems to work for one day and then break on the following.

**Comment by Oliiidee** [comment]
https://www.wowhead.com/quest=10110/hellfire-fortifications

**Comment by beraus** [comment]
Include your in game name please.
Do you have [Forward Base: Reaver's Fall ](https://www.wowhead.com/quest=10124/forward-base-reavers-fall)completed?

**Comment by babno** [comment]
FYI you should get marks for every pvp kill you get while in the vicinity of the towers

**Comment by z5n** [comment]
unable to reproduce
