### ISSUE TITLE
Even Gronn have Standard bugged.

### ISSUE THREAD

**Issue by Iluvya1** [SunstriderEmu/BugTracker#3977]
ITEM DOESNT DROP
After u kill the mob, he doesnt dropp the item.

https://www.wowhead.com/quest=10997/even-gronn-have-standards#videos

We killed the Elite Son of Gruul and he just wont drop the item.

**Comment by Jerrythemagicdog** [comment]
He doesn't drop the item he summons a lootable game object behind himself on death.

**Comment by Iluvya1** [comment]
Yeah but the Mob doesnt do it - we  killed him and there was no Flag to loot :D

**Comment by Jerrythemagicdog** [comment]
Fixed with next restart.
