### ISSUE TITLE
Blue/Red Ogre Brew Special works outside of Blade`s Edge Plateau

### ISSUE THREAD

**Issue by dwarfkac** [SunstriderEmu/BugTracker#3978]
**Describe the bug**
As the title says - Potions which should work only in Blade`s Edge region tends to work outside. I happened to use mine in Skettis Veil Ala'rak area.
**To Reproduce**
Fly outside of Blade`s Edge Mountains and use the Blue/Red Ogre Brew Special.

Item: 
https://www.wowhead.com/item=32910/red-ogre-brew-special
https://www.wowhead.com/item=32909/blue-ogre-brew-special

**Expected behavior**
Shouldn't work outside of Blade's Edge.

**Screenshots/videos**
![bugsplat](https://user-images.githubusercontent.com/62179600/88065122-7d75cc80-cb6c-11ea-87b5-994b1a38da9b.jpg)

**Comment by z5n** [comment]
issue has since been fixed

**Comment by dwarfkac** [comment]
Actually. Im quite amazed, that you delivered this minor change after all these years. Props!
    On Sunday, June 4, 2023 at 11:51:44 PM GMT+2, z5n ***@***.***> wrote:  
 
 


fixed
