### ISSUE TITLE
Quest bugged cant turn

### ISSUE THREAD

**Issue by Guildesh** [SunstriderEmu/BugTracker#3979]
![image](https://user-images.githubusercontent.com/68246170/88067276-2c061700-cb45-11ea-94b5-e22ceca99d26.png)
Logged out and in
Turned addons off
Nothing happened

![image](https://user-images.githubusercontent.com/68246170/88067628-9e76f700-cb45-11ea-92b8-756b406183fd.png)
Same problem

I have tryed to left and get it again and now i can get the quests back -.- fix it too

**Comment by Guildesh** [comment]
I have tryed to left and get it again and now i can get the quests back -.- fix it too

**Comment by beraus** [comment]
What's your rep with Sporeggar?

**Comment by Guildesh** [comment]
> What's your rep with Sporeggar?

Friendly

**Comment by Guildesh** [comment]
????

**Comment by InhumanGM** [comment]
Your reputation with Sporeggar cannot be Friendly to accept/turn in this quest.
