### ISSUE TITLE
FlameWrath Polearm not scaling with spellpower

### ISSUE THREAD

**Issue by cummybloodrag** [SunstriderEmu/BugTracker#3980]
The Flamewrath polearm that drops from ambassador flamewrath in Blackrock Depths has a proc effect on hit that gives you a fire thorns shield. it is supposed to scale with spell power 1:1 at thihs time frame in the games life, as it did in vanilla. currently it does not scale with any spell power and hard capped at 10 fire dmg per tick of the thorns.

**Comment by TheMoneyHater** [comment]
Proof?

**Comment by cummybloodrag** [comment]
I will make a video tonight and send it in. Is this a valid email address to send the video to?

**Comment by Jerrythemagicdog** [comment]
Intentionally removed.
