### ISSUE TITLE
NO Puedo ingresar al server con Set logon.endless.gg . Se queda en autentificando

### ISSUE THREAD

**Issue by Gwplay** [SunstriderEmu/BugTracker#3982]
**Describe the bug**

Can not Enter to the server. maybe didnt work the Set logon.endless.gg
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment]
Estamos trabajando para resolver este problema. Únete a nuestro Discord para más información.
