### ISSUE TITLE
Stormstrike debuff

### ISSUE THREAD

**Issue by fredortukut** [SunstriderEmu/BugTracker#3983]
The debuff should increase nature proc dmg (like poisons) but not consume any charges on the debuff.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, need some proof to see it should work that way.

**Comment by fredortukut** [comment]
I think the only way to prove it is to test it in classic. Anyone playing classic who can do that?

**Comment by TheMoneyHater** [comment]
So ur saying that the 2stacks on the debuff should never be consumed by a nature damaged?

**Comment by fredortukut** [comment]
From direct spells (earth shock lightning bolt wrath) it should.

**Comment by TheMoneyHater** [comment]
So you mean the dot damage?

**Comment by fredortukut** [comment]
And poison or other on hit nature effects. It's pretty lame that two poison procs removes the debuff instantly and that's what blizzard thought too if I remember correctly.

**Comment by Jerrythemagicdog** [comment]
https://media.discordapp.net/attachments/708074383159328838/1134976935408173167/image.png?width=1152&height=204
