### ISSUE TITLE
priest talent reflective shield causes pushback

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3984]
I noticed it when I had dotted a priest and then tried to mount my felsteed after dropping combat. Obviously it's a huge issue for dot classes, for warlocks that can be up to 4 tics of pushback every 3 seconds.

**Comment by Jerrythemagicdog** [comment]
http://www.arenajunkies.com/topic/26184-priest-reflective-shield/?p=217518 (Two posts in here mentioning it does work)
http://www.wowhead.com/forums&topic=158400.1#p2115245 ( also still present in wotlk)
