### ISSUE TITLE
I'm not getting honor hold rep from killing orcs in normal hellfire ramparts or normal blood furnace

### ISSUE THREAD

**Issue by rossb-btw** [SunstriderEmu/BugTracker#3985]
username is VickVinegar

**Comment by Jerrythemagicdog** [comment]
That's probably because you're past the stage where normal dungeons give you rep on your level and rep standing.

**Comment by rossb-btw** [comment]
Then there’s another bug :)

In blood furnace normal, I was getting rep from killing the felguards and
felstalkers, but not from the orcs or imps
