### ISSUE TITLE
[Quest] Whelps of the Wyrmcult

### ISSUE THREAD

**Issue by Killko448** [SunstriderEmu/BugTracker#3986]
**Describe the bug**
With quest "Whelps of the Wyrmcult" you get a [Blackwhelp net]. Which on use gives error "You can never use that item" saying that i cannot equip that.

**To Reproduce**
1. In Blade's Edge Mountains get quest [Whelps of the Wyrmcult]
2. Use given net on supposed whelps to catch em.
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Delete Cache and try again, thanks.
