### ISSUE TITLE
REMOVE

### ISSUE THREAD

**Issue by TheMoneyHater** [SunstriderEmu/BugTracker#3987]
REMOVE

**Comment by mechanicsTBC** [comment]
Attack speed formula:
Attack_speed = "current attack speed" / (("Percent increase or decrease" / 100) + 1 )

Attack_speed = 2.0 / ( (30 / 100) + 1 ) = 1.5384
Attack_speed = 2.0 / ( (35 / 100) + 1 ) = 1.4814

https://wowwiki.fandom.com/wiki/Attack_speed
