### ISSUE TITLE
priest talent reflective shield causes pushback 

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3988]
I noticed it when I had dotted a priest and then tried to mount my felsteed after dropping combat. Obviously it's a huge issue for dot classes, for warlocks that can be up to 4 tics of pushback every 3 seconds. Same as #3984

@Jerrythemagicdog I see a trend from you. If you're going to try and close an issue citing extremely shitty research (or nothing), and then ignore me after I correct you on the closed issue, maybe you should wait before closing the issue?

The first link you provided is dead, and the second link doesn't mention pushback at all. And if you think for even half a bloody second, you would realize how obvious this is a bug. Because spells have travel time that means literally every spell cast would cast pushback. Every frostbolt, steady shot, mind flay. Channels are a big thing because they'd be cut in half at least!

**Comment by Jerrythemagicdog** [comment]
Provide proof that it's not supposed to cause push back, I've provided proof in the issue that it's supposed to. Link is dead but you can use an archive to access it.

**Comment by babno** [comment]
So provide an archive link?
![image](https://user-images.githubusercontent.com/244626/88394446-7974c500-cd8d-11ea-8941-b7fedf54c007.png)

You're asking me to prove a negative. I assert that every time a warlock casts fear 1g will be added to their inventory upon the next logout. Here's a link oginesvdnbfshkjbsdvhfjbnkjsnkjnbdvk.com it'll work if you put it in the right archive. If you disagree provide proof it's not supposed to happen.

https://www.google.com/search?q=reflective+shield+pushback+wow&oq=reflective+shield+pushback+wow&aqs=chrome..69i57j33.4710j1j7&sourceid=chrome&ie=UTF-8

I looked through 5 pages and didn't see any mention of reflective shield causing pushback.

**Comment by babno** [comment]
Cause I was bored

https://youtu.be/86ZCLm910uo?t=1646

You can see him take 4-5 instances of damage in a 3 second period while having 3 dots on himself and while he has bop on, meaning that at least 1-2 of those instances of damage must have been reflective shield, yet he takes no pushback on immolate.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
