### ISSUE TITLE
warrior spell reflection , not show damage reflected

### ISSUE THREAD

**Issue by 6yTblJIka** [SunstriderEmu/BugTracker#3990]
After reflect spells ,
does not show damage reflected.

Spell: https://tbcdb.com/?spell=23920

This is how it should work : https://www.youtube.com/watch?v=JbqGayDUeL0

This is how it works on our server : https://youtu.be/XSYxkLRYtw0?t=14

please FIX <3

**Comment by Jerrythemagicdog** [comment]
Fixed with next update, thanks.
https://github.com/kelno/sunstrider/commit/a28027b6f7f3c49c89ebd8fb800ce2b06bfe6152
