### ISSUE TITLE
Master of Elixirs Quest Broken

### ISSUE THREAD

**Issue by Stinklebum** [SunstriderEmu/BugTracker#3991]
**Describe the bug**
The Master of Elixirs quest is bugged and will not allow you to turn it in even though you have all of the items and it shows complete in your quest log. Attached are screen shots showing the quest log and my bag with the items

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

![image](https://user-images.githubusercontent.com/68700500/88303595-35be8480-ccd5-11ea-9390-c1559dd19742.png)
![image](https://user-images.githubusercontent.com/68700500/88304006-b0879f80-ccd5-11ea-890e-4a682163d815.png)

**Additional context**

**Comment by Stinklebum** [comment]
Here is the shot of the quest giver showing I can't turn it in.

![image](https://user-images.githubusercontent.com/68700500/88305034-0446b880-ccd7-11ea-849a-cd95dcf70c53.png)

**Comment by JCalavetta** [comment]
I have the same issue

**Comment by agvs95** [comment]
I have the same issue with master of potions

**Comment by Stinklebum** [comment]
Fix found, if you take the quest items and put them into your bank and put back into your bags right away, you will be able to turn in the quest.

**Comment by beraus** [comment]
Fixed some time ago.
