### ISSUE TITLE
Feral druid : Clearcasting makes finishing moves cost 100 energy instead of 0 // Edit : only ferocious bite is affected

### ISSUE THREAD

**Issue by lmstct** [SunstriderEmu/BugTracker#3992]
**Describe the bug**
When under the CLEARCASTING buff provided by the talent OMEN OF CLARITY, using a finishing move such as ferocious bite in cat form makes the spell cost 100 energy instead of 0.

**To Reproduce**

1. Have a clearcasting proc from omen of clarity in cat form
2. Use a finishing move (ferocious bite)
3. Lose 100 energy instead of 0

Spells : 
https://classic.wowhead.com/spell=16870/clearcasting
https://classic.wowhead.com/spell=22568/ferocious-bite
https://fr.classic.wowhead.com/spell=16864/augure-de-clart%C3%A9

**Expected behavior**
When under clearcasting, the spell should be free of any ressources instead of costing energy / rage / mana

**Comment by babno** [comment]
read the tooltip for ferocious bite very closely.
