### ISSUE TITLE
Master of potions

### ISSUE THREAD

**Issue by agvs95** [SunstriderEmu/BugTracker#3994]
Master of potions quest bugged, I tried to deliver it with all the items that requested to do it and couldn´t deliver it, I abandoned the quest and now the botanist´s field guide disappeared from my inventory and now I cant complete the quest... Please help to fix this and to get back the item so i can deliver it, its been 4 days to look for a group to do the botanica and this to happen is soo  discouraging I did it with my account agvs95, with Vacagandola.

**Comment by Stinklebum** [comment]
I just had this issue with the elixirs version, take the items for the quest, and put them in your bank. Take them right back out and you can turn it in immediately.

**Comment by agvs95** [comment]
the problem is that this has happened before to me in other quests, soo I just abandonded them and take the quest again and that worked before, but with this quest a did it all and my quest item that  found it in the botanica is gone! :/

**Comment by Stinklebum** [comment]
> the problem is that this has happened before to me in other quests, soo I just abandonded them and take the quest again and that worked before, but with this quest a did it all and my quest item that found it in the botanica is gone! :/

That's why you just put the quest items in your bank then pull them right back out. Its annoying but it works.

**Comment by agvs95** [comment]
I did it again the quest, and it worked thanks alot for the help man!
