### ISSUE TITLE
"Kormok" boss respawning in Scholomance

### ISSUE THREAD

**Issue by holymolyhm** [SunstriderEmu/BugTracker#3996]
Hello;
So basically there is a boss in Scholomance: "Kormok" , that respawns right after he gets killed, and basically what people are doing is that they're killing him again and again and sharding his gear.
horde AH is overwhelmed w/ shards from 2 guys that might be abusing the bug named: "Tutoyo", and "Kinggd".
need fix please.
Have a good day.

**Comment by Jerrythemagicdog** [comment]
Thanks, he's removed for now and his spawn time will be corrected with next update.
