### ISSUE TITLE
Slice and Dice increases attack speed by 20% instead of 30%

### ISSUE THREAD

**Issue by hanbi-wow** [SunstriderEmu/BugTracker#3997]
**Describe the bug**
Slice and Dice increases attack speed by 20% instead of 30%

**To Reproduce**
Cast rank 2 SnD on a target.
Rank 1 is 20%, but we have rank 2 (people in classic do too).
Tooltip (of the skill, not the buff) says it's 30% too.

**Source**
https://classic.wowhead.com/spell=6774/slice-and-dice
https://wowwiki.fandom.com/wiki/Slice_and_Dice

**Screenshots/videos**
https://imgur.com/a/W9Vl4Tn

You can see the screenshot shows a 20% increase (2.6/1.2 ≈ 2.17)
If it was 30%, it would be 2s exactly (2.6/1.3 = 2)

**Comment by blblblaz** [comment]
hello, i've tested it and rank 2 slice works correctly, gives 30% like it should, are you sure you are using rank 2 slice in your screenshot? are you sure you're using rank 2 slice in the screenshot? need more info if possible

**Comment by hanbi-wow** [comment]
> hello, i've tested it and rank 2 slice works correctly, gives 30% like it should, are you sure you are using rank 2 slice in your screenshot? need more info if possible

Can't really downrank Rogue abilities since they just overwrite the old ranks, but I just changed SnD bind to this macro: 

#showtooltip
/cast Slice and Dice(Rank 2)

Still 20%. Is this some weird client issue? Using the Endless client.

Disabled all addons, same thing.

**Comment by hanbi-wow** [comment]
It was related to me using it on low level mobs and it using rank 1 instead of rank 2, worked fine in PvP
