### ISSUE TITLE
Text in game not working past 14pt

### ISSUE THREAD

**Issue by Seampriest** [SunstriderEmu/BugTracker#3998]
All game text is not able to go past 14pt. The character select screen text and the zone introduction text in is size 12pt and is what I would think is abnormally small. Even when I try to change chatbox text size to 16pt or 18pt, nothing happens. The chatbox registers that I have selected 16pt for instance, but will remain 14pt. It's quite irritating, I've included photos.

In one of my addons, Miks Scrolling Combat Text, I have selected all of my fonts/text to be 30pt, but they are also stuck below the 14pt threshold. I just started playing on this server so I can't confirm if the game has always looked like this, it's only been a few days.  I have disabled all addons and still, same issue. Using the UI Scale slider in video options doesn't affect text size either. 

I'm not at all concerned with making my chatbox text larger, but I really would like my scrolling combat text and general game text to be larger.

Thanks for your time.

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/68761809/88445815-47964980-cdf3-11ea-9d48-85641ac3f124.png)
![image](https://user-images.githubusercontent.com/68761809/88445820-53820b80-cdf3-11ea-8f96-75d9342e2675.png)
![image](https://user-images.githubusercontent.com/68761809/88445822-5aa91980-cdf3-11ea-9bc5-aac0b3f05fed.png)
![image](https://user-images.githubusercontent.com/68761809/88445827-61379100-cdf3-11ea-9b79-0a4e5407fded.png)

^please note the text size only changing from 12pt and 14pt

Happy to add more images information. I have 0 addons enabled.

**Comment by Jerrythemagicdog** [comment]
That's a client issue, we can't help with that.
I don't really know what could be done here, perhaps try resizing the chat box and see if anything changes.
