### ISSUE TITLE
I CANNOT login to the server!

### ISSUE THREAD

**Issue by Chablo954** [SunstriderEmu/BugTracker#4000]
I am constantly getting stuck on "authenticating". I have cleared my cache, I have deleted my WTF folder, I have checked my realmlist. CAN ANYONE EXPLAIN THIS???????? This is the only server this is happening on.

**Comment by paukcovek** [comment]
i have connection issues also, but it's in form of random dc's, can any1 help us?

**Comment by Jerrythemagicdog** [comment]
Possibly region based, 99% of players are logging in without issues, sorry we probably can't help in this case.
