### ISSUE TITLE
 [Klaven's Tower]

### ISSUE THREAD

**Issue by Tocke123** [SunstriderEmu/BugTracker#4001]
Hi im trying to do the quest so i can get poisions for my rouge. After i have retrived Defias Tower Key, i don't get it in my bag, but it says on the quest i have 1/1 Defias Tower Key.
I stealth my way up to the top of the tower and the Duskwood chest is still locked. can you fix this bug please so i can continue the Klaven's Tower quest

**Comment by Jerrythemagicdog** [comment]
The key most likely went to your key ring not the bags, the chest appearing as locked can be a cache issue on your end, please clear Cache and try again.
