### ISSUE TITLE
Twilight set bugged

### ISSUE THREAD

**Issue by jediiiiiiiiiiiiiii** [SunstriderEmu/BugTracker#4003]
Hello, seems like wearing twilight 3 set in silithus doesn't give an aura buff and lesser stones are hitting with lightening even though the full set is equipped

**Comment by Mythogit** [comment]
Bump*, this stops people from obtaining the Dungeon 2 set

**Comment by Mythogit** [comment]
Cannot Summon the Templars from the Lesser Wind Stones, so the Abyssal Crest do not drop

**Comment by Mythogit** [comment]
https://wowwiki.fandom.com/wiki/Dungeon_Set_2

On the 3 Kings of Flame quest, can't complete

**Comment by Jerrythemagicdog** [comment]
Fixed a few days ago.
