### ISSUE TITLE
Shartuul's Transporter

### ISSUE THREAD

**Issue by D4emon** [SunstriderEmu/BugTracker#4004]
1.  When transitioning from the Doomguard Punisher to the Shivan Assassin it can happen that you dont switch to the Assassin and the Event ends (Maybe if you deal to much damage to her)
2. Shartuul knocked me up into the sky very high and evaded, after i landed and attacked him again the Event ended during the fight.

**Comment by Rettiy** [comment]
Sometimes also randomly ends in the middle of Felguard phase (the first one) - can't really tell why, just ends.
