### ISSUE TITLE
Lifebloom last tick heals through cyclone

### ISSUE THREAD

**Issue by stanyanev** [SunstriderEmu/BugTracker#4005]
Issue: When you have 2 stacks of lifebloom on yourself and you're cycloned you still get healed by the last tick.
How it should work: Cyclone should prevent all heals

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, broken recently, fixed with next update.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, broken recently, fixed with next update.
