### ISSUE TITLE
"Getting the Bladespire Tanked" quest

### ISSUE THREAD

**Issue by timelordricknmorty** [SunstriderEmu/BugTracker#4007]
**Describe the bug**
When using the quest item, an ogre will be attracted and pick up the beer mug as intended, but often quest credit will not be given.

**To Reproduce**
1. With the "Getting the Bladespire Tanked" quest, use Bloodmaul Brutebane Keg to attract an ogre from outside its aggro radius.

Item: https://www.wowhead.com/item=30353/bloodmaul-brutebane-keg
Quest: https://www.wowhead.com/quest=10512/getting-the-bladespire-tanked

**Expected behavior**
There should be credit for getting a "Bladespire ogre drunk" any time an ogre runs to the mug and takes a drink.

**Additional context**
This mechanic occasionally works, but not consistently enough to reliably complete the quest. The quest item has charges, and I ran out before I was able to complete the quest, despite actually getting 5 ogres drunk.

**Comment by Jerrythemagicdog** [comment]
Can't reproduce, there is a small cooldown on them getting drunk but they shouldn't come up to the keg in the first place.
