### ISSUE TITLE
Rescript zoning into fresh raid instance as a locked participant

### ISSUE THREAD

**Issue by Tasressurect** [SunstriderEmu/BugTracker#4008]
**Describe the bug**
I accidentally locked players to a saved raid ID as someone that joined another player's raid. I am not supposed to be able to do that, as it should instead prevent me from entering the raid leader's raid - as I am locked to a different ID. The zoning in mechanics are intended to be run this way.

**To Reproduce**

1. Fix zoning in script to prevent people who are locked to a different ID from zoning into a fresh raid ID, or a raid ID in progress.

**Expected behavior**
A raid-locked player should not be able to zone into a fresh ID, as the game's mechanics are intended to be solely based off the raid ID of the raid leader. Even if they have not zoned into the raid ID that they are the raid leader of, players locked to a different ID should be prevented from zoning into the raid portal.

**Comment by Jerrythemagicdog** [comment]
Which instance was that?
