### ISSUE TITLE
HUnter pet bug

### ISSUE THREAD

**Issue by avazaki1** [SunstriderEmu/BugTracker#4010]
**Describe the bug**
 ****When i Dismiss pet with full hp and after iI call pet bach his hp is not full anymore and I need to heal everytime i call pet**** 

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Can't reproduce, need details here.

**Comment by artieau** [comment]
Working correctly anyway. If the extra HP is from some item/set bonus it applies after the summon anyway
