### ISSUE TITLE
Hearts of the Pure (succubs quest): Dalin´s heart cant be acquired

### ISSUE THREAD

**Issue by ruteyute** [SunstriderEmu/BugTracker#4011]
As the title states im unable to get one the required quest items due to it showing as already acquired even though it´s nowhere to be found in my inventory.

The item in question is Dalin´s heart dropped off Dalin in Silverpine Forest.

I´ve tried to abandon the quest and redo it 3 times at this point to no avail.

[Heats of the Pure screenshot.pdf](https://github.com/SunstriderEmu/BugTracker/files/4981460/Heats.of.the.Pure.screenshot.pdf)

**Comment by Jerrythemagicdog** [comment]
I've just checked, you have the item in your bank.
