### ISSUE TITLE
logged out in ssc, logged in dead.

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4012]
i logged out as my paladin in ssc and switced to warlock (diff account).  We killed vash 2 pulls later (thu eu evening).  I logged the pal's account on 2-3 days later saw that it was in ssc, remembered i had flask running and cancelled my login (by pressing esc) without entering game.  I logged in 1 days after (4 days since i logged out in ssc) mon (eu evening) and was dead at the char select (its possible i am misremembering this part, maybe i wasnt dead at character select and just logged in deadat the spriit healer in zangar pvp area just south of ssc).  I was able to ressurect by running into ssc.

doesn't seem correct.  if we were in combat when i logged out, i should've known it as everyone in the raid would've been in combat when the first person entered combat.  when i logged in 3 days later, i was not a ghost at character select.  i don't understand how/why i ended up dead 1 day later.  

some sort of reset?  arbitrary death for being in dungeon 4 straight days?  glitch where logging to char select causes some in game action?  paladin was in for 5/6, then logged out before first vash pull, maybe some sort of invisible debuff on it from morrogrim or ftl?  some debuff vash does to everyone in the raid/targetted (even if they are logged off?)

**Comment by Jerrythemagicdog** [comment]
Probably kicked out of the raid group / raid group dissolved and removing your character from the instance.

**Comment by michaelkittrell** [comment]
you auto die when removed from raid instance while logged out?

**Comment by Jerrythemagicdog** [comment]
Probably moved to the graveyard, hard to tell what exactly happened since it's so spread out over a few days.

**Comment by michaelkittrell** [comment]
i logged out in hyjal, while i was offline they disbanded the raid and reformed.  i logged in dead again.

not a huge deal i guess, but not sure why we dont just tp out of the instance... or tp to the graveyard... instead of to graveyard dead.  maybe to keep you from keeping some random instance specific buff?

**Comment by kelno** [comment]
I'll close this one, hard to work on something with this data.
