### ISSUE TITLE
Quest "Cuergo's Treasure Map"

### ISSUE THREAD

**Issue by Kassarix** [SunstriderEmu/BugTracker#4013]
So I am pretty sure that this quest should be repeatable if you combine the 3 map fragments again and do it but currently it isn't repeatable in the game. I made a ticket and got a mail that says that I should report here.  Obviously this quest is not a game breaker or anything but still something that I found.

**Comment by Sheikthecatman** [comment]
Thanks! Fixed in [1e892c56054346db9941d63b07c32adede1fa05f](https://github.com/kelno/sunstrider-scripts/commit/1e892c56054346db9941d63b07c32adede1fa05f)!
The fix will be live next restart

**Comment by Kassarix** [comment]
Nice! that was pretty quick.

**Comment by LSD7** [comment]
yeah, im waiting fix for https://github.com/SunstriderEmu/BugTracker/issues/3477 since may
