### ISSUE TITLE
[Paladin][Talent] Applying Vindication to a target should be considered an offensive spell

### ISSUE THREAD

**Issue by ZophosTheSavage** [SunstriderEmu/BugTracker#4014]
Vindication does not grant the caster mana when applied to a target under the effect of Judgement of Wisdom.
It should be considered an offensive spell and therefore trigger Judgement of Wisdom and 'Chance on spell hit' effects of trinkets such as Mark of Vindication and 'Each time you land a harmful spell' of Darkmoon Card : Crusade.
Described bug results in significantly lower mana regeneration of Retribution paladins as well as decreased value of Darkmoon Card : Crusade.

**To Reproduce**
1. Attack a target under the effect of Judgement of Wisdom.

Talent : https://db.endless.gg/?spell=26021
Aura : https://db.endless.gg/?spell=26018#triggered-by

**Expected behavior**
When a melee swing occurs and Vindication is applied to a target under the effect of Judgement of Wisdom it should be possible to get two mana gains one for the melee swing and one for the application of Vindication aura considered separate from the swing that triggered it. This is also true for raid bosses who are immune to the effect of the aura.

**Screenshots/videos**
You can see that the video speed is x 1.0 looking at the swing timer addon and the lenght of the video since Brutallus has an enrage timer. Multiple 'double procs' occur in this video.
https://www.youtube.com/watch?v=UyooXkH6mT8

A forum post from 2008.
https://imgur.com/zNcZlaf

Current behavior on Sunstrider. During that test 0 out of 20 procs returned mana.
https://imgur.com/CAWAAYN

**Additional context**
Different server bug tracker discussion - proven this was a bug - however most of the links are outdated.
https://github.com/ccshiro/cc-buglist/issues/2247

Various mentions of this that I've digged up on some webarchived forums.

**tarja, 11/14/07, 12:53 PM - elitistjerks.com**
Last night in the first night of raiding since the 2.3 patch, I could've sworn that I was proccing JoW far more than normal. My combat log would often have 2 or 3 lines in a row of "You gain 74 mana...". It seemed to me like JoW was proccing off the "immune to vindication" combat result (where vindication procs a TON).

**Sorry, 01/05/08, 3:52 PM - elitistjerks.com**
I only have 2 old WWS-Reports to look at from ZA, one with 2/3 Vindication and one without, I specced out of it to reach BoK and didn't think the debuff was much useful.

Melee+SoC+CS+JoC hits, not counting Consecration:
For example on Narolakk,
with Vindication: 108 hits, 152 JoW procs
without Vindication: 126 hits, 93 JoW procs

Akil'zon:
with Vindication: 111 hits, 148 JoW procs
without Vindication: 115 hits, 84 JoW procs

**Galick, 02/04/08, 1:03 PM - elitistjerks.com**
In regards to the mana issue, I've found that since I started putting one point into vindication, mana problems are a thing of the past

**Ufalah, 2008-11-04, 05:33 PM - mmo-champion.com**
Put one point into vindication as a PvE-ret paladin because procs of Vindication, even if the boss is immune, have a chance to proc JoW.

This is my 2nd report of this bug. I have reported this before on May 30th but the bug remains unfixed. I think I've provided ample evidence this time and I wouldn't want anyone to link the previous reports of Vindication not working properly with Grounding totems etc. using videos from 2017 from an unknown server. Tyvm.

**Comment by ZophosTheSavage** [comment]
**frmorrison, 01/03/08, 6:34 PM - elitistjerks.com**
Something I did not see listed, is Vindication (spell hit based) if it procs on a boss even though immune, can proc JoW and the Darkmoon Card: Crusade

**Comment by Rettiy** [comment]
#1713 #1714

**Comment by ZophosTheSavage** [comment]
> #1713 #1714

I specifically asked not to link those reports. You are using videos posted in 2017 from an unknown source. Please don't mix it with my 2007 / 2008 retail sources for the sake of all the paladins on this server. Thanks.

**Comment by Jerrythemagicdog** [comment]
Thanks for all the sources here guys, we've done some testing after a fix and after the update:
- You can get double proc of JoW by applying Vindication and for example auto swinging
- You gain buff stacks on your Darkmoon Card: Crusade from Vindication
- Vindication triggers Mark of Vindication

The fix will be live probably this Friday (31.07) please re-test then and let us know if there are any issues left with this exact mechanic (https://github.com/SunstriderEmu/BugTracker/issues/1713 unchanged right now)

**Comment by Rettiy** [comment]
Procs the regen Meta so it's probably working, can't be too hard to do that with the Jugement renewal now then.

**Comment by Jerrythemagicdog** [comment]
Fixed
