### ISSUE TITLE
Proving Grounds AV quest

### ISSUE THREAD

**Issue by Mofolele** [SunstriderEmu/BugTracker#4016]
Proving Grounds Alterac Valley Quest
So you pick up the quest outside of AV the quests sends you inside AV to go retrieve the stormpike banner in a cave. So when you go and click the banner to pick it up an error message occurs "this item is already being used".

**To Reproduce**
1.Pick up Proving Grounds quest from Lieutenant Haggerdin.
2.Go inside the Icewing Caverns located southwest of Dun Baldar inside of Alterac Valley.
3.Walk to the end of the cave and there will be a stormpike banner that is clickable.
4.Get the error message and wont be able to complete the quest.

Item: https://classic.wowhead.com/item=17849/stormpike-banner
Quest: https://classic.wowhead.com/quest=7162/proving-grounds
NPC: https://classic.wowhead.com/npc=13841/lieutenant-haggerdin

**Expected behavior**
I expected to go inside and get the quest item but i kept getting the error message even after restarting the game and clearing the Cache folder.

**Screenshots/videos**
https://imgur.com/a/jHWzqqw

**Additional context**
I need the trinket for my resistance set for SSC would appreciate if you guys would fix this bug.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
