### ISSUE TITLE
Quest broken: True believers

### ISSUE THREAD

**Issue by Randalierer** [SunstriderEmu/BugTracker#4017]
**Describe the bug**

After completing the quest you recieve a letter from the Quest-NPC Ortell. There should be an item attached called "Decoded True Believer Clippings" but there isnt. The letter is empty.

Quest: https://classic.wowhead.com/quest=8323/true-believers
Item needed: https://classic.wowhead.com/item=20404/encrypted-twilight-text
Quest Reward: https://classic.wowhead.com/item=20469/decoded-true-believer-clippings

**Comment by z5n** [comment]
Fixed in [6cf8e38ec088797971aa87e092f7aca42a8c5292](https://github.com/kelno/sunstrider/commit/6cf8e38ec088797971aa87e092f7aca42a8c5292)
