### ISSUE TITLE
Warlock supression quest ~ Doomguard pet quest

### ISSUE THREAD

**Issue by loweri** [SunstriderEmu/BugTracker#4018]
**Describe the bug**

**To Reproduce**

1. Cast Glowing Crystal prision on Doomguard commander
2. Stop casting immediatly 
3. Nothing happens

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2105
