### ISSUE TITLE
Investigate the Alchemist Shop mage's quest undercity

### ISSUE THREAD

**Issue by qwezxcrr** [SunstriderEmu/BugTracker#4021]
**Describe the bug**
scroll doesn't summon minion

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2825
