### ISSUE TITLE
dalaran protector

### ISSUE THREAD

**Issue by qwezxcrr** [SunstriderEmu/BugTracker#4022]
**Describe the bug**

dalaran protector should summon 1hp snake but its more then 400hp
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.
