### ISSUE TITLE
login unavailable

### ISSUE THREAD

**Issue by Ekspoo** [SunstriderEmu/BugTracker#4023]
Hello, help please, I can not enter the game - login unavailable (Werewolff1994)

![image](https://user-images.githubusercontent.com/68948579/88792735-648c9d00-d1a4-11ea-96e9-ba54880e1917.png)
![image](https://user-images.githubusercontent.com/68948579/88792817-87b74c80-d1a4-11ea-9aa2-25545b073b2b.png)

**Comment by Jerrythemagicdog** [comment]
You are IP banned for selling third party gold.

**Comment by Ekspoo** [comment]
1. This is definitely some kind of mistake, since I did not do anything like that
2. As far as I know now, everyone has dynamic IP
