### ISSUE TITLE
tk, alar, p2 doesn't fly up sometimes

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4025]
sometimes in p2, alar will get stuck and not fly up (for 60+ seconds of pretty free dps).  usually happens pretty late into the fight and i believe only/always after it charges someone (late into his cycle, like the last charge before he flys up).  looks like he gets stuck and just stops trying to move.  

im not sure but i think one of the times he also stopped doing melt armor during this.  he still autos but its just a tank and spank when it bugs out.

**Comment by kelno** [comment]
Thanks, do you have that on video by chance?

**Comment by michaelkittrell** [comment]
sorry, i don't record.

**Comment by Jerrythemagicdog** [comment]
Thanks, we've found one potential cause, most likely fixed with next update.
