### ISSUE TITLE
Killing Blows in BGs

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#4026]
Honorable kills in BGs are granted no matter how far you are from the actual kill. For example a kill at Vann in AV still grants honor to people at Drek. The outcome is +1 honor to literally every player in AV. Same probably applies to other BGs.

This might be related to the instance-wide loot distributions which were implemented lately.

Some downsides are:
- 1v1 kills in BG are of no value to the player who actually killed the opponent, everything is shared
- leads to distortion of "Lifetime kills", especially by playing AV you can get big amounts since you benefit from every kill

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with cc53fde886a4b5d7c85cc367356736d7a1b2ad76

**Comment by kelno** [comment]
https://github.com/kelno/sunstrider/commit/cc53fde886a4b5d7c85cc367356736d7a1b2ad76
