### ISSUE TITLE
Shapeshift forms should override other transforms.

### ISSUE THREAD

**Issue by bugged-tech** [SunstriderEmu/BugTracker#4028]
(sorry for my english)
So, when u using Noggenforger elixir, or Savory Deviate Delight and u enter Bear, Cat or another form character entering form, but looks still like a Elixir or Savory effect (i mean character no changing visual form)

And when im using Noggenforger Elixir i can't mount.
Its also impossible to use Flight Master

**Comment by beraus** [comment]
I'm not sure about all of those, but I remember that you can use Noggenfoger -> savory deviate delight -> mount -> cancel savory deviate delight and you'll keep noggenfoger while on a mount

**Comment by bugged-tech** [comment]
yeah, but  they could repair that coz its bugged

**Comment by Jerrythemagicdog** [comment]
The steps beraus described are consistent with how it worked on retail, the rest of the report is valid.

**Comment by bugged-tech** [comment]
26 days ago, still not working...

**Comment by bugged-tech** [comment]
26 days later still not working like should...

**Comment by hufsa** [comment]
Fixed
