### ISSUE TITLE
Rare(blue) Recipes/Formulas drop rate.

### ISSUE THREAD

**Issue by nadezdakuchko** [SunstriderEmu/BugTracker#4029]
For some rare(blue) recipes/formulas drop rate after lasts updates too high. Looks like now it have ~20% drop rate.

1. Schematic: Mana Potion Injector. Got x4 after killing aroun 15 Wrath Hounds. Same for Schematic: Healing Potion Injector from Wrath Speaker.
2. Last 4 Karazhan runs: 2 of 4 Formula: Enchant Weapon - Soulfrost, 3 of 4 Formula: Enchant Weapon - Sunfire.

Item: https://db.endless.gg/?item=23883 Source: https://db.endless.gg/?npc=22195
Item: https://db.endless.gg/?item=23884 Source: https://db.endless.gg/?npc=20557
Item: https://db.endless.gg/?item=22560 Source: https://db.endless.gg/?npc=16524
Item: https://db.endless.gg/?item=22561 Source: https://db.endless.gg/?npc=15688

It should be rare drop(less then 1%), not common.

**Comment by Jerrythemagicdog** [comment]
Buffed intentionally, but thanks for the report.
