### ISSUE TITLE
Demons dont keep their buffs when mounting up. 

### ISSUE THREAD

**Issue by Anderstegnel** [SunstriderEmu/BugTracker#4031]
**Describe the bug**

The demons dont keep their buffs Stamina intelelct etc when you mounted up
**To Reproduce**

1. Do a warlock, Summon a demon buff it with anything like fortitude or intellect or something.
2.  Mount up. and then dismount, BAM buffs are gone, I think this is also the issue for Demonic knowledge it dont "update"
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Anderstegnel** [comment]
Just make so the demon dont disapear when people mount.... same issue with the demonic knowledge talent its because the pet resets and does not update its stats while getting buffed.. come on for the warlock community on here..

**Comment by TheMoneyHater** [comment]
This is really big for pvp and should be fixed :)

**Comment by hufsa** [comment]
Issue regarding Demonic Knowledge was fixed recently.

**Comment by z5n** [comment]
issue has since been fixed
