### ISSUE TITLE
Crystal Yield

### ISSUE THREAD

**Issue by Chertenok62** [SunstriderEmu/BugTracker#4033]
Crystal Yield doesn't work. Сannot be used

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, was removed intentionally.

**Comment by Chertenok62** [comment]
And it was impossible to delete this quest? I spent 4 hours on the farm of these items, and then it turns out that you specifically disabled it. I would have earned 2-3 thousand gold during this time.
