### ISSUE TITLE
Hunter:  "Improved Stings"(MM Talent) doesnt work on "Wyvern Sting"

### ISSUE THREAD

**Issue by Hmk6** [SunstriderEmu/BugTracker#4035]
Tittle

I have been testing it on different mobs and players, Wyvern Sting does his base dmg after the wakeup, the talent doesnt affect it at all... only Serpent Sting and Viper Sting works please fix

**Comment by hufsa** [comment]
Affect data seems correct

**Comment by kelno** [comment]
Thanks!
Fixed with next server update
