### ISSUE TITLE
mob feared into air, unlootable on death

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#4036]
![image](https://user-images.githubusercontent.com/244626/89042323-b81df880-d314-11ea-9ddd-8cfb3aa5fdeb.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, any reproduce steps for fearing them into the air?

**Comment by babno** [comment]
it's the mob from the spellcloth cooldown, so don't know if this will reproduce the error (4 day cooldown) but I made a spellcloth by the area 52 flightmaster, mob spawned, I feared, it went to that location and stayed there as I attacked and killed it.

**Comment by Jerrythemagicdog** [comment]
Thanks, should be fixed with latest changes.
