### ISSUE TITLE
"Eye of Magtheridon" not proccing on "Seal of Vengeance" debuff apply resists

### ISSUE THREAD

**Issue by GigilPiq** [SunstriderEmu/BugTracker#4037]
**Describe the bug**

"Eye of Magtheridon" does not proc when "Seal of Vengeance" is used and resisted when trying to apply the "Holy Vengeance" (DoT) debuff. The bug might apply to other DoT skill aswell ?

**To Reproduce**
1. Equip Eye of Magtheridon.
2. Cast Seal of Vengeance.
3. Hit a target, get resisted when trying to apply the "Holy Vengeance" (DoT) debuff.
4. Be sad.

Top Right corner, change lang. to french.

Item:
[Eye of Magtheridon](https://www.thegeekcrusade-serveur.com/db/?item=28789) 
Spells: 
[Seal of Vengeance](https://www.thegeekcrusade-serveur.com/db/?spell=31801)
[Holy Vengeance ](https://www.thegeekcrusade-serveur.com/db/?spell=31803)

**Expected behavior**

The "Recurring Power" buff from the "Eye of Magtheridon" should proc on these resist.

**Screenshots/videos**

![Proff_EOM](https://user-images.githubusercontent.com/59665141/89047380-9e010c00-d34e-11ea-8a3d-15bd6384efcf.png)

**Additional context**

It might extend to other spells as seen in this issue https://github.com/SunstriderEmu/BugTracker/issues/1555

**Comment by GigilPiq** [comment]
Bump ? Anyone can confirm this or add his part ?

**Comment by Jerrythemagicdog** [comment]
Seal of Vengeance has an attribute preventing it from procing anything, would like to see some proof that the proc is indeed supposed to happen.
