### ISSUE TITLE
Darkmantle Proc Rate became too low.

### ISSUE THREAD

**Issue by someguy113** [SunstriderEmu/BugTracker#4038]
**Describe the bug**
The Darkmantle vanilla set energy proc [https://tbc-twinhead.twinstar.cz/?spell=27788](url) has become too low after updates on 30th july 2020. 
2 days ago (29.08.2020.) i got almost 50% of total energy gained from Darkmantle proc. But now its only 2 or 3 times in 5 minutes fight.
**To Reproduce**

1. Wear 4 pieces of [https://tbc-twinhead.twinstar.cz/?item=22003](url) set.
2. Load your Recount Addon.
3. Fight the training dummy as long as possible.
4. Check the "Energy gained" tab in your Recount.

**Expected behavior**
Not expected but verified many times on many tbc servers including Endless. Proc rate was pretty high until recently.

**Comment by fileegg** [comment]
Thats true, proc rate got nerfed like 1000%

**Comment by Jerrythemagicdog** [comment]
https://classic.wowhead.com/spell=27787/rogue-armor-energize#comments

Is the proc rate not consistent with the information here?

**Comment by fileegg** [comment]
It’s extremely low right now

**Comment by someguy113** [comment]
It have not a fixed proc rate. Just random proc on hit. even based on a 5% proc chance it must be way more than 1 PPM because the rogues doing about 81 swings per minute only with SND buf maybe 5 of this amount of swings are miss/dodge. Let's not forget that finishing moves like rupture/eviscerate/expose armor/Envenom are also a "swings", besides Garrote/Gouge/Sinister strike/mutilate( 2 swings)/Shiv etc are also a "swings" and can trigger any proc. Let's not forget AGAIN that the raid buffs like Bloodlust/Drums of Battle/Windfury and Combat Potency talent/Mongoose/DST procs give you additional "swings". 
So it can't be 1 PPM as it now is! Fix it please. Thank you in advance!

**Comment by someguy113** [comment]
> https://classic.wowhead.com/spell=27787/rogue-armor-energize#comments
> 
> Is the proc rate not consistent with the information here?

Ofc its consistent with this part of discussion: 
     "From ThottbotBy Octang on 2006/05/30 (Patch 1.10.2) |This has to be my favorite Set bonus for SC and Darkmantle. It procs a lot during pve battles."

**Comment by someguy113** [comment]
I want to add some approximate calculations.
![Д2 удары](https://user-images.githubusercontent.com/53577683/89416220-974f0c00-d735-11ea-8be9-806721fc0899.png)
![Проки енергии в д2](https://user-images.githubusercontent.com/53577683/89414979-eb58f100-d733-11ea-9bce-46f833a797fe.png)

Melee              - 998-89-43=866
Sinister Strike  - 242-6=236
Extra Attack    - 52-1=51
Sum                - 866+236+51=1153

Energy procs    - 1295/35=37

37*100/1153=3.2%
This is the result without taking finishing moves into account. (Expose Armor/Rupture)
Fight duration 12.5 minutes.
37/12.5=2.96 PPM

Endless results

**Comment by someguy113** [comment]
Warmane Results:
![warmane D2 swings](https://user-images.githubusercontent.com/53577683/89418812-3c1f1880-d739-11ea-9673-04cfd671a13e.png)
![warmane D2 energy](https://user-images.githubusercontent.com/53577683/89418820-3fb29f80-d739-11ea-81dc-598302dfeea5.png)

Melee              - 1001-78-11=912
Sinister Strike  - 262-2=260
Extra Attack     - 75-6-4=65
Sum                 - 912+260+65=1237

Energy Procs     - 3570/35=102

102*100/1237=8.3%
Fight duration 7.5 minutes.
102/7.5=13.6 PPM

**Comment by someguy113** [comment]
Netherwing results

![image](https://user-images.githubusercontent.com/53577683/89424979-15fd7680-d741-11ea-835d-6e8e57233a89.png)
![image](https://user-images.githubusercontent.com/53577683/89425167-53fa9a80-d741-11ea-9d5c-6f458748215d.png)
![Rupture extra attack proc](https://user-images.githubusercontent.com/53577683/89426537-f23b3000-d742-11ea-9b76-06d60a6fca68.png)

Melee           - 1005-12-7-5=981
Sinister Strike - 281-4-3=274
Eviscerate      - 19
Extra Attack    - 32+15+2+2-1-2=48
Sum             - 981+274+19+48=1322

Energy procs    - 3325/35=95

95*100/1322=7.2%
Fight duration is unknown because there are no Target Dummies. So i had to fight a trivial mobs in Terrokar Forest.
I have every reason to believe that this could affect the number of procs so here is the results excluding everything except melee hits.
1322-19-274=1029
95*100/1029=9.2%

P.S. I'm not sure should i exclude finishing moves because it can trigger the sword specialization procs (extra attack). But i called it "an approximate calculations" so everyone decides for himself whether it is important or not.
