### ISSUE TITLE
Hints of a New Plague

### ISSUE THREAD

**Issue by wing32s** [SunstriderEmu/BugTracker#4039]
**Describe the bug**
Killed the courier but the document item does not drop.

**To Reproduce**

1. Kill the courier
2. Mob has no loot
3. 

Item: https://wowhead.com?item=
Quest: https://classic.wowhead.com/quest=658/hints-of-a-new-plague
Spell: https://wowhead.com?spell=

**Expected behavior**
The mob should drop something that can be turned in

**Screenshots/videos**

![hintsofanewplague](https://user-images.githubusercontent.com/69062761/89090415-cc8fde80-d370-11ea-834c-3e94b077d2c1.png)

**Additional context**

**Comment by Jerrythemagicdog** [comment]
You need to kill the entire formation, they're currently loot linked.
