### ISSUE TITLE
[Quest] [A Mission of Mercy] - Cannot be Started - Can't Farm Ethereum Prison Key for Rep

### ISSUE THREAD

**Issue by ChuckFerrera** [SunstriderEmu/BugTracker#4040]
**Description:** After gaining Honored reputation with Consortium, I should be able to start the quest line [A Mission of Mercy] by either speaking with NPC Commander Ameer directly or accepting quest [Seek Out Ameer] from NPC Protectorate Advisor Rahim. I am 8,000 reputation through Honored, and am not able to obtain these quests. As an aside, I have completed the quest line for [The Ethereum] all the way through [Dimensius The All-Devouring]. This has resulted in me not being able to farm Ethereum Prison Keys, thus farming reputation for The Consortium. Furthermore, if I were to have already completed [A Mission of Mercy], I would be able to complete the follow on quest [Ethereum Secrets] and be able to complete the daily to turn in Ethereum Prisoner I.D. Tags, which I am also unable to do as seen in the discussion when speaking with Commander Ameer.

**To Reproduce**

1. Gain Honored Reputation with The Consortium.
2. Quest is not available.

Quest - [A Mission of Mercy]: https://tbcdb.com/?quest=10970
Quest - [Seek Out Ameer]: https://tbcdb.com/?quest=10969
Quest - [The Ethereum]: https://tbcdb.com/?quest=10339
Quest - [Dimensius The All-Devouring]: https://tbcdb.com/?quest=10439
Quest - [Ethereum Secrets]: https://tbcdb.com/?quest=10971
NPC - [Commander Ameer]: https://tbcdb.com/?npc=20448
NPC - [Protectorate Advisor Rahim]: https://tbcdb.com/?npc=22899
Item - [Ethereum Prison Key]: https://tbcdb.com/?item=29460

**Expected behavior:** After gaining Honored reputation, this quest should be available to me.

**Screenshots**

![World Of Warcraft Screenshot 2020 07 31 - 22 25 52 47](https://user-images.githubusercontent.com/65261502/89092115-dae3f780-d37c-11ea-9bf0-365f25f1c2e6.png)
![World Of Warcraft Screenshot 2020 07 31 - 22 22 35 25](https://user-images.githubusercontent.com/65261502/89092117-df101500-d37c-11ea-93c7-6de6a4438adc.png)

**Comment by FoxyLOVEyou** [comment]
I have the same problem!
All conditions have been met, the reputation is Revered. Throughout the location, absolutely all the quests with the Consortium were done. Starting from the fields, ending with all places where there is at least one NPC consortium in this location. I need this quest to get the keys. The NPC simply does not provide any 1 quest. Only it doesn't work for me. Quest names — "The mission of Mercy"
All my guildmates did the same and everything works for them.
P.S. I deleted the cache, it still does not work.

**Comment by ChuckFerrera** [comment]
@FoxyLOVEyou, I thought I would be the only one!! It is so odd. I have completed all consortium quests as well.

**Comment by Jerrythemagicdog** [comment]
Thanks for the report.
For some reason the quest "Seek out Ameer" (10969) was not labelled as a breadcrumb quest for "A Mission of Mercy" (10970)
while at the same time the quest starter data was missing from Protectorate Advisor Rahim which essentially made picking up this quest and the next quest impossible.
Fixed with next update.

**Comment by Jerrythemagicdog** [comment]
https://github.com/kelno/sunstrider-scripts/commit/7e09b8537cda8a37394f79a7c61d09c5ccdffe00

**Comment by ChuckFerrera** [comment]
Awesome. Thank you @Jerrythemagicdog!!!!
