### ISSUE TITLE
Blizzard not proccing Winter's Chill talent

### ISSUE THREAD

**Issue by Socloseagain** [SunstriderEmu/BugTracker#4042]
**Describe the bug**
Using Blizzard(a mage spell) is not proccing the Winter's Chill talent(mage talent).

**To Reproduce**

1. Cast blizzard onto a target and see that the target does NOT get ANY Winter's Chill debuffs ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://tbc-twinhead.twinstar.cz/?spell=10

**Expected behavior**
When you cast Blizzard(a mage spell) onto a target, and you have the talent Winter's Chill(mage talent) your target should start to get Winter's Chill debuffs with each tic of damage that he gets. 

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Working as intended.

**Comment by Socloseagain** [comment]
> Working as intended.
Please take a look here I made a video about it: https://streamable.com/ym7iu4 
First I opened my talents for you to see I have 5/5 Winter's Chill which gives u 100% chances on any frost damage to proc that talent. And as you can see the first ENTIRE channel of the Blizzard spell didn't give a SINGLE debuff there. Only at the end of the second channel Winter's Chill started proccing. I've just tested it on Smolderforge and there every single tick procs the Winter's Chill.

**Comment by Rettiy** [comment]
He means Working as intended as in **Blizzard should not proc Winter's Chill**.

**Comment by Socloseagain** [comment]
> He means Working as intended as in **Blizzard should not proc Winter's Chill**.

Huh? But you can clearly see that it DOES proc it from the video. The problem is that it sometimes doesn't proc when it should proc on every tick from blizzard, since it's a frost damage spell. Winter's Chill states the following: "Gives your frost damage spells a 100% chance to apply the Winter's Chill effect.."
