### ISSUE TITLE
[Quest] Arcatraz Sentinels

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#4043]
The Normal daily quest "Wanted: Arcatraz Sentinels" gives you credit on Heroic only if they don't die by their own explosion. If you for example HoJ them and they have no chance to explode (suicide), you get credit. Otherwise you don't.

**Comment by Rettiy** [comment]
#4002 might be related

**Comment by Jerrythemagicdog** [comment]
Thanks for the details, was helpful.
Fixed with next update.
