### ISSUE TITLE
Area 52 guards

### ISSUE THREAD

**Issue by metallicant** [SunstriderEmu/BugTracker#4045]
The guards at Area 52, i.e. Area 52 Bruiser, Area 52 Big Bruiser, Netherstorm Agent, Area 52 Death Machine...
They don't intervene in players' PvP actions. Similar issue #2135 was closed some time ago, stating that this problem should be fixed. Well, it's not. People abuse this bug to their advantage. A human mage, nickname Lianchhiari, was killing horde players all day long. He/She was choosing "special" places (like right at the Area 52 Bruiser location) to do this thing.

**Comment by Sheikthecatman** [comment]
Thanks! Some changes and additions have been made to Area 52 to smoothen your experience in [39bec10f37cf12a515db131e35dbd046a5b3915b](https://github.com/kelno/sunstrider-scripts/commit/39bec10f37cf12a515db131e35dbd046a5b3915b).
Changes will be live next restart.
