### ISSUE TITLE
[Quest] [A Mission of Mercy] - admins help us!

### ISSUE THREAD

**Issue by FoxyLOVEyou** [SunstriderEmu/BugTracker#4047]
The quest for the NPC does not work for me - Commander Ameer. He doesn't give me the quest to open prisons. (Ethereum Prisons Keys).

All conditions have been met, the reputation is Revered. Throughout the location, absolutely all the quests with the Consortium were done. Starting from the fields, ending with all places where there is at least one NPC consortium in this location. I need this quest to get the keys. The NPC simply does not provide any 1 quest. Only it doesn't work for me. Quest names — "The mission of Mercy"
All my guildmates did the same and everything works for them.
P.S. I deleted the cache, it still does not work.

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/4040
