### ISSUE TITLE
Windfury does not have ICD.

### ISSUE THREAD

**Issue by Malem217** [SunstriderEmu/BugTracker#4049]
**Describe the bug**
Windfury should have an internal cool down timer naturally,

**To Reproduce**
Create shaman, use windfury on both weapons when dual wielding. Watch the procs per minute skyrocket compared to any other realm.

**Expected behavior**
Windfury should have an internal cd of 5 seconds.

**Comment by Jerrythemagicdog** [comment]
It does have an internal cooldown.

**Comment by Malem217** [comment]
Thats utter BS and you know it, every enhance i come across procs WF every swing on me. Whether its main hand resetting offhand ICD or vice versa something is going on here.

**Comment by TheMoneyHater** [comment]
It have a cd

**Comment by SabreValkyrn** [comment]
>It does have an internal cooldown.

Should #1228 be closed then?
