### ISSUE TITLE
Karazhan ID : 5528 Loot Attument

### ISSUE THREAD

**Issue by Centuri0n123** [SunstriderEmu/BugTracker#4050]
**Describe the bug**
<can´t loot boss item-->

**To Reproduce**
<!-I died and released the spirit after boss died and I can´t loot the item from attument the huntsman -->

Item: https://wowhead.com?item= [Gauntlets of Renewed Hope]
https://www.wowhead.com/item=28505/gauntlets-of-renewed-hope

**Expected behavior**

**Screenshots/videos**

**Comment by Jerrythemagicdog** [comment]
You need to be present for the boss kill in order to receive loot, if you release before the boss dies you won't be eligible. We've tested this extensively before and there weren't any issues.
