### ISSUE TITLE
didn't receive gears after I bought the 70 instant bundle

### ISSUE THREAD

**Issue by francisltx** [SunstriderEmu/BugTracker#4052]
**Describe the bug**
didn't receive gears after I bought the 70 instant bundle. Character name is imhater.

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Resolved ingame.
