### ISSUE TITLE
Dire Maul dungeon closed

### ISSUE THREAD

**Issue by Meyvan** [SunstriderEmu/BugTracker#4053]
**Describe the bug**
When  i try to enter the instance, it says that the minimum level required is 71 which is impossible for this extension.

**Affected quests **
https://classic.wowhead.com/quest=8948/anthions-old-friend
https://classic.wowhead.com/quest=8949/falrins-vendetta
https://classic.wowhead.com/quest=8950/the-instigators-enchantment

**Additional context**
This 3 quests are required to finish the darkmantle set.

I would like to know when the instance we'll be back again and if you have planned solutions for the players who need to finish quest inside , Good luck .

**Comment by Jerrythemagicdog** [comment]
Yes, open with next update.
