### ISSUE TITLE
 Reset my Paladin quests

### ISSUE THREAD

**Issue by Bengouse** [SunstriderEmu/BugTracker#4055]
Hello I have been playing on your server for a few days and I have a problem with the Paladins quest and I wanted to know if it was possible to reset the quests so that I can get redemption please. My paladin's name is Guldir. Thank you .

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, can you be more specific?
What is the issue exactly, which quest are you on, how does the problem manifest itself?

**Comment by Bengouse** [comment]
J'ai fais une erreur avec la quête (Tome de divinité) qui me permet d'obtenir la rédemption et quand je retourne voir le pnj qui donne la quête j'ai rien, du coup je veux savoir si ces possible de réinitialiser la quête. Merci

**Comment by kansler13** [comment]
Здравствуйте, у меня такая же проблема с этим квестом Фолиант божественности на получения искупление. Можете помочь. Заранее спасибо.

**Comment by kansler13** [comment]
Hello I have been playing on your server for a few days and I have a problem with the Paladins quest and I wanted to know if it was possible to reset the quests so that I can get redemption please. My paladin's name is Kansler. Thank you .

**Comment by kansler13** [comment]
I made a mistake with the quest (Tome of Divinity) which allows me to get redemption and when I go back to PNJ gives the quest I have nothing, suddenly I want to know if it is possible to reset the quest

**Comment by hufsa** [comment]
Seems to be related to Tome of Divinity which has been fixed recently. Closing this.
