### ISSUE TITLE
Darkmoon Card: Crusade and Seal of Blood

### ISSUE THREAD

**Issue by Blayst** [SunstriderEmu/BugTracker#4056]
**Describe the bug**

Seal of Blood is not proccing the melee effect of Darkmoon Card: Crusade. Seal of Command; however, is working as intended. 
When you hit a target with Seal of Blood up the melee attack and the Seal damage should each apply a separate stack of Darkmoon Card: Crusade. When you judge with SoB it applies the melee stack (intended). When you use SoC both the white hit and the SoC proc will apply the melee stack, same with the judgement (intended). The only portion that isnt working as intended is the SoB weapon attack not applying the stack. 

**To Reproduce**

1. Cast Seal of Blood on yourself
2. Attack target
3. Only one application is occurring (from the melee hit)
4. Judgement applies the attack power proc though (working as intended)

SoB: https://db.endless.gg/?spell=31892
Crusade Card: https://db.endless.gg/?item=31856

**Expected behavior**

SoB should be applying a melee stack of Darkmoon Card: Crusade similar to Seal of Command. 

**Screenshots/videos**

Video of using BOTH Seal of Blood and Seal of Command and showing the difference. (please disregard the dodges and misses i'm not perfect) 

https://www.youtube.com/watch?v=dfirdAJizO0

**Comment by Rettiy** [comment]
Can you provide some source for SoB? I am not questioning it, just wondering.

Also #1713 is related. Every refresh of judgement should be a "harmful" spell. So even if using Blood purely, you would be stacked on both all the time.

**Comment by Blayst** [comment]
I do not have an earlier source for SoB. Also i'm ok with judgement stacking both :)

**Comment by Blayst** [comment]
I do think that Judgement proccing the spell damage portion of the trinket was something that happened in 2.1 and 2.0, I'm not 100% certain but Judgement may have switched when they made ret more relevant.

**Comment by Jerrythemagicdog** [comment]
SoB does not proc any other procs that some other Seals do so I'd really like to see some source for that.

**Comment by Blayst** [comment]
Jerry I'd really like to see your source for saying SoB does not proc any other procs that some other Seals do because qute frankly thats bullshit. SoB goes off Melee mechanics. The idea of me trying to find a video from 2008 to show Darkmoon Card: Crusade stacking is hilarious. 

"This seal is counted as a second melee strike in terms of game mechanics, meaning that the damage it deals can miss, be dodged, be blocked, and be parried. "

https://wowwiki.fandom.com/wiki/Seal_of_Blood 


This is as much "evidence" as I can find, there are no 2008-2009 videos with a horde ret paladin using Seal of Blood and Darkmoon Card: Crusade.

**Comment by Jerrythemagicdog** [comment]
The proof we have is the spell having an attribute when it was made by Blizzard that's preventing it from triggering item spells.
Other spells in that category are: Sap, Gouge, Seal of Righteousness, Scatter Shot.  
Attributes given to spells by Blizzard are correct ~99% of the time, we rely on them to ensure spells work as intended.
We've also looked into this extensively when putting together our seal twisting implementation.
