### ISSUE TITLE
Aspect of the Cheetah - Daze incorrectly being procced by DoTs on application & on damage.

### ISSUE THREAD

**Issue by Skuzzlez** [SunstriderEmu/BugTracker#4058]
As the title suggests, DoT effects are incorrectly causing Daze to proc from Aspect of the Cheetah, both upon application and on individual ticks. Only direct damage (i.e. attacks, direct damaging spells, wands) should cause daze. DoTs should not cause daze under any circumstances:

Aspect of the Cheetah:
> The hunter takes on the aspects of a cheetah, increasing movement speed by 30%. If the hunter is struck, <he/she> will be dazed for 4 seconds. Only one Aspect can be active at a time.

https://wowwiki.fandom.com/wiki/Patch_1.9.0
> Aspect of the Pack and Aspect of the Cheetah - Periodic damage will no longer trigger the Dazed effect.

**Comment by Jerrythemagicdog** [comment]
Lazy Classic proof: https://youtu.be/sndrfr0DVc0?t=601

**Comment by Jerrythemagicdog** [comment]
Fixed with next update.
