### ISSUE TITLE
Darkmoon faire ticket hand-in bug

### ISSUE THREAD

**Issue by Slamminn** [SunstriderEmu/BugTracker#4061]
**Describe the bug**
Very simple bug. I was handing in dense grinding stones to get darkmoon prize tickets. After completely roughly 5-7 hand-ins, the quest is no-longer available, however the blue question mark is still above the quest-givers head. This quest is meant to be repeatable infinitely (unlike some of the others which disappear upon higher reputation). 

Link: https://classic.wowhead.com/quest=7939/more-dense-grinding-stones#comments
(as of 1.9 you do not need the blacksmith profession to hand these in just in case your wondering)

Plz fix 👍 

Cheers
Slammin

**Comment by Jerrythemagicdog** [comment]
Fixed with next update, thanks.
