### ISSUE TITLE
Unbridled wrath warrior talent

### ISSUE THREAD

**Issue by metallicant** [SunstriderEmu/BugTracker#4062]
**Describe the bug**
The warrior talent "unbridled wrath" procs incorrectly, i.e.:
-) at rank 5 with a 3.6 speed weapon it adds 1 extra rage for every melee white swing that deals damage, i.e. 100% chance.
-) it does not proc from such abilities as heroic strike and cleave

**To Reproduce**
I tested it on a boss dummy with a 3.6 speed weapon:
-) at rank 1 talent: it generated 20 rage out of 131 successful white melee swings, i.e. about 15.26% proc chance (should be 18%)
-) at rank 5 talent: it generated 147 rage out of 147 successful white melee swings, i.e. 100% proc chance (should be 90%)
-) tried to hit not only with white attacks, but with heroic strike and cleave abilities as well. The talent did not proc from these two abilities at all.
-) I also tried a 1.6 weapon at rank 5: 150 successful white swings, 75 rage generated, i.e. 50% proc chance (should be 40%).

**Expected behavior**
This talent should be reconsidered in two ways:
-) its proc chance at all ranks and all weapon speeds (spreadsheet attached)
-) it should also proc from the abilities that are bound to melee swing time, i.e.: heroic strike and cleave abilities (moreover, if cleave successfully hits more than 1 target, then it should have separate proc chance per target, i.e. generate 2 rage).
[Unbridled wrath.xlsx](https://github.com/SunstriderEmu/BugTracker/files/5020487/Unbridled.wrath.xlsx)

**Additional context**
The talent chance to proc depends on the rank and the weapon speed. The slower the weapon and higher the rank, the higher the proc chance. In other words, the ranks 1, 2, 3, 4 and 5 should have 3, 6, 9, 12 and 15 procs per minute respectively. Below is two links with a detailed spreadsheet for each rank and some "popular" weapon speed. 

sources: 
https://wowwiki.fandom.com/wiki/Unbridled_Wrath_(old)
https://wow.gamepedia.com/Unbridled_Wrath_(warrior_talent)

Since wowwiki and gamepedia does not have all proc chance information (on all possible weapon speed, but only popular ones), I also attach a full spreadsheet with all the data (based on the information about the quantity of PPM from these websites).

**Comment by Jerrythemagicdog** [comment]
Thanks for the sources!

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
