### ISSUE TITLE
Gnomish Net-O Matic Projector bugged

### ISSUE THREAD

**Issue by becike84** [SunstriderEmu/BugTracker#4063]
Hello There!

Just created the trinket to my char, and tested it in duel.

It should be "sometimes" backfire as the tooltip says, what is like 10% on engi stuff.

But from 10 duels, backfired 8 times and rooted my warrior. My warrior didn't get Second Wind proc from it, when got immobilized from the trinket backfire.  2 of 10 tryes applied the net on the target..  Chances should be reversed.

Pls check it out and the second wind effect too.

thanks,

**Comment by becike84** [comment]
And whenever i log in with my warrior "Shyguy"  i got net o matic 10 second root on my instanly after logging in, even when my trinket is in the bank.. :D someone joking me? cmon :D

**Comment by Jerrythemagicdog** [comment]
Seems to be working with a chance to backfire.
