### ISSUE TITLE
Multi-Shot Cone Angle & Secondary AOE radius incorrect

### ISSUE THREAD

**Issue by Skuzzlez** [SunstriderEmu/BugTracker#4064]
On Endless, the cone angle of multi-shot seems to be too small, meaning it can be difficult to hit multiple targets. Similarly, the secondary AOE radius of the additional projectiles from Multi-Shot seems to be too small. 

Here are a couple Classic videos showing how multi-shot should function:

Angle: https://www.youtube.com/watch?v=RsRkN30HpDE
The cone looks like it has a 180 degree angle.

Radius: https://www.youtube.com/watch?v=zPGJ7pm77eE

Additionally, it was reported in another report but secondary projectiles from Multi-shot do not currently go through pillars as they used to back in retail / do on classic. This seems to be a result of the custom changes on Endless and i'm not sure if it's intended. However as argued in the other thread: "If this is somewhat the result of a custom change, it is inconsistent that Channeled Spells like Arcane-Missiles or Drain Life wouldn't be affected in the same way." Could this also be clarified?

**Comment by Jerrythemagicdog** [comment]
Multi-Shot is a ranged chain ability, it can chain to targets through LoS.

**Comment by Skuzzlez** [comment]
> Multi-Shot is a ranged chain ability, it can chain to targets through LoS.
It might be a side effect of the low AoE radius then, but it doesn't seem to do this currently on Endless. In other TBC environments it's pretty easy to hit an entire team around a pillar hugging with multi-shot. I've yet to see this happen on Endless.

**Comment by bluemanguy112** [comment]
Clearly this was changed on purpose as it was working properly on the PTR, before it has been falsely reported as bug by the following clip:

https://www.twitch.tv/scopemeup/clip/SpeedyPlausibleCardImGlitch?filter=clips&range=all&sort=time

**Comment by artieau** [comment]
Working correctly.

**Comment by bluemanguy112** [comment]
NOT WORKING, stop closing these. Tested 15.09.
