### ISSUE TITLE
Hitting evade to NPC in prowler mode using Pounce.

### ISSUE THREAD

**Issue by bagojan9898** [SunstriderEmu/BugTracker#4065]
It happens frequently whenever i'm stealthed in cat form and attempt to hit an npc with Pounce skill that right when im about to hit them with it they see me in stealth and my hit goes as 'Evade' and then they strike me out of stealth then i no longer hit evade.

I don't think that them seeing me in stealth should make my hit go evade even though my hit was before theirs.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, could you provide some examples of creatures?

**Comment by bagojan9898** [comment]
I think it they were the aggro mobs at un goro. The flying pterrodax  npc's
and the ground ones that look like dino/ crocodiles. As i play more i will
let you know if other mobs do the same. I'll keep you guys updated.

**Comment by bagojan9898** [comment]
Just had the same bug again with an npc named Twilight Avenger at silithus
Twilight base camp.

**Comment by bagojan9898** [comment]
illidari taskmaster evaded my Ravaage from stealth as well. I think it's a
general bug and not tied to a specific mob.

**Comment by z5n** [comment]
issue has since been fixed!
