### ISSUE TITLE
Very low drop rate for Linen cloth

### ISSUE THREAD

**Issue by royuchiha** [SunstriderEmu/BugTracker#4067]
Linen cloth is one of the starter level cloth that is dropped by every humanoid from level 1-15, however during my levelling experience i have seen this cloth to be never dropped really. It never drops from most of the humanoids and the drop rate is around 5% which shouldnt be the case as this is a low level cloth. Have played in other servers too but never really had an issue with linen cloth drop.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3833
