### ISSUE TITLE
Mage Quest Investigate the Blue Recluse bugged

### ISSUE THREAD

**Issue by nixae** [SunstriderEmu/BugTracker#4069]
**Describe the bug**
After summoning and defeating a rift spawn it goes into the stunned state. When attempting to use the chest of containment coffers on it. It states "i cant do that yet". Possibly relevant, when speaking to the quest giver they can not say my character name and instead say $n

**To Reproduce**
follow the questline Investigate the blue recluse.

Item: https://wowhead.com?item=
Quest: https://classic.wowhead.com/quest=1920/investigate-the-blue-recluse
Spell: https://wowhead.com?spell=

**Expected behavior**
After summoning and defeating a rift spawn it goes into the stunned state. Then you use the chest of containment coffers which throws a trap on the ground. The trap catches the rift spawn and the player collects it

**Comment by beraus** [comment]
Thanks, duplicate https://github.com/SunstriderEmu/BugTracker/issues/1907
