### ISSUE TITLE
Infinity Respawning at Gnomeregan

### ISSUE THREAD

**Issue by ConFuh** [SunstriderEmu/BugTracker#4070]
I was farming at gnomeregan and when stoped to kill all mobs  some mobs keeps spawning before of Electrocutioner

**To Reproduce**

1. Go In main entrance and pull all the mobs
2. Before of Electrocutioner kill them

Mobs- Leprous Defender and Leprous assistance

**Expected behavior**

**Screenshots/videos**

**Additional context**
idk if is a bug o just mechanic but they keep spawning and droping loot

**Comment by Sheikthecatman** [comment]
Are the respawning creatures specific or is it just a general issue in the instance? I'm unable to reproduce the respawning and their respawn timers are all correct.

Could you provide a video or more context to where exactly it happens, what exact creature you can reproduce it with or just a video of the whole thing?

**Comment by ConFuh** [comment]
Specific creature, Ill try it to make a short video

**Comment by ConFuh** [comment]
https://youtu.be/E4vLL8sdYWQ
Some i noticed this time
the spawning mobs are coming from mobile system alerts, 
if i dont kill them, they will keep spawning mobs
some i forgot to mention is
if i go at the main entrance and pull all the system alarm,
and try to go out from workshop entrance they will spawning mobs

**Comment by Sheikthecatman** [comment]
The issue are the [Mobile Alert System](https://db.endless.gg/?npc=7849) that keep respawning mobs as they alert them, they now only summon 3 and then attack you directly!

Fix will be live next server restart.
