### ISSUE TITLE
Items from mailbox disappear after collecting them

### ISSUE THREAD

**Issue by Dancemypoles** [SunstriderEmu/BugTracker#4076]
**Describe the bug**
After spending 21gold on the AH to buy 6 stacks of Netherweave cloth, I went to the mailbox to collect it, after opening the the mail and clicking on it for it to go to inventory, it instead just disappeared. This happen to all 6 stacks of Netherweave cloth.

Receiving mail from a friend, I again, opened the mail which happened to be cloth, and it too disappeared, nowhere to be found.

The same friend tried to trade me Potions during ZF, again, the items disappeared.

**To Reproduce**
1. I dont really want to try to reproduce the fault as it ends up with me losing gold / items.

Item: https://wowhead.com?item=21877/netherweave-cloth

**Expected behavior**
I was expecting to receive the stacks of Netherweave cloth into my inventory

**Screenshots/videos**
NIL

**Additional context**
NIL

**Comment by Jerrythemagicdog** [comment]
What's your character's name?

**Comment by Dancemypoles** [comment]
Dancemypoles

**Comment by kmayberry91** [comment]
I have noticed similar behavior when using any type of Auction House addons on this server. Try disabling them and repurchasing the item from AH to see if the problem persists.
