### ISSUE TITLE
"Fragmented Magic" Quest; not funktioning properly.

### ISSUE THREAD

**Issue by patmanpost** [SunstriderEmu/BugTracker#4077]
1. I accept the quest at the NPC, the NPC hands out the item (Prismatic Shell).
2. The quests Objection to Polymorph the Naga in order to kill the polymorph clones can not be completed due to the spawning of the Polymorph clones despawning "instantly". There is no chance to kill the Polymorphed clones.

This quest is only to be obtained by mages.

**Comment by Sheikthecatman** [comment]
Thanks! The issue has been fixed in [8a76da6087888b9e7def0d8ca208d26955c62aaf](https://github.com/kelno/sunstrider-scripts/commit/8a76da6087888b9e7def0d8ca208d26955c62aaf).

The fix will be live next restart.
