### ISSUE TITLE
Priest Tier 5 2 set not working

### ISSUE THREAD

**Issue by Truefaxlol** [SunstriderEmu/BugTracker#4079]
**Describe the bug**
<!- Avatar Regalia for shadow priest specialization 2 set bonus does has not worked. -->

**Expected behavior**

**Comment by Jerrythemagicdog** [comment]
The proc worked, it was just proccing "on hit" instead of "on cast" which lead it to be consumed instantly by the same spell that it procced from.
Fixed with next update.
