### ISSUE TITLE
Warlock t5 4 piece does not work

### ISSUE THREAD

**Issue by Balanarr** [SunstriderEmu/BugTracker#4081]
**Describe the bug**
Warlock t5 4 piece does not work

**To Reproduce**
1. Equip 4 pieces of corruptor raiment
2.  Put Corruption on the target, cast a few shadow bolt and observe the tick damage for corruption.
3.  Put Immolate on the target, cast a few incinerates and observe the tick damage for immolate
Remaining ticks of corruption / immolate are unaffected and deal the same damage.

**Expected behavior**
Each time a shadow bolt hits and there is an active corruption on the target, the remaining ticks deal 10% more damage.
Each time an incinerate hits and there is an active immolate on the target, the remaining ticks deal 10% more damage.

**Comment by blblblaz** [comment]
thanks for the report

**Comment by hufsa** [comment]
Thanks, fixed with next update.
