### ISSUE TITLE
tk, kt infinity blade 12 attacks in 2.43 seconds...

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4082]
today in raid got thrashed by KT infinity blades at 2.43, 1.4, 1.07, .03   that is 4 thrashes in 2.43 seconds for 12 attacks (4 thrashes x2 attacks each, + 4 melees).  

I'm not sure whats going on here, seems excessive?  parry haste and just got super unlucky that every attack also triggered a thrash?  

![kt weaps thrash](https://user-images.githubusercontent.com/5479930/89830898-d4d6df00-db11-11ea-8b17-9eeb3f6aaf18.png)

**Comment by Jerrythemagicdog** [comment]
Seems like it, very unlikely otherwise.
