### ISSUE TITLE
[Hyjal] Chain heal bounces on NPC

### ISSUE THREAD

**Issue by Xsh74500** [SunstriderEmu/BugTracker#4083]
**Describe the bug**
Chain heal boumce to every NPC in Hyjal, even if raid member are half HP.
Chain heal Bounce on Elemental (considered as NPC)
![image](https://user-images.githubusercontent.com/69485218/89833720-cdd7bd00-db61-11ea-9b14-587bf84e9660.png)

**To Reproduce**
Group on a raid and head to Hyjal
Chain heal the Main tank, and see it bounce mainly to NPC even if raid member are half HP

**Expected behavior**
Chain heal should not bounce to friendly npcs. If you cast chain heal on friendly npc, it should bounce back to party/raid member. (keep in mind that chain heal should still bounce to pets)

**Screenshots/videos**
https://youtu.be/bo6yLMBwybU?t=2m9s
(All npcs died few seconds later. They were most demaged unit, but chain heal didnt bounce to them)

https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/137808-guide-resto-shaman.html

"Therefore, chain heal will not bounce to Elementals if you first target a raid member for healing. However, if you first target an Elemental, chain heal will bounce to members of the raid"

**Comment by kelno** [comment]
Fixed with next server update
