### ISSUE TITLE
Vengeful Gladiator's Right Ripper AP cost is too high

### ISSUE THREAD

**Issue by hanbi-wow** [SunstriderEmu/BugTracker#4085]
**Describe the bug**
Vengeful Gladiator's Right Ripper costs 3150 Arena Points.
All the other melee One-Hands at 2.6s speed cost 2625 Arena Points.
The Fist OH is correctly priced at 1125 like the other off-hands.

Vengeful Gladiator's Right Ripper https://tbc-twinhead.twinstar.cz/?item=33737

**Expected behavior**
The Fist is MH-only so its cost gets lumped in with the Spell Caster Mainhands (which cost 3150), even though it should have the same cost as the melee onehands (2625).

**Screenshots/videos**
![Cost](https://i.imgur.com/esScPoo.png) 

**Additional context**
Wiki: https://wowwiki.fandom.com/wiki/Season_3_Arena_rewards#Price_history

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
If you still see the wrong price after that please clear your Cache.
