### ISSUE TITLE
Ranged attacks missing despite Hit Cap - Night Elf Racial bugged?

### ISSUE THREAD

**Issue by Skuzzlez** [SunstriderEmu/BugTracker#4088]
**Describe the bug**
Silencing Shot is capable of missing targets despite the hunter being PvP hit capped:
https://imgur.com/ikA1ZSE

I checked the druid's gear to make sure he's not using any funky items that reduce chance to be hit or silenced and he/she isn't.

**To Reproduce**
1. Cast Silencing Shot repeatedly on a class that doesn't have extra chance to be missed (i.e. resto druid like in the above example)

**Expected behavior**
I would expect that Silencing Shot would not be able to miss with the physical hit cap. Is silencing shot using Spell Hit cap instead of Phys hit cap? I always thought that it used/should use the Physical hit cap since it was a projectile.

Update: Just heard that apparently night elf racial either correctly or incorrectly affects ranged attacks, so this might be the culprit? I always thought it was simply melee dodge as opposed to chance to be missed however.

Update 2:

TBC Quickness:
https://tbc-twinhead.twinstar.cz/?spell=20582
Dodge chance increased by 1%.

WotLK Quickness: 
https://wotlk-twinhead.twinstar.cz/?spell=20582
Reduces the chance that melee and ranged attackers will hit you by 2%.
--

It seems that the NE racial might be using WotLK values rather than just the 1% dodge it grants in TBC?

It might be worth investigating other racials to see if they're using WotLK values too as this may explain why misses seem quite prevalent on this server (a lot of resistance passives were changed to 2% miss in WotLK).

**Comment by blblblaz** [comment]
according to the screenshot it seems like you had insect swarm on you, that's the only explanation I have right now

**Comment by Skuzzlez** [comment]
Ah thanks for checking this, I'm dumb it seems. You can close it i guess!
