### ISSUE TITLE
[#10] Mobs under water part1

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#409]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Thursday Dec 06, 2018 at 11:42 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/10_

----

Current behaviour: Mobs are porting up and down when moving through a body of water

Expected behaviour: Mobs should be swimming through the water

Steps to reproduce the problem:
Agro an NPC when under the water
Watch as it approaches you from the sky

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Sunday Dec 09, 2018 at 10:07 GMT_

----

For that kind of report, please include the creature id as well as the location
The location can fetched with `.gps`

**Comment by plutonium447** [comment]
Jumping out of water while in combat with a mob in the water will cause it to leave combat
Swimming up above the mob will cause its animations to "flip" between pointing vertically towards the player and reseting to its normal horizontal idle animation.
im playing around with the umbrafen eels in zangarmarsh @ 71.9, 64.9.
seem pretty fucky

**Comment by artieau** [comment]
Similar to above @kelno however this was a very older version of core.
Was mobs in Durotar off the coast of Sen'jin Village

**Comment by kelno** [comment]
Fixed with 10822

**Comment by Jerrythemagicdog** [comment]
Mobs seem to be able to swim in the air when above water maybe related to the issue below: 
https://gfycat.com/MelodicAmbitiousArthropods
