### ISSUE TITLE
[Item] Hand of Justice

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#4090]
**Describe the bug**
Hand of Justice never procs the extra 1 melee attack(chance on hit 2%?) https://classic.wowhead.com/spell=15600/hand-of-justice

Item: https://wowhead.com?item=11815
Spell: https://wowhead.com?spell=15600

**Expected behavior**

Procs should happen at 2% chance both main hand and offhand, and melee abilities... There is no Internal CD.

**Screenshots/videos**

![image](https://user-images.githubusercontent.com/45275285/90057088-1f389700-dc9d-11ea-9bfa-302c312018cc.png)

**Additional context**
Tested w/ daggers as I was sword spec talented and wanted a good test. Double checked combat logs to the best of my manual ability over 5 minutes~ and could not see any procs either.

**Comment by Jerrythemagicdog** [comment]
1000 attacks: 
![image](https://user-images.githubusercontent.com/46463908/90061938-c7228480-dcde-11ea-9960-fcdfed90963b.png)

Please use bigger sample sizes if you're trying to confirm something as small as 1%.

**Comment by kmayberry91** [comment]
Yeah okay, it was a 6 min parse and I was trying to be funny. Thanks

**Comment by kmayberry91** [comment]
I guess its diminishing returns on a level 60 item vs a boss lvl ?? dummy. It doesn't work AT ALL.
![image](https://user-images.githubusercontent.com/45275285/90071904-a85ac880-dcb3-11ea-81f1-25914d2cd4b9.png)

**Comment by kmayberry91** [comment]
Cant get thru Bar Door without Grim Guzzler Key that Plugger Spazzring did not drop now too.
