### ISSUE TITLE
Can't continue the Black Temple attunement

### ISSUE THREAD

**Issue by Nobrainnillidari** [SunstriderEmu/BugTracker#4091]
I seem not able to continue the Black Temple attunement quest. 
i ve completed the chain quests @Akama but at Seer Olum in SSC i dont get a continuation of this chain quest.

**Comment by Jerrythemagicdog** [comment]
Have you handed in the quest Akama's Promise at A'dal?
https://wow.gamepedia.com/Seer_Olum

**Comment by Nobrainnillidari** [comment]
Yes, after i made this topic. The last Akama quest 'reset' and i turned it in back at A'dal. 

Seer Olum already despawned so i ll conform next week

**Comment by Jerrythemagicdog** [comment]
Alright, that was the problem then, the quest has to be handed in.
