### ISSUE TITLE
Warlock immolate

### ISSUE THREAD

**Issue by Flamelock** [SunstriderEmu/BugTracker#4092]
**Describe the bug**
Immolate is doing 1 less damage than the calculation from the damage increases with improved immolate and emberstorm talents

**To Reproduce**

Cast immolate on any target multiple times with 0 spell damage as lvl 70 with immolate rank 9

https://tbc-twinhead.twinstar.cz/?spell=27215, since such spell do not exist on wowhead anymore

**Expected behavior**
With all the calculations for the spell that does 327 initial damage + 25%(+80 damage) from Improved immolate + 10%(40) from emberstorm, should do a damage of 447 to 448 and not 446, also u can check that the description calculated properly the values, yet they r doing the numbers they r not supossed to.

**Screenshots/videos**

https://imgur.com/a/25Oi7Oc
**Additional context**
Should also take into consideration it should benefit from spell damage and sacrifice demon, since it could affect those spells doing a wrong calculation not taking those into the subject for the correct amounts of damage.

**Comment by kelno** [comment]
Thanks for reporting!
This is expected, a lot of those calculations are doing rounding at some steps that leads to those imprecision, this is not specific to immolate and can be seen for most spells in the game.
As far as I know retail also has the same behavior and way to be somewhat imprecise with these calculations. But it's all good and well as long as those errors are minors and also impacting every spell and even melee damage in the game in the same way.
So we're not going to change this.

**Comment by Flamelock** [comment]
Would u mind if i check the the formulas u r using in ur code, isnce u r closing the case, id rather at least check whats the problem on it or why its not calculating properly.

**Comment by kelno** [comment]
If you're a programmer you can check out the last public version of our core here:
https://github.com/SunstriderEmu/sunstrider-legacy
Even then I can tell you that there is no single place you can look at for this formula, spells do go in a lot of different places while being processed.
I'm pretty sure the problem is not even with the formula itself but rather with the data types used. For example if the result of some calculation step is 5.4 but we store it in some integer data, it's going to be rounded down to 5, affecting the final result.

**Comment by Flamelock** [comment]
mind if i ask if this base code is wotlk or tbc, since ive seen idk if u took code from wotlk to make some fixes and changes, or its wotlk code and translated changes to tbc.

**Comment by kelno** [comment]
Core has always been a tbc one since 2008

**Comment by Flamelock** [comment]
thats interesting i guess they were working on wotlk already cause many parts of the code have the scripts for lk fight and dk abilites.

**Comment by kelno** [comment]
Bits of TrinityCore have been ported into this core over its history, and some LK-related code kept (but disabled) for various reasons.

**Comment by Flamelock** [comment]
hey is it possible to take a look at the database values of skills and stuff?
