### ISSUE TITLE
Third weapon shiv bugging all poisons in arenas!

### ISSUE THREAD

**Issue by Mindflex** [SunstriderEmu/BugTracker#4093]
**Describe the bug**
When i use "Shiv" (rogue spell for applying offhand poison) in arenas, from time to time, in middle of arena it wont apply
poison. It does like 250-300 nature (spell) damage, but without applying my "wound poison" on target (poison that is currently on offhand weapon). When it start to getting buggy, shiv acting like there is no poison on weapon, even me and my partner clearly can see there is poisons on my weapons.
First time i saw this happening was yesterday and i reported it within a ticket, but it keeps bugging all day long, its annoying.

**To Reproduce**
Whenever i cast Shiv, it should instantly apply poison from my offhand weapon to target. 
Doesn't meter if i changed my offhand, as soon as my new offhand weapon have poison, shiv should apply it.

Spell: https://wowhead.com?spell=5938

**Expected behavior**
When i use 2 different poisons on 2 different offhand weapons, it should do both poisons when i re-equip them.
Example: offhand1 has crippling - offhand2 has wound 
When i use offand1 shiv it should do crippling for 12sec, in that case i re-equip offhand into offhand2 and start using shiv's till i reach 5 stacks of wound, but when i change my weapon, my offhand2 acting like there is no poison on it, shivs only do low dmg without applying a wound.

**Additional context**
Hint: It goes buggy only in arenas, working fine in duels/world pvp. Also its usually getting buggy in arenas after i change my offhand weapon (using 3 offhands for better poison applying, for example im using third weapon to apply wound, so when i equip my third weapon my shiv's dont apply poison.)
Everything worked great till yesterday, since then im getting frustrated in areans, please fix this.

**Comment by Jerrythemagicdog** [comment]
Probably swapping to the wrong weapon with your macro or the poison resists. Check your macros.

**Comment by Mindflex** [comment]
Bro i tested it, im not using wrong macro.
Even when i change weapons with my mouse, still getting buggy every next arena.
I'll try to make you video prove.

**Comment by Mindflex** [comment]
Also how my macro working everywhere else except arena.
Im doing bgs/duels and its working fine.
