### ISSUE TITLE
I cant make Donnations from Colombia

### ISSUE THREAD

**Issue by S4LGado** [SunstriderEmu/BugTracker#4094]
I have an issue with the donations. It seems that the server doesnt have active methods of payment to Colombia
![queja](https://user-images.githubusercontent.com/69695137/90286574-ca7f5280-de3b-11ea-9b80-6bc332ceb747.png)

**Comment by Jerrythemagicdog** [comment]
That's not a service we operate, please contact Paymentwall. Thanks!
