### ISSUE TITLE
Ancestral Healing and Inspiration

### ISSUE THREAD

**Issue by Xsh74500** [SunstriderEmu/BugTracker#4095]
**Describe the bug**
Ancestral Healing (shaman crit) and Inspiration (priest crit) does stack when they shouldn't
Plus if another shaman/priest derank it, it can stacks up to 6 time, giveing quite amazing armor bonus.

**To Reproduce**
Crit heal with a Sham and a priest on the same target, and watch armor
Crit with 2 priest/shamon the same target, one with 2/3 Fortitudem and the other 3/3 fortitude

**Expected behavior**
They should not stack, having both shouldnt change your armor value

**Screenshots/videos**

http://wowwiki.wikia.com/wiki/Inspiration
It does not stack with the restoration shaman's third tier talent Ancestral Healing.

http://wowwiki.wikia.com/wiki/Ancestral_Healing
It does not stack with the holy priest's third tier talent Inspiration.

http://www.warcrafthuntersunion.com/200 ... not-stack/
Armor Increase Percentage Buff:
Inspiration (priest)
Ancestral Healing (shammy)

**Additional context**

**Comment by blblblaz** [comment]
thanks for the issue, you are correct

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
