### ISSUE TITLE
Quest "A Cleansing Light" (Aldor) can't be turned in for me.

### ISSUE THREAD

**Issue by Wembi** [SunstriderEmu/BugTracker#4097]
As simple as the headline. Quest "A Cleansing Light" (Aldor) can't be turned in for me.

1x Fel Armement needs to be turned in to Ishanah on Aldor Rise. The quest is marked as completed in my quest log, I have the armament in my bag (see link on IMGUR for screenshot) but the NPC won't recognize it, so it can't be turned in.

Item: https://www.wowhead.com/item=29740/fel-armament
Quest: https://www.wowhead.com/quest=10420/a-cleansing-light
Screenshot: https://imgur.com/a/b9DNBux

**Comment by Cayman91** [comment]
Try clearing your cache folder.
