### ISSUE TITLE
Cannot complete Battle for Hillsbrad questchain!

### ISSUE THREAD

**Issue by Stotysiecy** [SunstriderEmu/BugTracker#4098]

**Comment by Stotysiecy** [comment]
Cannot complete Battle for Hillsbrad questchain as my lvl19 twink.
i have completed the first one, but im not able to take the second one. That wasnt an issue when i tried to do it with my lvl 70 char and i could do the chain without any problem. My guess is that the level requirements are wrong for this quest here as the quest reward is bis 2H sword for lvl 19 twink and even your database says it should be lvl 19
My ingame name is Halabarda. I hope you can fix this issue as quickly as possible.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
