### ISSUE TITLE
Hemorrhage Weapon Damage Bonus Incorrect

### ISSUE THREAD

**Issue by Skuzzlez** [SunstriderEmu/BugTracker#4101]
Tested with a level 70 rogue with a Worn dagger (for very little weapon damage variance) attacking a naked level 70 hunter with 300 armour (2.76% reduction). The Rogue did _not_ have an offhand equipped.

After 100s of hits, these are the absolute minimum values for hits with both Melee Attack and Auto Swing. I'm using the lowest recorded hits to reduce the amount of variables (Hemorrhage debuff, Dirty Deeds extra damage modifier) and these were the values we got (note that these are 100% the lowest possible values you can get, it's easy to guarantee this using a weapon with 1-2 weapon damage)

Lowest melee swing hit (no hemo debuff): 194
Lowest Hemorrhage hit: 237

Hemorrhage Rank 4: https://tbc-twinhead.twinstar.cz/?spell=26864

> An instant strike that deals 110% weapon damage and causes the target to hemorrhage, increasing any Physical damage dealt to the target by up to 42. Lasts 10 charges or 15sec. Awards 1 combo point. | An instant strike that deals 110% weapon damage and causes the target to hemorrhage, increasing any Physical damage dealt to the target by up to 42. Lasts 10 charges or 15sec. Awards 1 combo point.

I can't find anything else in the rogue's talents or gear that modifies the weapon damage modifier.

194*1.15 = 213.4 damage (expected), however Hemorrhage is doing 237 at the absolute minimum (122% weapon damage?)

This suggests that the weapon damage modifier for Hemorrhage is using incorrect values, giving rogues a significant damage buff.

To recreate:

Attack a target with a Worn Dagger (1-2 weapon damage) repeatedly, and compare minimum hits for both Melee attack hits and Hemorrhage hits on a very low armor target. You can also compare Average hits, but it'll be more difficult to test since you'll need to account for the Hemorrhage debuff.

**Comment by Skuzzlez** [comment]
I've just noticed a similar issue with Mortal Strike. A warrior is hitting my 300 armour hunter for 182-183 or 189-190 physical damage consistently. Mortal Strike however is hitting for a minimum of either 402 or 419 damage.

https://tbc-twinhead.twinstar.cz/?spell=30330

> A vicious strike that deals weapon damage plus 210 and wounds the target, reducing the effectiveness of any healing by 50% for 10sec.

Using the above, against such a low armour target you'd expect MS hits to be doing either 393 or 400 damage. Instead it's consistently hitting for either 402 / 419.

Are there any other things that innately modify weapon damage modifiers that aren't openly known about / expressed within the game? If not, it might be worth investigating other abilities that deal Weapon damage + x as well.

**Comment by Skuzzlez** [comment]
Hunter:

Did some testing with Auto & Steady shot with naked gear against a naked warrior with 186 armor (1.73% dmg reduction), Using Worn Shortbow (5-10 damage), Rough Arrow (1.5dps ammo).

Character sheet damage range: 67-73. 
Actual Auto-Shot damage (hit): 73 min, 76 avg, 79max.
Steady Shot damage: 255 min, 258 Avg, 262 Max

Steady Shot tooltip:
"A steady shot that causes base weapon damage plus 219. Caues an additional 175 against Dazed targets."

Using the above info in the tooltip, you'd expect Steady Shot to be doing roughly 76 + 219 = 295 damage. However, it's hitting for 258 average. 

Of course, Steady Shot shouldn't take into account ammunition damage! So let's subtract that from the base damage. With no ammo: Character Sheet damage range = 63-69, a VERY minimal decrease. I'd imagine I'd still be hitting for 69-72 auto shots. I can't test this because you can't shoot without ammo. Now, let's be generous and subtract 10 damage from the damage rather than the supposed 4 that it should be. Even if we did this, Steady Shot should _still_ be hitting for 285 damage at the very least.


In the above cases, Rogue and Warrior abilities seem to be doing more damage than their tooltip should imply. In this case, Steady Shot seems to be doing a lot less damage than its tooltip implies. Something seems pretty funky here.

**Comment by blblblaz** [comment]
both hemo and mortal strike are subjected to weapon speed normalization

normalized_damage = base_weapon_damage + (X * Attack Power / 14)
where X is:

1.7 for daggers
2.4 for other one-handed weapons
3.3 for two-handed weapons
2.8 for ranged weapons

source: https://wow.gamepedia.com/index.php?title=Normalization&oldid=1563852

all that we are doing with spells like this is using this normalization formula and adding the spell effect ontop of it 

hemo example (check combat log) - using formula above: 2 + (1.7*1715/14) * 1.1 (hemo spell effect) = 231
![WoWScrnShot_081620_113806](https://user-images.githubusercontent.com/53877162/90330378-10abf180-dfb5-11ea-929c-fb3b1c338477.jpg)

mortal strike example - using s3 mace (386 - 580 dmg range), using formula above, for max weapon dmg lets say: 580 + (3.3*1868/14) + 210 (mortal strike bonus damage) = 1230
![WoWScrnShot_081620_114146](https://user-images.githubusercontent.com/53877162/90330470-94fe7480-dfb5-11ea-9cfc-b710b67828e5.jpg)

**Comment by Jerrythemagicdog** [comment]
Seems like it's explained, closing the issue.
