### ISSUE TITLE
bg's, warlock is required to have 1 shard to cast any spell requiring shards.

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4102]
in battle grounds spells don't require shards to cast, however if you have actually 0 shards, you can't cast them because you dont have reagents.

**Comment by Balanarr** [comment]
That's not even true. Bg's in tbc required and consumed shards. Be thankful tht they don't get consumed.

**Comment by Jerrythemagicdog** [comment]
Intended.
