### ISSUE TITLE
Raidwide aggro range on trash

### ISSUE THREAD

**Issue by Balanarr** [SunstriderEmu/BugTracker#4103]
**Describe the bug**
If a player aggroes trash, everyone in the raid, regardless of where they are, get in combat with those mobs

**To Reproduce**
Have the raid stand in one part of the raid (i.e. at leotheras in ssc)
Have a single player pull a mob located at the entrance

The pack also aggroes the players on the other end of the raid instance

**Expected behavior**
Trash should only aggro in a limited range around them (don't know the exact range)

**Additional context**
Very annoying change/bug for no apparent reason

**Comment by Jerrythemagicdog** [comment]
Yes, that's intended in raids.
