### ISSUE TITLE
[Hunter] Raptor Strike

### ISSUE THREAD

**Issue by bugreport4** [SunstriderEmu/BugTracker#4105]
**Describe the bug**
When queued, prevents autoshot firing. Must be cancelled in order to continue shooting.

**Expected behavior**
Not affecting autoshots.

**Screenshots/videos**

**Additional context**

**Comment by artieau** [comment]
That is working correctly, please reply here if you feel otherwise with some form of evidence.

**Comment by bugreport4** [comment]
Evidence can be found in any hunter pvp video from back in the day. I'm not sure where you got the idea that it's working correctly.

**Comment by artieau** [comment]
Please share one of these pvp videos from back in the day, with the timestamps, detailing your issue per above. @bugreport4

**Comment by bugreport4** [comment]
https://www.youtube.com/watch?v=VhCI3DDvGGU
16:36, 16:44, 17:40, 17:47

https://www.youtube.com/watch?v=QyAccRnxN1s
7:15

https://www.youtube.com/watch?v=ItiaES2ch7A
01:02

The original post is incomplete (didn't re-read it when I replied, my bad).
The scenario where the hunter stops to fire an auto shot with RS queued, without using any special shots, is actually difficult to find, and I believe **Auto Attack/Auto Shoot** must be checked in the options for that to work. I recall seeing a video where RS was switched on/off as the hunter stopped to fire an auto while running away from a melee (can't find it now sadly).
It's very unlikely that players manually cancelled it whenever it doesn't go off, or had a line for it in all macros. (because it happens so often in PVP)
