### ISSUE TITLE
[QUESTION] Scarab lord title and black-qiraji-resonating-crystal

### ISSUE THREAD

**Issue by LSD7** [SunstriderEmu/BugTracker#4106]
If i complete quest https://classic.wowhead.com/quest=8743/bang-a-gong#guides on this server will i get the https://classic.wowhead.com/item=21176/black-qiraji-resonating-crystal and title https://www.wowhead.com/achievement=416/scarab-lord?

**Comment by Jerrythemagicdog** [comment]
No.
