### ISSUE TITLE
Two trinkets with identical effects, duration and CDs

### ISSUE THREAD

**Issue by metallicant** [SunstriderEmu/BugTracker#4107]
**Describe the bug**
Two trinkets:
- Ancient Draenei Arcane Relic - https://tbcdb.com/?item=31615
- Vengeance of the Illidari - https://tbcdb.com/?item=28040
have absolutely identical effects on-use and cooldowns, i.e.: they give 120 spell damage and 220 healing for 15 seconds. Both have 1.5 min cooldown.
Obviously you cannot use both of them simultaneously, since once you use either of them, it triggers a 15 second CD on the other one. But after these 15 seconds, you still cannot use the other trinket, though the trinket icon doesn't appear to have a cooldown. So, the second trinket can be used only when the first one's cooldown ends. 

**To Reproduce**
1. Use Ancient Draenei Arcane Relic
2. Wait for 15 seconds until Vengeance of the Illidari cooldown ends.
3. Use Vengeance of the Illidari.
4. Vengeance of the Illidari doesn't work. Just the glow effect on hands.
5. Wait for Ancient Draenei Arcane Relic cooldown ends.
6. Only then Vengeance of the Illidari is usable.
Same result if you reverse the trinket order.

**Expected behavior**
When the effect of one trinket ends, you should be able to use the other one.

**Additional context**
Having searched similar issues (e.g. #2087), I've come to a conclusion that this bug appears when wearing and using two trinkets with identical effects, durations and cooldowns.

**Comment by hufsa** [comment]
Thank you! Fixed with next update.
