### ISSUE TITLE
[API] Can't use SwapRaidSubgroup in combat

### ISSUE THREAD

**Issue by LSD7** [SunstriderEmu/BugTracker#4109]
Scripts SwapRaidSubgroup  or SetRaidSubgroup are should be able for using in combat. But it doesn't work in combat. As we can see they don't have 'NOCOMBAT ' modifiers https://wowwiki.fandom.com/wiki/World_of_Warcraft_API

**Comment by Jerrythemagicdog** [comment]
That's not something we control.
