### ISSUE TITLE
CAN NO LONGER LOG IN TO SERVER

### ISSUE THREAD

**Issue by ptaluc** [SunstriderEmu/BugTracker#4110]
I played for several hours today and then tried to log in again around 7pm.  I noticed that my account name was not shown, nor was the "remember account name" checked.  I entered my account name and password just as I did several times already today, but it repeatedly said that the information is invalid.  Please help. 

Character: Zole - Alliance

**Comment by Jerrythemagicdog** [comment]
You can always use: https://endless.gg/account/recoverpassword
