### ISSUE TITLE
Wound poison dont work properly in arenas!

### ISSUE THREAD

**Issue by Mindflex** [SunstriderEmu/BugTracker#4112]
**Describe the bug**
When i do wep switch macro my wounds got buggy, they simply cant be applied.
As soon as i do wep switch my wound disappear from target and cant be applied again for random amount of time.
I already made a report on this, but you guys told me its about macro.
(macro is going like this, and i tried many variations, same problem)
Macro: /equipslot 17 Merciless Gladiator's Shiv
            /equipslot 17 Merciless Gladiator's Quickblade

**Add any other context about the problem here.**
Fun fact is that macro working fine in world pvp/bg's without problem.
I tried to make video while in duel, but it worked fine.
As soon as i use it in arena, strange things are going on.

Please test it by yourself, its frustrating to play arenas without wounds.

**Comment by Jerrythemagicdog** [comment]
Yes, this is an incorrect macro.
Bind your weapons separately.
The fact that it works in the open world is related to something completely unrelated, this won't work anywhere else you'll just swap weapons and put yourself on GCD if you're in combat.

**Comment by Mindflex** [comment]
Can you link me proper macro mate?

**Comment by Jerrythemagicdog** [comment]
`/equipslot 17 Merciless Gladiator's Shiv` and `/equipslot 17 Merciless Gladiator's Quickblade`
under separate buttons
