### ISSUE TITLE
Mechanar

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#4114]
Mechano Lord Capacitus in Mechanar pulled when we pulled the Mechanar Tinkerer bombers on the side of the wall closest to the Cache(the pink boxes). The party had a healer leave, tank did the same pull when I joined to heal and finish their dungeon, and it happened again.

The Mind Control on last boss was also bugged and didnt let tremor work on the charm.

**Comment by Jerrythemagicdog** [comment]
Call for help issue fixed with next update.
Tremor Totem won't work on a charm when the player is hostile to it (because they're Mind Controlled).
