### ISSUE TITLE
Roll Discarded if removed from group

### ISSUE THREAD

**Issue by asthmattack** [SunstriderEmu/BugTracker#4116]
**Describe the bug**
If a player is removed before loot is rolled the item will not include them into the roll regardless of player need or greed roll.

**To Reproduce**
X players roll greed
Y player rolls need
Y is removed from group before roll
Item is given to X player even though Y rolled need

**Expected behavior**
Item would be rolled and given to player Y as need > greed.
![WoWScrnShot_081920_195200](https://user-images.githubusercontent.com/69945454/90707102-d2d4f480-e264-11ea-861d-98208e4830ae.jpg)
![WoWScrnShot_081920_195236](https://user-images.githubusercontent.com/69945454/90707103-d36d8b00-e264-11ea-82c1-e005bcbadd88.jpg)
![WoWScrnShot_081920_195253](https://user-images.githubusercontent.com/69945454/90707104-d36d8b00-e264-11ea-9751-3b28085d7ade.jpg)
![WoWScrnShot_081920_195257](https://user-images.githubusercontent.com/69945454/90707106-d36d8b00-e264-11ea-9165-7e421bf44303.jpg)
![WoWScrnShot_081920_195303](https://user-images.githubusercontent.com/69945454/90707107-d36d8b00-e264-11ea-82dd-53133b65a9ad.jpg)

**Screenshots/videos**

**Additional context**

**Comment by michaelkittrell** [comment]
please do not fix this "bug".

it is used by group leaders to disqualify people who roll incorrectly.  for example player A rolls need but its their OS, group leader removes player A from group and possible ninja is averted.

**Comment by asthmattack** [comment]
So as a leader, I could say, remove you from the group because you rolled need against my friend who also needs the item.
That seems more like it can be used to ninja accidentally than a ninja averted.

**Comment by michaelkittrell** [comment]
yes it can be abused both way, prefer the leader be entrusted with this power rather than the 24 other people correctly choosing need/greed.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2826
