### ISSUE TITLE
Quiver bug on kael thas fight

### ISSUE THREAD

**Issue by timk900** [SunstriderEmu/BugTracker#4118]
**Describe the bug**
When ending combat/dying with legendary bow our quiver bugs out and doesnt give the speed bonus until we relog. EVERY SINGLE TIME. Tried it all to fix including removing and re equipping my bow/ammo. 

**To Reproduce**
equip kael thas legendary bow and die. itll always bug.

**Comment by Skuzzlez** [comment]
Pretty sure this doesn't just apply to the KT fight, it applies any time you unequip your ranged weapon and then re-equip it. You lose attack speed (I guess Serpent's Swiftness talent isn't reapplying) unless you relog.

**Comment by Fishcowduck** [comment]
You can just move which bag slot your quiver is and it'll properly readjust your attack speed bonus. It is indeed bug but it's quite easy to fix, hope this helps!

**Comment by kelno** [comment]
Thanks for reporting.
It's indeed quiver related and not talent related.

**Comment by kelno** [comment]
Fixed with next server update
