### ISSUE TITLE
Shattered Hand Assassin

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#4119]
Shattered Hand Assassins in Shattered Halls sap people (including tank) in combat during fights. This also happens during Porung fight leading mostly to wipes when tank gets sapped.

No clue if this is intended behaviour, but certainly is kinda nonsense.

**Comment by Jerrythemagicdog** [comment]
Yeah they always did Sap in combat, their Sap has no regard for combat state.
