### ISSUE TITLE
looting/creating items doesn`t add them to the bags

### ISSUE THREAD

**Issue by WILLVONPHEARE** [SunstriderEmu/BugTracker#4120]
i have notice that when you loot or create items it will show in the chat the amount howeve when you look for it in the bags is it not there. i first notice this when creating mok` nathal shortribs, you see, i had 20 raptor ribs, which is th reagent needed to create the item in question, however when attempted to consume on of them i noticed i had only 13.

recently.  when farming elementals, i got 4 motes of water but my bags only show 2. 

![2020-08-20](https://user-images.githubusercontent.com/69994323/90835478-f56d1900-e309-11ea-950a-8e6a97b3d084.png)

**Comment by Jerrythemagicdog** [comment]
Seems like your addon is not displaying all of your bag contents (5 bags * 16 slots each) we can only see 64 slots here so we're missing one bag, which is most likely where the items are going.

**Comment by WILLVONPHEARE** [comment]
ty so much, i reinstalled it and now itw working properly <3
