### ISSUE TITLE
Attacking a target with a pet should put the player in combat.

### ISSUE THREAD

**Issue by Skuzzlez** [SunstriderEmu/BugTracker#4122]
**Describe the bug**
Currently, attacking another player with a pet (and seemingly NPCs too) does not put the player character in combat. It should - it was a common strategy in both TBC and WotLK arena to send your pet in immediately to avoid sap. There was even an active, most likely unintended bug where you were immune to sap despite not being in combat, as long as your pet was running to attack a target. I don't expect the latter to be introduced, but at the very least the pet should put the player in combat when it HITS or performs an action on an enemy.

**To Reproduce**
1. Attack a player / NPC with just the pet - no combat status gained.

**Expected behavior**
The owner of the pet should be put in combat while the pet is attacking. It's difficult to find video / written evidence of this since the old Blizzard forums no longer exist, but here's a thread from CoreCraft's github discussing the exact same issue back in 2015 (and the aforementioned bug) - the consensus was that the pet should put & keep the player in combat:

https://github.com/ccshiro/cc-buglist/issues/246

**Comment by kelno** [comment]
Thanks for reporting!
Updated with next server restart. We won't be following the retail rule exactly there, we'll make that a consistent combat start whenever the pet attacks.

**Comment by tbc123** [comment]
what about this moment its from retail tbc boys

**Comment by tbc123** [comment]
https://camo.githubusercontent.com/448321b69a56d982cbac6e5674dc82f8743fc9c8/687474703a2f2f692e6779617a6f2e636f6d2f39323164303638626264333333306135626562373931303335366636633339642e706e67

**Comment by tbc123** [comment]
screenshot

**Comment by tbc123** [comment]
https://www.warmane.com/bugtracker/report/46407

**Comment by tbc123** [comment]
https://www.warmane.com/bugtracker/report/49283

**Comment by tbc123** [comment]
there with time code pet use devour magic and wlock didint have combat its retail movie

**Comment by tbc123** [comment]
https://www.youtube.com/watch?v=86ZCLm910uo&t=155s&ab_channel=b0ne91

**Comment by tbc123** [comment]
https://youtu.be/86ZCLm910uo?t=781

**Comment by tbc123** [comment]
https://youtu.be/86ZCLm910uo?t=930

**Comment by tbc123** [comment]
@kelno check and fixed this bugs plz

**Comment by tbc123** [comment]
I know for sure how it worked during WoTLK (on retail), and I'm going to explain it :

If you send your pet to an enemy, you can't be sapped, regarding your combat state. It is NOT related to your combat state, which means you don't have those "crosse blades" and you still can not be sapped.
If your pet hits an enemy with a melee hit, or a damaging ability, he will enter combat, and the owner of the pet as well.
If your pet hits an enemy with a non damaging ability (devour magic, soothing kiss etc), he will enter combat, but the owner will not (and can be sapped if pet isn't running to the enemy)
If your pet gets hit, he will gain combat, but the owner won't (and can be sapped if pet isn't running to the enemy)
If the owner of the pet uses health funnel and pet is in combat, owner will gain combat.

**Comment by kelno** [comment]
Thanks for the details. Right now we're happy with the consistency of the current logic, but if we have to revisit this rule this will be useful.
