### ISSUE TITLE
Altar of Shatar Vindicators decided to go aggro

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#4125]
![image](https://user-images.githubusercontent.com/45275285/90939606-6a535800-e3c9-11ea-8467-5909473ee302.png)

And im exalted aldor

**Comment by kmayberry91** [comment]
Nothing like that. I was getting auto logged out for AFK and came back and cancelled it. Maybe that had something to do with it.

**Comment by kelno** [comment]
Can't reproduce, please do report again if you get any more details
