### ISSUE TITLE
Hunter Training - bug with scare beast

### ISSUE THREAD

**Issue by painfool** [SunstriderEmu/BugTracker#4127]
As Night Elf Hunter, go to train with [Einris Brightspear](https://classic.wowhead.com/npc=5515/einris-brightspear).
As soon as you train 1 ability, [scare beast](https://classic.wowhead.com/spell=1513/scare-beast) rank 1 pops up as available (even though it is already trained) and you cannot re-learn it or get rid of it.  You have to manually click every other ability to learn those other abilities.
(Click next ability, click learn, click next ability, click learn.)

When leveling fast on server, it can be quite a tedious issue instead of being able to just train, train, train, train, etc.

*NOTE - this was still an issue after turning all addons off*
Please see screenshot

![WoWScrnShot_082220_104224](https://user-images.githubusercontent.com/70071132/90962382-63c5ee80-e464-11ea-8789-0ad9baf78443.jpg)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
