### ISSUE TITLE
Auberdine to Teldrassil boat

### ISSUE THREAD

**Issue by Bubblesqueak** [SunstriderEmu/BugTracker#4128]
I got on a boat from Auberdine to Teldrassil and somehow, I ended up out of the boat in the water in the fatigue zone... I don't think there was a loading screen and my character wasn't moving.

I should have been taken all the way instead of dying in water. :(

https://imgur.com/Be4Dk6y

**Comment by hufsa** [comment]
Duplicate: https://github.com/SunstriderEmu/BugTracker/issues/445
