### ISSUE TITLE
Lieutenant Jackspring <Weapons Quartermaster> Missing items.

### ISSUE THREAD

**Issue by Sathirien** [SunstriderEmu/BugTracker#4129]
NPC Missing stuff,  Lieutenant Jackspring <Weapons Quartermaster> Alliance chapions's hall

https://tbc-twinhead.twinstar.cz/?npc=12784

**Comment by Sathirien** [comment]
# Wine and a baguette, for whoever will fix this.

**Comment by Sathirien** [comment]
Dear,  Jerrythemagicdog "Black Temple" has been opened ,Vengeful Gladiator also UP. Whole Server getting best of fun ,and adventures, same with me, but I can't compete with others, because, of missing vendor stuff, Im very involted in the game. Friends of mine persuaded me for moving here from Atlantis ,was there 60k hks hunter, and now cant buy bow.  Its 5 day stucked, and still dont know whats going on. Some GM said they are fixig that, but status didnt change. Im begging to get any info, about status. Checking that every time, even at my work.

**Comment by Jerrythemagicdog** [comment]
Fixed with next update, thanks.
