### ISSUE TITLE
Lifebloom dispels not healing correctly

### ISSUE THREAD

**Issue by Aedark** [SunstriderEmu/BugTracker#4130]
**Describe the bug**
When lifebloom x2 or lifebloom x3 is being dispeled or spellstealed is currently not healing 

**To Reproduce**
When lifebloom x2 or lifebloom x3 is being dispeled or spellstealed is currently not healing 

Spell: https://wowhead.com?spell=33763

**Expected behavior**
When Lifebloom expires or is dispelled, the target is instantly healed

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1453
