### ISSUE TITLE
Merciless Gladiator's Libram of Justice

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#4140]
Merciless Gladiator's Libram of Justice http://tbc.cavernoftime.com/item=33077 might be proccing off more things than just Flash of Light. 

It's just a speculation because I can't test it myself but I'm seeing multiple not holy paladins running this so it might be broken just as Stonebreaker Totem #1710 was or Libram of Divine Judgement (crucial) #1904 still is.

I would like you to test the possible procs of this libram from:
- Blessings,
- Cleanse,
- Holy light.

If you find anything weird the other seasons librams might be checked too
Gladiator's Libram of Justice http://tbc.cavernoftime.com/item=28356
Vengeful Gladiator's Libram of Justice http://tbc.cavernoftime.com/item=33842
Brutal Gladiator's Libram of Justice http://tbc.cavernoftime.com/item=35040

Sorry for the trouble if you found it's working properly.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
