### ISSUE TITLE
World Breaker

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#4141]
World Breaker mace http://tbc.cavernoftime.com/item=30090 proc _"Chance on hit: Increases the critical strike rating of your next attack made within 4 seconds by 900."_ is incorrectly applied not only to the "next attack", but also to **all secondary attacks** that "come" from the initial "next attack".

This means that when the Mace procs and on next attack 900 crit is gained - not only the initial white hit is affected, but also all Seal Hits, Windfury Hits etc gain this bonus. This means that currently in absolutely ordinary scenario you get the 900 crit (idk 45 % crit?) for the White hit + Windfury hit + two Seal of Blood hits (or Command hit). Same would apply to Shaman Windfury Weapon. 

This mace was already abused in last season and the fix is very much needed now, because in this state it would still easily outvalue even S4 weapon for ret imo.

Suggestion is to change it so that only one next hit is affected. Seal of Command should for example have a chance to proc the Mace, but the granted proc would then apply ONLY to the next crusader strike or white hit or even judgement.

There are many more possibilities to abuse this mace rn which I am obviously not gonna bring up here.

**Comment by Jerrythemagicdog** [comment]
Not sure how it's supposed to work, would be cool to get some sources however slim the possibility of that is.

**Comment by Rettiy** [comment]
As you said, it's impossible to get any info on this particular thing. Couldn't find any old ret videos using World Breaker either. Few comments on wowhead mention this but these are always just questions, no clear answer is given there.

It is probably up to your decision at this point but in my opinion this Mace would be way more discussed in the past if it was this OP. Also the current state is simply not healthy for PVP.

Either way please decide quickly @Jerrythemagicdog so that if you decide to let it be like this (and don't change your opinion a month later), I myself could get my hands on this mace ( ͡° ͜ʖ ͡°)

**Comment by TheMoneyHater** [comment]
I remember World Breaker to be the bis enh 2-hand PvP wep the whole expansion but idk

**Comment by kelno** [comment]
Thanks!
Fixed with next server update
