### ISSUE TITLE
Loot bug if inventory full while herbing/skinning/mining etc

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#4144]
**Describe the bug**
Have full inventory and attempt to herb/skin a monster or mine a node. You can only fill current stacks of items but then get bugged that your inventory is full - and the loot is not left on the monster to be looted once you clear your bags. Deleting an item from inventory while the loot window is still open does not let you obtain the item either and it will disappear and vanish for good.

**To Reproduce**

1. Kill a Talonsworn Forest-Rager with full inventory
2. Herb it
3. Delete an item from inventory with loot window open
4. Loot window disappears and you lose loot rights on the monster

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/4115

**Comment by kelno** [comment]
Fixed since
