### ISSUE TITLE
Mage - Water Elemental Bugg

### ISSUE THREAD

**Issue by kekburkek** [SunstriderEmu/BugTracker#4145]
Summon Water Elemental: 

The summon of the water elemental combat state is set to passive, once you set it to defensive or aggressive it doesn't save it for the next time you summon the water elemental. It goes back to passive instead of saving what you put it on etc (defensive). 
Can you please fix this?

**Comment by Jerrythemagicdog** [comment]
Same as retail, Water Elemental has no pet states saved. 
Make a macro with the stance you want with the Summon spell.
