### ISSUE TITLE
Bloodgem Crystals quest bugged

### ISSUE THREAD

**Issue by Cicavirag** [SunstriderEmu/BugTracker#4147]
The quest itself sounds like this:
"Magistrix Larynna wants you to go to Manaforge B'naar and obtain a Bloodgem Shard from a Sunfury Magister. Use this shard near the larger Bloodgem crystals and return to her at Area 52."

Whenever you get accidentally that 0,00001% dropchance Bloodgem Shard and try to use it near a Bloodgem crystal, you get interrupted imediatelly, it doesn't matter if you are combat or not. Tried to do this quest like 7 times; abadon quest, retake, relog, go to another Bloodgem crystal etc. But it didn't work for me. So please fix this quest, I would appreciate it, thank you in advance!

**Comment by beraus** [comment]
Duplicate https://github.com/SunstriderEmu/BugTracker/issues/2058
