### ISSUE TITLE
Paladin Judgements are allowed on multiple targets simultaneously

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#4148]
**Describe the bug**
You can judge wisdom/light/crusader/vengeance/etc on multiple targets and rets/prots can technically can keep them up forever. The tooltip and mechanics of this state "Only one Judgement per paladin can be active on one target at any one time"

**Comment by Jerrythemagicdog** [comment]
Yes, that's correct.
