### ISSUE TITLE
Flasks problem

### ISSUE THREAD

**Issue by bugged-tech** [SunstriderEmu/BugTracker#4149]
I did quest Elixir Mastery, after created overall 800 Elixirs of Major Agility i unlocked 0  FLASKS.. It is possible to not unlock even 1? I think its something wrong with that

**Comment by Jerrythemagicdog** [comment]
Are you talking about unlocking new recipes or creating additional elixirs?

**Comment by bugged-tech** [comment]
> Are you talking about unlocking new recipes or creating additional elixirs?

about discover new flasks

**Comment by beraus** [comment]
`Discoveries
The discovery system grants a **_very small chance_** to learn a new recipe when making other potions.

Potion and Flask Discoveries
Six potion and flask recipes can be randomly learned via discovery, when making flasks, elixirs or potions.

[Flask of Blinding Light]
[Flask of Fortification]
[Flask of Mighty Restoration]
[Flask of Pure Death]
[Flask of Relentless Assault]
[Super Rejuvenation Potion]`
https://wowwiki.fandom.com/wiki/Sources_of_Burning_Crusade_alchemy_recipes

Include your char name, but this was tested already multiple times.

**Comment by bugged-tech** [comment]
Mhm... so if this was tested multiple times im probably unlucky.

Last question
when do u will repair https://github.com/SunstriderEmu/BugTracker/issues/4028 ?

**Comment by beraus** [comment]
4028- isn't really a high priority issue. If you have more data about this one - feel free to open a new one and we'll check it further.

**Comment by bugged-tech** [comment]
Professional approach😂😂  that's all what i wanted to know... 😂
