### ISSUE TITLE
Aldor to scryer problem

### ISSUE THREAD

**Issue by thedetax** [SunstriderEmu/BugTracker#4152]
hello, 
Im stuck with scryers factions, neutral 0/3000 and zero quests availables.
 I came from exalted aldor with the basilik'seyes quest.

Now i'm supposed to give firewing signets to Magistrix Fyalenn (18531).

That npc doesnt give the quest; so im stuck.

Ingame GM said i need to be friendly for that quest, but according to your guide there is no other way.

https://db.endless.gg/?faction=934

Can you please help ?

Regards

![scryers](https://user-images.githubusercontent.com/18287808/91634177-acdeeb00-e9ee-11ea-8ade-ca0dc4356d2a.png)
![scryers2](https://user-images.githubusercontent.com/18287808/91634237-24147f00-e9ef-11ea-87e0-c383fa368802.png)
![scryers3](https://user-images.githubusercontent.com/18287808/91634384-52df2500-e9f0-11ea-8aa9-936a7ee72b5a.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
Funnily enough the min rep requirement was "1" while you were at "0".
