### ISSUE TITLE
Thrallmar pvp daily quest missing

### ISSUE THREAD

**Issue by Andrewcapo** [SunstriderEmu/BugTracker#4156]
On my hunter I am unable to do the Thrallmar daily quest. I have finished all prerequisite quests needed to be able to pick up the daily. The NPC that is supposed to give the quest does not have any quests for me to pick up, it just acts like a normal vendor. My best guess is the quest is no longer available for me because I am exalted with Thrallmar. That shouldn't be the case, but I believe that is what is causing it.

**Comment by Cayman91** [comment]
You did not mention any NPC name, any quest name or pretty much anything that would help devs to check it :)

**Comment by Andrewcapo** [comment]
There is literally only 1 daily quest in Thrallmar, so I didn't think that would be necessary.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Proof (just in case): 
https://www.wowhead.com/quest=10110/hellfire-fortifications#comments:id=88829:reply=19546

Fixed with next update.
