### ISSUE TITLE
gnomish/goblin engie

### ISSUE THREAD

**Issue by hannahieb** [SunstriderEmu/BugTracker#4159]
its not possible to swap from goblin to gnomish and the other way round. i tried to swap from goblin to gnomish and now i cant use my rocket and iam not able to learn the gnomish recipes like the battlechicken

**Comment by Jerrythemagicdog** [comment]
How did you try to swap the specializations?

**Comment by hannahieb** [comment]
i went to the house in 65,9 21,1 or sth in tanaris and swapped the specc over there. it worked out, but i wasnt able to learn recipes at the gadge trainer. so iam gnomish with goblin recipes

**Comment by Jerrythemagicdog** [comment]
If you want to learn Gnomish Engineering recipes you have to visit the Gnomish Engineering trainer.
https://www.wowhead.com/npc=7406/oglethorpe-obnoticus
