### ISSUE TITLE
[#31] Mobs don't reset inside of instances while your zoned out

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#416]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Sunday Dec 09, 2018 at 12:00 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/31_

----

Patch:
2.4.3

Current behavior:
If I pull mobs to the portal in ramparts and zone out; they will still be there when I zone in

Expected behaviour:
Mobs should return to their normal positions when your zone out

Steps to reproduce the problem:
Step 1: Zone into ramparts
Step 2: Pull the mobs to the portal
Step 3: Run out of the portal
Step 4: Zone in - See the mobs only just now starting to run back
![wowscrnshot_120918_215404](https://user-images.githubusercontent.com/45530324/49697009-d98d1680-fbfd-11e8-9ef6-b542d342ead0.jpg)
![Uploading WoWScrnShot_120918_215409.jpg…]()
![Uploading WoWScrnShot_120918_215413.jpg…]()

**Comment by Jerrythemagicdog** [comment]
Tested now, creatures return home correctly.

**Comment by kelno** [comment]
The issue is about the creature only starting to run back when you enter. But it seems unimportant
