### ISSUE TITLE
BT big robot trash to council one shot

### ISSUE THREAD

**Issue by jebossue** [SunstriderEmu/BugTracker#4162]
**Describe the bug**
Promenade sentinel one shot ppl with his L4 Arcane charge which is not even his max rank : the L5 is the cast one !

**Screenshots/videos**
![WoWScrnShot_083120_193142](https://user-images.githubusercontent.com/22474597/91766972-b5e0df80-ebdb-11ea-8e6b-6a6f843117a3.jpg)

**Comment by Jerrythemagicdog** [comment]
Yes, move away from the beam.

**Comment by NeonicSupersonic** [comment]
gd move
