### ISSUE TITLE
Rockbitter weapon bug

### ISSUE THREAD

**Issue by Mandetta1234** [SunstriderEmu/BugTracker#4164]
**Describe the bug**
 Improperly increases melee damage when switching from off hand to main hand enchanted with Rockbiter weapon.

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**
 
![WoWScrnShot_083120_134641](https://user-images.githubusercontent.com/70534381/91777891-74ded000-ebc7-11ea-9590-a019e18bdb1d.jpg)
![WoWScrnShot_083120_134725](https://user-images.githubusercontent.com/70534381/91777906-7c9e7480-ebc7-11ea-9686-88587c5bbeb8.jpg)
![WoWScrnShot_083120_134733](https://user-images.githubusercontent.com/70534381/91777918-83c58280-ebc7-11ea-83f6-5c8f0dfd1b90.jpg)
![WoWScrnShot_083120_134758](https://user-images.githubusercontent.com/70534381/91777937-8b852700-ebc7-11ea-955f-84e887e0a268.jpg)

Video :  https://www.youtube.com/watch?v=VfYfdJm0XVw

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Please stop opening duplicate issues, thanks.
https://github.com/SunstriderEmu/BugTracker/issues/3760
