### ISSUE TITLE
Pet resistances and avoidance training doesn't work for AoE on the Illidari Council encounter

### ISSUE THREAD

**Issue by alexnxs** [SunstriderEmu/BugTracker#4165]
**Describe the bug**
Pet training avoidance (reduces AoE damage taken by 50%) and appropriate resistances do not seem to work on the Illidari Council encounter. 

**To Reproduce**

1.  Spec pet into fire/frost/arcane resistances and avoidance
2.  Check damage from Illidari Council AoE spells
3.  Respec pet out of fire/frost/arcane resistances and avoidance
4.  Observe no change in damage taken

Flamestrike: https://wowhead.com?spell=41481
Blizzard: https://wowhead.com?spell=41482
Arcane Explosion: https://wowhead.com?spell=41524
Consecration: https://wowhead.com?spell=41541

**Expected behavior**
Pet Frost Resistance & Avoidance should work on Blizzard
Pet Fire Resistance & Avoidance should work on Flamestrike
Pet Arcane Resistance & Avoidance should work on Arcane Explosion
Avoidance should work on Consecration

**Comment by Jerrythemagicdog** [comment]
Thanks, pets dying instantly does sound pretty bad. 
We've removed the attribute making the spells ignore resistances.
Live with next update.
