### ISSUE TITLE
Transmutation master not proccing when creating skyflare or earthstorm diamonds

### ISSUE THREAD

**Issue by DruidManos** [SunstriderEmu/BugTracker#4166]
Hi,

My druid Manos is a transmutation master and I have made 12 earthstorm diamonds (https://www.wowhead.com/spell=32765/transmute-earthstorm-diamond) and 13 skyflare diamonds yet I have received 0 procs of additional items. (https://www.wowhead.com/spell=57425/transmute-skyflare-diamond) I made an ingame ticket and they told me to make a bug report for further investigation. Please help me out if this is bugged because I invested 400 gold to become a transmutation master and if it doesn't work it is completely useless. According to wowhead it should proc about 20% of the time. It seems very unlikely that it didn't proc once in 25 tries. Thanks in advance,

Manos the druid

**Comment by MianLavanAelin** [comment]
It can proc, happened to me once on earthstorm, but definitely the chance of it is not 20%. Same with primal might. 
It is suppose to be 20% chance for each creation of the item, so on offi it proced 5 times to someone and is documented. 
Like if it happens on first transmute, the procced item also has 20% chance etc etc. Obviously the chance of it happening in reality is low, but still. 
Here the base definitely does not seem to be set at 20%

**Comment by Jerrythemagicdog** [comment]
The chance is at 16%, most of the extra procs are in the 14% - 16% chance range.
