### ISSUE TITLE
Any invites to/from rogue dont work

### ISSUE THREAD

**Issue by kmayberry91** [SunstriderEmu/BugTracker#4167]
**Describe the bug**
Tested dualbox, with macros, and guildmates. Thx

**Comment by Jerrythemagicdog** [comment]
Sounds like some issue on your end, tested just now with many players. Clear Cache, disable addons and do all the other usual stuff.

**Comment by kmayberry91** [comment]
I cant receive a guild invite either. Its still not working.

**Comment by Jerrythemagicdog** [comment]
What's the character name?

**Comment by Jerrythemagicdog** [comment]
Resolved in game.
