### ISSUE TITLE
Icy Veins + frostbolt

### ISSUE THREAD

**Issue by xatheros** [SunstriderEmu/BugTracker#4168]
Frostbolt (2.5 seconds cast rank 13) is casted in 2.1 seconds instead of 2 seconds when used with icy veins (20% faster casting speed)

**Comment by Jerrythemagicdog** [comment]
https://www.wowhead.com/spell=12472/icy-veins#comments:id=215635

2.5s - 16.66% =~ 2.08s

![image](https://user-images.githubusercontent.com/46463908/91931397-44885600-ecdb-11ea-9797-245a4cd4f1e8.png)

**Comment by xatheros** [comment]
Thanks but why is it 16.66% when the spell states 20%?
________________________________
De: Jerrythemagicdog <notifications@github.com>
Enviado: miércoles, 2 de septiembre de 2020 0:15
Para: SunstriderEmu/BugTracker <BugTracker@noreply.github.com>
Cc: xatheros <mravanal_1991@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [SunstriderEmu/BugTracker] Icy Veins + frostbolt (#4168)


https://www.wowhead.com/spell=12472/icy-veins#comments:id=215635

2.5s - 16.66% =~ 2.08s

[image]<https://user-images.githubusercontent.com/46463908/91931397-44885600-ecdb-11ea-9797-245a4cd4f1e8.png>
