### ISSUE TITLE
Incorrect item from chicken quest

### ISSUE THREAD

**Issue by ruhan33** [SunstriderEmu/BugTracker#4169]
**Describe the bug**
Chicken q in westfall gives wrong item. Morphing Trinket 1 instead chicken pet.

**To Reproduce**

1. Go to westfall and use /chicken emote on chicken few times
2. Complete q and loot egg thats spawned after feeding chicken

**Screenshots/videos**
 <img src="https://i.imgur.com/Z4msBP0.jpg" alt="egg" >

**Comment by beraus** [comment]
Clear your cache and you'll see a proper item.

**Comment by ruhan33** [comment]
Ty, that fixed it
