### ISSUE TITLE
Mail and axes display bug

### ISSUE THREAD

**Issue by Joffre23** [SunstriderEmu/BugTracker#4170]
**Describe the bug**
For a rogue i have is not possible to wear mail or axes, but in bagpack it seems like i can until you click on it to wear it. After that the game write to you its not for you and you dont have the spec for it. In auction you can't see it if you choose items valuable for you but if you look for it without check button for aviable things for you, there you can see it light and it is displayed that you can wear it, but you can't.

**Comment by Jerrythemagicdog** [comment]
Clear Cache and disable addons.

**Comment by Joffre23** [comment]
But i need that addons :D
