### ISSUE TITLE
Loot not appearing in inventory

### ISSUE THREAD

**Issue by KN0MI** [SunstriderEmu/BugTracker#4172]
**Describe the bug**
When I mine copper veins the chat box says I recieve some copper and stone, but in my inventory nothing appears. I had one full stack of copper in my inventory, which I traded over to my friend in hopes of fixing the bug. When he mailed it back and I opened the mail, again the copper did not appear in my inventory. However when at the smelting station I still had a "hidden stack" which I could smelt into bars and those did appear in my inventory. Also when I looted a chest and a rare dropped in my name it did not go into my inventory but wasn't on the ground anymore either. Some items like junk does go to my inventory however.

I don't care much for the items themselves, I just hope that this get fixed soon. IGN: KNOMI

**To Reproduce**
--

--

**Expected behavior**
--

**Screenshots/videos**
--

**Additional context**
--

**Comment by Jerrythemagicdog** [comment]
What bag addons are you using?

**Comment by KN0MI** [comment]
Bagnon, but I never had this issue before and it happend while in a
session, no relog or reload.

Op do 3 sep. 2020 20:22 schreef Jerrythemagicdog <notifications@github.com>:

**Comment by Jerrythemagicdog** [comment]
Disable the addon and try again please, we've had a player with a similar issue recently where the addon would not display all of the available bag slots.

**Comment by KN0MI** [comment]
Okay, if it were to happen again I shall try that. However the bags were
not full at all when this happend. All is working fine now though.

Op do 3 sep. 2020 22:39 schreef Jerrythemagicdog <notifications@github.com>:
