### ISSUE TITLE
Problem to capture towers and graveyard in the valley of alteracle

### ISSUE THREAD

**Issue by Dastent** [SunstriderEmu/BugTracker#4173]
**Describe the bug**
When I try to capture a tower or a graveyard in the valley of alteracle, the progress gauge does not show but the enemy flag is burned, then it quickly reappears without being able to capture the objective. Note that other members of the raid can do it without problem. Escuse me for not posting any screenshot since it's of no use in my case. IGN; Ninastir

**To Reproduce**

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, clear your Cache and try again please.
