### ISSUE TITLE
water totem 7/8 quest bugged

### ISSUE THREAD

**Issue by idri2idri3kkk** [SunstriderEmu/BugTracker#4174]
Call of Water (Part 7) bugged out on me. In this quest you need to kill a corrupt water elemental, get his bracer, then talk to a brazier to complete the quest. After the quest is completed, a "purified" water elemental spawns that gives you a new quest (Call of Water (Part 8)). That NPC don't spawned for me, 
I try to reset it serveral times but nothing, my sapta is out, What can i do now ? 
I get back in the barens, asked for another sapta, get back again in altar at brazier, try  to fix it but nothing.

**Comment by Jerrythemagicdog** [comment]
Which part doesn't work correctly for you? I've tested the quest recently and after completing the quest at the brazier the elemental spawns along with some lights around him.
