### ISSUE TITLE
I didn't get the gold from the auction house

### ISSUE THREAD

**Issue by ludamm** [SunstriderEmu/BugTracker#4175]
482/5000
well I think my problem is simple I just want to know why it happens and a quick solution.
In conclusion, the gold from the sale of some materials ([Hardened Adamantite Tube] [Hardened Adamantite Bar]) in the auction house, when I collected the gold by mail and selected the gold, I did not recognize it in my bag, I DID NOT RECEIVE THE respective GOLD for the sale of material. I don't know if it will be a bug, I know it is little but it works.
That would be all my problem. I would appreciate your answer. Thank you.

**Comment by Jerrythemagicdog** [comment]
What's your character's name?

**Comment by ludamm** [comment]
Mercnario ( elf warr)

**Comment by Jerrythemagicdog** [comment]
Here are some instances in the recent past of you selling those items and receiving gold
![image](https://user-images.githubusercontent.com/46463908/92319542-59cdef00-f011-11ea-8deb-a6347813640b.png)

**Comment by ludamm** [comment]
They were two of 96 coins that did not add up in my bag. I just asked some friends and one told me that it happened to him that it was like a visual bug and that after a while after re-entering the gold would be.  But so far nothing and I know that I take into account what I have because I don't have much either so no, at that time I had 320 if it was little maybe it would not have passed me but 190 I think the sum would be obvious
