### ISSUE TITLE
Inspecting and Spirit Healer

### ISSUE THREAD

**Issue by KoRn5979** [SunstriderEmu/BugTracker#4176]
Whenever I inspect someone and click on their talents, it shows a complete other class. Its really weird.

The Spirit Healer in all BG's doesn't effect my Arcane Intellect. It's supposed to reduce the cost of spells by 100% for like 5 sec after you revive. But when I cast AI, it still takes 700 mana away from me.

**Comment by Jerrythemagicdog** [comment]
1. Seems like an addon issue, if you provide a screenshot maybe we'll be able to identify it.

2. Your max mana is increased, the spell doesn't cost anything.
