### ISSUE TITLE
Relearning Professions?

### ISSUE THREAD

**Issue by ErnieAnders** [SunstriderEmu/BugTracker#4177]
I accidentally unlearned my Tailoring profession and now can't use my Primal Mooncloth set. I unlearned it last week, but I didn't notice until I got on this morning. Is there a way to relearn professions like retail WoW? It just feels terrible to have lost hundreds of hours of [play just for one stupid mistake.

**Comment by Jerrythemagicdog** [comment]
No such functionality in TBC, sorry!
We could add something like it but at the same time players are able to for example Enchant their rings and drop enchanting in favour of something else which is a part of the game and is a gold sink which we want to keep.
