### ISSUE TITLE
BM hunter tallent  [Ferocious Inspiration] stop working

### ISSUE THREAD

**Issue by AntoniYo** [SunstriderEmu/BugTracker#4178]
**Describe the bug**
Tallent  [Ferocious Inspiration]  in BM spec stops working until today.

**To Reproduce**
1. Take tallent  [Ferocious Inspiration] in beast mastery tree
2. Send pet to attack any target
3. After every crits of pet, buff [Ferocious Inspiration] dont shows at all

Spell: https://db.endless.gg/?spell=34460

**Expected behavior**
buff must be place on your pet, player and all in your grp

**Comment by DwarvenJoe** [comment]
Doesn't proc frenzy either

**Comment by DwarvenJoe** [comment]
Tested further, go for the throat doesnt proc on crits either and just for the heck tested the hourglass trinket and it also does not apply the buff after crits so it appears nothing that is applied after crits work currently atleast not for hunters.

**Comment by bjh368** [comment]
Haven't tested the BM talents reported here but I can at least say that Survival talents Thrill of the Hunt and Expose Weakness and MM talent Go for the Throat are working as they should.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.
