### ISSUE TITLE
ssc, flk quest mob despawns

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4179]
the in ssc, the flk quest mob for the bt attunment despawns at some point within an hour or 2 of killing flk + questing it (no idea what happens if you just kill flk and dont quest).  at some point later (within the next 20 hours) it respawns (the quest mob)

i assume its despawning with all the trash linked to flk and then a later respawn cycle respawns the quest mob.  

maybe don't despawn the quest mob.

**Comment by Jerrythemagicdog** [comment]
Thanks, we're not going to despawn him with next update.
