### ISSUE TITLE
pally power addon

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4180]
When you go out of a certain range from members of your group or raid, pally power somehow loses knowledge of those buffs and when you come back into range its not updated.  

This has always been a peculiarity of endless. I'm not asking you guys to fix pally power, but i did not have this problem on warmane or other servers i have played on so maybe the server stops transmitting information to people x yards away and maybe you could bump that up to in the same zone or always to everyone in the same raid/group or i dunno...  

this is really annoying all the time but especially in hyjal where i buff the raid, then go and drop consecrates on the trash mobs as they path to jaina/thrall.  when i get back i usually spot buff the dead people, but since pally power is telling me no one has my buffs, I have no idea who to buff.  i have to try and individually remember each and every person who died in the previous wave or at least each class and well... it works on other servers so i assume it could work here if you have time.

**Comment by Jerrythemagicdog** [comment]
This was fixed earlier today have you tried it?

**Comment by Jerrythemagicdog** [comment]
https://endless.gg/changelog/2020/09/05

> Fixed aura information not being sent correctly when the unit having the aura enters viewer's distance again (fixes issues with addons like Pally Power).

**Comment by kelno** [comment]
Fixed again with next server update, I did an oopsie that broke it again.

**Comment by michaelkittrell** [comment]
awesome guys thanks a ton!
