### ISSUE TITLE
Black Bow of the Betrayer on hit effect not working properly

### ISSUE THREAD

**Issue by bjh368** [SunstriderEmu/BugTracker#4181]
They way it should work: "On Successful ranged attack gain 8 mana and if possible drain 8 mana from the target." (exact wording on tooltip)

Meaning **always gain 8 mana per hit**. Right now, as far as I can tell through testing, it only gives the 8 mana on **a killing blow**. Which is obviously wrong.

Weirdly enough, the "if possible drain 8 mana from the target" part seems to work just fine, in that the target loses mana on every hit. It's just not given to the shooter unless the target dies from that particular shot.

This bow is supposed to give 40-50 mp5 during a bossfight, which is pretty significant, and now it gives nothing.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
