### ISSUE TITLE
Ashenvale zone keeps dc'ing my character

### ISSUE THREAD

**Issue by Martolqa** [SunstriderEmu/BugTracker#4182]
Hello, i tried to go to felwood from ashenvale with my character named Qaj when i got 1st dc and since then i wasnt able to login, my wow crashed on loading screen everytime i tried to enter, however i was able to login with my other character which is on the same account, i played with it quite some time, then tried again to login with Qaj and still same errors, wrote ingame ticket and GM moved my character to shatt, when i got back to ashenvale my wow crashed again and wasnt able to login, GM moved it again to shatt and no more errors, so i think the problem is with that zone. 1st time it happened to me, i leveled my character there back then and there wasnt any problem but now ashenvale zone keeps crashing my wow.

**Comment by Jerrythemagicdog** [comment]
Download another client, this is not something we control, sorry.
