### ISSUE TITLE
Mobs hit in rogues CS open

### ISSUE THREAD

**Issue by SviatP** [SunstriderEmu/BugTracker#4183]
**Describe the bug**
Mobs hit before rogues CS

**To Reproduce**
1. Cast stealth and get to mob behind (use Distract if needed)
2. Cast Cheap Shot
3. U got hit whereas mob is stunned

**Expected behavior**
Mob stunned without hitting you

**Screenshots/videos**
![1](https://user-images.githubusercontent.com/26345286/92374105-f8d51280-f107-11ea-9cfe-25e7473c73fd.jpg)
![2](https://user-images.githubusercontent.com/26345286/92374101-f83c7c00-f107-11ea-8335-cdfb21e098ab.jpg)

**Additional context**
Sometimes its critically, in case if mob can stun/fear you. For example - Clefthoof in Nagrand. All the time u get a stun and have no possibility to kill it for stun lock.

**Comment by kelno** [comment]
Thanks for reporting!
We're experimenting with spell delay in PvP situations, I've made a change so that this doesn't apply in a PvE setting like described here. Applied with next server update.
