### ISSUE TITLE
New database doesn't highlight unusable weapons and armor in red

### ISSUE THREAD

**Issue by Massie323** [SunstriderEmu/BugTracker#4184]
**Describe the bug**
I think the issue started when I deleted the WDB cache for the heroic keys rep update. Normally, any weapon/armor that your character has no proficiency in should be highlighted in red, while also marking the weapon/armor type in the tooltip as red (i.e. Mail for priests).
This however is not the case anymore, and only a level that is not met will be marked up as red and unusable. Any weapon/armor type will appear as usable until you attempt to equip it and the error message tells you "Your character does not have the proficiency to wield this weapon."

**To Reproduce**
1. Delete the WDB cache if you have a version prior to the keys update
2. Notice that no unusable equipment will be highlighted in red unless it's too high level.

**Expected behavior**
Equipment that you cannot currently wear should be highlighted in red with the conflicting attribute being marked in red.

**Screenshots/videos**
 - Hovering over an item
![image](https://user-images.githubusercontent.com/57675820/92387998-cf6fb300-f116-11ea-9d25-5f587d983d3f.png)
 - Attempting to equip it
![image](https://user-images.githubusercontent.com/57675820/92387968-c1ba2d80-f116-11ea-9f67-2da858f934ba.png)

**Additional context**
Even downloading a fresh client does not solve the issue, since it simply redownloads a fresh faulty WDB folder.

**Comment by kelno** [comment]
Thanks for reporting, that's a new one!
Fixed with next server update
