### ISSUE TITLE
Mail, plate, 1h & 2h axes and more

### ISSUE THREAD

**Issue by Joffre23** [SunstriderEmu/BugTracker#4186]
**Describe the bug**
For a rogue i have is not possible to wear mail, plate or axes, but in bagpack it seems like i can until you click on it to wear it. After that the game write to you its not for you and you dont have the spec for it. In auction you can't see it if you choose items valuable for you but if you look for it without check button for aviable things for you, there you can see it light and it is displayed that you can wear it, but you can't. I turn off all addons and clear cache but its not working.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
