### ISSUE TITLE
Blackfang tarantula loot table/window not working

### ISSUE THREAD

**Issue by MianLavanAelin** [SunstriderEmu/BugTracker#4188]
**Describe the bug**
blackfang tarantula https://db.endless.gg/?npc=18983 cannot be looted 

**To Reproduce**
1. Kill, try to loot, fail(tried as alliance) 

**Expected behavior**
it has loot

**Comment by Jerrythemagicdog** [comment]
Outside of a small chance for some grey items it doesn't drop anything.
It won't drop the Spider Silk if that's what you're looking for which is intended for us.
Thanks for the issue.
