### ISSUE TITLE
[#37] Quest Mission: Gateways Murketh and Shaadraz

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#419]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Tuesday Dec 11, 2018 at 10:57 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/37_

----

Current behaviour:
Then Gateway of Shaadraz doesn't give quest credit when killed by the bomb

Expected behaviour:
It should give quest credit when bombed

Steps to reproduce the problem:
Step 1: Do the quest Mission: Gateways Murketh and Shaadraz
Step 2: Bomb Gateway of Shaadraz, watch as you get no credit
![wowscrnshot_121118_205532](https://user-images.githubusercontent.com/45530324/49796023-497ad880-fd87-11e8-9181-fb123a9b632c.jpg)

**Comment by kelno** [comment]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [BarrensJerk](https://github.com/BarrensJerk)**
_Saturday Jan 26, 2019 at 12:53 GMT_

----

After bombing one objerct and getting credit it seems like the other gate gets phased or something so dropping bomb on second gate doesn't trigger completing that part of the quest. Once the quest is abandoned and picked up again, both gates reappear and one can be bombed, but not the second.

**Comment by kelno** [comment]
<a href="https://github.com/BrockSamson1"><img src="https://avatars3.githubusercontent.com/u/46757539?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [BrockSamson1](https://github.com/BrockSamson1)**
_Saturday Jan 26, 2019 at 15:18 GMT_

----

Confirming this interaction as above. Also unable to complete this quest

**Comment by kelno** [comment]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [BarrensJerk](https://github.com/BarrensJerk)**
_Tuesday Jan 29, 2019 at 10:53 GMT_

----

Identical behaviour on alliance and horde versions
Alliance quest 10146
Horde quest 10129
The objects in game that make the gates are mislabelled, when you hover over Shaadraz it says that name but when you bomb it, you get quest credit for bombing Murketh. Then you can't bomb Murketh, it phases out and even hitting it wouldn't give quest credit for the gate you already bombed.

**Comment by kelno** [comment]
<a href="https://github.com/SUN-Leekie"><img src="https://avatars0.githubusercontent.com/u/18554785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SUN-Leekie](https://github.com/SUN-Leekie)**
_Saturday Feb 02, 2019 at 04:54 GMT_

----

@kelno 
Fixed by https://github.com/kelno/sunstrider-core/commit/717f826c90e431bb7d27fac62b51d1cbbbbc09b9
I guess you'll want to move the code in SpellScript or something but I'd rather let you do it since I'm not so sure where to put it and how to rewrite it cleaner.
Also: 
* both the gameobjects have the flag `GO_FLAG_NODESPAWN`, yet they still despawn
* the credit is given as soon as the spell is launched instead of on spell hit. I tried to add a SmartAI script to the gameobject and the kill credit creature to trigger the kill credit on spellhit but that never worked hence the C++ script.

```sql
-- NPC 19291- Legion Transporter: Alpha (credit Murketh)
SET @ENTRY = 19291;
UPDATE creature_template SET AIName='SmartAI', ScriptName='' WHERE entry = @ENTRY;
DELETE FROM smart_scripts WHERE entryorguid = @ENTRY AND source_type = 0;
INSERT IGNORE INTO smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_flags, target_param1, target_param2, target_param3, target_x, target_y, target_z, target_o, comment) VALUES 
(@ENTRY, 0, 1, 0, 8, 0, 100, 0, 33655, 0, 0, 0, 33, 19291, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'Legion Transporter: Alpha - On Spellhit "<a href="http://wowhead.com/spell=33655">Dropping The Nether Modulator</a>" - Quest Credit "<a href="http://wowhead.com/quest=19291">Legion Transporter: Alpha</a>" ');

-- GO 183350  - Gateway Murketh
SET @ENTRY = 183350;
UPDATE gameobject_template SET AIName='SmartGameObjectAI', ScriptName='' WHERE entry = @ENTRY;
DELETE FROM smart_scripts WHERE entryorguid = @ENTRY AND source_type = 1;
INSERT IGNORE INTO smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_flags, target_param1, target_param2, target_param3, target_x, target_y, target_z, target_o, comment) VALUES 
(@ENTRY, 1, 1, 0, 8, 0, 100, 0, 33655, 0, 0, 0, 33, 19291, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'Gateway Murketh - On Spellhit "<a href="http://wowhead.com/spell=33655">Dropping The Nether Modulator</a>" - Quest Credit "<a href="http://wowhead.com/quest=19291">Legion Transporter: Alpha</a>" ');
```

There are still cosmetic stuff to do on this quest tho:
* Deactivate/unspawn the fire gameobjects on Gateway Murketh
* Activate/respawn the fire gameobjects on spell hit for some time (a minute?)

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Saturday Feb 02, 2019 at 13:46 GMT_

----

Thanks!

**Comment by kelno** [comment]
<a href="https://github.com/zemfi"><img src="https://avatars1.githubusercontent.com/u/46832429?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zemfi](https://github.com/zemfi)**
_Thursday Feb 07, 2019 at 03:20 GMT_

----

Can confirm in .rev 10392 you can complete this quest, but as leekie mentioned, the the graphics/game objects still need to be fixed (just shadows on the ground).

**Comment by Jerrythemagicdog** [comment]
Confirmed, the gateways disappear instead of activating the fire GameObjects next to them.
To dev:
` 33655: // Dropping the Nether Modulator`

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed

**Comment by kelno** [comment]
also https://github.com/kelno/sunstrider/commit/15b689260b711bc6a83e76b775ac74ec7819b47e
and https://github.com/kelno/sunstrider/commit/e7ec6b62f7041468359e6f8d8e0fd744cde79c2f
