### ISSUE TITLE
MELEE DAMAGE REDUCED

### ISSUE THREAD

**Issue by Shamiroquai** [SunstriderEmu/BugTracker#4191]
Melee Damage reduced.

Today i figer it out that my damage as melee its beed reduced with no reason, i never have this problem. Oh btw im Shaman Enhancement, and this problem its big, to be precisly my damage before was 615 - 846 (melee stats) with WF buffs on both weapons, and with rockbiter goes to 900 -1100 (melee stats) . NOW my damage is 475 to 600!!!! Whats the problem here? i see my DPS and DAMAGE DONE so low!

1. i equip my gear and see the Damage so low
2.  cant fixed by my self
3.  its been a very big problem for me

**Expected behavior**

**Comment by beraus** [comment]
You prolly want to check this bug report: https://github.com/SunstriderEmu/BugTracker/issues/3760

**Comment by Shamiroquai** [comment]
> You prolly want to check this bug report: #3760

DOESNT WORK. this not solve my problem.
