### ISSUE TITLE
Rockbiter wep on offhand does NOTHING. 

### ISSUE THREAD

**Issue by Doodlewang** [SunstriderEmu/BugTracker#4192]
Currently applying rockbiter wep on an offhand for a shaman does NOTHING.

Ever since the update last night of rockbiter stacking it has also had the effect of making rockbiter on an offhand not apply the buff at all.

**Comment by Jerrythemagicdog** [comment]
![image](https://user-images.githubusercontent.com/46463908/92575366-25139f00-f280-11ea-830d-68c78d74f7f0.png)

**Comment by Doodlewang** [comment]
If you look at your image you have 2 rockbiter effects on.  One on your main hand and one on your offhand.   
Right click off the main hand and you will see the one left on your offhand does nothing.

**Comment by Jerrythemagicdog** [comment]
![image](https://user-images.githubusercontent.com/46463908/92580701-9fdfb880-f286-11ea-99e9-d70a20530777.png)

**Comment by Doodlewang** [comment]
Okay im ret
