### ISSUE TITLE
DAMAGE ALMOST 50% less

### ISSUE THREAD

**Issue by Shamiroquai** [SunstriderEmu/BugTracker#4194]
**Describe the bug**
The solution this team give me, doesnt work, im playing on shamn long ago, and i know the Rock bitrer thing, and WF change weapons and stuff.. BUT now, my damage go down and no solution. FIX my problem

THIS SOLUTION DOESNT FIX MY PROBLEM : 

Rockbitter and windfury Weapons stacking up
Just apply Rockbitter first to ur both or 2h weapon then unequip them Afterwards equip ur weapon back then change it to wf then unequip and equip again just to make sure it worked but in that time u prob already has an melee increase dps from rockbitter and wf.

**Comment by Jerrythemagicdog** [comment]
This bug was fixed, those no longer stack.
