### ISSUE TITLE
There is a spot in desolace that you get stuck in a hole you can't walk or jump out of.

### ISSUE THREAD

**Issue by Twistedpower** [SunstriderEmu/BugTracker#4196]
I went to mine a node of mithril and fell into a small indent in the ground that you cannot climb out of. I had to hearth out. It is right by the boarder of desolace and stone talon

 mountains.  Here is a screen shot of the location and of me in the hole. 

![WoWScrnShot_091020_174449](https://user-images.githubusercontent.com/20755364/92812970-4d89bf00-f38e-11ea-8231-39a9760f8301.jpg)

https://i.imgur.com/yxWNhzv.jpg

**Comment by Sheikthecatman** [comment]
Thanks! Our construction team were ordered to fill up the hole with concrete from another time line, the roads should now be safe and less bumpy! 

Fix live next server restart.
