### ISSUE TITLE
Kidney Shot wrong DR timer

### ISSUE THREAD

**Issue by Kalisss** [SunstriderEmu/BugTracker#4199]
**Describe the bug**
Kidney Shot has different DR timer. Endless is supposed to have 18 sec DR flat. KS has 20 sec cd. If I use second KS right when it is off cooldown, there is DR. 

**To Reproduce**
1. Use 5CP Kidney Shot
2. Use second 5CP KS right when it is off cooldown.

**Expected behavior**
If the DR is set to 18 sec, KS should not be on DR when you use it second time as it has 20 sec cooldown.

**Comment by Jerrythemagicdog** [comment]
DR is calculated from the time the effect ends.
