### ISSUE TITLE
Darkmoon Card: Madness

### ISSUE THREAD

**Issue by Sergejovic** [SunstriderEmu/BugTracker#4200]
Hello, please trinket Darkmoon Card: Madness works badly in the party. He should give a buff for killing a mob that should give experience, but in a party he gives a buff only for a mob that I kill and as a tank I kill 2 mobs for a dungeon. on all other servers as well as on the official one when TBC was working in the group so that by killing the mob anyone by anyone gave a buff. Can you look at it, please? At the moment when he gives buff only when killed by me (tank), then it is useless

**Comment by Jerrythemagicdog** [comment]
Yes, the trinket only works for your killing blows.
It works as intended.
https://wowwiki.fandom.com/wiki/Darkmoon_Card:_Madness
https://www.wowhead.com/item=31859/darkmoon-card-madness#comments

If you've got evidence to support what you're saying feel free to post it here (that's not clips of other private servers).
