### ISSUE TITLE
Can't turn in a quest when buying some required items from AH

### ISSUE THREAD

**Issue by rossb-btw** [SunstriderEmu/BugTracker#4201]
**Describe the bug**
Doing the epic flight form quest chain. Need to get 10 bogblossom, 10 ancient lichen, 10 dreaming glory. Bought the lichen and dreaming glory on the auction house, and picked the bog blossoms on top of the mushrooms. quest log says complete. quest giver still shows the gray question mark and i am unable to turn the quest in.

**To Reproduce**
1. Be a level 70 nelf druid with epic flying 
2. accept the "The Ward of Wakening" quest
e. collect the stuff in the quest
4. try to turn it in

https://www.wowhead.com/npc=22832/morthis-whisperwing

**Expected behavior**
I can turn the quest in given i have completed the quest

**Additional context**
I am sad i can't turn the quest in

**Comment by Jerrythemagicdog** [comment]
Thanks, what's your in-game name?

**Comment by rossb-btw** [comment]
Xylem.

FWIW i was able to resolve the issue by mailing the dreaming glory and
ancient lichen to an alt then mailing it back. So there must be a bug with
the receipt of items rather than the quest itself.

I bought the lichen and dreaming glory off the auction house so i received
the items all at once. Not sure if that helps.

**Comment by Jerrythemagicdog** [comment]
This helps a lot, thank you.

**Comment by Jerrythemagicdog** [comment]
Do you remember if you bought the items in many stacks from separate sellers and what were the stack sizes?

**Comment by rossb-btw** [comment]
Separate sellers. Two stacks of five dreaming glory. One stack of 15
ancient lichen

**Comment by Jerrythemagicdog** [comment]
More details from another player:

> Oh hey, yes i bought the 4 Heavy Knothide Leather and like 3 Adamantite Frames from the AH. Then split 1 Frame off and sold the other two on the AH again. The other item I bought from the Vendor in Shattrath. I use Bagnon and Auctioneer. What fixed it for me was abandoning the quest and accepting it again, didnt think of this option until later.. ^^

**Comment by Massie323** [comment]
Put the items in the bank then take them back and it will usually fix that issue. It happens with other quests that require x amount of items, sometimes even with soulbound items.

**Comment by kelno** [comment]
Fixed since! Thanks for reporting.
This doesn't fix the issue retroactively though so if you already had the issue before it was fixed, you can put the items in bank and get them back as suggested by Massie323.
