### ISSUE TITLE
Too high melee damage or resilence not working properly

### ISSUE THREAD

**Issue by Draqq** [SunstriderEmu/BugTracker#4202]
Hey. I see too high melee damage. When I played on the official server in 2007, there was no such damage and there were no too frequent critical hits. Here is a link to a video with timecode https://youtu.be/nTCgTEh40T8?t=1019 you can watch the whole video and understand what the damage was on the official server. On WOW endless melee damage is very high.

I also noticed that sometimes I hit at a slick distance. The target ran very far 30 meters, but I dealt 1-2 hits and the damage went

**Comment by Jerrythemagicdog** [comment]
If you get CCed or lose control of your character in any other way and you've done an attack your client will display the latest attack you've done when you're able to control your character again regardless of range, no damage is actually done.

As to damage being high, there is no evidence to support that, quite the contrary after a quick search:
https://youtu.be/aSMWQcLDKgo?t=180
https://youtu.be/xF4Rx1sQYQU?t=539

We'll gladly accept some serious breakdown or proof as to why something is wrong that's not anecdotal evidence and comparisons to old memories.
