### ISSUE TITLE
Alterac Valley Graveyards Bug/Cheating

### ISSUE THREAD

**Issue by Cayman91** [SunstriderEmu/BugTracker#4203]
**Describe the bug**
When AV started, both graveyards (ally and horde) near final bosses were take by enemy faction. GY near Drek was allies, GY near Vann was horde. It happened on Sun 13/09 ~10:00 ST. When reached to the Ally base (~1min since start) there were already 3 horde there: Taujaro, Brocklesnar, Jackedripper. They either abused the bug or used some cheats to get there. It's impossible ot get there within that quick period of time. 3 screenshots below.

**To Reproduce**
No idea
1. Join AV

**Expected behavior**
Both GY are taken by respective side.

**Screenshots/videos**
https://postimg.cc/gallery/cgM1pwX

**Additional context**
This is either some kind of a bug or someone cheated. However, if you check 1st ss, there are no allies that reached horde based yet while on Allies base there were already 3 horde players.

**Comment by Jerrythemagicdog** [comment]
Thanks, the players got to keep their Stormpike Insignia / Frostwolf Insignia after faction changing until the next relog.
