### ISSUE TITLE
Teron Gorefiend Quests bugged

### ISSUE THREAD

**Issue by Sai0777** [SunstriderEmu/BugTracker#4206]
On "Teron Gorefiend - Lore and Legend" the Shadowmoon Ancient does not spawn (probably doesn't spawn in general).  Have Goggles, tried restarting the quest, etc.  Teron Gorefiend himself is at the Altar, but that's it.

**Comment by Jerrythemagicdog** [comment]
The NPC resets after some time, he's in his correct form right now on the live server.
![image](https://user-images.githubusercontent.com/46463908/93019688-81ecbd80-f5d0-11ea-9372-20e682a8c980.png)
We've found a potential issue though, thanks!
