### ISSUE TITLE
combat bug

### ISSUE THREAD

**Issue by tbc123** [SunstriderEmu/BugTracker#4208]
**Describe the bug**
i found biggest bug with combat on this server if u got combat u suck in cobat 6,5 seconds.

**To Reproduce**
When a character attacks or is attacked, they will be flagged by the game as being in combat. This state is denoted to the player with an icon of two crossing swords next to their character portrait. Many actions and abilities cannot be used while you are in combat, making knowing how to get into and out of combat very important, especially in PvP combat.

In PvP, a player will leave combat if they have not attacked or been attacked for 5 seconds, or all the enemy characters that have attacked you are killed.

https://wowwiki.fandom.com/wiki/Combat

**Comment by Jerrythemagicdog** [comment]
I've linked this in a previous issue: https://endless.gg/changes
Please stop making pointless issues.
