### ISSUE TITLE
Pets will sometimes resurrect without their talents (avoidance, resistances, etc.)

### ISSUE THREAD

**Issue by cmurda26** [SunstriderEmu/BugTracker#4209]
**Describe the bug**
When your pet dies, sometimes when you res it the pet will NOT have its talents. 

**To Reproduce**
1. Have your pet die and res it as many times as it takes to reproduce
2. You will notice no resistances on it at all. Dismiss the pet and resummon and it will come back out. Obviously very gamebreaking on bosses.
3.

**Comment by artieau** [comment]
See #2352 @Jerrythemagicdog

**Comment by Jerrythemagicdog** [comment]
Reproduce steps:
1. Kill the pet
2. Teleport to another map
3. Revive the pet
After this step you'll be required to resummon the pet for the auras to appear again.

**Comment by Ironjudgment** [comment]
Still an issue

**Comment by Massie323** [comment]
I would like to add that this essentially makes or breaks a fight for a BM hunter for certain bosses.
For example on P3 Illidan, should your pet die for any reason (i.e. Flame Crash), you need to spend 4 seconds to rez it back up and another 5 seconds to dismiss it + the GCD from summoning it again. And if you transition into P4 during those sequences, you are essentially shit out of luck, as the Flame Burst will oneshot your pet again without resistances and avoidance, while Illidan's Aura of Dread will also do "double" damage to it each tick, basically nuking your pet's happiness and forcing you to play petless for that individual phase.

**Comment by kelno** [comment]
Thank you, fixed with next update
