### ISSUE TITLE
Grandmaster Vorpil - Shadow Lab (H)

### ISSUE THREAD

**Issue by Nostaglicdude** [SunstriderEmu/BugTracker#4211]
We were doing Grandmaster Vorpil in Shadow Lab on heroic mode. Before today, the void walkers were moving at a slow pace which is the correct way. However, today, they were moving at a super high speed which was not normal at all. The boss managed to get up to 10 stacks of their buff which is uncalled for.

**Comment by Jerrythemagicdog** [comment]
Fixed with next update.
https://github.com/SunstriderEmu/BugTracker/issues/4210
