### ISSUE TITLE
Nightmare vine spawn points and spawn time

### ISSUE THREAD

**Issue by MianLavanAelin** [SunstriderEmu/BugTracker#4212]
**Describe the bug**
Herb gathering nightmare vine is nearly impossible for personal use and without botting, issue is with number of spawn points, their spawn time, number of allowed spawns in a pool(if you have pooling) and possibly other pooling issue as well. 

For example dreaming glory should not share spawn points with other herbs in the zone(wowhead map source) and possibly should be outside the main pool because of netherwing island. 
Shared spawn point pool between felweed and nightmare vine have some same spawn points based on map sources, but here very likely the nightmare vine should have higher prio, as it is herb of this zone as again, no recolections of anyone from offi, that shadowmoon is felweed zone or other such stuff, nightmare vine should really be dominant and plentyfull. 

This is pretty clear based on the AH prices and the fact that there is no mention of this being ultra difficult herb to gather on any forum from TBC. Same issue applies to netherbloom, but that deserves its own report if you want to address these issues. 

https://www.wowhead.com/object=181280/nightmare-vine

**Expected behavior**
Blizzard did not update in any way the herbs spawns in outland after TBC/WOTLK(unlike with Azeroth where they changed the behaviour) so the objects you can see on wowhead, are true data that did not change since TBC, another proof is addon called MobMap database, dating back to TBC era, which also gathered ingame data during TBC. 
https://i.imgur.com/Qd2gOOG.jpg screenshot from the addon. It corresponds with the wowhead data. 

**Additional context**
If you are willing to address this issue, but don't have the manpower, we can talk on Discord, I can fix it for you if you provide binaries and db structure with template tables etc.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, I believe that's just spawn points missing.
We are going to import Gatherer data for all herbs at some point in the future as we've done already for mining ores which should fix the problem and correct other inconsistencies as well.

**Comment by Jerrythemagicdog** [comment]
If you're bored and interested in this sort of stuff contact me on Discord because importing most likely won't happen in the near future and we might be able to solve this problem temporarily.

**Comment by Jerrythemagicdog** [comment]
Fixed with next update by @MianLavanAelin
