### ISSUE TITLE
PVP trinket or gladdy Bugged 

### ISSUE THREAD

**Issue by tbc123** [SunstriderEmu/BugTracker#4213]
clip from
https://www.twitch.tv/despqq/clip/MoldyPopularQueleaRaccAttack?filter=clips&range=7d&sort=time

**Comment by Jerrythemagicdog** [comment]
Disable Trinket Tracker in Gladdy options, tell the same to your partner.

**Comment by tbc123** [comment]
okay if he didint have trinket tracker.lua

**Comment by tbc123** [comment]
![image](https://user-images.githubusercontent.com/46471537/93105093-50025680-f6b7-11ea-92cc-798d59eb55e7.png)

**Comment by Jerrythemagicdog** [comment]
Then he's the only person on the entire planet with this problem because everyone else who has it disabled has no such problems.
