### ISSUE TITLE
S1 Shields Missing from Vendor in Hall of Legends?

### ISSUE THREAD

**Issue by nhthor** [SunstriderEmu/BugTracker#4214]
I see only one shield available from the Weapons Quartermaster "Sergeant Thunderhorn" and that is the Gladiator's Shield wall. If I am correct there should be 2 other shields (caster shield and healer shield) but they aren't listed. I sent message to GM and they said to track the bug.

**Comment by Jerrythemagicdog** [comment]
There are no healer shields or spell damage shields in Season 1, the items don't exist until Season 2.
