### ISSUE TITLE
Missing spell from Enchanting trainers.

### ISSUE THREAD

**Issue by Zomrizubo** [SunstriderEmu/BugTracker#4215]
**Description:** The spell to turn a Nexus Crystal into a Small Prismatic Shard was supposed to be added in 2.2 - Trainable by the enchanting trainers in hellfire, and the scryer enchanting trainer on scryer rise.

**Nexus Transformation [Spell] [Enchanting]**
This spell was introduced in patch 2.2 with a 2 day cooldown. In patch 2.3 this cooldown was removed.

**Taught by:**
Horde - Felannia in Hellfire Peninsula.
Alliance - Johan Barnes in Hellfire Peninsula.
High Enchanter Bardolan in Shattrath City.

**Current behaviour:** Not able to be trained.

**Source:**
https://wowwiki.fandom.com/wiki/Nexus_Transformation

**Comment by Rettiy** [comment]
Probably analogically #3954 up to your decision

**Comment by Sheikthecatman** [comment]
Thanks! The spell should be available next server restart!
