### ISSUE TITLE
[Quest] Wanted: Nazan's Riding Crop does not give reputation

### ISSUE THREAD

**Issue by Cayman91** [SunstriderEmu/BugTracker#4216]
**Describe the bug**
When returning the quest to npc it should give the following reputation: +350 Honor Hold / Thrallmar and +350 The Consortium. Currently, it does not provide any reputation, only gold and BoJ.

**To Reproduce**
1. Kill Nazan, get quest item.
2. Return the quest to NPC.
3. Do not receive reputation.

Quest: https://tbcdb.com/?quest=11354
Faction: https://tbcdb.com/?faction=933
Faction: https://tbcdb.com/?faction=946

**Expected behavior**
It should give BoJ + Gold + 350 Honor Hold / Thrallmar +350 The Consortium

**Screenshots/videos**
https://i.postimg.cc/43660dmH/Wo-WScrn-Shot-091520-202720.jpg (chat)

**Additional context**
I have also asked other party member and he also did not receive the repu.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
