### ISSUE TITLE
[General] Chain effects should not chain behind player

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#4218]
**Describe the bug**
https://github.com/SunstriderEmu/BugTracker/issues/1668
Marked as fixed and after half a year still broken.

https://github.com/SunstriderEmu/BugTracker/issues/2069

https://youtu.be/4SLLsjYfTxo?t=21

**Comment by kelno** [comment]
Fixed for the critter part

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
