### ISSUE TITLE
[General] Chain effects do not chain behind LoS or when main target is killed

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#4220]
**Describe the bug**
https://github.com/SunstriderEmu/BugTracker/issues/1667
https://github.com/SunstriderEmu/BugTracker/issues/2646

https://youtu.be/4SLLsjYfTxo

**Expected behavior**
LoS should not be checked with player but with target. 
Chain effects should NOT ignore line of sight completely. LoS should be checked with main target, not with player -> If hunter multi-shots pet and pet (as main target of multishot) is in LoS with any other player then multi-shot/chain lightning should jump, if the second enemy player was in LoS with 3rd or 1st enemy player it should jump again. 
(Thats how the good servers had it and thats how I interpret it). If you agree with me or not it is irrelevant, either way current state is not blizzlike.

**Screenshots/videos**

https://www.youtube.com/watch?v=VhCI3DDvGGU&start=733
Chains on priest that is out of LoS with player

https://youtu.be/m8nOaNMHZIQ?t=332
Hunter gets error message "Target(mage) not in line of sight", targets water ele and multi shot chains on mage

**Additional context**
https://www.twitch.tv/scopemeup/clip/SpeedyPlausibleCardImGlitch
It worked correctly untill some player, clueless of blizzlike mechanic, cried to clueless/lazy? member of dev team and it got "fixed". You could literaly search your own bugtracker and find the video I linked...

Id like to ask you, in case this doesnt get fixed that it gets listed under custom changes. Thanks.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, no need to open new ones though:
#1667
#2646

**Comment by bluemanguy112** [comment]
Those reports are over half a year ago though. Is there any ETA on a fix? Considering the clip above shows that it was once in working condition, it can impossibly take this long.
