### ISSUE TITLE
Our raid did not receive loot because the boss bugged.

### ISSUE THREAD

**Issue by FoxyLOVEyou** [SunstriderEmu/BugTracker#4221]
Hi. We beat the boss in Karazhan with a guild. I was a raid leader, I have 5% of my boss lives, I knocked out the Internet. I immediately re-logged in and the boss was already dead. After entering the game, when distributing loot, I did not see anyone on the list of those to whom I can give things. I tried to change loot for absolutely any type of split. Nobody could lift things, nor did the transfer of the leader to any other player help. He was getting exactly the same error. I am attaching a video in which this error is clearly visible. Help divide the loot.

Karazhan ID: 10272

Boss:
https://www.wowhead.com/npc=15690/prince-malchezaar

Items in loot: 
1) Helm of the Fallen Defender;
https://www.wowhead.com/item=29761/helm-of-the-fallen-defender

2) Helm of the Fallen Champion;
https://www.wowhead.com/item=29760/helm-of-the-fallen-champion

3) Helm of the Fallen Hero;
https://www.wowhead.com/item=29759/helm-of-the-fallen-hero

4) Gorehowl;
https://www.wowhead.com/item=29759/helm-of-the-fallen-hero

5) Adornment of Stolen Souls;
https://www.wowhead.com/item=28762/adornment-of-stolen-souls

The video showing the error itself:
https://www.youtube.com/watch?v=_6QnO2LxD6Y&feature=youtu.be

My nickname in the game is "Korostovtsy".

P.S. We hope for the good graces of the administration regarding this situation. Thank you for your attention. :)

**Comment by Jerrythemagicdog** [comment]
That's because you disconnected, open a ticket in game to get your loot.
