### ISSUE TITLE
Didn't recieve item after winning the loot.

### ISSUE THREAD

**Issue by Crunkie** [SunstriderEmu/BugTracker#4222]
**Describe the bug**

![WoWScrnShot_091520_231751](https://user-images.githubusercontent.com/71372291/93303801-b1840b80-f804-11ea-8e02-c6f81a24deba.jpg)
 Last night in Karazhan I won (need before greed) at trash mobs a pair of boots and because I had my bags full I didn't receive the feet.

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

I thouyght it will show up on my mail but it didnt'

**Screenshots/videos**

![WoWScrnShot_091520_231751](https://user-images.githubusercontent.com/71372291/93303801-b1840b80-f804-11ea-8e02-c6f81a24deba.jpg)
**Additional context**

**Comment by z5n** [comment]
unable to reproduce
