### ISSUE TITLE
Illidari Council: Server-client desynchronization of Veras Darkshadow model after Vanish phase exit

### ISSUE THREAD

**Issue by reyalphp** [SunstriderEmu/BugTracker#4223]
*Description*

Sometimes after quitting Vanish phase Veras is rendered incorrectly. We can see the rendered model at one point, but the serverside hitbox is, really, in the other place. This desynchronization is critical, in terms of boss encounter, because Veras can one shot random player in raid. Each 60 seconds, as we know, he unveils himself from vanish and stands for 2 seconds, then, attacking his target. The problem is, that if the clientside model is desynced with its actual serverside coordinates - it is unreal to point out his real position. This leads to tank being unavailable to taunt him, so Veras, not being taunted, kills any random player.

This issue happens like 1 time for 15. Examples listed below in the videos. Timecodes included.

*Videos*

https://youtu.be/Z45qxNlnL5s?t=4719

https://youtu.be/Z45qxNlnL5s?t=5924

https://youtu.be/Z45qxNlnL5s?t=6502

https://youtu.be/Z45qxNlnL5s?t=6683

https://youtu.be/Z45qxNlnL5s?t=10233

https://youtu.be/Z45qxNlnL5s?t=10292

https://youtu.be/Z45qxNlnL5s?t=10790

https://youtu.be/Z45qxNlnL5s?t=11720

**Comment by mechanicsTBC** [comment]
+1

**Comment by MianLavanAelin** [comment]
This issue is also very noticeable with the Ashtongue Defenders in the Shade of Akama fight. If you try charge/intercept while they are running towards akama, you charge to very different location than they appear to be.

**Comment by kelno** [comment]
I found the issue, will fix soon. The Ashtongue Defenders case is a different one though, but I'll try looking at it later, it's an issue in other places as well.

**Comment by kelno** [comment]
Pending internal testing as this is actually a big rework:
https://github.com/kelno/sunstrider/pull/189

**Comment by kelno** [comment]
Fixed and applied
