### ISSUE TITLE
Paladin

### ISSUE THREAD

**Issue by Mekinho7** [SunstriderEmu/BugTracker#4224]
Paladin can't remove sheeps and blind with Seal of Blood anymore due to your last update.
Also they can't use Blessing of Protection on their partner while they're blinded , normally they should can. 
Classes are totally unbalanced due to this bugs , may i ask you to fix this?

**Comment by Jerrythemagicdog** [comment]
Thanks, seal and judgement delays fixed with next restart.
Blessing of Protection is only usable on self if you're disabled.
