### ISSUE TITLE
In Dreams

### ISSUE THREAD

**Issue by StafordDev** [SunstriderEmu/BugTracker#4225]
**Describe the bug**

The quest doesn't work at all. Seems like it's not scripted since Highlord Taelan Fordring don't start moving after you accept the quest.
Also you can't get another disguise from Myranda the Hag if the one you've got from previous quest wears off. No dialogue.

**To Reproduce**

1. Do previous quests.
2. Accept "In Dreams".

NPCs: https://tbcdb.com/?npc=1842, https://tbcdb.com/?npc=11872
Quest: https://tbcdb.com/?quest=5944
Spell: https://tbcdb.com/?spell=17961

**Expected behavior**
A video from Vanilla WoW:
https://www.youtube.com/watch?v=QBHpy8an_p4
https://www.wowhead.com/quest=5944/in-dreams#comments:id=305 (first comment on Wowhead).
https://classic.wowhead.com/guides/tirion-fordring-questline-in-dreams-classic-wow - Guide on Classic version of Wowhead.

**Screenshots/videos**

https://ibb.co/7KsbTYs - Escort doesn't started.
https://ibb.co/Lgw2SQM - Can't get another disguise.
https://ibb.co/D4b2bpq - A proof from Wowhead about disguise (https://www.wowhead.com/quest=5944/in-dreams#comments:id=654636)

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
