### ISSUE TITLE
Instantly releasing after dying while under fear flies you to your corpse.

### ISSUE THREAD

**Issue by Massie323** [SunstriderEmu/BugTracker#4227]
**Describe the bug**
Within BGs (probably outside too), if you die while under the effect of Fear/Horrified/Disorient or any other random movement debuff and instantly release spirit, you will sometimes fly through the map towards your corpse as ghost.

**To Reproduce**
I'm not 100% sure if it's related to random movement debuffs or something else but:
1. Get deathcoiled
2. Die during the deathcoil on a specific server tick
3. Instantly release spirit (i.e. with DBM feature)

Spell: https://classic.wowhead.com/spell=5782/fear (as example)

**Expected behavior**
You release spirit and get ported to the Spirit Healer and wait for respawn.

**Screenshots/videos**
https://youtu.be/XMdjBpAOloo

**Additional Context**
My guess is that releasing on practically the same tick as the death makes the server think it should still "move" you because of the Fear, but the location update happens 1 tick after the release spirit signal and takes the data from when you were alive.

**Comment by z5n** [comment]
rev. 35167

**Comment by z5n** [comment]
rev. 35219

[kelno/sunstrider/244
](https://github.com/kelno/sunstrider/issues/244)

**To Reproduce**

1. .die yourself in some spot
2. don't press release, .save
3. restart worldserver (kill process, don't .server restart)
4. log back in

**Comment by kelno** [comment]
Fixed with next server update
