### ISSUE TITLE
Doomguards despawn few seconds after summoning

### ISSUE THREAD

**Issue by Massie323** [SunstriderEmu/BugTracker#4228]
**Describe the bug**
As a warlock, when you summon a Doomguard it will despawn in about 3 seconds even if you enslave it and it will not target anything unless engaged..

**To Reproduce**
1. Cast Ritual of Doom
2. Observe as the Doomguard despawns within a few seconds

Spell: https://classic.wowhead.com/spell=18540/ritual-of-doom

**Expected behavior**
After sacrificing a player, the Doomguard should last [15 minutes](https://wowwiki.fandom.com/wiki/Ritual_of_Doom) (?).

**Additional context**
[Dragon's Call](https://classic.wowhead.com/item=10847/dragons-call) has a similar issue where the Whelps despawn after 3 seconds instead of 10 and do not engage in combat.

**Comment by kelno** [comment]
Closing in favor of https://github.com/SunstriderEmu/BugTracker/issues/5091
