### ISSUE TITLE
heroic reputation keys showing up red at honored

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4229]
i visited the CE rep vendor to buy the heroic key and noted that it looked red (unavailable to buy even though I have was honored before logging in).  

however... I clicked on it and was able to buy it... so behavior is correct, but vendor display code/flag is probably still based on revered faction..

**Comment by StafordDev** [comment]
Clear your Cache folder. That should fix the problem.
