### ISSUE TITLE
pvp masters in shat overcrowding

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4230]
the arathi basin, alterac valley, warsong gulch, eots bg masters are often covered by players either by accident or by intentional efforts.  

the alterac valley one is really the worst because after an av  the 30-40 players get teleported back to where they were (which is usually right next to the guys you talk to.  

please increase their size like was done for the daily pvp quest guy they are standing next to so that they can only be blocked by intentional efforts (and then give those assholes a short ban to further discourage the behavior)

 or perhaps when teleporting people back to shat after a bg (specifically shat near the bg masters),  teleport them to a default location at the base of the stairs instead of their last location (usually in front of the bg masters).

**Comment by Jerrythemagicdog** [comment]
You can just use nameplates to interact with them.

**Comment by michaelkittrell** [comment]
thanks for the tip, i usually have friendly name plates off.
