### ISSUE TITLE
Fists of fury setbonus not proccing correctly

### ISSUE THREAD

**Issue by Eykoendless** [SunstriderEmu/BugTracker#4231]
**Describe the bug**
The % rate for the fire damage proc is almost nonexistant. I ran some tests autoattacking in melee with a procrate of around 0.2%. Very far from the intended 5%. I also didn't manage to proc it once for ranged attacks, which should be possible as long as you stay within 20y of your target.

**To Reproduce**

1. You attack an enemy within 20y of yourself
2.  5% chance to deal additional 100 to 150 fire damage
3. Spell damage can be resisted, can not crit. No internal CD.

Item: https://www.wowhead.com/item=32945/fist-of-molten-fury and https://www.wowhead.com/item=32946/claw-of-molten-fury
Spell: https://www.wowhead.com/spell=41990/fists-of-fury#comments
 

**Expected behavior**
Whenever you attack your target within 20y range, 5% chance for a 100-150 fire damage proc.

For further reference, see this wowhead comment from 2008

"""
By 64872 (269 – 1·2) on 2008/05/12 (Patch 2.4.1) |   |  
The proc rate is right at 5%. I used proc watch with auto swings on halaa guards to find out proc rate. I then tested this on special attacks, of which also cause the proc at 5% . That means they are happily buffed by haste *giving you more ppm* !No Internal CD!

Running about 1300 dps shows that I do about ~.9% of my total dmg from the proc of these fists--Recount*dmg review

To compare, the Shattered Sun Pendant of Might *scryer*, had a slightly higher overall dmg of ~1% of my total dmg done on 1300 dps.

All dmg from the Molten Fist proc is buffed from Curse of Elements. The Proc DOES NOT crit--unlike the pendant of might above noted. The proc CAN be resisted--though why/how is unclear.

My DPS did increase over my Talon of Azshara, Merciless Gladiator's Quickblade, for two reason: The DPS increase as well as the % proc. Though the total dmg increase was only at about +1% on 10 min *halaa guards again* In both cases I was hit capped/expertise capped.

Though they aren't the BEST weapons in the game, they do look very nice. I would suggest that these are above the dps of the badge weapons, although I have yet to test the badge pair.
"""

**Additional context**
Please look into this, these are already pretty mediocre weapons stat-wise, the main appeal to use them is both the looks and the proc chance. If the proc isn't working there is really no justification for anybody to use them if they have access to any of the many alternatives with better stats.

**Comment by BasedForfrost** [comment]
I've had similar results testing the setup with my normal rotation over about 6 minutes of combat. After 457 melee attacks (and 50 WF attacks), I saw exactly one proc from the weapon bonus. This definitely isn't working correctly.

![image](https://user-images.githubusercontent.com/62028592/93402659-61806580-f853-11ea-95c6-81b1aa8e2e4d.png)

**Comment by Eykoendless** [comment]
I ran some more tests yesterday: over 701 melee attacks, I saw 6 procs ( 0.008% ). Over 400 ranged shots within 20y of the dummy, I saw 0 procs.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
The proc doesn't work on ranged attacks which is intended.

**Comment by Eykoendless** [comment]
Damn, could you make it work on ranged though :smiling_face_with_three_hearts:  ?? haha
thanks still!
