### ISSUE TITLE
mt hyjal evading mobs (also bt teron?)

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4235]
as of roughly thursday 9/17 (and seemingly not tuesday 9/15), trash mobs are sometimes evading and not coming in...  i tank it the same way every week but today multiple occurences of mobs on multiple waves getting hung up and just evading (until im free to come pick them up prot pal).  ghouls, necros for sure,  think there was a couple of crypyt fiends as well.  1-3rd boss so far.

i also heard that the ghosts @ teron gorefiend if you're fully in the corner don't spawn correctly (at player pos) and instead spawn on raid (evade + teleport?)  if you come slightly out of the corner they spawn properly (reportedly).  

Did you guys change some clipping/evade parameters/code?

**Comment by michaelkittrell** [comment]
in ally camp they seem to get hung up coming down the hill just outside the gates.  

in horde camp its along the mountain side about 5-10 yards outside of the tower on the left.

**Comment by Jerrythemagicdog** [comment]
Teron issues most likely fixed with next update, not sure about Hyjal.
