### ISSUE TITLE
Hyjal Rep Rings

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#4236]
You are able to obtain Rings (Band of Eternity) from Hyjal reputation without doing the Vials prequest http://tbc.cavernoftime.com/quest=10445 simply just by obtaining reputation.

You can join a random world group for rep farm, get friendly and get rings basically for nothing. This affects PvP since these are very often superior to Veteran and other shit PvP players are forced to wear.

https://wowwiki.fandom.com/wiki/Quest:The_Vials_of_Eternity
"Patch 2.4.0 (25-Mar-2008): Changes including quest not needed.
_The vials no longer are required for attunement to Hyjal, however, the quest will be the only way a player can get the Band of Eternity (the various versions), and in addition to this quest, completing the (also no longer required) Black Temple attunement, players receive the title "Hand of A'dal"._"

There are also some comments on wowhead that support the above-mentioned.

I hope it's possible to also remove the rings from all the people that haven't completed the prequest since it puts the ones that paid big price for the vials (or got them legit) into bad position.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, we're keeping it the way it is now though.
