### ISSUE TITLE
Mobs in BT Teleporting

### ISSUE THREAD

**Issue by Allnatural49** [SunstriderEmu/BugTracker#4237]
**Describe the bug**
Mobs in BT (teron constructs, illidan shadow demons) are teleporting when they spawn. One of four ghosts would spawn in the raid, and sometimes shadow demons would spawn underground when they fixate. It seemed to happen on teron when the person who had shadow of death was standing against a wall.

**To Reproduce**
Die with shadow of death near the wall in terons room.

**Expected behavior**
wiping our raid :(

**Screenshots/videos**
https://www.twitch.tv/videos/743258883
can can see an example of it in this video at 2:35:45

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update. https://github.com/kelno/sunstrider/commit/ebc97ed4da8649e4b086bdd1032677b369c5aafd
