### ISSUE TITLE
[#49] Central beacon not spawning for quest "Marking the Path

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#424]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Monday Dec 17, 2018 at 07:19 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/49_

----

Current behavior:
Central becon is not spawning

Expected behaviour:
It should be there

Steps to reproduce the problem:

Step 1: Go to 34.1, 60 in hellfire and see that its not there

First pic is PTR: 2nd pic is quest guide on youtube
![wowscrnshot_121718_171706](https://user-images.githubusercontent.com/45530324/50072133-d60e1680-021f-11e9-81c9-3f91cfcdc425.jpg)
![report 014](https://user-images.githubusercontent.com/45530324/50072148-e1614200-021f-11e9-8296-d8a63de0e822.JPG)

**Comment by Tamosheik** [comment]
Quest ID#9391

**Comment by Jerrythemagicdog** [comment]
Thanks!
Tested now, works correctly.
