### ISSUE TITLE
Allegiance to the Aldor no rep reward

### ISSUE THREAD

**Issue by shillus** [SunstriderEmu/BugTracker#4240]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by shillus** [comment]
I completed the City of Light escort quest and turned in the follow up Allegiance to the Aldor however I am still unable to talk to either the Scryers or The Aldor since I got no rep reward from completing Allegiance to the Aldor.

**Comment by Jerrythemagicdog** [comment]
Can't reproduce locally, what's your character name?

**Comment by shillus** [comment]
Hey there, my character name is Ohyesnice level 70 BE paladin.
