### ISSUE TITLE
Protectorate Treasure Cache does not contain gold and guaranteed loot 

### ISSUE THREAD

**Issue by MianLavanAelin** [SunstriderEmu/BugTracker#4241]
**Describe the bug**
Oppened Protectorate Treasure Cache did not give me gold nor loot. 

**To Reproduce**

1. Get Protectorate Treasure Cache
2. Open
3. Gain nothing

Item: https://wowhead.com?item=32064

**Expected behavior**
It should contain gold(~20g) and an item. Should be random 70 uncommon(from world drop) and chance for the specific rares that are related to this whole bashir stuff, can be seen in the list here https://tbc-twinhead.twinstar.cz/?item=32064 and source wowhead https://www.wowhead.com/item=32064/protectorate-treasure-cache#comments:id=352973 for gold and item list there as well(but not full obv, cause not all from world drop 70s dropped).

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
