### ISSUE TITLE
Test of Endurance Quest 

### ISSUE THREAD

**Issue by Derfell** [SunstriderEmu/BugTracker#4242]
Hi there, 

For the Test of Endurance Quest in Thousand Needles, the ability to trigger the quest even - breaking the food crates - doesnt seem to be working and therefore, you're unable to summon Grenka in order to get Grenka's Claw.  Can this be fixed? 

Thanks for looking into this! 

Cheers, 
Derfell

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update!
