### ISSUE TITLE
Spell reflected spell not giving threat

### ISSUE THREAD

**Issue by MianLavanAelin** [SunstriderEmu/BugTracker#4243]
**Describe the bug**
Spell reflected spells that deal dmg back to the casters do not increase threat for the warrior on that target. 

**To Reproduce**

1. Find npc that casts spells
2. Reflect its damaging spell
3. In test enviroment use the threat command outside the test enviroment use 2 characters

https://db.endless.gg/?spell=23920

**Expected behavior**
Reflected spells should give the threat for the reflected spell. Widely accepted that it should by 1 dmg = 1 threat(also info on wowhead), but for warrior you have additional threat modifier from defensive stance and defiance. 

Sources are:
https://classic.wowhead.com/forums&topic=20024 from TBC
+
one of the reasons why warrior tanked the big void in M`uru fight, is because the reflected spell gave him enough threat. so the casters did not have to care about stopping dmg there. 

**Additional context**
This is also one big thing that enables warriors to better tank in 5-mans because usually they would just get the caster threat thanks to reflect and could have ignored them and focus on the melee mobs.

**Comment by Frostfirexy18** [comment]
Its true tho, can u fix it?

**Comment by Jerrythemagicdog** [comment]
Fixed with next update, thanks.
https://github.com/kelno/sunstrider/commit/605e03eb0f065a418792474a7b561fde7ac6798f
