### ISSUE TITLE
Captain Galvangar (AV) double fears with Intimidating Shout, doesn't break fear on hit.

### ISSUE THREAD

**Issue by Massie323** [SunstriderEmu/BugTracker#4244]
**Describe the bug**
When Captain Galvangar casts Frightening Shout (the NPC equivalence to Intimidating Shout), it afflicts his primary target with both the primary incapacitate and the secondary fear. The damage threshold for the secondary fear seems to be non-existant so whoever is tanking him will be hit (in the back) while they are feared, breaking the first incapacitation debuff, but not the secondary fear.

**To Reproduce**
1. Engage Galv
2. Be his target
3. Get feared and notice the debuff bar

NPC: https://classic.wowhead.com/npc=11947/captain-galvangar

Spell: Wowhead lists the warrior's Intimidating shout as Galvs ability, however here he actually uses Frightening Shout which has multiple different variations.

https://classic.wowhead.com/spell=5247/intimidating-shout
https://www.wowhead.com/spell=38946/frightening-shout

**Expected behavior**
When the room gets feared, if the primary target is hit by Galv, it breaks them out of the incapacitation and they regain full control.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
