### ISSUE TITLE
The mission Klaven's Tower 

### ISSUE THREAD

**Issue by mihne1** [SunstriderEmu/BugTracker#4245]
I can't open the chest from the tower, even tho I have the key for it, so it should work. I tried to right click on the key and then use it on the chest but nothing happend. When I try to open, it says something like this "You need a key for it", and I'm like "Man, I have it".

**Comment by Jerrythemagicdog** [comment]
You need lockpicking to open the chest.
https://www.youtube.com/watch?v=FkJZkvylBOE

Note #1: You need to buy thieves tools from a rogue supplier, to be able to lick-pock at all

Note #2: You need your lock-picking skill up to 70 to be able to use it on that chest

Note #3: You don't have to kill Klaven, sapping and ninja'ing the chest is much easier
