### ISSUE TITLE
Trapping Coilfang Champions with freezing trap - game crash

### ISSUE THREAD

**Issue by Jonsbe** [SunstriderEmu/BugTracker#4246]
**Describe the bug**
Trapping Coilfang Champions with freezing trap - game crash

**To Reproduce**

1. Put freezing trap on SP HC last 2 big packs before boss 
2. Try to yell at coilfang champion so he comes to your trap
3. The effect of freezing trap activates, see the game crash?
4. Lose

NPC: https://www.wowhead.com/npc=17957/coilfang-champion
Spell: https://wowhead.com?spell=187650/freezing-trap

**Expected behavior**

Freeze the mob

**Screenshots/videos**

**Additional context**

Game crash on w10, wow.exe just hangs and win10 exits wow after clicking once

**Comment by Jerrythemagicdog** [comment]
Download a new client and avoid using any sort of texture packs or client modifications.

**Comment by Jonsbe** [comment]
I have 4 weeks old client from your website, i dont have any texture packs, or client modifications except addons.

**Comment by Jerrythemagicdog** [comment]
Try disabling addons then.

**Comment by Jonsbe** [comment]
The culprit was RaukinCC - cc breaker announce addon https://github.com/Macumbafeh/RaukinCC
