### ISSUE TITLE
Mount Hyjal Rage Winterchill bug

### ISSUE THREAD

**Issue by Nynholol** [SunstriderEmu/BugTracker#4248]
Yesterday our guild cleaned 8 waves and the boss Rage arrived. The boss killed us 75% and we didn't know inside the instance. We wrote a ticket and GM reset it for us. Now we have to kill 8 waves again. Can for our guild AfterAffect this waves delete when we have this waves cleared ? In Endless website you garantee this waves dont kill next time. THX
![rage1](https://user-images.githubusercontent.com/67372942/93746609-b296ad80-fbf5-11ea-831f-418e1baf7841.jpg)
![rage2](https://user-images.githubusercontent.com/67372942/93746620-b6c2cb00-fbf5-11ea-9edb-0255281174e4.jpg)
![Support](https://user-images.githubusercontent.com/67372942/93746687-d8bc4d80-fbf5-11ea-9c65-de2e8417bfe7.png)

please help us .

**Comment by Jerrythemagicdog** [comment]
Boss is in combat with Jaina until he kills her because an encounter is in progress which is why you couldn't enter the dungeon, if a GM reset your instance don't expect to be able to continue your progress in the same one.

**Comment by Nynholol** [comment]
ye but we wating out 20min. And thats isnt normal
