### ISSUE TITLE
FACTION BALANCE - ALLIANCE LOOSING POPULATION

### ISSUE THREAD

**Issue by Baliang47** [SunstriderEmu/BugTracker#4249]
Dear Admins,

I'm writting to you not to report you any bugs but I tried on discord many times to alarm you about the faction balance:

Today i think we reach a pick about that. The faction balance is more or less 40% alliance 60% Horde and still no action from Endless. We lost 10% of population (even more some days) within 1 month. If it still continue in this way we will not be able to recruit any people for the guilds, to find groups for Dunjeons, to interact with the community. You have to take drastic decision in order to counter balance this effect or every body from alliance side will just stop playing or switch to another server.

Hope you take in consideration my concerns.
Regards,
Bali

**Comment by Jerrythemagicdog** [comment]
Not a bug report, thanks for the suggestion though.
