### ISSUE TITLE
HYJAL, archimonde few tear oddities/issues

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4250]
hyjal, archimonde

air bursted, feared after landing was wandering around next to terrain and got stuck couldnt move.  about 40 yards south of archimonde and all the way west at the edge of terrain (happened to me 1x).  screen shot included (qubed)

also heard of issues of people activating tear in air and touching the big tree branches to the south and insta dieing from "falling" even under tear effect. (heard 2x)

if you are targetted for air burst and it goes off right after fear, you kinda get popped up and immediately cancelled. (happened to me 2x in 5 hyjals).  probably intended so you arent feared in air and unable to use tear?

you might also be able to pop tear right after getting air bursted and stay on the ground (observed it happening to someone else, not related to fear)

![image](https://user-images.githubusercontent.com/5479930/93806605-3c4a7900-fbfe-11ea-9757-dfbd12801c69.png)

**Comment by NeonicSupersonic** [comment]
Yeah those branches are completely bugged, and have nothing to do with ppl being unable to time their tears properly. Or being feared through invisible walls is a totally not a thing which was used for exploration at least till the end of wrath.

Out of all issues you have described only real one is ppl not being airbursted if they use tear on the ground. Personally I never seen that, but who knows. Got any clips?

**Comment by michaelkittrell** [comment]
i assume they're using the tear the split second after they are airbursted which changes their upward trajectory to floating down and since they're so close to the ground they basically don't go anywhere.
