### ISSUE TITLE
Warlock lesser firestone enchant is not working

### ISSUE THREAD

**Issue by mantiblades** [SunstriderEmu/BugTracker#4252]
**Describe the bug** 
 Warlock lesser firestone enchant is not working

When I create a lesser firestone and right click on it to enchant weapon instead of enchantment sticking to weapon it just  ends up putting the weapon in my inventory and the stone ends up in my main hand so when I go to engage in combat it says I need a weapon. Basically it's not enchanting my weapon it's just trading places with it. Been playing WOW since the day of launch. yay

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
That's what the spell and item do, they work on equip not as an item enchantment.
You can read about it in the spell's tooltip.
