### ISSUE TITLE
Turning Point quest in Netherstorm

### ISSUE THREAD

**Issue by Andrewcapo** [SunstriderEmu/BugTracker#4253]
**Describe the bug**
This quest requires you to teleport using the teleporter at Invasion Point: Overlord using the item called "Socrethar's Teleportation Stone", which is just north of Forge Base Oblivion. This teleports you to the island at the northwest corner of Netherstorm. Upon arriving at the teleporter on the island some NPCs are supposed to spawn for the quest. After that you're supposed to go up to the boss named "Socrethar" and use the item called Voren'thal's Presence to weaken him and make him attackable. The problem here is there are already friendly NPCs spawned in place of the ones that are supposed to spawn when you teleport to the island, and Voren'thal's Presence is unable to be used on the boss. I am Scryer, and I believe this bug is caused by someone that is Aldor attempting the quest and then dying on the boss. If you read the comments on wowhead for this quest there are a few that mention this. Link below

**To Reproduce**

1. Read above
2. 
3. 

https://www.wowhead.com/item=29796/socrethars-teleportation-stone - item used to teleport to the island
https://www.wowhead.com/item=30259/vorenthals-presence - item used to make the boss attackable
https://www.wowhead.com/quest=10507/turning-point# - the bugged quest

**Expected behavior**
Upon teleporting to the island there should be npcs that spawn and start an event, either scryer or aldor npcs, depending on which one you are. You should then be able to progress up to the boss and use vorenthals presence on him to make him attackable and kill him.

**Screenshots/videos**

**Additional context**
This bug was previously reported in issue #2963. I believe that Simon-GM was confused as to which quest Balanarr was referring to, as this quest is most definitely still bugged. If any more information is needed please let me know, I'll keep an eye on this to respond to any questions. Thanks

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
