### ISSUE TITLE
Hitting a sitting target does not result in a crit if the attacker has 0% crit chance after resilience

### ISSUE THREAD

**Issue by bluemanguy112** [SunstriderEmu/BugTracker#4254]
Pretty self explanatory. Important to note however that this should not allow Players to abuse this mechanic in order to receive certain buffs.

https://wowwiki.fandom.com/wiki/Sit

Patch 2.3.2:
Effects triggered from being critically hit: Many abilities and talents were changed in 2.3.0 to allow them to trigger from critical strikes that occurred while the player benefiting from them was sitting. These abilities once again do not trigger if the victim is sitting.

**Comment by Jerrythemagicdog** [comment]
![image](https://user-images.githubusercontent.com/46463908/93906116-b7da2200-fcf3-11ea-9c5e-296d8be4d27d.png)
Procs are disabled as per patch note.

**Comment by Massie323** [comment]
This has something to do with Resilience reducing chance to be crit. I leveled a Warrior recently utilizing forced Enrage procs. However being in full PvP gear I am not getting critted anymore (in PvE) despite sitting guaranteeing a 100% crit chance.

**Comment by kelno** [comment]
Seems that currently if you reduce the crit chance under 0%, this crit damage doesn't apply anymore.

**Comment by kelno** [comment]
Fixed with next server update
