### ISSUE TITLE
Angered Arakkoa Protector not summoned

### ISSUE THREAD

**Issue by TheMoneyHater** [SunstriderEmu/BugTracker#4256]
These npcs(https://i.imgur.com/pY3AqfR.png) do not spawn https://db.endless.gg/?npc=21470 like they should.

https://www.youtube.com/watch?v=ipxvrrqSeNE
This video is 4.2 but the mobs were in the game and summoned from 2.2 (same time as ogrila quests)

**Comment by z5n** [comment]
thanks, fixed with next update!
