### ISSUE TITLE
Interface and video problems

### ISSUE THREAD

**Issue by yanghu27** [SunstriderEmu/BugTracker#4257]
**Describe the bug**
 Every time a restart the game all the video settings and key binding restart too.

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Log out in the game before closing it to save your keybinds and video settings.

**Comment by yanghu27** [comment]
Doesnt work. I log out and then quit the game. I run open the game again and all was restarted...
