### ISSUE TITLE
Call for help

### ISSUE THREAD

**Issue by Jimant2** [SunstriderEmu/BugTracker#4258]
**Describe the bug**

Please fix the aggro radius. It's ridiculous trying to pull one pack of mobs and the other pack that's located 20 yards away getting dragged in as well. Literally imposssible to do certain dungeons like Botanica without dying ( especially at the part right after the 1st boss ). Terrific server other than that. Thanks 
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, would need some specific examples here. 
By aggro range maybe you mean the call for assist pulse that happens every so often for creatures and other creatures join them in combat?

**Comment by Jimant2** [comment]
> Thanks for the issue, would need some specific examples here.
> By aggro range maybe you mean the call for assist pulse that happens every so often for creatures and other creatures join them in combat?

I'm mostly referring to the aggro radius. When a player pulls mob, even when using a ranged attack/spell, it's extremely likely that other mobs get pulled in as well, even if they are further away from that mob's aggro radius. 

To give you an example, as mentioned in the OP as well, clearing the pack of mobs in The Botanica that are right after the 1st boss ( Commander Saranis ). No matter how carefully I try to pull one pack, it's almost certain that another pack, in a much further spot, will get dragged in as well, which they shouldn't. It's also not uncommon for the entirety of the packs in one area in a dungeon to get pulled in because of this. This problem is especially prominent in The Botanica and The Arcratraz.  Having spoken with a few other players, some said that the aggro radius is not working properly and I'm inclined to believe that.

I hope you at least consider taking a more detailed look at this issue and fix it, if it is indeed broken.

Thanks for the quick reply.

**Comment by crw614** [comment]
Absolutely unplayable without party
ttps://www.youtube.com/watch?v=4FiKUNaHOxc

**Comment by Jimant2** [comment]
> Absolutely unplayable without party
> https://www.youtube.com/watch?v=4FiKUNaHOxc

I think this sums it up perfectly. In dungeons this gets exacerbated even more because of the overtuned mobs. It's clear that this is NOT working as intended and it's an issue that needs to be fixed.

**Comment by Jerrythemagicdog** [comment]
Thanks, that's call for help and not aggro range related but your video is helpful!

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
