### ISSUE TITLE
Perception range bugged [please fixe ASAP]

### ISSUE THREAD

**Issue by tbc123** [SunstriderEmu/BugTracker#4260]
Perception does increase stealth detection, but no far enough: Here you can see a rogue with 5/5 Master of Deception at like 10yards away, when you should be able to see him at like 25yards away.

Proof for retail perception :
http://www.warcraftmovies.com/movieview.php?id=218053 He see's the rogue at like 25yards away (without even walking towards the rogue while seeing him).
https://www.youtube.com/watch?v=dUVDBT9v66U&feature=youtu.be&t=2m55s There he see's the rogue, same range again 25yards away, and behind a pillar.
https://www.youtube.com/watch?v=dUVDBT9v66U&feature=youtu.be&t=5m9s Here he is following a druid at the start of the clip, and he see's the rogue, again, at like 25yards away.
https://www.youtube.com/watch?v=eJWNMCD8SMU&feature=youtu.be&t=5m59s He first see's a rogue, one last time, at like 25yards away, and then a druid.

Please fix ASAP, it's important in order to balance Alliance / Horde racials in pvp.

**Comment by tbc123** [comment]
For the first link you need to look at 4:20

**Comment by blblblaz** [comment]
![image](https://user-images.githubusercontent.com/53877162/94049965-4a56f000-fdde-11ea-9b59-ac55148eee72.png) - This is max range at which you can see a player with 0 stealth level talents or gear or anything (in game this is around 22 yards)


![WoWScrnShot_092320_205012](https://user-images.githubusercontent.com/53877162/94050338-cb15ec00-fdde-11ea-9f14-a8767d046a77.jpg) - This is max range at which you can see a Rogue with 5/5 Master of Deception and no other stealth gear(in game this is around 19 yards)


In example one the enemy Rogue is Mutilate spec, and as you can see it's the range is around the same as in my screenshot.
And in the other examples the range clearly doesn't exceed what's shown in my screenshots.  

As far as Perception specifically goes it clearly works so I'll close this one for now, thanks for the report.
