### ISSUE TITLE
Shadow siegh bug

### ISSUE THREAD

**Issue by tbc123** [SunstriderEmu/BugTracker#4262]
The Problem: The shadow sight debuff that is obtainable in arena currently only increases your stealth detection by a lot in an ordinary fashion. This results in that you can not see stealthed players that are behind you.

How it should work: Should give the player complete stealth detection, regardless of which direction you're facing.

How to reproduce: enter arena, take shadow sight, have a rogue stealth behind you.

**Comment by Jerrythemagicdog** [comment]
That's how stealth detection in general works, you can't see someone who's behind you.
