### ISSUE TITLE
Interface and video problems

### ISSUE THREAD

**Issue by yanghu27** [SunstriderEmu/BugTracker#4263]
**Describe the bug**
 Every time a restart the game all the video settings and key binding restart too.

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

 Only open the game
Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**
 This is my second bug report of this problem because the answer of the previous one did not serve me

**Comment by beraus** [comment]
Is your game in the zip file? If yes - extract it.

**Comment by yanghu27** [comment]
Keeps being the same

**Comment by beraus** [comment]
Try to right-click on folder, "Properties" and uncheck "Read-only". 
Bugtracker is primarily for server-side issues which this isn't - I'll close it - but if ^ doesn't solve your issue try with Discord, we have quite active and helpful community.
