### ISSUE TITLE
Disrupt Their Reinforcements

### ISSUE THREAD

**Issue by Protegit** [SunstriderEmu/BugTracker#4266]
Hey Endless Gm

I am trying to do the quest Disrupt Their Reinforcements. but it wont let me finish it.

the quest needs some items dropped from the mobs in the area, i need 4 pr objective, i have gathered those, i have also done the first objective, but when i get to the 2nd objective, it wont let me do it... It says that i dont have a target or wrong target. also when im certain that i do have the right portal targeted. pls help 

/Protegit

**Comment by Jerrythemagicdog** [comment]
Sounds like you're at the wrong portals then.

**Comment by Jerrythemagicdog** [comment]
Tested on live and on local, both H and A quests work, stand in the portals and use your quest item or watch a video guide on how to complete them.

**Comment by Protegit** [comment]
well i will try and see if i am at the wrong portal... but he one i need is grimh, and last i was standing in it

**Comment by Protegit** [comment]
![WoWScrnShot_092320_194026](https://user-images.githubusercontent.com/71782748/94049258-0a3f3f80-fdd5-11ea-9e75-4d91cd7e4e50.jpg)
 check that... if u see my minimap, i am at the right spot...

**Comment by Jerrythemagicdog** [comment]
Walk inside.

**Comment by go2havefaith** [comment]
You need 4 rune stones to complete Portal Kruul so it seems, just had trouble completing the second part of this quest but could do so after obtaining 4 stones
