### ISSUE TITLE
Blackwing lair Master Elemental Shaper Krixix no option to teach Smelt Elementium ore

### ISSUE THREAD

**Issue by Speankitsover** [SunstriderEmu/BugTracker#4267]
**Describe the bug**

Master Elemental Shaper Krixix in Blackwing Lair does not have the option to teach https://tbc-twinhead.twinstar.cz/?spell=22967 Smelt elementium ore to a Miner when Mind Controlled.
**To Reproduce**

1. Cast X on target affected by ...
2. Cast Mind controll on Master Elemental Shaper Krixix in Blackwing Lair, and you can see theres no ability on the bars to teach https://tbc-twinhead.twinstar.cz/?spell=22967
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

When Master Elemental Shaper Krixix is mind controlled, he should have an ability to teach your target https://tbc-twinhead.twinstar.cz/?spell=22967 

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
