### ISSUE TITLE
Doomsayer Jurim - too quick spawn rate and the same spawn point

### ISSUE THREAD

**Issue by Hihilist** [SunstriderEmu/BugTracker#4269]
**Describe the bug**
Rare elite Doomsayer Jurim from Terokkar Forest spawns in the same spot every time (70.9 49.9) despite having option to spawn in three different routes. Additionally, his spawn time is very quick as it respawns after about every 5-6 minutes.
After killing it, it is a matter of going to his respawn point and wait for another respawn, which allows players to grief his rare drop.

**To Reproduce**
1. Locate Doomsayer Jurim roaming on road between Tuurem in Terokkar Forest and entrance to Shadowmoon Valley
2. Kill Doomsayer Jurim
3. Go to spot (70.9 49.9) in Terokkar Forest
4. Wait about 5-6 minutes
5. Kill Doomsayer Jurim once he respawns
6. Repeat steps 4&5

https://www.wowhead.com/npc=18686/doomsayer-jurim

**Expected behavior**
Doomsayer Jurim has 3 different spawn points and has a longer respawn timer.

**Additional context**
NPC can be semi-afk farmed by classes with pets (hunter, warlock) as they only need to set their pet to stay in the spawn point, use Defensive stance and then just gather the loot once the NPC is dead.

**Comment by Sheikthecatman** [comment]
Thanks! Doomsayer Jurim's spawn position will now vary! Fixed in [7532c5835ef852b0ec35e3abb8157d245841173e](https://github.com/kelno/sunstrider-scripts/commit/7532c5835ef852b0ec35e3abb8157d245841173e)
