### ISSUE TITLE
Grimtotem mobs

### ISSUE THREAD

**Issue by bluewierdness** [SunstriderEmu/BugTracker#4270]
**Describe the bug**

Grimtotem Mobs near camp aparaje in stonetalon mountains pull all mobs when one is pulled. 

**To Reproduce**

1. try to pull one mob.
2. pull all mobs around it. 

Quest: https://www.wowhead.com/quest=6548/avenge-my-village

**Expected behavior**

When pulling one mob, only one gets pulled or even just a few instead of all the mobs in the area. 

**Screenshots/videos**

https://imgur.com/a/rd851sR

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
