### ISSUE TITLE
honor quest  for great honor x3 xp fail

### ISSUE THREAD

**Issue by danyriosa** [SunstriderEmu/BugTracker#4271]
**Describe the bug**
Hi, today i completed the quest "for great honor" because it was x3 honor bonification. The surprise was when i check my honor. I completed 10 quest in a row but i only get 9 k for honor. It was very frustating becouse this is the normal honor for 10 quest.  I neeed  to return the honor x3 or the 4 pvp marks for every quest and less 9k honor that i get. Thanks you very mach

**Comment by Jerrythemagicdog** [comment]
Sounds like you didn't look at the time then because bonus honor starts at 18:00 server time on Fridays.
