### ISSUE TITLE
Justicar title bugged?

### ISSUE THREAD

**Issue by Ticketdudu** [SunstriderEmu/BugTracker#4273]
Hello, i got all 3 PvP Reputations(Silverwing sentinels, Stormspike Guard and The League of Arathor) exalted, and i still dont have the Justicar title. Is it bugged? If yes, please fix :)

**Comment by Jerrythemagicdog** [comment]
It appears so, thanks for the report!

**Comment by hufsa** [comment]
Thanks, fixed with next update. You'll need to gain one point of reputation with any of the three factions for it to update.
