### ISSUE TITLE
Harvest Festival quest "Honoring a Hero" missing reward item

### ISSUE THREAD

**Issue by Andrewcapo** [SunstriderEmu/BugTracker#4274]
**Describe the bug**

The quest itself works perfectly fine. The problem is 24 hours after completing the quest you're supposed to get a letter in the mail from the quest npc with an item included. The item is called "Bounty of the Harvest". I received the letter, but the item was not included with it. Links for item and quest below.
**To Reproduce**

1. Complete quest
2. Wait 24 hours
3. Receive letter without included item

Item: https://www.wowhead.com/item=19697/bounty-of-the-harvest
Quest: https://classic.wowhead.com/quest=8150/honoring-a-hero
Spell: https://wowhead.com?spell=

**Expected behavior**

Should receive letter from NPC after 24 hours that includes said item listed above.
**Screenshots/videos**

**Additional context**

Edit: The wait time for receiving the letter in the mail _might_ be 48 hours. Not 100% sure.

**Comment by z5n** [comment]
Fixed in [f1894f8e5b890b4477923fb74b79fec51f383f51](https://github.com/kelno/sunstrider/commit/f1894f8e5b890b4477923fb74b79fec51f383f51)
