### ISSUE TITLE
SSC - One of the roaming Underbog Colossus trash NPCs is popping out of textures

### ISSUE THREAD

**Issue by Hihilist** [SunstriderEmu/BugTracker#4275]
**Describe the bug**
In SSC instance there is one roaming Underbog Colossus trash NPC that traverses in a loop between rooms of Leotheras the Blind and Morogrim Tidewlaker boss NPCs that gets into the textures at some point when moving from Tidewalker. It tends to pop out from textures somewhere past Leotheras, interrupting the clear of the other trash NPCs or causing a massive wipe.

**To Reproduce**
1. Enter the Serpentshrine Cavern raid
2. Clear the trash NPCs up to the tunnel entrance to the room with Leotheras the Blind boss NPC
3. Wait in the tunnel until Underbog Colossus trash NPC pops out
4. If Underbog Colossus trash NPC does not pop out in the tunnel, clear the trash NPCs on the right side of the room with Leotheras the Blind boss NPC and wait somewhere next to the big pillar

https://www.wowhead.com/npc=21251/underbog-colossus

**Expected behaviour**
All roaming Underbog Colossus trash NPCs are properly pathfinding, on the proper level of textures.

**Comment by Jerrythemagicdog** [comment]
Can't make it happen, the Colossus patrols on the path from the entrance of Leotheras' room as you've described, does a loop around one of the columns in Fathom Lord's room and then goes on his way back through the previous points to Leotheras' entrance. 
A clip of it happening would be helpful, thanks.

**Comment by Hihilist** [comment]
I might know what I missed in steps - to bug Underbog Colossus trash NPC into textures he needs to be chain-pulled with previous pack consisting of https://www.wowhead.com/npc=21299/coilfang-fathom-witch trash NPC by fearing one trash NPC (eg. https://www.wowhead.com/npc=21229/greyheart-tidecaller) from another previous pack (all mobs are cloase to each other on the path to Leotheras' room).

Did SSC today and one trash NPC run into the other pack, we wiped, and after recovering from wipe we pulled again 1st pack and in the middle the Colossus appear from textures.

**Comment by Hihilist** [comment]
@Jerrythemagicdog managed to record video https://www.youtube.com/watch?v=crG9dmIPKdI

**Comment by Jerrythemagicdog** [comment]
Seems like someone pulls the creature somewhere in the instance (there are a few players far away from you in this clip, or they could've been chased in other parts of the instance while you were already resurrecting).
Each creature in 25m raids on the server puts your entire raid in combat on engage, same way a boss would (we can see "+Combat" in your scrolling combat text at around 0:03 in the video) in which case the creature will teleport to you inside the instance if it can't find a path.
I'm more inclined to believe there were still some players being chased by the Colossus while you were recovering.
