### ISSUE TITLE
The Ashtongue trinkets have an internal cooldown

### ISSUE THREAD

**Issue by PekelZoda** [SunstriderEmu/BugTracker#4276]
**Describe the bug**

The Ashtongue trinkets seem to have internal cooldowns. Making them un-viable for raiding.

**To Reproduce**

1. Check out this guys trinket (as of 2020-09-29): https://endless.gg/armory/character/gotarrows
2. See how the tooltip of Ashtongue Talisman of Swiftness says "5 minutes cooldown" 

Items: 
https://tbc-twinhead.twinstar.cz/?item=32490
https://tbc-twinhead.twinstar.cz/?item=32486
https://tbc-twinhead.twinstar.cz/?item=32488
https://tbc-twinhead.twinstar.cz/?item=32492
https://tbc-twinhead.twinstar.cz/?item=32493
https://tbc-twinhead.twinstar.cz/?item=32487
https://tbc-twinhead.twinstar.cz/?item=32485
https://tbc-twinhead.twinstar.cz/?item=32491
https://tbc-twinhead.twinstar.cz/?item=32489

**Expected behavior**

The Ashtongue talisman had **no internal cooldown** on retail, making some of them viable for raiding, but not great.
They should be able to refresh their own procs, and the tooltip of the armory should reflect this.

**Comment by Jerrythemagicdog** [comment]
Don't suggest yourself by armory tooltips.
