### ISSUE TITLE
Essence-Infused Moonstone is lost from my bag

### ISSUE THREAD

**Issue by gozkok** [SunstriderEmu/BugTracker#4277]
Hello, I got my 280% after a while and then I called Anzu. However after that call I tried to do another Setthek Halls for Anzu, when I tried to call for Anzu, it was telling me Essence-Infused Moonstone is missing.

I tried to learn how to recover but there is no way, it is just gone from my key bag. I would like to recover my Essence-Infused Moonstone.

My Character name is Umbaku in Horde

**Comment by Jerrythemagicdog** [comment]
Seems like you deleted it.
You'll find a replacement in your mailbox.
