### ISSUE TITLE
Ashtongue trinkets have ICD

### ISSUE THREAD

**Issue by PekelZoda** [SunstriderEmu/BugTracker#4278]
**Describe the bug**

The Ashtongue trinkets seem to have internal cooldowns. Making them un-viable for raiding.

Item: 
https://tbc-twinhead.twinstar.cz/?item=32490
https://tbc-twinhead.twinstar.cz/?item=32486
https://tbc-twinhead.twinstar.cz/?item=32488
https://tbc-twinhead.twinstar.cz/?item=32492
https://tbc-twinhead.twinstar.cz/?item=32493
https://tbc-twinhead.twinstar.cz/?item=32487
https://tbc-twinhead.twinstar.cz/?item=32485
https://tbc-twinhead.twinstar.cz/?item=32491
https://tbc-twinhead.twinstar.cz/?item=32489

**Expected behavior**

The Ashtongue talismans had no internal cooldown on retail, making some of them viable for raiding, but not great.
(They should be able to refresh their own procs)

**Comment by TheMoneyHater** [comment]
Proof?

**Comment by Jerrythemagicdog** [comment]
There's no cooldown on them as said in the previous issue.
