### ISSUE TITLE
More Venom Sacs

### ISSUE THREAD

**Issue by kuukivilol** [SunstriderEmu/BugTracker#4279]
The quest "More Venom Sacs" should give aldor reputation in order to switch sides from scryer to aldor, however it removes reputation from both factions, making it impossible for me to switch sides

I have tried multiple times doing the quest, and the result has been the same every single time.

https://www.wowhead.com/quest=10019/more-venom-sacs

Before doing this quest I had somewhat recently changed my race.

**Comment by Jerrythemagicdog** [comment]
What's your character's name?

**Comment by kuukivilol** [comment]
kuukivilol

**Comment by Jerrythemagicdog** [comment]
It doesn't make you lose reputation with the Aldor the fact that you "progress further" (you're at 32430 after turn in you'll gain 250 reputation) into Hated brings you closer to Neutral.
