### ISSUE TITLE
Unable to post Pendant of Withering on Neutral AH 

### ISSUE THREAD

**Issue by jrozasv** [SunstriderEmu/BugTracker#4280]
**Describe the bug**
The game does not allow us to post this item because it claims to have used charges when it doesn't (fully new crafter BoE item).

**To Reproduce**

1. Get a new pendant of withering
2. Try to post it on  neutral AH
3. Get the error message (bugged)

Item: https://www.wowhead.com/item=24095/pendant-of-withering

**Expected behavior**
Should be allowed to be sold on AH.

**Screenshots/videos**

**Additional context**
There are other pservers where this happened like: http://forum.warmane.com/showthread.php?t=336462

**Comment by hufsa** [comment]
Clear your cache and try again. Please confirm that it works.
