### ISSUE TITLE
Investigate the Alchemist Shop Quest is broken

### ISSUE THREAD

**Issue by mantiblades** [SunstriderEmu/BugTracker#4281]
**Describe the bug**

**To Reproduce**

1. Cast Manifestation scroll on target affected by ...
2.  You must be 26lvl ... I'm 27lvl mage
3. I tried login in & out of game. I tried restarting quest line. Please review provided photo for visual notes.
![QUEST BROKEN](https://user-images.githubusercontent.com/52470199/94725629-ef0e8b80-0310-11eb-8b9a-a8b6d0d41568.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
