### ISSUE TITLE
ZA - sealed scroll case. 

### ISSUE THREAD

**Issue by MianLavanAelin** [SunstriderEmu/BugTracker#4282]
**Describe the bug**
Sealed scroll case should have a chance to drop random recipe from the world drop recipe reference 

**To Reproduce**

1. If you haven't fix it yet, it will just contain scrolls currently, just open many of them/check real DB

https://db.endless.gg/?item=33926

**Expected behavior**
Should have a chance for the world drop recipes. Many many people wrote about it on wowhead back during TBC 
https://www.wowhead.com/item=33926/sealed-scroll-case#comments:id=167277
Chance unknown, but based on high occurence of comments and only one time usage of the item, it should be really high.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
