### ISSUE TITLE
Quest: *-Investigate the Alchemist Shop

### ISSUE THREAD

**Issue by mantiblades** [SunstriderEmu/BugTracker#4286]
**Describe the bug**
 When casting the "Cantation manifestation scroll"  
![QUEST BROKEN](https://user-images.githubusercontent.com/52470199/94866940-19397980-03f5-11eb-81d0-5c623a2275fd.png)
<----- broken
 The Invisible creatures never show up. 

**To Reproduce**

1. Cast X on target affected by ...  CAST  "Cantation of Manifestation" to make "Invisible creatures" appear. Then kite it back and burn it down like you would any melee mob.
2. Chest of Containment Coffers...     right click the box to capture "Invisible creatures", open the box to collect the coffer
3. Filled Containment Coffer (3) Do this until  you get three and return to the Magic Quarter turn in to quest giver.

Item: https://wowhead.com?item= https://classic.wowhead.com/object=105174/chest-of-containment-coffers
Quest: https://wowhead.com?quest= https://classic.wowhead.com/quest=1960/investigate-the-alchemist-shop
Spell: https://wowhead.com?spell= https://classic.wowhead.com/item=7308/cantation-of-manifestation

**Expected behavior**
Take a chest of coffers and a scroll from behind 
 Algernon's alchemist shop.. Go to the apothecary district to Investigate the disturbance. Look for the expert alchemist and alchemy supplier and use the "Cantation manifestation scroll" to see the elementals.  
Fight an elemental until it stops attacking, right click the box to capture it, open the box to collect the coffer. Return with the filled coffers, the empty coffers and the cantation.

**Screenshots/videos**

**Additional context**
 I've completed this quest before many time on other servers the quest is broken.

**Comment by viziouzkizz** [comment]
Quest is not working cantation manifestation scroll is not manifesting invisible creatures when casting.

**Comment by Jerrythemagicdog** [comment]
Yes, the quest will be fixed with the next update: https://github.com/SunstriderEmu/BugTracker/issues/4281
It didn't happen yet.

**Comment by viziouzkizz** [comment]
> Yes, the quest will be fixed with the next update: #4281
> It didn't happen yet.

Thank you for the reply 🌺

**Comment by viziouzkizz** [comment]
So I was able to complete the quest.  Note: I had to summon and kill all the mobs 3x's in order to collect all 3 coffers. In WOW you only had to summon mobs 1 time to kill all the mobs collect all 3 Coffers.

**Comment by viziouzkizz** [comment]
> Yes, the quest will be fixed with the next update: #4281
> It didn't happen yet.

So I was able to complete the quest. Note: I had to summon and kill all the mobs 3x's in order to collect all 3 coffers. In WOW you only had to summon mobs 1 time to kill all the mobs collect all 3 Coffers.
