### ISSUE TITLE
Felhunter quest

### ISSUE THREAD

**Issue by serggibz** [SunstriderEmu/BugTracker#4288]
Hello, i can't find the Felhunter's quest, i know where is the npc that gives you the first quest. Don't know if i destroyed an important item or abandoned it. The problem is that if i go to the npc for iniciate the quest, he doesnt give any quest. I'm undead so my npc is in Undead City, the quest is Seeking Strahad. Thanks for read, i hope someone can help me.

**Comment by serggibz** [comment]
Any GM can help or chat with me ?

**Comment by viziouzkizz** [comment]
So Strahad is in rachet up on the hill LOC 62.6, 35.5 
![STRAHAD LOCATION](https://user-images.githubusercontent.com/72232423/94985809-81c84980-050e-11eb-9f1e-924e729b1680.png)

**Comment by viziouzkizz** [comment]
If you have a hard time finding npc's  look the quest up on youtube I usually get what I'm looking for there. This site is for reporting programing errors within the game which you will be experiencing soon on this current quest line. Soon you will be asked to go to Dustwallow marsh to turn in an orb to Tabetha and she will summon an elite red demon but this is bugged cause she is suppose to summon only 1 but 2 end up spawning and it's hard enough to beat the one. This is where my LOC Blurmewdah is currently stuck at. Quest says to bring friends lol.

**Comment by serggibz** [comment]
Thanks for read.. It is not a question of not knowing where the Npc is.
The possible bug is that the npc doesn't give me the quest to start the felh quest chain.
I repeat .. the mission is called 'Seeking Strahad' (I know where Strahad is) and Carendin Halgar (Undead City) supposedly gives it this quest.

**Comment by serggibz** [comment]
I attach 2 screenshots to show both horde npcs.. both of them dont give me the quest 'Seeking Strahad'.

![WoWScrnShot_100420_131048](https://user-images.githubusercontent.com/72260641/95014019-695a4b00-0644-11eb-947f-68403b9d5038.jpg)

![WoWScrnShot_100420_131741](https://user-images.githubusercontent.com/72260641/95014027-75dea380-0644-11eb-85ca-0d8f5a8f1987.jpg)

there is no possibility that the quest is low level and does not appear on my screen.

Thanks!

**Comment by Jerrythemagicdog** [comment]
You're at the wrong NPC, you've finished Seeking Strahad (3001) and the first Tome of the Cabal (1801), you've left off the chain at "Jorah Annison" (Undercity) and the next part in "Tome of the Cabal" (1803). 
Please use Google next time.
Screenshot taken with a copy of your character (with the exact same quest progression):
![image](https://user-images.githubusercontent.com/46463908/95107504-e7485000-0731-11eb-848b-db75a36f0b6c.png)

**Comment by serggibz** [comment]
> You're at the wrong NPC, you've finished Seeking Strahad (3001) and the first Tome of the Cabal (1801), you've left off the chain at "Jorah Annison" (Undercity) and the next part in "Tome of the Cabal" (1803).
> Please use Google next time.
> Screenshot taken with a copy of your character (with the exact same quest progression):
> ![image](https://user-images.githubusercontent.com/46463908/95107504-e7485000-0731-11eb-848b-db75a36f0b6c.png)

Thanks a lot! I really google it but didn't see nothing about this guy.
