### ISSUE TITLE
Quest: Insult Coren Direbrew

### ISSUE THREAD

**Issue by nadezdakuchko** [SunstriderEmu/BugTracker#4290]
**Describe the bug**

Insult Coren Direbrew quest should be daily. Not repetable like atm.

NPC: https://db.endless.gg/?npc=26719
Quest: https://db.endless.gg/?quest=12062

**Comment by Jerrythemagicdog** [comment]
Thanks, it was made intentionally repeatable to allow players to get their trinkets if they decide to farm them.
