### ISSUE TITLE
Warlock Quest: Cleansing of the Orb of Orahil

### ISSUE THREAD

**Issue by viziouzkizz** [SunstriderEmu/BugTracker#4291]
**Describe the bug**
 Turn orb in to NPC Tabetha she summons Demon of the Orb but instead of summoning the one demon which is real hard to kill on your own. She is now summoning 2. She is only suppose to summon 1 demon not 2. 

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item= https://www.wowhead.com/item=7291/infernal-orb
Quest: https://wowhead.com?quest= https://www.wowhead.com/search?q=Cleansing+of+the+Orb+of+Orahil
Spell: https://wowhead.com?spell= fragments-of-the-orb-of-orahil
Demon: https://www.wowhead.com/npc=6549/demon-of-the-orb

**Expected behavior**
 T
![DEMON DBBL SPAWNS](https://user-images.githubusercontent.com/72232423/94980961-1f0d8880-04e3-11eb-9754-d0847da90347.png)
urn orb in to Tabetha at Dustwallow Marsh she summons 1 demon of the orb not 2.

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
