### ISSUE TITLE
Wow Endlesss Server - Any way to get German audio or in game text?

### ISSUE THREAD

**Issue by johngolddog** [SunstriderEmu/BugTracker#4292]
**Describe the bug**

I've tried to download a few addons like Dictionary and Quest translator but I'm not having much luck.
Is there a way I can get German audio or in game text on Endless? 

cheers

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
No idea, sorry! Maybe there's some fan made project.
