### ISSUE TITLE
Moonfire(low rank) doesnt trigger the daze on Aspect of Cheetah

### ISSUE THREAD

**Issue by Ticketdudu** [SunstriderEmu/BugTracker#4295]
All direct damage should trigger the daze effect of the Aspect of Cheetah from hunters, also the Moonfire initial damage should trigger it... But it doesnt :/

How to reproduce:
1. Get a Hunter with Aspect of Cheetah
2. Get a Druid with Moonfire(Rank 1)
3. Cast Moonfire(Rank 1) on the hunter with Aspect of Cheetah on
The hunter will not get dazed. 

This is really annoying while fighting against hunters in wpvp or bgs (at running away for example), so please fix :)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
