### ISSUE TITLE
Karazhan opera, lion feared behind scenery

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4297]
Karazahan Opera

Lion was feared and constantly pathing behind the scenery.  Multiple times, left right and middle.

I don't remember seeing this behavior 3 months ago.

**Comment by Jerrythemagicdog** [comment]
Happens all the time, unfortunately there's not much we can do there without some dark magic, those are dynamically spawned gameobjects that won't be recognized as obstacles for pathing.
