### ISSUE TITLE
Items disappearing from inv, quests resetting

### ISSUE THREAD

**Issue by KN0MI** [SunstriderEmu/BugTracker#4298]
**Describe the bug**
My item's keep disappearing. This is two issues in one.

1. Since yesterday when I got 400 Brewfest tokens, I did one more queust to get 450 then I logged out. Then the 400 stay in my inventory, however anything above 400 gets reset on each log out. Almost all my quests for the brewfast get reset. I say almost, meaning some tokens are unretrievable.

2. Also since yesterday, when I got 100 Eye of the Storm marks. Now I logged in to see all my Eye of the Storm marks gone. Because 100 is max I got a mail with 2 more tokens from the last game we won, when I tried to retrieve those yesterday it said I couldn't because I have to many of those (meaning 100 is the cap). However today now that I lost my 100 marks, I still can't retrieve the 2 remaining marks, saying I still have too many. I have turned off all my addons and reset the entire game, still they're not there. I haven't tried buying anything with the "invisible"  marks yet but I will soon.

I've disabled all addons and restarted, unequipped all bags, it was clear that they're not simply invisible.

Item: https://www.wowhead.com/item=37829/brewfest-prize-token
Item: https://www.wowhead.com/item=29024/eye-of-the-storm-mark-of-honor

**Screenshots/videos**
![WoWScrnShot_100420_025624](https://user-images.githubusercontent.com/70709627/95026534-3a6ac600-0692-11eb-997a-8893ec8741cf.jpg)

**Comment by Jerrythemagicdog** [comment]
The items show up in your inventory when I look up your character.
Disable addons, check bank.

**Comment by KN0MI** [comment]
> The items show up in your inventory when I look up your character.
> Disable addons, check bank.

How embarrassing, I found the marks in my bank. That solves that issue.

Still I have the problem with the quests (and brewfast tokens) resetting. I talked to my guild and they said that indeed quests are bugged. Also I heard that the brewfast still lasts a couple of days. 

If you could confirm this is the case and the quest bugs are known I'll close the comment and wait out the fixes.

Thanks alot for the help already, truely a great server!
