### ISSUE TITLE
Blessing of freedom (paladin)

### ISSUE THREAD

**Issue by paladrayne** [SunstriderEmu/BugTracker#4299]
**Describe the bug**
In Bg I can cast Blessing of freedom on enemies, instead of cast on me and my friends target.

**To Reproduce**
1. Target ennemi
2. Cast blessing fo freedom
3. Blessing of freedom is on my ennemi whereas on me, like other cast like heal, buffs....

**Comment by Jerrythemagicdog** [comment]
Can't reproduce, do you have a video or a screenshot showing this?

**Comment by paladrayne** [comment]
I will try to take a video or screenshot.
