### ISSUE TITLE
Continuing Ally of the Netherwing

### ISSUE THREAD

**Issue by Xalcinious** [SunstriderEmu/BugTracker#4301]
I got a group to killed Zuhuled the Whacked and I cannot return talk to the dragon to return and start Earn Your Wings

**Comment by Jerrythemagicdog** [comment]
Maybe you've completed the quest while in a raid.

**Comment by Xalcinious** [comment]
I killed the boss, got the key, used it and freed Karyunaku and it didn't give me the quest to return on her back, Ally of the Netherwing

**Comment by Jerrythemagicdog** [comment]
Seems like you've already done it, the next quests require Artisan Riding (280%).
