### ISSUE TITLE
Swift Brewfest Ram disappeared after logging out

### ISSUE THREAD

**Issue by thoraxus** [SunstriderEmu/BugTracker#4302]
**Describe the bug**

Unfortunately dont have screenshots of this issue because i was not prepared to this.
Pls investigate and i hope my mount will back.

**Comment by Jerrythemagicdog** [comment]
Sounds like you didn't have the mount but used the Hops.

**Comment by thoraxus** [comment]
I payed for him 100 gold and 600 prize tokens, Supports already gave me back my mount but still it coild happn to other players
