### ISSUE TITLE
Quest Broken - Hecular's Revenge

### ISSUE THREAD

**Issue by viziouzkizz** [SunstriderEmu/BugTracker#4303]
**Describe the bug**
 Quest does not recognize when you've obtained "Hecular's Rod

**To Reproduce**
 Obtain Hecular"s Rod from yeti mob click on Flame of Azel to charge. Flame of Veraz to charge, Flame of Uzel to charge. I do this and they all say I don't have Hecular's Rod.    

1. Cast X on target affected by ...  https://www.wowhead.com/object=1768/flame-of-azel
2. https://www.wowhead.com/object=1769/flame-of-veraz
3. https://www.wowhead.com/object=1770/flame-of-uzel
![Quest Broken - Hecular's Revenge](https://user-images.githubusercontent.com/72232423/95388301-ec7adb80-08a6-11eb-91ea-8f5d49d4de08.png)

Item: https://wowhead.com?item= https://www.wowhead.com/item=3710/rod-of-helcular
Quest: https://wowhead.com?quest= https://www.wowhead.com/quest=553/deprecated-helculars-revenge
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by mantiblades** [comment]
Quest doesn't know when you get quest item Hecular's Rod when you click on the flames it says you need Hecular's Rod even when you have Hecular's Rod in inventory.

**Comment by Jerrythemagicdog** [comment]
You're at the first part of the quest, "Helcular's Revenge" (552) that requires you to retrieve the Rod and bring it to Novice Thaivand. That's the quest item you're hovering over. The one you need to charge is called "Rod of Helcular" and is a part of the next quest "Helcular's Revenge" (553).
Please read the quest text before opening issues.
