### ISSUE TITLE
soulstone from action bar

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4304]
if you drag a soulstone from your bag onto your action bar, then target a raid member and click on it... you at least sometimes soulstone yourself instead of your target.

i had this happen couple months into the server, but i usually click mine out of my bag.  i tried it yesterday and it worked fine (ss on target), but my wife did it just now and it ss herself instead.

she says its random and it happens to her all the time.  no idea if thats true.

**Comment by Jerrythemagicdog** [comment]
Can't reproduce, sounds like some addon interaction or the issue players are having with their ALT key being unknowingly pressed down.
