### ISSUE TITLE
Premeditation Rogue Combo Points Fade

### ISSUE THREAD

**Issue by Ch33z0r** [SunstriderEmu/BugTracker#4305]
The Combo points from Premeditation fade after 10 seconds if no points are added or if they arent used. It seems that the Combo points fade even if you add new ones for example by Cheap Shot. The Combo points from Premeditation should stay on Target if you add at least 1 more Combo Point.

Easy to test on Target dummy or anything. Add CP with Premeditation and Cheap shot. The CP from Premeditation fade after 10 sec. They should stay.

https://www.youtube.com/watch?v=ufPs8Uu-uM4&ab_channel=uzb
can Check this behavoir in this VOD at around 56:40

**Comment by kelno** [comment]
Thanks! 
Fixed with next server update.
