### ISSUE TITLE
Mount Hyjal Ores despawned after raid (or stolen)

### ISSUE THREAD

**Issue by Massie323** [SunstriderEmu/BugTracker#4307]
**Describe the bug**
Due to the lack of a miner, we postponed mining the ores to the next day. But when our miner logged on today, all the ores were already gone. We're unsure whether the ores just despawned or if someone else logged in during the night and stole them.
I made a ticket and the GM advised me to create a bugtracker ticket instead.

**To Reproduce**

1. Clear MH completely
2. Wait 9 hours
3. Ores despawned?

Raid ID: 2108

**Additional context**

If it actually turns out that somehow someone actually nicked the ores for themselves, please let me know in Discord (Massie#3756)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, ores don't despawn unless mined, so yes there's a thief somewhere on the loose!
