### ISSUE TITLE
2 Bots

### ISSUE THREAD

**Issue by Dafloppy** [SunstriderEmu/BugTracker#4308]
i found 2 Bots in Zangarmarsch, Feralfen Village. 1Horde Shadowpriest named Perete and 1 Alli named Opetq. Hope u do something against that.

Greetings Thomas

**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Please open a ticket for this type of issue.
