### ISSUE TITLE
[#66] Fire shield from sunseekers in astromage hurts player members after being spell-stolen

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#431]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Monday Dec 17, 2018 at 12:37 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/66_

----

Current behavior:
The fire shield buff hurts allied players around the mage after they spellsteal the buff 

Expected behavior:
It should be damaging enemies

Step 1: Spell steal the fireshield buff and stand next to an ally
![wowscrnshot_121718_221517](https://user-images.githubusercontent.com/45530324/50087604-564a7100-024c-11e9-814e-af0f0dc4900b.jpg)

**Comment by kelno** [comment]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kaziner](https://github.com/Kaziner)**
_Wednesday Dec 19, 2018 at 00:38 GMT_

----

https://www.wowdb.com/npcs/19168-sunseeker-astromage#related:casts

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Dec 31, 2018 at 18:05 GMT_

----

Note to self: Need update original caster on spell steal?

**Comment by Jerrythemagicdog** [comment]
After spellstealing the spell does not do damage to anyone anymore - the enemies or friendly units.

**Comment by terranaut1** [comment]
> After spellstealing the spell does not do damage to anyone anymore - the enemies or friendly units.

That's wrong, it still damages party members.

**Comment by kelno** [comment]
It does damage them but only if you're close to the caster npc, a bit weird right now.

**Comment by kelno** [comment]
Fixed with next update
