### ISSUE TITLE
Missing Items: Badge of Justice at G'eras

### ISSUE THREAD

**Issue by Nostaglicdude** [SunstriderEmu/BugTracker#4311]
I would like to report a mistake made with when the 2.3 was released. It is about a missing item at G'eras with the new Badge of Justice rewards. There is ONE missing item.

1. Stormwrap (Mail Belt for 60 BoJ)

https://wowwiki.fandom.com/wiki/G%27eras

I have confirmed six times after careful searching and can say that indeed, this one is missing.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update!
