### ISSUE TITLE
Into the Churning Gulch quest

### ISSUE THREAD

**Issue by Nostrop** [SunstriderEmu/BugTracker#4313]
Quest

https://www.wowhead.com/quest=10799/into-the-churning-gulch#see-also

Mobs are not spawning. For 2 days I cannot find a single one. There are 2 places with animation of worms under the crust, but they just don`t surface, whatever I do.

**Comment by Jerrythemagicdog** [comment]
You don't need to kill the big ones, there are not that many of them, Young Crust Bursters (21381) also drop the item.
