### ISSUE TITLE
Rogue -T6 2 piece haste not scaling with slice n dice

### ISSUE THREAD

**Issue by thegreatestqb** [SunstriderEmu/BugTracker#4314]
Hello,

I have attached some screen shots of the T6 2 set not scaling appropriately for 5% haste increase on "Slice and dice" going from 30%-->35% taking weapon speed for this example from 2.7 SPS to 1.8 (1.755) can someone please look into this? or explain to me if I'm incorrect with the calculations. 

Thank you 
![rogue 1_LI (5)](https://user-images.githubusercontent.com/63981501/95664248-c9486a00-0afa-11eb-9b75-f30286203559.jpg)

![rogue 1_LI (2)](https://user-images.githubusercontent.com/63981501/95664213-85556500-0afa-11eb-9cc5-b01817dabfbf.jpg)

**Comment by Jerrythemagicdog** [comment]
It's not going to show up in the tooltip or your character panel but the bonus works, similarly to every other set bonus.
However if you were to mouseover your Slice and Dice on your action bar you'll see 35% displayed correctly.

**Comment by blblblaz** [comment]
this is the Attack speed formula that WoW uses - Attack_speed = "current attack speed" / (("Percent increase or decrease" / 100) + 1 ) - source : https://wowwiki.fandom.com/wiki/Attack_speed?oldid=1503268

in your case that would be " 2.7 / ((35 / 100) +1) = 2 " and " 1.5 / ((35 / 100) +1) = 1.11 "
