### ISSUE TITLE
zulaman, eagle boss gauntlet, too many eagles after wipe

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4315]
eagle boss gauntlet, we slow wiped over the course of 5m or so.  we ran in (not in combat, rebuff etc) and found that the warriors at bottom were still spawned.  we killed them then walked up to where we wiped.  there was a double or triple set of eagles waiting (top of the first ramp).

eagles should probably despawn or gauntlet should probably reset.  maybe we didn't wait long enough for them to despawn.

**Comment by kelno** [comment]
Thanks for reporting.
I've updated the gauntlet reset logic
