### ISSUE TITLE
zulaman 3rd boss (firehawk) weird hatching behavior

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4316]
fighting 3rd boss we killed the right side firehawks.  we pushed boss below hp threshold and left side eggs spawned and came.  we let a hatcher continue because the leftside eggs were already spawned (from boss hp mechanic), but we then got 2-3 waves of additional birds that i presume came from the hatcher we let pass.  

Is this correct behavior?  pushing the boss down below 30% or whatever hps spawns all the eggs left.  There should be no additional eggs for the hatcher to hatch.

**Comment by kelno** [comment]
Thanks for reporting. I couldn't see an issue there, so I'm going to close it for now but we'll keep our eyes open for other people reporting similar issues.
