### ISSUE TITLE
S1 shield

### ISSUE THREAD

**Issue by shadcsm** [SunstriderEmu/BugTracker#4317]
**Describe the bug**

Hi, there. I'am having troubles finding the s1 healing shield in honor hall in SW. Is there any, or its missing? Ty
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Unfortunately there's no healing shield in Season 1.
