### ISSUE TITLE
not reciving gold from my action house mail.

### ISSUE THREAD

**Issue by thicness** [SunstriderEmu/BugTracker#4318]
**i am not able to recive gold from my actions sold on the AH, this happens with almost all of the mails.

![image](https://user-images.githubusercontent.com/72724903/95708659-22301380-0c5d-11eb-8741-521fe09ce7fe.png)

**Comment by Jerrythemagicdog** [comment]
This is a notification mail, the mail content specifies "Amount not sent yet" and specifies the time of arrival for the money.
