### ISSUE TITLE
Ah not delivering gold on sales. Get pending mail, but then real mail with gold never arrives.

### ISSUE THREAD

**Issue by lysobo** [SunstriderEmu/BugTracker#4319]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by lysobo** [comment]
Any help appreciated. Very strange and frustrating bug.

**Comment by Cadense111** [comment]
I have the exact same problem, was advised to disable Ah addons and/or mailbox addons. Problem still not resolved however.

**Comment by Jerrythemagicdog** [comment]
What are the character names?

**Comment by Jerrythemagicdog** [comment]
You've both already looted the gold, please pay attention the mail sith gold arrives at the same time as the notification sometimes before.

**Comment by Cadense111** [comment]
Character name is Cadense, pretty sure that sometimes the pending payment has not arrived although other times it arrives at the same time the notification does, as you stated.
