### ISSUE TITLE
Charcter problem chat isssue

### ISSUE THREAD

**Issue by AlexandruMorun** [SunstriderEmu/BugTracker#4320]
Hello, 

I've been adresssing this isssue for like 5-6 tickets in the end was asked to post it here. Once with my rogue using shadowstep In Netherstorm my client crashed after this my character Funfakt can't see /w /s /g and so on, everyone can instead of me for them. I've tried changing the settingss and client but on another account and on the same account with a different character there is no problem it is a strict problem related to the character but the guys said on their end my account looks fine, if oyu could please invetigate further.

**Comment by Jerrythemagicdog** [comment]
That's your local settings in your game that you can change. 
https://www.wowinterface.com/forums/showthread.php?t=44861#:~:text=%2D%20Right%2Dclick%20on%20the%20name,you%20want%20to%20turn%20off.
