### ISSUE TITLE
Lost phone and haven't recovery codes

### ISSUE THREAD

**Issue by sMuve** [SunstriderEmu/BugTracker#4322]
Hey there,

I activated the 2FA for my account.  Now I've lost my phone, haven't activated the cloud backup for my authenticator and iirc I was so stupid and saved my recovery codes locally on it.
So actually I haven't the 2FA nor the recovery codes. How can I recover my account?

Best regards
sMuve

**Comment by hufsa** [comment]
Hello,
Please send an email to hello@endless.gg from the registered email address.

**Comment by sMuve** [comment]
I mailed you ~66h ago and got no answer. Sadly today is my last chance to participate in the brewfest event. I'm kinda disappointed... I know it was me, who didn't backup everything properly, but is it so much effort to help me out?
