### ISSUE TITLE
Endless.gg Capcha system not working. Been over a week.

### ISSUE THREAD

**Issue by CosmicMessiah** [SunstriderEmu/BugTracker#4323]
I'm trying to get a friend to create an account on endless.gg and the capcha service is unavaillable. He was unable to create an account so I tried to create one for him and I've encountered the same problem. I've made sure i had no conflicting extensions such as adblock etc. tried diff browsers, diff pc's even tried on mobile with no success. Even sent an e-mail to hello@endless.gg and got no response.. It's been over a week so i decided to submit this bug report in hopes you guys can get the captcha service back up and running again. Thanks in advance!

**Comment by Jerrythemagicdog** [comment]
Need to try with a different browser or refresh the page a few times, Captcha is having some issues lately which we're trying to work out.
Thanks for the issue, work in progress.

**Comment by CosmicMessiah** [comment]
Ok thank you :)
