### ISSUE TITLE
Auctionhouse Bugs!

### ISSUE THREAD

**Issue by tumbil1337** [SunstriderEmu/BugTracker#4327]
So , i am trading a lot in the auctionhouse , 
first bug that really gets my nerves is , that as soon as i got more then about 250 auctions open , some of these auctions dont get displayed in the "Auctions" Tab in the Auctionhouse , making it impossible to cancel these!

The second Bug is regarding my Mailbox. which since today for some reason has a maximum of 50 mails, forcing me to put items into my bank ( which is full) or posting them in the auctionhouse, before i can receive the money of my successful auctions, which makes it hard to plan on further trading.

Usually there is no limit in the mailbox, and if there was it was above 50!, also i should have control over all of my auctions, regardless of the amount of auctions i post!

**Comment by Jerrythemagicdog** [comment]
Those are pretty reasonable limits you'll have to work with, sorry.

**Comment by tumbil1337** [comment]
i didn´t have these limits before tho, are they working now as intended?
