### ISSUE TITLE
Few bugs i found.

### ISSUE THREAD

**Issue by PPGGPilot** [SunstriderEmu/BugTracker#4328]
**Describe the bug**

1. A boat from Auberdine to Rut'theran Village drops players into the water far from their destination.
2. Admiral Odesyus does not offer a quest 'A Small Start' to non-draenei characters.
3. Magwin has a swimming animation as she returns to her route after each fight.
4. A hunter's pet gains experience points only when his master (a hunter) gains it.

**To Reproduce**

1. The boat from Auberdine to Rut'theran village throws players into the water far enough out of land causing them die of fatigue. A boat works fine when sailing in opposite direction.
2. Admiral Odysseus does not offer a quest 'A Small Start' to non-draenei characters. checked with draenei, dwarf and gnome.
3. During the quest "A Cry For Help", the questgiver and escorted NPC - Magwin, has a swimming animation when she returns to her route after each fight.
4. If a hunter and his pet differ in level so that the killed NPCs do not give the hunter experience points, the pet also does not gain experience. Example: A level 28 hunter with a level 24 pet are killing a level 22 NPC. Hunter does not gain experience as expected (he's 6 levels higher) but his pet which is only 2 levels higher than NPC and should gain some xp, doesnt get it.
This issue also affects hunters who reached level 70 and will no longer gain any experience. Then their pets doesn't get experience either.

1. N/A
2. NPC: https://www.wowhead.com/npc=17240/admiral-odesyus QUEST: https://www.wowhead.com/quest=9506/a-small-start DRAENEI PREQUEST: https://www.wowhead.com/quest=9505/the-prophecy-of-velen
3. NPC: https://www.wowhead.com/npc=17312/magwin, QUEST: https://www.wowhead.com/quest=9528/a-cry-for-help
4. N/A

**Expected behavior**

1. Boat works properly sailing both directions.
2. The Draenei have the prequest 'Velen's Prophecy', but other races should have 'A Small Star' available without any additional conditions.
3. A walking or running animation.
4. Pet should gain experience if kills NPCs up to 5 levels lower.

**Screenshots/videos**

I have no screenshots/videos.

**Additional context**

N/A

**Comment by Jerrythemagicdog** [comment]
Thanks for the report, 2 and 3 are fixed with next update, 1 is a work in progress.

**Comment by bjh368** [comment]
Nr.4 is just straight up wrong/untrue. Works properly.

**Comment by Jerrythemagicdog** [comment]
Pet XP:
https://www.wowhead.com/forums&topic=114223
https://xpoff.com/threads/hunters-pets-and-leveling-xp-management-mini-guide.90695/

For boats: https://github.com/SunstriderEmu/BugTracker/issues/445
