### ISSUE TITLE
Missing Money

### ISSUE THREAD

**Issue by DragoonKafei** [SunstriderEmu/BugTracker#4329]
Early morning 14/10-20 i put many low lvl items up for sale on AH and when logging in during the afternoon i found some to be sold and i got the silver for it but some are just letters with info of who bought it and that the money is not sent with an estimated delivery time thats already past by hours. 

**To Reproduce**

1. Put item up for sale on auction.
2. Return when sold and find missing money in the mail.

Item: https://classic.wowhead.com/item=1387/ghoulfang
https://classic.wowhead.com/item=6560/soldiers-shield
https://classic.wowhead.com/item=4577/compact-shotgun
https://classic.wowhead.com/item=15926/spellbinder-orb
https://classic.wowhead.com/item=2957/journeymans-vest

**Expected behavior**
After having my item sold i expected to get the silver i put it up for minus the AH charge.

**Screenshots/videos**
![WoWScrnShot_101420_182521](https://user-images.githubusercontent.com/72893166/96048884-89291480-0e77-11eb-9296-08aa8b62719d.jpg)
![WoWScrnShot_101420_182541](https://user-images.githubusercontent.com/72893166/96048886-8a5a4180-0e77-11eb-8975-3422284ef956.jpg)
![WoWScrnShot_101420_182544](https://user-images.githubusercontent.com/72893166/96048888-8b8b6e80-0e77-11eb-86a5-c0399d15208e.jpg)
![WoWScrnShot_101420_182546](https://user-images.githubusercontent.com/72893166/96048896-8cbc9b80-0e77-11eb-8f04-a38de38254a0.jpg)
![WoWScrnShot_101420_182548](https://user-images.githubusercontent.com/72893166/96048900-8dedc880-0e77-11eb-8080-19de45e7b6be.jpg)

**Comment by DragoonKafei** [comment]
Logged in on my alt and found the same problem. Lost around 5g. 
![WoWScrnShot_101520_004910](https://user-images.githubusercontent.com/72893166/96053755-6fd89600-0e80-11eb-9250-2bf5a34a0a13.jpg)
![WoWScrnShot_101520_004912](https://user-images.githubusercontent.com/72893166/96053756-70712c80-0e80-11eb-90a3-d385dca9601e.jpg)

**Comment by Jerrythemagicdog** [comment]
You're not losing anything, the gold arrives at the same time  as the notification.
