### ISSUE TITLE
Rescue OOX-09/HL! Escort Route Bugged

### ISSUE THREAD

**Issue by ahoxsey** [SunstriderEmu/BugTracker#4330]
While escorting the Homing Robot it will eventually start walking into the sky disappearing from view and never giving a quest completion.

**To Reproduce**
1. Begin escort quest "Rescue OOX-09/HL!
2. Follow escort to point where owlkin spawn and kill them.
3. After Homing robot will start to walk into the sky rising while still following the path it is supposed to eventually disappearing from view.
4. Quest does not complete even if waiting in general area for some time.

**Expected behavior**
Escort is supposed to continue along the ground path till the overlook cliffs are reached then rocket off into the sky as quest completion is issued.

**Comment by Jerrythemagicdog** [comment]
The Homing Robot credited me correctly at the end of the path before he used the jetpack and flew away, are you sure you weren't in a raid or some other player in your party didn't start the quest?

**Comment by ahoxsey** [comment]
Yeah, I was in a party but the other player had already done the quest. I tried dropping and restarting and got the same result the second time.

**Comment by ahoxsey** [comment]
Tried again solo, same bizarre behaviour. 
![Screenshot from 2020-10-16 00-40-27](https://user-images.githubusercontent.com/27936240/96218086-931b4800-0f49-11eb-90e0-c88be7f2fe51.png)

**Comment by Jerrythemagicdog** [comment]
That's expected, the homing robot flies away after announcing so with a rocket boots effect.
I can't reproduce not getting credit at the end though.

**Comment by ahoxsey** [comment]
Yeah, it isn't rocket booting though, it just goes at a walking pace into the sky.

**Comment by ahoxsey** [comment]
And no announcement is made.

**Comment by Jerrythemagicdog** [comment]
Can't reproduce on live or locally, disable some addons, clear Cache and try again.
