### ISSUE TITLE
Magtheridon BUG with debris hit

### ISSUE THREAD

**Issue by pabloxxi** [SunstriderEmu/BugTracker#4331]
debris hit kills the tank in one hit without knocking the cealing rocks off it.
please fix this bug
 
thanks

**Comment by Jerrythemagicdog** [comment]
https://wowwiki.fandom.com/wiki/Magtheridon_(tactics)

_Collapses kill everybody in an 8 yard radius of the spot of impact. There is a cave-in animation shortly preceding it so players are able to safely move out of the way._
