### ISSUE TITLE
Warlock Quests: Succubus and Fel Hound

### ISSUE THREAD

**Issue by Faukeu** [SunstriderEmu/BugTracker#4334]
**Describe the bug**

Character named Elfingyomom. I decided to only do the voidwalker quest and lvl up through dungeons with my friend who is lvl 70 and I got to lvl 70 without doing any of the warlock quests (except for the voidwalker which i used throughout lvling). Now that I am trying to get all my demons, i cannot get the fel hound and succubus quests anywhere. i have tried silvermoon(character is a Blood Elf), Undercity, and even Orgrimmar. I get different quests such as "An Imp's request", "Mor'zul Bloodbringer", "in search of Menara Voidrender" but I do not get the  quests to get the Succubus and Fel Hound. I have looked in my spell book and talked to the trainer, to see if I already have them. I do not. Please help me
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
You've started the chain in Orgrimmar for Succubus and left it off at "Zankaja" and started the Felhunter chain and left it off in Undercity at Jorah Annison.
