### ISSUE TITLE
Outbid on AH - Bug.

### ISSUE THREAD

**Issue by Niglathag** [SunstriderEmu/BugTracker#4335]
~ Describe ~
Lose gold after been OUTBID on AH.

1. Just tried to bid 650g for "The 2 Ring".
2. I got Outbid.
3. Don't get the money back.

Screenshots:
I opened a ticket in game and you guys told me about this page, so i'm here.
https://imgur.com/a/TtC0gKj

Tell me what more i can do to solve the problem, is my first time reporting ;D

**Comment by Jerrythemagicdog** [comment]
You've won the auction for the Ring for 500 gold on 2020-10-15 13:32:51, in fact it's even in your inventory.

**Comment by Niglathag** [comment]
Plz help me, i'm not liying.
I bid for the one ring like 1day before this 2020-10-15 13:32:51.
I lose the bid then i decide to try buy another and this time i found one for 500g.
