### ISSUE TITLE
Waiting for pending account recovery

### ISSUE THREAD

**Issue by sMuve** [SunstriderEmu/BugTracker#4336]
Hello,

I have written an email >96h ago and asked for an account recovery. You asked for it in another issue and I didn't get a response... I asked multiple times on discord and didn't even get an answer. I'm very sad and disappointed :-( I know you guys have much to do, but it isn't actually such a big thing.

PLZ HELP ME! I just want to play a bit tbc in the few spare time I have. I also spend quite a few big bucks on endless, because I believe in you guys, but actually I'm losing my faith :-( 

If you look for Smuve in your hello@endless.gg mailbox, you'll find my request for sure!

Best regards
sMuve

**Comment by Jerrythemagicdog** [comment]
This tracker is for in-game issues only.
