### ISSUE TITLE
2 Step Authentification is not working, please fix.

### ISSUE THREAD

**Issue by Losjkfake** [SunstriderEmu/BugTracker#4337]
The 2 step authentification is not working.

I scanned the QR code once, which let me to download an app called FreeOTP.

with this app I scan the QR code again and it also gets recognised as endless wow.

However, when I now generate a code and try to put it into endless WoW website it will always say "invalid code" although I followed the steps on endless wow without mistake,

bugged since several days now. Please fix.

regards Los

**Comment by Jerrythemagicdog** [comment]
Try using Google Authenticator which is what most players are using.

**Comment by Losjkfake** [comment]
It didnt change a thing...still not working.

**Comment by beraus** [comment]
Everything is OK on our side - try with https://authy.com/

**Comment by Losjkfake** [comment]
HI Heraus Could you maybe take a look into my account? Even with 2fa it is not working.

I tried 4 different authenticators already, it keeps saying invalid code..

Account name Aftermath, thanks alot mate.
