### ISSUE TITLE
Acc hacked! 

### ISSUE THREAD

**Issue by sexygreattheone** [SunstriderEmu/BugTracker#4339]
My account got hacked! Today i wanted to play my warrior and realised that i could not. I entered the world on my twink acc and saw my character running around. Every time i am trying to wisper him, i got instantly added to ignore list.

1. It was my original e-mail with all passwords on it that i can give if needed. 
2.  I can provide all proves that this is my account

Help me please to get my account back. Please restore there my original e-mail so i can take my account back.

**Comment by Jerrythemagicdog** [comment]
You sold your account and you're now trying to claim it back.
