### ISSUE TITLE
UC died on elevator when i shouldn't have, unstuck failed

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4345]
i rode the elevator in UC up and died randomly for no reason (lisbeth) at approximately 3:32 on 10/19/2020 (server time).  the other 4 people I was with did not die, just lisbeth.  

i could not ress the corpse even though it was visible on the elevator.  i couldnt at the top (line of sight).  i couldn't on the elvator.  i couldn't at the bottom.

I used the website to unstuck which said "Lisbeth teleported and ressed successfully" but my char was still a ghost in roughly the same spot.  looked on map, no grave marker, no corpse or option to ressurect.   could not try and unstuck again because it was too soon.

found an angel luckily on my way out of UC (cuz i had no idea where the nearest or any angel was) and took ress sickness.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update. https://github.com/kelno/sunstrider-scripts/commit/f0cb4ad6116d85f5741bb0f79702509839763d6d
