### ISSUE TITLE
Warlock Tier 6 set bug

### ISSUE THREAD

**Issue by jerryplz** [SunstriderEmu/BugTracker#4346]
**Describe the bug**
Equipping 4 pieces of warlock tier 6 set cancels Fel Armor (both rank 1 and rank 2)

**To Reproduce**

1. Cast Fel armor
2. Equip 4 pieces of warlock tier 6 set, note that you have to equip 4 pieces. Equipping 1, 2 , or 3 pieces does not cancel Fel armor.

Item: 
https://www.wowhead.com/item=31050/gloves-of-the-malefic
https://www.wowhead.com/item=31051/hood-of-the-malefic
https://www.wowhead.com/item=31053/leggings-of-the-malefic
https://www.wowhead.com/item=31054/mantle-of-the-malefic

Spell: https://www.wowhead.com/spell=44520/fel-armor

**Expected behavior**
Fel armor shouldn't be canceled.

It looks like the 4 set bonus that's causing the issue rather than the individual items.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update. https://github.com/kelno/sunstrider-scripts/commit/c9c0413195cc18649e4ebc08e3095d809afeed74
