### ISSUE TITLE
shattered halls, pet pathing through closed door

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4348]
door to the first boss is closed, if you jump down without dismissing your pet, your pet runs through the closed door and the tunnel to reach you.

usually wipes group cuz it pulls everything along the way.

pet probably shouldnt run through a closed door.  no idea if you can do it here, but on some servers you can pull 1st boss through door with pet tricks like this.

**Comment by Jerrythemagicdog** [comment]
You can't pull the boss because of protection against it but the pet has no notion of the door existing so you'll have to dimiss the pet and summon it downstairs unless we make some workaround there.

**Comment by michaelkittrell** [comment]
ok my apologies, i forgot to dismiss my pet and they floated down when i jumped down.
