### ISSUE TITLE
grand warlock netherkurse shh normal

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4350]
after reaching about 20% boss walks up to his steps and paths back and forth endlessly.  

he does melee swings but doesn't seem to do anything else.  i melee'd him to death as a prot pal taking breaks to regen health/mana over the course of 2-3 minutes.

he used to spin and throw shadow bolts at people, current behavior doesn't seem right.

**Comment by michaelkittrell** [comment]
also, some of the linking/agro radius seem ... weird.  4 mobs in 1 pack will be standing next to each other and if you pull one with arcane torrent, only 2 come even though a body pull woudl certainly pull all 4.   noticed this in several places.  picture of one.  this mob is part of a pack of 5 but somehow because i arcane torrented the darkcaster, he never agrod.  depending on where the legionaire is in his path you can actually pull just 2 or 3 of the mobs isntead of 4 like i did here.  

if you want to separate the packs to make it easier cool, but it just seems odd and unintuitive how the agro works here and in several places in shh.

![image](https://user-images.githubusercontent.com/5479930/96534927-919d9880-1245-11eb-9a02-ab8760ceb1c3.png)

**Comment by michaelkittrell** [comment]
in this picture, i pulled the acolyte on the left and got the legionaire and the acolyte.  then i pulled the darkcaster and got that one and a savage.   So basically i managed to pull 1 pack of 6, 2 mobs at a time because i used a single target arcane torrent to pull.

![image](https://user-images.githubusercontent.com/5479930/96540892-ada83680-1253-11eb-87e4-f403d0c5dd3c.png)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, indeed he stopped spinning.
Fixed with next restart.
