### ISSUE TITLE
enemy pets don't attack you when you aggro their master

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4352]
**Describe the bug**
all enemy pets should immediately run to the player and attack them when they aggro the enemy master, regardless of distance.  currently, all enemy pets will only aggro their master's target when the player goes too close to the pet.

**To Reproduce**

1. aggro an enemy with a pet at 20-30y range.
2. watch the pet follow its master like a dufus while its master runs toward you (or ranged attacks if the master is a ranged/caster class)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, we'd need to see some specific examples of which creatures specifically you mean, some are actual pets and summons, some are just spawned next to them and aren't actually their pets.

**Comment by tankfest** [comment]
the quilboar hunters just outside of crossroads to the east are a perfect example, head out there, and ranged attack the hunter.  you'll see the wolf just sits next to them while the hunter ranges you.  i'm not sure how deep the issue extends.

**Comment by kelno** [comment]
Thanks for reporting, fixed with next server update
