### ISSUE TITLE
burrowing worms in hellfire peninsula keep moving on their patrol path even when aggroed

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4353]
**Describe the bug**
the worms that burrow and pop up when players are nearby in hellfire peninsula will aggro a player, but keep moving on their patrol path while popped up and attacking, even if it's away from the player.  they should stay in place until the player kills or runs away from them, at which point they re-burrow.

**To Reproduce**

1. aggro one of those burrowing worms
2. watch it slowly slide away from you while nuking you.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed in next update. https://github.com/kelno/sunstrider/commit/551c5ac6a8d1a36107f2850cd9beacb759dfe206
