### ISSUE TITLE
wolf rider npcs in hellfire peninsula don't despawn their pets immediately when they lose aggro

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4354]
**Describe the bug**
they should immediately lose their pets, because they remount when they de-aggro... instead for about 10-15 seconds, they have both a pet AND a mount.
![image](https://user-images.githubusercontent.com/37684138/96665183-2a491c80-1309-11eb-8e03-fe5624291860.png)

**To Reproduce**

1. engage one of the wolf riders at Zeth'Gor
2. lose aggro and watch them run back to their patrol path with two doggies

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
