### ISSUE TITLE
knockback animation on mobs needs a cooldown of some sort

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4355]
**Describe the bug**
so i'm in the ramparts dungeon, killing orcs with a group of 5, and by me using hellfire, my pld buddy using consecrate, and everyone else beating on the same mob, the orcs look like they are getting MASSIVE whiplash from their "i've been hit" animation triggering 6 times each second.  on retail, there is definitely an internal cooldown for them displaying this animation.

**To Reproduce**

1. enter ramparts instance, use many damaging abilities on the same orc

ign: Dankeykong

**Comment by Jerrythemagicdog** [comment]
This is not something we control.
