### ISSUE TITLE
quartermaster urgronn sells single units of lvl 45 water for 18s

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4356]
**Describe the bug**
he is definitely supposed to sell them in multiples of 5, his food too.  one is lvl 45, the other is lvl 55... seems off.
![image](https://user-images.githubusercontent.com/37684138/96690155-2c769f80-1338-11eb-8163-8e145e2cfa5d.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
