### ISSUE TITLE
flight path npcs require you to talk to them again in order to use them after unlocking the path for the first time

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4357]
**Describe the bug**
in retail, when you right click a new windrider master, it immediately opens up your possible destinations to fly to.  here, it gives a default dialogue, you have to close the dialogue and re-open with the flight master to travel elsewhere.

**To Reproduce**

1. right click a new windrider master
2. observe that they don't let you fly somewhere in the window that pops up
3. close that window, and talk to them again
4. now, you can fly where you want

![image](https://user-images.githubusercontent.com/37684138/96694291-220ad480-133d-11eb-8580-d9e792b7c370.png)

**Comment by Jerrythemagicdog** [comment]
Most likely not something we can do anything about.
