### ISSUE TITLE
when failing to turn in a quest that rewards an item, you must close dialogue and re-turn in quest to accept

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4358]
**Describe the bug**
when failing to turn in a quest that rewards an item, you must close dialogue and re-turn in quest to accept.  in retail, you can just hit accept again without closing the dialogue window and it will give you the item and complete the quest.

**To Reproduce**

1. have a full inventory
2. try to turn in a quest that rewards an item, it will say you have no room
3. with the same quest-npc dialogue window still open, clear a spot in your inventory
4. hit the accept turn in button again to receive your quest... it will error out when it should just give you the reward.

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Yes, that's TBC client.
