### ISSUE TITLE
issue in den of haal'esh with pets entering the cave

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4359]
**Describe the bug**
this is the second time i noticed this.  when i'm sending my pet into the den to attack a mob, they sit there at the edge trying to figure out what to do.

**To Reproduce**

1. stand outside the cave where the bird is, with your pet
2. have your pet assault the bird
3. he will go to the edge of the cave and stare at the bird

![image](https://user-images.githubusercontent.com/37684138/96692355-c9d2d300-133a-11eb-940a-31791635d337.png)

**Comment by Jerrythemagicdog** [comment]
Possibly maybe resolved after today's update.

**Comment by Jerrythemagicdog** [comment]
Fixed with next update, thanks.
https://github.com/kelno/sunstrider/commit/f402c0e46554c2cb873e2bdf9f1453e1304f005a
