### ISSUE TITLE
[#86] Marsh Lurker and Marsh Dredger do not have Blizz-like behaviour

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#436]
<a href="https://github.com/plutonium447"><img src="https://avatars0.githubusercontent.com/u/40911527?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [plutonium447](https://github.com/plutonium447)**
_Friday Dec 21, 2018 at 07:30 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/86_

----

**Current behavior:**
Marsh Dredger and Marsh Lurker NPCs do not aggresively attack Sporelok NPCs in the zanagrmarsh cave at 71.3, 97.7 .  The two NPCs just stare at each other. This behaviour is not blizz-like.

![wowscrnshot_121818_081131](https://user-images.githubusercontent.com/40911527/50325912-30b2b580-0533-11e9-87bd-f6fab5bc5fff.jpg)
_The Marsh Lurker and Marsh Dredger NPCs do not egage in combat against Sporelok NPCs when they spawn._

**Expected behavior:**
Marsh Dredger and Marsh Lurker NPCs should attack on sight Sporelok NPCs.
_"Sporelok are sporelings found in Funggor Cavern. They can be seen fighting the Marsh Lurkers and Marsh Dredgers."_ - gamepedia

**Steps to recreate issue**
Step 1: Go to around 71.3, 91.7 in zanagrmarsh
Step 2: Enter the cave
Step 3: Watch when Sporelok NPCs spawn, they are not attacked by Marsh Lurkers or Marsh Dredgers

**id's:**
[creature 1] = Sporelok (18912)
[creature 2] = Marsh Lurker (18136)
[creature 3] = Marsh Dredger (18137)

**Source(s)**
https://www.wowdb.com
https://wow.gamepedia.com/Sporelok

**Comment by kelno** [comment]
<a href="https://github.com/Kittnz"><img src="https://avatars2.githubusercontent.com/u/5845231?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kittnz](https://github.com/Kittnz)**
_Friday Dec 21, 2018 at 15:55 GMT_

----

maybe a faction problem for these npcs

**Comment by Jerrythemagicdog** [comment]
Thanks, confirmed to be working correctly now - there was an issue with creatures not updating until one of them moves.
