### ISSUE TITLE
bloodthirsty marshfang stuck in wall in zangarmarsh (52.1, 58.8)

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4361]
**Describe the bug**
watched him for about 30 seconds, he seems stuck:
![image](https://user-images.githubusercontent.com/37684138/96724121-547bf800-1364-11eb-946e-e709b0cd07c2.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, it's free after next update.
