### ISSUE TITLE
Hallow's End Pumpkin Facing Wrong Way

### ISSUE THREAD

**Issue by confessore** [SunstriderEmu/BugTracker#4362]
**Describe the bug**
pumpkin is facing the wrong way

**To Reproduce**
1. Just look at it!

hallow's end pumpkin

**Expected behavior**
pumpkin should be facing the center of shattrath

**Screenshots/videos**
https://i.imgur.com/NuIDt3g.png

**Additional context**
seems insignificant!

**Comment by Jerrythemagicdog** [comment]
Or should it be spooking the players coming down the ramp?
