### ISSUE TITLE
Seal of Light

### ISSUE THREAD

**Issue by Shonner23** [SunstriderEmu/BugTracker#4363]
**Describe the bug**
Last raid night I notice that my judgement of light didn't refresh after melle hits so i was forced to reaply it every 20 seconds. Whats more the seal healed the players for the base 95hp not getting the bonus from my bonus healing.

**Comment by Jerrythemagicdog** [comment]
Judgement of Light is not supposed to scale with your healing.
I can't reproduce not refreshing, maybe it got pushed off visually off the debuff bar that lead you to believe that or perhaps some addon interferes with the duration not being displayed correctly.
