### ISSUE TITLE
razormane seer has identity issues

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4365]
**Describe the bug**
the seer that wanted to be a rogue (42.2, 78.5 in barrens)
![image](https://user-images.githubusercontent.com/37684138/96798112-06431500-13b5-11eb-935c-c39d1eb001d0.png)

**Comment by Jerrythemagicdog** [comment]
Years of training unfortunately were not enough for the Razormane Seer to become a Rogue and he's back to his old Seer self (with the next server update, he's still trying now).
