### ISSUE TITLE
razorfen thornweavers outside of RFD always use heal on themselves immediately when they engage in a fight

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4366]
**Describe the bug**
if i aggro a thornweaver, it will begin healing itself immediately, even if it's at full health.  they may need their heal recast delay timer increased, too, as they seem to spam it.

**Comment by Jerrythemagicdog** [comment]
Indeed, the previous timer didn't make any sense, thanks for the issue.
Fixed with next server update.
