### ISSUE TITLE
Server Restart on Wednesday Despawns ZA Chests

### ISSUE THREAD

**Issue by Elunekin** [SunstriderEmu/BugTracker#4367]
**ZA Chests Despawned**
At around 12:15 ST, the timed Zul'Aman bear Pumper's run had a server restart cut in. After the restart, we see that our timed chests have respawned. We were lucky and had opened the Third chest, but that's all we were able to see.

Server restarts can sometimes be unavoidable, but we expected to have Wednesday clear of restarts for a timed ZA bear run. Would be awesome if there could be a way to respawn the chests!

**Comment by Jerrythemagicdog** [comment]
Please contact me on Discord (Jerry#9132) so we can arrange solving this.
