### ISSUE TITLE
Naxxramas trash mobs have way too much HP

### ISSUE THREAD

**Issue by N4xx** [SunstriderEmu/BugTracker#4369]
**Describe the bug**
The majority of the trash mobs in Naxxramas have way more HP than they should have, thus making them in effect unkillable. There are only a couple of mobs in there that have the correct amount of HP, but these mobs do not appear to have a loot table as they should, which may be the case for all mobs in there (this cannot be tested though since the mobs with the extremely high HP pools cannot be killed)

Mobs with incorrect health values:
Deathknight (https://tbcdb.com/?npc=16146) - Has 389202k, should have 75,456
Risen Deathknight (https://tbcdb.com/?npc=16154) - Has 129734k, should have 25,152
Shade of Naxxramas (https://tbcdb.com/?npc=16164) - Has 288848k, should have 56,000
Dark Touched Warrior (https://tbcdb.com/?npc=16156) - Has 134108k, should have 26,000
Skeletal Smith (https://tbcdb.com/?npc=16193) - Has 259468k, should have 50,304
Deathknight Captain (https://tbcdb.com/?npc=16145) - Has 486502k, should have 94,320
Bony Construct (https://tbcdb.com/?npc=16167) - Has 194601k, should have 37,728
Deathknight Cavalier (https://tbcdb.com/?npc=16163) - Has 466960k, should have 113,175
Patchwork Golem (https://tbcdb.com/?npc=16017) - Has 454069k, should have 88,032
Bile Retcher (https://tbcdb.com/?npc=16018) - Has 551369k, should have 106,896
Sludge Belcher (https://tbcdb.com/?npc=16029) - Has 432220k, should have 80,925
Living Monstrosity (https://tbcdb.com/?npc=16021) - Has 242043k, should have 45,318
Mad Scientist (https://tbcdb.com/?npc=16020) - Has 207554k, should have 50,304
Surgical Assistant (https://tbcdb.com/?npc=16022) - Has 170228k, should have 42,728
Carrion Spinner (https://tbcdb.com/?npc=15975) - Has 291901k, should have 56,592
Infectious Skitterer (https://tbcdb.com/?npc=15977) - Has 77370k, should have 15,000
Dread Creeper (https://tbcdb.com/?npc=15974) - Has 243251k, should have 47,160
Venom Stalker (https://tbcdb.com/?npc=15976) - Has 486502k, should have 94,320
Infectious Ghoul (https://tbcdb.com/?npc=16244) - Has 486502k, should have 94,320
Plague Slime (https://tbcdb.com/?npc=16243) - Has 729753k, should have 141,480
Stoneskin Gargoyle (https://tbcdb.com/?npc=16168) - Has 1362098k, should have 264,075

These are the mobs that I found that have the correct HP values:
Death Touched Warrior (https://tbcdb.com/?npc=16158) - 24759
Doom Touched Warrior (https://tbcdb.com/?npc=16157) - 25152
Necro Stalker (https://tbcdb.com/?npc=16453) - 81744

Another to note is that all these mobs should have a 1% chance to drop every epic on the Naxxramas trash loot table.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, Naxx needs a complete rework is not in a playable state at the moment.
We'll close it for the time being.

**Comment by N4xx** [comment]
Is there any chance to just get the HP on the mobs fixed as there's an item I would really like to get from the trash mobs?

**Comment by Jerrythemagicdog** [comment]
We can look into it soon, I can't make any promises but it shouldn't take long and this is long overdue.

**Comment by N4xx** [comment]
Alright, thanks a lot, really appreciate it. You're doing fantastic work here.
