### ISSUE TITLE
cancelling a channeled spell while other people are helping channel.  

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4370]
if you are casting a spell like soulwell, summon, ritual of refreshment.... and people are assisting (channeling) and you interrupt before the spell completes, the people who were clicking are not interrupted and continuing to channel the cancelled spell for at least 30s (probably never stops until they interrupt it by moving).

**Comment by kelno** [comment]
Fixed with next server update
