### ISSUE TITLE
mobs patroling as 1 in steam vaults

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4372]
in steam vaults normal

as of the last 48 hours, the 3 mobs (war and 2 sirens) before 1st boss, and the 3 mobs in the hallway (sorc and 2 war) are patrolling on top of each other (pretty much as one unit) instead of spread out in their traditional triangle formation.

**Comment by beraus** [comment]
Fixed after next reset. Thanks!
