### ISSUE TITLE
shh mob packs that aren't linked

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4373]
several places in shh, mobs that stand as a pack of 5-6 are pullable in some pretty interesting ways.  a 70 prot pal pulling with belf racial can single pull, or double pull or double pull 3x out of the same group of mobs.  a body pull would pull the entire pack.  one of the packs in the room with the centurions (on the 2 sides) if you pull the darkcaster, he comes solo.  standing with a pack of 5-6 and you can pull him solo...

wasn't sure whether to report it, but agro radius's in several places on teh server seem to have changed significantly recently.  maybe these mobs need to be linked so the entire pack pulls, maybe you like it this way so its easier, but it seems odd to pull a mob through other mobs without agroing them.

pulls like this have existed since opening of the server, but usually it was a little more reasonable, pulling 4 instead of 6 ... instead of now pulling 2 or even 1 in the same situation.

**Comment by beraus** [comment]
Fixed after next reset, thanks!
