### ISSUE TITLE
sv hydromancer thespia audio taunt after death

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4374]
if you die (like to the hurricane) after the boss dies, she still says her audio taunt.    so for example she dies (she says her death audio) 3s later you die from hurricane (she says her killed you audio)

maybe despawn the hurricane?  or add a check to see if shes alive before playing the taunt.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
