### ISSUE TITLE
gruul, HKM, kiggler moves after cast

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4375]
gruul, high king mulgar fight... kiggler the crazed (the one that does the aoe blast and knockback) takes a step towards the tank between casts which makes tanking it with a boomkin/hunter pretty hard/impossible.   

not sure this is still a thing since groups just take a 4th tank instead, but i was reading the update for 9/5/2020 changelog and it said this:  High Astromancer Solarian will reset her swing timer after Arcane Missiles cast finishes.

can kiggler get the same treatment so he doesn't move after cast.

**Comment by kelno** [comment]
Thanks for reporting, fixed with next server update.
The way it will work now is that he'll start chasing in melee only if you get close in melee to him.

**Comment by michaelkittrell** [comment]
tested it out twice this week, seems to be working great!
