### ISSUE TITLE
vorsha the lasher quest bugs out

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4377]
**Describe the bug**
i did this quest a week ago or so, but my recollection is that the npc you are escorting completely ignores all naga on his way to the brazier... then he disappears in the middle of the brazier event before vorsha even spawns so the escort quest can't even complete.  it needs to be investigated.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with the next update.
