### ISSUE TITLE
mobs patrolling stacked on top of each other in blood furnace

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4378]
**Describe the bug**
saw the report about steamvaults yesterday, then just caught them doing it, this specific patrolling pack that we're killing:
![image](https://user-images.githubusercontent.com/37684138/97049403-8346c980-1530-11eb-91a5-ac76636dfc7d.png)

**Comment by tankfest** [comment]
found some murkblood invaders doing the same thing in nagrand now, too (patrolling on path through 28.9, 54.4):
![image](https://user-images.githubusercontent.com/37684138/97064296-b5b8ec80-1559-11eb-8857-b061c4f0edd7.png)

**Comment by Jerrythemagicdog** [comment]
Fixed with next update, thanks.
