### ISSUE TITLE
Quest "By Any Means Necessary" bug

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4380]
**Describe the bug**
the npc you talk to, empoor, can be killed too quickly for him to surrender and give up the information.  i accidentally hit him once with a windfury and it took him to 30%, and he never stopped fighting when i hit damaged the rest of the way to 0 health:
![image](https://user-images.githubusercontent.com/37684138/97098086-4b29ae80-1636-11eb-9545-17be5b25e56b.png)

**Comment by tankfest** [comment]
also, for whatever reason, people in party also on the quest don't get shared credit for it.

i just killed him again, he didn't turn friendly, he just died again, and it was a slow kill.

**Comment by tankfest** [comment]
further info on this... so i had two people in the party, dankeykong talked to him first and his low hp triggered completion properly.  bruisefest talked to him second, and that's when i killed him for the first time, then i waited for respawn and killed him again hoping he'd complete the quest but he didn't.

then, when he respawned again, i killed his bodyguard first, then tried lowering his hp to 10%, but that didn't work, so i had both chars run away from him to lose aggro (he began walking but his body guard who immediately respawned did not).  i then dropped party on bruisefest and talked to him, which caused him to aggro me, but not his body guard (glitch of some sort), and he completed the quest around 40% hp.  there's possibly an issue with this quest when in party, or if he's talked to twice in a row.

**Comment by Jerrythemagicdog** [comment]
Thanks for the details, it was the party causing the issue here and a check for the attacking's player quest status.
Fixed with next update.
