### ISSUE TITLE
graphical issue with bone crawler

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4381]
**Describe the bug**
they don't pop up immediately, and are invisible while in combat (specifically the one in terokkar at 43.2, 49.2:
![image](https://user-images.githubusercontent.com/37684138/97099390-98f9e300-1645-11eb-8789-7076506f8c4e.png)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
