### ISSUE TITLE
ITEM  [Hammer of Righteous Might] still didnt EXIST!!

### ISSUE THREAD

**Issue by moinmutti** [SunstriderEmu/BugTracker#4382]
**Describe the bug**

it just looks like u guys are not able to fix this like month, i thing the bug is the server owner and crew...
cant beleeve that no1 cares , game master just writing the same shit again and again!

https://www.wowhead.com/item=33954/plans-hammer-of-righteous-might
https://www.wowhead.com/item=33954/plans-hammer-of-righteous-might
https://www.wowhead.com/item=33954/plans-hammer-of-righteous-might
https://www.wowhead.com/item=33954/plans-hammer-of-righteous-might
https://www.wowhead.com/item=33954/plans-hammer-of-righteous-might
https://www.wowhead.com/item=33954/plans-hammer-of-righteous-might

btw i reported the bug the 3rd time now... 
the community is dead soon if u guys dont care about player, just saying

greedings

**Comment by Jerrythemagicdog** [comment]
Fixed with next update, thanks.
