### ISSUE TITLE
Reached in-game cap of unique mail recipients

### ISSUE THREAD

**Issue by meru012** [SunstriderEmu/BugTracker#4383]
**Describe the bug**
I get the error message that I've Reached in-game cap of unique mail recipients when I try to mail stuff from my main toon to my bank alt and cannot send anything out from my main toon.

**To Reproduce**
1. open mailbox.
2. start new mail and add in the items to send.
3. click send.
4. receive error message and the mail did not send.

**Expected behavior**
I expected my mail to send from my main toon to my bank alt. 

**Additional context**
My account name is ameruelo. The problem I am having is on Rhuun. I can send mail from my bank alt to my main toon but not the other way around. This problem has been ongoing for more than 24 hours. I submitted an ingame ticket and the GM responded that this was working as intended. I disagree.

**Comment by kelno** [comment]
This error should only appear if the receiver character already has too many mails in mailbox. The limit is currently 100. Could it be your issue here?

**Comment by meru012** [comment]
That seemed to be it. Thank you.
