### ISSUE TITLE
Quest - In Need of Felblood

### ISSUE THREAD

**Issue by Kersin67** [SunstriderEmu/BugTracker#4384]
Description:

Location - Pools of Aggonar
Mob - Terrorfiend
Drop - Fel Blood Sample
Request - 6x Fel Blood Sample

The drop rate is actually terribly low. I have killed about 40 Terrorfiends and got only 2 Fel Blood Samples.

Item: https://www.wowhead.com/item=23269/felblood-sample
Quest: https://www.wowhead.com/quest=9366/in-need-of-felblood

**Expected behavior**
Compared to official drop rate, it should be around 25% drop rate.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
