### ISSUE TITLE
Holy Priest Spirit of redemption takes damage and dies, preventing further healing

### ISSUE THREAD

**Issue by kasamuel** [SunstriderEmu/BugTracker#4386]
Holy Priest Spirit of redemption takes damage and dies, preventing further healing.

First noticed in BT near Supremus with Dragonmaw Wind Reaver air attack.

Priest takes damage from air attack, killing them while pulling aggro by healing. This puts them into Spirit or Redemption form. The second fireball kills the spirit of redemption form and prevents the priest from healing.
The form persists after the "second" death for the full duration, but no healing or movement (spinning in place) can occur.

The following death, regardless of the way the priest dies, the spirit of redemption is unusable, like above. The form persists, but no action can happen.
Suspect this will happen until release, every time the priest is rezzed by a teammate.

https://www.wowhead.com/npc=23330/dragonmaw-wind-reaver

**Comment by kelno** [comment]
Thank you for reporting.
It seems spirit of redemption doesn't prevent spells already in flight from hitting.

**Comment by kelno** [comment]
Fixed with next server update
