### ISSUE TITLE
Quest "Zuluhed the Whacked" issue

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4387]
**Describe the bug**
the quest is a 5 person group quest, but the event starts as soon as one person accepts the quest from the drake at the top of the camp.  this causes you to have to do it multiple times, or to mount up and fly away before he gets to you so that you can reset the event and allow the next person to accept the quest.  it needs to be shared automatically to the group when the first person accepts it, or some other mechanic to fix this issue.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
