### ISSUE TITLE
Netherstrom (The Stormspire)

### ISSUE THREAD

**Issue by Viesiiss** [SunstriderEmu/BugTracker#4388]
Hello!

Netherstrom City -> (The Stormspire)

Not working elevator to get up to city.

**Comment by Jerrythemagicdog** [comment]
Can't reproduce, do you maybe have a clip of it?

**Comment by Viesiiss** [comment]
@Jerrythemagicdog 

Sure, here video.
https://vimeo.com/472982541

**Comment by Ironjudgment** [comment]
The elevator in the video seems awfully small compared to the one I have :S

Mine:
![image](https://user-images.githubusercontent.com/33090790/97726346-08008d00-1ac7-11eb-9ba9-f69d4c13633a.png)


Yours:
![image](https://user-images.githubusercontent.com/33090790/97726422-18186c80-1ac7-11eb-98b9-602d84e09b5b.png)

Are you using original textures, or tried to delete cache?

**Comment by Dokandree** [comment]
Had the same issue. Clearing the cache solved it.
