### ISSUE TITLE
Auction house doesn't return bid when outbid

### ISSUE THREAD

**Issue by Easyhistory** [SunstriderEmu/BugTracker#4389]
Put bid on several items at AH. Went offline. Got outbid. When i came online there was no bid return mail in the mailbox. This happened several time during past 2 weeks.

PS: Who will return my gold back now? ~150g already lost.

**Comment by Jerrythemagicdog** [comment]
I don't see that happening in my tests, what's your character name?

**Comment by Easyhistory** [comment]
With Finegrip - put several bids yesterday on some items at AH. Logged in today and found that i was outbid, and there was no mail about this.
With Easyhistory - bidded an Insightul earstorm diamond gem last week. The same, logged in and found no gold and no gem.

**Comment by Jerrythemagicdog** [comment]
Could you provide more details with the amounts you've bid?

**Comment by Easyhistory** [comment]
Dont quite remember for Finegrip, there have been 10 bids from 50 silvers to 1.5g.
On Easyhistory the bid was for 132g as i recall.

**Comment by Jerrythemagicdog** [comment]
Resolved in game.
