### ISSUE TITLE
Quest "Veil Lithic: Preemptive Strike" bugs

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4390]
**Describe the bug**
this quest has a few problems: 
1. when you approach a nest, sometimes a malevolent hatchling will immediately spawn for whatever reason, when it should not.
2. when you break an egg, two mobs spawn.  i kept getting two malevolent hatchlings, or one malevolent and one redeemed.
3. credit is not shared for redeeming them between party members as it should be.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
