### ISSUE TITLE
Quest "An Improper Burial" does not share credit between pt members

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4391]
**Describe the bug**
this is one of many quests we've run into that SHOULD be shared credit for other pt members on the quest, and it's not.  is this a known issue (or considered not an issue *shudders*), or do we need to be reporting all of these quests?

**Comment by Jerrythemagicdog** [comment]
Most likely deemed not an issue, most of these quests are for one player only. Current retail is much better at dealing with these quests and always crediting groups.

**Comment by Jerrythemagicdog** [comment]
However, it doesn't make sense to make these quests not completable in a group, updated with next restart.
