### ISSUE TITLE
Looted Rethban Ore as a horde

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4392]
**Describe the bug**
loot table seems off for this

**Comment by beraus** [comment]
Any specifics on this? Coords?

**Comment by tankfest** [comment]
no, he didn't note the coords of the point.  i assumed all of the tin nodes in barrens would have the same loot table

**Comment by tankfest** [comment]
he says 50,11 in barrens... approximate

**Comment by beraus** [comment]
To devs: Looks like only faction is an issue here.
https://classic.wowhead.com/quest=347/rethban-ore

**Comment by Jerrythemagicdog** [comment]
Seems possible even long into retail: https://www.wowhead.com/item=2798/rethban-ore#comments:id=2363755
