### ISSUE TITLE
Quest "Taken in the Night" issues

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4393]
**Describe the bug**
so i'm here trying to do this quest in a party... AFTER we started counting because the rate of sha'tar warriors to enemies was so bad, we had 2 done for one character out of 36 webbed prisoners killed, and to make matters worse, this quest is not shared for party members.  legit impossible to complete for 4 people doing it, needs to be fixed.

**Comment by Jerrythemagicdog** [comment]
Thanks, changed it to work with grouped players. Live with next restart.
