### ISSUE TITLE
Quest "Digging Through Bones" Issue

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4394]
**Describe the bug**
YIKES... you can attack the guy you're supposed to be escorting... i was tab targeting to get the scorpion he aggroed, and i targeted him and dotted him instantly, causing the quest to fail:

![image](https://user-images.githubusercontent.com/37684138/97389574-e3729e00-1897-11eb-9d94-c83abf486a94.png)

**Comment by Jerrythemagicdog** [comment]
Haha, thanks for the issue, fixed with next update.
