### ISSUE TITLE
Quest "Blood of the Warlord"

### ISSUE THREAD

**Issue by lrdelange** [SunstriderEmu/BugTracker#4396]
**Describe the bug**

After turning in the quest "Blood of the Warlord" I did not recieve the 10 BoJ, I have tried it on both my characters.

**To Reproduce**

1. Get the Blood from Zul'jin and turn in the quest
2. Check BoJ before
3. Check BoJ after

Quest: https://wowwiki.fandom.com/wiki/Blood_of_Zul%27jin

**Expected behavior**

To get 10 BoJ

**Screenshots/videos**

![image](https://user-images.githubusercontent.com/43291625/97404340-38dd9800-18f6-11eb-8971-e8f94706c55a.png)
(First quest gave the BoJ ... Blood did not...)

**Additional context**

**Comment by Jerrythemagicdog** [comment]
The quest that gives you badges is called "Undercover Sister" which is a follow up quest from Donna Brascoe next to Budd Nedreck.
