### ISSUE TITLE
"you receive loot" message doesn't show when winning a roll, and inserting item in inventory.

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4397]
**Describe the bug**
when you win an item in a loot roll need or greed, it should show that the item went in your inventory, but it currently does not:
![image](https://user-images.githubusercontent.com/37684138/97409865-87217580-18bb-11eb-82a6-4f60c6d7b905.png)

**Comment by hufsa** [comment]
Thanks, fixed with next restart.
