### ISSUE TITLE
Darkmoon Card: Madness pulls nearby mobs

### ISSUE THREAD

**Issue by D4emon** [SunstriderEmu/BugTracker#4398]
**Describe the bug**
Darkmoon Card: Madness can pull other mobs that you are not in combat with with the dementia debuff

**To Reproduce**
1. Kill a mob close to other mobs while you have Darkmoon Card: Madness equiped

https://www.wowhead.com/item=31859/darkmoon-card-madness

**Expected behavior**

**Screenshots/videos**
https://youtu.be/zCixTTFnLp0

**Additional context**
This can happen to other mobs/ in dungeons as well

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
