### ISSUE TITLE
using life tap without enough life doesn't give error message

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4400]

**Comment by Jerrythemagicdog** [comment]
Does for me in my tests: 
![image](https://user-images.githubusercontent.com/46463908/97543104-ad303e00-19bf-11eb-9f87-9d315f183c41.png)

**Comment by tankfest** [comment]
ign: dankeykong... you can watch me do it right now

**Comment by tankfest** [comment]
interesting, sometimes it fizzles and sometimes it doesn't depending on how much health i have (but always less than the required amount for me to gain mana)
