### ISSUE TITLE
Plans: Hammer of RIghteous Might x10?

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#4402]
Did a kara couple days ago, never seen this pattern "plans: hammer of righteous might", but it dropped like 4-5x (in a row) in about 10 mobs (heading to moroes).  (seems like a recent change)

seems suspiciously high.

similar issue, in botanica the tree mobs before warp splinter have a very very very high chance to drop mana potion injector schematic.  sometimes 2-3 in the 20 mobs or whatever you kill there. (true for a while)

**Comment by tankfest** [comment]
lol, was just coming to report this issue.  we got 5 of them in two dungeons, and i found another just now questing in netherstorm.

someone fudged up the global drop rate for this.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
