### ISSUE TITLE
The loot system is bugged and I lost the loot

### ISSUE THREAD

**Issue by Verionyang** [SunstriderEmu/BugTracker#4403]
**Describe the bug**

Item: https://www.wowhead.com/item=32078/pauldrons-of-wild-magic?bonus=6710
The team set up was a warlock, a tank pal, a heal priest, a balance druid and me an elemental shaman. 
When the boss was looted, only the loot frames for other items (the nether, the blue chest piece, and the gem) popped up and I was not able to choose roll or greed on the shoulder - pauldrons of wild magic. In the end, the priest greed on the item and got it for no good. And I, who really need this piece was not even given a chance to roll before the item was given to others. 
The priest is called Sehanine. It was not ninja root. The loot was simply bugged. 
The instance ID was 4771. 

**Expected behavior**
<Please verify the instance and boss drop. And I'd like to have the shoulder piece back then, as nobody would roll on the shoulder. I was the only one who needs it. -->

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/73673431/97642347-33db2e80-1a45-11eb-9bc3-7a4f649ea5da.png)

**Additional context**
<You may contact me in game. My character name is Fengchee. )

**Comment by Jerrythemagicdog** [comment]
Open a ticket in game.

**Comment by Verionyang** [comment]
> Open a ticket in game.

How can I do that?
