### ISSUE TITLE
grounded mobs don't immediately lose aggro when you're too high above them for melee hits

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4405]
**Describe the bug**
in retail TBC, when you aggroed a mob on the ground on your flying mount, then lifted into the air where they couldn't hit you, the mob would nearly immediately lose aggro.  here, they will stay aggroed to you and follow you (keeping you in combat), even though they have no chance of hitting you, even if you're way above the ground.

**Comment by Jerrythemagicdog** [comment]
Yes, that was a conscious change, thanks for the report though.

**Comment by hufsa** [comment]
Pls fix
