### ISSUE TITLE
Totem of wrath multiple stacking

### ISSUE THREAD

**Issue by Gloominator** [SunstriderEmu/BugTracker#4411]
Totems of wrath don't stack

**To Reproduce**
1. party with at least 2 shamans
2. cast 2 totems of wrath
3. they don't stack but they should

Spell: https://www.wowhead.com/spell=63283/totem-of-wrath

**Comment by Jerrythemagicdog** [comment]
Duplicate: https://github.com/SunstriderEmu/BugTracker/issues/2480
