### ISSUE TITLE
Fahssn, sporegar npc despawned and wont reappear.

### ISSUE THREAD

**Issue by samoxc** [SunstriderEmu/BugTracker#4413]
**Describe the bug**
The quest giver for natural enemies etc "fahssn" has vanished and cannot be found.

**To Reproduce**

1. N/A NpC is just gone
2. 
3. 

https://www.wowhead.com/npc=17923/fahssn

**Expected behavior**
he should be there

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Back with next update, thanks.

**Comment by samoxc** [comment]
Is there any form of timeframe? dopes this mean i cant do my rep for a few days/hrs?
