### ISSUE TITLE
Blessings deck sold in AH -> no golds received 

### ISSUE THREAD

**Issue by matej441** [SunstriderEmu/BugTracker#4414]
Blessings deck sold in AH -> no golds received 

1. Player Mening (me) sold Blessings deck in AH for 6999g
2. It has been sold and i did not receive golds.
3. 6999g full price -> 250AH cut -> 12g deposit

https://tbc-twinhead.twinstar.cz/?item=31890
https://www.wowhead.com/spell=39480/blessings-deck

Blessings deck sold in AH -> no golds received.
I checked and opened AH mail ingame 1.11.2020; about after 11am

no screenshot taken

I dont know who bought the item (I didn't really pay attention to that).

**Comment by Jerrythemagicdog** [comment]
The gold appears to still be in your mailbox, the auction was successfully concluded.

**Comment by matej441** [comment]
Apparently, golds are not in mailbox, either in bag.
As I remember correctly, I accepted golds, but no golds appear in bag.
![image](https://user-images.githubusercontent.com/73778622/97802156-c6482180-1c41-11eb-895e-ac6ea1d536db.png)
