### ISSUE TITLE
Not getting gold bid back

### ISSUE THREAD

**Issue by Ryangoslingx** [SunstriderEmu/BugTracker#4415]
When bidding on several items and eventually not winning them, the gold doesn't return in the mail. Something like 500g just missing in the twisted nether.

**Comment by Jerrythemagicdog** [comment]
What's the character name?

**Comment by Ryangoslingx** [comment]
Ryangosling. I've had a correspondence with gms in game but they couldnt find anything.Skickat från min Samsung Galaxy-smartphone.
-------- Originalmeddelande --------Från: Jerrythemagicdog <notifications@github.com> Datum: 2020-11-02  07:45  (GMT+01:00) Till: SunstriderEmu/BugTracker <BugTracker@noreply.github.com> Kopia: Ryangoslingx <patrik@milael.se>, Author <author@noreply.github.com> Ämne: Re: [SunstriderEmu/BugTracker] Not getting gold bid back (#4415) 
What's the character name?

**Comment by Jerrythemagicdog** [comment]
You should be able to find the bids in your mailbox.
