### ISSUE TITLE
Graveyard spawn in orgrimmar

### ISSUE THREAD

**Issue by yajoto** [SunstriderEmu/BugTracker#4416]
The graveyard spawn of alliance if they did in orgrimmar is not were it supposed to be. Would be great if you guys can fix it soon, so we don't need to bring tons of locks who would like to do something else instead of summoning when we raid OG

**Comment by Jerrythemagicdog** [comment]
https://wow.gamepedia.com/Durotar

_A Horde-only graveyard has been added in the northern section of Durotar, just to the south of Orgrimmar. In addition to serving northern Durotar, Horde characters dying in Orgrimmar, The Hall of Legends and Ragefire Chasm will use this new graveyard. Alliance characters dying in Durotar will continue to only use the Razor Hill graveyard._
