### ISSUE TITLE
Murkblood Escape Plans

### ISSUE THREAD

**Issue by utopiahwt** [SunstriderEmu/BugTracker#4417]
this item dropped for me, https://tbc-twinhead.twinstar.cz/?item=32726

I am friendly with netherwing but I cant seem to start the quest, it says that I don't meet the requirements

**Comment by Jerrythemagicdog** [comment]
What's your in-game name?

**Comment by utopiahwt** [comment]
Coulson

**Comment by Jerrythemagicdog** [comment]
Seems like you have to complete "The Netherwing Mines" (11075) first.
