### ISSUE TITLE
[#108] Quest: Shizz work - Not working

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#442]
<a href="https://github.com/qoth"><img src="https://avatars2.githubusercontent.com/u/35262513?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [qoth](https://github.com/qoth)**
_Wednesday Dec 26, 2018 at 06:42 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/108_

----

Quest 'Shizz Work' https://tbc-twinhead.twinstar.cz/?quest=10629

You summon a felhound through item 30803 (Felhound Whistle). The felhound follows you properly and is supposed to cause object (https://tbc-twinhead.twinstar.cz/?object=184980) 'Felhound Poo' to spawn.

Currently the object is not spawning and the felhound runs away as soon as an enemy dies.

**Comment by kelno** [comment]
<a href="https://github.com/Nqsty"><img src="https://avatars3.githubusercontent.com/u/11685475?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Nqsty](https://github.com/Nqsty)**
_Monday Dec 31, 2018 at 02:44 GMT_

----

@kelno It seems like a regression in the ACTION_MOVE_TO_POS or with TARGET_ACTION_INVOKER with the flag CAN_TARGET_DEAD.
There are other bugs, we need to talk about too.

**Comment by kelno** [comment]
Updated, test again!

**Comment by kelno** [comment]
@SUN-Leekie It was a CORE REGRESSION indeed

**Comment by woiwoz** [comment]
fixd done! Good job now!
