### ISSUE TITLE
[#124] Transports system

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#445]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Monday Dec 31, 2018 at 03:29 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/124_

----

Current behaviour: 
Zeppelin stops midair for 20 seconds, shortly after departing a tower.
Then continues on.
Once teleported, arrives near instantly to next tower.

Expected behaviour: 
Zeppelin should not stop, fly until it teleports to destination.
Should continue flight path to next tower too, not teleport to it.

Steps to reproduce the problem:
Board any zeppelin, watch as it pauses and then ports directly.

**Comment by kelno** [comment]
<a href="https://github.com/Kittnz"><img src="https://avatars2.githubusercontent.com/u/5845231?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kittnz](https://github.com/Kittnz)**
_Monday Dec 31, 2018 at 09:09 GMT_

----

Same with some boats..

**Comment by emorelix** [comment]
![wowscrnshot_021619_140533](https://user-images.githubusercontent.com/47015256/52893834-da8d8600-31f4-11e9-9aaa-d707717b264d.jpg)
![wowscrnshot_021619_140732](https://user-images.githubusercontent.com/47015256/52893837-da8d8600-31f4-11e9-8d0f-eb4f6a82ea75.jpg)
![wowscrnshot_021619_140734](https://user-images.githubusercontent.com/47015256/52893840-da8d8600-31f4-11e9-9041-d7dc570ce7c3.jpg)
![wowscrnshot_021619_140737](https://user-images.githubusercontent.com/47015256/52893841-db261c80-31f4-11e9-9574-48881105896a.jpg)
![wowscrnshot_021619_140738](https://user-images.githubusercontent.com/47015256/52893842-db261c80-31f4-11e9-8ee1-f592408ac24a.jpg)
![wowscrnshot_021619_140759](https://user-images.githubusercontent.com/47015256/52893843-db261c80-31f4-11e9-8a33-175694517124.jpg)

**Comment by kelno** [comment]
Doesn't seem to happen often, more details here are welcome

**Comment by kelno** [comment]
Seems to happen after a while when the server is running

**Comment by kelno** [comment]
Still sketchy

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1766

**Comment by Varanak** [comment]
I had tried the boat from Azuremyst Isle to Auberdine again today and it seems to be dependent on where you are standing on the boat. If you wait for the boat to come to a full stop at the dock and are only on the boat as much as you have to be, when you load into the other zone it functionally works.

**Comment by hufsa** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1806

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1859

**Comment by kelno** [comment]
Maybe fixed https://github.com/kelno/sunstrider/commit/5bab421d2a054e433707aece3d4885553d308c00

**Comment by artieau** [comment]
Undercity < - > Grom'gol zeppelin still bugged @kelno

**Comment by Lunasoll** [comment]
Boat from Menethil Harbor to Theramore Isle drops you in the ocean and continues its voyage.

**Comment by kelno** [comment]
Fixed with next update

**Comment by artieau** [comment]
Issue still exists for Grom'Gol < > UC @kelno

**Comment by kelno** [comment]
Indeed, seems fixed in SOME cases but clearly not all

**Comment by kelno** [comment]
Updated with next server update
