### ISSUE TITLE
[#139] [Hunter] Kill Command

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#448]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Tuesday Jan 08, 2019 at 10:10 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/139_

----

Using Kill Command on a target, when your Pet is not in melee range of the target, causes Kill Command to do no damage + still cause spell to go on cooldown + still use the spells mana cost.

Kill Command is used after the Hunter lands a critical strike.
The spell cast by the Hunter has a 45yard range to their current target.
Using the spell with the Pet out of melee range of that same target, should cause Kill Command to not trigger. It should not cause damage outside melee range + not use the cooldown + not consume any mana of the Hunter.

Sources to be added - combat log shows nothing when this happens.

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Tuesday Jan 08, 2019 at 12:21 GMT_

----

No sources needed for that. 
Spell Ids and current server revision should be added though.

**Comment by woiwoz** [comment]
Hunters cast spells, pets instantly attack. The killing instructions used to have a variety of problems - Pets still consume mana when they can't attack and are influenced by public CDs, but killing instructions themselves are a powerful skill for pets.
It's not BUG. It's the same behavior in Blizzard.

**Comment by Jerrythemagicdog** [comment]
What @woiwoz said is the blizzlike behavior and has to be taken into consideration while playing Hunter. There are also situations where you want to use Kill Command even though your pet is not in melee range. One of those is the Dungeon 3 set (Beast Lord) bonus (http://tbc.cavernoftime.com/spell=37483) which, under your described behavior could only be used while pet is in melee range.

**Comment by artieau** [comment]
Further research shows pet range was a requirement from MoP onwards.
However, mana cost and chosen target appears to still be incorrect on core compared to TBC Patch 2.2
https://wow.gamepedia.com/Patch_2.2.0
 [Kill Command] will not charge the hunter mana if their pet is on passive.
 [Kill Command] no longer affects the Hunter’s current target.

**Comment by Jerrythemagicdog** [comment]
Fixed in https://github.com/kelno/sunstrider/commit/27809258b2c6d4a70dbc54a7593a38c26c8a0b4a
