### ISSUE TITLE
[#145] [NPC] - Wisp in Evergrove is Attackable (Blade's Edge Mountain)

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#451]
<a href="https://github.com/Cheelout"><img src="https://avatars2.githubusercontent.com/u/38281939?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Cheelout](https://github.com/Cheelout)**
_Saturday Jan 12, 2019 at 01:50 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/145_

----

What happens: Wisps in Evergrove are Attack-able to Horde
What should happen: As this is a NEutral Outpost they should be Neutral to both factions

Source for Evergrove: http://wowwiki.wikia.com/wiki/Evergrove

![image](https://user-images.githubusercontent.com/38281939/51067662-66494b00-1668-11e9-9eff-a6d240d79398.png)

To Replicate: Go to Ever grove as Horde in Blade's Edge Mountain

**Comment by kelno** [comment]
<a href="https://github.com/Kittnz"><img src="https://avatars2.githubusercontent.com/u/5845231?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kittnz](https://github.com/Kittnz)**
_Monday Jan 14, 2019 at 10:49 GMT_

----

wrong faction id it seems

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Jan 14, 2019 at 15:45 GMT_

----

That or add flags immune to pc/npc + unselectable, should do the trick as well

**Comment by Jerrythemagicdog** [comment]
Fixed
