### ISSUE TITLE
[#146] [NPC] - Thrallmar War Riders patrol incorrectly (Stacked on each other)

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#452]
<a href="https://github.com/Cheelout"><img src="https://avatars2.githubusercontent.com/u/38281939?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Cheelout](https://github.com/Cheelout)**
_Saturday Jan 12, 2019 at 02:11 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/146_

----

What happens: Thrallmar War Riders are currently patrolling on top of one another
What is meant to happen: They are meant to be spread out from each other

![image](https://user-images.githubusercontent.com/38281939/51067969-74e53180-166b-11e9-8315-ddf356a91886.png)

NPC ID=16599

Reproduce: Go to Thrallmar and watch them run like spastics.

**Comment by kelno** [comment]
<a href="https://github.com/Kittnz"><img src="https://avatars2.githubusercontent.com/u/5845231?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kittnz](https://github.com/Kittnz)**
_Monday Jan 14, 2019 at 10:49 GMT_

----

Wrong formation in db?

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Jan 14, 2019 at 14:59 GMT_

----

Maybe, but creature formation system is a bit broken as well

**Comment by kelno** [comment]
<a href="https://github.com/Kittnz"><img src="https://avatars2.githubusercontent.com/u/5845231?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kittnz](https://github.com/Kittnz)**
_Monday Jan 14, 2019 at 14:59 GMT_

----

how broken exactly? 🗡

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Jan 14, 2019 at 15:43 GMT_

----

Members do follow the leader too far behind their supposed offset positions

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago, thanks.
