### ISSUE TITLE
[#147] [Loot] - Players able to pickup same quest items if looted at the same time

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#453]
<a href="https://github.com/Cheelout"><img src="https://avatars2.githubusercontent.com/u/38281939?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Cheelout](https://github.com/Cheelout)**
_Saturday Jan 12, 2019 at 02:18 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/147_

----

What happens: If players loot a mob at the same time in a group they both get the items from the mob
What should happen: Only 1 player gets the loot

Steps to reproduce: Loot a mob at the same time while in a group with a player

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Saturday Jan 12, 2019 at 09:27 GMT_

----

Can you give me a specific id for the creature looted + the item looted?

**Comment by kelno** [comment]
<a href="https://github.com/Cheelout"><img src="https://avatars2.githubusercontent.com/u/38281939?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Cheelout](https://github.com/Cheelout)**
_Saturday Jan 12, 2019 at 09:34 GMT_

----

Quest discovered on: https://tbc-twinhead.twinstar.cz/?quest=10450
Quest Item: https://tbc-twinhead.twinstar.cz/?item=30327
From Mob: https://tbc-twinhead.twinstar.cz/?npc=16925

**Comment by kelno** [comment]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [artieau](https://github.com/artieau)**
_Saturday Feb 02, 2019 at 12:45 GMT_

----

all quest items on all mobs @kelno

**Comment by Jerrythemagicdog** [comment]
Managed to reproduce, it also happens with all gameobjects - if both players click at the same time the loot window opens for both of them.

**Comment by kelno** [comment]
Is this still a thing?
