### ISSUE TITLE
[#149] [NPC] - Crust Buster - Goes underground when out of range

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#454]
<a href="https://github.com/Cheelout"><img src="https://avatars2.githubusercontent.com/u/38281939?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Cheelout](https://github.com/Cheelout)**
_Saturday Jan 12, 2019 at 02:42 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/149_

----

What happens: Mob will go underground when you run out of range and still cast but not move
What should happen: Go underground run towards you and pop up

![image](https://user-images.githubusercontent.com/38281939/51068251-a829bf80-166f-11e9-9db7-481d176dfa46.png)

NPC ID: 16844

Steps to reproduce: Aggro one, run out of range.

**Comment by Jerrythemagicdog** [comment]
The creature now stands there and continues casting on the player if the player attempts to run away or goes under the ground when it resets.
