### ISSUE TITLE
[#150] [Hellfire] NPC glide hax and no agro

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#455]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Saturday Jan 12, 2019 at 02:42 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/150_

----

![image](https://user-images.githubusercontent.com/40563134/51068264-d7d8c780-166f-11e9-84b7-caab2b012181.png)

This NPC does not stop its patrol path when attacked.
It also glides through the air, instead of running.

The NPC should dismount and attack its agro target and should not be gliding

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
