### ISSUE TITLE
[#160] NPC (69504) Dreadcaller (59)

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#460]
<a href="https://github.com/johnboy1989"><img src="https://avatars3.githubusercontent.com/u/39358344?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [johnboy1989](https://github.com/johnboy1989)**
_Sunday Jan 13, 2019 at 22:31 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/160_

----

Mob Dreadcaller is casting Shadowbolt every 1-2 seconds (seems way to strong for this level)

Casts both in melee and ranged positions

https://www.wowdb.com/npcs/19434-dreadcaller#related:casts

![image](https://user-images.githubusercontent.com/39358344/51091464-fe694080-17de-11e9-8452-abbcfb2e9d9b.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
