### ISSUE TITLE
[#164] [NPC] Irradiated Worker

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#463]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Tuesday Jan 15, 2019 at 06:08 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/164_

----

In Area52, these NPC are scripted in the middle of town.

These NPC should be scripted inside the pit inside the town.

GUID 74523

![image](https://user-images.githubusercontent.com/40563134/51161855-28f2f080-18e8-11e9-8250-3b58f6f3a628.png)

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Tuesday Jan 15, 2019 at 10:53 GMT_

----

Thanks.
On a general rule: 
- Give guid for an unique specific creature
Or
- Give entry for a creature type (like here)

It is included in your screenshot so no worries.

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Tuesday Jan 15, 2019 at 11:16 GMT_

----

Note to dev: They have some pos on TC, can't take from there.

**Comment by Jerrythemagicdog** [comment]
fixed some time ago
