### ISSUE TITLE
[#165] [NPC] Innkeeper Remi Dodoso

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#464]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Tuesday Jan 15, 2019 at 06:12 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/165_

----

The Innkeeper for Area52 has no dialogue options.

The Innkeeper should have options for purchasing items as well as setting hearthstone location.

GUID 70010
![image](https://user-images.githubusercontent.com/40563134/51162000-b6cedb80-18e8-11e9-99ed-24373b21eaac.png)

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Tuesday Jan 15, 2019 at 11:45 GMT_

----

This is partly fixed with https://github.com/kelno/sunstrider-scripts/commit/9bdcc2d14b1039052713ca3ce4963e949c1873c2

Now db side, some innkeepers like her don't sell anything, see:
`SELECT * FROM creature_template WHERE npcflag & 0x00010000 AND (NOT npcflag & 0x00000080)`
They need to have their UNIT_NPC_FLAG_VENDOR added as well as their vendor items.

**Comment by kelno** [comment]
She still needs to have items added to her inventory

**Comment by Jerrythemagicdog** [comment]
This innkeeper is not supposed to sell any items. 
There are food and drink vendors outside of the inn for that purpose.
