### ISSUE TITLE
[#166] [Quest] Manaforge B'naar

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#465]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Tuesday Jan 15, 2019 at 06:30 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/166_

----

After completing quest # 11039, the NPC # 19468 does not offer any further quests.

However, he should then offer the next quest # 10189 in the chain.

Will manually add to myself for now to keep testing.
http://db.hellfire-tbc.com/?quest=10189

**Comment by kelno** [comment]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [artieau](https://github.com/artieau)**
_Tuesday Jan 15, 2019 at 06:30 GMT_

----

Nevermind, dont have that command...

**Comment by kelno** [comment]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [artieau](https://github.com/artieau)**
_Tuesday Jan 15, 2019 at 06:32 GMT_

----

Double nevermind...I do have that command...it was hidden...
Chain still broken!!

**Comment by SUN-Leekie** [comment]
Fixed in bb929603718d2565fcd7d952b5d88598d1313da9
