### ISSUE TITLE
[#176] Quest: Taming the Beast (blood elf) 

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#472]
<a href="https://github.com/mrqiksta"><img src="https://avatars2.githubusercontent.com/u/46828437?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mrqiksta](https://github.com/mrqiksta)**
_Saturday Jan 26, 2019 at 14:28 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/176_

----

https://wotlk.evowow.com/?quest=9484

Belf Hunter racial quest to tame a dragonhawk works ok, but am unable to dismiss the dragonhawk afterward to proceed with the next quest (to tame another pet). Usual option to abandon is not present when right-clicking the unit frame, no abilities in spellbook to dismiss/abandon.

Expected behaviour: Unsure if the 'pet' should be dismissable, or should auto-dismiss/despawn at completion of quest.

Workaround: Relogging causes the dragonhawk to path back to it's spawn point, allowing the player to move to next quest without waiting 15 mins for the charm to wear off.

**Comment by Jerrythemagicdog** [comment]
Thanks!
Tested now, can dismiss the pet which causes it to return to its original point.
