### ISSUE TITLE
[#181] Quest "Unexpected Results" spawns mobs who do not approach

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#474]
<a href="https://github.com/mrqiksta"><img src="https://avatars2.githubusercontent.com/u/46828437?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mrqiksta](https://github.com/mrqiksta)**
_Saturday Jan 26, 2019 at 15:28 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/181_

----

Quest to protect NPC from adds that spawn and attack

Adds spawn ok but stand together some distance away. Adds do not engage NPC upon spawn.

https://wotlk.evowow.com/?quest=8488

**Comment by kelno** [comment]
<a href="https://github.com/Tamosheik"><img src="https://avatars2.githubusercontent.com/u/40758487?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tamosheik](https://github.com/Tamosheik)**
_Sunday Jan 27, 2019 at 05:12 GMT_

----

ISSUE #186 exhibits the same behaviour

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed!
