### ISSUE TITLE
[#182] Remorseless attacks talent not working

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#475]
<a href="https://github.com/BrockSamson1"><img src="https://avatars3.githubusercontent.com/u/46757539?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BrockSamson1](https://github.com/BrockSamson1)**
_Saturday Jan 26, 2019 at 15:38 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/182_

----

Patch:
PTR

Current behaviour:
Remorseless attack buff does not activate on enemy kill

Expected behaviour:
Should buff self when enemy that yeilds exp/honour dies

Steps to reproduce the problem:

2/2 remorseless attacks talent
Kill enemy
See no buff
![remorseless attacks not proccing](https://user-images.githubusercontent.com/46757539/51789379-6571f680-21dc-11e9-9211-504bbcf19546.jpg)

**Comment by kelno** [comment]
<a href="https://github.com/BrockSamson1"><img src="https://avatars3.githubusercontent.com/u/46757539?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [BrockSamson1](https://github.com/BrockSamson1)**
_Saturday Jan 26, 2019 at 17:00 GMT_

----

Correction, works sometimes. But rarely.

**Comment by kelno** [comment]
<a href="https://github.com/Tamosheik"><img src="https://avatars2.githubusercontent.com/u/40758487?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tamosheik](https://github.com/Tamosheik)**
_Saturday Jan 26, 2019 at 20:40 GMT_

----

Remorseless Attacks (Rank 1) - Spell ID# 14144
Remorseless Attacks (Rank 2) - Spell ID# 14148

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Jan 28, 2019 at 13:38 GMT_

----

For this kind of bugs "sometimes working", it's all about context so make sure to include a lot of details such as the creature you're attacking (included in the screen here) and how you're killing it.

**Comment by kelno** [comment]
Can't reproduce, could have been fixed since then. Closing for now.

**Comment by Jerrythemagicdog** [comment]
Updated in https://github.com/kelno/sunstrider/commit/eac20427982cac97b368f9b529b7dd05a908afe2

Maybe was the same problem initially where the proc was consumed instantly by the spell that procced it.
