### ISSUE TITLE
[#187] Quest "Whitebark's Memory" non-completable

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#478]
<a href="https://github.com/mrqiksta"><img src="https://avatars2.githubusercontent.com/u/46828437?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mrqiksta](https://github.com/mrqiksta)**
_Sunday Jan 27, 2019 at 06:25 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/187_

----

Quest id:
http://db.hellfire-tbc.com/?quest=10166

After killing required mob and getting "completed" status, the NPC to hand in to does not spawn: http://db.hellfire-tbc.com/?npc=19456

Quest is not completeable.

**Comment by Jerrythemagicdog** [comment]
Thanks!
Tested, works fine now, made a small improvement.
