### ISSUE TITLE
[#188] Quest mobs in "Powering Our Defenses" do not engage when spawned

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#479]
<a href="https://github.com/mrqiksta"><img src="https://avatars2.githubusercontent.com/u/46828437?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mrqiksta](https://github.com/mrqiksta)**
_Sunday Jan 27, 2019 at 07:28 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/188_

----

Quest ID: http://db.hellfire-tbc.com/?quest=8490
Expected behaviour: quest begins and waves of the following mob spawn and attack the object the player is protecting:
http://db.hellfire-tbc.com/?npc=17086

observed behaviour:
Mobs spawn in waves as expected, but take no action.
'
Quest is completeable by killing these mobs.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in "4f1b6f187b0dc2f69a2fc04e4aa57cc249779896" (scripts)
