### ISSUE TITLE
[#193] [QUEST] "Fel Spirits" not completeable

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#483]
<a href="https://github.com/BrockSamson1"><img src="https://avatars3.githubusercontent.com/u/46757539?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BrockSamson1](https://github.com/BrockSamson1)**
_Sunday Jan 27, 2019 at 09:00 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/193_

----

Patch:
2.4.3

Current behaviour:
Spirits mob required to complete quest does not spawn
Expected behaviour:
When Shattered hand berserkers ID: 16878 die near anchorite relic object ID: 185298 after using quest item anchorite relic ID: 31772 a fel spirit should spawn to kill for quest credit.

Steps to reproduce the problem:
Take quest "Fel spirits" from Klatu in honor hold
Travel to Gor'gaz Outpost
Place anchorite relic
Kill shattered hand berserker
Observe no further mob spawn
![fel spirits quest broken](https://user-images.githubusercontent.com/46757539/51798913-2be9cb80-226e-11e9-9d37-8e8d8f9d578d.jpg)

**Comment by Jerrythemagicdog** [comment]
fixed!
