### ISSUE TITLE
[#195] [NPC] Goliathon (Pathing through the air!)

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#484]
<a href="https://github.com/zemfi"><img src="https://avatars1.githubusercontent.com/u/46832429?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zemfi](https://github.com/zemfi)**
_Sunday Jan 27, 2019 at 10:13 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/195_

----

Noticed Bigdick NPC boss Goliathon (#19305) pathing is out, noticed he was jumping up and down the crystal, then started floating in the air and despawned, only just caught the tail end of it in a video.

According to: https://www.wowhead.com/npc=19305/goliathon#comments, he is suppose to be summonable only by a quest?

![tbc_goliath22](https://user-images.githubusercontent.com/46832429/51799670-1a0d2600-2278-11e9-8a49-621c86c81998.jpg)
![world of warcraft 2019 01 27 - 20 50 18 06 mp4_snapshot_00 00_ 2019 01 27_20 57 26](https://user-images.githubusercontent.com/46832429/51799672-1bd6e980-2278-11e9-8ade-0a128127d558.jpg)

**Comment by zemfi** [comment]
this is still a thing as of .rev 10914 

![goliathon](https://user-images.githubusercontent.com/46832429/55954817-0d0ea900-5ca3-11e9-84b2-5b42574d3468.jpg)

**Comment by Jerrythemagicdog** [comment]
Tested now, works correctly. The creature was incorrectly spawned in the world.
Thanks!
