### ISSUE TITLE
[#197] [Quest] Mission: The Abyssal Shelf (10162)

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#486]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BarrensJerk](https://github.com/BarrensJerk)**
_Sunday Jan 27, 2019 at 11:41 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/197_

----

Current Behaviour:
After completing the bombing run and killing all quest conditions in quest log, the quest in log is marked as complete but the NPC (19273) Still has a grey ? and quest cannot be handed in

**Comment by kelno** [comment]
<a href="https://github.com/SUN-Leekie"><img src="https://avatars0.githubusercontent.com/u/18554785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SUN-Leekie](https://github.com/SUN-Leekie)**
_Sunday Jan 27, 2019 at 18:55 GMT_

----

Did you do it from Horde or Alliance?

**Comment by kelno** [comment]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [BarrensJerk](https://github.com/BarrensJerk)**
_Sunday Jan 27, 2019 at 20:26 GMT_

----

Horde

**Comment by wreckxos** [comment]
I'm also having issues with this quest.. But i'm on Alliance.. It won't let me pick the reward i want.
As you can see from the reward screenshots there are 3 items, although when checking the rewards once in the quest log you can only select one.

![WoWScrnShot_041619_230001](https://user-images.githubusercontent.com/49684915/56213664-a3740d80-609b-11e9-9413-8a3a44a8a77a.jpg)
![WoWScrnShot_041619_230018](https://user-images.githubusercontent.com/49684915/56213668-a4a53a80-609b-11e9-8081-1461c63c26d0.jpg)

**Comment by Jerrythemagicdog** [comment]
Tested now, works correctly. Thanks!
