### ISSUE TITLE
[#198] [Quest] The Agony and the Darkness (10389)

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#487]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BarrensJerk](https://github.com/BarrensJerk)**
_Sunday Jan 27, 2019 at 12:08 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/198_

----

After completing quest Vile Plans (10393) by handing in item Burning Legion Missive (29590) to NPC Magister Bloodhawk (21175) the NPC offers the quest The Agony and the Darkness. On accepting, a message appeared in chat log "You don't meet the requirements for that quest", the quest made the quest failed sound, and cannot be found in quest log to abandon, nor be picked up again. Like it never existed.

**Comment by kelno** [comment]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [BarrensJerk](https://github.com/BarrensJerk)**
_Sunday Jan 27, 2019 at 12:18 GMT_

----

Was able to pick the quest back up after completing quest chain that culminates in quest Doorway to the Abyss (10392). Shoudn't be prerequisite for The Agony and the Darkness (10389).

**Comment by Jerrythemagicdog** [comment]
Thanks for the details, fixed!
