### ISSUE TITLE
[#199] [NPC] Grelag (16858) missing a quest

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#488]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BarrensJerk](https://github.com/BarrensJerk)**
_Sunday Jan 27, 2019 at 12:55 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/199_

----

NPC Grelag (16858) should give a quest called Preparing the Salve (9345). At present he just has the post quest completed dialogue when you interact with him. 

There was a prequest for this quest called A Hasty Departure (9344) but was removed in tbc beta. On live he simply had the quest available.

**Comment by Jerrythemagicdog** [comment]
Thanks a lot, fixed.
