### ISSUE TITLE
[#204] [NPC] 2 Terrorfiends with unusual behaviour

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#490]
<a href="https://github.com/BrockSamson1"><img src="https://avatars3.githubusercontent.com/u/46757539?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BrockSamson1](https://github.com/BrockSamson1)**
_Monday Jan 28, 2019 at 00:41 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/204_

----

Patch:
2.4.3

Current behaviour:
2 Terrorfiends ID: 16951 are standing still and are in very close proximity in pools of aggonar

Expected behaviour:
Terrorfiends should have behaviour similar to the other terrorfiends in the area, ie. they should be doing small movements and animations and are usually not in such close proximity to one another

Steps to reproduce the problem:
Look at terrorfiends near right hand of aggonar's skeleton in pools of aggonar.
![terrorfiends with unusual behaviour](https://user-images.githubusercontent.com/46757539/51809140-a7d92780-22f1-11e9-8783-5f0afc696fa3.jpg)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
