### ISSUE TITLE
[#205] NPC Nestlewood Owlkin

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#491]
<a href="https://github.com/silumor"><img src="https://avatars2.githubusercontent.com/u/46830678?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [silumor](https://github.com/silumor)**
_Monday Jan 28, 2019 at 02:03 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/205_

----

npc=16518

These mobs are non aggressive, patrolling around Nestlewood Thicket

When you attack them they ignore you and just keep patting, they do not attack back, but still take damage.

Cannot drop combat till the mob has been killed

Fairly sure they should attack back once initiated into combat

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed!
