### ISSUE TITLE
[#211] Onorok Torn-Heart attacked by Domesticated Felboars

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#495]
<a href="https://github.com/Desparto"><img src="https://avatars0.githubusercontent.com/u/26176852?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Desparto](https://github.com/Desparto)**
_Monday Jan 28, 2019 at 04:15 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/211_

----

revision 10296 

Onorok Torn-Heart (npc=21183) currently gets attacked and killed by the surrounding Domesticated Felboars (npc=21195). They should not aggro onto him.

![image](https://user-images.githubusercontent.com/26176852/51814331-f6e18580-230e-11e9-826e-4f50546bf44f.png)

**Comment by Jerrythemagicdog** [comment]
fixed some time ago, was a faction issue.
