### ISSUE TITLE
[#214] Escape from Coilskar Cistern quest does not activate

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#497]
<a href="https://github.com/Desparto"><img src="https://avatars0.githubusercontent.com/u/26176852?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Desparto](https://github.com/Desparto)**
_Monday Jan 28, 2019 at 05:04 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/214_

----

Revision 10296

Killing Keeper of the Cistern (npc=20795) should activate the event where Earthmender Wilda (npc=21027) is released from her watery prison and can offer the Escape from Coilskar Cistern quest (quest=10451).

Currently killing the Keeper does nothing and the quest cannot be started. 

Expected behaviour can be seen here: https://youtu.be/i_CpElkm5q4?t=120

**Comment by zemfi** [comment]
Confirmed still broken as of .rev 11118

Additional: Earthmender Wilda Trigger (#21041)

**Comment by Sheikthecatman** [comment]
Was fixed in [3db110247d2a3c5551eaf96abe215168ee747bc2](https://github.com/kelno/sunstrider/commit/3db110247d2a3c5551eaf96abe215168ee747bc2).
