### ISSUE TITLE
[#217] [NPC] Fulgorge - npc goes invisible/glitchy when in combat

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#500]
<a href="https://github.com/zemfi"><img src="https://avatars1.githubusercontent.com/u/46832429?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zemfi](https://github.com/zemfi)**
_Monday Jan 28, 2019 at 07:11 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/217_

----

Rare NPC Fulgorge (#18678) goes invisible/glitchy when engaged in combat. still able to target/fight and kill it, but unable to see the actual npc. It did very briefly become visible a few times.

Intended: You should be able so see the npc you are fighting/engaged combat with.

Can provide video on request. Screenshots from the video:
![world of warcraft 2019 01 28 - 18 01 10 07 mp4_snapshot_00 16_ 2019 01 28_18 07 03](https://user-images.githubusercontent.com/46832429/51819772-ae829180-2327-11e9-812d-e6d32f17b049.jpg)
![world of warcraft 2019 01 28 - 18 01 10 07 mp4_snapshot_00 26_ 2019 01 28_18 07 34](https://user-images.githubusercontent.com/46832429/51819873-1b962700-2328-11e9-9d3a-f99a814f1b1e.jpg)

1st one is what its like fighting it, second one happened randomly for about a quarter of a second.

**Comment by kelno** [comment]
<a href="https://github.com/zemfi"><img src="https://avatars1.githubusercontent.com/u/46832429?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zemfi](https://github.com/zemfi)**
_Wednesday Feb 06, 2019 at 07:08 GMT_

----

bump, seems to be with other worms too.

Marauding Crust Burster (#16857)

![tbc_worm](https://user-images.githubusercontent.com/46832429/52325715-2e9cab80-2a3a-11e9-92c2-1b57386304fd.jpg)

.rev 10357

**Comment by BarrensJerk** [comment]
All other worms seem fixed but fulgorge still broken
rev. 10570

**Comment by kelno** [comment]
To db dev: copy other worms script there, they have been reworked

**Comment by Jerrythemagicdog** [comment]
Fixed
