### ISSUE TITLE
[#220] [Item] Looting Jaggal Clams that are stacked consumes the whole stack but yields only loot from one.

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#502]
<a href="https://github.com/Guvernor"><img src="https://avatars1.githubusercontent.com/u/28607117?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Guvernor](https://github.com/Guvernor)**
_Tuesday Jan 29, 2019 at 00:11 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/220_

----

**Current behaviour:**

Looting a Jaggal Clam (24476) that is in a stack of multiple clams will remove the whole stack and return only the loot from a single clam. I haven't tested with other clams or stackable inventory containers.

**Expected behaviour:**

Each right click should yield the loot of one clam and reduce the stack count by one.

**Steps to reproduce the problem:**

1. Obtain multiple jaggal clams.
2. Right click on the stack.

**rev. hash/commit:** 

10296 (c3ddeaeda23a+)

**Comment by Cheelout** [comment]
@kelno

**Comment by hufsa** [comment]
Should they even stack at all?

**Comment by hufsa** [comment]
No.
Stacking of 20 introduced in 3.0.1:
https://www.wowhead.com/item=24476/jaggal-clam Look at comments

**Comment by Cheelout** [comment]
shouldn't stack. individual item until 3.0 yeah

**Comment by Jerrythemagicdog** [comment]
Thanks, tested now, they don't stack and have correct loot.
