### ISSUE TITLE
[#226] Dreghood drudge spell "shared bonds" not working

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#505]
<a href="https://github.com/BrockSamson1"><img src="https://avatars3.githubusercontent.com/u/46757539?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BrockSamson1](https://github.com/BrockSamson1)**
_Tuesday Jan 29, 2019 at 05:40 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/226_

----

Dreghood drudge ID: 18122 spell shared bonds ID: 34789 appears to be malfunctioning and not splitting damage with an ally.
**Current behaviour:**

No effect from spell visible. Nearby allies do not share damage.

**Expected behaviour:**

Damage taken by one drudge should be split 50% with nearby allied drudge as per tooltip

**Steps to reproduce the problem:**

1. Engage Dreghood drudge pair
2. Wait for spell application
3. Begin damage on a single drudge - Auto attacks and sinister strikes used
4. Observe no reciprocal damage taken by bonded ally

**rev. hash/commit:** 
In screenshot
![sacred bonds npc malfunction](https://user-images.githubusercontent.com/46757539/51886340-92442a80-23e3-11e9-8995-4a3629c0a9b6.jpg

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Friday Feb 01, 2019 at 04:11 GMT_

----

Scripted effect, needs to be scripted core side

**Comment by Jerrythemagicdog** [comment]
Fixed in some commit, tested now and works correctly.
