### ISSUE TITLE
[#227] [Quest] The Exorcism of Colonel Jules - Glitchy Animations; Missing NPC

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#506]
<a href="https://github.com/zemfi"><img src="https://avatars1.githubusercontent.com/u/46832429?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zemfi](https://github.com/zemfi)**
_Tuesday Jan 29, 2019 at 06:13 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/227_

----

rev 10296

 **Issue:** The quest The Exorcism of Colonel Jules (#10935) has glitchy animations. spawned npc's jumping and down, wrong animation for a floating npc, and a pathing issue with another, see below:

- As Darkness Released (#22507) spawns, it constantly jumps up and down while it paths around.
- When Colonel Jules (#22432) starts floating around the room, he is flat, should be curved (check youtube link below)
- Towards the end Anchorite Barada (#22431) goes back to his original position, but doesnt walk path properly and stays in the same stance.
- Foul Purge (#22506) should also spawn during the encounter, only does for a brief split second then disappears.

**What should Happen:** Should be no graphical weirdness, and that npc should spawn/be killable; check video at the bottom.

Recording of this available on request; heres some frames from the video:

![world of warcraft 2019 01 29 - 16 33 57 13 mp4_snapshot_02 19_ 2019 01 29_16 59 07 _](https://user-images.githubusercontent.com/46832429/51887663-b1918680-23e8-11e9-85e9-eed1c5ec213e.jpg)
Darkness Released (#22507) Jumping up and down.
![world of warcraft 2019 01 29 - 16 33 57 13 mp4_snapshot_02 37_ 2019 01 29_16 59 39 _](https://user-images.githubusercontent.com/46832429/51887668-b5250d80-23e8-11e9-9a6a-8cab3e97a860.jpg)
Colonel Jules (#22432) floating around flat when he should be curved/impaled
![world of warcraft 2019 01 29 - 16 33 57 13 mp4_snapshot_03 16_ 2019 01 29_17 00 48 _](https://user-images.githubusercontent.com/46832429/51887669-b6eed100-23e8-11e9-8e24-45b22ad780d2.jpg)
Anchorite Barada (#22431) his same stance pathing
![world of warcraft 2019 01 29 - 16 33 57 13 mp4_snapshot_07 27_ 2019 01 29_17 07 06 _](https://user-images.githubusercontent.com/46832429/51887677-b9512b00-23e8-11e9-87a9-8f375cacc092.jpg)
Foul Purge (#22506) Split second spawn then disappear.

https://www.youtube.com/watch?v=rl3eXf6WsKw
What the encounter is intended to look like.

**Comment by kelno** [comment]
<a href="https://github.com/SUN-Leekie"><img src="https://avatars0.githubusercontent.com/u/18554785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SUN-Leekie](https://github.com/SUN-Leekie)**
_Saturday Feb 02, 2019 at 05:29 GMT_

----

Fixed Darkness Released weird movements & speed in 10356.

Note:
* Darkness Released has the `SMART_ACTION_SET_DISABLE_GRAVITY` to true but that didn't work, had to update the entry in `creature_template_movement` for it to work. 🤔 
* Foul Purge are faction 14 and they can't seem to attack the Anchorite which is neutral but you can attack him with a right click.

Quick links:
* Darkness Released: http://dev.sunstrider.com.test/creature/entry/22507/smartai
* Anchorite Barada: http://dev.sunstrider.com.test/creature/entry/22431/smartai
* Colonel Jules: http://dev.sunstrider.com.test/creature/entry/22432/smartai
* Foul Purge: http://dev.sunstrider.com.test/creature/entry/22506/smartai

**Comment by Jerrythemagicdog** [comment]
Fix live after next restart.
