### ISSUE TITLE
[#234] Vol'jin missing 

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#513]
<a href="https://github.com/balunn"><img src="https://avatars2.githubusercontent.com/u/46829506?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [balunn](https://github.com/balunn)**
_Tuesday Jan 29, 2019 at 10:36 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/234_

----

**Current behaviour:**
NPC Vol'Jin #10540 is missing, as a result I can't hand in 'The admiral's Orders' #831

**Expected behaviour:**
Vol'Jin should be in Orgrimmar (rough co ords 34.3, 36.3)

**Comment by Jerrythemagicdog** [comment]
Just checked, he's spawned correctly. Must've been killed?
