### ISSUE TITLE
[#237] [Quest] Cluck!

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#515]
<a href="https://github.com/balunn"><img src="https://avatars2.githubusercontent.com/u/46829506?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [balunn](https://github.com/balunn)**
_Thursday Jan 31, 2019 at 02:00 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/237_

----

**Current behaviour:**

Quest 'Cluck!' #3861 cannot be handed in, even though i have the required 'Special Chicken Feed' #11108

**Expected behaviour:**

The Quest is behaving like a blue ? quest (can't be picked up and goes strait to hand in). When you should be able to pick the quest up from the chicken.
Source - https://www.youtube.com/watch?v=NqQ94b7tdYI 

**Steps to reproduce the problem:**

1.  - Go to Westfall.
2. Buy Special Chicken Feed From Farmer Saldean #223
3. Target a Chicken and spam /chicken
4. Talk To Chicken once it becomes friendly.

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/46829506/52025300-f25bdd80-2557-11e9-8ee6-7f13c85de7e1.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed!
