### ISSUE TITLE
[#240] [Quest] Assist Exarch Orelis (11038) / Report to Spymaster Thalodien (11039)

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#517]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BarrensJerk](https://github.com/BarrensJerk)**
_Thursday Jan 31, 2019 at 21:14 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/240_

----

**Current behaviour:**

Aldor quest available at neutral aldor from NPC 23270 if you are Draenei; 
Scryer Quest available from NPC 23273 if you are any other race

**Expected behaviour:**

Quest should only be available to people who have selected a faction after completing City of Lights quest chain and selected a faction. Friendly with Aldor / Scryer at least 

Discussed in comments
https://www.wowhead.com/quest=11038/assist-exarch-orelis

**Steps to reproduce the problem:**

1. Go to Aldor / north bank as Draenei
2. Pick up quest from NPC 23270 without having completed City of Lights quest line or selected Aldor faction

1. Go to Scryer bank as Troll or Tauren (these 2 i tested)
2. Pick up quest 11039 from NPC 23273

Also available with one of the other breadcrumb quests for netherstorm in quest log, which shouldn't occur. Discussed here:
https://github.com/TrinityCore/TrinityCore/issues/22454

Was able to pick up quest even though I had quest 11040 Parts For the Rocket-Chief in my quest log

**rev. hash/commit:** 

Sunstrider rev. 10343 (8129e9d56781+)

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Friday Feb 01, 2019 at 04:10 GMT_

----

Nice thanks for the Trinity reference

**Comment by Jerrythemagicdog** [comment]
Thanks, the data is correct now, must be one the breadcrumb quest fixes commit.
