### ISSUE TITLE
[#243] Mr. Smite

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#520]
<a href="https://github.com/balunn"><img src="https://avatars2.githubusercontent.com/u/46829506?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [balunn](https://github.com/balunn)**
_Friday Feb 01, 2019 at 01:49 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/243_

----

**Current behaviour:**

Mr. Smite #646, after using his stomp ability, isn't going to his chest to swap weapons. Instead he keeps hitting you while you are stunned.

**Expected behaviour:**

After casting Smite Stomp #6432 at 66%, Should cast Duel Wield #674. Then at 33% when he casts stomp again, should cast Smites hammer #6436

source https://youtu.be/L4BUqPlhFU0?t=497

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/46829506/52097586-bd1ac280-261f-11e9-8be9-0a30ab561d0c.png)

**Comment by Jerrythemagicdog** [comment]
Fixed some time before launch.
