### ISSUE TITLE
[#245] [Quest] Shutting Down Manaforge B'naar (10299)

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#522]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BarrensJerk](https://github.com/BarrensJerk)**
_Friday Feb 01, 2019 at 03:05 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/245_

----

**Current behaviour:**

After looting item 29366 successfully, can interact with object B'naar control Console and select gossip menu option <Begin Emergency Shutedown> but no event starts, no Sunfury Technicians spawn, and after 120 seconds has elapsed no shutdown occurs, and no quest objective credit.

**Expected behaviour:**

Activating the console should start a 2 minute event where Sunfry Technicians spawn and run towards the console trying to cancel the shutdown. There was an emote at 30 seconds to go and an emote when completed.

**rev. hash/commit:** 

Sunstrider rev. 10343 (8129e9d56781+)

**Comment by kelno** [comment]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [BarrensJerk](https://github.com/BarrensJerk)**
_Friday Feb 01, 2019 at 04:44 GMT_

----

Script for event and all the other "shutting down manaforge....." quests?
https://github.com/TrinityCore/TrinityCore/issues/12724

**Comment by kelno** [comment]
<a href="https://github.com/SUN-Leekie"><img src="https://avatars0.githubusercontent.com/u/18554785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SUN-Leekie](https://github.com/SUN-Leekie)**
_Saturday Feb 02, 2019 at 03:23 GMT_

----

Script is still there but not triggering.
@kelno  check:
http://dev.sunstrider.com.test/gameobject/entry/183770/smartai
http://dev.sunstrider.com.test/creature/entry/20209/smartai

**Comment by SUN-Leekie** [comment]
Fixed in bb929603718d2565fcd7d952b5d88598d1313da9
