### ISSUE TITLE
[#246] [Quest] You, Robot (10248) - Server Crash

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#523]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BarrensJerk](https://github.com/BarrensJerk)**
_Friday Feb 01, 2019 at 12:11 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/246_

----

**Current behaviour:**

Used item 28634 Scrap Reaver Controller to control the robot and fight Negatron, server crashed. Was trying to use the stomp ability the pet has

**Expected behaviour:**

Server shouldn't crash 

**Steps to reproduce the problem:**

1. Accept quest "You, Robot" 
2. Right click item 28634 in proximity to the scrap reaver
3. Try using an ability

**rev. hash/commit:** 

Sunstrider rev. 10343 (8129e9d56781+)

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Friday Feb 01, 2019 at 15:38 GMT_

----

I can't seem to reproduce it.
Did you have a pet already?

**Comment by kelno** [comment]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [BarrensJerk](https://github.com/BarrensJerk)**
_Friday Feb 01, 2019 at 20:43 GMT_

----

Using the quest item brought up my pet bars - the Scrap Reaver was the pet. I hit the stomp ability and the server died. Will try again

**Comment by dinkletron** [comment]
Hey all, this quest is completed but unable to hand in. I have the item required in bags and quest is completed, but the NPC is grey. Should I submit a new issue or are you across it?

**Comment by kelno** [comment]
New issue yes

**Comment by Jerrythemagicdog** [comment]
Crash was fixed some time ago, closing.
