### ISSUE TITLE
[#248] Big Game Hunter

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#525]
<a href="https://github.com/balunn"><img src="https://avatars2.githubusercontent.com/u/46829506?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [balunn](https://github.com/balunn)**
_Sunday Feb 03, 2019 at 00:39 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/248_

----

**Current behaviour:**

Quest 'Big Game Hunter' #208, can be accepted without completing the required prequests.

**Expected behaviour:**

You should have to finish 'Tiger Mastery' #188, 'Panther Mastery' #193 and 'Raptor Mastery' #197 before being able to accept 'Big Game Hunter'

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/46829506/52170959-275e6f00-27a8-11e9-89a3-eb0beb69fb30.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
