### ISSUE TITLE
[#250] Special Forces

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#527]
<a href="https://github.com/balunn"><img src="https://avatars2.githubusercontent.com/u/46829506?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [balunn](https://github.com/balunn)**
_Sunday Feb 03, 2019 at 01:13 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/250_

----

Current behaviour:

Quest 'Special Forces' #574 can be accepted without completing the required prequests.

Expected behaviour:

You should have to finish 'Bad Medicine quest id 204 and 'The Second Rebellion' quest id 203 Before being able to accept Special Forces.

rev. hash/commit:
![image](https://user-images.githubusercontent.com/46829506/52171209-12d0a580-27ad-11e9-82b9-37d9f7b97b8d.png)

**Comment by Jerrythemagicdog** [comment]
Fixed
