### ISSUE TITLE
[#251] Gurf's Dignity

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#528]
<a href="https://github.com/silumor"><img src="https://avatars2.githubusercontent.com/u/46830678?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [silumor](https://github.com/silumor)**
_Sunday Feb 03, 2019 at 01:37 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/251_

----

item=23850

Tell us what happens:
I am level 12
Looted item=23850 off of npc=17475
opened quest window, clicked accept
Got the "You don't meet the requirements for that quest"

Should be able to accept quest as i meet the requirement of Level 7 

**Steps to reproduce the problem:**

1. Step 1 Loot item=23850
2. Step 2 Try to accept quest

Sunstrider Rev. 10357 (a9a5f35b2353) 2019-02-02 00:25:39 -0500 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by kelno** [comment]
<a href="https://github.com/silumor"><img src="https://avatars2.githubusercontent.com/u/46830678?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [silumor](https://github.com/silumor)**
_Sunday Feb 03, 2019 at 01:44 GMT_

----

After handing in quest=9562

I was Able to accept and complete quest=9564 , i should be able to use item=23850 even while doing quest=9562

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in "d77fc51af1e5878a5637ee047636ed4c81bddcd0" (scripts)
