### ISSUE TITLE
[#252] Bhag'thera

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#529]
<a href="https://github.com/balunn"><img src="https://avatars2.githubusercontent.com/u/46829506?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [balunn](https://github.com/balunn)**
_Sunday Feb 03, 2019 at 02:21 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/252_

----

**Current behaviour:**

I Killed Bhag'thera #728 roughly half an hour ago and he still hasn't respawned.

**Expected behaviour:**

Should Spawn.

![image](https://user-images.githubusercontent.com/46829506/52171673-15cf9400-27b5-11e9-9e33-90d936fdc2f7.png)

**Comment by kelno** [comment]
<a href="https://github.com/SUN-Leekie"><img src="https://avatars0.githubusercontent.com/u/18554785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SUN-Leekie](https://github.com/SUN-Leekie)**
_Sunday Feb 03, 2019 at 02:25 GMT_

----

It has a respawn time of 5min.

**Comment by Jerrythemagicdog** [comment]
Thanks, the respawn timer was 30 minutes, reduced it to 10.
