### ISSUE TITLE
[#255] [Quest] The Stones That Bind Us

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#530]
<a href="https://github.com/zemfi"><img src="https://avatars1.githubusercontent.com/u/46832429?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zemfi](https://github.com/zemfi)**
_Sunday Feb 03, 2019 at 06:17 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/255_

----

**Current behaviour:** Completing the objectives of this quest is significantly different than what is intended. You are able to kill the servants outright without needing to click the stone. You shouldnt be able todo that. Some stones are completely unclickable.

**Expected behaviour:** As you weaken each servant to a low health, they become immune until you click the stone freeing their spirit. The stone should despawn.

**Steps to reproduce the problem:**

1. Engage the servant NPC and you are able to kill it and it makes as progress in the quest.
2. Most stones are unclickable, found a few that are, clicking it (which you shouldnt be able to if the servant is dead or not engaged) does nothing, and doesnt despawn.

**Steps on what should happen:**

1. Engage the Servant, stone unclickable
2. Servant gets to a very low % (5%?) and becomes immune with an animation
3. Stone becomes clickable, click it
4. Servant dies, quest objective updates.

Quest: 
The Stones That Bind Us (#2681)
NPC's:
Servant of Sevine (#7671)
Servant of Allistarj (#7670)
Servant of Grol (#7669)
Servant of Razelikh (#7668)
Stone:
Stone of Binding (#141858)

Video of what should happen: https://youtu.be/UdplBOQlyBo?t=470

.rev 10357

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with the same one as https://github.com/SunstriderEmu/BugTracker/issues/724
