### ISSUE TITLE
[#257] [Item] Unidentified Plant Parts (24401)

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#532]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BarrensJerk](https://github.com/BarrensJerk)**
_Sunday Feb 03, 2019 at 12:51 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/257_

----

**Current behaviour:**

Item is lootable off herbalism nodes in Hellfire Peninsula and Netherstorm (haven't tried other zones)

**Expected behaviour:**

Should only be present as additional loot from herbalism nodes in Zangarmarsh

**Steps to reproduce the problem:**

1. Get herbing somewhere other than Zangarmarsh
2. Pretty soon you'll loot one

**rev. hash/commit:** 

Sunstrider rev. 10357 (a9a5f35b2353)

NOTES: 
- Please don't be shy on the details and context, screenshots and videos are VERY welcome
- Include the ID for game objects, npcs (creatures, pets, minions), spells, items, quests, instances, zones, skills related to this issue.

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago with the loot rework
