### ISSUE TITLE
[#260] Bloodsail Buccaneers

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#534]
<a href="https://github.com/balunn"><img src="https://avatars2.githubusercontent.com/u/46829506?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [balunn](https://github.com/balunn)**
_Monday Feb 04, 2019 at 00:20 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/260_

----

**Current behaviour:**

Quest 'Bloodsail Buccaneers' #599 can be accepted from 'Fleet Master Seahorn' #2487 as well as 'First Mate Crazz' #2490.

**Expected behaviour:**

The quest should be picked up from 'First Mate Crazz' and handed in at 'Fleet Master Seahorn'

![image](https://user-images.githubusercontent.com/46829506/52185018-bdf56380-286e-11e9-8a70-f3937073754f.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, the data is correct now.
