### ISSUE TITLE
[#261] [NPC] Mageslayer (18866) x2 underground spawns

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#535]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BarrensJerk](https://github.com/BarrensJerk)**
_Monday Feb 04, 2019 at 00:39 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/261_

----

**Current behaviour:**

These particular Mageslayers are spawning underground near quest giver NPC's in Netherstorm and attacking from at range eventually killing players. If an immunity is used or you run away, they surface and can be killed

GUID: 67476.
Faction: 16.
npcFlags: 0.
Entry: 18866.
DisplayID: 15438 (Native: 15438).
Level: 68.
EquipmentId: 0.
Health (base): 5233. (max): 5233. (current): 4057.
Field Flags: 524288.
Dynamic Flags: 4.
Faction Template: 16.
SpawnTime: Full:5m Remain:0s
Loot: 18866 Pickpocket: 0 Skinning: 0
Armor: 4995
InstanceID: 0

GUID: 67474.
Faction: 16.
npcFlags: 0.
Entry: 18866.
DisplayID: 15438 (Native: 15438).
Level: 69.
EquipmentId: 0.
Health (base): 5409. (max): 5409. (current): 0.
Field Flags: 0.
Dynamic Flags: 0.
Faction Template: 16.
SpawnTime: Full:5m Remain:5m21s
Loot: 18866 Pickpocket: 0 Skinning: 0
Armor: 5235
InstanceID: 0
Position: 2207.068359 2280.259277 78.565338 -0.024362.
AIName: 
ScriptName: 
Movement type: Ground: Run, Swim: true, Flight: None
Creature Pool ID: 0
Member of spawn group 2

**Expected behaviour:**

Spawn point should be above ground so players can see the mob or attack it back

**Steps to reproduce the problem:**

1. Go down hill from NPC Custodian Dieworth (19488) 
2. Get attacked by Mageslayer you can't see
3. Iceblock or run away and it'll surface to continue attacking

**rev. hash/commit:** 

Sunstrider rev. 10357 (a9a5f35b2353)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
