### ISSUE TITLE
[#262] Secrets of the colossus - Ashi

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#536]
<a href="https://github.com/balunn"><img src="https://avatars2.githubusercontent.com/u/46829506?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [balunn](https://github.com/balunn)**
_Monday Feb 04, 2019 at 00:54 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/262_

----

**Current behaviour:**

Quest 'Secrets of the colossus - Ashi' #8857 Can be accepted from 'Oglethorpe Obnoticus' #7406.

**Expected behaviour:**

The quest should be accepted from  'Colossus Researcher Nestor' #15798 and handed in at Oglethorpe Obnoticus'

![image](https://user-images.githubusercontent.com/46829506/52185414-90f77f80-2873-11e9-8a72-58b21b8b1874.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, must have been fixed in some previous update, the data is correct now.
