### ISSUE TITLE
[#265] Bloodsail Warlocks

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#538]
<a href="https://github.com/balunn"><img src="https://avatars2.githubusercontent.com/u/46829506?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [balunn](https://github.com/balunn)**
_Monday Feb 04, 2019 at 01:42 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/265_

----

**Current behaviour:**

Bloodsail Warlock #1564 with a summoned Succubus will not move to auto attack you. Instead they cast one shadow bolt and stand in place. Their summoned Succubus pets will only attack you if you hit then directly and do nothing if you hit their master.

Bloodsail warlocks that are supposed to have a summoned Imp instead have no pet, but their AI is working as intended.

![image](https://user-images.githubusercontent.com/46829506/52186248-5218f800-287a-11e9-8c56-01954d43f322.png)

**Comment by Jerrythemagicdog** [comment]
Tested, works fine, the pet is randomized on respawn
