### ISSUE TITLE
[#267] [NPC] Kirin'Var Ghost (20480)

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#540]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BarrensJerk](https://github.com/BarrensJerk)**
_Monday Feb 04, 2019 at 23:52 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/267_

----

**Current behaviour:**

Mob has neutral nameplate (yellow) but acts like hostile mob, agroes on proximity as it should

**Expected behaviour:**

Should be flagged as regular hostile mob with red nameplate

Changing unit_flags to 0 in creature_template fixed it on an old Suntrider core, probs same thing here

**rev. hash/commit:** 

Sunstrider rev. 10357 (a9a5f35b2353)

**Comment by Jerrythemagicdog** [comment]
Tested, it's hostile correctly.
