### ISSUE TITLE
[#271] [Quest] Mazen's Behest

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#541]
<a href="https://github.com/balunn"><img src="https://avatars2.githubusercontent.com/u/46829506?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [balunn](https://github.com/balunn)**
_Wednesday Feb 06, 2019 at 04:12 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/271_

----

**Current behaviour:**

The quest Mazen's Behest is acceptable from the hand in NPC 'Wather Mahar Ba' #5285
The quest item 'Khadgar's Essays on Dimensional Convergence' #6065 also doesn't seem to be dropping (I killed roughly 150 swamp walkers with no drop).

**Expected behaviour:**

Quest should only be acceptable from 'Accolyte Dellis' #5286.
 'Khadgar's Essays on Dimensional Convergence' should have a 5% chance to drop from #764, #765, #766 and #1081.
![image](https://user-images.githubusercontent.com/46829506/52320074-47e52e00-2a21-11e9-9627-08a9ea086218.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in loot rework some time ago.
