### ISSUE TITLE
[#276] [Item] Eroded Leather Case

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#545]
<a href="https://github.com/zemfi"><img src="https://avatars1.githubusercontent.com/u/46832429?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zemfi](https://github.com/zemfi)**
_Thursday Feb 07, 2019 at 07:06 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/276_

----

**Current behaviour:**

Item: Eroded Leather Case (#23338) required for opening a quest is not dropping, we able to confirm its in the loot table or just an extremely low drop rate?

**Expected behaviour:**

Should be able to kill a reasonable amount of the NPC's that drop it to obtain it.

**Steps to reproduce the problem:**

1. Kill Marauding Crust Burster (#16857)
2. Ive gone through over 7-10 respawn laps of these (over 75-100+ kills) and no drops.
3. They also drop from Tunneler (#16968) but due to another bug (#50), they cant be killed.
3.1 Ive killed a bunch of these guys for another quest and not looted them, that should have no issue?

.rev 10392

**Comment by Jerrythemagicdog** [comment]
Thanks!
Fixed with the loot rework.
