### ISSUE TITLE
[#277] [Quest] The Exorcism of Colonel Jules - Has Pre-Req, Shouldnt Be Open

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#546]
<a href="https://github.com/zemfi"><img src="https://avatars1.githubusercontent.com/u/46832429?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zemfi](https://github.com/zemfi)**
_Thursday Feb 07, 2019 at 07:24 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/277_

----

Note, this has no relation to my prev report of this quest (#227) which is todo with doing the quest itself; this one i missed earlier, as the quest should not be open (its part of a chain) at the start.

**Current behaviour:**

You are able to start this quest at anytime.

**Expected behaviour:**

Its part of a quest chain with pre-req, which is opened by completing Fel Spirits (#10909) and a laundry list of quests before that.

**Steps to reproduce the problem:**

1. Create a new toon, and go to Assistant Klatu (#22430)
2. Accept the quest: The Exorcism of Colonel Jules (#10935)

Info on the chains: 
http://db.hellfire-tbc.com/?quest=10935
https://www.wowhead.com/quest=10935/the-exorcism-of-colonel-jules#comments:id=32155

.rev 10392

**Comment by Tamosheik** [comment]
Updating comments for people that find this through the site quest status:
You **must** be on the correct part of the quest chain to complete this quest:
- After Digging for Prayer Beads
- Before Fel Spirits

**Comment by Jerrythemagicdog** [comment]
Doesn't seem to be the case anymore, had to be fixed in some commit.
