### ISSUE TITLE
[#281] [NPC] Various: Umbrafen - Totem not working, 0 sec buff

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#550]
<a href="https://github.com/zemfi"><img src="https://avatars1.githubusercontent.com/u/46832429?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zemfi](https://github.com/zemfi)**
_Friday Feb 08, 2019 at 06:00 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/281_

----

**Current behaviour:**

Two Issues:
Umbrafen Witchdoctor (#20115): Drops a Terror Totem (#20455); The totem's ability is to Terrify (#35198), but does nothing/no ability.

The Following NPC's have different persistent buffs applied to them, but the tooltip/mouseover buff shows them all at 0 seconds remaining:

Umbrafen Seer (#18079) [BUFF: Umbrafen Buff (#34871)
Umbrafen Oracle (#18077) [BUFF: Lightning Shield (#12550)
Umbrafen Witchdoctor (#20115) [BUFF: Umbrafen Buff (#34871)

**Expected behaviour:**

Totems ability should work once dropped, and the above buffs should not show 0 seconds remaining.

**Steps to reproduce the problem:**

1. Engage & Observe the above mobs.

.rev 10402

**Comment by Jerrythemagicdog** [comment]
Thanks!
The buffs were fixed in the aura duration rewrite.
Terror Totem (20455) now casts Terrify (35198) correctly as well.
