### ISSUE TITLE
[#282] [RAID] Kara - Gold dropped

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#551]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Friday Feb 08, 2019 at 12:01 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/282_

----

**Current behaviour:**

Mobs in Kara are dropping 3-4silver each - for example NPC # 16468
Ghostly Philanthropist are dropping 20-30silver each - NPC # 16470

**Expected behaviour:**

Mobs should drop more in general - may need source,
Ghostly Philanthropist should be dropping 10-12gold each
This was reduced/removed in WotLK

https://wow.gamepedia.com/Ghostly_Philanthropist

**Steps to reproduce the problem:**

1. Kill mobs in Kara
2. Observe loot dropped
3. Cry when you cant afford repair bills

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/52477310-859ab000-2bf5-11e9-8e17-95a245802c46.png)

**Comment by kelno** [comment]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [artieau](https://github.com/artieau)**
_Friday Feb 08, 2019 at 12:06 GMT_

----

Further testing - mobs in general are dropping hardly any loot at all.
Some mobs no loot ever just low amounts of currency.
The Curator only dropped gold, no items. - NPC # 15691

**Comment by kelno** [comment]
<a href="https://github.com/SUN-Leekie"><img src="https://avatars0.githubusercontent.com/u/18554785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SUN-Leekie](https://github.com/SUN-Leekie)**
_Wednesday Feb 13, 2019 at 02:04 GMT_

----

Gold is hardly something we can batch update just saying the gold should be up by 30%. It needs to be tested for each NPCs.

**Comment by kelno** [comment]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [artieau](https://github.com/artieau)**
_Wednesday Feb 13, 2019 at 07:51 GMT_

----

Certainly needs some input overall, research will take some time here.

However the Ghostly Philanthropist NPC # 16470 is the key here as that mob is supposed to drop a lot of currency (10-12gold)  each

**Comment by Jerrythemagicdog** [comment]
Fixed Ghostly Philantropist in Karazhan trash rework, no sources state the other ones should drop more.
