### ISSUE TITLE
[#287] Size of AoE spell animation

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#556]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Sunday Feb 10, 2019 at 10:05 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/287_

----

**Current behaviour:**

The visual effect of an AoE spell on the ground does not correlate to actual start/end of the effect of said spell.

**Expected behaviour:**

The visual and actual damage area in game, should fairly closely correlate.
There are some examples where it would not (such as Archimonde fire).
Examples found where it is WAY off - Netherspite void zones and Nightbane's Charred Earth

**Steps to reproduce the problem:**

1. Observe aoe ability on the ground, such as Charred Earth
2. Move out, even 10 yards away
3. Cry when die

**rev. hash/commit:** 

REV: 10421

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Feb 11, 2019 at 02:11 GMT_

----

I remember working on that but I also remember some were off on retail as well. Can you provide an example in video for charred earth on retail?

**Comment by kelno** [comment]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [artieau](https://github.com/artieau)**
_Monday Feb 11, 2019 at 05:58 GMT_

----

@kelno 
https://www.youtube.com/watch?v=9r3sf0xdthM
@ 1:13 Charred Earth spawns
@ 1:21 can see his safe distance - on current core this is not safe.

**Comment by artieau** [comment]
This is still an issue across all NPC enemy spell effects.
Example Spell ID # 25033 @kelno

**Comment by kelno** [comment]
Can someone test this charred earth example and see if that's still an issue atm?

**Comment by kelno** [comment]
Still broken and can be seen with Flare easily

**Comment by kelno** [comment]
Would be very nice to test flare range exactly and retail (maybe in classic) for reference

**Comment by kelno** [comment]
Should be fine now

**Comment by kelno** [comment]
Fixed Flare animation size as well

**Comment by kelno** [comment]
Okay, still wrong for some cases such as the Charred Earth. Hard to find a proper rule.

**Comment by Jerrythemagicdog** [comment]
Flare visual further improved in b2af058d12143243ecf45cf161d4914b454ef23c

**Comment by kelno** [comment]
We can't make a general rule, it has to be fixed case per case.
