### ISSUE TITLE
[#294] [Blood Furnace] Laughing Skull Rogue 

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#558]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Sunday Feb 10, 2019 at 11:04 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/294_

----

**Current behaviour:**

Laughing Skull Rogue  NPC # 17491 is stealthed and standing still.
These mobs can be seen from any distance, they are faded but not invisible.

**Expected behaviour:**

Mob should be patrolling the area while in stealth.
Mobs should be stealth/invisible to players.

**Steps to reproduce the problem:**

1. Enter Blood Furance
2. Clear Up the stairs
3. Find the rogues not moving (find with detection or flare)

**rev. hash/commit:** 

REV: 10421

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Feb 11, 2019 at 04:20 GMT_

----

To dev: Stealth issue might be related to their stealth spell not working correctly.

Need some more info about their movement as well, should ALL of them be doing this? Should only some?

**Comment by kelno** [comment]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [artieau](https://github.com/artieau)**
_Monday Feb 11, 2019 at 06:03 GMT_

----

From memory, all of the stealthed mobs here patrol their area.
2-3 mobs around stairway at entrance
2-3 mobs in hallway with technician between 1st/2nd bosses
to be confirmed though.

**Comment by artieau** [comment]
Mob stealth appears to be fixed, however do not seem to patrol in any dungeon @kelno

**Comment by kelno** [comment]
f-i-x-e-d
