### ISSUE TITLE
Drunk texts do not (always) appear anymore

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#56]
Drunkness effects are correctly working but the broadcasted texts (sober/tipsy/drunk/smashed) seems faulty and do not appear.
Sometimes they do but I don't know exactly when.

This text is handled by SMSG_CROSSED_INEBRIATION_THRESHOLD in the function Player::SetDrunkValue

**Comment by z5n** [comment]
unable to reproduce, issue has likely since been fixed
