### ISSUE TITLE
[#296] [Blood Furnace] The Maker - Knock up in air

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#560]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Sunday Feb 10, 2019 at 11:14 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/296_

----

**Current behaviour:**

When tank gets knocked up in air, if they do not move their character, the boss will evade and heal

**Expected behaviour:**

Boss should not evade

**Steps to reproduce the problem:**

1. Tank gets knocked up in air
2. Tank stands still
3. Boss heals due to evade

**rev. hash/commit:** 
 REV: 10421

**Comment by artieau** [comment]
Confirm this still happens, with any mobs knock-up in air type ability.
Another recent example is the Harbringer near the end of Arcatraz dungeon.

**Comment by kelno** [comment]
Working now
