### ISSUE TITLE
[#302] [Old Hillsbrad] Captain Skarloc 17862

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#562]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Sunday Feb 10, 2019 at 11:44 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/302_

----

**Current behaviour:**

Captain Skarloc#17862 spawns while running on his feet into battle, doing no RP with Thrall

**Expected behaviour:**

Boss should spawn in on his horse, not be attackable and do RP with Thrall before boss encounter starts.

**Steps to reproduce the problem:**

1. Start Skarloc
2. He runs in and fights straight up

**rev. hash/commit:** 

REV: 10421

**Comment by Jerrythemagicdog** [comment]
Thanks!
Fixed a long time ago in the Old Hillsbrad rewrite.
