### ISSUE TITLE
[#304] [NPC Spells] Black Blood & Vibrant Blood - Can Stealth

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#563]
<a href="https://github.com/zemfi"><img src="https://avatars1.githubusercontent.com/u/46832429?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zemfi](https://github.com/zemfi)**
_Sunday Feb 10, 2019 at 13:33 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/304_

----

**Current behaviour:**

As awesome as these debuffs are to your character graphically, you can actually stealth with them still applied (mob is dead)

Black Blood (#35331)
Vibrant Blood (#35329)

**Expected behaviour:**

When the debuff is applied to you, you shouldnt be able to stealth (as the tooltip says)

**Steps to reproduce the problem:**

1. Engage Marshlight Bleeder (#18133)
2. Get the debuff applied to you
3. Try and successfully stealth.

![tbc_blood1](https://user-images.githubusercontent.com/46832429/52534344-9e8d9780-2d94-11e9-8c6d-ae8d424accce.jpg)
![tbc_blood2](https://user-images.githubusercontent.com/46832429/52534346-a0eff180-2d94-11e9-8bee-a6f0aa7d0a51.jpg)

.rev 10421

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Feb 11, 2019 at 04:09 GMT_

----

No such effect in the spell effects, has to be custom scripted in

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed...
