### ISSUE TITLE
[#308] [Quest] Beer Basted Boar Ribs

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#564]
<a href="https://github.com/Tamosheik"><img src="https://avatars2.githubusercontent.com/u/40758487?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tamosheik](https://github.com/Tamosheik)**
_Monday Feb 11, 2019 at 02:47 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/308_

----

**Current behaviour:**
The quest [Beer Basted Boar Ribs, Quest.ID# 384] is not accessible unless the player has learned the cooking skill.

**Expected behaviour:**
The quest should be able to be accepted by anyone, even if they do not have the cooking skill.

**rev. hash/commit:**
Sunstrider rev. 10422 (12deac15c9a4) 2019-02-10 16:10:30 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Feb 11, 2019 at 04:12 GMT_

----

Can you source that please?

**Comment by kelno** [comment]
<a href="https://github.com/Tamosheik"><img src="https://avatars2.githubusercontent.com/u/40758487?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tamosheik](https://github.com/Tamosheik)**
_Monday Feb 11, 2019 at 04:53 GMT_

----

https://wow.gamepedia.com/Beer_Basted_Boar_Ribs_(quest)

![image](https://user-images.githubusercontent.com/40758487/52546626-ccaebe00-2e0c-11e9-8b60-88b6e7a0a832.png)

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Feb 11, 2019 at 20:17 GMT_

----

Thanks

**Comment by Jerrythemagicdog** [comment]
Fixed
