### ISSUE TITLE
[#309] [Cosmetic - World] - Floating Item @ Dun Morogh (49.3, 48.3)

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#565]
<a href="https://github.com/Tamosheik"><img src="https://avatars2.githubusercontent.com/u/40758487?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tamosheik](https://github.com/Tamosheik)**
_Monday Feb 11, 2019 at 03:40 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/309_

----

**Current behaviour:**

An item in the world at coords Dun Morogh 49.3, 48.3 are floating. (See Screenshot)
![image](https://user-images.githubusercontent.com/40758487/52545334-72106480-2e02-11e9-94f7-ab69a05960ce.png)

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Feb 11, 2019 at 04:12 GMT_

----

Probably a table missing there

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
