### ISSUE TITLE
[#323] [Quest] Morthis Whisperwing 10955

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#568]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Wednesday Feb 13, 2019 at 09:55 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/323_

----

**Current behaviour:**

The quest Morthis Whisperwing#10955 is not available in game currently.

**Expected behaviour:**

Quest should be available from the following places, once player has 300 riding skill only -
NPC # 12042
According to quick search, also available from all Druid trainers in their cities.

**Steps to reproduce the problem:**

1. Obtain 300 riding skill
2. Visit NPC 12042 or Druid trainers
3. Cry because cant get epic flight form, this is the starter quest but its missing

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/52703041-8f475d80-2fd1-11e9-9278-8091bd109135.png)

* Footnote to trigger Kel *

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed some time ago in "7a3879f20071ab9126310f9b5ed3dd547671ca4f" (scripts)
