### ISSUE TITLE
[#324] [Dungeon] Sethekk Halls - Sethekk Spirit

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#569]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Wednesday Feb 13, 2019 at 10:45 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/324_

----

**Current behaviour:**

The Sethekk Spirit NPC ID # 18703 which spawn in normal and heroic Sethekk Halls cast a spell called Spirit Burst, spell ID # 24050
This spell is  always fully resisted by the player.

**Expected behaviour:**

Spirit burst should do ~500 damage in a 10 yard radius, not resisted fully.

**Steps to reproduce the problem:**

1. Kill mobs near end of Sethekk Halls to spawn Sethekk Spirit
2. Sethekk Spirit attacks players and casts Spirit Burst
3. Spirit Burst is always fully resisted

![image](https://user-images.githubusercontent.com/40563134/52706074-9b82e900-2fd8-11e9-9695-84096d433690.png)

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/52706096-a89fd800-2fd8-11e9-9f84-184e88428d05.png)

Hi kel

**Comment by BarrensJerk** [comment]
The NPC needs a reduction in its move speed

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed!
