### ISSUE TITLE
[#326] [Quest] Vanquish the Raven God 11001

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#570]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Wednesday Feb 13, 2019 at 11:38 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/326_

----

**Current behaviour:**

Killing Anzu # 23035 in Sethekk Halls heroic does not count for quest # 11001

**Expected behaviour:**

Killing Anzu should count and complete the quest

**Steps to reproduce the problem:**

1. Have quest 11001
2. Kill Anzu
3. Still 0/1 Slain on quest

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/52709153-0be13880-2fe0-11e9-9cf7-77e6d9cdebf3.png)

**Comment by Jerrythemagicdog** [comment]
Tested now, works correctly.
