### ISSUE TITLE
[#330] Greater Bogstrok's not socially linked (can pull part of the pack at a time)

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#574]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Wednesday Feb 13, 2019 at 12:27 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/330_

----

**Current behaviour:**

You can pull 1-2 elites of the pack at a time 

**Expected behaviour:**

They should all be linked and come gang-bang you

**Steps to reproduce the problem:**

1. Stand at max range of a greater bogstrok in slave pens
2. Pull the mob
3. Watch only 1-2 come

![image](https://user-images.githubusercontent.com/45530324/52711661-169ace00-2fde-11e9-92fa-4778e719e92d.png)
![image](https://user-images.githubusercontent.com/45530324/52711694-2fa37f00-2fde-11e9-94b4-57c7be523e7d.png)

https://db.excalibur.ws/?npc=17817

**Comment by Jerrythemagicdog** [comment]
Thanks!
Fixed.
