### ISSUE TITLE
[Dungeon] Broken levers in shadowfang keep

### ISSUE THREAD

**Issue by plutonium447** [SunstriderEmu/BugTracker#575]
**Current behaviour:**
clicking on the levers that open cell doors in the first part of the dungeon will cause the levers to trigger their flipped animation, however the cell doors will not open, preventing further progress.

![screenshot from 2019-02-14 20-57-24](https://user-images.githubusercontent.com/40911527/52824969-a50a6f00-3106-11e9-8f47-2fc162f21954.png)

**Expected behaviour:**
clicking on the levers should open the cell doors

**Steps to reproduce the problem:**
1. .tele sfk
2. progress up to the first area where the cells are
3. pic related
4. click on one of the three levers

**rev. hash/commit:** 
Sunstrider rev. **10455** (aaf72e209219) 2019-02-13 12:14:05 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in 2098da89b283f82e8c32b44b35015fc3a90e98d1 (scripts)
