### ISSUE TITLE
[#338] 4 Packs + a patrol are all linked in the first room of shattered halls

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#583]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Wednesday Feb 13, 2019 at 12:55 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/338_

----

**Current behaviour:**

When I pull any mobs of the big group in the first room they all aggro and are linked together

**Expected behaviour:**

You should be able to pull 1-2 packs at a time if your careful of your timing with the pat

**Steps to reproduce the problem:**

1. Pull the left move pack when the patrol is on the far right side
2. Watch like 12 elites charge at you 

BE VERY SPECIFIC HERE. Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

![image](https://user-images.githubusercontent.com/45530324/52713139-3fbd5d80-2fe2-11e9-98a1-b971b7e51b53.png)

https://www.youtube.com/watch?v=YTX-5DYVgNw - 20 seconds in

**Comment by Jerrythemagicdog** [comment]
Thanks!
Tested recently, we were able to pull packs separately after the rework.
