### ISSUE TITLE
[#350] First patrol in shadow lab's isn't there (or not moving)

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#595]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Wednesday Feb 13, 2019 at 13:40 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/350_

----

**Current behaviour:**

First patrol in shadow lab's isn't there (or not moving)

**Expected behaviour:**

There should be a 1 mob pat that walks around that your sopost to pull first

**Steps to reproduce the problem:**

1. Zone into S-labs and see no pat there

BE VERY SPECIFIC HERE. Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

https://db.excalibur.ws/?npc=20641

![image](https://user-images.githubusercontent.com/45530324/52715488-49e25a80-2fe8-11e9-812f-a9cd33b932a7.png)

https://www.youtube.com/watch?v=1QHbVdiBbNY - I know this is retail and its defs the wrong mob but the dude I'm talking about is in the same spot at the first mob they kill on this video

**Comment by kelno** [comment]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kaziner](https://github.com/Kaziner)**
_Wednesday Feb 13, 2019 at 13:54 GMT_

----

Seen 0;06 sec into this video dead on the floor https://www.youtube.com/watch?v=3ft15SAj-go

**Comment by Jerrythemagicdog** [comment]
fixed some time ago
