### ISSUE TITLE
[#365] Mobs fleeing at full speed

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#608]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Thursday Feb 14, 2019 at 12:40 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/365_

----

**Current behaviour:**

When mobs are below 15% HP, they move at the same speed as above 15% HP.

**Expected behaviour:**

When below 15% HP, they should move/flee at a reduced movement speed.
Exact amount to be confirmed

**Steps to reproduce the problem:**

1. Damage mob to to 15% hp
2. Mob will try flee
3. Moves at full speed

Example is Bonechewer npcID 18952

**rev. hash/commit:** 

rev. 10550

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Thursday Feb 14, 2019 at 13:27 GMT_

----

Thanks!

**Comment by kelno** [comment]
Need more info on speed

**Comment by artieau** [comment]
Can not find any source, but this is most certainly a bug.
Perhaps 50% reduced movement speed, but it needs to be below 100% @kelno

**Comment by kelno** [comment]
Weellll thanks but that's still very imprecise, I'm pretty sure we can find it on some questing videos

**Comment by Jerrythemagicdog** [comment]
https://github.com/TrinityCore/TrinityCore/issues/21899
mentions 66% of run speed:

> This is still valid issue, they should run but be slowed by 33%, current implementation sets the speed properly to 66%.

**Comment by kelno** [comment]
Fixed
