### ISSUE TITLE
Mob disengagement

### ISSUE THREAD

**Issue by DotDotGoose** [SunstriderEmu/BugTracker#620]
**Description:**
-Fighting mobs, Ice Thistle Yeti, in winter spring can only run about 30 yards away and it will disengage combat. Seems way too low of a distance for disengagement. Must be checked

**Comment by artieau** [comment]
Please follow the ticket format where possible.
Can you share NPC ID # for the mobs you were fighting too?

**Comment by kelno** [comment]
https://www.wowhead.com/npc=7458/ice-thistle-yeti

**Comment by kelno** [comment]
Can you provide some evidence that this distance is too low?

**Comment by soup1234** [comment]
With further testing last night this is a more widespread issue, on any hostile NPC. 
If you move further then 40 yards from it’s spawning location it will immediately run away and reset.

**Comment by soup1234** [comment]
https://youtu.be/FgbhoxPwAt4

here is a quick video preview

**Comment by Jerrythemagicdog** [comment]
Info dump:

https://wowwiki.fandom.com/wiki/Leash?oldid=208713

https://www.reddit.com/r/wowservers/comments/5n57nw/how_is_mob_aggro_rangereset_range_supposed_to_work/


The range does seem low compared to the info here.

**Comment by kelno** [comment]
Fixed with 7ccd810c33655e5242ad2be600ef487daf808cb8
