### ISSUE TITLE
charge is proccing mage magisters set instantly

### ISSUE THREAD

**Issue by oj449** [SunstriderEmu/BugTracker#623]
**Description:**
charge is proccing mage frostbite talent instantly - gives your chill effects a 5/10/15% chance to freeze the target for 5 sec.
**Current behaviour:**
when you charge a mage with the 6 piece set bonus, which has a chance of freezing, you do not get to move the distance of charge as the charge hit is instant before you reach them so you are instantly frozen

**Expected behaviour:**
charge should not be proccing the 6 piece set
**Steps to reproduce the problem:**
charge a mage with the 6 piece bonus of magisters set a few times, should work.

**Comment by Jerrythemagicdog** [comment]
Is this issue about Frostbite (the mage talent) or the Magister's 6 piece set bonus, or both? You change it half way through.
Spell ID for Magister's set bonus: 27867

**Comment by oj449** [comment]
ah sorry i was testing it and realised it was the 6pc thought i changed all of the bits before posting my bad, it is for the 6 piece

**Comment by Jerrythemagicdog** [comment]
Thanks!
