### ISSUE TITLE
[GameObject] WANTED: Chok'sul, after accepting wanted board can still be interacted but is empty

### ISSUE THREAD

**Issue by Tamosheik** [SunstriderEmu/BugTracker#628]
**Description:**

After accepting **Wanted, Chok'Sul** [QUEST.ID #256] from the **Wanted** Board, the board can still be interacted with but provides no text.

**Current behaviour:**

See Screenshot
![image](https://user-images.githubusercontent.com/40758487/52890383-2ed23f00-31d0-11e9-8a10-22b1b5b09682.png)

**Expected behaviour:**

The Item should no longer be able to be interacted with after accepting the quest.

**Steps to reproduce the problem:**

1. Accept **Wanted, Chok'Sul**
2. Interact with The **Wanted** Board

**rev. hash/commit:** 
Sunstrider rev. 10470 (e53d6cfe1130) 2019-02-15 01:13:38 +0100 (master branch) (Unix, Debug, Static)

**Comment by Jerrythemagicdog** [comment]
Seems like an issue with all quest giver game objects (SELECT * FROM gameobject_template WHERE type = 2;) more than this individual one.

**Comment by z5n** [comment]
issue has since been fixed
