### ISSUE TITLE
[Hunter] Auto Shot Doesn't Change Targets

### ISSUE THREAD

**Issue by Tamosheik** [SunstriderEmu/BugTracker#629]
**Description:**
When swapping targets while **Auto Shot** [SPELL.ID #75] is enabled, a new target can be selected, however auto-shot will still target the original target,

**Expected behaviour:**
The next, and subsequent, Auto Shots should target the newly selected mob.

**Steps to reproduce the problem:**
1. Select a mob in range
2. Cast Auto Shot
3. Select a new target by left clicking, WITHOUT turning off auto shot
4. Auto Shot will still attack the original target, until cancelled and reapplied

**rev. hash/commit:** 
Sunstrider rev. 10470 (e53d6cfe1130) 2019-02-15 01:13:38 +0100 (master branch) (Unix, Debug, Static)

**Comment by kelno** [comment]
Very annoying indeed

**Comment by Tamosheik** [comment]
Am unsure if this can help: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2517

**Comment by kelno** [comment]
I get the "interrupted" message and the auto shot stops.
Anyway that's also a bug.

**Comment by woiwoz** [comment]
Let me check. I've solved this problem in my Vanilla Warcraft before.

**Comment by woiwoz** [comment]
In tbc, we can use UI settings - combat options - to set ourselves whether to stop automatic attacks. If we check this option, automatic shooting will not change the target as we switch targets, but interrupt casting.

**Comment by Tamosheik** [comment]
The current behaviour is that it continues the attack the old target, even after switching targets

**Comment by woiwoz** [comment]
You can try to find the "Stop Auto Attack" option in the UI interface and uncheck it.

**Comment by Tamosheik** [comment]
That's not the issue. When you switch targets, auto attack **should** attack the target you switch to, not continue attacking whatever target you had previously selected.

**Comment by woiwoz** [comment]
I see what you mean. When you follow the settings I said, automatic shooting will automatically switch to your current target.

**Comment by Tamosheik** [comment]
I'm uploading 2 videos showing the current behaviour, both with and without the option selected
https://youtu.be/0SGDGHk0hms - Option Deselected
https://youtu.be/MMtRqC4hdKQ - Option Selected

**Comment by woiwoz** [comment]
okay,thanks

**Comment by woiwoz** [comment]
Option Deselected   I see here that the second target you selected is not in front of you... of course it will be interrupted.

**Comment by Tamosheik** [comment]
It **wasn't** interrupted, that's the point. It continues to attack the spider **even after** the pig is selected.

**Comment by prosax** [comment]
This bug is still ingame...

**Comment by kelno** [comment]
We've fixed issues related to this recently, it all depends on the option you set in your client:
![image](https://user-images.githubusercontent.com/3866946/83323051-79a88680-a25c-11ea-94f5-900347c0689e.png)

"Stop auto attack" and "Auto attack/Auto shot" affect this behavior.
