### ISSUE TITLE
track humanoids in kitty wipes previous tracking

### ISSUE THREAD

**Issue by emorelix** [SunstriderEmu/BugTracker#632]
**Description:** / **Current behaviour:**
Tracking minerals in normal forms. When i swap to kitty, it automatically tracks humanoids and when i leave kitty form, this then clears my tracking altogether on the minimap.

**Expected behaviour:**

Shouldn't it revert to tracking minerals? I remember in BC on live, it would stay on the tracked items you were tracking in normal forms when you swap to kitty, unless you specifically turned it to track humanoids.

**Steps to reproduce the problem:**
**rev. hash/commit:** 

Sunstrider rev. 10470 (e53d6cfe1130) 2019-02-15 01:13:38 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by artieau** [comment]
Could be,  can you find some sources and provide them please?

**Comment by emorelix** [comment]
> Could be, can you find some sources and provide them please?

Will see if i can find anything for ya online =D

**Comment by kelno** [comment]
I remember that specific bug being discussed before, I'm okay without further proof here.

**Comment by kelno** [comment]
Fixed a long time ago
