### ISSUE TITLE
[Shaman] Totemic Call range

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#640]
**Description:**

Totemic Call Spell ID 36936
Appears to have a range check - should not

**Current behaviour:**

Using Totemic Call (36936) when a totem/s is more than 60 (?) yards away, results in no mana being return to the Shaman while the totem is destroyed still.

**Expected behaviour:**

There should not be a range check. Should return the mana and destroy the totem from any range.

**Steps to reproduce the problem:**

CHANGEME
1. Drop totem such as Tremor Totem (8143)
2. Run away from it, say 60 yards - dont have .distance command so cant be accurate but far away however can still see the totem
3. 0 mana returned and totem destroyed

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/53000641-f73bef00-347c-11e9-8594-25519ef8c36c.png)

**Comment by SUN-Leekie** [comment]
It actually works as intended (mana, totem unsummon) *however*, you don't see the totem disappear without moving after casting Totemic Call.

**Comment by Jerrythemagicdog** [comment]
Tested, works correctly even at extreme lengths.
