### ISSUE TITLE
[NPC] Evading NPCs at Veil Lashh - Blade's Edge Mountains

### ISSUE THREAD

**Issue by BarrensJerk** [SunstriderEmu/BugTracker#649]
**Description:**

2 Evading mobs  at Veil Lashh South West Blade's Edge. Evading at range.

**Current behaviour:**

Lashh'an Wing Guard (19944) and Lashh'an Windwalker (19945) both evading at range. Move into melee and can be killed / stop evading.

Once .npc info works again can link actual mobs
![veil lashh](https://user-images.githubusercontent.com/44628946/53215709-8d4e6000-369d-11e9-97ef-72ea99c8bcdd.jpg)

**Expected behaviour:**

**Steps to reproduce the problem:**

Sunstrider rev. 10530 (ec8fa6ac1145)

**Comment by BarrensJerk** [comment]
these mobs:

GUID: 71055.
Faction: 1738.
npcFlags: 0.
Entry: 19944.
DisplayID: 17858 (Native: 17858).
Level: 65.

GUID: 71069.
Faction: 1738.
npcFlags: 0.
Entry: 19945.
DisplayID: 19605 (Native: 19605).
Level: 66.

**Comment by BarrensJerk** [comment]
GUID: 71048.
Faction: 1738.
npcFlags: 0.
Entry: 19943.
DisplayID: 18485 (Native: 18485).
Level: 66.

**Comment by kelno** [comment]
Seems fixed
