### ISSUE TITLE
[NPC] Sethekk Guard (18323)

### ISSUE THREAD

**Issue by BarrensJerk** [SunstriderEmu/BugTracker#655]
**Description:**

NPC Sethekk Guard (18323) should be cc'able in normal mode, and immune to things like polymorph and freezing trap in heroic

**Current behaviour:**

Mob is immune to polymorph in normal mode

**Expected behaviour:**

Mob should be cc'able

**Steps to reproduce the problem:**

**rev. hash/commit:** 

Sunstrider rev. 10530 (ec8fa6ac1145)

**Comment by Jerrythemagicdog** [comment]
Thanks, https://wow.gamepedia.com/Sethekk_Guard only mentions heroic indeed. Fixed.
