### ISSUE TITLE
[Hellfire Ramparts] Nazan fire patch

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#666]
**Description:**

Fireball (Spell 34653) shot my Nazan (NPC 17536) should leave a flame patch on the ground which damages players. The graphic is missing and cant be seen, despite damage still taken.
Flame area left behind is called Liquid Flame (cant find spell effect ID)

**Current behaviour:**

Nazan shoots fireballs but the flame patch area cant be seen by players.
If standing in the area that the fireball landed, player still takes fire damage as if the flame patch was visible.

**Expected behaviour:**

Flame patch should be visible to player if it exists.

**Steps to reproduce the problem:**

1. Engage Vazruden/Nazan encounter
2. While fighting Vazruden, Nazan fireballs at players
3. Stand still, player takes fire damage but it cant be seen on the ground.

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/53278912-83416580-3760-11e9-80ce-6ffcec7ac9fd.png)

**Comment by kelno** [comment]
Fixed as of 10564

**Comment by kelno** [comment]
https://github.com/kelno/sunstrider-scripts/commit/756d48641b7436b93a974271ab474da7aba110ae

**Comment by artieau** [comment]
The flame can now be seen.
Players now take damage from the fireball hit only.
The flamepatch does no ticking damage while standing in it @kelno

**Comment by kelno** [comment]
Tested in heroic, it seems to work.
The resist chance is actually super high when attacked by a lvl 60 target.
