### ISSUE TITLE
Captain Dranarus - 25138

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#670]
**Description:**

Captain  Dranarus (NPC 25138) is dead in Shattrath.

**Current behaviour:**

Captain  Dranarus (NPC 25138) is dead in Shattrath and dies whenever he respawns.

**Expected behaviour:**

NPC should not be dead or die, just part of script of NPC's practicing next to flight master, see pic.

**Steps to reproduce the problem:**

1. Go to Shatt, near flight master
2. See Captain dead
3.  /mourn

![image](https://user-images.githubusercontent.com/40563134/53279890-7de81900-3768-11e9-9c0e-55abf0b73a00.png)

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/53279896-8c363500-3768-11e9-9a54-7932e0514c99.png)

**Comment by kelno** [comment]
Alive now!

**Comment by artieau** [comment]
Dead  again on rev. 13018 @kelno

**Comment by kelno** [comment]
Thanks

**Comment by kelno** [comment]
Fixed
