### ISSUE TITLE
[Hunter] Rework pet trainers

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#671]
Todo:
- [x] Make sure their text is okay and different for hunter/non hunter. Those can be switched with conditions. Trinity has most of those.
- [x] Make sure they sell their correct spells
- [x] Make sure they don't have any LK gossips/options left (those needs to be switched to patch 5). Note that having NO options means using the default ones, which is the correct behavior in most (all?) cases.

Old issue:
**Current behaviour:**

Karrina Mekenda (NPC 2879) does not have any Pet abilities to train for Hunters.

**Expected behaviour:**

NPC should have access to train Pet abilities such as Growl etc 
example Growl (Spell ID 27344)

**Steps to reproduce the problem:**

1. Talk to Karrina
2. No training options for Pet
3. Pet cries

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/53281276-f7d4ce00-3779-11e9-9b99-c3d084f57ed6.png)

**Comment by artieau** [comment]
Example of what it should look like from IF Pet trainer.
NPC #10090 - Belia Thundergranite

![image](https://user-images.githubusercontent.com/40563134/53281309-58640b00-377a-11e9-88b4-a54cde1c15a0.png)

**Comment by kelno** [comment]
`SELECT * FROM creature_default_trainer WHERE CreatureId = 2879`
`SELECT * FROM trainer WHERE id = 204889`
`SELECT * FROM trainer_spell WHERE TrainerId = 204889`

She got the spells, but not the menu.

**Comment by kelno** [comment]
Updated with 0303f8b40062dcbe854afcae99e80f83ffce1f2a
