### ISSUE TITLE
[Quest] "What Book? I Don't See Any Book" is not completable

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#678]
**Description:**

Quest (10231) NPC "Dirty Larry" (19720) turns hostile only for a little while and then turns back to neutral after starting the fight with him and his buddies. This leads to the quest not being completable as we have to beat him down to complete the quest.

**Expected behaviour:**

He should turn hostile and fight us. 

Video: https://www.youtube.com/watch?v=DLVvCI5eHLc

**rev. hash/commit:** 

Sunstrider rev. 10533 (cf4f6bcdef22) 2019-02-22 15:51:09 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by SUN-Leekie** [comment]
Regression

**Comment by giveusmezpls** [comment]
have also tried recently to complete this quest, the NPC 19720 becomes hostile looks like he evades or some such event and then reverts to neutral however not even Swidge with his mighty swords could land an attack in this time.

**Comment by Jerrythemagicdog** [comment]
Fixed
