### ISSUE TITLE
[Quest] "Vision of the Dead" does not allow the player to see ghost NPCs

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#679]
**Description:**

The quest Vision of the Dead (10252) should allow players to see "ghost" NPCs like "Horvon the Armorer" (19879), Greatfather Aldrimus (19698) and Orc Ancestors (18662) in Nagrand. 

Quest completion:
> Stranger... I was not forthright with you. Once you drink this potion, you will forever see into the world of the dead. This recipe that you drink of is a rite of initiation for all death priests of Auchindoun. Many go mad after its effects have taken hold. Seeing the dead is ... shocking.
> 
> <Nitrin puts the potion up to your lips.>
> 
> Do you wish to continue? 

**Sources**:
https://wowwiki.fandom.com/wiki/Horvon_the_Armorer

https://www.wowhead.com/npc=19698/greatfather-aldrimus#comments:id=133162

https://wowwiki.fandom.com/wiki/Ancient_Orc_Ancestor

**Current behaviour:**
The NPCs are currently spawned and are invisible but don't become visible to the players when quest completes (only visible in GM mode. )

**rev. hash/commit:** 

Sunstrider rev. 10533 (cf4f6bcdef22) 2019-02-22 15:51:09 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by woiwoz** [comment]
After testing, fixed completion.

**Comment by Jerrythemagicdog** [comment]
Fixed in a commit some time ago - tested works correctly.
