### ISSUE TITLE
[Quest] Deathblow to the Legion script is broken.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#680]
**Description:**

Deathblow to the Legion (10409) needs to be looked at. Currently the main "boss" NPC Socrethar (20132) is attackable before the quest event starts. He should only be attackable after starting the encounter involving the other NPCs. Kaylaan the Lost (20794) is also standing there since the beginning and a new Kaylaan the Lost gets spawned when the event starts.  After that the helping NPCs just reset and return to their original spawn point at the transporter instead of starting the fight. Kaylaan and Socrethar stand in place and don't engage with players.

**Expected behaviour:**

Here's a good source from retail: https://youtu.be/9d5PlpaSoKI 

**rev. hash/commit:** 

Sunstrider rev. 10533 (cf4f6bcdef22) 2019-02-22 15:51:09 +0100 (master branch)

**Comment by SUN-Leekie** [comment]
Regression

**Comment by rychersky** [comment]
Quest isn't working:

After taking the portal, the boss is unattackable and the Draenei NPCs are non-interactable (can't talk to them).

![WoWScrnShot_032420_203106](https://user-images.githubusercontent.com/45608488/77495584-aaa8ad00-6e0e-11ea-8b28-11e746b9868e.jpg)

Sunstrider rev. 13982 (e8564fe9e18a) 2020-03-23 12:16:27 +0100 (HEAD branch) (Unix, Release, Static)
