### ISSUE TITLE
[Rogue] Item "Warp-Spring Coil" buff gets consumed by special attacks

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#683]
**Description:**
Warp-Spring Coil buff Perceived Weakness (37174) gets cleared by special attacks and abilities. It should last for 15 seconds and not get cleared by anything other than canceling the aura manually.

**rev. hash/commit:** 

rev. 10543

**Comment by Jerrythemagicdog** [comment]
Fixed

**Comment by hufsa** [comment]
https://github.com/kelno/sunstrider/commit/ecc3e8896024d676018a303dd79070b21d2df094
