### ISSUE TITLE
[Quest] Protecting Our Own (10457)

### ISSUE THREAD

**Issue by BarrensJerk** [SunstriderEmu/BugTracker#685]
**Description:**

Using item Rina's Bough (29952) on Grove Seedlings gives credit for 2 summons each time one is used, instead of one.

**Current behaviour:**

Living Grove Defenders summoned (5) - 2 of the 5 credited each time you interact with the Grove Seedling

**Expected behaviour:**

Should have to interact with 5 Seedlings to get the 5 quest credits

**Steps to reproduce the problem:**

**rev. hash/commit:** 

Sunstrider rev. 10541 (2c9e67f6a401)

**Comment by Jerrythemagicdog** [comment]
Fixed in https://github.com/SunstriderEmu/BugTracker/issues/685
