### ISSUE TITLE
Add Lich King support

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#72]
This is more of a fun side project than a real issue, but here's a draft of what needs to be done.

The server expansion can be switched using the `LICH_KING` toggle in cmake.
A lot of code functionality is switched using this.
A lot of tables will have slightly different data... we need a standardized way to handle this.

- [ ] Change existing DBC imports
- [ ] Import all new DBC
- [x] How to handle world spawns switch? Game events?
- [ ] Add all missing creatures and gameobjects spawns
- [x] Handle creatures/gameobjects spawns removed after TBC
- [ ] New spell database
- [x] Check and fix each opcode structure
- [ ] Handle object update fields changes
   - [ ] PvP fields
   - [ ] Item fields
   - [ ] ...
- [ ] Add TLK scripts 
  -  [ ] core
      - [ ] Instances & creatures
      - [ ] Spells
   - [ ] db
- [ ] New item_template table
- [ ] Handle creature_template changes? Worth a full new table? Maybe an *_override system such as the one from spell_template?
- [ ] Completely missing systems
   - [ ] Achievements
   - [ ] Battlefields
   - [ ] LFG
- [ ] New spell effects
- [ ] New SummonPropertiesFlags
- [ ] ...

**Comment by Kittnz** [comment]
https://github.com/ValorenWoW/sunstrider-core/pull/76 can be used to handle spawns and much more.

**Comment by Kittnz** [comment]
We can add existing scripst from woltk to the db now since guid is now ok, we can add patch 5 to all of that data.

**Comment by plutonium447** [comment]
._0
