### ISSUE TITLE
Hellfire Peninsula - Flight Point from Honor Point to Honor Hold

### ISSUE THREAD

**Issue by BarrensJerk** [SunstriderEmu/BugTracker#720]
**Description:**

After completing quests at Honor Point, the last being "Invasion Point: Annihilator" (10397), the NPC manning the gryphons has no gossip option to fly back to Honor Hold, leaving ppl stranded at Honor Point.

**Current behaviour:**

The NPC Gryphoneer Leafbeard (20236) has no gossip option to fly back to Honor Hold.

**Expected behaviour:**

Should be able to talk to the NPC 20236 to fly back to Honor Hold after finishing quests at Honor Point.

**Steps to reproduce the problem:**

1. Go to Honor Point and do quests.
2. Build a summer beach house there cos you can't get back to Honor Hold via the Gryphon Master NPC 

**rev. hash/commit:** 

10570

**Comment by Jerrythemagicdog** [comment]
The NPC Gryphoneer Leafbeard (20236) offers a flight back to Shatter Point if the player has completed "Shatter Point" (quest 10340) which is in the chain previously.
He should not offer a flight back to Honor Hold, but a flight to Shatter Point. Then, the regular flightmaster Runetog Wildhammer (20234) provides a flight back to Honor Hold.
