### ISSUE TITLE
[NPC] Servant of Razelikh should be Unkillable

### ISSUE THREAD

**Issue by Tamosheik** [SunstriderEmu/BugTracker#724]
**Description:**

The Servant of Razelikh [NPC.ID #7668] is killable.
The Servant of Grol [NPC.ID #7669] is killable.
The Servant of Allistarj [NPC.ID #7670] is killable.
The Servant of Sevine [NPC.ID #7671] is killable.

**Expected behaviour:**

The Servant of Razelikh/Grol/Allistarj/Sevine should only be able to be damaged to 1% health and not be able to be killed unless the player is on The Stones That Bind Us [QUEST.ID # 2681] and clicks on the crystal linked to that specific mob.

** Steps to reproduce the problem:**

1. Attack one of the servants
2. Kill it

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/40758487/53635336-80ff6f80-3c68-11e9-9187-48bb0abae849.png)

**Comment by Jerrythemagicdog** [comment]
Thanks!
Fixed with one of the import commits in the past.
