### ISSUE TITLE
[QUEST] Assisting Arch Druid Staghelm Offered Twice

### ISSUE THREAD

**Issue by Tamosheik** [SunstriderEmu/BugTracker#725]
**Description:**

Innkeeper Firebrew [NPC.ID #5111] offers the quest Assisting Arch Druid Staghelm twice.

**Current behaviour:**

![image](https://user-images.githubusercontent.com/40758487/53642478-9c28aa00-3c7d-11e9-89dd-2dfa7c23ecfc.png)

**Expected Behaviour**
The two quests being offered are probably [QUEST.ID #3763] and [QUEST.ID #3789]. Both these quests are identical, however I believe the correct Quest ID he should offer is 3789.

He should also offer [QUEST.ID #8353], but **only** seasonally, during Hallow's End.

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/40758487/53642578-da25ce00-3c7d-11e9-84dd-386a2246f5d4.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
