### ISSUE TITLE
[Creature movement] Some creatures end up with a weird orientation after spreading around the target

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#726]
**Description:**
Some creatures (for example Laughing Skull Enforcer (17370) - first pack in Blood Furnace) don't correctly adjust their orientation when spreading (or fanning, whichever term is correct) around their target.

**Current behaviour:**

This is how it looks like, two of them are hitting the same target but one of them is looking away:
https://imgur.com/a/wEPt8gD

**Expected behaviour:**

They should both be facing their target.

**Steps to reproduce the problem:**

1. Pull the creatures
2. Run in circles so they stack on top of each other while chasing
3. Stop and let them spread around you, one of them will end up looking away

It's not a very common occurrence, I didn't test for long but only saw it happen to those specific Enforcers.

**rev. hash/commit:** 
rev. 10571

**Comment by kelno** [comment]
Fixed now?

**Comment by Jerrythemagicdog** [comment]
Seems so I haven't seen it happen in a very long time.
