### ISSUE TITLE
[Professions] Training Past 75/150/225/300

### ISSUE THREAD

**Issue by BarrensJerk** [SunstriderEmu/BugTracker#730]
**Description:**

Training a profession skill from trainer NPC drops the profession icon from action bars

**Current behaviour:**

Whenever a new profession skill eg. Tailoring (Journeyman), Jewelcrafting (Expert) from appropriate NPC, any profession icon present on action bars drops off, and needs to be re-added from spellbook

**Expected behaviour:**

Profession icon / link on action bars should persist through training a new proficiency of a profession and remain on actionbars, and not need to be re-added.

**Steps to reproduce the problem:**

1. Train tailoring to level 50
2. Have a Tailoring (apprentice) icon present on an action bar
3. Learn Tailoring (Journeyman) from NPC
4. The Tailoring icon will disappear from action bars, will need to be re added from spellbook General tab 

**rev. hash/commit:** 

rev. 10570

**OBVOIUSLY NOT A BIG DEAL OR GAME BREAKING BUT STILL BUGGED**

**Comment by Jerrythemagicdog** [comment]
Fixed with the linked commit, the icons are now replaced correctly.
