### ISSUE TITLE
[Gruul's Lair] Lair Brute performs threat drops without charging

### ISSUE THREAD

**Issue by Kaziner** [SunstriderEmu/BugTracker#731]
**Description:**

Lair Brute performs threat drops without charging

**Current behavior:**

When a lair brute is being tanked; when everyone else in the raid sits on his ass he doesn't perform his charge but he does perform a threat drop

**Expected behaviour:**

The threat drop should be tied to his charge

**Steps to reproduce the problem:**

CHANGEME
1. Tank; thanks a lair brute and builds plenty of threat
2. Someone stands behind the lair brute and waits
3. The lair brute will perform the threat drop; turn around and smash the dude behind him

rev 10570

https://db.excalibur.ws/?npc=19389#abilities

Comment from wowhead: https://www.wowhead.com/npc=19389/lair-brute#comments

These guys wont charge people randomly if your whole group stands right behind the mob. Even hunters have to melee. Now that the charge is gone, it's a basic tank'n'spank mob. Only the tank should be standing in front of the mob. Now this become tricky with two mobs but not impossible.

**Comment by Jerrythemagicdog** [comment]
Thanks!
The script has changed since this report and the threat drop is linked to the charge.

**Comment by tthierolf** [comment]
This issue is not fixed, the Lair Brutes will drop aggro every few seconds without charging.
