### ISSUE TITLE
[Karazhan] Spectral charger is using its fear in melee without charging

### ISSUE THREAD

**Issue by Kaziner** [SunstriderEmu/BugTracker#740]
**Description:**

Spectral charger is using its fear in melee without charging

**Current behaviour:**

Spectral charger is using its fear in melee without charging

**Expected behaviour:**

It should charge to a player (that must be more then 7 yrds away) and drop an aoe fear bomb ontop of them when it arrives

**Steps to reproduce the problem:**

CHANGEME
1. Fight a spectral charger; get fear bombed while in melee

10570

https://db.excalibur.ws/?npc=15547#abilities
https://db.excalibur.ws/?spell=29320

**Comment by Jerrythemagicdog** [comment]
Sources: 
https://wowwiki.fandom.com/wiki/Spectral_Charger
https://www.wowhead.com/npc=15547/spectral-charger#comments:id=130629

> Charge (Physical) - Charges the most distant enemy, inflicting normal damage plus 150, then fears all nearby targets. 

Thanks, fixed.
