### ISSUE TITLE
[Karazhan] Skeletal Usher's Ice Tomb doesnt perform a threat drop

### ISSUE THREAD

**Issue by Kaziner** [SunstriderEmu/BugTracker#741]
**Description:**

Skeletal Usher's Ice Tomb doesnt perform a threat drop

**Current behaviour:**

AFter being Ice Tombed you keep your current threat

**Expected behaviour:**

It should perform a full threat drop

**Steps to reproduce the problem:**

CHANGEME
1. Fight a skeletal usher
2. Get ice tombed

rev 10570

![wowscrnshot_030119_211937](https://user-images.githubusercontent.com/45530324/53690158-ee1e1c80-3db0-11e9-9926-4dcf9aae49a9.jpg)

https://db.excalibur.ws/?npc=16471
https://db.excalibur.ws/?spell=29670
https://www.wowhead.com/npc=16471/skeletal-usher#comments

"They freeze their target and drop 100% threat and start over, so if you are mid shot and hit him right after you prolyl get the aggro"

**Comment by Jerrythemagicdog** [comment]
It appears to be the same mechanic that made creatures swap targets from the feared one (e.g. Nightbane) to the next on threat list - was removed in later patches. 
This is restored though as it can be a fun little thing in a raid.
Thanks!
