### ISSUE TITLE
[Tempest Keep] Trash packs in TK are missing mobs

### ISSUE THREAD

**Issue by Kaziner** [SunstriderEmu/BugTracker#742]
**Description:**

Lots of trash missing in TK

**Current behaviour:**

Trash packs in TK are missing mobs

**Expected behaviour:**

Those mobs should be there

**Steps to reproduce the problem:**

CHANGEME
1. Look at the trash in TK

rev 10570

Found a good video to refrence from TBC https://www.youtube.com/watch?v=49eEaKnRvz4

Also note that the patrol isn't patroling as well

![wowscrnshot_030219_213326](https://user-images.githubusercontent.com/45530324/53690205-f9257c80-3db1-11e9-91d4-51e48143b592.jpg)
![wowscrnshot_030219_213634](https://user-images.githubusercontent.com/45530324/53690206-fe82c700-3db1-11e9-8fd0-f3efae3d674e.jpg)

**Comment by Jerrythemagicdog** [comment]
Fixed in one of 19e3fd2df122f4daaf9102d7f03d494012cb70e3 some time ago.
