### ISSUE TITLE
[Tempest Keep] Phoenix-Hawks in TK have too little hp (have 70k instead of 500k

### ISSUE THREAD

**Issue by Kaziner** [SunstriderEmu/BugTracker#743]
**Description:**

Phoenix-Hawks in TK have too little hp (have 70k instead of 500k

**Current behaviour:**

Phoenix-Hawks in TK have too little hp (have 70k instead of 500k

**Expected behaviour:**

Phoenix-Hawks in TK have too little hp (have 70k instead of 500k

**Steps to reproduce the problem:**

CHANGEME
1. Look at a phoenix hawk in TK

Note: They appear to have the same HP as the little ones under Alar; if thats noteworthy

rev 10570

![wowscrnshot_030219_213952](https://user-images.githubusercontent.com/45530324/53690223-4570bc80-3db2-11e9-98b0-8a733d25b519.jpg)

https://db.excalibur.ws/?npc=20039

**Comment by Cheelout** [comment]
Fixed with SQL Update
UPDATE `creature_template` SET `HealthModifier` = 83.3 WHERE `entry` = 20039; -- Phoenix Hawk - Set HP to 500k instead of 60k

**Comment by Jerrythemagicdog** [comment]
Fixed with Mode's commit
