### ISSUE TITLE
[Tempest Keep] Links of mobs in TK is broken

### ISSUE THREAD

**Issue by Kaziner** [SunstriderEmu/BugTracker#744]
**Description:**

Alot of the social links are broken; alot of packs are coming in parts

**Current behaviour:**

Alot of the social links are broken; alot of packs are coming in parts

**Expected behaviour:**

The packs should pull together

**Steps to reproduce the problem:**

CHANGEME
1. Pull a crystalcore sentinal or pretty much of the trash between alar and void reaver and note they don't all come

rev10570
![wowscrnshot_030219_214514](https://user-images.githubusercontent.com/45530324/53690236-9aacce00-3db2-11e9-917c-5dd51a759c75.jpg)
![wowscrnshot_030219_214533](https://user-images.githubusercontent.com/45530324/53690240-9f718200-3db2-11e9-877f-9b6bed9fd20c.jpg)
![wowscrnshot_030219_215717](https://user-images.githubusercontent.com/45530324/53690245-aac4ad80-3db2-11e9-8e35-acba698b56e6.jpg)

**Comment by Jerrythemagicdog** [comment]
Fixed some time ago in the TK trash rework (one of 19e3fd2df122f4daaf9102d7f03d494012cb70e3)
