### ISSUE TITLE
[Tempest Keep] Void reaver is in the wrong spot

### ISSUE THREAD

**Issue by Kaziner** [SunstriderEmu/BugTracker#745]
**Description:**

Void reaver is in the wrong spot

**Current behaviour:**
Void reaver is in the wrong spot

**Expected behaviour:**

He should be square in line with the entrance to the room; instead he is off to the side

**Steps to reproduce the problem:**

CHANGEME
1. Look at void reaver

rev 10570
![wowscrnshot_030219_220420](https://user-images.githubusercontent.com/45530324/53690271-2292d800-3db3-11e9-8230-8f766718da0c.jpg)
![lootreaver](https://user-images.githubusercontent.com/45530324/53690276-36d6d500-3db3-11e9-992e-3653f5cecddd.JPG)

https://db.excalibur.ws/?npc=19516

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
