### ISSUE TITLE
Crimson head centurions's arcane flurry is not shooting arcane bolts at ranged

### ISSUE THREAD

**Issue by Kaziner** [SunstriderEmu/BugTracker#749]
**Description:**

Crimson head centurions's arcane flurry is not shooting arcane bolts at raned

**Current behaviour:**

Crimson head centurions's arcane flurry is not shooting arcane bolts at ranged - just melee dmg only

**Expected behaviour:**

While it spins it should shoot arcane bolts at ranged people

**Steps to reproduce the problem:**

CHANGEME

1. Fight a crimson hand centurion and let it cast arcane flurry
2. Not does it doesn't shoot arcane bolt at ranged people

rev 10570

![wowscrnshot_030219_220203](https://user-images.githubusercontent.com/45530324/53690360-d0eb4d00-3db4-11e9-861c-06bea58c7b7f.jpg)

https://db.excalibur.ws/?npc=20048#abilities
https://db.excalibur.ws/?spell=37268
https://www.wowhead.com/npc=20048/crimson-hand-centurion#comments
"Arcane flurry does spam bolts at people that tick for 1-1.2k, but the real deal is when you get into melee with them. Not advisable."

**Comment by Jerrythemagicdog** [comment]
Thanks!
It's actually a second spell (37161).
Fixed with one of the TK rework commits some time ago, possibly "bb14664fa6147f4ea5ecfe333b636fe28ed46223" (scripts)
