### ISSUE TITLE
[Mechanic] Shooting a wand (or maybe other ranged attacks) doesn't correctly trigger a GCD

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#755]
**Description:**

When shooting a wand we can immediately cast another spell. There should be a Global Cool Down issued when we release our shot preventing us from casting a spell while shooting.

**rev. hash/commit:** 

rev. 10597

**Comment by Jerrythemagicdog** [comment]
Here's how it looks:
https://streamable.com/l98vz
both the wand shot and the spell have to be pressed as the wand shot is about to leave the character.

**Comment by hufsa** [comment]
The 'Shoot' does in fact trigger a GCD afaik. The issue I believe is that an instant spell can be casted during the cast time of Shoot. Expected behaviour: Shoot should be interrupted when casting a spell

**Comment by kelno** [comment]
We did some changes related to this I think, doesn't seem possible anymore?

**Comment by Jerrythemagicdog** [comment]
It's still possible, but it requires the player to hit a tight timing window - not very reliable or impactful.

**Comment by artieau** [comment]
Tested and still possible, per Jerry its a very small window though.
Close issue if its OK exist? @Jerrythemagicdog
