### ISSUE TITLE
[Mechanic] Effects which benefit from being a victim of a critical strike - resilience interaction

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#772]
**Description:**
From https://wowwiki.fandom.com/wiki/Patch_2.0.7

> Any effect which benefits the victim of a critical strike will now trigger even if resilience converted the attack from a critical strike to a normal strike; this applies to melee, ranged, and spell. The affected talents, abilities, and items are: "Eye for an Eye", "Blessed Resilience", "Enrage", "Martyrdom", "Blood Craze", "Eye of the Storm", and "Bonespike Shoulder". 

**Current behaviour:**
Currently not implemented

**Comment by kelno** [comment]
Dup https://github.com/SunstriderEmu/BugTracker/issues/1425
