### ISSUE TITLE
[Priest] Fully resisted dot damages break Blind

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#773]
**Description:**

SW:D deals backlash damage to the caster even if the damage of the spell was fully resisted

> Brug gains Cloak of Shadows.
> Tom casts Shadow Word: Death at Brug.
> Tom's Shadow Word: Death was fully resisted by Brug.
> Tom is afflicted by Shadow Word: Death.
> Brug casts Blind at Tom.
> Tom's Blind is refreshed.
> Tom is afflicted by Blind.
> Shadow Word: Death dissipates from Tom.
> Blind dissipates from Tom.

It appear to deal no damage but is still capable of breaking CCs 

**Steps to reproduce the problem:**

1. Duel a Rogue
2. Make Rogue use Cloak of Shadows
3. Use Shadow Word: Death
4. Tell him to Blind while he is still Cloaked
5. He resists the spell but Blind is still broken as a result of the backlash "damage"

**rev. hash/commit:** 

10603

**Comment by soup1234** [comment]
Thanks for checking this, I was fully hit capped so I didn’t see any resists

**Comment by kelno** [comment]
Fixed
