### ISSUE TITLE
[Mechanics] Downranking

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#775]
**Description:**

Some spells have a downranking factor in their damage formula. For example Rank 1 of Shadow Word: Pain deals a lot of damage right now (125 per tick on level 70), while in the damage formula it is mentioned that it's supposed to take into account the downranking factor:

**From wowwiki Shadow Word: Pain** (https://wowwiki.fandom.com/wiki/Shadow_Word:_Pain?oldid=1386790):

```
Damage = (Real_base_damage + (1.1 * Shadowdamage * Downrank_factor )) * (1 + Misery + Darkness) * ((18+Improved_SW_Pain_duration_bonus)/18) 
    Damage_per_tick = Damage / ((18/3)
```

**Here's how Downrank factor gets calculated during Burning Crusade** (https://wowwiki.fandom.com/wiki/Downranking): 

```
downrank = (spell_maxlevel + 6) / playerlevel;
if (downrank > 1) downrank = 1;
if(spell_minlevel  < 20) 
{
  sub20downrank = 1.0 - ((20-spell_minlevel) * 0.0375);
  if(sub20downrank < 0) sub20downrank = 0;
  downrank = downrank * sub20downrank;
}
```

Right now the Rank 1 of Shadow Word: Pain follows the coefficient (https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=1285321) of 110%

I suspect this is the case for a whole bunch of spells.

**rev. hash/commit:** 

rev. 10629

**Comment by soup1234** [comment]
You’re looking at patch 3.2.0 for the damage on down ranks. I’m pretty sure that was changed due to DOT critical strikes

**Comment by Jerrythemagicdog** [comment]
do you mean the formula for Downranking? Wowwiki says patch 2.2.

**Comment by hufsa** [comment]
#771

**Comment by hufsa** [comment]
http://wow.allakhazam.com/wiki/spell_coefficient_(wow)

**Comment by kelno** [comment]
I remember that we had the TLK one and Leekie did some work to change that at some point.

**Comment by kelno** [comment]
Needs to confirm what's correct here!

**Comment by Jerrythemagicdog** [comment]
I think this formula that I link is from TBC but I'm not sure, it might result in a lot of weird cases that are not thought of. Shadow Word: Pain (Rank 1) doing 121 damage per tick seems a little crazy though.

**Comment by Jerrythemagicdog** [comment]
Fixed the case in this issue, for future problems with downranking penalty always check for maxLevel in the spell.
