### ISSUE TITLE
[Alterac Valley] Quests

### ISSUE THREAD

**Issue by Azytheoneandonly** [SunstriderEmu/BugTracker#783]
**Description:**

Alterac Valley Quests Can't Be completed. Various Issues.

**Current behaviour:**

Unable to Loot the banners in the cave as either alliance or horde states "That is already being used."
http://db.hellfire-tbc.com/?object=179024 & http://db.hellfire-tbc.com/?object=179025
![AV Quest - Banner - Proving Grounds Alli](https://user-images.githubusercontent.com/37324574/54469721-9f787580-47e7-11e9-8723-068ab0db24a1.PNG)
Killing the Mine Boss fails to complete the quest.
Looting Tower/Graveyard fails to complete quests.

Not sure if Korrak quest is meant to still exist as he doesn't spawn anymore.
In patch 1.10, Korrak was removed from Alterac Valley, along with most of the other non-Alliance & non-Horde NPC (though harpies, troggs, gnolls, and kobolds still exist). 
ref: https://wow.gamepedia.com/Korrak_the_Bloodrager

**Expected behaviour:**

Quests should be completed as each objective is done.

**Steps to reproduce the problem:**

1. Zone into AV and attempt to do each objective.

Quests.
Mine Capture: http://db.hellfire-tbc.com/?quest=7124
Bunker Capture: http://db.hellfire-tbc.com/?quest=7102
Graveyard Capture: http://db.hellfire-tbc.com/?quest=7081
Proving Grounds: http://db.hellfire-tbc.com/?quest=7162

**rev. hash/commit:** 
![Server Version Sat 16 12pm](https://user-images.githubusercontent.com/37324574/54469722-a0110c00-47e7-11e9-91b4-4f932c32d4d0.PNG)

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/4016
