### ISSUE TITLE
[NPC] Sergeant Shatterskull

### ISSUE THREAD

**Issue by Azytheoneandonly** [SunstriderEmu/BugTracker#784]
**Description:**

NPC Outside Thrallmar sets new reset point if you talk to him while he is in combat.

**Current behaviour:**

Updates Reset Location every time you talk to him while he is in combat. Could be used to Grief.

**Expected behaviour:**

He Should Reset to the correct Location rather than the place where he is interacted with.

**Steps to reproduce the problem:**

1. Wait for Sergeant Shatterskull to chase after NPC and talk to him.
2. Repeat Process multiple times to have him cross hellfire.
3. .die him so he revives to see his true spawn location where he should reset after each fight.

http://db.hellfire-tbc.com/?npc=19256

**rev. hash/commit:** 
![Server Version Sat 16 12pm](https://user-images.githubusercontent.com/37324574/54470161-1bc28700-47ef-11e9-9816-88fd1560893f.PNG)

**Comment by Azytheoneandonly** [comment]
This might work on more than just him tested it on an alliance npc and it kinda worked but they went back to their patrol after about 30 seconds. assuming he doesn't because he has no patrol.

**Comment by Jerrythemagicdog** [comment]
The creatures indeed go back to their home position after the "stop to talk" timer expires.
