### ISSUE TITLE
[Alterac Valley] Belinda Issues

### ISSUE THREAD

**Issue by Azytheoneandonly** [SunstriderEmu/BugTracker#785]
**Description:**
Belinda Targeting horde player after Reset and not engaged.
Greater Water Elemental Does not Engage instantly if you are at range.

**Current behaviour:**

Reset Belinda and she was still targeting me. Didn't Occur every time. once out of like four times i was playing around with her.
Her Greater Water Elemental Does not attack until she moves closer to melee or you move into melee range.

**Expected behaviour:**

Belinda should reset without having a target.

Her Greater Water Elemental should attack whoever she is in combat with no matter where they are located until they run outside the building.

**Steps to reproduce the problem:**

1. Zone into AV as horde.
2. Slap Belinda a few times from range to see the water elemental issue
3. reset her to see if the targeting issue happens.

**rev. hash/commit:** 
![Server Version Sat 16 12pm](https://user-images.githubusercontent.com/37324574/54470345-eb301c80-47f1-11e9-999b-627e30140108.PNG)

**Comment by kelno** [comment]
Rewritten since
