### ISSUE TITLE
[Tailoring] Broken Moonwells

### ISSUE THREAD

**Issue by Azytheoneandonly** [SunstriderEmu/BugTracker#787]
**Description:**
Moonwell in Darnassus is broken.

Another just outside Darnassus
http://db.hellfire-tbc.com/?object=19551

Checked most others and didn't find any other broken ones.

**Current behaviour:**
When inside the moonwell and attemping to craft mooncloth it fails with requires moonwell.

**Expected behaviour:**

When inside the moonwell and attemping to craft mooncloth it should craft it.

**Steps to reproduce the problem:**
1. 250+ Tailor
2. Go to Darnussus/Other attempt to craft mooncloth

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/37324574/54478569-5106bd80-485f-11e9-9357-274e286dd08a.png)

**Comment by kelno** [comment]
Fixed
