### ISSUE TITLE
[Zone] Nagrand - Halaa bombing flight posts do not work.

### ISSUE THREAD

**Issue by Arissarlia** [SunstriderEmu/BugTracker#790]
**Description:**

The flight posts to kill the guards in Halaa can't be claimed by the opposing faction.

**Current behaviour:**

After Halaa has been claimed by the opposite faction - You cannot claim the posts on the outskirts of Halaa to start bombing the guards. The channeling time goes along, but soon as it finishes nothing happens.

**Expected behaviour:**

After channeling to take-over of the mount-posts on the outskirts of Halaa as the opposing faction, you should be able to click on the mount and spawn on-top of it and fly around Halaa with the 10x Firebombs it gives you to bomb Halaa guards with. 

https://www.youtube.com/watch?v=USPHP6a9IaI

**Steps to reproduce the problem:**

1. Have Halaa be taken by opposing faction

2. Try to take the outposts on the outskirts of Halaa using the opposing faction to that has claimed it.

3. Fail to take the outposts on the outskirts of Halaa due to no mounts spawning.

4. Cry

**rev. hash/commit:** 

![serverinfo](https://user-images.githubusercontent.com/48640427/54487606-f2d1ed00-48e7-11e9-94e1-2dced604ea86.jpg)

**Comment by kelno** [comment]
Fixed since
