### ISSUE TITLE
[Zone] Nagrand - Halaa guard counter doesn't work.

### ISSUE THREAD

**Issue by Arissarlia** [SunstriderEmu/BugTracker#791]
**Description:**

Halaa guard counter isn't going down when guards are killed.

**Current behaviour:**

The guard counter up the top of the screen when inside Halaa stays at 15/15 even after the guards are killed.

**Expected behaviour:**

The counter is supposed to go down with each guard killed allowing the opposite faction to take the zone after 0/15 has been achieved.

**Steps to reproduce the problem:**

Step 1. Go to Halaa
Step 2. Kill the Halaa guards
Step 3. Look at guard counter

**rev. hash/commit:** 

![serverinfo](https://user-images.githubusercontent.com/48640427/54517202-eebdd200-49b0-11e9-88ab-86f5fa3552b5.jpg)

**Comment by kelno** [comment]
Fixed since
