### ISSUE TITLE
[Dungeon] Hellfire Ramparts - Trash immunities

### ISSUE THREAD

**Issue by Arissarlia** [SunstriderEmu/BugTracker#793]
- Description  Hellfire Rampart mobs aren't using abilities & mind control immunity tables are wrong.

Current Behavior - Every mob in hellfire ramparts just use melee attacks and don't use their abilities at all & some mobs should be immune to mind control / be mind controlled. (Can abuse the Destroyer's melee knock-back to do quick damage)

- Expected Behavior

The trash mobs should be using the ability selection below.

Bleeding Hollow Archer - [Multi-Shot] / [Aimed Shot] - Should be immune to [Mind Control]
Bleeding Hollow Darkcaster - [Rain of Fire] [Scorch]
Bleeding Hollow Scryer - [Fear] / [Shadow Bolt] - Shouldn't be immune to [Mind Control]
Bonechewer Beastmaster - [Battle Shout] & Summons 3 Warhounds
Bonechewer Destroyer - [Mortal Strike] & Randomly knocks away its target switching aggro to another target. - Should be immune to [Mind Control]
Bonechewer Hungerer - Runs away at low hp, uses [Demoralizing Shout] & [Disarm] - Should be immune to [Mind Control]
Bonechewer Ravener - Should [Kidney Shot] - Shouldn't be immune to [Mind Control]
Bonechewer Ripper - Should enrage at the start of combat - 

- Reproduce

Step 1. Go to Hellfire Ramparts
Step 2. Face-pull mobs and watch them do nothing but melee you
Step 3. Use a priest to [Mind Control] the mobs and see mobs that should be immune aren't and some that aren't supposed to be immune are.
Step 4. Use Destroyer's #2 ability to spam mass damage on monsters quickly.

- Screenshot
![serverinfo](https://user-images.githubusercontent.com/48640427/54526176-e45a0300-49c5-11e9-8eda-0c8a09ba6dfd.jpg)

- Source https://wowwiki.fandom.com/wiki/Hellfire_Ramparts

**Comment by kelno** [comment]
DB was corrupted for some reason, their AI is now restore.
I didn't check the immunities yet.

**Comment by Arissarlia** [comment]
> DB was corrupted for some reason, their AI is now restore.
> I didn't check the immunities yet.

Just went and had a look at the fix after database restore, looks like the caster mobs are running while casting while trying to LOS them - Scryer & Darkcaster

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in one of the dungeon rework commits.
