### ISSUE TITLE
Fenthwick - rogue trainer in IF no interaction

### ISSUE THREAD

**Issue by Stryker68** [SunstriderEmu/BugTracker#794]
**Description:**

Can not interact with one rogue trainer in Ironforge

**Current behaviour:**

Dialogue in text window says "Can't help ya Spike. I only train rogues." On one trainer I can not interact at all. Can not click "train me" or reset talents. The other trainer has the same dialogue in the text window but I can interact.

**Expected behaviour:**

Dialogue should be different for rogues interacting with rogue trainers. Should be able to interact with them as well.

**Steps to reproduce the problem:**

https://www.wowhead.com/npc=5167/fenthwick#outfit

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:**

**Comment by kelno** [comment]
The following rogue trainers are affected:
3328
4163
4583
5167
13283

They all use the script: "npc_rogue_trainer" which expect some very specific ids.
Use 5165 for reference.
