### ISSUE TITLE
DM North Gordok Courtyard Door

### ISSUE THREAD

**Issue by Azytheoneandonly** [SunstriderEmu/BugTracker#796]
**Description:**

The Gordok Courtyard Door Has no way to interact with it.
![image](https://user-images.githubusercontent.com/37324574/54643811-88859c00-4ae3-11e9-9943-e3585ba790e0.png)

I would suggest checking the other door further in as well while you are at it.

**Current behaviour:**

Unable to Interact with Courtyard Door
http://db.hellfire-tbc.com/?object=177219
**Expected behaviour:**

Loot Chest near Fengus and open door. 

**Steps to reproduce the problem:**

1. DM north run. loot chest.
2. Not be able to open door and watch as Qoth makes fun of you as he blinks through it on his mage.

**rev. hash/commit:** 

![Screen Shot 03-20-19 at 07 36 AM](https://user-images.githubusercontent.com/37324574/54644228-a3a4db80-4ae4-11e9-80e2-41584a7c8f3f.JPG)

**Comment by beraus** [comment]
Jerry fix me close
