### ISSUE TITLE
Dire Maul Torches to Unlock Doors

### ISSUE THREAD

**Issue by Azytheoneandonly** [SunstriderEmu/BugTracker#797]
**Description:**

Dire maul has torches that act as hidden triggers to open doors from the inside.
Currently they don't work.

**Current behaviour:**

The Torches that normally open the doors are currently broken and do not work.
![image](https://user-images.githubusercontent.com/37324574/54644983-7c4f0e00-4ae6-11e9-906d-3259269cad62.png)

**Expected behaviour:**

To open the door when used.

**Steps to reproduce the problem:**

1. Click torch.
2. Hope you have the key else you are stuck or die and zone into east

**rev. hash/commit:** 
![Screen Shot 03-20-19 at 07 36 AM](https://user-images.githubusercontent.com/37324574/54645465-d6040800-4ae7-11e9-965c-405fae6b97e7.JPG)

**Comment by Nolin7777** [comment]
Torch gobject ID: 179510
Door gobject ID: 177192

**Comment by z5n** [comment]
thanks, fixed with next restart
