### ISSUE TITLE
Gnomish Death Ray broken

### ISSUE THREAD

**Issue by emorelix** [SunstriderEmu/BugTracker#799]
**Description:**

Gnomish death ray doesn't do dmg

**Current behaviour:**

Gnomish death-ray trinket works normally when you pop it. Builds up the channel and removes hp, then at the end nothing happens, no dmg, no lightning animation, nothing.

**Expected behaviour:**

It should channel and then do a burst of lightning and dmg the target when the channeling ends, but it doesn't.

**Steps to reproduce the problem:**

CHANGEME
1. Gnomish deathray equipped
2. activate it on a hostile target
3. channelling begins and removes hp with each tick
4. nothing.

**Comment by Kaziner** [comment]
Please include item ID and version number

**Comment by emorelix** [comment]
https://classicdb.ch/?item=10645 is this what you need? i cant find any more info online for it

**Comment by emorelix** [comment]
https://vanillawowdb.com/?spell=13278 too is the channeled spell

**Comment by kakarotkaruma** [comment]
Have had this same issue, Gnomish Death Ray (Item ID:10645) does not have any effect, should be spell ID: 12759

**Comment by hashblaster** [comment]
March 22nd 2020 still not working.

**Comment by Frencich** [comment]
May 24th, still nothing

**Comment by z5n** [comment]
issue has since been fixed
