### ISSUE TITLE
[DM:E] 0.5 Boss Issue

### ISSUE THREAD

**Issue by Azytheoneandonly** [SunstriderEmu/BugTracker#800]
**Description:**
0.5 Boss is up without summoning
Empyrean hits harder than it should.

**Current behaviour:**

0.5 Boss is up without summoning & Isalien spawns the hippogryph everytime it is engaged which didn't despawn. (ended up despawning after i ran back)
![image](https://user-images.githubusercontent.com/37324574/54647071-ef5b8300-4aec-11e9-95bf-fe21f3902e51.png)

Empyrean hits like a bloody truck (0.5 boss' pet)
![image](https://user-images.githubusercontent.com/37324574/54648428-f042e380-4af1-11e9-964e-1243ab1e9ff3.png)

**Expected behaviour:**

0.5 boss Isalien should only spawn when summoned.
her pet should only be able to spawn once. so a check if one exists
Reduced melee damage done by Empyrean.

**Steps to reproduce the problem:**

1. Zone into Dire Maul East run to last boss
2. kill summoned boss cause its up! just watch out for the dmg from her pet!
 http://db.hellfire-tbc.com/?npc=16097
 http://db.hellfire-tbc.com/?npc=16098

**rev. hash/commit:** 
![Screen Shot 03-20-19 at 09 25 AM](https://user-images.githubusercontent.com/37324574/54651908-867e0600-4b00-11e9-9922-559712bbbb1e.JPG)

**Comment by Nolin7777** [comment]
Please open just one ticket for one bug

**Comment by artieau** [comment]
This is the case for all 0.5 bosses in all dungeons currently @kelno

**Comment by kelno** [comment]
I must say I don't speak vanilla, I don't know what being 0.5 means

**Comment by Azytheoneandonly** [comment]
The 0.5 bosses are summon bosses for the dungeon set upgrade questline

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
