### ISSUE TITLE
Rare spawns not dropping any loot

### ISSUE THREAD

**Issue by kakarotkaruma** [SunstriderEmu/BugTracker#805]
**Description:**

Rare spawns in Silithus (possibly all rare-spawns, currently untested) not dropping any loot.

**Current behaviour:**

When you kill a rare spawn, there is nothing to loot from it.

**Expected behaviour:**
It is expected that rare spawns have a high chance to drop uncommon loot.

**Steps to reproduce the problem:**

CHANGEME

The loot dropped from rare mobs is unique and locates almost exclusively within the uncommon table. There may be some kind of error linking the spawn to the loot table.
 
CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by kelno** [comment]
I need some specific creatures here

**Comment by artieau** [comment]
Example @kelno 
Fenros - NPC ID # 507
![image](https://user-images.githubusercontent.com/40563134/56430680-72e5db00-630a-11e9-9221-ed2af1320b31.png)

**Comment by Jerrythemagicdog** [comment]
Fixed with the loot rework some time ago.
