### ISSUE TITLE
Group looting issues when party members aren't in proximity

### ISSUE THREAD

**Issue by kakarotkaruma** [SunstriderEmu/BugTracker#806]
**Description:**

When in a party with other players who aren't in the same zone or area as yourself, uncommon loot or higher is not automatically looted to the player who killed the corresponding mob. Instead a "this item is still being rolled for" error appears and does not disappear. 

**Current behaviour:**
Loot is not automatically distributed to the player who killed a mob, even when party members are in different zones or on different continents.

**Expected behaviour:**

When party members are not sharing the same zone, loot of uncommon quality or higher should auto-loot to the player who kills the corresponding mob.

**Steps to reproduce the problem:**

CHANGEME
1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead-like page.  
2. Step 2
3. Step 3

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in "5469846a189759da792f1f7fbe825b26dd5431ff" (core)
