### ISSUE TITLE
Dire Maul East: Door Event Missing

### ISSUE THREAD

**Issue by Azytheoneandonly** [SunstriderEmu/BugTracker#809]
**Description:**

Door to last boss is Missing.

**Current behaviour:**

Can Skip Whole Instance and do last boss as door is missing.

**Expected behaviour:**

Door should be closed in main room and you need to kill the satyr boss to talk to the tree npc who breaks down the door!

**Steps to reproduce the problem:**
1. Zone in drop down to check out door is missing.

https://youtu.be/rkcBX_Hn7R0?t=17 - Shows the Door being intact During TBC
**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/37324574/54714089-e5448d80-4b9b-11e9-806f-7aec6d472093.png)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
