### ISSUE TITLE
Corpse revival / ghost form

### ISSUE THREAD

**Issue by emorelix** [SunstriderEmu/BugTracker#810]
**Description:**

I died to pvp in blackrock mountain. When i released, my ghost spawned at my body and i was able to rez up quickly.

**Current behaviour:**

I died to pvp in blackrock mountain, 3 times, and each time i released, i spawned as a ghost at my dead body. 

**Expected behaviour:**

I should have been teleported as a ghost to the nearest spirit healer.

**Steps to reproduce the problem:**

1. Be killed by pvp in blackrock mountain (unsure if this is pvp only, or effect pve deaths too)
2. Release from corpse
3.you are now a ghost, at your body.

**Comment by kelno** [comment]
Needs a proper location here. A screenshot of it is fine.

**Comment by artieau** [comment]
Confirmed this happens
![image](https://user-images.githubusercontent.com/40563134/55157082-a7ed8a80-51af-11e9-8251-48cbad6c2c4d.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
