### ISSUE TITLE
[Quest] Players can see and accept all ZG Island reputation quests

### ISSUE THREAD

**Issue by plutonium447** [SunstriderEmu/BugTracker#811]
**Description:**
Paladins can accept warrior quests on zg island

**Current behaviour:**
Paladins can accept all the warrior quests on zg island.

![Screenshot from 2019-03-21 07-21-24](https://user-images.githubusercontent.com/40911527/54720225-a79b3100-4baa-11e9-8fd4-ffa0dcf68436.png)

**Expected behaviour:**
Paladins should not be able to see or accept any of the warrior quests

**Steps to reproduce the problem:**
1. Be a paladin
2. Go to ZG island @ 15.3,14.5 in STV
3. Talk to Jin'rokh the Breaker

**rev. hash/commit:** 
**rev. 10710**

[npc] Jin'rokh the Breaker (14902)

**Comment by plutonium447** [comment]
**Update**
Players appear to be able to see and accept *all* class reputation quests on ZG Island

![Screenshot from 2019-03-21 07-29-45](https://user-images.githubusercontent.com/40911527/54720499-4f186380-4bab-11e9-9587-de02b6e2324e.png)
![Screenshot from 2019-03-21 07-29-57](https://user-images.githubusercontent.com/40911527/54720504-50e22700-4bab-11e9-8805-d099a807ed5c.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed by Sheik.
