### ISSUE TITLE
Dire Maul East: No Patrols

### ISSUE THREAD

**Issue by Azytheoneandonly** [SunstriderEmu/BugTracker#813]
**Description:**
The Warpwood Guardian are not patrolling as they should be.

**Current behaviour:**

Warpwood Guardian are standing still.

**Expected behaviour:**

Warpwood Guardian groups should patrol around the room.

**Steps to reproduce the problem:**

1. Zone into DM:East and check out the main room.

http://db.hellfire-tbc.com/?npc=11461

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/37324574/54725912-82afb980-4bbc-11e9-8c3f-7c54c62f2068.png)

**Comment by z5n** [comment]
fixed with next update!
