### ISSUE TITLE
Midsummer Fire Festival incorrectly active

### ISSUE THREAD

**Issue by Cheelout** [SunstriderEmu/BugTracker#831]
**Description:**

Midsummer Fire Festival is active when it should not be

**Current behaviour:**

https://wowwiki.fandom.com/wiki/Midsummer_Fire_Festival is currently active, or atleast giving out the following buff in major city's https://www.wowhead.com/spell=29235/fire-festival-fortitude

**Expected behaviour:**

As per the article Occurs June 21st - July 5th, 2019.

**Steps to reproduce the problem:**

1. Stand in major city to receive buff (Which is also hidden)

![image](https://user-images.githubusercontent.com/38281939/54821211-9f034180-4cf5-11e9-8bb4-369ea85b80c2.png)

**Comment by kelno** [comment]
Fixed since

**Comment by kelno** [comment]
Sorry it's still in the works :)

**Comment by TheMoneyHater** [comment]
It was activated but then out of nowhere it was removed. All the raiders are waiting for the buffs from it.
