### ISSUE TITLE
Hunter Quest bug

### ISSUE THREAD

**Issue by mrqiksta** [SunstriderEmu/BugTracker#837]
**Description:**

Hunter quests bugged - tamed creatures not despawning on hand-in or following player

**Current behaviour:**
QuestID:
(pre-requisite quest id is 6068)
6062
6083
6082

Observed:
- Minion does not despawn upon hand-in, player cannot complete next part of quest without logging out and in as they do not have abandon/dismiss pet abilities yet, and the minion from previous quest is occupying this slot.
- Minion does not set follow on player and stays where it was tamed.

**Expected behaviour:**

Expected:

The "Taming the beast" 3-step quests require player to tame a specific type of beast. When tamed, the beast changes into a minion and sets follow on the player. 
Upon hand-in of the quest the beast despawns, freeing up the slot to tame another minion in the next step.

**Steps to reproduce the problem:**
(complete pre-quest 6068 to obtain this quest)
1. Accept quest
2. Tame a beast using item provided. Attn: Beast will not follow you, but this is not a game-breaking issue.
3. Hand in and accept next quest
4. Try taming the beast they ask you, you cannot, receiving an error indicating that you already have a tamed beast.

Workaround: Player can log out and in and the previous tamed minion will have despawned, allowing player to tame the new beast and complete quest objective.

![bug](https://user-images.githubusercontent.com/46828437/54860512-e5df4e80-4d6a-11e9-8e1e-fce3f670cb98.JPG)

**rev. hash/commit:** 

Attached.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
