### ISSUE TITLE
[npc] Whip Lasher Lash of Pain being casted in front of players

### ISSUE THREAD

**Issue by plutonium447** [SunstriderEmu/BugTracker#841]
**Description:**
Whip Lasher mobs are able to cast their [Lash of Pain] ability while not behind their target, as required by the conditions of the spell.

**Current behaviour:**
Whip Lasher mobs can cast [Lash of Pain] on players while in front of the player.

![Screenshot from 2019-03-23 16-02-51](https://user-images.githubusercontent.com/40911527/54862379-a114e100-4d85-11e9-9adc-02ac311b9353.png)

![Screenshot from 2019-03-23 16-07-48](https://user-images.githubusercontent.com/40911527/54862419-2c8e7200-4d86-11e9-9593-a574f9f4437c.png)

**Expected behaviour:**
Whip Lasher mobs should not be able to cast [Lash of Pain] on players unless they are behind the player

**Steps to reproduce the problem:**

1. Go to DM:E
2. Find a pack of Whip Lasher mobs
3. Start combat
4. Remain in front of the mobs
5. notice that the mobs are casting [Lash of Pain] on you

**rev. hash/commit:** 
**rev. 10718**

**id's**
[npc] Whip Lasher (13022)
[spell] Lash of Pain (21987)

http://db.hellfire-tbc.com/?spell=21987
https://db.excalibur.ws/?spell=21987
https://classicdb.ch/?spell=21987

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
