### ISSUE TITLE
Custom emotes can be seen cross faction

### ISSUE THREAD

**Issue by Desparto** [SunstriderEmu/BugTracker#842]
**Description:**

Custom made emotes (e.g. /e xxxxxxx) can be read by the opposite faction, essentially allowing people to talk cross faction, this shouldn't occur. Any blizzard emotes should be able to be read cross faction, but custom made emotes should show as "<character name> makes strange gestures" to the opposite faction.

**Current behaviour:**

Custom emotes can be read by the opposite faction, allowing people to speak cross faction

**Expected behaviour:**

Custom emotes should display as xxxx makes strange gestures to anyone on the opposite faction.

**Steps to reproduce the problem:**

CHANGEME
1. Have a toon create a custom emote
2. Have a toon of the opposite faction within range
3. Read the emote written

**rev. hash/commit:** rev 10718

**Comment by plutonium447** [comment]
**example**
"Mesohorny" is a horde player. My character is alliance.
![Screenshot from 2019-03-23 21-17-36](https://user-images.githubusercontent.com/40911527/54865411-1f3aad00-4db1-11e9-8bca-65c564734430.png)

**Comment by kelno** [comment]
Fixed
