### ISSUE TITLE
Enchanting Trade Cast Time

### ISSUE THREAD

**Issue by Azytheoneandonly** [SunstriderEmu/BugTracker#843]
**Description:**

Enchants done in the trade window have a cast time

**Current behaviour:**

Currently when you do an enchant on someones item in a trade it does a cast.
This could be abused to get enchants off someone without paying them if they are supplying the mats.
Demo here - https://streamable.com/jinhs
Tested it two times.

**Expected behaviour:**

When you apply the enchant to item it should only cast when the trade is completed.

**Steps to reproduce the problem:**

1. Trade enchanter and get an item enchanted.
2. Enchant is applied with cast time instead of at end of trade.

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/37324574/54863764-72543600-4d98-11e9-9f09-8876d4420cb9.png)

**Comment by kelno** [comment]
Do you have a video of that behavior? 
Was that working on the previous vanilla core?

**Comment by artieau** [comment]
Yes @kelno

**Comment by kelno** [comment]
Fixed!
