### ISSUE TITLE
Easter Eggs in Goldshire

### ISSUE THREAD

**Issue by nyamyy** [SunstriderEmu/BugTracker#844]
**Description:**
Eggs from the retail Easter event are spawning in Goldshire.

**Current behaviour:**
The Easter eggs spawn and de-spawn after looting. Only sometimes do they give loot. There are no event NPCs that I could find.

**Expected behaviour:**
There shouldn't be eggs.

**Steps to reproduce the problem:**
1. Go to Goldshire
2. Find the eggs in the bushes, behind posts, etc.
3. Click and loot them, they'll either give you event items (chocolates, elegant dress, etc) or nothing.
4. It'll de-spawn and spawn somewhere else in Goldshire

**rev. hash/commit:** 
Sunstrider rev. 10718 (7f942c34c69d) 2019-03-22 14:51:21 +0100 (master branch) (Unix. RelWithDebInfo, Static)
![WoWScrnShot_032319_190751](https://user-images.githubusercontent.com/48854560/54864262-a2073c00-4da0-11e9-8f81-c29259af6db6.jpg)
![WoWScrnShot_032319_191253](https://user-images.githubusercontent.com/48854560/54864272-bd724700-4da0-11e9-932f-3a11b13c39f7.jpg)

**Comment by plutonium447** [comment]
easter egg id for elwynn forest: 113769

**Comment by kelno** [comment]
Fixed
