### ISSUE TITLE
Warlock Voidwalker pet does not move when ordered to attack

### ISSUE THREAD

**Issue by MELVINDEW** [SunstriderEmu/BugTracker#854]
Yes

**Description:**

When Voidwalker pet is ordered to attack he becomes aggressive but does not move to attack. 

![Lockee- serverinfo](https://user-images.githubusercontent.com/48870334/54872967-f94cf100-4e20-11e9-8f64-ac21ff028750.JPG)

 

**Current behaviour:**
If toon initiates attack the Voidwalker will stand still unless the target moves within range but still doesn't move from the spot from when you requested the attack. To start the Voidwalker moving you need to hit the follow order for it to move but this also breaks the attack. 

CHANGEME Tell us what happens.

**Expected behaviour:**
Voidwalker should move to engage when ordered to attack

Voidwalker stands stationary but does become aggressive so target will get attacked but must move withing the rage of the now stationary Voidwalker

**Steps to reproduce the problem:**
happen consistently - everytime

attached screen shot
[LOCKEE pet issue.zip](https://github.com/thebarrensissues/Issues/files/2999886/LOCKEE.pet.issue.zip)

**Comment by kelno** [comment]
Working now
