### ISSUE TITLE
Lockboxes and dungeon chests = no loot 

### ISSUE THREAD

**Issue by emorelix** [SunstriderEmu/BugTracker#860]
**Description:**

Any chests inside dungeons and lockboxes to be opened by rogues appear to have no loot and "fizzle" when opened. (This does not apply to junkboxes.)

**Current behaviour:**

When opening a lockbox in your inventory as a rogue (lockpicking) the item then has no loot when you loot it and the item disappears from inventory.
When opening a chest in a dungeon, it says "fizzled" and no loot appears. (Chests in dungeons dont appear locked either.)

**Expected behaviour:**

Chests and lockboxes should have loot in them.

**Steps to reproduce the problem:**

Dungeon chest:
1. Find chest
2. Open chest (not locked)
3. Chest opens and then closes as an error message saying "fizzled" appears in red.
3. Chest resets and remains unlocked.

Lockbox:

1. Unlock lockbox in inventory.
2. Open lockbox.
3. No loot appears and lockbox is removed from inventory.

**rev. hash/commit:** 

item=5759 - thorium lockbox tested

object=153469 - large mithrilboundchest tested

![WoWScrnShot_032419_173032](https://user-images.githubusercontent.com/47015256/54876785-c4b15780-4e69-11e9-8159-20046908fd82.jpg)

**Comment by Azytheoneandonly** [comment]
Just opened 4 Mithril Lockboxes and had 2 be empty
![image](https://user-images.githubusercontent.com/37324574/54969872-b1b69880-4fcb-11e9-9acf-f6b375491d22.png)

**Comment by emorelix** [comment]
Also effecting outland chests and junkboxes (item=29569)

**Comment by emorelix** [comment]
Rev 10800

**Comment by Tamosheik** [comment]
From a database perspective, this appears to be two separate issues.
Loot from chests is found in gameobject_loot_template
Loot from lockboxes is found in item_loot_template

Upon investigation of Lockboxes
![image](https://user-images.githubusercontent.com/40758487/56850881-d3e56280-694b-11e9-959e-66e478f7518f.png)

**Comment by Tamosheik** [comment]
Further to this, the game seems to be selecting loot based on explicit "chance", rather than "group" field

**Comment by Azibeel** [comment]
Had this happen today with a Khorium Lockbox. Picked it and when the loot box came up it was empty.

**Comment by Jerrythemagicdog** [comment]
Appears to be fixed with the loot rework some months ago.
1. 5760 has 94 items now in the db (item_loot_template)
2. Junkboxes (29569) also have loot
3. Khorium Lockbox (31952) also has loot
4. Chests in dungeons also have loot
