### ISSUE TITLE
[Paladin] Divine Shield is not always preventing some CC spells

### ISSUE THREAD

**Issue by pewpewlaserz** [SunstriderEmu/BugTracker#875]
**Description:**

Divine Shield makes you immune to all damage and spells, including environmental.

**Current behaviour:**

If you use Divine Shield and walk into lava you take damage.

**Expected behaviour:**

If you use Divine Shield and walk into lava you should not take damage.

**Steps to reproduce the problem:**

1. Use Divine Shield
2. Walk into lava

![image](https://user-images.githubusercontent.com/48882366/54898222-22e84400-4f17-11e9-833d-c56faab19785.png)

**rev. hash/commit:**

**Comment by pewpewlaserz** [comment]
![image](https://user-images.githubusercontent.com/48882366/54915262-791eac80-4f42-11e9-9040-c299b4c53f62.png)
In BGs occasionally spells are going through divine shield, mostly CC based ones. Its hard to reproduce reliably, idk if its about having started the cast prior to divine shield but i havent had a damaging ability go through it.

**Comment by kelno** [comment]
The original issue is fixed with 11519.
I can't seem to reproduce that second issue with seduce. Any other spells it happens with?

**Comment by kelno** [comment]
Closed until news of this
