### ISSUE TITLE
[NPC] Connor Rivers <Apprentive Chef>

### ISSUE THREAD

**Issue by pewpewlaserz** [SunstriderEmu/BugTracker#877]
**Description:**

Connor Rivers (ID 5081) can't be interacted with.

**Current behaviour:**

Connor Rivers (ID 5081) can't be interacted with. Stormwind Location 40.8, 92.3

**Expected behaviour:**

You should be able to interact with him as a cooking trainer, additionally he should have a quest available (Quest ID 1301) James Hyal (lvl req 30).

**Steps to reproduce the problem:**

1. Attempt to interact with him in Stormwind.
![image](https://user-images.githubusercontent.com/48882366/54899707-698c6d00-4f1c-11e9-896d-0fc805ccb5d5.png)

**Comment by Jerrythemagicdog** [comment]
Fixed
