### ISSUE TITLE
Incorrect Quest item effect

### ISSUE THREAD

**Issue by mrqiksta** [SunstriderEmu/BugTracker#883]
**Description:**
On-use Quest item http://db.hellfire-tbc.com/?item=23675 gives error "Can't Target players"
Quest: http://db.hellfire-tbc.com/?quest=9433

**Current behaviour:**

On-use Quest item http://db.hellfire-tbc.com/?item=23675 gives error "Can't Target players"
http://db.hellfire-tbc.com/?quest=9433

**Expected behaviour:**

on-use, the quest item should spawn a controllable unit for the player to operate.

**Steps to reproduce the problem:**

1. pick up quest http://db.hellfire-tbc.com/?quest=9433
2. use provided item while standing near game object http://db.hellfire-tbc.com/?object=181825
3. observe error

**rev. hash/commit:** 
Sunstrider rev. 10748 (4c8418973318) 2019-03-25 08:40:16 +0100 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed!
