### ISSUE TITLE
Lyceum door wont open

### ISSUE THREAD

**Issue by Calebizza** [SunstriderEmu/BugTracker#885]
**Description:**

Lyceum door won't open 

**Current behaviour:**

At the end of the Lyceum, lighting the two braziers does not open the door 

**Expected behaviour:**

Lighting these two braziers should open the door

**Steps to reproduce the problem:**

CHANGEME
- Reach end of lyceum
- Light both braziers
- get stuck

**rev. hash/commit:** 

![WoWScrnShot_032519_210717](https://user-images.githubusercontent.com/48810241/54911561-de729d80-4f42-11e9-8a0b-0b8bb38dbf46.jpg)

**Comment by Sheikthecatman** [comment]
Fixed 03/30/2020 in [b729d1e7ff605be92b0ecb06f91f070d2adce98d](https://github.com/kelno/sunstrider-scripts/commit/b729d1e7ff605be92b0ecb06f91f070d2adce98d)
