### ISSUE TITLE
Doom'Rel summoning incorrect mobs

### ISSUE THREAD

**Issue by Calebizza** [SunstriderEmu/BugTracker#886]
**Description:**

Doom'rel is currently spawning the wrong mobs

**Current behaviour:**

instead of casting summon voidwalker, Doom'Rel instead spawns 2 zombies

**Expected behaviour:**

Doom'Rel should summon voidwalkers

**Steps to reproduce the problem:**

-Fight Doom'rel in BRD

**rev. hash/commit:** 

![WoWScrnShot_032519_210717](https://user-images.githubusercontent.com/48810241/54912598-0c58e180-4f45-11e9-9750-7e3094f027d4.jpg)

**Comment by Sheikthecatman** [comment]
Thanks!
Fixed in [b568c703a492fbdc5fffaf4a73ad9a044a91dba9 ](https://github.com/kelno/sunstrider-scripts/commit/b568c703a492fbdc5fffaf4a73ad9a044a91dba9)
