### ISSUE TITLE
[Container/Object] Truesilver Deposit (ID 2047) showing Gold Gear to Interact

### ISSUE THREAD

**Issue by pewpewlaserz** [SunstriderEmu/BugTracker#890]
**Description:**

Truesilver Deposit is showing as intractable for non-miners - displaying a gold gear.

**Current behaviour:**

When mousing over the Truesilver Deposit (ID 2047) at 63.5, 10.9 it shows a golden gear, no further interaction is available.

**Expected behaviour:**

Should display a mining pick but be greyed out / showing it can't be interacted with as you don't have the required profession. Below is the tooltip that should be displayed along with a greyed out pick icon over the object when you mouse over it.

![image](https://user-images.githubusercontent.com/48882366/54964351-d9036a80-4fb7-11e9-8d61-439d43ab95db.png)

**Steps to reproduce the problem:**

1. Go to felwood 63.6, 10.9 and hover over Truesilver deposit in screenshot.
![image](https://user-images.githubusercontent.com/48882366/54964123-f6840480-4fb6-11e9-81b1-181b1a95dcd5.png)

I have disabled all mods/relogged and issue persists.

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/48882366/54964144-07cd1100-4fb7-11e9-8651-a08bfc86de73.png)

**Comment by kakarotkaruma** [comment]
Also seen this issue at the same location.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed
