### ISSUE TITLE
[NPC] Deadwood Avenger (ID 7157) Loc 63.1, 9.9 - unit flies up / is unattackable

### ISSUE THREAD

**Issue by pewpewlaserz** [SunstriderEmu/BugTracker#892]
**Description:**

When attacking the Deadwood Avenger (ID 7157) at loc 63.1, 9.9 in Felwood.

**Current behaviour:**

When attacking the Deadwood Avenger (ID 7157) at loc 63.1, 9.9 in Felwood your pet has issues pathing to it and will end up in the sky / the NPS will end up in the sky and will evade bug / if you go into melee you will be unable to attack it as it says you are out of range / your pet will be able to attack it.
NPC position and mine when attacking.
![image](https://user-images.githubusercontent.com/48882366/54966089-ec660400-4fbe-11e9-906b-f02545f6b302.png)
![image](https://user-images.githubusercontent.com/48882366/54966073-e2440580-4fbe-11e9-9e78-7d85f6ff3f8b.png)
![image](https://user-images.githubusercontent.com/48882366/54966108-f7b92f80-4fbe-11e9-8c7b-0c823cc4f1ec.png)

**Expected behaviour:**

You should be able to target the NPC and attack it without it going into the sky / without your pet / be able to melee attack it.

**Steps to reproduce the problem:**

1. Attack deadwood avenger at 63.1, 9.9
2. Using your pet observe it bug out trying to path to the NPS
3. Using ranged attacks observe being unable to attack it / evade bugging / not being in range - ranged instant attacks some times "fire" and damage.

**Comment by kelno** [comment]
Fixed since
