### ISSUE TITLE
[Hunter} Auto Shot (Spell ID 75) not being able to be turned on

### ISSUE THREAD

**Issue by pewpewlaserz** [SunstriderEmu/BugTracker#893]
**Description:**

When manually toggling auto shot (Spell ID 75) on/off it will get to a state where auto attack (melee) is stuck turned on and can not be turned off and you can not enable auto shot.

**Current behaviour:**

When manually toggling auto shot on/off it will get to a state where auto attack (melee) is stuck turned on and can not be turned off and you can not enable auto shot. You can still use instant ranged attacks but these do not toggle on auto shot as they then should. Additionally when taking "other" actions ie drinking you are still stuck in the melee attack stance.

Observe how auto attack is turned on, when pressing "1" for auto shot or manually clicking it, unable to turn it on.
![image](https://user-images.githubusercontent.com/48882366/54966341-af4e4180-4fbf-11e9-97d2-a5860ac0a24d.png)
Auto attack is still turned on / stuck when drinking, animation stays as auto attack.
![image](https://user-images.githubusercontent.com/48882366/54966390-df95e000-4fbf-11e9-94a3-ee632aa17188.png)

**Expected behaviour:**

You should be able to toggle auto shot on/off without issue and not be stuck in auto attack.

**Steps to reproduce the problem:**

1. Be a hunter
2. Target a mob and start auto shotting (Spell ID 75) it, toggle auto shot off/on and use instant ranged attacks
3. Observe it get stuck in auto attack, still be able to use instant ranged attacks ie Arcane Shot but be unable to toggle auto shot back on.
4. Observe Auto Attack be stuck on.

**Comment by Azytheoneandonly** [comment]
I have also observed this issue but had not worked out the cause yet. nice work!

**Comment by mrqiksta** [comment]
this happened to me once, and relogging resolved it. Haven't been able to reproduce it since.

**Comment by pewpewlaserz** [comment]
Oddly i havent had it replicate after playing for a few hours today after posting this, more testing is probably needed.

**Comment by Jerrythemagicdog** [comment]
Thanks for all the details here!

**Comment by pewpewlaserz** [comment]
So i've not had it happen as much the last few days - it seems to be linked to for me (to reliably reproduce it) trying to attack a bugged (evade/stuck) mob. After trying to shoot them / launching a few arcane shots and then moving onto another mob it gets "stuck". Because I knew which ones to leave alone, I'd stopped getting the issue.

**Comment by kelno** [comment]
Nice. Reliable reproduce steps would be very valuable here

**Comment by mrqiksta** [comment]
For what it's worth, the example i saw was as a troll hunter at low level with the human mobs in durotar around the castle.

**Comment by Jerrythemagicdog** [comment]
Tested now, can't reproduce and haven't heard about it from anyone.
Possibly fixed with "77c71a3f9a830b2e38aa34bfaecaa9780754fdcc"
