### ISSUE TITLE
[Quest] Investigate the Blue Recluse

### ISSUE THREAD

**Issue by nuclearsheep540** [SunstriderEmu/BugTracker#896]
**Description:**
Investigate the Blue Recluse is a low level Mage Class quest which requires you to use 2 quest items to, A; summon quest mobs, B; capture quest mobs. Neither items appear to be working correctly.

**Current behaviour:**
1. The Mana Rift at the Blue Recluse Inn isn't detectable by the quest item 'Chest of Containment Coffers'
2. Quest item 'Cantation of Manifestation' is able to spawn as many Rift Spawns without limit
3. Unable to Subdue Rift Spawns, possibly because of issue 1.

**Expected behaviour:**
1. 'Cantation of Manifestation' probably should have a limit to how many times can be used (to prevent accidental over-spawning)
2. 'Chest of Containment Coffers' should detect the Rift inside the Blue Recluse
3. Rift Spawns should be subdued, not killed (?) - I presume this is meant to occur once you take them to a certain level of health?
4. Subdued Rift Spawns should be enabled for capture with 'Chest of Containment Coffers'

**Steps to reproduce the problem:**

1. Collect the 'Investigate the Blue Recluse' quest from NPC "Jennea Cannon" at the top of the Mage Tower.
2. Collect quest items behind "Jennea Cannon" before departing Mage Tower for Blue Recluse Inn
3. Enter the main room of the Blue Recluse, and use quest item "Cantation of Manifestation" near the blue Rift. 
4. Defeat a Rift Spawn. 
5. No subdued state to use

**rev. hash/commit:** 
![WoWScrnShot_032619_055856](https://user-images.githubusercontent.com/37055772/54974612-82cd0200-4f8c-11e9-983d-3177f91b0ddb.jpg)
![WoWScrnShot_032619_055839](https://user-images.githubusercontent.com/37055772/54974623-89f41000-4f8c-11e9-9ffb-fd960d5d6434.jpg)

**Comment by Tamosheik** [comment]
Quest ID #1920

**Comment by Sheikthecatman** [comment]
Testfix is live [See my comment](https://github.com/SunstriderEmu/BugTracker/issues/1907#issuecomment-598924715)
