### ISSUE TITLE
Quest 'Protect Kanati Greycloud' completes without action, and NPC then despawns

### ISSUE THREAD

**Issue by dylbarrenstbc** [SunstriderEmu/BugTracker#897]
**Description:**

The quest 'Protect Kanati Greycloud' (Quest: 4966) completes 1 - 2 seconds after it is accepted, instead of starting an event.

**Current behaviour:**

After accepting the quest, 1 hostile mob spawns outside of aggro distance, then the NPC (Kanati Greycloud, NPC: 10638) despawns. The quest is then marked as complete. 

**Expected behaviour:**

This is from memory, but I believe 3 x hostile mobs should spawn (I believe Galak Assassin, NPC: 10720), engage the NPC, and if all 3 are defeated before Kanati Greycloud dies, the quest is marked complete.

**Steps to reproduce the problem:**

1. Kill NPC 'Galak Messenger' (NPC: 10617)
2. Loot item 'Assassination Note' (Item: 12564)
3. Accept quest 'Assassination Plot' (Quest: 4881) from item
4. Turn in quest 'Assassination Plot' to Kanati Greycloud (NPC: 10638)
5. Accept quest 'Protect Kanati Greycloud' (Quest: 4966)

Note: several minutes after despawning, the NPC Kanati Greycloud respawns, and the quest is able to be turned in successfully. 

**rev. hash/commit:** 

Sunstrider rev. 10755 (934026d00f9c) 2019-03-25 17:48:34 +0100 (master branch) (Unix, RelWithDebInfo, Static)

Love, 
Shapey

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed some time ago in "21d203db3bf3938dcc8bf3fb57b5af6dcfc6545b"
