### ISSUE TITLE
Spell - Shadowguard

### ISSUE THREAD

**Issue by imtrollingu** [SunstriderEmu/BugTracker#900]
**Description:**

Shadowguard doesn't discharge when Powerword shield is active. http://db.hellfire-tbc.com/?spell=19312

**Current behaviour:**

Shadowguard doesn't discharge on spell, melee or ranged hit when Powerword shield is active. This has worked on every server I have played on including the Barrens and Nostralia.

**Expected behaviour:**

Shadowguard orbs should do damage to the attacker if their attack hits. Even though Powerword Shield absorbs the damage is still a hit.

**Steps to reproduce the problem:**

1. I have had people attack me in PvP and while Powerword Shield holds no discharges happen. Also this was the case in PVE mobs. It will work if a mob casts a none damaging spell on you ie debuff.

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by imtrollingu** [comment]
Seems to work sometimes on some mobs but not others, the mobs it is working on tend to trigger the discharge rather late as oppose to the first damage attack. Like Lightning shield it will take about 2 hits until another discharge happens.

**Comment by imtrollingu** [comment]
Ok I have tested it on Fireflys in Zangamarsh that have a melee attack and cast a spell. On melee attacks nothing happens on spell cast it works as intended straightaway.

**Comment by kelno** [comment]
Should be fixed with https://github.com/kelno/sunstrider/commit/461f5a5b2a224987cd0f3fd59765be66fd1cf389
