### ISSUE TITLE
Songflower

### ISSUE THREAD

**Issue by zsavicreative** [SunstriderEmu/BugTracker#901]
**Description:**

Songflower buff isnt popping off cleansed songflowers

**Current behaviour:**

Upon handing in cenarion plant salve at a corrupted songflower it cleanses the flower, however upon clicking the cleansed no buff is given.

**Expected behaviour:**

Upon handing in cenarion plant salve at a corrupted songflower it cleanses the flower, upon clicking the cleansed one should receive songflower buff.

**Steps to reproduce the problem:**

1. Step 1 - go to Maybess Riverbreeze and retrieve a [cenarion plant salve]x2(horde)
2. Step 2 - go to corrupted songflower
3. Step 3 - hand in cenarion plant salve to corrupted songflower
3. Step 4 - once songflower is cleansed click cleansed songflower - at this point you should receive a buff.

![image](https://user-images.githubusercontent.com/17961871/54999332-1c93be00-5024-11e9-9b1b-032dc107699a.png)

**Comment by Sheikthecatman** [comment]
Thanks!
Fixed in 09b9f62193a2c16659ffe32ca44dcfe8a5462577 (scripts)
