### ISSUE TITLE
[Warlock] Quest: The Completed Orb of Dar'Orahil Broken

### ISSUE THREAD

**Issue by Azytheoneandonly** [SunstriderEmu/BugTracker#903]
**Description:**

Quest The Completed Orb of Dar'Orahil Fails to do anything and can't be handed in.

**Current behaviour:**

Quest The Completed Orb of Dar'Orahil Fails to do anything and can't be handed in.
Demo: https://streamable.com/qcnfr

**Expected behaviour:**

Quest should complete after picking it up.

**Steps to reproduce the problem:**

1. Pick up quest after doing chain. 
2. Unable to complete quest as it doesn't do anything.

Quest: http://db.hellfire-tbc.com/?quest=4964

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/37324574/55006570-ae51fa00-5029-11e9-9859-91c287898439.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed!
