### ISSUE TITLE
Bonereaver's edge proc rate

### ISSUE THREAD

**Issue by qoth** [SunstriderEmu/BugTracker#905]
**Description:**

Bonereaver's Edge [17076] is currently a very low proc rate

**Current behaviour:**

Debuff is appearing on the wielder which is correct, however the rate is very low and never gets to 3 stacks.

**Expected behaviour:**

Debuff should be able to stack up to 3 times and should be quite easily kept up _near_ 100% uptime with spamming a no cooldown instant attack.

**Steps to reproduce the problem:**

CHANGEME
1. Equip Bonereaver's Edge
2. Fight a target
3. Proc rate will be almost non-existent and never go past two stacks

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/35262513/55052268-3840a800-50a8-11e9-843f-4851449f9e44.png)

**Comment by qoth** [comment]
https://drive.google.com/file/d/0B0K52-VEkRDTeWI3U3V2LTVVYUk/view

Full list of proc rates used by Lightbringer and Kronos. Closest to a source I can find. Has BRE at 17% proc rate. 

Currently it appears BRE is set at 1ppm which is far too low.

**Comment by Jerrythemagicdog** [comment]
Fixed in 10766

**Comment by qoth** [comment]
![image](https://user-images.githubusercontent.com/35262513/55205237-f176bd80-5221-11e9-9d61-7dd411e190eb.png)

Does not appear to be fixed with most recent update.

**Comment by Jerrythemagicdog** [comment]
It's set to 17%, which is using the Kronos and Lightbringer data. The Classic data though points to an 11% chance.
