### ISSUE TITLE
Quest: The Hunt Completed (The Ashenvale hunt)

### ISSUE THREAD

**Issue by Oomiosi** [SunstriderEmu/BugTracker#915]
Description:

Able to hand in Ashenvale quest "The Hunt Completed" without completing requirements or taking any quest.
http://db.hellfire-tbc.com/?quest=247 (The Hunt Completed - handing in only)

Associated Quests:
Sharptalon's Claw - http://db.hellfire-tbc.com/?item=16305
Ursangous's Paw - http://db.hellfire-tbc.com/?item=16303
Shadumbra's Head - http://db.hellfire-tbc.com/?item=16304

http://db.hellfire-tbc.com/?quest=6383 (The Ashenvale Hunt - The prequest, not required for completion. Included here just in case.)

Current behaviour:

With no requirements for the quest met or associated quests done.
Interact with Senani Thunderheart at Splintertree Post in Ashenvale.
Click on quest.
Click complete quest.
Quest hands in with reward given.

Expected behaviour:

Quest should not be able to be completed without the three associated quests completed.

Steps to reproduce the problem: Speak to Senani Thunderheart in Ashenvale on any character without any prerequisites and complete quest.

Partially completing the prerequisite quests has NOT been tested.
Tested on a 29 Tauren Druid and 60 Undead Warlock on seperate accounts.

rev. hash/commit:
![AshenValeHunt](https://user-images.githubusercontent.com/11486346/55126376-c8d8c000-515c-11e9-856c-8b7ae3337651.png)

Sunstrider rev. 10770 (0032f2c637e0+) 2019-03-27 04:01:45 +0100 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
