### ISSUE TITLE
[BG] Disproportionate Games Caused by Group Queueing

### ISSUE THREAD

**Issue by zemfi** [SunstriderEmu/BugTracker#918]
This is more a server/core issue

**Description:**

Currently if a group (x amount) of players on either faction queue for a BG, and a new room opens, when the required amount of players on both sides are met, it often pulls in the entire group of players, instead of matching them, causing vary-ing disproportionate games where one side (the side that grouped) has more players than the other.

**Current behaviour:**

As above, anyone queueing for a bg on both sides, when the conditions are met (the minimum amount of players required to open/pop a BG), it pops the BG, but if one or more are grouped, it seems to bring in all the group, (not matching the amount of players), causing an unbalanced game.

**Expected behaviour:**

Explained more in-depth below, but the queueing system should match the amount of players on both sides queueing, and also the amount in the group.

**More Info:**

**Scenario 1 (current):**
On other servers and on the previous core, if individuals queue and say it requires 6 players from both sides to open a room, it opens.
[ 6 individuals/solo horde+ally = open bg room 6v6 ]

**Scenario 2 (current):**
If one of those players or more are queueing and in a group, say 1 horde that is 3rd in line, queuein as a group of 5, then the other side needs to match not only 6, but an extra 4 due to the group. This is not happening currently.
[6 individual ally, 5 individal horde+1 in a group with 4 others = open bg room 6v10 ]

**Scenario 3 (what should happen):**
Game doesnt open til those 4 extras are matched by ally, making a 10v10 or the group de-ques.

![wsg_barrents](https://user-images.githubusercontent.com/46832429/55154876-03b51500-51aa-11e9-9ce1-10beed1ae337.jpg)
^ Quick example of a game that had all those players from start, and only lasted under 10mins.

**rev. hash/commit:** 
 rev. 10770

**Comment by Cheelout** [comment]
Devs I dont think group queue has anything to do with it as we have seen the same outcome sithout group queueing. I believe all spots in the BG are opening up once the game pops.

**Comment by kelno** [comment]
Yes on that last comment

**Comment by Cheelout** [comment]
@kelno Still a big issue atm for BG's

**Comment by kelno** [comment]
We don't plan to implement for now
