### ISSUE TITLE
Scepter of Celebras quest

### ISSUE THREAD

**Issue by Calmafud** [SunstriderEmu/BugTracker#923]
**Description:**

Scepter of Celebras bugged

**Current behaviour:**

Celebras walks up to the stone to create the scepter then does a small amount of RP, 
stops saying anything and sits there channeling infinitely.

**Expected behaviour:**

Should create the scepter after doing some RP

**Steps to reproduce the problem:**

Attempt to do the quest inside Maraudon will show up every single time.

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

Sunstrider rev. 10796 (9a4b0404442d) 2019-03-28 21:29:22 +0100 (master branch) 
(Unix, RelwithDebInfo, Static)

**Comment by Tamosheik** [comment]
Quest ID#7046

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
