### ISSUE TITLE
Quest "Weapons of Spirit" available without completing pre-requisite quests

### ISSUE THREAD

**Issue by Killabean** [SunstriderEmu/BugTracker#925]
**Description:**

Quest "Weapons of Spirit" available without completing pre-requisite quests

**Current behaviour:**

Camp Mojache, Feralas NPC Witch Doctor Uzer'i (npc=8115) offers quest "Weapons of Spirit" (quest=3129) to any without requiring completion of the _Muisek_ quest chain.

**Expected behaviour:**

The quest should not be offered until the pre-requisite quests are complete.

**Steps to reproduce the problem:**

1. Be a level 40+ Horde that has not completed "Weapons of Spirit".
2. Click on Witch Doctor Uzer'i 
3. Accept "Weapons of Spirit"
4. Observe yellow **?** appear over NPC head (without the expected NPC activity)
5. Click on Witch Doctor Uzer'i 
6. Select a reward
7. Complete quest

**rev. hash/commit:** 

Sunstrider rev. 10796 2019-03-28 21:29:22+0100 (master branch) (Unix, RelWithDebInfo, Static) 
_may have been previous release_

**Comment by kelno** [comment]
FIXED
