### ISSUE TITLE
[Profession] Leatherworking Satchel appears learnable, but is not

### ISSUE THREAD

**Issue by LoshyFirestorm** [SunstriderEmu/BugTracker#934]
**Description:**

Trying to learn the recipe Leatherworking Satchel from the leatherworking trainer in Shattrath City will spend your gold to learn it, but will not actually learn the recipe.

**Current behaviour:**

Trying to learn the recipe Leatherworking Satchel spends your gold and does nothing.

**Expected behaviour:**

Spend your gold to learn the recipe, and learn it.

**Steps to reproduce the problem:**

Step 1: Have 300 leatherworking
Step 2: Attempt to learn Leatherworking Satchel
Step 3: Realise it just takes your gold like a scam

**rev. hash/commit:** 

![ServerInfo300319](https://user-images.githubusercontent.com/43313533/55274335-025b2800-5323-11e9-9d6b-2c1582b25cc0.png)

**Comment by Jerrythemagicdog** [comment]
Tested, works correctly now
