### ISSUE TITLE
Ramparts: Beastmaster's summoned adds pull other npcs when they spawn

### ISSUE THREAD

**Issue by mrqiksta** [SunstriderEmu/BugTracker#937]
**Description:**
Hellfire Ramparts Dungeon (seen in normal, possibly occurring in Heroic)
Bonechewer Beastmaster spawning wolf adds a long way from him, aggroing many NPCs onto the player group as the adds run to the player group.

**Current behaviour:**
The NPC
http://db.hellfire-tbc.com/?npc=17455
Will spawn multiple (2+?) wolf adds after a set time from being aggro'd, which spawn behind a pack of enemies further into the dungron. They then run to the player group as expected, but are incorrectly causing the packs on the way to socially aggro with them.

**Expected behaviour:**

The spawned adds should be appearing near the NPCs but should not be aggroing them onto the player group. 

Note: The adds will not spawn if the NPC is killed quickly enough.

**Steps to reproduce the problem:**

1. Clear to the first beastmaster NPC who is patrolling separate to the packs of humanoid enemies. He is located before the first boss of the dungeon.
2. Aggro the beastmaster, and wait until he emotes the second time. This is when he spawns the wolves.
3. Observe the location the wolves spawn, some way closer to the first boss of the dungeon. They then running towards the player group. This is incorrectly draggin a lot of social-aggro'd humanoid adds with them.

**rev. hash/commit:** 

Current is
Sunstrider rev. 10807 (5214c38d2654+) 2019-03-30 14:39:31 +0100 (master branch) (Unix, RelWithDebInfo, Static) 

but this issue was observed 1 or 2 revisions before this report.

**Comment by SUN-Leekie** [comment]
Hello, the spawning away from the beastmaster is intended as you can see in this video: https://youtu.be/bFSnpICbSu4?t=40
The aggroing along the way is not.

**Comment by mrqiksta** [comment]
I stand corrected :) 
Is it appropriate to alter the title of this ticket in that case @Devs?

**Comment by SUN-Leekie** [comment]
Yes since the title is now unrelated to the real issue.

**Comment by Jerrythemagicdog** [comment]
Changed the positions a bit, the wolves now spawn in the back, from the direction where players enter.
This will make them not aggro the other creatures on their way.

To dev: the summon action with attack victim is what made them pull other creatures, this seems like a better solution than scripting wolves individually to achieve the same effect.

**Comment by kelno** [comment]
But the position is not blizzlike now :'((((
