### ISSUE TITLE
[Quest] Scryer Chain: Shutting Down Manaforge B'naar

### ISSUE THREAD

**Issue by Azytheoneandonly** [SunstriderEmu/BugTracker#945]
**Description:**

Quest Shutting Down Manaforge B'naar is broken.

**Current behaviour:**

Do not get credit for shutting down Manaforge B'naar when you interact with the console.

**Expected behaviour:**

Quest complete when you interact with the console dialog.

**Steps to reproduce the problem:**

1. Pick up quest. & kill the npc for the Access crystal.
2. Attempt to shut down the Manaforge.

Quest: http://db.hellfire-tbc.com/?quest=10329
Seems to be this you interact with to get credit. http://db.hellfire-tbc.com/?npc=20209

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/37324574/55285306-7d2c4d80-53cc-11e9-9f70-360be3d9ba19.png)

**Comment by zemfi** [comment]
dupe: #522

**Comment by SUN-Leekie** [comment]
Fixed in bb929603718d2565fcd7d952b5d88598d1313da9
