### ISSUE TITLE
[Quest] Scryer Chain: Behind Enemy Lines

### ISSUE THREAD

**Issue by Azytheoneandonly** [SunstriderEmu/BugTracker#946]
**Description:**

Quest:  Behind Enemy Lines is broken.

**Current behaviour:**

Quest states that you should talk to the npc go get flown to a certain location.
This option doesn't exist.
![image](https://user-images.githubusercontent.com/37324574/55285351-75b97400-53cd-11e9-9d58-c25e0d583d4a.png)

**Expected behaviour:**

NPC: Veronia should have dialog to fly to the location.

Should fly from NPC: http://db.hellfire-tbc.com/?npc=20162
to NPC: http://db.hellfire-tbc.com/?npc=19840

Landing location:
![image](https://user-images.githubusercontent.com/37324574/55285440-b6b28800-53cf-11e9-9cce-0d16aca27919.png)

**Steps to reproduce the problem:**

1. Pick up quest. 
2. Be unable to fly to location and have to travel by mount.

Quest: http://db.hellfire-tbc.com/?quest=10652
NPC: http://db.hellfire-tbc.com/?npc=20162

**rev. hash/commit:** 
![Screen Shot 03-31-19 at 03 48 PM](https://user-images.githubusercontent.com/37324574/55285413-fd53b280-53ce-11e9-926a-74c5765b199a.JPG)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
