### ISSUE TITLE
Quest: An Improper Burial

### ISSUE THREAD

**Issue by cursedbitcoin** [SunstriderEmu/BugTracker#957]
Description:

The slain Auchenai warrior corpses cannot be burned.

Current behaviour:

When you target the slain Auchenai warrior and use the Sha'tari torch it tells you you have no target.

Expected behaviour:

When you use the torch on the slain warriors they should burn.

Steps to reproduce the problem:

Attempt to burn the slain Auchenai warriors with the Sha'tari torch.

**Comment by Tamosheik** [comment]
Please provide quest/item/object ids. Check the pinned messages in #game-issues, or ask for help if you are unsure.
An Improper Burial - Quest ID# 10913
Sha'tari Torch - Item ID# 31769
Slain Sha'tar Vindicator - NPC ID# 21859
Slain Auchenai Warrior - NPC ID# 21846

**Comment by giveusmezpls** [comment]
still bugged the Slain Sha'tar Vindicator - NPC ID# 21859 does not give credit when the item is used Sha'tari Torch - Item ID# 31769

**Comment by Jerrythemagicdog** [comment]
Fixed
