### ISSUE TITLE
[Quest] Gorgrom the Dragon-Eater

### ISSUE THREAD

**Issue by Paralol** [SunstriderEmu/BugTracker#959]
**Description:**

Totems for the quest do not drop

**Current behaviour:**

The totems required to complete the quest don't drop from the Blouder'mok ogres. 

**Expected behaviour:**

Totems drop and can be used around the corpse of Gorgrom

**Steps to reproduce the problem:**

1. Click the altar, summons Gorgrom who then dies.
2. Kill millions of ogres and not get any totem drops.

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/4516769/55298135-3fcccc00-546f-11e9-98ef-aa9156c887fa.png)

**Comment by Jerrythemagicdog** [comment]
Fixed
