### ISSUE TITLE
Neltharaku's Tale - Cannot finish talking with him to complete the quest

### ISSUE THREAD

**Issue by Kaziner** [SunstriderEmu/BugTracker#962]
REV 10820

**Description:**

**Current behaviour:**

When talking to the dragon for this quest you need to click through a chat window; at the end the last option doesnt do anything and it bugs out

**Expected behaviour:**

It should instead complete the quest and allow you to continue

**Steps to reproduce the problem:**

CHANGEME
1. Talk to the dragon while on this quest

http://db.hellfire-tbc.com/?quest=10814

**Comment by plutonium447** [comment]
![55457119-49e7f980-562c-11e9-94ef-a25c85253be5](https://user-images.githubusercontent.com/40911527/55486591-e8e21500-566f-11e9-8e4d-ea8682e3fbfc.png)
ripped from other report

**Comment by HueHueTBCTheBarrens** [comment]
https://www.youtube.com/watch?v=3AXDHGVFieU&feature=youtu.be
Video of the described issue

**Comment by kelno** [comment]
Confirmed broken

**Comment by kelno** [comment]
Fixed
