### ISSUE TITLE
[Quest] Veil Lithic: Preemptive Strike - Incorrect Spawns?

### ISSUE THREAD

**Issue by Tamosheik** [SunstriderEmu/BugTracker#969]
**Description:**
The Quest Veil Lithic: Preemptive Strike (ID#10861) cannot be completed as credit is not given for the Redeemed Hatchling (NPC ID#22339)

**Current behaviour:**
When looting the Cursed Egg (GameObject ID#185211), the Malevolent Hatchlings (NPC ID#22337) are spawned, and additionally a large number of Redeemed Hatchlings are spawned but no quest credit is given.

**Expected behaviour:**
The cursed egg should have a 50/50 chance to spawn either a malevolent or Redeemed hatchling. Credit should be given automatically if it is redeemed, and on kill if it  malevolent.

**Steps to reproduce the problem:**
1. Have the quest Veil Lithic: Preemptive Strike
2. Loot a Cursed Egg

**rev. hash/commit:** 
Rev. 10820

**Comment by Tamosheik** [comment]
![image](https://user-images.githubusercontent.com/40758487/55326932-4a697e80-54cc-11e9-9472-807f437a5f3c.png)

**Comment by Tamosheik** [comment]
After looting some more eggs, quest credit was given for a redeemed hatchling, however, as with the malevolent hatchling, a large number of redeemed hatchlings **also** spawned, for which no credit was given.

**Comment by mrqiksta** [comment]
I seem to remember that on live, the redeemed hatchlings would spawn then fly upwards and despawn, after which you'd get credit. These seem to just be hanging around & not giving credit.

Spawned by spell 38854

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed in "b0dfd163a503317b6b14b6e22914ef048a87f928"
