### ISSUE TITLE
Stormstrike debuff being consumed by purge

### ISSUE THREAD

**Issue by qoth** [SunstriderEmu/BugTracker#974]
**Description:**

A charge of the Stormstrike [17364] debuff is currently being consumed by purge and possibly other nature spells with no damage.

**Current behaviour:**

Casting purge whilst the debuff from Stormstrike[17364] is on the enemy will result in a charge being consumed.

**Expected behaviour:**

Purge should not be consuming a charge of Stormstrike[17364]

**Steps to reproduce the problem:**

CHANGEME
1. Find a mob that has a buff or casts a buff
2. Cast stormstrike
3. Purge buff off, see that it consumes a charge.

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/35262513/55367340-2477c480-5534-11e9-810a-79ba9cf1bbd2.png)

**Comment by Cheelout** [comment]
Also being consumed by Earthbind Totem pulses.

**Comment by kelno** [comment]
Hopefully fixed with 11559

**Comment by Jerrythemagicdog** [comment]
fixed
