### ISSUE TITLE
battle of the crimson watch quest not working

### ISSUE THREAD

**Issue by HueHueTBCTheBarrens** [SunstriderEmu/BugTracker#975]
**Description:**

Mobs not spawning 
**Current behaviour:**

CHANGEME Tell us what happens.
Nothing
**Expected behaviour:**
 When you accept the quest, mobs are meant to spawn and swamp you 

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**
Accept quest 

1. Step 1 https://tbc-twinhead.twinstar.cz/?quest=10781
2. Step 2 Accept quest
3. Step 3 ???

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
sunstrider rev 10826 (87ef5fb676f5+) 2019-04-01 07:11:49 +200 (master branch) (Unix, RelWithDebInfo, Static)

https://www.youtube.com/watch?v=yqu_fisWWoE&t=3s

**Comment by Jerrythemagicdog** [comment]
Thanks for the video!

**Comment by giveusmezpls** [comment]
It appears the script for this event does not start.

**Comment by z5n** [comment]
issue has since been fixed
