### ISSUE TITLE
[Quest] Fire At Will! 

### ISSUE THREAD

**Issue by Hoochsex** [SunstriderEmu/BugTracker#977]
Description:

Current behaviour:

The Fel cannon at the north Warp Gate is uncontrollable and cannot destroy the gate (pet bar is Grey), The Fel cannon at the south Warp Gate does  work as intended however.

Expected behaviour:

The Fel cannon should be able to be controlled via pet commands to destroy the Warp Gate

Steps to reproduce the problem: 

Take control of the north Fel Cannon 

rev. hash/commit:
https://cdn.discordapp.com/attachments/121222122864508928/562488404105887774/unknown.png

**Comment by DotDotGoose** [comment]
![fireatwill](https://user-images.githubusercontent.com/46829458/55658460-7d539f80-5849-11e9-805c-1a3c5c1b98e4.jpg)

http://db.hellfire-tbc.com/?quest=10911

Contains a BiS pre-raid caster necklace

**Comment by Mediowow** [comment]
Also experienced this issue 31 May 19
