### ISSUE TITLE
warrior rage gen issue, after release issue auto attacks

### ISSUE THREAD

**Issue by oj449** [SunstriderEmu/BugTracker#980]
**Description:**
warrior failed auto attacks should be giving rage (misses,parries,dodges, couldn't find videos on blocks)

**Current behaviour:**
warrior auto attacks that fail, do not give any rage

**Expected behaviour:**
warrior auto attacks that fail should be giving rage
videos:
https://youtu.be/3z2nV3pRDS0?t=197   - 3:20-3:23, dodge
https://youtu.be/fPQRqe_ycHo?t=91 - 1:29-1:31 parry , he only takes less than 500 damage which is also less than 5 rage gained
https://youtu.be/fPQRqe_ycHo?t=179 - 2:59-3:01 , takes no damage, turns around and parry hits and gains rage
https://youtu.be/fPQRqe_ycHo?t=312 - 5:12-5:16 , dodge
https://youtu.be/dGWAB3mxA_A?t=190 - dodge
https://youtu.be/PitLxapXtD4?t=40 - miss DISCARDED- private server
the damage gained from taking damage is much less than what they are getting after, so it shouldn't be rage gained from damage, formula =
Rage Gained = (Damage Taken) / (Rage Conversion at Your Level) * 2.5, lvl conversion is 275 value, so 500 damage taken is about 4.6 rage gained

**Steps to reproduce the problem:**
auto attack stuff as a warrior till you get a failed attack,(dodge,miss,parry) and watch your rage gen

**Comment by oj449** [comment]
further findings show that the warbringer battlegear set for warriors, tier 4, has a set effect: "You gain an additional 2 rage each time one of your attacks is parried or dodged", indicating further with the wording, additional, that there would have to be a base rage gain from those actions occurring.

**Comment by oj449** [comment]
https://wow.gamepedia.com/Patch_1.3.0
"Fixed a bug where rage was not being generated when normal melee attacks were parried, dodged, and blocked."

**Comment by oj449** [comment]
https://vanilla-wow.fandom.com/wiki/Parry
https://worldofwarcraft.fandom.com/et/wiki/Parry
https://wowwiki.fandom.com/wiki/Parry
https://wow.gamepedia.com/Parry
"When a warrior's special attack is parried, he does not lose the rage cost associated with that spell (even though the spell fails). Miss, dodge, or block events will consume the full rage cost when the spell fails."

**Comment by oj449** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3957
this issue goes over the above, seems to be a problem with other tbc servers where rage sustain after a failed ability and potentially energy is just not there

**Comment by oj449** [comment]
it could be that auto attacks generate 80% of a normal swings rage, similiar to how abilities retain 80% rage, but i am struggling to find data for the rage gained from an auto attack missing and etc

**Comment by oj449** [comment]
https://www.youtube.com/watch?v=9Dj2KCL6tSc - 3:00-3:05 - warrior misses an attack and uses battle shout, gains 3 rage overall so he gained 13 rage when he missed, easier to see than the above video posted for misses.

**Comment by kelno** [comment]
Fixed with 11382

**Comment by oj449** [comment]
whirlwind doesn't retain 80% rage when it fails to hit it seems, and that is intentional.
https://youtu.be/9Dj2KCL6tSc?t=206
ww is parried and doesn't reduce the cost to 20%, so don't give the retain special attack rage to whirlwind

**Comment by oj449** [comment]
on that note cleave should most likely only retain rage when the targeted mob avoids it, and not the cleaved mob

**Comment by Jerrythemagicdog** [comment]
fixed
