### ISSUE TITLE
you, robot negatron no leash range

### ISSUE THREAD

**Issue by oj449** [SunstriderEmu/BugTracker#983]
**Description:**
the quest you, robot in netherstorm near area 52 spawns a robot called negatron that doesn't ever stop and start evading back, it will follow you forever, and after you die it doesn't despawn, it seems to just be on a timed despawn after a bit of no combat.

**Expected behaviour:**
robot stops and evades back/despawns when you die and should not follow you forever

**Steps to reproduce the problem:**
start quest
run away
notice it never evades away, can stop combat at a distance but it won't run back it will just relocate its combat area to that spot

**Comment by totaemoeggerli** [comment]
It's also possible to spawn multiple [Negatron](https://www.wowhead.com/npc=19851/negatron) and have them camp FP/town. They do despawn eventually.
![](https://imgur.com/EVAuWCe.png)

**Comment by h0rz** [comment]
Addition: Pet is not controllable, all buttons on pet bar are grey.

**Comment by atmichalak** [comment]
> 
> 
> Addition: Pet is not controllable, all buttons on pet bar are grey.

Confirmed on this addition.

**Comment by Jerrythemagicdog** [comment]
Thanks, both issues fixed since then.
