### ISSUE TITLE
[Alchemy] Elixir of Draenic Wisdom

### ISSUE THREAD

**Issue by Deatherapy** [SunstriderEmu/BugTracker#987]
**Current behaviour:**

None of the master alchemists are able to teach Elixir of Draenic Wisdom

**Expected behaviour:**

It is one of the main recipes that can be taught via trainer

http://db.hellfire-tbc.com/?spell=39638 Recipe
http://db.hellfire-tbc.com/?npc=19052#starts Lorokeem
http://db.hellfire-tbc.com/?npc=18802 Alchemist  Gribble
http://db.hellfire-tbc.com/?npc=16588 Apothercary Antonivich

**Steps to reproduce the problem:**

Be 300 Alchemist and speak to one of the outland master alchemists

**rev. hash/commit:** 

rev 10843

**Comment by Jerrythemagicdog** [comment]
The requirement for those seems to be 320 
https://www.wowhead.com/spell=39638/elixir-of-draenic-wisdom (difficulty).
That's the same for us currently.

**Comment by Jerrythemagicdog** [comment]
The mentioned trainers have those spells, the required skill is set to 320, which according to sources is correct.
