### ISSUE TITLE
Implement CREATURE_FLAG_SUMMON_GUARD

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#99]
Data is extracted from client:
https://gist.github.com/Kinzcool/e81137dab3bc828631ada717f7da5159
+
https://github.com/TrinityCore/TrinityCore/blob/f94deace764f0b8d99249760d2bc2e85c891c387/src/server/game/Entities/Creature/CreatureData.h#L32

Comment on last link: "Creature will summon a guard if player is within its aggro range (even if creature doesn't attack per se). DB data for this is from MoP client."

The flags have been added as extra flag CREATURE_FLAG_SUMMON_GUARD in our DB but still needs implementation. I never played on retail so I have no idea what this is supposed to do. Needs research.

**Comment by ratkosrb** [comment]
Related TC issue -> https://github.com/TrinityCore/TrinityCore/issues/11563

The guards are supposed to be summoned by server-side spells (they are in the 1.12 Spell.dbc since no spells are hidden there). 

Example: http://classicdb.ch/?spell=11475

These spells target the nearest guard post, which is a gameobject of type 21 GAMEOBJECT_TYPE_GUARDPOST. I believe they are spawned around towns, but cannot be seen by players. These gameobjects have charges, and the summon guard spell cast should fail if the guard post is out of charges.

Quote from the 0.8 Beta Patch Notes:
http://wowwiki.wikia.com/wiki/Patch_0.8
>  New Guard System
>
> A new guard system has been added. This new system will enable NPCs to call for guards when they see an enemy as well as when they are attacked. The guards will chase players and then return to the NPC that called for help once they lose track of, or kill the player. If a guard is killed, another guard will be called to take its place. There is a limit to how many guards each town can have which will recharge over time. The cities that currently have the new Guard System in place are: Astranaar, Auberdine, Bloodhoof Village, Brill, Crossroads, Goldshire, Razor Hill, Sen'jin Village, Sentinel Hill, Sepulcher and Thelsamar. The Guard System will be implemented in other cities in future patches.

**Comment by kelno** [comment]
Thanks a lot!

**Comment by kelno** [comment]
Any idea where to find the correct gameobject_template?
I don't have anything with type = 21 on any db I have.

**Comment by ratkosrb** [comment]
They are in the TC 3.3.5 database, but I think the data there is not actually from 3.3.5, but a later expansion, since it references guards added in Cataclysm. (Data0 field)

**Comment by kelno** [comment]
Ah yes, on master then. Did check on 3.3.5.

**Comment by ratkosrb** [comment]
I have done an implementation of this, but without using the guard post gameobjects and the summoning spells. https://github.com/vmangos/core/commit/5d7467f79b58eaa46c17f4a9fb2a395d3d3ec00a

**Comment by kelno** [comment]
https://github.com/ValorenWoW/sunstrider-issues/issues/99

**Comment by kelno** [comment]
Done since!

**Comment by ratkosrb** [comment]
Did you write a GuardMgr like me, or did you do it the blizzlike way with the spells and guard post gameobjects :P

**Comment by kelno** [comment]
I used gameobjects, we got little guard post crystals in the middle of cities now. I didn't do the proper texts though, creatures just yell "Guards!"

**Comment by ratkosrb** [comment]
Good job!
