### ISSUE TITLE
[Quest] Messenger to the Feralfen

### ISSUE THREAD

**Issue by DONALDBURKE** [SunstriderEmu/BugTracker#994]
**Description:**
Cannot complete the quest Messenger to the Feralfen
http://db.hellfire-tbc.com/?quest=9803

**Current behaviour:**
It allows you to drink Ahuurn's Elixir and it turns you into an arrakoa. Elder Kuruti becomes friendly and you can now interact with him but going through his dialogue doesn't do anything.

**Expected behaviour:**
You should be able to interact with him and get his answer, completing the quest.

**Steps to reproduce the problem:**
1. Go to the Boha'mu Ruins in south Zangarmarsh.
2. Drink Ahuurn's Elixir.
3. Interact with Elder Kuruti.

**rev. hash/commit:** 
10843

**Comment by zemfi** [comment]
Tried it a few days ago and was still broken, but tried it again now (.rev 10913) and seems to be working.

![feralfen](https://user-images.githubusercontent.com/46832429/55799701-5af5a680-5b15-11e9-843b-4f9bb61004da.jpg)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.

To dev: there was a "no repeat" flag set and the quest giver never reset - it was only completable by 1 player each server restart.
